### ISSUE TITLE
Visual Database Design with MySQL Workbench

### ISSUE THREAD

**Issue by Tsanguu** [section-engineering-education/engineering-education#1010]
### Brief Summary: 
MySQL Workbench is a visual database design tool that integrates SQL development, administration, database design, creation, and maintenance into a single integrated development environment for the MySQL database system. This article will discuss Workbench from installation and configuration to creating a working database visually.

### Key Takeaways: 
Introduction to MySQL WOrkbench
Setting up MySQL WOrkbench
Database Design with MySQL Workbench
Reverse Engineering with MySQL Workbench
Forward Engineering with MySQL Workbench

### References: 
https://www.mysql.com/products/workbench/

**Comment by ninjaginja** [comment]
good topic @Tsanguu - approved
