### ISSUE TITLE
NPM vs Yarn Which one to choose

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#1012]
### Brief Summary: 

Both NPM and Yarn are package managers. They automate the process of installing, upgrading, configuring, or removing  Node.js packages. The two most popular package managers are Yarn and NPM. This guide will discuss the following key takeaways about these two packages.

### Key Takeaways: 

What are NPM and Yarn
How to use NPM  and  Yarn 
The differences between Yarn and NPM in terms of application, speed, security, and trends comparison.
Migrating from one package manager to another

### References:

https://docs.NPMjs.com/
https://classic.yarnpkg.com/en/docs/

**Comment by ninjaginja** [comment]
Thanks for all the topic suggestions @kimkimani. I see that you have several open issues that still have PRs yet to be created. Could you please work through drafts for existing issues before suggesting new topics? This helps us expedite reviews/payouts for everyone. I'm going to close this issue until you've working through the backlog, and you can request to reopen this one as soon as you're ready to begin working on it. Thank you.

**Comment by kimkimani** [comment]
@ninjaginja Can I draft this?

**Comment by kimkimani** [comment]
There is a discussion going on around the community about a new yarn release that has added [new features](https://yarnpkg.com/features). I will revisit this topic once I get more grounds to cover on the basis of the new yarn updates such as [Plug'n'Play](https://yarnpkg.com/features/pnp)
