### ISSUE TITLE
Using React suspense for data fetching

### ISSUE THREAD

**Issue by Larry-Mason** [section-engineering-education/engineering-education#1027]
### Brief Summary:
React is a JavaScript library for creating interactive user interfaces.In this we shall try to discuss about the suspense API and use it to fetch data.

### Key Takeaways: 
1. Learn about React suspense
2. Interact with a third-party API to fetch data
3. Learn how to use React components

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @Larry-Mason - approved
