### ISSUE TITLE
OSI Layer

### ISSUE THREAD

**Issue by Aju100** [section-engineering-education/engineering-education#1055]
### Brief Summary: 
The Open Systems Interconnection model is a conceptual model that characterizes and standardizes the communication functions of a telecommunication or computing system without regard to its underlying internal structure and technology. 

### Key Takeaways: 
By the end of the article about OSI Layer. 
- Layers of OSI
    - Physical Layer
    - Data Link Layer
    - Network Layer
    - Transport Layer
    - Session Layer
    - Presentation Layer
    - Application Layer
    

### References: 
N/A

**Comment by ninjaginja** [comment]
great topic @Aju100 - approved.
