### ISSUE TITLE
HOW TO CREATE COUNTDOWN TIMER USING JS,PHP AND MYSQL DATABASE

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#1057]
### Brief Summary:
The learner will be able to write jquery in a laravel project to achieve a a timer countdown

### Key Takeaways: 
1.using Javascript in a laravel project.
2.Creating Timer on a Laravel website.
3.Manipulating the DOM.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @jumamiller. Are you able to either expand on the description that you've provided, or provide a short (1-2 paragraph) writing sample that allows us to better assess readability/grammar upfront? We don't provide editing services and try our best to avoid having to reject submitted drafts that don't meet our writing standards.

**Comment by jumamiller** [comment]
@ninjaginja, I think this title is now self-explanatory.
