### ISSUE TITLE
How to use Java JDBC API

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#1061]
### Brief Summary: 
JDBC stands for Java Database Connectivity. JDBC is a Java API to connect and execute the query with the database. It is a part of JavaSE (Java Standard Edition). JDBC API uses JDBC drivers to connect with the database. In this article I will explain how to use JDBC to connect to a MYSQL database and perform CRUD operations using Java.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. What is JDBC.
2. Connecting to MYSQL database using JDBC.
3. Performing CRUD operation using JDBC.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
great topic @jumapaul - approved
