### ISSUE TITLE
Building your first simple Application using Angular.

### ISSUE THREAD

**Issue by MahanteshR** [section-engineering-education/engineering-education#1062]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Having discussed data-binding in the first article. In this tutorial, we will build a simple Angular SPA that covers most of the core topics. The application would be similar to a streaming site, but here we will stick to anime only. This guide basically serves as hands-on training for developers willing to explore Angular.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Understanding how an application is structured.
2. How template and component class communicate.
3. In-app navigation and services.
4. Finally, a basic idea on how to build a SPA from scratch.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://angular.io/docs - References used

**Comment by ninjaginja** [comment]
good topic @MahanteshR  - approved. Just an alternate suggestion on the title - 'How to Build a Simple Angular SPA from Scratch'
