### ISSUE TITLE
Top Node.js Monitoring Tools 

### ISSUE THREAD

**Issue by EKahuha** [section-engineering-education/engineering-education#1065]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Over the years, Node.js has become a popularly used JavaScript framework for rapid micro-service and API development. With workloads running on Node.js, it becomes crucial to have the right monitoring system for essentials metrics.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1.	What is Node.js Monitoring?
2.	What you should monitor
3.	Node.js Monitoring Tools
•	Appmetrics
•	Retrace
•	PM2
•	Prometheus
•	Clinic.js
•	AppSignal
•	Express Status Monitor

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved

**Comment by ninjaginja** [comment]
(sorry, mistakenly clicked the wrong button - didn't intend to close the issue)
