### ISSUE TITLE
Building an Image Classifier with Keras

### ISSUE THREAD

**Issue by Inyrkz** [section-engineering-education/engineering-education#1072]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

In this article, you will learn how to build and train a Convolutional Neural Network to perform Image Classification using Keras at the back of TensorFlow.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

After reading this article, you will be able to:
1. perform Data Visualization of training images,
2. perform Data Preprocessing and Image Augmentation,
3. build and train a Convolutional Neural Network with Keras,
4. evaluate the Performance of the trained model,
5. use the trained model to make predictions on new image data.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

- Keras Documentation https://keras.io/api/
- Matplotlib Documentation https://matplotlib.org/3.3.3/contents.html
- Coursera Guided Project https://www.coursera.org/projects/classification-of-covid19-using-chest-xray-images-in-keras

**Comment by ninjaginja** [comment]
cool topic @Inyrkz - approved 👍
