### ISSUE TITLE
Token vs Cookie based authentication

### ISSUE THREAD

**Issue by ReactifyStudio** [section-engineering-education/engineering-education#1078]
### Brief Summary: 
Authentication refers to the process or action of verifying the identity of a user or process. In this article I will be comparing between the two mostly used ways of authentication in web.

### Key Takeaways: 
1. Understanding what is session authentication
2. Understanding what is token authentication
3. Advantages and disadvantages of session authentication
4. Advantages and disadvantages of token based authentication
5. When to choose depending on the project

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @ReactifyStudio - approved

**Comment by ReactifyStudio** [comment]
@ninjaginja , the Cookie and Session too related, I might need to edit the title in the final stages
