### ISSUE TITLE
Data Mining using CRISP-DM methodology

### ISSUE THREAD

**Issue by srishilesh** [section-engineering-education/engineering-education#1081]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Cross-industry standard process for data mining, known as CRISP-DM, is an open standard process model that describes common approaches used by data mining experts. It is the most widely-used analytics model.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- The reader will understand various steps used in this methodology
- The reader will also understand this methodology, by analyzing a case study
- The reader will be able to plan out strategies for making their data science project successful.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
- https://en.wikipedia.org/wiki/Cross-industry_standard_process_for_data_mining
- https://paginas.fe.up.pt/~ec/files_0405/slides/02%20CRISP.pdf

**Comment by ninjaginja** [comment]
good topic @srishilesh - approved
