### ISSUE TITLE
Applications of artificial intelligence (AI) in design technologies 

### ISSUE THREAD

**Issue by Pius1991** [section-engineering-education/engineering-education#1084]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Artificial intelligence has enormously changed the engineering field. We are not in the age where engineering design was carried on using paper and a pencil.  
This article will outline some of the basic techniques engineers use today in design and how they are related to technology. 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1.	How has the design process changed due to technology evolution?
2.	Various applications of AI in the design process, with real examples.
3.	The future of AI in design.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
@Pius1991 could you please elaborate on the context of the term 'design' within the topic that you intend to explore? Design in engineering can mean a lot of different things.

**Comment by Pius1991** [comment]
@ninjaginja I meant Applications of AI in design systems, my apologies. A design system being a collection of re-usable components, that can be assembled together to build applications guided by a clear standards.

**Comment by ninjaginja** [comment]
Great, thanks for the clarification and refinement of the title - approved
