### ISSUE TITLE
TCP/IP Protocols:TCP and UDP

### ISSUE THREAD

**Issue by raboba2re** [section-engineering-education/engineering-education#1085]
### Brief Summary: 
This article talks about how the transport layer uses the Transmission Control Protocol (TCP) and User Datagram Protocol (UDP) to established a temporary communication session to deliver data between two applications.

### Key Takeaways: 
At the end of this article, the reader should know the following:
-The TCP/IP layer 4 (Transport Layer) 
-The Transport control protocol (TCP) and it benefits.
- The User Datagram Protocol (UDP) and it benefits.

### References: 
https://searchnetworking.techtarget.com/definition/TCP
https://www.cisco.com/c/en/us/support/docs/ip/routing-information-protocol-rip/13769-5.html
https://www.certificationkits.com/cisco-tcpip/

**Comment by ninjaginja** [comment]
good topic @raboba2re - approved. Just one minor suggestion... I'd recommend refining the title to more accurately describe what the reader can expect to gain (e.g. 'Understanding...', 'How to Implement...').

**Comment by raboba2re** [comment]
Noted Ma, your suggestion will be taken into consideration. Thank you.
