### ISSUE TITLE
Understanding Static and Dynamic routing.

### ISSUE THREAD

**Issue by raboba2re** [section-engineering-education/engineering-education#1091]
### Brief Summary: 
Every router can learn about remote  network routes in one of two ways:
- Manually or
- Dynamically.
 For Manual networks, the routes are configured by the network administrator, while for dynamic routes, the routes are entered by a dynamic routing protocol

### Key Takeaways: 
By the end of this article, the reader should have the basic knowledge of:
-Static routing
- Types of Static routes
- Dynamic routing
- Types of dynamic routing protocols.
- when to Implement Static routing or Dynamic routing .

### References: 

https://en.wikipedia.org/wiki/Static_routing
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus3000/sw/unicast/503_u1_2/nexus3000_unicast_config_gd_503_u1_2/l3_route.htm

**Comment by ninjaginja** [comment]
good topic @raboba2re - approved.

**Comment by raboba2re** [comment]
@ninjaginja  Thank you for the correction.
