### ISSUE TITLE
How to Implement Network Address Translation (NAT) on a Cisco router.

### ISSUE THREAD

**Issue by raboba2re** [section-engineering-education/engineering-education#1099]
### Brief Summary: 
At the inception of the internet, Internet Protocol Version 4 (IPV4) provided up to 4 billion addresses, which at that time was a very large amount of addresses. But at as the internet began to grow in the 1990s with the introduction of Bring Your Own Device (BYOD) and Internet of Things (IOT) a major limitation of IPv4,  which is Limited number of addresses to accommodate all devices was discovered.
  As a short time solution to this problem, Network Address Translation (NAT) was introduced to translate private IPV4 addresses to Public IPV4 addresses.  Without NAT IPV4 addresses would have been exhausted long before the year 2000 and new users would not have been able to connect to the internet.     

### Key Takeaways: 
At the end of this article, the reader should be able to:
-Understand the limitations of IPV4 address Space.
- Understand the basic concept behind NAT.
- Configure NAT on a Cisco router ( 1941 series router) using the command line interface (CLI)
- Understand the Long time solution to IPV4 limitations.

### References: 
 N/A

**Comment by ninjaginja** [comment]
good topic @raboba2re - approved
