### ISSUE TITLE
How to implement dark mode in Android Studio

### ISSUE THREAD

**Issue by WanjaMIKE** [section-engineering-education/engineering-education#1109]
### Brief Summary: 

Dark mode is one of the most exciting features when it comes to designing user interface. It allows users to change the look and feel of their application on a click of a button. It is, therefore, important to learn how to implement this attribute in your android application.

### Key Takeaways: 
-  Understand dark mode entails
-  Learn how to implement dark mode in an android application.
- Debug errors

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @WanjaMIKE - approved
