### ISSUE TITLE
MongoDB vs. MySQL

### ISSUE THREAD

**Issue by Pius1991** [section-engineering-education/engineering-education#1112]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Database stores real-time information and handles a massive volume of queries at a fast rate. The volume of data keeps on increasing in recent years. Both MongoDB and MYSQL have large community users.
The article will be about analyzing key differences and similarities between the two databases. The article will highlight their differences in automation, structure, security, documentation, etcetera. It will also enumerate the pros and cons of using each.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1.	What is MongoDB? What is MYSQL?
2.	Applications of these databases, where are they deployed?
3.	What are the characteristics of both MongoDB and MYSQL?
4.	What are the differences between MongoDB and MYSQL? 
5.	What are the advantages and disadvantages of using MongoDB and MYSQL?

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @Pius1991 - approved. (Please be mindful of grammar/readability checks prior to submitting your draft for review. I noticed some grammatical errors in your description.)

**Comment by hectorkambow** [comment]
closing due to activity
