### ISSUE TITLE
Getting started with Linux container security

### ISSUE THREAD

**Issue by molly80** [section-engineering-education/engineering-education#1118]
### Brief Summary: 
With the rise in popularity of containers so is the need to deploy good and strategic container security measures

### Key Takeaways: 
Overview about containers
Guide on how to deploy container security
Benefits of containerization and container security
### References: 
https://www.nist.gov/publications/application-container-security-guide

**Comment by ninjaginja** [comment]
good topic @molly80 - approved. 

I see that you've suggested a separate topic on Intro to Linux Containers. I think that the overview that you provide in the intro of this article will suffice, as opposed to having a separate article on the topic. We already have an article that covers the history of containers, so I think focusing on security is a good idea. I'm going to close the other issue that you opened.

**Comment by molly80** [comment]
@ninjaginja sure

**Comment by molly80** [comment]
Hello, I would like reopen this issue
