### ISSUE TITLE
How to Carry Out Effective User Acceptance Testing (UAT)

### ISSUE THREAD

**Issue by Tsanguu** [section-engineering-education/engineering-education#1120]
### Brief Summary: 
User Acceptance Testing is the process of conducting a test on whether the product meets the business requirements and usability by the end-user. The end-user or the client does it to verify a software system before moving it to the production environment. This article will discuss UAT in detail.

### Key Takeaways: 
What is User Acceptance Testing
Why you Need User Acceptance Testing
User Acceptance Testing Process
User Acceptance Testing Tips

### References: 
https://www.softwaretestinghelp.com/what-is-user-acceptance-testing-uat/

**Comment by ninjaginja** [comment]
good topic @Tsanguu - approved. Note, I made one minor adjustment to the title.
