### ISSUE TITLE
Implementing Flask WTF Forms

### ISSUE THREAD

**Issue by corpsgeek** [section-engineering-education/engineering-education#1140]
#### Brief Summary:
Form handling are crucial components of web applications. In this article the reader will understand the two ways of handling forms and the best way to approach form handling with flask web framework. 

### Key Takeaways: 
- How to access forms
- How to use the WTForms
- How to handle form errors 
- 
### References: 
WTForms documentation.

**Comment by ninjaginja** [comment]
good topic @corpsgeek - approved

**Comment by corpsgeek** [comment]
Work in progress. 😊
