### ISSUE TITLE
Introduction to static site generator

### ISSUE THREAD

**Issue by Aju100** [section-engineering-education/engineering-education#1143]
### Brief Summary: 
A static site generator is a tool that generates a full static HTML website based on raw data and a set of templates. Essentially, a static site generator automates the task of coding individual HTML pages and gets those pages ready to serve to users ahead of time. Because these HTML pages are pre-built, they can load very quickly in users' browsers.

### Key Takeaways: 
- Importance of static site generator
- Learning about JamStack technologies
- Comprehensive list of static site generator tools
- Building a sample website using a static site generator

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @Aju100 - approved. Please note that Section offers static site edge hosting technology through our Node.js module. I'm not sure if you're looking to go that deep (i.e. deployment) into your tutorial, but if so, please be mindful that we prefer not to feature competitive providers in our content (e.g. Netlify, Heroku, etc.) Feel free to double check if in doubt as you're working through the content. Also, if you're interested in testing out the Section offering to feature in your article, we'd be happy to set you up with an account.

**Comment by Aju100** [comment]
Hi @ninjaginja, I would be happy for testing and deploying the static site in the section through Node.js Module

**Comment by ninjaginja** [comment]
Excellent! When you're ready, you can sign up for a trial account here - https://aperture.section.io/new/onboarding/slipway. Once you sign up, it will direct you through the docs for how to deploy your app. Feel free to reach out with any questions along the way.

**Comment by hectorkambow** [comment]
@Aju100  
👋  

Good morning just wanted to get a status on this article topic - I know the submissions were paused for a while - but we are open for new article submissions again.

**Comment by Aju100** [comment]
HI, @hectorkambow  I will give an update within this week. Thank you.


Regards,
Aju Tamang

**Comment by hectorkambow** [comment]
closing to clear the queue - can be resubmitted whenever ready to continue 🚀
