### ISSUE TITLE
AJAX request in Django (Using Axios)

### ISSUE THREAD

**Issue by atoyegbe** [section-engineering-education/engineering-education#1149]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Django is a python web framework for building web application. we shall handle sending and receiving HTTP requests in the background(AJAX request) using Axios a javascript library.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. What is an Ajax request 
2. Introducing Axios
3.  Using Axios to submit a form 
4. Handling a post request form in Django
### References: 
https://www.npmjs.com/package/axios

**Comment by ninjaginja** [comment]
good topic @atoyegbe - approved. Please be mindful of grammar/readability and be sure to put your content through a thorough round of editing review prior to submitting your final draft. I noticed some grammar and readability errors (e.g. capitalization, punctuation) in your description that raised a flag and want to try to maximize opportunity for your article to get published, which will also help maximize your potential payout.
