### ISSUE TITLE
Is Object-Oriented Overrated?

### ISSUE THREAD

**Issue by nicholaskross** [section-engineering-education/engineering-education#1152]
### Brief Summary: 
Most professional programming languages are object-oriented, including Java and the C languages. However, their key features (such as encapsulation and inheritance) have come under attack many times in recent memory. Object-oriented detractors claim these features are overcomplicated, and make code writing and maintenance more difficult. We will explore these arguments, and their counters, to better understand the cases where object-oriented programming is more or less useful.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- Recognize the unique features of the object-oriented paradigm.
- Understand arguments that these features are counterproductive for professional programming tasks.
- Understand the counterarguments to the above.

### References: 
- https://medium.com/better-programming/object-oriented-programming-the-trillion-dollar-disaster-92a4b666c7c7
- https://thenewstack.io/why-are-so-many-developers-hating-on-object-oriented-programming/
- https://stackoverflow.blog/2020/09/02/if-everyone-hates-it-why-is-oop-still-so-widely-spread/
- https://www.youtube.com/watch?v=QM1iUe6IofM

**Comment by hectorkambow** [comment]
[published](https://www.section.io/engineering-education/is-object-oriented-overrated/)
