### ISSUE TITLE
Understanding Dijkstra's Shortest Path Algorithm in Network routing using Python

### ISSUE THREAD

**Issue by Agusioma** [section-engineering-education/engineering-education#1153]
### Brief Summary: 
We will discuss how Dijkstra's algorithm computes the shortest distances between network nodes and illustrate it using Python.

### Key Takeaways: 
In the end, the reader will learn about:
- Graphs
- Types of graphs
- Use of the graphs by Dijkstra's Algorithm in computing the shortest path
- Writing a script in Python for Implementing the algorithm

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
[FreeCodeCamp](https://www.freecodecamp.org/news/dijkstras-shortest-path-algorithm-visual-introduction/)
[GeeksforGeeks](https://www.geeksforgeeks.org/python-program-for-dijkstras-shortest-path-algorithm-greedy-algo-7/)

**Comment by ninjaginja** [comment]
good topic @Agusioma - approved
