### ISSUE TITLE
Getting Started With Http Client in Laravel

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#1155]
### Brief Summary: 
At the end of this tutorial, the learner will gain substantial skills in making HTTP requests to communicate with other applications
and web services.
The learner will be introduced to the popular Guzzle Http client.

### Key Takeaways: 
Introduction to Guzzle, PHP HTTP client.
Building query strings.
HTTP error handling.
Faking Responses.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @jumamiller - approved. Just one small note, please be consistent with references to HTTP (not Http).
