### ISSUE TITLE
Cynefin Framework and Software Engineering

### ISSUE THREAD

**Issue by gracinev** [section-engineering-education/engineering-education#1157]
### Brief Summary: 
My article will go into depth about what the Cynefin Framework is. It will describe the different domains of the Cynefin Framework, as well as examples of each kind of domain. Furthermore, the article will describe how the Cynefin Framework impacts software engineers.

### Key Takeaways:
When reading this article, readers should have a better understanding of what exactly the Cynefin Framework is, what each domain of the Cynefin framework is, and how the overall framework is used in software engineering. 

### References: 
“Chapter 1. Introduction.” Essential Scrum: a Practical Guide to the Most Popular Agile Process, by Kenneth S. Rubin, Addison-Wesley, 2012.

**Comment by ninjaginja** [comment]
good topic @gracinev - approved. I just have one minor suggestion to make the title more impactful. I'd recommend tying the two together in a more descriptive way, such as "How Software Engineers Use the Cynefin Framework to...", "Application of the Cynefin Framework in Software Engineering", etc.

**Comment by hectorkambow** [comment]
@gracinev 👋 just wanted to check if there was any update on this article topic
