### ISSUE TITLE
Implementing Email Verification In Laravel

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#1158]
### Brief Summary: 
Typically, after registering a user using an email address, you should send a verification email to verify that the user owns the email address they used for the registration of the account.
This is an important feature that is used in almost every site requiring a user authentication.
Instead of a developer repeating this process, again and again, Laravel provides this feature out of the box to save development time.

### Key Takeaways: 
1.Model Preparations.
2.Database Preparation.
3.The email verification notification handler.
4.Resending email verification notification.
5.Verification Email Customization

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @jumamiller - approved.
