### ISSUE TITLE
CI/CD with Vue, Firebase Hosting and Github Actions

### ISSUE THREAD

**Issue by Worawat101** [section-engineering-education/engineering-education#1160]
### Brief Summary:
Automating the development process is an essential step towards reaching the production ready product with zero bugs and errors. Here, by deploying some GitHub actions, we are going to automate the testing of the coding implementation during the pull request. This means Github Actions will automatically run the tests in case the pull request occurs and won’t allow merging to master and deploying to production until test fails. The automation with also handle the Firebase deployment after the pull request is successful.

### Key Takeaways:
- Learn to create a Vue project using Vue/CLI
- Learn Git and GitHub workings
- Learn how to configuring Firebase hosting in Vue project
- Learn to apply GitHub actions for configuring proper workflows

**Comment by ninjaginja** [comment]
good topic @Worawat101 - approved
