### ISSUE TITLE
An Overview of Consensus Protocols in Blockchain

### ISSUE THREAD

**Issue by lalith1403** [section-engineering-education/engineering-education#1166]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Blockchain validates the transactions made through a distributed consensus protocol. In this article, I explain the need for consensus protocols and dive deep into the various types of consensus protocols available.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Introduction to consensus protocols
2. Types of consensus protocols: Proof of work, proof of stake, proof of elapsed time, proof of space, and proof of retrievability
3. Compare the different types of consensus protocols based on their properties, efficiency, and applications.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @lalith1403 - approved
