### ISSUE TITLE
Introduction to built-in datastructures in Java

### ISSUE THREAD

**Issue by srishilesh** [section-engineering-education/engineering-education#1174]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Java collection contains several built-in datastructures like Arraylist, Vector, Linkedlist, Hashset and so on. In this article, the reader will get to know all the built-in data structures used in Java. The reader will also see various examples and uses of each built-in datastructure.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

- The reader will learn about different built-in datastructures in Java
- The reader will learn how to use each of the datastrucutures
- The reader will also learn how inbuilt datastructures improves the time and space complexity

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

- https://www.coursera.org/projects/java-built-in-data-structures
- https://www.geeksforgeeks.org/data-structures/

**Comment by ninjaginja** [comment]
good topic @srishilesh - approved. Just one note, 'data structures' is two words.
