### ISSUE TITLE
How to Create a Dataset for Machine Learning

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#1179]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Most articles today talk about how to create deep learning models, but almost none talks about how to prepare your own dataset and how important is data in machine learning. In this article, we'll discuss how importand data is in Machine Learning and how to prepare your own dataset.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

By the end of this article, a reader should be able to understand:

1. How important data is in machine learning?
2. How to prepare you own dataset, i.e. from data collection, data preprocessing, splitting data into training set, training set etc

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
1. [A Survey on Data Collection for Machine Learning](https://arxiv.org/pdf/1811.03402.pdf)

**Comment by ninjaginja** [comment]
good topic @Bayler - approved
