### ISSUE TITLE
Getting started with Spring Data JPA

### ISSUE THREAD

**Issue by paulodhiambo** [section-engineering-education/engineering-education#1180]
### Brief Summary: 
Spring Data makes it easy to use data access technologies, relational and non-relational databases, map-reduce frameworks, and cloud-based data services. In the article I will explain how to implement various database relationships and models using Spring Data and Spring Data JPA.

### Key Takeaways: 
The reader should have some knowledge of [Spring Boot]() to understand the concepts that I will explain in the article.
1. What is Spring Data.
2. What is Spring Data JPA.
3. How to create database models using Spring Data.
4. How to create various database relationships using Spring Data.
5. How to perform various database queries using Spring Data JPA.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @paulodhiambo - approved. Just one suggestion, I'd recommend refining the title to be more specific to what the reader can expect to takeaway from the content, e.g. "Getting Started with Spring Data JPA", "Working with Databases in Spring Data JPA", etc.
