### ISSUE TITLE
Parametric vs Non-Parametric Machine Learning Models 

### ISSUE THREAD

**Issue by collins-a** [section-engineering-education/engineering-education#1181]
### Brief Summary: 

In machine learning, a learner learns from training data to map a target function. However, the configuration of the function is undetermined. As a result, we test out many machine learning algorithms to determine which models the intrinsic function effectively. To tune the behavior of models for a given task, these models are parameterized. We seek to understand such a process by dissecting parametric and non-parametric models. 

### Key Takeaways: 

The reader shall:
1. Be introduced to parameters and their characteristics
2. Understand parametric models
3. Learn about non-parametric models
4. Understand the contrast between parametric vs non-parametric modeling

### References: 

https://machinelearningmastery.com/parametric-and-nonparametric-machine-learning-algorithms/

https://medium.com/analytics-vidhya/parametric-and-nonparametric-models-in-machine-learning-a9f63999e233

https://machinelearningmastery.in/2020/07/16/parametric-vs-non-parametric-machine-learning/

**Comment by ninjaginja** [comment]
good topic @collins-a  - approved
