### ISSUE TITLE
Landmark Recognition Using Firebase ML in a Non-Expo React Native Application

### ISSUE THREAD

**Issue by zolomohan** [section-engineering-education/engineering-education#1182]
## Brief Summary
In this tutorial, we will develop a React Native application (Non-Expo) to recognize landmarks from images using Firebase's ML modules.

## Key Takeaways

- Set up Firebase Project for Landmark Recognition.
- Add a Picker component to select Images or use the camera to take pictures.
- Use Firebase ML to recognize landmarks.
- List all the recognized landmarks in the application.

**Comment by ninjaginja** [comment]
cool topic @zolomohan - approved
