### ISSUE TITLE
Problem Framing in Machine Learning

### ISSUE THREAD

**Issue by collins-a** [section-engineering-education/engineering-education#1183]
### Brief Summary: 

In a business context, choosing a machine learning method to implement on data is not the easiest of processes. It is important to first understand the precise business problem and its objectives. For instance, understanding what is trying to be predicted and the potential outcomes is key. One also needs to know what data should be used to train a model, among other factors. Such considerations help in the framing of a machine learning problem. In this article, we look at how to correctly frame a machine learning problem. 

### Key Takeaways: 

Reader should:
1. Be aware of the role/position of problem framing in a basic ML workflow
2.  Understand the factors that complicate the problem framing process
3. Learn best practices/steps to frame a machine learning problem

### References: 

https://medium.com/towards-artificial-intelligence/problem-framing-the-most-difficult-stage-of-machine-learning-1a7f208ea414#:~:text=%20Problem%20Framing%3A%20The%20Most%20Difficult%20Stage%20of,Building.%20Pick%20the%20machine%20learning%20tool...%20More%20

https://developers.google.com/machine-learning/problem-framing/

https://medium.com/towards-artificial-intelligence/machine-learning-problem-framing-2a0eba4c0d6d

https://labelbox.com/blog/framing-problem-helps-build-dataset/

**Comment by ninjaginja** [comment]
good topic @collins-a - approved
