### ISSUE TITLE
How to choose between native vs hybrid mobile applications

### ISSUE THREAD

**Issue by ipitah** [section-engineering-education/engineering-education#1188]
Brief Summary:
Describe the what, why, and how of your content idea in 2-5 sentences.
1.	Clients/customers are in dire need of mobile applications for their companies.
2.	Developers evaluate the needs/requirements to establish the most suitable development method.
3.	There are two major choices for mobile application developers; native and hybrid.
4.	The choice for the method is greatly determined by certain factors that include:
●	App Performance,
●	Support/Documentation,
●	Feature Accessibility,
●	User Experience,
●	Cost of Development,
●	App Complexity,
●	Platform Code Support,
●	Delivery Time,
●	Pushing Updates, 
●	Scalability, and 
●	Security.
Key Takeaways:
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1.	Mobile application development falls under two broad categories; native and hybrid.
2.	Developers need to keenly analyze a situation and adopt a suitable method.
3.	The focus is on developing with the user in mind.
4.	Each method has its strengths and shortcomings.
References:
1.	https://clearbridgemobile.com/mobile-app-development-native-vs-web-vs-hybrid/#:~:text=Hybrid%20apps%20work%20across%20multiple,app%20and%20a%20web%20app.&text=These%20types%20of%20apps%20are,that%20incorporates%20additional%20native%20features.
2.	https://ymedialabs.com/hybrid-vs-native-mobile-apps-the-answer-is-clear
3.	https://existek.com/blog/difference-between-native-app-and-hybrid-app/
4.	https://www.mobiloud.com/blog/native-web-or-hybrid-apps
5.	https://greenice.net/native-vs-hybrid-mobile-app-development-choose/
6.	https://siliconithub.com/native-vs-hybrid-app/
7.	https://mindsea.com/security-hybrid-apps-vs-native-apps/
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @ipitah - this is a good topic to write about and you may proceed. For your next topic suggestion, please supply the description in paragraph format. This helps us better evaluate your writing style and provide feedback that prevents errors and streamlines our review processes. Please also be sure to put your content through a thorough grammar/readability review prior to submitting your final draft, as I did notice a few issues in the sentences that you provided. 

One other note - the title that you've suggested is worded awkwardly. I'd suggest updating to "How to choose between native vs hybrid mobile applications"

**Comment by ipitah** [comment]
@ninjaginja Thank you very much, I will put into consideration your recommendations.
