### ISSUE TITLE
Pure Node.js? Node.js without frameworks? An overview.

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#1192]
### Brief Summary: 
Frameworks form an intense ecosystem around any Node.js applications. The high chances are that almost every developer will use one or several Node.js packages to develop a web app.

What about the Node.js purest function?  Building Node.js application with no frameworks?  This guide aims to discuss using the Node.js purest functions.

### Key Takeaways: 

Why you should learn to use pure Node.js
The benefits of pure Node.js.
The benefits and drawbacks of using Node.js frameworks as a developer.
The drawbacks of using pure Node.js as a developer.
Build a hello world server with pure Node.js (no frameworks such as Express).

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @kimkimani - approved
