### ISSUE TITLE
Bitcoin vs Ethereum: Technical Differences

### ISSUE THREAD

**Issue by lalith1403** [section-engineering-education/engineering-education#1193]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
These are the two largest cryptocurrencies in the world. But, Ethereum was introduced around 6 years after Bitcoin. This article discusses the key differences between the two and why there was a need for Ethereum. The differences lie in the way consensus is reached, time taken to verify the blocks, and other aspects. Towards the end of the article, we will discuss the applications and the value proposition that each of these currencies propose.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Introduction to Bitcoin and Ethereum. 
2. Technical differences: Comparison based on the mining process, consensus protocols used, hash rates, rewards, and blockchain structure.
3. Value proposition

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @lalith1403 - approved
