### ISSUE TITLE
Shared Nothing and Shared Disk Clustering Architectures 

### ISSUE THREAD

**Issue by EKahuha** [section-engineering-education/engineering-education#1195]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Many organizations turn to clustering as they look to increase the availability and computing capabilities of their hardware. Clustering basically works on the principle that multiple processors can tackle a problem better, faster, and more reliably than a single computer. Companies considering clustering options need to know what technologies and architectures provide the best approach to clustering. This article will discuss shared nothing and shared disk clustering architectures. 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. Why Use Clusters?
2. Types of Clustering
3. The differences between Shared Nothing and Shared Disk Clustering Architectures in terms of scalability, availability, etc. 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved
