### ISSUE TITLE
Choosing between Managed WordPress vs Shared WordPress Hosting 

### ISSUE THREAD

**Issue by EKahuha** [section-engineering-education/engineering-education#1196]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

There are different hosting services available in the market, including shared, managed WordPress hosting, and even dedicated hosting service. But which one is suitable for your needs? This article aims to compare shared and managed WordPress hosting.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. What is Shared WordPress hosting
2. What is Managed WordPress hosting
3. Benefits and drawbacks of both Managed WordPress and Shared WordPress Hosting

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved
