### ISSUE TITLE
fork() in C programming language - Linux 

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-engineering-education/engineering-education#1199]
### Brief Summary: 
Fork system call is used for creating a new process, which is called the child process, which runs concurrently with the process that makes the fork() call (parent process). After a new child process is created, both processes will execute the next instruction following the fork() system call.

### Key Takeaways: 
- What is a fork and what it is used for.
-  How to implement fork in the C programming language.
- I will create about 4-5 practical examples to take the reader to a new level with that system call.

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @ahmadmardeni1 - approved
