### ISSUE TITLE
Introduction to Kotlin flows

### ISSUE THREAD

**Issue by kayere** [section-engineering-education/engineering-education#1205]
### Brief Summary
Suspending functions asynchronously return single values. But, what if we want to return multiple values? That is where flows come in. A flow is a stream of multiple, asynchronously computed values. This article goes through the basics of kotlin flows.

### Key Takeaways: 
1. Understand what flows are.
2. Understand the basic applications of flows.
3. Understand how to use flows in a program.

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @kayere  - approved
