### ISSUE TITLE
Android paging library 

### ISSUE THREAD

**Issue by LinusMuema** [section-engineering-education/engineering-education#1206]
### Brief Summary: 
Working with paged data is usually a challenge to most android developers. Implementing a smooth flow of data is not easy if done manually. Paging library comes in to help with loading of data to a recyclerview in an easy way.

### Key Takeaways: 
1. What is the paging library 
2. How to implement the paging library 
3. The advantages of the paging library 

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @LinusMuema  - approved. Please be sure that the title is more specific and reflective of what the reader can expect to takeaway from the content, e.g. "How to implement Android Paging Library"
