### ISSUE TITLE
Introduction to Elastic Stack(ELK Stack)

### ISSUE THREAD

**Issue by OMONDIELLY** [section-engineering-education/engineering-education#1210]
### Brief Summary: 
ELK stack is a bundle of  software components that are designed to manage large amounts of log data.
Every activity or process completed by computer is stored as a log file which can be used for various purposes. The ELK stack (made up of Elasticsearch, Logstash, Beats and Kibana)  provide log management platform for these log files.
In this article, I'll cover the basics of Elastic Stack.

### Key Takeaways: 
1. What is Elastic stack
2. Components of ELK
3. How ELK works
4. Benefits of using ELK

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @OMONDIELLY - approved.

**Comment by edeediong** [comment]
I'm interested in this article when it's published
