### ISSUE TITLE
Introduction to Dialogs in Android using Kotlin

### ISSUE THREAD

**Issue by Ericgacoki** [section-engineering-education/engineering-education#1216]
### Brief Summary:
 
Android has distinguished techniques for improving user experience. One of them is the use of dialogs. A dialog is a brief conversation between the user and the application. They can be used to request actions from the users or pass quick messages to them.

### Key Takeaways: 

By the end of this tutorial, the learner should be able to:

1. Understand what are Dialogs and their roles in an application
2. Create an alert Dialog using Kotlin
3. Design and implement different types of custom Dialogs

### References: 

N/A

**Comment by ninjaginja** [comment]
good topic @Ericgacoki - approved
