### ISSUE TITLE
Setup CI/CD For Flutter Application Using Github Actions

### ISSUE THREAD

**Issue by Mastersam07** [section-engineering-education/engineering-education#1217]
### Brief Summary: 
During development, we need to ensure that any new code that is merged with the production/main codebase is tested and does not break any features. Also, automated release creation will save efforts to perform repetitive tasks that can be used to develop new features.

Here, we would deploy some GitHub actions to run tests on every pull requests and won't allow merging to the main codebase when this test fails. This automation would also handle generating the release APK. As a bonus, we would also create some step in the workflow to compare the previously generated APK with the new APK coming from the pull request branch. This would be useful in projects where the APK sizes matter and must be kept as minimal as possible.

### Key Takeaways: 
- Setting up workflow in GitHub actions
- Learn to apply GitHub actions for configuring proper workflows
- Comparing APKs for a high-level view of what changes in the apk with regards to size, assets, methods

### References: 
'N/A'

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @Mastersam07. Before moving forward, can you please confirm that there is not too much overlap with this previously published article - https://www.section.io/engineering-education/github-actions/

**Comment by Mastersam07** [comment]
Thanks, @ninjaginja. I have read through the article. Its an introduction to GitHub actions with the workflow targeted at Node.Js while my article aims to focus on different levels of app production using flutter right from development, code tests, pull requests, generating and releasing APKs or app bundles as the case may be.

**Comment by ninjaginja** [comment]
Ok, I just wanted to confirm, thanks - approved

**Comment by Mastersam07** [comment]
Okay. I can go ahead with the topic, right?

**Comment by ninjaginja** [comment]
yes, that's what I meant by 'approved' :)

**Comment by hectorkambow** [comment]
@Mastersam07 👋 just wanted to check if there was any update on this article topic
