### ISSUE TITLE
Creating a Vuejs2 CRUD application with local storage

### ISSUE THREAD

**Issue by EspiraMarvin** [section-engineering-education/engineering-education#1220]
### Brief Summary: 

A Vuejs2 CRUD application with local storage. Local storage helps persist data so users don't lose their state of the app between sessions. It stores and retrieves data in Web Storage API in modern browsers, and can be used completely offline as a data storage.

### Key Takeaways:

By the end of the article the student should be able to:
1. Create a Vuejs project with Vue CLI
2. Install the Vuejs dev tools browser extension.
3. Creating the Books Component and BookItem component.
4. Work with data.
5. Save and load data from Local Storage

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @EspiraMarvin - approved. Just one minor suggestion on the title, I'd recommend adding a descriptor that helps readers understand what they can expect to takeaway, e.g. "How to create a Vuejs2 CRUD ..."

**Comment by EspiraMarvin** [comment]
@ninjaginja Sure, I'll consider that.
