### ISSUE TITLE
Building a Cryptocurrency Tracking Telegram Bot with Python

### ISSUE THREAD

**Issue by LordGhostX** [section-engineering-education/engineering-education#1221]
### Brief Summary: 
A telegram bot is an account on telegram social media powered by a script built to serve as chatbots, games, and automation tools. In this article, we will be going over what they are, how they work, how to build them, then proceed to build a telegram bot that will send updates on cryptocurrency prices to users using Python.

### Key Takeaways:
By the end of this tutorial, the reader will be able to:
* define what telegram bots are
* build a telegram bot with Python
* build scripts to track cryptocurrency prices
* build a telegram bot that regularly sends cryptocurrency price updates

### References:
* https://core.telegram.org/bots
* https://python-telegram-bot.readthedocs.io/en/stable/

**Comment by ninjaginja** [comment]
cool topic @LordGhostX  - approved
