### ISSUE TITLE
SimCLR: A Simple Framework for Contrastive Learning of Visual Representations

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#1224]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Constrastive Learning date as far back as the 1990s. It is a learning paradigm where a representation is learned by comparing among the input samples. Instead of learning a signal from individual data samples one at a time, contrastive learning learns by comparing among different samples. 
In this article, we will learn about the SimCLR framework which is an improvement of previous contrastive learning approaches to self-supervised representation learning on images.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

By the end of this article, the reader will be able to understand:

1. What is Contrastive Learning?
2. The SimCLR Framework
3. Applications of Contrastive Learning in Computer Vision, Natural Language Processing and Reinforcement Learning.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

1. [Advancing Self-Supervised and Semi-Supervised Learning with SimCLR] (https://ai.googleblog.com/2020/04/advancing-self-supervised-and-semi.html) 
2. [A Simple Framework for Contrastive Learning of Visual Representations ] (https://arxiv.org/pdf/2002.05709.pdf)
3. [Contrastive Representation Learning: A Framework and Review] (https://arxiv.org/ftp/arxiv/papers/2010/2010.05113.pdf)

**Comment by ninjaginja** [comment]
good topic @Bayler  - approved
