### ISSUE TITLE
$group operator in MongoDB

### ISSUE THREAD

**Issue by HARITJOSHI1** [section-engineering-education/engineering-education#1228]
### Brief Summary: 
MongoDB is a very popular no sql solution in many tech communities and $group operator is a very important operator and its concept confuses many beginners, so my article can provide detail information on $group operator with some test cases and information on how and where to use it efficiently. 

### Key Takeaways: 
1. Reader will be able to understand what is $group operator. 

2. Used test cases and examples will provide better understanding of the operator and its syntax. 

3. Applications of  $group operator and how to use it will make user fully understand about all the key features of this operator. 

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @HARITJOSHI1 - approved
