### ISSUE TITLE
Implementing Bottom Sheet Dialogs Using Android Studio

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#1230]
### Brief Summary: 
The bottom sheet seems to be replacing the regular android dialogs and menus. Bottom Sheet slides up from the bottom, showing more relevant content into your android application UI cycle.

Many big corporations have implemented the bottom sheet dialog concept.  Some familiar examples are Google maps and Googles drive.

Google maps 
![set (2)](https://user-images.githubusercontent.com/36155624/104027076-f2e75f00-51d7-11eb-8ceb-d0655b20c25a.png)

Googles drive
![set (1)](https://user-images.githubusercontent.com/36155624/104027114-fed32100-51d7-11eb-8ea3-e8c042554b82.png)

An instance such as a music app, an app that requires a user to select a document/file and upload OR share them,

![set1](https://user-images.githubusercontent.com/36155624/104027185-13afb480-51d8-11eb-80de-3c27c79ee017.png)

 and payment components 

![set](https://user-images.githubusercontent.com/36155624/104027209-1ad6c280-51d8-11eb-84d9-f95509cb7a9a.jpg)

have been constantly implemented using the bottom sheet dialog to load the relevant data.

In terms of application, any android view such as text images, recycler views, buttons, and text inputs can be implemented into a bottom sheet. This makes it dynamic to load more diverse information, i.e., load data from the database and display them using the bottom sheet or collect information and save them to a database. In short, a bottom sheet can be applied in many instances as long as it fits your application cycle.

### Key Takeaways: 

Advantages of using the bottom sheet dialog
Types of the bottom sheet dialogs
Different bottom sheet behavior
Implementing a bottom sheet in android application using android studio
### References: 
https://developer.android.com/reference/com/google/android/material/bottomsheet/BottomSheetBehavior
https://developer.android.com/reference/com/google/android/material/bottomsheet/BottomSheetDialog

**Comment by ninjaginja** [comment]
good topic @kimkimani - approved
