### ISSUE TITLE
Fundamentals of Big Data Supply Chain

### ISSUE THREAD

**Issue by mbaabuones** [section-engineering-education/engineering-education#1231]
### Brief Summary: 
A big data supply chain is a process by which data collected by an organization is transformed into a valuable form for strategic use. This article provides the fundamentals of this emerging concept.

### Key Takeaways: 
1. Introduction to big data supply chain
2. Benefits of big data supply chain
3. Components of big data supply chain
4. Steps for Building a data supply chain
5. Issues for consideration
6. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
