### ISSUE TITLE
Understanding memoization in javascript

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#1232]
### Brief Summary:
 
 According to [Wikipedia](https://en.wikipedia.org/wiki/Memoization),  ***Memoization or memoisation is an optimization technique used primarily to speed up computer programs by storing the results of expensive function calls and returning the cached result when the same inputs occur again. Memoization has also been used in other contexts (and for purposes other than speed gains), such as in simple mutually recursive descent parsing. Although related to caching, memoization refers to a specific case of this optimization, distinguishing it from forms of caching such as buffering or page replacement. In the context of some logic programming languages, memoization is also known as tabling.***

Memoization is a technique of storing the results returned by a called function call. The next time we call the function, it just returns us the stored result instead of repeating the function execution once again.

### Key Takeaways: 

What is Memoization
importance of Memoization
How Memoization works
Caching functions values using Memoization technique
Memoizing recursive functions
Test Memoization by Performance
When to use Memoization

### References: 

https://www.sitepoint.com/implementing-memoization-in-javascript/#:~:text=Memoization%20is%20a%20programming%20technique,candidates%20to%20act%20as%20caches.&text=If%20it%20does%2C%20then%20the%20cached%20value%20is%20returned.
https://en.wikipedia.org/wiki/Memoization
https://flaviocopes.com/javascript-memoization/
https://dev.to/unalo_baayriyo/understanding-memoization-in-javascript-1e22

**Comment by ninjaginja** [comment]
good topic @kimkimani - approved. Just be sure that the majority of the article is original content and try to avoid copying entire paragraphs from cited sources. One way to help prevent this is by showing original examples of how memoization works.
