### ISSUE TITLE
Editing Video with Python (tutorial)

### ISSUE THREAD

**Issue by nicholaskross** [section-engineering-education/engineering-education#1234]
### Brief Summary: 
Videos are great for getting ideas across. But editing those videos can take a long time. Some types of videos (from sports clips to data visualizations) are both simple and time-consuming to edit. In this tutorial, we will use MoviePy, a library for Python, to automatically edit and add effects to a given video clip.

### Key Takeaways: 
- Recognize situations where MoviePy would be useful in the workplace
- Understand the key concepts/objects in MoviePy
- Use MoviePy to build an automatic video-editing script

### References: 
- https://zulko.github.io/moviepy/
- https://www.learningcontainer.com/mp4-sample-video-files-download/
- https://medium.com/@TejasBob/moviepy-is-awesome-part1-f90e91fffbb9

### Prerequisites:
- Basic Python (3) knowledge

**Comment by ninjaginja** [comment]
cool topic @nicholaskross - approved
