### ISSUE TITLE
Getting Started with Kubernetes

### ISSUE THREAD

**Issue by paulodhiambo** [section-engineering-education/engineering-education#1236]
### Brief Summary: 
Kubernetes is an open-source container-orchestration system for automating computer application deployment, scaling, and management. In the article, I will be explaining how various Kubernetes components work and how they are setup.

### Key Takeaways: 
1. What is Kubernetes.
2. How to install Kubernetes on the local computer for development.
3. Various Kubernetes components.
4. Basic Kubernetes commands.

### References: 
N/A

**Comment by ninjaginja** [comment]
great topic @paulodhiambo - approved
