### ISSUE TITLE
Getting started with ktor

### ISSUE THREAD

**Issue by LinusMuema** [section-engineering-education/engineering-education#1238]
### Brief Summary: 
Ktor server framework used to create servers using kotlin. This article aims to help the reader get a basic understanding of what ktor is and how to create RESTful services with it.

### Key Takeaways: 
1. What is ktor
2. How to setup ktor
3. Ktor application stracture

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @LinusMuema - approved
