### ISSUE TITLE
Implementing heap data structure in JavaScript.

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#1241]
### Brief Summary: 
Although not present in JavaScript data structures, heaps make it blazing fast to access priority-level elements. With arrays getting your data in O(n), heaps can get it in O(1). In this article, we shall discuss what heaps are, different kinds of heaps and walk-through implementing heap data structure in JavaScript.

### Key Takeaways: 
- Understand what heaps are.
- Understand the different types of heaps.
- Understand how to implement heap data structure in JavaScript.

### References: 
https://blog.bitsrc.io/implementing-heaps-in-javascript-c3fbf1cb2e65

**Comment by ninjaginja** [comment]
Thanks for the topic suggestions @mwangiKibui, but I think these foundational concepts have already been sufficiently covered in this previously published article - https://www.section.io/engineering-education/heap-data-structure-python/. 

While I recognize that you're proposing to discuss the implementation in JavaScript, I'm concerned with the overlap in the explanations at the beginning. Can you please describe the additional value that you intend to bring, or if too repetitive, suggest a different topic area to explore?

**Comment by mwangiKibui** [comment]
@ninjaginja I shall comprehensively look into the two heap types that is MinHeap and MaxHeap by explaining each of them with a JavaScript implementation. The reader at the end of the article shall be able to understand what they are, their use cases and how to implement them in JavaScript.

**Comment by ninjaginja** [comment]
Sounds great @mwangiKibui. Based on this, do you think it would be more descriptive to title the article "Understanding MinHeap vs MaxHeap in JavaScript"?

**Comment by mwangiKibui** [comment]
@ninjaginja Yes "Understanding MinHeap vs MaxHeap in JavaScript" sounds great title.
