### ISSUE TITLE
Spring Security Crash Course

### ISSUE THREAD

**Issue by john-amiscaray** [section-engineering-education/engineering-education#1244]
### Brief Summary: 
A crash course of some of the major features Spring security provides to secure your Spring boot applications. This guide will go over a few authentication strategies, ways to add authorization and more.

### Key Takeaways: 
- What is authentication and authorization
- The theory behind http basic, JWT, and OAuth authentication and how to implement them
- How to implement role based authorization
- Method level authorization with the preauthorize and postauthorize annotations

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @john-amiscaray - approved
