### ISSUE TITLE
Connect Basic4Android(B4A) Android development tool to MySQL Database Using PHP

### ISSUE THREAD

**Issue by tambastar** [section-engineering-education/engineering-education#1251]
### Brief Summary: 
Basic4Android is a rapid development tool used to develop native Android applications rapidly.
PHP is a serverside programming language used for developing web applications or serverside applications.
MySQL is a database management system used for managing relational database

### Key Takeaways: 
1. Learn about B4A libraries
2. Connect android application with PHP serverside language
3. Deploying android application on the android phone

### References: 
www.b4x.com

**Comment by ninjaginja** [comment]
good topic @tambastar - approved.
