### ISSUE TITLE
CSS Pseudo classes and Pseudo elements

### ISSUE THREAD

**Issue by ReactifyStudio** [section-engineering-education/engineering-education#1253]
### Brief Summary: 
Cascading Style Sheets is a style sheet language used for describing the presentation of a document written in a markup language such as HTML. Some of the topics one need to understand is dealing with pseudo elements and pseudo classes.

### Key Takeaways: 
1. Understanding what is a pseudo class in CSS
2. Understanding what a pseudo element is in CSS
3. How to use pseudo elements and classes in CSS

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @ReactifyStudio. I think this is a good topic area to cover, but I'd advise making the title more descriptive of what the reader can expect to gain after reading this article, e.g. "Understanding...", "How to Implement...", etc.

**Comment by ReactifyStudio** [comment]
Thanks. I will be changing the title

On Jan 11, 2021 20:23, "Molly Wojcik" <notifications@github.com> wrote:

Thank you for the topic suggestion @ReactifyStudio
<https://github.com/ReactifyStudio>. I think this is a good topic area to
cover, but I'd advise making the title more descriptive of what the reader
can expect to gain after reading this article, e.g. "Understanding...",
"How to Implement...", etc.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/section-io/engineering-education/issues/1253#issuecomment-758100820>,
or unsubscribe

**Comment by ReactifyStudio** [comment]
Well, @ninjaginja. Can I continue with this?

**Comment by ninjaginja** [comment]
yes, you may continue with this topic
