### ISSUE TITLE
Understanding Buffers and Streams in Node.js

### ISSUE THREAD

**Issue by ReactifyStudio** [section-engineering-education/engineering-education#1254]
### Brief Summary: 
Node.js is an open-source, cross-platform, back-end, JavaScript runtime environment that executes JavaScript code outside a web browser. One important topic to understand as a backend developer is dealing with Binary streaming. This article will focus on binary streams and buffers in Node.js.

### Key Takeaways: 
1. Understanding buffers in Node.js
2. Understanding streams in Node.js
3. Types of streams in Node.js
4. Code examples explaining the concepts

### References: 
https://nodejs.org/api/buffer.html

**Comment by ninjaginja** [comment]
good topic @ReactifyStudio - approved.

As a side note, please work through your list of open issues and submit final drafts before suggesting new topics. This helps us keep our pipelines clean. Thank you.
