### ISSUE TITLE
Introduction to Boosting Algorithms

### ISSUE THREAD

**Issue by bloodprashure** [section-engineering-education/engineering-education#1255]
### Brief Summary: 
Boosting algorithms have taken over Kaggle competitions. They have found their way into every submission and has been a reliable technique for delivering results. In this article, the reader is introduced to boosting algorithms, how they work and how to use them.

### Key Takeaways: 
1. Boosting algorithms
2. How they work
3. Examples of boosting algorithms
4. Using boosting algorithms to product results

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @bloodprashure - approved. Please be sure to put your draft through a thorough grammar/readability check prior to submitting for review. I noticed some grammatical errors and awkward phrasing in the description that you provided and wanted to call attention to it as an opportunity for you to maximize your payout.

**Comment by hectorkambow** [comment]
@bloodprashure  

Just wanted to follow up on this topic suggestion - since new article submission are now open.

**Comment by bloodprashure** [comment]
Hey Hector! I shall submit the article by tomorrow latest.
Sorry for the delay!

**Comment by hectorkambow** [comment]
Just closing to make room in the queue - can be resubmitted whenever ready to continue 🚀
