### ISSUE TITLE
Building your first Telegram bot in Node.js and Telegraf library

### ISSUE THREAD

**Issue by calebroHQ** [section-engineering-education/engineering-education#1262]
###Brief Summary: 
The main objective of this article is to introduce the reader to building  Telegram bots in Javascript runtime environment,Node.js.
This will enable one to create weather apps, notification bot, spambots, and vendor bots.

### Key Takeaways: 
1.Creating bots using Node.js
2. Using telegram bot API
3. Deploying telegram bots locally

###References: 
Official telegraf.js(Modern Telegram bot framework for Node.js) documentation https://telegraf.js.org/

**Comment by ninjaginja** [comment]
@calebroHQ  Could you please expand on this topic suggestion by providing a 2-3 paragraph sample of a portion of this article? The description that you've provided is rather brief and we'd like to better assess before approving.

**Comment by calebroHQ** [comment]
**BRIEF SUMMARY**
In this tutorial, you will learn how to build telegram bots using node.js runtime environment and telegraf library from scratch. This will act as an introduction to the Telegram bot environment that will enable you to build weather bot, vendor bots, e-commerce bot, or even dictionary bot. This tutorial will be as beginner-friendly as possible.

### INTRODUCTION
What are bots? Bots are third-party application accounts that run inside the Telegram application. Users can interact with bots by sending them messages, commands, and inline requests. You control your bots using HTTPS requests from the Telegram Bot API.

### PREREQUISITE 
Before you begin this guide you’ll need the following:

1. node.js installed
2. npm installed
3. visual studio code installed
4. Commandline use knowledge  

**KEY TAKEAWAYS**

- Coding telegram bot in javascript
- Running telegram bot locally
- using telegram bot API


**REFERENCE**
Official telegraf.js(Modern Telegram bot framework for Node.js) documentation [](https://telegraf.js.org/)

Telegram official introduction to bots [](https://core.telegram.org/bots)

**Comment by calebroHQ** [comment]
@ninjaginja, Kindly update me on this issue.
