### ISSUE TITLE
Introduction to Network Scanner-Nmap

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#1263]
### Brief Summary: 
 Nmap is a network scanning tool that uses IP packets to identify all the devices connected to a network and to provide information on the services and operating systems they are running.
Whether you are a private user with important information on your system, a major corporation or a government agency protecting a wealth of highly sensitive data, Nmap can provide the level of knowledge and pre-emptive thought required to keep things safe.

### Key Takeaways: 
1.Performing Port Scanning.
2.Operating System and Version Detection .
3.Finding live hosts on a network.
### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @jumamiller - approved
