### ISSUE TITLE
Introduction to Network Packet Analyzer-Wireshark

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#1264]
### Brief Summary: 
Wireshark is a network packet analyzer. A network packet analyzer presents captured packet data in as much detail as possible.
Network administrators use it to troubleshoot network problems.
Network security engineers use it to examine security problems.
QA engineers use it to verify network applications.
Developers use it to debug protocol implementations.

### Key Takeaways: 
1.color coding in Wireshark
2.Installation of Wireshark Software
3.Filters in Wireshark
4.Wireshark packet sniffing
5.Wireshark Statistics

### References: 
N/A

**Comment by ninjaginja** [comment]
@jumamiller is there a way to weave this into #1263 ? They seem like closely related topics.

**Comment by jumamiller** [comment]
@ninjaginja  Both very handy tools, Nmap allows you to scan an object for listening ports, discover services on a network and more. Wireshark lets you log network traffic and analyse it.

**Comment by ninjaginja** [comment]
Ok, I'll defer to your judgment on whether the two could be covered within a single article, or if you think they each warrant their own separate articles.

**Comment by ninjaginja** [comment]
@jumamiller this is the open issue that I was referring to, but maybe you ended up combining this content into your other article?

**Comment by jumamiller** [comment]
You didn't give me the go ahead, it's not in anyway linked to the other article

**Comment by ninjaginja** [comment]
Ok, you may proceed with this article. Once you've submitted a final draft for this issue, you may request that the other issue be reopened. We're simply trying to streamline our review processes, and keeping the pipeline contained to only articles that are actively being worked on helps us do this. Thank you for your cooperation :)

**Comment by jumamiller** [comment]
Noted with thanks
