### ISSUE TITLE
Angular vs. Vue.js

### ISSUE THREAD

**Issue by Pius1991** [section-engineering-education/engineering-education#1268]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

A couple of years ago, most developers depended on Angular and React JavaScript frameworks for their projects. Other JavaScript frameworks have since evolved rapidly over the past few years with frontend capabilities. 
In 2014, Vue.js was released, a progressive frontend framework for building complex user interfaces.
The article will give focus on the two amazing technologies, Angular and Vue.js frameworks. I will make comparisons, key features of each, and key differences.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1.	An overview of Angular. 
2.	An overview of Vue.js.
3.	Enumerate the key features of both Angular and Vue.js frameworks.
4.	Enumerate the key differences between the two in back-end technology combination, interaction with the users, compatibility with templates, performance metrics, speed, etcetera.
5.	Use cases of both frameworks.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
@Pius1991 I see that you have several issues open without drafts submitted. Please work through open content suggestions before suggesting new topics. I'm going to close this for now and you can request that it be reopened when ready. Thank you.

**Comment by Pius1991** [comment]
@ninjaginja Alright Madam, though I have only two open topics which I am yet to submit an article, I am on final touches. I will submit by tomorrow the I shall request for reopening. 
Thank you

**Comment by Pius1991** [comment]
@ninjaginja please re-open the topic
