### ISSUE TITLE
Understanding the Software Development Life Cycle (SDLC)

### ISSUE THREAD

**Issue by mbaabuones** [section-engineering-education/engineering-education#1269]
### Brief Summary: 
This article provides an overview of the steps taken by developers to develop software and related applications. It also takes readers through the most popular SDLC models and highlights their advantages and disadvantages. 

### Key Takeaways: 
1. What is software development life cycle (SDLC)?
2. Importance of SDLC
3. An Overview of SDLC stages
4. Software development process models (with advantages and disadvantages)
5. Limitations of SDLC
6. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
