### ISSUE TITLE
Implementing a Splash screen and Introduction slides in android applications.

### ISSUE THREAD

**Issue by BrianaNzivu** [section-engineering-education/engineering-education#1270]
### Brief Summary: 
A splash screen is the first screen that pops up when you open a mobile application. The splash screen most of the time contains a company's logo or an application's logo hence showing the identity and ownership of an application. Introduction slides is a brief slideshow mostly used by developers to summarize how to use the application, features in an application e.t.c.

### Key Takeaways: 
1.The reader should understand how to add a splash screen to a mobile application.
2.The reader should be able to understand how to add introduction slides to a mobile application.
3.The reader should be able to understand the importance of these features.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @BrianaNzivu - approved
