### ISSUE TITLE
Implementing a Date and Time picker in Android applications.

### ISSUE THREAD

**Issue by BrianaNzivu** [section-engineering-education/engineering-education#1271]
### Brief Summary: 
Most Android applications use date and time pickers to select dates and times other than having a user type it in. This has improved the User Experience of many applications. Date and time pickers are very simple to implement compared to having a user type it in by themself hence it is a growing trend in mobile application development due to its simplicity and functionality.

### Key Takeaways:
1.The reader should understand how to implement a time picker. 
2.The reader should understand how to implement a date picker. 
3.The reader should understand the importance of having a date and time picker.

### References: 
https://www.journaldev.com/9976/android-date-time-picker-dialog

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @BrianaNzivu . In order to help keep our production pipelines clean, we're asking that students focus on a single article before suggesting new topics. I just approved another topic suggestion from you. Please work through that content first, and you can request for this issue to be reopened once you've submitted a final draft for your other article. Thank you.

**Comment by BrianaNzivu** [comment]
Hey @hectorkambow 👋 . I was requesting for this issue to be re-opened so that I can submit an article for it.

Regards.

**Comment by hectorkambow** [comment]
@BrianaNzivu approved

**Comment by hectorkambow** [comment]
👋  Hi @BrianaNzivu  

Just pinging you on this topic form - as Im trying to make some room in the topic queue. 

No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by ahmadmardeni1** [comment]
Hey 👋 @BrianaNzivu 

Any update on this topic? We are trying to clear the queue. 
As Hector said, we can re-open it at any time.

**Comment by BrianaNzivu** [comment]
Hey @ahmadmardeni1 :wave: .
You can close it for now as I am still working on it. 
I will ping you once I open the PR.

cc @hectorkambow 

Regards.
