### ISSUE TITLE
An Introduction to Secure Sockets Layer/Transport Layer Security Protocol

### ISSUE THREAD

**Issue by kvardhan10** [section-engineering-education/engineering-education#1277]
### Brief Summary: 

This article dives into SSL/TLS protocol, its implementation(SSL Handshake, cipher suites, SSL certificates) and need while also dabbling with encryption and its 2 types(symmetric key and asymmetric key encryption), the role of encryption and the reinforced need for information security.

### Key Takeaways: 

1.Realise the need for encryption on the web.
2.Understand encryption and its types: symmetric key encryption and asymmetric key encryption.
3.Understand what SSL/TLS protocol is and how it is implemented(with the help of examples and diagrams)
4.Understand where and how SSL/TLS is used.

### References:
 
https://transparencyreport.google.com/https/overview?hl=en
https://en.wikipedia.org/wiki/Transport_Layer_Security

**Comment by ninjaginja** [comment]
great topic @kvardhan10 - approved. One minor note: Please be mindful of spacing. I noticed that you didn't include spaces after periods and before opening parentheses. There should be a single space after periods and before '(' in copy. Thank you. Please put your final draft through a thorough grammar/readability check prior to submitting for review. Thank you!

**Comment by kvardhan10** [comment]
Thank you.
Sure, will definitely keep that in mind👍
