### ISSUE TITLE
A beginners guide to python

### ISSUE THREAD

**Issue by WanjaMIKE** [section-engineering-education/engineering-education#1283]
### Brief Summary: 
Python is one of the most popular programming languages. Many developers use python due to its simplicity, as well as access to a huge range of libraries. This tutorial provides beginners with the basic knowledge of different python's functionalities.

### Key Takeaways: 
From this tutorial, you will learn
 - Variables 
 -  Classes
 - Methods
 - loops
 - lists and arrays

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @WanjaMIKE - approved
