### ISSUE TITLE
Implementing Hashtables using  CRC-32 algorithm.

### ISSUE THREAD

**Issue by jerimkaura** [section-engineering-education/engineering-education#1289]
### Brief Summary: 
Hashtable is a data structure that implements an associative array abstract data type, a structure that can map keys to values. This article explains the implementation of hash tables using the CRC-32 algorithm.
### Key Takeaways: 

1. Creating a hash table.
2. Performing Various Operations on Hashtable 
2. Hash function used for implementation.
3. Collision detection in hash tables

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @jerimkaura - approved
