### ISSUE TITLE
A Friendly Beginner's Guide to TypeScript

### ISSUE THREAD

**Issue by Olanetsoft** [section-engineering-education/engineering-education#1291]
### Brief Summary: 
TypeScript is a programming language that extends JavaScript by adding types. It saves you time catching errors and providing fixes before you run code. This tutorial is to provide a beginner guide to a developer trying to upskill or learn TypeScript.

### Key Takeaways: 
- Understand TypeScript fundamentals
- Compiling and Configuration of TypeScript 
- Classes in Typescript
- Interface in TypeScript
- Module and Namespaces

### References: 
https://www.typescriptlang.org/docs/
https://github.com/dzharii/awesome-typescript

**Comment by ninjaginja** [comment]
good topic @Olanetsoft - approved. (You may also find some opportunities to reference [this article](https://www.section.io/engineering-education/typescript-static-typing/) in your content.)

**Comment by Olanetsoft** [comment]
Oh great, thank you 😊
