### ISSUE TITLE
How To Build a Music Player with Django

### ISSUE THREAD

**Issue by Chukslord1** [section-engineering-education/engineering-education#1294]
### Brief Summary: 
This article would introduce the readers to the Django framework and frankly engage them in building a simple music player using the Django framework.

The music player would play and download songs on select by retrieving it's content from the database and utilizing html attributes.

### Key Takeaways: 
The reader  would be learn how to work with Django and it's  MVT structure

The reader would learn how to utilize sql database and Django's ORM

The reader would understand the structure of a music player and how it works.

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Chukslord1. While the topic sounds interesting, the grammar and readability of the description and bullet points that you've provided raises some red flags. Are you able to provide a writing sample of 2-3 paragraphs that will help us get a better sense of your English writing aptitude? You can simply post it via comment in this issue. Thank you.

**Comment by Chukslord1** [comment]
Thank you for responding. Sorry about the grammar issue. I will try to be more careful next time.
Here is a previously written sample you could use in assessment  https://soshace.com/how-to-use-prospector-for-python-static-code-analysis/.
If this isn't sufficient I could also provide some paragraphs from the article I pitched.

**Comment by ninjaginja** [comment]
Thank you @Chukslord1  - the article sample that you provided is really great! Nice work! You may go ahead and proceed with this topic. We look forward to reviewing the content :)
