### ISSUE TITLE
Python Projects for beginners part 1

### ISSUE THREAD

**Issue by Anitaachu** [section-engineering-education/engineering-education#1300]
### Brief Summary: 
Python is a high-level general purpose programming language. Python is popularly know for its simple and easy syntax which makes it easy to learn(beginner-friendly).  The best way to learn a new programming language is coding by the side and building a project, this tutorial series will provide step by step guide on how to build two beginner-friendly projects. 

### Key Takeaways: 
1. How to install python
2. Learn to work basic python functionalities. 
3. How to build two projects(rock, paper and scissors and a guessing game)
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://docs.python.org/3/tutorial/

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Anitaachu . While the topic is okay, the grammar and readability of the description and bullet points that you've provided raises some red flags. Are you able to provide a writing sample of 2-3 paragraphs that will help us get a better sense of your English writing aptitude? You can simply post it via comment in this issue. Thank you.

**Comment by Anitaachu** [comment]
Python is a high-level general-purpose programming language. Python is one of the most popular programming languages, it is known for its simple and easy syntax which makes it easy to learn, it is also popular because of its vase usability, python is used for web development, data analysis, scripting, automation, and according to research, python is growing in machine learning and artificial intelligence. Other uses include building security and network tool, game development, etc. 

Like every programming language, learning can be exciting and overwhelming, yet, learning theory is not enough to get a good grasp of the language. Indeed the first step to understanding a language is understanding its basic concepts, to have a good understanding of these concepts it is important to implement the theoretical knowledge by building projects using the concept.

**Comment by Anitaachu** [comment]
Thank you, I apologize for the grammatical errors. I will cross-check the article next time. Here's a link to an already published article. https://www.section.io/engineering-education/working-with-forms-in-django/.  I hope this is okay, thank yo

**Comment by ninjaginja** [comment]
Thank you for providing this @Anitaachu. You may proceed with this article.

I noticed that you also submitted another topic suggestion following this one. We're requesting that students work through a single article before suggesting new topics. I'm going to close the other issue until you've submitted a final draft for this article, at which time you may request to reopen it. Thank you.
