### ISSUE TITLE
Building an analytics system using InfluxDB

### ISSUE THREAD

**Issue by adithbharadwaj** [section-engineering-education/engineering-education#1302]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
In the previous article, I explored the basics of time series databases and influxDb. In this article, I will explore building a time-series analytics system in InfluxDB using its API in Python. 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Understand how to use the InfluxDB Python API
2. Understand how to insert data into InfluxDB using Python
3. Visualize and analyze the data using the InfluxDB UI
4. Query and retrieve data from InfluxDB

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://www.influxdata.com/

**Comment by ninjaginja** [comment]
great topic @adithbharadwaj - approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic suggestion - since new article submission are now open.
@adithbharadwaj

**Comment by adithbharadwaj** [comment]
> Just wanted to follow up on this topic suggestion - since new article submission are now open.
> @adithbharadwaj

Hey Hector. I forgot that the submissions were open. I will try to work on this article. Thank you :)

**Comment by adithbharadwaj** [comment]
Closing this because I'm a little occupied at the moment. Will try to contribute when I get some time :)
