### ISSUE TITLE
Introduction To Wireless Networking

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#1303]
### Brief Summary: 
Wireless networking is a method by which homes, telecommunications networks and business installations avoid the costly process of introducing cables into a building, or as a connection between various equipment locations.
Wireless devices such as WiFi-enabled smartphones, laptops, WiFi phones such as Spectralink, and even wireless printers rely on the strength and security of your WLAN (wireless LAN).
### Key Takeaways: 
1.Types of wireless networks
2.Wireless Networking Devices
3.Examples of wireless technologies
### References: 
N/A

**Comment by ninjaginja** [comment]
@jumamiller I noticed that you have several issues open. In an effort to keep our pipelines clean, we're requesting that you work through existing open issues before suggesting new topics. I'm going to close this for now. Once you are ready to begin working on this article (i.e. have opened a PR for prior open issues), please request to reopen this issue. Thank you.

**Comment by jumamiller** [comment]
@ninjaginja kindly this issue too,

**Comment by ninjaginja** [comment]
@jumamiller Are you intending to combine this article with #1304? If not, which single issue would you prefer for me to reopen at this time? (We only keep one active issue open at a time.)

**Comment by jumamiller** [comment]
@ninjaginja open this one #1303
