### ISSUE TITLE
Introduction to Network Management

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#1304]
### Brief Summary: 
Enterprises must be able to accurately track network performance to ensure users can access the applications they need. Find out about the latest trends shaping network monitoring software and tools, including expert advice about the steps companies should take to best manage their networks.

### Key Takeaways: 
1. Network Resource Monitoring Techniques
2. Simple Network Management Protocol
3. ISO Network Management Model
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
closing until open previous open issues are worked through

**Comment by jumamiller** [comment]
I do not have any open issues already submitted pull requests

**Comment by jumamiller** [comment]
@ninjaginja only pending issues are the ones not approved.You can confirm

**Comment by jumamiller** [comment]
@ninjaginja kindly open this issue

**Comment by jumamiller** [comment]
@ninjaginja you can now open this issue
