### ISSUE TITLE
Node.js CLI Input

### ISSUE THREAD

**Issue by zolomohan** [section-engineering-education/engineering-education#1306]
## Brief Summary
In this tutorial, we will learn how to accept input from the user in a Node.js CLI application using the `readline` package.

## Key Takeaways

- Set up the `readline` object.
- Learn how to ask a question and use a callback function to process the result from the user.
- Write an `async` function with an `asyncIterator` to simulate halting the flow of the program to get input.

**Comment by ninjaginja** [comment]
@zolomohan Before proceeding, could you please confirm that there's not too much overlap with [this article](https://www.section.io/engineering-education/create-a-nodejs-cli/)? While it doesn't cover the readline package specifically, I want to be sure that the overall process isn't too repetive.

**Comment by zolomohan** [comment]
@ninjaginja [This article](https://www.section.io/engineering-education/create-a-nodejs-cli/) is not covering how to get input from the user. There won't be any overlap in the content.

**Comment by ninjaginja** [comment]
Ok, great. Thank you for confirming. You may go ahead and proceed with the content.
