### ISSUE TITLE
Python static typing

### ISSUE THREAD

**Issue by jerimkaura** [section-engineering-education/engineering-education#1316]
### Brief Summary: 
Python is a dynamically typed language. The interpreter handled types implicitly. This article demonstrates how several annotation tools can be used to specify constraint data types of objects. Typing makes the code cleaner and maintainable.

### Key Takeaways: 
1. Static typing in python
2. Function Annotations
3. Variable Annotations
4. Basics of mypy type checker

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @jerimkaura - approved. My only (minor) suggestion is to be a bit more descriptive with the title.

**Comment by jerimkaura** [comment]
Alright noted.
