### ISSUE TITLE
Getting started with game development using windows forms

### ISSUE THREAD

**Issue by mohamedgh16** [section-engineering-education/engineering-education#1317]
### Brief Summary: 
Playing video games is always fun, but what about making one? In this tutorial, we will use windows forms to build a game and go through the steps of making a small puzzle game called Mastermind. Mastermind is a puzzle game that tests the memory and the ability of the player to determine the exact output between all the possibilities.

### Key Takeaways: 
1-How to play/win the game.
2-building the form & the controls of the game.
3-understand all the methods used inside the code.

### References: 
https://en.wikipedia.org/wiki/Mastermind_(board_game)
https://www.section.io/engineering-education/getting-started-with-windows-forms-using-c-sharp/

**Comment by ninjaginja** [comment]
good topic @mohamedgh16 - approved
