### ISSUE TITLE
Introduction to Grails Development with Intellj

### ISSUE THREAD

**Issue by tambastar** [section-engineering-education/engineering-education#1320]
### Brief Summary: 
Get to know how to develop Grails application using IntellJ. Grails application  is a java framework that uses MVC for web app development

### Key Takeaways: 
1. Understand Views
2. Understand Services and Controllers
3. Understand Domains
4. Publish application

### References: 
https://grails.org/

**Comment by ninjaginja** [comment]
good topic @tambastar - approved
