### ISSUE TITLE
Introduction to Adafruit.io

### ISSUE THREAD

**Issue by srishilesh** [section-engineering-education/engineering-education#1323]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Adafruit.io is a cloud provider primarily focusing on deployments of IoT solutions. It helps in displaying real-time data, connect several webservices like Twitter, and RSS feeds. In this article, the reader will get an overview of what adafruit.io is, how to work with it, and a simple demonstration using Python will be done.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- The reader what adafruit.io is, and its use
- The reader will learn how to work with it
- The reader will build a simple project using Python

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
- https://io.adafruit.com/api/docs/#adafruit-io-http-api
- https://learn.adafruit.com/adafruit-io/overview

**Comment by ninjaginja** [comment]
@srishilesh - Is adafruit.io a cloud provider or a platform? From what I can tell, they don't own their own infrastructure to support cloud hosting?

**Comment by srishilesh** [comment]
> @srishilesh - Is adafruit.io a cloud provider or a platform? From what I can tell, they don't own their own infrastructure to support cloud hosting?

Hi @ninjaginja . I'm sorry it's a cloud platform, not a cloud provider. My bad.

**Comment by ninjaginja** [comment]
Ok, thanks for the clarification. You may go ahead and proceed with this article. I noticed that you opened another issue following this one. We're requesting that students focus on seeing an article through from topic suggestion to final draft before suggesting new topics. I'm going to close that issue for now and you can request that it be reopened once you've submitted a draft for this article.

**Comment by srishilesh** [comment]
> Ok, thanks for the clarification. You may go ahead and proceed with this article. I noticed that you opened another issue following this one. We're requesting that students focus on seeing an article through from topic suggestion to final draft before suggesting new topics. I'm going to close that issue for now and you can request that it be reopened once you've submitted a draft for this article.

Alright thanks.
