### ISSUE TITLE
Working with SQLite database

### ISSUE THREAD

**Issue by srishilesh** [section-engineering-education/engineering-education#1324]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
SQLite is a relational database management system (RDBMS) contained in a C library. In contrast to many other database management systems, SQLite is not a client–server database engine. Rather, it is embedded into the end program. In this article, we will learn what SQLite database is, how to work with it, and demonstrate all the operations by building a simple project.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- The reader will understand what SQLite database is, and how to work with it
- The reader will build a simple project to understand better

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
- https://en.wikipedia.org/wiki/SQLite
- https://www.sqlite.org/index.html

**Comment by ninjaginja** [comment]
closing while other article is worked through

**Comment by srishilesh** [comment]
Hey @ninjaginja/@hectorkambow,

My other article is in final review. Can I start working on this?

Requesting for your approval.

Thank you.

**Comment by hectorkambow** [comment]
@srishilesh 👋  

I'd hold off on submitting a PR - just in case the last one requires any final edits 🚀

**Comment by hectorkambow** [comment]
gtg 👍

**Comment by hectorkambow** [comment]
@srishilesh just wanted to follow up - in case I missed the PR for this tipic

**Comment by srishilesh** [comment]
> @srishilesh just wanted to follow up - in case I missed the PR for this tipic 

@hectorkambow 

This article is in progress, will raise a PR soon by this weekend.

**Comment by hectorkambow** [comment]
👋  @srishilesh 
Just pinging you on this topic form - as Im trying to make some room in the topic queue.

No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by srishilesh** [comment]
@hectorkambow 

Yeah sure.

I'll close this PR now. Will reopen once I complete it.

Thanks.
