### ISSUE TITLE
Multicollinearity in Regression Models

### ISSUE THREAD

**Issue by collins-a** [section-engineering-education/engineering-education#1330]
### Brief Summary: 

Interpretability of machine learning models helps us understand the predictions of a model. Interpretable models are desirable. However, the interpretability of a regression model may be affected when the process of determining the effects of individual features in a model becomes unreliable. A cause of this is multicollinearity. We explore multicollinearity; we learn how to detect and fix it. 

### Key Takeaways: 

Reader should;
1. Understand collinearity, multicollinearity, and variables.
2. Read on the causes of multicollinearity.
3. Learn to test for multicollinearity through VIF.
4. Explore simple fixes for multicollinearity.

### References: 

https://machinelearningmind.com/2019/10/19/multicollinearity-how-to-fix-it/

https://statisticsbyjim.com/regression/multicollinearity-in-regression-analysis/

https://www.analyticsvidhya.com/blog/2020/03/what-is-multicollinearity/

https://towardsdatascience.com/multicollinearity-in-data-science-c5f6c0fe6edf

https://www.datasciencecentral.com/profiles/blogs/multicollinearity-a-problem-or-an-opportunity

**Comment by ninjaginja** [comment]
good topic @collins-a - approved. Wondering if a stronger title might be "How to Detect and Correct for Multicollinearity in Regression Models"?

**Comment by collins-a** [comment]
Noted, @ninjaginja it is stronger. Thank you
