### ISSUE TITLE
Detecting Botnets using DNS-based technique

### ISSUE THREAD

**Issue by pauloprof** [section-engineering-education/engineering-education#1332]
### Brief Summary: 
The world of technology has seen increased security threats in the recent past.  One such threat is botnet, which can be used to cause DDoS attacks among others. To deal with such a threat, one must be able to identify its presence. It is in this view that this article explains how to identify botnets using a DNS-based technique.
### Key Takeaways: 
1.	Meaning and threats posed by botnets
2.	How to use DNS-based technique to detect botnets
3.	Examples of DNS-based technique tools

### References: 
'N/A'.)

**Comment by ninjaginja** [comment]
good topic @pauloprof - approved.
