### ISSUE TITLE
Mobile Automation Testing with Appium: An Introduction

### ISSUE THREAD

**Issue by mbaabuones** [section-engineering-education/engineering-education#1341]
### Brief Summary: 
Appium is a popular mobile automation testing tool used for testing mobile browsers and mobile applications. This article introduces readers to this important tool that tests numerous mobile phone apps. 

### Key Takeaways: 
1.	Introduction to Appium automation testing
2.	Why Appium is widely used
3.	Features of Appium
4.	Appium architecture
5.	How Appium works
6.	Limitations of Appium
7.	Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
