### ISSUE TITLE
Phone Number Authentication using Firebase in a Non-Expo React Native Application 

### ISSUE THREAD

**Issue by zolomohan** [section-engineering-education/engineering-education#1343]
## Brief Summary
In this tutorial, we will develop a React Native application (Non-Expo) and add phone number authentication using Firebase.

## Key Takeaways

- Set up Firebase Project for Phone number authentication.
- Add 2 Screens: Log in and Authenticated screen.
- Use the Firebase Auth module and authenticate users using Phone numbers.
- Logout from the authenticated screen.

**Comment by ninjaginja** [comment]
good topic @zolomohan - approved
