### ISSUE TITLE
Setting up CI/CD for Python Packages using GitHub Actions

### ISSUE THREAD

**Issue by edeediong** [section-engineering-education/engineering-education#1351]
### Brief Summary: 
Continuous Integration and Continuous Deployment is an important part of DevOps culture as companies, products and individuals need to release their software faster and bug-free. GitHub Actions is one tool used to accomplish this. In this tutorial, we will mimic a python project and deliver updated versions of that project using CI/CD techniques.

### Key Takeaways: 
* What is CI/CD
* Building a Python Package
* Testing Python Package with GitHub Actions
* Deploying Python Package to PyPI with GitHub Actions
* Conclusion

### References: 
https://www.section.io/engineering-education/building-a-python-package-and-publishing-on-pypi/
https://edeediong.me/how-to-build-a-python-package/

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @edeediong. Could you please take a look at the article in progress under #1217  to make sure there's not too much overlap in the fundamental process that you follow to set this up?

**Comment by edeediong** [comment]
Thanks for pointing out the article in progress. The [first](https://www.section.io/engineering-education/github-actions/) article posted here and this upcoming article will explain a lot about GitHub Actions. Luckily, my article is more focused on using Python available tools and also connecting to PyPI from GitHub Actions, which none of them are writing on. They are NodeJS and Flutter applications being built. Those two articles will be a reference for _Testing Python Package with GitHub Actions_ section as I won't dwell on the CI tool but on the language.

So no, there isn't much overlap in the fundamental process. However, I could use another CI tool (although, don't you think it will make a good series if we can curate all articles on GitHub Actions together?).

**Comment by ninjaginja** [comment]
Thanks for the additional clarification @edeediong. Sounds like a great opportunity to build on value delivered across other articles. You may go ahead and proceed with drafting this content. Thank you!

**Comment by edeediong** [comment]
Thank you!
