### ISSUE TITLE
Branching and Decision Making in Java

### ISSUE THREAD

**Issue by cyberShaw** [section-engineering-education/engineering-education#1357]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
This article will be an introduction to branching and decision making statements in Java, such as:
- if 
- if ... else
- switch
- ternary operator

There would also be a hands-on where the reader is taught how to use those statements in different use cases and scenarios.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- The reader will be able to understand the intuition behind branching in Java.
- The reader will be given a hands-on to the various branching features in Java.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://docs.oracle.com/javase/tutorial/

**Comment by ninjaginja** [comment]
please see comment on #1356
