### ISSUE TITLE
Verifying Website Domains

### ISSUE THREAD

**Issue by pkalynan** [section-engineering-education/engineering-education#1360]
### Brief Summary: 

Verifying website domains for originality can be complicated during a time where internet is used constantly for both good and bad. By using Python 3.8.5 Shell and Windows Power Shell within a Windows Operating System environment, determining the credibility of a website domain name can be done. 

### Key Takeaways: 

Retrieve DNS information by coding in Python Shell. Use website API commands within a Windows Power Shell. Identify the complexities of domain modifications.   

### References: 
'N/A'

**Comment by ninjaginja** [comment]
good topic @pkalynan - approved.
