### ISSUE TITLE
The development of 5G protocol standardization.

### ISSUE THREAD

**Issue by RuthAMare** [section-engineering-education/engineering-education#1362]
### Brief Summary: 
This article will describe the LTE evolution and the 5G new technologies such as the NextGen core network and NR which are defined in R15 and R16. This will also cover the various Releases in an attempt to give a good understanding of the development of the 5G protocol standardization.
### Key Takeaways: 
1.	Introduction to 5G protocol standardization
2.	5G networking mode.
3.	Development of uRLLc and mMTC
4.	5G Network security

### References: 
 N/A

**Comment by hectorkambow** [comment]
Nice topic @RuthAMare - approved.
