### ISSUE TITLE
Uploading Images to Cloudinary from Django Application

### ISSUE THREAD

**Issue by shuaiboseni** [section-engineering-education/engineering-education#1363]
### Brief Summary: 
Learn how to use Django to save images to Cloudinary.
If you deploy your Django-app to Heroku, you won't be able to save images, so we will use Cloudinary to solve this problem.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Learn about Cloudinary
2. django-cloudinary-storage package 
3. how to create folders in cloudinary

### References: 
N/A

**Comment by hectorkambow** [comment]
@shuaiboseni  Sounds like a great topic - please go through the current Django articles we have to be sure to expand upon them were possible.  Topic approved.

**Comment by shuaiboseni** [comment]
Hi,

Thanks for the approval.

I wanted to mention that my pull request will be coming from my other
github account(shosenwales), as its my main github profile. I should have
used from the beginning.

I hope this wont be a problem

Thanks.

**Comment by shuaiboseni** [comment]
Hi,

Thanks for the approval.

I wanted to mention that my pull request will be coming from my other
github account(shosenwales), as its my main github profile. I should have
used from the beginning.

I hope this wont be a problem

Thanks and regards

**Comment by hectorkambow** [comment]
@shuaiboseni 

Should not be a problem - lets just be sure to link this topic form to that PR to have it closed once merged.
