### ISSUE TITLE
Getting Started With JSON Web Auth Using Angular 8 and NodeJS

### ISSUE THREAD

**Issue by ephnjor2021** [section-engineering-education/engineering-education#1366]
### Brief Summary: 
The guide is about interfacing an Angular 8 Project with a secure backend API. The backend will be running on Node.js. The security that will underlay the interfacing will be JSON Web Tokens.

The reason for using JSON Web tokens is because it's a secure way to verify the integrity of the exchange of information between the client and the server. Then I will adapt it for authorization so that in case of any breach the token will not verify or expire based on time.

### Key Takeaways: 

At the end of this guide the learner will be able to:

- Create JSON Web Token after Authentication
- Secure API Endpoints with JSON Web Tokens
- Integrate JSON Web Tokens in Angular 8
- Store and Retrieve a JSON Web Token
- Implement an Interceptor/Middleware in Angular 8 and Node.JS and also a status 401 Unauthorised Code

### References: 
N/A

**Comment by hectorkambow** [comment]
Sounds like a great guide - topic approved. @ephnjor2021
