### ISSUE TITLE
JavaScript vs. TypeScript

### ISSUE THREAD

**Issue by Catemacharia** [section-engineering-education/engineering-education#1372]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Both JavaScript (JS) and TypeScript are among the world's most commonly used programming languages in HyperText Markup Language (HTML).
 Generally, JavaScript (JS) has powerfully built features, and it can easily enhance your website's HTML pages. On the other hand, TypeScript is more a superset of JS with some added features. 
This article will highlight their key differences in annotations, type, compilation, interface, syntax, etcetera. It will also enumerate their key features and advantages of using TypeScript over JavaScript.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1.	What is JavaScript? What is TypeScript?
2.	Why both JavaScript and TypeScript are used as programming languages?
3.	What are the key features of both JavaScript and TypeScript?
4.	What are the key differences between JavaScript and Typescript?
5.	What are the advantages of using TypeScript over JavaScript?

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by hectorkambow** [comment]
@Catemacharia  sounds like a great topic- approved.

**Comment by hectorkambow** [comment]
@Catemacharia 

Just wanted to follow up on this topic suggestion - since new article submission are now open.
