### ISSUE TITLE
Flask Database Integration with SQLAlchemy

### ISSUE THREAD

**Issue by corpsgeek** [section-engineering-education/engineering-education#1373]
### Brief Summary: 
SQLAlchemy is a python library that aids in manipulating database with the use of SQL and Object Relational Mapping.

### Key Takeaways: 
- Installing and setting up SQLAlchemy
- Understanding one-to-one and one-to-many database relationship
- Creating a model
- Building a Flask web application that registers user data and store into the database.

### References: 
N/A

**Comment by hectorkambow** [comment]
Topic approved @corpsgeek
