### ISSUE TITLE
Introduction to OpenFlow protocol in SDN 

### ISSUE THREAD

**Issue by AakashR2208** [section-engineering-education/engineering-education#1374]
### Brief Summary: 
This article would start with basics of SDN and then introduce open flow protocol and how is it used in networks. A brief explanation of why is SDN so popular. Advantages and features of OpenFlow protocol and why is it used in SDN.

### Key Takeaways: 
1. What is high level definition of SDN,
2. Why is SDN needed ?
3. What is OpenFlow protocol? The features, pros, cons, and alternatives if any?  
### References: 
[SDXCentral](https://www.sdxcentral.com/networking/sdn/definitions/what-is-openflow/)
[Science direct](https://www.sciencedirect.com/topics/computer-science/openflow-protocol)
[ONF](https://opennetworking.org)

**Comment by hectorkambow** [comment]
Sounds like a good topic - approved @AakashR2208
