### ISSUE TITLE
An overview of Database Testing

### ISSUE THREAD

**Issue by mbaabuones** [section-engineering-education/engineering-education#1376]
### Brief Summary: 
Database testing is an important concept in database management systems. This is because it establishes whether there are errors in a database system to enhance the consistency, performance and reliability of these systems. This article provides an overview of this concept. 

### Key Takeaways: 
1. What is database testing?
2. Why database testing is important
3. Types of database testing
4. Stages of database testing
5. List of popular database testing tools
6. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by hectorkambow** [comment]
Sounds like a nice topic - approved @mbaabuones
