### ISSUE TITLE
Getting Started with PHP

### ISSUE THREAD

**Issue by Erastuskanyatta** [section-engineering-education/engineering-education#1378]
### Brief Summary: 
PHP is a server scripting language and a powerful tool for making dynamic and interactive web pages. It is  widely-used, free, and efficient language.It is also easy to learn and understand hence making it one of the best server language for beginners. PHP is free and easy to download. In this tutorial we will look at the most important basic parts of PHP step by step.

### Key Takeaways: 
After reading this article the reader will be able to:
1. set up an environment for running PHP i.e downloading xampp which will come along with PHP
2. understand PHP syntax
3. write a program eg Helloworld using PHP
4. write PHP statements
5. output a PHP program

### References: 
N/A

**Comment by hectorkambow** [comment]
Sounds like a nice topic to share with the community - please make sure there is no topic overlap with past published articles and current upcoming articles in the PR queue. - Approved @Erastuskanyatta

**Comment by Erastuskanyatta** [comment]
@hectorkambow the only part that appears to be similar to the past PR is that of the Xampp and its must be there for PHP to run. What should I do with do it because I want my PR to be unique?
