### ISSUE TITLE
Understanding the Contacts and File system browser APIs

### ISSUE THREAD

**Issue by ReactifyStudio** [section-engineering-education/engineering-education#1379]
### Brief Summary: 
Javascript is the programming language of the browser. With the recent improvements in the web, the added APIs gives us the possibility of near native-platform. This will focus on the Files and Contacts APIs commonly used in Progressive web Applications.
### Key Takeaways: 
1. What is the file system browser API
2. What is the Contacts API
3. How to use the files and browser API

### References: 
N/A

**Comment by hectorkambow** [comment]
👍  
Seems like a helpful guide. 
Approved. @ReactifyStudio 

Would be helpful to include some practical examples of how these APIs are useful. 🚀

**Comment by hectorkambow** [comment]
Moving forward: 
Only one topic issue opened at a time
