### ISSUE TITLE
Create Login and Register System with C# Winforms

### ISSUE THREAD

**Issue by tambastar** [section-engineering-education/engineering-education#1381]
### Brief Summary: 
Create a logic of how a developer can create a system that will enable register. After Register, it will enable login and authentication with C# window forms

### Key Takeaways: 
1. Database connection, selection, insertion using MySQL.
2. Logic for Login in C#
3. Logic of Register with Verification
4. Security when getting data

### References: 
https://docs.microsoft.com/en-us/dotnet/csharp/

**Comment by hectorkambow** [comment]
Sounds like a nice topic to share with the community - please make sure there is no topic overlap with past published articles and current upcoming articles in the PR queue. - Approved 
@tambastar
