### ISSUE TITLE
Understanding systemd

### ISSUE THREAD

**Issue by Bashorun97** [section-engineering-education/engineering-education#1386]
### Idea Summary
systemd is a tool used for service initialization amongst Linux based systems.
It's a big divergence from the common System V init implementation such that it's able to flexibly manage dependencies during service startup.
systemd is a relatively new and sophisticated technology which might be intimidating for one to learn as it also has a lot of features.
I will be discussing systemd and its configuration, dependency management and system control using unit files, service activation etc.

### Key Takeways:

- An understanding of why and how systemd is a solution to Sytem V init - deficiencies.
- The different types of unit files and how they work to perform boot-time tasks
- Have an understanding of systemd's method of dependency management
- The reader would be able to manage, edit and write systemd unit files
- Use systemctl as a tool for instrospecting and controlling the state of systemd and service manager

### References: 
- https://wiki.archlinux.org/index.php/Systemd.
- https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files
- https://people.redhat.com/pladd/systemd_NYRHUG_2016-03.pdf

**Comment by hectorkambow** [comment]
Sounds like a cool topic to share with the community - please make sure there is no topic overlap with past published articles and current upcoming articles in the PR queue. - Approved 
Also, be sure to consult our [resources page](https://github.com/section-io/engineering-education/blob/master/new_contributors/resources-page.md) to see our helpful guides and tips. 
@Bashorun97

**Comment by Bashorun97** [comment]
Thanks for the approval.
I just finished preparing the article only for me to find out the max words is 750 as I was creating the PR. My article is over 3,000 words because I really when in-depth on explaining several key concepts. I also find this to be a valid reason. So please I want to know if this article can fly (based on my reason) or it should be reduced 750 words.
Thank you.

**Comment by hectorkambow** [comment]
@Bashorun97  The max is no longer a requirement - where did you see that ? That is old and must be edited.

**Comment by hectorkambow** [comment]
There is no max only a min @Bashorun97

**Comment by Bashorun97** [comment]
Thank you @hectorkambow. By the way, I'm a first time poster so getting a review will help me learn the ropes quickly.
