### ISSUE TITLE
Getting started with Spring Data MongoDB with Kotlin

### ISSUE THREAD

**Issue by paulodhiambo** [section-engineering-education/engineering-education#1387]
### Brief Summary: 
Spring Data MongoDB provides an integration between Spring Boot application and the MongoDB document database. In the article I will explain all the concepts need to create a Spring Boot application that integrates with MongoDB document database. I will be creating a simple Spring Boot application in the article to enable the reader to gain practical knowledge on how to use Spring Data MongoDB in a real application.

### Key Takeaways: 
1. What is Spring Data MongoDB.
2. How to use Spring Data MongoDB.
3. Creating Rest APIs in Kotlin with Spring Data MongoDB.

### References: 
N/A

**Comment by hectorkambow** [comment]
Sounds like a nice topic to share with the community - please make sure there is no topic overlap with past published articles and current upcoming articles in the PR queue. - Approved 
Also, be sure to consult our [resources page](https://github.com/section-io/engineering-education/blob/master/new_contributors/resources-page.md) to see our helpful guides and tips. 
@paulodhiambo
