### ISSUE TITLE
Getting Started With Javascript Modules

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#1396]
### Brief Summary: 
As an application grows bigger, we want to split it into multiple files, so called “modules”. 
A module may contain a class or a library of functions for a specific purpose.

### Key Takeaways: 
1.Core Module features.
2.Module patterns.
3. How to use CommonJS and AMD to manage modules.
4. Bundling Modules
### References: 
N/A

**Comment by hectorkambow** [comment]
Sounds like a great topic to share with the community - please make sure there is no topic overlap with past [published articles ](https://www.section.io/engineering-education/search/)and current upcoming articles in the[ PR queue](https://github.com/section-io/engineering-education/pulls). 
Approved - @jumamiller - May be helpful to provide some background knowledge on modules 

Be sure to consult our [resources page](https://github.com/section-io/engineering-education/blob/master/new_contributors/resources-page.md) to see our helpful guides and tips.
