### ISSUE TITLE
How to consume data from an API in Android

### ISSUE THREAD

**Issue by WanjaMIKE** [section-engineering-education/engineering-education#1397]
### Brief Summary: 

APIs are important because they allow developers to access a huge range of functionalities and data without building everything from scratch. APIs can provide information relating to movies, weather, finances, as well as human resources. Therefore, we can be more productive when we incorporate APIs in our android applications.

### Key Takeaways: 
- Understanding APIs
- Knowing how to make requests from APIs
- Parsing data to UI components

### References: 
N/A

**Comment by hectorkambow** [comment]
Sounds like a great topic to share with the community - please make sure there is no topic overlap with past [published articles ](https://www.section.io/engineering-education/search/)and current upcoming articles in the[ PR queue](https://github.com/section-io/engineering-education/pulls). 🚀 
Approved - @WanjaMIKE

**Comment by WanjaMIKE** [comment]
@hectorkambow 
okay, thank you
