### ISSUE TITLE
Getting started with Matlab loops

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#1398]
### Brief Summary: 
MATLAB is a special-purpose language that is an excellent choice for writing moderate-size programs that solve problems involving the manipulation of numbers. In the article I will be explaining various loops in Matlab.

### Key Takeaways: 
1. Matlab loops.
2. Creating a Matlab application using loops.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by hectorkambow** [comment]
Sounds like a good topic to share with the community - please make sure there is no topic overlap with past [published articles ](https://www.section.io/engineering-education/search/) and current upcoming articles in the[ PR queue](https://github.com/section-io/engineering-education/pulls). 

Approved - @jumapaul 

Be sure to consult our [resources page](https://github.com/section-io/engineering-education/blob/master/new_contributors/resources-page.md) to see our helpful guides and tips.

**Comment by hectorkambow** [comment]
@jumapaul  
FYI just saw this PR in our queue - want to make sure that the topics are not overlapping to too similar. 👀 
https://github.com/section-io/engineering-education/pull/1185

**Comment by jumapaul** [comment]
Hello,,what about the article getting started with Matlab loop are they merging?

**Comment by jumapaul** [comment]
> @jumapaul
> FYI just saw this PR in our queue - want to make sure that the topics are not overlapping to too similar. 👀
> #1185

Hey what about the article getting started with Matlab,,are they merging

**Comment by jumapaul** [comment]
> @jumapaul
> FYI just saw this PR in our queue - want to make sure that the topics are not overlapping to too similar. 👀
> #1000 
Sorry,,I mean are they overlapping?

**Comment by ninjaginja** [comment]
closing due to redundancy
