### ISSUE TITLE
Introduction to Distributed Systems

### ISSUE THREAD

**Issue by OMONDIELLY** [section-engineering-education/engineering-education#1401]
### Brief Summary: 
A distributed system is a set of independent computer components or software programs linked together by a network that performs actions or coordinates activities to appear to users as a single coherent system when providing services.
In this article, I'll cover the basics of Distributed Systems.

### Key Takeaways: 
1. What is a distributed system(distributed systems).
2. Distributed system architectures.
3. Building distributed systems/ how distributed systems work.
4. Application areas of distributed systems.

### References: 
N/A

**Comment by hectorkambow** [comment]
@OMONDIELLY 
Seems like a nice topic but sounds like a topic that may be heavily covered elsewhere.
Could you please elaborate a bit on how this topic would differ from what we can find out in other articles.
