### ISSUE TITLE
Regularization to Prevent Overfitting

### ISSUE THREAD

**Issue by collins-a** [section-engineering-education/engineering-education#1403]
### Brief Summary: 

Overfitting impacts the accuracy of machine learning models. The model attempts to capture data points that do not represent the accurate properties of data. These data points may be considered as noise. To avoid the occurrence of overfitting, we may use a technique known as regularization. In this article, we introduce and mathematically explore two types of regularization.

### Key Takeaways: 

Reader should:

1. Have a general understanding of regularization and overfitting
2. Learn how L1 Regularization (Lasso Regression) works and how it is derived from a linear regression equation.
3. Learn how L2 Regularization (Ridge Regression) is derived as well as how it works.

### References: 

The Elements of Statistical Learning https://www.springer.com/gp/book/9780387848570

https://towardsdatascience.com/regularization-in-machine-learning-76441ddcf99a

https://www.geeksforgeeks.org/regularization-in-machine-learning/

https://analyticsindiamag.com/regularization-in-machine-learning-a-detailed-guide/

https://www.javatpoint.com/regularization-in-machine-learning#:~:text=Regularization%20is%20one%20of%20the%20most%20important%20concepts,does%20not%20perform%20well%20with%20the%20test%20data.

https://codeburst.io/what-is-regularization-in-machine-learning-aed5a1c36590

https://www.educba.com/regularization-machine-learning/

https://datascience.eu/machine-learning/regularization-in-machine-learning/

**Comment by hectorkambow** [comment]
Sounds like a great topic to share with the community - please make sure there is no topic overlap with past [published articles ](https://www.section.io/engineering-education/search/)and current upcoming articles in the[ PR queue](https://github.com/section-io/engineering-education/pulls). 
Approved - @collins-a 

Be sure to consult our [resources page](https://github.com/section-io/engineering-education/blob/master/new_contributors/resources-page.md) to see our helpful guides and tips.
