### ISSUE TITLE
Getting started with Preference DataStore in Kotlin

### ISSUE THREAD

**Issue by carolinemusyoka** [section-engineering-education/engineering-education#1404]
### Brief Summary: 
A lot of developers have used SharedPreferences at one point of their development process to store key-value pairs. But there was just something about it. Such as manually needing to switch to a background thread, not being safe from runtime exception and signal errors  like IOException.  Jetpack DataStore works pretty much the same but offers more capabilities. 

### Key Takeaways: 
- Understanding what is DataStore and why you should use it.
- A brief description of the different types of DataStore and how they work.
- Working with Preference DataStore.

### References: 
N/A

**Comment by hectorkambow** [comment]
Sounds like a great topic to share with the community - please make sure there is no topic overlap with past [published articles ](https://www.section.io/engineering-education/search/)and current upcoming articles in the[ PR queue](https://github.com/section-io/engineering-education/pulls). 

Approved - @carolinemusyoka 

Be sure to consult our [resources page](https://github.com/section-io/engineering-education/blob/master/new_contributors/resources-page.md) to see our helpful guides and tips.
