### ISSUE TITLE
Breaking Down Kubernetes vs Docker Swarm 

### ISSUE THREAD

**Issue by EKahuha** [section-engineering-education/engineering-education#1405]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

When it comes to container technologies, two names emerge as open source leaders: Kubernetes and Docker. A lot of people want to know which option is better. In this article, we’ll explore the fundamentals of Docker and Kubernetes, how the two work together and take a look at their similarities and differences. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

What is Kubernetes?
What is Docker Swarm? 
Kubernetes vs. Docker Swarm: Similarities and Differences 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
@EKahuha, it's really important to call out the distinction between Docker Swarm and Kubernetes (vs. comparing Docker and Kubernetes). Kubernetes can orchestrate Docker containers, so it wouldn't be accurate to call out a comparison of Kubernetes vs. Docker.

This is a good topic, assuming you are clear on the direction that it should take.

**Comment by EKahuha** [comment]
@ninjaginja I have noted your point.
