### ISSUE TITLE
How to make a web page with a custom scrollbar using CSS

### ISSUE THREAD

**Issue by ReactifyStudio** [section-engineering-education/engineering-education#1408]
### Brief Summary: 
Most web pages need styling. Cascading Style Sheets is a style sheet language used for describing the presentation of a document written in a markup language such as HTML. In this tutorial, I will build a simple web page with a custom scrollbar.

### Key Takeaways: 
1. How to use the CSS scrollbar pseudo-element
2. How to build a web page with a customized scrollbar
3. Styling application and using HTML
### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @ReactifyStudio - approved. (Note, I'd suggest incorporating 'CSS' into the title since that is the intended method you plan to use.)

**Comment by ninjaginja** [comment]
@ReactifyStudio did you decide not to move forward with this article? I see that you closed the PR.

**Comment by ReactifyStudio** [comment]
It's complete but because it was initially a draft, I was advised by
zolomohan to close it first. I have helped my friend with my PC to complete
an attachment project. I'm on a mobile device. Let me reopen it and push
the code once the pc is back. Definitely willing to do it

**Comment by ReactifyStudio** [comment]
I won't be submitting drafts anymore. I had initially decided to be working
on chunks code updates but I will switch to first completing the articles
before making a PR. Much better

**Comment by ReactifyStudio** [comment]
I have pinged him for updates but didn't add the final commit from my
external file.

**Comment by ReactifyStudio** [comment]
Check it out

**Comment by ReactifyStudio** [comment]
@ninjaginja replied via em
