### ISSUE TITLE
Introducing the Page Visibility API by building a video playback controls website

### ISSUE THREAD

**Issue by ReactifyStudio** [section-engineering-education/engineering-education#1409]
### Brief Summary: 
The Page Visibility API provides events you can watch for to know when a document becomes visible or hidden, as well as features to look at the current visibility state of the page. This tutorial aims at showing how we can detect an active browser tab and do certain actions depending on whether the tab is active. This tutorial will check for visibility of the document and determine whether to play a video or not.

### Key Takeaways: 
1. Introduction to web visibility API
2. Introduction to video tags in HTML media
3. How to check for browser visibility
### References: 
N/A

**Comment by ReactifyStudio** [comment]
@ninjaginja I have proposed two topics and I am confident that they will be complete by today. The work on this is already in progress. Regarding the issues pipeline queue

**Comment by ninjaginja** [comment]
Thank you for the note @ReactifyStudio. This topic is approved, but the phrasing of the article title is a bit awkward. Please refine that when you submit your draft.
