### ISSUE TITLE
Android Nested RecyclerView

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#1411]
### Brief Summary: 
Android studio provides developers with an easy way to implement a recycler view. This guide will discuss and implement a nested recycler view. A nested recycler view is a recycler view inside another recycler view.

### Key Takeaways: 
One of the perfect examples that showcase the nested recycler view is the Google play store. 

![NestedRecyclerView1](https://user-images.githubusercontent.com/36155624/104930015-aa892780-59b5-11eb-8103-d45a4bc5c732.gif)

In this case, the app integrates several recycler views. Nas, a child to one main recycler view.
Each recycler view will then be used to display distinct data. Google PLAY STORE nested recycler view is scrollable horizontally.

Recycler views are diverse, and they and best when it comes to displaying different data into your application. You can modify the view to meet your data representation.
This guide will discuss and implement an application that showcases a nested recycler view 

### References: 
https://developer.android.com/guide/topics/ui/layout/recyclerview

**Comment by ninjaginja** [comment]
good topic @kimkimani - approved.
