### ISSUE TITLE
Introduction to C++ namespace

### ISSUE THREAD

**Issue by Dawe-7** [section-engineering-education/engineering-education#1415]
### Brief Summary: 
A name can represent only one entity in each scope. Thus, in the same scope, there cannot be two variables with the same name as this can generate compiler errors. We may declare two variables or member functions that have the same name in the same scope using namespaces. This causes several functions to have the same name and all functions can be accessed from anywhere in the program by referencing the name of the namespace. This article will go through namespaces and how they are used in C++.

### Key Takeaways: 
1. What is a namespace.
2. Features of namespace.
3. How a namespace works in c++.
4. Declaration of namespace.

### References: 
N/A

**Comment by ninjaginja** [comment]
This topic is approved @Dawe-7. However, we're actively working to get away from topics that are repetitive of information that is already readily available through documentation. We're really looking for original content that applies principles, like this one, to unique challenges/projects. Please keep that in mind as you brainstorm new topics. Thank you.

**Comment by Dawe-7** [comment]
@ninjaginja well noted, thanks.
