### ISSUE TITLE
StyleGAN: A Style-Based Generator Architecture for Generative Adversarial Networks

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#1425]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Despite improvements in image quality synthesis, the generator in Generative Adversarial Networks (GANs) still operates as black boxes. For example, the properties of the latent spaces and the understanding of various aspects of the image synthesis process, e.g., the origin of stochastic features, is still lacking.
The StyleGAN [paper](https://arxiv.org/pdf/1812.04948.pdf) proposed a model for the generator that is inspired by the style transfer networks. It re-designed GANs generator architecture in a way that exposes novel ways to control the image synthesis process. The discriminator model is not modified in any way. 

This article aims to discuss on the StyleGAN architecture, a variant of the Generative Adversarial Network.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

By the end of this article, the reader should be able to understand:

1. What is a Generative Adversarial Network (GAN)?
2. Challenges with GANs
3. An overview of the StyleGAN architecture
4. The Flickr-Faces-HQ (FFHQ) dataset. 
A dataset that offers much higher quality and covers considerably wider variation than existing high-resolution datasets.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

1. [A Style-Based Generator Architecture for Generative Adversarial Networks](https://arxiv.org/pdf/1812.04948.pdf)
2. [Arbitrary Style Transfer in Real-time with Adaptive Instance Normalization](https://arxiv.org/pdf/1703.06868.pdf)

**Comment by ninjaginja** [comment]
good topic @Bayler - approved
