### ISSUE TITLE
Understanding the Basics of Responsive Web Design (RWD)

### ISSUE THREAD

**Issue by mbaabuones** [section-engineering-education/engineering-education#1430]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Many global businesses are building websites to provide a platform for marketing and promoting their products. Building an attractive website only may not be enough. This is because customers require a site that enhances usability and responsiveness. Responsive web design ensures that the website responds well with the customers' devices, which leads to a great user experience. This article provides the basics of this concept in web development. 

### Key Takeaways: 
1. What is responsive web design (RWD)?
2. The building blocks of RWD
3. Why you need a responsive web design
4. How to get started with RWD
5. Examples of responsive web design
6. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
