### ISSUE TITLE
Serving a Machine Learning application with Fast API

### ISSUE THREAD

**Issue by jamessandy** [section-engineering-education/engineering-education#1434]
**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
This article will give readers an introduction of Restful API's, how to build a machine learning project and serve it on Fast API as a Rest API

### Key Takeaways: 

- Brief Intro to RESTful API
- Introduction to Fast API
- Develop a RESTful API
- Build a machine learning model

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @jamessandy - approved

**Comment by ahmadmardeni1** [comment]
I can take this one as well 👀 @hectorkambow

**Comment by hectorkambow** [comment]
@jamessandy 

Just wanted to follow up on this topic suggestion - since new article submission are now open.

**Comment by jamessandy** [comment]
Hello Hector

I’ll send a pr by weekend please.

**Comment by hectorkambow** [comment]
Just closing to make room in the queue - can be resubmitted whenever ready to continue 🚀
