### ISSUE TITLE
How to Choose Levels of Logging 

### ISSUE THREAD

**Issue by EKahuha** [section-engineering-education/engineering-education#1438]
**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Application logging is one of the most important things you can do in your code when facilitating production support. Your log files serve as a sort of archaeological record of what your codebase did in production on earth. Each entry in a log file has essential information, including a timestamp, contextual information, and a message. And most importantly, something called a logging level. This article describes different logging levels.  

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. What is a logging level?
2. Background to logging levels 
3. The most common logging levels (DEBUG, ERROR, FATAL, INFO, etc.) and how to choose them. 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A.')
https://www.tutorialspoint.com/log4j/log4j_logging_levels.htm

**Comment by ninjaginja** [comment]
great topic @EKahuha - approved
