### ISSUE TITLE
React.js Application using DjangoRestFramework

### ISSUE THREAD

**Issue by OkothPius** [section-engineering-education/engineering-education#1441]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
-This article will give readers an overview of intergrating a frontend framework(reactjs) and a backend technology(django) through the use of API(djangorestframework). 
-It has always been a challenge to intergrate two technologies to form a complete application for most beginners and they can learn more through this article.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
-Introduction to django
-Introduction to DjangoRestFramework
-Develop an API with django
-Introduction to React
-Build a Todo application in React and Django

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @OkothPius - approved with a couple notes:

- Please be mindful of grammar. I noticed a couple spelling ('integrate', not 'intergrate') and spacing (missing spaces before opening parentheses) mistakes in your description.
- Please refine the title to be more descriptive of what the reader can expect to learn or be able to do after reading this article (e.g. 'Building a React.js Application Using Django REST framework') - note the spelling of 'Django REST framework' within copy, as referenced on [their documentation](https://www.django-rest-framework.org/)

**Comment by OkothPius** [comment]
Thank you @ninjaginja .

 I will put into play all that you have said.
