### ISSUE TITLE
How to implement motion layout animation in android studio

### ISSUE THREAD

**Issue by WanjaMIKE** [section-engineering-education/engineering-education#1442]
### Brief Summary: 

Motion Layout provides a fun way to add animations in your android application. As compared to other animation techniques, motion layout animation takes less time and code.

### Key Takeaways: 
- Understand what is motion layout
- Know how to implement motion layout.
- Debug 

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @WanjaMIKE - approved
