### ISSUE TITLE
Consuming unsplash api using Node.js Graphql API.

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#1445]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Unsplash is a photo sharing application. It enables one to access and download for free photos that have been uploaded by others regarding any topic. With the unsplash api, you can extend the features of the application to your project. In this article we shall implement the features provided by the unsplash api on a graphql API.

### Key Takeaways: 
- How to create a developer account on unsplash
- How to fetch photos from unsplash to your application using unsplash api.
- How to search for photos from unsplash on your application using unsplash api.

### References: 
https://dev.to/arnavmotwani/the-most-basic-unsplash-api-example-probably-3p67

**Comment by ninjaginja** [comment]
good topic @mwangiKibui - approved
