### ISSUE TITLE
MariaDB vs MySQL

### ISSUE THREAD

**Issue by Ernest715** [section-engineering-education/engineering-education#1448]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

In this topic we’ll take a look at some of the differences between MariaDB and MySQL, two similar yet different database technologies used to power millions of websites around the globe

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1.	An overview of MariaDB.
2.	An overview of MySQL.
3.	Enumerate the key features of both MariaDB and MySQL frameworks.
4.	Enumerate the key differences between the two in back-end technology combination.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
great topic @Ernest715 - approved

**Comment by hectorkambow** [comment]
LAST OLD ONE *NOTE*
