### ISSUE TITLE
Basics of Routing in Computer Networking

### ISSUE THREAD

**Issue by Taiwrash** [section-engineering-education/engineering-education#1454]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Connectivity between networks, both on Local Area Network (LAN) and internet at large, are managed and controlled by the idea of computer networking and **routing** been one of the important component. For this reason, understanding how it works is very important for both the users and developers.

### Key Takeaways: 
- Understand basis of routing process
- Understand IP address and how they work together to provide network access
- How packets (data) moves from one end of a network to another
- Explain the key concepts of routing and networking at large

### References: 
[Routing at WikiPedia](https://en.wikipedia.org/wiki/Routing)

**Comment by rasheedtaiwo** [comment]
## Request
Please can I re-open this issue?
@hectorkambow

**Comment by Taiwrash** [comment]
I don't know why I am not getting responses on this @hectorkambow  @

**Comment by hectorkambow** [comment]
@Taiwrash my apologies for the delayed response - please always reach out via DM in Slack since my Github notifications get lost in my inbox - as I get too many in a day.

**Comment by Taiwrash** [comment]
Alright, thanks so much. Anticipate your review

**Comment by hectorkambow** [comment]
@Taiwrash 
👋  Im confused - does this topic have a PR associated with it??

**Comment by rasheedtaiwo** [comment]
No PR attached yet, waiting for topic review and acceptance before proceeding to making PR. 

Thanks and I am very sorry for confusion created.

**Comment by Taiwrash** [comment]
@hectorkambow 

Thanks

**Comment by hectorkambow** [comment]
@Taiwrash 

Please (always feel free to ping me via a DM on Slack for a faster response). 

Will this article potential overlap with this past article 🤔 

https://www.section.io/engineering-education/network-routing-final/

**Comment by hectorkambow** [comment]
@Taiwrash 

We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by Taiwrash** [comment]
This my article is a bit advance than the one in this link https://www.section.io/engineering-education/network-routing-final/ but mine based on the knowledge taught here, though I was not aware of this when I was writing mine. But it still follow the knowledge gained in the Network routing article.

Thanks

@hectorkambow

**Comment by Taiwrash** [comment]
Why is this closed sir? @hectorkambow

**Comment by hectorkambow** [comment]
@Taiwrash @rasheedtaiwo 

Just pinging you on this topic form - as Im making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

Please create a NEW topic form for the PR if and when the articles is completed. 

Thank you 🚀  
Looking forward to some solid articles.
