### ISSUE TITLE
How to integrate Google Maps to your Android Application - Part One

### ISSUE THREAD

**Issue by bluemutheu** [section-engineering-education/engineering-education#1489]
### Brief Summary: 
Google maps have become a necessity for application development. Most common apps like Airbnb, Uber and so many delivery apps use Google Maps. It is therefore just and reasonable to learn how to implement Google maps on your application from scratch. In this article, we will not use the already provided google maps activity on android studio but create our own in an empty activity. This will help us adjust the application according to our needs.

### Key Takeaways: 
1. How to access fine location permission
2. How to show Google Maps using Support Map Fragment
3. How to show a User's current location.

### References: 
N/A

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the message posted in Slack last week, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
