### ISSUE TITLE
Creating your first web story

### ISSUE THREAD

**Issue by Jethro-magaji** [section-engineering-education/engineering-education#1501]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Web Stories are a web-based version of the popular "Stories" format that blend video, audio, images, animation and text to create a dynamic consumption experience. This visual format lets you explore content at your own pace by tapping through it, or swiping from one piece of content to the next.

### Key Takeaways: 
- Learn how to create web stories using content management system
- Learn what web story is about.
- Learn best practices for web stories

### References: 
https://www.google.com/amp/s/stories.google/
https://developers.google.com/search/docs/guides/enable-web-stories
https://www.google.com/amp/s/blog.google/web-creators/10-web-stories-and-whats-great-about-them/amp/

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion. Per the message posted in Slack last week, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
