### ISSUE TITLE
Connecting library application to SQL Server using Windows forms

### ISSUE THREAD

**Issue by mohamedgh16** [section-engineering-education/engineering-education#1502]
### Brief Summary: 
 _**windows forms**_ is one of the best tools used in making applications. 
 With windows forms, you can make a variety of applications, from a mini calculator to a library application that connects to a database. In this tutorial, we will connect a library application using Windows forms to a database using SQL Server.

### Key Takeaways: 
- Understand the controls used inside of the application.
- Understand the Queries used in SQL Server. 
- Connect the application to the database.

### References: 
 'N/A'.

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the message posted in Slack last week, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
