### ISSUE TITLE
Build an API using Python

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-engineering-education/engineering-education#1503]
### Brief Summary: 
API is the acronym for Application Programming Interface, which is a software intermediary that allows two applications to talk to each other. Each time you use an app like Facebook, send an instant message or check the weather on your phone, you're using an API.

### Key Takeaways: 
In this tutorial, I'm going to build an API using Flask framework, and the reader will learn the following:
- What is an API and why we need it.
- How to build an API using Flask.
- Test it by using Postman to make requests (GET, POST, PUT, DELETE).

### References: 
N/A

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the message posted in Slack last week, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
