### ISSUE TITLE
Getting Started with PyTorch

### ISSUE THREAD

**Issue by nicholaskross** [section-engineering-education/engineering-education#1504]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
PyTorch is a fast-growing library for machine learning. It's especially common in research, being used by OpenAI and academic researchers alike. In this tutorial, we will setup PyTorch and use it to classify images of handwritten numbers.

### Key Takeaways: 
- Install PyTorch (the tutorial would be on Windows)
- Download image data to integrate with PyTorch (we'll use the KMNIST dataset)
- Learn the basic concepts of PyTorch (tensors, neural network models)
- Build an image classifier neutral network model

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
- https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html
- https://pytorch.org/get-started/locally/
- https://visualstudiomagazine.com/articles/2020/06/08/getting-started-pytorch.aspx
- https://pytorch.org/docs/stable/torchvision/datasets.html#kmnist
- https://github.com/rois-codh/kmnist

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the message posted in Slack last week, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
