### ISSUE TITLE
Downloading Large Files on Windows with wget

### ISSUE THREAD

**Issue by nicholaskross** [section-engineering-education/engineering-education#1505]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Whether it's downloading datasets for machine learning, or simply backing up personal data, we work with larger files than ever. A popular tool for Linux, `wget`, makes it easy and fast to download these large files. As it turns out, we can use this on Windows as well. In this tutorial, you will learn how to get `wget` running on Windows, start and pause downloads, and customize our download to our liking.

### Key Takeaways: 
- Install `wget` on Windows
- Download files from the internet
- Pause and resume downloads (without starting them over again)
- Customize `wget` runs to see more information

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
- https://the-eye.eu/public/Wget_Windows_Guide.pdf
- https://techstop.github.io/pause-and-resume-wget-downloads/
- http://gnuwin32.sourceforge.net/packages/wget.htm

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the message posted in Slack last week, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
