### ISSUE TITLE
Understanding Recursions in Ruby

### ISSUE THREAD

**Issue by ianmaish** [section-engineering-education/engineering-education#1508]
### Brief Summary: 
Ruby is an interpreted, high-level, general-purpose programming language.  Recursion is a method of solving a problem where the solution depends on solutions to smaller instances of the same problem. Such problems can generally be solved by iteration, but this needs to identify and index the smaller instances at programming time. This article will explain recursion using the Ruby programming language.

### Key Takeaways: 
1. Understanding recursion in programming
2. How to implement recursion in Ruby
3. Best practices to using recursion in Ruby

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion. Per the recent message posted in Slack, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
