### ISSUE TITLE
Building a documentation website with MkDocs and the material theme

### ISSUE THREAD

**Issue by Quadrisheriff** [section-engineering-education/engineering-education#1510]
In the tutorial, the reader will learn how to build a documentation website with MkDocs and the material theme. 

MkDocs is a python based static site generator for creating beautiful and responsive websites. The Material for MkDocs theme is a MkDocs theme that is based on the material design.

The reader will learn how to :
- Set up a documentation website with mkdocs and the material theme.
- Edit the theme by adding an extra.css file and javascript files.
- Add a lightbox implementation to mkdocs.
- Deploy website with GitHub pages and automate deployment with github actions

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion. Per the recent message posted in Slack, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
