### ISSUE TITLE
Building a portfolio website with 11ty and Tailwind CSS

### ISSUE THREAD

**Issue by Quadrisheriff** [section-engineering-education/engineering-education#1511]
In this guide, the reader will learn how to set up a portfolio website with 11ty and customize the website with tailwind CSS.

11ty is a simple static site generator that works with different templating engines like Nunjucks, liquid, pug, etc. Tailwind CSS is a CSS framework used for creating user interfaces.

The reader will learn how to:

- Set up a website with 11ty.
- Add tailwind CSS to the 11ty website.
- Customise the website with css.
- Deploy the final website with gh-pages.

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion. Per the recent message posted in Slack, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
