### ISSUE TITLE
Understanding loops in C++.

### ISSUE THREAD

**Issue by Mwars56** [section-engineering-education/engineering-education#1512]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Programming might become difficult when learning on your own. In this tutorial, I will try to make it easy for a programmer to understand everything using simple examples. This tutorial good for everyone either being a beginner or a programmer by ensuring a quick understanding.

### Key Takeaways: 
 Important things the reader should understand or be able to do after reading this article?
1. Get to know and use for loops.
2. Understand while loops and do-while loops.
3. Differentiate between while and do-while loops.
4. Be able to write programs of loops.
### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion. Per the recent message posted in Slack, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
