### ISSUE TITLE
Using AWS Node.js SDK to implement s3 functionalities on a GraphQL API.

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#1516]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
AWS is a subsidiary of amazon offering cloud computing services revolving around application, infrastructure and storage. Node.js SDK from AWS brings the services offered by S3 to a Node.js application. s3 is the storage service provided by AWS. Its functionalities revolves around creating buckets, uploading files to the buckets, reading the files from the buckets and deleting the files and buckets. In this article, we shall implement all this functionalities to a GraphQl API using AWS Node.js SDK. 

### Key Takeaways: 
- Understand how to create a bucket in s3 using AWS Node.js SDK.
- Understand how to upload files to a bucket in s3 using AWS Node.js SDK.
- Understand how to fetch files from a bucket in s3 using AWS Node.js SDK.
- Understand how to delete files from a bucket in s3 using AWS Node.js SDK.
- Understand  how to delete a bucket in s3 using AWS Node.js SDK.

### References: 
- https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/getting-started-nodejs.html

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in Slack, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
