### ISSUE TITLE
How to build a documentation website with Docusaurus version 2, Facebook's open source project.

### ISSUE THREAD

**Issue by calebroHQ** [section-engineering-education/engineering-education#1518]
### Brief Summary: 
INTRODUCTION
Are you just starting your new project and not sure how to go about the documentation? Well, the Facebook open source community has something for you, Docusaurus or rather Docusaurus version 2 to be specific. This is a documentation site generator build in React.js with simplicity and ease of use in mind. With SEO friendly pages, Document versioning, and full search features this tool will be of great help to you so that you can focus more on your project.

PREREQUISITES
 Node.js version >= 10.15.1 or above installed
 
 Yarn version >= 1.5 installed
 
GETTING STARTED
The most convenient way of installing Docusaurus is to use a command-line tool. You can run this command anywhere in a new empty directory or existing directory. It will create a new directory containing the scaffolded files.

### Key Takeaways: 
1.Getting started with Docusaurus
2..Configuring your documentation site
3.Deploying your documentation site

### References: 
https://v2.docusaurus.io/docs/

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in Slack, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
