### ISSUE TITLE
 Build GIF search using Vue  3 

### ISSUE THREAD

**Issue by Worawat101** [section-engineering-education/engineering-education#1519]
**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
The main goal of this tutorial is to showcase the search mechanism used to search the GIFs from the GIPHY API. For GIPHY API, we will be creating an account of GIPHY and registering an app to get the API key. There will also be the showcase of JavaScript debouncing for the search input. We are going to use the Vue version 3 ecosystem fragment components for this tutorial project.

### Key Takeaways: 
1. Learning Vue 3 ecosystem.
2. JavaScript debouncing for search Input.
3. Configure GiPHY account and app to get GiPHY API.
4. Fetch GIFs from GiPHY API.

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in Slack, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
