### ISSUE TITLE
Exploring Plots for Effective Data Visualization

### ISSUE THREAD

**Issue by bloodprashure** [section-engineering-education/engineering-education#1521]
### Brief Summary: 
Data Visualization has often been overlooked in the realm of data science jobs. Finally getting its recognition, the need to understand various charts and plots is imperative to succeed in the field. This article provides a dive into the various (common and not-so-common) plots and charts used in data visualization.

### Key Takeaways: 
1. Understand the importance of data visualization in the current market
2. To make a choice on how to represent data that is easy to interpret
3. Types of plots

### References: 
N/A

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in Slack, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
