### ISSUE TITLE
How to create CRUD API with FastAPI. 

### ISSUE THREAD

**Issue by atoyegbe** [section-engineering-education/engineering-education#1522]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
[FastAPI](https://fastapi.tiangolo.com/) is a modern, fast (high-performance), a web framework for building APIs with Python 3.6+ based on standard Python type hints. FastAPI is a Python framework and set of tools that enable developers to use a REST interface to call commonly used functions to implement applications. In this tutorial, i will be creating a simple API using FastAPI. This article aims to teach the reader how to create various CRUD APIs using FastAPI.
### Key Takeaways: 
Basic Python knowledge is required to understand the concept covered in this article.

1. What is FastAPI.
2. Why FastAPI?.
3. How to create CRUD API using FastAPI.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in Slack, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
