### ISSUE TITLE
Basic introduction to node.js for beginners

### ISSUE THREAD

**Issue by sheenanicole** [section-engineering-education/engineering-education#1523]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

For first time users of github and people with interest in coding, this article will give a basic understanding on what node.js is and how the user can incorporate it in their day to day coding life. The article will give a beginner friendly guide to the user in simple terms so that they are able to navigate the platform with ease and also write their own articles after acquiring basic knowledge on node.js and java script. It will accomplish this through explaining what node.js is, its components, why it is popular, how it can be used and the prerequisites of learning it.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

The reader should understand; what node.js is, its components, its relation to java script, how it can be used and why you would opt for it
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in Slack, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
