### ISSUE TITLE
Getting Started With Python Virtual Environments 

### ISSUE THREAD

**Issue by FREDERICO23** [section-engineering-education/engineering-education#1524]
### Brief Summary:

Python virtual environment is an isolated environment for Python projects that solves different project management dependencies. In this article, we shall be talking about the different virtual environments that Python provides, their pros and cons.

### Key Takeaways: 

1. Understanding of Python virtual environments
2. Different types of virtual environments in Python
3. Using virtual environments

### References: 

N/A

**Comment by hectorkambow** [comment]
👋  @FREDERICO23 
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
