### ISSUE TITLE
Building API's with Django and GraphQL

### ISSUE THREAD

**Issue by atoyegbe** [section-engineering-education/engineering-education#1525]
**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
GraphQL is an open-source data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data. GraphQL used on the frontend and backend. In this tutorial, I will be creating a Web API in GraphQL using Graphene-Python, Graphene-Python is a library for building GraphQL APIs in Python easily.

### Key Takeaways: 
1 - What is GraphQL.
2 - Integrating GraphQL in Django.
3 - Build a Simple Note API using GraphQL.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in Slack, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
