### ISSUE TITLE
Radio Frequency Identification Technology

### ISSUE THREAD

**Issue by OkothPius** [section-engineering-education/engineering-education#1526]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 

Radio frequency identification (RFID) is a technology that uses communication via radio waves to exchange data between a reader and an electronic tag attached to an object, for the purpose of identification and tracking.
RFID has gained more popularity because of its applications.

### Key Takeaways: 

1 - What is Radio Frequency Identification Technology
2 -  Components of Radio Frequency Identification Technology
3 - Applications of Radio Frequency Identification Technology
4 - Advantages and Disadvantages of Radio Frequency Identification Technology

### References: 

Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
