### ISSUE TITLE
Understanding the OSI model for Software Engineers

### ISSUE THREAD

**Issue by Njunu-sk** [section-engineering-education/engineering-education#1527]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Every developer should be able to understand some concepts of networking, how a request is sent from client to server and response back to the client, This article will give a friendly approach to understanding OSI model from a software engineer point of view. The article will accomplish this by bisecting the OSI model.

### Key Takeaways: 
Basic understanding of the encapsulation and de-encapsulation process in networking.
Understand the OSI model and its role in development.
Understand basic terms in networking

### References: 
https://afteracademy.com/blog/what-is-data-encapsulation-and-de-encapsulation-in-networking
https://www.freecodecamp.org/news/osi-model-networking-layers-explained-in-plain-english/

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
