### ISSUE TITLE
Web design mistakes that are unfriendly to SEO and how to avoid them

### ISSUE THREAD

**Issue by wobin1** [section-engineering-education/engineering-education#1530]
**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
SEO stands for “search engine optimization.”It is the process of improving your site to increase its visibility for relevant searches, the more visible a website is the more likely it's going to gain attention and attract prospective and existing customers to your business.

### Key Takeaways: 
1. A knowledge of Design Mistakes that are not SEO Friendly.
2. Learn how to avoid them.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
