### ISSUE TITLE
How to create a Virtual Assistant using Alexa with Python

### ISSUE THREAD

**Issue by CodeLeom** [section-engineering-education/engineering-education#1535]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
A virtual assistant, also called an AI assistant or digital assistant, is an application program that understands natural language voice commands and completes tasks for the user. This article will be using a python library that will integrate Alexa and will help you build your own Voice Assistant.

### Key Takeaways: 
You will learn what an AI assistant is
You will create your own working voice assistant using Python

### References: 
N/A

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
