### ISSUE TITLE
Overview of Cloud Computing

### ISSUE THREAD

**Issue by CodeLeom** [section-engineering-education/engineering-education#1536]
**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
The distribution of various services via the Internet is cloud computing. Tools and applications like data storage, servers, databases, networking, and apps are included in these tools. It has access to the data and the software programs to run it as long as an electronic computer has access to the internet.

### Key Takeaways: 
In this article, I will cover all aspects of cloud computing, you will also learn the following:
Why is cloud computing typically cheaper to use?
Why should you move to the cloud?
What are some cloud computing advantages?
What are cloud service models and Serverless computing?

### References: 
Google Cloud Platform, Amazon Web Service, and Microsoft Azure

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
