### ISSUE TITLE
How To Build a Progress Bar On Page Scroll

### ISSUE THREAD

**Issue by Larry-Mason** [section-engineering-education/engineering-education#1537]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Building engaging user interfaces requires writing semantic CSS. One way to build such an engaging UI is via page scroll. In this article, we will cover how we can implement a scroll bar to show the scroll page position using CSS and JavaScript,

### Key Takeaways: 
1. Scaffolding HTML and CSS web page
2. Using CSS for styling
3. Implementing JavaScript to showcase progress bar in a webpage

### References: 
N/A

**Comment by hectorkambow** [comment]
👋  
@Larry-Mason 
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.

**Comment by Larry-Mason** [comment]
Was closed before I could write a single article. When should I expect
this?
