### ISSUE TITLE
Difference between digital currency and cryptocurrency

### ISSUE THREAD

**Issue by molly80** [section-engineering-education/engineering-education#1540]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
People often confuse digital currency and cryptocurrency. This article aims at educating readers on the differences that exists between cryptocurrency and digital currency

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Cryptocurrency overview
Digital currency overview
Differences between cryptocurrency and digital currency
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by hectorkambow** [comment]
👋 
@molly80 
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
