### ISSUE TITLE
Digital currency- overview, types, how it works, advantages and disadvantages, risks

### ISSUE THREAD

**Issue by molly80** [section-engineering-education/engineering-education#1542]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

This articles aims to educate investors about digital currency. How digital currency works . The types that exists, possible risks, advantages and disadvantages.

 ## Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

An overview about digital currency
Different types of digital currency
How digital currency work
Risks involved
Advantages and disadvantages of digital currency
## References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by hectorkambow** [comment]
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
