### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by EKahuha** [section-engineering-education/engineering-education#1545]
**Is your feature suggestion related to a current problem or issue? Please describe.**
A clear and concise description of what the problem is. Ex. I''ve found it difficult when [...]

1. Sometimes, reviewers are taking weeks to review an assigned article. 
2. Writers are taking too long to make changes to their articles (as suggested by reviewers).  

**Describe the solution you'd like to implement to the program**

1. Reviewers to be allowed a maximum of one week to provide feedback after assigning an article. This will ensure that reviewers only assign themselves the workload they're able to handle comfortably within a short time. 
2. Writers to be allowed a maximum of three days to complete revisions. 

**Describe alternatives you've considered or seen**

**Additional context on how you could go about building this**

**Comment by hectorkambow** [comment]
Thank you for sharing @EKahuha  
Great insight!!
