### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#1546]
**Is your feature suggestion related to a current problem or issue? Please describe.**
A clear and concise description of what the problem is. Ex. I''ve found it difficult when [...]

**Describe the solution you'd like to implement to the program**

**Describe alternatives you've considered or seen**

**Additional context on how you could go about building this**

I've noticed the article backlogs due to the increased submissions by new authors. This has led to the issue submissions being put on hold. I had a suggestion that I think will help streamline the process. 
Just like companies like Upwork did earlier on, how about the company pauses the admission of new authors, let's say, for 3 months so that the process can be streamlined. That'll be better than pausing issuing of new articles going forward.

**Comment by hectorkambow** [comment]
@Bayler  Thank you v much for the thoughts and suggestions - we will take it into consideration 🚀 
👍 

That would be another way to handle a backlog - hoping we do not pause again.
