### ISSUE TITLE
Comment and Likes feature

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#1547]
**Is your feature suggestion related to a current problem or issue? Please describe.**
At this moment most of the students do not follow up on an article once it is already published. Introducing the comments and the likes feature will make it necessary for the student to follow up. It is also make the student to share the article across the various social platforms. 

**Describe the solution you'd like to implement to the program**
The comments and likes feature. When a reader finishes going through the article, the reader can leave a comment in the comments section. The student who is responsible for that article will be notified and he or she can respond to the comment. Likes will just be a matter of clicking a thumbs up icon.

**Describe alternatives you've considered or seen**
The rating feature. After the reader goes through the article, there is a question like was this article helpful. If yes the reader can rate from 0 to 5. If no the student responsible for the article will be notified.

**Additional context on how you could go about building this**
For every article have an array of comments and likes starting at zero. If a reader comments, the comment is added and the student responsible for the article is notified by email. If the reader likes, then the article likes are incremented.

**Comment by ahmadmardeni1** [comment]
I agree with you one adding the likes feature 🚀 Maybe a heart instead ❤️

**Comment by hectorkambow** [comment]
@mwangiKibui  Thank you v much for the suggestion 🚀

**Comment by mwangiKibui** [comment]
You are welcome @hectorkambow
