### ISSUE TITLE
Testing Express APIs with Jest and Supertest

### ISSUE THREAD

**Issue by vicradon** [section-engineering-education/engineering-education#1552]
- Title: Testing Express APIs with Jest and Supertest
- Introduction: API testing is a core requirement in modern software development. When building APIs using Express, A combination of two libraries can be used for testing: Jest and Supertest. Jest acts as the test runner and assertion library while Supertest acts as the API client.
-  Goals: Learn about API testing by testing a microservice written in Express.
- Prerequisites: Knowledge of NodeJS and ExpressJS. 
- Step 1: Install Jest and Supertest
- Step 2: Writing tests for each endpoint
- Step 3: Debugging and running tests
- Best practices for working with test databases
- Conclusion

**Comment by vicradon** [comment]
Hi @ninjaginja 

Any updates on this issue?

**Comment by hectorkambow** [comment]
@vicradon  
(apologies for the delayed response - we were meeting about articles submissions.)
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.

**Comment by vicradon** [comment]
Hi @hectorkambow 
Can this issue be reopened?
