### ISSUE TITLE
How to send SMS in Django with Twillio

### ISSUE THREAD

**Issue by shosenwales** [section-engineering-education/engineering-education#1553]
### Brief Summary: 
How to send SMS in Django using Twillio. This can be used to send otp's in a project

### Key Takeaways: 
1. Learn about Twillio
2. How to send/recieve messages in a Django project
3. How to use twillio with django

### References: 
 N/A

**Comment by hectorkambow** [comment]
@shosenwales 
(apologies for the delayed response - we were meeting about articles submissions re-opening soon as our program is under a process of being streamlined.)
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
