### ISSUE TITLE
Using the Google Play Developer Console

### ISSUE THREAD

**Issue by ChristineWasike** [section-engineering-education/engineering-education#1554]
**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
In this article, I intend on drawing the readers attention to the Google Developer Console. This article is a part two of the Deploying your Android Application to Google Play Store. This article will walk through how to use the information we gathered to learn how it feeds into Google Play Console. The necessary prerequisites are an account on Google Play console, Android Studio and an Android application. This builds on my previous article on [Deploying an Android App To Play Store](https://www.section.io/engineering-education/deploying-your-android-app-to-google-play-store/)

### Key Takeaways: 
At the end of this article, te readers should be able to:
- Understand the regulations and necessary procedures Google has in place when deploying applications to play store
- Navigate through the Google Play Console with ease
- Set up their application on play store and have it run live

### References: 
- [Google Play Support](https://support.google.com/googleplay/android-developer/answer/6112435?hl=en)
- [Android Developers](https://developer.android.com/distribute/console)

**Comment by hectorkambow** [comment]
@ChristineWasike 
(apologies for the delayed response - we were meeting about articles submissions re-opening, as our program is under a process of being streamlined.)
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
