### ISSUE TITLE
Setting up your AI Environment on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ChristineWasike** [section-engineering-education/engineering-education#1555]
**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Through this article, I hope to shed light on some of the fundamental steps and approaches I learnt about and implemented after setting up my AI environment. This process was complicated because I had no prior knowledge of how to effectively go about the online documentation and journals to help have a functional environment. But now that I successfully have my AI environment set up, I would like to pass on this information as succinctly as possible.

### Key Takeaways: 
By the end of this article, the reader should be able to:
- Install the anaconda tool on their computer
- Understand the role of Python in setting up an AI environment
- Run a basic local AI project setup using JupyerNotebook

### References: 
[Anaconda Documentations](https://docs.anaconda.com/anaconda/user-guide/getting-started/)
[Tensorflow installation procedure](https://www.tensorflow.org/install)
[Jupyter notebook journal](https://arxiv.org/pdf/1804.05492)

**Comment by hectorkambow** [comment]
@ChristineWasike 
(apologies for the delayed response - we were meeting about articles submissions re-opening, as our program is under a process of being streamlined.)
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.

**Comment by ChristineWasike** [comment]
Hello @hectorkambow 
When is it possible to reopen this issue?
Please let me know at your earliest convinience
