### ISSUE TITLE
Getting started with Quasar Framework

### ISSUE THREAD

**Issue by EspiraMarvin** [section-engineering-education/engineering-education#1556]
Quasar framework is Vue js framework used to created cross-platform applications using one code base saving development costs. It offers state of art UI, support builds for SPA, PWA, SSR, Mobile Apps (IOS and Android), Desktop app, and Browser Extensions. 

### Key Takeaways: 
By the end of the article the student should be able to:
1.	Create a simple quasar project with Quasar CLI
2.	Build a SPA (single page application)
3.	Build a PWA (progressive web app).
4.	Build a desktop app (electron)

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by hectorkambow** [comment]
@EspiraMarvin 👋 
(apologies for the delayed response - we were meeting about articles submissions re-opening, as our program is under a process of being streamlined.)
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
