### ISSUE TITLE
Dunder/Magic Methods in Python

### ISSUE THREAD

**Issue by rahulbanerjee26** [section-engineering-education/engineering-education#1558]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
The article will talk about dunder methods like __init__, __len__, __getitem__ etc. Various example functions and classes will be discussed

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- Reader will understand dunder/magic methods
- Reader will know about common dunder/magic methods
- Reader will be able to create their own classes with dunder methods

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by hectorkambow** [comment]
@rahulbanerjee26 
(apologies for the delayed response - we were meeting about articles submissions re-opening, as our program is under a process of being streamlined.)
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
