### ISSUE TITLE
Logical network segmentation

### ISSUE THREAD

**Issue by josep562** [section-engineering-education/engineering-education#1565]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by josep562** [comment]
1.An overview of what is segmentation in networking.
2.Reasons for network segmentation.
3.The two major types of network segmentation.
4.In depth understanding of what is logical network segmentation.
5.Examples of cases when to use logical network segmentation.

**Comment by hectorkambow** [comment]
👋   
@josep562  
(apologies for the delayed response - we were meeting about articles submissions re-opening, as our program is under a process of being streamlined.)
Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
