### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by pkalynan** [section-engineering-education/engineering-education#1567]
**Is your feature suggestion related to a current problem or issue? Please describe.**
A clear and concise description of what the problem is. Ex. I''ve found it difficult when [...]

I've automatically assumed Peer Reviewers work from a first-come-first-serve basis and this might place some stress and strain on them and student contributors regarding time and energy.

**Describe the solution you'd like to implement to the program**

Place categories and time constraints to organize content suggestions to effectively and efficiently work through.

Categorizing issues by subject and possible subcategories may eliminate time issues. Examples include: application creation, tips on completing a task, programming language, or installations. 

Additionally, limiting number of issues per timeframe may help. For example, number of issues per timeframe of choice (37 issues per week).

**Describe alternatives you've considered or seen**

Allow incoming issues, although a message in the text box to add new content ideas warning there will not be any approvals or declines. Paused yet allowing new idea suggestions to continue a first-come-first-serve themed structure.

**Additional context on how you could go about building this**

To select categories:
Drop-down menus
Radio buttons
Separate text boxes

Timeframe:
Timer
Timeout (for new issues)

**Comment by hectorkambow** [comment]
@pkalynan  
Thank you v much for the thoughts and suggestions we are going through them all to see if there is any overlap.
