### ISSUE TITLE
Animation in CSS

### ISSUE THREAD

**Issue by prince-joel** [section-engineering-education/engineering-education#1569]
### Brief Summary: 
This article will introduce the readers to animations in CSS and frankly walk the reader through the properties of animation and how they can be used.

### Key Takeaways: 
- The reader would learn about animation in CSS.
- The reader would learn about  the different properties of animation.
- The reader would learn how to use the properties of animation.

### References: 
N/A

**Comment by hectorkambow** [comment]
👋
@prince-joel 

(Good afternoon and thank you for your article submission to the EngEd program - we are meeting as our program is under a process of being streamlined.)

Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
