### ISSUE TITLE
Implementing Rate Limiting in Flask APIs

### ISSUE THREAD

**Issue by LordGhostX** [section-engineering-education/engineering-education#1571]
**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Rate limiting is a strategy for limiting network traffic. It puts a cap on how often someone can repeat an action within a certain timeframe. In this article, we will be going over what rate limiting is, the advantages of limiting request rates, and explore implementing rate-limiting in Flask APIs.

### Key Takeaways:
By the end of this tutorial, the reader will be able to:
* define what rate limiting is
* understand the importance of limiting request rates in APIs
* build Flask APIs that limit the rate of requests received

### References:
N/A

**Comment by hectorkambow** [comment]
👋
@LordGhostX 
(Good afternoon and thank you for your article submission to the EngEd program - we are meeting as our program is under a process of being streamlined.)

Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
