### ISSUE TITLE
One issue, one pull request.

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#1573]
**Is your feature suggestion related to a current problem or issue? Please describe.**
I've found that it is difficult to follow through pull requests submitted and not yet closed.

**Describe the solution you'd like to implement to the program**
If each issue is connected to a certain pull request. No other issue or pull request should be submitted until that pull request is closed. Peer reviewers should also not be allowed to review another article until one has finished the current article.

**Describe alternatives you've considered or seen**
A maximum of two pull requests for a student and a pull reviewer.

**Additional context on how you could go about building this**
If a student's pull request is not yet closed any other pull request submitted should be labelled pending review. A peer reviewer who takes on another article before completing an initial one is communicated to and reminded of the guideline.

**Comment by hectorkambow** [comment]
👍  Great suggestion! 

Thank you v much @mwangiKibui

**Comment by mwangiKibui** [comment]
You are welcome @hectorkambow
