### ISSUE TITLE
Import Spatial Data to PostgreSQL

### ISSUE THREAD

**Issue by iank-m** [section-engineering-education/engineering-education#1576]
### Brief Summary: 
This article will give readers a detailed manner in which they can setup a spatial database and load the database with spatial data. The database I will be using is postgreSQL and I will be using Qgis to load it with spatial data. 
 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. How to setup postgreSQL and enable postgis.
2. How to load qgis with spatial data.
3. How to import the spatial data to postgreSQL.
4. How to view the data in pgAdmin4

### References: 
N/A

**Comment by hectorkambow** [comment]
@iank-m 
@LordGhostX
(Good afternoon and thank you for your article submission to the EngEd program -  our program is under a process of being streamlined.)

Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.

**Comment by iank-m** [comment]
Good afternoon, are you accepting new articles yet?
