### ISSUE TITLE
Introduction To Design Pattern: Strategy Pattern

### ISSUE THREAD

**Issue by corpsgeek** [section-engineering-education/engineering-education#1589]
### Proposed title of article
Introduction To Design Pattern: Strategy Pattern

### Introduction paragraph(s):
Design patterns are different well though and designed solutions that apply to a lot of recurring problems in software engineering. This article aims to cover the Strategy design pattern and the benefits. 

### Key takeaways: 
- Benefits of design pattern
- Object-Oriented Principles
- Strategy pattern and pseudocode samples of its implementation
- 
### References: 
N/A

**Comment by hectorkambow** [comment]
@corpsgeek 👋  
(Good afternoon and thank you for your article submission to the EngEd program - our program is under a process of being streamlined.)

Thank you for your topic suggestion. Per the recent message posted in our EngEd Slack channel, we are getting ready to accept new articles on the 15th. We were working through a backlog of submitted drafts.
Please be sure to check the EngEd slack community channel for more updates.
Thank you for your patience.
