### ISSUE TITLE
What's new in Flutter

### ISSUE THREAD

**Issue by HeatherMataruse** [section-engineering-education/engineering-education#1601]
-The article will highlight what are the new technologies in flutter for example  new animations 
-This will also give an introduction to flutter to someone who has not  made flutter applications
-Advantages and disadvantages of using flutter 
-ide used to run flutter applications
-resources to get started with flutter

**Comment by hectorkambow** [comment]
@HeatherMataruse  👋 Please be sure to use the form to start writing the intro paragraphs. Use the template to start organizing your thoughts. 

We just re-opened our article suggestion form today - but we need to have a fledge out article structure to review and approve. 👍 

Thank you.

**Comment by ninjaginja** [comment]
Ah, I see that Hector already commented on this that we require all topic suggestions follow our new form flow. We'll look out for a new issue whenever you're ready to resubmit.
