### ISSUE TITLE
Working with lambda functions in Kotlin

### ISSUE THREAD

**Issue by RaphaelNdonga** [section-engineering-education/engineering-education#1603]
### Proposed title of article
Working with lambda functions in Kotlin

### Introduction paragraph(s):
In Kotlin, functions are ‘first-class citizens’. This means that you can do the following to functions in Kotlin: 
1.	Functions can be passed as arguments to other functions and classes.
2.	Functions can be assigned to variables and stored in data structures.
3.	Functions can be returned from other higher order functions.
The above functionality is enabled through the use of lambda functions.

Lambda functions are called when the higher order function, (the function that calls the lambda function), is created. This means that by the time we implement the higher order function, the lambda function will already possess the arguments passed to it during creation, and thus we can manipulate those values for our own purposes.

The above paragraph will be demonstrated.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.
1. What lambda functions are.
2. Why lambda functions are important.
3. When to use lambda functions.

### References: 
https://kotlinlang.org/docs/lambdas.html
https://en.wikipedia.org/wiki/First-class_function

The article will be different from the references in that those references do not explain explicitly why lambda functions are important and they also give vague examples of when to use lambda functions. 
This article will tackle those issues in detail. Lambda functions happen to be a very confusing area to beginners and intermediate developers

**Comment by hectorkambow** [comment]
@LinusMuema  

Could you please review this article suggestion on Kotlin - to see if there are any suggestions we could add to improve this topic. 

If it looks good as is 👍  fantastic. Let us know. Thank you. 🚀  

We want to start our review process from the get-go instread of waiting for a draft.

**Comment by LinusMuema** [comment]
Hi @hectorkambow 
I would love to give this suggestion a review. Does that mean I assign myself this issue right now?

I think that would be mirrored in the pull request too 🤔

**Comment by hectorkambow** [comment]
@LinusMuema  Good question - at this moment - I'd say lets not self-assign yet. 
We just want to look over the topic -see if it makes sense. 

If it missing anything major that would help the author put together their thoughts on the subject - perhaps some guidance if needed. 

That is it. 

If it looks good as it - we can just give the 👍

**Comment by LinusMuema** [comment]
okay...
The suggestion looks good to go. The author can go ahead and write...

@RaphaelNdonga welcome to the community. Happy to have you here :smile:

**Comment by RaphaelNdonga** [comment]
Awesome
