### ISSUE TITLE
Understanding Inter-VLAN routing

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#1605]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Gaining the understanding of VLANs and the ways of inter-VLAN communication.

### Introduction paragraph(s):
Consider yourself an employee of an organisation as the network administrator.One of your task is to partition the single switched network of that organisation to match the functional  requirements without having to run new cables or make major changes in the existing network infrastructure.

To be able to do this one must have the knowledge of virtual local area networks (vlans) and how they are configured to enable communication  within the network from one vlan to the other . This article clearly describes what vlans are and how they can be configured to improve the overall performance  of the network as they tend to be flexible since they are based on logical connections rather than physical connections

### Key takeaways: 
The reader should be able to :
1. Understand what vlans are.
2. How to use vlans in segmenting or rather partitioning  a switched network.
3. How to enable communcation between two vlans in a network

### References: 
N/A

### Templates to use as guides
N/A

**Comment by hectorkambow** [comment]
👋  Good morning and welcome @dentonya  

Thank you for your article topic suggestion. 
This seems like it could be a helpful topic to discuss. 

We just want to make sure it leans more heavily on software as opposed to hardware. 

Vlans are a great one to understand. 

Please also review this article to make sure we are not overlapping and to see how we can build on it if possible. 

https://github.com/section-engineering-education/engineering-education/issues/new?assignees=&labels=topic+suggestion&template=enged-content-idea-suggestion.md&title=

topic approved 👍

**Comment by dentonya** [comment]
Thank you hectorkambow..the topic leans on the software part and will make sure it doesn't overlap with other articles and it focuses on softwares only..kind regards
