### ISSUE TITLE
What is Word2Vec?

### ISSUE THREAD

**Issue by wilkistermumbi** [section-engineering-education/engineering-education#1609]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph(s):

How can we make computers understand us better using natural language?

Computers are good at understanding numbers. They are good at taking large matrices and applying linear algebra to those matrices. By converting words into vectors, we can make computers understand the meaning and context of words in natural language. 

It turns out that the word2vec algorithm can help us achieve this.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this article, the reader should be able to understand:

1. How computers are able to understand words
2. What the Word2Vec algorithm entails
3. The workings of the Continuous Bag of Words (CBOW) and Continuous Skip-gram models used in the Word2Vec algorithm

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

1. [Efficient Estimation of Word Representations in Vector Space](https://arxiv.org/pdf/1301.3781.pdf)
2. [word2vec Parameter Learning Explained](https://arxiv.org/pdf/1411.2738.pdf)
3. [Tomas Mikolov](https://en.wikipedia.org/wiki/Tomas_Mikolov)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
🤔  

@wilkistermumbi  very cool topic - seems like it could be very informative and useful. Lets be sure the aricle includes enough substance that a beginner can follow along - and please be sure to go over any machine learning or computer vision articles that we have published so make sure there is not much overlap and/or see how we can build upon them or reference them only if applicable. 

👍 approved.
