### ISSUE TITLE
TransGAN: A Transformer based GAN architecture

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#1610]
### Introduction paragraph(s):

Can we build a strong Generative Adversarial Network (GAN) utterly free of convolutions?

This article aims to discuss this recent [paper](https://arxiv.org/pdf/2102.07074.pdf), a buzz in the AI community over the past couple of weeks. The paper aims to re-design the architecture for Generative Adversarial Networks (GANs) using only pure transformer-based architecture.

### Key takeaways: 

What are the 3-5 most important things the reader should understand or be able to do after reading this article? 

1. What is a Generative Adversarial Network (GAN)?
2. A description of the TransGAN architecture
3. Tricks for TransGAN

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

1. [TransGAN: Two Transformers Can Make One Strong GAN](https://arxiv.org/pdf/2102.07074.pdf)

**Comment by hectorkambow** [comment]
@Bayler  
Just wanted to make sure we are using the [newest topic form](https://github.com/section-engineering-education/engineering-education/issues/new?assignees=&labels=topic+suggestion&template=enged-content-idea-suggestion.md&title=).

**Comment by Bayler** [comment]
> @Bayler  
> Just wanted to make sure we are using the [newest topic form](https://github.com/section-engineering-education/engineering-education/issues/new?assignees=&labels=topic+suggestion&template=enged-content-idea-suggestion.md&title=). 
> 
> 

Yes, we are @hectorkambow

**Comment by Bayler** [comment]
I just removed the rest of the info. But it's the same @hectorkambow

**Comment by hectorkambow** [comment]
🚀  

Seems like a great article in line with our other AI related one. 👍  approved
