### ISSUE TITLE
Overview of Spanning Tree Protocol (STP)

### ISSUE THREAD

**Issue by raboba2re** [section-engineering-education/engineering-education#1612]
### Introduction
Organizations rely on the network infrastructure to provide mission-critical services.
A network failure can result in loss of revenue and customers. Because of this, network designers must design and build a highly available network.
This article will discuss how network designers use the Spanning Tree Protocol (STP) to ensure network redundancy and availability.

### Key takeaways: 
At the end of this article the reader must have learned the following:
- What Spanning Tree Protocol is
- Network redundancy and various redundancy issues
- How to avoid network redundancy issues using Spanning Tree Protocol
- Different types of Spanning Tree Protocols 

### Reference
- https://www.cisco.com/c/en/us/support/docs/lan-switching/spanning-tree-protocol/5234-5.html
- https://www.computernetworkingnotes.com/ccna-study-guide/stp-spanning-tree-protocol-explained-with-examples.html

**Comment by hectorkambow** [comment]
👋  @raboba2re 

Please be sure to review our [contribution guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md) before continuing.

We are asking students to only open on topic and PR at time to get published.

Please pick one and close the others.

**Comment by raboba2re** [comment]
@hectorkambow sorry for that, I was hopping only one will get approved. 
I have closed all others except this one.

**Comment by ninjaginja** [comment]
@raboba2re thank you for the topic suggestion. We are more interested in featuring content that focuses on Layer 3-7 technologies. Please suggest a different topic area to explore. Many thanks!
