### ISSUE TITLE
 Introduction to Dynamic Host Configuration Protocol (DHCP)

### ISSUE THREAD

**Issue by raboba2re** [section-engineering-education/engineering-education#1613]
### Proposed title of article
 Introduction to Dynamic Host Configuration Protocol (DHCP)

### Introduction 
The vast majority of the host on the internet are user-end devices. These devices require a unique identifier on the internet known as an Internet Protocol (IP) address.
This address can be configured as static by a network administrator or dynamically using Dynamic Host Configuration Protocol (DHCP).
This article will look at DHCP version 4 (DHCPv4) and DHCP version 6 (DHCPv6).

### Key takeaways: 
At the end of this article, the reader should have learned:
- What DHCP is
- the need for DHCP
- The various versions of DHCP in used

### References: 
https://www.efficientip.com/what-is-dhcp-and-why-is-it-important/

**Comment by ninjaginja** [comment]
good topic @raboba2re - approved.
