### ISSUE TITLE
How to build a Flutter web application

### ISSUE THREAD

**Issue by WanjaMIKE** [section-engineering-education/engineering-education#1615]
### Proposed title of article
How to build a Flutter web application

### Introduction paragraph(s):

Flutter is an emerging framework for crafting beautiful cross-platform mobile applications. It allows developers to target both iOS and Android platforms with a single code base. This feature helps to save a significant amount of time and resources.  With the release of `Flutter 2`, its popularity is set to rise even further. The Flutter framework will definitely cause ripples in the web development field. New icons, as well as other features included in Flutter 2 will simplify the development of web applications. 

Flutter for Web has recently moved from `beta` to `stable`. This is good news to developers since they can build highly secure and appealing websites. Flutter widgets are based on Google's `material design` and principles. This means that even inexperienced Flutter developers can design visually-appealing applications. This tutorial guides you on how to create a simple Flutter web application.

### Key takeaways: 

  - Understand how to install the Flutter SDK.
  - Set up the development environment.
  - Build a simple Flutter web application

### References: 
    N/A

**Comment by ninjaginja** [comment]
good topic @WanjaMIKE  - approved.

**Comment by hectorkambow** [comment]
@WanjaMIKE just wanted to follow up on this topic as I'm clearing up the queue where possible?

**Comment by WanjaMIKE** [comment]
@hectorkambow I will upload the article by tomorrow. Thanks

**Comment by hectorkambow** [comment]
merged https://github.com/section-engineering-education/engineering-education/pull/2418
