### ISSUE TITLE
 Getting started with Visual Basic .NET

### ISSUE THREAD

**Issue by Dyrstiu** [section-engineering-education/engineering-education#1616]
### Introduction paragraph(s):
Visual Basic.net is a multi-paradigm ,object
oriented programming language .it is implemented in the .NET framework developed by Microsoft. It is widely-used in in creating desktop applications.in this tutorial we will look at the most important basic parts of Visual Basic.net step  by step

### Key takeaways:
1. setting up an environment for running Visual Basic.net i.e. Visual Studio 
2. understanding visual basic.net syntax
3.write a hello world program 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Dyrstiu. There are some grammar/readability issues in the description that you've provided. We do not provide editing services and these topic suggestions are a way for us to understand the level of review that may be required.

We are unable to accept this topic as proposed, but please feel free to spend some time cleaning up and expanding on this topic suggestion to help us better assess the readability and substance of your proposed article. When you are ready, you may request that this issue be reopened. Thank you.
