### ISSUE TITLE
Digital currency - overview, types, how it works, advantages and disadvantages, risks

### ISSUE THREAD

**Issue by molly80** [section-engineering-education/engineering-education#1617]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph(s):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.

This articles aims to educate investors about digital currency. How digital currency works . The types that exists, possible risks, advantages and disadvantages.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

An overview about digital currency
Different types of digital currency
How digital currency work
Risks involved
Advantages and disadvantages of digital currency

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by hectorkambow** [comment]
@HeatherMataruse Please be sure to review our contribution guidelines before continuing.

We are asking students to only open on topic and PR at time to get published.

Please pick one and close the other..

**Comment by molly80** [comment]
@hectorkambow I picked this one should I continue?

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @molly80, but this is outside our preferred topic focus areas. Please feel free to suggest an alternate topic for review.

Also, please note these topic suggestions are a way for us to understand the level of review that may be required of an article once the topic is approved. In order for us to assess, please be as thorough and descriptive as possible when proposing a topic. We suggest writing and submitting the first 3 paragraphs of your proposed article. (The sample description that you've provided here is very sparse.)
