### ISSUE TITLE
Difference between digital currency and cryptocurrency

### ISSUE THREAD

**Issue by molly80** [section-engineering-education/engineering-education#1618]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph(s):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.

People often confuse digital currency and cryptocurrency. This article aims at educating readers on the differences that exists between cryptocurrency and digital currency.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

Cryptocurrency overview
Digital currency overview
Differences between cryptocurrency and digital currency

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by molly80** [comment]
Will open after I have published the other one Issue in queue

**Comment by hectorkambow** [comment]
> Will open after I have published the other one Issue in queue

This one can be opened after the other one has been published. 

To avoid queues we are only allowing one topic and PR open at at time until publishing. 🚀
