### ISSUE TITLE
Implementation of dark theme using CSS variables and JavaScript's local storage.

### ISSUE THREAD

**Issue by phinaomondi** [section-engineering-education/engineering-education#1619]
### Introduction paragraph(s):
Dark them has gained prevalence in both mobile, desktop, and web applications. Lately, users tend to shift to dark themes. Applying a dark theme to a website not only satisfy users but also aid in reducing power consumption and minimizing eye strain by providing eye comfort especially during the dark. This article explains how to add a dark theme to a website using CSS variables and JavaScript's local storage functionality. 

### Key takeaways: 
1. Using CSS variables
2. How to use local storage in JavaScript to create cookies
3. Retrieving web cookies using JavaScript
4. Switching CSS classes of elements using JavaScript

### References: 
N/A

**Comment by ninjaginja** [comment]
Good topic @phinaomondi - approved.

Just a note to be mindful of grammar and readability, and make sure that you've put your draft through a thorough editing review prior to submitting for final review. There are several free tools out there that we recommend, which you can find in our resources guides.

**Comment by hectorkambow** [comment]
@phinaomondi 

Check out our[ resources page here ](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md)
