### ISSUE TITLE
How to use React to send a POST request to a Laravel application

### ISSUE THREAD

**Issue by Agusioma** [section-engineering-education/engineering-education#1620]
### Proposed title of the article
How to use React to send a POST request to a Laravel application
### Introduction paragraph(s):
Maybe you are a backend engineer wanting to load data to your site using the React library, or you want to explore the use of React with Laravel or you have any other interests validating the use of Laravel with React, then you are at the right place. We are going to learn how to make a POST request to a Laravel application using React and retrieve the response.

#### Basic descriptions

- **React:** This is a JavaScript library that assists us in creating interactive and dynamic Single Page Applications. 
- **Axios:** It is a library used to handle HTTP requests to external resources in our web applications.
- **Laravel:** This is a PHP framework based on the Model View Controller architecture and it helps us create web backend applications faster.

#### Prerequisites

- A basic understanding of PHP and its working with Laravel
- A basic understanding of HTML and CSS
- A basic understanding of JavaScript and its working with React
- Php, Composer, Laravel installer installed in your machine.

Having that, we can now start delving into the topic.

#### What will be doing

We will be sending input data from a signup page and send the data to a Laravel controller which will, in turn, return JSON data and display it in an alert.

> **JSON**, JavaScript Object Notation, is a data exchange format between web applications.

### Key takeaways: 
In the end, the user will get to learn about:

- JSON and its role in HTTP requests
- The Axios library and how to use it to send HTTP POST data
- Using Axios in React
- Receiving the POST request in a Laravel application and returning the response back as JSON

### References: 

- [Jason Watmore's blog](https://jasonwatmore.com/post/2020/07/17/react-axios-http-post-request-examples)
- [Blog Pusher](https://blog.pusher.com/react-laravel-application/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @Agusioma - approved
