### ISSUE TITLE
Connecting library application to SQL Server using Windows forms.

### ISSUE THREAD

**Issue by mohamedgh16** [section-engineering-education/engineering-education#1621]
### Proposed title of the tutorial.
Connecting library application to SQL Server using Windows forms.

### Introduction paragraph(s):
 _**windows forms**_ is one of the best tools used in making applications. 
 With windows forms, you can make a variety of applications, from a mini calculator to a library application that connects to a database. In this tutorial, we will connect a library application using Windows forms to a database using SQL Server.

In this tutorial, we will use a windows forms project and work on it, we will add new forms that will add edit & delete books from the library, we will also manage the authors, the stores & the publishers stored in the database. We will display the information of each attribute & refresh it each time a change accrues.

### Key takeaways: 
- Understand the controls used inside of the application.
- Understand the Queries used in SQL Server. 
- Understand the code that connects the application to the database.

### References: 
The database that we will use in this tutorial, [pubs database](https://github.com/microsoft/sql-server-samples/blob/master/samples/databases/northwind-pubs/instpubs.sql).
The project that we will use to make the library application add the forms & connect to the database.
[project link](https://github.com/mohamedgh16/Library-app-code-in-windowsforms).

**Comment by ninjaginja** [comment]
good topic @mohamedgh16 - approved
