### ISSUE TITLE
Flutter Folder Organization

### ISSUE THREAD

**Issue by jerimkaura** [section-engineering-education/engineering-education#1622]
### Introduction paragraph(s):
Flutter allows one to program an entire application in one file. However, however, as the size of the android application increases, identifying and fixing bugs in a single large file is challenging. This raises the need to identify a preferable folder structure. This article explains the folders and files autogenerated during Flutter project creation and provides a framework for organizing them to enhance the scalability of a project.

### Key takeaways: 
1. An explanation to Flutter folders and files
2. Organisation of Flutter project files and folders for large scale application.
3. Benefits of maintaining proper folder structure.

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @jerimkaura - approved
