### ISSUE TITLE
Angular 11 - JWT Authentication Example & Tutorial

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#1623]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Angular 11 - JWT Authentication Example & Tutorial  

### Introduction paragraph(s):
This post is a step-by-step guide for both designing and implementing JWT-based Authentication in an Angular Application.  
The goal here is to discuss JWT-based Authentication Design and Implementation in general, by going over the multiple design options and design compromises involved, and then apply those concepts in the specific context of an Angular Application.  
We will follow the complete journey of a JWT from creation on the Authentication server and back to the client, and then back to the Application server and talk about all the design options and decisions involved.   

Because Authentication also requires some server code, we will show that too so that we have the whole context and can see how all the multiple parts work together.

### Key takeaways: 
- Creating the login page to implement JWT. 
- Creating a JWT based user session
- Sending JWT back to the client
- Storing and using the JWT on the client side
- Validating user requests.
### References: 
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @jumamiller  - approved
