### ISSUE TITLE
Angular 11 HTTP Client - Quickstart Guide

### ISSUE THREAD

**Issue by owinowendy** [section-engineering-education/engineering-education#1624]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Angular 11 HTTP Client - Quickstart Guide

### Introduction paragraph(s):
This post will be a quick practical guide for the Angular HTTP Client module. We will cover how to do HTTP in Angular in general. We will be using the new @angular/common/http module, but a good part of this post is also applicable to the previous @angular/http module.  
We will provide some examples of how to use this module to implement some of the most common uses that you will find during development.

### Key takeaways: 
- Introduction to the new HTTP Client module
- HTTP Request Parameters (Immutability-based API)
- HTTP PUT, PATCH, POST, DELETE
- HTTP error handling
- HTTP Interceptors
### References: 
N/A 

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @owinowendy - approved
