### ISSUE TITLE
What are Architectural Patterns in Android?

### ISSUE THREAD

**Issue by kvardhan10** [section-engineering-education/engineering-education#1625]
### Proposed title of article
What are Architectural Patterns in Android?

### Introduction paragraph(s):
A native Android application may require instructions to reorient its interface and structure based on the different fragments accessed by the user. These integral portions need to be remodeled using architectural patterns. This article deals with such architectural patterns which can be implemented to improve the overall project design. This enhances code readability, makes the UI design user-friendly, and provides good A/B testing results.

### Key takeaways: 
The reader will be able to understand:
- MVC pattern 
- MVP pattern
- MVVM pattern
- Their definition and working
- Advantages and Disadvantages

### References: 
https://yourstory.com/mystory/mvp-vs-mvc-vs-mvvm
https://www.geeksforgeeks.org/android-architecture-patterns/

**Comment by ninjaginja** [comment]
good topic @kvardhan10 - approved

**Comment by hectorkambow** [comment]
merged
https://github.com/section-engineering-education/engineering-education/pull/2403
