### ISSUE TITLE
Deploying a Django-React application to heroku

### ISSUE THREAD

**Issue by OkothPius** [section-engineering-education/engineering-education#1626]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Deploying Django-React application to Heroku
### Introduction paragraph(s):
In the previous [post](https://www.section.io/engineering-education/react-and-django-rest-framework/) we tackled how to develop an application by integrating Django and React. In this post we take the application live by hosting it on Heroku by using the Heroku CLI and Git client.

### Key takeaways: 
* A quick walkthrough on Django and React
* What is Heroku and its importance
* Setting up Heroku CLI
* Setting Django and React to Heroku
* Using Git to push our application to Heroku

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @OkothPius. Unfortunately, Heroku is a competing product to Section, and we prefer not to publish content that centers around their deployment tooling. As an alternative, you may try exploring [Section's Node.js Edge Hosting solution](https://www.section.io/modules/nodejs-edge-hosting/) to see if you can achieve a similar outcome. 

I'm going to go ahead an close this issue for now. Please feel free to reopen, if you'd like to rework this topic suggestion. Thanks.
