### ISSUE TITLE
Front End vs Back End in Web Development

### ISSUE THREAD

**Issue by mbaabuones** [section-engineering-education/engineering-education#1627]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Front End vs Back End in Web Development

### Introduction paragraph(s):
Web development is an important field in the tech industry because it contributes to the development of e-commerce sites, social network services, and complex web applications. Building a web application requires two fundamental parts: back end and front end. Understanding the difference between these parts is important especially to young developers because it helps to determine their right career paths. 

This article provides a comparison between back end and front end in web development and provides an overview of how they interact with each other. It also provides a guide that can help developers to choose the right development path.

### Key takeaways: 
- What is front end development?
- What is back end development?
- Differences between front end and back end development
- Understanding full stack development
- Choosing the right development path (as a developer)
- Summary table
- Conclusion

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
