### ISSUE TITLE
Android Dependency Injection With Koin

### ISSUE THREAD

**Issue by kayere** [section-engineering-education/engineering-education#1628]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Android Dependency Injection With Koin

### Introduction paragraph(s):
Dependency injection is a programming technique that makes a class independent if its dependencies. This is made possible by decoupling the usage of an object from its creation. Many android developers are familiar with Java based dependency injection frameworks such as Dagger and Guice. However, there are also frameworks that are purely written in Kotlin for Kotlin. These Frameworks include Koin and Kodein. This article goes through how to manage dependencies in android with the new kotlin dependency injection framework Koin.

### Key takeaways: 
1. Understand what is dependency injection.
2. Understand the advantages of dependency injection technique.
3. Understand how to use Koin to manage dependencies in android.
4. Understand the advantages if using Koin as a dependency injection framework.

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @kayere - approved
