### ISSUE TITLE
Build an API using Python

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-engineering-education/engineering-education#1629]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

#### Introduction
In this tutorial, we are going to learn what is an API and how to build one using [Flask](https://flask.palletsprojects.com/en/1.1.x/) which is a [microframework](https://en.wikipedia.org/wiki/Microframework) written in Python. Then we will send GET/POST/PUT/DELETE requests to return or modify data.

##### What is an API?
Application programming interface is software that allows two applications to talk to each other. Regardless of those being web, mobile, or desktop applications, etc... Every day you are using APIs without notice. For example, when you like a post on Facebook, send a message, or even check the weather on your phone.

### Key takeaways: 
In this tutorial, I'm going to build an API using Flask framework, and the reader will learn the following:

- What is an API and why we need it.
- How to build an API using Flask.
- Test it by using Postman to make requests (GET, POST, PUT, DELETE).

### References: 
N/A for now.

**Comment by WanjaMIKE** [comment]
Are you going to use Django to build the API? If so, then it is already covered here `https://www.section.io/engineering-education/django-crud-api/`

**Comment by paulodhiambo** [comment]
I already covered Flask API [here](https://www.section.io/engineering-education/flask-crud-api/)

**Comment by ahmadmardeni1** [comment]
> I already covered Flask API [here](https://www.section.io/engineering-education/flask-crud-api/)

Thanks. i didn't see that one
