### ISSUE TITLE
Comparing Graphical User Interface (GUI) and Command Line Interface (CLI

### ISSUE THREAD

**Issue by BridgetMwikali** [section-engineering-education/engineering-education#1631]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Comparing Graphical User Interface (GUI) and Command Line Interface (CLI)
### Introduction paragraph(s):
Any device's operating system is nothing but an interface between the user and hardware components of that device. The operating system offers a GUI and CLI user interface to interact with an electronic device. GUI means a Graphical user interface while CLI means the command line interface. A GUI is a graphical representation in which the users can interact with software or devices through clickable icons. A CLI is a console or text-based representation in which the user types commands into a terminal to operate and navigate the software or devices. 

Choosing to use a GUI or a CLI is dependent on the purpose of computer navigation. Many users prefer a GUI because it is easier and more comfortable. Many users like a visual representation of their actions on a computer or other device. GUIs are the default when computer interaction is considered and is the go-to because of their usability. 

This article discusses GUI and CLI and compares the two in terms of ease of use, multitasking, remote access, scripting, speed, and control. 

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

1. What is GUI
2. What is CLI
3. A comparison between GUI and CLI in terms of :

    

- Ease of use
- Multitasking
- Remote access
- Scripting
- Speed
- Control

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
https://www.tutorialspoint.com/graphical-user-interface-gui
https://www.w3schools.com/whatis/whatis_cli.asp
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @BridgetMwikali - approved
