### ISSUE TITLE
Understanding c++ templates

### ISSUE THREAD

**Issue by Dawe-7** [section-engineering-education/engineering-education#1632]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Understanding c++ templates

### Introduction paragraph(s):
A template is a method of writing a single function or class for a family of related functions or classes. In plain terminology, you can declare a single function or a class to work with different data types using templates.  This helps the developer avoid redundant code in a program. In the broader codebase, we use templates for code reusability and software flexibility. This article will take a look at templates and how to use them for generic programming in c++. 

### Key takeaways: 
1. How templates work and when to use them
2. Class and function templates
3. Variadic function templates
4. How to create a class and function template using intuitive programs
5. Advantages of templates

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @Dawe-7 - approved
