### ISSUE TITLE
Variable Fonts on the Web: An Overview

### ISSUE THREAD

**Issue by annwawesh** [section-engineering-education/engineering-education#1633]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Variable Fonts on   the Web: An Overview

### Introduction paragraph(s):
Variable fonts are making a huge impact in web design. These are innovative types of fonts that employ CSS attributes to improve typography in web design. Developers can utilize variable fonts to improve user experience and enhance creativity in web design. 

This article provides a basic understanding of variable fonts. It will also explain how they work and provide examples of free variable fonts that can be used by web designers. 

### Key takeaways: 
1. What are variable fonts?
2. Why use variable fonts?
3. How variable fonts work
4. Examples of free variable fonts
5. Conclusion

### References: 
N/A.

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @annwawesh, however this is outside of our preferred topic areas. We're not as interested in web design-related topics and tend to lean more heavily in favor of programming-centric topics. Please feel free to suggest an alternate topic area to explore. Thank you.
