### ISSUE TITLE
Declarative vs Imperative UI in Android

### ISSUE THREAD

**Issue by LinusMuema** [section-engineering-education/engineering-education#1634]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Declarative  Imperative UI in Android

### Introduction paragraph(s):
Creating user interfaces in Android was had always followed an imperative way of programming. This worked and still does today but there has been an emerging trend of Declarative UI programming. This article aims to guide the reader on the differences between the two and help them transition between the two paradigms. It will make use of Jetpack compose which is the latest UI toolkit by Android developers.

### Key takeaways: 
1. What is declarative programming
2. What is imperative programming
3. The difference between the two paradigms using code samples
4. A short introduction into Jetpack compose.

### References: 
N/A

**Comment by RaphaelNdonga** [comment]
Nice

**Comment by hectorkambow** [comment]
approved 👍
