### ISSUE TITLE
Change Data Capture (CDC) Application in Real-Time Data Integration and Analytics

### ISSUE THREAD

**Issue by EKahuha** [section-engineering-education/engineering-education#1635]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Change Data Capture (CDC) Application in Real-Time Data Integration and Analytics
### Introduction paragraph(s):
In databases, change data capture (CDC) is a set of software design patterns used to determine and track the data that has changed so that action can be taken using the changed data. Companies use change data capture for several use cases, including cloud adoption and enabling real-time data warehousing. 

CDC eliminates the need for bulk load updating and inconvenient batch windows by enabling incremental loading or real-time streaming of data changes into your data warehouse. It is also used to populate real-time business intelligence dashboards, synchronize data across geographically distributed systems, and facilitate zero-downtime database migrations.
### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

1. What is Change Data Capture (CDC)? 
2. Why use CDC 
3. Different methods of CDC (Log-Based Change Data Capture, Triggers, Audit Columns, Table Deltas)
4. Use cases of CDC 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/about-change-data-capture-sql-server?view=sql-server-ver15
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved

**Comment by hectorkambow** [comment]
@EKahuha just wanted to follow up on this topic as I'm clearing up the queue where possible?

**Comment by EKahuha** [comment]
@hectorkambow I will submit a PR for this issue by the end of this week.

**Comment by hectorkambow** [comment]
merged
