### ISSUE TITLE
Data Classes in Python

### ISSUE THREAD

**Issue by OkothPius** [section-engineering-education/engineering-education#1637]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Data Classes in Python

### Introduction paragraph(s):
The main function of a Python class is to contain and represent data. In previous Python versions, the init function stores values on the instance of the class. This is a common pattern that begs the question of why must we explicitly store each argument on the object. Well, in Python 3.7 we actually don't. A new feature called data class which helps to automate the creation and managing of classes that mostly exist just to hold data was introduced to help solve this.

### Key takeaways: 
* Defining a data class
* Using post initialization
* Using default values
* Immutable data classes

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @OkothPius - approved

**Comment by ahmadmardeni1** [comment]
I would like to review this one when he publishes it 👀 @hectorkambow

**Comment by hectorkambow** [comment]
> I would like to review this one when he publishes it 👀 @hectorkambow

@ahmadmardeni1 
We don't want to assign it as a topic - because things can occur (between now and a PR) - and we do not want to make the process take longer.
But now that you have found one - lets keep an eye out for it.
If someone jumps on it - we can ask them to allow you a test run.
Please lets only pick one - one for the test run.  (if im not confused-you've yet to do a test review correct?)
