### ISSUE TITLE
Cryptography in Computer Networking

### ISSUE THREAD

**Issue by awinomackrine** [section-engineering-education/engineering-education#1638]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Cryptography in Computer Networking

### Introduction paragraph(s):
The Internet is a computer network that interconnects hundreds of millions of devices (personal computer, mobile phone, laptop, TV,…) in the world. Most people use the Internet to send/receive data (photo, video, email,…). Connections on the Internet are NOT secure by default and cryptography makes it secure as much as possible.    
This tutorial covers the basics of the science of cryptography. It explains how programmers and network professionals can use cryptography to maintain the privacy of computer data. Starting with the origins of cryptography, it moves on to explain cryptosystems, various traditional and modern ciphers, public key encryption, data integration, message authentication, and digital signatures.

### Key takeaways: 
- Network Layers
- Cryptosystems
- Attacks on cryptosystems
### References: 
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @awinomackrine - approved

**Comment by hectorkambow** [comment]
@awinomackrine just wanted to follow up on this topic as I'm clearing up the queue where possible?
