### ISSUE TITLE
Sending emails with Spring Boot SMTP

### ISSUE THREAD

**Issue by qawuor** [section-engineering-education/engineering-education#1640]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Introduction paragraph(s):
Spring Boot is a Java web framework that simplifies web development. The Simple Mail Transfer Protocol (SMTP) is a communication protocol for electronic mail transmission. In this tutorial the reader will learn how to configure SMTP on a gmail account and finally send emails through a Spring Boot application

### Key takeaways: 
1. The reader should be able to configure gmail SMTP.
2. The reader should be able to send emails from a Spring Boot application. 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by paulodhiambo** [comment]
I already covered Flask API [here](https://www.section.io/engineering-education/flask-crud-api/)

**Comment by ninjaginja** [comment]
good topic @qawuor - approved
