### ISSUE TITLE
Django REST API documentation with swagger and open API

### ISSUE THREAD

**Issue by okeloviolet** [section-engineering-education/engineering-education#1641]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Introduction paragraph(s):
Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design. In this tutorial the reader will learn how to create a Django REST API and document it with swagger. REST API documentation makes it easier for API consumers to easily integrate with the API.

### Key takeaways: 
1. The reader will be able to create REST APIs in Django.
2. The reader will be able to document the REST API endpoints created using Swaggger.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @okeloviolet. Before we approved this topic, can you please confirm that there will not be too much crossover with this existing article - https://www.section.io/engineering-education/django-crud-api/? 

It sounds like your proposed article is more focused on the swagger documentation, but wanted to confirm before having you proceed.

**Comment by okeloviolet** [comment]
@ninjaginja  the article is majoring on the REST API documentation rather than creating REST APIs
