### ISSUE TITLE
Getting started with Spring Boot social authentication in Kotlin

### ISSUE THREAD

**Issue by paulodhiambo** [section-engineering-education/engineering-education#1642]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Introduction paragraph(s):
The Spring Framework is an application framework and inversion of control container for the JVM platform. In this tutorial the reader will learn how to authenticate users in a Spring Boot application through their social accounts i.e. Gmail, Facebook or GitHub account. 

### Key takeaways: 
1. The reader will learn the basics of Spring security.
2. The reader will be able to integrate Google, Facebook and GitHub authentication into their Spring Boot applications.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
[Spring Security Documentation](https://spring.io/projects/spring-security)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @paulodhiambo - approved
