### ISSUE TITLE
Getting started with Matlab plots

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#1643]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Introduction paragraph(s):
MATLAB plot is a graphical representation of a given set of data. MATLAB is very useful for making scientific and engineering plots. You can create plots of known, analytical functions, you can plot data from other sources such as experimental measurements, you can analyze data, perhaps by fitting it to a curve, and then plot a comparison. MATLAB also has powerful built-in routines for drawing contour and three-dimensional plots. In this article I will take the reader through various plots that are available in MATLAB.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.
1. The reader will be able to create simple plot from matrix data.
2. The reader should understand the various types of plots.
3. The reader should understand the various plot commands and the application
4. The reader will be able to create complex plots such as distribution and mesh plots.
 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Hello @jumapaul 👋👀
I covered the Matlab plots in [my tutorial](https://www.section.io/engineering-education/getting-started-with-matlab/)
But if you want to create an advanced tutorial, then please refer to my tutorial as a prerequisite for beginners

**Comment by jumapaul** [comment]
This is the advance Matlab plotting.

**Comment by jumapaul** [comment]
> Hello @jumapaul 👋👀
> I covered the Matlab plots in [my tutorial](https://www.section.io/engineering-education/getting-started-with-matlab/)
> But if you want to create an advanced tutorial, then please refer to my tutorial as a prerequisite for beginners

@ahmadmardeni1 this is the advance Matlab plotting

**Comment by ninjaginja** [comment]
@jumapaul It sounds like this is no longer a 'Getting started' guide. Could you please resubmit your revised topic suggestion in a new issue, referencing this comment string and the new direction for the advanced guide? Thank you. (I'll close this issue for now.)
