### ISSUE TITLE
Understanding Wireframing in Web Design

### ISSUE THREAD

**Issue by gracejolie** [section-engineering-education/engineering-education#1644]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Understanding Wireframing in Web Design

### Introduction paragraph(s):
The layout and design of a web page affect the number of online users visiting the page. Wireframing is an important concept in web design because it helps developers to plan how web content will be organized on the web page. This article takes you through various aspects of this concept and provides examples of popular wireframing tools that can be used by web designers. 

### Key takeaways: 
1. What is a wireframe?
2. Why Wireframe is needed in web designs
3. Essential components of a wireframe
4. Types of wireframes
5. Popular wireframing tools
6. Conclusion

### References: 
N/A.

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @gracejolie, however this is outside of our preferred topic areas. We prefer content that is more programming-centric within the web technologies ecosystem. Please feel free to suggest an alternate topic area to explore.
