### ISSUE TITLE
How to insert 3D objects into a webpage using HTML and CSS

### ISSUE THREAD

**Issue by RisoriTofa** [section-engineering-education/engineering-education#1645]
### Proposed title of the article
How to insert 3D objects into a webpage using HTML and CSS

### Introduction paragraph(s):
Are you a creative frontend web designer or are you looking for ways to make your website look more interactive and visually appealing? Would you like to advertise your products interestingly? Look no further. We are going to learn how to insert 3D objects into a website.

## Basic descriptions
- **3D object:**  It is an object or a shape with three dimensions; these are length, width, and height.
- **CSS:** A computer language used for structuring and laying webpages written in HTML or XML

## Prerequisites

- A basic knowledge and understanding of HTML
- A basic understanding of CSS
- A basic web development IDE or a text editor installed on your machine

Having all these we can now get into the topic.

## What we will be doing
We will be creating a simple webpage with basic components, design its layers, and then inserting the 3D object into the webpage.

### Key takeaways: 
At the end of this tutorial, the user will get to learn about:

- 3D objects, formats, and some of their properties
- How to create or acquire 3D objects for their website
- Inserting a 3D object in a website
- Formatting the 3D object inserted into the webpage

> 3D file formats are used to store information about the object. They are used in video games, 3D printing, engineering, movies and so much more.

### References: 

- [Diego González blog](https://medium.com/samsung-internet-dev/adding-3d-models-to-your-website-d374a8cbbadd)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @RisoriTofa - approved
