### ISSUE TITLE
Understanding Glassmorphism in UI Design

### ISSUE THREAD

**Issue by artmuth** [section-engineering-education/engineering-education#1647]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Understanding Glassmorphism in UI Design

### Introduction paragraph(s):
Glassmorphism is an emerging trend in user interface design. It is a modern technique of styling web-pages while providing 3D experiences and glass effects. Web designers are using this technique to improve user experience and the attractiveness of web applications. 

This article provides an understanding of this concept and explains how it has been applied in the UI industry.

### Key takeaways: 
1. What is glassmorphism?
2. Why is glassmorphism popular?
3. Key features of glassmorphism in UI design
4. How glassmorphism has been applied in the UI industry
5. The future of glassmorphism

### References: 
N/A.

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @artmuth, however this is outside of our preferred topic areas. We lean more heavily towards programming-centric topics as opposed to design-centric topics. Please feel free to suggest an alternate topic area to explore.
