### ISSUE TITLE
Creating your first Google web story 

### ISSUE THREAD

**Issue by Jethro-magaji** [section-engineering-education/engineering-education#1648]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Creating your first  Google web story 

### Introduction paragraph(s):
Web Stories are a web-based version of the popular Story format, allowing creators to host and own their content.

### Key takeaways:
- what is a web story
- how to create a web story using NoCode
- how to create a web story with code
- web stories best practices

### References: 
- https://www.google.com/amp/s/stories.google/
- https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/
- https://www.google.com/amp/s/blog.google/web-creators/10-web-stories-and-whats-great-about-them/amp/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Jethro-magaji, however the description that you've provided is rather sparse and doesn't allow us to fully assess the quality and substance of your proposed article. We are unable to accept this topic as proposed, but please feel free to spend some time expanding on this topic suggestion - we suggest writing the first 3 paragraphs of your article and including that in your submission. When you are ready, you may request that this issue be reopened. Thank you.

**Comment by Jethro-magaji** [comment]
Hi @ninjaginja 
Thanks for the corrections, I have just updated the description.
can you please check it out?
