### ISSUE TITLE
How to implement SearchView in Android

### ISSUE THREAD

**Issue by Ericgacoki** [section-engineering-education/engineering-education#1649]
### Proposed title of article

How to implement SearchView in Android

### Introduction paragraph(s):

When dealing with a vast amount of data, it can sometimes be strenuous to find the piece of data that you want. A `SearchView` is an Android widget that solves this problem by filtering out matches found with respect to the keyword provided. It also helps in quick data analysis that would otherwise be impossible.

### Key takeaways: 

By the end of this tutorial, the reader will be able to: 

1. Create a SearchView user interface
2. Work with Linear search algorithm
3. Implement SearchView in an Android Recyclerview

### References: 

N/A

**Comment by ninjaginja** [comment]
good topic @Ericgacoki - approved
