### ISSUE TITLE
Recommender System Explained

### ISSUE THREAD

**Issue by ninah12** [section-engineering-education/engineering-education#1650]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Recommender System Explained

### Introduction paragraph(s):
Recommender systems are used by top online companies such as YouTube, Netflix and Amazon to suggest online products to buyers based on their interests, preferences and purchasing behavior. These systems help online businesses to optimize user interaction on their websites with the purpose of increasing their sales revenue. 

This article takes you through the basics of these systems and provides some popular use cases. 

### Key takeaways: 
1. What is a Recommender system?
2. Components of a recommender
3. Types of recommender systems
4. How recommender systems work
5. Applications of recommender systems (use cases)

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. N/A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @ninah12. Could you please expand on some of the technical components that you intend to cover in this article so that we can better assess?

**Comment by ninah12** [comment]
> 
> 
> Thank you for the topic suggestion @ninah12. Could you please expand on some of the technical components that you intend to cover in this article so that we can better assess?

@ninjaginja I intend to introduce readers to recommender systems and related basic terminologies. I intend to explain the three component procedures of a recommender system: candidate generations, scoring systems, and re-ranking systems. I will also analyze various types of recommender systems: collaborative filtering, content-based filtering, hybrid recommender systems, mobile recommender systems, multi-criteria recommender systems and session-based recommender systems. The article will also explain how recommender systems work, including how various types of data are utilized to provide recommendation. The main use cases will be popular sites such as Netflix, Amazon, YouTube, Spotify, and Best Buy.

**Comment by ninah12** [comment]
@ninjaginja Can I please start writing the article?

**Comment by hectorkambow** [comment]
@ninjaginja 👍  

Good topic- approved. 🚀
