### ISSUE TITLE
A Beginner's guide to python programming language

### ISSUE THREAD

**Issue by majiezra** [section-engineering-education/engineering-education#1652]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
A Beginner's guide to python programming language
### Introduction paragraph(s):
This article covers all the basic information and contents a newbie in python programming needs to know to understand the language better. It is also very important for python programming old-timers who might need some refreshing too.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- understand the concept of the string method.
- using a formatted string in programming
- the basic principle guiding the IF, ELIF, and ELSE statement

### References: 
- https://www.jetbrains.com/pycharm/download/download-thanks.html?platform=mac
- https://www.python.org/ftp/python/3.9.2/python-3.9.2-macosx10.9.pkg
- Python programming by Adam Stewåart 
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Unfortunately, I already covered this topic. `https://www.section.io/engineering-education/a-beginners-guide-to-python/`

**Comment by majiezra** [comment]
Okay.. thanks... I'll make some adjustments

**Comment by ninjaginja** [comment]
@majiezra I'm going to close this issue while you rework your topic suggestion. Please open a new issue when ready. Thank you.
