### ISSUE TITLE
User groups and permissions - Linux

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-engineering-education/engineering-education#1653]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph(s):
To create a secure environment in Linux, you need to learn about user groups and permissions. For example, if you work in a company and you want the finance department to read a file but making no modification to it, then you need to use permissions in Linux, it is a must for every programmer working with Linux nowadays.

### Key takeaways: 
In this tutorial, I'm going to explain the following:
- File permissions (read/write/execute) and how does it work.
- Create/Delete and test file permissions.
- Create, delete and modify local user accounts.
- Create, delete and modify groups.
- How to add a user to a group then how to delete it.
And a lot more.
### References: 
https://www.linux.org/
(Just this one, for now, I may add more later)

**Comment by ninjaginja** [comment]
good topic @ahmadmardeni1 - approved
