### ISSUE TITLE
How to implement and configure Windows Server 2019 on AWS

### ISSUE THREAD

**Issue by HeatherMataruse** [section-engineering-education/engineering-education#1654]
### Proposed title of the article
How to implement and configure windows server 2019 on AWS

### introduction paragraph(s):
-This will include how to create an account on AWS
- how to get started with infrastructure as a service (EC2)
- Creating and launching the Windows Server 2019 base instance
- Getting your key pair and password
- running your first windows server 2019 on your machine 

### Key takeaways: 
1.How to create an instance on AWS
2.How to run the windows server on your PC

### References: 
User does not necessarily need references to look at as I will be showing them step by step with screenshots of each step

**Comment by hectorkambow** [comment]
@HeatherMataruse  Please be sure to review our [contribution guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md) before continuing. 

We are asking students to only open on topic and PR at time to get published - I believe you have an older on - I just left a comment on

Please pick one and close the other..

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @HeatherMataruse, however this topic fringes on some competitive commercial offerings to Section, and we prefer not to publish content that highlights our competitors. I do see that you had suggested a different topic. I'll take a look at that one to see if its suitable.
