### ISSUE TITLE
Internet Inconsistencies with R-Programming

### ISSUE THREAD

**Issue by pkalynan** [section-engineering-education/engineering-education#1655]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Internet Inconsistencies with R-Programming

### Introduction paragraph(s):

An Internet Protocol (IP) address is one of several Domain Name System (DNS) attributes. Typically, IP address sequences can be displayed in two formats: IPv4 and IPv6. There are databases that hold more information about an IP such as approximate geological location, longitudinal and latitudinal coordinates, Internet Service Provider (ISP), Media Access Control (MAC), Virtual Private Network (VPN) and Autonomous System Numbers (ASN). Further information can be obtained from various databases that receive ongoing data releases. If not redacted, these pieces of information can merge into one collective research platform. The sole purpose is to detect the likelihood of inconsistencies. 

In this tutorial, R-Programming is used to identify various IP addresses mostly in IPv4 format and other DNS components. The purpose is to gain understanding about accuracies and inaccuracies of instances that may occur coincidently during internet activities. The tutorial can be used on any compatible Windows, Ubuntu, Macintosh, and or Google computer operating system. For this tutorial, Windows with a featured Linux emulator were chosen based on convenience. To compliment, any programming language can be chosen accordingly. R-Programming was chosen because of its built-in libraries dedicated to Domain Name Systems. Extended coding can establish statistical insights. Deriving insights from research can provide the probability of accuracies and inaccuracies.

### Key takeaways: 
1.	Discover and explore built-in libraries indirectly or directly dedicated to Domain Name Systems.
2.	Basic statistics (probability, descriptive and predictive analytics, confusion matrices, measures of central tendency, fractions, data and statistical modelling).
3.	Inconsistencies are present in highly sophisticated and elaborate internet activities.
4.	Domain Name System components and its role over the internet.
5.	Reverse IP lookups are helpful to provide some insights to other possibilities.

### References: 
[CRAN R-Programming Library Resources](https://cran.r-project.org/)
[Whois directory](https://www.whois.com/whois)
[RIPE directory](https://www.ripe.net)
[Host.io](https://host.io/)

**Comment by ninjaginja** [comment]
great topic @pkalynan - approved
