### ISSUE TITLE
What is Fog Computing?

### ISSUE THREAD

**Issue by kvardhan10** [section-engineering-education/engineering-education#1656]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
What is Fog Computing?

### Introduction paragraph(s):
Cloud computing is something you’ll be already acquainted with. It generally provides data storage and data management to users and enables to access them anywhere from the world since they are hosted on the internet. There are quite many applications in Cloud Computing if we use the right infrastructure. But this article deals with Fog computing. It is a decentralized computing facility that uses peripheral devices. This helps in achieving a more widespread regional distribution. The word ‘Fog’ represents edges of the cloud where peripherals are attached, hence also called ‘Edge computing’.

This article will provide a brief introduction to fog computing, and the differences between cloud computing and fog computing.  

### Key takeaways: 
The readers will be able to:
- Have a clearer concept about Fog computing 
- Understand whether fog computing and edge computing are the same
- Understand how fog computing works
- Learn about the benefits of fog computing
- Comprehend the advantages and disadvantages of fog computing

### References: 
https://en.wikipedia.org/wiki/Fog_computing
https://www.geeksforgeeks.org/difference-between-cloud-computing-and-fog-computing/?ref=rp

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @kvardhan10, however we already have quite a bit of content on the Section blog that spans across this topic, including [this article](https://www.section.io/blog/fog-computing-vs-edge-computing/), for example. We'd prefer to maintain our blog content as the primary educational source on this topic within our web properties. Please feel free to suggest an alternate topic to explore.
