### ISSUE TITLE
How to create tidy data with tidyr package in R.

### ISSUE THREAD

**Issue by Madrinmarison** [section-engineering-education/engineering-education#1657]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Introduction paragraph(s):
Tidyr is a package in R that is used to organize data in consistent way for easy visualization using visualization tools such as ggplot2 package. In this article, i will explain all steps involved in creating an organised datasets using tidyr package.

### Key takeaways: 
1. The reader will learn what's untidy data and how to identify if a dataset is untidy.
2.The reader will learn the reasons why some of datasets are untidy.
3. Finally learner will learn how to to create a tidy dataset from untidy one.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Madrinmarison . There are some grammar/readability issues in the description that you've provided. We do not provide editing services and these topic suggestions are a way for us to understand the level of review that may be required.

We are unable to accept this topic as proposed, but please feel free to spend some time cleaning up and expanding on this topic suggestion to help us better assess the readability and substance of your proposed article. When you are ready, you may request that this issue be reopened. Thank you.

**Comment by Madrinmarison** [comment]
@ninjaginja Data tidying is a consistent way to organize dataset in R. A fully organized dataset is called Tidy Data. It one of the essential steps in data preparation because visualization tools such ggplot2 package for data visualization work with organized data. Therefore it makes it easy for data manipulation and analysis. We achieve tidy data in R through the use of the tidyr package. In the article, I will explain how to organize a messy dataset using various functions in the tidyr package.
