### ISSUE TITLE
Introduction to LXD Container Manager

### ISSUE THREAD

**Issue by domiwanja** [section-engineering-education/engineering-education#1658]
### Proposed title of article

Introduction to LXD Container Manager

### Introduction paragraph(s):

LXD is a next-generation system container manager. It uses Linux containers to provide individuals with a unique experience.  LXD is image-based and supported by numerous Linux distributions. Furthermore, it is powerful, intuitive, and scalable. The LXD project was founded and is currently led by Canonical Ltd with contributions from other developers.

LXD's key features include advanced resource control, network management, storage management, device passthrough, and support for cross-host containers. This article provides a detailed overview of LXD technology.

### Key takeaways: 

- Understand what LXD entails
- Key features of LXD
- Benefits of LXD
- LXD's releases.

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @domiwanja. Could you please expand upon how your content will differ from what is already available through the LXD website and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by domiwanja** [comment]
I will provide a step by step guide  on how to use LXD container manager.

**Comment by domiwanja** [comment]
@ninjaginja can I go ahead and write about the topic?

**Comment by hectorkambow** [comment]
@domiwanja  

👍  a step by step guide is always welcome - it may be more appealing to the community if it was used in a real use case along with your guide. 

topic approved.
