### ISSUE TITLE
An Introduction to KNN Algorithm

### ISSUE THREAD

**Issue by srishilesh** [section-engineering-education/engineering-education#1659]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
**An Introduction to KNN Algorithm**

### Introduction paragraph(s):
In this article, we will learn about a supervised machine learning algorithm called K-Nearest Neighbors (KNN). We will learn about where this algorithm can be used, give a comparison with other supervised algorithms, and we will also be building a KNN algorithm from scratch.

KNN is a supervised machine learning algorithm which is primarily used for classification, but also can be used in regression. This algorithm is also called lazy learning, non-parametric algorithm, which uses several classes to classify the unseen data.

### Key takeaways: 
- The reader will learn about the nuts and bolts of KNN supervised algorithm.
- The reader will learn about its working and will understand where it can be used
- The reader will also learn to build the KNN algorithm from scratch.

### References: 
- https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm
- https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

**Comment by ninjaginja** [comment]
good topic @srishilesh - approved
