### ISSUE TITLE
How to handle outliers in R.

### ISSUE THREAD

**Issue by Daniel695** [section-engineering-education/engineering-education#1660]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### How to handle outliers in R.
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction
Outliers are values in a dataset that they fall at extreme levels from bulky of data distribution. Therefore, they need to be handled before the data is visualized so as to eliminate chances of biasness in the process of data analysis.
Therefore in this article I'll explain all steps involve in dealing with outliers.
### Key takeaways: 
1. Leaner will know how to identify outliers in dataset.
2. Leaner will know the condition under which an outliers is useful and when it's not useful.
3. Learner will then learn the methods used in treating them.
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Daniel695. There are some grammar/readability issues in the description that you've provided. We do not provide editing services and these topic suggestions are a way for us to understand the level of review that may be required.

We are unable to accept this topic as proposed, but please feel free to spend some time cleaning up and expanding on this topic suggestion to help us better assess the readability and substance of your proposed article. When you are ready, you may request that this issue be reopened. Thank you.

**Comment by Daniel695** [comment]
@ninjaginja 
Outliers are values which are distant from the most of observation. They disort prediction and affect accuracy of models if are not detected and handled appropriately.
In the article, I'll explain how to detect and removing them from a data distribution using R.
