### ISSUE TITLE
Applying AI and Machine Learning to predict customer behavior

### ISSUE THREAD

**Issue by skay-ai** [section-engineering-education/engineering-education#1663]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
**Role of AI in Futuristic Digital Marketing**

### Introduction paragraph(s):
Artificial Intelligence is changing the face of digital landscape in the recent past. AI can analyze data to easily predict the buying behaviors and decisions of target customers and also improve user experience to provide the audience what they actually need.

In this article, we will learn about how AI has helped in understanding customers better. We will also learn about various tools and technologies which helps in Data analysis for providing better insights on consumer behavior.

### Key takeaways: 
- Reader will understand the importance of AI and its deployment in understanding targeted customers better for their buying behaviors and decisions
- Reader will also understand how AI helps to improve user experience
- Reader will learn about various data analysis tools and technologies

### References: 
- https://www.nihtdigitalmarketing.com
- https://www.smartinsights.com

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @skay-ai, however this is outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore.

**Comment by skay-ai** [comment]
@ninjaginja 
Just to clarify. In this article, though I will be giving an overview about AI for Marketing, I will also cover technical concepts related to AI and ML. For example, in recommendation systems, I would explain about concepts like collaborative filtering and content based filtering, which is being used in ecommerce industries to improve their marketing strategies. Also, I would explain code snippets related to it.

Something like these:
- https://www.kaggle.com/panpolikarp/customer-insights-collaborative-filtering
- https://www.kaggle.com/c/ga-customer-revenue-prediction

I believe the article title that I have chosen might have confused you. It would be great if you could suggest an alternative title for this article.

Thank you.

**Comment by ninjaginja** [comment]
Thanks for the clarification @skay-ai. Perhaps an appropriate title might be, "Applying AI and machine learning to predict customer behavior"? Or, feel free to suggest an alternate title based on how your content develops.

**Comment by hectorkambow** [comment]
@skay-ai 👋  

just wanted to follow up on this topic as I'm clearing up the queue where possible?

**Comment by skay-ai** [comment]
@hectorkambow 

I'm working on this article currently. Will create a PR in 2 days.

Thanks

**Comment by hectorkambow** [comment]
Just closing this PR for now to clear the queue - we can reopen it as soon as the PR is ready 👍
