### ISSUE TITLE
Hash Tables in JavaScript

### ISSUE THREAD

**Issue by JudyNduati** [section-engineering-education/engineering-education#1664]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Hash Tables in JavaScript

### Introduction paragraph(s):
Hash tables are an extremely useful data structure, which allows you to store data using key-value pairs. Hash tables store data in associative arrays. 
In JavaScript objects and maps provides an efficient hash table structure. The key inputs run through a hash function. It maps the strings to numbers and numbers correspond to indexes in an array.
This article will make you understand hash tables in JavaScript, how they work, and their implementation

### Key takeaways: 
1. What are hash tables?
2.  How hash tables work
3. Handling collisions
4. Implementing hash tables

### References: 
https://www.udemy.com/course/js-algorithms-and-data-structures-masterclass/
https://www.freecodecamp.org/news/how-to-implement-a-simple-hash-table-in-javascript-cb3b9c1f2997/
https://javascript.plainenglish.io/algorithm-in-javascript-hash-table-7b0464d2b81b

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @JudyNduati - approved
