### ISSUE TITLE
TypeScript: Overview and Types

### ISSUE THREAD

**Issue by cyberShaw** [section-engineering-education/engineering-education#1665]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
An Introduction to TypeScript Types

### Introduction paragraph(s):
TypeScript is an open-source programming language that exists as a superset of JavaScript. It builds up on JavaScript, which is one of the world's most popular programming languages by adding static typing. Let us dive into why TypeScript is useful, and how to use the TypeScript compiler and tooling.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

- The reader will get an overview of what problem TypeScript solves
- The reader will also understand the various types in TypeScript
- The reader will also get a hands-on with TypeScript and will be walked through the workflow of compiling a TypeScript program.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
https://www.typescriptlang.org/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
👋  
@cyberShaw  

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

Please pick one topic and close the other 👍

**Comment by cyberShaw** [comment]
Understood, @hectorkambow. Can I close the other one for now, so that I can re-open it once I've finished up with this article?

**Comment by cyberShaw** [comment]
Is this article approved? Can I start working on the article? @hectorkambow ?

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @cyberShaw, however it looks like this topic has already been sufficiently covered in this previously published article - https://www.section.io/engineering-education/a-friendly-beginner-guide-to-typescript/. Please suggest a different topic area to explore. Thank you.

**Comment by cyberShaw** [comment]
Hey @ninjaginja. Understood, I've created another issue that is a different topic (just re-opened it)
