### ISSUE TITLE
Implementing Rate Limiting in Flask APIs

### ISSUE THREAD

**Issue by LordGhostX** [section-engineering-education/engineering-education#1667]
### Introduction paragraph(s):
Rate limiting is a strategy for limiting network traffic in a system. It puts a cap on how often someone can repeat an action within a certain timeframe. In this article, we will be going over what rate limiting is, the advantages of limiting network request rates, and explore how to implement rate-limiting in Flask APIs.

### Key Takeaways:
By the end of this tutorial, the reader will be able to:
* define what rate limiting is.
* understand the importance of limiting request rates in APIs.
* build Flask APIs that limit the rate of requests received.

### References:
* https://pypi.org/project/ratelimit/

**Comment by ninjaginja** [comment]
good topic @LordGhostX - approved
