### ISSUE TITLE
Building an Appointment Scheduling Telegram Bot with Python and Fauna

### ISSUE THREAD

**Issue by Chukslord1** [section-engineering-education/engineering-education#1669]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Building an Appointment Scheduling Telegram Bot with Python and Fauna

### Introduction paragraph(s):
Have you ever wanted to build a telegram bot that would allow you to schedule or plan your appointments and get reminded on time for them? If your answer is yes, then this article is just what you need. We would also be utilizing a serverless database system called FaunaDB to build our system which will make our work easier. Now we are versed with what this article entails, let's get to the building part.

### Key takeaways:
Readers will learn how to work with the python telegram API.

Readers would be engaged with building an appointment scheduling bot for themselves with python.

Readers would learn how to utilize and manipulate the database using Fauna.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @Chukslord1 - approved
