### ISSUE TITLE
Why You Should Learn Flutter

### ISSUE THREAD

**Issue by wobin1** [section-engineering-education/engineering-education#1671]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph(s):
Flutter is a tool kit created by Google. It is used to develop applications for android, IOS, Linux, Mac, Windows, Google fuchsia, and the web from a single codebase. This technology is changing the Software development industry by making application development faster and cheaper.
In this article, we will understand why Flutter is gaining recognition by developers all over the world and why you should consider learning the technology.
### Key takeaways: 
The reader will understand;
1. What Flutter really is.
2. Why its best for Startups.
3. Tech Giant Using Flutter. 
4. Why He/She should Learn Flutter.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @wobin1, but we're currently leaning more heavily towards practitioner-focused content that takes a deeper technical dive into programming-centric topics/tutorials. Please feel free to suggest an alternate topic to explore. Thank you.
