### ISSUE TITLE
A brief explanation of CSS animation properties with sample codes.

### ISSUE THREAD

**Issue by prince-joel** [section-engineering-education/engineering-education#1672]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
A brief explanation of CSS animation properties with sample codes.

### Introduction paragraph(s):

In this article, you will learn about CSS animation properties, and how they can be used in animating simple 2d shapes. This article gives the readers an introduction to basic CSS animations by explaining the different CSS animation properties along with examples of how they can be implemented using sample codes.

Animation is used to manipulate images, texts, and characters to move and style them. CSS can be used to animate HTML elements and other CSS properties using animation properties.

### Key takeaways: 

* The reader would learn about CSS animation properties.
* The reader would learn how to utilize CSS animation properties in animating simple 2d shapes.
* The reader would learn how CSS animations work with HTML elements.

### References: 

N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @prince-joel. Your proposed article seems to cover a very broad topic. Are you able to narrow the focus a bit? Perhaps you could structure a tutorial around building a specific type of animation using CSS?

**Comment by prince-joel** [comment]
@ninjaginja I have updated my article pitch to be more focused on a particular topic which is explaining CSS animation properties.
