### ISSUE TITLE
Classes, Methods and Constructors in TypeScript

### ISSUE THREAD

**Issue by cyberShaw** [section-engineering-education/engineering-education#1673]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*
Classes, Methods and Constructors in TypeScript

### Introduction paragraph(s):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

A class is one of the most important tools used in Object Oriented Programming. It can be defined as a blueprint of an object. Classes are supported from the ES6 version of JavaScript and also in TypeScript. Let us dive into the various powerful features that we get in TypeScript for working with classes, methods and constructors in TypeScript.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

- The reader will get a hands-on to declaring classes, methods and constructors in TypeScript.
- The reader will be introduced to using type declarations within method parameters and member variables.
- The reader will also be given a comparison to JavaScript and would be able to get a solid idea about the differences.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
https://www.typescriptlang.org/docs/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Closing for now

**Comment by cyberShaw** [comment]
Hey, @hectorkambow @ninjaginja could you guys approve this? My other topic issue has been closed because there's already another similar topic

**Comment by ninjaginja** [comment]
@cyberShaw It seems that this topic has already been sufficiently covered in this previously published article - https://www.section.io/engineering-education/a-friendly-beginner-guide-to-typescript/. Please select a different topic area to explore. Thank you.
