### ISSUE TITLE
An introduction to Neumorphism UI in android studio

### ISSUE THREAD

**Issue by Rose-stack** [section-engineering-education/engineering-education#1674]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
An introduction to Neumorphism UI in android studio

### Introduction paragraph(s):
This is a design trend concept used to make soft Widgets based on object shadows. It uses highlights and shadows to create UI elements that appear as if they were floating above the surface. In this concept design object seems to extrude from the background.

Neumorphism leans heavily on layers, shadows, and angles to dictate hierarchy and context while embracing a minimal design.

Neumorphism began from design concepts posted on Dribble. One of these designs was posted by [Alexander Plyuto](https://dribbble.com/shots/8557373-Skeuomorph-Mobile-Banking-Dark-Mode).

Neumorphism concepts have led to the development of products like UI kits, tutorials, and libraries to fit in various development platforms such as [CSS](https://www.youtube.com/watch?v=PLTJr7fLv4E), [Dart](https://www.youtube.com/watch?v=OR2DMRnEXkA)(Flutter UI), [SwiftUI](https://www.youtube.com/watch?v=z3tJdxwlo_Y), etc. In this guide, we'll discuss how to implement Neumorphism UI designs in android studio with hand on examples. 

### Key takeaways: 
What is Neumorphism
Background
How Neumorphism works
Implementating Neumorphic UI in android studio
Usage

### References: 
Design concept: https://dribbble.com/shots/8557373-Skeuomorph-Mobile-Banking-Dark-Mode
https://github.com/fornewid/neumorphism
https://uxdesign.cc/neumorphism-in-user-interfaces-b47cef3bf3a6

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Rose-stack , however this is outside of our preferred topic areas. We lean more heavily towards programming-centric topics as opposed to design-centric topics. Please feel free to suggest an alternate topic area to explore.

**Comment by kimkimani** [comment]
@molly80 ,this is a programming tutorials using Android studio

**Comment by Rose-stack** [comment]
@ninjaginja This a programming tutorial using android studio, It employs the concept of Neumorphism to develop an android application.

**Comment by Rose-stack** [comment]
@ninjaginja Changed the Tittle a little bit to "How to implement Neumorphism UI in the android studio"
