### ISSUE TITLE
ruby-recursion 

### ISSUE THREAD

**Issue by ianmaish** [section-engineering-education/engineering-education#1675]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
ruby-recursion 

### Introduction paragraph(s):
This article will help understand how to implement recursion in ruby. recursion is when a method calls itself. understand simple recursive calls and complex ones used to solve calculations. anatomy of a recursive method and how the recursive calls work. recursion allows us to divide larger problems into similar smaller problems that are easy to solve. 
we will also understand the difference between recursion and iteration, how to use them to solve different operations using either of them   

### Key takeaways: 
1. The reader will learn to use a recursive method to solve complex calculations. 
2. the reader will learn the difference between recursion and iteration. 
3. understand infinite loops and learn strategies for programming recursively. 
### References: 
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @ianmaish . There are some grammar/readability issues in the description that you've provided. We do not provide editing services and these topic suggestions are a way for us to understand the level of review that may be required.

We are unable to accept this topic as proposed, but please feel free to spend some time cleaning up and expanding on this topic suggestion to help us better assess the readability and substance of your proposed article. When you are ready, you may request that this issue be reopened. Thank you.
