### ISSUE TITLE
Working with Python's unittest

### ISSUE THREAD

**Issue by st3v3nmw** [section-engineering-education/engineering-education#1676]
### Introduction paragraph(s):
In software engineering, a unit test refers to a program used to automatically check for bugs in individual parts/units of a software. A developer specifies a set of testcases which consists of a function call to a particular unit and the expected result for comparison. Since unit testing is important, most programming languages provide inbuilt unit testing frameworks. In this article, we'll focus on Python's unittest. 

### Key takeaways: 
1. An introduction to unit testing
2. An introduction to regression testing
3. An explanation on how to use Python's unittest module
4. An explanation on the benefits of unit testing
5. A comparison of unittest with other Python testing frameworks

### References: 
1. [Python documentation on the unittest module](https://docs.python.org/3/library/unittest.html)

**Comment by ninjaginja** [comment]
good topic @st3v3nmw - approved
