### ISSUE TITLE
Building your Web Server with Vlang

### ISSUE THREAD

**Issue by Umoren** [section-engineering-education/engineering-education#1677]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of the article
Building your Web Server with Vlang

### Introduction paragraph (2-3 paragraphs):
One language that has gotten a considerable amount of recognition recently by programmers most especially backend developers is Vlang. V is a statically typed programming language inspired by Rust, Go, Oberon, Swift, Kotlin, and Python. It is open-sourced and claims to be very easy to learn.
V takes a more strict approach to everything compared to Go and Rust. For instance, they are no global variables, no null, no undefined values, functions are pure by default, uses structs rather than objects and variables are immutable. 

### Key takeaways: 
-  Introduce Vlang and core features
-  Understand V basics and write first V program
- Using V on the web
    - Building a web server with V
    - Why you should use V  (and contribute to its development)

### References: 
- https://vlang.io/
- https://hackaday.com/2019/07/23/the-v-programming-language-vain-or-virtuous/, 
- https://christine.website/blog/vlang-update-2020-06-17, and 
- https://christine.website/blog/v-vaporware-2019-06-23

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @Umoren - approved. One important note: Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)

**Comment by Umoren** [comment]
Thanks @ninjaginja 
I have submitted the initial draft
https://github.com/mbaabuones/engineering-education/pull/1
