### ISSUE TITLE
How to make an Image Carousell  for your website using basic HTML,CSS and Javascript.

### ISSUE THREAD

**Issue by KanizoRGB** [section-engineering-education/engineering-education#1678]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Title
How to make an Image carousel using basic HTML,CSS and Javascript.

### Introduction paragraph (2-3 paragraphs):
An Image Carousel is like a container of Images which the user can select through by clicking a buttons which directs him forward or backwards in the collection of images. It enables the website to be more interactive and hence enhance the user experience. The collection of Images can be set to change automatically by use of a timer or manually when the user clicks the displayed buttons. This is kind of a fun exercise to beginners in web development to test their prowess.

### Key takeaways: 
After reading this article, the user will have gained the following:
1.An understanding of HTML since it is among the prerequisites.
2.An understanding of CSS and its use in making a web-page stylish.
3.An understanding of Javascript and its use in adding more functionality to a web page.
4. How to interweave the understanding of the three languages to make their web pages more interactive,stylish and appealing to the eye.

### References: 
https://www.w3schools.com/tags/att_script_src.asp

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by KanizoRGB** [comment]
topic suggestion

**Comment by ninjaginja** [comment]
good topic @KanizoRGB - approved
