### ISSUE TITLE
Getting Started With WebRTC and Firebase

### ISSUE THREAD

**Issue by NgukuAmos** [section-engineering-education/engineering-education#1681]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Getting Started With WebRTC and Firebase

### Introduction paragraph (2-3 paragraphs):
Work from home has been a boom these days. This has been made possible by using various streaming applications
to facilitate communication. For a web developer, WebRTC is an API that is used to build a real-time peer-to-peer connection
between two or more browsers. It is a native browser API and works without the need for a third-party server or native app.

WebRTC facilities real-time audio/video communication on the web using a peer-to-peer protocol, 
allowing you to build apps like Zoom, Skype, etc. In this tutorial, we will use JavaScript and Firebase as the signaling server to build a simple video chat application.

### Key takeaways: 
1. Introduction to WebRTC

2. How WebRTC works

3. How to use WebRTC API with Firebase

### References: 
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
great topic @NgukuAmos - approved

**Comment by hectorkambow** [comment]
@NgukuAmos 
just wanted to follow up on this topic as I'm clearing up the queue where possible?

**Comment by hectorkambow** [comment]
Can be re-opened when needed
