### ISSUE TITLE
How to render HTML pages as an HTTP server response Using Node.js

### ISSUE THREAD

**Issue by mosesreigns** [section-engineering-education/engineering-education#1682]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
How to render HTML pages as an HTTP server response Using Node.js

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

When developing web applications, you might need to render the HTML components to the user as the server response. There are various ways of hosting your HTML pages (website), for example;

- Rendering your client-side on its own using like a framework for such as React or,
- Rend the pages directly from the server when the browser tries to access some routes specified in your server.

This guide will teach you how to render HTML elements and HTML pages as server response-using Node.js.

### Prerequisites

Basic knowledge of using [Node.js](https://www.youtube.com/watch?v=fBNz5xF-Kx4) and [Express.js](/engineering-education/express/)

### Setting up

- [Download Node.js](https://nodejs.org/en/) and install it. Run `node -v` to test if the installation was successful.

```bash
$ node -v
v12.18.3 ## installed node.js version
```

- Create a Node.js project/directory. Initialize the project within the directory you have created. Use `npm init -y` to automatically initialize this Node.js project or check this [guide](/engineering-education/beginner-guide-to-npm/) to learn more about using NPM.
- Install the Express framework using `npm install express`. Express is. Check this [guide](/engineering-education/express/) to learn more about of Express.
- We will create a server using Express. You may want to hook the server with Nodemon. It is an optional package (installed globally) which automatically restarts the server after saving any server-side code changes. Go ahead and install Nodemon using `npm install -g nodemon`. Check this [guide](https://www.npmjs.com/package/nodemon) to learn more about Nodemon.
- 
### Key takeaways: 
- Prerequisites
- Setting up
- Rendering inline Html elements as HTTP response
- Render HTML web pages as server response
- Parsering form data to the server using the HTML forms
- Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

[Node.js](https://www.youtube.com/watch?v=fBNz5xF-Kx4) and [Express.js](/engineering-education/express/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @mosesreigns  - approved. Please note that if you opt to go all the way through the deployment process with this tutorial, you may illustrate the process using Section's [Node.js Edge Hosting](https://www.section.io/modules/nodejs-edge-hosting/) solution.
