### ISSUE TITLE
A beginners guide to Next.js Framework

### ISSUE THREAD

**Issue by EssyWanjira** [section-engineering-education/engineering-education#1683]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
A beginners guide to Next.js

### Introduction paragraph (2-3 paragraphs):
React.js has been one of the most influential UI libraries in front-end development. Being in the developer community has led to a revolution in how we build client-side applications. It uses a component-based approach to build robust applications.

Next.js is an open-source React front-end development web framework that enables functionality such as server-side rendering and generating static websites for React-based web applications. Next.js gives the best developer experience with all the features needed for production such as hybrid static & server rendering, TypeScript support, smart bundling, route pre-fetching, and more with no configurations needed. In this article, we will go through an in-depth beginner's guide to Netx.js.

### Key takeaways: 
1. Understanding what is Next.js

2.  How to set up a Next.js Framework

3. What Static Site Generation is

4. What Server Side rendering is

5. Benefits of using Next.js 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @EssyWanjira , but it seems there is quite a bit of overlap with content from this previously published article - https://www.section.io/engineering-education/node-versus-next-react-approach/. Please feel free to either refine your focus or suggest a different topic area to explore. Thank you.
