### ISSUE TITLE
Reading pdf and old images to text using django easy

### ISSUE THREAD

**Issue by yitzackRabin** [section-engineering-education/engineering-education#1684]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Reading pdf and old images to text using django easy
### Introduction paragraph (2-3 paragraphs):

Django is a Python-based free and open-source web framework that follows the model-template-views architectural pattern
It always been hard to read old images and pdf to text file but django framework makes it easy reading it. This is by use of famous library I.e tesseract sponsored by google with famous tool OCR (Optical Image Recognition). 
we'll read images to text files and also get good understating working with OCR over pdf document to extract the text file.  
### Key takeaways: 
1. Brief introduction to django
2. Introduction to reading images and pdf in django easy
3. building a simple application to read files to text using django
4.  Working with OCR in Django
5. Understanding the use of tesseract library 
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @yitzackRabin. Could you please expand upon your introduction by providing a couple more paragraphs that go into a little deeper detail around what you intend to cover?
