### ISSUE TITLE
How to use Dictionaries to convert Emoji in python

### ISSUE THREAD

**Issue by majiezra** [section-engineering-education/engineering-education#1687]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
How to use Dictionary to convert Emoji in python
### Introduction paragraph (2-3 paragraphs):
this tutorial will help both beginners and intermediates in python programming language to the get the basic concept of dictionary in python and then show us how it can be use as an emoji converter during programming. 

### Key takeaways: 
- a quick recall of python basis
- The reader should know the uses of dictionaries
- To be able use python dictionary as an emoji converter

### References: 
[learn python](https://www.learnpython.org/)
Python for beginners udemy
the python book by aaron asadi

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @majiezra. We request that you provide more in-depth detail, with grammar/readability in mind when suggesting topics. Please take some time to polish and expand upon what you intend to cover in this article, and you may request to reopen this issue once you've updated it. Thank you.
