### ISSUE TITLE
How Load Datagridview With Data From MySQL Database Using C#

### ISSUE THREAD

**Issue by tambastar** [section-engineering-education/engineering-education#1689]
How to implement Datagridview in C#

Introduction paragraph(s):
In this article will learn about Datagridview control and connecting it with the MySQL database. Datagridview is highly configurable and extensible, and it provides many properties, methods, and events to customize its appearance and behavior based on user requirements.
The tutorial will use the MySQL database as the main data source.

Key takeaways:
By the end of this tutorial, the reader will be able to:

1. Create a winform application
2. Create MySQL database
3. Connect C# application with MySQL database
4. Load data to the DatagridView
5. Run DatagridView Events

References:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridview?view=net-5.0

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @tambastar. The title and description that you've provided triggered some grammar/readability concerns. We do not provide editing services and these topic suggestions are a way for us to understand the level of review that may be required.

We are unable to accept this topic as proposed, but please feel free to spend some time cleaning up and expanding on this topic suggestion to help us better assess the readability and substance of your proposed article. When you are ready, you may request that this issue be reopened. Thank you.
