### ISSUE TITLE
Understanding Matlab plots

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#1697]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Introduction paragraph(s):
Matlab plot is a graphical representation of a given set of data. Matlab is very useful for making scientific and engineering plots. You can create plots of known, analytical functions, you can plot data from other sources such as experimental measurements, you can analyze data, perhaps by fitting it to a curve, and then plot a comparison. Matlab also has powerful built-in routines for drawing contour and three-dimensional plots. In the article, I will take the reader through various plots that are available in Matlab.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.
1. The reader will be able to create simple plot from matrix data.
2. The reader should understand the various types of plots.
3. The reader should understand the various plot commands and the application
4. The reader will be able to create complex plots such as distribution and mesh plots.
 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @jumapaul, however it seems that this topic has already been sufficiently covered in this article - https://www.section.io/engineering-education/getting-started-with-matlab/. Please feel free to suggest a different topic area to explore.
