### ISSUE TITLE
How to Create a Responsive Form Using Tailwind CSS

### ISSUE THREAD

**Issue by M0nicah** [section-engineering-education/engineering-education#1701]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
How to Create a Responsive Form Using Tailwind CSS

### Introduction paragraph (2-3 paragraphs):
HTML forms are an integral part of a web application. They are a crucial tool for interacting with users. It is, therefore important to make them appealing, presentable and responsive. This can be achieved by styling using plain CSS. It is, however possible to achieve this easily using CSS frameworks such us Bootstrap and Tailwind. This article goes through creating and styling responsive forms using Tailwind CSS framework.

### Key takeaways: 
1. Understand how to make create responsive forms using tailwind CSS. 
2. Understand how to easily style forms and form inputs using tailwind CSS.
3. Understand how making a form appealing and presentable improves the quality of a website. 

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @M0nicah - approved
