### ISSUE TITLE
Implementing AWS S3 functionalities on a Node.js GraphQL API

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#1703]
### Proposed title of article
Implementing AWS S3 functionalities on a Node.js GraphQL API

### Introduction paragraph (2-3 paragraphs):
AWS is  a cloud service provider developed by Amazon. S3 is the storage service provided by AWS. GraphQL is a server-side runtime for executing operations on type defined data. AWS Node.js SDK is a package that enables implementation of various services from AWS on a Node.js application.
In this article, we will implement basic s3 functionalities provided by AWS Node.js SDK.
### Key takeaways: 
- The reader will be able to know how to create an s3 bucket.
- The reader will be able to know how to upload a file or multiple files to s3 bucket.
- The reader will be able to know how to delete a file or multiple files from s3 bucket.

### References: 
- https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-node-examples.html

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @mwangiKibui, however this topic seems to have some overlap with competing technology to Section, and we prefer not to highlight competitive offerings. I'd invite you to explore Section's [Node.js Edge Hosting](https://www.section.io/modules/nodejs-edge-hosting/) solution to see if you might be interested in adapting this idea using Section's tooling.

**Comment by ninjaginja** [comment]
Apologies @mwangiKibui, after re-evaluating this topic, I think it's probably within the parameters of how we evaluate content featuring competitive offerings. You may go ahead with this topic if you'd like and again, sorry for the confusion.

**Comment by mwangiKibui** [comment]
Thank you @ninjaginja
