### ISSUE TITLE
The Basics of Genetic Algorithm in Machine Learning

### ISSUE THREAD

**Issue by artmuth** [section-engineering-education/engineering-education#1704]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
The Basics of Genetic Algorithm in Machine Learning

### Introduction paragraph (2-3 paragraphs):
Genetic algorithm is a search-based algorithm used for solving optimization problems in machine learning. This algorithm is important because it solves difficult problems that would take a long time to solve. It has been used in various real-life applications such as data centers, electronic circuit design, code-breaking, image processing, and artificial creativity. 

This article takes you through the basics of this algorithm and explains how it works. It also explains how it has been applied in various fields and highlights some of its limitations. 

### Key takeaways: 
1. Genetic algorithm (GA) explained (including basic terminologies)
2. Advantages of genetic algorithm
3. The structure of genetic algorithm
4. How genetic algorithm works (including operators)
5. Application areas
6. Limitations of genetic algorithm

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. N/A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @artmuth - approved
