### ISSUE TITLE
How to Become a Prominent Python Programmer

### ISSUE THREAD

**Issue by annwawesh** [section-engineering-education/engineering-education#1705]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
How to Become a Prominent Python Programmer

### Introduction paragraph (2-3 paragraphs):
Python is used extensively in various fields such as web development, data science and machine learning. If you are a programmer or developer, having a good understanding of Python programming language is important for your career growth. Learning this language equips you with the right coding skills for solving various global challenges. 

This article provides important tips for becoming a prominent python programmer. It also guides readers on the best practices for using Python. 

### Key takeaways: 
1. An overview of Python programming
2. Why Python?
3. Tips for becoming a prominent Python programmer
4. Best practices for using Python
5. Summary table
6. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A.
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @annwawesh, however this topic is more broad than we typically prefer. We're more interested in original, programming-centric content that takes a practitioner's approach to solving specific developer challenges. Please feel free to suggest a different topic area to explore.
