### ISSUE TITLE
Implementing Fingerprint Authentication in Android applications.

### ISSUE THREAD

**Issue by BrianaNzivu** [section-engineering-education/engineering-education#1706]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of the article
Implementing Fingerprint Authentication in Android applications.

### Introduction paragraph (2-3 paragraphs):
Let's admit it, typing over eight characters in the name of a password is quite a task that is if a user even remembers the password. These days most developers and companies have made it easier for us by using biometrics as a form of authentication. Biometrics time and again has proved to be more efficient and less prone to cyber-attacks. This article will cover one of the biometric ways for authentication which is using our fingerprint.

### Key takeaways: 

1.What is Authentication?
2.The reader is meant to understand what is biometrics and various applications of biometrics.
3.The user is meant to understand how to implement fingerprint authentication in android applications.

### References: 
1.https://www.androidauthority.com/how-to-add-fingerprint-authentication-to-your-android-app-747304/
2.https://developer.android.com/training/sign-in/biometric-auth

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @BrianaNzivu - approved

**Comment by hectorkambow** [comment]
👋  @BrianaNzivu  

Good evening Briana - just wanted to follow up on this topic as I'm clearing up the queue where possible?

**Comment by BrianaNzivu** [comment]
> 👋  @BrianaNzivu  
> 
> Good evening Briana - just wanted to follow up on this topic as I'm clearing up the queue where possible?
> 

@hectorkambow Good morning- Planning on submitting the PR by today latest tomorrow.
I am sincerely sorry for the delay I have been a little bit held up for the past two months.

**Comment by hectorkambow** [comment]
merged
