### ISSUE TITLE
Introduction to Next.js

### ISSUE THREAD

**Issue by katungi** [section-engineering-education/engineering-education#1707]
### Proposed title of article
Introduction to Next.js

### Introduction paragraph (2-3 paragraphs):
React.js is becoming one of the most popular frameworks in the developer community. It's component based approach to handling frontend development has made is easy for developers to build robust applications very fast. Other frameworks that add to React's capabilities have also come up. The popular ones are Gatsby which is a static site generator and Next.js which was created by Vercel and has been adopted by big players in the tech space like tiktok.

In this article, We will look at the key differences or the key additional features Next.js brings to the React ecosystem and how they make your life as a developer easier. We will look at how to boostrap a Next.js application, we will look at the key concepts like static site generation and server side rendering that Next.js offers, and finally build a demo to see Next.js in action.

### Key takeaways: 
By the end of the tutorial, the reader will have learned :

- How to create a Next.js application
- What Static Site Generation is
- What Server Side rendering is
- How to build a simple application in Next.js

### References: 
https://nextjs.org/docs/getting-started

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @katungi  , but it seems there is quite a bit of overlap with content from this previously published article - https://www.section.io/engineering-education/node-versus-next-react-approach/. Please feel free to either refine your focus or suggest a different topic area to explore. Thank you.

**Comment by katungi** [comment]
Hello @ninjaginja I read this article and some of the concepts are well explained. However, I was hoping to rather show the reader the concepts in practice.
