### ISSUE TITLE
Google OAuth in React Native Application using Firebase

### ISSUE THREAD

**Issue by zolomohan** [section-engineering-education/engineering-education#1708]
### Proposed title of the article

Google OAuth in React Native Application using Firebase

### Introduction paragraph(s):
OAuth is an open standard for access delegation, commonly used as a way for Internet users to grant websites or applications access to their information on other websites but without giving them the passwords.

In this tutorial, we will learn how to authenticate users with their Google accounts using the authentication module in Firebase in a Non-Expo React Native application.

### Key takeaways

- Set up Firebase Project for Google OAuth.
- Add Login/Create account screen.
- Use the Firebase Auth module and authenticate users.
- Logout from the authenticated screen.

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @zolomohan - approved
