### ISSUE TITLE
Structuring Large Application in Flask

### ISSUE THREAD

**Issue by corpsgeek** [section-engineering-education/engineering-education#1709]
### Proposed title of article
Structuring Large Application in Flask

### Introduction paragraph (2-3 paragraphs):
This article will explain and illustrate how to structure web applications on a large scale with the Python Flask backend web framework.

### Key takeaways: 
- Structure Large Applications
- Implementing Blueprints
- Configuration and Application Factory Options
- Launch Script
- Requirements File
- Database Setup

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you @corpsgeek, but we request that you provide more detailed descriptions in your topic suggestions, including the first 2-3 paragraphs of your proposed article (pre-edited for grammar/readability). Please take some time to expand upon your description and resubmit when ready.
