### ISSUE TITLE
How To Deploy React Applications To Firebase Using GitHub Actions

### ISSUE THREAD

**Issue by marienjus** [section-engineering-education/engineering-education#1711]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
How To Deploy React Applications To Firebase Using GitHub Actions

### Introduction paragraph (2-3 paragraphs):
CI/CD is a way of developing software in which you're able to release updates at any time in a sustainable way. The idea is to replace stressful releases and manual testing with routine, daily updates, and automated testing. Github Actions is an awesome tool to automate such tasks. 
In this tutorial, we will build a simple React  app and automate the deployment process to Firebase. Firebase is a Baas platform developed by Google for creating mobile and web applications.

### Key takeaways: 
1. Introduction to CI/CD
2. How to use GitHub Actions
3. Configuring Firebase for a React Application
4. Building a simple React app and deploy to Firebase hosting 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @marienjus, however this topic seems to have some overlap with competing technology to Section, and we prefer not to highlight competitive offerings. I'd invite you to explore Section's Node.js Edge Hosting solution to see if you might be interested in adapting this idea using Section's tooling.
