### ISSUE TITLE
 How to send emails in a Django application using SMTP server

### ISSUE THREAD

**Issue by Anitaachu** [section-engineering-education/engineering-education#1715]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Introduction paragraph(s):
Google gmail provides an excellent way where emails can be sent using the SMTP server.
Simple Mail Transfer Protocol (SMTP) is an internet standard communication protocol for electronic mail transmission. There are a lot of free SMTP servers which can be used to send mails, however this article focuses on Google SMTP Server. 
Google SMTP server provides for a means where mails can be sent without having to manage your own outgoing mail server. 

In an application mails such as a password reset link, invitation or any other information are essential and these can be sent using the google SMTP server. 
While building an application, for example a user login in page, the password reset email is usually sent to enable the user to retrieve or set a new password. The major advantage of google SMTP server is that it provides a means for the password of the developer to stay hidden using the app passwords methods. This tutorial would primarily focus on how the google SMTP server works and how to add SMTP to your Django app to send a password reset mail  to users. 

### Key takeaways: 
1. Understand what SMTP server means
2. Have knowledge of other free SMPT servers
3. Learn how google SMTP server and set app passwords.
4.  Send a password reset mail to a user in a Django application
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
none
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Anitaachu, but it seems there might be quite a bit of overlap with the fundamentals of the article being worked on in #1640. We'd prefer that you select a different topic area to explore.
