### ISSUE TITLE
Developing a one-to-one mapping application leveraging hibernate.

### ISSUE THREAD

**Issue by davidmbochi** [section-engineering-education/engineering-education#1716]
### Title:
Developing a one-to-one mapping application leveraging hibernate.

### Introduction:
Hibernate is an object relational mapping tool(ORM) for mapping object-domain model to relational database. This means that hibernate creates the tables according to the classes(objects) created and annotated as entities and also generate the fields in the classes annotated as columns in the database. Hibernate also is responsible for CRUD operations apart from when complex queries are required resulting to use of hibernate query language(HQL).

In this tutorial the reader will learn how to implement a one-to-one relationship application by applying the four CRUD operations and how cascading is handled by hibernate.

### Key takeaways:
1.The reader should be able to configure or set up a hibernate application.  
2.The reader should be able to develop a hibernate application.  
3.The reader should be able to control cascading using hibernate.  

### References:
- [Hibernate user guide](https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html)  
- [Maven repository](https://mvnrepository.com/)  
- [one-to-one relationship](https://www.baeldung.com/jpa-one-to-one)

**Comment by ninjaginja** [comment]
good topic @davidmbochi - approved
