### ISSUE TITLE
The Basics of Means End Analysis (MEA) in AI

### ISSUE THREAD

**Issue by gracejolie** [section-engineering-education/engineering-education#1718]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
The Basics of Means End Analysis (MEA) in AI

### Introduction paragraph (2-3 paragraphs):
Means end analysis (MEA) is an important concept in artificial intelligence because it enhances problem resolution. MEA solves problems by defining the goal and establishing the right action plan. This technique is used in AI programs to limit search. 

This article explains how MEA works and provides the algorithm steps for implementing it. It also provides an overview of how it has been applied in AI programs. 

### Key takeaways: 
1. Introduction to MEA and problem-solving in AI
2. How MEA works
3. Algorithm steps for MEA
4. Applications of MEA
5. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. N/A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @gracejolie - approved
