### ISSUE TITLE
How To Integrate Google Maps in React Application

### ISSUE THREAD

**Issue by Julius-1996** [section-engineering-education/engineering-education#1719]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
How To Integrate Google Maps in React Application

### Introduction paragraph (2-3 paragraphs):
React is a JavaScript library for building highly interactive user interfaces. This means that building a dynamic site with the library results to a robust web application. One of the most common feature is to integrate the location and finding GPS locations. This is where the Google Maps API comes into play.
In this tutorial, we will build a simple React application that implements an integrated Google Maps.

### Key takeaways: 
1. How to set up React application
2. Using Google Maps is a React application
3. Interacting with an API

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @Julius-1996 - approved. Just one important note - please ensure that you put your article draft through a thorough grammar/readability check prior to submitting for final review.

**Comment by hectorkambow** [comment]
@Julius-1996 just wanted to follow up on this topic as I'm clearing up the queue where possible?
