### ISSUE TITLE
Build a Tasks iOS Application using Swift

### ISSUE THREAD

**Issue by cyberShaw** [section-engineering-education/engineering-education#1722]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

An Introduction to Swift

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

Swift is a modern programming language that was developed by Apple to build applications for MacOS and iOS. Today, Swift has become one of the fastest growing languages with excellent developer support. Let us dive into the nuances of the Swift Language, set up the environment and build our first iOS application in the article.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

- The reader will get an idea about the purpose of the Swift language.
- The reader would be introduced to the Swift compiler and basic syntax.
- The reader will be walked through setting up an environment to build iOS apps.
- The reader will be able to build a simple iOS app.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

https://swift.org/documentation/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @cyberShaw, but we're really looking for original content, and based on the description that you've provided, it seems that information that you intend to cover is already readily available through the Swift documentation. An alternate path might be to create a unique project using Swift?

**Comment by cyberShaw** [comment]
> Thank you for the topic suggestion @cyberShaw, but we're really looking for original content, and based on the description that you've provided, it seems that information that you intend to cover is already readily available through the Swift documentation. An alternate path might be to create a unique project using Swift? 

Understood, @ninjaginja. I've modified the tutorial to be a guide to build an iOS application using Swift.

**Comment by ninjaginja** [comment]
@cyberShaw Thanks for the updates. Can you be a bit more specific about what type of iOS app you will be building in this tutorial?

**Comment by cyberShaw** [comment]
> @cyberShaw Thanks for the updates. Can you be a bit more specific about what type of iOS app you will be building in this tutorial?


I'd be building a simple note taking application. 😅

**Comment by hectorkambow** [comment]
@cyberShaw  

Building out an app with a step by step guide sounds like it should be helpful for the community. 👍  

topic approved.

May be helpful to have the article title reflect the type of tutorial it will be (app we are building).
