### ISSUE TITLE
How To Build a Todo app with flutter 

### ISSUE THREAD

**Issue by wobin1** [section-engineering-education/engineering-education#1723]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article's higher ranking.*

### Introduction paragraph(s):
Flutter is a tool kit created by Google. It is used to develop applications for android, IOS, Linux, Mac, Windows, Google fuchsia, and the web from a single codebase. This technology is changing the Software development industry by making application development faster and cheaper.
In this article, we will do an overview of what is possible with flutter by building a Todo app. The article will give the reader an understanding of how flutter works.
### Key takeaways: 
The reader will understand;
1. Flutter Widget
2. Stateful and stateless Widgets
3. Flutter and dart packages
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @wobin1 - approved
