### ISSUE TITLE
How to build a command-line utility(CLI) using Node.js

### ISSUE THREAD

**Issue by ephnjor2021** [section-engineering-education/engineering-education#1724]
### Introduction:

Command-line utilities are used almost every day by the developers. They are useful and fast when you want to get something done. Most of the developers’ tasks can be automated using a CLI. We can utilize quite a number of packages and built-in libraries that Node.js offers to build a highly portable, multi-operating system CLI.

### Key takeaways: 

The reader will be able to:

Build a simple CLI to translate between different languages
Use a translation API to fetch the language translations and display the output
Use the terminal colors to decorate the output and make it presentable.

### References: 

N/A

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @ephnjor2021, but it seems that this topic has already been sufficiently covered in this previously published article - https://www.section.io/engineering-education/create-a-nodejs-cli/. Please select a different topic area to explore.
