### ISSUE TITLE
Logical network segmentation

### ISSUE THREAD

**Issue by josep562** [section-engineering-education/engineering-education#1725]
**Introduction**
Network segmentation has been in existence for many years. If you are a network engineer or a Sys admin segmenting a network is a very essential skill to have in your toolbox. There are two ways of segmenting a network. The first method is physical network segmentation and the other method is logical network segmentation. In this article we are going look in depth about logical network segmentation.

**Key** **takeways**
1.An overview of what is segmenting.
2. Reasons for network segmentation.
3. An in depth understanding of what is logical network segmentation.
4. Example of cases when to use logical segmentation.

**Comment by ninjaginja** [comment]
good topic @josep562 - approved

**Comment by hectorkambow** [comment]
@josep562 just wanted to follow up on this topic as I'm clearing up the queue where possible?
