### ISSUE TITLE
Why Node.js is good for building an online store

### ISSUE THREAD

**Issue by verah-tech** [section-engineering-education/engineering-education#1726]
### Introduction:

From a technical perspective, E-commerce platforms are generally complex systems. To make all pieces work in such a system, a reliable technology that can support it is required. Node.js is known to be fast and scalable but the question is, does it have what it takes to build such platforms?

### Key takeaways:

The reader will be able to understand:
The real advantages of building systems using Node.js
Other platforms that build E-Commerce systems compared to Node.Js
The factors to consider whether to use Node.js or other platforms

### References: 

N/A

**Comment by ninjaginja** [comment]
Good topic @verah-tech - approved
