### ISSUE TITLE
Biometric 2FA in a Django Application with TypingDNA

### ISSUE THREAD

**Issue by Nomzy-kush** [section-engineering-education/engineering-education#1727]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Biometric 2FA in a Django Application with TypingDNA

### Introduction paragraph (2-3 paragraphs):
TypingDNA is a two-factor authentication API that easily helps to integrate biometrics authentication to secure user accounts on your website using powerful typing analysis. TypingDNA typically helps you learn a user’s typing pattern and match them, then use it to further authenticate users after login. This double user verification is what is known as a “two-factor authentication”.  

This article shows a step-by-step guide to integrating TypingDNA services into a Django web application. To learn more visit their official website https://www.typingdna.com

### Key takeaways: 
* Readers will learn about TypingDNA
*  Readers will learn how to implement 2FA with TypingDNA API
*  Readers will learn how to integrate TypingDNA in a Django application.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @Nomzy-kush - approved
