### ISSUE TITLE
Understanding ICT Help Desk Support

### ISSUE THREAD

**Issue by ipitah** [section-engineering-education/engineering-education#1728]
### Introduction
The modern world business activities performance has greatly improved. Businesses have put more emphasis on customer satisfaction that is monitored by evaluating effectiveness, efficiency, cost, and time for an activity. To better their service, businesses have adopted a couple of ways, the major one is embracing the use of technology with a number of them establishing a support department (ICT or IT department). A common task that can often be taken for granted is user support which is classified in different levels. This article will therefore discuss and classify the ICT support.
 
ICT support is mainly a routine activity performed on a daily basis. It takes a lot of time, with some situations requiring 24/7 support. The activity requires skilled staff to handle it from troubleshooting to solving the problem. The technicality of staff is based on the level of education and experience. Therefore, ICT support is handled in a certain approach, from low to high technical levels. The levels are classified from L0 to L4. Therefore, it is important to note each level and its requirements. This will guide members of staff when seeking support and when provided with a response.

### Key takeaways: 
1. Understand ICT support.
2. Understand ICT support classification.
3. Understand the escalation of support in the different levels.
4. Realise the feedback expected at every level.
5. Estimate the level of support required by a user.

### References: 
1. https://www.bmc.com/blogs/support-levels-level-1-level-2-level-3/
2. https://www.greycampus.com/blog/it-service-management/it-support-what-are-the-different-levels
3. https://tss.nmsu.edu/technical-support-center-service-level-agreement/
4. https://medium.com/@harshanacslab/what-is-l1-l2-and-l3-support-engineering-6e9ca20c1dbb
5. https://www.quora.com/What-are-the-differences-in-L1-L2-and-L3-support-of-jobs-in-software-engineering
6. https://itsyndicate.org/blog/what-is-l1-l2-l3-support/
7. http://www.greenstech.in/oracle-application-support.pdf
8. https://serverhealers.com/what-is-l1-l2-l3-support/

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @ipitah, however this is outside of our preferred topic areas. Please feel free to suggest an alternate topic to explore.
