### ISSUE TITLE
Managing file uploads in HTML forms using PHP

### ISSUE THREAD

**Issue by Dyrstiu** [section-engineering-education/engineering-education#1729]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Managing file uploads in HTML forms using PHP.

### Introduction paragraph (2-3 paragraphs):
In today’s world, files are highly exchanged, especially over the internet. For interaction, HTML also allows the upload of files, this ranges from images, videos to pdf documents. Websites use these files for various uses such as profile pictures and also exchange of information among users in web apps. In this tutorial, we will look at how to use HTML forms and PHP to allow the uploading of files to a website.

 ### Prerequisites.
How to create HTML forms.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.
1. configuring PHP to allow file uploads
2.Creating the upload file PHP script 
3. Steps to make file upload secure 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

**Comment by ninjaginja** [comment]
good topic @Dyrstiu - approved
