### ISSUE TITLE
How to convert text to emoji using python  

### ISSUE THREAD

**Issue by majiezra** [section-engineering-education/engineering-education#1731]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
How to convert text to emoji using python  
### Introduction paragraph (2-3 paragraphs):
Emojis are now used by almost all on social media in some form or another.
As a programmer, have you ever considered writing code that produces emojis in python? well this article is for you.
In this tutorial, we'll learn how to build an emoji converter from text using Python code and dictionaries, which store data in the form of key-value pairs. this is another use for dictionaries in python programming
 

### Key takeaways: 
- short overview of python
- create dictionaries 
-  how to use dictionaries to convert text to emojis.
### References: 
[learn python](https://www.learnpython.org/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @majiezra - approved
