### ISSUE TITLE
Testing a django application with unit test

### ISSUE THREAD

**Issue by Anitaachu** [section-engineering-education/engineering-education#1732]
### Introduction paragraph (2-3 paragraphs):
In developing any software or application, testing is sorted as a means to finding errors in the application while the software is at the development stage(coding phase) before the software is moved to production. Application testing gives sufficient importance to the performance, load and security of the application. There are various methods of testing a application and one of these methods of testing is unit testing.

Unit test is a method of application testing where each component or parts of the application is being tested. Unit test is done in the development stage before the application is hosted or pushed to production. Unit test is mostly preferred to other methods of application testing because it is the best way to find bugs since all the units and parts of the application are tested, it is also fast and done during development thereby helps to reduce cost.

This tutorial focuses on Unit test, the importance of unit testing and how to test a Django application. 

### Key takeaways: 
1. Knowledge of what  unit test is
2. Importance of testing an application
3. How to test a Django application using unit test

### References: 
none

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Anitaachu, but it seems like there's too much overlap with this open topic - #1676. Please select a different topic area to explore.
