### ISSUE TITLE
How to upload files to AWS S3 using Django Rest Framework

### ISSUE THREAD

**Issue by Damephena** [section-engineering-education/engineering-education#1733]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
How to upload files to AWS S3 using Django Rest Framework

### Introduction paragraph (2-3 paragraphs):
File upload and download are some of the most performed actions on the web. With the rise of cloud-based services and functions, which includes storage service, companies are moving their files from an on-premises solution to cloud storage mainly for its cheaper cost and convenience. This article shows how to upload and download user-generated files like images and document files to Amazon S3 via Django Rest Framework which is one of Django's most popular Restful API framework.

### Key takeaways: 
At the end of this article, the reader should be able to:
- Understand what type of files are stored on AWS S3
- Have a working Restful API endpoint that connects to AWS S3
- Understand the need for verifying user-generated files
- Upload and download user-generated files from AWS S3

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
- [AWS Boto3 Python documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-examples.html)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @Damephena - approved
