### ISSUE TITLE
From Theory to Practice: Implementing MFA in Python

### ISSUE THREAD

**Issue by prince-joel** [section-engineering-education/engineering-education#1735]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Introduction paragraph (2-3 paragraphs):
Multi-factor authentication (MFA) is an electronic authentication method in which a device user is granted access to a website or application only after successfully presenting two or more pieces of evidence (or factors) to an authentication mechanism. In this article, we will be going over what MFA is, the advantages of MFA, and explore how to implement MFA using Google Authenticator in a Python application.

### Key takeaways: 
By the end of this tutorial, the reader will be able to:
* define what multi-factor authentication (MFA) is
* understand the underlying concept behind MFA
* implement Google authenticator MFA in a Python application

### References: 
* https://en.wikipedia.org/wiki/Multi-factor_authentication
* https://pyauth.github.io/pyotp/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by prince-joel** [comment]
@ninjaginja I closed the former article idea and pitched this one instead. I feel this idea will be more convinient for me to write on. Please review.

**Comment by ninjaginja** [comment]
sounds great, thanks @prince-joel! You may proceed with this topic :)
