### ISSUE TITLE
Getting Started with Quasar Framework

### ISSUE THREAD

**Issue by EspiraMarvin** [section-engineering-education/engineering-education#1736]
Quasar Framework is a Vuejs framework used to develop cross-platform applications using one code base saving development costs. It offers state of art UI, support builds for SPA, PWA, SSR, Mobile Apps (IOS and Android), Desktop app, and Browser Extensions. 

### Key Takeaways: 
By the end of the article the student should be able to:

1.   Install Quasar framework
2.  Create a simple quasar project with Quasar CLI
3.	Familiarize with the Structure of the Components
4.	Understand the pros and cons of choosing Quasar Framework

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @EspiraMarvin - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
