### ISSUE TITLE
Using Celery with Dockerized Django Rest API for Background task processing

### ISSUE THREAD

**Issue by Damephena** [section-engineering-education/engineering-education#1737]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Using Celery with Dockerized Django Rest API for Background task processing

### Introduction paragraph (2-3 paragraphs):
Celery is an implementation of a task queue (First In First Out) written in Python but available for use in other languages such as PHP and Node. It is used to execute requests asynchronously independent of the HTTP request/response cycle. A background task or process is one that happens without the requesting client's participation. Examples of background tasks are email sending, user notifications and logging. This article gives a step by step guide on how to use Celery to run background task in a dockerized Django Rest API.

### Key takeaways: 
At the end of this article, the reader should be able to:
- Understand what Celery is
- Understand why web applications need to run background tasks
- Identify what a broker and a worker are
- Use celery to run background task such as send email via Django Rest Framework

### References: 
- [Getting Started with Docker](https://www.section.io/engineering-education/getting-started-with-docker/)
- [Understanding Docker Concepts](section.io/engineering-education/docker-concepts/)
- [How to create Django Docker Images](https://www.section.io/engineering-education/django-docker/)
- [Celery documentation](https://docs.celeryproject.org/en/stable/getting-started/index.html)
- [Django Rest Framework documentation](https://www.django-rest-framework.org/)
- [DRF-yasg](https://drf-yasg.readthedocs.io/en/stable/) for Swagger API generator

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Damephena  👋  
>NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)

Closing this issue for now
