### ISSUE TITLE
What is Container orchestration?

### ISSUE THREAD

**Issue by molly80** [section-engineering-education/engineering-education#1738]
Container orchestrations refer to the automation management of container lifecycles through microservices within multiple clusters. Through container orchestration, resources are shared effectively among containers; there is a redundancy reduction, ensures availability of containers, scaling up containers, resource allocation, among others. Docker Swarm and Kubernetes are tools needed for container orchestration.
Through this article, you will learn everything you need to know about container orchestration.

Key takeaways
What is container orchestration?
Why we need container orchestration?
How does container orchestration work?
Kubernetes orchestration vs Docker orchestration
Enabling Docker Swarm
Enabling Kubernetes

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @molly80, however we've already got several previously published articles covering the proposed topic areas, including:
- https://www.section.io/engineering-education/history-of-container-technology/
- https://www.section.io/engineering-education/breaking-down-kubernetes-vs-docker-swarm/
- https://www.section.io/engineering-education/what-is-kubernetes/

Please select a different topic area to explore. Thank you.
