### ISSUE TITLE
What is Self-Supervised Learning?

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#1740]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

What is Self-Supervised Learning?

### Introduction paragraph (2-3 paragraphs):

How do humans learn so quickly?

Humans learn by using both supervised learning and unsupervised learning. We are multifaceted. This multifaced approach to learning has been so easy for humans. But, that has not been the case for deep learning systems. Though we have seen robust deep learning systems that have performed image recognition and natural language processing tasks, performing complex tasks has remained challenging. This is the problem self-supervised learning is trying to address.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this article, the reader should be able to understand:

1. What is Supervised Learning?
2. The challenges associated with Supervised Learning
3. Introduction to Self-Supervised Learning
4. Applications of Self-Supervised Learning

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

1. [A Simple Framework for Contrastive Learning of Visual Representations](https://arxiv.org/pdf/2002.05709.pdf)
2. [Unsupervised Representation Learning by Predicting Image Rotations](https://arxiv.org/pdf/1803.07728.pdf)
3. [Generative Pre-trained Transformer 3 (GPT-3)](https://openai.com/blog/openai-api/)
4. [Bidirectional Encoder Representations from Transformers (BERT)](https://arxiv.org/pdf/1810.04805.pdf)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @Bayler. Can you please confirm that there is not too much overlap with this previously published article? https://www.section.io/engineering-education/supervised-learning-algorithms/

**Comment by Bayler** [comment]
@ninjaginja the article just touches a bit on supervised learning as it is essential to explaining it's challenges but the topic solely focuses on self supervised learning

**Comment by Bayler** [comment]
@ninjaginja Hi, is my topic approved?

**Comment by hectorkambow** [comment]
nice topic - approved
