### ISSUE TITLE
Designing API Endpoints

### ISSUE THREAD

**Issue by Anitaachu** [section-engineering-education/engineering-education#1747]
### Introduction paragraph (2-3 paragraphs):
API which is an acronym for Application Programming Interface is a software that allows communication between two applications using requests and responses. These applications (client and server) provide data and can also make changes to the data.
Endpoints in API are very important, they specify where resources can be accessed by the API. The performance of an API is dependent on its ability to communicate effectively with API Endpoints . In this tutorial, we'll look at what a good API is and how a good API Endpoint is designed

### Key takeaways: 
1. What an API is.
2. A good understanding of CRUD operations.
3. How to design API Endpoint.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @Anitaachu, however this topic has already been covered across a range of previously published articles (https://www.section.io/engineering-education/search/?q=api).

To better your chances for topic acceptance, please note what we look for when evaluating:

- **Polish and depth of the description and key takeaways provided** - Grammar, readability, and substance are all being reviewed. Be sure to treat your topic suggestion as the best representation of your writing.
- **Originality** - We're looking for unique content that isn't readily available through existing documentation and wikipedia definitions. Consider applying concepts to unique projects.
- **Minimal overlap with previously published articles** - Please use the search function in the EngEd article library to confirm that your proposed topic area hasn't already been covered.
- **Programming-centric topics in the web technologies space** - We're most interested in articles that take a practitioner's approach to solving common (and not so common) challenges in the modern technology ecosystem. We tend to lean more heavily towards meaty front- and back-end technology-related content and are generally less interested in tangential technology topics, such as UI design and hardware.
