### ISSUE TITLE
Applications of APIs in financial services

### ISSUE THREAD

**Issue by Reestuart** [section-engineering-education/engineering-education#1748]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article

Application of APIs in financial services

### Introduction paragraph (2-3 paragraphs):
API or Application Programming Interface is a software intermediary that allows two applications to communicate with each other. Using an application like facebook is an example in application. Software products usually interchange information and data using interfaces that are machine-readable. Application programming interfaces usually comprises two components, that is, technical specifications illustrating the options of data exchange between solutions and software interfaces written to the designation that represents it. The use of APIs is inevitable to businesses and financial institutions as it is presenting lots of innovations and possibilities. The software accessing the information, for instance, Uber charges for a particular distance, or functionality, such as google map from another software, connects its API while giving specifications on the manner in which data or functionality ought to be provided. The second software responds as requested.

API helps developers to communicate with consumers easily. Each time you access a page online from shopping to playing games, you’re interacting with API. API helps developers to communicate with consumers easily. Each time you access a page online from shopping to playing games, you’re interacting with API. It is important to note that API is a code that directs the access points to the server. It is not the database itself. The applications work in line with JavaScript Object Notation (JSON) which represents data like JavaScript objects. JSON is applied everywhere in Internet of Things applications and modern web and mobile. It also has advantages of being readable and lightweight. Its functioning is perfect in applications written in JavaScript. APIs have tremendously become popular and many financial institutions and companies have followed the emerging trend toward use of APIs to expose their assets and services. Custom applications are being used by top banks all over the world in call centers and other corporate transactions. With API-driven systems, access to system data is more efficient and secure therefore enhancing integrity.

### Key takeaways: 
-Understanding the concept of Application Programming Interface.
-Extensive analysis of the functioning of APIs.
-Real world examples of APIs
-Applications of APIs in financial services.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @Reestuart , however this topic has already been covered across a range of previously published articles (https://www.section.io/engineering-education/search/?q=api).

To better your chances for topic acceptance, please note what we look for when evaluating:

- **Polish and depth of the description and key takeaways provided** - Grammar, readability, and substance are all being reviewed. Be sure to treat your topic suggestion as the best representation of your writing.
- **Originality** - We're looking for unique content that isn't readily available through existing documentation and wikipedia definitions. Consider applying concepts to unique projects.
- **Minimal overlap with previously published articles** - Please use the search function in the EngEd article library to confirm that your proposed topic area hasn't already been covered.
- **Programming-centric topics in the web technologies space** - We're most interested in articles that take a practitioner's approach to solving common (and not so common) challenges in the modern technology ecosystem. We tend to lean more heavily towards meaty front- and back-end technology-related content and are generally less interested in tangential technology topics, such as UI design and hardware.
