### ISSUE TITLE
How to fix memory leaks in python

### ISSUE THREAD

**Issue by BashiirIsla** [section-engineering-education/engineering-education#1750]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
How to Fix Memory Leaks in Python

### Introduction paragraph (2-3 paragraphs):
Memory is a vital part of any program as it keeps the efficient working of the program. Likewise, memory storage in python is crucial but it becomes out of space error due to memory leaks. 

Memory leaks occur in python when the unused data is heaped up and the programmer forgets to delete it. In order to diagnose such memory leaks from python, we have to perform a process of memory profiling whereby we can measure the memory used by each part of the code.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

1. What is a memory leak
2. What causes memory leak in Python
3. Methods to fix memory leaks 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
https://dzone.com/articles/python-memory-issues-tips-and-tricks
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @BashiirIsla - approved
