### ISSUE TITLE
Key Design of HDFS Architecture

### ISSUE THREAD

**Issue by RuthAMare** [section-engineering-education/engineering-education#1751]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Key Design of HDFS Architecture

### Introduction paragraph (2-3 paragraphs):
HDFS (Hadoop Distributed File System) is a big data framework by Apache that needs to have several features of design implemented to work effectively in processing, distibuting and storing big data.
We'll look keenly into the very key features of design  that need to be implemented within HDFS to achieve an effectively functional distributed file system within Hadoop.

### Key takeaways: 
1. Brief introduction to Big data Framework
2. General Design of HDFS architecture
3. Configuring HDFS Data Storage policies.
4. Colocation and it's benefits in HDFS

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @RuthAMare - approved
