### ISSUE TITLE
face detection in an image using viola-jones algorithm

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#1752]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Introduction paragraph (s)
Face detection is the ability to distinguish faces from non-faces object in an image or video. The viola-jones algorithm is an object recognition framework that allows the detection of the human faces. Despite being an outdated framework, viola-jones algorithm is quit power,robust and faster therefore it is found exceptionally notable in real-time face detection. In this article we will look on how to use viola-jones algorithm to detect faces in real time.

### Key takeaways: 
1. The reader shoould understand the need for face detection
2.  The reader should understand the viola-jones algorithm for face detection.
3. The reader should be able to use the algorithm to detect faces in an image

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @jumapaul - approved. One important note: please ensure that you put your content through a thorough grammar/readability review prior to submitting for final approval. I noticed some issues in the description that you provided that raises some concerns. For example, this sentence is very difficult to read: 

> Despite being an outdated framework, viola-jones algorithm is quit power,robust and faster therefore it is found exceptionally notable in real-time face detection.

By being more attentive upfront, it raises the likelihood of your article being published (and you receiving a payout).
