### ISSUE TITLE
How to Create an Automatic Slider in Android Studio

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#1753]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of the article
How to Create an Automatic Slider in Android Studio

### Introduction paragraph (2-3 paragraphs):
Sliders are commonly used on cross platforms, i.e., websites, Desktop applications, and mobile applications. They are widely implemented on the home pages or application main screens to showcase major and key features.

Let's take the case of an eCommerce application. You would like to show the new items you have in your shop without interfering with the user app interaction. Slides would be a perfect way to showcase some of these major new items to your users.

This guide will walk you through how to create an automatic slider page using android studio.

### What we shall look at
We will create a slider based on the following concepts.
- Populate an array list of slides into a `ViewPager` using `PagerAdapter`.
- Set a list of slides in a tabbed layout and a toolbar.
- Set timmer that will automatically slide to the next slider after a set of milliseconds.

### Prerequisites
This guide uses java in android studio. Prior knowledge of android [ViewPager](https://developer.android.com/training/animation/screen-slide), [PagerAdapters](https://developer.android.com/reference/kotlin/androidx/viewpager/widget/PagerAdapter), and [TabLayout](https://developer.android.com/reference/com/google/android/material/tabs/TabLayout) would be helpful.

### Setting Up
Start a new android studio project. I have changed the default parent theme. To do that on your android studio, go to `res` folder → `values` → `style.xml` and change the app theme, as shown below.

```xml
<resources 
<style name="Theme.AnAutomaticAndroidSlider" parent="Theme.AppCompat.Light.DarkActionBar"></style>
</resources>
```

### Laying out the slider components
Create an XML layout name it `slider_items_layout.xml`. The slides are comprised of two major views.

- A text view for the slide title.
- An image view for the slide hero image.

### Key takeaways: 

- Setting up the android studio project
- Laying out the slider UI components
- Setting a ViewPager and TabLayout
- Setting up PagerAdapte and a model class
- Preparing the slider adapter
- Setting up the timer
- Testing the application

### References: 
https://developer.android.com/reference/kotlin/androidx/viewpager/widget/PagerAdapter
https://developer.android.com/reference/com/google/android/material/tabs/TabLayout

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)

**Comment by ninjaginja** [comment]
good topic @kimkimani - approved
