### ISSUE TITLE
Understanding Pattern Recognition in Machine Learning

### ISSUE THREAD

**Issue by annwawesh** [section-engineering-education/engineering-education#1754]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Understanding Pattern Recognition in Machine Learning

### Introduction paragraph (2-3 paragraphs):
Pattern recognition is the use of computer algorithms to recognize data regularities and patterns. This type of recognition can be done on various input types such as biometric recognition, colors, image recognition, and facial recognition. It has been applied in various fields such as image analysis, computer graphics, and bioinformatics. 

This article takes readers through pattern recognition in machine learning and explains how it works. It also discusses how it has been applied in various fields and analyzes its future outlook. 

### Key takeaways: 
1. What is pattern recognition?
2. Features of pattern recognition
3. How pattern recognition works
4. Algorithms in pattern recognition
5. Applications of pattern recognition
6. The future of pattern recognition

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. N/A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @annwawesh - approved
