### ISSUE TITLE
Introduction to PHP Operators

### ISSUE THREAD

**Issue by Erastuskanyatta** [section-engineering-education/engineering-education#1755]
### Title of article:
Introduction to PHP Operators

### Introduction  :
PHP operators are used to perform different operations on variables and values. In this article we are going to look at different operators in PHP and their functions.

### Key takeaways: 
- differentiate between operator and operands
- types of operators
- writing PHP programs using operators

### References: 
[Getting Started with PHP](https://www.section.io/engineering-education/introduction-to-php/)

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @Erastuskanyatta. We're really looking for more detail in these topic suggestions that allows us to gain a better feel for your writing style and the depth of the article content. Please spend some time expanding upon your topic suggestion and reopen this issue when ready. Thank you.

**Comment by Erastuskanyatta** [comment]
@ninjaginja details added to the topic. Please have a look.

**Comment by ninjaginja** [comment]
Thank you @Erastuskanyatta. There are some significant readability challenges in your description that raise concerns over how much review/editing would be required from our peer review team. We don't provide editing services and recommend that students leverage online editing services (there are both free and paid services that you can explore), or try engaging with the community or other peers in your network to have them review prior to submitting a revised proposal. Thank you.

**Comment by Erastuskanyatta** [comment]
@ninjaginja  Please have a look.
