### ISSUE TITLE
Getting started with Spring Boot RestTemplate

### ISSUE THREAD

**Issue by elizabeth962** [section-engineering-education/engineering-education#1759]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Getting started with Spring Boot RestTemplate
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
RestTemplate makes interacting with most RESTful web services a one-line incantation. In the tutorial I will be explaining how to consume RESTful APIs from the popular [JSON placeholder](https://jsonplaceholder.typicode.com/).

### Key takeaways: 
1. Setting up RestTemplate in Spring Boot.
2. Consuming data from the various REST API endpoints using RestTemplate.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for your topic submission @elizabeth962. In order to better assess your proposed content, we request that you provide a more detailed introduction so that we can better evaluate the suitability of your article. Please expand upon your topic suggestion and reopen this issue when ready. Thank you.
