### ISSUE TITLE
Converting HTML content to PDF with pdfkit for Python

### ISSUE THREAD

**Issue by Anitaachu** [section-engineering-education/engineering-education#1760]
### Introduction paragraph (2-3 paragraphs):
HTML **(HyperText Markup Language)** is a standard markup language for creating Web pages. It provides users with information and details of a web page. A standard web page text is created and information of users is viewed on a page using HTML.
In recent times, web pages contained documents such as reports, contracts, questionnaires, etc. which may require downloading. Though these documents are written in HTML, they cannot be downloaded successfully in HTML.
A more suitable format for this action is converting these text files to PDF. PDF which stands for Portable Document Format has become the most used format for saving and transferring documents. Web pages make use of documents and HTML data contained in these pages, HTML files and strings are therefore rendered to a PDF document using pdf converter and there are various PDF converters in python.

### Key takeaways: 
1. Libraries and tools to convert HTML to PDF in python
2. What PDFKIT is and how to install PDFKIT and other libraries in both Windows and Ubuntu.
3. How to generate  to PDF from HTML from weburls, external HTML file and from a string

### References: 
https://pypi.org/project/pdfkit/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
you may proceed with this topic @Anitaachu
