### ISSUE TITLE
Getting started with Java

### ISSUE THREAD

**Issue by Jeff-mwangi** [section-engineering-education/engineering-education#1761]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Getting started with Java

### Introduction paragraph (2-3 paragraphs):

Java is an object-oriented programming language for developing desktop application and web application. It requires Java Development Kit  and Java IDE like IntelliJ to run on a machine.  It is secure, fast, powerful and one of the most popular programming language in the world.

### Key takeaways: 
By the end of this tutorial the reader will be able to:

1. Install and set up Java IDE (IntelliJ)
2. Install and set up Java Development Kit
3. Write a hello world application using Java
4. Understand the basic syntax of a Java application

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Jeff-mwangi.  We're really looking for more detail in these topic suggestions that allows us to gain a better feel for your writing style and the depth of the article content. Please spend some time expanding upon your topic suggestion and reopen this issue when ready. Thank you.

**Comment by Jeff-mwangi** [comment]
@ninjaginja  I have added some details on the topic.
