### ISSUE TITLE
Getting started with multiple linear regression in R

### ISSUE THREAD

**Issue by Madrinmarison** [section-engineering-education/engineering-education#1764]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Linear regression is a linear approach to modeling the relationship between a scalar response and one or more explanatory variables. In the article I will explain how to perform a simple linear regression model in R. I will also explain how to obtain regression statistics such as coefficients, confidence interval, residuals, error term of the model, and other important statistics. I will also explain how to obtain those statistics as a summary and how to interpret such a summary.

### Key takeaways: 
1. The learner will understand how to perform simple linear regression using R software.
2. Learner will understand how to obtain regression coefficients from the performed simple linear model.
3. Learner will understand how to obtain and interpret regression summary.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @Madrinmarison. We're really looking for more detail in these topic suggestions that allows us to gain a better feel for your writing style and the depth of the article content. Please spend some time expanding upon the first 2-3 opening paragraphs of your proposed content and reopen this issue when ready. Thank you.
