### ISSUE TITLE
Introduction to Flutter

### ISSUE THREAD

**Issue by HeatherMataruse** [section-engineering-education/engineering-education#1765]
**##Introduction to flutter**

**##Table of contents**

- Introduction

- Flutter Widgets

- Flutter Animations

- Advantages of using flutter

- Disadvantages of using flutter

- Uses cases

- Examples of apps build using flutter

- References

**##Introduction**

Flutter is an open-source mobile SDK that allows developers to build native-looking Android and iOS apps from a single code base. Dart language is used to build flutter applications and it was developed by Google in October of 2011. Flutter has been around since Google released it in 2015, and it was in beta until December 2018 when it was officially launched.
 
#Flutter includes:
An SDK (Software Development Kit) is a set of tools that will assist you in the development of your applications. Tools for compiling the code into native machine code are included (code for iOS and Android).
Framework (widget-based UI Library) is a  collection of interchangeable user interface elements (buttons, text inputs, sliders, ) that you can customize to meet your specific needs.

**##Flutter widgets** (I will expand on this in the full article)

#Types of flutter widgets

- Stateless Widget

- Stateful Widget

**##Uses of common widgets:**

- Scaffold:  Implements the basic visual interface framework for material design.

- AppBar: Adds a bar to the top of the phone.

- Text: to write whatever you want on the phone.

- Container: A container is used to house some widgets.

- Center: To match other widgets in the middle.

**##Advantages of using flutter**

- no platform-specific UI components 
- faster to deploy code because of hot reload
- faster code creation 
- increased time-to-market speed 
- performance is comparable to native apps 
- enormous UI customization ability 
- separate rendering engine 
- no dependency on the platform
- specific UI components
-suitable for any target platform 
-reduces the company's costs and losses

**##Disadvantages of using Flutter**

**##Examples of apps build using flutter**

**##key takeaways**

- Idea of what is flutter
- types of widgets in flutter and their uses
- reasons why you should use flutter to create your applications
- 

**##References**
1.Flutter - Beautiful native apps in record time (2021). Available at: https://flutter.dev/ (Accessed: 17 March 2021).
2.Top 8 Flutter Advantages (2019). Available at: https://relevant.software/blog/top-8-flutter-advantages-and-why-you-should-try-flutter-on-your-next-project/ (Accessed: 17 March 2021).
3.Top Apps Made with Flutter – 17 Stories by Developers and Business Owners (2020). Available at: https://www.thedroidsonroids.com/blog/apps-made-with-flutter (Accessed: 17 March 2021).
4.Introduction to widgets (2021). Available at: https://flutter.dev/docs/development/ui/widgets-intro (Accessed: 17 March 2021).

**Comment by ninjaginja** [comment]
Thank you for such a great, in-depth topic suggestion @HeatherMataruse. This is exactly the level of detail that we're looking for in topic submissions. Unfortunately, we've already got several other open topics that are addressing this 'intro to Flutter' concept. If you'd like to check out the other open issues (via a simple search of 'flutter') and narrow your focus, or take a different, unique approach with your content, please feel free to reopen this issue. Otherwise, please select a different topic area to explore.

**Comment by HeatherMataruse** [comment]
On the website when I search for flutter I am seeing four articles that have not necessarily covered an introduction to flutter but have went straight into integrating flutter with firebase as a database and also about the file organization in flutter 
[https://www.section.io/engineering-education/search/?q=flutter]
