### ISSUE TITLE
Django web security checklist before deploying on servers

### ISSUE THREAD

**Issue by yitzackRabin** [section-engineering-education/engineering-education#1768]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Web security is an important factor to keeping hackers and cyber fraudsters from getting crucial information of your website. Checking security vulnerability and paying close attention to them and fixing them right will help avoiding loss in prior. 
Django a python famous framework will help us to fix this in combination of different security scan tools.   
### Key takeaways: 
1. Understanding the use Checklist
2. Working with different security scan tools i.e using observatory by Mozila
3. Understanding Cross site forgery protection
4. Understanding cross site scripting 
5. Django admin security 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @yitzackRabin . We're really looking for more detail in these topic suggestions that allows us to gain a better feel for your writing style and the depth of the article content. Please spend some time expanding upon the first 2-3 opening paragraphs of your proposed content and reopen this issue when ready. Thank you.
