### ISSUE TITLE
Beginners guide to APIs in Flutter

### ISSUE THREAD

**Issue by jerimkaura** [section-engineering-education/engineering-education#1769]
### Proposed title of the article
Beginners guide to APIs in Flutter

### Introduction paragraph (2-3 paragraphs):
Most applications use APIs to fetch the data consumed in the mobile from the backend. With the HTTP package, Flutter provides an efficient way of consuming HTTP resources in mobile applications. This article will explain how to fetch and consume data from an API with an example of the GitHub REST API.

### Key takeaways: 
1. Understanding the Flutter HTTP package
2.  Converting JSON objects to custom Dart objects
3.  Using await and async features
4. Using the GitHub REST API

### References: 
https://flutter.dev/docs/cookbook/networking/fetch-data

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @jerimkaura . We're really looking for more detail in these topic suggestions that allows us to gain a better feel for your writing style and the depth of the article content. Please spend some time expanding upon the first 2-3 opening paragraphs of your proposed content and reopen this issue when ready. Thank you.

**Comment by jerimkaura** [comment]
I have updated the topic suggestion details.
