### ISSUE TITLE
Introduction to recursion in ruby 

### ISSUE THREAD

**Issue by ianmaish** [section-engineering-education/engineering-education#1770]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Introduction to recursion in ruby 

### Introduction paragraph (2-3 paragraphs):
Recursion occurs when a method is defined in terms of itself. We will learn how to create simple recursive calls to solve simple calculations, then build onto that and create complex recursive calls. Recursion is commonly applied in mathematics and computer science, where the function being created is called in terms of itself. We will understand how a recursive call creates stacks until it gets to the base case where no more calls are made.
 You can only use recursion in certain situations, which can be decomposed into smaller versions of themselves. We will learn when it is appropriate to employ recursion to solve problems. We will also compare recursion and iteration since every method that is written recursively can be written iteratively.  

### Key takeaways: 

1.	Understand what recursion is 
2.	How stacks are created in recursive calls 
3.	Strategies for programming recursively 
4.	Learn to break down complex problems into simpler implementations 

### References: 
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
good topic @ianmaish - approved

**Comment by hectorkambow** [comment]
merged

**Comment by hectorkambow** [comment]
https://github.com/section-engineering-education/engineering-education/pull/2451
