### ISSUE TITLE
Integrating Payment Gateway in Node JS

### ISSUE THREAD

**Issue by Richu98** [section-engineering-education/engineering-education#1775]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of the article
Integrating Payment Gateway in Node JS

### Introduction paragraph (2-3 paragraphs):
Payment Gateway you may be thinking that why you need one when you have an option to flash your payment address and take the payment from the customer. But it can save you some bucks and can work when you are starting up but it is a heck of a lot of work to track the payment or update the user we have received your money or to process a refund. All these are manual work where the error rate is more.

It is an integral part of any e-commerce site. Since Pandemic as hit more number of people are buying online and if you are a techie shop owner you can integrate the payment gateway yourself and make yourself digital-ready or you are an aspiring web developer already doing many freelance projects or a beginner in this domain it is good to have the skill.

### Key takeaways: 
- Why we need a payment gateway?
- Some popular payment gateways and their comparison?
- What are all things we should consider while selecting a payment gateway?
-  One main issue you will face while receiving payments(late payment reconciliation)
- How we will integrate stripe/razorpay payment gateway in nodejs?

### References: 
-https://stripe.com/docs
-https://razorpay.com/docs/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
This is a great topic @Richu98, however there are a substantial amount of grammar/readability issues in the description that you've provided which raises concerns about the level of review that may be required. Please spend some time polishing your opening paragraphs and resubmit when ready. Thank you.

**Comment by Richu98** [comment]
What is a Payment Gateway?
In simple words, Payment Gateway is a service that helps us to collect payments for the products/service we deliver.


But you may be thinking about why we need one when we have an option to flash your payment address and take the payment from the customer. Yes, it will work when you are starting up but it is a lot of work to track the payment or to process a refund. All these are manual work where the error rate is more.

It is an integral part of any e-commerce site. Since Pandemic as hit more number of people are buying online and this trend will only increase in years to come. So this skill has got a huge demand and it is a must known skill for a web developer.


@ninjaginja I have updated the paragraphs.  Is it good to go?
