### ISSUE TITLE
Getting Started With Spring WebSockets In Java

### ISSUE THREAD

**Issue by john-amiscaray** [section-engineering-education/engineering-education#1776]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Getting Started With Spring WebSockets In Java

### Introduction paragraph (2-3 paragraphs):
Nowadays, web applications have become much more powerful than they once were. You now can have real-time functionality in the form of chat applications or even multiplayer games. All this has been made possible by the use of WebSockets. In this guide, we will go over the theory behind this technology and how to implement them in Spring.

### Key takeaways: 
- What are WebSockets
- HTTP vs WebSocket protocol
- STOMP subprotocol
- Setting up and Securing WebSocket endpoints
- Connecting to a WebSocket endpoint client side

### References: 
https://stackoverflow.com/questions/45405332/websocket-authentication-and-authorization-in-spring

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @john-amiscaray . We're really looking for more detail in these topic suggestions that allows us to gain a better feel for your writing style and the depth of the article content. Please spend some time expanding upon the first 2-3 opening paragraphs of your proposed content and reopen this issue when ready. Thank you.

**Comment by john-amiscaray** [comment]
> 
> 
> Thank you for your topic suggestion @john-amiscaray . We're really looking for more detail in these topic suggestions that allows us to gain a better feel for your writing style and the depth of the article content. Please spend some time expanding upon the first 2-3 opening paragraphs of your proposed content and reopen this issue when ready. Thank you.

Thanks for letting me know, I'll try my best to bring it up to standard. Quick question though: from my understanding, I believe I cannot reopen this issue so would you like me to just notify you when I fixed these issues with this, or would I create this issue over again?
