### ISSUE TITLE
Understanding abstraction in c++

### ISSUE THREAD

**Issue by Dawe-7** [section-engineering-education/engineering-education#1778]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of the article
Understanding abstraction in c++

### Introduction paragraph (2-3 paragraphs):
Data abstraction is one of the most essential and important features of object-oriented programming. Data abstraction concept in c++ helps developers to provide only essential information without providing the background details. It is the most widely used technique that relies on the separation of implementation and interface of the code. This article will take a look at data abstraction along with the types and respective examples.

### Key takeaways: 
1. What is abstraction
2. Types of abstraction
3. Advantages of data abstraction
4. How to achieve data abstraction in c++ through class, header files, and access specifiers

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @Dawe-7 . We're really looking for more detail in these topic suggestions that allows us to gain a better feel for your writing style and the depth of the article content. Please spend some time expanding upon the first 2-3 opening paragraphs of your proposed content and reopen this issue when ready. Thank you.
