### ISSUE TITLE
How to animate RecyclerView items in Android

### ISSUE THREAD

**Issue by paulnjoroge789016** [section-engineering-education/engineering-education#1784]
### Proposed title of article
How to animate RecyclerView items in Android

### Introduction paragraph (2-3 paragraphs):

It is a good practice in Android to show data to the user in a presentable way rather than displaying everything at the same time on the User Interface. This article will help you to understand how you can present your list of data in an animated manner that will improve user experience of your application. 
Animations are one of the ways through which you can visualize updates in the list in case data changes from the data source. In this article we will learn 3 types of animations namely:
- left to right animation
- right to left animation
- Scaled animation 

### Key takeaways: 

By the end of this tutorial, the reader will be able to:

1. Understand what is animation.
2. Create ` XML` animation files.
3. Integrate animations in RecyclerView.

### References: 

N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @paulnjoroge789016, however it seems that this topic has already been sufficiently covered across some previously published articles - https://www.section.io/engineering-education/search/?q=recyclerview. Please select a different topic area to explore. Thank you.

**Comment by paulnjoroge789016** [comment]
Hi @ninjaginja, This is a completely different and an unique area that has not been tackled in the previously published articles. I have gone through all articles related to RecyclerView and there are no conflicts. Thanks.
