### ISSUE TITLE
Using Random Search to Optimize Hyperparameters

### ISSUE THREAD

**Issue by collins-a** [section-engineering-education/engineering-education#1785]
### Introduction paragraph (2-3 paragraphs):

There are a number of ways to optimize the hyperparameters of a model. We previously looked at [grid search](https://www.section.io/engineering-education/grid-search/) and a basic example of its implementation. This time, we seek to understand another method of hyperparameter optimization known as random search. We shall introduce random search as well as go through a simple method of its implementation in Python.

Random search is a method in which random combinations of hyperparameters are selected and used to train a model. The best random hyperparameter combinations are used. Random search bears some similarity to grid search. However. A key distinction is that we do not specify a set of possible values for every hyperparameter. Instead, we sample values from a statistical distribution for each hyperparameter. To do a random search, a sampling distribution is defined for every hyperparameter.

This technique allows us to control the number of attempted hyperparameter combinations. Dissimilar to grid search where every possible combination is attempted, random search allows us to specify the number of models to train. We can base our search iterations on our computational resources or the time taken per iteration. The image below shows a random layout.

### Key takeaways: 

The reader should:
1. Be introduced to random search as a method of optimization.
2. Understand the use of random search with the aid of a random forest regressor.
3. Be taken through the model parameters in use before encountering them in the code.
4. Follow the step-by-step implementation of random search in python.
5. A clear distinction between grid and random search methods.

### References: 

1. https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV
2. https://towardsdatascience.com/gridsearchcv-or-randomsearchcv-5aa4acf5348c
3. https://medium.com/analytics-vidhya/how-does-random-search-algorithm-work-python-implementation-b69e779656d6

**Comment by hectorkambow** [comment]
@collins-a  please only one topic form at a time. 👍

**Comment by hectorkambow** [comment]
nice topic - approved
