### ISSUE TITLE
Creating A Location-tracking App Using Firebase and Google Maps in Android

### ISSUE THREAD

**Issue by carolinemusyoka** [section-engineering-education/engineering-education#1792]
### Proposed title of article
Creating a location-tracking app using Firebase and Google Maps in android

### Introduction paragraph(s):
 This tutorial aims to show you how to create an android application that tracks the current location of another user. We shall create two applications, one that writes to firebase and another that reads from firebase. This way, you can be able to track the location of another user who is miles away from you.

You shall have a good understanding of how Google Maps works and how to also use Firebase to store and retrieve data from the realtime database

### Key takeaways: 
- Understand Google Maps 
- Understand how to add Google Maps API to an application
- Understand how firebase realtime database works
- Understand how to store and retrieve data in Android

### References: 
N/A

**Comment by hectorkambow** [comment]
👋  @carolinemusyoka  

Just noticed you have two topic suggestions open - please pick one to continue with. 

We are asking students to have one topic and PR open at at ime.

**Comment by carolinemusyoka** [comment]
Cool. I will pick this one. Let me close the other topic suggestion issue. Thank you

**Comment by hectorkambow** [comment]
very cool topic - approved 👍  @carolinemusyoka
