### ISSUE TITLE
Beginners guide to APIs in Flutter

### ISSUE THREAD

**Issue by jerimkaura** [section-engineering-education/engineering-education#1793]
### Proposed title of the article
Beginners guide to APIs in Flutter

### Introduction paragraph (2-3 paragraphs):
Application Programming Interface(API) is a communication portal that allows two or more applications to connect for data sharing. It acts as an intermediary for delivering requests to service providers and returning the responses. Generally, an API enables seamless communication between different platforms by ensuring that data is shared without sharing the entire system codebase.

The use of APIs has been pervasive in the programming world, as most developers use pre-existing scaffoldings. Through APIs, developers can focus on other vital components of their applications instead of writing the entire code from scratch. Programmers can efficiently develop dynamic applications that easily integrate with existing data-sharing systems.

Most applications use APIs to fetch the mobile data from the back end. Flutter provides an efficient way of consuming HTTP resources in mobile applications with the HTTP package. The HTTP package contains classes and function that enables easy consumption of HTTP resources in a web, android or desktop application. In most cases, the HTTP resources returned by the APIs are in Javascript Object Notation (JSON) format, this article will explain how to fetch and consume data in JSON format from an API with an example of the GitHub REST API.

In the implementation, this article will build a mini android application using the folder organization structure explained in [flutter-folder-organization](https://www.section.io/engineering-education/flutter-folder-organization/) article.

### Key takeaways: 
1. Understanding the Flutter HTTP package
2.  Converting JSON objects to custom Dart objects using JSON serialization
3.  Using await and async methods
4. Using the GitHub REST API to fetch a user's repositories and consume the results in a flutter application
5

### References: 
https://flutter.dev/docs/cookbook/networking/fetch-data
https://flutter.dev/docs/development/data-and-backend/json
https://pub.dev/packages/http
https://docs.github.com/en/rest

**Comment by hectorkambow** [comment]
@jerimkaura  seems like a great topic - do you have a type of application in mind?  

We want to make sure the article goes beyond the basic implementation (or something the reader could find in the docs).

It may be useful to add the type of app in the title.
