### ISSUE TITLE
Creating a Android Chat App using B4A ,PHP and MySQL  with Data Encryption

### ISSUE THREAD

**Issue by tambastar** [section-engineering-education/engineering-education#1794]
With the growing number of internet connectivity, most organizations will adopt secure, quick, and real-time communication. These would mean faster message exchange within the internet and encrypted messages to avoid security breaches. This tutorial will help in creating an Android application based on B4A. The tutorial will introduce how to encrypt data and decrypt data for the readability of both users.

### Key takeaways:
The reader will be able to:
Build a simple Android chat app with B4A.
Create the backend using PHP.
Encrypt and Decrypt the messages.
Get Complete project in Github.

### References:
https://www.b4x.com/b4a.html
https://www.section.io/engineering-education/connecting-basic4android-b4a-application-with-php-and-mysql-database/

**Comment by hectorkambow** [comment]
Good topic - approved @tambastar

**Comment by hectorkambow** [comment]
@tambastar just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
