### ISSUE TITLE
Getting started with Data Preprocessing in R

### ISSUE THREAD

**Issue by Daniel695** [section-engineering-education/engineering-education#1797]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

###  Getting started with Data Preprocessing in R
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):Getting started with Data Preprocessing in R.
Data preprocessing is the intial stage in the machine learning model in which data is imported and transformed into a basic form that makes it easy to work with.
Activities that take place at this step include,
1. Transforming data into a format of tidy data, i.e,
Tidy data is a dataset with characteristics such as,
i) One observation per row
ii)One variable per column
iii) One entry per cell.
2. Detecting presence of Missing value in the data and how to handle them.
3. Detecting and handling outliers in the dataset using appropriate methods present in the R software.
4. Detecting duplicates in the data and rectify if any is present.

In this tutorial, I will explain all steps that are involved in data preparation so as to have the right data for creating reliable models for machine learning.

Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

### Key takeaways:
This tutorial will enhance the reader with a complete understanding on how to create clean dataset from messy one that is suitable for creating reliable model.  Reliable model is the one which gives the right prediction.
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
good topic @Daniel695  - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
