### ISSUE TITLE
Getting started with linear regression in R.

### ISSUE THREAD

**Issue by Madrinmarison** [section-engineering-education/engineering-education#1799]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Getting with started linear regression in R.
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs): 

Linear regression is a machine learning algorithm that is used to model a relationship between a continuous dependent variable and one or more independent variables. The independent variable can be either categorical or numerical. The case when we have only one independent variable then it is called as simple linear regression. If we have more than one independent variable, then it is called as multivariate regression.

In this tutorial, I will explain how to execute linear regression in R using some select functions and test its assumptions before we  can use it for a final prediction on test data.I will also explain how to obtain and understand the regression summary that help in determining the level of significance of the model.

### Key takeaways: 
(i) The leaner will understand how to perform linear regression using R.
(ii)  The leaner will be able to test the assumptions of the model before it  can be used for a final prediction on test data.
(iii) The learner will understand how to obtain and interpret linear regression statistics.
(iv) The leaner will be able to perform linear regression and draw important

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
nice topic approved @Madrinmarison
