### ISSUE TITLE
Android Application Widgets Tutorial in Java

### ISSUE THREAD

**Issue by manmusa100** [section-engineering-education/engineering-education#1800]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of the article
Android Application Widgets Tutorial in Java

### Introduction paragraph (2-3 paragraphs):
Application widgets are views that contain some of the application functionality and data that are accessible from the user's home screen. Widgets vary in size and support resizing. Widgets are placed on the device's home screen to enable quick access to the data they hold and functionalities. They enable you to create shortcuts for your favorite apps. Some of the most common widgets are weather widget, calendar widget, Google search widget, among others.

This tutorial will cover Android app widgets in detail. You will learn how to create an Android widget. Widgets are categorized into:
- Information widgets
- Control widgets
- Collection widgets
- Hybrid widgets

### Key takeaways: 
- Introduction to Android widgets
- Types of widgets
- Creating a sample widget in Java
- Limitations of Widgets

### References: 
https://developer.android.com/guide/topics/appwidgets/
https://www.tutorialspoint.com/android/android_widgets.htm

### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
cool topic approved @manmusa100
