### ISSUE TITLE
Creating your first Google web story

### ISSUE THREAD

**Issue by Jethro-magaji** [section-engineering-education/engineering-education#1802]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Creating your first Google web story

### Introduction paragraph (2-3 paragraphs):
Web Stories are a web-based version of the popular "Stories" format that blends video, audio, images, animation, and text to create a dynamic consumption experience. This visual format lets you explore content at your own pace by tapping through it, or swiping from one piece of content to the next.
This tutorial on how content creators, bloggers, advertisers, website owners e.t.c can leverage Google web stories to build short consumable content on the web using code and NoCode web story builder like Make story or WordPress.

### Key takeaways: 
- What is a web story
- How to create a web story using NoCode
- How to create a web story with code
- Web stories best practices

### References: 
https://www.google.com/amp/s/stories.google/
https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/
https://www.google.com/amp/s/blog.google/web-creators/10-web-stories-and-whats-great-about-them/amp/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Jethro-magaji  sounds like an interesting topic - approved. 

Please be sure to submitted a polish and publish ready draft for review to expedite publishing.
