### ISSUE TITLE
Integrating TailwindCss into your Flask apps

### ISSUE THREAD

**Issue by Curiouspaul1** [section-engineering-education/engineering-education#1807]
### Introduction Paragraph(s)
TailwindCss is a utility-first CSS framework for building frontend applications, TailwindCss differs from other kinds of CSS frameworks, as it gives the user total control over their design, rather than adding obscure CSS classes to your code, with TailwindCss you use utility classes to create your components, with as much control over every single styling as you want, all without having to ever write a single line of CSS. In this article, I'll share how Flask developers can take advantage of TailwindCss' utility classes to build frontend templates for their Flask web apps.

### Key Takeaways:
By the end of this tutorial, the reader would be able to:
* Install TailwindCss using `npm` or `yarn` .
* Compile TailwindCss using the `npx` command into a file for the Flask server.
* Use TailwindCss to build frontend components for their web apps.

### References:
* https://tailwindcss.com/docs/installation

**Comment by hectorkambow** [comment]
nice article @Curiouspaul1  

Lets also be sure to include a unique perspective that goes beyond something that can be found by reading the standard docs. 👍

**Comment by Curiouspaul1** [comment]
Thanks I'll be sure to do that

**Comment by hectorkambow** [comment]
https://github.com/section-engineering-education/engineering-education/pull/2464
