### ISSUE TITLE
How To Build A Custom URL Shortener Using Node.js, Express and MongoDB

### ISSUE THREAD

**Issue by marienjus** [section-engineering-education/engineering-education#1810]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
How To Build A Custom URL Shortener Using Node.js, Express, and MongoDB

### Introduction paragraph (2-3 paragraphs):
Using links or URLs has been the norm of surfing the web for a long time. Long URL links are not the best way to post links, especially on social media. The benefit of a URL shortener is, you can cross-promote your products, blog posts, or services with any of the links you're sharing. URL shortening tools like Snip.ly and Starafire.com help in driving the maximum traffic back to your website.
JavaScript is a popular programming language these days for full-stack development. One of the tools commonly used to develop the backend code using Javascript is Node.js. In this tutorial, we will build a URL shortener service using Node.js.

### Key takeaways: 
1. How URL Shortener service works
2. Integrating MongoDB database in Node.js
3. How to use Express framework in Node.js

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
great topic - approved
