### ISSUE TITLE
Performing CRUD Operations in Node.js using GraphQL and React

### ISSUE THREAD

**Issue by Qodestackr** [section-engineering-education/engineering-education#1811]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Performing CRUD Operations in Node.js using GraphQL and React

### Introduction paragraph (2-3 paragraphs):
Fullstack web applications have been simplified by Node.js these days. This backend JavaScript runtime helps us build a complete web app using one programming language, JavaScript. React is a client-side JavaScript library for building interactive User interfaces. Often, these client-side interfaces need data from the backend. That is where GraphQL comes in to play. It helps us build an API to achieve this seamlessly. GraphQL reduces the complexity of building APIs by abstracting all requests to a single endpoint. Unlike traditional REST APIs, it is declarative and efficient in data fetching cycles.
In this tutorial, we will build a CRUD application using React and Node.js. GraphQL will be the alternative to the REST API in the application.

### Key takeaways: 
1. Introduction to GraphQL
2. Configuring a GraphQL server in Node.js
3. How to use Mutations and Queries in GraphQL
4. Building the CRUP application

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ReactifyStudio** [comment]
@hectorkambow I still don't have a PayPal account. If not sorted I will be pushing y content for free, else ping you if I find a way to get one. @ninjaginja I will make sure to host this at section.io as well. I did create a free account, been learning varnish caching and search on the platform.

**Comment by ReactifyStudio** [comment]
cc: @hectorkambow

**Comment by hectorkambow** [comment]
@Qodestackr just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
