### ISSUE TITLE
How to get SSL/HTTPS for localhost

### ISSUE THREAD

**Issue by lewe01** [section-engineering-education/engineering-education#1812]
### Introduction:

 Building a web application that later will be deployed in the production server, requires first to be tested in a local machine. It is also possible to deploy the web application in a local machine, and be accessed over the internet. It is equally important that we get an SSL certificate for the same, for the users to trust the site and remove red 'Not Secure' message at the address bar.

### Key takeaways: 

The reader will be able to: 
Create an SSL Certificate
Set-up a Node.js Express server
Configure the browser to allow certificates that are signed

### References: 

N/A

**Comment by hectorkambow** [comment]
@lewe01  seems like a good topic. - approved 👍 

Please be sure to check out our resources page for more helpful links and tips to improve your tutorial.
