### ISSUE TITLE
Sealed classes in Kotlin

### ISSUE THREAD

**Issue by RaphaelNdonga** [section-engineering-education/engineering-education#1817]
### Proposed title of article
Sealed classes in Kotlin

### Introduction paragraph (2-3 paragraphs):
The concept behind sealed classes can be difficult to understand. This is especially true when developers fail to see a reason to use them. This article aims to clearly define what a sealed class is. It will also demonstrate (as a tutorial) the best use case for a sealed class.

A sealed class can be defined as a unique blend of an enum and abstract class. Our tutorial will start by creating an enum class use case. As the tutorial grows more complex, we will be forced to switch to using an abstract class. The sealed class will then finally step in, proving to be more powerful and convenient.

### Key takeaways: 
1. What is an enum class 
2. When to use an enum class
3. What is an abstract class
4. When to use an abstract class
5. What is a sealed class
6. How a sealed class compares to enum and abstract classes

### References: 
https://www.youtube.com/watch?v=OyIRuxjBORY

**Comment by hectorkambow** [comment]
sounds like a good topic - approved 👍  

@RaphaelNdonga
