### ISSUE TITLE
Understanding EtherChannel Technology 

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#1818]
### Proposed title of article
Understanding EtherChannel Technology

### Introduction paragraph (2-3 paragraphs):
In most of the networks, network administrators use more bandwidth and redundancy. They achieve it by connecting multiple links between devices on the network. With this method, the redundant links get blocked by the Spanning Tree Protocol (STP) to prevent switching loops. A technology is needed to achieve the redundancy and increased bandwidth, by allowing redundant links between devices that STP will not block. The technology is the EtherChannel Technology.  

To gain the understanding of this, this article will show us how to configure, troubleshoot and understand EtherChannel technology to achieve the more bandwidth and redundancy.

### Key takeaways: 
The reader should be able to:
1. Understand EtherChannel technology.
2. Configure the EtherChannel.
3. Troubleshoot the EtherChannel.

### References: 
N/A

### Templates to use as guides
N/A

**Comment by dentonya** [comment]
cc @hectorkambow

**Comment by hectorkambow** [comment]
sounds like a good topic - approved 👍  @dentonya

**Comment by hectorkambow** [comment]
@dentonya 
Let be sure to include the # of the topic and PR on your PR and topic forms to link the two so when we merge the PR it auto closes the topic form 👍

**Comment by dentonya** [comment]
Ook 👍@hectorkambow
