### ISSUE TITLE
Getting started with EASy avionics suite in Airlines

### ISSUE THREAD

**Issue by Reestuart** [section-engineering-education/engineering-education#1819]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article

Getting started with EASy avionics suite in Airlines

### Introduction paragraph (2-3 paragraphs):
The enhanced avionics system refers to integrated modular avionics and a display system on the cockpit used in Falcon aircrafts such as 200EX and 7X. It is based on Honeywell Primus Epic. EASy represents modern progress and fundamental progress particularly in achieving the paperless cockpit. It is designed with intelligence and enables both pilots to work synchronously. 
Important features in this system include: four screens which clearly display information from aircraft sensors, communication, flight management and navigation. The pilot takes control over all of these functions. This makes EASy more advanced and safer as compared to other avionics systems using the same Primus Epic platform. The pilots’ means of controlling the flight deck lies within the Dassault’s Cursor Control Device (CCD). The trackball controller does everything just like the windows operating system. Each pilot has their own CCD which is as easy to use as a computer mouse. Using the CCD is fast and automatic. It is not affected by environmental conditions such as darkness and turbulence.
This article discusses the enhanced avionic systems as applied in Falcon aircrafts. 

### Key takeaways: 

- An overview of EASy avionic architecture and functions.
- Understanding how EASy avionics system works in aircrafts.
- An analysis of EASy avionics as the most intuitive man-machine interface.
- Functioning of aircrafts using EASy avionics

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Thank you for the topic suggestion @Reestuart , however this is a bit outside of our preferred topic areas. 

We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

Please feel free to suggest an alternate topic to explore. 🚀
