### ISSUE TITLE
Email authentication and verification using Nodejs, Express, and Firebase

### ISSUE THREAD

**Issue by phinaomondi** [section-engineering-education/engineering-education#1822]
### Proposed title of article
Email authentication and verification using Nodejs, Express, and Firebase

### Introduction paragraph (2-3 paragraphs):
Email authentication is one of the most vital application features to implement. Unlike usernames and passwords, emails are easy to remember or retrieve when forgotten. When a system uses email authentication and verification, its users can verify their accounts by clicking a link sent to their emails. Moreover, password recovery procedure is made easier, since the application can allow users to request a password reset, and complete the process with a simple click of a link.

Firebase is a back-end framework that leverages programmers from the need to create their own back-end, encrypt passwords, and deploy their applications. Firebase streamlines the process of user authentication, database management, and analytics. Through firebase, authenticate users when signing in, sending them a link to click to sign in. In the process, the users' emails get verified. This prevents your application from loading the database with dummy emails.

This article helps you learn how to build user authentication and verification using Firebase and Nodejs. We will build and mini-login and registration system to test our implementation.

### Key takeaways: 
1.	Setting up a Nodejs application
2.	Connecting a Nodejs application with Firebase
3.	Email authentication using Nodejs.

### References: 
1. https://firebase.google.com/docs/auth/web/email-link-auth

**Comment by hectorkambow** [comment]
👋  @phinaomondi  

Is this the topic you were referring to with the Node.js?

**Comment by phinaomondi** [comment]
Yes.

**Comment by hectorkambow** [comment]
Nice topic - approved 👍 

Be sure to check out our [resources pages](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more helpful link and tips to improve articles.
