### ISSUE TITLE
Designing IoT Solutions

### ISSUE THREAD

**Issue by OMONDIELLY** [section-engineering-education/engineering-education#1825]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Designing IoT Solutions
### Introduction paragraph (2-3 paragraphs):
The emergence of disruptive technologies such as Big data, AI, and Internet of Things (IoT) has brought a rapid growth in the Fourth Industrial revolution. The industrial revolution being data driven, is the primary reason for the rise in development of IoT applications and solutions.

IoT solutions and applications leverage on network of physical objects -''things'' that are embedded with sensors, software and data for the purposes of connecting and exchanging data over a network or the internet. This article will give readers an overview of what is takes to design IoT solutions.   
### Key takeaways: 
1. What is IoT
2. IoT architecture
3. IoT protocols
4. IoT development platforms and use cases
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@OMONDIELLY it seems you have two topic suggestions open. Please pick one to elaborate and proceed with 👍

**Comment by OMONDIELLY** [comment]
Hi @hector , I'll go with the recently sent issue (#1825). Thanks for the
heads up

**Comment by OMONDIELLY** [comment]
Hi.. does this mean that I can go ahead with this or wait for Molly to send an approved tag?

**Comment by hectorkambow** [comment]
@OMONDIELLY seems like a cool topic - approved. 👍
