### ISSUE TITLE
Consuming co-operative bank API using Node.js

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#1829]
### Proposed title of article
Consuming co-operative bank API using Node.js

### Introduction paragraph (2-3 paragraphs):
Co-operative bank is a financial services institution operating in East African community. As of 2018, it had registered over 7.8 million users. The API from co-operative bank is a simple restful API that enables developers to ship functionalities provided by the bank to their applications. In this article, we will implement various functionalities provided by the API to a Node.js application.

### Key takeaways: 
- How to create a co-operative bank developer account.
- How to fetch resources from an external restful API in Node.js.
- How to implement various functionalities provided by the co-operative bank API on a Node.js application.

### References: 
- https://developer.co-opbank.co.ke:9443/store/apis/documentation

**Comment by hectorkambow** [comment]
Great topic - approved
