### ISSUE TITLE
Getting Started With Node.js - OS Module

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#1831]
### Proposed title of article
Getting Started With Node.js - OS Module 

### Introduction paragraph (2-3 paragraphs):
The Node.js OS module has many useful utility functions for getting information about the computer system that the OS module’s program it is running on. It can provide information about hardware like CPUs, endianness, the home directory, IP address, hostname, the platform the program is running on, system uptime, information about the currently logged in user and more.

### Key takeaways: 
1.os.EOL- The operating system-specific end-of-line marker.
2. os. arch()-The function returns a string that tells us the operating system CPU architecture that the Node.js binary is compiled on.
3.os.endianness
The os.endianness() function returns a string identifying the endianness of the CPU from which the Node.js run-time binary is compiled from.
And other core OS module features in Node.JS

**Comment by hectorkambow** [comment]
@jumamiller  

👋  Nice topic - seems like a great fit for the Node.js focus. Topic - approved.

We really want to encourage students to use this form to start the bulk of the intro for their articles. 

This will help us get a better idea of the tone, quality, and direction of the article. 

Can gauge much from the two sentences provide - one which seems to be a bit of a run on. 

Please be sure to submit throughly reviewed and polished (ready to be published) PR - for the peer reviewer team to review. 

With the tiered payout gone - we can only review or close the PRs moving forward. 👍  
Thank you
