### ISSUE TITLE
A beginner's guide to memoization and Dynamic Programming in Python

### ISSUE THREAD

**Issue by elkiplangat** [section-engineering-education/engineering-education#1833]
### Proposed title of article
A beginner's guide to memoization and Dynamic Programming in Python

### Introduction paragraph (2-3 paragraphs):
Memoization is the process of saving the results of a function to a cache to improve its performance. It is the technique where we ensure that the function does not run for the same inputs more than once; instead, we return a cached result to reduce the running time of an algorithm.

Dynamic programming is an algorithm technique where we break down a problem into simpler, smaller subproblems, find the solutions to these sub-problems then use these solutions to provide an optimal solution to the original problem.
In this article we are going to introduce the reader to these two concepts using relevant examples then we are going to use them to solve a common optimization problem.

### Key takeaways: 
1. What is Dynamic programming.
2.  What is memoization.
3. How to use memoization and DP in python
4. How to solve the 0-1 Knapsack problem  using DP and memoization in python

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
👀  very cool topic - just want to make sure there is not much overlap with [this article](https://www.section.io/engineering-education/introduction-to-dynamic-programming/)

Want to make sure this new article will cover a new unique approach 👍

**Comment by elkiplangat** [comment]
The article introduces the reader to d.p but only talks about tabulation, they linked to an external source when it came to memoization. In this article, I'll be focusing on memoization and how to use it to solve the Knapsack problem. What do you think, @hectorkambow  ?

**Comment by hectorkambow** [comment]
@elkiplangat My apologies for the delayed response - please always reach out via Slack for the quickest possible reply. 

regarding your topic - if you would like to continue - please do so - approved.

**Comment by hectorkambow** [comment]
@elkiplangat  Just wanted to follow up on this Topic - before closing it to clear up the queue.

**Comment by elkiplangat** [comment]
Hello, @hectorkambow sorry about the late reply, I have been busy with school work. Let me start writing right away.
