### ISSUE TITLE
Getting started with Nodejs EJS templating engine

### ISSUE THREAD

**Issue by qawuor** [section-engineering-education/engineering-education#1834]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Introduction paragraph (2-3 paragraphs):
EJS is a simple templating language that lets you generate HTML markup with plain JavaScript. EJS simply stands for Embedded JavaScript templates, and we can use it both server-side or client-side.

In the article I will introduce the reader to EJS templating engine, explain how to add it to a Nodejs project, and finally use it to generate an HTML page. Throughout the tutorial, I will be explaining how to build a webpage using EJS templating engine.

**Basic syntax**
- <% 'Scriptlet' tag, for control-flow, no output.
- <%= Outputs the value into the template (HTML escaped).
- <%- Outputs the unescaped value into the template.

### Key takeaways: 
1. The reader will be able to setup EJS in a Nodejs project.
2. The reader will be able to use various EJS templating tags. 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Nice topic 👍  approved @qawuor
