### ISSUE TITLE
Nodejs SMS Integration with Vonage’s SMS API

### ISSUE THREAD

**Issue by mercymeave** [section-engineering-education/engineering-education#1838]
### Proposed title of the article
Sending messages in Nodejs using Vonage's SMS API

### Introduction paragraph (2-3 paragraphs):
Short Message Service (SMS) is one of the best marketing strategies that organizations can use to keep their clients close.  SMS integration in a mobile or a web application effectively reaches out to customers. Most people check their message inbox than emails, besides, SMSs are mobile-friendly, and reach a comprehensive demographic cover.

Vonage's SMS API allows programmers to integrated messaging services into an application. The  API can easily be used by applications to send and receive text messages from users worldwide. Vonage's API's benefits are support for local phone numbers, low latency, high delivery rates, and support for modern web technologies.

This tutorial will build a node application that sends messages to a phone number supplied using Vonage's Short Message Service API.

### Key takeaways: 
After this article, the reader should :
1.	Understand how Vonage's SMS API works
2.	Integrate Vonage's SMS API into a node application
3.	Send messages using Vonage's REST API in a Node application.

### References: 
1.	https://developer.nexmo.com/messaging/sms/overview

**Comment by hectorkambow** [comment]
👋  @mercymeave  Good morning. 

Really nice topic - seems to be a great fit. 

Just wanted to call attention to a few minor readability challenges in your description - please be sure to go through our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for helpful links to help improve the article before submission.

Thank you.

**Comment by mercymeave** [comment]
Alright. Thank you @hectorkambow
