### ISSUE TITLE
 How To Create an NFT Art using Rarible

### ISSUE THREAD

**Issue by wmkinyan** [section-engineering-education/engineering-education#1839]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

How To Create an NFT Art using Rarible

### Introduction paragraph (2-3 paragraphs):

Non-Fungible Tokens (NFTs) are a new type of unique and indivisible blockchain-based tokens introduced in late 2017. It is simply a digital representation that cannot be equally swapped or traded for another NFT of the same type. NFTs can represent a digital art, an event ticket, in-game item, or virtual property.
In this tutorial, I will go over the process of Creating a Non Fungible Tokens (NFT) digital art using the Rarible app. If you are interested in turning your art into Crypto tokens on the Ethereum Blockchain this is your ticket!

### Key takeaways:
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

In this article, we will discuss 4 important things:

1. Briefly introduce Non-Fungible Tokens (NFTs)?
2. Discuss the Rarible app.
3. Create our own NFT digital Art
4. Sell our NFT

### References:
Please list links to any published content/research that you intend to use to support/guide this article.

1. [Rarible](https://app.rarible.com/)
2. [How to setup Metamask](https://www.youtube.com/watch?v=4UCsPWQdVmw)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Although we like the topic suggested here. 🤔 
@wmkinyan , however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀 

Or if you could find a way to orient this topic with a more practitioner-focused content approach.

**Comment by hectorkambow** [comment]
@wmkinyan  

Apologies that this topic got closed (and another just like it was approved) - can we build upon this topic to make your article more practioner-focused or a natural next step of the Topic "what is an NFT" ?? 

Thank you - approved.

cc @ahmadmardeni1

**Comment by wmkinyan** [comment]
@hectorkambow @ahmadmardeni1 I've slightly edited my topic issue. I'll be writing a tutorial on how to create an NFT art using raribles. @Jethro-magaji  can write about getting started with NFTs while I focus on How to create an NFT art. Once published, I'll link my tutorial to his for the benefit of our readers

**Comment by hectorkambow** [comment]
@wmkinyan  THank you very much for shifting the topic focus - this will be helpful to reader - by ensuring we have a wide breath of knowledge around this topic. 

Yet - this new topic - creating NFT art on the Rarible platform - is way _outside of our preferred topic areas._ 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 


The topic need to be technical is some format - this topic is strictly how to create NFT art - which granted is an awesome topic - just not in our area(s) of focus.  

We have turned down similar type of topics (for example design oriented topics). 

Again - apologies for any inconvenience - but feel free to submit another topic - anything in the blockchain space (from a technical POV is welcome).

**Comment by ahmadmardeni1** [comment]
Hey 👋 @wmkinyan 
This is a great topic but as Hector said, it is way outside of our preferred topic areas. 

@Jethro-magaji is writing an introductory guide on how to mint an NFT using Solidity: https://github.com/section-engineering-education/engineering-education/issues/2865

You can both collaborate in a way that you build on top of his tutorial, maybe an advanced tutorial - I believe this topic is somehow huge and may need 2 articles to fully cover it.

Please discuss here and let's decide what you both will work on. @wmkinyan @Jethro-magaji 

(I didn't use Solidity before tho, just took a look at [this tutorial](https://betterprogramming.pub/how-to-create-nfts-with-solidity-4fa1398eb70a) so please let me know your thoughts.
cc @hectorkambow

**Comment by Jethro-magaji** [comment]
Hi @wmkinyan sorry your topic suggestion was closed. If you have any idea, you want us to collaborate on, I would be glad to work with you. Thanks.

**Comment by hectorkambow** [comment]
@wmkinyan 

Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

Please create a NEW topic form for the PR if and when the articles is completed. (lets reference this topic issue in the new one as to keep track of the conversation). Also ping us that you made a new topic via slack to get it reviewed/approved asap. 

Thank you 🚀  
Looking forward to some solid awesome articles.
