### ISSUE TITLE
How to Connect MongoDB to Node.js Using Mongoose

### ISSUE THREAD

**Issue by nancy-maina** [section-engineering-education/engineering-education#1841]
### Proposed title of article
How to Connect MongoDB to Node.js Using Mongoose

### Introduction paragraph (2-3 paragraphs):       
MongoDB is one of the most widely used No-SQL databases in the developer world today. No-SQL databases allow developers to send and retrieve data as JSON documents, instead of SQL objects. To work with MongoDB in a Node.js app, we need Mongoose.

[Mongoose.js](https://github.com/Automattic/mongoose) offers an "elegant MongoDB object modeling for node.js". It connects your MongoDB cluster with your Node app. It allows you to define objects with a strongly typed schema that is mapped onto your MongoDB document. Mongoose provides a lot of functionality for creating and working with schemas. In this tutorial we will look at how to integrate MongoDB with a Node.js application.

### Key takeaways:
By the end of this tutorial, the reader will be able to:
1. Install Mongoose on a Node.js environment.
2. Import and setup Mongoose.
3. Create a database connection using Mongoose.
4. Verify the connection by performing a GET.

### References: 
N/A

**Comment by hectorkambow** [comment]
Sounds like a good topic 👍  approved @nancy-maina
