### ISSUE TITLE
Integrating Payment Gateway in Node JS

### ISSUE THREAD

**Issue by Richu98** [section-engineering-education/engineering-education#1842]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Integrating Payment Gateway in Node JS

### Introduction paragraph (2-3 paragraphs):
What is a Payment Gateway?
In simple words, Payment Gateway is a service that helps us to collect payments for the products/service we deliver.

But you may be thinking about why we need one when we have an option to flash your payment address and take the payment from the customer. Yes, it will work when you are starting up but it is a lot of work to track the payment or to process a refund. All these are manual work where the error rate is more.

It is an integral part of any e-commerce site. Since Pandemic as hit more number of people are buying online and this trend will only increase in years to come. So this skill has got a huge demand and it is a must known skill for a web developer.

### Key takeaways: 

- Why we need a payment gateway?
- Some popular payment gateways and their comparison?
- What are all things we should consider while selecting a payment gateway?
- One main issue you will face while receiving payments(late payment reconciliation)
- How we will integrate stripe/razorpay payment gateway in nodejs?

### References: 
-https://stripe.com/docs
-https://razorpay.com/docs/
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Richu98 

There are some significant readability challenges in your description that raise concerns over how much review/editing would be required from our peer review team. 

We don't provide editing services and recommend that students leverage online editing services (there are both free and paid services that [you can explore](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md)), or try engaging with the community or other peers in your network to have them review prior to submitting a revised proposal. 

Thank you.


To continue please please be submit a polish and publish ready to form to be approved.

**Comment by hectorkambow** [comment]
closing to clear up the queue - can always resubmit a new topic form when ready 👍
