### ISSUE TITLE
Debug Android Application Using Wifi.

### ISSUE THREAD

**Issue by paulnjoroge789016** [section-engineering-education/engineering-education#1843]
### Proposed title of article
Debug Android Application Using WiFi.

### Introduction paragraph (2-3 paragraphs):
We will learn how android debug bridge works and why it is important to your career in developing android applications. Most people struggle in debugging their application due to: 
 1. Either their laptop or computer cannot support running emulators.
 2. Or whether you can have a device to test your application and you don't have a cable.
 3. Or even sometimes the cable is broken.

If you face the above problems don't worry I got your back. I will teach you how to connect your android studio to a physical device using WiFi or mobile hot-spot and thus debug your application with ease.

### Key takeaways: 
You will:
 1. Understand how android debug bridge works.
 2. Learn how you can connect you physical device to android studio using WiFi.
 3. Learn how you can connect you physical device to android studio using mobile hot-spot if you don't have WiFi.
 4. Reduce the expense of buying USB cables every now and then.

**Comment by hectorkambow** [comment]
Sounds like a cool topic. 🤔 @paulnjoroge789016  - approved. 

One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. 

This will help increase the likelihood of your article getting published and you receiving a payout :)

Thank you 🚀

**Comment by hectorkambow** [comment]
@paulnjoroge789016 just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
