### ISSUE TITLE
How To Troubleshoot A Network Using Traceroute Utility

### ISSUE THREAD

**Issue by Su-sid** [section-engineering-education/engineering-education#1845]
### Proposed title of the article
Network Troubleshooting Using Traceroute Utility

#### Introduction

The internet is a revolutionary technological marvel that has allowed for faster transfer of data between people. The world has been converted into a global village through the internet, allowing businesses to thrive as they offer their services. The internet constitutes a series of interconnected routers that transfer data from one computer to another. Due to the importance that the internet possesses, any networking professional must first be equipped with the basic network troubleshooting skills to allow them to be able to diagnose and repair network issues.

#### Definition

**Traceroute** is a command-line utility used in network troubleshooting to find the exact route data packets take as they travel across the internet from a source to their destination addresses.

#### Other uses of traceroute

- The utility can show an estimate of the time taken by packets as they move through intermediate routers. 
- Traceroute is used to determine routers and devices' names and identities within the chosen destination path.

### Key takeaways: 
At the end of the article the reader will be able to understand:

1. How to use traceroute on all three major operating systems.
2. The background functionality of traceroute.
3. The various functions of traceroute.
4. How to interpret data produced by traceroute utility.
5. How to use traceroute to run IPv4 and IPv6 addresses.

### References: 
[PC & Network Downloads](https://www.pcwdld.com/traceroute)

**Comment by hectorkambow** [comment]
seems like an interesting topic 👍  - approved @Su-sid
