### ISSUE TITLE
Integrating Safaricom C2B MPESA API  using PHP

### ISSUE THREAD

**Issue by tambastar** [section-engineering-education/engineering-education#1849]
Integrating Safaricom C2B MPESA API  using PHP

Safaricom is a telecommunication Company in the East and Central Africa region. As of June 2019, it had over 33.1 million subscribers. The API from Safaricom M-Pesa is a restful API that enables developers to query M-Pesa System for different Functionality. In this article, we will implement Customer to Business (C2B) using the API to a PHP application.

### Key takeaways:
1. How to create a Safaricom daraja developer account.
2.  Implement C2B in the PHP application

### Reference
https://developer.safaricom.co.ke/docs

**Comment by hectorkambow** [comment]
sounds like a cool topic - approved 👍 @tambastar

**Comment by hectorkambow** [comment]
@tambastar just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
