### ISSUE TITLE
Concepts and Configuration of the Spanning Tree Protocol

### ISSUE THREAD

**Issue by Dawe-7** [section-engineering-education/engineering-education#1851]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Concepts and Configuration of the Spanning Tree Protocol.

### Introduction paragraph (2-3 paragraphs):
Loop prevention is one of the most important considerations when developing a switched network. In a switched network, once a loop forms, the amount of traffic that can be exchanged between switches easily consumes all of the bandwidth available within each of the affected switches. One way to avoid loops is to provide only a single path between switches and to ensure that there is no path continuity in the switched network. The Spanning Tree Protocol (STP) is capable of preventing loops in the switched network. It accomplishes this by blocking redundant paths between switches for a short period of time. This article reviews the configuration needed to deploy STP on a switch and looks at some of the based STP concepts.

### Key takeaways: 
1. What is STP
2. Purpose of STP
3. STP operations
4. Advantages of STP

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
good topic @Dawe-7  - approved. 👍 
One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
