### ISSUE TITLE
Getting started with Strapi - A Node.js API CMS

### ISSUE THREAD

**Issue by geoffrey45** [section-engineering-education/engineering-education#1852]
### Proposed title of article
Getting started with Strapi - A Node.js API CMS

### Introduction paragraph (2-3 paragraphs):
Node.js is one of the most used backend technologies used today. Node.js can be used to build many types of apps and APIs.

Strapi is an open-source Node.js headless content management system (CMS) for building customizable APIs. It allows developers to focus on shipping software instead of coding software by providing an API management systems. Using an easy to use interface, devs can create and expose APIs without much coding.

Strapi allows developers to quickly build the backend logic using customizable routes, plugins, components and content types. It can be integrated with major SQL
 and NO-SQL databases eg. MongoDB.

In this tutorial, we are going to create a fully functional API using Strapi.

### Key takeaways: 
By the end of this tutorial, the reader will be able to:
1. install and setup Strapi
2. Configure database for use with Strapi
3. Use Strapi content types, users, components, etc.
4. Set roles and permisiions
5. Publish and consume the API

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a cool topic - approved @geoffrey45  

Moving forward please be sure to to add more to these topic forms - we encourage students to use this to frame their thinking and it allows us to really get a sense for the overall quality of the incoming article 👍
