### ISSUE TITLE
An Introduction to CI/CD Tools

### ISSUE THREAD

**Issue by corpsgeek** [section-engineering-education/engineering-education#1854]
### An Introduction to CI/CD Tools
Continuous Integration is a software engineering practice that ensures each developer in a team merges all activities with that of other developers in an environment

### Introduction paragraph (2-3 paragraphs):
Continuous integration (CI) and continuous delivery (CD) integrate a culture, set of operating principles, and set of practices that enable application development teams to make more frequent and consistent code changes. The implementation is also called the pipeline of the CI/CD. This article will cover the  top 5 CI/CD tools and their workflow

### Key takeaways: 
- Values of CI/CD 
- Understand the features of Bamboo and why you should use it as a CI/CD tool
- Understand the features of Jenkin and why you should use it as a CI/CD tool
- Understand the features of CircleCI and why you should use it as a CI/CD tool
- Understand the features of Buddy and why you should use it as a CI/CD tool

### References: 
N/A

**Comment by hectorkambow** [comment]
@corpsgeek 
Just want to make sure that this article will be covering topics not already discussed in any of the [already published works](https://www.section.io/engineering-education/search/?q=CI/CD%20Tools)

🤔  
sounds like a helpful article - approved 👍

**Comment by corpsgeek** [comment]
Yes, @hectorkambow  gone through the previous content, and it will be different.
