### ISSUE TITLE
Understanding Simulink using Matlab

### ISSUE THREAD

**Issue by mohamedgh16** [section-engineering-education/engineering-education#1858]
### Proposed title of the tutorial.
Understanding Simulink using Matlab.

### Introduction paragraph(s):
**Simulink** is a MATLAB-based graphical programming environment for modeling, simulating, and analyzing multi-domain dynamical systems. Its primary interface is a graphical block diagramming tool and a customizable set of block libraries. It offers tight integration with the rest of the MATLAB environment and can either drive MATLAB or be scripted from it. Simulink is widely used in automatic control and digital signal processing for multi-domain simulation and model-based design.

In this tutorial, we will use the *Simulink* library browser to understand the blocks, waves & functions that it has and perform a set of operations on a set of waves and plot each one of them on a scope.

### Key takeaways: 
- Understand the Simulink library browser.
- Perform logical & arithmetic operations.
- plot singular & compounded waves.

### References: 
https://en.wikipedia.org/wiki/Simulink.
https://www.mathworks.com/products/simulink.html.

**Comment by hectorkambow** [comment]
Sounds like a cool topic - I think it already is different enough just want to make sure we dont cover much of what was [covered here](https://www.section.io/engineering-education/getting-started-with-matlab/).

Topic approved 👍 @mohamedgh16

**Comment by mohamedgh16** [comment]
Roger that 👍.
@hectorkambow
