### ISSUE TITLE
Why you should use Celery with RabbitMQ

### ISSUE THREAD

**Issue by edeediong** [section-engineering-education/engineering-education#1860]
### Introduction paragraph (2-3 paragraphs):
In today's technology space, there is an increase in event-driven architectures as companies develop solutions that require asynchronous communication between their microservices. Ingesting these events faster in system architecture and processing them enables system architectures to be persistent, resilient and allows batch processing of data. Celery and RabbitMQ are some tools used in these architectures. Choosing the right combination of tools and viewing an example of these tools that goes beyond the ["hello world"](https://docs.celeryproject.org/en/stable/getting-started/brokers/rabbitmq.html) is what this article cover.

### Key takeaways: 
* Differentiate between Message Queues and Task Brokers
* Identify examples of message queues and task brokers
* Understand why to choose The Celery & RabbitMQ Combo
* Be able to set up Celery with RabbitMQ

### References: 
https://docs.celeryproject.org/en/stable/getting-started/brokers/rabbitmq.html
https://dog.ceo/

**Comment by hectorkambow** [comment]
topic approved 👍 @edeediong
