### ISSUE TITLE
Getting Started With Spring WebSockets in Java

### ISSUE THREAD

**Issue by john-amiscaray** [section-engineering-education/engineering-education#1861]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article

Getting Started With Spring WebSockets in Java

### Introduction paragraph (2-3 paragraphs):

Nowadays, web applications have become much more powerful than they once were. You can now have real-time functionality in the form of chat applications or even multiplayer games. All this has been made possible by the use of WebSockets.

For those who don’t know, WebSocket is a communications protocol. It's useful for opening persistent two-way connections between web client and server. This allows you to establish real-time interaction you could never do with only HTTP. In this guide, we will explore in further detail the theory behind this protocol. Not only that but we'll explore a subprotocol that you can use alongside it. Then, we will go over how to implement WebSockets in Java using Spring Boot, testing it with a simple web client. We'll also go over some of the basics to secure WebSocket connections.

### Key takeaways: 
- What are WebSockets and what are the advantages of using them?
- What is the STOMP subprotocol and why might we need it?
- How to implement a WebSocket server using Spring Boot
- How to connect to a WebSocket server client-side
- How to secure WebSocket connections with Spring

### References: 
https://stackoverflow.com/questions/45405332/websocket-authentication-and-authorization-in-spring

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
sounds like an interesting topic - approved @john-amiscaray
