### ISSUE TITLE
Introduction to Sequelize ORM for Node.js

### ISSUE THREAD

**Issue by OkothPius** [section-engineering-education/engineering-education#1864]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Introduction to Sequelize ORM for Node.js

### Introduction paragraph (2-3 paragraphs):
Chances are that when using relational databases, we create separate scripts when defining our database tables. This adds unnecessary friction and mixing SQL and JavaScript in the same script is not sustainable. This leads to a lot of boilerplate code and little business logic which are not easy to maintain.

Using Sequelize on the other hand, help us avoid writing SQL queries altogether. Instead, we define models then use the `sync()` function to look through all the models we're defining and generate a SQL query under the hood which in turn creates associated tables for us. This enables us to write less junk code making our code easy to read, maintain and extend.

This article will cover what problems Sequelize solves as well as its pros.

### Key takeaways: 

After this article, the reader should:

1. Know what Sequalize is
2. Understand in-depth what an ORM is
3. Understand SQL database
4. Benefits of Sequalize

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Seems like a good topic @OkothPius  approved 👍
