### ISSUE TITLE
How to set up a Node.js Express server for React

### ISSUE THREAD

**Issue by verah-tech** [section-engineering-education/engineering-education#1868]
### Introduction:

React is a JavaScript library used to build user interfaces, can be used to develop single-page applications using reusable UI components. It’s used for frontend development and can be connected to the backend server. In this guide, I will develop a simple React App and connect it to the server build using the Node.js server.

### Key takeaways: 

The reader will be able to:
Create a simple Web App using React as a frontend
Set up an Express server to act as backend
Set up a proxy to call the Express backend from React

### References: 

N/A

**Comment by hectorkambow** [comment]
@verah-tech seems like a good topic - approved 👍  

It would be helpful to name the type of React app you are building to name it in the title for better searchability by a reader 🚀

**Comment by verah-tech** [comment]
@hectorkambow The React App am going to build is a Demo App supposed to fetch the route from the backend server and display the success message on the frontend. Thanks
