### ISSUE TITLE
Introduction to computer vision with opencv in python.

### ISSUE THREAD

**Issue by mykolkiprono** [section-engineering-education/engineering-education#1869]
### Proposed title of the article
Introduction to computer vision with opencv in python.

### Introduction paragraph (2-3 paragraphs):
Opencv is an open-sourced cross-platform library used in computer vision. It mainly focuses on basic image processing, video capture and analysis, face recognition, and object detection. Its real-time application domains include autonomous vehicles, vision-guided robotics, industrial inspection(defect detection), etc. 

In this article, we are going to cover the introductory part of opencv .

### Key takeaways: 
By the end of this article, the reader should be able to perform the following operations with opencv:
1. Perform basic image operations.
2. Core image processing.
3. Feature Detection.
### References: 
https://www.tutorialspoint.com/opencv/opencv_overview.htm

**Comment by hectorkambow** [comment]
Sounds like an interesting tutorial. 
Lets be sure to not cover too much of what has been already published [here](https://www.section.io/engineering-education/search/?q=computer%20vision)

approved 👍  @mykolkiprono

**Comment by hectorkambow** [comment]
just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed. @mykolkiprono
