### ISSUE TITLE
Building a simple cryptocurrency Blockchain in Nodejs

### ISSUE THREAD

**Issue by yitzackRabin** [section-engineering-education/engineering-education#1876]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
The unprecedented rise of cryptocurrencies, and their underpinning blockchain technology, have taken the world by storm. The blockchain technology is receiving a lot of attention because of its ability to enhance security in trustful environments, enforce decentralization, and make processes efficient.
Blockchain is the technology that powers digital currencies, such as Bitcoin and Ethereum. It is an innovative distributed public ledger technology that maintains a continuously growing list of records, referred to as blocks, which are connected securely using cryptography.

Traditionally, Python has been the recognized programming language for blockchain development. However, with the proliferation of this amazing technology, the development options have also increased — and Node.js has not been left behind.In this tutorial, I’m going to talk about how to build a simple cryptocurrency blockchain in Node.js and help understand the how blockchain works and it;s implementation in code.

### Key takeaways: 
1. what is blockchain and how it works
2. How to create blockchain
3. Understanding Nodejs 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a very cool topic - approved @yitzackRabin
