### ISSUE TITLE
How To Auto-generate Admin Panels for Node.js with AdminBro

### ISSUE THREAD

**Issue by KayveTech** [section-engineering-education/engineering-education#1878]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of the article
How To Auto-generate Admin Panels for Node.js with AdminBro

### Introduction paragraph (2-3 paragraphs):
When crafting any backend infrastructure, we often need to check if the data that we are handling is being saved in the database in development. In such cases, we have to open up a database query tool or mock the API via Postman or Swagger. This is not always a convenient way especially when it needs CRUD operations. You have to build a separate admin panel for basic CRUD operation which doesn’t worth it.
In this tutorial, we will implement an admin panel within minutes without writing any front-end code, more like the Django admin but in a Node.js project. We will use Express and  the database with Mongoose.
### Key takeaways: 
1. How To set up Express in Node.js
2. Initializing  and configuring AdminBro in Express project
3. How To create data models using Mongoose

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
sounds like an interesting topic - approved @KayveTech

**Comment by hectorkambow** [comment]
Im taking this topic was not followed through??
 @KayveTech 
 
 Since there is another one open - we will go ahead and close this one for now. Can be re-opened later.
