### ISSUE TITLE
Working with APIs in TypeScript

### ISSUE THREAD

**Issue by cyberShaw** [section-engineering-education/engineering-education#1880]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article

Working with APIs in TypeScript

### Introduction paragraph (2-3 paragraphs):

TypeScript was introduced by Microsoft as an extension to JavaScript. It takes the versatility of JavaScript and enhances it with type definitions. TypeScript is used along with a lot of popular frameworks like React.js for enterprise applications. In this article, we shall take a look at how to harness the power of TypeScript to consume APIs.

### Key takeaways: 

- The reader will be able to understand how to use TypeScript in a basic web application.
- The reader will be given a hands on about how to create APIs using TypeScript and Node.js.
- The reader will be able to extend the usecases and build their own webapp using TypeScript.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
https://www.typescriptlang.org/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@cyberShaw 
 please wait until the one waiting to be published to be reviewed - 👍 (waiting for final review)

thank you.

We can re-open this one when the other one publishes.

**Comment by cyberShaw** [comment]
> @cyberShaw 
>  please wait until the one waiting to be published to be reviewed - 👍 (waiting for final review)
> 
> thank you.
> 
> We can re-open this one when the other one publishes.

Hey Hector, I just figured since it is in the final review phase, I could start working on this topic if you gimme the approval

**Comment by hectorkambow** [comment]
I think we recently published a typescript article - please be sure to check it to see if we can reference it in any way 👍

**Comment by hectorkambow** [comment]
Sounds like  cool topic - I'd add the type of app you plan on creating in the title to make it stand out. @cyberShaw  
Approved
