### ISSUE TITLE
How to perform a reverse image search in Node.js using the TinEye Reverse Image Search API

### ISSUE THREAD

**Issue by munubi254** [section-engineering-education/engineering-education#1882]
### Proposed title of the article
Using the TinEye Reverse Image Search API in Node.js

### Introduction paragraph (2-3 paragraphs):
At one point or another, we get a need of searching online for an image. Perhaps we need one with better quality, or we need to see the origin of the image or any other reason. Reverse image searching now comes in and here we are going to delve into the API of one of the commonly used tools, the TinEye reverse image search. We will look at how to feed images and get the results using Node.js.

### Key takeaways: 
In the end, the reader will learn about:

- Reverse Image Searching
- The TinEye Reverse Image Search
- Consuming the TinEye Reverse Image Search API
- Troubleshooting common errors that occur during the process

### References: 
[TinEye API documentation](https://services.tineye.com/developers/tineyeapi/what_is_tineyeapi)

**Comment by hectorkambow** [comment]
@munubi254  good topic - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
