### ISSUE TITLE
Client-Side Rendering (CSR) vs. Server-Side Rendering (SSR) vs. Static-Site Generation (SSG)

### ISSUE THREAD

**Issue by mosesreigns** [section-engineering-education/engineering-education#1883]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of the article
Client-Side Rendering vs. Server-Side Rendering vs. Static-Site Generation

### Introduction paragraph (2-3 paragraphs):
In the development history, websites were just basic information with less or no on-page interactions. They were static webpages with no dynamic elements. HTML, CSS, and JavaScript are the standard ways to style, script, and display the page on the browser.  To display these HTML elements on the screen, you would prepare an HTML document and send it in on the server-side. When a user requests a page, the server will convert the HTML elements to meaningful information on the user’s screen. Websites were pretty much static. Server-side rendering was the only approach to load the .html page. This approach worked great at the time as most pages displayed plain text and images.

Fast-forward to today, this is no longer the case, and websites have advanced. Corporates want to get the dynamic content and display it right. They want websites that load fast, smooth with flawless performance, have a good user experience, and get search engine optimization right on search ranking results. They are the sales lead for most of the companies.

Today websites are much like applications. You can send messages, transact, shop, and much more. In short, more interactivity is need on the user end, and hence server-side rendering can longer handle all this and once. It is taking a backseat and giving way to many advanced rendering technologies. There several major players here. This includes Client-Side Rendering (CSR) vs. Server-Side Rendering (SSR) vs. Static-Site Generation (Pre-rendering). Develops often find themselves confused about these terms. If you get yourself in this circle, this tutorial is for you. We’ll discuss these technical terms, explore their pros and cons, and when to consider approach A or B.

### Key takeaways: 
- What is Client-Side Rendering
- What is Server-Side Rendering 
- What is Static-Site Generation

Client-Side Rendering vs. Server-Side Rendering vs. Static-Site Generation
- Pros
- Cons
- When to use Each approach

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
sounds like a helpful topic - approved @mosesreigns
