### ISSUE TITLE
Introduction to Python's Virtual Environments and Dependency Managers

### ISSUE THREAD

**Issue by FREDERICO23** [section-engineering-education/engineering-education#1887]
### Introduction to Python's Virtual Environments and Dependency Managers

When crossing the bridge from being a beginner to an intermediate, you'll start to work on projects. A big problem you'll often encounter is dependency conflicts which differ from one project to another. This is where Python's virtual environments come in.
Virtual environments are isolated Python environments where libraries, python interpreters, and scripts are installed separately from other virtual environments, and the default Python environment installed in the machine.

### Key takeaways: 
1. What are virtual environments?
2. Types of virtual environments in Python
3. How and where to use virtual environments

### References: 
[Python Virtual Environment](https://docs.python.org/3/library/venv.html#:~:text=A%20virtual%20environment%20is%20a,part%20of%20your%20operating%20system.)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @FREDERICO23

**Comment by hectorkambow** [comment]
merged
