### ISSUE TITLE
Documenting a Node.js REST API using swagger

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#1890]
### Proposed title of article
Documenting a Node.js REST API using swagger

### Introduction paragraph (2-3 paragraphs):
API (Application Programming Interface) documentation has vast advantages including improving the experience for developers consuming it. Swagger is a software tool used in designing, building, documenting, and using REST (Representational State Transfer) API's. In this article we will walk through the steps of documenting a Node.js REST API.

### Key takeaways: 
- How to set up a REST API in Node.js
- How to configure swagger in a Node.js REST API
- How to document a Node.js REST API using swagger

### References: 
- https://medium.com/swlh/automatic-api-documentation-in-node-js-using-swagger-dd1ab3c78284
- https://medium.com/wolox/documenting-a-nodejs-rest-api-with-openapi-3-swagger-5deee9f50420

**Comment by hectorkambow** [comment]
@mwangiKibui  seems like a very helpful article. 

I can't find any overlap (but if we could do a double check with any incoming articles and/or published articles) for potential overlap - or to see where we could build upon. 

If there is a specific type of app you will create for the tutorial - please place that somehow in the title as well. 👍  

approved

**Comment by hectorkambow** [comment]
@mwangiKibui  Please speak with @marienjus to see how your two articles will not overlap much 👍

**Comment by mwangiKibui** [comment]
@hectorkambow @Qodestackr is working with GraphQl API am working with REST API. Also we are using two different JavaScript frameworks.  To avoid the overlap I will include the framework in the title just like @Qodestackr had done.
