### ISSUE TITLE
Facebook OAuth in React Native Application using Firebase

### ISSUE THREAD

**Issue by zolomohan** [section-engineering-education/engineering-education#1891]
### Proposed title of the article

Facebook OAuth in React Native Application using Firebase

### Introduction paragraph(s):
OAuth is an open standard for access delegation, commonly used as a way for Internet users to grant websites or applications access to their information on other websites but without giving them the passwords.

In this tutorial, we'll learn how to authenticate users with their Facebook accounts using the authentication module in Firebase in a Non-Expo React Native application.

### Key takeaways

- Set up Firebase Project for Facebook OAuth.
- Add Login/Create account screen.
- Use the Firebase Auth module and authenticate users.
- Logout from the authenticated screen.

### References: 
N/A

**Comment by hectorkambow** [comment]
@zolomohan  please wait until the one waiting to be published to be reviewed - 👍  (waiting for final review)

thank you. 

We can re-open this one when the other one publishes.

**Comment by zolomohan** [comment]
@hectorkambow Reopening the topic suggestion since the other PR got merged.

**Comment by hectorkambow** [comment]
cool topic - approved. 

Lets try to find a way around the % issue 👍  

@zolomohan
