### ISSUE TITLE
How to use CORS in Node.js with Express

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#1895]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your articles a higher ranking.*

How to use Cors in Node.js

### Introduction paragraph (2-3 paragraphs):
CORS stands for Cross-Origin Resource Sharing. Allows us to bypass security applied to a Node.js API. An API is a set procedure for two programs to communicate. This means the two (client and server) have a different origin, i.e., accessing resources from a different server to the server you are in. In this case, trying to make a request to a resource on the server will fail. You are getting something from that server, and it's not the server you (the client) are coming from.

That's a security concern for the browser. These resources are meant to be consumed by other clients and servers. CORS comes into play to disable this mechanism and allow access to these resources. CORS will add a response header [access-control-allow-origins] and specify which origins are to be permitted the access.

CORS helps us to make sure that we are sending the right headers. This is done by sending the headers from the server to the client to inform the browser that the client can access the resources requested.

### Key takeaways: 
What is CORS
How CORS works
Using CORS with Express to access resources from a server

### References: 
https://www.npmjs.com/package/cors
https://expressjs.com/
https://www.npmjs.com/package/cors
https://nodejs.dev/learn/introduction-to-nodejs

### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
🤔  

Sounds like a helpful article - lets please be sure to build upon and not overlap the already published [content here](https://www.section.io/engineering-education/what-is-cors-policy/)

If so approved @kimkimani
