### ISSUE TITLE
Why Python is good for Machine Learning?

### ISSUE THREAD

**Issue by ogoti-lilian** [section-engineering-education/engineering-education#1901]
### Introduction:

Python can create applications ranging from web development to scripting and process automation. It is gradually becoming a choice for developers who are creating Artificial Intelligence, machine learning and deep learning projects. AI has created a world of endless opportunities for application developers. But what is it that makes Python so good for AI?

### Key takeaways: 

In this article, the reader will learn:

What is Machine Learning in relation to Artificial Intelligence?
The difference between  AI Machine Learning and Deep Learning.
The reasons that make Python best for Artificial Intelligence.

### References: 

N/A

**Comment by hectorkambow** [comment]
sound like a cool topic approved @ogoti-lilian  👍
