### ISSUE TITLE
Node.js vs Python: Which is the best Technology for backend Development?

### ISSUE THREAD

**Issue by Erastuskanyatta** [section-engineering-education/engineering-education#1907]
### Proposed title of article
Node.js vs Python: Which is the best Technology for backend Development?

### Introduction paragraph (2-3 paragraphs):
Node.js and Python are both amazing backend technologies for building dynamic web apps. The two of them fall under similar classification, yet their features are very different. There are those who argue that Node.js is better due to its high speed of execution while others choose Python because of its learning curve being shallow.

Before we argue that one is better than the other, let's first look at the primary differences between the two.

Node.js is an open-source, cross-stage, JavaScript runtime environment, based on Chrome's V8 JavaScript engine. The purpose of this engine is to compile JavaScript functions into machine code. It is well-known for its high speed and constantly advancing performance.

Python is a general-purpose programming language. It is used in Web Development to create dynamic websites using frameworks like Flask, Django, and Pyramid.

In this article, we are going to compare Node.js and Python for backend programming.

### Key takeaways:
In this article, we are going to look at the differences between Node.js and Python  based on:

1. Speed - which has the highest executing speed.
2. Universality - different ways in which the two languages can be used
3. Learning curve - which language is easier to learn and implement.
4. Extensibility - which one is easier to extend using plugins and packages
5. Syntax - which one offers developer friendly syntax

### References:
N/A

**Comment by hectorkambow** [comment]
🤔  

It sounds like a helpful topic - it sounds different enough - but if you could please go through and see if there will be any overalp with this [article here](https://www.section.io/engineering-education/node-vs-python/) or others in the similar topic. 

otherwise - approved.
