### ISSUE TITLE
Lists and Dictionaries in Python

### ISSUE THREAD

**Issue by duncandegwa** [section-engineering-education/engineering-education#1909]
### Proposed title of article
Working with Lists and Dictionaries in Python

### Introduction paragraph (2-3 paragraphs):
A list is an ordered collection of items. Lists enable you to store a set of items in place. In Python elements of a list are separated by commas and enclosed in square brackets []. 

In Python a dictionary is a collection of key value pairs where each key is connected is a value. In a dictionary order is not preserved compared to lists. A dictionary is wrapped in braces {}, with a series of key value pairs inside the braces. Acknowledging dictionaries empowers you to represent a variety of real-world objects more accurately.

One of the most powerful features of Python readily accessible to new programmers are lists and dictionaries, and they tie together many important concepts in programming. To acquire understanding on lists and dictionaries, this tutorial shows us how to start working with elements in a list, how to access the information once it’s in a dictionary and how to modify that information.

### Key takeaways
By the end of this tutorial, the reader should:
1.	Access, change, add, and remove elements in a list
2.	Sort and Slice a list
3.	Loop through a list 
4.	Access, add and remove new-key value pairs in a dictionary
5.	Loop through a dictionary

### References: 
N/A

**Comment by hectorkambow** [comment]
sounds like a helpful topic - approved 👍  @duncandegwa
