### ISSUE TITLE
How To Set-up Node.js API using Swagger, GraphQL and Hapi

### ISSUE THREAD

**Issue by marienjus** [section-engineering-education/engineering-education#1910]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How To Set-up Node.js API using Swagger, GraphQL and Hapi

### Introduction paragraph (2-3 paragraphs):
Separating frontend and backend has been the de facto way of building full-stack applications. This comes with the advantage of reusing APIs and a great separation of concerns.
Swagger is an Interface Description Language for describing RESTful APIs expressed using JSON. Swagger is used together with a set of open-source software tools to design, build, document, and use RESTful web services. Swagger includes automated documentation, code generation, and test-case generation.
In this tutorial, we will create a simple API that integrates the Hapi Node.js framework, GraphQL, MongoDB database, and Swagger API  documentation.

### Key takeaways: 
1. An introduction to API design
2. How to set-up GraphQL
3. Setting up Hapi framework in Node.js

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
sounds like a very helpful topic - but just want to make sure there is not too much overlap with this upcoming article being written
#1890

**Comment by Qodestackr** [comment]
He's setting up a REST API and I'm writing for GraphQL API. Not much overlap. Swagger is just a tool that documents APIs. And my framework for Nodejs is Hapi.js of which @mwangiKibui will be different I guess. @hectorkambow

**Comment by mwangiKibui** [comment]
Yes I am going with Express.js . I suggest I will change the title to be specific @Qodestackr

**Comment by Qodestackr** [comment]
Node.js is a runtime. A framework is like Express or Nest.js, meaning you using "pure Node" I say? I can remove Swagger if that makes it convoluted and my issue will still be well.

**Comment by mwangiKibui** [comment]
Am using Express.js sorry *
