### ISSUE TITLE
Understanding and implementing rate limiting in Node.js

### ISSUE THREAD

**Issue by paulodhiambo** [section-engineering-education/engineering-education#1919]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an article to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Introduction paragraph (2-3 paragraphs):
Rate limiting is a very powerful feature for securing backend APIs from malicious attacks and for handling unwanted streams of requests from users. In general terms, it allows us to control the rate at which user requests are processed by our server.

In the article, I will explain the different approaches to implementing rate limiting in theory, as well as the pros and cons of each. I will also get practical by implementing a selected approach, i.e., the most optimal for our use case in Node.js.

### Key takeaways: 
1. The reader will learn what is rate limiting and its importance.
2. The reader will learn how to create APIs in Node.js.
3. The reader will learn how to implement rate limiting in Node.js.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@paulodhiambo  seems like a cool topic- just want to make sure there won't be much overlap with this recently published article. 

https://www.section.io/engineering-education/implementing-rate-limiting-in-flask/
