### ISSUE TITLE
Building an Image Management Pipeline with Flask, Cloudinary, and MongoDB

### ISSUE THREAD

**Issue by LordGhostX** [section-engineering-education/engineering-education#1922]
### Introduction paragraph (2-3 paragraphs):
A content delivery network (CDN) allows for the quick transfer and retrieval of web assets (images, videos, HTML pages, stylesheets, JavaScript files) by distributing them to a group of servers that are geographically distant and work together to provide the required content to end-users.

In this article, we will be going over what CDNs are, the advantages of using CDNs in your application, explore how Cloudinary can be used in image management pipelines, and implement its comprehensive APIs and administration capabilities in a Python application with Flask and MongoDB.

### Key takeaways: 
By the end of this tutorial, the reader will be able to:
* define what CDNs are and know what Cloudinary is.
* build a CRUD application with Flask and MongoDB. 
* build a Python application that integrates Cloudinary comprehensive APIs and administration capabilities for image management pipelines.

### References: 
* https://www.cloudflare.com/en-gb/learning/cdn/what-is-a-cdn/
* https://cloudinary.com/documentation/cloudinary_get_started
* https://palletsprojects.com/p/flask/
* https://www.guru99.com/what-is-mongodb.html
* https://pypi.org/project/pymongo/
* https://pypi.org/project/cloudinary/

**Comment by hectorkambow** [comment]
Sounds like a very cool topic - approved. @LordGhostX

**Comment by hectorkambow** [comment]
@LordGhostX 
just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
