### ISSUE TITLE
How to Prevent Cross Site Scripting in Node.js

### ISSUE THREAD

**Issue by Pauline-Mwangi** [section-engineering-education/engineering-education#1927]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to Prevent Cross Site Scripting in Node.js

### Introduction paragraph (2-3 paragraphs):
Cross-Site Scripting (XSS) is a common attack based on code injection. Some developers do not understand how XSS works. A developer can not prevent XSS if he does not know how it works.
Attackers use vulnerable websites to inject malicious code or script. The malicious code is executed by the user (victim) while using the website. Therefore, the attacker gain access to sensitive and confidential information.
In this article, you will learn how XSS works and how to prevent it in relation to node.js.

### Key takeaways: 
1. What is Cross Site Scripting (XSS)
2. How XSS Works
3. Types of XSS Attacks
4. How to prevent XSS

### References: 
http://it.uobabylon.edu.iq/fileshare/articles/repository1_publication157312_4_3251.pdf
https://software-lab.org/publications/Synode_TR_Nov2016.pdf
https://link.springer.com/chapter/10.1007/978-981-15-5400-1_69

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - approved.

**Comment by hectorkambow** [comment]
merged
