### ISSUE TITLE
Node.js Structural Comparisons

### ISSUE THREAD

**Issue by pkalynan** [section-engineering-education/engineering-education#1928]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Node.js Structural Comparisons

### Introduction paragraph (2-3 paragraphs):
Node.js is a type of computer language based on JavaScript. When structuring codes to produce and generate results, the number of lines of code can become time efficient. This tutorial will display structural breakdowns of numerous scenarios by comparing Node.js to R-Programming, C++, and Java. 

R-Programming, C++, and Java were selected to differentiate components that can typically be found quickly with Node.js. The tutorial will extend to other areas of programming structure such as sequencing, organization, features, and available options. Applying these concepts might be beneficial to specific situations such as data science, applications with possible graphic user interface preferences, and general scripts.

### Key takeaways: 
* Possible benefits from less lines of codes.
* Providing opportunities for further adjustments may also be a possibility.
* Each programming language is chosen more often than others due to available options.
* Computer language applications may have special features for specific purposes.

### References: 
https://medium.com/analytics-vidhya/statistical-functions-in-node-js-12303286de4a

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a good topic - approved @pkalynan
