### ISSUE TITLE
How to implement API Rate Limiter in NodeJS

### ISSUE THREAD

**Issue by Olanetsoft** [section-engineering-education/engineering-education#1929]
### Proposed title of the article
How to implement API Rate Limiter in NodeJS

### Introduction paragraph (2-3 paragraphs):
A technique for restricting network traffic in a system is rate-limiting. It imposes a cap on how many times an operation can be repeated in a system in a given period of time.
Node.js is a free, open-source server environment. It uses javascript on the server and it runs  on various platforms (Windows, Linux, Unix, Mac OS X, etc.)

### Key takeaways: 
By the end of this tutorial, the reader will:

- Understand rate limiting.
- Understand the significance of restricting API request rates.
- Develop NodeJS APIs that restrict the number of requests that are accepted.

### Templates to use as guides
- [https://www.w3schools.com/nodejs/nodejs_intro.asp](https://www.w3schools.com/nodejs/nodejs_intro.asp)
- [https://www.npmjs.com/package/express-rate-limit](https://www.npmjs.com/package/express-rate-limit)

**Comment by paulodhiambo** [comment]
@Olanetsoft I have suggested this here #1919

**Comment by hectorkambow** [comment]
@Olanetsoft  

like @paulodhiambo mentioned - this one is in the works -perhaps you could tweak it to make it substantially different or suggest a new topic .
