### ISSUE TITLE
How to create image database using Matlab

### ISSUE THREAD

**Issue by atienodorine3** [section-engineering-education/engineering-education#1931]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
Face database are imagery data that are used for testing face processing algorithm. In the content of biometrics, database are collected and used to evaluate the performance of face recognition biometrics system.
There are so many image database available in the internet but if you want to make the database of your own faces then you can use this program. The framework of this program can be used to create the database for other many objects
In this case we will use the WEBCAM to make the number of required faces. Face database can be used to implement projects such as face recognition

### Key takeaways:
- How to use your WEBCAM to make snapshots of the face to make the database.
- How to create an image database with a particular number of images.
- Importance of image database.

**Comment by hectorkambow** [comment]
@atienodorine3  
seems like a cool topic 👍 

One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
