### ISSUE TITLE
Why Python is Essential for Data Analysis

### ISSUE THREAD

**Issue by majiezra** [section-engineering-education/engineering-education#1934]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Why Python is Essential for Data Analysis
### Introduction paragraph (2-3 paragraphs):
We live in the digital era of high technologies, smart devices, and mobile solutions. Data is a critical component of any enterprise. It is crucial to gather, process, and analyze data flow quickly and accurately. The data science industry is growing at a rapid pace, Data volume can be large, which makes information handling time-consuming.
Python is a widely-used programming language in scientific computing because its many data-oriented feature packages can speed up and simplify data processing, making it timesaving.
### Key takeaways: 
- overview of python
- What makes Python a brilliant choice for data analysis?

### References: 
Data Analysis from Scratch with python by peters morgan.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - approved. 
@majiezra
