### ISSUE TITLE
How to use Streams in Node.js

### ISSUE THREAD

**Issue by kayere** [section-engineering-education/engineering-education#1935]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to use Streams in Node.js

### Introduction paragraph (2-3 paragraphs):
Streams are objects that allow one to read data from a source or write to a destination in a continuous manner. Node.js has four types of streams; readable, writable, duplex, and transform. Each stream has an `eventEmitter` instance that emits different events at several intervals. 
These events are used to track and monitor the stream. Some of the most commonly used events are data, end, error, and finish. This article aims to take you through reading an writing a file using streams in Node.js.

### Key takeaways: 
The reader will;
1. Know what streams are.
2. Know various usages of streams in Node.js.
3. Understand all operations that can be done with streams in Node.js.
4. Understand the importance of using streams.
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Seems like a helpful answer - not sure if it would overlap with [article here](https://www.section.io/engineering-education/batch-processing-vs-stream-processing/) or if your article could build upon it - if it discusss similar subjects. 

otherwise - approved. @kayere

**Comment by kayere** [comment]
Hello @hectorkambow - I have checked the article that you have highlighted. It does not overlap with the one I have suggested. The both talk about different concepts.
