### ISSUE TITLE
Multithreading in Java

### ISSUE THREAD

**Issue by Jeff-mwangi** [section-engineering-education/engineering-education#1936]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Multi-threading in Java

### Introduction paragraph (2-3 paragraphs):
A thread is a lightweight process. They can be used to perform complicated tasks in the background without interrupting the main program. Any process can have multiple threads running concurrently in it that is referred to as multi-threading. It enables us to improve the responsiveness of a system.
For example in a web browser, we can have one thread which will load the user interface and another thread which will actually retrieve all the data that needs to be displayed in that interface.

We will learn how to create threads in your programs. It can be created by extending the Thread class or implementing the runnable interface.

### Key takeaways: 
1. What is a thread and multi-threading
2. Why we need Multi-threading
3. Create threads by extending the thread class 
4. Create threads by implementing the runnable interface.

### References: 
N/A

**Comment by hectorkambow** [comment]
🤔  @Jeff-mwangi  

Could you please expand upon how your content will differ from what is already available through any Java documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by Jeff-mwangi** [comment]
@hectorkambow I have changed my topic. Please check it

**Comment by hectorkambow** [comment]
sounds like a good one - approved @Jeff-mwangi

**Comment by hectorkambow** [comment]
merged

**Comment by hectorkambow** [comment]
https://github.com/section-engineering-education/engineering-education/pull/2432
