### ISSUE TITLE
How to Build a Speed Typing Game Using Javascript 

### ISSUE THREAD

**Issue by CallmeMukty** [section-engineering-education/engineering-education#1937]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to Build a Speed Typing Game Using Javascript.

### Introduction paragraph (2-3 paragraphs):
This tutorial focuses on using concepts such as Javascript, API calls, timers, DOM(Document Object Model) manipulation to build a speed typing game to improve your coding skills. 
This should be interesting because it is fun and educational at the same time. The game could also turn out useful as it could be used to test and improve your typing abilities while you would also be having fun.

### Key takeaways: 
After reading this article, the reader should understand:
How to fetch APIs using a random quote generator.
DOM Manipulation using Javascript.
How to use Javascript to set up a timer that accurately counts up in seconds. 
How to apply Async Function and Promises in Javascript.

### References: 
https://stateofjs.com/
https://www.w3schools.com/tags/att_script_defer.asp
https://www.w3schools.com/tags/att_script_defer.asp
https://www.w3schools.com/js/js_async.asp
https://www.w3schools.com/js/js_promise.asp

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a great topic - approved 👍  @CallmeMukty
