### ISSUE TITLE
Encryption in MongoDB.

### ISSUE THREAD

**Issue by HARITJOSHI1** [section-engineering-education/engineering-education#1940]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Encryption at rest in MongoDB.

### Introduction : 
The article is about Encryption at rest in MongoDB. In recent years, MongoDB has risen to become top player in non-relational database providers in the world and we all know that it is so much necessary and important to protect our data and databases from non legitimate access. 

So my article will give thorough knowledge and information about how to encrypt MongoDB databases using encryption at rest and also explain some other related terms regarding encryption in a clear and easy way so that the readers can realise the importance of implementing security features on databases. 

### Key takeaways: 
After reading the article readers will be able to understand :

1. What encryption at rest means in MongoDB. 
2. How to implement encryption at rest. 
3. Encryption key management in MongoDB. 
4. Information on encryption life cycle. 
5. Best practices for encryption in MongoDB. 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
sounds like a cool topic - approved. @HARITJOSHI1
