### ISSUE TITLE
How to get started with file systems in Node.js

### ISSUE THREAD

**Issue by RisoriTofa** [section-engineering-education/engineering-education#1941]
### Proposed title of the article
How to get started with file systems in Node.js

### Introduction paragraph (2-3 paragraphs):
File systems allow one to read, write, create, update, delete, rename and organize data on physical storage media. In Node.js, one can be able to do all these and many more through the use of the file system module (fs). This enables one to manipulate data automatically during code execution.
This tutorial aims to take you through Node.js file system module methods and show you practically how to implement some of the methods in your code.

### Key takeaways: 
At the end of this tutorial, you will be able to:
- Understand the file system module in Node.js
- Know some of the methods in the file system module and their applications
- Apply the methods in a code

### References: 
[Node.js basics](https://www.youtube.com/watch?v=OIBIXYLJjsI&list=PL4cUxeGkcC9jsz4LDYc6kv3ymONOKxwBU&index=2)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@RisoriTofa  

Just want to ensure there is not overlap with this already [published article here](https://www.section.io/engineering-education/node-file-handling/)

**Comment by RisoriTofa** [comment]
Yap, you are right man!
