### ISSUE TITLE
Integrating B2C M-pesa API using Node.js

### ISSUE THREAD

**Issue by Roba-W** [section-engineering-education/engineering-education#1950]
### Introduction paragraph (2-3 paragraphs):
M-pesa is a mobile banking service operating in various countries in Africa.  As of March 2020, M-pesa had recorded 41.5 billion transactions. The B2C API enables software developers to implement the functionality of merchants sending payments to customers in their applications. In this article, we will integrate the B2C API on a Node.js restful API.

### Key takeaways: 
- Handling requests to external resources on a Node.js application.
- Exposing a local server to be accessed by an external server.
- Using swagger to interact with a restful API.

### References: 
- https://developer.safaricom.co.ke/docs

**Comment by hectorkambow** [comment]
Sounds like a great topic approved @Roba-W
