### ISSUE TITLE
Introduction to C++ type conversion

### ISSUE THREAD

**Issue by Dawe-7** [section-engineering-education/engineering-education#1952]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Introduction to C++ type conversion

### Introduction paragraph (2-3 paragraphs):
Conversion from one type to another is referred to as `type conversion`. Type conversion's ultimate aim is to make variables of one data type work with variables of another data type to perform an operation. This is done to take advantage of some of the aspects of type hierarchies and type representations. So, when will a type conversion be beneficial?. Type conversion can be used to force the correct type of mathematical computation to be performed. 
For example, to find the sum of two variables, one of `int` type and the other of `float` type. So, to find the sum, you must typecast `int` variable to`float`. This article will introduce the reader to type conversion In c++, the two types of type conversion  and follow it with a detailed practical demonstration.

### Key takeaways: 
By the end of this tutorial, the reader will understand:
1. Type conversion in C++
2. Implicit type conversion
3. Explicit type conversion
4. Conversion using cast operators
5. Conversion using the assignment operator

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @Dawe-7
