### ISSUE TITLE
Useful Browser Extensions for Web Developers

### ISSUE THREAD

**Issue by Cslamonde** [section-engineering-education/engineering-education#1958]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an article to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
Useful Browser Extensions for Web Developers

### Introduction paragraph (2-3 paragraphs):
Have you ever come across a beautiful/good website and you wondered which technology/framework/tool that particular website was built on? Or maybe how a certain browser extension works? Well, in this article, you will be able to know some good stuff. Let me begin by defining a browser extension and explaining how it works.

### Key takeaways: 
1. Understand how plug-ins work.
2. Know a few varieties of browser extensions.
3. Add various plug-ins essential for web developers.
4. Few tips to adhere to while using plug-ins.

### References: 
https://www.forbes.com/sites/adrianbridgwater/2019/04/16/how-browser-extensions-work/?sh=52b67aa7674c

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - approved @Cslamonde

**Comment by Cslamonde** [comment]
Thank you

**Comment by hectorkambow** [comment]
@Cslamonde just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
