### ISSUE TITLE
Integrating Paypal checkout into a Nodejs application

### ISSUE THREAD

**Issue by okeloviolet** [section-engineering-education/engineering-education#1962]
### Integrating Paypal checkout into a Nodejs application
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article's higher ranking.*

### Introduction paragraph (2-3 paragraphs):
PayPal Holdings, Inc. is an American company operating an online payments system in most countries that support online money transfers and serves as an electronic alternative to traditional paper methods like checks and money orders. Paypal checkout allows merchants to accept payments through PayPal, MasterCard, and visa within their websites. In the tutorial, I will explain the stepwise process of integrating Paypal checkout into a Nodejs website.

### Key takeaways: 
1. Handling requests to external resources on a Nodejs application.
2. Exposing a local server to be accessed by an external server.
3. Integrating PayPal checkout into Nodejs application.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - approved 👍  @okeloviolet
