### ISSUE TITLE
How to create deep neural network in MATLAB

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#1963]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
Neural network form the base of deep learning and a subfield of machine learning where algorithm are inspired by the structure of human brain. It takes in data train themselves to recognize the pattern in this data and then predict the output for a new set of similar data.
MATLAB provides a deep learning toolbox for implementing the deep neural network. MATLAB includes the digit dataset so you don't need to download it from an external source.
In this article we will look at how to prepare your digit dataset,the structure of convolution neural network. We will also look at the Matlab code for training and validation and code for discrete testing.

### Key takeaways: 
- How to create deep neural network such as convolution neural network (CNN).
- How to train the CNN on your own set of images.
- How to recognize objects

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Seems like a helpful topic - approved. 
Let be sure to reference these already published articles if it makes sense to do so. 👍  @jumapaul  

https://www.section.io/engineering-education/search/?q=MATLAB
