### ISSUE TITLE
How to publish your custom Node.js module

### ISSUE THREAD

**Issue by RisoriTofa** [section-engineering-education/engineering-education#1966]
### Proposed title of the article

How to publish your custom Node.js module

### Introduction paragraph (2-3 paragraphs):

Although there are so many Node.js modules that one can access and use in their code, sometimes one can't find the most suitable code based on their application and problem being solved. This brings the necessity for one to create their custom module which they can publish and reuse later.
In this tutorial, we are going to learn how to create our custom package, publish it and use it.

### Key takeaways:

At the end of this tutorial, you will be able to:

- Understand modules in Node.js
- Know some of the common packages in Node.js
- Create your package
- Share the package created
- Publish, access, and test the package

### References: 

- [NPM docs](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages)

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic @RisoriTofa  approved 👍

**Comment by kimkimani** [comment]
@hectorkambow , perhaps you did forget to point out the simmilarty of this topic to this already published content 
https://www.section.io/engineering-education/npm-packages/

**Comment by hectorkambow** [comment]
🎉  great catch @kimkimani  

@RisoriTofa  - please go over the already published articles to make sure we are contributing unique topics. 🚀
