### ISSUE TITLE
Quasar Vuejs Google authentication with firebase

### ISSUE THREAD

**Issue by EspiraMarvin** [section-engineering-education/engineering-education#1967]
### Proposed title of article
Quasar Vuejs framework Google authentication with firebase.

### Introduction paragraph:
When developing an app, providing specific authorization flows for the application should be easy with guaranteed security. OAuth 2.0 provides such a standard without having to deal with users' security issues such as passwords. 
Firebase implements OAuth 2.0 with google auth provider in the simplest way possible.

### Key takeaways: 
By the end of the article, the learner should be able to
-	Set up quasar vuejs app
-	Create sign in, and forgot password components
-	Add firebase authentication to the app
-	Access user information
-	Logout user
-	Implement password resets

### References: 
 N/A

**Comment by hectorkambow** [comment]
Seems like a helpful topic - please be sure to double check that we have no overlapping or existing articles - 

approved @EspiraMarvin
