### ISSUE TITLE
How to use Modular patterns in Node.js

### ISSUE THREAD

**Issue by Wachira48** [section-engineering-education/engineering-education#1968]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

How to use Modular patterns in NodeJS

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

When building applications, you don’t write all your code in one single file. First, this would very hard to manage. This been a large application, it would be very hard for a developer to come back to this code and refactor or extend the application functionalities. However, you can break down this complex application into small reusable parts.

Typically, what developers do is that an application is divided into several logical files. Each file has a different bit of code with certain functionality. This way, it will be easier to maintain your codebase because each file has less code to accomplish a specific task. It is easier to debug right and share the code do another developer, this easier maintenance.

This concept is common in most programming languages. The concept is called modularity (Modular patterns). In this case, every single file is a module. Let’s say, for example, you are creating a calculator application. In this case, you can have a file that handles addition. Another file that handles substation functionality. Each file has a specific arithmetical task.

Modular patterns can be used to export these files to the main file. This pattern can be implemented in several ways, but that depends on the modular programming paradigm of the host programming language.

In Node.js, the concept of Modular patterns has additional features that go beyond the regular module (file) pattern. The Node.js modular functionality can be used to import own external files, core Node.js modules, and NPM modules. This tutorial will focus on creating modules, exporting and importing them to different files using Node.js.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

How to create a module
Export functions and objects
Exports vs. module.exports 
A use-case of Node.js NPM module (library)

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
good topic @Wachira48 - approved. 

One important note: Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)

**Comment by hectorkambow** [comment]
merged
