### ISSUE TITLE
Speakeasy Two Factor Authentication in Nodejs

### ISSUE THREAD

**Issue by mia-roberts** [section-engineering-education/engineering-education#1971]
### Proposed title of article
Speakeasy Two Factor Authentication in Nodejs

### Introduction paragraph (2-3 paragraphs):
On top of your very basic email and password authentication, two-factor authentication adds a layer of security to your application. It ensures that besides your email and passwords, a one-time PIN (OTP) is generated and given a period of expiry beyond which it becomes outdated. The user, however, has the option of requesting a new OTP for login.

According to [npmjs.com](https://www.npmjs.com/package/speakeasy), Speakeasy is a one-time passcode generator that besides being widely used for two-factor authentication, has immense support for Google Authenticator and other two-factor devices. Speakeasy user hashing algorithms like SH256 and SHA512 besides helpers like secret-key generators. One advantage of Speakeasy is that it ensures a robust implementation of OTP generator as standardized by the Initiative for Open Authentication (OATH).

In this article, we will register users, store them in a database with a secret code under their credentials, and get a one-time code  which we authenticate the user against a secret code we have on a database  using Speakeasy library; by submitting the code to a separate authentication route.  This application will be implemented in Node.js.
 

### Key takeaways: 
1. Building a Nodejs Server
2.  Setting up Speakeasy in Nodejs
3. Using Node-JSON database
4. Understanding benefits of two factor authentication

### References: 
https://www.npmjs.com/package/speakeasy
https://github.com/speakeasyjs/speakeasy

**Comment by hectorkambow** [comment]
Seems like a good topic @mia-roberts  - approved. 

One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)

**Comment by mia-roberts** [comment]
Alright, understood @hectorkambow
