### ISSUE TITLE
How To Use the Node.js REPL

### ISSUE THREAD

**Issue by odiwuoramos** [section-engineering-education/engineering-education#1972]
### Proposed title of article
How To Use the Node.js REPL

### Introduction paragraph (2-3 paragraphs):
The Node.js Read-Eval-Print-Loop (REPL) is an interactive shell that processes Node.js expressions. The shell reads JavaScript code the user enters, evaluates the result of interpreting the line of code, prints the result to the user, and loops until the user signals to quit.

The REPL is bundled with with every Node.js installation and allows you to quickly test and explore JavaScript code within the Node environment without having to store it in a file.

### Key takeaways: 
-  Executing Code in the Node.js REPL
-  Mastering REPL Shortcuts
- Using REPL Commands

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @odiwuoramos  

If you havent already please be sure to check that this does not overlap too much with previously published Node.js EngEd articles. 

And/or to see what articles you can refer to as resources 👍

**Comment by hectorkambow** [comment]
https://www.section.io/engineering-education/nodejs-repl-tutorial/ 

merged
