### ISSUE TITLE
Getting Started with Node.js

### ISSUE THREAD

**Issue by Terripha** [section-engineering-education/engineering-education#1974]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting Started with Node.js

### Introduction paragraph (2-3 paragraphs):
Node.js is an open-source, cross-stage, JavaScript runtime environment, based on Chrome's V8 JavaScript engine. The purpose of this engine is to compile JavaScript functions into machine code. It is well-known for its high speed and constantly advancing performance.

In this article, We will understand better what node.js is, how to install it in our machines, as well as write our first simple web server application. We shall look at each line of our web server application.

### Key takeaways: 
At the end of this article, the reader will be able to:
1. Install and set up node.js
2. Write a simple web server application using Node.js
3. Understand the basic syntax of a Node.js application
4. Understand each line of code that is, HTTP Server, function and parameters req and res, Status code, Content-Type, Finishing the request, Listening to the port

### References: 
N/A

**Comment by hectorkambow** [comment]
🤔  @Terripha  

Just want to make sure this topic doesnt overlap with this. 
https://www.section.io/engineering-education/nodejs-os-module/

**Comment by Terripha** [comment]
@hectorkambow  My article will focus more on understanding a simple web server application like 'hello world'. We will understand each line of code that is, HTTP Server, function and parameters req and res, Status code, Content-Type, Finishing the request, Listening to the port
