### ISSUE TITLE
Getting Started with Vue.js 3

### ISSUE THREAD

**Issue by KutswaLemis** [section-engineering-education/engineering-education#1976]
### Proposed title of article
Getting started with Vue.js Version 3

### Introduction paragraph:
Vuejs is a versatile font-end JAVASCRIPT framework. It’s highly adoptable with more than 181k GITHUB stars. With the stable release of version 3 on 1st March, it has come with some changes and improvements including key features such as composition API, Teleporting to name a few. Given the large number of developers using it on a daily basis. It is best developers get their hands dirty with Vue  version 3

### Key takeaways: 
After reading this article the learner is expected to:
1.  Understand Vue 3 basics
2. Create a simple app with Vue 3
3.  Understand and be able to use Composition API
4. Understand the differences between Composition API and Options API

### References: 
N/A

**Comment by hectorkambow** [comment]
sounds like a good topic - approved @KutswaLemis 

if you haven't already please go through our published articles (via the search bar) to make sure this does not overlap with past works.

**Comment by hectorkambow** [comment]
@KutswaLemis just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
