### ISSUE TITLE
Clone Twitter Home page with Vue and Tailwind

### ISSUE THREAD

**Issue by Worawat101** [section-engineering-education/engineering-education#1983]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Clone Twitter Home page with Vue and Tailwind

### Introduction paragraph (2-3 paragraphs):
The tutorial will demonstrate the implementation of Twitter Home page UI using Vue with Tailwind CSS. The content will impart thorough knowledge on the implementation of each section of the Twitter Home page. The most essential thing is that the total implementation of UI in Vue Version 3. The detailed stepwise integration of how to integrate Tailwind CSS into the Vue project will also be shown. We will also be implementing a tweeting feature.

### Key takeaways: 
- Basics of Vue Version 3
- Basics of Tailwind CSS
- Integration of Tailwind CSS in Vue project
- Using Tailwind CSS to implement Twitter Home page UI

### References: 
https://v3.vuejs.org/
https://tailwindcss.com
https://tailwindcss.com/docs/guides/vue-3-vite

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
good topic - approved @Worawat101

**Comment by hectorkambow** [comment]
merged
