### ISSUE TITLE
Node.js Callback Concept

### ISSUE THREAD

**Issue by M0nicah** [section-engineering-education/engineering-education#1985]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Node.js Callback Concept

### Introduction paragraph (2-3 paragraphs):
A callback is the equivalent of an asynchronous function. Asynchronous functions are also known as non-blocking functions since they do not block the thread on which they are running on. Node.js heavily relies on asynchronous functions. This is because servers often receive many requests at a time; if the server was to be synchronous, requests would be processed one at a time which would lead to a bad user experience since the user might have to wait for a long time.

Since asynchronous functions do not block the thread, it might be difficult to track the function or do another task immediately the function is done executing. This is where callbacks come in, callback functions are functions that are passed in asynchronous functions and run immediately  after the function. This article goes through the basics of asynchronous functions in node.js and how to use callbacks to perform tasks asynchronously.

### Key takeaways: 
1. Understand what asynchronous functions are.
2. Understand how to use callbacks in node.js.
3. Understand the importance of callbacks.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - approved @M0nicah
