### ISSUE TITLE
Getting Started With HTTP/2 And Server Push in Node.js 

### ISSUE THREAD

**Issue by Bradley8555** [section-engineering-education/engineering-education#1989]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting Started With HTTP/2 And Server Push in Node.js 

### Introduction paragraph (2-3 paragraphs):
HTTP/2 is the new standard of the web. It has many great features which will make the web faster and simplify the development. For example, no need to concatenate files thanks to multiplexing, or a server push which can send files before a browser knows it need them.

In this tutorial, we willll focus on server push and implement it in Node.js using Express and the spdy library.

### Key takeaways: 
1. Getting Started with http/2 in Node.js

2. Configuring Express and spdy in Node.js

3. Implementing http/2 and Server push in Nodejs

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
good topic @Bradley8555  - approved. 

One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)

Also if you havent already please be sure to check that this does not overlap too much with previously published Node.js EngEd articles.

And/or to see what articles you can refer to as resources 👍
