### ISSUE TITLE
A quick guide to Node.js - Event Emitter

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#1992]
### Proposed title of the article
A quick guide to Node.js - Event Emitter

### Introduction paragraph (2-3 paragraphs):
The core of NodeJS is event-driven programming. In NodeJS, we achieve event-driven programming with the event-emitter class.  
In this article, we’ll discuss everything about the event-emitter class. The following are the topics that I’ll be covering in this article.
What is an event emitter?
Creating an event emitter
Attaching event listeners and publishing events to an event emitter
Maintaining a single event-emitter instance applicationwide
Is it synchronous or asynchronous?
Order of execution of event emitters
How and where NodeJS internally uses event emitters
Some useful member functions of the event-emitter class

EventEmitter is a class that helps us create a publisher-subscriber pattern in NodeJS.
With an event emitter, we can simply raise a new event from a different part of an application, and a listener will listen to the raised event and have some action performed for the event.

### Key takeaways: 
- Creating an Event Emitter:
To create an event emitter, we need to create an instance of the event emitter instance from the events module in NodeJS.
- Publishing Events and Listening to Them
The EventEmitter class comes with a lot of member functions. We’ll be using these member functions to publish events and listen to them.
- Maintaining a Single Event-Emitter Instance Applicationwide
A node application is generally 100s of files. This gets challenging to maintain by a single copy of the EventEmitter instance throughout the application.

**Comment by hectorkambow** [comment]
seems like a helpful topic @jumamiller  - approved 

Please note we are using Node.js instead of NodeJS in the article for consistency 👍
