### ISSUE TITLE
Building an Object Detection Application with TensorFlow.js and React.js

### ISSUE THREAD

**Issue by wmkinyan** [section-engineering-education/engineering-education#1995]
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Building an Object Detection Application with TensorFlow.js and React.js

### Introduction paragraph (2-3 paragraphs):

In this article, we will learn on how to build a real-time object detection application using TensorFlow.js and React.js.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this article, the reader should be able to:

1. Access the React.JS and Tensorflow.JS Computer Vision Template
2. Install Tensorflow.JS and setup the pre-built models
3. Build a React.JS app that accesses the webcam
4. Make detection from the webcam in real time

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - @wmkinyan  approved. 

If you havent already please be sure to check that this does not overlap too much with previously published EngEd articles.

And/or to see what articles you can refer to as resources 👍
