### ISSUE TITLE
Introduction to Node.js 15

### ISSUE THREAD

**Issue by valerio140** [section-engineering-education/engineering-education#1999]
### Proposed title of article
Introduction to Node.js 15

### Introduction paragraph (2-3 paragraphs):
Node.js is a popular framework for executing JavaScript code on the server. This functionality allows developers to build powerful and scalable applications. The release of Node.js 15 takes things to a new level . 

Production deployments are generally recommended to use LTS release line.
Node.js 15 has distinctive features such as abort controller, N-API version 7 and many others. One of the major changes in  Node.js 15 is that peer dependencies are installed by default.

### Key takeaways: 
-Understand what node.js 15 entails 
-Understand the packages required in node.js 15
-understand the key advantages of node.js 15 over other node.js versions
### References:
 N|A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - @valerio140  approved 👍  

If you haven't already, please be sure to check that this does not overlap too much with previously published Node.js EngEd articles.

And/or to see what articles you can refer to as resources 👍
