### ISSUE TITLE
The Best Caching Strategy for AdonisJS RESTFUL API

### ISSUE THREAD

**Issue by Kaperskyguru** [section-engineering-education/engineering-education#2001]
### Proposed title of article
A Caching Strategy for AdonisJS RESTFUL API

### Introduction paragraph (2-3 paragraphs):
I will be showing you the best practice in handling Caching in Adonisjs, discussing in details the best strategies involved in handling a scalable Caching System in your RESTFUL API. We will build a real-world app to demonstrate how to boost performance with a good Caching Strategy.

### Key takeaways: 
Students will learn how to build a high-performance app with Adonisjs
Students will learn how to implement a Caching System in AdonisJS Restful API
Students will learn how to choose the right Caching Strategy depending on the project.
Students will learn about the concept of Caching and how to scale large App with it.
Students will learn best practices in building performance-oriented Web apps with AdonisJS.

### References: 
https://dev.to/vigzmv/a-simple-caching-strategy-for-node-rest-apis-part-1-72a
https://blog.appsignal.com/2021/03/10/powerful-caching-with-redis-for-nodejs-applications.html
https://hackernoon.com/how-to-setup-caching-in-nodejs-using-redis-tq143usy

**Comment by hectorkambow** [comment]
🤔  

Just want to make sure this article will not overlap with this existing one [here](https://www.section.io/engineering-education/build-a-restful-api-with-adonisjs/)

@Kaperskyguru

**Comment by Kaperskyguru** [comment]
No @hectorkambow this is an entirely different topic.

It's a topic on Caching Strategy.

It can be demonstrated with any Backend framework or language, I just decided to implement it with Adonisjs.

**Comment by hectorkambow** [comment]
@Kaperskyguru  👍  fantastic just wanted to triple check - 

If the one above can be reference (if it is helpful) lets be sure to add it if needed. 

Approved
