### ISSUE TITLE
How to set up User Authentication from Scratch with Rails 6

### ISSUE THREAD

**Issue by Njunu-sk** [section-engineering-education/engineering-education#2002]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 
This article is meant for Ruby on Rails beginners I will implement a full authentication system, this will support sign up, sign in, sign out, account management, password reset and basic user administration.
We will explore the Model View Architecture, layouts, migrations and cookies in Rails.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.
Be able to understand MVC architecture.
Able to build a complete authentication system in Rails.
Basic knowledge on security features and cookie storage in rails.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
https://guides.rubyonrails.org/
https://medium.com/@wintermeyer/authentication-from-scratch-with-rails-5-2
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
good topic @Njunu-sk - approved. 

One important note: Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)

**Comment by hectorkambow** [comment]
@Njunu-sk just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
