### ISSUE TITLE
How to integrate Google Maps into your Android Application

### ISSUE THREAD

**Issue by bluemutheu** [section-engineering-education/engineering-education#2009]
### Proposed title of article
How to integrate Google Maps into your Android Application

### Introduction paragraph (2-3 paragraphs):
Google maps have become a necessity for application development. Most common apps like Airbnb, Uber and so many delivery apps use Google Maps. It is therefore just and reasonable to learn how to implement Google maps on your application from scratch. In this article, we will not use the already provided google maps activity on android studio but create our own in an empty activity. This will help us adjust the application according to our needs.

### Key takeaways: 
1. How to access fine location permission
2. How to show Google Maps using Support Map Fragment
3. How to show a User's current location.

### References: 
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a good topic - approved @bluemutheu

**Comment by hectorkambow** [comment]
@bluemutheu just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.

**Comment by bluemutheu** [comment]
@hectorkambow Please do not close it,, I am still working on it, will submit by end of the week
