### ISSUE TITLE
Applet programming in java

### ISSUE THREAD

**Issue by Paul22691** [section-engineering-education/engineering-education#2011]
### Proposed title of article
 Understanding Applet programming in java

### Introduction paragraph (2-3 paragraphs):
An applet is a small java program that is used in internet programming. 

Applets are run mainly using applet viewer or web browsers that mainly supports java. An applet just like any other stand-alone application it performs many functions of which includes performing arithmetic operations, play sounds, accept inputs from the user and also display graphics.

Applets cannot be run independently like stand-alone applications they therefore  use HTML tags to enable them run in a web browser

### Key takeaways: 
By the end of this tutorial the learner should understand:

1. Definition of an applet and write a 'hello world' program using applet.
2. The lifecycle of an applet.
3. Difference between an applet and java stand-alone application
4. How to invoke an applet.
5. How to convert applications to applets.

### References: 
N/A

**Comment by hectorkambow** [comment]
sounds like a good topic - approved @Paul22691
