### ISSUE TITLE
Why Node.js is great for Backend Development? 

### ISSUE THREAD

**Issue by ephraa** [section-engineering-education/engineering-education#2012]
### Proposed title of article
Why Node.js is great for Backend Development?

### Introduction:
Node.js backend development is not a new concept and has been used in the implementation of many digital products online. It comes with a lot of advantages, which make it suitable for the development of enterprise and B2C applications.

Node.js is popular in the software engineering community, but what makes it this attractive from both technology and business points? In this article, we will answer this question.

### Key takeaways: 
At the end of this article, the reader will understand:
- What is Node.js is used for? and Node.js frameworks.
- The competitors of Node.js in backend development.
- Reasons why Node.js should be considered for backend development.

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a nice topic - but we want to make sure it does not overlap too much with these existing articles:

https://www.section.io/engineering-education/nodejs-frontend-backend/

https://www.section.io/engineering-education/nodejs-os-module/

https://www.section.io/engineering-education/why-nodejs-good-for-online-store/

Can you elaborate a bit more how your article will differ?

**Comment by ephnjor2021** [comment]
@hectorkambow 
The articles above have concentrated on comparisons of Node.js as frontend or backend, the advantages of Node.js for Online stores, and Node.js Os module.  Unlike them, I will concentrate more on the technical aspects of Node.js, its frameworks and their use, the major reasons why developers should go with Node.js when developing backend applications, and the major comparisons of Node.js with other backend languages and frameworks.

**Comment by ephraa** [comment]
@hectorkambow
The articles above have concentrated on comparisons of Node.js as frontend or backend, the advantages of Node.js for Online stores, and Node.js Os module. Unlike them, I will concentrate more on the technical aspects of Node.js, its frameworks and their use, the major reasons why developers should go with Node.js when developing backend applications, and the major comparisons of Node.js with other backend languages and frameworks.

**Comment by hectorkambow** [comment]
👍 sounds great - if helpful lets be sure to reference any past related articles for the audience @ephraa  

approved 🚀
