### ISSUE TITLE
How to generate URL and Text QR codes using Node

### ISSUE THREAD

**Issue by franciskaguongo** [section-engineering-education/engineering-education#2013]
### Proposed title of the article

How to generate URL and Text QR codes using Node

### Introduction paragraph (2-3 paragraphs):

Have you ever desired to build a code that generates QR codes of text or URL inputs using Node.js? You are in the right place. In this tutorial, you are going to learn how to create a QR code generator for text or URL input using Node.js.
Before we begin, let us learn briefly about QR codes and how they work.

### Key takeaways:

At the end of this tutorial, you will have understood:

- What QR codes are
- Purpose of QR codes
- How to create a QR code generator
- How to run it on a simple webpage
- What to do with the QR codes generated

### Pre-requisites:

Some of the minimum requirements for this course are:

- Basic understanding of HTML, CSS, and web development
- Basic understanding of Node.js
- An IDE installed on your machine, in our case we shall use Visual Studio Code
- A stable internet connection

### References:

- [Minimum QR Code size](https://www.sproutqr.com/blog/qr-code-minimum-size#:~:text=There%20is%20no%20standardized%20QR,wide%20by%202%20centimeters%20long.)
- [QR code structure](https://www.keyence.com/ss/products/auto_id/barcode_lecture/basic_2d/qr/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
sounds like a cool topic - approved @franciskaguongo

**Comment by hectorkambow** [comment]
merged
