### ISSUE TITLE
HOW TO BUILD A RANDOM PASSWORD GENERATOR APP WITH HTML CSS AND JAVASCRIPT 

### ISSUE THREAD

**Issue by destiny251** [section-engineering-education/engineering-education#2014]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
HOW TO BUILD A RANDOM PASSWORD GENERATOR APP WITH HTML CSS AND JAVASCRIPT 

### Introduction paragraph (2-3 paragraphs):
In this article, readers will learn how to build a random password generator application with HTML, CSS, and JavaScript.
Before we dive in, you will need to know what a "password generator application" is all about.  This is an application that can automatically generate passwords randomly for you. These generated passwords consist of alphabets, numbers, and symbols. The main reason for this application is that it helps the user create a very strong password that cannot be easily guessed or bruteforced. 

### Key takeaways: 
* The reader will learn how to successfully build a password generator application with pure HTML CSS AND JAVASCRIPT.
* The reader will learn about the createElement method, the execCommand method, and how to floor a decimal value in Javascript.
* Lastly the reader will understand what is an ASCII Character table and why we need it for the application. 

### References: 
Nil.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - please be sure to check (if you haven't already) that this topic does not conflict with any past publshed works. 
👍  

Approved @destiny251

**Comment by hectorkambow** [comment]
@destiny251 just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
