### ISSUE TITLE
Why you should use the Wakanda JavaScript Framework

### ISSUE THREAD

**Issue by annmichubu** [section-engineering-education/engineering-education#2016]
### Proposed title of the article
- Why you should use Wakanda JavaScript Framework

### Introduction paragraph (2-3 paragraphs):
Wakanda is a JavaScript platform used to run and develop mobile apps and the web. Wakanda Framework consists of a stack of tools and technologies. They include the Wakanda client connector which has a data provider to facilitate communication with front-end frameworks and the server.

Wakanda server lowers the cost of configuration by giving pre-bundled components.  These components include an HTTP server that generates and expose Wakanda REST API. The server also provides a security layer management and database abstraction layer. Wakanda Studio is used in designing the data model and building functionalities for mobile development. 

### Key takeaways
- What is Wakanda JavaScript Framework
- Key features of Wakanda JavaScript Framework 
- Advantages  of Wakanda JavaScript Framework

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a cool topic - approved 👍  @annmichubu
