### ISSUE TITLE
Building a Rest API using Node.js, Postgresql and Prisma

### ISSUE THREAD

**Issue by katungi** [section-engineering-education/engineering-education#2018]
### Proposed title of article
Building a Rest API using Node.js, Postgresql and Prisma

### Introduction paragraph (2-3 paragraphs):
JavaScript is amazing for building backend Rest APIs. One small hurdle most Node.js developers face is when choosing or planning a straightforward database workflow. The easier route and the most common route that is tested and proven is the NoSql route. Node.js and JS in general has amazing compatibility with databases like MongoDB and Firebase. 

Working with SQL databases like postgresql is an uncommon route for Node.js developers to take. This can be attributed to the myth that using ORM (Object Relational Models), is hard. There are many options for ORMs like sequelize, TypeORM, bookshelf, Prisma and many more. Prisma is an open source easy to use ORM that comes with a type safe system and easy to work with tools to help developers interact with there SQL database easily. 

In this tutorial, we will learn how to setup our Node.js and prisma workflow for use with Postgresql. We will do so while building a simple blog Rest API.

### Key takeaways: 
The reader will learn how to:
 - Setup Node.js with Postgres and Prisma
 - How to model data with Prisma
 - How to write and read from Postgres database
### References: 
https://www.prisma.io/docs/getting-started/quickstart-typescript

**Comment by hectorkambow** [comment]
seems like a cool topic - please be sure to check (if you haven't already) that this topic does not conflict with any past published works.
👍

Approved @katungi

**Comment by hectorkambow** [comment]
@katungi just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?

**Comment by katungi** [comment]
Hey @hectorkambow , I am still working on it, and will push the PR asap
