### ISSUE TITLE
Session Management in Node.js using Express.js and Express-session

### ISSUE THREAD

**Issue by Catemacharia** [section-engineering-education/engineering-education#2019]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

### Introduction paragraph (2-3 paragraphs):
A session is an authentication programming concept. Authentication is the process of proving that a systematic procedure is authentic or valid. A session is used to store information about a particular user or client.

For example, a login system. The Authentication would be checking to see if a user exists and if their login credentials are valid. A website is based on HTTP protocol. HTTP is a stateless protocol that means that there's a browser and a server. At the end of every request and response cycle, the client and the server forget about each other. This is where the session comes in.

A session will contain some unique data of that client to allow the backend (server) to keep track of the user's state.

### Key takeaways: 
How sessions works
The difference between session and cookie
Prerequisites
Setting up the required environments and libraries
Express-session Options and how to use it
Setting up the session middleware

### References: 

https://www.npmjs.com/package/express-session
https://www.npmjs.com/package/express
### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - please be sure to check (if you haven't already) that this topic does not conflict with any past published works.
👍

https://www.section.io/engineering-education/search/?q=node.js

Approved @Catemacharia

**Comment by hectorkambow** [comment]
https://www.section.io/engineering-education/session-management-in-nodejs-using-expressjs-and-express-session/
