### ISSUE TITLE
How to generate Fake Data in Node using Faker.js

### ISSUE THREAD

**Issue by justusmbuvi** [section-engineering-education/engineering-education#2025]
### Proposed title of the article:

How to generate Fake Data in Node using Faker.js

### Introduction paragraph (2-3 paragraphs):

During system development and testing, the use of Fake data can be very useful. This is because it prevents one from using one's real identity especially in important data such as identification number, full names, and date of birth among others. Generation of this fake data manually takes much time hence slowing down the testing period since it is hard to come up with a lot of new data.

In this tutorial, we are going to learn how to generate fake data in Node.js using the Faker module and output it in a webpage as a table. 

### Key takeaways: 

At the end of this tutorial, you will be able to:

- Know the main components of Faker.js
- Create a simple webpage structure
- Link the Faker module to the webpage
- Generate the fake data
- Store the fake data in a table

### Pre-requisites:

The basic requirements for this course include:
- Web development basics
- Node.js basics
- A basic IDE installed on the machine
- A stable internet connection

### References: 

- [Faker.js documentation](https://www.npmjs.com/package/faker)
- [Node.js modules documentation](https://nodejs.org/dist/latest-v15.x/docs/api/packages.html#packages_modules_packages)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - approved @justusmbuvi

**Comment by hectorkambow** [comment]
merged
