### ISSUE TITLE
Integrating Stripe checkout in Flutter

### ISSUE THREAD

**Issue by jerimkaura** [section-engineering-education/engineering-education#2026]
### Proposed title of article
Integrating Stripe checkout in Flutter

### Introduction paragraph (2-3 paragraphs):
The most significant trend in e-commerce applications is the increased integration of mobile wallets through which customers could pay for the products and services they purchase. Stripe it's an online payment platform that allows merchants to receive payment using MasterCard and Visa via their website for the products and services they sell.  

Stripe was launched in 2011 with headquarters in San Francisco and Dublin, and today, Stripe has millions of users. Since the real value of a checkout system is in the design and security of the Checkout page, Stripe provides a basic credit card form that makes integration of the Checkout system easy. It provides programmers with an intuitive UI for the checkout page. This tutorial will give a stepwise explanation of the process of integrating stripe checkout in a flutter application.

### Key takeaways: 
1. Creating a checkout UI using Stripe
2. Creating checkout sessions with Stripe API
3. Simple server to make HTTP requests to the stripe API
4. Making payments with the Stripe checkout.

### References: 
https://stripe.com/docs/payments

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
cool topic - approved @jerimkaura
