### ISSUE TITLE
Building a Calculator: A javaScript project for beginners

### ISSUE THREAD

**Issue by Nomzy-kush** [section-engineering-education/engineering-education#2027]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Building a Calculator: A javaScript project for beginners

### Introduction paragraph (2-3 paragraphs)
Building a web calculator is a great project to put your hands on if you just learnt javascript. In this article, you are going to be taken through the various HTML and CSS elements along with vanilla javascript and modern ES6 practices used in building a functional and responsive calculator.

### Key takeaways: 
1. Readers will be able to build a modern javascript calculator that worked in a browser.
2. Readers will be able to input all the calculator operations i.e addition, subtraction, multiplication and division.
3. Readers will understand vanilla javascript more thereby furthering their knowledge on the topic. 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
cool topic - approved @Nomzy-kush

**Comment by hectorkambow** [comment]
merged https://github.com/section-engineering-education/engineering-education/pull/2418
