### ISSUE TITLE
A Vanilla Node.js REST API Without Frameworks such as Express.js

### ISSUE THREAD

**Issue by Rose-stack** [section-engineering-education/engineering-education#2029]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Node.js is a popular very JavaScript framework. Node.js has been used to create applications of all levels. It shines most when used to build back-end services and APIs.

In most cases, when building APIs with Node.js, developers use open-source [Node.js libraries and frameworks](/engineering-education/most-useful-nodejs-packages/) such as [Express.js](/engineering-education/express/). These libraries are readily available in the NPM registry.

Whenever you use such packages, there is a lot of abstraction as you don't utilize the core functionalities of Node.js. The low-level logic Node.js of your application is hidden from you as these packages process and execute raw Node.js behind the scenes.

One key thing to note is that these packages make [Node.js a popular technology](/engineering-education/why-node-js-is-popular/). On the other side, you can opt to use core Node.js to develop your applications. This way, you make use of the [vanilla Node.js](/engineering-education/pure-node-js-no-frameworks-or-packages/) functionalities. This blog will teach you how to use vanilla Node.js with no frameworks to build simple APIs.

### Goal
In this guide, we'll build a simple REST API skeleton using functionalities core to Node.js itself. We're just using the barebones of [vanilla Node.js](https://nodejs.dev/learn) with the [HTTP module](https://nodejs.org/api/http.html#http_http) for creating and managing a server. This means we won't use NPM. Therefore no NPM associated dependencies, no `package.json`,  no `package-lock.json`, and no `node_module` folder. The reason is to demonstrate and give you an overview of how raw Node.js works/can be used without frameworks.

> Note: When working on any actual project, it is best to use Node.js libraries and packages. This way, you'll take full advantage of the readily available code to make your development workflow easier and faster.

### Key takeaways: 
Setting up a simple HTTP server
Setting up the REST API
Explore the API using Postman

### References: 
https://nodejs.dev/
https://nodejs.org/api/http.html#http_http

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
cool topic -  @Rose-stack 
 
But I do not see any info or sentences explaining the Title. 🤔

**Comment by Rose-stack** [comment]
> cool topic - @Rose-stack
> 
> But I do not see any info or sentences explaining the Title. 🤔

Yes @hectorkambow , I have added a few paragraphs explaining the tittle

**Comment by Rose-stack** [comment]
I've also submitted the same via this PR #2243
