### ISSUE TITLE
WEBCAM and IPCAM interface with MATLAB

### ISSUE THREAD

**Issue by queenterbruce063** [section-engineering-education/engineering-education#2030]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
A WEBCAM is connected to pc and can be used to make videos available to other users. The connection is normally through the USB. IPCAM involves the combination of high-end web functionality, pc and network interface to one network-ready product
In this tutorial we will look at how to install the WEBCAM and IPCAM hardware package for MATLAB which is necessary to access the hardware. We will also look at how to access laptop's inbuilt WEBCAM and external USB webcam with Matlab code to take snapshots, preview and to record a video clip.
The android application to convert mobile phone's camera as an IPCAM and look at the MATLAB code that can be used to make the mobile phone's camera as an IPCAM 

### Key takeaways: 
- how to access inbuilt WEBCAM.
- how to make mobile phone's camera as an IPCAM
- how to access live video stream using MATLAB

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
cool topic - approved @queenterbruce063
