### ISSUE TITLE
Integrating stripe checkout in a website application using Node.js

### ISSUE THREAD

**Issue by ghost** [section-engineering-education/engineering-education#2031]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Stripe is an Irish-American financial services and software as a service company dual-headquartered in San Francisco, California and Dublin, Ireland. The company primarily offers payment processing software and application programming interfaces for e-commerce websites and mobile applications. Stripe allows users to make payment easily within the website due to it's simplicity. In this tutorial i will explain step wise integration of stripe into a Node.js application

### Key takeaways: 
1. Handling requests to external resources on a Nodejs application.
2. Exposing a local server to be accessed by an external server.
3. Integrating Stripe checkout into Nodejs application.
### References: 
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a great topic - @Purity-Gwaro  

Just want to make sure its not overlapping too much with this upcoming article topic. 

https://github.com/section-engineering-education/engineering-education/issues/2026

**Comment by yitzackRabin** [comment]
Hi @hectorkambow  
The topic is mainly explaining step wise integration of stripe in simple way that a beginner can understand. I selected on Nodejs as it's my current study. Thanks

**Comment by PurityGwaro** [comment]
Hi @hectorkambow
The topic is mainly explaining step wise integration of stripe in simple way that a beginner can understand. I selected on Nodejs as it's my current study. Thanks

**Comment by PurityGwaro** [comment]
Hi @hectorkambow I would like to request you to help me merge my accounts into one for the section engineering or probably for the whole github if it's possible. I found out I had more than one account and was using both without knowing and it's confusing. Thank you.

**Comment by hectorkambow** [comment]
@PurityGwaro 👋  Hello - and my apologies for the delayed response. For a quicker reply please always reach out via slack, 

Regarding your GitHub question - I would advise simply using one and not the other to avoid confusion - unfortunately GitHub is a separate entity and we can not do anything to the accounts.

**Comment by hectorkambow** [comment]
just wanted to follow up on this topic as I'm clearing up the queue where possible? We can be re-opened when needed.
Of perhaps I missed the PR this is attached to? @PurityGwaro
