### ISSUE TITLE
An Introduction to Evolutionary Algorithms in Python

### ISSUE THREAD

**Issue by Tvashta** [section-engineering-education/engineering-education#2034]
### Proposed title of article
An Introduction to Evolutionary Algorithms in Python

### Introduction paragraph (2-3 paragraphs):
A computer program is built to follow rigid and explicit rules. Though this prescriptive approach has aided us well, it requires that a programmer must not only know the exact steps to solve the problem, but also know how to compute it in this lifetime.
If we swerve a bit from this strict method into the domain of heuristic algorithms, we might stumble across one of the most powerful ones, a population based optimization algorithm, the **Evolutionary algorithm**.

An evolutionary algorithm mimics one of nature's most fascinating process, natural selection, in the context of the problem given. Simply put, from an initial set of all possible solutions, only fitter members will survive and produce new generations.
Inspired by the biological model of evolution proposed by Darwin in 1859, the algorithm can be used to approximate solutions for problems where even the most optimized approach known is still not fast enough to meet real world constraints [ Ex: [NP-Complete](https://www.ics.uci.edu/~eppstein/161/960312.html) ].

### Key takeaways: 
This article aims to explain Evolutionary algorithms with an example problem and code excerpts in Python
By the end of this tutorial, the reader will understand:
1. What Evolutionary Algorithms are and how they work
2. Genetic operators [Mutation/ Crossover]
3. How to Simulate genetic/evolutionary algorithms using Python

### References: 
http://www.talkorigins.org/faqs/genalg/genalg.html

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - approved @Tvashta
