### ISSUE TITLE
How to embed a video into a webpage using HTML and CSS

### ISSUE THREAD

**Issue by annwawesh** [section-engineering-education/engineering-education#2035]
### **Proposed title of an article**

How to embed a video into a webpage using HTML and CSS.

### **Introduction paragraph (2-3 paragraphs):**

Embedding is incorporating videos, images, GIFs, links, or other social media contents like Electronic books (pdf or HTML files), tweets, Scribd, etc. into web pages or any other social media posts. 
Embedding allows you to lend a video from a different platform to another one without worrying about any compatibility issues like dissimilar software versions or formats. 
Embedding has various terminologies depending on the context is being used. For instance, embedding in computing is merging both software and hardware computer components to execute a highly tailored task. 

### **Key takeaways:**

1. What is embedding or generally video embedding?
2. HTML or HTML5.
3. Advantages and Disadvantages of embedding.
4. Embedding using URL.
5. How to embed videos from video sharing website.

### **References:**

N/A

### **Templates to use as guides**

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md) 
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by annwawesh** [comment]
Hello

**Comment by hectorkambow** [comment]
@annwawesh my apologies for the delayed reply - please always refer to contacting me via Slack - for a quicker response 👍

**Comment by hectorkambow** [comment]
sounds like a cool topic - approved @annwawesh

**Comment by hectorkambow** [comment]
merged
