### ISSUE TITLE
Structure Large Applications in Flask Using Blueprints and Flask Application Factory

### ISSUE THREAD

**Issue by corpsgeek** [section-engineering-education/engineering-education#2037]
### Proposed title of article
Structure Large Applications in Flask Using Blueprints and Flask Application Factory

### Introduction paragraph (2-3 paragraphs):
This article will explain and illustrate how to structure web applications on a large scale with the Python Flask backend web framework.

### Key takeaways: 
- Work Environment Setup
- Understanding  and implementing Blueprints and Application Factory
- Working with configuration and environment variable
- Summary and Conclusion

### References: 
N/A

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
@corpsgeek
