### ISSUE TITLE
How to upload images to Cloudinary using Node.js

### ISSUE THREAD

**Issue by RisoriTofa** [section-engineering-education/engineering-education#2038]
### Proposed title of the article
How to upload images to Cloudinary using Node.js

### Introduction paragraph (2-3 paragraphs):
One of the main problems a developer faces during media upload is a quick image and video manipulation and delivery optimization. This can be solved by the use of artificial intelligence (AI) which not only does it do both of these but also automates the process. Cloudinary is a good example of this service.
In this tutorial, we are going to learn how to upload an image to Cloudinary using Node.js

### Key takeaways: 

At the end of the tutorial, you will have learned about:

- Getting started with Cloudinary.js
- Integrating Cloudinary.js in a Node application
- Uploading an image to Cloudinary

### Pre-requisites
The basic requirements for this tutorial are:

- Web development basics
- A basic IDE installation on the machine. In our case, we shall use Visual Studio Code.
- Node basics
- A stable internet connection

### References: 

- [Cloudinary.js documentation](https://www.npmjs.com/package/cloudinary)

### Templates to use as guides:

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Seems like a good topic - just want to double check that it wont overlap too much with this existing article - and/or of it an be used in yours as a reference. 

🤔 

https://www.section.io/engineering-education/uploading-images-to-cloudinary-from-django-application/

**Comment by RisoriTofa** [comment]
Yes, it will be used as a reference in this article. The article was written in python but this shall be written using Node.js. @hectorkambow

**Comment by hectorkambow** [comment]
👍  Fantastic - thank you. Topic approved @RisoriTofa
