### ISSUE TITLE
Integration of Facebook authentication in Nodejs application 

### ISSUE THREAD

**Issue by sylvance7560** [section-engineering-education/engineering-education#2039]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
The need to simplify registration and login in applications has risen in many applications, registration form is not only time-consuming and tiresome but also frustrating the end user. Over time, account management becomes hard remembering credentials for every application. 
In the evolved technology, we can use popular social media applications such as Google, Facebook and Twitter to authenticate users. This process makes implementing authentication easier and increases adoption due to existing trust built with the social network. 
In this tutorial we are going to explain step-by-step how to code a Facebook login on your app using OAuth 2.

### Key takeaways: 
1. Handling requests to external resources on a Nodejs application.
2. Integrating Facebook authentication in Nodejs application. 
3. Exposing a local server to be accessed by an external server.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
cool topic - approved @sylvance7560

**Comment by hectorkambow** [comment]
@sylvance7560 just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?
