### ISSUE TITLE
Understanding Node.js Sequelize ORM Models

### ISSUE THREAD

**Issue by Tsanguu** [section-engineering-education/engineering-education#2042]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
**Understanding Node.js Sequelize ORM Models**

### Introduction paragraph (2-3 paragraphs):
Sequalize is an Object Relational Mapper for Node.js. This article will help you understand Sequalize models from model definition to model usage. At the end of this tutorial, you should be able to:
- Define models in Sequalize
- Understand different data types and use them in the model definition
- Validate models
- Define model associations
- Generate database schema from Sequalize models

Models are the backbone of any ORM. Therefore, you must understand how to work with models extensively to realize the full benefits of ORM. Models are database-independent.

### Key takeaways: 
- Introduction to models in Sequalize
- Sequalize model definition
- Sequalize data types
- Sequalize model validations
- Sequalize model associations

### References: 
[Sequelize Documentation](https://sequelize.org/master/)
[Sequelize API Reference ](https://sequelize.org/master/identifiers.html)

### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - if you havent already please review recently published Node.js articles in the EngEd library to avoid overlap and/or see what can be used as a reference. @Tsanguu approved

I think we just published an article on ORM - but it may be a different topic. 

https://www.section.io/engineering-education/introduction-to-sequalize-orm-for-nodejs/

**Comment by Tsanguu** [comment]
@hectorkambow  noted. I had gone through the article even before you published it. I suggested this issue with the published one in mind. The previous will be a prerequisite to this issue. There will be no overlap.

**Comment by hectorkambow** [comment]
@Tsanguu just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?
