### ISSUE TITLE
Getting started with Fastify Node.js framework and faunadb

### ISSUE THREAD

**Issue by marienjus** [section-engineering-education/engineering-education#2043]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting started with Fastify Node.js framework and faunadb 

### Introduction paragraph (2-3 paragraphs):
Fastify is a framework for backend web development with a powerful plugin architecture and the least overhead. It’s primarily inspired by Hapi and Express and is one of the fastest web frameworks running on Node.js. On the other hand, [Faunadb](https://fauna.com/) is a multi-model cloud database created to integrate with the JAMstack and modern serverless architecture. It easily transforms the traditional DBMS into a Data API that gives us all the capabilities of an old-guard database, without sacrificing flexibility, scale, and performance. In this tutorial, we will building an API to see a quick overview on how to use Fauna and Fastify in Node.js.

### Key takeaways: 
1. Introduction to Faunadb
2. Introduction to Fastify Node.js framework
3. How to integrate Fastify and Faunadb in a Node.js application
4. Building a Node.js backend API using Faunadb and Fastify

### References: 
N/A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by marienjus** [comment]
cc: @hectorkambow I hope this will be an even helpful topic. 💯

**Comment by hectorkambow** [comment]
cool topic - approved 👍  @marienjus
