### ISSUE TITLE
Push Notifications in Nodejs using Service Workers

### ISSUE THREAD

**Issue by mercymeave** [section-engineering-education/engineering-education#2047]
### Proposed title of article
Push Notifications in Nodejs using Service Workers

### Introduction paragraph (2-3 paragraphs):
A push notification is a message that pops on the screen when another activity is being performed on a mobile device or a web application. In modern web applications, push notifications have a wider place. The notifications help to engage the user and draw the attention fully to a new activity that occurs in the web application. 

A service worker is a script run by the browser in the background separate from the web page and acts as a bridge between the browser and the network. It usually intercepts requests made by the document in the browser and redirects requests to cache memory to allow offline access.

Service workers can be used to implement push notifications in a web application. In this tutorial, I will explain a step-by-step method of implementing push notifications in a node application using service workers.

### Key takeaways: 
1. Understanding push notifications in web application.
2. Clear introduction to service workers in Nodejs.
3. Implementing push notifications in a Nodejs web app.

### References: 
https://developers.google.com/web/fundamentals/primers/service-workers

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - if you havent already please review recently published Node.js articles in the EngEd library to avoid overlap and/or see what can be used as a reference. @mercymeave  approved
