### ISSUE TITLE
Android Hilt Tutorial

### ISSUE THREAD

**Issue by RaphaelNdonga** [section-engineering-education/engineering-education#2050]
### Proposed title of article
Android Hilt Tutorial

### Introduction paragraph (2-3 paragraphs):
Hilt is a dependency injection library best suited for android app development. Dependency injection is technique of separating two things. How dependencies are created and how the dependencies are used. Dependencies are parts of a program relied upon by other parts of a program. For example, a database can be a dependency for a repository or viewmodel that accesses its data. Dependency Injection therefore involves providing the database to the constructor of the repository. The dependency itself is instantiated elsewhere.

Dependency Injection has many benefits. Code is more testable, readable and maintainable. It also provides loosely coupled code that create room for flexibility. Flexible code results into extensible code. Hilt as a dependency injection library provides all this and more. Compared to other ways of enforcing dependency injection (e.g dagger and manual dependency injection), it has the least boilerplate code. That is why this tutorial is essential for all android developers.

### Key takeaways: 
1. The meaning of dependency injection 
2. Reasons for using Hilt for dependency injection
3. How to instantiate dependencies using Hilt
4. How to incorporate hilt into Activites, ViewModels, Services and other Android Components.

### References: 
https://developer.android.com/training/dependency-injection/hilt-android

**Comment by hectorkambow** [comment]
cool topic - approved @RaphaelNdonga
