### ISSUE TITLE
Getting Started With Node.js and Svelte

### ISSUE THREAD

**Issue by KayveTech** [section-engineering-education/engineering-education#2058]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting Started With Fastify and Svelte

### Introduction paragraph (2-3 paragraphs):

The Front-end JavaScript stack is ever-changing, one of the popular tools in front-end development these days is Svelte. [Svelte](https://svelte.dev/) is a radical new approach to building user interfaces. It is a compiler that works behind the scenes to turn your component files into beautifully optimized JavaScript. Unlike React, instead of using techniques like virtual DOM diffing, Svelte writes code that surgically updates the DOM when the state of your app changes. 
This tutorial will use svelte and Node.js to build a full-stack CRUD application.

### Key takeaways: 
1. Getting started with svelte
2. How to build a full-stack application using Svelte and Node.js
3. Advantages of using Svelte for client-side applications

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
cool topic - approved @KayveTech
