### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by WanjaMIKE** [section-engineering-education/engineering-education#2062]
**Is your feature suggestion related to a current problem or issue? Please describe.**
Code challenges can help empower the community. For instance, individuals can build Node.js applications and host them on section edge server. The code for these applications could be made public and the winning developers receive some token of appreciation. Later, the company can showcase these apps to attract more clients

**Describe the solution you'd like to implement to the program**
Code challenges

**Describe alternatives you've considered or seen**
Other sites implement this feature to encourage collaboration and teamwork amongst their community

**Additional context on how you could go about building this**
Should be implemented by the project head.

**Comment by marienjus** [comment]
cc: @hectorkambow, how about this 🤔

**Comment by hectorkambow** [comment]
Love it 👍  Thank you Sir! 

This way when we are ready to incorporate some new changes and events we can refer to this. 🚀
