### ISSUE TITLE
How to use an API in a Vue.js project

### ISSUE THREAD

**Issue by edidee** [section-engineering-education/engineering-education#2065]
### Proposed title of article
How to use an  API in a Vue.js project
### Introduction paragraph (2-3 paragraphs):
New web technologies are emerging every day. Vue.js is a JavaScript framework that is recently gaining popularity.
 When developing some projects using Vue.js, there will be a need to fetch or consume user-related data from an API. This will make the front-end of the project interact with the backend and the user-related data is fetched and displayed on the UI of the project.

### Key takeaways: 
By the end of this article, the reader will be able to:

- install and use Axios to get data from an API in Vue.js
- consume API with vuex and Axios
- Use Fetch API method to get data from an API
- Display user-related data in the UI of a project

### References: 
https://vuejs.org/v2/cookbook/using-axios-to-consume-apis.html
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by hectorkambow** [comment]
cool topic - approved @edidee

**Comment by hectorkambow** [comment]
@edidee just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?
