### ISSUE TITLE
Using Modern CSS Features in Old Browser using @supports

### ISSUE THREAD

**Issue by cyberShaw** [section-engineering-education/engineering-education#2066]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article

Using Modern CSS Features in Old Browsers using @supports

### Introduction paragraph (2-3 paragraphs):

In the world of Web Development, there are a lot of web browsers like Chrome, Safari, Firefox, etc. They vary slightly in their support for CSS features and properties. To solve this, the `@supports` CSS rule was introduced. This article is going to give readers an introduction to the @supports rule and give a hands on about the different ways this rule can be used to use modern features without breaking support in old web browsers. 

### Key takeaways: 

- The reader will be exposed to the different types of web browsers and web engines.
- The reader will be given an introduction to the `@supports` CSS rule.
- The reader will be walked through the different ways to use modern features without breaking compatibility in old web browsers.

### References: 

https://developer.mozilla.org/en-US/docs/Web/CSS/@supports

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
sounds like a cool topic - approved @cyberShaw

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 @cyberShaw  Please only one at a time.
 
 I just noticed this one - since its been approved - when your other PR is published we can open this one. 👍

**Comment by cyberShaw** [comment]
@hectorkambow Could you re-open this again?
