### ISSUE TITLE
How Artificially Intelligent Chatbots have impacted Healthcare Industry? 

### ISSUE THREAD

**Issue by verah-tech** [section-engineering-education/engineering-education#2070]
### Proposed title of article:
How Artificially Intelligent Chatbots have impacted Healthcare Industry?

### Introduction:
In recent times, companies have been taking the advantage of AI-powered virtual agents to automate routine processes and give their clients attention in customer services, payments, and marketing.
The trend has now spread to the healthcare industry. AI has created an environment where the patient outcome has been improved with minimum costs involved. 
Can a doctor's appointment be replaced by a machine?  This article will answer that question.

### Key takeaways: 
At the end of the article the reader will understand:
- How chatbots work?
- The benefits of using chatbots in the healthcare industry.
- The challenges faced when using chatbots in the healthcare industry.
- The health companies leading in the implementation of chatbots.

### References: 
N/A

**Comment by hectorkambow** [comment]
sounds like a cool topic - approved @verah-tech

**Comment by hectorkambow** [comment]
Just noticed that you have 2 topic forms open. 

Please to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍

@verah-tech

**Comment by verah-tech** [comment]
@hectorkambow The first topic I wrote and the article was published but the issue remained open.

**Comment by hectorkambow** [comment]
@verah-tech  understood my mistake - thank you for clarifying 🚀

**Comment by verah-tech** [comment]
@hectorkambow You are welcome

**Comment by hectorkambow** [comment]
merged
