### ISSUE TITLE
Feature suggestion: Header permalinks

### ISSUE THREAD

**Issue by geoffrey45** [section-engineering-education/engineering-education#2072]
**Is your feature suggestion related to a current problem or issue? Please describe.**
---
It's very difficult to share or refer to a specific part of an already published article. One has to find their way through the developer console in the browser to find a link to that specific header. 

**Describe the solution you'd like to implement to the program**
---
Adding a permalink to the headings would be helpful. These are icons in each header that one contains a link to that specific header (normally hidden but revelead when a cursor is placed on the header).

![Screenshot from 2021-04-16 16-04-38](https://user-images.githubusercontent.com/48554537/115028565-ae054f80-9ecd-11eb-9e30-feb93017367c.png)

**Describe alternatives you've considered or seen**
----
N/A

**Additional context on how you could go about building this**
---
N/A

**Comment by hectorkambow** [comment]
👀  Thank you v much!! 
We appreciate all feature/program suggestions - we are keep tabs via the labels.
