### ISSUE TITLE
A practical approach to date and time in javascript 

### ISSUE THREAD

**Issue by Sajeyks** [section-engineering-education/engineering-education#2074]
### Proposed title of article
A practical approach to date and time in javascript 

### Introduction paragraph (2-3 paragraphs):
Date and time are very crucial in our day-to-day lives, therefore, knowing how to work with them is important. Javascript comes with an inbuilt `Date ` object which can have various applications. There are also many inbuilt methods in javascript that can help us take advantage of the `Date` object.

In some situations, a programmer may find themselves in need to use dates and time to make important calculations, set up a countdown timer, or get information from a date. This tutorial is meant to help out with just that.

### Key takeaways: 
1. Getting the day of the week from a date
2. Iterating through dates
3. Calculating the number of days between two dates
4. Calculating number of workdays between two dates(excluding weekends)
5. Building a countdown timer 

### References: 
N/A

**Comment by hectorkambow** [comment]
cool topic - approved @Sajeyks

**Comment by hectorkambow** [comment]
Just noticed this is your 2nd (open) approved topic. 

 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
 
 Since it was already approved - go ahead and get the article ready - and when the other PR is published we can reopen this one. 🚀

**Comment by Sajeyks** [comment]
@hectorkambow Hello!  Am done with the other one. I'd like to get back to this one if you would allow me.

**Comment by kimkimani** [comment]
@Sajeyks  Hope the topic doesn't explore these Node.js Date libraries.
- https://www.section.io/engineering-education/nodejs-date-and-time-objects-with-moment/
- https://www.section.io/engineering-education/javascript-dates-manipulation-with-date-fns/

**Comment by hectorkambow** [comment]
@Sajeyks 
just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?

**Comment by Sajeyks** [comment]
Hey @hectorkambow .Am almost making a PR . Would you mind reopening this Issue?
