### ISSUE TITLE
Type Casting in Java

### ISSUE THREAD

**Issue by Terripha** [section-engineering-education/engineering-education#2075]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Type Casting in Java

### Introduction paragraph (2-3 paragraphs):
Type casting is a process of changing one type value to another type. It is also known as type conversion or Type Coercion.
There are two types of casting in java, that is explicit and implicit casting. 
Explicit casting is when you are assigning a larger type value to a variable of smaller type while Implicit casting is when you are assigning a smaller type value to a variable of larger type. In this article, we are going to cover the two type of casting and simple programs on how to go about it.

### Key takeaways: 

1. What is type casting
2. Explicit casting
3. Implicit casting
4. Advantages
5. Disadvantages

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @Terripha 

One major thing to note - your article should differ from what is already available through the official documentation.
We always lean towards content that offers an original viewpoint/approach around programming-centric topics.
