### ISSUE TITLE
Integrating GraphQL API in a Django application

### ISSUE THREAD

**Issue by Anitaachu** [section-engineering-education/engineering-education#2077]
### Integrating GraphQL API in a Django application
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
GraphQL is an open-source query language used to communicate data between the client (the browser) and the server. GraphQL was created by Facebook and is now used by a wide range of companies such as Microsoft, Github, Shopify, Amazon, etc.

GraphQL provides a runtime environment for Application Program Interfaces (API) which is easy to use, fast and developer-friendly. The most outstanding attribute of GraphQL is that it returns the requested data from multiple sources with just a single request this makes it more preferred than RESTAPI which is the alternative.
GraphQL has a lot of advantages however, in this tutorial our focus would be on integrating a GraphQL API into a Django project and effectively using it to query data.

### Key takeaways: 
1.  Creating a Django application
2. Integrating GraphQL
3. Creating a root schema
4. How to fetch data from query.

### References: 
https://graphql.org/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Anitaachu  
👋   Pleas to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 

When the 1st one is published we can re-open this open asap 🚀  

Thank you.

**Comment by hectorkambow** [comment]
seems like a cool topic - approved @Anitaachu

**Comment by hectorkambow** [comment]
merged
