### ISSUE TITLE
Concept of First Hop Redundancy Protocols

### ISSUE THREAD

**Issue by raboba2re** [section-engineering-education/engineering-education#2078]
### Proposed title of article
Concept of First Hop Redundancy Protocols

### Introduction paragraph (2-3 paragraphs):
Organizations uses various protocols to prevent a single point failure in their network, one of these protocols is the **First Hop Redundancy Protocol (FHRP)** which present a virtual default gateway to the organization's network for the purpose of redundancy. 
  This protocol provides the mechanism for determining which router should take the active role in forwarding traffic and  also determines when the forwarding role must be taken over by a standby router. The transition from one forwarding router to another is transparent to the end devices.

### Key takeaways: 
- Understand the concept of FHRP
- understanding Hot Standby Routing Protocol 
-  How to configure FHRP in a network. 

### References: 
- https://en.wikipedia.org/wiki/First-hop_redundancy_protocol
- https://www.routerfreak.com/ccna-fhrp-hop-redundancy-protocols/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @raboba2re 

One major thing to note - your article should _differ from what is already available through the official documentation._
We always lean towards content that offers an original viewpoint/approach around programming-centric topics.
