### ISSUE TITLE
PDF to Audio Book converter with Django

### ISSUE THREAD

**Issue by Chukslord1** [section-engineering-education/engineering-education#2082]
### Introduction paragraph (2-3 paragraphs):
If we could hear our books talk then studying would become easier and more versatile. In this article, we would be building a Django application that converts pdfs and text files to mp3 audiobooks. We would be making use of the gTTS( Google Text To Speech) library and the pdfminer library.

### Key takeaways: 
* The reader will learn how to utilize the gTTS library in a python application
*  The reader will learn how to extract data from a pdf using pdfminer
*  The reader will learn how to build a Django application.

### References: 
Nil

**Comment by hectorkambow** [comment]
good topic @Chukslord1  - approved. 

One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)

**Comment by hectorkambow** [comment]
@Chukslord1 just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?
