### ISSUE TITLE
Algorithms used in Data Mining

### ISSUE THREAD

**Issue by karuana2021** [section-engineering-education/engineering-education#2083]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Algorithms used in Data Mining

### Introduction paragraph (2-3 paragraphs):
Data mining is one of the fields used in Computer Science. It is the process of finding patterns and repetitions in huge datasets. Data mining techniques and algorithms are commonly used in Artificial Intelligence and Machine Learning. 
In this article we will have a look at Data Mining Algorithms, why Algorithms are used in Data Mining and types of Algorithms in Data Mining for example, Machine Learning Based Approach, Naive Bayes Algorithm, KNN Algorithm etc. 

### Key takeaways: 
1.	What are Data Mining Algorithms?
2.	Why Algorithms are used in Data Mining?
3.	Types of Algorithms used in Data Mining.
4.	Advantages and disadvantages of Data Mining.

### References: 
N/A

**Comment by hectorkambow** [comment]
cool topic - approved @karuana2021

**Comment by hectorkambow** [comment]
@karuana2021 just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?

**Comment by karuana2021** [comment]
Hi, wishing to reopen the project and submit the article for previewing of the article.
