### ISSUE TITLE
Getting started with C++ function pointers 

### ISSUE THREAD

**Issue by Dawe-7** [section-engineering-education/engineering-education#2087]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting started with C++ function pointers 

### Introduction paragraph (2-3 paragraphs):
Pointers are used to point to data. Like normal data pointers, we have `function pointers` which point to functions. Function pointers store the `address` of a function. In greater detail, they store the starting address or entry point of the block of memory containing all the instructions in a function. We use function pointers for several tasks. One example is to prevent code redundancy, which is what most programmers seek to achieve. For example, if you're writing a `sort()` function, you may want to give the function's caller the option of sorting data in ascending or descending order. Some programmers may need to sort in ascending or descending order, while others may prefer something in between. Function pointers allow the programmer to choose how to sort the data. Callbacks, event-driven programs, and so on are all applications of function pointers. This article will introduce the reader to the working and examples of the function pointer along with code examples. 

### Key takeaways: 
1. Function pointers and callbacks
2. How to create function pointers
3. Interesting facts about function pointers
4. Passing function pointers as arguments
5. Code examples to demonstrate the use of function pointers.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Dawe-7  
 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
 
 I just noticed you submitted like 3-4 topics - please only one at a time.
