### ISSUE TITLE
Understanding IPV4 and IPV6 protocols

### ISSUE THREAD

**Issue by awinomackrine** [section-engineering-education/engineering-education#2095]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Understanding IPV4 and IPV6 protocols
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Internet protocol versions are basically protocols responsible for data-gram relay across am interconnections of computers.  There exists two versions of internet protocol versions, namely internet protocol version 4 and internet protocol version 6.

In this article I will be explaining the two internet protocol versions, explain their functionalities and the reasons why one version might take preference to another.

### Key takeaways: 
1.  The reader will be in a position to understand what internet protocols  are and its importance in  communication over the internet.
2.  The reader will be able to understand what internet protocol versions are , the different  types of internet protocol versions available today and their functionalities.
3.  The reader will be able to learn the differences between the two versions of internet protocol and which version is preferred to the other and why.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@awinomackrine  to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
Once the 1st one is published we can re-open this one 🚀

**Comment by hectorkambow** [comment]
👍 

Fixed - thank you. My apologies for the confusion - to help avoid this with future PR - lets be sure to link our topic forms with our PRs so when merged they close the topic form as well 🚀

**Comment by hectorkambow** [comment]
seems like a helpful topic - please be sure to go over past EngEd articles to see how they can be referenced if applicable 

https://www.section.io/engineering-education/search/?q=lan

@awinomackrine  approved
