### ISSUE TITLE
How to get started with NFT's (Non-Fungible Tokens)

### ISSUE THREAD

**Issue by Jethro-magaji** [section-engineering-education/engineering-education#2097]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to Get started with NFT's (Non-Fungible Tokens)

### Introduction paragraph (2-3 paragraphs):
A non-fungible token (NFT) is a unit of data stored on a digital ledger, called a blockchain, that certifies a digital asset to be unique and therefore not interchangeable. NFTs can represent items such as photos, videos, audio, and other types of digital files. What makes an NFT unique is the digital asset tied to the token. 
This tutorial is on how blockchain developers, enthusiasts, investors, artists, musicians, etc can get started with NFT's (Non-Fungible Tokens). it also provides a guide on the basis and creation of an NFT on the Ethereum blockchain network.  

### Key takeaways: 
- What is an NFT
- Uses of NFT
- Creating an NFT using code
- How to sell an NFT
- Trends with NFT's

### References: 
- https://en.wikipedia.org/wiki/Non-fungible_token#:~:text=A%20non%2Dfungible%20token%20(NFT,other%20types%20of%20digital%20files.
- https://ethereum.org/en/nft/
- https://www.cnet.com/news/nfts-explained-these-expensive-tokens-are-as-weird-as-you-think-they-are/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
 
 @Jethro-magaji
