### ISSUE TITLE
How to send SMS in Django using Twilio

### ISSUE THREAD

**Issue by shosenwales** [section-engineering-education/engineering-education#2098]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article

How to send SMS in Django using Twilio

### Introduction paragraph (2-3 paragraphs):
 
How to send SMS in Django using Twillio. This can be used to send otp's in a project

### Key takeaways: 

1. Learn about Twilio
2. How to send/recieve messages in a Django project
3. How to use twillio with django

### References: 

N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - @shosenwales 

Yet - there is very little for us to go by in this form - we actually are asking students to include 2-3 paragraphs in order for us to decide on quality to approve. 👍

**Comment by shosenwales** [comment]
Hi @hectorkambow, sorry about that. Here's a more detailed paragraph

## Introduction paragraph (2-3 paragraphs):

Imagine building a django web application that requires the feature of sending text messages or one time password(OTP) for authentication. Fortunately Twilio can be easily integrated with django to achieve this.

**Comment by hectorkambow** [comment]
👍  Thank you next time please include two or three paragraphs for the topic to be reviewed .

@shosenwales  - topic -approved
