### ISSUE TITLE
Integrating Instagram basic display API on a Node.js graphql API

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#2100]
### Proposed title of article
Integrating Instagram basic display API on a Node.js graphql API

### Introduction paragraph (2-3 paragraphs):
Instagram is a photo and video social networking service launched in 2010. As of 2021, Instagram is estimated to have more than one billion users. In October 2019, Instagram launched the basic display API that allows users of your application to get photos, videos, and basic profile information on their Instagram accounts. It only provides read-access. In this article, we will integrate the Instagram basic display API on a Node.js graphql API.

### Key takeaways: 
- How to create a Facebook developer account.
- How to get an access token while working with the Instagram basic display API.
- How to get profile information, photos, and videos while working with the Instagram basic display API.
- How to exchange short-lived access token to long lived access token while working with the Instagram basic display API.

### References: 
- https://developers.facebook.com/docs/instagram-basic-display-api/guides
- https://levelup.gitconnected.com/getting-started-with-the-instagram-basic-display-api-5124c92c4935

**Comment by hectorkambow** [comment]
seems like a cool topic - approved @mwangiKibui

**Comment by hectorkambow** [comment]
@mwangiKibui just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?

**Comment by mwangiKibui** [comment]
I need to submit it now @hectorkambow . Can it be reopened?

**Comment by mwangiKibui** [comment]
@hectorkambow I have submitted the PR.
