### ISSUE TITLE
Getting started with Spring Boot Rest Template

### ISSUE THREAD

**Issue by elizabeth962** [section-engineering-education/engineering-education#2106]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article on time from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Getting started with Spring Boot RestTemplate
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article's higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Interacting with REST APIs in Java requires a lot of boilerplate code that makes the final application code complex. RestTemplate makes interacting with most RESTful web services a one-line incantation. RestTemplate simplifies REST API interaction in Spring Boot applications by abstracting away the boilerplate code that would slow down the development process and providing a single-line implementation.  In the tutorial, I will be explaining how to consume RESTful APIs from the popular [JSON placeholder](https://jsonplaceholder.typicode.com/).

### Key takeaways: 
1. Setting up RestTemplate in Spring Boot.
2. Consuming data from the various REST API endpoints using RestTemplate.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@elizabeth962 seems like a helpful topic - I think its a different topic altogether - but I just wanted to double check that it does not overlap with any of the existing [Spring Boot articles](https://www.section.io/engineering-education/search/?q=Spring%20Boot) - and/or see which ones can be referenced in your article. 

Approved 👍
