### ISSUE TITLE
CRUD Operations with YII2 Framework Using GII

### ISSUE THREAD

**Issue by Beatricewanjiru** [section-engineering-education/engineering-education#2111]
###  Proposed title of article

CRUD Operations with YII2 Framework Using GII

### Introduction paragraph (2-3 paragraphs):

Programmers who have ever worked with the database are likely to have also worked with CRUD Operations.

CRUD is an acronym that stands for Create, Read, Update, Delete. Each letter in the acronym can refer to all functions executed in relational database applications.

The function of each letter in the CRUD acronym is as shown below:

CREATE: Performs the INSERT statement to create a new record.

READ: Reads the table records based on the primary keynoted within the input parameter.

UPDATE: Executes an UPDATE statement on the table based on the specified primary key for a record within the WHERE clause of the statement.

DELETE Deletes a specified row in the WHERE clause.

YII2 is a PHP Framework for rapidly developing modern Web applications.

GII is a YII2 module, which provides web-based code generation facilities.

In this article, we are going to look at CRUD operations in YII2 using GII in detail.

### Key takeaways: 

In this article the reader will be able to:

1. Define the term CRUD

2. Create a simple database record 

3. Configure and use GiiModule in the Yii framework

4. Enable GII in Yii2

5. Store data in database using GII

**Comment by hectorkambow** [comment]
Sounds like a very cool topic - approved @Beatricewanjiru  

I dont think its the same - but perhaps there is things we could reference in [this article](https://re.sajari.com/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiY2xpY2siLCJkZXN0aW5hdGlvbiI6Imh0dHBzOi8vd3d3LnNlY3Rpb24uaW8vZW5naW5lZXJpbmctZWR1Y2F0aW9uL3BocC15aWkyLWZyYW1ld29yay8iLCJ2YWxzIjp7ImNvbGxlY3Rpb24iOlsic2VjdGlvbi1pbyJdLCJjb21wYW55IjpbIjE1NjgyMzQxMTYwNzg2MTQ4NjgiXSwiZmllbGQiOlsidXJsIl0sInByb2plY3QiOlsiMTU2ODIzNDExNjA3ODYxNDg2OCJdLCJxLmlkIjpbIjFzcnd2cDlueWoyemtiM3EiXSwicS5zbCI6WyIxIl0sInEudWlkIjpbIjFzcnd2cDlueWoyemtiM3EwIl0sInZhbHVlIjpbImh0dHBzOi8vd3d3LnNlY3Rpb24uaW8vZW5naW5lZXJpbmctZWR1Y2F0aW9uL3BocC15aWkyLWZyYW1ld29yay8iXX19.AwczHyJAYtn-21Qg3EeDz5fAkHIqyaNcxz1CbKcu8Zk)
