### ISSUE TITLE
What are container components in React

### ISSUE THREAD

**Issue by Caleb335** [section-engineering-education/engineering-education#2113]
### Proposed title of article
What are container components in React

### Introduction paragraph (2-3 paragraphs):
As time goes on, while making use of React, one would need to think of how we make data interact with different types of components in a React application. 

"Container components", gotten from [Dan Abramov's](https://twitter.com/dan_abramov) ideology of a React app pattern, are components whose sole responsibility or functionality is to fetch data. Fetching data doesn't compulsorily mean obtaining data from an API. Fetching of data could also include the logic of a particular component.

Once the logic or data fetching in the container component is done, it renders its corresponding component. This corresponding component, most of the time holds the user interface or layout of such container components.

### Key takeaways: 
In this article, the reader(s) will have an understanding of how a container component functions, then we'd look at a simple example of a container component by building a search container component

### References: 
- [Presentational and Container Components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)

**Comment by hectorkambow** [comment]
@Caleb335 sounds like a good topic @ - approved. 

One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)

**Comment by Caleb335** [comment]
Thank you, Hector!

I'd make sure to do all that you've said.

**Comment by hectorkambow** [comment]
merged
