### ISSUE TITLE
Image processing with Node.js and Jimp

### ISSUE THREAD

**Issue by flavianadhiambo** [section-engineering-education/engineering-education#2114]
### Image processing with Node.js and Jimp
[JavaScript Image Manipulation Program (Jimp)](https://github.com/oliver-moran/jimp) allows us to easily manipulate and transform your images into any required format, style, or dimension. It also optimizes images for minimal file size, ensures high visual quality for an improved user experience, and reduces bandwidth. 

With Jimp, we can resize and crop images, convert them to the image format that fits your needs, and apply filters and effects. In this tutorial, we’ll go over how the library works and describe some common use cases for Jimp image manipulation.

### Key takeaways: 
1. Setting up Jimp in a Node.js application.
2. Image resizing, cropping, and rotation using Jimp.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - approved @flavianadhiambo
