### ISSUE TITLE
Getting Started With Node.js and Hapi

### ISSUE THREAD

**Issue by Bradley8555** [section-engineering-education/engineering-education#2115]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting Started With Node.js and Hapi

### Introduction paragraph (2-3 paragraphs):
Node.js is a wide ecosystem and the great thing about this ecosystem is the fact that if you’re looking to create an application, there’s most likely a module/framework that can help with that. One such Node.js framework is Hapi.  Hapi is extremely light weight and built around a plugin system that keeps everything modular. This enables developers to focus on writing reusable application logic instead of spending time building infrastructure.
In this tutorial, we will be setting up a server in Node.js and Hapi.

### Key takeaways: 
1. Installing and configuring Hapi in a Node.js project
2. Creating routes using Hapi framework
3. Setting plugins, best practices and serving files 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by kayere** [comment]
Hello @Bradley8555, I think your article suggestion matches this [Article](https://www.section.io/engineering-education/introduction-to-hapi/). Please have a look.
