### ISSUE TITLE
Implementing Logging With Pino and Asynclocalstorage in Node.js

### ISSUE THREAD

**Issue by marienjus** [section-engineering-education/engineering-education#2116]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials promptly. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an article to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Implementing Logging With Pino and Asynclocalstorage in Node.js

### Introduction paragraph (2-3 paragraphs):
Spending hours, or even days, trying to fix an obscure bug is frustrating and unproductive. Eventually, you’ll end up staring at the screen waiting for a eureka moment to magically happen. Instead, building a logging system to trace any bug can be quite helpful. When used correctly, logging can give you the necessary insights into your application so to help figure out exactly what happened. Proper logging can be the difference between a lousy dump of debug statements and a powerful debugging tool that helps you find bugs easier and fix them faster.
In this tutorial, we will use Pino, a popular fast, and minimal logging library in the Node.js ecosystem to create a logging trace systematically with Asynclocalstorage.

### Key takeaways: 
1. Setting up Pino and Asynclocalstorage in Express Node.js server
2. What is AsyncLocalStorage and how does it work?
3. What is a logging library and why you should use it
4. How to associate logs with a particular request

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@marienjus   to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 

Thank you - once the 1st one is published we can reopen this one 🚀
