### ISSUE TITLE
Testing Nodejs Express API Endpoints With Jest and supertest

### ISSUE THREAD

**Issue by KayveTech** [section-engineering-education/engineering-education#2117]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Testing Nodejs Express API Endpoints With Jest and supertest

### Introduction paragraph (2-3 paragraphs):
 Software testing is the process of verifying a system with the purpose of identifying any errors, gaps, or missing requirements versus the actual requirement. In JavaScript and Node.js, one popular tool for testing is Jest. Jest is a JavaScript testing framework developed by Facebook. It works out of the box with minimal configuration and has an in-built test runner, assertion library, and mocking support. Supertest is a library for testing Node.js HTTP servers. It enables us to programmatically send HTTP requests such as GET, POST, PATCH, PUT, DELETE to HTTP servers and get results.
This tutorial will focus on testing in Node.js Express API using Jest and Supertest.

### Key takeaways: 
1. What is testing and why should we write tests?
2. Configuring `supertest` and `Jest` in Node.js
3. Testing API endpoints using Jest and `supertest`

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@KayveTech  
 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍

**Comment by KayveTech** [comment]
@hectorkambow , can I start working on this issue? Had my paypal changed too. Did contact you via slack.
