### ISSUE TITLE
How to create charts in Node.js with billboard.js

### ISSUE THREAD

**Issue by qawuor** [section-engineering-education/engineering-education#2120]
### How to create charts in Node.js with Billboard.js
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article's higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Data is such a crucial part of not just software development, but society in general. Wherever data resides, and however it’s used, it’s important to display it in a way that helps the audience digest and understand it.

Billboard.js is a powerful, reusable, elegant interface chart library based on D3 v4+. It’s a JavaScript library that allows developers to create a chart instantly to visualize data. In the tutorial, I will explain how to set up Billboard.js in a Node.js application and finally create different charts.

### Key takeaways: 
1. Billboard.js setup in Node.js application.
2. Creation of different chart types using Billboard.js.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
very cool topic - approved @qawuor
