### ISSUE TITLE
How to handle navigation in flutter

### ISSUE THREAD

**Issue by wobin1** [section-engineering-education/engineering-education#2121]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
One of the core concepts in all mobile applications is navigation, it allows a user to move between different pages. Navigating to different pages defines the workflow in any mobile application. This article will explain the flutter navigation and routing system. 

### Key takeaways: 
At the end of this article, the reader will:
-Understand What navigation is generally in mobile development
-Understand the navigation and routing system in flutter
-Know how to handle navigation in flutter

### References: 
https://flutter.dev/docs/development/ui/navigation

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
sounds like a cool topic - approved @wobin1

**Comment by hectorkambow** [comment]
@wobin1 just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?
