### ISSUE TITLE
Working with cypress in Nodejs

### ISSUE THREAD

**Issue by LinusMuema** [section-engineering-education/engineering-education#2124]
### Proposed title of article
Working with cypress in Nodejs

### Introduction paragraph (2-3 paragraphs):
End to End or simply E2E testing is one of the commonly used testing methods. In web applications, this comes in handy to allow the developer to maintain a strict TDD development pattern. 
Cypress is an end-to-end testing framework that helps developers test their web applications easily and provides an interface for them to easily analyze their test progress and results. It also offers features like test snapshots and dashboard services. 
This article aims to help readers understand how cypress works and how to write end-to-end tests.

### Key takeaways: 
1. What end-to-end tests are
2. How to install cypress
3. Writing tests with cypress
4. Using the cypress to check your tests

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
cool topic - approved @LinusMuema
