### ISSUE TITLE
Top Node.js Security Vulnerabilities and their Solutions 

### ISSUE THREAD

**Issue by Annpurity** [section-engineering-education/engineering-education#2127]
### Proposed title of article

Top Node.js Security Vulnerabilities and their Solutions 
### Introduction paragraph (2-3 paragraphs):
Node.js, like any other framework or programming language, is prone to all kinds of web application vulnerabilities. The core of Node.js is secure, but third-party packages may require additional security measures to protect your web applications. 
The most common Node.js security issues include NPM phishing and regular expressions Denial of Service (DoS). Besides the Node-related threats, there are also the usual web security issues like cross-site request forgery, cross-site scripting, unvalidated redirects, and security misconfiguration.

### Key takeaways: 

1. Definition of NPM and its relation with security issues
2. Main Node.js Security Vulnerabilities
3. Solutions to these vulnerabilities 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
very cool topic @Annpurity  - approved

**Comment by hectorkambow** [comment]
@Annpurity just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?
