### ISSUE TITLE
Getting started with Container as a Service (CaaS)

### ISSUE THREAD

**Issue by OMONDIELLY** [section-engineering-education/engineering-education#2128]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting started with Container as a Service

### Introduction paragraph (2-3 paragraphs):
There seems to be a trend today where solutions tend to rely on "the as a service" model/offering. I bet you have heard of Infrastructure as a Service, Platform as a Service and even more.
Containers have joined the trend with the evolution of Container  as a Service model for container based solutions.
This article aims to help readers understand  Container as Service and its benefits when working with containers.

### Key takeaways: 
1. What is Container as a Service
2. Why Container as a Service
3. Benefits of Container as a Service
4. Container as a Service tools
5. Working with Amazon Elastic Container Service (ECS).

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like an interesting topic - approved @OMONDIELLY

**Comment by hectorkambow** [comment]
@OMONDIELLY just noticing that this is your 2nd opened article topic. 

To help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 

Since its been approved - go ahead and get the article ready - once your first PR is published we can re-open this one.

**Comment by OMONDIELLY** [comment]
ok, thanks

**Comment by OMONDIELLY** [comment]
> @OMONDIELLY just noticing that this is your 2nd opened article topic.
> 
> To help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
> 
> Since its been approved - go ahead and get the article ready - once your first PR is published we can re-open this one.

Hello , I think you could help me by reopening this issue now that the first PR is published.

**Comment by OMONDIELLY** [comment]
I think am ready to open a PR on this, would you kindly reopen it.
