### ISSUE TITLE
Sharing data across destinations using `safe-args` in Android-Kotlin

### ISSUE THREAD

**Issue by Ericgacoki** [section-engineering-education/engineering-education#2129]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an article to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

**Sharing data across destinations using `safe-args` in Android-Kotlin**

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

Data sharing involves passing arguments between screens in an operation referred to as navigation. This not only enhances communication between the involved destinations but also establishes a continuous flow of the application. In the past few years, Android developers made use of the Android `Bundle` class which was one of the common techniques to share data across activities. This came with a bunch of cons among which is the tedious work the developer had to do, unreliability due to the manual approach, and lack of type safety that could easily crash the application.

The Navigation components API, (part of [Jetpack](https://developer.android.com/jetpack) libraries) is a MAD(Modern Android Development) approach that solves these problems by introducing `safe-args` -a plugin capable of passing data attached to a navigation action in a more efficient, safe, and encapsulated way.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, the reader is expected to:

1. Understand what is meant by **sharing data** across destinations.
2. Implement navigation **safe-args** in an Android application.
3. Be able to pass **custom arguments** used in a navigation action.
4. Be able to **debug parcels** within the navigation.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

1. https://developer.android.com/guide/navigation/navigation-pass-data
2. https://www.youtube.com/watch?v=8I8Xykqn4hk
3. https://developer.android.com/kotlin/parcelize

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Ericgacoki** [comment]
Hey @hectorkambow, could you please give me a signal on this?

**Comment by hectorkambow** [comment]
@Ericgacoki  seems like a very helpful topic - approved
