### ISSUE TITLE
Top 7 Docker Container Monitoring Tools

### ISSUE THREAD

**Issue by BridgetMwikali** [section-engineering-education/engineering-education#2131]
### Proposed title of article
Top 7 Docker Container Monitoring Tools
### Introduction paragraph (2-3 paragraphs):
Monitoring systems help DevOps teams detect and solve performance issues faster. With Docker and Kubernetes steadily rising, it’s essential to get container monitoring and log management right from the start.

Due to its popularity, monitoring docker containers sometimes boils down to a problem of choice, as there exist a variety of tools from which to choose, each of them has its pros and cons.

This article will delve deep into what container monitoring is and why you need it and compare the best container monitoring tools available today.

### Key takeaways: 
1.	Why Should You Monitor Docker Containers 
2.	Monitoring VS orchestration
3.	Docker Container Monitoring Tools
MetricFire
Docker CLI (docker stats)
cAdvisor
Scout
Data Dog
Sensu monitoring framework
Sematext

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
very cool - approved

**Comment by hectorkambow** [comment]
merged
