### ISSUE TITLE
Which JS Framework between Angular and React is suitable for your next project?

### ISSUE THREAD

**Issue by martha-ngugi** [section-engineering-education/engineering-education#2138]
### Proposed title of article
Which JS Framework between Angular and React is suitable for your next project?

### Introduction:
Choosing the right JavaScript framework for a project can be confusing. Especially when a lot of options that are resourceful and capable of facilitating project requirements are available. However, choosing the right one requires knowledge of several critical aspects. In the article, I will cover essential points by comparing Angular and React.

### Key takeaways: 
In this article the reader will be able to:
- Understand the comparisons between Angular and React in terms of popularity, performance, testing, code quality, code maintainability, server rendering, optimization, and learning curve.
- Understand the reasons behind using Angular or React.
- Know popular Angular and React use cases.

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a cool topic and helpful topic - @martha-ngugi  approved 👍
