### ISSUE TITLE
A-star algorithm: a "smart" way to search

### ISSUE THREAD

**Issue by nimra200** [section-engineering-education/engineering-education#2139]
### Proposed title of article
Title: A-Star algorithm: a "smart" way to search

### Introduction paragraph (2-3 paragraphs):

Imagine you wanted to travel from Toronto to Vancouver. You want to find a path that lets you get to your destination quickly.  One way is to consider all the cities that lie in between Toronto and Vancouver. You start by picking the city closest to Toronto, for example Milton, and travel there. You could then consider all the cities that lie between Milton and Vancouver, and again pick the closest city to you. But is there a better way to search? This article explores a "smarter" way to search by using the A-star (A*) algorithm. 

The A* algorithm is "smarter" because it is an _informed_ search. It considers how much each action will cost and guesses how far away we are from achieving our goal. This guess is called a "heuristic", and it helps us find the cheapest way to get to our goal. Mathematically, we use the formula _f(n) = g(n) + h(n)_, where _g(n)_ is the cost of getting to the node _n_ from our start point and _h(n)_ is the estimated cost to get to the goal from node _n_. 

### Key takeaways: 

1. The reader should be able to perform A* search algorithm on pen and paper. 
2. The reader should understand what an admissible heuristic is, and that it allows A* search to find the cheapest path from start to goal. 
3. The reader will understand a common variations of the A* search: weighted A* search, uniform cost search, greedy best first search.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
The textbook Artificial Intelligence A Modern Approach by Russell and Norvig.

**Comment by hectorkambow** [comment]
very cool @nimra200 - approved 👍

**Comment by hectorkambow** [comment]
@nimra200 just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?

**Comment by nimra200** [comment]
Sorry, I didn't get a chance to make a PR for this topic. Hopefully when I get the chance to do so we can reopen this issue

**Comment by hectorkambow** [comment]
@nimra200 100% the topic can always be reopened - just ping me when you would like to reopen it 👍
