### ISSUE TITLE
Running and Managing Docker Containers

### ISSUE THREAD

**Issue by Agusioma** [section-engineering-education/engineering-education#2142]
### Proposed title of the article

*Running and Managing Docker Containers*

### Introduction paragraph (2-3 paragraphs):

**Docker** is a tool used to create and run applications using containers that can run virtually anywhere. Some benefits of using Container Technology include enhanced scalability, abstracting your application's underlying infrastructure, efficiency, etc.

In this article we will get an overview of the Docker Image Format, Building the images, and the Docker Container Runtime. Moreover, we will also check about optimizing image sizes, limiting resource usage, and data cleanup.

### Key takeaways: 

After reading this article, the reader will have a kickstart knowledge about:

1. Container images
2. Building Application Images using Docker
3. The Docker Container Runtime 

### References: 

BOOK - Kubernetes: Up and Running by Kelsey Hightower, Brendan Burns, and Joe Beda

**Comment by hectorkambow** [comment]
seems like an informative topic - approved @Agusioma

**Comment by Agusioma** [comment]
@hectorkambow thank you.
