### ISSUE TITLE
Getting started with Kubernetes Clusters

### ISSUE THREAD

**Issue by munubi254** [section-engineering-education/engineering-education#2143]
### Proposed title of the article

Getting started with Kubernetes Clusters

### Introduction paragraph (2-3 paragraphs):

A **Kubernetes Cluster** is a dynamic system that places and manages containers, grouped in pods, running on nodes, along with all the interconnections and communication channels working to perform a certain operation. In this article, we will first look at how to install Kubernetes on a Cloud Provider and locally in our machines. We will also look at how to use the Kubernetes Client(`kubectl`)  to check our clusters and a few cluster components available such as the *Kubernetes Proxy, Kubernetes UI,* and *Kubernetes DNS*.

### Key takeaways: 

We will get an overview of:

1.  Installing Kubernetes on a Cloud Provider and locally in our machines
2. The Kubernetes Client(`kubectl`) 
3. Kubernetes Cluster components

### References: 
N/A

**Comment by hectorkambow** [comment]
very cool - approved @munubi254
