### ISSUE TITLE
Containers vs VMs: What are the differences?

### ISSUE THREAD

**Issue by Jeff-mwangi** [section-engineering-education/engineering-education#2146]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Containers vs. VMs: What are the differences?

### Introduction paragraph (2-3 paragraphs):
Containers have become a dominant force in cloud native development, so it’s important to understand what they are. While containers and VMs have distinct and unique characteristics, they are similar in that they both improve IT efficiency and provide application portability.

A VM is essentially an emulation of a real computer that executes programs like a real computer. VMs run on top of a physical machine using a “hypervisor”. A hypervisor, in turn, runs on either a host machine or on “bare-metal”.
Unlike a VM which provides hardware virtualization, a container provides operating-system-level virtualization by abstracting the “user space”. 

In this article, we will make clear distinction between containers and virtual machines, as this can heavily impact your decision on which to use.

### Key takeaways: 
1. What are containers and Virtual machines (VM)
2. Why we should use containers
3. Differences and similarities between containers and virtual machines.
4. Advantages and disadvantages of Containers and VMs 

### References: 
N/A

**Comment by hectorkambow** [comment]
👋  
 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
 @Jeff-mwangi
