### ISSUE TITLE
How to work with Docker containers using VS Code

### ISSUE THREAD

**Issue by Njerikariuki** [section-engineering-education/engineering-education#2147]
### Proposed title of article
---
How to work with Docker containers using VS Code

### Introduction paragraph (2-3 paragraphs):
---
Containers are an easy way to bundle up your application, its dependencies, and configurations in a portable and easily distributable image file. Containers are an abstraction at the app layer that packages code and dependencies together. Did you know that you can manage your Docker containers and develop inside them in VS Code? 

The Docker extension makes it easy to build, manage, and deploy containerized applications from Visual Studio Code. This extensions enables you to create new Docker containers with only a few clicks saving you from memorizing docker commands. Building Dockerfiles and deployment of Docker containers is taken care of.

In this tutorial, we are going to look at how we can integrate development in Docker containers into VS Code.

### Key takeaways: 
---
By the end of this tutorial, the readers will be able to:
- install Docker in their machines.
- Install the Docker Vs Code extension.
- Run a simple Node.js application in Docker using VS Code.
- Generate a `Dockerfile`.
- Understand the most used Docker commands.
- Build and run a Docker image.
### References: 
---
N/A

**Comment by hectorkambow** [comment]
seems like a very helpful topic @Njerikariuki  approved

**Comment by hectorkambow** [comment]
@Njerikariuki just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?

**Comment by Njerikariuki** [comment]
Hello @hectorkambow I have opened a pull request for this issue. Please reopen.
