### ISSUE TITLE
How To Share Data between Docker Containers

### ISSUE THREAD

**Issue by OkothPius** [section-engineering-education/engineering-education#2151]
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
How To Share Data between Docker Containers

### Introduction paragraph (2-3 paragraphs):

Docker is a popular containerization tool used to provide software applications with a filesystem that contains everything they need to run. Using Docker containers ensures that the software will behave the same way regardless of where it is deployed because its run-time environment is consistent.

Docker containers are transient, running just as long as it takes for the command issued in the container to complete. Sometimes, however, applications need to share access to data or persist data after a container is deleted. Persistent access to data is provided with Docker Volumes.

In this article, we will look at three different ways to share data between docker containers.

### Key takeaways: 

1. What docker container is
2. Create an independent volume
3. Create a volume from an existing directory with data
4. Share data between multiple docker containers

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @OkothPius
