### ISSUE TITLE
Introduction to Subnetting

### ISSUE THREAD

**Issue by kwennB** [section-engineering-education/engineering-education#2153]
**Proposed name of the article**: **Introduction to Subnetting**

Subnetting is a logical partition process of splitting a single-page network into two or more strands.
Subnetting narrows down the internet protocol(IP) address to usage within a range of devices. It makes computer networks more efficient.
This article will ferret deep into what subnetting is, how it works, and its benefits. 

**Key Takeaways**

1. what subnetting is and its benefits
2. know about internet protocol and its classes
3. Learn what a subnet mask is
4. understand the basics of routing in networks

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - @kwennB - approved

**Comment by hectorkambow** [comment]
@kwennB just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?
