### ISSUE TITLE
Introduction to Containers and Docker.

### ISSUE THREAD

**Issue by Evanslodoctor** [section-engineering-education/engineering-education#2154]
### Introduction paragraph (2-3 paragraphs):
Container is a standard unit of software development in which software service are packaged together so that the application runs quickly across all computing environment. The containerized application can be tested as a unit and deployed as a container image instance to the target operating system.

Docker container image is a lightweight standalone executable package of software that includes system tools, system libraries, code and settings used to run an application. Developers can use development environments on Windows, Linux, or macOS on a computer, the developer runs a Docker host where Docker images are deployed.
### Key takeaways: 
   1. Brief introduction to Containers and Dockets.
   2. Container Terminology
   3. Introduction to Docker/Docker Engine.
   4. Reasons why we use Dockers.
   5. Docker Windows System Requirements and installation.

**Comment by hectorkambow** [comment]
@Evanslodoctor seems like a great topic - please be sure to go over any of the existing articles to see where we can expand upon and what can be refernced. 

We want to be sure we dont overlap with existing content 🚀  

https://www.section.io/engineering-education/topic/containers/

approved

**Comment by hectorkambow** [comment]
@Evanslodoctor just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?

**Comment by Evanslodoctor** [comment]
hello @hectorkambow.  I request  reopening of this issue please.
