### ISSUE TITLE
Setting up Frontend Asset Compilation in AdonisJS Using Webpack

### ISSUE THREAD

**Issue by vicradon** [section-engineering-education/engineering-education#2157]
### Tutorial Format
- Setting up Frontend Asset Compilation in AdonisJS Using Webpack
- AdonisJS allows developers to choose how their frontend assets should be compiled. This degree of freedom also brings issues for developers who need a fast and quick way to set up asset compilation. In this tutorial, we will explore how frontend asset compilation can be set up in AdonisJS using Webpack.
- Prerequisites:
    - Node.js version 12 or higher
    - npm version 6 or higher
- Step 1 — Cloning the repository
- Step 2 — Installing webpack and webpack CLI
- Step 3 — Frontend compilation of Bootstrap and Sass
- Step 4 — Frontend compilation of Tailwind CSS
- Step 5 — Frontend compilation of AlpineJS
- Step n — Optimizing build
- Conclusion: In this tutorial, you learned how to set up frontend asset compilation in AdonisJS using Webpack

**Comment by hectorkambow** [comment]
seems like a very helpful topic - lets be sure to include substance and value beyond what is readily available on official docs or other blog posts 👍  

@vicradon - approved

**Comment by hectorkambow** [comment]
@vicradon just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?
