### ISSUE TITLE
Clone Reddit Homepage with Tailwind CSS 

### ISSUE THREAD

**Issue by Worawat101** [section-engineering-education/engineering-education#2159]
### Proposed title of article
This tutorial will be about using Tailwind CSS with latest version of Vue framework. We will learn how to integrate Tailwind CSS to Vue ecosystem and use it to style for UI component. For the UI build, we are going to implement the clone of Reddit UI. Making use of Tailwind CSS, we are going to create the Reddit clone UI in Vue JS.

### Introduction paragraph (2-3 paragraphs):
- Basics of Vue 3
- Basics of Tailwind CSS framework
- Integrating Tailwind CSS in Vue
- Using style classes of Tailwind CSS
- Implementing Reddit UI clone

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

### References: 
[vuejs](https://vuejs.org/)
[tailwindcss](https://tailwindcss.com/)
[vue cli](https://github.com/tailwindlabs/tailwindcss-setup-examples/tree/master/examples/vue-cli)

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
 @Worawat101
