### ISSUE TITLE
Understanding Support Vector Machines

### ISSUE THREAD

**Issue by mykolkiprono** [section-engineering-education/engineering-education#2160]
# **Brief Summary:** 

Support vector machines are a set of supervised learning methods mainly used for classification problems though they can also be used for regression and outlier detection, they are very efficient in high dimensional spaces and are  memory-efficient since they only use  a subset of the training points in the decision function

 **Key Takeaways:** 
1. Understand what support vector machines are.
2. Appreciating what support vector machines are used for in machine learning.
3. Understand the mathematical formulation behind support vector machines.
4. Be able to solve a real-world problem using support vector machines.

### _References:_ 
N/A

**Comment by hectorkambow** [comment]
@mykolkiprono  
 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
