### ISSUE TITLE
Getting Started With CSS

### ISSUE THREAD

**Issue by LucyMaina12** [section-engineering-education/engineering-education#2161]
**Proposed Title of the Article**
Getting started with CSS

**Introduction**
CSS,an abbreviation for Cascading Style Sheets,is a style sheet language that is used in expressing the display of a document that is written in a Markup language for example HTML.Alongside HTML and JavaScript,CSS is a foundation technology in the world wide web.
Users will be able to carry out presentation of web pages and also adjust the presentation of web pages to different types of gadgets such as large screens and small screens using the different properties available in CSS.
The article proposed will aid the user in navigating the different properties available in CSS.

**Key Takeaways**
By reading this article,the user will be able to understand;

1. The meaning of CSS
2. The functions of CSS
3. CSS properties and how to use them
4. Benefits of CSS

**References**
N/A

**Comment by hectorkambow** [comment]
Seems like a helpful topic - we just want to make sure this does not overlap too much with other EngEd articles. 

This one [seems similar](https://www.section.io/engineering-education/what-is-css/)

But I believe we can go into much more detail with yours 👍  

Unique use cases are always a great option.

@LucyMaina12  - approved

**Comment by hectorkambow** [comment]
@LucyMaina12 just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?
