### ISSUE TITLE
Breaking Down Docker Containers vs. Virtual Machines (VMs)

### ISSUE THREAD

**Issue by nellyat** [section-engineering-education/engineering-education#2164]
### Proposed title of article
Breaking Down Docker Containers vs. Virtual Machines (VMs)

### Introduction paragraph (2-3 paragraphs):
Virtual Machines (VMs) and containers can help get the most out of available computer hardware and software resources. Containers are the new kids on the block, but VMs have been, and continue to be, tremendously popular in data centers of all sizes.

Virtual machines and containers are used to create isolated virtual environments for developing and testing applications or software. The question is how they differ.

This article examines the two concepts to help understand the difference between a container and a VM. It defines containers and virtual machines separately and side-by-side to see what makes one distinct from the other.

### Key takeaways: 

1. How VMs work
2. How containers work
3. Containers pros and cons
4. VMs pros and cons  
5. Which one to use: Containers vs. Virtual Machines

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic approved @nellyat
