### ISSUE TITLE
Sending WhatsApp Messages with server less Python applications using AWS Chalice

### ISSUE THREAD

**Issue by J-rayX** [section-engineering-education/engineering-education#2166]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
-  Sending WhatsApp Messages with serverless Python applications using AWS Chalice

### Introduction paragraph (2-3 paragraphs):
Serverless computing enables developers to build software and applications without dealing with servers. It abstracts server management from the responsibilities and worries of a developer. AWS Chalice is a light and fast serverless framework built by AWS. It is Python-based and uses the Amazon API Gateway and AWS Lambda.

WhatsApp is a free messaging platform used by over 2 billion people across the world. WhatsApp Messaging API allows developers to build applications that interact with users via WhatsApp. 
In this article, we will build and deploy an AWS Chalice application with DynamoDB. We will also learn how to send WhatsApp messages with he Chalice application.

### Key takeaways: 
- Create and deploy AWS Chalice applications 
- Setup DynamoDB for use in production
- Send WhatsApp message to users from serverless Python applications

### References: 
- [AWS Chalice Official Documentation](https://aws.github.io/chalice/main.html)
- [Twilio WhatsApp API Documentation](https://www.twilio.com/docs/whatsapp/tutorial)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@J-rayX only one article topic/pr approved at a time 👍
