### ISSUE TITLE
Building a simple game application with melonjs

### ISSUE THREAD

**Issue by yitzackRabin** [section-engineering-education/engineering-education#2167]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Game development is not something that needs to be restricted to people using Unity or Unreal Engine4. JavaScript game development has been a thing for quite some time providing us with simple a cool framework melonjs.
MelonJS is an open source HTML5 game engine that empowers developers and designers to focus on content.
The framework provides a collection of composable entities and support for a number of third-party tools. Giving you a powerful combination that can be used wholesale or piecemeal. This JavaScript Game Engine that is fully compatible with all major browsers (all the way from Chrome to Opera, going through Chrome for mobile as well as iOS Safari).
In this tutorial I will build a simple game using melonjs.

### Key takeaways: 
1. Understanding melonjs.
2. Understand the of 3rd party tools in melonjs.
3.  Utilizing APIs to make the game fancy and effective.
4. Building a game using melonjs.  
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool and helpful topic - approved @yitzackRabin

**Comment by hectorkambow** [comment]
@yitzackRabin just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?

**Comment by yitzackRabin** [comment]
@hectorkambow I'd wish my issue to be reopened. Had issues but resolved.
Thanks

**Comment by hectorkambow** [comment]
seems like a cool and helpful topic - approved @yitzackRabin

**Comment by hectorkambow** [comment]
@yitzackRabin 
Just pinging you on this topic form - as Im making some room in the topic queue.

No rush if you're still working on this one - if you need more time we can always re-open at a later date.
