### ISSUE TITLE
Convoluted Neural Networks in deep learning.

### ISSUE THREAD

**Issue by Bravinsimiyu** [section-engineering-education/engineering-education#2169]
**Proposed title of article**
Convoluted Neural Networks for Computer Vision

** Introduction paragraph (2-3 paragraphs)**
Convolutional Neural networks are multilayers neural networks used for image classification. This plays a big role in filtering and analyzing images to be used for object detection. Convoluted neural networks are used to produce powerful models that can be used for:  Image & Video recognition, Image Analysis & Classification, Media Recreation, Recommendation Systems, Natural Language Processing.
It shall basically cover:

- The basic structure of a convoluted neural network.
- The stages involved to produce a fully connected neural network.
- both the testing and training phases of the convoluted neural network.
- Making predictions with a given new data sets.

** Key takeaways: **

- The structure and architecture of the convoluted neural network.
- The steps from input to a fully connected network(input-convolutions-pooling-Flattening-output)
- The syntax code using python in the design and implementation of a convoluted neural network.
- Training and testing of data.
- Making new predictions.

**References: **

**Comment by hectorkambow** [comment]
Just want to make sure this article is not overlapping with this one @Bravinsimiyu 

https://www.section.io/engineering-education/basics-of-convolution-neural-networks/

**Comment by Bravinsimiyu** [comment]
No,
This has python code that will show how to build the network and train it to become fully connected.

**Comment by Bravinsimiyu** [comment]
At the end we will have a network that give prediction using a given set of inputs.
