### ISSUE TITLE
Getting Started with React Hooks 

### ISSUE THREAD

**Issue by Evans-Chelelgo** [section-engineering-education/engineering-education#2170]
**Proposed title of the article**

Understanding React JavaScript  Hooks 

**Introduction**

Before hooks (which came with in react v.16.8) function base components were basically just a render method. That meant if you were to use state, refs, or logic at LifeCycle events like componentDidmount(), componentDidUnmount(), or update you’d had to use the class syntax.
Now that we have react hooks, the number of react concepts we need to manoeuvre are greatly reduced when developing our applications. Examples of react hooks include; useState(), useEffect(), useContext() e.t.c

In this topic, we shall look at the following;

-The basic structure of react functional components.
- The comparing and contrasting between functional base components compared to class base components.
- How each hook aid in development of our applications.

**Key Takeaways**

1.Understanding why we prefer functional based components to class based components.
2.Understanding how to and when to use each  react hook.
3.Answering the question(do we still need to use class based components?).

**References**

-  React JavaScript Documentation.

**Comment by hectorkambow** [comment]
@Evans-Chelelgo just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?
