### ISSUE TITLE
Building a Java application with Jenkins in Docker

### ISSUE THREAD

**Issue by Kikiodazie** [section-engineering-education/engineering-education#2171]
### Proposed title of article
Building a Java application with Jenkins in Docker

### Introduction paragraph (2-3 paragraphs):
Over the past 3 years, the way we build software has undergone significant change. New technologies are being created in the range of months, and new ways of building and deploying applications are being launched. Thus also, new ways of improving teamwork performance, code coverage and deployment. 

We can run Jenkins in a container technology like Docker to automate the building, testing, and deploying of software which facilitates continuous integration and continuous delivery. Jenkins in Docker provides a way out of Jenkins configuration files clashes, issues running Jenkins on multiple platforms, etc., by reducing the task of running Jenkins to as little as two commands `docker pull` Jenkins base image and `docker run` a docker container instance.

In this tutorial, we will set up Jenkins in a Docker container. Also, we will build, dockerize and automate the testing and deployment of a Java application on Github with Jenkins in a Docker container.

### Key takeaways: 
1. Understand the basics of continuous integration and continuous delivery (**CI/CD**)
2. Learn how to setup and use Jenkins
3. Understand Docker-in-Docker, such as building Docker images in a Docker container.

### References: 
- https://www.linkedin.com/pulse/simple-guide-devops-cicd-jenkins-pipelines-docker-ramos-da-silva/

- https://www.youtube.com/watch?v=mszE-OCI2V4&list=PLVz2XdJiJQxwS0BZUHX34ocLTJtRGSQzN&index=5

- https://medium.com/swlh/quickstart-ci-with-jenkins-and-docker-in-docker-c3f7174ee9ff

- https://www.techrunnr.com/build-and-push-docker-image-to-docker-hub-using-jenkins/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @Kikiodazie 🚀
