### ISSUE TITLE
Getting started with graphical user interface(GUI) in Matlab

### ISSUE THREAD

**Issue by linetachieng** [section-engineering-education/engineering-education#2174]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
A graphical user interface is a pictorial interface that allows the user to use an application without understanding the language.
This is done by providing intuitive controls. The controls may include menus, pushbutton, and others that we will discuss later in this article. GUI is an event-driven program. This is because it acquires input at any given time and uses the call back functions to execute the program and give results.
In this article, we will be basically looking at the components that are used to construct the graphical user interface. We will also look at how to write the callback function of the components that make it possible for them to execute the controls. Matlab generates the codes for a GUI. This makes it easier to use since you only write the program for callback functions.  

### Key takeaways: 
- Components and their functions.
- Generation of the GUI functions.
- Writing the callbacks of components

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic @linetachieng  - approved
