### ISSUE TITLE
How to Containerize a Python Application

### ISSUE THREAD

**Issue by codeInn001** [section-engineering-education/engineering-education#2175]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to Dockerize a Python Application

### Introduction paragraph (2-3 paragraphs):
Docker takes away repetitive, mundane configuration tasks and is used throughout the development lifecycle for fast, easy and portable application development - desktop and cloud. Docker’s comprehensive end to end platform includes UIs, CLIs, APIs and security that are engineered to work together across the entire application delivery lifecycle.
Readet will learn how to use docker to containerize a python application using flask or any python framework
### Key takeaways: 
Reader will learn how to communicate with a flask endpoint outside a container.

Reader will get Python code running in a container by packing it as a Docker image and then run a container based on it.

After writing the Dockerfile and building the image from it,  Reader will learn how to run the container with Python service.

###References:
https://www.docker.com
https://www.python.org
https://www.flask.palletsprojects.com

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a very helpful topic - approved @codeInn001
