### ISSUE TITLE
Working with AWS DynamoDB and Node.js

### ISSUE THREAD

**Issue by manmusa100** [section-engineering-education/engineering-education#2176]
### Introduction paragraph (2-3 paragraphs):
DynamoDB is a solid and flexible NoSQL database service offered by Amazon Web Service. It can be used in handling non-relational databases workload. The main reasons why DynamoDB is getting popular are:
- Low management overhead
- Low latency
- Scales well
- It is easy to set up and has great migration tools

DynamoDB can be used for mobile apps, web apps, IoT devices, and gaming. Python has good support for DynamoDB. In this tutorial, we will use AWS Javascript SDK (Boto3) to perform CRUD (create, read, update, delete) operations on DynamoDB.

### Key takeaways: 
- Setting up AWS for Javascript SDK
- Configuring AWS JavaScript SDK
- DynamoDB CRUD Operations with Node.JS

### References: 
https://docs.aws.amazon.com/amazondynamodb/
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html

### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@manmusa100  to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
