### ISSUE TITLE
Integrating Twitter API in Rails Application

### ISSUE THREAD

**Issue by Njunu-sk** [section-engineering-education/engineering-education#2177]
### Proposed title of article
Integrating Twitter API in  Rails Application.

### Introduction paragraph (2-3 paragraphs):
Twitter is an American microblogging and social networking service on which users post and interact with tweets, it is good for business advertisement. Scheduled tweets allow users to create a tweet and schedule to alter date and also users can manage these Tweets, this allows users to create native tweets and plan their creative campaign in advanced. We will be able to demonstrate this is in a Rails application.

### Key takeaways: 
 -  How to create a Tweeter developer account.
 -  How to set up OATH and Omniauth
 -  CRUD basics in Rails
 -  Posting to Twitter App
 -  How to set up Sidekiq and run background jobs.

### References: 
 - https://developer.twitter.com/en/docs/twitter-ads-api/creatives/guides/scheduled-tweets-guide
 - https://rubygems.org/gems/sidekiq
 - https://guides.rubyonrails.org/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Njunu-sk 
 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 
 
 We can re-open this one when the 1st one is published.
