### ISSUE TITLE
Data Encryption and Decryption in Node.js using Crypto

### ISSUE THREAD

**Issue by JudyNduati** [section-engineering-education/engineering-education#2178]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Data Encryption and Decryption in Node.js using Crypto

### Introduction paragraph (2-3 paragraphs):
Cryptography and encryption are techniques used to secure and protect data stored in databases or being transferred over a network. Most data security operations are executed in the back-end of an application. Therefore we will use Node.js to implement encryption and decryption of data.
Node.js provides a built-in module called crypto to implement cryptographic operations on data.
In this article, we will learn basic cryptographic and Node.js techniques to secure data. Also, we will learn how to use Node.js 'crypto' module to perform encryption and decryption operations on data.  

### Key takeaways: 
1. Cryptography in Node.js
2. Node.js Crypto Module
3. Encrypting data in Node.js
4. Decrypting data in node.js

### References: 
https://nodejs.org/api/crypto.html
https://www.w3schools.com/nodejs/ref_crypto.asp

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
closing for now

**Comment by essy258** [comment]
@hectorkambow please reopen this issue

**Comment by JudyNduati** [comment]
Hello @hectorkambow, please reopen this issue.
