### ISSUE TITLE
Vue.js Vs React.js 

### ISSUE THREAD

**Issue by winlinda** [section-engineering-education/engineering-education#2182]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Vue.js Vs React.js

### Introduction paragraph (2-3 paragraphs):
Vue.js and React.js are both front-end JavaScript frameworks. React.js is the leading front-end framework. Each of these frameworks has its demerits and merits depending on its nature. 

Vue.js is a progressive framework that has more features than React. It is flexible in terms of its structure and easier in integrating with other tools. Vue.js recently uses typescript unlike where the first version was using JavaScript and typescript as optional. React.js is used for building UI with components. It allows for rendering and controlling content to the DOM. The React developers use JavaScript and JSX. The React.js developers use the architectural design of their choice. The difference between React and Vue.js lies in the way they are built, The tooling and the syntax. 

### Key takeaways: 
- What Vue.js entails
- What React.js entails
- Key similarities between Vue.js and React.js
- Advantages of using Vue.js and React.js as a front-end JavaScript Frameworks

### References:
N|A 

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
cool topic - approved @winlinda

**Comment by hectorkambow** [comment]
@winlinda just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?
