### ISSUE TITLE
Understanding the DNS

### ISSUE THREAD

**Issue by ionware** [section-engineering-education/engineering-education#2184]
### Introduction paragraph (2-3 paragraphs):
The domain name system is a fundamental part of the internet that every developer should understand. This article will help the reader understand how the internet maps name addresses (like section.io) into their corresponding IP addresses while explaining how to manage domain name records.

### Key takeaways: 
1. Familiarity with the terms used in DNS, such as A, AAAA, CNAME, MX, etc.
2. Configuring and managing records on a domain service.
3. Tools for querying a domain.

### References: 
- [Wikipedia](https://en.wikipedia.org/wiki/Domain_Name_System)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
cool topic - @ionware - approved

**Comment by ionware** [comment]
Thanks @hectorkambow

**Comment by hectorkambow** [comment]
@ionware just wanted to follow up on this topic as I'm clearing up the queue where possible? Can be re-opened when needed.
Of perhaps I missed the PR this is attached to?

**Comment by ionware** [comment]
Oh no, there hasn't been a PR @hectorkambow. I had issues with my health two days after this was approved.

I will definitely open this next week. Do I have to do anything other than to reopen it?

**Comment by ionware** [comment]
@hectorkambow, I would love to re-open this and work on the article. Kindly let me know if I can go ahead with it. 
Thanks.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
