### ISSUE TITLE
Making Network Requests in Node.js Using Axios

### ISSUE THREAD

**Issue by kayere** [section-engineering-education/engineering-education#2185]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Making Network Requests in Node.js Using Axios

### Introduction paragraph (2-3 paragraphs):
In the modern technological world, it is very rear to find stand-alone applications. Most applications depend on resources from other applications. These resources are made available through the use of API's. Servers are no exception. Though servers store their own relevant data, they sometimes need data from other servers. To access the data, servers need a way to communicate with the API(s) of the depended server(s). This is where Axios comes in.

Axios is a very popular JavaScript framework used to perform network requests. Axios works both on the browser and Node.js runtime. Axios is promise based but also allows us to use the modern async/await methods. This article goes through Axios and how to use it to make network requests in Node.js.

### Key takeaways:
1. Understand what axios is.
2. Understand the importance of making network requests.
3. Understand how to make network requests in node.js.

### References: 
N/A

### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@kayere 

 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 
 
 We can re-open this one when the 1st one is published.
