### ISSUE TITLE
Node.js Image Processing with Light-weight Image Processor (lwip)

### ISSUE THREAD

**Issue by manmusa100** [section-engineering-education/engineering-education#2187]
### Proposed title of article
Node.js Image Processing with Light-weight Image Processor (lwip)

### Introduction paragraph (2-3 paragraphs):
NodeJS Image Processing with Light-weight Image Processor (lwip)

Lwip is a Node.js package for image processing. it is a native module written in C++ thus fast. Lwip does not require external runtime dependencies. Currently, lwip supports three image formats; JPEG, PNG, and GIF. It is easy to use and provides comprehensive image processing capabilities. This tutorial will take you through lwip. You will learn how to process and manipulate images in Node.js.

Some of the common image processing operations supported by lwip are scale, mirror, rotate, crop, sharpen, opacify, among others. Lwip also supports batch image processing. To install lwip in Node.js using NPM, run the command below.

```
npm install lwip
```
### Key takeaways: 
- Introduction to image processing
- Installing Light-weight Image Processor (lwip) for NodeJS
- Image operations with lwip
	- Scale
	- Rotate
	- Crop
	- Blur
	- Sharpen
	- Flip
	- Border
	- Brightness
	- Hue

### References: 
https://github.com/EyalAr/lwip

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a cool topic - approved @manmusa100

**Comment by hectorkambow** [comment]
@manmusa100 
Just wanted to follow up on this Topic - before closing it to clear up the queue.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing thie topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
