### ISSUE TITLE
Understanding the Concept of Precision and Recall

### ISSUE THREAD

**Issue by Debagboola** [section-engineering-education/engineering-education#2188]
### Introduction paragraph (2-3 paragraphs): 
Certain concepts in machine learning are either too bogus for enthusiasts to demystify or too difficult to understand, but in the real sense, they are just terms that can be related with day-to-day with several examples around us. Apparently, one of such examples is Precision and another is Recall.

After you read this article, I will understand the concept of precision and recall and how to use it to evaluate machine learning models.

### Key takeaways:  
By the end of this tutorial, the reader will be able to:
1. Understand the concept of precision and recall
2.  Differentiate between the categories of Machine Learning and their uses
3. Understand the basics of classification and regression

### References: 
https://en.wikipedia.org/wiki/Precision_and_recall
https://en.wikipedia.org/wiki/Regression_analysis
http://kaggle.com/learn/

**Comment by hectorkambow** [comment]
seems like a helpful topic - @Debagboola  approved 
 lets be sure to include knowledge beyond what is cover in the official docs. 👍

**Comment by Debagboola** [comment]
@hectorkambow alright. I will begin work on the article immediately

**Comment by hectorkambow** [comment]
@Debagboola Just wanted to follow up on this Topic - before closing it to clear up the queue.

**Comment by Debagboola** [comment]
I am done with it. I just need to push it to the repo. Give me some time please. Thanks

**Comment by hectorkambow** [comment]
@Debagboola 
Just pinging you on this topic form - as Im making some room in the topic queue.

No rush if you're still working on this one - if you need more time we can always re-open at a later date - or when you are ready to push a PR - we can reopen to attach it to the PR. 👍
