### ISSUE TITLE
A Grasp of Linear Regression

### ISSUE THREAD

**Issue by wizardcalidad** [section-engineering-education/engineering-education#2189]
### Introduction paragraph(s):
Linear regression is one of the most fundamental algorithms in Machine Learning. It is a model used to show or predict the relationship between two variables, One dependent, also called the Target and the other being independent, which is called Feature(s) or Predictor(s). The two types of linear regression are Simple Linear Regression and Multiple Linear Regression.

Regression is an important tool for analyzing and modeling data. It operates by fitting a curve or a line to the data in order to differentiate with the minimum distance of the actual data points from the plotted curve or line.
Some of the usefulness of regression are:
1. It depicts a clear relationship between the target and the feature(s).
2. It shows the rate of influence of the features on the target.
3. It measures effect regardless of the scale of the variables.

 
### Key Takeaways: 
By the end of this tutorial, the reader will be able to:
- understand fully the concept of linear regression.
- create a simple dataset using pandas dataframe.
- build a linear regression model from scratch.
- calculate model coefficients and the application.

### References: 
- [What A Simple Linear Regression Model Is and How It Works](https://www.thebalancesmb.com/what-is-simple-linear-regression-2296697)
- [Multiple Linear Regression (MLR)](https://www.investopedia.com/terms/m/mlr.asp)

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 @wizardcalidad
