### ISSUE TITLE
How Sweet is Kubernetes?

### ISSUE THREAD

**Issue by wizardcalidad** [section-engineering-education/engineering-education#2190]
### Introduction paragraph(s):
Another Docker? Hell No! Kubernetes is rather a system that can work hand in hand with a docker, not one that depends on docker to work, docker is used for building and containerizing images right, those containers built, the function of Kubernetes is to manage them effectively, hence you can say Kubernetes is an orchestration tool. In proper definition: Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications. Kubernetes is meant to run across clusters while Docker runs on a single node. Kubernetes is a tool built by engineers at google before being made an open-source project. However, before going into learning Kubernetes at full strength, it is highly important to know the basic concepts involved. Let’s start with pods.

 
### Key Takeaways: 
By the end of this tutorial, the reader will be able to:
- understand the concept of Kubernetes.
- explain deployment as a configuration in Kubernetes.
- differentiate between pods and replica sets.
- analyze how config map works for external configuration.

### References: 
- [Kubernetes](https://kubernetes.io)
- [What is Kubernetes?](https://www.redhat.com/en/topics/containers/what-is-kubernetes)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved. 

One thing to note is that we like to stray away from readily available information through any of the official documentation.

**Comment by wizardcalidad** [comment]
Thanks for approving it, I will proceed to write it. When is the deadline for submission?

**Comment by hectorkambow** [comment]
https://github.com/section-engineering-education/engineering-education/pull/2389
