### ISSUE TITLE
Sentiment Analysis With Naive Bayes Algorithms

### ISSUE THREAD

**Issue by wizardcalidad** [section-engineering-education/engineering-education#2192]
### Introduction paragraph(s):
In the era of hate speech on social media, how do we easily analyze the true intent of people's conversations among themselves on the social web, where people can be anonymous and throw slander at others from the corners of their rooms. This project is targeted at getting the sentiments in people's tweets whether it is positive or negative.
First and foremost, we built a simple sentiment analysis model using Naive Bayes and discover which of its algorithms is best. Also, it is not a tutorial about which algorithm is best for sentiment analysis but rather, which of the Naive Bayes Algorithms is best. 
An IMDB dataset is used, it’s somewhat complicated data, a function was written to be able to read it into our notebooks. You can check out the function in the utils.py of our [Github repo](github.com/Semicolon-Tech/sentiment_analysis/blob/main/utils.py). 

[Code Base on Github](github.com/Semicolon-Tech/sentiment_analysis/)

 
### Key Takeaways: 
By the end of this tutorial, the reader will be able to:
- understand fully the concept of sentiment analysis.
- understand Bayes Algorithms and the types.
- carry out effective exploratory data analytics and feature engineering.
- build a functioning model of several Naive Bayes Algorithms.
- understand the concept of Natural Language Processing.
- evaluate effectively classification models.

### References: 
- [What is Sentiment Analysis? A Complete Guide for Beginners](https://www.freecodecamp.org/news/what-is-sentiment-analysis-a-complete-guide-to-for-beginners/)
- [Sentiment Analysis: What is it and how does it work?](https://awario.com/blog/sentiment-analysis/)
- [Word Vectorization (TFIDF/Word2Vec)](https://thedatasingh.medium.com/introduction-713b3d976323)

**Comment by hectorkambow** [comment]
@wizardcalidad 
 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
