### ISSUE TITLE
Creating a JavaScript Image Editor App with foto.js

### ISSUE THREAD

**Issue by evakeva** [section-engineering-education/engineering-education#2193]
### Proposed title of article
Creating a JavaScript Image Editor App with foto.js

### Introduction paragraph (2-3 paragraphs):
Foto.js is a powerful and simple to use JavaScript image manipulation library. It is light weight and compatible with modern browsers. The library can be used to incorporate image editing functionalities in an existing web app. One of the most common application of image processing and manipulation is when users are uploading a profile photo.

This tutorial will help you create a functional web-based image editing app. Some of the function in the app are crop, flip, rotate, colorize, grayscale, brightness, blur, among others.

### Key takeaways: 
- Introduction to foto.js
- Setting up foto.js
- Image editing operations with foto.js
- Creating a JavaScript Web-based Image Editor

### References: 
https://github.com/kousik19/foto.js

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved  @evakeva

**Comment by hectorkambow** [comment]
@evakeva 

Just closing this TOPIC to make room in the queue - it can be REOPENED whenever the PR is ready 👍
