### ISSUE TITLE
Introduction To Vite.js 2.0

### ISSUE THREAD

**Issue by Danmasanii** [section-engineering-education/engineering-education#2196]
# Introduction

Vite.js (a French word for "fast" or “quick”, pronounced /vit/) developed by the creator of Vue.js, Evan You. 

Vite.js 2.0 is a front-end build tool or framework for designing a rich, elegant and sleek User Interface, it is referred to as the next-generation framework for front-end tooling.

In this tutorial, we are going to install Vite 2.0 with all its dependencies and explore its advantages over other frameworks.

## Purpose of this article 

This tutorial targets beginner, intermediate and advanced level, front-end developers.
The purpose of this article is to help the reader fully understand how to install Vite.js, its advantages, and its relevance in front-end development.

## Prerequisites

It is assumed that the reader possesses the following:

- Basic understanding of JavaScript or TypeScript
- [Node.js](www.nodejs.org) version 12 or later
- Preferred text editor( Recommended: [VS Code](code.visualstudio.com) )

## Why Vite.js

Before we install Vite.js, let's have a look at the following advantages of Vite.js over other frameworks;

1. Instant server-side rendering.
   Contrary to other frameworks, Vite starts the server instantly, taking the dependencies that don't often change and rebuild them using esbuild (an extremely fast javascript bundler).

2. CSS preprocessor
Vite.js offers CSS preprocessor support for LESS and SASS.

3. Mono repo support
Vite.js provides support for multiple file rendering within the dist folder.

4. Lighting fast HMR
Regardless of the app size, Vite.js provides a fast Hot Module Replacement by re-bundling only the dependencies.
 
5. Rich features
Vite.js offers out of the box support for CSS, JSX, and JavaScript.

6. Optimized building
Vite.js uses Rollup in build mode with multiple pages and library mode support.

7. Fully typed APIs
Vite.js offers Typescript typing and server-side rendering for APIs.

8. Faster dependency pre-building
When talking about other bundlers like webpack, parcel or Rollup, the rebuilding process occurs on every save, which may cause a delay in bundling.

Among other advantages is experimental support for react, preact, Vue, and svelte.

## Installing Vite.js

In this tutorial, we are going to install Vite using npm and yarn.

## Steps

Open your terminal, navigate into the folder you want to install Vite.js, if you have one, else create a folder, navigate into the folder and run the following commands:

### - Installing using npm

```javascript
npm init @vitejs/app
```

Follow the prompts to continue:
- Project name:
- Select a framework:
- Select a variant:

After a successful installation, run the following commands:

```javascript 
cd project-folder-name
```
To install all the dependencies, run
```javascript
npm i
```
To start the development server run:
```javascript
npm run dev
```
To run the build server, execute this command:
```javascript
npm run build
```

### - Installing using yarn

```javascript
yarn create @vitejs/app
```

Follow the prompts to continue:
- Project name:
- Select a framework:
- Select a variant:

After a successful installation, run the following commands:

```javascript
cd project-folder-name
```

To install all the dependencies, run this command
 ```javascript
yarn i
```

To start the development server, run
```javascript
yarn run dev
```

To start the build server, run
```javascript
yarn run build
```

Now, let's have a look at the files in our project folder:

## Key words
- NPM: Node Package Manager
- HMR: Hot Module Replacement
- API: Application Programming Interface

## Conclusion

You can also read more about [Vite.js](https://www.vitejs.dev).

## Reference
- www.vitejs.dev
- www.stackoverflow.com

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved  @Danmasanii

**Comment by hectorkambow** [comment]
Just closing this TOPIC to make room in the queue - it can be REOPENED whenever the PR is ready 👍 
https://github.com/section-engineering-education/engineering-education/pull/2462
