### ISSUE TITLE
Building a speech-to-text app with javascript 

### ISSUE THREAD

**Issue by prince-joel** [section-engineering-education/engineering-education#2204]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Building a speech-to-text app with javascript.

### Introduction paragraph (2-3 paragraphs):
In this article, we will be learning how to build a speech-to-text app with javascript, using Web Speech Recognition API  and how it can be used.
Speech to text as it sounds is the conversion of spoken words to text. You might have been looking for ways to convert spoken words to text, or wondered if it's possible and how it can be done.

### Key takeaways: 
*The reader will learn about Web Speech Recognition API.
*The reader will learn how to make a request to the Web Speech Recognition API.
*The reader will be able to implement the Web Speech Recognition API in a web application.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@prince-joel 
 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍

**Comment by prince-joel** [comment]
@hectorkambow a topic issue for my previous article which is already merged was still open. I guess this was why it seemed I had two open issue

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved  @prince-joel 

Let be sure to check there is no overlap with exisitng EngEd aritcles if we haven't already

**Comment by hectorkambow** [comment]
@louisefindlay23 & @ahmadmardeni1  

If we could also please triple check that TOPIC forms are tied to the PRs (active) makes cleaning up the Topic queue much easier 👍  

Thank you

**Comment by ROYFORDWANYOIKE2001** [comment]
i can help him rewrite it using another language like Golang and  php

**Comment by prince-joel** [comment]
I’m interested can we discuss details on slack @  Prince Joel
