### ISSUE TITLE
Getting started with Django, Celery Docker configurations

### ISSUE THREAD

**Issue by njerikaren** [section-engineering-education/engineering-education#2205]
### Getting started with Django, Celery Docker configurations
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article's higher ranking.*

### Introduction paragraph (2-3 paragraphs):
[Celery](https://docs.celeryproject.org/en/stable/getting-started/introduction.html) is an asynchronous task queue/job queue based on distributed message passing. It is focused on real-time operation but supports scheduling as well.

In the article, I will be explaining how to configure Celery and a Django application in a Docker container. I will also explain how to schedule asynchronous tasks in Django using Celery.

### Key takeaways: 
1. Celery configuration in a Docker container.
2. Django project setup and configuration in Docker container.
3. How to schedule a task in Django with Celery.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @njerikaren 

I dont think they overlap at all - but may be good as a [reference ](https://re.sajari.com/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiY2xpY2siLCJkZXN0aW5hdGlvbiI6Imh0dHBzOi8vd3d3LnNlY3Rpb24uaW8vZW5naW5lZXJpbmctZWR1Y2F0aW9uL3doeS15b3Utc2hvdWxkLXVzZS1jZWxlcnktd2l0aC1yYWJiaXRtcS8iLCJ2YWxzIjp7ImNvbGxlY3Rpb24iOlsic2VjdGlvbi1pbyJdLCJjb21wYW55IjpbIjE1NjgyMzQxMTYwNzg2MTQ4NjgiXSwiZmllbGQiOlsidXJsIl0sInByb2plY3QiOlsiMTU2ODIzNDExNjA3ODYxNDg2OCJdLCJxLmlkIjpbInJ3NGZzNWJ4dXkzbGpnc24iXSwicS5zbCI6WyIxIl0sInEudWlkIjpbInJ3NGZzNWJ4dXkzbGpnc24wIl0sInZhbHVlIjpbImh0dHBzOi8vd3d3LnNlY3Rpb24uaW8vZW5naW5lZXJpbmctZWR1Y2F0aW9uL3doeS15b3Utc2hvdWxkLXVzZS1jZWxlcnktd2l0aC1yYWJiaXRtcS8iXX19.egZ4Brw21j7IqRgdd0daRDEUJSg65QXZwCEmRSF8_n0)for other readers going through your article. 
🤔
