### ISSUE TITLE
Containerizing Node.js Applications with Docker

### ISSUE THREAD

**Issue by samchy4k** [section-engineering-education/engineering-education#2208]
### Proposed title of article
Containerizing Node.js Applications with Docker

### Introduction paragraph (2-3 paragraphs):
Application containers are an inevitable and powerful tool in modern software development. Containers are lighter and resource-efficient. They also provide better version control, scaling capabilities, and enhance security. 

This tutorial will take you through containerizing Node.js applications with Docker. You will also learn the best practices for dockering your Node.js application.

### Key takeaways: 
- Creating sample Node.js App
- Setting up a Docker container
- Building Docker image
- Running and Testing

### References: 
https://docs.docker.com/language/nodejs/build-images/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @samchy4k

**Comment by hectorkambow** [comment]
@samchy4k 
Just closing this TOPIC to make room in the queue - it can be REOPENED whenever the PR is ready 👍
