### ISSUE TITLE
Deploying Docker Containers to Kubernetes Cluster

### ISSUE THREAD

**Issue by bastian-zab** [section-engineering-education/engineering-education#2210]
### Proposed title of article
Deploying Docker Containers to Kubernetes Cluster

### Introduction paragraph (2-3 paragraphs):
Docker is a tool designed to make it easier to create and deploy and run applications using containers such that a developer is allowed to package an application, all its libraries and dependencies as one during deployment.

While Docker runs on a single node, Kubernetes is meant to run across a cluster. It is more expensive and it's meant to coordinate clusters of nodes at a skinny production to enhance efficiency.

In this article I will explain a step-by-step procedure of deploying Docker containers to a Kubernetes cluster.

### Key takeaways: 
1. Building a Docker based app using flask
2. Using Load Balancers to expose containers with Kubernetes
3. Deploying a Docker container to Kubernetes cluster

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @bastian-zab
