### ISSUE TITLE
Docker Security: Best Practices to Secure a Docker Container

### ISSUE THREAD

**Issue by JudyNduati** [section-engineering-education/engineering-education#2211]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Docker Security: Best Practices to Secure a Docker Container

### Introduction paragraph (2-3 paragraphs):
Docker is a software platform that creates, deploys, and runs applications using containers. Learning how to secure Docker containers is of importance and is complex as well.
In this article, we'll offer an overview of docker container security best practices. Docker container security helps in preventing security breaches and attacks.

### Key takeaways: 
1. What is Docker Container Security
2. Best Practices to Secure Docker Containers
- Regularly update docker and host
- Run containers as a non-root user
- Configure resource quotas
- Set container resource limits
- Keep images clean
- Secure container registries
- Monitor API and network security

### References: 
https://docs.docker.com/engine/security/
https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@JudyNduati   to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍

I see you have one for node.js and one here -pick the one youd like to proceed with and we will review for approval.

**Comment by Pauline-Mwangi** [comment]
@hectorkambow I choose to proceed with docker security. You can close the node.js issue and will request for opening when the other is published

**Comment by JudyNduati** [comment]
@hectorkambow I choose to proceed with docker security. You can close the node.js issue and will request for opening when the other is published

**Comment by hectorkambow** [comment]
seems like a helpful topic - @JudyNduati  approved
