### ISSUE TITLE
Why is Docker so Popular

### ISSUE THREAD

**Issue by mosesreigns** [section-engineering-education/engineering-education#2212]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article's higher ranking.*
Why is Docker so popular? What makes it a big deal

### Introduction paragraph (2-3 paragraphs):
Docker is an open platform container technology for developers and sysadmins to build, ship, and run distributed applications, whether on laptops, data center VMs, or the cloud. Docker has been a game-changer since its release in 2013. It has become a massively popular containerization technology. In this article, we will discuss why Docker is a big deal.

### Key takeaways: 

What is Docker?
How popular is Docker?
Reasons Why is Docker so popular and why the rise of containers?
Advantages of Docker Containers
Which companies use Docker?

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a interesting topic - approved @mosesreigns 

please check that it does not overlap too much with other new incoming articles 👍
