### ISSUE TITLE
Predicting employee's salary using Polynomial regression in R

### ISSUE THREAD

**Issue by mbici** [section-engineering-education/engineering-education#2213]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials promptly. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

*NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article promptly from inception to publishing.)*

*NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.*

We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.

### Proposed title of the article
Predicting employee's salary using Polynomial regression in R

### Introduction paragraph (2-3 paragraphs):
Polynomial regression is a modeling algorithm that is used to model the relationship between the dependent variable (y) and the independent variable (x) as an nth polynomial. Since it's an nth polynomial, this algorithm is suitable for modeling a non-linear relationship between two variables. As most real-world problems are non-linear, this algorithm wide usage in the world of data science.  Some of its applications are, prediction of a salary of an employee in a company, the prediction of a spread of a pandemic in a population, and many others.

In the article, we will learn the intuition behind a polynomial regression, and implement a polynomial regression model using a salary data sample in R. Finally, we shall learn how we can use our model to predict the salary of a certain employee depending on their level and years of experience in the industry.

### Key takeaways: 
1. Learner will have a clear understanding of the intuition behind the polynomial regression.
2. Learner will know how to implement a polynomial regression model using R.
3. Learner will know how to use an implemented model and perform prediction of the continuous variable ( Salary).
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@mbici 
My apologies - your TOPIC form got lost in the sea of pages .

PLEASE do not hesitate to reach out via a DM on SLACK for a quicker response. 

Topic @mbici approved

**Comment by hectorkambow** [comment]
@mbici 

just wanted to follow up on this topic as I'm clearing up the queue where possible?
