### ISSUE TITLE
Turn your Python Script into a ‘Real’ Program with Docker

### ISSUE THREAD

**Issue by patrickchisembe** [section-engineering-education/engineering-education#2215]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
No worries, I’m sure the developer was kind enough to give you an installation script to get you up and running. So you run their script, and the next thing you know your shell is a massacre of error logs. “Well it worked on my machine”, is what the developer will normally retort when you ask for help.
Docker solves this issue by making Dockerized applications almost trivially portable. This tutorial will show you how to quickly Dockerize your Python applications so that you can easily share them with anyone who has Docker.
In particular, we will be focused on scripts that are intended to be run as a background process.

### Key takeaways: 
1. Understanding Docker
2. Learning how to share docker files
3. Getting the importance of dockerization  

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic @patrickchisembe approved

**Comment by yitzackRabin** [comment]
@hectorkambow  Thanks

**Comment by hectorkambow** [comment]
@patrickchisembe 
Just closing this TOPIC to make room in the queue - it can be REOPENED whenever the PR is ready 👍
