### ISSUE TITLE
Fundamentals of container security

### ISSUE THREAD

**Issue by calebroHQ** [section-engineering-education/engineering-education#2216]
### Brief Summary

The purpose of this article is to highlight the security issues and how developers and other key players can mitigate them during the deployment and maintenance of container environments.

### Introduction

To understand security issues facing container technology we first have to understand what containers are. Containers are executable units of application that are packaged, along with their libraries and dependencies needed to run the application.

Containers allow developers to deploy and maintain applications seamlessly across different environments.

Different components of a container have different security risks associated with them. We are going to dive into images, registry, and Host Operating systems vulnerabilities.

### Key takeaways

1. What components of containers.

2. What are the vulnerabilities that are associated with the core components of containers.

3. How to mitigate these security risks.

### Reference

Microsoft Azure introduction to containers. https://azure.microsoft.com/en-us/overview/what-is-a-container/#beyond-containers

**Comment by hectorkambow** [comment]
@calebroHQ   to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍

**Comment by hectorkambow** [comment]
> re-opend @calebroHQ

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @calebroHQ 

Please be sure to include information beyond what is included in the documentations or other basic blogs.

Also be sure to go through the submitted topics to avoid overlap. 👍

**Comment by calebroHQ** [comment]
thanks, @hectorkambow. I'll be sure to do that.
