### ISSUE TITLE
 Understanding Worker Threads in NodeJs

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#2217]
### Proposed title of article
 Understanding Worker Threads in NodeJs

### Introduction paragraph (2-3 paragraphs):
Workers threads in Node.js are a way to offload CPU-intensive tasks away from the single-threaded process which Node gives you.
Firstly, we need to understand why you can't put a CPU-intensive task in the main process of your Node.js instance. This is because Node.js is single-threaded and you only get one process out of the box, A process is a global object that has the information of what is being executed at the time.  

Before worker threads, there were multiple ways to perform CPU-intensive applications using Node.js. Some of those were,
- Using child_process module and run CPU-intensive code in a child process.
- Using cluster module to run multiple CPU-intensive operations in multiple processes.
- Using a third-party module such as Microsoft’s Napa.js.
But none of these solutions was widely adopted because of performance limitations, additionally-introduced complexity, lack of adoption, instability, or lack of documentation.

Although worker_threads is an elegant solution for JavaScript’s concurrency problem, it does not introduce multi-threading language features to JavaScript itself. Instead, worker_threads implementation provides concurrency by allowing applications to use multiple isolated JavaScript workers where the communication between workers and the parent worker is provided by Node. 

### Key takeaways: 
1.How Worker Threads Work
2.Using Worker Threads(Creating and Running New Workers)
3.Communication Between Parent and Worker Threads
4.The Better Way of Handling Workers
5.Sharing Memory Between Parent and Worker
6.Worker Thread Pooling

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved  @jumamiller 

Let be sure to check there is no overlap with existing EngEd articles if we haven't already

**Comment by hectorkambow** [comment]
merged :
https://github.com/section-engineering-education/engineering-education/pull/2119
