### ISSUE TITLE
Understanding Quality of Service (QoS)

### ISSUE THREAD

**Issue by Su-sid** [section-engineering-education/engineering-education#2218]
### Proposed title of the article
Understanding Quality of Service (QoS)

### Introduction paragraph (2-3 paragraphs):

People optimize their networks so that these networks can perform at their full potential. QoS is an essential set of technologies in networking that allow you to optimize your network, allowing it to run at its full potential. Having an optimized network ensures that intensive applications run efficiently due to the availability of adequate network resources.

### Key takeaways: 

1. The reader will gain an understanding of what is Quality of Service 

2. How QoS utilizes traffic marking, queuing, and the resource reservation protocol to guarantee the optimal performance of critical applications on a network.

3. The importance of QoS on a network. 

4.  The best scenarios to use QoS

### References: 
- https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc787218(v=ws.10)?redirectedfrom=MSDN
- https://www.tutorialspoint.com/what-is-rsvp-resource-reservation-protocol

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍

We can re-open this one when the 1st one is published. @Su-sid

**Comment by Su-sid** [comment]
I have immediately closed my previous issue.
