### ISSUE TITLE
Beginners' Guide to Lottie Animations in Android Using Kotlin

### ISSUE THREAD

**Issue by carolinemusyoka** [section-engineering-education/engineering-education#2220]
### Proposed title of article
Beginners' Guide to Lottie Animations in Android Using Kotlin

### Introduction paragraph (2-3 paragraphs):
Lottie is an open-sourced mobile library developed by Airbnb. It basically renders after-effect animations in real-time. Lottie animations help in providing a simpler way to use animations in mobile. As an android developer, you might have used animations in your app, but it turned out to be cumbersome. With Lottie animations, you will be able to convey more with less. 

### Key takeaways: 
- An introduction to Lottie Animations
- Why use Lottie Animations in Android
- How to integrate Lottie Animations into your app using Kotlin

### References: 

https://lottiefiles.com/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved  @carolinemusyoka 

Let be sure to check there is no overlap with existing EngEd articles if we haven't already
