### ISSUE TITLE
Exoplanets discovery in deep space using Machine Learning

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-engineering-education/engineering-education#2222]
### Introduction paragraph (2-3 paragraphs):
All of the planets in our solar system orbit around the Sun. Planets that orbit around other stars are called exoplanets.
In 2009, NASA launched a spacecraft called Kepler to look for exoplanets. Kepler looked for planets in a wide range of sizes and orbits. And these planets orbited around stars that varied in size and temperature.

Some of the planets discovered by Kepler are rocky planets that are at a very special distance from their star. This sweet spot is called the habitable zone, where life might be possible.

Kepler detected exoplanets using something called the transit method. When a planet passes in front of its star, it’s called a transit.

![](https://media.giphy.com/media/l0MYN99HMzGaEhGrm/giphy.gif)

As the planet transits in front of the star, it blocks out a little bit of the star's light. That means a star will look a little less bright when the planet passes in front of it.

![](https://media.giphy.com/media/3o6Ei3lMtg8W3pMORO/giphy.gif)

Astronomers can observe how the brightness of the star changes during a transit. This can help them figure out the size of the planet.
By studying the time between transits, astronomers can also find out how far away the planet is from its star. This tells us something about the planet’s temperature. If a planet is just the right temperature, it could contain liquid water—an important ingredient for life.

### Key takeaways: 
In this tutorial, I will guide the readers into a deep learning adventure into space. We will build a machine learning model with Python (CNN) to predict the existence of an exoplanet based on light intensity using the Kepler space telescope dataset.

This tutorial will be 2 parts:
1. The first part will discuss the transit method and explain it in details, then build a part of our machine learning model.
2. In the second part, we will continue to build our machine learning model.

### References: 
N/A for now. But I will search for good materials to reference in my article.

**Comment by hectorkambow** [comment]
seems very cool - just closing for now - we can reopen once the other is published.
