### ISSUE TITLE
Email Password Authentication in React Native Application using Firebase

### ISSUE THREAD

**Issue by zolomohan** [section-engineering-education/engineering-education#2223]
### Proposed title of the article

Email Password Authentication in React Native Application using Firebase

### Introduction paragraph(s):
In this tutorial will learn how to authenticate users with their email and password using Firebase's authentication module in a Non-Expo React Native application.

Firebase is a platform developed by Google for creating mobile and web applications. It was originally an independent company founded in 2011. In 2014, Google acquired the platform and it is now their flagship offering for app development.

### Key takeaways

- Set up Firebase Project for Email Password Authentication.
- Add Login/Create account screen.
- Use the Firebase Auth module and authenticate users.
- Logout from the authenticated screen.

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved  @zolomohan
