### ISSUE TITLE
Routing with Angular 11 Router: Full-Tutorial & App by Example

### ISSUE THREAD

**Issue by owinowendy** [section-engineering-education/engineering-education#2224]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Routing with Angular 11 Router: Full-Tutorial & App by Example

### Introduction paragraph (2-3 paragraphs):
Routing is a mechanism in modern web or mobile applications, be it single-page applications, progressive web applications, or mobile apps. A user can fetch content in the view based on the component a user wants to navigate. It can also be directly done by using the route URL in the browsers.

In this tutorial, we’ll learn about the Angular Router by building an Angular 11 example and will teach you everything you need to start using routing to build Single Page Applications with navigation, guards, resolvers, and animations.

We'll learn how to use multiple outlets, redirect users from the empty path, use wild-card paths to implement 404 error pages and lazy load modules using the loadChildren() method.

### Key takeaways: 
1.Configuring Routes & RouterModule
2.Angular Route Matching Strategies
3.Wildcard Route in Angular
4.Angular Route Parameters
5.Angular Router Outlet & Navigation Directives

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a very helpful topic - approved  @owinowendy 

Let be sure to check there is no overlap with existing EngEd articles if we haven't already
