### ISSUE TITLE
How to Build Authentication Api with Jwt Token in Nodejs

### ISSUE THREAD

**Issue by Olanetsoft** [section-engineering-education/engineering-education#2226]
### Proposed title of the article
How to Build Open Authentication Api with Jwt Token and Nodejs

### Introduction
Introduction paragraph (2-3 paragraphs):

JSON Web Token (JWT) is an open standard (RFC 7519) that specifies a compact and self-contained method for securely transmitting information as a JSON object between two parties. Since it is digitally signed, this information can be checked and trusted. JWTs can be signed with a password (using the HMAC algorithm) or with an RSA or ECDSA public/private key pair.

Node.js is a cross-platform runtime environment for building server-side and networking applications that is open-source. Node.js programs are written in JavaScript and run on OS X, Microsoft Windows, and Linux using the Node.js runtime.

### Key takeaways:
By the end of this tutorial, the reader will:

- Learn JWT Basics and how to use them.
- Understand how JWT works behind the scene in NodeJS for Authentication
- Develop an API using JWT Token for Authentication in NodeJS.

### References:
Templates to use as guides
https://jwt.io/
https://nodejs.org/en/

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved  @Olanetsoft 

Let be sure to check there is no overlap with existing EngEd articles if we haven't already
