### ISSUE TITLE
Google Drive API in Nodejs

### ISSUE THREAD

**Issue by paulromans** [section-engineering-education/engineering-education#2228]
### Proposed title of article
Google Drive-API in NodeJs

### Introduction paragraph (2-3 paragraphs):
Google Drive API was developed by Google to enable developers create applications that leverage Google Drive cloud storage. 

Through the API you can develop an application that seamlessly integrate with Google Drive for data storage and sharing. Among the functionalities provided by the API is downloading and uploading files to Google Drive, sharing of files and folders as well as searching for stored files. 

In the article we will explain a step-by-step process of integrating a NodeJs application with Google Drive API to enable uploading, downloading and sharing of files.

### Key takeaways: 
1. What is Google Drive API
2. Integrating the API with NodeJs
3. Uploading, Downloading Files using Google Drive API

### References: 
https://developers.google.com/drive/api/v3/about-sdk

**Comment by hectorkambow** [comment]
@paulromans seems like a helpful topic - approved  

Let be sure to check there is no overlap with existing EngEd articles if we haven't already
