### ISSUE TITLE
Understanding Inversion of Control Principle—Android Kotlin

### ISSUE THREAD

**Issue by Lamouresparus** [section-engineering-education/engineering-education#2230]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Understanding Inversion of Control Principle—Android Kotlin

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

Inversion of Control is a software design principle that is used in object-oriented programming to reverse control, to achieve loose coupling of classes. Coupling here is a measure of how closely connected software modules are on one another, while control refers to any other additional responsibility a class has apart from its main responsibility. Remember the S in SOLID principles of object-oriented design? Let me help you: Singularity of Purpose—that’s what IoC is about. Loose coupling in software engineering is often a sign of testable, well-structured, maintainable, and readable software.

Imagine this: suppose you have a bakery that specializes in making egg rolls. What is an egg roll without an egg? Right. So eggs are essential in the making of egg rolls. Why egg rolls you may ask? Well, you could call it nepotism. Applying the IoC principle in your bakery:  rather than having poultry and involving yourself with all the poultry-related stuff, you order the eggs and get them delivered to you. You don't have to worry about the chicks not dying and whether or not you are using the right feed for your chicks and all. With this new design, you can focus on baking egg rolls which results in a more effective baking process. This is the big idea behind IoC: separating concerns.

In this article you are going to learn the basics of inversion of control in Kotlin, why it is important in great software design, how it is connected to dependency injection and the strategy pattern, and get to see just how IoC makes your code less complex, flexible, and easily testable.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

- Understand the concept of loose coupling.
- Understand the S in SOLID principles.
- Understand why objects need to be loose coupled.
- Differentiate between Design pattern and Design Principles.
- Understand the overall Idea of Dependency Injection and Strategy pattern.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved  

Let be sure to check there is no overlap with existing EngEd articles if we haven't already @Lamouresparus

**Comment by hectorkambow** [comment]
@Lamouresparus 
Just closing this TOPIC to make room in the queue - it can be REOPENED whenever the PR is ready 👍
