### ISSUE TITLE
Using Google Sheets API in Nodejs

### ISSUE THREAD

**Issue by mia-roberts** [section-engineering-education/engineering-education#2236]
### Proposed title of article
Using Google Sheets API in Nodejs

### Introduction paragraph (2-3 paragraphs):
Google sheet is an online-based spreadsheet that enables one to create and format spreadsheets while working with other people. It allows multiple users to collaboratively work on a document in real-time. 

Google developed Sheets API to achieve similar functions in various programming languages and frameworks including Nodejs. Among other functionalities, Sheets API allows one to create, write and read values from a spreadsheet and update the spreadsheets. 

This article aims at giving readers an understanding of how Google sheets API works and how to implement it in a Nodejs application.

### Key takeaways: 
1. What is Sheets API?
2. Integrating Sheets API in Nodejs 
3. Creating spreadsheets using Sheets API
4. Manipulating spreadsheets

### References: 
https://developers.google.com/sheets/api/quickstart/nodejs

**Comment by hectorkambow** [comment]
@mia-roberts seems like a helpful topic - approved  

Let be sure to check there is no overlap with existing EngEd articles if we haven't already
