### ISSUE TITLE
Building a real-time sign language detection application using tensorflow.js and python

### ISSUE THREAD

**Issue by wilkistermumbi** [section-engineering-education/engineering-education#2239]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Building a real-time sign language detection application using tensorflow.js and python

### Introduction paragraph (2-3 paragraphs):

Language barriers are very much still a real thing. We can take baby steps to help close that. Speech to text and translators have made it a heap easier. But what about for those that maybe don't speak or can't hear? What about them? 
Well...we can begin to use Tensorflow Object Detection and Python to help close that gap. This article helps us learn how to take the first steps to doing just that.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this article, the reader should be able to:
1. Label sign language images for object detection
2. Train tensorflow for sign language detection
3. Detect different sign languages in real-time

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@wilkistermumbi seems like a helpful topic - approved  

Let be sure to check there is no overlap with existing EngEd articles if we haven't already
