### ISSUE TITLE
Getting Started With MariaDB Using Docker and Node.js

### ISSUE THREAD

**Issue by ephnjor2021** [section-engineering-education/engineering-education#2244]
### Proposed title of article
Getting Started With MariaDB Using Docker and Node.js

### Introduction:
MariaDB has become a popular database solution for developers over the years. The reason is it is open-source and relational thus has a huge community of developers using it to develop their application's databases. MariaDB corporation provides superior quality, enterprise-grade products that thrusts MariaDB into the forefront of database vendors.
In this guide, I will provide a walkthrough to provide a launchpad for the developer to get started using MariaDB with Docker and Node.js.

### Key takeaways: 
In this guide the reader will be able to:
- use a MariaDB Docker container
- create a MariaDB database
- connect to MariaDB with Node.js

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @ephnjor2021 

Please be sure to include information beyond what is included in the documentations or other basic blogs.

Also be sure to go through the submitted topics to avoid overlap. 👍
