### ISSUE TITLE
Using KubeMQ Bridges to communicate between Edge and Cloud Clusters

### ISSUE THREAD

**Issue by ogoti-lilian** [section-engineering-education/engineering-education#2245]
### Proposed title of article
Using KubeMQ Bridges to communicate between Edge and Cloud Clusters

### Introduction:
For years companies have been migrating to the cloud. With the rise of internet-connected devices, it is normal to rely on cloud-based services for the majority of applications today. 

However, the rise of edge computing has shown that there is also a need for hyper-local, distributed computing which can offer latencies and resilience that cloud ca not match. With these benefits come ever-increasing complexity both in terms of individual application development as well as overall infrastructure management.

In this article, I will take a look at the unique benefits and challenges of edge computing, as well as how a lightweight, Kubernetes-based messaging queue can meet those challenges.

### Key takeaways: 
In this article, the reader will be able to:
- understand what is meant by edge computing, the benefits it offers, and the challenges it faces
- understand how messaging can address the complexity and limitations of edge computing
- implement a lightweight bridge between multiple kubeMQ clusters installations
### References: 
N/A

**Comment by hectorkambow** [comment]
@ogoti-lilian seems like a helpful topic - approved  

Let be sure to check there is no overlap with existing EngEd articles if we haven't already

**Comment by ogoti-lilian** [comment]
@hectorkambow I will reopen the issue at a later date once I have more content on the topic.
