### ISSUE TITLE
Comparing Serverless computing vs containers

### ISSUE THREAD

**Issue by jaykip** [section-engineering-education/engineering-education#2247]
### Proposed title of article
Comparing Serverless computing vs containers
### Introduction paragraph (2-3 paragraphs):
Both serverless computing and containers enable developers to build applications with far less overhead and more flexibility than applications hosted on traditional servers or virtual machines. Which style of architecture a developer should use depends on the needs of the application, but serverless applications are more scalable and usually more cost-effective.

Although the features of containers and serverless architectures overlap in some respects, they are not interchangeable technologies. Containers work better for some use cases, while in others, serverless is what you need.

This article will discuss how serverless computing and containers differ from each other and when to use what?

### Key takeaways: 

1. Why we need Serverless computing 
2. Why we need Containers 
3. Similarities 
4. Differences in terms of Scalability, Time of deployment, Cost, Longevity Limitations, Latency & Startup Time, etc. 
5. When to Use Serverless and When to Use Containers

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @jaykip 

Please be sure to include information beyond what is included in the documentations or other basic blogs.

Also be sure to go through the submitted topics to avoid overlap. 👍
