### ISSUE TITLE
Using Formidable for parsing form data in Node.js application.

### ISSUE THREAD

**Issue by sardug10** [section-engineering-education/engineering-education#2248]
### Proposed title of the article
**Using Formidable for parsing form data**

### Introduction paragraph (2-3 paragraphs):
Formidable is an npm package that has been around the longest, with version 1.0 being released in 2011. This package is used to parse multipart form data, especially file uploads. A few months ago, I wrote an article about Multer which is also used for almost the same purpose. 
So, this article will also be a step-by-step tutorial on how to upload any kind of files from client-side to server-side **while focusing on different steps and strategies we can make in Formidable which makes it more famous than Multer.**

### Key takeaways: 
1. How to use Formidable to parse form data.
2. How to use different configuration methods that come with Formidable.
3. Difference between Multer and Formidable.

### References: 
N/A

### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@sardug10 seems like a helpful topic - approved

Let be sure to check there is no overlap with existing EngEd articles if we haven't already
