### ISSUE TITLE
introduction to GUI using tkinter with python

### ISSUE THREAD

**Issue by majiezra** [section-engineering-education/engineering-education#2259]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article

introduction to GUI using tkinter with python.

### Introduction paragraph (2-3 paragraphs):
The term GUI (graphic user interface) refers to a desktop application that allows you to communicate with computers and improves the experience of giving commands (command-line input) to your code. They are used in desktop computers, notebook computers, and other electronic devices to perform a variety of tasks.
Tkinter is a platform that is included with Python.
### Key takeaways: 
In this tutorial, programmers will learn and know
- What are Widgets?
- How to create a simple graphic user interface
- Inserting of menu keys and background colour to make it more user friendly.
### References: 
python GUI programming with tkinter by Alan D. Moore.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved - we just want to ensure that this tutorial goes beyond the already created blog articles and tutorials out there - and beyond the ones references. We want to create unique articles that solve problem not already discussed our solved somewhere else 👍 @majiezra 

Let be sure to check there is no overlap with existing EngEd articles if we haven't already

**Comment by pkalynan** [comment]
@hectorkambow 
Sorry to intrude, I had written an article about [Python Tkinter](https://medium.com/analytics-vidhya/python-tkinter-as-a-java-application-36536176fe83). You may proceed with the publication, as I am okay with student learners receiving rewards for their content. :-)

**Comment by majiezra** [comment]
Okay  @pkalynan. Thank you very much I'll ensure your link on python tkinter gets added to the reference.😊
