### ISSUE TITLE
Integrating Instagram Graph API on a Node.js API

### ISSUE THREAD

**Issue by Roba-W** [section-engineering-education/engineering-education#2261]
### Proposed title of article
Integrating Instagram Graph API on a Node.js API

### Introduction paragraph (2-3 paragraphs):
Launched in 2018, Instagram Graph API is a product for businesses and creators using Instagram. The API is used to get and publish media, manage and reply to comments on your media, identify media where you have been mentioned by other Instagram users, find hash tagged media, and get basic metadata and metrics about other Instagram businesses and creators.

In this article, we will walk through the process of integrating the API to a Node.js API using GraphQL and TypeScript.

### Key takeaways: 
- Learn how to create a Facebook developer account and an Instagram app.
- Learn how to set up GraphQL and TypeScript.
- Learn how to consume the Instagram Graph API from a Node.js GraphQL API

### References: 
- https://developers.facebook.com/docs/instagram-api/

**Comment by hectorkambow** [comment]
@Roba-W seems like a helpful topic - approved

Let be sure to check there is no overlap with existing EngEd articles if we haven't already

**Comment by hectorkambow** [comment]
Just closing this TOPIC to make room in the queue - it can be REOPENED whenever the PR is ready 👍 @Roba-W
