### ISSUE TITLE
Files and Exceptions in Python

### ISSUE THREAD

**Issue by duncandegwa** [section-engineering-education/engineering-education#2263]
### Proposed title of article

Files and Exceptions in Python

### Introduction paragraph (2-3 paragraphs):
Working with files and saving data makes your Python programs easier for people to use. Users can run your program, choose what data to enter and when to enter it, do some work, and then close the program and pick up where they left off later.

Exceptions are special objects Python creates to manage errors that arise while a program is running. Understanding exceptions will help you deal with situations in which files don’t exist and deal with other problems that can cause your programs to crash. Exceptions are handled with try - except blocks. When you use try - except blocks, your programs will continue running even if things start to go wrong. Instead of trace-backs, which can be confusing for users to read, users will see friendly error messages that you write.

In this article we will learn to work with files and how to handle errors so your Python programs don’t crash when they encounter unexpected situations.
### Key takeaways
In this article,the reader should be able to:

   1.Read from a file
   2.Work with a File’s Contents
   3.Write to a File
   4.Handle the ZeroDivisionError Exception
    5.Handle the FileNotFoundError Exception

### References
N/A

**Comment by duncandegwa** [comment]
Hi @hectorkambow the other article is already published please give me a signal on this
Thank you

**Comment by hectorkambow** [comment]
Seems like a helpful topic - perhaps we could include a real use case (if it makes sense). 

either way - @duncandegwa - approved 👍 🚀 

Thank you for you patience with publishing as we worked out our Repo changes.
