### ISSUE TITLE
How to Nginx Reverse Proxy with Docker Compose

### ISSUE THREAD

**Issue by ephraa** [section-engineering-education/engineering-education#2265]
### Proposed title of article
How to Nginx Reverse Proxy with Docker Compose

### Introduction:
When developing a web application, a normal way to call the application from your local machine is through http://localhost:x ports. This means that you are required to expose several ports to access different modules of the application.

In this guide, we will go through the method of using a reverse proxy to call an application and the benefits of using it.

### Key takeaways: 
The learner will be able to:
- know the reason why we use a reverse proxy and the benefits it offers
- create a docker container
- create WordPress-MySQL server with Nginx in one service to implement reverse proxy and test the web app

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved @ephraa 

Please be sure to include information beyond what is included in the documentations or other basic blogs.

**Comment by ephraa** [comment]
@hectorkambow I have to close this topic to draw more content on the same and hopefully reopen later
