### ISSUE TITLE
Core Concepts To Master As Django Developer

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#2269]
##Introduction

Being a Django Developer with years of experiences,  I have come to share my insights on "Core Concepts To Master As Django Developer".
Yeah, Django!! If you are familiar with it, you should know much about it. Join me in the journey of exploring the world of Django.  What is DJANGO? 
Anyway, "Django is a free, open source web framework written in the Python programming language".  A “web framework” is software that abstracts away many of the common challenges related to building a website, such as connecting to a database, handling security, user accounts and much more. Django uses a python  package called pip and this come in handy having installed Python. We dive deeper into this later.

## Key takeaways: 
At the end of this article, you should be familiar with the key areas of Django and I bet it with you, that you would want to proceed in learning the framework if you have not:

1. How to set up Django project as a developer,
2. Master the concepts required in  development of Django project,
3. Be confident to take on the journey of Django by  using knowledge gained here,
4. And finally apply for Django jobs out of the tons of opportunities out there.
 

### References: 
[Django official Website](https://docs.djangoproject.com/en/3.2/contents/)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs.  - approved

@Horlawhumy-dev

**Comment by hectorkambow** [comment]
merged
