### ISSUE TITLE
Getting Started With Custom Pipes in Angular 11

### ISSUE THREAD

**Issue by bhanjibrilliant** [section-engineering-education/engineering-education#2270]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting Started With Custom Pipes in Angular 11

### Introduction paragraph (2-3 paragraphs):
Angular pipes are used for transforming input data to desired output in the view template. Angular provides various built-in pipes like DatePipe,UppercasePipe,CurrencyPipe etc.
Though there are many Angular built-in pipes for data transformation, Angular framework also gives you an option to create a custom pipe to cater to custom data transformation.
Built-in pipes sometimes may not be sufficient for our use case. We need to create our own custom pipes to meet requirements.

In this tutorial, I am going to discuss how to create Angular Custom Pipe with an example.
At the end of this tutorial, you will understand how to create custom pipe and when do we need to create custom pipes and how to use it in Angular Application.

### Key takeaways: 
1.Defining custom pipe class
2.Declaring pipe in the AppModule
3. Implementing pipe in the view template

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍

We can re-open this one when the other one is published.
