### ISSUE TITLE
Network Management Using CDP and LLDP Layer 2 Protocols

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#2273]
### Proposed title of article
Understanding how to manage networks using Layer 2 Protocols (CDP and LLDP)

### Introduction paragraph (2-3 paragraphs):
One of the basic steps in network management and troubleshooting is to ensure the network connectivity between the devices is perfect and up running. To achieve this, one must understand how devices are interconnected between the network topology and have a proper documentation of the network.
To do this, in this article will show the reader how to use the Layer 2 discovery protocols to help the network administrator gather hardware and protocol information about neighbouring devices, which is useful information for troubleshooting, management and 
 Documenting the network. It will also equip the reader with the knowledge of how to configure the protocols on the network devices.
### Key takeaways: 
The reader should be able to:
1. Understand the Layer 2 protocols, both Cisco Discovery Protocol (CDP) and Link Layer Discovery Protocol (LLDP).
2. Be able to configure both the two protocols on networking devices.
3. Be able to troubleshoot and manage networks using the two protocols.

### References: 
N/A

### Templates to use as guides
N/A

**Comment by dentonya** [comment]
cc @hectorkambow

**Comment by dentonya** [comment]
cc @hectorkambow

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @dentonya
