### ISSUE TITLE
Using machine learning to translate brain signals to text

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#2276]
### Proposed title of article

Using machine learning to translate brain signals to text

### Introduction paragraph (2-3 paragraphs):

Brain–computer interfaces (BCIs) can restore communication to people who have lost the ability to move or speak. So far, a major focus of BCI research has been on restoring gross motor skills, such as reaching and grasping.
However, rapid sequences of highly complex behaviors, such as handwriting or touch typing, might enable faster rates of communication. But,can we use the brain's neural activities from people imagining handwriting to actually decode letters, words, and even sentences?

This article aims to answer that question.

As it appears,  there might be a way of solving this problem by using dimensionality reduction techniques and machine learning to decode neural signals and convert them into texts and words.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this article, a reader will be able to:

1. Be introduced to the subject and given a high level overview
2. Understand how the neural representation of handwriting is achieved
3. Understand how we can decode handwritten sentences and not just letters
4. Explain results from the experiments performed

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

[High-performance brain-to-text communication via handwriting](https://www.nature.com/articles/s41586-021-03506-2)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @Bayler
