### ISSUE TITLE
Compile your Node.js application into a .exe file

### ISSUE THREAD

**Issue by RisoriTofa** [section-engineering-education/engineering-education#2283]
### Proposed title of the article

Compile your Node.js application into a .exe file

### Introduction paragraph (2-3 paragraphs)

During program development, one undergoes several processes of installation, coding, and running an application. These processes drastically change during deployment or execution where the users are just interested in the running of the application and not the underlying codes. This arises the need to creation of a simple executable file that can run on the current operating system without further package installation process.

In this course, we will learn how to create executable files for our Node.js application. We shall compile our JavaScript files into executable files. The `.exe` file not only does it support quick running without the terminal commands but also hides the source code from the users preventing unwanted alterations.

### Key takeaways

At the end of this tutorial, you would have learned the following:

- What are `.exe` files and what are their importance.
- Some of the packages we can use to compile your Node.js application into `.exe` files.
- Creating a simple Node.js application.
- Compiling Node.js files into an executable file for different operating systems.
- Running the executable file in the current operating system.

### Pre-requisites

For one to easily follow up with this tutorial, you require a minimum of the following requirements:

- Basic web development skills.
- Node.js installed in your machine. If not, download it [here](https://nodejs.org/en/download/).
- An IDE. I highly recommend Visual Studio Code which is free and highly customizable. You can download it [here](https://code.visualstudio.com/download).
- A stable internet connection.

### References

Some references used for this tutorial are:

- Node.js [pkg](https://www.npmjs.com/package/pkg) module documentation.
- [nexe](https://www.npmjs.com/package/nexe) package documentation.
- [Importance of .exe files](https://www.bu.edu/tech/support/research/software-and-programming/common-languages/matlab/standalone/benefits/).

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @RisoriTofa
