### ISSUE TITLE
Hashing in Data Structure

### ISSUE THREAD

**Issue by anubhavb11** [section-engineering-education/engineering-education#2284]
*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

## Introduction paragraph (2-3 paragraphs):

In hashing the idea is to use a hash function that converts a given key to a smaller number and uses the smaller number as an index in a table called a hash table.

**Hashing is used in a data structure known as a hash table** to make searching and insertion faster. It is generally the best data structure used to decrease time complexity in your code.

We will learn about hash tables, their operations ( insert, delete, search), hash collisions, and rehashing 

**Hash Table** : In data structures, we use a hash table to store key-value pairs. It is used when the searching, insertion of an element is required to be fast. There are various operations in a hash table like insertion, deletion, searching.

( Will explain everything in detail  about hashing in this article in the simplest way with implementation using C++)

### Key takeaways: 

1. Learn about hashing and hash table
2. Learn about Collision handling techniques.
3. Implementation of hash table data structures in C++

### References: 

N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @anubhavb11

**Comment by anubhavb11** [comment]
This fixes #2460

**Comment by anubhavb11** [comment]
https://replit.com/@Anubhavb11/HashMap#main.cpp
