### ISSUE TITLE
Normalizing a react application state shape with redux-orm

### ISSUE THREAD

**Issue by lucasm08** [section-engineering-education/engineering-education#2286]
### Proposed title of article
Normalizing a react application state shape with redux-orm,

### Introduction paragraph (2-3 paragraphs):
Most of the time, react applications receive from a backend REST API a collection of data items that are nested or relational in nature. What is the best approach to store this kind of data into the redux store?. The documentation suggests to store this data in a "normalized" form. In other words, treat your store as if it were a relational database. How does it work in practice? 
This article will explore techniques and potential implications of normalizing the redux state shape. It will introduce Redux-orm as a tool in various example scenarios to demonstrate this idea. 

### Key takeaways: 

- Why should we normalize the redux state shape?
- What's the proper way to organize nested or duplicate data the state?
- Using redux-orm to normalize the state shape
- Practical example of a normalized state

### References: 
[Redux Documentation](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape)
[Redux-ORM](https://github.com/redux-orm/redux-orm)
[Redux Style Guide](https://redux.js.org/style-guide/style-guide)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @lucasm08

**Comment by hectorkambow** [comment]
@lucasm08 
Just and FYI I will be closing thie topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
