### ISSUE TITLE
H2O Security Implementation

### ISSUE THREAD

**Issue by pkalynan** [section-engineering-education/engineering-education#2291]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*
H2O Security Implementation

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

Security in the data analytical space is important to consider internally and externally. While surrounding a network with cybersecurity protection increases stability, the kernel within the coding program remains vulnerable. Cyber threats and attacks are unpredictable, however, this tutorial shows one of several security precautions to consider prior to starting a coding program. In this tutorial, a module in Python Programming called H<sub>2</sub>O, Internet Protocol (IP) and Domain Name System (DNS) components, and a Linux container are introduced. 

#### Prerequisites
* Linux computer Operating System (OS) or Linux container.
* Basic Bash knowledge.
* Python (preferably 3.3+, tutorial uses 3.9).
* Bash installations: H<sub>2</sub>O, Java, keytools, and a text editor.
* Python installation: H<sub>2</sub>O.
* Internet access with internet browser.

This tutorial is written at root.  

First, open a Linux container.  
[Ubuntu LTS](https://www.zdnet.com/article/minimal-ubuntu-for-containers-and-clouds/#:~:text=While%20that%20release%20is%20useful%20mostly%20for%20hobbyists%2C,the%20standard%20Docker%20Hub%20Ubuntu%2018.04%20LTS%20image.) and [Kali Linux](https://kali.org) are examples of containers.  

For any security mechanism to become stable, generation of authentication files are necessary. Refer to the instructions at the [H<sub>2</sub>O documentation website](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/security.html#keystore-truststore-generation) to generate `keystore` and `truststore` authentication files.  

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

* Increasing security can start with the kernel.
* H<sub>2</sub>O allows security options.
* Linux systems and Linux containers can include security and protection.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

[H<sub>2</sub>O documentation website](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/security.html#keystore-truststore-generation).  
[Linux Container](https://kali.org)
[ZDnet-Ubuntu](https://www.zdnet.com/article/minimal-ubuntu-for-containers-and-clouds/#:~:text=While%20that%20release%20is%20useful%20mostly%20for%20hobbyists%2C,the%20standard%20Docker%20Hub%20Ubuntu%2018.04%20LTS%20image.)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @pkalynan
