### ISSUE TITLE
PID controllers in Matlab

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#2292]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
The performance of a system is usually on basis of a few parameters. These parameters are of the time domain as well as the frequency domain. 
PID controller is an acronym that stands for proportional integral derivative. These acronyms form the basis of the controllers. This means that we have Proportional controllers, Integral controllers, and derivative controllers. When all these modes are combined, we have the PID controllers. It is used to makes some factors such as temperature, pressure, and flow constant. It uses a control loop feedback to ensure that the output wanted is what you get. A controller can are the system's response modifiers. They come in various forms such as standalone units or PLC programming.
In this tutorial, we will see how to use the Matlab `PID()` function and the various effect of changing the parameter Kp, Ki, and Kd. This will help us understand what is going on in the controller.

### Key takeaways: 
- What PID controllers are and the functions.
- How the PID controllers work.
- Understand the program behind the controllers.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @jumapaul
