### ISSUE TITLE
How to Deploy RESTful APIs Using Node, Express 4 and Docker

### ISSUE THREAD

**Issue by jaredphelix** [section-engineering-education/engineering-education#2298]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to Deploy RESTful APIs Using Node, Express 4 and Docker

### Introduction paragraph (2-3 paragraphs):
We'll build our REST API using Express 4, a popular Node-based framework that offers flexible routing options to allow us to customize our API endpoints to fit our needs. There are also other Node-based frameworks available, such as Hapi.js and restify, you may wish to explore as well.

For this walkthrough, we'll further build an app that tracks the current onhand quantities for our products. It will use MongoDB as our data store, though you can choose your datastore of choice. We'll also use mongoose for our document mapper between Node and MongoDB.
For those more familiar with web API design, I've chosen to use the HAL hypermedia format for response payloads. To generate these easily, I'm using the halson module.

For discussion purposes, I'll split the sections up. You can view the full source code for the product on my github product if you prefer to view all the code at once. Feel free to fork the product and try it out for yourself, add new endpoints, or use it as a starting point for your own idea.

### Key takeaways: 
1.Setup Packages and the Database
2.Define the Model
3.Implementing the API
4.Configuring Mongoid with Sinatra
5.Trying Our API Locally
6.Dockerize and Run Your API Locally
7.Preparing to deploy your Dockerized API using Cloud 66
8.Deploy your Dockerized API using Cloud 66
9.Tips for Debugging Your Cloud 66 Docker Stack
10.What Else Can Cloud 66 Do to Manage My Production Containers?

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
we can re-open when the other one is published 👍
