### ISSUE TITLE
Couchbase Cluster Using Docker Compose

### ISSUE THREAD

**Issue by jaredphelix** [section-engineering-education/engineering-education#2299]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction paragraph (2-3 paragraphs):
We often describe Docker as a lightweight solution for isolating your production processes. But sometimes we may forget to say how easy it is to use Docker for setting up your development environment.

Because Docker provides environment isolation, let’s see how easy it is to create and configure the following Couchbase cluster with 3 nodes and one port mapped on your local machine exposing the admin console:

Couchbase 4.0 provides lots of features that allow you to develop with agility and operate at any scale. Some of the features that allow you to operate at any scale are:

0.Elastic Scalability
1.Consistent High Performance
2.Always-On Availability
3.Multi-Data Center Deployment
4.Simple and Powerful Administration
5.Enterprise-grade Security

### Key takeaways: 
1. Creating Couchbase Nodes
2. Configuring Couchbase Cluster
3. Couchbase Cluster Rebalance

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - approved

Let be sure to check there is no overlap with existing EngEd articles if we haven't already @jaredphelix  

We will be closing the prior topic - just due to the one-topic - one pr policy (to prevent too much of a backlog and publish all in a timely manner) once this one is published we can reopen the prior one for approval 👍

**Comment by hectorkambow** [comment]
Just and FYI I will be closing thie topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍 

@jaredphelix
