### ISSUE TITLE
Create a Weather app in Node.js using OpenWeatherMap API

### ISSUE THREAD

**Issue by blacklihgt** [section-engineering-education/engineering-education#2300]
### Proposed title of the article

Create a Weather app in Node.js using OpenWeatherMap API

### Introduction paragraph (2-3 paragraphs):

Have you ever wanted to create a fully functional weather website in Node.js? Do you need an application that can show you weather forecasts instantly in clicks? If you are one of them, you are in the right place.
Weather forecasting is very necessary for our daily lives. It helps us to prepare and make plans depending on the expectations. In this tutorial, we will learn how to build a beautiful weather app using OpenWeatherMap API. 

### Key takeaways: 

At the tip of the tutorial, you would have known:

- What is OpenWeatherMap API
- How to work with OpenWeatherMap API to access data from the website
- Building a beautiful weather website using HTML, CSS, and JavaScript
- Integrating the API to the system
- Running the web Application

### Pre-requisites

Some basics needed for easy follow-up on this tutorial include:

- Basics in the web development process
- Basics on Node.js. If you don't have Node.js installed on your machine, you can download it from [here](https://nodejs.org/en/).
- An IDE installed on the computer. I strongly recommend to those who don't have one, to download and install [Visual Studio Code](https://code.visualstudio.com/).
- A good and stable internet connection.

### References

Please list links to any published content/research that you intend to use to support/guide this article.
- [OpenWeatherMap API documentation](https://www.npmjs.com/package/openweathermap).
- [OpenWeatherMap website](https://openweathermap.org/).

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @blacklihgt

**Comment by hectorkambow** [comment]
@blacklihgt 
Just and FYI I will be closing thie topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by blacklihgt** [comment]
My code is ready but I can't find the reopen button. How do I re-open it?. @hectorkambow
