### ISSUE TITLE
Create custom website loading animations in a Node.js project

### ISSUE THREAD

**Issue by prograte** [section-engineering-education/engineering-education#2304]
### Proposed title of the article

Create custom website loading animations in a Node.js project

### Introduction paragraph (2-3 paragraphs)

Have you ever created a beautiful website but felt like there is a part missing to make it appealing? Have you ever needed some custom-made loading animations for your site? You have come to the right place.

Many websites today add more and more visually appealing effects even in the smallest areas. This makes users interested in interacting more with it. Custom website loading animations, 404 Error pages, No internet connection pages among others have been such an example.

In this tutorial, we will see how to create some custom animations, load them on our website and test them in a simple Node.js project.

### Key takeaways

Some of the knowledge that will be gained at the end of the tutorial will include:

- Benefits of custom website loading animations
- How to create different website loading animations
- How to integrate the animations in a website
- How to create websites with custom page loading animations

### Pre-requisites

Minimum requirements for easy follow-up on this tutorial will include:

- Web development basics
- Node.js basic skills. If you don't have Node.js installed on your computer, please click [here](https://nodejs.org) to download and install it.
- A simple IDE installed on your machine. I recommend Visual Studio Code if you have none. You can get it [here](https://code.visualstudio.com
Visual Studio Code).
- A stable internet connection.

### References

None.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @prograte

**Comment by hectorkambow** [comment]
@prograte 
Just and FYI I will be closing thie topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
