### ISSUE TITLE
How To Use The .splice() Array Method

### ISSUE THREAD

**Issue by twish-254** [section-engineering-education/engineering-education#2318]
### Proposed title of article
How To Use The .splice() Array Method

### Introduction paragraph (2-3 paragraphs):

What is the splice() method? It is a built-in method for JavaScript Array objects which enables one to update the content of an array by removing or replacing current components with new ones.
This method alters the original array and returns a new array with the removed or replaced elements.
This tutorial will focus on how the splice() method is used to remove, add and replace elements within an array.

### Key takeaways: 
After this article the learner will be able to:
- Remove array elements with splice()
- Add array elements using splice()
- Remove and add elements without removing any elements using splice()

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @twish-254
