### ISSUE TITLE
How to write efficient Python code

### ISSUE THREAD

**Issue by Samuel-2626** [section-engineering-education/engineering-education#2323]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to write efficient Python code

### Introduction paragraph (2-3 paragraphs):
 As a beginner programmer, writing efficient code is not the main focus but rather just learning the syntax, the flow and how to think like a programmer. But things get interesting when you are trying to advanced to a more intermediate level developer and really become a true nerd, no pun intended.

  Writing efficient code is one of the ways a beginner programmer can advance to become an intermediate programmer and really appreciate code readability coupled with the productivity of a developer.

  This tutorial is focused on writing efficient python code. By the end of this tutorial, you would have been equipped with the tools needed to improve your productivity as a developer.

### Key takeaways: 
A detailed explanation on key concepts like
 - List-Comprehension
 - Lambdas Functions
 - Map, Filter and Reduce
 - Recursive functions and Memoization

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @Samuel-2626
