### ISSUE TITLE
How to Setup and run PHP Websites using Docker Containers with PHP Apache and MySQL.

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#2334]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
How to set up and run PHP Websites Using Docker Containers with PHP Apache and MySQL

### Introduction paragraph (2-3 paragraphs):
Container technology is growing day by day. It's a technology that makes application development much easier and faster. It has a clean architecture that ensures application services utilize resources sustainably by dividing an application into smaller services called images. This allows you to set up each service independently without affecting how the other services run.

In this case, Docker provides a docker-compose file that allows you to set all your application environments and run a few commands to fully set up your application in a more elegant and faster approach. 

Let's take the case of running a PHP application. In this case, you would have to install all environments that you need to run a PHP script. You need an apache server installed in your server/system and probably a MySQL database. Then set up each environment in a way that will allow you to run your PHP-driven website.

With Docker, things are much more manageable. Docker allows you to set and your application with each service running as a microservice. This way, you set a single YAML file that will isolate all the services that your application needs to run. The file set up the apache server and MySQL database for you. All you need is to specify the parameters that you need your application to run on.

The main advantage of this is that Containers provides a scalable environment to run your application services. It ensures that the practices of continuous integration and continuous delivery (CI/CD) pipelines are enhanced across the team. So you only need to share run this YAML file with every team member. This will set all the necessary environments across the team regardless of the operating system they are running on. 

This guide will show you how we can use Docker development environment to

- Setup and run a local PHP Apache server instance.
- Serve a dynamic PHP-driven website.
- Setup a Mysql database to run SQL scripts, fetch records, and print them in a PHP-driven website.

We will use the Docker hub images to set up a containerized PHP development environment.

### Key takeaways: 
Docker installation
Setting docker-compose
Setting PHP and Apache
Setting MySQL database
Running PHP container

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@kimkimani seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved
