### ISSUE TITLE
Getting started with Spring Boot batch processing

### ISSUE THREAD

**Issue by okeloviolet** [section-engineering-education/engineering-education#2336]
### Getting started with Spring Boot batch processing
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article's higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Batch Service is a process to execute more than one command in a single task. Tasks that are grouped and completed at once such as creating a backup of application or exporting database tables to CSV files are called Batch processes.

In the article, I will explain how to create a Batch Process and schedule it for execution at a later time using Spring Boot and the Batch processing dependency. By the end of the article, the reader will be able to create and schedule Spring Boot Batch processes.

### Key takeaways: 
1. Creating and adding Batch processing dependency to Spring Boot application.
2. Creating Batch processes and scheduling them for execution at a specific time.
3. Testing the Spring Boot Batch processing application.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @okeloviolet
