### ISSUE TITLE
How to start up with Socket Programming with Java

### ISSUE THREAD

**Issue by apondi-911** [section-engineering-education/engineering-education#2338]
### Proposed  Title of the article
How to start up with Socket Programming with Java 

### Introduction paragraph (2-3 paragraphs):

A socket is simply described as a combination of IP and ports.  When it comes to programming, it connects two nodes on a network to communicate with each other.
A socket is one endpoint of a two-way communication link between two programs running on a network.

 Mostly a socket is bound to a port number so that the TCP layer can find the data the application is destined to be sent to.
One socket(node) has to listen to a particular port at an IP while the other reaches out to make a connection.
An endpoint consists of an IP address and port number. 

In this tutorial, you will be able to understand more about the client and server relationship.

### Key Takeaways:
1.  Networking protocols(TCP/IP)
2.  Client-server relationship
3. Socket programming with java

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing [EngEd articles](https://www.section.io/engineering-education/search/?q=Socket) or incoming topic suggestions (if you haven't already). - approved

@apondi-911

**Comment by hectorkambow** [comment]
@apondi-911 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible.
