### ISSUE TITLE
User Input and while Loops in Python

### ISSUE THREAD

**Issue by Bonimum** [section-engineering-education/engineering-education#2340]
### Proposed title of article
User Input and while Loops in Python

### Introduction paragraph (2-3 paragraphs):

Most programs are written to solve an end user’s problem. To do so, you usually need to get some information from the user.
In this article we will learn how to accept user input so your program can then work with it. When your program needs a name,you will be able to prompt the user for a name. When your program needs a list of names, you will be able to prompt the user for a series of names. To achieve this, we’ll use the input() function.We’ll also learn how to keep programs running as long as users want them to, so they can enter as much information as they need to; then, your program can work with that information. We will use Python’s while loop to keep programs running as long as certain conditions remain true.

With the ability to work with user input and the ability to control how long your programs run, you will be able to write fully interactive programs.

### Key takeaways: 

1.How the input() Function Works
2.Using int() to Accept Numerical Input
3.Introducing while Loops
4.Using a while Loop with Lists and Dictionaries

### References: 
N\A

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @Bonimum
