### ISSUE TITLE
Java Vs C#

### ISSUE THREAD

**Issue by Alicewangari** [section-engineering-education/engineering-education#2343]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Java Vs C#

### Introduction paragraph (2-3 paragraphs):

Java and C# are both Object-Oriented languages used for developing  Web applications, Networking applications, Database applications, Mobile application, Videos games, Service applications and so much more.

Let's look at the primary difference between the two.

Java is an Object-Oriented, class-based and general-purpose programming language. Developers can use the principal – “write once, run anywhere” with Java. Java was invented in 1995.  It requires Java Development Kit to run on a machine.

C# is an Object-Oriented Programming language and it is portable as it can develop software for many computer systems. C# was invented in 2002. Programs written in C# utilize the .NET Framework to run on a machine. 

In this article, we shall compare between Java and C#.

### Key takeaways: 
1.  Application - Where the languages can be used
2. Installation - The requirement of each language to run on a machine
3. Cross-platform - Which of the languages is easily compatible to other platforms
4. Project - Where does each language suit the best. i.e, suited for complex web-based concurrency projects or game development projects
5. Syntax - which one offers developer friendly syntax

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @Alicewangari
