### ISSUE TITLE
Top 5 Docker Logging Best Practices

### ISSUE THREAD

**Issue by BashiirIsla** [section-engineering-education/engineering-education#2346]
### Proposed title of article
Top 5 Docker Logging Best Practices
### Introduction paragraph (2-3 paragraphs):
As with developing any application, logging is a central part of the process and especially useful when things go wrong. But logging in the world of containerized apps is different than with traditional applications. Logging Docker effectively means not only logging the application and the host OS, but also the Docker service.

There are a number of logging techniques and approaches to keep in mind when working with Dockerized apps. This article explains what Docker logging is, discusses Docker logging challenges, and outlines the top 5 best practices and their strengths. 

### Key takeaways: 

1. What is Docker logging? 
2. Challenges with Docker logging.
3. Docker logging methods and best practices.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in any official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @BashiirIsla
