### ISSUE TITLE
Decision making and branching in java

### ISSUE THREAD

**Issue by Georgewamama** [section-engineering-education/engineering-education#2348]
### Proposed title of article
Decision making and branching in java

### Introduction paragraph (2-3 paragraphs):
A java program is a set of statements, which are normally executed sequentially in the order in which they appear. This happens when options or repetitions of certain calculations are not necessary. However, in practice, we have a number of situations, where we may have to change the order of the execution of statements based on certain conditions, or repeat a group of statements until certain specified conditions are met. This involves a kind of decision making to see whether a particular condition has occurred or not and then direct the computer to execute certain statements accordingly.
When a program breaks the sequential flow and jumps to another part of the code, it is called branching. When the branching is based on a particular condition, it is known as conditional branching. If branching takes place without without any   decision, it is known as unconditional branching.
Java language possesses such decision making capabilities and supports control or decision making statements.

### Key takeaways
1.	If statement
2.	If…else statement
3.	Nested if…else statement
4.	Switch statement

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @Georgewamama
