### ISSUE TITLE
Website vs web application: The Key Differences.

### ISSUE THREAD

**Issue by Erastuskanyatta** [section-engineering-education/engineering-education#2351]
### Proposed title of article
Website vs web application: The Key Differences.

### Introduction paragraph (2-3 paragraphs):
It is not easy for an end-user to tell the difference between a website and a web application. They type the URL and get the expected results.

Getting the results of what they are searching for is what matters to the end-user. How they get the results is not their business.

Developer builds these products for the user. Thus it is expected of him to differentiate between the two very well. Some developers argue that website and web application means the same, others argue that they are two different terms. Between the two types of developers who is wrong and who is correct?😕.

I was once among those who argued that the two terms mean the same, but after research, I found out that these are two different things.   In this article, I will try and highlight some of the key differences which helped me understand how websites and web application differ.

### Key takeaways: 

1. Definition of website and web application

2. Types of websites and web application

3. Characteristics of both website and web application

4. Why you need a website and web application

5. Key differences between a website and web application

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @Erastuskanyatta
