### ISSUE TITLE
Difference Between a Hub, Switch and Router

### ISSUE THREAD

**Issue by Jeddy947** [section-engineering-education/engineering-education#2358]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article:
Difference Between a Hub, Switch and Router

### Introduction paragraph (2-3 paragraphs):
Hubs, switches, and routers are all common types of devices to help connect a network. Because they are often integrated into a single device, it can be challenging to understand the distinction between these items. In some cases, the terms may even be used interchangeably, though this is incorrect. The functions and uses of these devices are all very different from one another. 

In this article, we will look at a simple guide on the difference between a hub, switch, and router to others understand their dissimilarity.

### Key takeaways: 
1. What is a hub, switch and  router.
2. How each transmit data from end to another
3. Connectivity - What does each of these items connect
4. The security of each item.
5. Networks used - The uses of each item.
### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @Jeddy947

**Comment by hectorkambow** [comment]
Just and FYI I will be closing thie topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by Jeddy947** [comment]
@hectorkambow  The article is ready for submission. Am not able to reopen the issue, would you open for me please
