### ISSUE TITLE
Structure Large Applications in Flask Using Blueprints and Flask Application Factory 

### ISSUE THREAD

**Issue by corpsgeek** [section-engineering-education/engineering-education#2365]
### Proposed title of article
Structure Large Applications in Flask Using Blueprints and Flask Application Factory

### Introduction paragraph (2-3 paragraphs):
This article will explain and illustrate how to structure web applications on a large scale with the Python Flask backend web framework. 

### Key takeaways: 
- Work Environment Setup
- Understanding and implementing Blueprints and Application Factory
- Working with configuration and environment variable
-  Summary and Conclusion

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @corpsgeek 

Also FYI - we encourage students to use these topic forms as a skeleton to start writing the intro paragraphs to their articles

**Comment by corpsgeek** [comment]
alright @hectorkambow noted

**Comment by corpsgeek** [comment]
would like to inform you that I'm currently working on this article and almost done @hectorkambow. Very active.
