### ISSUE TITLE
Handling JSON data in MongoDB

### ISSUE THREAD

**Issue by salvador02** [section-engineering-education/engineering-education#2366]
### Introduction paragraph (2-3 paragraphs):
According to developer.mozilla.org, JavaScript Object Notation (JSON) is a standard text-based format for representing structured data based on JavaScript object syntax.

It is commonly used for transmitting data in web applications. This process involves sending and receiving data between the server and the client. 

This article will focus on explaining how to handle JSON data in MongoDB.

### Key takeaways: 
1. Understanding JSON
2. Data representation in MongoDB
3. How to use JSON data in MongoDB

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @salvador02

**Comment by hectorkambow** [comment]
@salvador02 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible.

**Comment by salvador02** [comment]
@hectorkambow, I am ready with the article will create the PR today. I however will ping you on slack for a little issue I got.
