### ISSUE TITLE
Uploading Media to Cloudinary from a Spring Boot Application

### ISSUE THREAD

**Issue by Kikiodazie** [section-engineering-education/engineering-education#2370]
### Proposed title of article
Uploading Media to Cloudinary from a Spring Boot Application

### Introduction paragraph (2-3 paragraphs):
Software developers building products with media features have to store the media somewhere. In most cases, they will need to perform [transformations](https://cloudinary.com/documentation/transformation_reference#parameter_types) on the media to give users the best experience possible. Cloudinary's end-to-end image- and video-management solution can help them upload, store and transform media programmatically.

While building a Spring Boot Rest API, integrating Cloudinary was a struggle for me. I had to comb through GitHub repositories and spend a lot of time debugging errors I encountered. In addition, although the documentation for Cloudinary is pretty good, it never mentioned the whole workflow when building with spring boot, and I had to figure that out on my own.

This tutorial will step you through uploading media (images and videos) programmatically to Cloudinary from a Spring Boot application and save you the effort I had to put in to get my code working. Also, at the end of this tutorial, you would've built a Spring Boot RESTful API to upload media to Cloudinary.

### Key takeaways: 
1. Introduction to Cloudinary and its Java integration using Maven.
2. Learn how to handle file upload and manipulation in Spring Boot.
3. Learn how to upload images and videos to Cloudinary.

### References: 
- https://github.com/princesoni1989/Spring-Boot-Cloudinary
- [Cloudinary documentation on Java](https://cloudinary.com/documentation/java_integration)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - we can re-open to be approved once your 1st PR is merged/published 👍  @Kikiodazie

**Comment by Kikiodazie** [comment]
Yes sure. No problem. 

About the relevance and value. Yes I did my research and the topic suggestion was borne out of my struggle when I first worked with Cloudinary in a springboot app. And the content value will definitely be beyond what's on Cloudinary’s official docs. 

And yes there are similar topics but those other ones are using different languages and frameworks. Like the one of NodeJS of Javascript and Django of Python.

@hectorkambow 😁😁.

**Comment by Kikiodazie** [comment]
> seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - we can re-open to be approved once your 1st PR is merged/published 👍 @Kikiodazie

Hey, @hectorkambow just want to check up on this for re-open. I hope this meets you well.
