### ISSUE TITLE
Understanding C++ storage class

### ISSUE THREAD

**Issue by Dawe-7** [section-engineering-education/engineering-education#2371]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Understanding C++ storage class

### Introduction paragraph (2-3 paragraphs):
Each variable has a data type when defined in C++ to help the user understand what type of variable it is. Since we were using the default Storage classes, we didn't identify any storage classes yet. When defining a variable, the compiler assigns a storage class by default.  In C++, storage classes are used to describe the characteristics of a variable and functions. It specifies the scope, lifetime, and visibility of variables and functions. These characteristics enable us to track the presence of a variable over the course of a program's execution. This article will look at various storage classes and code examples that show how they work.

### Key takeaways: 
1. What is the storage class in C++
2. Types of storage classes
3. Automatic storage class
4. Register storage class
5. Static storage class
6. External storage class
7. Mutable storage class

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
closing for now - since there is another one approved one.
can reopen when the 1st one is published
