### ISSUE TITLE
Creating a Custom Data Transformer using Scikit-Learn

### ISSUE THREAD

**Issue by Agusioma** [section-engineering-education/engineering-education#2374]
### Proposed title of the article
Creating a Custom Data Transformer using Scikit-Learn

### Introduction paragraph (2-3 paragraphs):
A Transformer is used to make data fit for the machine learning process while Scikit-Learn is a Python library used for machine learning. It provides built-in methods for data preparation before the data is fed into a training model. However, as a data scientist, you may need further perform custom cleanup processes or adding more attributes that may improve your model's performance. To do that, you will need to create your own custom transformer for your data.
We will look at how to do that using a class, perform feature scaling and then implement the transformer in a pipeline.

### Key takeaways: 
We will learn about:
1. Getting the data
2. Creating a Custom Transformer
3. Transformation Pipelines
4. Handling text and categorical attributes

### References: 
**Book** : Hands-On Machine Learning with Scikit-Learn & TensorFlow CONCEPTS, TOOLS, AND TECHNIQUES TO BUILD INTELLIGENT SYSTEMS by Aurélien Géron

**Comment by hectorkambow** [comment]
good topic @Agusioma  - approved. 

One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. 

This will help increase the likelihood of your article getting published and you receiving a payout :)

As we want to ensure we publish articles in a timely manner - we can not provide any revision.
👍
