### ISSUE TITLE
LXC vs. Docker, what's the difference and why Docker is better

### ISSUE THREAD

**Issue by JuliusGikonyoNyambura** [section-engineering-education/engineering-education#2375]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*
LXC vs. Docker, what's the difference and why Docker is better

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

Containers are the new technologies in enterprise IT, and most seem to be very interested in this technology. Many are using them to develop and deploy applications to the public. Containers are useful for many reasons. They isolate applications and operating systems from the rest of the system, thus bringing speed and flexibility. They are portable and easy to clone and move to other operating systems. Thus, containers can be more or less of a virtualized software environment that the application or operating system runs on a host computer.

There several kinds of container technologies you can you. These include Docker containers, Kubernetes containers, and Linux containers (LXC). This article will go over and compare LXC over Docker.

### What is LXC, and what does it do

[LXC](https://linuxcontainers.org/LXC/introduction/) is a userspace interface for the [Linux kernel containment features](https://linuxcontainers.org/LXC/getting-started/). It lets Linux users easily create and manage systems or application containers through a powerful API and simple tools.

To understand LXC well, let first discuss what a virtual machine is.

#### The concept of Virtual Machines (VM)

Typically, in a virtual machine, you have a host machine where you install your operating system. It could be windows, macOS, or Linux on the host machine. When you use a virtual machine, you add or install hypervisors in your host operating system, for example, VirtualBox, VMware and ESXi. You use the hypervisor to install a guest operating system to run o top of your host operating system. In this case, the Guest os is running as a virtual machine/container. Each of the guest operating systems you add is a complete operating system. all the hardware resources (RAM, CPU, HDD/SSD) attached to these guest virtual machines are virtualized. And the hypervisor is responsible for allocating the guest OS the hardware resources they need from your base/host machine in a virtualized fashion. Basically, you create an instance of an emulator that you can interact with just like an ordinary computer. The image below depicts this concept.

![Virtual machine vm architecture](virtual-machine-vm-architecture.jpeg)

[Image source](https://www.docker.com/resources/what-container)

The main issue with the above is that every instance running will need resource allocation, which can lead to over-allocation of the available resources. Every instance of an operating system has to have these resources allocated to it, and those resources will be used whether or not the server needs them.

Check this out. If you have 16GB of RAM and start 4 Guest machines/servers, they will use all of the RAM that is currently available, i.e., each is allocated 4GB of ram. Even if the individual server only uses 1GB of RAM. Assuming each can run on 1GB of RAM, you just need 4RAM to boot up these four virtual hosts. But because the instances that they are in have been given four gigs each, they are using 16GB of ram within your virtual environment. If you were to add another virtual host, you wouldn't have enough RAM to start it. Every time a VM starts, all of the resources that have been assigned to it are automatically given to it. Those resources can't be assigned to another guest host. In the end, you have lots of wasted resources.

Another issue is that all the guest operating instances are running on a single machine. In case of any boot-up processes, or whenever you want to restart service for some reason, you have to reboot that entire computer. depending on what environment you are you're in, a couple of extra seconds matter

#### LXC virtual environments (VE)

[LXC](https://www.youtube.com/watch?v=CWmkSj_B-wo) (Linux Containers), on the other hand, is an operating system-level virtualization solution that allows many isolated Linux virtual environments(VE) to be created and operate on a single control host. These isolation levels, often known as containers, can isolate specific applications or simulate a completely different host.

LXC mitigates VM disadvantages. Linux containers enable the host CPU to effectively divide memory allocations into confinement levels known as namespaces. In comparison, a VM contains the whole operating system and machine setup/emulators, such as the hard disk, virtual CPUs, and network interfaces. Its whole enormous virtualized environment usually takes a long time to boot and uses a significant amount of CPU and RAM. LXC virtual environment has no hardware preload emulation. Each virtual environment (an OS or an application) is loaded in a container and executes without any additional overhead and no hardware emulation. This means no penalty from software with limited memory. In the end, LXC will improve the performance of the bare metal as it only bundles the OS/application that is required.

![LXC container](lxc-container.png)

[Image source](https://www.polarsparc.com/xhtml/LXC.html)
### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

 ### What is LXC, and what does it do
 #### The concept of Virtual Machines (VM)
 #### LXC virtual environments (VE)
 ### Docker containers
 ### What is the major difference between Linux and Docker containers
 ### Why Docker is better

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@JuliusGikonyoNyambura  I do not see any info for me to read about on the topic besides the title

**Comment by JuliusGikonyoNyambura** [comment]
Added content

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @JuliusGikonyoNyambura
