### ISSUE TITLE
The Overview of Container Technology

### ISSUE THREAD

**Issue by julie-techie** [section-engineering-education/engineering-education#2376]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
The Overview of Container Technology

### Introduction paragraph (2-3 paragraphs):
Container technology is a method to package an application to be run, with its dependencies, isolated from other processes. Containers allow you to run an application and its dependencies in a resource-isolated process. The major cloud computing providers include Amazon Web Services, Microsoft Azure and Google Cloud Platforms, have embraced container technology.

Container technology enables enterprises to put apps in containers, and multiple containers can run on a single OS. That makes the servers much more efficient, and it makes deploying apps faster. When you move from one computing environment to another, containers are a solution to the problem of how to get your software to run reliably.

This article will discuss container technology in general.

### Key takeaways: 
1. Container technology
2. Understanding containers
3. Difference between containers and virtual machines
4. Classifications of containers
5. Pro and cons of containers

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Just want to make sure that your article will cover more than what has been covered here 

https://www.section.io/engineering-education/history-of-container-technology/

It may be best to approach a different topic if so.  @julie-techie

**Comment by julie-techie** [comment]
@hectorkambow, I went through https://www.section.io/engineering-education/history-of-container-technology/ . My article cover more concepts on container technology

**Comment by hectorkambow** [comment]
Approved @julie-techie - lets be sure to reference other articles where it makes sense. 👍
