### ISSUE TITLE
Comparison between the HTTP/3 and HTTP/2 Protocols

### ISSUE THREAD

**Issue by Bradley8555** [section-engineering-education/engineering-education#2382]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Comparing HTTP/3 and HTTP/2 protocols

### Introduction paragraph (2-3 paragraphs):
Most developers have only just gotten their teeth into HTTP/2, but the movers and shakers of the web are already spinning out an update: the HTTP/3. HTTP/3 is the third and upcoming major version of the Hypertext Transfer Protocol used to exchange information on the World Wide Web, alongside HTTP/1.1 and HTTP/2. HTTP semantics are consistent across versions: the same request methods, status codes, and message fields are typically applicable to all versions.
In this article we will compare the two protocols with features and what they aim to solve deeply.

### Key takeaways: 
1. What HTTP/3 and HTTP/2
2. What both protocols are aiming to improve over the previous versions
2. Comparing HTTP/2 to HTTP/3
3. The limitations of HTTP/2 that led to HTTP/3 being introduced

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Bradley8555** [comment]
I had previously written a tutorial about HTTP/2 in Node.js. I find updating to HTTP/3 and comparing this will even be more useful.

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @Bradley8555
