### ISSUE TITLE
Wavelet transform based denoising of images using Matlab

### ISSUE THREAD

**Issue by atienodorine3** [section-engineering-education/engineering-education#2384]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
Removing noise from an original image is still a challenge in the developing world. Several algorithms have been written and some discussed but it still remains to be a challenge. We will discuss the currently available method, that is, wavelet based denoising of images, which is the currently efficient method. When a signal is transmitted over some distance, it is frequently contaminated with noise. The objective here is to remove the noise from the image using the wavelet technique. This makes it easy to come up with a denoised image.
The wavelet-based diagnosis scheme involves, the signal is first decomposed into various wavelet coefficients using discrete wavelet transforms. The co-efficient is then thresholded and the resulting co-efficient are collected together and the inverse denoising wavelet transforms (IDWT) to obtain the denoised image.

### Key takeaways: 
- Denoising scheme using wavelet transforms.
- How to use 'waveletAnalyzer' Matlab tool.
- Matab's function for denoising.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @atienodorine3
