### ISSUE TITLE
What is AWS, why is AWS popular?

### ISSUE THREAD

**Issue by mosesreigns** [section-engineering-education/engineering-education#2386]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an article to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
What is AWS and reasons why AWS is so popular

### Introduction paragraph (2-3 paragraphs):
AWS stands for Amazon Web Services, a subsidiary of Amazon, the tech giant. AWS provided cloud computing and APIs services on-demand for organizations to run and host online infrastructures and applications. It offers a wide variety of computing powers, databases, storage, content delivery platforms, networking, virtualization, analytics, security, and many services that easily scalable and available across businesses and organizations of all levels.

### A brief history of AWS and how it came to be

Aws was first launched in 2002 internally by amazon to provide tools to developers to incorporate the features of amzon.com to the website.

In 2004 The first AWS service was launched to the public. The service was called simple queuing service (SQS). It provided just simple queue services.

>Some omitted paragraphs

In 2013, AWS saw one of its major breakthroughs, the Central Intelligence Agency (CIA), moved its infrastructure to AWS. This was a huge success. In 2015, AWS released its profit figure to the public, with a record of 4.6 billion for the previous year (2014). with an expected growth of about 49% that is 6.2 billion in 2015. And in 2016, AWS surpassed its 10 billion revenue target.

Today, AWS has a ton of services and certifications. There is a massive demand for AWS services these days. The AWS cloud service platform is now estimated to be used by more than 45% of the global market. An average of 1 of the 3 website you visits uses AWS services.

### A recap of cloud service

Think of a personal use case of a cloud service. Just like iCloud and Dropbox, AWS is a cloud service provider. In your past, you may have used cloud computing to store pictures, videos, and documents. However, that is only a very small subset of what cloud computing is.

>Some omitted paragraphs

In this scenario, you have the following main cloud advantage.

High availability and fault tolerance

### How AWS Works as a cloud service provider

Think of an enterprise company that is not using cloud services such as AW. this means the company has on-premise data centers and servers for handling and storing their data. When a customer wants to access the company's software or a service, they're accessing resources on the company's servers.

Let's say in 2019, about 3000 users accessed this software, so the company has three severs to power up its software to these users. When the number of user base grows in the next year, let's say to 6000. The three servers the company has will not be enough to handle that significant number of additional users. The company will be required to add a cost and space to double the number of servers on its on-premise data center to handle the load of having more users. In this case, they have to research what type of servers they need, make an order, wait for delivery, set them up, install operating systems software, test them and get them all up and running.

>Some omitted paragraphs

This is the biggest problem that cloud computing provides, such as AWS, solves. The company no longer has to project or estimate future growth naturally to set a number of servers. As the user base grows, AWS can automatically and instantly add additional servers and resources according to the number of users accessing the company's services. AWS, within no time it automatically upgrades functionality and features for you.

>Some omitted paragraphs

### Key takeaways: 
A brief history of AWS and how it came to be
A recap of cloud service
How AWS Works as a cloud service provider
How popular is AWS
Reasons why AWS is popular

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @mosesreigns
