### ISSUE TITLE
How to containerize an Angular Application featuring Nginx Using Docker containers

### ISSUE THREAD

**Issue by Rose-stack** [section-engineering-education/engineering-education#2388]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
How to containerize n Angular Application with Nginx Using Docker containers

### Introduction paragraph (2-3 paragraphs):
Docker is a lightweight virtual machine (VM) that lets you specify virtual computers known as containers. These containers are made up of software images provided by various official software vendors. These containers, unlike traditional VMs, are super light and are not resource-intensive. Multiple containers can usually run in parallel with little impact on the host machine's resources. And that is absolutely what docker containers are made for. The lightweight docker containerization philosophy separates each service that your application requires and runs them in isolated environments.

Docker makes it simple to set up these environments. With a single yml file, you'll be able to build several containers that will all work together within a single network and communicate with each other to create a single functioning application. Containers enable developers to bundle up an application and all of its essential components, including libraries and other dependencies and distribute it as a single package.

On the other hand, Angular is a single-page app design javascript front-end framework and a development platform for building innovative and advanced apps. Similar to React and Vue used to run the application on the client-side. Angular is also often used with back-end APIs to create powerful full-stack applications, such as making HTTP requests to a MERN stack.

In this guide, we'll set up a simple docker-compose script to get you up and to run with Docker, docker-compose, and a local Angular environment on your computer featuring Nginx for reverse proxy. No need to install angular CLI and Node.js locally. Docker-compose will help us lay down some instructions to get Angular containerized and ready to run some code.

### Key takeaways: 
Set up Docker
Writing a Dockerfile
Writing docker-compose.yml
Running the Docker Container

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @Rose-stack
