### ISSUE TITLE
A beginner-friendly guide into flutter social Authentication

### ISSUE THREAD

**Issue by jerimkaura** [section-engineering-education/engineering-education#2394]
### Proposed title of the article
A beginner-friendly guide into flutter social Authentication

### Introduction paragraph (2-3 paragraphs):
Social authentication is an authentication technique in which one uses an existing account to log into or create a new account in another application. Besides levying a user on constantly remembering multiple passwords, social authentication ease the registration process and improves security.

Most of the well-known social platforms widely used for social authentication are Facebook, Github, Google, and Twitter.
This article aims at guiding the readers through a step-by-step understanding and implementation of social authentication in Flutter while narrowing it down to Google and Facebook. We will build a project in flutter and implement social authentication in the flutter application.
### Key takeaways: 
1. Introduction to social Authentication
2.  Setting up Firebase console for Social Authentication
3. Integrating Google and Facebook authentication in Flutter.

### References: 
- https://firebase.flutter.dev/docs/auth/social/
- https://pub.dev/documentation/firebase_auth/latest/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @jerimkaura
