### ISSUE TITLE
Understanding Docker Networking

### ISSUE THREAD

**Issue by Pauline-Mwangi** [section-engineering-education/engineering-education#2396]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Understanding Docker Networking

### Introduction paragraph (2-3 paragraphs):
Docker takes care of the networking aspects so that the containers can communicate with other containers and also with the Docker Host. Docker has a network concept. It has several network drivers to work with. Depending on how we want our container to behave, we can select our network. This helps us to connect a container with a container or container with the host.

This article will help you understand  Docker networking and the problems it solves, container networking models, and networking drivers

### Key takeaways: 
1. Docker Networking
2. Why Docker Networking is Important
3. Container Network Models
4. Network Drivers

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
https://docs.docker.com/network/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in any official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved @Pauline-Mwangi
