### ISSUE TITLE
Create API Authentication With Laravel Passport

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#2397]
### Proposed title of article
Create API Authentication With Laravel Passport

### Introduction paragraph (2-3 paragraphs):
APIs typically use tokens to authenticate users and do not maintain session state between requests. Laravel makes API authentication a breeze using Laravel Passport, which provides a full OAuth2 server implementation for your Laravel application development in a matter of minutes.

In this tutorial, we will see how to use laravel passport authentication in your Laravel application. We will also build a simple Product CRUD (Create, Read, Update and Delete) using Laravel Passport Authentication.

Laravel already provides tradition login forms authentication, but what if you want to use APIs? APIs use tokens for authenticating users, because they do not use sessions. When a user login via API, a token is generated and sent to the user which is used for authentication purposes. Laravel provides Passport to work with API Authentication without any difficulty.

### Key takeaways: 
1: Installing Passport Auth.
2.Passport Configuration.
3. Issuing Access Tokens
4. Authorization Code Grant with PKCE

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @jumamiller
