### ISSUE TITLE
A beginners guide on how to become a blockchain developer

### ISSUE THREAD

**Issue by wilkistermumbi** [section-engineering-education/engineering-education#2398]
### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

A beginners guide on how to become a blockchain developer

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

Blockchain, being the revolutionary technology has obviously opened up a new field of development called blockchain development. This, in turn, has created numerous job opportunities for developers and tech enthusiasts. Even with such fantastic job opportunities around, people generally seem to be confused about the direction they should take to become a blockchain developer. Hence, I decided to write up this article to guide fellow blockchain enthusiasts into the world of blockchain development.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.
 
By the end of this article, a reader should be able to understand:

1. Who is a blockchain developer?
2. Which blockchain should I use?
3. Libraries and frameworks for blockchain development
4. Which programming languages for blockchain?
5. Use cases for blockchain

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @wilkistermumbi
