### ISSUE TITLE
Will Serverless Computing replace Docker Containers?

### ISSUE THREAD

**Issue by verah-tech** [section-engineering-education/engineering-education#2400]
### Proposed title of article
Will Serverless Computing replace Docker Containers?

### Introduction:
Will serverless computing eventually replace Docker? That’s the conclusion the article is interested in. We will look at the relationship between Docker containers and serverless computing.

Serverless computing refers to platforms that allow an organization to run a specific piece of code on-demand. It’s called serverless because the organization does not have to maintain a physical or virtual server to execute the code.

Modern platforms such as AWS Lambda, Azure Functions, and (for an on-premises version) Fission.io make serverless computing readily available to organizations today.
Can serverless computing revolution regarded as a threat to Docker? The article will bring that to light.

### Key takeaways: 
The reader will understand:
- concept of containers and serverless computing
- comparisons between serverless and docker containers
- reason on whether serverless can replace or not replace docker containers

### References: 
N/A

**Comment by hectorkambow** [comment]
@verah-tech seems like a helpful topic - lets please be sure it add value beyond what is in any official docs and that it does not overlap with any existing EngEd articles (if you haven't already). - approved
