### ISSUE TITLE
Working with Google Translate API in Nodejs

### ISSUE THREAD

**Issue by mercymeave** [section-engineering-education/engineering-education#2401]
### Proposed title of article
Working with Google Translate API Nodejs

### Introduction paragraph (2-3 paragraphs):
Google Translate API is an application Programming Interface for translating text from one language to another. This API comes in very handy when you want to perform the localization of an application. It enables a developer to develop an application for consumers who use different languages. The translate API can also be used to build a basic language translator application.

This article will take the reader through a step-by-step procedure of Integrating Google Cloud Translate API. In the end, the user should have set up a running application that takes in a text from one language and outputs the text in a different language. Follow along to know more.

### Key takeaways: 
1. What is Google Translate?
2. Setting Google Translate in Google Cloud
3. Language Translation in Nodejs using Translate API

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @mercymeave
