### ISSUE TITLE
A dive into python strings

### ISSUE THREAD

**Issue by diannesandra** [section-engineering-education/engineering-education#2406]
### Proposed title of article
A dive into python strings

### Introduction paragraph (2-3 paragraphs):
The string data type is a crucial data type for every programmer. In python, strings are arrays of characters. Python provides a variety of operations that a programmer can perform with strings.

At the end of this tutorial, the reader should be able to have a complete understanding of string operations in python. The tutorial will guide the reader to write programs that incorporate strings in python. Among the operations include extracting string portions, modifying and manipulating string data.

### Key takeaways: 
1. Introduction to strings in python
2. Manipulating strings
3. Major string operations in python.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @diannesandra
