### ISSUE TITLE
Getting started with Docker, Spring Boot JMS and  ActiveMQ

### ISSUE THREAD

**Issue by paulodhiambo** [section-engineering-education/engineering-education#2408]
### Getting started with Spring Boot JMS and  ActiveMQ
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
The communication between Spring Boot microservices becomes slow whenever the number of HTTP requests increases, this leads to an overall slow performance of the entire system. Java Message Service(JMS) through message broker (ActiveMQ) solves the problem of slow HTTP connections between the services through the use of point to point model of communication.

In the article I will explain how to create,  add support for JMS in a Spring Boot application and connect to ActiveMQ instance running in a Docker container. 

### Key takeaways: 
1. Integrating JMS into a Spring Boot application.
2. Connecting to ActiveMQ instance running on a Docker Instance.

### References: 
N/A

**Comment by hectorkambow** [comment]
Noticed there are two open - will close this one for now - until the other one is merged 👍
