### ISSUE TITLE
Handling Recyclerview Clicks the Right Way

### ISSUE THREAD

**Issue by JoelKanyi** [section-engineering-education/engineering-education#2409]
### Proposed title of article
Handling Recyclerview Clicks the Right Way

### Introduction paragraph (2-3 paragraphs):
The RecyclerView class supports the display of a collection of data. It is a modernized version of the ListView and the GridView classes provided by the Android framework.

When trying to handle clicks on a RecyclerView, many developers tend to do it the wrong way which is against android  best practices. There are a number of ways that we can do this, but for this article we will use the most appropriate way. This means creating a Click Class that has appropriate methods inside the adapter class.

### Key takeaways: 
- What is a RecyclerView?
- Handling clicks in a RecyclerView?
- Cons of using other method?

### References: 
- [Android Documentation] (developer.android.com/)

**Comment by hectorkambow** [comment]
@JoelKanyi Just wanted to make sure that this artile will not repeat or overlap with what has been created before or published via our [EngEd docs](https://www.section.io/engineering-education/search/?q=RecyclerView).

**Comment by JoelKanyi** [comment]
The article won't overlap or repeat from what has already been written. 

https://www.section.io/engineering-education/android-recyclerviews/

The article article above will act as a point of reference because it just explain the basics of a recyclerview. My article will be an advancement of it (using ListAdapter and Diff Util Callbacks) and it also talks about handling clicks on the recylerview.

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @JoelKanyi  👍  

Sounds good thank you for the clarification 🚀 looking forward to it.
