### ISSUE TITLE
Common npm commands used in Node.js

### ISSUE THREAD

**Issue by lokalawashington** [section-engineering-education/engineering-education#2412]
##Introduction
As a beginner, you need to understand basic NPM commands to learn Node.js. Being a JavaScript Developer with 2years of experiences, I have come to share my insights on "Common npm commands used in Node.js".
Knowing npm commands is one of the ways that will help you to write your Node.js codes with ease and be productive in your development journey.

Anyway, " NPM is a package manager for Node.js  that is used for frontend and backend ". 
Key takeaways:
At the end of this article, you should be familiar with some NPM commands, that you would want to proceed in learning Node.js, if you have not:
    1. You will know how to fork and use Node.js related project from GitHub.
    2. Help and short hands commands list
    3. How to create package.JSON and setting the defaults
    4. Installing, updating and upgrading NPM packages
    5. Installing specific versions
    6. Search for packages
    7. NPM registry
    8. Prunning

References:
N/A

**Comment by hectorkambow** [comment]
Just wanted to make sure that this artile will not repeat or overlap with what has been created before or published via our [EngEd docs.](https://www.section.io/engineering-education/search/?q=NPM)

@lokalawashington

**Comment by lokalawashington** [comment]
In reference to https://www.section.io/engineering-education/beginner-guide-to-npm/ my article will cover more.

**Comment by hectorkambow** [comment]
@lokalawashington  Thank you for the great topic - we actually started slow down our EngEd focus with Node.js - as we have a great growing # of Node.js article in our EngEd library - and we'd like to even out the # of articles in other topic areas. 

If you could try to shift your article focus to another area 🚀  

That would be great  - this came through today or I would have mentioned it yesterday.
