### ISSUE TITLE
Getting started with PHP Superglobals

### ISSUE THREAD

**Issue by awinomackrine** [section-engineering-education/engineering-education#2413]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting started with php superglobals

### Introduction paragraph (2-3 paragraphs):
Superglobal varriables unlike the common PHP varriables we declear in php code are inbuild  predefined varriables that are always accessible from any part of the code. They are accessed freely by any function, class or even any file without any complications.

 This article will be stating and introducing the different types of PHP supergolbal varriables,  explaining their fuctionalities and finally explaining how they can in implemented if PHP code.
### Key takeaways: 
-The reader should be able to understand the different superglobal varriables available in PHP.
-The reader should understand the functionalities of the different superglobal varriables in PHP.
-The reader should be able to implement the different superglobals in their PHP codes successfully.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @awinomackrine
