### ISSUE TITLE
Using Entropy and Information Gain to Build Decision Trees in Machine Learning

### ISSUE THREAD

**Issue by collins-a** [section-engineering-education/engineering-education#2414]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article

Using Entropy and Information Gain to Build Decision Trees in Machine Learning

### Introduction paragraph (2-3 paragraphs):

A decision tree is a supervised learning algorithm used for both classification and regression problems. Simply put, it takes the form of a tree with branches representing the potential answers to a given question. There are metrics used to train decision trees. One of them is information gain. In this article, we get to understand how information gain is computed, and how it is used to train decision trees.

### Entropy

Entropy is an information theory metric that measures the impurity or uncertainty in a group of observations. It determines how a decision tree chooses to split data. The image below gives a better description of the purity of a set.

![purity](/engineering-education/Entropy/purity.png)

[Source](https://towardsdatascience.com/what-is-entropy-and-information-gain-how-are-they-used-to-construct-decision-trees-aadf7d0728f0)

Consider a dataset with N classes. The entropy may be calculated using the formula below:

$$ E = - \sum\limits_{i=1}^{N} p_i log_2 p_i $$

$p_i$ is the probability of randomly selecting an example in class $i$. Let’s have an example to better our understanding of entropy and its calculation. Let’s have a dataset made up of three colours; red, purple and yellow. If we have one red, three purple and four yellow observations in our set, our equation becomes:

$$ E = - (    p_r log_2 p_r  + p_p log_2 p_p + p_y log_2 p_y   ) $$

### Information Gain

We can define information gain as a measure of how much information a feature provides about a class. Information gain helps to determine the order of attributes in the nodes of a decision tree. The main node is referred to as the parent node, whereas sub nodes are known as child nodes. We can use information gain to determine how good the splitting of nodes in a decision tree. It can help us determine the quality of splitting, as we shall soon see. The calculation of information gain should help us understand this concept better.

$$ Gain = E_{parent} - E_{children} $$

### Key takeaways: 

The reader should:

1. Get a brief introduction to decision trees.
2. Learn entropy theory and formula.
3. Understand how information gain is calculated.
4. Learn the steps to use information gain to build a decision tree.

### References: 

1.	[What is Entropy and Information Gain?](https://towardsdatascience.com/what-is-entropy-and-information-gain-how-are-they-used-to-construct-decision-trees-aadf7d0728f0)

2.	[A Simple Explanation of Information Gain and Entropy](https://victorzhou.com/blog/information-gain/)

3.	[Information Gain and Mutual Information for Machine Learning](https://machinelearningmastery.com/information-gain-and-mutual-information/)

4.	[Entropy and Information Gain in Decision Trees](https://towardsdatascience.com/entropy-and-information-gain-in-decision-trees-c7db67a3a293)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @collins-a
