### ISSUE TITLE
Audio signal processing using Matlab

### ISSUE THREAD

**Issue by queenterbruce063** [section-engineering-education/engineering-education#2415]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
A signal describes how some physical quantity varies over time and/or space. Signal processing involves the manipulation of signals to change their characteristics or extract information. Matlab provides a tool for the creation and manipulation of discrete-time signals. This involves the reading and analysis of this signal. It focuses on altering the sounds, methods used in musical representation, and telecommunication sectors.
In this article, we will discuss the filtering methods for various signals. We will also look at the graphic equalizer, echo effect, flange, and reverb effect. We will look at the low pass filter which is used to remove the white Gaussian noise from a signal.  We major on the spectral processing techniques of relevance for the description and transformation of sounds, practical knowledge with which to analyze, synthesize, transform and describe audio signals in the context of music applications

### Key takeaways: 
- Understanding and using the signal processing toolbox
- Understanding basic filtering:low pass filter.
- understanding the practical implementation of signal processing in audio signal processing.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @queenterbruce063
