### ISSUE TITLE
Understanding Quality of Service (QoS)

### ISSUE THREAD

**Issue by Su-sid** [section-engineering-education/engineering-education#2416]
### Proposed title of the article
Understanding Quality of Service (QoS)

### Introduction paragraph (2-3 paragraphs):
People optimise their networks so that these networks can perform at their full potential. QoS is an essential set of technologies in networking that allow you to optimise your network, allowing it to run at its full potential. Having an optimised network ensures that intensive applications run efficiently due to the availability of adequate network resources.

### Key takeaways:
* The reader will gain an understanding of what is Quality of Service

* How QoS utilises traffic marking, queuing, and the resource reservation protocol to guarantee the optimal performance of critical applications on a network.

* The importance of QoS on a network.

* The best scenarios to use QoS

### References:
* https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc787218(v=ws.10)?redirectedfrom=MSDN
* https://www.tutorialspoint.com/what-is-rsvp-resource-reservation-protocol

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @Su-sid
