### ISSUE TITLE
Create a 3D World in react using Three.js and React Three Fiber

### ISSUE THREAD

**Issue by franciskaguongo** [section-engineering-education/engineering-education#2417]
### Proposed title of the article

Create a 3D World in react using Three.js and React Three Fiber

### Introduction paragraph (2-3 paragraphs):

3D environments have come a long way ever since their first appearance in computers in the '60s. It was followed up by 3D modeling which was seen in the '70s. Their quick rise in popularity is due to the additional dimension of objects visible. This copied real-life object characteristics. 3D objects have been fascinating sites to behold during our interaction with computers, whether in games, videos, websites, or even simulations. Unlike 2D objects, more angles, light, shade, and contrast are visible hence appealing. You can read more on 3D objects and how to acquire them and their importance in [this](https://www.section.io/engineering-education/how-to-insert-3d-objects-into-a-webpage-using-html-and-css/) article. 

As we speak today, there are more characteristics, features, formats, and aspects of both 3D environments and objects than ever. We all expect the trend to increase both in discoveries, invention, and popularity as time goes by.

In this tutorial, you will learn how to create a 3D World in React using Three.js and React Three Fiber. 

### Key takeaways: 

At the tip of this tutorial, you will be able to know the following:

- What are 3D Worlds
- What is Three.js and React Three Fibre
- How does React Three Fibre work
- How to create 3D worlds in React
- How to interact with the 3D Worlds and objects in them

### Pre-Requisites

Basic knowledge and understanding of the following are required:

- React. If you are new to it, you can check the [documentation](https://reactjs.org/docs/) to start a step-by-step learning journey.
- An IDE installed and configured in your machine. I recommend the usage of Visual Studio Code. Download it [here](https://code.visualstudio.com/).
- A stable internet connection.

### References: 

- [How to Insert 3D Objects into a Webpage using HTML and CSS])(https://www.section.io/engineering-education/how-to-insert-3d-objects-into-a-webpage-using-html-and-css/).
- [Three.js documentation](https://threejs.org/docs/).
- [React Three Fibre documentation](https://github.com/pmndrs/react-three-fiber).
- [Three.js website](https://threejs.org/).
- [React Documentation](https://reactjs.org/docs/).

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @franciskaguongo 

I'd suggest cutting down any fluff and jump straight to the tutorial after a brief intro - to get the audience up and running 🚀

**Comment by hectorkambow** [comment]
@franciskaguongo 
Just pinging you on this topic form - as Im making some room in the topic queue.

No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by franciskaguongo** [comment]
> @franciskaguongo
> Just pinging you on this topic form - as Im making some room in the topic queue.
> 
> No rush if you're still working on this one - if you need more time we can always re-open at a later date.

Finished it, let me just create the pr

**Comment by franciskaguongo** [comment]
@hectorkambow am done with the article, could you reopen the issue so that I can push it

**Comment by franciskaguongo** [comment]
Thanks
