### ISSUE TITLE
Node.js Native Http Module

### ISSUE THREAD

**Issue by FeezyHendrix** [section-engineering-education/engineering-education#2419]
### Proposed title of article
Node.js native http module

### Introduction paragraph (2-3 paragraphs):
This article is to explain how we can use native http modules in Node.js rather than installing a library. 

### Key takeaways: 
 - Introduction and Understanding of the native http module.
 - Abstracting over the http module.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [Node.js v16.2.0 documentation](https://nodejs.org/api/http.html)
- [Making HTTP requests with Node.js](https://nodejs.dev/learn/making-http-requests-with-nodejs)

**Comment by hectorkambow** [comment]
@FeezyHendrix 
Seems like a nice topic - but there is not much for me to go off here - we ask students to include the first couple sentences of the article for us to better gauge the incoming quality 👍 

Please add a bit more detail - by including the first couple paragraphs of the article.

**Comment by hectorkambow** [comment]
@FeezyHendrix 

Thank you for the great topic - we actually started slow down our EngEd focus with Node.js - as we have a great growing # of Node.js article in our EngEd library - and we'd like to even out the # of articles in other topic areas. 

If you could try to shift your article focus to another area 🚀  

That would be great
