### ISSUE TITLE
Docker Images with Google Cloud

### ISSUE THREAD

**Issue by doloresmia** [section-engineering-education/engineering-education#2422]
### Proposed title of article
Deploy Docker Containers to Google Cloud

### Introduction paragraph (2-3 paragraphs):
Docker is a containerization tool used to deploy and run applications using containers such that an application and its libraries are packaged together.
In this article, we will understand how to deploy Docker images into google cloud.

### Key takeaways: 
1. Containerization of an application with docker.
2. Setting up google cloud for Docker containers
3. Deploying Docker containers to Google cloud.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved 

@doloresmia 
We had some recent docker articles publish. 👍  Please see if those can be references or built upon 🚀
