### ISSUE TITLE
How to Make a Discord Bot using Python

### ISSUE THREAD

**Issue by harshitab13** [section-engineering-education/engineering-education#2424]
*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### How to Make a Discord Bot using Python

<br>

### Introduction
Discord is most used apps nowadays by companies, students and work professional and bots make it easy to protect our server from spams, greeting new people, verification , enjoyment and many more... .So I will give a full tutorial so that everyone can make their own bots using python for their servers, 

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

1. Will learn how to make a bot using python
2. Add to the reader's skills to their most-using app and learn a bit about coding in python if not familiar yet.
3. How to use bot commands, checks, and converters.
4. How to create a Discord connection in Python.

### References: 
N/A

There is an article in EngEd about making a bot using node.js so I thought it would be helpful if one can also learn how to make it using python

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved 
@harshitab13  

Do not forget to add soruces for sentences like : "Discord is most used apps nowadays by companies, students and work professional and bots make it easy to protect our server" - this is not an opinion statement therefore needs sources. 👍
