### ISSUE TITLE
Why Not Use Virtual Machines instead of Containers for Microservices?

### ISSUE THREAD

**Issue by erixbiz** [section-engineering-education/engineering-education#2426]
### Proposed title of article
Why Not Use Virtual Machines instead of Containers for Microservices?

### Introduction:
Virtual Machines offer virtualization of hardware as well as the OS and create an efficient, isolated duplicate of a real machine. In the case of containers, only the OS is virtualized and not the hardware, creating a lightweight environment that houses the application and the dependent assets.
In this software era of constant evolution, it is common to use containers for microservices and there is a need to modernize monolithic applications.
But when microservices come into the picture, the question :  “containerize or virtualize?” seems to be frequent. This article will answer and address the issue by comparing containers and VMs from a microservices architecture viewpoint.

### Key takeaways: 
In this article, the reader will understand:
- the concept of microservices and how microservices benefit an enterprise application
- why use the containers for microservices
- benefits of using containers over VMs for microservices

### References: 
N/A

**Comment by WanjaMIKE** [comment]
```Already covered```

https://github.com/section-engineering-education/engineering-education/pull/2301
