### ISSUE TITLE
PM2 with Node.js

### ISSUE THREAD

**Issue by HARITJOSHI1** [section-engineering-education/engineering-education#2434]
### Proposed title of the article
PM2 with Node.js

### Introduction paragraph (2-3 paragraphs):
In today's world, every enterprise-level project have very complex and large backend clusters, and managing the server process is of utmost importance and one of the best solutions for this is PM2. PM2 or Process Manager 2 is an incredibly versatile production process manager written in Node.js. 

This article will cover PM2, its advantages, how to use it, and why PM2 is popular amongst organizations. This article will also help new developers to get started with PM2 and have an in-depth knowledge of PM2 so that they can take the advantage of this robust tool to automate their node applications.

### Key takeaways: 
1. Readers will learn about PM2 and how to use it in Node.js applications.
2. Readers will be able to realize why PM2 is so successful in process management for Node applications.
3. Readers can get started using PM2.
4. Readers will know more about Node.js

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @HARITJOSHI1
