### ISSUE TITLE
Understanding @Output and EventEmitter in Angular

### ISSUE THREAD

**Issue by odiwuoramos** [section-engineering-education/engineering-education#2435]
### Proposed title of article
Understanding @Output and EventEmitter in Angular

### Introduction paragraph (2-3 paragraphs):

Angular is based on a one-directional data flow and does not have two-way data binding. So, how do you get a component to emit an event to another component?
In Angular, a component can emit an event using @Output and EventEmitter. Both are parts of the @angular/core.

Angular components are the fundamental building blocks of architecture. Once you’ve understood component architecture, you can build a picture in your head as to how to assemble your interface based on data communication.

In this post we’re going to dive into Angular components and how to use the EventEmitter and Outputs, so we can transfer or notify any parent component that something has changed, or we would like to change it. This is typically done via “events”, hence our “EventEmitter” and is designed around a uni-directional data flow system that adopts a much more reasonable approach to application development.

### Key takeaways: 
1.Understanding @Input decorator  
2.Understanding @Output decorator  
3. Angular Event Emitters

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @odiwuoramos 

Mind you minor grammatical errors - to speed up publishing 🚀
