### ISSUE TITLE
Why and when you should use Kubernetes?

### ISSUE THREAD

**Issue by erixbiz** [section-engineering-education/engineering-education#2440]
### Proposed title of article
Why and when you should use Kubernetes?

### Introduction:
Kubernetes is a powerful container management tool that automates the deployment and management of containers. Kubernetes is the next big wave in cloud computing and it’s easy to see why as businesses migrate their infrastructure and architecture to reflect a cloud-native, data-driven era.
Before the business decides to use Kubernetes, the question of why or when Kubernetes should be used arises. This article will address the issue.

### Key takeaways: 
At the end of this article the learner will be able to:
- understand the overview of Kubernetes and container orchestration
- know the top reasons why a business should go for Kubernetes and the benefits it offers
- understand the instances when Kubernetes can be used or not used

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already). - approved @erixbiz
