### ISSUE TITLE
How to implement Structured Logging in Adonisjs

### ISSUE THREAD

**Issue by Kaperskyguru** [section-engineering-education/engineering-education#2442]
### How-To Guides Overview 
I will be showing you the best practice in implementing Structured in Adonisjs, discussing in detail the best ways involved in implementing a scalable Logging System in your RESTFUL API. We will build a real-world app to demonstrate how to debug easily with a good Structured Log in AdonisJS.

### What is the Scope and Purpose of the Guide
Students will learn how to build a high-maintainable app with Adonisjs
Students will learn how to implement a Structured Logging in AdonisJS Restful API
Students will learn how to choose what to Log and how to Log it.
Students will learn about the concept of Structured Logging and how to maintain a large App with it.
Students will learn best practices in building large-scale Web apps with AdonisJS.

References:
https://www.scalyr.com/blog/the-10-commandments-of-logging/
https://stackify.com/what-is-structured-logging-and-why-developers-need-it/
https://www.loggly.com/blog/30-best-practices-logging-scale/

**Comment by Kaperskyguru** [comment]
Hello @hectorkambow,

What's the status of this?

**Comment by hectorkambow** [comment]
@Kaperskyguru  seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved 

Apologies for the delayed response - we try to approved at the same time we published 🚀

**Comment by Kaperskyguru** [comment]
Thanks.

**Comment by hectorkambow** [comment]
@Kaperskyguru 
Just pinging you on this topic form - as Im making some room in the topic queue.

No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by Kaperskyguru** [comment]
Yeah. I am almost done with this. Sorry for delaying. I will send my first draft by Monday.
