### ISSUE TITLE
Image processing with Coil in Android using Kotlin

### ISSUE THREAD

**Issue by nonimdiana** [section-engineering-education/engineering-education#2443]
![](https://camo.githubusercontent.com/8040af2643fa01e37a03d46457e643baad6ea5dafe15707386b8164ddd942de7/68747470733a2f2f63646e2e6f7572636f6465776f726c642e636f6d2f7075626c69632d6d656469612f67616c6c6572792f67616c6c6572792d356536626366643063366132352e706e67)
### Proposed title of article
Image processing with Coil in Android using Kotlin

### Introduction paragraph (2-3 paragraphs):

An application that doesn't process images, is pretty weird and tedious nowadays. One of the essential skills that an Android developer should have is knowing how to correctly work with images especially from a remote source. Nevertheless, this can be done in different ways based on the feature you want to implement in your app. In most cases, you might need to perform not only loading but also memory and disk caching, down-sampling the image in memory, re-using Bitmaps, and automatically pausing/cancelling requests.

In this tutorial we will learn how to perform the above mentioned tasks and many more using a **fast**,  **lightweight**, and **easy-to-use** library called `Coil`. This library is made in 100% Kotlin which makes it suitable for modern Android development.

### Key takeaways: 

By the end of this tutorial, the reader is expected to be able to:

1. Understand why Coil is preferred over other image processing libraries.
2. Load images from  remote sources using Coil.
3. Perform various image transformations.
4. Effectively handle errors encountered in any task.

### References: 

N/A

**Comment by hectorkambow** [comment]
closing for now - can be reopened when the 1st on is published.

**Comment by nonimdiana** [comment]
Hey @hectorkambow, could you please reopen this! The other one has been merged 🎉

**Comment by hectorkambow** [comment]
@nonimdiana 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please references any relevant EngEd articles in yours. - Approved
