### ISSUE TITLE
Building a Digital Clock using JavaScript

### ISSUE THREAD

**Issue by Nomzy-kush** [section-engineering-education/engineering-education#2450]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Building a Digital Clock using JavaScript

### Introduction paragraph (2-3 paragraphs):
Building a digital clock is a great project to put your hands on if you just learned javascript. It is quite simple for people of any skill level. In this article, you will be taken through the various HTML and CSS elements along with JavaScript used in building a simple digital clock. This is a must-do project for you if you just learned JavaScript. 

### Key takeaways: 
1. Readers will be able to build a functional digital clock using just HTML, CSS, and JavaScript
2. Readers will learn how to use javascript classes and the native date object to bring out current-time information.
3.Readers will learn how to use web languages/tech to create something tangible.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Nomzy-kush Love the type of tutorial - but just wanted to make sure it does not overlap too much with this topic: 
https://www.section.io/engineering-education/how-to-build-a-clock-with-javascript-and-svg/
