### ISSUE TITLE
Filter Machine with Vanilla JavaScript

### ISSUE THREAD

**Issue by Taiwrash** [section-engineering-education/engineering-education#2452]
### Proposed title of article
Creating functional filter/search feature with JavaScript

### Introduction paragraph (2-3 paragraphs):
In this article we will be building a filter bar which respond to user search in real time using vanilla javascript. Most amazing part is the step by step explanation of each code snippet

### Key takeaways: 
- Readers will be able to build search/filter app with JavaScript
- Improve CSS and HTML skills
- implement new JavaScript methods
- Learn how to use online tools to code

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @Taiwrash 

For the next topic form - try to provide a bit more context for us to better gauge incoming overall quality 🚀  
Thank you
