### ISSUE TITLE
HOW TO DEPLOY A STREAMLIT APP WITH DOCKER

### ISSUE THREAD

**Issue by Bravinsimiyu** [section-engineering-education/engineering-education#2454]
### Proposed title of article
How to deploy streamlit app with docker

### Introduction paragraph (2-3 paragraphs):
Docker is a tool designed to make it easier to create, deploy, and run applications by using containers, here after building a machine learning app with streamlit we can now use Docker to deploy the app through the dockerlizing the streamlit app and finally deploying it.
We will basically go through the steps of installing docker to creating docker containers to finally deploying the streamlit app using docker

### Key takeaways: 
1. The installation process of docker.
2. Creating a virtual environment for the streamlit app.
3. The steps involved in building a docker file.
4. Creating a docker image.
5. Creating a docker container.
6. Deploying the streamlit app using docker.

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @Bravinsimiyu
