### ISSUE TITLE
 C# Enumerations (Enum)

### ISSUE THREAD

**Issue by Jeff-mwangi** [section-engineering-education/engineering-education#2455]
### Proposed title of article
 C# Enumerations (Enum)

### Introduction paragraph (2-3 paragraphs):
In C#, an `enum` (or enumeration) is used to assign constant names to a group of numeric integer values. The names make a program easy to read and maintain. For example, the days of the week can be defined as an enumeration and used anywhere in the program. The enumeration is defined with the help of the keyword `enum`.

In this article, we shall look at what is an `enum`, how to declare them and access them.
### Key takeaways: 
1. What it is an Enum
2. Syntax of an Enum
3. How to access an Enum
4. Interesting facts and rules about initialization of enum.
### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @Jeff-mwangi
