### ISSUE TITLE
What are White-Hat and Black-Hat SEO Techniques?

### ISSUE THREAD

**Issue by kvardhan10** [section-engineering-education/engineering-education#2458]
### Proposed title of article
What are White-Hat and Black-Hat SEO Techniques?

### Introduction paragraph (2-3 paragraphs):
Search Engine Optimization(SEO) is a kind of internet advertising method in which the websites are optimized to enhance the quality and quantity of their search engine traffic. It is beneficial due to the fact that a website will get hold of extra traffic from a search engine by getting ranked better at the Search Engine Results Page(SERP). This article will address two types of SEO techniques namely, White-Hat and Black-Hat.

White hat SEO technique is the way of using optimization techniques that comply with the policies and rules given by the search engines. Similarly, black hat SEO technique is the way of using optimization techniques that do not comply with the policies and rules given by the search engines. 

### Key takeaways: 
The reader will be able to understand:
- What is SEO?
- How does it help?
- White-Hat and Black-Hat SEO Techniques
- Functionalities of the same
- Which one to opt for?

### References: 
https://www.weidert.com/blog/white-hat-seo-black-hat-seo

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @kvardhan10

**Comment by hectorkambow** [comment]
Although I think this a very cool topic - it may be steering a bit too much from our software realm. 

Perhaps we could circle it back around - what softwares can integrate with SEO. 

Im having a difficulty thinking how we could tie this more into our software realm. 

For the time being - please try to find another topic @kvardhan10  

Thank you.

**Comment by hectorkambow** [comment]
We do have a few topics written on SEO in the past - perhaps these would help better craft a topic around SEO. 

https://www.section.io/engineering-education/search/?q=seo 

Becuase I do think its a good topic - just trying to tie it more into the software developer world - if that makes sense. 🚀  @kvardhan10

**Comment by kvardhan10** [comment]
Hey @hectorkambow 
Yes, when I thought of working on this topic, I considered it to be a descriptive one. Just a simple article explaining what 'White-Hat and Black-Hat SEO Techniques' are. Also, I knew there were SEO-related articles and I was going to backlink them too. I understand this article's content is descriptive and explanatory and that it does not go with software POV. 

So, I thought maybe I will start the article by describing what "White-Hat and Black-Hat SEO" is. Then I'll introduce the readers to some SEO marketing tools, keyword tools, ranking tools such as Ahrefs, SEMRush, SE Ranking, SpyFu, or Yoast (which is a SEO plugin for WordPress)

How does that sound? Will that be okay?

**Comment by hectorkambow** [comment]
🙌 sounds great - thank you for the follow up @kvardhan10 
approved

**Comment by hectorkambow** [comment]
@kvardhan10 
Just pinging you on this topic form - as Im making some room in the topic queue.

No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by kvardhan10** [comment]
Sorry @hectorkambow . My bad! I have the article ready just some last-minute correction needs to be done. I got hung up on some other things. I will definitely submit the PR by EOD🚀

**Comment by kvardhan10** [comment]
Hey @hectorkambow . I have submitted the PR for this issue. While I was writing this article, I discovered most of the parts I wrote revolved around "What is SEO? Why it is helpful? Factors affecting SEO, Types of SEO techniques, and then some SEO marketing tools". Its not just about black hat and white hat, but more than just those two topics.
So will it be okay if I change the article's name to "A Beginner’s Guide to Search Engine Optimization"

**Comment by kvardhan10** [comment]
Also, have I submitted the PR correctly, regarding the branching of the repo?
I haven't done this in months and wondered whether the process has changed or is still the same.

**Comment by hectorkambow** [comment]
The repo structure has changed - so please do a git pull on your forked repo before submitting the PR - I just checked it has the old structure - won't be able to merge it like that 👍

**Comment by kvardhan10** [comment]
> The repo structure has changed - so please do a git pull on your forked repo before submitting the PR - I just checked it has the old structure - won't be able to merge it like that 👍

I see...so I should Pull all the updates from the original repo to my forked repo. I used to submit my PR by adding the article in the /articles directory. But now it should be done in the /content/articles directory. Did I get that right?

And to do that I should first fork my repo and then fetch from the upstream repo to keep my forked one updated - by "Fetch and Merge"
![forked](https://user-images.githubusercontent.com/67724353/126107217-a87ace6f-c384-4481-8969-923cbd915639.png)

Sorry, this is my first time doing something like this. Just wanted to clarify my doubts and refrain from doing any big blunders.
