### ISSUE TITLE
Creating responsive layouts with MaterialUI in ReactJS

### ISSUE THREAD

**Issue by Caleb335** [section-engineering-education/engineering-education#2463]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Creating responsive layouts with MaterialUI in ReactJS

### Introduction paragraph (2-3 paragraphs):
Oftentimes, when we build websites or web applications, one of the important aspects of the whole process is to make it responsive, asides from the functionalities. 

Making a web(site/app) responsive is among the quirks of accessibility that it must have so anyone with any type of device can be able to make use of the app or website.

Responsiveness has to do with how an application behaves and appears when it is being accessed on different devices. 

These devices range from mobile phones with different screen sizes and Personal computers or desktop computers. 

It is then, the obligation of a Frontend developer to create or write styles that would conform with the layout of the app to the different screen sizes of devices.

In this article we’d take a look at how to create layouts that are responsive at different device widths and breakpoints using a React framework, called [NextJS](https://nextjs.org/) and [Material UI](https://material-ui.com/) to make the process of creating such layouts less painful. 

### Key takeaways: 
The reader(s) will be able to grasp the following concepts when they're done reading this article:
- How to create a React application with nextJS
- Understand what Material UI is all about
- Components and Props

### References: 
None for now.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @Caleb335

**Comment by Caleb335** [comment]
Thank you @hectorkambow!

I'll ensure it does.
