### ISSUE TITLE
Working with Styled-components in React

### ISSUE THREAD

**Issue by OMONDIELLY** [section-engineering-education/engineering-education#2465]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Working with styled-components in React

### Introduction paragraph (2-3 paragraphs):
If you have worked with React in developing your applications, you will agree with me that adding style to your Components is super cool when using styled-components feature. In any case you have not used React or styled-components, do not worry because this article is for you.

Styled-components allows you to write CSS in your JavaScript application and we will leverage this to build our simple website.
In this tutorial, you will learn an overview of React and what styled-components is and why use it. In the end. we will build a simple web page in React and add styles to it using styled-components.

 
### Key takeaways: 
1. What is React.
2. What is styled-components.
3. Advantages of using styled-components.
4. Creating and styling a simple web-page using styled-components.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @OMONDIELLY
