### ISSUE TITLE
An Introduction to WhiteSource's Bolt GitHub App

### ISSUE THREAD

**Issue by crescentmusyoki** [section-engineering-education/engineering-education#2467]
### How-To Guides Overview 
WhiteSource is an open-source library management platform. It acts as a license and security compliance management platform for real-time alerts.
The software discovers opensource components in the app, alerts when a vulnerability is added to the projects being used.
.

### What is the Scope and Purpose of the Guide
Bolt discovers open-source components in an app and alerts when a potentially vulnerable piece of code is added to the ongoing development of a project. It also alerts when new vulnerabilities affecting an existing piece of software pop up. It does the following;
- Facilitate workflows within an application
- Realtime vulnerability alerts
- License compliance
- Package scanning for both public and private repositories. 
- Detects opensource components in the repositories UI, generate inventory and security compliance reports.
- Provides detailed information included a suggested fix.
- IDE integration. This provides practical remediation on vulnerabilities in the IDE.

**Comment by hectorkambow** [comment]
@crescentmusyoki 
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

**Comment by hectorkambow** [comment]
@crescentmusyoki 
Just pinging you on this topic form - as Im making some room in the topic queue.

No rush if you're still working on this one - if you need more time we can always re-open at a later date.
