### ISSUE TITLE
Building a loader using animations in Tailwind CSS.

### ISSUE THREAD

**Issue by M0nicah** [section-engineering-education/engineering-education#2468]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Building a loader using animations in Tailwind CSS.

### Introduction paragraph (2-3 paragraphs):
What you see on the screen while the rest of the page’s content is still loading is what is called loaders/preloaders.  They are a fun way to bring life into a webpage. Loaders can be simple or complex animations that may keep site visitors entertained as they wait for the servers to load the page content.
Although there are some websites that offer free loaders as GIFs, we could build our own! After all we are developers, right?

In this tutorial , you are going to be taken through the various Tailwind CSS classes , along with some custom CSS  used in building beautiful and fun loaders.

### Key takeaways: 
1. Readers will learn how to use the animation classes in Tailwind CSS and animation elements in custom CSS.
2. Readers will understand how loaders can improve user experience.
3. Readers will understand the importance of using simple loaders for their applications.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@M0nicah 
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

Be sure to link to any[ past Tailwind articles](https://www.section.io/engineering-education/search/?q=tailwind%20css) (if applicable).
