### ISSUE TITLE
Introduction To  C Programming Language

### ISSUE THREAD

**Issue by ghost** [section-engineering-education/engineering-education#2480]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of an article
Introduction To  C Programming Language

### Introduction paragraph (2-3 paragraphs):
C is probably the most widely known programming language and Basic language. It is used as the reference language for computer science courses and used in competitive programming all over the world, and it's probably the language that people feel difficult when they are starting programming, and this series I will explain everything from ground level  to  high level 

### Key takeaways: 
As this is the introduction to C 
- History of C
- Structure of C program
- Installing C in our System
- Writing the First C program
- Understanding the Code
- Files  used in C program
- Uses Of C

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@MouliDev 👋  Hello - Hector here from the EngEd program. 

Thank you for submiting what seems like would be a really helpful article - just wanted to make sure that it does not overlap too much with this [past article](https://www.section.io/engineering-education/history-of-c-programming-language/)

🤔

**Comment by MouliDev** [comment]
@hectorkambow Sir my article don't not overlap with past article
This is total different from past article
And i am sure for that

**Comment by hectorkambow** [comment]
@MouliDev 👍 
sounds good @ - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)

**Comment by MouliDev** [comment]
@hectorkambow Ok sir! Sure and Thanks
