### ISSUE TITLE
Bing Maps With Angular in a Spring Boot Application

### ISSUE THREAD

**Issue by owinowendy** [section-engineering-education/engineering-education#2482]
### Proposed title of article
Bing Maps With Angular in a Spring Boot Application
How to integrate Bing Maps with Angular to show different site properties at different points in time with a Spring Boot backend.

### Introduction paragraph (2-3 paragraphs):
The **AngularAndSpringWithMaps** project shows how to integrate Bing Maps, Angular, and Spring Boot with a Gradle build. The property data of the sites is stored with JPA in H2/PostgreSQL databases. 

The purpose of the **AngularAndSpringWithMaps** project is to show the site properties at different points in time. To choose the site and then choose the time and have the site properties displayed in a map. New properties can be added and deleted on the map and then persisted. This article will show how to store and display company sites.

### Key takeaways: 
1.The Spring Boot Backend.
2. The Angular Frontend.
3. How to integrate the Spring Boot and Angular to work together
4. How to use Bing Maps

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @owinowendy
