### ISSUE TITLE
Getting started with Django unit testing

### ISSUE THREAD

**Issue by qawuor** [section-engineering-education/engineering-education#2486]
### Getting started with Django unit testing
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Testing is vital. Without properly testing your code, you will never know if the code works as it should. Countless hours can be lost fixing problems caused by changes to the codebase. What’s worse, you may not even know that there are problems at all until your end-users complain about it, which is not how you want to find out about code breaks.

Having tests in place will help ensure that if a specific function breaks you will know about it. Tests also make debugging breaks in code much easier, which saves time and money.

In the article, I will explain how to create test cases for Django View, Templates, and models.

### Key takeaways: 
1. Setting up Django project and adding unit testing packages.
2. Writing unit tests for the views and models.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved 
@qawuor 

be sure to link to any past articles [that make sense](https://www.section.io/engineering-education/software-testing-part1/)
