### ISSUE TITLE
Creating a responsive navigation bar using Tailwind CSS and JavaScript

### ISSUE THREAD

**Issue by ianmasae** [section-engineering-education/engineering-education#2487]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Creating a responsive navigation bar using Tailwind CSS and JavaScript.

### Introduction paragraph (2-3 paragraphs):
What is a navigation bar? A navigation bar is a tool at the top most position of a webpage which is used by website visitors to easily steer through to different sections in the webpage. When a webpage is long, a navigation bar comes in handy. It helps the user to easily navigate through to specific sections of the webpage. A navigation bar should therefore, be simple and easy-to-use.
This article goes through creating our own responsive navigation bar using Tailwind CSS with some little bit of JavaScript from scratch. We will use the various Tailwind classes to create and style up our navigation bar.
 

### Key takeaways: 
1.	The reader will learn how to create a simple navigation bar.
2.	The reader will learn how to style up their own navigation bar and make it appealing.
3.	The reader will learn how to make a navigation bar responsive.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @ianmasae 

Be sure to link to any [past Tailwind articles](https://www.section.io/engineering-education/search/?q=tailwind%20css) (if applicable).

**Comment by ianmasae** [comment]
🚀
