### ISSUE TITLE
Network Automation and Automation tools

### ISSUE THREAD

**Issue by raboba2re** [section-engineering-education/engineering-education#2491]
#### Network Automation and Automation tools

During the industrial age, automation was use to reduce and potentially eliminates the needs of human intervention, thus making the process self driven. 
With the advancement in technology, automation has spread across all aspect of human life, from automatic building environmental controls to autonomous cars and planes.
Because setting up networks can be time consuming,especially in large organizations, configuration management tools are use to automate the configuration of network devices such as routers, switches, firewalls and serves. 
In this article, we will look at network automation and some popular automation tools in used.

### Key takeaways: 
- What automation and network automation is
-  Configuration management tools
- How tools such as **Ansible,  Chef  and  Salfstack** are use to automate networks

**Comment by hectorkambow** [comment]
@raboba2re Just closing this topic for now - I see you have another one open (duplicate PR - ready to be published) 
we can re-open this one asap once that one is published 👍

**Comment by raboba2re** [comment]
@hectorkambow  Thank you for your observation. The PR has been open  for long now, and it seems to be stagnant. That was why i decided to open a new issue, pending when the peer reviewer will decide to work on it.
