### ISSUE TITLE
Node.js place locator using Geojson

### ISSUE THREAD

**Issue by phinaomondi** [section-engineering-education/engineering-education#2493]
### Proposed title of article
Node.js place locator using GeojsonNode.js place locator using Geojson

### Introduction paragraph (2-3 paragraphs):
GeoJson is a standard format for storing geographic points in a database based on JavaScript Object Notation. GeoJson is based on JSON format making it easy to use with JavaScript. Geographic features encode using GeoJson include Latitude, Longitude, line strings and Polygons.

In this article, we are going to use GeoJson to build a locator application using Nodejs. We will develop an application that adds a location (for instance a school) on a database and be able to display the locations encoded on the database on a map display.
. 

### Key takeaways: 
1. Understanding GeoJson
2. Setting up MongoDB with Node.js
3. Encoding location data into MongoDB using mongoose.
4. Using Mapbox with Node.js

### References: 
1. https://geojson.io/
2. https://www.mongodb.com/
3. https://www.npmjs.com/package/mongoose

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@phinaomondi  Thank you for the great topic - we actually started slow down our EngEd focus with Node.js - as we have a great growing # of Node.js article in our EngEd library - and we'd like to even out the # of articles in other topic areas. 

If you could try to shift your article focus to another area 🚀  

That would be great

**Comment by phinaomondi** [comment]
Alright @hectorkambow . Thank you for the update.
