### ISSUE TITLE
Building a Telegram bot with Python

### ISSUE THREAD

**Issue by shosenwales** [section-engineering-education/engineering-education#2496]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Building a Telegram bot with Python

### Introduction paragraph (2-3 paragraphs):
This article will take you through how to to build a Telegram bot with Python. Will also walk you through how to deploy the bot to a server.

### Key takeaways: 
-How to Build a telegram bot
-How to deploy bot to pythonanywhere server
-Concept of building a bot with python

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@shosenwales seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

please be sure that it does NOT overlap too much with these [past telegram articles](https://www.section.io/engineering-education/search/?q=telegram)

**Comment by shosenwales** [comment]
Thanks Hector

I couldn't find any results after visiting the past telegram articles link.

**Comment by shosenwales** [comment]
Hi @hectorkambow , for some reason Telegram has stopped accepting wildcard https certificates for bots, so unfortunately Pythonanywhere free account cant be used.

I would like to change the hosting provider to Heroku
