### ISSUE TITLE
Storing data in Python using Json module

### ISSUE THREAD

**Issue by fely545** [section-engineering-education/engineering-education#2497]
### Proposed title of article
Storing data in Python using Json module

### Introduction paragraph (2-3 paragraphs):

Many of your programs will ask users to input certain kinds of information. You might allow users to store preferences in a game or provide data for a visualization.Whatever the focus of your program is, you’ll store the information users provide in data structures such as lists and dictionaries. When users close a program, you’ll almost always want to save the information they entered. A simple way to do this involves storing your data using the json module.

The json module allows you to dump simple Python data structures into a file and load the data from that file the next time the program runs. You can also use json to share data between different Python programs. Even better, the JSON data format is not specific to Python, so you can share data you store in the JSON format with people who work in many other programming languages. 

In this tutorial we'll learn how to save data using json.dump() and  json.load(), and reading user-generated data.

### Key takeaways: 

1.Using json.dump() 

2.Using json.load()

3.Saving and Reading User-Generated Data

### References: 
N\A

**Comment by ahmadmardeni1** [comment]
Approved - @fely545 
Please consider changing the title of your articles for something specific, like "Storing data in Python using Json module"
