### ISSUE TITLE
Creating an Audiobook with PyPDF3 and Pyttsx3

### ISSUE THREAD

**Issue by FREDERICO23** [section-engineering-education/engineering-education#2499]
### Proposed title of the article
Creating an Audiobook with PyPDF3 and Pyttsx3 (Python libraries)

### Introduction paragraph (2-3 paragraphs):
There's has never been a time in the history of humankind with so much knowledge to consume. This has caused a distracted world where what you read is what makes you. This, in turn, caused time deficiency among readers which has led to the creation of audiobooks. Whether working, driving or eating, you can consume a book.

But as a developer, you need not buy one when you can actually create one for free.

In this tutorial, we shall look at PyPDF3 and Pyttsx3 (Python libraries) and how to use them to create your own audiobook.

### Key takeaways:
* What isPyPDF3?
* What is Pyttsx3?
* Using both PyPDF3 and Pyttsx3 to create, use and save an audiobook in a .mp3 format.

### References:
* [Pyttsx3](https://pypi.org/project/pyttsx3/)
* [PyPDF3](https://pypi.org/project/PyPDF3/)

**Comment by hectorkambow** [comment]
@FREDERICO23 
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
