### ISSUE TITLE
Implementing an auto-typing feature in JavaScript

### ISSUE THREAD

**Issue by munubi254** [section-engineering-education/engineering-education#2501]
### Proposed title of the article
Implementing an auto-typing feature in JavaScript

### Introduction paragraph (2-3 paragraphs):
Auto-typing enhances the look of a site and improves user experience. One may want to animate his/her text content for the users to see when they visit the page.
It can be used to make eye-catching adverts for attracting customers. In this article, we will look at how to implement it in JavaScript.

### Key takeaways: 
We will learn about:
1. **IIFEs**(Immediately Invoked Function Expressions).
2. JavaScript timing methods.
3. Using IIFEs and the JavaScript timing methodsto create an auto-typing feature for text. 

### References: 
N/A

**Comment by hectorkambow** [comment]
@munubi254 

Seems like a helpful topic - lets please be sure it add value beyond what can be found in the official docs and other blog sites. Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
