### ISSUE TITLE
Introduction to Boosting Algorithms

### ISSUE THREAD

**Issue by bloodprashure** [section-engineering-education/engineering-education#2503]
Boosting algorithms have taken over almost all Kaggle notebooks. They have found their way into almost every award-winning model and have been the most sought-after techniques in Machine Learning. In this article, the reader is introduced to boosting algorithms, how they work and how to use them.

Key Takeaways:
1. Boosting algorithms
2. How they work
3. Examples of boosting algorithms
4. Using boosting algorithms to product results

References:
N/A

**Comment by ahmadmardeni1** [comment]
We covered this topic [here](https://www.section.io/engineering-education/ensemble-learning/) and [here](https://www.section.io/engineering-education/ensemble-bias-var/).
Does your article bring another value to the topic? Maybe code examples?

**Comment by ahmadmardeni1** [comment]
We covered this topic [here](https://www.section.io/engineering-education/ensemble-learning/) and [here](https://www.section.io/engineering-education/ensemble-bias-var/). 
Does your article bring another value to the topic? Maybe code examples? @bloodprashure

**Comment by bloodprashure** [comment]
Hey @ahmadmardeni1!
Yes, I plan on including code snippets and a little bit of math apart from the theory!

**Comment by ahmadmardeni1** [comment]
Approved - @bloodprashure 
Please change the title because this will not be an introduction and refer to the articles/tutorials I linked above.

**Comment by bloodprashure** [comment]
Will do, thanks!
