### ISSUE TITLE
Sequence diagrams in Object Oriented Analysis and Design

### ISSUE THREAD

**Issue by elijahndungu** [section-engineering-education/engineering-education#2511]
### Proposed title of article
Sequence diagrams in Object Oriented Analysis and Design

### Introduction paragraph (2-3 paragraphs):
In Object Oriented Analysis and Design, diagrams are vital tools that will ensure great success to the upcoming software. These diagrams must be related and therefore sequence diagrams go deep into the  interaction between the diagrams.
 Sequence diagrams has symbols that represent objects and the various interaction operations amongst the objects.

Once the sequence diagrams are incorporated in the analysis of the software, designing becomes very easy and more accurate.

### Key takeaways: 
1) What is Object Oriented Analysis and Design?
2) What are sequence diagrams?
3)Advantages of sequence diagrams.

### References:
N/A

**Comment by ahmadmardeni1** [comment]
This is not approved - @elijahndungu 
There are a lot of resources out there covering the topic in detail. 
We encourage you to make another suggestion.

**Comment by hectorkambow** [comment]
@elijahndungu To follow up on that:

We're really looking for original content, and based on the description that you've provided, it seems that information that you intend to cover is already readily available through the documentation. An alternate path might be to create a unique project using the concepts mentioned here.?

cc @ahmadmardeni1

**Comment by elijahndungu** [comment]
It's alright. I have pushed another request which is better. Thank you.
