### ISSUE TITLE
Getting started with Spring Boot caching

### ISSUE THREAD

**Issue by elizabeth962** [section-engineering-education/engineering-education#2512]
### Getting started with Spring Boot caching
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Caching is a part of temporary memory (RAM). It lies between the application and the persistence database. It stores the recently used data that reduces the number of database hits as much as possible. 

The primary reason for using cache is to make data access faster and less expensive. When the highly requested resource is requested multiple times, it is often beneficial for the developer to cache resources so that it can give responses quickly. Using cache in an application enhances the performance of the application. Data access from memory is always faster in comparison to fetching data from the database. 

In the article, I will explain how to add various caching mechanisms to a Spring Boot application.

### Key takeaways: 
1. Introduction to caching and caching mechanisms.
2. Adding caching to Spring Boot applications.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Approved - @elizabeth962 
Please make sure to refer to [our published content](https://www.section.io/engineering-education/search/?q=Spring%20Boot) about Spring Boot in your article.  And to add value beyond what is in the [official docs](https://spring.io/guides/gs/caching/).
