### ISSUE TITLE
Implementation of CI and CD in Java application(Linux) Using Shell and Docker Executor on GitLab

### ISSUE THREAD

**Issue by djayjames** [section-engineering-education/engineering-education#2518]
### Proposed title of article
Implementation of CI/CD in Java application(Linux) Using Shell and Docker Executor on GitLab

### Introduction paragraph (2-3 paragraphs):
There are numerous executors available for implementing CI/CD with GitLab Runner. Shell and Docker, on the other hand, are more popular, and we can easily configure a repository with these runners. These runners can be chosen based on the requirements and resources available. 
This article is primarily concerned with the Shell and Docker executors of Java Linux applications.

### Key takeaways: 
By the end of this article the reader will understand:

1. what Shell and Docker  executors are.
2. implementation of java on shell executor.
3. Implementation of java on docker executor.

### References: 
N/A

**Comment by hectorkambow** [comment]
@djayjames 
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
