### ISSUE TITLE
Understanding How kubernetes Networking Works

### ISSUE THREAD

**Issue by BridgetMwikali** [section-engineering-education/engineering-education#2519]
### Proposed title of article
Understanding How kubernetes Networking Works

### Introduction paragraph (2-3 paragraphs):
Kubernetes networking enables you to configure communication within your k8s network. It is based on a flat network structure, which eliminates the need to map ports between hosts and containers.

Kubernetes networking is an integral part of managing and making communication easier within a Kubernetes cluster. It manages a wide range of operations, such as handling internal container communication and exposing the containers to the internet. 

This article introduces the reader to Kubernetes networking and explains how it works.

### Key takeaways: 
1. What Is Kubernetes Networking?
2. Networking types in a Kubernetes cluster (Container-to-Container Networking, Internet-to-Service Networking, Pod-to-Pod Networking, and Pod-to-Service Networking). 
3. How kubernetes networking works.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

FYI we have recently published quite a few articls on K8 - so lets double check to make sure we are not overlapping with new articles. 
@BridgetMwikali
