### ISSUE TITLE
Understanding polymorphism & abstract classes using C#

### ISSUE THREAD

**Issue by mohamedgh16** [section-engineering-education/engineering-education#2520]
### Proposed title of the tutorial.
Understanding polymorphism & abstract classes using C#.

### Introduction paragraph(s):

**Polymorphism** is often referred to as the third pillar of object-oriented programming, after encapsulation and inheritance. *Polymorphism* is a Greek word that means "many-shaped". At run time, objects of a derived class may be treated as objects of a base class in places such as method parameters and collections or arrays. When this polymorphism occurs, the object's declared type is no longer identical to its run-time type.

**Polymorphism** is a very helpful concept when it comes to a single abstract idea used in different ways and shapes.
With polymorphism, you can define a single abstract class and reshape it in different ways to suit your methods & ideas. 

### Key takeaways:

- Understand the concept of polymorphism
- Understand abstract classes
- Multiple examples of polymorphism

### References:

https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/polymorphism

**Comment by ahmadmardeni1** [comment]
Approved - @mohamedgh16
