### ISSUE TITLE
Understanding Closures in Ruby

### ISSUE THREAD

**Issue by Njunu-sk** [section-engineering-education/engineering-education#2523]
### Proposed title of article

Understanding Closures in Ruby

### Introduction paragraph (2-3 paragraphs):

Closures is a sensitive concept in programming, it's a function whose body references a variable declared in its parent scope. In order to understand closures effectively we will tackle proc and lambda concepts, why it matters and it's differences. These key concepts can improve and introduce strong code designs.
With closures we can write effective and interesting code and provide an understanding to code written in other libraries.

### Key takeaways: 
Able to identify closures in a code base and write your own closures.
Define closures know what is lexical scoping and free variables.
Able to identify proc and lambdas.
Know the differences between proc and lambda and where to use if in need.

### References: 
- Ruby docs - https://ruby-doc.org/core-3.0.1/Proc.html
- Mastering Ruby Closures book
- The Well-Grounded Rubyist book

**Comment by hectorkambow** [comment]
@Njunu-sk 

seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
