### ISSUE TITLE
Creating a Single Page Application (SPA) using React routes.

### ISSUE THREAD

**Issue by NMJD** [section-engineering-education/engineering-education#2525]
### Proposed title of article
Creating a Single Page Application (SPA) using React routes.

### Introduction:
Single page application become a trend in the web. Many big companies use it to build modern web apps.
In traditional web apps pages are reloaded everytime you navigate through the links. But with the coming of SPA, web pages load once and you can navigate without reloading anything.
Among the cutting-edge technologies that give the possibility of building SPA, reactjs is one of the best. With the concept of react routers you can easily create a SPA in no time.
 
To correctly grasp the concepts, we will build a little blog SPA through the tutorial. However the main point is not building a great app but understanding the implementation of the spa in the app.  
This tutorial is a walkthrough towards a good understanding of what is a SPA and how to implement it with react routes. Please code along while following the tutorial to effectively understand the concepts..

### Key takeaways: 
At the end of this tutorial you will understand
 * What is a SPA
 * How to use react routes
 * How to manage the links in react

### References: 
* https://reactrouter.com/web/api/Link
* https://www.pluralsight.com/guides/understanding-links-in-reactjs
*
### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@NMJD 
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

cc @zolomohan  Does this overlap with any of our existing React articles ??

**Comment by zolomohan** [comment]
@hectorkambow checked all existing React articles. None of them go over React routes.
@NMJD Make sure your article provides more value than the existing documentations for React Routes.

**Comment by hectorkambow** [comment]
@NMJD 
Just pinging you on this topic form - as Im making some room in the topic queue.

No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by NMJD** [comment]
Hi there! I'm back, was busy with some stuff. Can I still write this article?
