### ISSUE TITLE
Why Unikernels may soon replace Docker?

### ISSUE THREAD

**Issue by ogoti-lilian** [section-engineering-education/engineering-education#2530]
### Proposed title of article
Why Unikernels may soon replace Docker?

### Introduction:
As the cloud-native ecosystem evolves, it is beginning to appear as if a challenger to containerization has emerged. In this article, I'm going to dive into what Unikernels are, and why they will be the most likely candidate to replace container-based infrastructure.

### Key takeaways: 
In this article, the learner will understand:
- what is meant by Unikernels
- comparisons between  containers and Unikernels
- the reason why containers may soon be replaced by Unikernels

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Approved - @ogoti-lilian
