### ISSUE TITLE
Transactions and transaction management in sql

### ISSUE THREAD

**Issue by Paul22691** [section-engineering-education/engineering-education#2534]
### Proposed title of article
Transactions and transaction management in sql

### Introduction paragraph (2-3 paragraphs):form by a user 
A transaction is a unit of work that is performed against a database. Transactions are units or sequences of work accomplished in a logical order whether in manual form by a user or automatically by an application.

A transaction is the propagation of one or more changes to the database. For example updating a record, deleting a record and creating a record.
### Key takeaways: 
1. Definition of a transaction
2. Transaction states
3. Properties of transactions
4. Transactional control commands
### References: 
N/A

**Comment by ahmadmardeni1** [comment]
You can find the same concepts [here](https://github.com/section-engineering-education/engineering-education/issues/2520).

Even if it is using another programming language but it is almost the same - Not approved @Paul22691

**Comment by ahmadmardeni1** [comment]
@Paul22691 The new topic (Transactions and transaction management in SQL) is covered in the documentation and. We're looking for original content, An alternate path might be to create a unique project using the concepts mentioned here.?

**Comment by Paul22691** [comment]
Hello @ahmadmardeni1 working with database needs one to be skilled and through this article a learner will be able to work with suitable examples, to enhance a better understanding to the learner and obtain better working skills on databases. Therefore far from other documentations this article will cover from a beginner to expertising his skills.

**Comment by ahmadmardeni1** [comment]
I see, but this content can be found easily on the internet, can you create a unique project using the concepts mentioned here? @Paul22691

**Comment by Paul22691** [comment]
Yes especially creating emphasis and an in depth on the transactional control commands @ahmadmardeni1

**Comment by ahmadmardeni1** [comment]
Topic Approved - @Paul22691 
Please make sure to create a unique project, change the title, and add more value than what they can find on the internet.
