### ISSUE TITLE
Document Your code with JSDoc

### ISSUE THREAD

**Issue by phinaomondi** [section-engineering-education/engineering-education#2536]
### Proposed title of article
Getting started with JSDoc

### Introduction paragraph (2-3 paragraphs):
JSDoc is a JavaScript Documentation Generator API that yields documentation for your JavaScript code. JSDoc documents your modules, libraries, data types, classes, methods and parameters. When writing your code, you need to add comments then JSDOC scans the comments and generates an HTML website for your documentation.

In this article, we will go over the use of JSDoc to generate a documentation for code snippets we will write. We will understand how to generate documentation for classes, methods, objects, variables and modules used in a program.

### Key takeaways: 
1. What is JSDoc ?
2. Initializing JSDoc
3. Writing comments usable with JSDoc in JavaScript programs
4. Generating code documentation with JSDoc

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Great topic, @phinaomondi. Topic suggestion approved. 

Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article on JSDoc very beneficial.
