### ISSUE TITLE
Introduction to Application Performance Management (APM) and its significance

### ISSUE THREAD

**Issue by Ernest715** [section-engineering-education/engineering-education#2537]
### Proposed title of article
Introduction to Application Performance Management (APM) and its significance

### Introduction paragraph (2-3 paragraphs):
The performance of computer application systems directly affects the output of businesses. For instance, a client getting irritated by slow application systems. Such clients are easy to lose when a company's service application system performs poorly. To prevent such financial and reputational losses, APM is used to ensure IT applications run smoothly and effectively. It is also used to maximize the utility of applications by, among other functions, detecting application issues that may cause poor performance or crushing of applications before it happens.
 
This article will enlighten application users with all there is to know about APM and its significance in financial production. It will focus on APM as a tool to measure performance and outline how the response time of applications is affected by peak load and how the applications use computer resources to get tasks completed. It describes the dimensions of APM in detail and outlines the challenges that may be experienced during its application.

### Key takeaways: 

The key take-homes of this article include but are not limited to;
•	Understanding of what Application Performance Management (APM) is and its purpose in IT applications
•	Knowledge of how performance metrics are used to measure the performance of applications
•	The ability to apply Application Performance Management (APM) in the identification of causes of delay in computer applications
•	Understanding of challenges that may be experienced in the implementation of Application Performance Management (APM), and knowledge of how to overcome them.

### References: 
n/a

### Templates to use as guides
n/a

**Comment by hectorkambow** [comment]
@Ernest715 

seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
