### ISSUE TITLE
Getting started with Jetpack Compose in Android

### ISSUE THREAD

**Issue by MaurineM** [section-engineering-education/engineering-education#2538]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

### Proposed title of article

Getting started with Jetpack Compose in Android

### Introduction paragraph (2-3 paragraphs):

Android’s current UI toolkit is over 11 years old now. Over this time, a lot of issues have been raised concerning the overall performance of the imperative paradigm used. Every Android developer would love to see all the pain points of the old view system and XML layouts go away.

Jetpack Compose is a modern toolkit designed to simplify UI development in Android. It combines a reactive programming model with the conciseness and ease of use of the Kotlin programming language. It is fully declarative, meaning you describe your UI by calling a series of composable functions that transform data into a UI hierarchy.

 This article will walk you through the fundamental concepts that you need to get started with this new paradigm.
  
### Key takeaways: 

In this article, the reader will learn:

1. Why we need Jetpack Compose.
2. How to build UIs with Compose.
3. How to manage states in composable functions.
4. Data flow principles in Compose.
5. What to expect in Jetpack Compose version 1.0.0

### References: 

N/A

**Comment by hectorkambow** [comment]
@MaurineM 

seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

**Comment by MaurineM** [comment]
Thanks @hectorkambow, I'll make sure my article is unique and informative.
