### ISSUE TITLE
Setting up WordPress with Docker

### ISSUE THREAD

**Issue by mia-roberts** [section-engineering-education/engineering-education#2540]
### Proposed title of article
WordPress setup with Docker

### Introduction paragraph (2-3 paragraphs):
WordPress is an open source content management written in PHP. WordPress comes with MSQL and MariaDB and together, they enable ease in creating dynamic websites. Besides, WordPress provides various plugins that facilitate drag and drop for website building.

In this tutorial, we will discus how to setup WordPress development environment using Docker. We will create a Docker compose file with a few services to run so our entire WordPress application will run on Docker container and not on our machine. We will use WordPress image, MySQL, and Phpmyadmin by setting up a single file that includes all of them before we setup wordpress.

### Key takeaways: 
1. Docker Compose
2. Using WordPress. MySQL & Phpmyadmin in a Docker container
2. Running WordPress using Docker 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any [existing EngEd articles](https://www.section.io/engineering-education/search/?q=docker) or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved 

@mia-roberts

**Comment by Rose-stack** [comment]
@hectorkambow  @mia-roberts I had already covered a similar topic of WordPress with Docker

https://www.section.io/engineering-education/docker-wordpress-containerizing-wordpress-with-docker-compose/

**Comment by mia-roberts** [comment]
Thank you @Rose-stack, I did not see that before. Closing this issue.
cc @hectorkambow
