### ISSUE TITLE
How to set up a single Hadoop cluster using Docker

### ISSUE THREAD

**Issue by Antony-Prince** [section-engineering-education/engineering-education#2543]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

How to set up a single Hadoop cluster using Docker

### Introduction paragraph (2-3 paragraphs):

This guide will teach you how to set up a single Hadoop cluster using Docker. But before that, let's take a recap of what the Docker and Hadoop cluster is.

### What is a Hadoop cluster?

The Hadoop framework helps in processing and analyzing Big Data. Hadoop framework stores and processes vast amounts of any data efficiently using a cluster of computer hardware. Thus we can refer Hadoop cluster as a special type of computer cluster. It is designed for storing and analyzing vast amounts of unstructured or structured data. Clustering is mainly used for parallel processing, load balancing, and fault tolerance. a Hadoop cluster run Hadoop open-source distributed processing software.

A Hadoop cluster works the same as a computer cluster. A computer cluster can be defined as a set of connected computers that work together in a way that they could be viewed as a single system. This way, it is relatively easy to add more power to the cluster. You simply add a new computer to the network.

The Hadoop ecosystem comprises three main components that are designed to specifically work on big data this are;

- Hadoop distributed file system (HDFS)

HDFS is a storage unit that helps to distribute data amongst many computers and is stored in blocks.  Hadoop framework divides the data into smaller chunks and stores each part of the data on a separate node within the cluster. Let's say you have around 4 terabytes of data. HDFS will split the data into multiple data blocks and then store the data in several data nodes in the Hadoop cluster. With each block(node) assigned 128 megabytes as the default size. This way time taken to store this data onto the disk is significantly reduced. The total time used to store this data into a disk will be equal to the total time used to store data in one block. HDFS will then use the replication method and make copies of each data node to other machines present within the cluster. This ensures no data is lost even if one data node crashes, making HDFS fault-tolerant.

- MapReduce

MapReduce splits data into parts and processes each of them separately on different data nodes. The individual results are then aggregated to give the final output.

- Yet Another Resource Negotiator (YARN)

YARN manages resources within a cluster. It consists of a resource manager, node manager, application master, and containers. The resource manager assigns resources to the Hadoop cluster. Node managers handle the nodes and monitor the resource usage in the node. The containers hold a collection of physical resources.  With YARN, the application requests the container from the node manager. Once the node manager gets the resources, it sends them to the resource manager. This way, YARN processes job requests and manages cluster resources in a Hadoop cluster.

### Key takeaways: 
What is a Hadoop cluster?
What is Docker and Docker containers?
How to set up a Hadoop cluster using docker-compose
Testing the Hadoop cluster

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Antony-Prince 

seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
