### ISSUE TITLE
Why Kubernetes is the best technology for running Cloud-Native Database

### ISSUE THREAD

**Issue by ephraa** [section-engineering-education/engineering-education#2544]
### Proposed title of article
Why Kubernetes is the best technology for running Cloud-Native Database

### Introduction:
The discussion about migrating workloads to the cloud has been there for a long time, but a looking at the application portfolios of many IT organizations demonstrates that there’s still a lot of work to be done. In many cases, challenges with persisting and moving data in clouds continue to be the key limiting factor slowing cloud adoption, despite the fact that databases in the cloud have been available for years.  
For this reason, there has been a surge of recent interest in a data infrastructure that is designed to take maximum advantage of the benefits that cloud computing provides. A good example of a cloud-native database is the K8ssandra project. It packages Apache Cassandra and supporting tools into a production-ready Kubernetes deployment. 
This raises an interesting question: must a database running on Kubernetes be considered cloud-native? This article will dive into the issue and try to come up with the answer.

### Key takeaways: 
In this article the reader will able to:
- understand the concept of Cloud-Native Databases
- explore different Kubernetes design principles
- draw the conclusion on the best designs based on the principles discussed earlier

### References: 
N/A

**Comment by hectorkambow** [comment]
@ephraa 
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

Please double check with recently K8 EngEd articles to avoid overlap 👍
