### ISSUE TITLE
Introduction to PHP Operators

### ISSUE THREAD

**Issue by mussooo** [section-engineering-education/engineering-education#2545]
### Proposed title of article
Introduction to PHP Operators

### Introduction paragraph (2-3 paragraphs):
PHP Operator is a symbol i.e used to perform operations on operands. In simple words, operators are used to perform operations on variables or values. For example:

$num=10+20;//+ is the operator and 10,20 are operands  

In PHP, we have different types of operators depending on the number of operands they take. There are some operators that take only one operand and perform an operation on it. This type of operators are called unary operators. Another type of operators are binary operators which take two operands.

### Key takeaways: 
1. Instaling PHP and Xampp in Linux
2. Define what is an operator and an operand
3. Learn the roles of different operators
4. Category of PHP Operators
5. Use Operators to perform mathmatical computation

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Serahmusoo Just wanted to make sure this topic wont overlap too much with this past article:

https://www.section.io/engineering-education/introduction-to-php/

**Comment by Serahmusoo** [comment]
@hectorkambow thanks for pinging me. This article is different from the published one. In the published article, the author did not discuss on operators. In this article, my attention is to equip the PHP beginners with knowledge on how to use different types of PHP Operators to accomplish their codding task. Anything similar(which I don't expect) will be referenced.

Please Ping me if there is anything else.  Thank you

**Comment by hectorkambow** [comment]
👍  Understood, thank you for the clarification - approved
