### ISSUE TITLE
Improving App performance with DiffUtil API in Android-Kotlin

### ISSUE THREAD

**Issue by MaurineM** [section-engineering-education/engineering-education#2548]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

### Proposed title of article

Improving App performance with DiffUtil API in Android-Kotlin

### Introduction paragraph (2-3 paragraphs):

Mobile applications performance is among the major factors that determines the user experience. Performance of mobile application refers to its capability to load and refresh data on various events.

DiffUtil is an API that calculates the difference between two data sets and outputs a list of update operations that converts the first list into the second one. It makes use of the [Eugene W. Myers's](https://www.nathaniel.ai/myers-diff/) difference algorithm to calculate the minimal number of updates to convert one data set into another. Myers's algorithm does not handle items that are moved so DiffUtil runs a second pass on the result to detect items that were moved thus saving time and device's resources giving the user a better experience.

In this article, we'll learn how to implement DiffUtil in an Android app.

### Key takeaways: 

This tutorial will mainly cover the following:

1. Introduction to DiffUtil.
2. Explanation on how Eugene W. Myers's difference algorithm works.
3. Integrating DiffUtil in an Android app.
4. Debugging callback errors.

### References: 

N/A

**Comment by hectorkambow** [comment]
To avoid much of a back log we only approve one PR/topic at a time per student. 

We can re-open this one once the 1st one is published. 👍

**Comment by MaurineM** [comment]
That's fine @hectorkambow. Does this mean I can start writing for this topic once I'm done with the first one? (as I wait for it to be published)

**Comment by MaurineM** [comment]
Thanks @louisefindlay23.
