### ISSUE TITLE
Face recognition using PCA in Matlab

### ISSUE THREAD

**Issue by linetachieng** [section-engineering-education/engineering-education#2550]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
PCA is a way of reducing the dimensions of a large dataset by transforming the large dataset into a smaller dataset but ensuring that the smaller dataset contains more information of the large dataset. By reducing the dataset, we are increasing reducing the accuracy but PCA works on the principle of trading little accuracy fr simplicity. This is because smaller data are easier to explore and visualize making the analysis of data easier and faster for machine learning algorithms.
Eigenvectors and eigenvalues are the linear algebra concept that is used to compute from the covariance matrix in order to determine the principal component of the data. Face recognition is the process of identifying an individual using their face. Matlab has numerous built-in functions that help calculate the principal components. In this article, we will see how we can use it to recognize the face.
### Key takeaways: 
- Dimensionality reduction using PCA.
- Face image database preparation for training and testing.
- Matlab code for training and testing.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@linetachieng 

Seems like a helpful topic - lets please be sure it add value beyond what can be found in the official docs and other blog sites. Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
