### ISSUE TITLE
Creating a Hangman Game with Vanilla JavaScript

### ISSUE THREAD

**Issue by Nomzy-kush** [section-engineering-education/engineering-education#2551]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Creating a Hangman Game with Vanilla JavaScript

### Introduction paragraph (2-3 paragraphs):
A Hangman game is a word-guessing game. One player picks a secret word, and the other player tries to guess it. In this article, I will take you through building a hangman game with Vanilla JavaScript, and more importantly, how I made it accessible for players who navigate with their keyboard or with a screen reader. 

### Key takeaways: 
1. Readers will learn how to create a Hangman game using just Vanilla Javascript.
2. Readers will learn to create this game without using any framework or library.
3. Readers will learn how to use dialogs to make the game interactive and take input from someone playing the game.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Nomzy-kush 

Seems like a helpful topic - lets please be sure it add value beyond what can be found in the official docs and other blog sites. Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
