### ISSUE TITLE
Build your own chrome extension

### ISSUE THREAD

**Issue by paulromans** [section-engineering-education/engineering-education#2555]
### Proposed title of article
Build your own chrome extension

### Introduction paragraph (2-3 paragraphs):
According to https://developer.chrome.com/docs/extensions/,  chrome extensions are software programs, built on web technologies (such as HTML, CSS, and JavaScript) that enable users to customize the Chrome browsing experience. The enable one to maximize their browsing experience by a simple mouse click. Take for instance, the Internet Download Manager that easily grabs download links.

In this tutorial, we are going to build a customized chrome extension using CSS, HTML, JavaScript and  bit of JSON. We will create a chrome extension that has direct links to launch Section.io social social media pages. Follow along to learn more.

### Key takeaways: 
1. Understanding how chrome extensions work
2. Building chrome extensions
3. Publishing a chrome extension to the chrome browser.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@paulromans 

Just wanted to make sure this topic wont overlap too much with this past article: 

https://www.section.io/engineering-education/how-to-build-chrome-extension/

**Comment by paulromans** [comment]
Noted. Thanks.
