### ISSUE TITLE
How To Implement Laravel Queue

### ISSUE THREAD

**Issue by bhanjibrilliant** [section-engineering-education/engineering-education#2558]
### Proposed title of article
How To Implement Laravel Queue

### Introduction paragraph (2-3 paragraphs):
What if your application could receive requests, execute logic, and then respond to the same request independently?

Ideally, in a highly-technical and automated world, a synchronous workflow can simplify even the most complex projects.

Laravel gives us a built-in queue system that helps us to run tasks in the background and configure how the system should react in different situations. It allows you to delay a time-consuming task until a later time. By postponing the time-consuming task, you can improve the performance of the Laravel applications.

### Key takeaways: 
Step 1: Configure The Queue
Step 2: Create An Email Template And Mailable
Step 3: Testing
Step 4:Dispatching/Delaying Jobs
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Seems like a helpful topic - lets please be sure it add value beyond what can be found in the official docs and other blog sites. Lets also make sure that it does not overlap with any existing [EngEd articles](https://www.section.io/engineering-education/search/?q=Laravel) or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

@bhanjibrilliant

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 can be reopened once the first PR is merged.
