### ISSUE TITLE
Getting Started With React Query for data fetching server-state data management

### ISSUE THREAD

**Issue by KayveTech** [section-engineering-education/engineering-education#2561]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting Started With React Query for data fetching server-state data management

### Introduction paragraph (2-3 paragraphs):
Server data is often asynchronous. The React Query library is often described as the React’s missing piece that helps with server-state data management. The old school standard way has been to keep the state globally, because most libraries were created to handle client state only and the server state is way different.  React Query is the library that can fetch, cache and update data in your React and React Native applications all without touching any "global state". 
In this tutorial, we will use React Query with hooks to build a React component that fetches data from third party API and React Query will handle the server state as well.

### Key takeaways: 
1. Using Hooks and intergrating React Query in a React Application
2. When to use React Query
3. fetch requests with the React Query package
4. Caching methods in React Query
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@KayveTech Seems like a helpful topic - lets please be sure it add value beyond what can be found in the official docs and other blog sites. Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

I know we have a few React articles - please go through them to again avoid overlap and see if any can be referenced to for the reader 👍

**Comment by hectorkambow** [comment]
@KayveTech 
Just pinging you on this topic form - as Im making some room in the topic queue.

No rush if you're still working on this one - if you need more time we can always re-open at a later date.
