### ISSUE TITLE
understanding django model relationships in crud application

### ISSUE THREAD

**Issue by dekings44** [section-engineering-education/engineering-education#2564]
Django is an MVT framework which is a dialect of the popular MVC architecture used by so many major frameworks across the web.

My topic is **understanding django model relationships in crud application**

The table of content are

1. Overview of Django MVT
2. One to Many Relationship
3. Many to Many Relationship
4. CRUD (Create Read Update Delete)
5. Conclusion

Reference to understand a little of what I want to write about can be found below
https://www.webforefront.com/django/relationshipmodelrecords.html

A link to my simple CRUD application using  Django and Chartjs can be found below.
https://myrichestmen.herokuapp.com/

I could also write an article on it, since I haven't written any on it.

You can find me on Medium 
https://dekings.medium.com/

**Comment by hectorkambow** [comment]
👋 @dekings44 
A couple things - noticing that your app is using Heroku - we tend not to focus on industry partner level companies. 
Not sure if this has been covered in our library already - its seems like this is something that has been extensively covered other places like the official docs.

We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore.
