### ISSUE TITLE
Setup a Containerized Docker MySQL Database Server and use PHPMyAdmin or Adminer for Viewing the MySQL Database

### ISSUE THREAD

**Issue by Wachira48** [section-engineering-education/engineering-education#2565]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
You can use several relational database management systems (RDBMS) to run SQL queries, such as MySQL PostgreSQL, SQLite SimpleDB, and Elasticsearch. At times it is hectic to set up an SQL server in your local computer. Let's say you are using a Windows environment and you want to run a MySQL database server. In this case, you have download software that supports the RDBMS and Apache server to run SQL commands and access your databases and records, such as WAMP and XAMPP. While installing these environments, something can go wrong, or maybe your computer needs other dependencies and libraries locally installed to support these programs. This makes it hard, especially for a beginner configure, a WAMP server to run SQL queries. Furthermore, it can be hard to specify which versions of MySQL you want to run. You have to download that specific version and reinstall it on your computer.

With docker, things get a little easier. This time you don't need to install all dependencies that you locally need to set up a MySQL server. Docker helps you to containerize software environments so that you can run them as containers. This way, you set a couple of commands that you want your application environment to run on. Then docker will execute these instructions for you, set up that specific environment, and deliver fully packaged and containerized application dependencies and libraries. This allows you to specify things like the version of the MySQL server you want to run.

You don't need to install and configure the MYSQL environment to access databases and records. Docker provides you with images (official software) that you use and run within your docker containers, such as PHPMyAdmin, Adminer, and Sequel Pro (for Mac OS), to access your record database.

When you need to execute SQL queries, you will only set up a dockerize yml file, run a few commands, and docker will set everything ready for you. As a beginner, you can be able to run and use SQL queries in a containerized environment.

In this tutorial, we will dockerize a MySQL Database Server and set up PHPMyAdmin or Adminer to interact with the MySQL Database. In simple words, dockerize means create a docker image (a virtualized instance) of an application.

Whenever you are dockerizing an application, you first need to write a docker-compose file and specify the instances you want to containerize to form your application stack. Let's go ahead and demonstrate how we can create this MYSQL, PHPMyAdmin, or Adminer stack.

### Key takeaways: 

Set up docker and docker-compose
Write docker-compose.yml
Set MYSQL sever
Set and run PHPMyAdmin
Set and run Adminer as an alternative to PHPMyAdmin

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Wachira48 
 Seems like a helpful topic - lets please be sure it add value beyond what can be found in the official docs and other blog sites. Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

I know we recently published an article about compose I believe - might be useful to reference (if applicable).
