### ISSUE TITLE
Password Cracking with John the Ripper 

### ISSUE THREAD

**Issue by Koros-Meshack** [section-engineering-education/engineering-education#2567]
**Introduction**
John the Ripper is a free open source password recovery and cracking security auditing tool. It is available in most operating systems but most recommended in Kali Linux.
John the Ripper is mostly used in penetration testing by security specialist to spot weak passwords in their system. The article proposed will be easily understood from a beginner to an advanced user.
The article will clearly guide the user in a step by step process to chose a target machine and set up necessary options for the bruteforce. The article will help the user avoid major errors caused by users during a brute force attack.

**Disclaimer**
The tutorial is meant for educational purposes only and any action that is related to content in this article is your responsibility.

**Key Takeaways**
By the end of this tutorial, the user will be able to:
1. Install John the Ripper in Kali Linux.
2. Run some major commands used in John the Ripper.
3. Perform a dictionary attack using John the Ripper
4. Understand word mangling rules in JtR.
5. Display their output during an attack.

**Reference**
N/A

**Comment by louisefindlay23** [comment]
Hi, @Koros-Meshack. Great topic suggestion. I'm sure your tutorial will benefit our readers. 

Could you explain how your article will differ from this [Varonis](https://www.varonis.com/blog/john-the-ripper/) and [Focal Point](https://blog.focal-point.com/lets-get-cracking-a-beginners-guide-to-password-analysis) article that both discuss John the Ripper as we focus on original content?

Thanks,
Louise - Content Moderator

**Comment by Koros-Meshack** [comment]
Update made @louisefindlay23  
Please continue with the approval process

**Comment by louisefindlay23** [comment]
Thanks, @Koros-Meshack. Topic approved.
