### ISSUE TITLE
Planting Timber Logs the Right Way

### ISSUE THREAD

**Issue by Owallah** [section-engineering-education/engineering-education#2569]
Proposed title of the article
Planting Timber Logs the Right Way
Introduction paragraph (2-3 paragraphs):
Timber is a logger with a small, extensible API. In addition to the regular Android log classes, it also provides a utility.

When logging in android, many developers tend to use the traditional log classes which tend to be tiresome and time-consuming. Timber, a library by Jake Wharton has made logging easy and simple. in this article, we'll be discussing the best and easiest way to plant timber trees. 

Key takeaways:
What is a Timber library?
Planting timber trees using Timber.plant.
The drawbacks of using other log classes.
References:
[https://github.com/JakeWharton/timber)

**Comment by hectorkambow** [comment]
@Owallah 
 Seems like a helpful topic - lets please be sure it add value beyond what can be found in the official docs and other blog sites. Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

**Comment by ahmadmardeni1** [comment]
Hey 👋 @Owallah 

Any update on this topic? We are trying to clear the queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by hectorkambow** [comment]
@Owallah 
Just pinging you on this topic form - as Im making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

Please create a NEW topic form for the PR if and when the articles is completed. 

Thank you 🚀  
Looking forward to some solid articles.

**Comment by Owallah** [comment]
Hello there, I'm having an issue with my Github authentication.  I've
submitted a  request to the help team and it will be reviewed in 3-5
working days.  please bear with me.  immediately I'm in I'll start working
on it
