### ISSUE TITLE
Getting started with JavaScript Machine Learning using Brain.js

### ISSUE THREAD

**Issue by jamila-laureen** [section-engineering-education/engineering-education#2572]
### Proposed title of article
Getting started with JavaScript Machine Learning using Brain.js

### Introduction paragraph (2-3 paragraphs):
Brain.js is a JavaScript Library used to building Neural networks in JavaScript. Brain.js is easy and simple to use.
In this tutorial, the readers will understand how to create a neural network, add training data and  test a neural network form scratch using brain.js.
### Key takeaways: 
1. What is brain.js?
2. Getting started with brain.js
3. Building, training and testing a neural network with brain.js.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@jamila-laureen 
 Seems like a helpful topic - lets please be sure it add value beyond what can be found in the official docs and other blog sites. Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
 
 One important note: Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)

**Comment by ahmadmardeni1** [comment]
Hey 👋  @jamila-laureen 

Any update on this topic? We are trying to clear the queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by hectorkambow** [comment]
@jamila-laureen 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

Please proceed to create a NEW topic to tie to your PR if and when the article is ready to be published.
