### ISSUE TITLE
Building World-class Apps with Angular Material

### ISSUE THREAD

**Issue by owinowendy** [section-engineering-education/engineering-education#2577]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Building World-class Apps with Angular Material

### Introduction paragraph (2-3 paragraphs):
Angular Material has been one of the most popular component libraries for Angular developers in recent times. In this article, we will discover the reasons for its popularity, learn how to set up a new Angular Material app and customise it with your own theme and typography.

Often times, the difference between an app that merely serves its purpose and one that delivers a great experience, is determined by the amount of thought and effort that goes into the smallest details of the individual components.

- Animations and motion provide visual feedback to the user to keep them aware of the state of the app.

- Work on accessibility and ease of use ensures that the app is built for the target audience.

-Internationalization(i18n) to make the app available for different languages and cultures.

- A very common requirement for web apps these days is that they should also function well across different screen sizes, and a lot of effort goes into making sure that the app is responsive. 

These aspects are all addressed by Material Design, which is a design system created by Google exclusively for building digital experiences. They use it across their vast suite of services, on web and mobile.

### Key takeaways: 
1.Getting Started with Angular Material Installation
2.Scaffolding Components with Material Schematics
3.Creating a Custom Angular Material Theme
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by owinowendy** [comment]
Reopening @ahmadmardeni1 am ready to work on this

**Comment by WanjaMIKE** [comment]
Unfortunately, your key takeaways have somehow expired. In other words, they have already been covered by numerous articles such as https://www.section.io/engineering-education/search/?q=Angular

**Comment by owinowendy** [comment]
> Unfortunately, your key takeaways have somehow expired. In other words, they have already been covered by numerous articles such as https://www.section.io/engineering-education/search/?q=Angular

I checked and it has not been covered,,, how has it expired?
