### ISSUE TITLE
Why and How Microservice messaging works in Kubernetes?

### ISSUE THREAD

**Issue by martha-ngugi** [section-engineering-education/engineering-education#2580]
### Proposed title of article
Why and How Microservice messaging works in Kubernetes?

### Introduction:
Struggling with connecting and maintaining your microservices in Kubernetes? As the number of microservices grows, the difficulty and complexity of maintaining your distributed fleet of services grow exponentially. Messaging can provide a clean solution to this issue, but legacy message queues come with their own set of problems. 
In this article, I’ll share the benefits of messaging in Kubernetes and the difficulties that can come with legacy solutions. I'll also briefly look at KubeMQ, which attempts to address some of the traditional problems with messaging in Kubernetes.

### Key takeaways: 
In this article, the reader will understand:
- why we need messaging in Kubernetes?
- the difficulties faced by messaging in Kubernetes
- the Kubernetes-native-approach to solve the Kubernetes related messaging issues

### References: 
N/A

**Comment by hectorkambow** [comment]
@martha-ngugi 
Seems like a helpful topic - lets please be sure it add value beyond what can be found in the official docs and other blog sites. Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

One important note: Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval for a quicker publishing process. (There are some great free tools that we reference in EngEd resources.)
