### ISSUE TITLE
Getting started with JavaScript Events

### ISSUE THREAD

**Issue by bastian-zab** [section-engineering-education/engineering-education#2582]
### Proposed title of article
Getting started with JavaScript Events

### Introduction paragraph (2-3 paragraphs):
A JavaScript events are operations that run when a user interacts with a given webpage. Events can be used to used to provide a dynamic interaction with a webpage by making the interaction  seamless and enjoyable. Alerts, form validation, window pop ups are all forms of events that facilitate user interaction with a webpage.

When an event occurs, we can use JavaScript event handler to detect the event and preform a specific task specified by the event. Events can be classified into Mouse events, keyboard events and events that are triggered by loading a webpage. Conventionally, most events are named according to their classifications.

In this article, the reader will understand how to JavaScript listen to events, pass them to event handlers and specify tasks to be performed depending on specific events.

### Key takeaways: 
1. How to listen to JavaScript events
2. Handling JavaScript events.
3. Types of JavaScript events

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Hi, @bastian-zab. 

Great topic suggestion. I'm sure our readers will find your guide to JavaScript Events very useful. 

Make sure to cover mouse and load events in detail to differentiate your article from our existing [Keyboard Events in JavaScript](https://www.section.io/engineering-education/keyboard-events-in-javascript/) article.

Topic approved ✔️

**Comment by hectorkambow** [comment]
@bastian-zab 
Just pinging you on this topic form - as were trying to make some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by hectorkambow** [comment]
@bastian-zab 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
