### ISSUE TITLE
Introduction to electrical and electronics, their differences

### ISSUE THREAD

**Issue by Khadijah62** [section-engineering-education/engineering-education#2586]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Introduction to electrical and electronics, their differences. 

### Introduction paragraph (2-3 paragraphs):
This article introduces the the term electrical  and electronics  as used in the engineering and technical communities.
It also gives a clear understanding on the differences between the two terms.

### Key takeaways: 
1. The reader would at the end of reading this article, be able to understand the terms electrical and electronics, and what they entails.
2. The reader would understand the clear differences between electrical and electronics devices 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Not approved - @Khadijah62 
It is not a tech-related article.
Please take a look at our GitHub resources and our published articles.
