### ISSUE TITLE
RISC -V Open Instruction Set Architecture: Exploring It's impact in Modern Computer Architecture

### ISSUE THREAD

**Issue by Umoren** [section-engineering-education/engineering-education#2587]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
RISC -V Open Instruction Set Architecture: Exploring It's impact in Modern Computer Architecture

### Introduction paragraph (2-3 paragraphs):
In computer architecture, the border between hardware and software is the Instruction Set Architecture (ISA). The ISA models how software communicates with the hardware and vice-versa. By software, I’m referring to the O.S, Application Software, Compiler, Firmware, and by hardware, we are not just considering the CPU, I/O, and Memory but lower-tier elements such as gates, transistors, and Digital Circuits. One of the founders of the RISC ISA, John Hennessy, describes the ISA as “what the machine language programmer must know to properly write a correct but timing-independent program”. 

### Key takeaways: 
- The reader (even with little to no knowledge in computer architecture) should be able to understand what instruction set architectures are and the types (most especially RISC, CISC MIPS and VLIW).
- The reader should also understand the features of old RISC and the changes in RISC-V.
- Peek into the RISC -V design
- The future potentials of RISC V

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Design of the RISC-V Instruction Set Architecture](https://escholarship.org/uc/item/7zj0b3m7#page=3)
- [A New Golden Age for Computer Architecture, Communications, February 2019, Vol. 62 No.2](https://cacm.acm.org/magazines/2019/2/234352-a-new-golden-age-for-computer-architecture/fulltext)
- Instruction Sets Should Be Free: The Case For RISC-V. Electrical Engineering and Computer Sciences University of California at Berkeley. Technical Report No. UCB/EECS-2014-146. August 6, 2014. (https://people.eecs.berkeley.edu/~krste/papers/EECS-2014-146.pdf)

**Comment by hectorkambow** [comment]
@Umoren 

🤔 
Thank you for the topic suggestion @Reestuart , however this is a bit outside of our preferred topic areas. (I believe this has to do actual hardware components?) 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
