### ISSUE TITLE
Swapping in C#

### ISSUE THREAD

**Issue by Terripha** [section-engineering-education/engineering-education#2594]
### Proposed title of article
Swapping in C#

### Introduction paragraph (2-3 paragraphs):
 Swapping is all about the interchanging of values at runtime. How do you swap two values without creating a new storage location using  C#, this type of question might confuse many developers in the .Net related fields.

My intent for this article is to explain how to answer the question, i.e Write a program to swap two values using C# without creating a new storage location. A new developer can become confused because, the first problem is that the developer does not even know which keyword to use for that, so how will he or she know how to write the program?

We will look at the concept of answering the question in this article with the basics and especially focusing on the beginner, student, and whoever might encounter this type of question.

### Key takeaways: 
1. What is swapping?
2. Conditions to swap values
3. The different ways of swapping values
4. How to swap 2 values and finally 3 values

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Not approved - @Terripha 
This is too simple to be a tutorial, try writing about in-depth topics.
