### ISSUE TITLE
Using Multiple SSH Keys for Multiple GitHub Accounts

### ISSUE THREAD

**Issue by LeahKui** [section-engineering-education/engineering-education#2595]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Using Multiple SSH Keys for Multiple GitHub Accounts
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
GitHub is a code hosting platform for collaboration. It enables people to work on projects from anywhere.
Most GitHub users have a problem with managing multiple GitHub accounts. This article aims to let the user understand how to use SSH Keys with multiple GitHub accounts.
The article will answer several questions, it will address what SSH keys are and how to generate them, how to manage SSH keys, and how to use them for multiple GitHub Accounts.

### Key takeaways: 
1. What are SSH Keys
2. How to manage SSH Keys on GitHub Accounts
3. What is SSH config and how to set up one
4. How to use SSH Keys for multiple GitHub Accounts

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Seems like a helpful topic - lets please be sure it add **value beyond what can be found in the official docs and other blog sites.** Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

One important note: Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval for a quicker publishing process. (There are some great free tools that we reference in EngEd resources.)
