### ISSUE TITLE
Arrays in java

### ISSUE THREAD

**Issue by Catherinemugo** [section-engineering-education/engineering-education#2598]
### Proposed title of article
Arrays in java
### Introduction paragraph (2-3 paragraphs):
An array is a group of contiguous or related data items that share a common name. For instance, we can define an array name salary to represent a set of salaries for a group of workers. 
A particular value is indicated by writing a number called index number or subscript in brackets after the array name. Arrays can be represented by any variable type .

### Key takeaways: 
1. Definition of arrays
2. Creating an array
3. One and two dimensional array
4. sorting arrays

### References: 
N/A

**Comment by hectorkambow** [comment]
@Catherinemugo 
Seems like a helpful topic - lets please be sure it add value beyond **what can be found in the official docs and other blog sites.**
(creating unique example cases is usually helpful)
Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

One important note: Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval for a quicker publishing process. (There are some great free tools that we reference in EngEd resources.)
