### ISSUE TITLE
CSS in HTML

### ISSUE THREAD

**Issue by temitope-david** [section-engineering-education/engineering-education#2602]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
CSS in HTML

### Introduction paragraph (2-3 paragraphs):
Adding styles to your webpage (HTML) is a given to give the look you actually desire. The language for adding styles to our webpage is called CSS (Cascading style sheet).

There are three approaches to adding CSS to your HTML page (s). This is a beginner centric tutorial teaching you how to add CSS to your HTML page (s). In this tutorial, you will learn when to use those different approaches and which approach is suitable for which condition. Basic knowledge of HTML and CSS is assumed.

### Key takeaways: 
Inline CSS
CSS in a single HTML page 
External Stylesheet

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
https://www.section.io/engineering-education/what-is-css/

https://www.section.io/engineering-education/embedding-a-video-into-a-webpage-using-html-and-css/

**Comment by temitope-david** [comment]
@WanjaMIKE my article goes more in-depth by showing the pros and cons of the approaches and when to use them

**Comment by ahmadmardeni1** [comment]
Not approved - @temitope-david 
We have [multiple](https://www.section.io/engineering-education/search/?q=css) articles/tutorials covering the topic very well.

**Comment by hectorkambow** [comment]
> Not approved - @temitope-david
> We have [multiple](https://www.section.io/engineering-education/search/?q=css) articles/tutorials covering the topic very well.

Please feel free to submit another topic for approval 🚀
