### ISSUE TITLE
Semantic HTML for Beginners 

### ISSUE THREAD

**Issue by josax01** [section-engineering-education/engineering-education#2603]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Semantic HTML for Beginners 

### Introduction paragraph (2-3 paragraphs):
Writing HTML without semantics is not recommended for efficient code, it can definitely work with little to no issue, but there is rather a better way of structuring our HTML. This is known as semantic HTML. 

This approach gives meaning to our HTML structure and it can be very useful to get other frontend developers to quickly understand the codebase.

In this tutorial, you will be learning how to write readable HTML code.

### Key takeaways: 
Why semantics HTML
Advantages of Semantic HTML
Different examples of semantic HTML

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Hi, @josax01. Thanks for submitting a topic suggestion. From looking at your article idea, it seems that there is much we could add to benefit readers but we're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is similar to articles on other blog sites such as [FreeCodeCamp](https://www.freecodecamp.org/news/semantic-html5-elements/). 

Could you expand on the different examples of semantic HTML that you would cover and what makes this article unique from other articles on Semantic HTML?

**Comment by josax01** [comment]
Thanks @louisefindlay23, so I just skimmed through freecodecamp article on semantic HTML5, my own approach will be more pragmatic. We would basically be building a full landing page both the traditional way (i.e before HTML 5 ), where we would be using div with a class name of header and so on. Then we will over haul everything to use sematic HTML 5.

**Comment by louisefindlay23** [comment]
That sounds great, @josax01. Topic approved. We look forward to reading your submitted article.
