### ISSUE TITLE
Getting started with machine learning in Matlab

### ISSUE THREAD

**Issue by peterAdongo** [section-engineering-education/engineering-education#2604]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Getting started with machine learning
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction:
Machine learning is a type of computer science that allows computer programs to learn and improve on their own. In the past, computers could only do what they are programmed to do but with machine learning, they could behave like human being and gain knowledge based on their past experiences. let's say for example we want a program that that can tell the difference between apples and bananas. First we give the computer some label pictures of each. The program will identify the pattern in the fruit and begin to remember them. It can then use these memories to identify the unlabeled and tell which is which.
Machine learning is encountered in daily basis for example, in the medical industry, it is applied for predicting life span, organizing patients data e.t.c. Matlab provides a machine learning toolbox that makes machine learning easier. In this article, we will look at the basis of machine learning.
### Key takeaways: 
- Overview of machine learning.
- Algorithms available in Matlab.
- Overcoming machine learning challenges using Matlab.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Approved - @peterAdongo 
Please make sure to create a unique application using these concepts, just to make the content original.
