### ISSUE TITLE
Build and Deploy Docker Based Project from GitHub to Server

### ISSUE THREAD

**Issue by DesignrKnight** [section-engineering-education/engineering-education#2605]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Build and Deploy Docker Based Project from GitHub to Server

### Introduction paragraph (2-3 paragraphs):

Continuous Deployment is a fantastic concept. It's amazing to commit your project and see it being created and deployed without you having to do anything. And in this article, I'll describe to you how to achieve it quickly and easily in your project.  

- You'll learn how to create a Dockerfile.
- How to Publish a GitHub Project
- Building the Docker image on Docker Hub automatically
- Fetch the updated image and use it on the server

We'll make a GitHub pipeline to create, and automatically deploy a created Docker container image on a remote server based on code changed on GitHub.

### Key takeaways: 
- Continuous Integration with Docker
- Build Docker image via GitHub Actions
- Transfer secret to Docker for building and deploy in public repo by using GitHub secrets
- Fetch and run the image from container registry to server

### References: 
- I would be using one of the earlier projects I worked on as a reference to base this article. It is an original work. Link: https://github.com/dscnitrourkela/project-dates

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
seems like a very helpful topic - approved. 

Be sure to link to any relevant recent container articles 🚀 

@DesignrKnight

**Comment by DesignrKnight** [comment]
Thanks @hectorkambow 
I will link the relevant article from official docs and engineering education in my article

**Comment by DesignrKnight** [comment]
Just wanted to give an update that the article draft is under process and I would be ready with first draft by month-end in 2 days

**Comment by hectorkambow** [comment]
@DesignrKnight 
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
