### ISSUE TITLE
Object Oriented Programming with Python

### ISSUE THREAD

**Issue by Temmy5113** [section-engineering-education/engineering-education#2606]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Object-Oriented Programming with Python

### Introduction paragraph (2-3 paragraphs):
Object-Oriented Programming is a technique of writing computer programs among others. It helps to modulize our code into objects that can be reused later on. This technique is supported by major popular languages including Python. 

In this tutorial, you would be exposed to object-oriented principle using Python language.

### Key takeaways: 
- Classes vs Objects
- Setters and Getters
- Magic method
- Inheritance

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Hi @Temmy5113 In this tutorial `https://www.section.io/engineering-education/a-beginners-guide-to-python/`, I covered some aspects on creating objects from classes, as well as passing data. How will your content be different?

**Comment by Temmy5113** [comment]
Hi @WanjaMIKE,  thanks I just skimmed through the article and I noticed OOP was not covered  in depth. My own approach to this article is to cover most of OOP concept including inheritances, getters and setters etc. Yours was only based on classes.

**Comment by hectorkambow** [comment]
> Hi @WanjaMIKE, thanks I just skimmed through the article and I noticed OOP was not covered in depth. My own approach to this article is to cover most of OOP concept including inheritances, getters and setters etc. Yours was only based on classes.

Can we make the article more unique by creating a simple use case/app/project example? Something the larger developer community could relate to or move over to a real life use case. 


Just want to make sure we are not working on an article that covers what is already readily available through the documentation or via many other blog sites. 👍  

@Temmy5113

**Comment by Temmy5113** [comment]
@hectorkambow ,  thanks I will write the article in a form of project base that covers most of OOP concept.

**Comment by hectorkambow** [comment]
Sounds good - approved 🚀  

Thank you

**Comment by hectorkambow** [comment]
@Temmy5113 

Just pinging you on this topic form - as Im making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by WanjaMIKE** [comment]
closed #2606 #4284
