### ISSUE TITLE
How to create a REST API using Spring Boot, Maven, and MySQL

### ISSUE THREAD

**Issue by Lekwacious** [section-engineering-education/engineering-education#2609]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to create a REST API using Spring Boot, Maven, and MySQL

### Introduction paragraph (2-3 paragraphs):
One of the benefits of REST APIs is the flexibility and scalability it gives to our application. Because the client and server are independent, the REST protocol separates the data storage and the UI from the server. With this, our application can be scaled quickly primarily due to the separation of concerns(the separation of the frontend from the server), which helps our application to be loosely coupled. This offers flexibility in modifying our code in the future as developers can easily integrate restful API without much-added work.

This article teaches how to create a spring boot restful API that performs CRUD operations by making a database call to a MySQL database using Hibernate(an implementation of JPA(Java Persistence API). The application we will be building in this tutorial is an employee management system that registers employees, read, update and delete an employee's information.

### Key takeaways: 
- How to create and set up a spring boot application with a tomcat server.
- MySQL Database Configuration in a spring boot project.
- You will learn how to implement Object Relational Mapping using Hibernate.
- Maven
- Exception Handling in Java 
- How to consume a rest API using postman.

### References: 
- [https://start.spring.io/]
- [https://www.oracle.com/java/technologies/javase-downloads.html]
- [https://gradle.org/install/]
- [https://maven.apache.org/download.cgi]
- [https://www.postman.com/downloads/]
- [https://spring.io/guides/gs/sts]
- [https://spring.io/guides/gs/intellij-idea/]

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Approved - @Lekwacious 
We have [multiple](https://www.section.io/engineering-education/search/?q=spring%20boot) articles/tutorials covering Spring boot and [one](https://www.section.io/engineering-education/spring-boot-crud-api/) of them is covering the CRUD operations.

So try not to overlap with our published content and make your application unique, also refer to our articles/tutorials in your further reading section.

**Comment by Lekwacious** [comment]
Thank You Ahmad. I have pushed and made a PR. Please review. Thanks

**Comment by Lekwacious** [comment]
Hi @Hectorkambow
I sent you a direct message on Slack regarding the payoff on this article,
but your notification is turned off.
