### ISSUE TITLE
How KubeMQ users build scalable messaging platforms with Kubernetes Operators?

### ISSUE THREAD

**Issue by ephnjor2021** [section-engineering-education/engineering-education#2611]
### Proposed title of article
How KubeMQ users build scalable messaging platforms with Kubernetes Operators?

### Introduction:
Over the last several years, the adoption of Kubernetes has increased tremendously. Leveraging Kubernetes allows organizations to create a management layer to commodify clouds themselves and build cross- or hybrid-cloud deployments that hide the provider-specific implementation details from the rest of the team.

One crucial part of the Kubernetes ecosphere is Operators, a tool initially introduced to utilize the Kubernetes APIs to deploy and manage the state of applications.

But what exactly are Operators, and how do they help manage these stateful applications? In this article will take look at Operators in detail, how they work within Kubernetes, and how the KubeMQ messaging platform uses Operators to help you build complex and scalable messaging services with minimal coding and overhead.

### Key takeaways: 
At the end of article the reader will be able to understand:
- what is meant by Kubernetes Operators
- the benefits of KubeMQ and its core components
- how KubeMQ uses Operators to its success

### References: 
N/A

**Comment by hectorkambow** [comment]
@ephnjor2021 
Seems like a helpful topic - lets please be sure it add value beyond what can be found in the official docs and other blog sites. Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

One important note: Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval for a quicker publishing process. (There are some great free tools that we reference in EngEd resources.)
