### ISSUE TITLE
Building a Kubernetes-based solution in a Hybrid Environment by using KubeMQ

### ISSUE THREAD

**Issue by lewe01** [section-engineering-education/engineering-education#2612]
### Proposed title of article
Building a Kubernetes-based solution in a Hybrid Environment by using KubeMQ

### Introduction:
As Kubernetes has become the standard for deploying, managing, and scaling container-based workloads, it has introduced features to allow clusters to exist across multiple clouds, span clouds, and on-premises environments, and even connect clouds and edge computing deployments. 

However, Kubernetes is a platform for deploying applications and isn’t inherently aware of location, topologies, or architectural distribution. While it can provide scalability and connect clouds to the edge, it falls to the application that is built and deployed on Kubernetes to work within that environment.
Requiring a developer to be aware of that level of detail pushes overhead and complexity too far into the development lifecycle. This article will take a look at Messaging Platform abstraction layer to come up with the solution to the above problem.

### Key takeaways: 
In this article the learner will be able to:
- briefly understand the concept of KubeMQ as a messaging platform abstraction layer
- understand how KubeMQ bridges large multiple clusters together in a hybrid environment
- know how KubeMQ supports Edge Computing by bridging information from many hardware devices and build real-time capabilities at the edge

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Approved - @lewe01
