### ISSUE TITLE
How to design a landing page with Builderall

### ISSUE THREAD

**Issue by TaiwoSam153** [section-engineering-education/engineering-education#2614]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to design a landing page with Builderall

### Introduction paragraph (2-3 paragraphs):
Builderall is one digital marketing tool for an online business owner. With Builderall you can design a high converting landing page without writing a line of code. It is well suited for business-oriented people. It is also well suited for beginners due to the shallow learning curve and detailed video explanation on how to use this web tool.

This tutorial will equip you to quickly build your first landing page without a single line of code with good analytics.

### Key takeaways: 
- Detailed explanation of Builderall
- Stunning landing page
- Good analytics

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Thank you for the topic suggestion @TaiwoSam153 , however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
