### ISSUE TITLE
Influence of Artificial Intelligence In Smart and  Intelligent Manufacturing

### ISSUE THREAD

**Issue by valerio140** [section-engineering-education/engineering-education#2616]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Influence of Artificial Intelligence in Smart and Intelligent Manufacturing

### Introduction paragraph (2-3 paragraphs):

Artificial Intelligence is growing rapidly. Artificial intelligence refers to any device that takes actions or rather perceives its environment that aims at maximizing chances of success towards some goal. This can include and is not limited to the growth of technologies, such as rule-based systems and traditional logic, that enable computers to solve issues in ways that resemble thinking.

Smart manufacturing is collaborative manufacturing systems that respond to meet changing demands in smart factories and customer needs. Increasing automation, digital transformation have led to the full transformation of industries, manufacturing businesses, companies, and processes. 

This article will discuss in detail the impact of Artificial Intelligence on smart manufacturing and intelligent manufacturing as well as its applications

### Key takeaways: 
1. Definition of Artificial Intelligence
2. Definition of smart manufacturing
3. Benefits of Intelligent manufacturing
4. Applications of Artificial Intelligence in intelligent  manufacturing
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@valerio140  

👋  Sounds like a very interesting and useful topic - but it seems a bit broad(and _almost_ out of our areas of focus). 

We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

Is there anyway to fold this topic into a more "practitioner-focused" sense. 

Perhaps focusing more on the applications being used for such a topic. How does tie back into the larger developer community. 

A couple notes to think about 🚀  

Thank you

**Comment by winlinda** [comment]
****

**Comment by hectorkambow** [comment]
@valerio140 
Just pinging you on this topic form - as were making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
