### ISSUE TITLE
Docker Push for Publishing Images to Docker Hub

### ISSUE THREAD

**Issue by OkothPius** [section-engineering-education/engineering-education#2617]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Docker Push for Publishing Images to Docker Hub

### Introduction paragraph (2-3 paragraphs):
Building and running Docker containers locally using custom Dockerfiles  has been used most times. What doesn't get explored more often and arguably the most useful feature of Docker is the ability to build a Docker image and upload that image to a Docker repository.

The reason it is useful is its ability to share container images on Docker Hub (Docker's public and private registry) allowing users to quickly share and build upon preexisting images.

In this article, we will be going through the use of this feature while learning the docker push command and using it to upload our Docker container image to Docker Hub.

### Key takeaways: 
1. Create a repository on Docker hub
2. Build an Image using your Docker Hub name and for organizations
3. Pushing our Container
4. Pushing to a Non-Docker-Hub registry

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@OkothPius 
Seems like a helpful topic - lets please be sure it add value beyond what can be found in the official docs and other blog sites. Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

One important note: Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval for a quicker publishing process. (There are some great free tools that we reference in EngEd resources.)
