### ISSUE TITLE
Understanding Data Structures And Algorithms In Python

### ISSUE THREAD

**Issue by destiny251** [section-engineering-education/engineering-education#2620]
We ask that you please be patient as our team works by approving and publishing all articles/tutorials quickly. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an article to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
Understanding Data Structures And Algorithms In Python

### Introduction paragraph (2-3 paragraphs)
A lot of novices and expert computer programmers don't learn data structures and algorithms because they think that it's of no use in real life but then actually it is the core fundamental for developing scalable and efficient codes for programs and software. in this article, I will be teaching you how to get started and understand data structures and algorithms using python and also how you can apply them in a real-life scenario.

### Key takeaways: 
Readers Will Get A Solid Understanding of Data Structures In Python For Example:
- Built-in Data Structures 
-  User-Defined Data Structures 

Readers Will Also Understand Algorithms In Python For Example:
-  Firstly What Are Algorithms
-   Elements Of Good Algorithms
-  Algorithm Classes 
-   Tree Traversal Algorithms
- Sorting Algorithms 
-   Searching Algorithms 
-   Algorithm Analysis and Lastly, the readers will be able to solve real-world complex problems. 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
We covered this topic in a lot of [tutorials/articles](https://www.section.io/engineering-education/search/?q=data%20structure%20python).
Not approved - @destiny251
