### ISSUE TITLE
Implementation of CI/CD in C/C++ Application(Linux) Using Shell and Docker Executor on GitLab

### ISSUE THREAD

**Issue by carteblanchemunene** [section-engineering-education/engineering-education#2621]
### Proposed title of article
Implementation of CI/CD in C/C++ Application(Linux) Using Shell and Docker Executor on GitLab

### Introduction paragraph (2-3 paragraphs):
Many executors with GitLab Runner are available for implementing CI/CD. Nevertheless, Shell and Docker are more popular with them and with these runners we can easily create a repository. These runners can be chosen based on the requirements and availability of the resources. 
This article focuses mainly on the C/C++ Linux application's Shell and Docker executor and code in the Bash script is written. A bash script can be used to build and test the application.

### Key takeaways: 
In this article, the reader will understand:
1. what docker and shell executors are.
2. implementation of C/C++ on Shell Executor.
3. implementation of C/C++ on Docker Executor

### References: 
N/A

**Comment by hectorkambow** [comment]
@carteblanchemunene 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
