### ISSUE TITLE
Understanding generic programming of C# in detail.

### ISSUE THREAD

**Issue by elijahndungu** [section-engineering-education/engineering-education#2624]
### Proposed title of article
Introduction to generic programming in C#.

### Introduction paragraph (2-3 paragraphs):
Due to the great advancement of technology in the 21st century, many software systems require to store large groups of entities
rather than individual entry. The concept of array could solve this problem but in C#, generic collections are far much better.

Collections according to C# are classes that hold together groups of objects. The .NET libraries provide useful system defined classes, like collection namespace, which  provide various collections and their functionalities.

In this article lists, dictionaries and hashsets collections are worked into and explained in detailed and easily understandable manner.

### Key takeaways: 
1. Understand the concept of list in C#.
2. Understand dictionaries in C#.
3. Understand hashsets form of collection in C#.
4. Know the advantages of a generic collection over a non-generic collection.

### References: 
N/A

**Comment by hectorkambow** [comment]
@elijahndungu 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (references any past and relevant articles in yours) or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
