### ISSUE TITLE
Kubernetes Cost Optimization Using Autoscaling Methods 

### ISSUE THREAD

**Issue by mumbi00** [section-engineering-education/engineering-education#2625]
### Proposed title of article
Kubernetes Cost Optimization Using Autoscaling Methods 

### Introduction paragraph (2-3 paragraphs):
Running more workloads on the same server instance might seem more cost-effective. But tracking which projects or teams generate Kubernetes costs is hard. Knowing whether you’re getting any savings from your cluster is also a challenge.  But there’s one tactic that helps: rightsizing. The tighter your Kubernetes scaling mechanisms are configured, the lower the waste and costs of running your application.  

One of the strengths of Kubernetes as a container orchestrator lies in its ability to manage and respond to dynamic environments. One example is Kubernetes’ native capability to perform effective autoscaling of resources. However, Kubernetes does not support just a single autoscaler or autoscaling approach. 

In this post, we discuss how to use Kubernetes autoscaling mechanisms and drive cloud costs down.

### Key takeaways: 
1. Horizontal vs. Vertical autoscaling in Kubernetes. 
2. Kubernetes autoscaling methods
3. How each method works
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@mumbi00 
Seems like a helpful topic - lets please be sure it add value beyond what can be found in the official docs and other blog sites. Lets also make sure that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

One important note: Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval for a quicker publishing process. (There are some great free tools that we reference in EngEd resources.)
