### ISSUE TITLE
How to Integrate Real-time Webcam on a Web Page Using Javascript

### ISSUE THREAD

**Issue by Olanetsoft** [section-engineering-education/engineering-education#2628]
### Proposed title of the article
 How to Integrate Real-time Webcam to a Web Page Using Javascript

### Introduction paragraph (2-3 paragraphs):
Many websites now include real-time camera integration for purposes such as verification, online calls, and streaming. As a result, this is a useful feature to have on your website or online application.
JavaScript is a scripting or programming language that allows you to implement complex features on web pages — such as displaying timely content updates, interactive activities etc. In this article, we'll be using javascript to integrate real-time webcam functionality on a web page.

### Key takeaways: 
- Understanding the basics of Javascript
- Javascript actions on the browser
- Integration of real-time webcam on a web page

### References: 
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript
https://en.wikipedia.org/wiki/Webcam

**Comment by hectorkambow** [comment]
@Olanetsoft 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (references any past and relevant articles in yours) or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
