### ISSUE TITLE
Localization in Flutter

### ISSUE THREAD

**Issue by jerimkaura** [section-engineering-education/engineering-education#2632]
### Proposed title of the article
Localization in Flutter

### Introduction paragraph (2-3 paragraphs):
Most of the time, we develop applications that target users across the world. However we all know that different people use different languages and to make the application as user-friendly as possible, every user needs to access the application in their own language. This is where localization comes in.

App localization is where a developer adds multiple languages to an application to cater to all users across the world.  Using the Flutter Localization Package, this article will show how to enable an application to support multiple languages at a time. Such applications are preferred by users as they give a friendly interaction with the users.

### Key takeaways: 
1. Localization in detail.
2. Using Flutter localization package.
3. Implementing localization in Flutter

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@jerimkaura 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (references any past and relevant articles in yours) or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

**Comment by hectorkambow** [comment]
@jerimkaura 

Just pinging you on this topic form - as were making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date when the article is ready to publish.

**Comment by WanjaMIKE** [comment]
@jerimkaura make sure you request this form to be reopened before submitting an issue.

**Comment by WanjaMIKE** [comment]
Closed #2632 via #3068

**Comment by jerimkaura** [comment]
Alright.
