### ISSUE TITLE
Using Google Maps API in your website

### ISSUE THREAD

**Issue by mercymeave** [section-engineering-education/engineering-education#2633]
### Proposed title of article
Using Google Maps API in your website

### Introduction paragraph (2-3 paragraphs):
Google Maps API is web mapping API that allows  developers to easily add location maps in a website. The API provides satellite views, streets view, aerial photography and street maps. This API is very useful to locate places in a website like businesses, sportsgrounds, roads and streets. 

This article will take the user through implementation of the API in JavaScript such that by the end of the article, a user should have a Google Map perfectly imbedded into a website with a functionality to autocomplete places search and get direction on the map using Places and Directs API. The user will be enter the location to start and the destination then we visualize the directions to the place and estimate the distance 

### Key takeaways: 
1. Getting Google  API keys for Google map, Places, and Directions
2.  Imbedding Google Map into a website using JavaScript
3. Adding place Markers and Different views in Google Maps
4.  Getting directions on a map
5. Autocomplete city names 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Hi, @mercymeave. Thanks for submitting a topic suggestion.

From looking at your article idea, it seems that there is much we could add for to benefit readers but we're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation and other blog sites.

Could you expand on the different views that you would cover and what makes this article unique from other Google Map API tutorials?

**Comment by mercymeave** [comment]
Hello @louisefindlay23 , thank you for the observation. I intend to add value by adding  autocomplete functionality in the map as well as showing directions on the map. So it is like using 3 APIs in a single project with a beginner friendly approach.

Let me know of any issues with that. Thank you.

**Comment by louisefindlay23** [comment]
Thanks, @mercymeave. That sounds great and will really add value. Topic approved ✔️. I've implemented an autocomplete Google Map in the past and there's certainly a dearth of up to date simple guides on the topic.

**Comment by mercymeave** [comment]
That is amazing I will ping you so that you share the link, I would love to see what you did.

**Comment by louisefindlay23** [comment]
Thanks so much. I'm afraid it's part of an ongoing client project so I can't share right now but I'll be sure to PM you through the EngEd Slack channel when it's live.

**Comment by mercymeave** [comment]
Alright

**Comment by hectorkambow** [comment]
@mercymeave 

Just pinging you on this topic form - as were making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date when the article is ready to publish.
