### ISSUE TITLE
HOW TO DEPLOY DJANGO PROJECT WITH DATABASE USING HEROKUAPP HOISTING SERVICES.

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#2637]
### Introduction

Deploying Django project with database can be done using different hoisting platforms. There are some dependencies required for the project to be hoisted as described by chosen platform. Heroku has been one of the great and sweet hoisting platform for Django project and in this article I will walk you through how to do just that using one of  my deployed site on Heroku which uses their database, https://microstoryapp.herokuapp.com . Lets get to real gist later!!

### Key Takeaways
At the end of this tutorial, readers will get proper understanding of how they can hoist their project on the chosen platform using the following concepts:

How to setup Django project with requirement dependencies,
How to setup account and login with Heroku,
How to push up project to git so that Heroku account created can access it,
Finally, How to hoist your project and get domain name with extension of herokuapp.com.

### Reference Sites
Heroku Official Website

**Comment by hectorkambow** [comment]
Currently only allowing one TOPIC/PR per student at a time for now. 

Will be closing this topic for now - can be re-opened once the other one is published 🚀

**Comment by Horlawhumy-dev** [comment]
Can you please reopen this sir ? @hectorkambow

**Comment by hectorkambow** [comment]
@Horlawhumy-dev 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites. (beyond a basic explanation - it would be best to reference your favorite intro article and build upon it).
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by Horlawhumy-dev** [comment]
Thanks @hectorkambow
