### ISSUE TITLE
Laravel Collections: PHP Arrays On Steroids

### ISSUE THREAD

**Issue by odongoalbert** [section-engineering-education/engineering-education#2638]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Laravel Collections: PHP Arrays On Steroids

### Introduction paragraph (2-3 paragraphs):
It is basically a API wrapper for PHP array functions. But it has much more features which benefit array processing.
Laravel Eloquent uses Collections to return the results. Collections contains very useful methods that makes them very powerful and helpful to use. You can filter them, modify them and much more with them very conveniently. We will be looking at laravel collection methods in this tutorial.

Collections are not only limited to eloquent results but can be used separately. Eloquent results uses collections. You can simply create a collection by passing an array to collect helper function. All of the next collection methods listed below are applicable to both the eloquent collections and collections itself as well.

### Key takeaways: 
1. Avoid braces hell- Think this case with at 5 braces:

```php 
shuffle(shuffle(arsort(array_unique(array_merge($array1,$array2)))));
```
This is hell, if the array with more than 10 braces, you might lose track of the brace in the end. However, if you use Collection, it can be replaced with:

```php
collect($array1)
     ->merge($array2)
     ->unique()
     ->sort()
     ->shuffle()
     ->shuffle()
```
This is more readable, object-oriented and flow-thinking.

2. Unify the use of API

It is PHP original API issue that you never know where the array should in parameter. they just not consistent. for example:

    ```php
      array_walk ( $array , $callback );
      array_map ( $callback , $array);
      array_merge ( $array1 ,$array2 );// return a new array
      array_push ($array1 ,$value); // not return a new array
   ```
Laravel Collect just provide consistent API make my life easier.

    ```php
        collect($array)
         ->each($callback)
         ->map($callback)
         ->merge($array2)
         ->push($value)
     ```
3.Collection API process key-value array better- Laravel focus on processing data from a database. So many cases are with key-value array situation, rather than an indexed array. So Laravel collection has many extended methods against the original PHP functions, which process with key of the array .

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@odongoalbert 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (references any past and relevant articles in yours) or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
