### ISSUE TITLE
Understanding facial recognition using local binary pattern histogram (LBPH) algorithm

### ISSUE THREAD

**Issue by RuthAMare** [section-engineering-education/engineering-education#2640]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Understanding facial recognition using local binary pattern histogram (LBPH) algorithm

### Introduction paragraph (2-3 paragraphs):
This article will explain what LBPH algorithm is, its applications and how is it applied in facial recognition. It will further detail the process of facial recognition using LBPH and gauge its efficiency in performing facial recognition. 
Finally, this article will site some the best application areas of LBPH.

### Key takeaways: 
1. Introduction to facial recognition.
2. The working of LBPH algorithm
3. The two Modes of operation of facial recognition
4. Steps in facial recognition using LBPH
5. Applications of LBPH

### References: 
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Approved - @RuthAMare 
Please let's add more value and make the content unique/original than what can be found on the internet. For example, [this one](https://towardsdatascience.com/face-recognition-how-lbph-works-90ec258c3d6b)
Also, make sure to refer to our previous content (when and where possible).
