### ISSUE TITLE
Introduction to Linux Shell and Shell Scripting

### ISSUE THREAD

**Issue by munenekelvin** [section-engineering-education/engineering-education#2643]
### Proposed title of article
Introduction to Linux Shell and Shell Scripting

### Introduction paragraph (2-3 paragraphs):
Shell Scripting is a free and open-source computer software that runs on the Unix/Linux shell. Shell Scripting is a program that allows you to write a series of instructions to be executed by the shell. It can condense long and repetitive command sequences into a single, easy script that can be saved and performed at any time, reducing programming time. Almost every programmer  interact with shell indirectly if he/she use any major operating system. When you use terminal on Ubuntu, Linux Mint, or any other Linux distribution, you are communicating with shell.
 In this article, we will discuss about Linux shells and shell scripting.

### Key takeaways: 
By the end of this article, the reader will understand:
1. what shell, kernel and terminal are.
2. graphical shell.
3. shell scripting.
4. Simple demo of shell scripting using Bash Shell.

### References: 
N/A

**Comment by louisefindlay23** [comment]
Hi, @munenekelvin. Thanks for submitting a topic suggestion. 

Could you tell me how your proposed article differs from our existing [Intro to Shell Scripting](https://www.section.io/engineering-education/introduction-to-shell-scripting/) article that we've already published since we focus on unique and original content?

Thanks,
Louise - Content Moderator

**Comment by munenekelvin** [comment]
Hi, @louisefindlay23
My article is different from the published article # 59. In my article I prefer to introduce a concept in a more basic manner. Before the reader can understand what shell scripting is, he/she must first understand what Kernel, shell and terminal are, also understand graphical shell and how it  provide means for manipulating programs based on graphical user interface (GUI), by allowing for operations such as opening, closing, moving and resizing windows, as well as switching focus between windows. After understanding the bases, the reader can now understand about shell scripting, know their advantages and disadvantages and then do a simple demo of shell scripting using Bash Script.  The published article is based on basic things like: executing files, variables, special keywords and control flow constructs on shell in a shell scripting.

**Comment by louisefindlay23** [comment]
Thanks for the clarification, @munenekelvin. Topic approved.
