### ISSUE TITLE
Data  abstraction in C#

### ISSUE THREAD

**Issue by Dick7603** [section-engineering-education/engineering-education#2648]
### Proposed title of article
Data  abstraction in C#

### Introduction paragraph (2-3 paragraphs):
The property of data abstraction is that just the most important details are displayed to the user. The user is not shown the units that are trivial or non-essential. The practice of identifying only the required attributes of an object while discarding the irrelevant information is known as data abstraction. An object's properties and actions distinguish it from other objects.

In this article, the reader will understand data abstraction with the aid of the abstract classes 

### Key takeaways: 
By the end of this article the reader will understand:
1. what is data abstraction.
2. types of abstraction
3. abstract classes.
4. use of abstract classes and abstract methods.
5. encapsulation vs data abstraction.
6. advantage of abstraction.

### References: 
N/A

**Comment by hectorkambow** [comment]
@Dick7603 

Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (references any past and relevant articles in yours) or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved
