### ISSUE TITLE
 CSS Selectors and how to use them to Style Your Web Page

### ISSUE THREAD

**Issue by Beatricewanjiru** [section-engineering-education/engineering-education#2650]
### Proposed title of article
 CSS Selectors and how to use them to Style Your Web Page

### Introduction paragraph (2-3 paragraphs):
CSS selectors are one of the most important parts of CSS. They let you style specific HTML elements on your website differently.

You wouldn't be able to style your page the way you want it to look without CSS selectors.

If you want to create amazing elements then you need to understand the CSS selectors and what you can do with them. You need to understand the basic CSS selectors before you work your way up to the advanced CSS selectors.

This article will cover both. By the end, you will be able to use CSS selectors to create your incredible elements.

### Key takeaways: 

1. Definition of CSS Selectors
2. CSS Element Selectors
3. Universal Selector
4. How to Group CSS Selectors
5. Advanced CSS Selectors

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Hi, @Beatricewanjiru. Thanks for submitting your topic suggestion. 

Could you tell me how your content will differ from similar articles we've already published about CSS and CSS Selectors such as [Getting Started with CSS](https://www.section.io/engineering-education/getting-started-with-css/), [Types of Styling in CSS](https://www.section.io/engineering-education/types-of-styling-in-css/) and [How CSS Works Behind the Scenes](https://www.section.io/engineering-education/how-css-works-behind-the-scenes/) since we look to publish original and unique content.

Thanks,
Louise - Content Moderator

**Comment by Beatricewanjiru** [comment]
@louisefindlay23  thanks for the ping. I intend to discuss Selectors in detail where I will look at each type of selector and how it is used in styling a web app. I had looked at the published articles and noticed that none is delivering the knowledge of selectors as a beginner would expect.  Therefore, using this article, I want to make sure that every developer who uses selectors to style a web page,  has all the knowledge that will help him/her succeed. 

Please notify me if there is any other issue. Thanks

**Comment by hectorkambow** [comment]
@Beatricewanjiru 

Just pinging you on this topic form - to inform we will be closing this topic form only to make some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date when the article is ready to publish.

**Comment by Beatricewanjiru** [comment]
@hectorkambow the topic is ready. Please re-open

**Comment by Ericgacoki** [comment]
Re-opening since the topic had already been `approved` and the student has linked a `PR` to it.
