### ISSUE TITLE
Iris Tracking using Tensorflow.js in a Browser

### ISSUE THREAD

**Issue by zolomohan** [section-engineering-education/engineering-education#2651]
### Proposed title of the article

Iris Detection using Tensorflow.js

### Introduction paragraph(s):

TensorFlow is a free and open-source software library for machine learning. It can be used across a range of tasks but has a particular focus on the training and inference of deep neural networks.

In this tutorial, we'll learn how to implement Iris Tracking in a webpage using Tensorflow.js.

### Key takeaways

- Set up Project for Iris Tracking using Tensorflow.
- Add Webcam feed to Screen.
- Use Tensorflow to detect Iris.
- Draw a circle around Iris in the webcam feed.

### References: 
N/A

**Comment by hectorkambow** [comment]
@zolomohan 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (references any past and relevant articles in yours) or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

**Comment by hectorkambow** [comment]
@zolomohan 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
Please proceed ping us to open the topic form to tie to your PR if and when the article is ready to be published.

**Comment by zolomohan** [comment]
Sure thing @hectorkambow.
