### ISSUE TITLE
Assertion and design by contract in java

### ISSUE THREAD

**Issue by Paul22691** [section-engineering-education/engineering-education#2659]
### Proposed title of article
Assertion and design by contract in java
### Introduction paragraph (2-3 paragraphs):
The design by contract specifies the interaction between various components of an application. To achieve this it defines a contract based on which the components of the application communicate with each other.

The design by contract technique uses assertions to check whether the application meets the requirement specified in the defined contract. These assertions can be used to test the assumptions made by a programmer in java programming language.
### Key takeaways: 
1. Design by contract.
2. Implementing assertion.
3. Assertion rules.
4. How to create a java program using assertion.
### References: 
N/A

**Comment by hectorkambow** [comment]
@Paul22691 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles (references any past and relevant articles in yours) or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved

**Comment by hectorkambow** [comment]
@Paul22691 
Just pinging you on this topic form - to inform we will be closing this topic form only to make some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date when the article is ready to publish.
