### ISSUE TITLE
How To Handle File Upload in Flask

### ISSUE THREAD

**Issue by wobin1** [section-engineering-education/engineering-education#2664]
### Proposed title of article
How To Handle File Upload in Flask
### Introduction:
Flask is a lightweight or micro web framework built with python that helps in creating web applications. It provides useful tools and features that make building web applications easier. Flask is extensible and doesn’t force a particular structure or require complicated boilerplate code before getting started. it gives developers flexibility.
One important feature in web applications is the ability to let users upload files. These files could be pictures, pdf, audio CSV e.t.c. in this article we will look at how to set up a basic app flask that will allow users to upload files.

### Key takeaways: 
In this article the reader will learn:
1. how to set and activate a virtual environment
2. how to set up a basic web application with flask
3. how to handle file uploads with flask

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@wobin1 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please references any relevant EngEd articles in yours. - Approved
