### ISSUE TITLE
How to Build Apps with Serverless Architecture?

### ISSUE THREAD

**Issue by kerubo-tech** [section-engineering-education/engineering-education#2667]
### Proposed title of article
How to Build Apps with Serverless Architecture?

### Introduction:
When a team considers building a serverless app, they have to re-adapt to the specifics of Сloud architecture. This article will discuss the stages of building frontend and backend in the serverless application model, discuss its opportunities and limitations, and reference best examples.

### Key takeaways:
At the end of the article, the reader will be able to:
- understand the concept of Serverless Architecture
- know if Serverless Architecture can be used to build mobile applications
- understand the advantages of Serverless Architecture for Apps development
- understand how the Serverless Application model works
- know examples of Serverless applications

### References: 
N/A

**Comment by hectorkambow** [comment]
@kerubo-tech 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please references any relevant EngEd articles in yours. - Approved
