### ISSUE TITLE
How to Set up and Configure  Redis Caching for WordPress

### ISSUE THREAD

**Issue by Catemacharia** [section-engineering-education/engineering-education#2671]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

Redis an open-source in-memory data structure store that can be used as a caching system. It is a memory caching software that runs on the service.

Redis object cache can be used to optimize the backend performance of WordPress website database usage. This will caching database queries objects, and it stores them in memory. As a result, the strategy will enhance the server response time as well as the website speed.

Whenever a user accesses a  WordPress website, a request is sent to the MySQL server, and then the request is served back to the user from the same server. This operation can be expensive/time, and resource-consuming if you have a large backend WordPress panel.

Redis object can be used to store the cache of this request outputs of the particular query sent to the MySQL server. So when another makes the same request that requires the same query transaction, instead of hitting the MySQL server again, the Redis object will serve the request from the object cache.

This guide will teach you how to set up and configure Redis object cache for your WordPress website or blog.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

What is Redis object cache?
How Redis object works
Setting up and configuring Redis object for WordPress

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thanks, @Catemacharia for the great topic suggestion. Could you tell me how will your article differ from existing Redis WordPress guides and our Redis Node.js [tutorial](https://www.section.io/engineering-education/implementing-caching-in-nodejs-using-redis/)?

**Comment by Catemacharia** [comment]
I like approaching a topic in a more beginner introductory. Before jumping in to discuss guide steps, I like to explore more about the subject. For example, in this case, we are talking about Redis and WordPress as a single topic. A reader needs first to understand what Redis is, how Redis work in relation to the subject, get to know the reasons for configuring the WordPress page with Redis and the benefits of this configuration.

**Comment by louisefindlay23** [comment]
That's great, @Catemacharia. We really love articles that go into detail about the technologies they're covering and go the extra mile in tailoring to the beginner audience. Topic approved.
