### ISSUE TITLE
Getting Started with PHP Sessions

### ISSUE THREAD

**Issue by Neema-2016** [section-engineering-education/engineering-education#2673]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting Started with PHP Sessions

### Introduction paragraph (2-3 paragraphs):
PHP Sessions provide server side storage of user information by use of session variables and makes this information accessed from several pages throughout a website.
Sessions uniquely identify users via a Session Identifier which provides connection of that particular user to their stored data on the server.
This article intends to cover how to create a Session, how to update a Session and how to destroy a Session.

### Key takeaways: 
1.What is a Sessions and why sessions are used.
2. How to create a Session.
3. How to access a Session.
4. Updating a PHP Session.
5. How to destroy a Session.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Neema-2016 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please references any relevant EngEd articles in yours. - Approved
