### ISSUE TITLE
MLP-Mixer: A pure MLP architecture for computer vision

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#2675]
### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

MLP-Mixer: A pure MLP architecture for Vision

### Introduction paragraph (2-3 paragraphs):

Convolutional Neural Networks (CNNs) are the go-to model for computer vision. Recently, attention-based networks, such as the Vision Transformer, have also become popular. In this article, we show that while convolutions and attention are both sufficient for good performance, neither of them are necessary. The article discusses the MLP-Mixer, an architecture based exclusively on multi-layer perceptrons (MLPs).

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this article, a reader should be able to understand:

1. An introduction and brief overview
2. The MLP-Mixer Architecture
3. The effects of Scale
4. The learned weights visualization

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

1. [Perceptron Algorithm - A Hands On Introduction](https://www.section.io/engineering-education/perceptron-algorithm/)
2. [MLP-Mixer: An all-MLP Architecture for Vision](https://arxiv.org/abs/2105.01601)

**Comment by hectorkambow** [comment]
@Bayler 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please references any relevant EngEd articles in yours. - Approved
