### ISSUE TITLE
Building a Nest.js microservice application using Redis as the transporter

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#2680]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

### Introduction paragraph (2-3 paragraphs):

Nest.js is a JavaScript framework for building efficient and scalable hybrid static and server-side applications. Nest.js is built on top of React to abstracts rendering complexity, giving you the flexibility to build scalable React applications. This hybrid enables your React apps to have additional functionality, such as server-side rendering. The Nest.js framework will allow you to build a react app but render the content in advance on the server-side. Traditional with React, you can only render on the client-side. Nest.js gives you the flexibility to choose which data fetching strategy fits your application as you grow and scale your application from a few pages to thousands. With server-side rendering, pages are rendered during the build-up phase. The content is served ahead of time to user or search engine bots. This way, they will only receive the fully rendered HTML. After receiving this initial page, client-side rendering takes over and works just like a traditional React app. This tutorial will teach you how to create a Nest.js Microservice application with Redis.

##### An Overview of a microservice

Microservice is an architectural design that allows you to create small modules/components of an application that can scale on demand. Each component is packaged independently and can communicate with each other via APIs. Nest.js comes with built-in support for microservice architecture and multiple transport layers. These transport layers are in charge of transferring messages between microservice instances. We can use Redis as a transport layer protocol for end-to-end connectivity to allow flow control and segmentation between different microservices. As a result, every microservice can connect to different channels, and every channel can have various microservices connected to it.

### Key takeaways: 

What is Nest.js
An Overview of a microservice
Setting Redis and creating client and server apps
Setting Nest.js microservice in both apps
Sending a message from the client to the server using Redis as the transporter

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Approved - @kimkimani
