### ISSUE TITLE
Building an Email parser using Python

### ISSUE THREAD

**Issue by vinstex** [section-engineering-education/engineering-education#2687]
### Proposed title of the article
Parsing emails in Python

### Introduction paragraph (2-3 paragraphs):

Perhaps you are a machine learning engineer trying to build an email spam classifier and you want to get some way of pre-processing the emails or you are trying to look for some correlations between some emails, you will in one way or another have to parse the emails first. We will look at how to do that using Python. Python has the `email` module containing methods to help us achieve this.

### Key takeaways: 

1. Loading emails from a datastore
2. Processing the loaded emails
3. Learn about the `email` module

### References: 
[Official Python Docs](https://docs.python.org/3/library/email.parser.html)

**Comment by ahmadmardeni1** [comment]
Approved - @vinstex 
Try to build a unique/original app different from what can be found on the internet.
What datastore are you going to use?

**Comment by vinstex** [comment]
Thank you. The datastore is found in the SpamAssassin site I've referenced
there.
