### ISSUE TITLE
Deploying Spring Boot application to Kubernetes cluster

### ISSUE THREAD

**Issue by flavianadhiambo** [section-engineering-education/engineering-education#2688]
### Deploying Spring Boot application to Kubernetes cluster
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Docker is a tool designed to make it easier to create and deploy and run applications using containers such that a developer is allowed to package an application, all its libraries, and dependencies as one during deployment. While Docker runs on a single node, Kubernetes is meant to run several nodes across a cluster.

In this article, I will explain a step-by-step procedure of deploying Spring Boot Docker containers to a Kubernetes cluster.

### Key takeaways: 
1. Building a Spring Boot Docker container.
2. Using Load Balancers to expose containers with Kubernetes.
3. Deploying the Spring Boot Docker container to the Kubernetes cluster.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@flavianadhiambo 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please references any relevant EngEd articles in yours. - Approved
