### ISSUE TITLE
Understanding DHCP Server Router Configuration

### ISSUE THREAD

**Issue by samotieno** [section-engineering-education/engineering-education#2689]
### Proposed title of article
Understanding how to configure DHCP server on routers.

### Introduction paragraph (2-3 paragraphs):
A dedicated DHCP server is scalable and easy to manage but it can be costly to have one at every location in a network, more so when the network is large. In such situations, network routers can be configured to provide the DHCP services without the need for a dedicated server. This will enable the network administrator to automate the process of configuring devices on the IP networks by use of DHCP protocol and save the extra cost of buying  DHCP servers.

In this article, we will show the reader how one can utilize a router to provide  DHCP services and be able to configure it on the network. This will reduce the workload of assigning IP addresses manually on the network devices.

### Key takeaways: 
-Understand how the DHCP server works.
-Understand how to configure a router to provide DHCP services.
-How to use DHCP protocols in assigning IP addresses dynamically using DHCP server

### References: 
N/A

### Templates to use as guides
N/A

**Comment by samotieno** [comment]
cc @hectorkambow

**Comment by samotieno** [comment]
cc @srishilesh @ahmadmardeni1

**Comment by ahmadmardeni1** [comment]
This is a hardware related-topic.
Can you use the same concepts on software like Cisco Packer tracer? @samotieno

**Comment by samotieno** [comment]
Hey @ahmadmardeni1  The concept behind this article is software-related as it involves the use of network simulator tools like the packet tracers, GNs3, NetSim for the configuration of the DHCP server on the routers.

**Comment by ahmadmardeni1** [comment]
Okay if you are using Packet tracer or any other software then it is approved @samotieno
