### ISSUE TITLE
Building Rest API with FastAPI

### ISSUE THREAD

**Issue by atoyegbe** [section-engineering-education/engineering-education#2693]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
[FastAPI](https://fastapi.tiangolo.com/) is a modern, fast (high-performance), a web framework for building APIs with Python 3.6+ based on standard Python type hints. FastAPI is a Python framework and set of tools that enable developers to use a REST interface to call commonly used functions to implement applications. In this tutorial, i will be creating a simple API using FastAPI. This article aims to teach the reader how to create various CRUD APIs using FastAPI.
### Key Takeaways: 
Basic Python knowledge is required to understand the concept covered in this article.

1. What is FastAPI.
2. Why FastAPI?.
3. How to create CRUD API using FastAPI.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ahmadmardeni1** [comment]
Please check if it is not already covered [here](https://www.section.io/engineering-education/search/?q=fast%20api).

Also, make sure you are building a unique application using FastApi. This will only be approved if you build a unique application that differs from what can be found on the internet or their docs. @atoyegbe

**Comment by hectorkambow** [comment]
@atoyegbe 
Just pinging you on this topic form - to inform we will be closing this topic form only to make some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date when the article is ready to publish.
