### ISSUE TITLE
Storing  Python Functions in Modules

### ISSUE THREAD

**Issue by duncandegwa** [section-engineering-education/engineering-education#2695]
### Proposed title of article

Storing  Python Functions in Modules

### Introduction paragraph (2-3 paragraphs):
One advantage of functions is the way they separate blocks of code from your main program. By using descriptive names for your functions, your main program will be much easier to follow. You can go a step further by storing your functions in a separate file called a module and then importing that module into your main program. An import statement tells Python to make the code in a module available in the currently running program file. 

Storing your functions in a separate file allows you to hide the details of your program’s code and focus on its higher-level logic. It also allows you to reuse functions in many different programs. When you store your functions in separate files, you can share those files with other programmers without having to share your entire program. Knowing how to import functions also allows you to use libraries of functions that other programmers have written. In this article, we will learn how to store Python functions in modules and how to import them.

### Key takeaways: 

1. Importing an entire module
2. Importing specific functions
3. Using as to give a function an alias
4. Using as to give a module an alias
5. Importing all functions in a module

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Not approved - @duncandegwa 
The content can be found on the internet.
Please feel free to make another topic-suggestion with a unique/original idea.
