### ISSUE TITLE
Statistical Hypothesis Testing With Python Implementation

### ISSUE THREAD

**Issue by wizardcalidad** [section-engineering-education/engineering-education#2696]
### Title
Statistical Hypothesis Testing with Python Implementation

### Introduction
This tutorial is a comprehensive explanation and implementation of statistical hypothesis testing methods such as t-test, chi-squared test & ANOVA in python, It is well known that most of the implementation of these techniques are always in R, and most Data Scientists and Analysts who use python always shy away from it. 
Despite being a beginner-friendly tutorial, not just a mid-level data scientist or machine learning engineer but a senior in the field as well will pick up one or two concepts that people find confusing in the world of work. The way it's being transitioned from basics to advance in no time is awesome and magnificent. It demystifies the concept of hypothesis and how it works before taking it a step further to show the implementation with python on Iris datasets. 
For professionalism's sake, the tutorial is written in the best play way method trying to stay relevant on the content and not lose readers. It is a promising piece even a novice will enjoy.

### Goals
The goal of this tutorial is to:
1. Make convincing concepts clearer and understanding enough.
2. Show the implementation of t-test, chi-squared test & ANOVA with python.
3. Make clear the trade-off between type 1 and type 2 error of null hypothesis.
4. Explain the confidence of the null hypothesis.
5. Present some pandas function for exploratory data analysis.
6. Show how to write python functions for data manipulation.

### Prerequisites
- Step 1 — Create a python virtual environment on your system / start a new notebook on google colab.
- Step 2 — If you've created a virtual environment on your system, install jupyter notebook or jupyter lab inside it
- Step 3 — Install all the libraries needed, such as NumPy, Pandas, Scipy on your Notebook.
- Step 4 — Import all libraries into your notebook or google colab.
- Step 5 — Download Iris dataset. (It is the dataset used for this tutorial)
- Step 6 — Get ready to follow through.

### Conclusion 
I strongly believe at the end of this tutorial, everyone will have gained one or two things regardless of their field of study or background, with the effort put in to make complex things look very basic and relatable.
It is definitely an interesting read.

### References
- [Machine Learning Mastery](machinelearningmastery.com)
- [Renesh Bedre](reneshbedre.com)
- [Google](google.com)
- [Kaggle](kaggle.com)

**Comment by ahmadmardeni1** [comment]
Approved - @wizardcalidad 
I loved the idea, please when you make the PR, @ me, I would like to read it.

**Comment by wizardcalidad** [comment]
Thanks a bunch, I kept refreshing the issue page not knowing you've sent
mail, I am honoured for you to have love to read this.

**Comment by wizardcalidad** [comment]
*i have an important question*

the results to the implementation, instead of snapping and attaching them
as pictures, i discovered a way to convert my notebook to markdown but the
results block has some HTML codes with it, and it has a perfect preview
though which I think is the most important, should i stick to that or use
the result image way? but works but the conversion is more efficient.
