### ISSUE TITLE
Understanding inheritance in C#

### ISSUE THREAD

**Issue by bancy-bit** [section-engineering-education/engineering-education#2697]
### Proposed title of article
Understanding inheritance in C#

### Introduction paragraph (2-3 paragraphs):
One of the most powerful notions or essential properties of an object-oriented programming language is inheritance. It's found in almost every OOPs-based programming language. Its primary goal is to reuse the same code.

In C#, inheritance is the process of transferring all of the properties of one class to another. The base class and the derived class are the two types of classes. The base class is also known as a parent class, and we want to inherit the attributes and methods of this class to another class. The derived class, also known as the child class, is used to inherit the base class's or parent class's properties and functions. It allows you to reuse the same code and eliminates the need to define the same properties again and over.

### Key takeaways: 
In this article, we will learn:
1. what is inheritance.
2. types of inheritance.
3. advantages o inheritance in C# programming.
4. features of inheritance.
5. why use inheritance and how it makes it easy to program/work with.

### References: 
N/A

**Comment by mohamedgh16** [comment]
Hello @bancy-bit, this topic is already covered [here](https://www.section.io/engineering-education/getting-started-with-inheritance-using-c/).
