### ISSUE TITLE
Getting started with STL in C++

### ISSUE THREAD

**Issue by Anand-Sinha** [section-engineering-education/engineering-education#2698]
### Proposed title of article
Getting started with STL in C++

### Introduction paragraph (2-3 paragraphs):
STL stands for Standard Template Library which is a powerful set of C++ template which provides various classes and functions that implements many commonly used data structures and algorithms few of which are Vector, List, Stack, Queue, and Map.
If you are familiar with python you must be impressed with how short and readable python codes are, but on the downside, it is also much slower than C++ which is a little concerning if you are preparing for competitive programming.
STL brings the same functionality of readability while significantly reducing the lines of code and without compromising on time but all in C++!

### Key takeaways: 
- What STL (Standard Template Library) is.
- Exploring STL containers, iterators, and algorithms.
- How to use various STL libraries (Pair, Set, Vector, List, Stack, Queue, Map).
- Advantages of STL in general programming and competitive programming.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Not approved - @Anand-Sinha 
This information can be found easily on the official website.
Please feel free to make another topic-suggestion.

**Comment by Anand-Sinha** [comment]
No worries I'll look into it, thanks!
