### ISSUE TITLE
How to create a WordPress Plugin

### ISSUE THREAD

**Issue by essy258** [section-engineering-education/engineering-education#2700]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to create a WordPress Plugin

### Introduction paragraph (2-3 paragraphs):
WordPress Plugins allow users to easily modify, customize, and enhance any WordPress website. However, sometimes you can’t find a plugin that meets your needs or you may simply want to try your hand at developing your own solution. 

If you’re interested in WordPress plugin development, you might be confused about where to even begin. Fortunately, it’s easier to build your own plugins than you might expect. 

This article will walk you through the steps in creating a WordPress plugin.

### Key takeaways: 
1. The Overview of a WordPress plugin
2. How WordPress plugins work
3. Steps of WordPress Plugin Development
- Step 1: Access your site via FTP
- Step 2: Navigate to WordPress Plugins folder and create your plugin file
- Step 3: Create the main PHP file for your plugin
- Step 4: Set up your plugin to add functions
- Step 5: Compress your plugin folder and export the plugin file
- Step 6: Activate and Run the plugin on your WordPress site

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Hi, @essy258. Great topic suggestion. I'm sure our readers will find it very interesting.

Can you tell me how your article will differ from similar articles published elsewhere such as [Tutplus](https://webdesign.tutsplus.com/tutorials/create-a-custom-wordpress-plugin-from-scratch--net-2668) and [Smashing Magazine](https://www.smashingmagazine.com/2011/09/how-to-create-a-wordpress-plugin) since we focus on unique and original content?

Thanks,
Louise - Content Moderator

**Comment by essy258** [comment]
Hello, @louisefindlay23. My article is about a WP functionality plugin. Some functionalities are either too basic or too custom-made for there to be a plugin for it. That's when the function PHP file comes in. A functionality plugin is a place for you to put your PHP code snippet.

The difference between the content my article will deliver from other articles is that it's about creating a functional plugin that is specific to your website and not publicly available for downloads. So you can structure it and be easily managed. My article will deliver original content and will be an interactive topic too. 

Regards.

**Comment by louisefindlay23** [comment]
Thanks, @essy258. Topic approved.
