### ISSUE TITLE
How to Build a Static site with Gridsome

### ISSUE THREAD

**Issue by ejirocodes** [section-engineering-education/engineering-education#2702]
### What is Gridsome?
[Gridsome](https://gridsome.org/) is a data-driven static site generator that generates HTML files from local files, CMSs, and external APIs. HTML files are initially loaded in the browser as static files and then hydrate into fully powered Vue.js apps. This improves SEO while providing all the benefits of Vue. The data is prefetched and stored in a GraphQL data layer.

### Key takeaways: 
Basic knowledge of Vue is required to understand the concept covered in this article.

1. What is Gridsome.
3. Folder structure
2. Building a blog with Gridsome

### References: 
[Getting started with Gridsome
](https://blog.logrocket.com/getting-started-with-gridsome/)

@louisefindlay23

**Comment by louisefindlay23** [comment]
Great topic suggestion @ejirocodes. Topic approved. Be sure to write a detailed introduction about what is Gridsome/JAMStack/static site generators to differentiate your tutorial for similar ones such as [this](https://mannes.tech/gridsome-jamstack-introduction).

**Comment by ejirocodes** [comment]
Got it. Thanks, @louisefindlay23.

**Comment by hectorkambow** [comment]
@ejirocodes 
Just pinging you on this topic form - to inform we will be closing this topic form only to make some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date when the article is ready to publish.

**Comment by ejirocodes** [comment]
Alright, thanks for the heads up @hectorkambow
