### ISSUE TITLE
How to send email with Django

### ISSUE THREAD

**Issue by Samuel-2626** [section-engineering-education/engineering-education#2705]
### Proposed title of the tutorial
How to send email with Django

### Introduction paragraph (2-3 paragraphs):
Most web applications require some sort of function to send emails to their customers. Sending an email with Django is pretty straightforward.  

In this tutorial, you will learn to create the views, forms and templates to enable you to send emails to your customers.

### Key takeaways: 
- Sending email with Django
- Using Gmail SMTP
- Views, forms, and templates with Django

**Comment by hectorkambow** [comment]
@Samuel-2626
 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 can be reopened once the first PR is merged.

**Comment by Samuel-2626** [comment]
@hectorkambow can this issue be re-open now, my previous article just got published :)

**Comment by hectorkambow** [comment]
@Samuel-2626 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
