### ISSUE TITLE
Hosting Websites live using GitHub

### ISSUE THREAD

**Issue by Kimosop-Wakanda** [section-engineering-education/engineering-education#2707]
**Introduction**
GitHub is a free, open-source cross-platform that not only allows software development but also internet hosting platform for its users.
For our tutorial, we will learn how to host your websites live using GitHub.

First, will create an account on GitHub and then install GitHub Desktop on your PC.
We will then create a .html and .css file to that we will be using as our demo website.
On GitHub, we will learn how to create a new project that we will be able to publish.
We will then see how we can copy our files to the new repository and publish the files and be ready for the 'magic'.
The article proposed will use images to guide the user step by step to avoid any errors.
The terms used will be simple and easily understood by every user.

**Key Takeaways**
By the end of the article, the user should be able to: 
1. Sign up on GitHub without any problem.
2. Install GitHub Desktop on the pc.
3. Create a project on GitHub.
4. Publish project and host them live.
5. Access website hosted on GitHub on a browser

**Reference**
N/A

**Comment by WanjaMIKE** [comment]
Hosting a website on `xampp` seems quite `basic`. How will it differ from other existing tutorials and official documentation? Such as https://www.apachefriends.org/faq_windows.html

**Comment by Kimosop-Wakanda** [comment]
Update made @WanjaMIKE 
Please continue with the approval process

**Comment by ahmadmardeni1** [comment]
Not approved - This content can be found easily on the internet.

Please feel free to make another topic-suggestion.
