### ISSUE TITLE
Namespaces in C#

### ISSUE THREAD

**Issue by ruth-ctrl** [section-engineering-education/engineering-education#2708]
### Proposed title of article
Namespaces in C#

### Introduction paragraph (2-3 paragraphs):
The namespace is a descriptive area within which identifiers (type names, features, variables, etc.) are given a scope. Namespaces are used to arrange code into logical groups and to discourage name collisions, particularly when various libraries are included in your codebase.
In C#, the namespace is used for organizing many classes to handle the application very easily. It is helpful for keeping a set of names separate from another. You can not conflict one class name declared in one namespace with the same class name declared in another namespace. It allows organizing the code systematically with a hierarchical system in a group. The hierarchical system can be used to define nested namespaces. You can keep the code in an organized manner by placing the code in different namespaces.

### Key takeaways: 
In this article the learner will understand:
1. overview of namespace.
2. Why do we Need Namespaces in C#.
3. How to define Namespaces in C#.
4. How to Access Namespaces in C#.

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Not approved - @ruth-ctrl 
The concepts are already covered and can be found easily on the internet.
Please feel free to make another topic suggestion as we are looking for unique/original content.
