### ISSUE TITLE
Debugging of Matlab code

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#2709]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
Just as human being, softwares too are prone to errors. This could be caused by writing a code that the software don't understand or a mistyping by the user. When you run your software with these errors, it's either the program will not run or give unexpected results. It is not running because it doesn't understand the code and it gives unexpected results due to misinterpretation of the code. These errors are called a bug. The process of analysing your code to remove these errors is called debugging.
Debugging of a code at some points may be hectic since it involves locating the error. Also, Matlab's error statement may sometimes be difficult to understand. In this article, we are going to look at how to locate the error in a code and how to correct them. Besides that, Matlab has an inbuilt debugger that helps in debugging of codes. We will also look at this tool and how to use it 

### Key takeaways: 
- Matlab's possible causes of errors 
- How to use a debugger.
- How to correct the possible errors.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@jumapaul 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by ahmadmardeni1** [comment]
.

**Comment by WanjaMIKE** [comment]
Closed #2709 via #2998.
