### ISSUE TITLE
Python or R For Data Science?  

### ISSUE THREAD

**Issue by jaykip** [section-engineering-education/engineering-education#2710]
### Proposed title of the article
Python or R For Data Science? 

### Introduction paragraph (2-3 paragraphs):
If you work in data science or analytics, you’re probably well aware of the Python vs. R debate. Although both languages are bring the future to life — through artificial intelligence, machine learning, and data-driven innovation — some strengths and weaknesses come into play.

In many ways, the two open-source languages are very similar. But they also differ in many ways. The main difference is that Python is a general-purpose programming language, while R has its roots in statistical analysis. Increasingly, the question isn’t which to choose, but how to make the best use of both programming languages for your specific use cases.

### Key takeaways: 

1. Differences in terms of: 
- Ecosystem 
- Ease of learning
- Data handling capabilities 
- Integrated Development Environment
- Data Collection
- Data Visualization
2. When to use Python
3. When to use R 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Approved - @jaykip
