### ISSUE TITLE
Introduction to Dialog Boxes in C#

### ISSUE THREAD

**Issue by mosesmwangi442** [section-engineering-education/engineering-education#2711]
### Proposed title of article
Introduction to Dialog Boxes in C#

### Introduction paragraph (2-3 paragraphs):
A dialog box in C# is a type of window, which is used to enable common communication or dialog between a computer and its user. A dialog box is most often used to provide the user with the means for specifying how to implement a command or to respond to a question. **Windows.Form** is a base class for a dialog box.

The simplest type of dialog box is the warning which displays a message and may require the user to acknowledge that the message has been read, usually by clicking “OK” or a decision as to whether or not an action should continue by clicking “OK” or “Cancel”.

### Key takeaways: 
1. What are dialog and message boxes
2. Types of dialog boxes
3. Types of Show Methods in Message boxes
4. Common Dialog Box and how to use them

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
We already covered windows forms [here](https://www.section.io/engineering-education/search/?q=windows%20forms).
Not approved - @mosesmwangi442
