### ISSUE TITLE
Understanding the CSS Box-Model

### ISSUE THREAD

**Issue by Terripha** [section-engineering-education/engineering-education#2712]
### Proposed title of article
Understanding the CSS Box-Model

### Introduction paragraph (2-3 paragraphs):
The box-model is one of the basics things in CSS and HTML. Everything in CSS is made of boxes so it is crucial to understand how the CSS box model works but even today, lots of web developers don’t understand the idea of how box-model behaves.  So, in this article, I will explain the basic logic of the box-model and why it is called the box-model. Besides, I will also give a deeper insight into the behavior of the box-model.

### Key takeaways: 
1. What is a box-model
2. Basic types of boxes
3. Controlling the Box-model
4. Styling the Box
5. Understanding the Sizing of Boxes

### References: 
N/A

**Comment by louisefindlay23** [comment]
Hi, @Terripha. Sounds like a great topic that would compliment our existing articles on CSS. Approved. 

Be sure to cover the box-model in-depth so your article isn't similar to our existing CSS Flexbox and Grid articles.
