### ISSUE TITLE
Build and Dockerize a Full-stack React application with docker-compose

### ISSUE THREAD

**Issue by mosesreigns** [section-engineering-education/engineering-education#2716]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):

React is one of the common and famous front web frameworks. Nevertheless is most situations, a web application will require back-end services to process different transactions. In this case, React as a front-end framework is not complete, and thus you need a back-end service to make this application complete. On the other hand, docker is the perfect containerizing technology to set up all the environments you need to set up this full-stack application. Docker will help you set React and any front-end environments, then run and build the whole application on a virtual environment using docker.

This tutorial will build a very handy React full-stack application and then dockerize and run the application environments in docker containers. We will dockerize this full-stack React application with Node.js as the back-end service, MySQL as the application database, and NginX for reverse proxy.

### Key takeaways: 

Setup project basics
Build the back-end Node.js application
Build the front-end React application
Create the development environments Docker files
Create the docker-compose.yml file
Run and test the containerized application 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@mosesreigns 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
