### ISSUE TITLE
Implementing a GraphQL server using Prisma, SQLite, and Nest.js with Typescript

### ISSUE THREAD

**Issue by JuliusGikonyoNyambura** [section-engineering-education/engineering-education#2717]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Implementing a GraphQL server using Prisma, SQLite, and Nest.js with Typescript

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

Nest.js is built on Node.js and Express, which is arguably the most popular way to build servers with JavaScript. Nest is a typescript-based JavaScript framework for developing and scaling backend microservices. Being statically typed with typescript, it allows you to do various JavaScript tasks as an escape hatch. This guarantees that your code is more solid. Furthermore, it makes the code easier to navigate through your code because everything is strongly typed and more scalable for large applications. This provides an out-of-the-box application architecture that enables developers and teams to construct highly testable, scalable, loosely connected, and easily maintainable applications.

Nest.js, like other frontend frameworks, is designed to deliver an Angular-like experience. As a result, when you create a new Nest.js application, you will be launched into an environment that resembles a normal front-end Angular application. The major distinction is that what you end up creating will be your backend services. You'll set up a server, link it to databases, and do all of the typical tasks associated with a back-end-based application.

The guide will focus on getting a simple server project up and running. We will use technologies such as Prisma, Nest.js, graphql, and SQLite as the project database.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

- Discuss what Nest.js entails.
- A quick glance on Grapgql.
- What are Prisma and SQLlite?
- Create a simple posts Nest.js GraphQL server-based application with all CRUD operations supported.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

https://docs.nestjs.com/cli/overview
https://docs.nestjs.com/techniques/database
https://www.sqlite.org/index.html
https://graphql.org/learn/queries/
https://www.apollographql.com/docs/apollo-server/
https://www.prisma.io/docs/concepts/components/prisma-client/crud

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Where are your introduction paragraph, key takeaways, and references? @JuliusGikonyoNyambura

**Comment by hectorkambow** [comment]
@JuliusGikonyoNyambura 

Just following up before we close the issue - due to inactivity - it can be re-opened whenever needed.

**Comment by JuliusGikonyoNyambura** [comment]
> Where are your introduction paragraph, key takeaways, and references? @JuliusGikonyoNyambura

@ahmadmardeni1 I have added some content. Can you please open the issue for topic approval?

**Comment by ahmadmardeni1** [comment]
Please fill out your key takeaways and references. @JuliusGikonyoNyambura

**Comment by JuliusGikonyoNyambura** [comment]
> Please fill out your key takeaways and references. @JuliusGikonyoNyambura

I have update them @ahmadmardeni1

**Comment by JuliusGikonyoNyambura** [comment]
@ahmadmardeni1, can I start building on the project for this article?

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - Approved.
Please be sure to double-check that it does not overlap with any existing EngEd articles:
- [Nest.js](https://www.section.io/engineering-education/search/?q=Nest.js)
- [graphql](https://www.section.io/engineering-education/search/?q=graphql)
- [Prisma](https://www.section.io/engineering-education/search/?q=prisma)
