### ISSUE TITLE
Getting Started with python decorators

### ISSUE THREAD

**Issue by mia-roberts** [section-engineering-education/engineering-education#2718]
### Proposed title of article
Getting Started with python decorators

### Introduction paragraph (2-3 paragraphs):
Pythons decorators are a design pattern that allows one to modify the functionality of an existing function  without change in the object structure. They are callable objects that can be used to  modify a function, method or a class. The decorators occur in the line just immediately before the object definition.

In this article we will look into python decorators and how to use them in python.

### Key takeaways: 
1. When to use decorators
2. How to create python decorators
3. Class decorators in python

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@mia-roberts 

Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@mia-roberts 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
Please proceed ping us to open the topic form to tie to your PR if and when the article is ready to be published.

**Comment by mia-roberts** [comment]
Hello @hectorkambow 

kindly open this issue, I have done it and opened a PR to fix it.

Regards
