### ISSUE TITLE
Getting Started With React Cosmos

### ISSUE THREAD

**Issue by marienjus** [section-engineering-education/engineering-education#2719]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting Started With React Cosmos

### Introduction paragraph (2-3 paragraphs):
One of the major advantage of React is that users can build components and reuse them repeatedly within a specific codebase. You can take this feature further with the help of the React Cosmos developer tool.

React Cosmos is used for building isolated and scalable React components. It lets you create a sole component for your React application. You can consider different use cases as well as different design patterns when making use of React Cosmos, which will allow you to create very versatile, isolated components that fit many other conditions.

### Key takeaways: 
1. Benefits of using React Cosmos
2. Reusable component creation
3. Integrating React Cosmos in a React applicatio
4. 
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Approved - @marienjus 

We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Therefore, please make sure to build a unique application that differs from what can be found on the internet.

**Comment by marienjus** [comment]
the react cosmos librabry has unfixed issue in their repo as bug. I've been facing this for a week now and decided to close this until they fix it.
