### ISSUE TITLE
How to Build React Web Application Without Shipping Javascript Using Astro

### ISSUE THREAD

**Issue by codeInn001** [section-engineering-education/engineering-education#2722]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to Build a React Web Application Without Shipping Javascript Using Astro

### Introduction paragraph (2-3 paragraphs):
For a technology built on top of three different languages, the modern web seems to focus an awful lot on JavaScript. We don’t think it has to—and that’s certainly not a revolutionary concept.

We’ll eagerly jump at the chance to sing JavaScript’s praises, but HTML and CSS are pretty great too. There aren’t enough modern tools that reflect that, which is why Astro was built.

While we’re at it, it’s time to accept that the framework wars won’t have a winner—that’s why Astro lets you use any framework you want (or none at all). Astro makes the production web app have great SEO and also makes the web app lightweight compared to when we ship a javascript web app. This also gives it a better performance.

### Key takeaways: 
The reader will learn how to Install and use React as an Astro renderer.
The reader will learn how to create and import a React component with Astro.
The reader will learn how to fetch data in Astro to pass dynamic props into React.
The reader will learn how to use  Astro Component Hydration API to load JavaScript bundles in the client.

### References: 
https://astro.build
https://reactjs.org
https://github.com/snowpackjs/astro/blob/main/docs/renderers.md

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@codeInn001 

Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by codeInn001** [comment]
@hectorkambow Thanks, got it.
