### ISSUE TITLE
Angular 11 Material Table With Pagination, Filtering, Sorting

### ISSUE THREAD

**Issue by benardogure** [section-engineering-education/engineering-education#2723]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Angular 11 Material Table With Pagination, Filtering, Sorting

### Introduction paragraph (2-3 paragraphs):

Angular material table is an inbuilt component that can be used to create a table where the user can searching, sorting, filtering, and paging rows. We use Angular 11 and Angular 11 Material for this demo example.  Angular Material is the ground running with significant, modern UI components that work across the web, mobile, and desktop applications. 

Angular Material components will help us to construct attractive UI and UX, consistent, and functional web pages and web applications while keeping the modern web design principles like browser portability and compatibility. In today’s post, we will use the table component in the Angular Material library. So let us start an Angular 10 Material Table Example For beginners.

### Key takeaways: 
1.Angular material table
2.Angular Table Pagination
3. Angular Material Table Sorting
4. Angular Material Filtering Functionality

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@benardogure 

Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
