### ISSUE TITLE
 Angular 12 Image Upload, Preview, Crop, Zoom and Scale Example

### ISSUE THREAD

**Issue by benardogure** [section-engineering-education/engineering-education#2724]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Angular 12 Image Upload, Preview, Crop, Zoom and Scale Example

### Introduction paragraph (2-3 paragraphs):

Throughout this comprehensive tutorial, we will explain how to upload an angular image, show image preview by creating a Base64 url in angular, how to crop an image in angular, how to zoom the image, and how to scale the image in Angular.
Adding image uploading, previewing, cropping, scaling, and zooming in Angular is easy; this required feature can be created using the ngx-image-cropper plugin.

The Image cropper for Angular is available through the node package manager, and this plugin allows you to add profound features related to an image file.
Register image cropper in Angular’s main app module class, after which you can access numerous methods and API for handling file upload, preview, and zoom

### Key takeaways: 
1.Setting Up Angular Environment
2.Adding NGX Image Cropper Package in your Angular application
3.Registering ImageCropperModule in App Module
4.Integrating Image Cropper in Angular 12 app.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@benardogure Unfortunately, you can only propose one topic at a time.

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
