### ISSUE TITLE
 Angular 12 Image Slider with Lightbox Tutorial with Example

### ISSUE THREAD

**Issue by benardogure** [section-engineering-education/engineering-education#2725]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Angular 12 Image Slider with Lightbox Tutorial with Example

### Introduction paragraph (2-3 paragraphs):
Angular 12 Image Slider or Carousel with Lightbox tutorial; Throughout this quick guide, you will learn how to seamlessly integrate the image slider with Lightbox in the angular app using the ng-image-slider npm package.

The ng-image-slider is a handy and impeccable carousel package, which helps you implement a responsive image slider with a Lightbox popup in angular.

It doesn’t limit to responsive support but also comes with extensive features. For instance, it captures swipes from phones and tablets, compatibility with Angular Universal, display images files with Lightbox popup on click. It supports keyboard key events for the next/previous arrow key, and most importantly, it smoothly handles runtime image ArrayList updates

### Key takeaways: 
1.Installing Angular Image Slider Package
2.Adding `NgImageSliderModule` in App Module
3.Integrating Image Lightbox Carousel in Angular

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@benardogure Unfortunately, you can only propose one topic at a time.

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍
