### ISSUE TITLE
Packet Filtering Using Access Control Lists in Networking

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#2728]
### Proposed title of article
Understanding Packet Filtering in Networks Using ACLs.

### Introduction paragraph (2-3 paragraphs):
Security is crucial for any network. In networks, packets are always moving from one host to another or from one network segment to another. This is insecure, as the network is more vulnerable to unwanted and dangerous traffic. To improve the security of the network, a security mechanism should be in place to control the incoming and outgoing traffic. For that, Access Control Lists become the solution to control the flow of traffic in and out of the network. They work on sets of rules that define how to forward or block a packet at a router's interface.
In this article, we are going to discuss how one can use the ACLs to restrict, permit or deny traffic in the network to provide secure remote administrative access. It will also equip the reader with the knowledge of how to configure the ACLs on the network devices, how to change them if they are not working correctly or if they require other changes.

### Key takeaways: 
- What are Access Control Lists in networking?
- How Access Control List provides security to a network.
- How to create and configure Access Control Lists to network devices.
### References: 
N/A

### Templates to use as guides
N/A

**Comment by dentonya** [comment]
cc @hectorkambow  @ahmadmardeni1

**Comment by hectorkambow** [comment]
@dentonya 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
