### ISSUE TITLE
Getting started with optimization in Matlab

### ISSUE THREAD

**Issue by florenceatieno45** [section-engineering-education/engineering-education#2729]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
Optimization is the process of combining the inputs to achieve the optimum output subject to satisfying certain specified constraints and conditions. It involves choosing the best among a given data or combining the inputs to obtain the optimal working condition. It is a mathematical discipline that works to obtaining the maxima and minima. Optimization forms part of linear programming.
Optimization is applicable in a wide range of fields. This includes the financial sector, transport sector and many more. This makes it an important tool in the everyday life of people and industries. In this article, we will look at the basics of optimization and how to apply them in Matlab. We will also look at its application in various fields.

### Key takeaways: 
- Understand what optimization.
- How to implement optimization in Matlab.
- Applications of optimazation.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@florenceatieno45 

🤔  

Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
