### ISSUE TITLE
IMPORTING AND EXPORTING MODULES IN NODE.JS

### ISSUE THREAD

**Issue by Elijahwanjiku** [section-engineering-education/engineering-education#2731]
### Proposed title of article
Introduction to the concept of importing and exporting of modules in Node.Js

### Introduction paragraph (2-3 paragraphs):
   A module encapsulates related code into a single unit of code. To increase functionality of the 
modules, their importation and exportation is an important aspect in programming with Node.Js.

   In this article there is an explanation of importing and exporting the Node.Js modules. 
Various functions for importing and exporting the modules are thoroughly explained in
this article.

Be sure to understand Node.js module's importation and exportation after going through this article.

### Key takeaways: 
1. Definition of Node.Js.
2. A deep explanation on how to import a node.js module.
3. A deep explanation on how to export a node.js module.
4. Definition of Node.Js modules.

### References: 
N/A

**Comment by hectorkambow** [comment]
@Elijahwanjiku Thank you for the topic suggestion @Reestuart, however this is a bit outside of our preferred topic areas. (As we have put a slight pause on Node.js centric topics - as we have plenty in the works. 

Please feel free to suggest an alternate topic to explore. 🚀
