### ISSUE TITLE
Introduction to Artificial Narrow Intelligence (ANI)

### ISSUE THREAD

**Issue by domiwanja** [section-engineering-education/engineering-education#2734]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Introduction to Artificial Narrow Intelligence
### Introduction paragraph (2-3 paragraphs):
Artificial intelligence (AI) is one of the most popular term used in  computer science recently. This article discusses one of the classifications of Artificial Intelligence namely Artificial Narrow Intelligence (ANI).
Artificial Narrow Intelligence is also known as WEAK AI. This is an AI that has narrow rangeability holding a perspective that executes specific focused tasks, without the ability to the self -expand mechanism. Narrow AI machines intelligence is achieved through Natural Language Processing concept. This concept is mostly functional in chatbots and other domains where machines are programmed to interact with humans using text recognition or speech.

### Key takeaways: 
1. What is Artificial narrow intelligence
2. Different types of narrow intelligence
3. The differences between general AI and Narrow AI
4. Limitations of Narrow intelligence 
5. key examples of Narrow AI
### References: 
N|A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
This is an interesting topic. Can we take up an interesting problem or an application where weak ai is used and then use that to explain the concepts. A Google search on weak ai results in similar looking articles with similar content. 

Do let us know about an interesting problem or application that you will consider for the purposes of the article. 

@hectorkambow

**Comment by hectorkambow** [comment]
@domiwanja

**Comment by hectorkambow** [comment]
@domiwanja
