### ISSUE TITLE
Implementing Ads with Firebase-AdMob SDK in Android (Kotlin)

### ISSUE THREAD

**Issue by Ericgacoki** [section-engineering-education/engineering-education#2735]
### Proposed title of article

Implementing Ads with Firebase-AdMob SDK in Android (Kotlin)

### Introduction paragraph (2-3 paragraphs):

As an Android developer, finding an effective and easy way to earn a reliable revenue from your apps is a great approach to grow your career financially. One of these ways is to embed advertisements in your apps.

Google-Firebase `AdMob SDK` is a smart monetization platform that helps you to maximize revenue from Ads and **in-app purchases**. AdMob is a well developed SDK that handles most of the work for you such as generating analytics reports based on the type of Ads shown and using Artificial Intelligence to determine relevant Ads for a particular user. It is also very secure in that user metrics' privacy is highly prioritized.

### Key takeaways: 

In this article, the reader will learn;

1. Why Ads are important in an app.
2. How to integrate AdMob SDK in Android.
3. How to manage and maximize revenue from Ads.
4. When to use what types of Ads.
5. How to avoid frustrating users with Ads.

### References: 

N/A

**Comment by hectorkambow** [comment]
@Ericgacoki 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@Ericgacoki 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
Please proceed ping us to open the topic form to tie to your PR if and when the article is ready to be published.
