### ISSUE TITLE
Getting started with Docker Compose using Spring Boot App and PostgreSQL containers 

### ISSUE THREAD

**Issue by Kikiodazie** [section-engineering-education/engineering-education#2737]
### Proposed title of article
Getting started with Docker Compose using Spring Boot App and PostgreSQL containers.

### Introduction paragraph (2-3 paragraphs):

Container technology has streamlined how we build, test and deploy software from our local environment to on-premise data centres and the cloud. With the benefit of building applications with container technology, as we build multi-container applications, manually starting and stopping each container becomes tedious. 

Docker-compose is a tool used in defining and running multi-container Docker applications. We use Docker-compose to replace the run commands repeatedly run on each container in a multi-container application. Using Docker compose, we can simplify the running of multi-container applications to as little as two commands; `docker-compose up` and `docker-compose down`.

In this tutorial, we’ll learn how Docker-compose makes it easier to configure and run multiple Docker containers in a local environment. We will also create Spring Boot application and PostgreSQL database containers.

### Key takeaways: 

1. Understand the basics of Docker Compose and why developers should use it in their workflow.
2. Learn how to create a PostgreSQL Docker image.
3. Learn how to define a docker-compose.yml file. 

### References: 

- https://www.youtube.com/watch?v=QeQ2MH5f_BE 
- https://github.com/Kikiodazie/Multi-User-TodoList-Api
- https://www.youtube.com/watch?v=HUpIoF_conA

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Approved - @Kikiodazie 
Please make sure it does not overlap with any [published](https://www.section.io/engineering-education/topic/containers/) article/tutorial, and to refer to our articles/tutorials about containers where and when possible.

**Comment by Kikiodazie** [comment]
> Approved - @Kikiodazie
> Please make sure it does not overlap with any [published](https://www.section.io/engineering-education/topic/containers/) article/tutorial, and to refer to our articles/tutorials about containers where and when possible.

Sure, all noted. I will do just that. Have a great day.
