### ISSUE TITLE
Creating a Screen Recorder in JavaScript

### ISSUE THREAD

**Issue by Jagathishrex** [section-engineering-education/engineering-education#2738]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction
The Screen Capture API is used to capture the screen or a part of the screen as a Media Stream. From the recorded Media Stream we can create a video file.

We will 
1. `recordScreen` -- This will start recording the user's screens.
2. `createMediaStream` -- This will create a MediaStream object from the screen stream.
3. `saveRecording` -- This will save the recorder stream as a file to our computer.

### Key takeaways: 
1. Understand how screen sharing and screen recording happens in web
2. Able to create a Screen recorder 

### References: 
-[Google Video Recording Article](https://developers.google.com/web/fundamentals/media/recording-video)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Hi, @BrianaNzivu. I see there's isn't a topic approved label for this issues. Has this topic already been approved as there's an existing PR for it?

**Comment by BrianaNzivu** [comment]
> Hi, @BrianaNzivu. I see there's isn't a topic approved label for this issues. Has this topic already been approved as there's an existing PR for it?

Hi @louisefindlay23 . I am coming to notice right now.
I am sorry for that mistake.
Do I still continue with the review process?

**Comment by louisefindlay23** [comment]
Yes, @BrianaNzivu. Just had a look at the PR and it's just on the cusp of originality from similar articles. 

It would be nice if the author included more detail though to add extra value such as covering the video and audio APIs like this [article](https://hackernoon.com/heres-how-i-built-a-video-audio-and-screen-recorder-web-app-with-javascript-f42z338r) and/or providing more detail about how the APIs work or some suggestions to readers as to how they could extend the web app shown (i.e. what extra functionality they could implement).

**Comment by BrianaNzivu** [comment]
> Yes, @BrianaNzivu. Just had a look at the PR and it's just on the cusp of originality from similar articles. 
> 
> It would be nice if the author included more detail though to add extra value such as covering the video and audio APIs like this [article](https://hackernoon.com/heres-how-i-built-a-video-audio-and-screen-recorder-web-app-with-javascript-f42z338r) and/or providing more detail about how the APIs work or some suggestions to readers as to how they could extend the web app shown (i.e. what extra functionality they could implement).

Cc @Jagathishrex .Take note.
