### ISSUE TITLE
Using  Web API's in Python

### ISSUE THREAD

**Issue by Bonimum** [section-engineering-education/engineering-education#2742]
### Proposed title of article
Using Web API's (GitHub API) in Python

### Introduction paragraph (2-3 paragraphs):
In this tutorial you’ll learn how to write a self-contained program to generate a visualization based on data that it retrieves. 
Your program will use a web application programming interface (API) to automatically request specific information from a website rather than entire pages. We’ll base our visualization on information from GitHub, a site that allows programmers to collaborate on projects. We’ll use GitHub’s API to request information about Python projects on the site .
.
 ### Key takeaways: 

- Requesting Data Using an API Call 
- Installing Requests
- Processing an API Response
- Working with the Response Dictionary
- Summarizing the Top Repositories

### References: 
N/A

**Comment by jerimkaura** [comment]
Hello @Bonimum, I think the topic was already suggested here #2406

**Comment by Bonimum** [comment]
I have changed and edited the topic to this  `Using Web API's (GitHub API) in Python` @jerimkaura 

cc @hectorkambow 

Thank you

**Comment by jerimkaura** [comment]
Aright @Bonimum, let's hope it will be approved soon enough.

**Comment by hectorkambow** [comment]
@Bonimum 

Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
