### ISSUE TITLE
How to install and configure Git on Windows OS?

### ISSUE THREAD

**Issue by supzi-del** [section-engineering-education/engineering-education#2743]
### Proposed title of article
How to install and configure Git Version control system on Windows OS?

### Introduction paragraph (2-3 paragraphs):
Introduction
In this walkthrough, you will be learning how to install, set up, and make a test directory Git on Windows OS. You will also learn how to configure your name or GitHub username, E-mail, and your chosen code editor to Git. This will take, like 10 minutes! it's that easy, so keep reading!

### Key takeaways: 
Step 1 - Installation 
Step 2 - Setup - default options and customization
Step 3 - Launching Git Bash
Step 4 - Making a test directory 
Step 5 - Learning basic Git commands
Step 6 - Configuration

### References: 
https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
https://www.udacity.com/course/version-control-with-git--ud123

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)

**Comment by louisefindlay23** [comment]
Hi, @supzi-de. Great topic suggestion. 

Since we focus on unique and original content, could you tell me how your article will differ from similar Windows Git guides such as this [Computer Hope](https://www.computerhope.com/issues/ch001927.htm) article?

Covering WSL2 would be a great way to add value as we don't have any existing articles on it.

**Comment by supzi-del** [comment]
> Hi, @supzi-de. Great topic suggestion.
> 
> Since we focus on unique and original content, could you tell me how your article will differ from similar Windows Git guides such as this [Computer Hope](https://www.computerhope.com/issues/ch001927.htm) article?
> 
> Covering WSL2 would be a great way to add value as we don't have any existing articles on it.

Hey @louisefindlay23,
My suggestion differs from the above article as I want to include every step of the setting up process (in selecting the options and what each one will do). I also want to include the configuration -- configuring your name/GitHub username, email, and code editor which I have not come across in any articles so far. :)
The Computer Hope article stresses more upon the Git commands and working in your local repository.
If you mean setting up Git on WSL, sure I can give it a try!
Thanks

**Comment by louisefindlay23** [comment]
Sounds good, @supzi-del. Topic approved.

**Comment by hectorkambow** [comment]
@supzi-del 

Just pinging you on this topic form - to inform we will be closing this topic form only to make some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date when the article is ready to publish.
