### ISSUE TITLE
Material Motion in Android

### ISSUE THREAD

**Issue by LinusMuema** [section-engineering-education/engineering-education#2745]
### Introduction paragraph (2-3 paragraphs):
When designing layouts and activities in Android, you are highly likely to come across Material Design and Material design components. This also applies to animations and transitions. As from Material design version `1.2.0`, we have the material motion tools to help us with transitions. These allow us to animate transitions in the application which helps the user understand navigation better hence a richer user experience. This article will help you learn the four transitions and how to use them in android.

### Key takeaways: 
1. What is material motion
2. What are transitions used for in an app
2. What are the 4 material motion transitions available
3. How to add the transitions in an android app

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@LinusMuema 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@LinusMuema 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
Please proceed ping us to open the topic form to tie to your PR if and when the article is ready to be published.

**Comment by LinusMuema** [comment]
Hi @hectorkambow 
I will revisit this article later. Sorry for any inconveniences...
