### ISSUE TITLE
Getting started with Operator Overloading in C#

### ISSUE THREAD

**Issue by bancy-bit** [section-engineering-education/engineering-education#2746]
### Introduction paragraph (2-3 paragraphs):
The concept of overloading a function can also be applied to operators. Operator overloading gives the ability to use the same operator to do various operations. It provides additional capabilities to C# operators when they are applied to user-defined data types. It enables to make user-defined implementations of various operations where one or both of the operands are of a user-defined class. Only the predefined set of C# operators can be overloaded. 
To make operations on a user-defined data type is not as simple as the operations on a built-in data type. To use operators with user-defined data types, they need to be overloaded according to a programmer’s requirement. An operator can be overloaded by defining a function to it. The function of the operator is declared by using the operator keyword.

### Key takeaways: 
In this article, we will understand :
1. what operator overloading is.
2. overloading unary operators.
3. overloading binary operators
4. overloading relational operators.
5. benefits of operator overloading.

### References: 
N/A

**Comment by hectorkambow** [comment]
@bancy-bit 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@bancy-bit 
Just pinging you on this topic form - to inform we will be closing this topic form only to make some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date when the article is ready to publish.
