### ISSUE TITLE
Top Kubernetes CI/CD Tools for Managing Large Deployments 

### ISSUE THREAD

**Issue by nellyat** [section-engineering-education/engineering-education#2748]
### Introduction paragraph (2-3 paragraphs):
Standing up Kubernetes and getting your apps running on it is a reasonably straightforward process, but when it comes to updating and deploying apps, it is not always so simple. In particular, performing manual Kubernetes deployments with a large development team can be error-prone. 

To mitigate this issue, developers working with apps running in Kubernetes are automating the workflow for code updates to achieve an end-to-end Continuous Integration/Continuous Delivery (CI/CD) pipeline.

Depending on your team’s needs and workflows, some tools might be better than others. In this two-part blog series, we discuss some of the more popular tools and highlight the pros and cons of each.

### Key takeaways: 

1. Package Managers.
2. CD Tools.
3. CI Tools.
4. Pros and cons for each tool. 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@nellyat 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@nellyat 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
Please proceed ping us to open the topic form to tie to your PR if and when the article is ready to be published.
