### ISSUE TITLE
C# Collections

### ISSUE THREAD

**Issue by Jeff-mwangi** [section-engineering-education/engineering-education#2749]
### Proposed title of article
C# Collections

### Introduction paragraph (2-3 paragraphs):
Collection is a group of similar types of objects on which we can perform the various operations like insert, delete, update, sorting, etc. unlike arrays, collections provide a more efficient way to manage the group of objects.

The objective of this article is to understand the concept of collections in C# programming language. Predominantly, collections (types) are used to manipulate and manage a group of similar types of data. As we know, Arrays are also used to manage a similar type of data, but collections provide more flexibility when working with groups of objects. In this article, I will help the reader to understand various types of collections with practical examples.

### Key takeaways: 
1. What are Collections in C#
2. Types of collections
3. The classes involved in each type of collection
4. ArrayList, Hashtable, Stack, and Queue
5. Properties of C# Collections

### References: 
N/A

**Comment by hectorkambow** [comment]
@Jeff-mwangi 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@Jeff-mwangi 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
Please proceed ping us to open the topic form to tie to your PR if and when the article is ready to be published.

**Comment by Jeff-mwangi** [comment]
@hectorkambow Hello. I have submitted the article. You can now reopen the issue
