### ISSUE TITLE
Graphs in Data structure ( Using C++) 

### ISSUE THREAD

**Issue by anubhavb11** [section-engineering-education/engineering-education#2751]
### Introduction paragraph (2-3 paragraphs):

Graphs are the mathematical structures that represent pairwise relationship between objects. A graph is a flow structure that represents the relationship between various objects.It can be visualized using two basic components:
* Nodes: These are the most important component in any graph. Nodes are the entities whose relationships are expressed using edges. If graph comprises 2 nodes A and B and an undirected edge between them, then it expressed a bi - directional relationship between the nodea nd the edges.
* Edges: Edges are the component that are used to represent the relationship between various node in graph. An edge between two nodes express a one-way or two-way relationship between the nodes.

### Key takeaways: 
I will explain - 
* real life exaples
* types of graph
* graph represntation
* tutorial on how to implement them using C++
* Some Traversal Algorithms ( BFS, DFS)

### References: 
N/A

**Comment by hectorkambow** [comment]
@anubhavb11 

🤔  (please double check this has NOT been covered before in our EngEd docs).
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by ahmadmardeni1** [comment]
.
