### ISSUE TITLE
Design Patterns in JavaScript

### ISSUE THREAD

**Issue by JudyNduati** [section-engineering-education/engineering-education#2754]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Design Patterns in JavaScript

### Introduction paragraph (2-3 paragraphs):
Design Pattern is a widely acknowledged concept in the software engineering industry regarding the benefits it brings to code reuse and maintainability. Design patterns in JavaScript are reusable solutions applied to commonly occurring problems in writing JavaScript web applications.

JavaScript design patterns assist developers in writing organized and well-structured codes. This article will give you a comprehensive understanding of the most popular JavaScript design patterns. Of course, most of them will fall under three categories: creation design patterns, structural design patterns, and behavioral design patterns.

### Key takeaways: 
1. What is a Design Pattern
2. JavaScript Design Patterns
3. Categories of Design Patterns
- Creational design pattern
- Structural design pattern
- Behavioral design pattern
4. JavaScript Design Patterns

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Great topic suggestion, @JudyNduati. I'm sure it will complement our Design Patterns in Java article. Make sure your cover each point in plenty of detail to provide value to our readers.

Thanks,
Louise - Content Moderator

**Comment by hectorkambow** [comment]
@JudyNduati 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
Please proceed ping us to open the topic form to tie to your PR if and when the article is ready to be published.

**Comment by JudyNduati** [comment]
@hectorkambow, please reopen this issue

**Comment by WanjaMIKE** [comment]
Closed #2754 via #3192
