### ISSUE TITLE
Getting Started with GSAP Animation Library

### ISSUE THREAD

**Issue by destiny251** [section-engineering-education/engineering-education#2756]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an article to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
GETTING STARTED WITH GSAP ANIMATION LIBRARY 

### Introduction paragraph (2-3 paragraphs):
In this tutorial, you are going to be learning what the GSAP ANIMATION LIBRARY is and how we can create amazing javascript animation with GSAP LIBRARY. You can definitely achieve anything you want using GSAP, it's the only system that makes it simple to do directional rotation.

### Key takeaways: 

- Readers will be able to work with the GSAP library and implement them on any frontend project 

- Readers will understand the fundamentals of the GSAP library 

- Readers would be able to build complex animations using Tweenlite

-  Readers will be able to Create amazing SVG animations , etc, 

- Readers will be able to animate almost every element on a webpage: DOM elements, elements inside of a canvas but also JS objects and elements of an SVG. All these different types of elements can be placed in a sequence to animate them simultaneously.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@destiny251 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@destiny251 

Just pinging you on this topic form - to inform we will be closing this topic form only to make some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date when the article is ready to publish.
