### ISSUE TITLE
Continuous Integration with Jenkins

### ISSUE THREAD

**Issue by Rmwamboi** [section-engineering-education/engineering-education#2759]
### Proposed title of article
Continuous Integration with Jenkins

### Introduction paragraph (2-3 paragraphs):

In the spirit of collaboration and agile methodology, several developers build codes and combine these different codes into one code base. This process would involve version control system (VCS) where different developers can get code from other developers using pull requests, send their changes to other developers using push requests and combine different code bases from different contributors using merge requests. This process can be automated using continuous integration.

There are various tools that can be used for continuous integration. Jenkins is one such tool. This article will focus on Jenkins as a tool for continuous integration. It is a popular open source tool that can be used to automate different build process. These processes are predefined and can be triggered by different processes such as on predefined time intervals or predefined user actions.

### Key takeaways: 

•	Understanding Jenkins and its role in continuous integration
•	Basic setup of Jenkins
•	What are pipelines and how are they used with Jenkins
•	Benefits of using Jenkins compared to other Continuous integration tools
•	Shortcomings of using Jenkins as a continuous integration tool

### References: 
n/a

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Rmwamboi 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by Rmwamboi** [comment]
I will give it my best.

**Comment by hectorkambow** [comment]
@Rmwamboi 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
Please proceed ping us to open the topic form to tie to your PR if and when the article is ready to be published.

**Comment by Rmwamboi** [comment]
Hey @hectorkambow my apologies for taking long on this one. Been unwell for a couple of weeks but i am now fine and recovering good. 
The article is now ready for upload. If you could kindly reopen under my PR.

**Comment by Rmwamboi** [comment]
hey @hectorkambow 
a polite reminder please

**Comment by Rmwamboi** [comment]
Noted
