### ISSUE TITLE
Network Automation and Automation tools

### ISSUE THREAD

**Issue by raboba2re** [section-engineering-education/engineering-education#2760]
Network Automation and Automation tools

During the industrial age, automation was use to reduce and potentially eliminates the needs of human intervention, thus making the process self driven.
With the advancement in technology, automation has spread across all aspect of human life, from automatic building environmental controls to autonomous cars and planes.
Because setting up networks can be time consuming,especially in large organizations, configuration management tools are use to automate the configuration of network devices such as routers, switches, firewalls and serves.
In this article, we will look at network automation and some popular automation tools in used.
Key takeaways:

    What automation and network automation is
    Configuration management tools
    How tools such as Ansible, Chef and Salfstack are use to automate networks

**Comment by hectorkambow** [comment]
@raboba2re 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #2760 via #3052
