### ISSUE TITLE
Operators in Python

### ISSUE THREAD

**Issue by Joshuathuo** [section-engineering-education/engineering-education#2765]
### Proposed title of the article
OPERATORS IN PYTHON

### Introduction paragraph (2-3 paragraphs):
An operator is a symbol that tells the compiler to perform specific mathematical or logical functions.

Operators are used to performing operations on variables and values.

The objective of this article is to understand the concept of operators in python. In this article, I will help the reader to understand deeply the various types of operators and how they defer from each other in terms of implementation with practical examples.
### Key takeaways: 
1. What are operators in python?
2. Various classifications of operators in python.
3. Implementation of operators in python.

### References: 
N/A

**Comment by lalith1403** [comment]
This is a very basic tutorial and we refrain from covering content that is covered widely on the net or too basic. We are looking for unique content to help the developers community. 

It can be an interesting problem that you are working on, or a specific problem that you faced while building a large project. We would love to know the thought process behind the solution you arrived at. 

@hectorkambow

**Comment by Joshuathuo** [comment]
@lalith1403  thanks for the ping. I intend to discuss Operators in deep detail where I will look at each type of operator and how it is fully implemented in Python. I have gone through various publications about operators in Python and what I keenly observed is that none of them is delivering the knowledge of Operators as a beginner would expect. This is because as a programmer, one has to start from the basics of something and if at any one time one is given a harsh introduction, then he or she feels as if they are in the wrong place or in the wrong field. This makes them struggle a lot for the concepts. Therefore, using this article, I want to make sure every developer or any programmer, including the beginners who want to learn
about Operators in python will have a smooth flow of learning and out of that, they will have all the knowledge that will help them succeed exelently.

**Comment by lalith1403** [comment]
Can you elaborate and give an example for a particular operator. Also, make the proposal much more detailed. This does not suffice to get an overview of the article. 

Given the scope of the article, I would still suggest you work on another topic that is more relevant to our readers. You may also make a solid case on this article if you wish. 

Good luck.

**Comment by Joshuathuo** [comment]
What I really wish is that you may grant me the chance to cover this topic because even I myself struggled to get the real concepts, a situation I would not like others to face. That I really have the feeling that I should help my fellow programmers.
