### ISSUE TITLE
Getting started with Spring Boot WebFlux

### ISSUE THREAD

**Issue by sumbaelvis** [section-engineering-education/engineering-education#2779]
### Getting started with Spring Boot WebFlux
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Reactive programming is a programming paradigm that promotes an asynchronous, non-blocking, event-driven approach to data processing. Reactive programming involves modeling data and events as observable data streams and implementing data processing routines to react to the changes in those streams.

Spring WebFlux is a parallel version of Spring MVC and supports fully non-blocking reactive streams. It supports the backpressure concept and uses Netty as an inbuilt server to run reactive applications.

In the tutorial, I will explain the basic concepts behind reactive programming, WebFlux APIs, and build a fully functional CRUD API example.

### Key takeaways: 
1. How to set up WebFlux in a Spring Boot application.
2. How to create CRUD API using WebFlux.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@sumbaelvis 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@sumbaelvis 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by sumbaelvis** [comment]
Hello @hectorkambow I am requesting for reopening of this issue, I am done with writing the article.

**Comment by WanjaMIKE** [comment]
Closed #2779 via #3805
