### ISSUE TITLE
How to set up Kali Linux for dual boot 

### ISSUE THREAD

**Issue by Wkd-Cyber** [section-engineering-education/engineering-education#2780]
**Introduction**

Kali Linux is a very powerful, open-source penetration testing tool used by hackers and security specialist in day to day encounters. Before learning or accessing various tools in Kali Linux, you will need  to install Kali Linux in your pc.
In this tutorial, we will learn how to set up Kali Linux for dual boot in your pc. We will first learn how to set up a pen drive to be used in the  boot process 
We will then set up the dual boot for Kali Linux  and enter the appropriate options.

**Key Takeaways**

By the end of the tutorial, the user should be able to :

1.  Set up a pen drive to be used in a dual boot
2.  Successfully set up any  OS for a dual boot

**Reference**

N/A

**Comment by hectorkambow** [comment]
@Wkd-Cyber 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
