### ISSUE TITLE
Introduction to Docker Swarm in Container Orchestration

### ISSUE THREAD

**Issue by maggiemun** [section-engineering-education/engineering-education#2787]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Introduction to Docker Swarm in Container Orchestration

### Introduction paragraph (2-3 paragraphs):
Docker Swarm refers to a container orchestration tool that allows users to manage multiple containers. It is used by developers to create, deploy and manage a cluster of Docker nodes. This tool is resourceful because it allows easy deployment. 

This article provides the basics of Docker Swarm and explains its key features. It also highlights some of its uses and explains how it works. 

### Key takeaways: 
1. Introduction to Docker Swarm
2. Key Features of Docker Swarm
3. How developers can use Docker Swarm
4. How Docker Swarm works
-nodes
-services
5. Advantages and disadvantages
6. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@maggiemun 

I know we have an article that briefly discusses Swarm [here ](https://re.sajari.com/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiY2xpY2siLCJkZXN0aW5hdGlvbiI6Imh0dHBzOi8vd3d3LnNlY3Rpb24uaW8vZW5naW5lZXJpbmctZWR1Y2F0aW9uL2JyZWFraW5nLWRvd24ta3ViZXJuZXRlcy12cy1kb2NrZXItc3dhcm0vIiwidmFscyI6eyJjb2xsZWN0aW9uIjpbInNlY3Rpb24taW8iXSwiY29tcGFueSI6WyIxNTY4MjM0MTE2MDc4NjE0ODY4Il0sImZpZWxkIjpbInVybCJdLCJwcm9qZWN0IjpbIjE1NjgyMzQxMTYwNzg2MTQ4NjgiXSwicS5pZCI6WyJuODMzbGV3YW1sMGRpODU3Il0sInEuc2wiOlsiMSJdLCJxLnVpZCI6WyJuODMzbGV3YW1sMGRpODU3MCJdLCJ2YWx1ZSI6WyJodHRwczovL3d3dy5zZWN0aW9uLmlvL2VuZ2luZWVyaW5nLWVkdWNhdGlvbi9icmVha2luZy1kb3duLWt1YmVybmV0ZXMtdnMtZG9ja2VyLXN3YXJtLyJdfX0.NOR8fasayuj2XSJYT3_4Y8hAgccsfSEyhOqbSrkkn5o)- if your article can go beyond this and possibly provide a relevant code execution example that would be ideal. 👍 

Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by maggiemun** [comment]
> @maggiemun
> 
> I know we have an article that briefly discusses Swarm [here ](https://re.sajari.com/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiY2xpY2siLCJkZXN0aW5hdGlvbiI6Imh0dHBzOi8vd3d3LnNlY3Rpb24uaW8vZW5naW5lZXJpbmctZWR1Y2F0aW9uL2JyZWFraW5nLWRvd24ta3ViZXJuZXRlcy12cy1kb2NrZXItc3dhcm0vIiwidmFscyI6eyJjb2xsZWN0aW9uIjpbInNlY3Rpb24taW8iXSwiY29tcGFueSI6WyIxNTY4MjM0MTE2MDc4NjE0ODY4Il0sImZpZWxkIjpbInVybCJdLCJwcm9qZWN0IjpbIjE1NjgyMzQxMTYwNzg2MTQ4NjgiXSwicS5pZCI6WyJuODMzbGV3YW1sMGRpODU3Il0sInEuc2wiOlsiMSJdLCJxLnVpZCI6WyJuODMzbGV3YW1sMGRpODU3MCJdLCJ2YWx1ZSI6WyJodHRwczovL3d3dy5zZWN0aW9uLmlvL2VuZ2luZWVyaW5nLWVkdWNhdGlvbi9icmVha2luZy1kb3duLWt1YmVybmV0ZXMtdnMtZG9ja2VyLXN3YXJtLyJdfX0.NOR8fasayuj2XSJYT3_4Y8hAgccsfSEyhOqbSrkkn5o)- if your article can go beyond this and possibly provide a relevant code execution example that would be ideal. 👍
> 
> Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
> Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

@hectorkambow My article is different from the other published articles. Thank you.
