### ISSUE TITLE
Can Blockchain improve Machine Learning privacy?

### ISSUE THREAD

**Issue by wilkistermumbi** [section-engineering-education/engineering-education#2788]
### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Can Blockchain improve Machine Learning privacy?

### Introduction paragraph (2-3 paragraphs):

Machine Learning algorithms have thrived in the era of big data. But to use that data safely and effectively, we have to take privacy into account when developing Machine Learning systems. This is especially the case when it comes to using sensitive data such as protected health records.
There has been previous attempts to solve this problem using [Federated Learning](https://www.section.io/engineering-education/secured-deeplearning-in-remote-devices/) and [Differential Privacy](https://www.section.io/engineering-education/understanding-differential-privacy/) but it turns out that these systems have a flaw which we'll discuss in the article. And that Blockchain technology might help us solve it.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to:

1. Understand the flaws associated with Federated Learning
2. Understanding the flaws associated with Differential Privacy
3. Understand how Blockchain technology can help solve this issue and improve ML privacy.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

1. [Machine Learning in/for Blockchain: Future and Challenges](https://arxiv.org/abs/1909.06189)
2. [Efficient Privacy-Preserving Machine Learning for Blockchain Network](https://ieeexplore.ieee.org/document/8827509)
3. [AI and Blockchain: A Disruptive Integration](https://ieeexplore.ieee.org/document/8481263)
4. [Secured Deep Learning in Remote Devices](https://www.section.io/engineering-education/secured-deeplearning-in-remote-devices/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
This has been covered widely in eng-Ed and the net in general. We prefer articles that cover something new. A problem that you faced and how you solved it, or a project you worked on. I encourage you to cover a unique project covering MlPs... For example, analysing various data types using MLPs and the code implementation. 
 
@hectorkambow

**Comment by wilkistermumbi** [comment]
@lalith1403 Thank you for the insight. Let me research on that. 

How about this new topic suggestion. I've edited the issue. I believe it should be a good one. What are your thoughts on subject?

**Comment by lalith1403** [comment]
This is an interesting topic. Good to explain all the concepts under federated learning, differential privacy and then talk about the setbacks. Once enough information has been given, then you may talk about how Blockchain will help solve the problem. Be as detailed and specific with the explanations. 

Best of luck.

Cc: @hectorkambow

**Comment by hectorkambow** [comment]
@wilkistermumbi 
Sounds like a very helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
