### ISSUE TITLE
Key differences between Kotlin and Java.

### ISSUE THREAD

**Issue by neheMaish** [section-engineering-education/engineering-education#2789]
### Proposed title of article
Key differences between Kotlin and Java.

### Introduction paragraph (2-3 paragraphs):
It has been quite a while since Kotlin came out, and it has been progressing nicely. Since it was made explicitly to replace Java, Kotlin has normally been contrasted with Java in numerous regards like syntax among others. 

 Java is a programming language and computing platform. It is used as the server-side language for most back-end development projects, including those involving big data and Android development.

On the other hand,  Kotlin is a general purpose, free, open source, statically typed programming language initially designed for the JVM (Java Virtual Machine) and Android that combines object-oriented and functional programming features. It is focused on interoperability, safety, clarity, and tooling support.

To assist you with choosing which of the two languages you should get, I will analyze a portion of the principle highlights of every language so you can pick the one you need to learn.

### Key takeaways: 

1. Syntax
2. Model Classes
3. Concurrency
4. Extension Functions
### References: 

N/A

**Comment by lalith1403** [comment]
Can you explain what unique aspect of functions and methods will you be covering that is not already covered. Functions and methods are widely covered on the net. We promote articles that are unique, or provide a new perspective on a widely covered topic.

**Comment by Joshuathuo** [comment]
thankyou@lalith403 for the question. It is true that functions and methods have been covered but not in detail. This is because I have observed most students and other learners struggling to get the real flow of methods and functions. So my task in this article will be to explain in detail the concept involved in functions and methods in Python. I will make sure that whoever will have to know all about functions and methods in Python will have a smooth flow with no struggle.

**Comment by lalith1403** [comment]
The article topic form that you have submitted is not detailed enough to get a gauge on the effectiveness of the article proposed. Can you provide more information to see if the approach fits well. 

More importantly, we suggest that you try a more unique article that you feel is rarely covered on the web.

**Comment by Joshuathuo** [comment]
@lalith1403  thanks for the ping. What I have really noticed with a lot of concern after going through the various publications and the related staff concerning Functions and Methods in python is that they really do not deliver the content as a beginner would expect it to be. Sometimes it becomes hard for a person who is an absolute beginner to learn and understand the concepts already delivered on the net. Therefore using this article, I will make sure that every beginner use wishes to learn about functions and methods will have a smooth flow of learning new skills.

**Comment by lalith1403** [comment]
Thank you for the topic suggestion, @Joshuathuo. However, this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀

**Comment by Joshuathuo** [comment]
That is really what I desire to do as part of my wish in helping other programmers out there. Deep diving into the content making sure that it caters to every programmer at any level of programming.

**Comment by hectorkambow** [comment]
> That is really what I desire to do as part of my wish in helping other programmers out there. Deep diving into the content making sure that it caters to every programmer at any level of programming.

Thank you @Joshuathuo  

Totally agree with you and the EngEd program is a community building content for developers of all levels. 

(An option and) a great way to write this article as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

That way a developer could see them in action. 

As mentioned above - we believe this topic is widely covered on other blog site. 

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value. 

> For topic approval - if you could gear it as a practitioner-focused tutorial. Thank you

**Comment by neheMaish** [comment]
@hectorkambow I have decided to change my topic. Please have a look.
 
Ping me if there is any issue. Thanks.

cc @lalith1403

**Comment by hectorkambow** [comment]
I'm pinging our Kotlin resident expert to see if this has been covered in our EngEd docs. 

cc @LinusMuema

**Comment by LinusMuema** [comment]
Hi @neheMaish 
I think it's a great idea. However, there are some drawbacks. There are topics that have covered your key takeaways in depth. For instance:
1. [Kotlin extensions](https://www.section.io/engineering-education/kotlin-extensions/) have been covered in-depth in this article
2. Concurrency in Kotlin has also been covered in depth in the [Flows](https://www.section.io/engineering-education/introduction-to-kotlin-flows/) and [Coroutines](https://www.section.io/engineering-education/introduction-to-kotlin-coroutines/) articles
3. Model classes have made appearances in most of the kotlin articles 

That leaves you with the syntax comparison alone which I don't think is enough to guarantee a great original article. Just as @lalith1403  mentioned, you can look for something original that is most probably yet to be covered on the web.
I hope I make some sense

**Comment by neheMaish** [comment]
Thanks @LinusMuema 
What I really want to cover in this topic is how kotlin differs with Java as a language. I want the readers to clearly understand the main differences between these two languages in detail. Some of the programmers despite of using these languages in development, they cannot expalin why they are not using kotlin if Java is what they are using and why they using kotlin instead of Java. I will kindly appreciate if you see me through.

**Comment by LinusMuema** [comment]
In that case, 
@neheMaish you will need to provide in-depth information on the same and make sure your content is original. Looking forward to seeing what you will do.
Topic approved.

**Comment by hectorkambow** [comment]
@neheMaish  Can you please contact me via Slack?? 

We can not seem to find your information in our records - 🤔
