### ISSUE TITLE
Introduction to Java Swing Desktop Application Using NetBeans IDE

### ISSUE THREAD

**Issue by JosephAyoma** [section-engineering-education/engineering-education#2798]
### Proposed title of article
Introduction to Java Swing Desktop Application Using NetBeans IDE

### Introduction paragraph (2-3 paragraphs):
Java Swing is part of Java Foundation Classes and it is used to create a window based application which makes it suitable for developing desktop application which could be lightweight. Java Swing is built on top of abstract windowing toolkit application programming interface which is purely written in Java programming language. 

In this article, we will get to learn the introduction on how we can use Java Swing Components to build (develop) desktop application which can be installed on any windows desktop computer. At the end of the article the learner will be able to understand briefly the main Java Swing Components which are commonly used in any desktop application as well as getting started to develop Java Swing based desktop application.

### Key takeaways: 
1.	Defining and describing Java swing and the difference with other Java frame works
2.	Discussing an describing Java Swing Components common for desktop application
3.	Getting Started with Java Swing desktop application in NetBeans

### References: 
https://www.javatpoint.com/java-swing

**Comment by hectorkambow** [comment]
@JosephAyoma 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
