### ISSUE TITLE
How to create Machine Learning App using the FastAPI and deploying it to kubernates cluster

### ISSUE THREAD

**Issue by Bravinsimiyu** [section-engineering-education/engineering-education#2799]
### Proposed title of the article
How to create Machine Learning App using FastAPI and deploying it to Kubernetes cluster

### Introduction paragraph (2-3 paragraphs):
FastAPI is a modern, fast (high-performance), web framework for building APIs with Python 3.6+.
Here we will build our machine learning model, after creating the model we will create an application using the FastApi which has different routes that can be used to make predictions.
After serving our machine learning model as an API, we will create a docker container for the application.
Finally, we will be able to deploy the FastAPI docker container to the Kubernetes cluster.
### Key takeaways: 
1. How to create a simple machine learning model.
2. How to install the FastAPI.
3. Serving the ML model as an API using the FastAPI.
4. How to create Docker Container.
5. Deploying the FastAPI docker container to Kubernetes cluster.
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Can you give more details about the machine learning model that you will be building?

**Comment by Bravinsimiyu** [comment]
Hello @lalith1403 the model I will be building is a simple machine learning model that can predict the churn rate within a bank.
Predict if a person will leave a bank or not depending on certain inputs.

**Comment by Bravinsimiyu** [comment]
@lalith1403  this model will then be used to show how we can serve a machine learning model as an API using the FastAPI.
Thereafter we will deploy the FastAPI docker container to the Kubernetes cluster.

**Comment by lalith1403** [comment]
Yes. This is a good project. Explain each step in detail. You are covering the entire machine learning life cycle, beginning with Data preprocessing to model deployment and inference. Make sure to explain the various alternatives that one can take during each phase and your thought process. 

Cc: @hectorkambow

**Comment by Bravinsimiyu** [comment]
Hello @lalith1403 should I now continue writing the article?
@hectorkambow

**Comment by hectorkambow** [comment]
@Bravinsimiyu 

sounds like a very helpful topic - approved 🚀
