### ISSUE TITLE
Setting and Running Docker Containers on Google Compute Engine

### ISSUE THREAD

**Issue by victorelvice** [section-engineering-education/engineering-education#2804]
### Proposed title of article
Setting and Running Docker Containers on Google Compute Engine

### Introduction paragraph (2-3 paragraphs):
Google Compute Engine (GCE) is an infrastructure-as-a-service (IaaS)  that enables programmers to run workloads on physical Google hardware. To this end, Google Compute Engine avails several virtual machines (VMs) that can be used as large-scale processing clusters. For this reason Google Computer Engine is a helpful for utilizing the vast Google Infrastructure.

Containers are convenient methods to run your application in multiple instances at the same time. Containers and enables one to run the same application but on different platforms conveniently. However, containers need to  be hosted somewhere where an application and its dependencies are packaged together. This is where Google Compute Engine comes in.  In this article, the reader will be able to install and run a Docker container on the Google Compute Engine.

### Key takeaways: 
1. Understanding Google Computer Engine
2. Creating Docker containers
3. Dockerizing a flask application
4. Installing and running Docker Containers on Google Cloud Engine
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Hi, @victorelvice. 

Great topic suggestion. 

Can we tell me how your artcile will differ from similar Docker tutorials using GCE such as this [Medium](https://medium.com/@kyle.powers103/installing-docker-on-gcloud-vms-1479dd9dde30) article since we focus on unique content?

Thanks,
Louise - Content Moderator

**Comment by victorelvice** [comment]
@louisefindlay23 , Thank you for the observation. I went through the article as well but as our platform is focused on content that are beginner friendly as well. I think the article did not have much consideration of beginners. I thought by building a flask/Django project from scratch, dockerising it  step by step, setting up containers and finally pushing to GCE, would enable beginners understand the concept better and relate the commands . Besides, the article in medium was focused in the commands to use yet mine will be about using the commands in a real project.

Let me know what you think about it. I would appreciate any recommendations. 
Thank you!

**Comment by louisefindlay23** [comment]
Thanks, @victorelvice for providing such in-depth detail. Topic approved.

**Comment by hectorkambow** [comment]
@victorelvice 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
