### ISSUE TITLE
Deploy a Flutter app to Google Compute Engine

### ISSUE THREAD

**Issue by paulromans** [section-engineering-education/engineering-education#2805]
### Proposed title of article
Deploy a Flutter app to Google Compute Engine

### Introduction paragraph (2-3 paragraphs):
Google provide various hosting options including Compute Engine, App Engine, Kubernetes, Firebase, Cloud Run, and Cloud functions. The option that one goes for depends on the nature of the app/site they wish to deploy. In this tutorial, we will see to deploy a flutter application to Google Compute Engine. 
In the end we will have created a Google Cloud project, installed a Virtual Machine, created a Flutter web app and deployed it on our tech stack hosted on the Virtual Machine.
### Key takeaways: 
1. Creating a flutter web app.
2. Creating Google Cloud Project on Google Cloud Console.
3.  Creating Virtual Machine instance on Google Compute Engine
4. Deploying the created app on the GCE.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double-check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @paulromans

**Comment by hectorkambow** [comment]
@paulromans 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by WanjaMIKE** [comment]
closed #2805 via #3826
