### ISSUE TITLE
Building Scrollable and Lazy components in Jetpack Compose

### ISSUE THREAD

**Issue by Janenjoki** [section-engineering-education/engineering-education#2808]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

### Proposed title of article

Building Scrollable and Lazy components in Jetpack Compose

### Introduction paragraph (2-3 paragraphs):

Jetpack Compose is an Android UI Toolkit with a new declarative approach. Compose makes it easy to design and manage your app's user interface by providing a declarative API that lets you render your app's user interface without having to change front-end views. This jargon has to be explained, but the ramifications are crucial for app design. 

Many apps require the visualization of multiple items. Compose includes a set of components that only compose and lay out elements visible in the view-port of the component. `LazyColumn` and `LazyRow` are two of these components. They manage how items are displayed regardless of their number. This makes development easier and provides an interactive experience to the users.

In this tutorial, we'll learn the best practices to build such components.

### Key takeaways: 
By the end of this tutorial, the readers will be able to;

1. Understand the "Lazy" terminology in Jetpack Compose.
2. Build scrollable compose elements.
3. Implement data models within composables.

### References: 

N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @Janenjoki

**Comment by hectorkambow** [comment]
@Janenjoki 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by Janenjoki** [comment]
@hectorkambow, Could you please re-open this issue?
I have already opened a PR for this topic. Thank you!

**Comment by Ericgacoki** [comment]
Reopening since the topic was approved and the student has linked it to a PR.
