### ISSUE TITLE
Building a Machine Learning Classification Model with PyCaret

### ISSUE THREAD

**Issue by smkinyan** [section-engineering-education/engineering-education#2809]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):

PyCaret allows you to leverage state of the art machine learning pipeline to build your machine learning models. You can build a series of ML models using a single function call and automatically rank different models against each other.
Using PyCaret, we learn how to build a heart disease prediction model using data from Kaggle.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

In this tutorial you'll learn how to: 

1. Install PyCaret, a machine learning library for Python
2. Load in custom data from Kaggle using Pandas
3. Build a PyCaret ML classification model using automated pipelines

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

1. [PyCaret](https://pycaret.org/)
2. [Heart Disease UCI](https://www.kaggle.com/ronitf/heart-disease-uci)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
This is an interesting topic. Thank you for the topic suggestion. In addition to covering creation of pipelines with PyCaret, I would like you to start with why should one use PyCaret. Is it a library based on existing libraries or does it require a separate learning curve? 

You may also cover the functionalities of PyCaret as an additional section. Look forward to reading this article. 

Cc: @hectorkambow

**Comment by lalith1403** [comment]
@smkinyan Great topic. This would complement the existing articles on building ML pipelines. Make sure you cover all the details. Best of luck.

Thanks,
Lalith

**Comment by smkinyan** [comment]
> @smkinyan Great topic. This would complement the existing articles on building ML pipelines. Make sure you cover all the details. Best of luck.
> 
> Thanks,
> Lalith

Thanks for the suggestion @lalith1403 I'll make sure I include those suggestions in my tutorial.
