### ISSUE TITLE
How to use git and github.

### ISSUE THREAD

**Issue by Alao-Abiodun** [section-engineering-education/engineering-education#2816]
### Proposed title of article

How to use git and github.

### Introduction paragraph (2-3 paragraphs):

Git consist of commands used in communicating with the project, Git is an open-source and version control system that helps to interact with projects, and also helps to keep track of these projects from beginning to end without any issues arising.
Github is a collaborative platform that helps to manage our project and it promotes interactions between developers helping them to know the stages of their project. 
Take your time and write the content as you would intend to get it published. 

### Key takeaways: 

1. Accepting an invitation and getting started with the repository.
1. Some automation techniques using git and Github.
2. Maintaining updates with upstream.
3. As a project Maintainers/Triage, how do you review PR.
4. using one line code.

### References: 
N/A

**Comment by louisefindlay23** [comment]
Hi, @Alao-Abiodun. Thanks for submitting a topic suggestion. 

Tutorials on Git and GitHub are a popular topic and has been covered extensively elsewhere. Since we focus on original content, can you tell me what makes your article unique?

Thanks,
Louise - Content Moderator

**Comment by Alao-Abiodun** [comment]
The process, I am explaining will based on each ways of contributing to team repository, and not just randomly explaining, The process is based on some techniques.

**Comment by louisefindlay23** [comment]
Thanks for the clarification, @Alao-Abiodun. Topic approved. Make sure your article is in-depth and detailed to provide value to readers.

**Comment by hectorkambow** [comment]
@Alao-Abiodun 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by Alao-Abiodun** [comment]
@hectorkambow Ok, No problem, I have actually completed my write-up for the topic, but am still unable to clone the repo on my system and I complained to you about it on slack. my slackName BlackAfricanDev, But I am still working on cloning when I am done with it.
