### ISSUE TITLE
CSS Hacks Every Web Developer Should Know

### ISSUE THREAD

**Issue by mosesmoses12** [section-engineering-education/engineering-education#2819]
### Proposed title of article
CSS Hacks Every Web Developer Should Know

### Introduction paragraph (2-3 paragraphs):
CSS is still among the top ten coding languages, according to Redmonk, despite not being as popular as JavaScript.
CSS is popular among website developers because it is quite robust, relatively straightforward to learn, and ubiquitous across different browsers.

There are various CSS shortcuts or hacks, as there are with any coding language, that help you to write cleaner code, improve design components, and save time. 

It's also vital to note that CSS does not require you to be a senior web developer.
CSS is utilized by 96 percent of all websites, according to W3Techs, and the ability to use CSS to improve the layout and design of a website is essential to the functionality of major open source CMSs like WordPress. 

If you’re new to CSS, this article will teach you the fundamental aspects, and CSS hacks that will be beneficial in your work. 

### Key takeaways: 
1. How to position content in the center with CSS
2. How to fit images to the page in CSS
3. How to consolidate styling in CSS
4. Visited link styling in CSS
5. How to disable text wrapping and add ellipsis in CSS.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to [double-check that it does not overlap with any existing EngEd articles](https://www.section.io/engineering-education/search/?q=css) or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @mosesmoses12
