### ISSUE TITLE
What's new in Next.js version 11

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#2820]
### Proposed title of article
What's new in Next.js version 11

### Introduction paragraph (2-3 paragraphs):
Next.js is a React based web development framework that offers the functionality of server-side rendering and generation of static sites. In the web development ecosystem Next.js has various benefits including improved SEO, improved web application performance, and improved development process. In Next.js version 11 various features have been introduced which were not there prior including *next/script* which allows for automatic  prioritized loading of third-party scripts, *next/image* which allows for smoother developer experience when working with images among others. In this article, we will learn about the new features introduced in Next.js version 11 by building a simple blog web application.

### Key takeaways: 
- How to set up a Next.js project using `create-next-app`.
- How to do various configurations in a Next.js project.
- How to implement the new features in Next.js version 11.
- How to deploy the Next.js project in Vercel.

### References: 
- https://nextjs.org/docs/getting-started

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double-check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @mwangiKibui

**Comment by hectorkambow** [comment]
@mwangiKibui 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
