### ISSUE TITLE
Parameter Passing Techniques in C/C++

### ISSUE THREAD

**Issue by neshmacharia** [section-engineering-education/engineering-education#2821]
### Proposed title of article
Parameter Passing Techniques in C/C++

### Introduction paragraph (2-3 paragraphs):
Parameter data can be provided into and out of methods and functions in a variety of ways. Assume that a function B() is invoked by another function A ().  In this situation, A is referred to as the caller function, while B is referred to as the called or Calle function. Furthermore, the arguments that A transmits to B are referred to as actual arguments, while the parameters of B are referred to as formal arguments.
In this case,, we will understand the concept of parameter passing  techniques in C/C++ programming language.

### Key takeaways: 
By the end of the article, we will learn:
1. terminologies used in parameter passing.
2. pass by value and pass by reference main methods of parameter passing.
3. other methods of parameter passing.

### References: 
N/A

**Comment by hectorkambow** [comment]
@neshmacharia 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by ahmadmardeni1** [comment]
Thank you for the topic suggestion @neshmacharia.
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
And this topic is widely covered in a lot of blogs, docs, etc ...
Please let me know if you can add more value than what can be found on the internet (and how?).
Otherwise, please feel free to suggest an alternate topic to explore.

**Comment by neshmacharia** [comment]
Hi, @ahmadmardeni1  in my article I will try to be on point and my code snippets will be light for a reader to understand and implement as opposed to the site you had suggested. Also I will include the C and C++ parameter passing considerations so that the reader can know the considerations to be made before passing a parameter.

**Comment by ahmadmardeni1** [comment]
Thank you for your response and we thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation as previously mentioned.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀 @neshmacharia
