### ISSUE TITLE
How I built a personality test app (Myers Briggs Personality test), with Java multi-dimensional arrays.

### ISSUE THREAD

**Issue by CaptainBKola** [section-engineering-education/engineering-education#2825]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Please fill in the Introduction paragraph, Key takeaways, and References. @CaptainBKola

**Comment by CaptainBKola** [comment]
Oh okay. Thank you

**Comment by CaptainBKola** [comment]
Introduction

 An Array is a form of data structure in java that can be very challenging to beginners, but building a complex stuffs with it can be so fascinating.. I come across this Myers Briggs Personality test  file on social media, and I feel I could do something magical with it by  implementing java arrays to make it more stunning. An array is a collection of elements of the same data type.  Java is a programming language with different types of array. Java  axes of  array are  of single dimensional array, or a two dimensional array or a multi-dimensional array. An axis simply means the dimension or the size of an array. A single or a one dimensional array is diagrammatically represented like a list  and usually defined with one square brackets while a two dimensional array takes the form of a table with rows and columns usually with two brackets.

Java array can be declared and initialized at the same time or separately. When declaring java  array,  java compiler does not know the type of elements we are storing in the array object. So, it is  important that we define the type of elements we storing in the array followed by square brackets and the name we are using to referencing the array during initialization or assignment. The name of the array follows java naming conventions. The square brackets denotes that  an array is being set up. The initialization of the array is done with the new keyword followed by the square brackets containing the number of elements we storing or the elements itself.

According to  Isabel Briggs Myers , there  are sixteen types of personalities identities and there are four key elements of categorizing people into the various sixteen personalities identities . The four key elements are:
- Introversion (I) vs. Extraversion (E)
- Sensing (S) vs. Intuition (N)
- Thinking (T) vs. Feeling (F)
- Judging (J) vs. Perceiving (P)
More information on personality typing is here (https://www.truity.com/page/16-personality-types-myers-briggs)

The test contains the four stages above and provides the personalities of the user base on the most common options in the users test answers. In order words, the questions are structured to determine if the user is an introvert or extravert, sensing or intuition, thinking or feeling, judging or perceiving. 

Extraversion – Introversion this test the source and direction of a person’s energy expression. An extravert’s  energy  is mainly in the external world, while an introvert has a source of energy mainly in their own internal world.

Sensing – Intuition test that represents the method by which someone perceives information. Sensing means that a person mainly believes information he or she receives directly from the external world. Intuition means that a person believes mainly information he or she receives from the internal or imaginative world.

Thinking – Feeling, test that represents how a person processes information. Thinking means that a person makes a decision mainly through logic. Feeling means that, as a rule, he or she makes a decision based on emotion, i.e. based on what they feel they should do.

Judging – Perceiving, reflects how a person implements the information he or she has processed. Judging means that a person organizes all of his life events and, as a rule, sticks to his plans. Perceiving means that he or she is inclined to improvise and explore alternative options.

With this test app, it prompt users for questions related to each of the four stages above and categorizes people into the below personality types: INFP, INTJ, INFJ, INTP, ENFP, ENTJ, ENTP, ENFJ, ISFJ, ISFP, ISTJ, ISTP, ESFJ, ESFP, ESTJ, ESTP.  For more information about personality identities kindly follow the link below : https://www.truity.com/page/16-personality-types-myers-briggs

The goals of this tutorial is to:

1. Makes convincing concepts clearer and understanding enough for beginners.

2. Shows the implementation of multi-dimensional array in java in a way that enables the reader how array can be used in I/O applications such as quiz app or in a question and answer app. 

3. Makes a clean implementation of formatting strings in java in relation with data representation in a table.

4. Shows how to write java functions  for array, string and floating-point manipulations.

5. Shows how to use StringBuilder class in java.


Reference 
-[Michael B. White](Mastering Java)

- [Dietel Dietel](https://deitel.com/wp-content/uploads/2019/11/java-how-to-program-11-early-objects-table-of-contents.pdf)

- [Google](google.com)

-[Myers Briggs Personality Interpretation] (https://www.truity.com/page/16-personality-types-myers-briggs)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.

Please be sure to double-check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, reference any relevant EngEd articles in yours. - Approved

Consider changing the title to something similar to Myers Briggs Personality test with Java multi-dimensional arrays
