### ISSUE TITLE
The best bootstrap examples

### ISSUE THREAD

**Issue by Erastuskanyatta** [section-engineering-education/engineering-education#2827]
### Proposed title of article
The best bootstrap examples

### Introduction paragraph (2-3 paragraphs):

Bootstrap is a popular web development front-end framework. It comes with ready-to-use components and design elements for formatting HTML content. Bootstrap is supported by modern browsers like Chrome, Firefox, Opera, Safari, and Internet Explorer.

For different layouts, Bootstrap features a responsive grid system. It's an excellent place to start when creating a mobile-friendly website. Optional JavaScript features like collapsible content, carousels, and modals are also included.

Bootstrap provides an easy solution both for design and responsiveness. It is packed with beautiful elements that can be further styled with your custom CSS, as well as a full grid system to keep your website responsive across all screens while using a clean and understandable syntax.
 

### Key takeaways: 
1. Installing Bootstrap with a Package Manager
2. How to add Bootstrap on a page
3. The Grid System
4. The container
5. The Jumbotron

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Erastuskanyatta 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

Can you tell me how are you planning on adding value beyond what can be found on the internet?  @Erastuskanyatta

**Comment by Erastuskanyatta** [comment]
@ahmadmardeni1, thanks for the question. From my research, I noticed that beginners find it hard to use Bootstrap using the knowledge on the internet. Therefore, in this article, I will try to make Bootstrap look as simple and interesting as possible by covering the main parts used by Web designers and web developers.  I will also show the user how to use bootstrap step by step. As a bonus, I will also explain some lines of CSS and JS that come with Bootstrap.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double-check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @Erastuskanyatta

**Comment by hectorkambow** [comment]
@Erastuskanyatta 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by Erastuskanyatta** [comment]
I am working on it @hectorkambow.  I will let you know once am done.
Sorry for taking too many days.

**Comment by WanjaMIKE** [comment]
Closed #2827 via #4052
