### ISSUE TITLE
How to store your Python functions into modules

### ISSUE THREAD

**Issue by Bonimum** [section-engineering-education/engineering-education#2828]
### Proposed title of article
How to store your Python functions into modules

### Introduction paragraph (2-3 paragraphs):
One advantage of functions is the way they separate blocks of code from your main program. By using descriptive names for your functions, your main program will be much easier to follow. You can go a step further by storing your functions in a separate file called a module and then importing that module into your main program. An import statement tells Python to make the code in a module available in the currently running program file.

Storing your functions in a separate file allows you to hide the details of your program’s code and focus on its higher-level logic. It also allows you to reuse functions in many different programs. When you store your functions in separate files, you can share those files with other programmers without having to share your entire program. Knowing how to import functions also allows you to use libraries of functions that other programmers have written. In this article, we will learn how to store Python functions in modules and how to import them.

### Key takeaways:

- Importing an entire module
- Importing specific functions
- Using as to give a function an alias
- Using as to give a module an alias
- Importing all functions in a module

### References:
N/A

**Comment by jerimkaura** [comment]
Hello @Bonimum , python unit testing was covered here

https://www.section.io/engineering-education/working-with-pythons-unittest/

**Comment by Bonimum** [comment]
@hectorkambow  I have edited the issue and suggested a new topic

**Comment by louisefindlay23** [comment]
@jerimkaura, could you have another look at this topic suggestion because the author has changed their topic. Thanks for looking as this one as I don't have knowledge of Python.

**Comment by jerimkaura** [comment]
Right away @louisefindlay23

**Comment by jerimkaura** [comment]
Thank you @Bonimum for this topic suggestion. Looks like it's a fantastic idea.

The topic seems to be helpful as the takeaways look very promising. I however urge you to go through existing articles to prevent overlap and provide value beyond any sources that I might have missed.

@louisefindlay23  you can go ahead and approve this.

**Comment by louisefindlay23** [comment]
Thanks so much, @jerimkaura. Thanks, @Bonimum for submitting. Topic approved.

**Comment by hectorkambow** [comment]
@Bonimum 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
