### ISSUE TITLE
Some Productivity Hack Developers Can Use to Improve their Career in Tech Faster

### ISSUE THREAD

**Issue by Alao-Abiodun** [section-engineering-education/engineering-education#2835]
### Proposed title of article
Some Productivity Hack Developers Can Use to Improve their Career in Tech Faster.

### Introduction paragraph (2-3 paragraphs):
1. Time Management: It's one of the essential stuff, developers should be aware of because it will actually payed off in aiming well and faster in their career

2. Plan Now, Today, Tomorrow: A sentence which means if you plan now(i.e currently) and making a sketch of the plan at that same spot(i.e Today), then you should be able to make yourself more productive to the next(i.e tomorrow).

3. Law of 33%: It's a process of breaking a model into 3 divisions of chunks, Here is how the 3 chunks can be used to develop yourself as a developer.
Firstly, as a developer, you will need to stay with people who you are a step ahead of, which means at least you will have some little knowledge which the lower developers do not.
Secondly, as a developer you will need to interact with people which you are in the same level, so here you have to watch out for friends who are the same like-minded people with your ambitions.
Thirdly, as a developer you will need to be with people who are more higher than you like 10X (senior engineer), so this will actually make your knowledge more widen.

4. Always Be Learning Something New: This also will actually make you more productive and make you wants to move out of boundary to learn and improve some stuff about you.

5. Stop Handling the Journey Alone: As a developer, you will need to have a mentor, or like joining a community, because there might be sometimes you might be having an issues e.g. Errors in Coding being stuck for hours, Imposter syndrome and others, So where you have mentor or communities they comes in such that they will assist you in solving those problems you are facing.

6. Side Hustle: You might be wondering how this will increase your productivity, yes it will because when it comes getting some jobs like freelancing, if you have that type of work and you have set for a deadline to deliver the product, you will want to deliver it at that time, so in that manner, it helps to move more faster in your learning.

### Key takeaways: 
- Tools used to improve your productivity and how to use it
- Books to read and let you understand how to improve your productivity
- Tech Communities, Podcast to help you find mentor who can pave way for you faster.

### Links to some productivity Apps
- [Pomodoro Web App](https://pomofocus.io/)
- [Pomodoro Mobile App](https://apps.apple.com/us/app/pomodoro-focus-timer/id1265128036)
- [Notability App](https://apps.apple.com/us/app/notability/id360593530)

**Comment by louisefindlay23** [comment]
@Alao-Abiodun, you are only allowed to submit one topic suggestion at a time. Closing in favour of #2816. You may reopen this when your previous topic suggestion has been approved and article published.
