### ISSUE TITLE
Deployment with Ansible

### ISSUE THREAD

**Issue by amchilos01** [section-engineering-education/engineering-education#2838]
### Proposed title of article

Deployment with Ansible

### Introduction paragraph (2-3 paragraphs):

Before the targeted end-users can use an application, it has to be deployed. Deployment refers to the process by which software is made available for use. Deployment can be to a single infrastructure or a wide range of infrastructures. Deployment to a single infrastructure is easily and quickly done, but as the number of infrastructures increases, so is the amount of effort and resources needed to deploy. 
The consistency of the environment is also more likely to change due to higher chances of human error. Another challenge that commonly arises when an application needs to be updated is that, the Updated applications become obsolete by the time the system finishes updating all the applications. Here is where Ansible comes to the rescue. Ansible enables us to deploy applications consistently and reliably. It allows the configuration of several systems from one single system. Application artifacts can also be easily pushed to different systems with the help of Ansible

### Key takeaways: 

•	What is Ansible
•	How to implement Ansible in an organization
•	Ansible integration with other tools 
•	Merits of using Ansible in deployment
•	Who should use Ansible?

### References: 
N/A

**Comment by hectorkambow** [comment]
@amchilos01 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by amchilos01** [comment]
Good afternoon to you, this is Well noted @hectorkambow. Will patiently wait.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double-check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @amchilos01
