### ISSUE TITLE
How to Get Started with Docker Machine

### ISSUE THREAD

**Issue by vincentoriyo** [section-engineering-education/engineering-education#2841]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to Get Started with Docker Machine

### Introduction paragraph (2-3 paragraphs):
Docker Machine is a tool for provisioning and managing your Dockerized hosts (hosts with Docker Engine on them). Typically, you install Docker Machine on your local system. Docker Machine has its own command line client docker-machine and the Docker Engine client, docker. You can use Machine to install Docker Engine on one or more virtual systems. These virtual systems can be local (as when you use Machine to install and run Docker Engine in VirtualBox on Mac or Windows) or remote (as when you use Machine to provision Dockerized hosts on cloud providers). The Dockerized hosts themselves can be thought of, and are sometimes referred to as, managed “machines”.

If you have ever wanted to deploy and configure a Docker host with a single command from your own terminal you have come to the right place. Docker Machine enables you to provision and manage Docker systems in the cloud directly from your own terminal.

Using the Docker Machine tools installed locally you can deploy a new cloud server through the cloud APIs in seconds without ever opening a web browser. This guide shows what you need to get started on Ubuntu Linux but Docker Machine is also available on a number of other operating systems including macOS and Windows.

### Key takeaways: 
1.Setting up Docker Machine environment
2.Provisioning Docker host
3.Deploying containers to Docker hosts remotely

**Comment by louisefindlay23** [comment]
Hi, @vincentoriyo. Great topic suggestion. Since we focus on unique content, can you tell me how your tutorial will differ from this similar Docker Machine [article](https://upcloud.com/community/tutorials/get-started-docker-machine/)?

Thanks,
Louise - Content Moderator

**Comment by vincentoriyo** [comment]
Hi, @louisefindlay23, this one doesnt give a beginner a clear way to get started with docker while this one will give basic understandings of the machine.

**Comment by vincentoriyo** [comment]
i.e "The Docker Client and the Docker Daemon communicate over REST APIs, even on the same system. One tool that can help you manage Docker Daemons running on different systems from our local workstation is Docker Machine." these are not covered on the existing article

**Comment by louisefindlay23** [comment]
Thanks, @vincentoriyo. Sounds great. Topic approved 🚀. Make sure to provide lots of detail in your article to benefit readers.
