### ISSUE TITLE
Getting started with pillow image processing

### ISSUE THREAD

**Issue by phinakersly** [section-engineering-education/engineering-education#2844]
### Getting started with pillow image processing
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
 Pillow is a python library for image processing. It takes care of various operation on images including opening, manipulating and saving different image formats. This tutorial give the reader a beginner friendly approach to using pillow to open image files, carry out image filtering, compress images without losing the quality and saving images in different formats. 
### Key takeaways: 
1. Opening image files in python.
2. Image filtering in python
3. Compressing images without loosing the quality
4. Saving images in different formats
### References: 
1. https://pillow.readthedocs.io/en/stable/
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
@phinakersly, Thank you for the topic suggestion. Looking at the topic form submitted, I see this article covering the basics of pillow library which is covered extensively in the documentation and the web. We tend to navigate towards practitioner focused, original articles. 

I would suggest you to come up with a project using the ideas mentioned above. That way the concepts can be communicated much clearly.

Thank you.

Cc: @hectorkambow

**Comment by phinakersly** [comment]
Hello @lalith1403, I intend to  build a complete Django project that compresses images before uploading them to a database. Uploaded images could be downloaded with lower size but quality maintained. 
Inform me if there is any issue with that. Thank you.

**Comment by lalith1403** [comment]
Yes this is an interesting topic. Please discuss the details and thought process behind every step. Discuss the database aspect in detail as well. 

Maintain emphasis on pillow library and use majority of the features of the library. 

Topic approved. Thank you.

**Comment by hectorkambow** [comment]
@phinakersly 

Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
