### ISSUE TITLE
How to turn your photo into a cartoon using python

### ISSUE THREAD

**Issue by KanizoRGB** [section-engineering-education/engineering-education#2846]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to turn your photo into a cartoon using python

### Introduction paragraph (2-3 paragraphs):
The use of cartoon characters has become a very popular trend among the youth worldwide from whatever they use for their profile pictures on online social platforms to trending memes. The use of these cartoon characters is not only limited to the social platforms but also to other various fields. For example, you can include cartoon characters of real people in school magazines or comics to amuse your readers.
In this article, I will teach you how to convert any photo to a cartoon image using a few lines of code written in python. You can use this concept to build an app solely for converting any image to a cartoon image. The results are quite impressive.

### Key takeaways: 
1. Use python modules to solve problems.
2. Tinkering with picture properties to obtain the desired effect.
3. Convert any photo to a cartoon image. 
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
I understand your other article is almost ready to be published. 

To help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 can be reopened once the first PR is merged.

@KanizoRGB

**Comment by KanizoRGB** [comment]
@hectorkambow reopen this please
