### ISSUE TITLE
Implementing video conferencing with Reactjs, Nodejs and webRTC 

### ISSUE THREAD

**Issue by SamoraCletus** [section-engineering-education/engineering-education#2853]
The article will aim at providing an indepth explanation of the following concepts
i. Fundamentals of web based video conferencing with React, Nodejs and webRTC
ii. Requirements for Video  packets handling 
iii. Integrating event listeners for Camera and microphone
iv. Error handling
v. Handling Browser support
vi. Recommended APIs
vii. Implementation and testing
viii. Conclusion

**Comment by louisefindlay23** [comment]
Hi, @SamoraCletus. Thanks for submitting a topic suggestion but please fill in all the questions in the template provided so we can accurate review your topic suggestion for approval.

**Comment by SamoraCletus** [comment]
> Hi, @louisefindlay23 
TOPIC:
 Implementing Video Conferencing with Reactjs, Nodejs and WebRTC 

Introduction:
 Developers around the world have an incredible task of handling client’s requirements and video conferencing is one of those requirements developers have great difficulty implementing. The pandemic has opened up opportunities in remote works and “work from home” which comes at the cost of efficient video conferencing and packets handling.
	React and WebRTC provides an excellent tool for making the implementation of web-based video conferencing seamlessly easy. We will take a deep dive into the details of using these frameworks in efficient video conferencing.

Key Takeaways: 
at the end of this article, the reader should be able to understand and answer the following questions
What are the fundamentals of web-based video conferencing?
What are the components of video conferencing system?
What are the requirements foe web packets handling?
How to integrate event listeners for camera and microphone?
What are the recommended APIs for video conferencing?
How to handle errors in video conferencing with react testing libraries. 
References: 
Centralized Conferencing (xcon). Left.org. 2014-07-16. Retrieved 2019-07-11

**Comment by louisefindlay23** [comment]
Hi, @SamoraCletus. Thanks for providing additional details. Great topic suggestion. 

Since we focus on original content, can you tell me how your article with differ for [this one](https://dev.to/arjhun777/video-chatting-and-screen-sharing-with-react-node-webrtc-peerjs-18fg) which has a similar topic?

Thanks,
Louise - Content Moderator

**Comment by SamoraCletus** [comment]
Thank you for the important question
From the article you shared, we are both trying to solve the same challenge
of video conferencing but the author focused on just the codes to solve the
challenge and not the theory or fundamentals.
My article will focus on
i. The fundamentals of web based video conferencing
ii handling video and audio packets
iii. How to integrate event listeners for Camera and microphone
iv. the recommended APIs
v. Finally, how to handle errors

**Comment by louisefindlay23** [comment]
Thanks, @SamoraCletus for your detailed answer. Topic approved.

**Comment by hectorkambow** [comment]
@SamoraCletus 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by louisefindlay23** [comment]
Reopened due to PR in review: #3087.

**Comment by WanjaMIKE** [comment]
Closed #2853 via #3087
