### ISSUE TITLE
Understanding AES and RSA encryption algorithms

### ISSUE THREAD

**Issue by awinomackrine** [section-engineering-education/engineering-education#2856]
### Introduction paragraph (2-3 paragraphs):
Encryption is basically a way of enciphering data especially when its on transit to prevent unauthorized personnel from  gaining access to it. Encryption is always done with intent of allowing only the intended recipient of a piece of data to have access to the data.  It is a key feature in maintaining the confidentiality, integrity and availability of data in communication.

In this article I will dwelling on the two methods of achieving encryption otherwise referred to as encryption algorithms. I will be diving deep into  AES and RSA encryption algorithms, discussing the steps involved in achieving encryption through them and the different reasons why they are in the front lane in the data encryption initiative.

### Key takeaways: 
1. The reader will be in a position to understand encryption as an emerging issue in information security and the ways of achieving encryption.
2. The reader will be able learn matters security through data encryption
3. The reader will be able to learn the two algorithms of achieving data security, that is AES and RSA.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@awinomackrine 

Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
