### ISSUE TITLE
JavaScript Split – How to Split a String into an Array in JavaScript.

### ISSUE THREAD

**Issue by Joshuathuo** [section-engineering-education/engineering-education#2861]
### Proposed title of the article
JavaScript Split – How to Split a String into an Array in JavaScript.

### Introduction paragraph (2-3 paragraphs):
The split() method in JavaScript is a technique that parts a string into a variety of substrings and returns the new exhibit. 
If an empty string (" ") is utilized as the separator, the string is parted between each character. 
The split() technique doesn't change the first string.

In this article, I shall look deeply at how you can use the split method in JavaScript by understanding what the split method entails first and then digging deep into the real usage of the split method in JavaScript.

### Key takeaways: 
1. The split() Method in JavaScript
2.  Splitting  a String by Each Character
3. Splitting  a String into One Array
4. Splitting  a String Using a Non-matching Character

### References: 
N/A

**Comment by lalith1403** [comment]
Good morning @Joshuathuo and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topic.
That way a developer could see them in action.

As mentioned above - we believe this topic is widely covered on other blog site.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
Cc: @hectorkambow

**Comment by Joshuathuo** [comment]
Thanks@lalith1403 . That means I'm open to suggesting a new topic.
Cc@hectorkambow

**Comment by Joshuathuo** [comment]
@lalith1403 I changed my topic to  JavaScript Split – How to Split a String into an Array in JavaScript. 
Please have a look .

Ping me if there is an issue.
Cc@hectorkambow

**Comment by lalith1403** [comment]
@louisefindlay23 Can you check this issue related to JavaScript whenever you get a chance?

**Comment by neheMaish** [comment]
@louisefindlay23  You can please have a look at this topic which was directed to you by @lalith1403 

I will highly appreciate.

**Comment by lalith1403** [comment]
@zolomohan Can you take a look whenever you get a chance? @louisefindlay23 might have a heavy workload of articles. Thank you.

**Comment by zolomohan** [comment]
sure thing @lalith1403.

**Comment by zolomohan** [comment]
@Joshuathuo split is just one function in JavaScript and the MDN docs are very good and cover almost everything. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split
can you please go over this and tell me what unique approach you have on the split function?

**Comment by Joshuathuo** [comment]
@zolomohan Thanks. In matters regarding the topic, there are some things that I will have to cover like the following,
1. How to split with Array Destructuring
2. How to split using Regex
3. How to split with a limit

These are some of the topics I'll have to add

**Comment by zolomohan** [comment]
@Joshuathuo I still don't think just writing about one function provides a lot of value. Maybe you can pick several string functions and then write about them whilst making sure you are not covering the same stuff from the docs or commonly covered use cases. Our goal here is to provide unique and valuable content to the readers. Please keep that in mind.

**Comment by neheMaish** [comment]
@zolomohan  Thanks. Yeah, more especially the ones that I have stated above and also some others.

**Comment by Joshuathuo** [comment]
@zolomohan I agree with you , especially those that I have mentioned above and some others that I will have to cover

**Comment by zolomohan** [comment]
Yes. Please let me know what other string functions you'll be covering.

**Comment by Joshuathuo** [comment]
Some others methods are 
1 How to split a character using a non- matching character
2 How to split a string by each character

**Comment by Joshuathuo** [comment]
@zolomohan Please check at my reply

**Comment by zolomohan** [comment]
I meant other JavaScript String functions. Not different methods using split function.

**Comment by Joshuathuo** [comment]
@zolomohan 
Search (Regexp)
Split (delimiter,[limit]
substr(start,[length]

**Comment by zolomohan** [comment]
You can rename your article has JavaScript String Functions or something like that. Make sure the article provides a unique perspective.

**Comment by zolomohan** [comment]
@ahmadmardeni1 I think this is good to go.

**Comment by ahmadmardeni1** [comment]
@Joshuathuo Make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions, and you have to bring a unique perspective, as Zolomohan said.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by WanjaMIKE** [comment]
Issue closed
