### ISSUE TITLE
How Edge Artificial Intelligence is Revolutionizing Mobile Application Development 

### ISSUE THREAD

**Issue by BashiirIsla** [section-engineering-education/engineering-education#2863]
### Proposed title of article
How Edge Artificial Intelligence is Revolutionizing Mobile Application Development 
### Introduction paragraph (2-3 paragraphs):
The growth of artificial intelligence is driving a whole new class of mobile app possibilities. AI has been influential in app development for several years already, and it has the potential to advance much more in the coming years. Machine learning has moved out of its infancy, and users now want flexible algorithms for seamless and intuitive experiences. The new availability and advancement of AI and machine learning are causing a revolutionary shift in the way that developers, businesses, and users think about intelligent interactions within mobile applications.

The Artificial Intelligence disruption in the mobile applications industry is very high at that moment. Even mobile device manufacturers are working to build devoted hardware to leverage the best AI capabilities. 
### Key takeaways: 

1. Artificial Intelligence at the edge
2. How mobile apps are leveraging AI in:
  IoT integration
 Delivering Personalized Content
 Voice-Powered Technology
  3. Examples of AI-Powered Mobile Apps

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Hello @BashiirIsla and thank you for submitting the topic suggestion form. In order to proceed, we will need a few clarifications on your end. Firstly, the title is misleading. I thought the article was about how AI was helping automate mobile app Dev. Secondly, can you throw some more light on what topics you are going to cover under AI deployed at edge devices. 

Once we have sorted these details, we can move further down the process. Thank you. Excited to know more about inference at edge and techniques that help the goal.

**Comment by BashiirIsla** [comment]
Hello @lalith1403 thank you for this feedback. 

1. I do not think the title is misleading. My article is not about automating mobile app dev. It is about using AI to deliver smart, safe, and effective applications (AI-based apps). I am open to changing the title of this article, though, depending on your suggestion. 
2. On Artificial Intelligence at the edge
AI-powered apps face challenges relating to latency, data security, complexity, and cost. The edge brings the intelligence as close as possible to the data source and the point of action. This will lead to improved privacy with AI-powered apps, reduced costs and latency times, etc.

**Comment by ahmadmardeni1** [comment]
Any update on this topic? @lalith1403 Should we approve it?

**Comment by lalith1403** [comment]
@ahmadmardeni1 @hectorkambow We can proceed with this topic provided the title has no issues. What do you think?

**Comment by ahmadmardeni1** [comment]
I like the title. Do you think it should be something else? any suggestions? @lalith1403

**Comment by lalith1403** [comment]
I must be looking at it from a different angle. Let's proceed. AI at edge is exciting. @BashiirIsla Topic approved.

**Comment by WanjaMIKE** [comment]
Closed #2863 via #3465
