### ISSUE TITLE
Understanding Cross Site Request Forgery Attacks

### ISSUE THREAD

**Issue by Pauline-Mwangi** [section-engineering-education/engineering-education#2866]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Cross Site Request Forgery Attacks

### Introduction paragraph (2-3 paragraphs):
Cross-site request forgery (CSRF) is a web security vulnerability that allows an attacker to induce users to perform actions they do not intend to perform. The attacker tricks the authenticated user (victim) into performing malicious activities on their behalf.

CSRFs are typically conducted using malicious social engineering, such as an email or link that tricks the victim into sending a forged request to a server. As the unsuspecting user is authenticated by their application at the time of the attack, it’s impossible to distinguish a legitimate request from a forged one.

 This article aims to give a comprehensive understanding of CSRF attacks.

### Key takeaways: 
1. Overview of CSRF 
2. How CSRF works
3. Impacts of CSRF attacks
4. Testing of CSRF attacks
5. How to prevent CSRF attacks

### References: 
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Pauline-Mwangi 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is covered in other blog sites.

I think it will be a great addition to our program. Please make sure to include a disclaimer - this is a very sensitive topic and we need everything to be legal. Approved @Pauline-Mwangi

**Comment by hectorkambow** [comment]
@Pauline-Mwangi 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by Pauline-Mwangi** [comment]
@hectorkambow I opened a new PR based on this issue. Please re-open
