### ISSUE TITLE
Client-side validation in React with react-alert

### ISSUE THREAD

**Issue by Caleb335** [section-engineering-education/engineering-education#2867]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Client-side validation in React with react-alert

### Introduction paragraph (2-3 paragraphs):
Having a way to check if the data that a user is sending to the webserver of a web application is correct or appropriate or valid has been one of the quirks that JavaScript enables on the web. This feature gives frontend developers the ability to write checks/logics that validate the data that users type into the input fields of web apps.

In this article, we’re going to have a look at how to accomplish this task by using an npm package called react-alert, react-alert makes it easier to render the error messages from the logic that would’ve been written beforehand by the developer.

### Key takeaways: 
When the reader is done reading this article: 
- They'd have an understanding of how conditional statements work in javascript and how to apply them in ReactJS.
- Dom manipulation

### References: 
None

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Caleb335 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by Caleb335** [comment]
Thank you very much @hectorkambow! 😊

I look forward to the feedback(s) 🥂

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Please [be sure to double-check that it does not overlap with any existing EngEd articles](https://www.section.io/engineering-education/search/?q=react%20alert) or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by Caleb335** [comment]
Thank you for approving this article! 

I'd be sure to follow all the guidelines that you have mentioned.
