### ISSUE TITLE
An Overview of Error Analysis; a new Responsible AI open-source toolkit

### ISSUE THREAD

**Issue by lilo254** [section-engineering-education/engineering-education#2868]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
An Overview of Error Analysis; a new Responsible AI open-source toolkit

### Introduction paragraph (2-3 paragraphs):
Error analysis is a strategy used to document the errors that show up in learner language, decide if those errors are systematic, and if conceivable clarify what caused them.
Error Analysis is a Responsible AI toolkit that enables you to get a more profound comprehension of Machine Learning model mistakes. While assessing a machine learning model, total precision isn't adequate and single-score assessment may shroud significant states of errors. Error Analysis is used to distinguish cohorts with higher error rates and analyze the main drivers behind these errors.
Error analysis in Machine Learning is not just to improve performance on your target metric, but also provides an avenue to know if your model is doing well and analyzing where your model went wrong on your test data, and how to make systematic changes to your model based on these insights.

### Key takeaways: 
1. Defining Error Analysis in Machine Learning.
2. An overview of how Error Analysis Work
3. Understanding failures in Machine Learning

### References: 
https://techcommunity.microsoft.com/t5/azure-ai/responsible-machine-learning-with-error-analysis/ba-p/2141774?wt.mc_id=aiml-17954-sejuare
https://towardsdatascience.com/responsible-machine-learning-with-error-analysis-a7553f649915
https://erroranalysis.ai/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Hello @lilo254. This is surely an exciting topic. Can you elaborate on the concept used, such as learner language, systematic errors, etc. Explain the terminology used to better communicate the ideas across to the reader. 

Excited to read the article. 
Cc: @hectorkambow

**Comment by lilo254** [comment]
Hi @lalith1403 
Thank you for the response. I will expound more on the concepts such as systematic errors that are consistent and repeatable errors displayed by the machine learning models under the section where I will be defining Error Analysis in machine learning.
