### ISSUE TITLE
IoT Development with Rust vs. C++

### ISSUE THREAD

**Issue by Snzovi** [section-engineering-education/engineering-education#2869]
### Proposed title of article
IoT Development with Rust vs. C++

### Introduction paragraph (2-3 paragraphs):
Rust and C++ languages are very important in IoT development. They are both utilized in the areas where the direct connection with hardware configuration, speed of performance, and low-level access to memory and controllers matter the most. 

Specifically, device and application levels of IoT, system programming (drivers, operating system kernels, controllers, etc.), desktop utility programming, 3D game development, and many other spheres. 

Both languages have certain competitive fields like Web, Game, and UI development. This article checks the most important comparison areas between the two to help you decide on which language to adapt for your latest project(s). 

### Key takeaways: 

1. IoT Deployment with Rust 
2. IoT Deployment with C++
3. Comparison between Rust and C++

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Snzovi 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Please reference any relevant EngEd articles in yours. - Approved @Snzovi
