### ISSUE TITLE
Spring Boot Messaging with Redis

### ISSUE THREAD

**Issue by okeloviolet** [section-engineering-education/engineering-education#2873]
### Spring Boot Messaging with Redis
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Redis is an open-source, in-memory data structure store, used as a database, cache, and message broker. In the article, I will use Redis as Message Broker to create a messaging layer in a demo finance application. The application consists of multiple microservices which interact with each other. 

I will explain how to create an event-driven construct, where services would connect to messaging layer and would publish and subscribe events to messaging layer.

### Key takeaways: 
1. Adding Redis support in a Spring Boot application.
2. Implementing a publish/subscribe message queue in Spring Boot with Redis.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@okeloviolet 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by LinusMuema** [comment]
Hi @okeloviolet 
I believe this would be a great article and I would be interested in reading it. 
One question however, how will it differ from the [official docs](https://spring.io/guides/gs/messaging-redis/) provided by spring or video tutorials such as [this one](https://www.youtube.com/watch?v=LUrk5xEXAf4)

**Comment by okeloviolet** [comment]
Hello @LinusMuema take note that the links you provided only show how to using Redis with a monolith Spring Boot application but in this case I am going to explain how to use Redis in microservices.

**Comment by LinusMuema** [comment]
Hi @okeloviolet 
Then if that is the case, make sure your article is original and provides some good help. Otherwise you can go ahead 🚀

**Comment by ahmadmardeni1** [comment]
Closing this topic to avoid a backlog queue. Can be reopened👍
