### ISSUE TITLE
How to Lazy Load Modules in Angular 12 with Dynamic Imports

### ISSUE THREAD

**Issue by jumamiller** [section-engineering-education/engineering-education#2877]
### Proposed title of article
How to Lazy Load Modules in Angular 12 with Dynamic Imports

### Introduction paragraph (2-3 paragraphs):
Lazy loading (also called on-demand loading) is an optimisation technique for the online content, be it a website or a web app.

Instead of loading the entire web page and rendering it to the user in one go as in bulk loading, the concept of lazy loading assists in loading only the required section and delays the remaining, until it is needed by the user.

By default, NgModules are eagerly loaded, which means that as soon as the app loads, so do all the NgModules, whether or not they are immediately necessary. For large apps with lots of routes, consider lazy loading—a design pattern that loads NgModules as needed. Lazy loading helps keep initial bundle sizes smaller, which in turn helps decrease load times.
There are two main steps to setting up a lazy-loaded feature module
1.Create the feature module with the CLI, using the --route flag.
2.Configure the routes.

### Key takeaways: 

1.Create a feature module with routing
2.Lazy Load Components
3.Advantages of Lazy loading:
4.Disadvantages of Lazy loading

**Comment by hectorkambow** [comment]
@jumamiller 
 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 can be reopened once the first PR is merged.

**Comment by jumamiller** [comment]
@hectorkambow, you can now reopen this, other has been published
