### ISSUE TITLE
 How the Model View Controller Architecture Works

### ISSUE THREAD

**Issue by Eztaezta** [section-engineering-education/engineering-education#2879]
### Proposed title of article
 How the Model View Controller Architecture Works

### Introduction paragraph (2-3 paragraphs):
Websites have evolved from simple pages with a little CSS to far more complicated and powerful applications in recent years.

Programmers use different patterns and software architectures to make the code less difficult, making these applications easier to develop.

 What is software architecture?
Architecture is a systematic way in which software is described. It also refers to its relationship with other software, and how they interact with each other.

The most popular software architecture, by far, is the Model-View-Controller, or MVC.

In this article, we will look at the Model-View-Controller software architecture.

### Key takeaways: 
1. Software architecture Definition in detail
2. Model-View-Controller (MVC) Architecture
3. How MVC Architecture works
4. Benefits of  Model-View-Controller
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Eztaezta 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by LinusMuema** [comment]
Hi @Eztaezta 
This sounds like a helpful article, especially for beginners.
Please let's be sure it adds value beyond what is covered in other blog sites.
Also, ensure it does not conflict with any other already published content.
topic approved

**Comment by hectorkambow** [comment]
@Eztaezta 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by Eztaezta** [comment]
@hectorkambow. Please re-open the topic. 
I apologize for the delay.
