### ISSUE TITLE
Visualizing Repositories Using Pygal

### ISSUE THREAD

**Issue by duncandegwa** [section-engineering-education/engineering-education#2882]
### Proposed title of article
Visualizing Repositories Using Pygal

### Introduction paragraph (2-3 paragraphs):
Pygal is a Python API that enables us to build scalar vector graphic (SVG) graphs and charts in a variety of styles. In this article,you will learn how to make a visualization showing the relative popularity of Python projects on GitHub. We’ll make an interactive bar chart: the height of each bar will represent the number of stars the project has acquired. Clicking a bar will take you to that project’s home on GitHub.

### Key takeaways: 
By the end of this article the reader should have learned the following:

- Refining Pygal Charts
- Adding Custom Tooltips
- Plotting the Data
- Adding Clickable Links to Our Graph

### References: 
N\A

**Comment by hectorkambow** [comment]
@duncandegwa 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Approved @duncandegwa

**Comment by ahmadmardeni1** [comment]
Closing this topic to avoid a backlog queue. Can be reopened👍
