### ISSUE TITLE
Concept of Functions in PHP

### ISSUE THREAD

**Issue by JosephWainaina** [section-engineering-education/engineering-education#2883]
### Proposed title of article
concept of functions in PHP server-side programming

### Introduction paragraph (2-3 paragraphs):
A function is a set of statements that performs a specific task. Function will produces output when it is called. They are different ways of calling a function. We will look different features of a functions such as code reusability 
In this article, we will understand the concept of function in PHP.
### Key takeaways: 
1. variable-length argument lists
2. Optional parameters
3. Passing Arguments by Reference
4. Basic Functions Usage

### References: 
N/A

**Comment by hectorkambow** [comment]
@JosephWainaina 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
