### ISSUE TITLE
Building a network with Dynamic and Static routing using Cisco packet tracer

### ISSUE THREAD

**Issue by mohamedgh16** [section-engineering-education/engineering-education#2884]
### Proposed title of article

Understanding Dynamic and Static routing using Cisco packet tracer.

### Introduction paragraph (2-3 paragraphs):

Packet Tracer is a cross-platform visual simulation tool designed by Cisco Systems that allows users to create network topologies and imitate modern computer networks. The software allows users to simulate the configuration of Cisco routers and switches using a simulated command-line interface. 

In this tutorial we will build a network in two different ways dynamic & static, we will also go through the steps of choosing the proper tools of Cisco packet tracer that would help us build the network from scratch. Cisco packet tracer is a very useful tool that allows the manipulation and implementation of various types of networks, it also gives us an authentic touch of how routers, switches, modems, and other useful tools really work in the real world.

### Key takeaways: 
- Dynamic routing implementation 
- Static routing implementation

### References: 
https://en.wikipedia.org/wiki/Packet_Tracer
https://www.section.io/engineering-education/understanding-static-dynamic-routing/

**Comment by hectorkambow** [comment]
@mohamedgh16 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Reference any relevant EngEd articles in yours. - Approved @mohamedgh16
