### ISSUE TITLE
Why Backup won't work for Stateful containers?

### ISSUE THREAD

**Issue by verah-tech** [section-engineering-education/engineering-education#2887]
### Proposed title of article
Why Backup won't work for Stateful containers?

### Introduction:
Any data that containers create need to be backed up. It is easier to backup data stored in stateful apps compared to stateless apps. However, there has been a myth that containers are stateless, which may be the truth or false. 
In this article, we will debunk these myths and misconceptions and explore why backup solutions may not work for stateful containers.

### Key takeaways: 
At the end of this article, the learner will be able to:
- understand where containers stores state
- explain where and why most backup solutions fail
- find out the right solution for backup

### References: 
N/A

**Comment by hectorkambow** [comment]
@verah-tech 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
@BrianaNzivu This topic as well, let me know your thoughts, please.

**Comment by BrianaNzivu** [comment]
Hey @ahmadmardeni1 👋🏾.

I think @verah-tech can maybe make this article a tutorial on how to back up containers. I think it will be of more value. 

She can still discuss her key takeaways even before starting the tutorial itself because I believe all that info can be squeezed into a paragraph or two. 

Regards 🚀.

**Comment by verah-tech** [comment]
> tutorial on how to back up containers

@BrianaNzivu cc @ahmadmardeni1 Thank you for reply, I can add the final part as a tutorial on how to back up containers like you have suggested in order to add more value to the article. Kindly advice.

**Comment by ahmadmardeni1** [comment]
@BrianaNzivu Do you think it is enough if she makes it a tutorial on how to back up containers? Will the reader expect any other value(s)?

**Comment by BrianaNzivu** [comment]
> @BrianaNzivu Do you think it is enough if she makes it a tutorial on how to back up containers? Will the reader expect any other value(s)?

I am suggesting that she can have an article that covers all the key take aways she has mentioned plus a tutorial at the end on how to back up containers just as @verah-tech has mentioned.


With that her article will be superb

Regards 🚀 .

**Comment by ahmadmardeni1** [comment]
Thank you 🚀 @BrianaNzivu 

Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double-check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @verah-tech

**Comment by WanjaMIKE** [comment]
Closed #2887 via #3519
