### ISSUE TITLE
Inheritance in Ruby 

### ISSUE THREAD

**Issue by ianmaish** [section-engineering-education/engineering-education#2888]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Inheritance in Ruby

### Introduction paragraph (2-3 paragraphs):
The term "inheritance" is made up of the words "inherit" and "to derive." As a result, inheritance is described as the tendency of one class to derive attributes and characteristics from other classes. It has additional functionality for extracting features from the base class and implying them into other derived classes. In simple terms, one class inherits the attributes and methods of another class. We will learn how to extend a class in Ruby, how to override a method and how to call the original method. We will also understand the principle of Don't Repeat Yourself (DRY) and apply code re-use to minimize repetition while writing code. We will gain insight into private methods and learn to write shy code. 

### Key takeaways: 
1. What is inheritance
2. How to extend a class
3. Learn how to override methods
4. Inheritance and DRY
5. Information hiding/encapsulation
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@ianmaish 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀 @ianmaish
