### ISSUE TITLE
Managing Docker Containers using Command Line Interface(CLI)

### ISSUE THREAD

**Issue by Wanyoike-shift** [section-engineering-education/engineering-education#2891]
### Proposed title of article
Managing Docker Containers using Command Line Interface

### Introduction paragraph (2-3 paragraphs):
If you are managing numerous Docker Containers simultaneously, you might have noticed that this is indeed a very hefty task. In this article, we will learn some top ways that can be very handy for you to manage Docker Containers straight from the Command Line Interface. We will see practical examples of the most commonly used yet very effective and efficient Docker Commands that would surely make your Docker experience seamless.

### Key takeaways: 
By the end of this article the reader will be able to manage docker containers by:
1. Running a Docker Container in Interactive Shell.
2. Remove all the Dangling Volumes
3. Removing Docker Containers and Images
4. Using Aliases.
5. Inspecting Docker Containers .

### References: 
N/A

**Comment by hectorkambow** [comment]
@Wanyoike-shift 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Hey @BrianaNzivu what do you think of this topic?

**Comment by BrianaNzivu** [comment]
Hey @ahmadmardeni1 👋🏾.
I think this is an amazing tutorial.
It is indeed a problem that is being faced when it comes to Containers.

From his key takeaways there is nothing I'd like to add or remove but only request @Wanyoike-shift to be as detailed as possible when explaining each his key takeaways (Provide as much detail, perks and code snippets) that will make his article stand out.

@Wanyoike-shift 👋🏾. 
I'd really like to read this article. Please ping me when you open a PR.

Regards 🚀.

**Comment by Wanyoike-shift** [comment]
Hello @ahmadmardeni1 and @BrianaNzivu can I start writing this article.

**Comment by Wanyoike-shift** [comment]
Hello @ahmadmardeni1 and @BrianaNzivu can I start writing this article.

**Comment by BrianaNzivu** [comment]
@Wanyoike-shift .please wait for @ahmadmardeni1 to approve the article first.
Regards.

**Comment by ahmadmardeni1** [comment]
Thank you! @BrianaNzivu 🚀

Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites. @Wanyoike-shift 

Please be sure to double-check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. Reference any relevant EngEd articles in yours. - Approved
