### ISSUE TITLE
Data modeling and Query customization in Cloud Firestore with Kotlin

### ISSUE THREAD

**Issue by nonimdiana** [section-engineering-education/engineering-education#2893]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Proposed title of article
Data modeling and Query customization in Cloud Firestore in Android-Kotlin

Introduction paragraph (2-3 paragraphs):

Firestore is a cloud-hosted document based database. It can be used via the appropriate native SDKs in numerous platforms (iOS, Android, and web apps). Firestore is a trustworthy database because it provides flexible data storage formats, expressive querying, offline support, better identity and access management, and synchronized real-time changes.

In this tutorial, we'll learn how to `design` a Firestore database, perform universal data `structuring/modeling` and implement complex and custom queries using the `Kotlin` programming language. 
As a Software Engineer, you need these skills to stand out in the Database management sector.

Key takeaways:

By the end of this tutorial, the reader will be expected to:

- Understand the importance of data modeling.
- Be able to design a Firestore database.
- Perform simple, complex, and custom queries.
- Effectively manage a myriad database.

References:

N/A

**Comment by hectorkambow** [comment]
@nonimdiana 
 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 can be reopened once the first PR is merged.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.

Please be sure to double-check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure (we have multiple articles/tutorials covering firebase so please double-check), reference any relevant EngEd articles in yours. - Approved @nonimdiana

**Comment by ahmadmardeni1** [comment]
Closing this topic to avoid a backlog queue. Can be reopened👍

**Comment by WanjaMIKE** [comment]
Closed #2893 via #3730
