### ISSUE TITLE
How to collect sensor data on your iPhone or Android using Matlab

### ISSUE THREAD

**Issue by queenterbruce063** [section-engineering-education/engineering-education#2897]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
Have you ever been in a situation where you are trying to build a project but are still waiting on sensors that haven't even left the warehouse? Well, there is a solution to this. Did you know you can use your smartphone for those tasks? Smartphones have several sensors and with the Matlab mobile app, you can use some of those sensors to collect and analyze data.
Sensors are electrical devices that can be used to detect various conditions or objects. They use signals to detect the various conditions and objects. Sensors form an important part of sensor involved project. In this tutorial, we will look at how we can collect data using the smartphone's sensors and use these data for various projects. 

### Key takeaways: 
- How to collect data using smartphone's sensors.
- Importance of sensors and various applications.
- How to use Phone Matlabs.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@queenterbruce063 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by lalith1403** [comment]
Sounds like an interesting topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double-check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved 
@queenterbruce063
