### ISSUE TITLE
Introduction to Java Servlets

### ISSUE THREAD

**Issue by munenekelvin** [section-engineering-education/engineering-education#2898]
### Proposed title of article
Introduction to Java Servlets

### Introduction paragraph (2-3 paragraphs):
Today we all are aware of the need of creating dynamic web pages i.e the ones which have the capability to change the site contents according to the time or are able to generate the contents according to the request received by the client. If you like coding in Java, then you will be happy to know that using Java there also exists a way to generate dynamic web pages and that way is Java Servlet. 

In this article we will understand the need for server-side extensions. Servlets are the Java programs that runs on the Java-enabled web server or application server. They are used to handle the request obtained from the web server, process the request, produce the response, then send response back to the web server.

### Key takeaways: 
By the end of this article the reader will have understood:
1.  what servlets are, their properties and execution.
2.  the Servlet Architecture.
3.  the need for server side extensions to to create dynamic web pages.
4.  what common gateway interface(CGI) is.
5. Advantages of a Java Servlet.
6. The Servlet Container.

### References: 
N/A

**Comment by hectorkambow** [comment]
@munenekelvin 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by LinusMuema** [comment]
Hi @munenekelvin 
This sounds like a really interesting article. Just make sure you cover your takeaways in-depth and provide more original content. Just ensure your article stands out from other articles on other blog sites. Also, please check your grammar and flow. I have noticed some flaws in the introduction paragraph.

You can check @louisefindlay23's or @katungi's articles. IMO, they are good when it comes to grammar and general flow.

article approved :rocket:
