### ISSUE TITLE
Federated Learning using TensorFlow Federated (TFF)

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#2902]
### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Federated Learning using TensorFlow Federated (TFF)

### Introduction paragraph (2-3 paragraphs):

Federated learning is a privacy-preserving technology for training and evaluating machine learning models across a fleet of devices (e.g. Android phones), orchestrated by a central server, without sensitive training data leaving any user's device. On the other hand, TensorFlow Federated is an open-source framework for machine learning used in implementing federated learning. 
In this article, we will learn how TensorFlow Federated can enable researchers and pioneers to simulate federated learning on their own datasets.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this article, a reader will be able to:

1. Learn about TensorFlow Federated (TFF)
2. Learn the code behind TensorFlow Federated learning
3. Learn how you can simulate Federated learning on your own datasets.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

1. [Federated Learning for Mobile Keyboard Prediction](https://arxiv.org/pdf/1811.03604.pdf)
2. [TensorFlow Federated](https://github.com/tensorflow/federated)
3. [TensorFlow Federated: Machine Learning on Decentralized Data](https://www.tensorflow.org/federated)
4. [An online comic book from GoogleAI to learn Federated learning](http://federated.withgoogle.com/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Bayler 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by lalith1403** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double-check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - 
Approved @Bayler

**Comment by WanjaMIKE** [comment]
Closed #2902 via #3029
