### ISSUE TITLE
Sending Notifications with Spring Boot, Angular, and Firebase Cloud Messaging

### ISSUE THREAD

**Issue by john-amiscaray** [section-engineering-education/engineering-education#2908]
### Proposed title of article
Sending Notifications with Spring Boot, Angular, and Firebase Cloud Messaging

### Introduction paragraph (2-3 paragraphs):
Notifications are a great way to increase user engagement. By keeping them notified of events in your app that interest them, you can keep them coming back to you. Many apps even rely on notifications as a core feature. For example, there are some reminder apps that help you remember important events. What would they be without being able to notify you while inactive? Either way, sending notifications is an important skill to learn as a developer.

In this guide, we will be learning how to send notifications to an Angular application. To make this possible, we will be using a Spring Boot backend with the help of **Firebase Cloud Messaging**. By the end of this guide, you should have a good understanding of how to send notifications in your next full-stack application.

### Key takeaways: 
- What is firebase cloud messaging and how do we set it up?
- What is a service worker and why do we need it?
- Using the firebase admin SDK to send notifications in Java or Kotlin.
- The high-level architecture of how the notification will be sent.
- Getting the user's permission to send notifications and reacting appropriately.

### References: 
- https://medium.com/mighty-ghost-hack/angular-8-firebase-cloud-messaging-push-notifications-cc80d9b36f82

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@john-amiscaray 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by LinusMuema** [comment]
Hi @john-amiscaray 
This article sounds great and helpful. Just check to provide more original content that is not available in official docs and other blog sites.

topic approved :rocket:
