### ISSUE TITLE
AI vs ML – What’s the Difference Between Artificial Intelligence and Machine Learning?

### ISSUE THREAD

**Issue by fely545** [section-engineering-education/engineering-education#2911]
### Proposed title of article
 AI vs ML – What’s the Difference Between Artificial Intelligence and Machine Learning?

### Introduction paragraph (2-3 paragraphs):

Artificial intelligence and machine learning are two popular and often hyped terms these days. And people often use them interchangeably to describe an intelligent software or system.

In this article, we will learn the differences between AI and ML with some practical examples to help clear up any confusion.

### Key takeaways: 

- What is AI, or Artificial Intelligence?
- Examples of artificial intelligence eg Robotics,Personal Assistants
- What is ML, or Machine Learning?
- Examples of Machine Learning egProduct Recommendations,Email Spam and Malware Filtering
- The Difference Between AI and ML

**Comment by lalith1403** [comment]
Thank you for the topic suggestion @fely545. However, this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀

**Comment by duncandegwa** [comment]
Is machine learning and programming not programming centric

**Comment by lalith1403** [comment]
This particular topic is covered widely on the web and we encourage authors to come up with original programmer centric articles that will truly add value to the reader. I hope that clarifies the doubt. 

You may submit a new issue. Would love to see what else is on your mind. 

Cheers,

Lalith
