### ISSUE TITLE
The five common pitfalls of MySQL window functions and how to avoid them

### ISSUE THREAD

**Issue by elphazesedah** [section-engineering-education/engineering-education#2914]
### Introduction paragraph (2-3 paragraphs):
A MySQL window function is a function that manipulates values from one or more rows to give value returns for every row using basal queries. Window functions usually have an OVER clause, hence any function that lacks the clause is not a window function.
In this article I will be diving deep into the MySQL window Function, explaining their functionalities,  discussing the five common pitfalls that have been seen in their use  and finally explaining how to avoid this pitfalls.

### Key takeaways: 
1. The reader will be able to definitively understand the concept of window functions and their functionalities.
2. The reader will be in a position to understand some of the problems that have been experienced with the use of window functions.
3. The reader will be able to understand the methods they can use to avoid the window function pitfalls

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@elphazesedah 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Hey @srishilesh What do you think of this topic? Let me know your thoughts, please.

**Comment by srishilesh** [comment]
@ahmadmardeni1 Thanks for pinging me.

@elphazesedah This sounds like an amazing topic. I don't find much articles on the internet either, so it will be a great value-add to your article and to the community.

My suggestion would be:
- Start by explaining what window functions are, why we use it, how is it better than normal aggregate functions, how it works, where do we use it (application).
- As an example, consider a database with different possible scenarios of data manipulation that can occur, explain how window functions helps it do better than the normal functions. Talk in terms of time and memory complexity.
- While explaining these pitfalls, make sure to use the scenarios (as mentioned in the previous point), and brief what the pitfalls are, why it occurs, and how to resolve/avoid them.
- Make sure not to just state the facts, instead walk the reader through the concepts. And, keep it simple.

Feel free to include other topics that you see fit. Hope this helps.

Thanks.

**Comment by ahmadmardeni1** [comment]
Thank you v much @srishilesh 🚀 Great feedback 

This topic is approved @elphazesedah but please make sure to do what Srishilesh pointed out above.

Let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double-check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours.
