### ISSUE TITLE
Integrating Vision Framework for conspicuous analysis in iOS

### ISSUE THREAD

**Issue by RoseKarose** [section-engineering-education/engineering-education#2918]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Integrating Vision Framework for conspicuous analysis in iOS

### Introduction paragraph (2-3 paragraphs):
Vision is an Apple platform for creating iOS computer vision applications. A multitude of image analysis and  computer vision capabilities are included in Vision Framework. You can use it to do a variety of tasks - face-to-face marker detection, text recognition, recognition of barcodes, registration of images, tracking of features, object classification and identification using [CoreML](https://developer.apple.com/documentation/coreml) models.

In this tutorial, we'll develop an app that filters the camera feed from an iOS device using conspicuous analysis to produce a highlight effect around attractive items. Conspicuous analysis uses algorithms to evaluate what in an image is of interest or significance to humans. Most importantly, figuring out what it is about a photograph that attracts someone's attention.

### Key takeaways: 

In this article, you will learn how to:
- Use the camera APIs introduced in iOS 13.
- Create requests to perform Conspicuous/salience analysis.
- Use the observations returned to generate a heat map.
- Filter a video stream using the heat maps as an input.

### References: 
N/A

**Comment by hectorkambow** [comment]
@RoseKarose 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by lalith1403** [comment]
Hi @RoseKarose 
This sounds like a helpful article. However, let's be sure it adds value beyond what is in the official docs and covered in other blog sites. Also, ensure it does not conflict with any other already published content.
**Topic approved**

**Comment by ahmadmardeni1** [comment]
Closing this topic to avoid a backlog queue. Can be reopened👍
