### ISSUE TITLE
How to build an Android Wear-OS Navigation App

### ISSUE THREAD

**Issue by Antonymuriuki** [section-engineering-education/engineering-education#2919]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

### Proposed title of article
How to build an Android Wear-OS Navigation App.

### Introduction paragraph (2-3 paragraphs):
When it comes to mobile app development, we usually focus on only two types of devices: smartphones and tablets. And we usually come across the proposed templates for other types of devices every time we start a new Android Studio project. Have you ever asked yourself how you can develop apps for smart watches? 

Due to the different usage scenarios and smaller screens, smart watches differ from mobile phones in terms of design and interaction. The layout is more concise and rely more on sliding gestures to operate. In this tutorial, you'll learn how to create a navigation app for a wearable device that runs on Wear OS (powered by Android).

### Key takeaways: 
By the end of this tutorial, the reader will:
1. Understand the importance and use cases of Wear OS.
2. Learn the basics of Wear OS development.
3. Create a dynamic UI particularly for the small screen category.
4. Implement Wear APIs in a Navigation app.

### References: 
N/A

**Comment by hectorkambow** [comment]
@Antonymuriuki 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by LinusMuema** [comment]
Hi @Antonymuriuki 
This sounds like a really great article.
Please let's be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Also, ensure it does not conflict with any other already published content.
topic approved

**Comment by ahmadmardeni1** [comment]
Closing this topic to avoid a backlog queue. Can be reopened👍
