### ISSUE TITLE
Cybersecurity and Cloud Computing

### ISSUE THREAD

**Issue by julie-techie** [section-engineering-education/engineering-education#2927]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Cybersecurity and Cloud Computing

### Introduction paragraph (2-3 paragraphs):
Every digital aspect comes with a security risk if not handled properly. With billions of people using online and digital technologies worldwide, there are adequate opportunities for hackers to break the security wall.

Cybersecurity in cloud computing environments is a multi-faceted endeavor, involving best practices in user access and privileges, hardware and software security, virtualization, firewalls, and other processes used to protect data and infrastructure. This article aims to discuss cloud computing security.

### Key takeaways: 
1. Overview of cloud computing security
2. Importance of cloud security
3. Cyber crime and cloud computing
4. Challenges of cloud computing security
5. Cloud Security best practices

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@julie-techie 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by louisefindlay23** [comment]
@ahmadmardeni1, would you be able to review this topic suggestion since you have knowledge about cyber security?

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @julie-techie 
We are looking for programmer-centric concepts explained in fun and intuitive ways.

Please feel free to suggest an alternate topic to explore. 🚀
