### ISSUE TITLE
getting started with constructor Overloading in C# 

### ISSUE THREAD

**Issue by mercie-nyakio** [section-engineering-education/engineering-education#2928]
### Proposed title of article
getting started with constructor Overloading in C# 

### Introduction paragraph (2-3 paragraphs):
When more than one constructor with the same name is defined in the same class, they are called overloaded, if the parameters are different for each constructor.
Constructor overloading is the ability to redefine a Constructor in more than one form. A user can implement constructor overloading by defining two or more constructors in a class sharing the same name. C# can distinguish the constructors with different signatures. i.e. the constructor must have the same name but with different parameters list.

### Key takeaways: 
By the end of this article, the reader will understand: 
1. what constructor overloading is.
2. overloading by changing the Data types of the parameters.
3. overloading by changing the number of the parameters.
4. overloading by changing the Order of the parameters.
5. overloading by Invoking an Overloaded Constructor using `this` keyword.
6. overloading by Overloading of Copy Constructor.

### References: 
N/A

**Comment by hectorkambow** [comment]
@mercie-nyakio 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @mercie-nyakio 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
