### ISSUE TITLE
Getting started with packet tracer

### ISSUE THREAD

**Issue by achiengrhoda** [section-engineering-education/engineering-education#2929]
### Introduction paragraph (2-3 paragraphs):
A packet  tracers is a network simulator. This means  it can be used to imitate  a live networking environment. This imitation is key especially in a learning environment where a learner is just getting started with network developments. There are many types of  network simulators and Packet tracer is one of them.

In this article I will be introducing what a packet tracers is, discussing the processes involved in its installation and finally I will discuss  its  functionality at  length.
### Key takeaways: 
1. The reader will be able to understand what a packet tracer is and why it is needed in networking.
2. The reader will be able to  get the installation process of a packet trace
3. The reader will learn how to use a packet tracer in network simulation.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@achiengrhoda 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by hectorkambow** [comment]
@achiengrhoda 

Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites. (beyond a basic explanation - it would be best to referenece your favorite intro article and build upon it).
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by NdoloBonface** [comment]
Can I help please?
