### ISSUE TITLE
Cloud Management in Cloud Computing

### ISSUE THREAD

**Issue by kwennB** [section-engineering-education/engineering-education#2932]
### Introduction
Cloud management is the medium that allows administration control of technologies and software. Cloud management cares for products and services. 
Cloud management is centralized. It manages resources, assets, data storage, applications, etc.

### Key Takeaways
What cloud management is.
Cloud management designs (platform).
Cloud management challenges.
Functionalities a good cloud manager should have.

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@kwennB 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by LinusMuema** [comment]
Hi @kwennB 
This sounds like a really helpful topic. Just make sure your content is original and does not conflict with any material already available on section.

topic approved :rocket:

**Comment by kwennB** [comment]
Thank you! @LinusMuema
