### ISSUE TITLE
Monitoring a Microsoft SQL Server database using Solar Winds Database Performance Analyzer

### ISSUE THREAD

**Issue by ruphus-muita** [section-engineering-education/engineering-education#2938]
### Proposed title of article
Database monitoring

### Introduction (2-3 paragraphs)
 This article will explain what database monitoring is and why it should be implemented in the network.
It will also provide insight into what parameters should be monitored for optimum service. The article will aim at enlightening the reader on how to monitor a Microsoft SQL Server database using Solar Winds Database Performance Analyzer (Self-Managed). 

### Key takeaways: 
1. How to deploy the Database performance analyzer in Windows.
2. How to register the database instances for monitoring.
3. Best practice for the installation and configuration process.

### References: 
Not Applicable
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@ruphus-muita 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by LinusMuema** [comment]
Hi @ruphus-muita 
This sounds like a good article. However, I have some concerns with the suggestion. It sounds a bit unclear. You can provide more info on the article like what kinds of databases are you monitoring? any tools you will use for the purpose?

The introduction paragraph seems a bit short hence the uncertainty. 

Could you please check on that...

**Comment by ruphus-muita** [comment]
Hi @LinusMuema To narrow the topic down, The article will aim at enlightening the reader on how to monitor a Microsoft SQL Server database using Solar Winds Database Performance Analyzer (Self-Managed). Hence the article will provide an overview of the following: 
1. How to deploy the Database performance analyzer in Windows.
2. How to register the database instances for monitoring.
3. Best practice for the installation and configuration process.
What are your thoughts?

**Comment by LinusMuema** [comment]
You can update the initial suggestion. There is an option to do that. 
Just update it and ping me when you're done

**Comment by ruphus-muita** [comment]
@LinusMuema I have updated the original suggestion.

**Comment by LinusMuema** [comment]
Okay @ruphus-muita 
Make sure you add value to your article and it is original. This is by ensuring your content covers more than what is available in official docs and other blog sites.

topic approved. 🚀

**Comment by ruphus-muita** [comment]
@LinusMuema Noted
