### ISSUE TITLE
Thread pool in node.js

### ISSUE THREAD

**Issue by HARITJOSHI1** [section-engineering-education/engineering-education#2941]
### Proposed title of article
Thread pool in node.js

### Introduction paragraph (2-3 paragraphs):

Node.js is the most widely used framework by all big mnc 's and it has made life a lot easier when working on complex backend for a project. My article will take a deeper dive and explain the readers about the concept of thread pool inside out which is a key actor in node.js event loop architecture. 

My article will cover will give an in depth information how thread pool actually works and how to use it so that readers can take real advantage of it and even can use it in their own project. 

### Key takeaways: 
1. Readers will understand the in depth idea of thread pool and how it works. 
2. Readers will understand the advantage and uses of it with some examples. 
3. Readers will understand the concept of event driven architecture and how thread pool blends into it. 
4. Readers will get good understanding of management of thread pool. 

### References: 
N/A

**Comment by hectorkambow** [comment]
@HARITJOSHI1 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by hectorkambow** [comment]
@HARITJOSHI1 
Thank you for suggesting another topic. 

Seems like a very cool topic - but regarding _Node.js we have more than enough currently in our EngEd library as we did a big push the last few months and are currently not accepting any more Node.js articles to publish for the time being._

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by HARITJOSHI1** [comment]
> @HARITJOSHI1 
> Thank you for suggesting another topic. 
> 
> Seems like a very cool topic - but regarding _Node.js we have more than enough currently in our EngEd library as we did a big push the last few months and are currently not accepting any more Node.js articles to publish for the time being._
> 
> Please feel free to suggest an alternate topic to explore. 🚀

Ohh okay
