### ISSUE TITLE
Data Access With ADO.NET In Micro Focus Visual COBOL

### ISSUE THREAD

**Issue by Amoh-writer** [section-engineering-education/engineering-education#2946]
### Proposed title of article
	
Data Access With ADO.NET In Micro Focus Visual COBOL

### Introduction paragraph (2-3 paragraphs):
ADO is the acronym for ActiveX Data Object and is based on Microsoft technology. Hence, ADO.NET which is the next evolutionary step in data access technology. Employing the aforementioned ADO technology, ADO.NET expands this by incorporating XML into a standard model to not only the relational data models but also the text based XML data.

This will be a multi-part article dealing with data access in the Microsoft .NET arena, using ADO. We will begin with a bit of history of ADO, what it is, why it's so important and finally how to utilize it in a COBOL environment. This article will provide a brief history of the data access as well as provide the basic flow for using ADO to access the data. 

### Key takeaways: 
By the end of this article, the reader will understand:
1. what ADO and ADO.NET are.
2. Basic ADO flow.
- preparation.
- Create a connection to the data object.
- Create a command for the data object to act upon.
- Read the data returned by the data object.
3. what wrap up is.

### References: 
N/A

**Comment by hectorkambow** [comment]
@Amoh-writer Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites, and to create a unique project using the concepts above. @Amoh-writer

Please be sure to double-check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by Amoh-writer** [comment]
Will do, thanks!

0713976067
