### ISSUE TITLE
How to Create a machine learning model using Turi Create 

### ISSUE THREAD

**Issue by willyngashu** [section-engineering-education/engineering-education#2947]
### Proposed title of article
How to Create a machine learning model using Turi Create 

### Introduction paragraph (2-3 paragraphs):
Turi Create is an open-source toolset for creating Core ML models, for tasks such as image classification, object detection, style transfers, recommendations. Turi Create simplifies the development of custom machine learning models. Turi Create was made by Apple and is a powerful tool for machine learning.
In this tutorial, we will use Turi Create to show us how to read CSV files, how to create data frames, and basic data manipulation. Eventually, we will create a machine learning model using this package, this will teach us a lot about the Turi Create library.
Benefits of using Turi create:
  - Easy-to-use: Focus on tasks instead of algorithms
 - Visual: Built-in, streaming visualizations to explore your data
 - Flexible: Supports text, images, audio, video, and sensor data
 - Fast and Scalable: Work with large datasets on a single machine 
### Key takeaways: 
 - How to install Turi Create into our machines.
 - How to create data frames.
 - Data manipulation using turi create.
 - Data Preprocessing using turi create.
 - Building a Classification Model.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@willyngashu 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by louisefindlay23** [comment]
Could you take a look at this topic suggestion, @ahmadmardeni1 if you have time since you have experience with ML?

**Comment by ahmadmardeni1** [comment]
Seems like a very interesting topic. I didn't use it before - but it can be a great addition to our program.
You can approve it @louisefindlay23

**Comment by louisefindlay23** [comment]
Thanks for looking it over, @ahmadmardeni1. Topic approved, @willyngashu.
