### ISSUE TITLE
Complete Guide on using Sequelize basic and advanced features.

### ISSUE THREAD

**Issue by Josh4324** [section-engineering-education/engineering-education#2949]
### Proposed title of article
Complete Guide on using Sequelize basic and advanced features.

### Introduction paragraph (2-3 paragraphs):
Sequelize is a JavaScript library that manages database. It supports all the popular databases such as PostgreSQL, MySQL, SQLite and MSSQL. This kind of package is known as an Object Relation Mapper, ORM’s are used to convert object relational syntax to database schema. Sequelize is used with NodeJS.
Sequelize only support relational databases, database like mongo DB or other NoSQL databases are not supported.  Sequelize supports solid transaction, eager and lazy loading, relations, read replication and other cool features.

### Key takeaways: 

- How to install sequelize
- How to install drivers associated with the different database
- Connecting to the database and testing the connection
- How to use Sequelize CLI
- Model Querying (Inserting, Updating, Deleting)
- Associations (One to One, One to Many, Many to Many).

### References: 
[Manual | Sequelize](https://sequelize.org/master/index.html)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Josh4324 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by LinusMuema** [comment]
Hi @Josh4324 
This is a great idea for an article. Let's please be sure it adds value beyond what is in the official docs and what is covered in other blog sites.
Ensure it does not conflict with any other already published content.
topic approved
