### ISSUE TITLE
Using React and Clipboard API to Implementing copy-to-clipboard

### ISSUE THREAD

**Issue by marienjus** [section-engineering-education/engineering-education#2950]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Using React and Clipboard API to Implementing copy-to-clipboard

### Introduction paragraph (2-3 paragraphs):
One of the common things developers do is copy-pasting in the clipboard. The clipboard is a special location on the computer, phone, and tablet memory that temporarily stores cut or copied text or other data. Once something is stored in the clipboard, it can be pasted to a new location. The clipboard holds its information until you cut or copy something else, or log out of the computer. JavaScript as the language of the browser has this feature available via an API. The Clipboard API provides the ability to respond to clipboard commands (cut, copy, and paste) as well as to asynchronously read from and write to the system clipboard. This is the feature that we will implement in React web applications.

### Key takeaways: 
1. What is JavaScript Clipboard API
2. Setting up Clipboard API in React
3. Building the React application

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@marienjus Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by louisefindlay23** [comment]
Hi, @zolomohan. It would be great if you give this topic suggestion a quick look to determine how much value it brings? 

I've not used React before (hence pinging you) but there seems to be a few similar articles such as [LogRocket](https://blog.logrocket.com/implementing-copy-to-clipboard-in-react-with-clipboard-api/) and [Medium](https://feargalwalsh.medium.com/copying-to-the-clipboard-in-react-81bb956963ec) but I know that React is very big so the author may cover a specific part of React that makes this article unique?

cc - @marienjus

**Comment by zolomohan** [comment]
@marienjus can you go through the articles that @louisefindlay23 pointed out and let me know how your article is going to be different?

**Comment by marienjus** [comment]
Logrocket seems to be using the same Library I am planning to integrate. My version is more advanced than that in Medium though. Maybe I can dive deeper into this Library more than Logrocket and build a better UI version? .

**Comment by zolomohan** [comment]
- When it comes to tutorial articles, the UI doesn't matter. It's important to teach the reader how to implement the functionality that you are discussing in an easy way. Building a good UI requires CSS code and it will clutter your article. TLDR; It's unnecessary.
- The Clipboard API is not a library, it's just a WebAPI. It's very simple. The MDN docs are excellent for it.

@louisefindlay23 I don't think this topic will provide a lot of value since a lot of articles and good documentation are available for this already.

**Comment by louisefindlay23** [comment]
Thanks, @zolomohan. @marienjus is there another topic you'd like to consider instead?

**Comment by marienjus** [comment]
Hey, I've been enjoying using React and Zustand for state management and I would like to write something about it. A tutorial of the UI state management library. Can I proceed?
