### ISSUE TITLE
Understanding and Working with JavaScript Cookies

### ISSUE THREAD

**Issue by fabulousDesigns** [section-engineering-education/engineering-education#2951]
### Proposed title of article
Understanding and Working with JavaScript Cookies

### Introduction paragraph (2-3 paragraphs):
  Many are the times users vist to a site and they are presented with a cookie preference window that obtains their cookie preference,including any consent they provide to certain non-essential cookies.
Basically a cookie is a small text file that stores a small amount of data (almost 4KB) on the user's pc. 
They typically track information such as user preferences that the site can retrieve to personalize a webpage when a user visits the website next time.
 Cookies can be managed right from the users browser.We will create, read, update and delete cookies using javascript

### Key takeaways: 
1.	Create browser  cookies
2.	Read cookies from a browser
3.	Update cookies created cookies
4.	Delete cookies

### References: 
N/A

**Comment by hectorkambow** [comment]
@fabulousDesigns 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by louisefindlay23** [comment]
Hi, @fabulousDesigns. Thanks for submitting a topic suggestion. 

Since we focus on unique and original content, can you tell me how your article will differ from similar JavaScript cookie articles such as this [TutorialsPoint](https://www.tutorialspoint.com/javascript/javascript_cookies.htm) post?

Thanks,
Louise - Content Moderator

**Comment by fabulousDesigns** [comment]
Hi, @louisefindlay23 in my article i will try to be on point and my code snippets will be light for a reader to understand and implement as opposed to the site you had suggested

**Comment by louisefindlay23** [comment]
Thanks, @fabulousDesigns. Topic approved. Please ensure your article is in-depth to provide value to our readers.

**Comment by fabulousDesigns** [comment]
Thanks, @louisefindlay23
