### ISSUE TITLE
An Introduction to Blockchain Architecture

### ISSUE THREAD

**Issue by corpsgeek** [section-engineering-education/engineering-education#2952]
### Proposed title of article
An Introduction to Blockchain

### Introduction paragraph (2-3 paragraphs):
Blockchain is a revolutionary technology, however, little knowledge about how distinct technological components come together as one that makes blockchain a blockchain. This article will illustrate practically what blockchain is and the components around it.

### Key takeaways: 
-What is blockchain
- Realms of Blockchain
-Understanding SHA256 Hash
- Distributed P2P Network
- A Basic Introduction on How Mining Works
- Understanding Consensus Protocols
- Proof of Work

### References: 
N/A

**Comment by hectorkambow** [comment]
@corpsgeek 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by corpsgeek** [comment]
alright.

**Comment by LinusMuema** [comment]
@katungi 
could you give this issue a review? You were good in machine learning last I checked.
If not you can ping someone in the peer reviewers community to check it out. :rocket:

**Comment by katungi** [comment]
Yeah, I will gladly take the review. I am well versed with Blockchain technology. I will get on with the review asap!

**Comment by corpsgeek** [comment]
@katungi i assume this topic has been approved??

**Comment by katungi** [comment]
This is a very interesting topic. Don't be afraid to go deep into the technical content. Topic approved🥳

**Comment by corpsgeek** [comment]
Yeah I did trust me @katungi 😎
