### ISSUE TITLE
Introduction to Node.js

### ISSUE THREAD

**Issue by amosnjoro** [section-engineering-education/engineering-education#2954]
### Introduction paragraph (2-3 paragraphs):
Node.js is an open-source and cross-platform JavaScript runtime environment. It is a popular tool for almost any kind of project!
Node.js runs the V8 JavaScript engine, the core of Google Chrome, outside of the browser. This allows Node.js to be very performant.
A Node.js app runs in a single process, without creating a new thread for every request. Node.js provides a set of asynchronous I/O primitives in its standard library that prevent JavaScript code from blocking and generally, libraries in Node.js are written using non-blocking paradigms, making blocking behavior the exception rather than the norm.
In this article we shall deeply look on how install Node.js into your machine and how Node.js works.
### Key takeaways: 
1. Installing Node.js
2. The V8 JavaScript engine
3. Running Node.js scripts from the command line
### References: 
N/A

**Comment by hectorkambow** [comment]
👋  @amosnjoro 

Seems like a very cool topic - but regarding Node.js we have more than enough currently in our EngEd library as we did a big push the last few months and are currently not accepting any more Node.js articles to publish for the time being. 

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by amosnjoro** [comment]
Thanks @hectorkambow
