### ISSUE TITLE
Working With JavaScript Timers

### ISSUE THREAD

**Issue by fabulousDesigns** [section-engineering-education/engineering-education#2959]
### Proposed title of article
Working With Javascript Timers

### Introduction paragraph (2-3 paragraphs):
A timer is a function that enables execition of a function in a particular time.Using timers you can delay the execution of code so that it does not get done at the exact moment an event is triggered or the page is loaded.
 For example, you can use timers to change the advertisement banners on your website at regular intervals, or display a real-time clock, etc. There are two timer functions in JavaScript:.setTimeout() and setInterval().
### Key takeaways: 
1.importance of javascript timers
2.setTimeout() function
3.setInterval() function
4.Application of Javascript Timers

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. @fabulousDesigns

**Comment by louisefindlay23** [comment]
@fabulousDesigns, you are only allowed one topic suggestion at a time to be considered. Closing in favour of #2951. 

You can reopen this once that topic suggestion has been written and published.
