### ISSUE TITLE
Implementing Dark Mode Using Tailwind CSS.

### ISSUE THREAD

**Issue by M0nicah** [section-engineering-education/engineering-education#2960]
### Proposed title of article
Implementing Dark Mode using Tailwind CSS.

### Introduction paragraph (2-3 paragraphs):
Dark mode/theme is gradually becoming one of the most used features on applications and operating systems. It lets a user change the color theme of an application to black or a color close to black. The applications and websites include a toggle switch/button that changes the theme only on the page/app.
In this tutorial, we will implement dark mode on a page using Tailwind CSS. We will create a small webpage using Tailwind, build a switch then add some JavaScript for it to work.

### Key takeaways: 
1.  Reader will learn how to make their pages responsive to the color scheme they like.
2.  Reader will be able to understand how adding a feature like Dark mode will improve the quality of the website.
3.  Reader will understand more about Tailwind CSS and the Dark Mode feature. 
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. @M0nicah

**Comment by LinusMuema** [comment]
Hi @M0nicah 
This sounds like a helpful topic. Please ensure your content is original and does not match what is available on the official documentation or other blog websites. Also, check that it doesn't conflict with content already available in section. 

topic approved :rocket:
