### ISSUE TITLE
Prototype vs JavaScript Class

### ISSUE THREAD

**Issue by owinowendy** [section-engineering-education/engineering-education#2962]
### Proposed title of article
Prototype vs JavaScript Class

### Introduction paragraph (2-3 paragraphs):
JavaScript classes, introduced in ECMAScript 2015, are primarily syntactical sugar over JavaScript's existing prototype-based inheritance.
The most important difference between class- and prototype-based inheritance is that a class defines a type which can be instantiated at runtime, whereas a prototype is itself an object instance.

A child of an ES6 class is another type definition which extends the parent with new properties and methods, which in turn can be instantiated at runtime. A child of a prototype is another object instance which delegates to the parent any properties that aren’t implemented on the child.

In this tutorial we dive into JavaScript to understand key differentiators between use of a Class and a Prototype - plus the impact each has on Lightning Web Components.

### Key takeaways: 
1.The Prototype Concept in JavaScript
2.The JavaScript Class
3.JavaScript Class v Prototype
4.Impact on Lightning Web Components

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @owinowendy

**Comment by owinowendy** [comment]
@ahmadmardeni1 updates on this?

**Comment by hectorkambow** [comment]
@owinowendy 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
