### ISSUE TITLE
Introduction to Grafana

### ISSUE THREAD

**Issue by HARITJOSHI1** [section-engineering-education/engineering-education#2963]
### Proposed title of the article
Introduction to Grafana

### Introduction paragraph (2-3 paragraphs):
ELK Stack is a modern and powerful tool that tackles the monitoring challenges in modern application and IT infrastructure.
It helps by providing users with a powerful platform that collects and processes data from multiple data sources, stores that data in one centralized data store that can scale as data grows, and provides a set of tools to analyze the data. One of the powerful tool is Grafana which gained a lot of popularity. My article will give in-depth clarity about what is Grafana, why it is used, its advantages, and how to use it with of course a nice background of ELK stack.

### Key takeaways: 
1. Readers will be able to understand what ELK stack and Grafana really are.
2. Readers will be able to understand its advantages and how big enterprises use it.
3. Services offered by Grafana.

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @HARITJOSHI1

**Comment by HARITJOSHI1** [comment]
@ahmadmardeni1 so what's the status?

**Comment by hectorkambow** [comment]
@HARITJOSHI1 

This seems like a very helpful topic - as Grafana is an extremely useful tool to learn. 

Although we are looking to create and curate topics that go above and beyond the official documentation or what can be found elsewhere online. 

Could you please expand upon how your content will differ from what is already available through the Grafana website and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics. 

Thank you - an alternate path might be to create a unique project using a Grafana for the audience to follow along ?

**Comment by HARITJOSHI1** [comment]
> @HARITJOSHI1 
> 
> This seems like a very helpful topic - as Grafana is an extremely useful tool to learn. 
> 
> Although we are looking to create and curate topics that go above and beyond the official documentation or what can be found elsewhere online. 
> 
> Could you please expand upon how your content will differ from what is already available through the Grafana website and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics. 
> 
> Thank you - an alternate path might be to create a unique project using a Grafana for the audience to follow along ?
> 

So is my topic approved?

**Comment by hectorkambow** [comment]
@HARITJOSHI1 

Not yet - as we are trying to go beyond intro type topics.

It may be more valuable to the reader to go above any introduction (it would be helpful to find one online that you'd like to reference) as we are trying to distance ourselves from basic topics (or specifically topics that are widely covered elsewhere). 

In order to approve the topic - it would have to go beyond a basic intro topic 👍

**Comment by hectorkambow** [comment]
I think there is substance we can flush out on what you mentioned above with the ELK stacks - the introductory parts can be pointed out in other articles as references - which would allow you to go more in depth on core Grafana topics 👍 @HARITJOSHI1

**Comment by HARITJOSHI1** [comment]
> @HARITJOSHI1 
> 
> This seems like a very helpful topic - as Grafana is an extremely useful tool to learn. 
> 
> Although we are looking to create and curate topics that go above and beyond the official documentation or what can be found elsewhere online. 
> 
> Could you please expand upon how your content will differ from what is already available through the Grafana website and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics. 
> 
> Thank you - an alternate path might be to create a unique project using a Grafana for the audience to follow along ?
> 

Okay then I will add a brief intro for grafana and give turn this article to advance metrics visualization and metrics alerting in Grafana with ISTIO.

**Comment by hectorkambow** [comment]
Sounds great - approved 💯

**Comment by HARITJOSHI1** [comment]
> @HARITJOSHI1
> Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. +1

@hectorkambow can you reopen this issue?

**Comment by WanjaMIKE** [comment]
It seems this PR is not yet ready.
