### ISSUE TITLE
Statefull vs. Stateless Architectures

### ISSUE THREAD

**Issue by Su-sid** [section-engineering-education/engineering-education#2966]
### Proposed title of the article
Statefull vs. Stateless Architectures

### Introduction paragraph (2-3 paragraphs):
Networks protocols control how data is transferred between different devices in a network. However, you should understand that networking protocols are divided into two: stateful and stateless protocols. Additionally, whether something is stateful or stateless depends on how long the state of interaction with it is being recorded and how that information needs to be stored. 

### Key takeaways: 
- Definition and basic history of stateful and stateless architectures
- The various protocols that utilize the two architectures
- The differences between the two architectures 
- Some of the advantages of each of the architectures 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Thank you. @Su-sid

**Comment by LinusMuema** [comment]
Hi @Su-sid 
Thank you again for the article submission. I think the article will be quite helpful.
Please make sure to add more value than the available articles on other blogs as well as content from section.

topic approved :rocket:

**Comment by Su-sid** [comment]
@hectorkambow Kindly reopen this topic.

**Comment by Su-sid** [comment]
@LinusMuema  Kindly reopen this topic.

**Comment by Su-sid** [comment]
@hectorkambow  Kindly reopen this topic.

**Comment by WanjaMIKE** [comment]
closed #2966 via #5284
