### ISSUE TITLE
Understanding 802.11(Wi-Fi) Standards

### ISSUE THREAD

**Issue by lin-chez** [section-engineering-education/engineering-education#2967]
### Proposed title of the article
Understanding 802.11 Standards

### Introduction paragraph (2-3 paragraphs):
802.11 based networks, also known as Wi-Fi networks, have progressively developed into the most common types of networks available and widely used in the modern world. It is common for you to connect to the internet through a wireless access point available in your office, bedroom, or favourite fun spot. Thus, understanding the history, types, standards and characteristics of wifi networks is fundamental in remaining up to date with modern technologies.

### Key takeaways: 
- Definition and history of 802.11 networks 
- The various types of 802.11 standards 
- Key characteristics and features of each type of 802.11 standards

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @lin-chez

**Comment by hectorkambow** [comment]
Good afternoon @lin-chez and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

Please feel free to suggest an alternate topic to explore. 🚀
