### ISSUE TITLE
How to migrate an on-prem application to serverless?

### ISSUE THREAD

**Issue by ogoti-lilian** [section-engineering-education/engineering-education#2968]
### Proposed title of article
How to migrate an on-prem application to serverless?

### Introduction paragraph:
Serverless is becoming popular in recent times. Developers and companies are adopting the approach to deliver business value using the public cloud. There are many articles covering the serverless architecture out there, but few really covers about the subject.
In this article, I will use a practical example, an Online Recruitment Portal which is hosted on-prem and cover the steps on how to migrate the web application to serverless.

### Key takeaways: 
At the end of the article, the reader will be able to understand:
- the problems faced with on-prem applications and why opt for seeverless way
- the journey to serverless solution and the migration approach from on-prem to serverless using practical example
- challenges likely to faced during development and delivery phase

### References: 
N?A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @ogoti-lilian

**Comment by hectorkambow** [comment]
@ogoti-lilian 
good topic - approved. 
One important note: Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)

Lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours.
