### ISSUE TITLE
Why should Healthcare industries adopt cloud computing?

### ISSUE THREAD

**Issue by martha-ngugi** [section-engineering-education/engineering-education#2969]
### Proposed title of article
Why should Healthcare industries adopt cloud computing?

### Introduction paragraph:
Cloud computing refers to the delivery of computing services like storage, servers, analytics, and software over the internet connection. It is not advisable for an organization to rush into cloud computing without understanding the specifics of its industry since most cloud vendors may not understand.
This article will look at different cloud deployment models and recognize the risks involved with adopting cloud computing in healthcare, also it will provide guidelines on how to get started.

### Key takeaways: 
At the end of this article the learner will be able to understand:
- what is cloud computing in relation to healthcare and how it is used
- the deployment models of cloud computing in healthcare
- the cloud computing applications in healthcare
- the benefits of cloud computing in healthcare
- the risks involved with cloud computing in healthcare and possible solutions to curb them

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @martha-ngugi

**Comment by hectorkambow** [comment]
@martha-ngugi 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by martha-ngugi** [comment]
@hectorkambow Thank you for the topic approval. Is it important to have a 'topic approved' label or I can continue the way it is

**Comment by ahmadmardeni1** [comment]
Done @martha-ngugi

**Comment by WanjaMIKE** [comment]
closed #2969 via #3215
