### ISSUE TITLE
Getting hands-on on a MicroProfile project

### ISSUE THREAD

**Issue by justusmbuvi** [section-engineering-education/engineering-education#2978]
### Proposed title of the article

Getting hands-on on a MicroProfile project

### Introduction paragraph (2-3 paragraphs)

MicroProfile specifies a collection of Java EE (Enterprise) technologies and APIs which in consolidation from a core baseline microservice that aims to deliver application portability across multiple MicroProfile runtimes.
It has been attracting attention from developers since this Java EE implementation does not take up much time in server booting and code run time as it did before when using former versions of Java EE. This is due to the continuous agile improvement of individual Java Specification Requests (JARs) that make up Java Enterprise (EE).

At the edge of this course, we will learn how MicroProfiles work and how they are used and how to use them. We shall also get hands-on one on MicroProfile Projects.

### Key takeaways

Coming to the tip of the article, we shall have the following to take with us:

- What is MicroProfile
- MicroProfile prerequisites
- Advantages and trade-offs of MicroProfile framework
- Creation of a MicroProfile application using different methods or tools such as from the [https://start.microprofile.io/](https://start.microprofile.io/) website, using Visual Studio Code and IntelliJ.
- MicroProfile project structure
- MicroProfile vs Spring Boot

### Pre-requisites

Some basics required for easy follow-up on this article include:

- A modern IDE that supports Java frameworks installed on your machine. This may either be Visual Studio Code or IntelliJ or any other. We shall focus on the two in this article.
- A stable internet connection for dependency downloads.
- **JDK 11+** of any distribution installed. This is because MicroProfile is not supported with lower versions than 11.
- Gradle or Apache Maven 3.8.1+ installed.
- Java programming skills (It will be a bit hard for a beginner to understand or catch up)

### References

[microprofile-3-0-support-comes-to-helidon](https://medium.com/helidon/microprofile-3-0-support-comes-to-helidon-f72ba752b42f)

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @justusmbuvi

**Comment by hectorkambow** [comment]
@justusmbuvi 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
