### ISSUE TITLE
Using Azure Functions and C# to Create Serverless APIs

### ISSUE THREAD

**Issue by wanjadeno** [section-engineering-education/engineering-education#2979]
### Proposed title of the article*
Using Azure Functions and C# to Create Serverless APIs

### Introduction paragraph (2-3 paragraphs):
Azure Functions is a serverless compute tool that makes it simple to run short amounts of code (or "functions") in the cloud. It has the potential to make our development even more fruitful. You will write only the code you need for the task at hand, without worrying about the rest of the program or the infrastructure required to run it.

In this tutorial, I will show the reader how to use Azure Functions to develop HTTP Trigger APIs utilizing Entity Framework Core Layer as an ORM and C# code, as well as a SQL Database for data storage.

### Key takeaways: 
1. Setting up the Azure Function
2. Database Schema and Entity Model
3. Setting up the Connection with SQL Database by using EF Core
4. Initialize Dependency Injection
5. Injecting the DbContext into a function
6. Implementing Functions
7. Testing the APIs using Postman

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @wanjadeno

**Comment by hectorkambow** [comment]
@wanjadeno 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
