### ISSUE TITLE
Introduction to Udoo x86 II Ultra 

### ISSUE THREAD

**Issue by sheldonaswani** [section-engineering-education/engineering-education#2982]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Introduction to Udoo x86 II Ultra 

### Introduction paragraph (2-3 paragraphs):
This article will describe the built in architecture and processing power of  Udoo x86 II Ultra. It will seek to highlight and clarify the different capabilities of Udoo X86 II Ultra and why its way far much better than most Session Border Controllers (SBC). 

This article among others important issues is majorly tailored to explain the advanced features that ensures Ultra X86 II ultra is capable of running software applications that are usually run on a PC on a daily basis.

### Key takeaways: 
1. Understand the best Session Border Controller (SBC) to use?
2. Understand the built in capabilities of Udoo ultra II X86?
3. Understand the decency and wide range of features that Udoo Ultra II x86 presents in order to make an informed decision when acquiring a Session Border Controller (SBC).

### References: 
Not applicable.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @sheldonaswani

**Comment by sheldonaswani** [comment]
Good evening, Thank you for this update.
kind regards.

**Comment by hectorkambow** [comment]
@sheldonaswani 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
