### ISSUE TITLE
Connect-Flash, Bootstrap, Passport and Express-sessions on the go

### ISSUE THREAD

**Issue by salvador02** [section-engineering-education/engineering-education#2989]
### Proposed title of article
Connect-Flash, Bootstrap, Passport and Express-sessions on the go

### Introduction paragraph (2-3 paragraphs):
Connect-flash is node module that allows developers to send flash messages to the user interface efficiently. Connect Flash usually works with express. Express sessions are used in managing sessions in an application. Session handling is a vital part in every web application.

Demonstrating session handling requires an authentication system and that where we will need passport. Passport is an authentication middle ware used to manage authentication in an application. Bootstrap is a CSS framework used for building responsive application.

This article aims at combining all the modules and demonstrate their functionality in a single application. We will build a login system that is based on passport authentication, manage our sessions using express sessions. And show flash messages using connect-flash with bootstrap styling. 

### Key takeaways: 
1. Session handling in an authentication application
2. Styling connect-flash messages using bootstrap
3. Authentication with passport
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @salvador02

**Comment by hectorkambow** [comment]
@salvador02 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by salvador02** [comment]
Hello @hectorkambow , I have finished writing the article. Would you please open the issue.

**Comment by WanjaMIKE** [comment]
Closed #2989 via #3599
