### ISSUE TITLE
Light/Dark theme toggle with Html,CSS and JavaScript 

### ISSUE THREAD

**Issue by prince-joel** [section-engineering-education/engineering-education#2991]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article

Light/Dark theme toggle with Html CSS and JavaScript 

### Introduction paragraph (2-3 paragraphs):
In recent times most mobile apps and web app has had light and dark moods which users find exciting to use.
In this article, we will be learning how to create a light and dark mood theme using Html, CSS, and JavaScript.

### Key takeaways: 
* the user will learn how to give a website two themes (Light/Dark) using Html, CSS and JavaScript 
* The user will learn how to create a toggle
* The user will learn how to target the necessary buttons for control using JavaScript 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by jerimkaura** [comment]
Hello @prince-joel I think @phinaomondi  covered the topic here https://www.section.io/engineering-education/adding-dark-theme-to-your-site/

**Comment by prince-joel** [comment]
Hello, @jerimkaura thank you, I will suggest a new topic.
