### ISSUE TITLE
 Language-Integrated Query (LINQ) in C#

### ISSUE THREAD

**Issue by amosnjoro** [section-engineering-education/engineering-education#2995]
### Introduction paragraph (2-3 paragraphs):
Language-Integrated Query (LINQ) is the name for a bunch of advancements dependent on the reconciliation of inquiry capacities straightforwardly into the C# language. Customarily, inquiries against information are communicated as basic strings without type checking at aggregate time or IntelliSense support.

In this article , I will deeply look on how LINQ works eg how one can generate sequences using LINQ , how to write methods that can be easily used in LINQ queries amongst others.

### Key takeaways: 
1. What is LINQ?
2.  Generating  sequences with LINQ.
3.  Writing  methods that can be easily used in LINQ queries.
4. Distinguishing  between eager and lazy evaluation.
5. Locating areas in your code where the LINQ queries might run into performance issues .

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @amosnjoro

**Comment by hectorkambow** [comment]
@amosnjoro 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
