### ISSUE TITLE
Cryptanalysis of Data after A Ransomware Attack

### ISSUE THREAD

**Issue by RuthAMare** [section-engineering-education/engineering-education#2996]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Cryptanalysis of Data after A Ransomware Attack

### Introduction paragraph (2-3 paragraphs):
This article seeks to explore the concept of cryptanalysis in light with data encrypted by a malicious actor seeking ransom to decrypt the data. The process of cryptanalysis will be clearly outlined, higlighting the various ethical ways to do the same putting into consideration the possible cryptographic algorithm that may have been employed in encrypting the data.
The possible decryption algorithms will also be identified to be able to help the reader know their possible go to option when they fall prey to a ransomware attack.

### Key takeaways: 
The learner should master the following by the end of studying this article:
1. What is cryptanalysis.
2. Tools used in Cryptanalysis.
3. Methods of encryption.
4.  Methods of decryption.

### References: 
https://www.section.io/engineering-education/cryptography-in-computer-networking/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @

**Comment by hectorkambow** [comment]
@RuthAMare 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
