### ISSUE TITLE
Hapi validation,Bcrypt Hashing and JWT in action

### ISSUE THREAD

**Issue by phinaomondi** [section-engineering-education/engineering-education#2999]
### Proposed title of article
Hapi validation,Bcryp Hashing and JWT in action

### Introduction paragraph (2-3 paragraphs):
Form validation is necessary before submitting form values to a server. You need to have a strict method that ensure you dont dump unnecessary values into your server. Hapi validation is a javascript module that provides just that with much ease.

Still on form validations, values like passwords need to not to be submitted as plain texts. Passwords should be hashed before they even pass the frontend on the application. This practice is solely meant to enhance the security of an application. Bcrypt is a module tha is used to hash & compare passwords in a server.

This article aims at illustrating the working logic of these two modules by building a basic authentication system with JWT and implemeting Hapi validation to validate the form inputs, bcrypt to hash and compare passwords and JWT to provide auth tokens for signing in and out of the application.

### Key takeaways: 
1. Hapi validation working login.
2. Encrypting passwords in the server side
3. Creating database Models with MongoDB  & Hapi

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @phinaomondi

**Comment by hectorkambow** [comment]
@phinaomondi 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
