### ISSUE TITLE
Things you need to take into consideration when building a backend software.

### ISSUE THREAD

**Issue by Josh4324** [section-engineering-education/engineering-education#3003]
### Proposed title of article
Things you need to take into consideration when building a backend software.

### Introduction paragraph (2-3 paragraphs):
Backend can be referred to the part of a software that cannot be directly interacted it, it is also know as the data access part of the Application or software. It is the middleman between the frontend and the database. The frontend application sends the request to the backend and the backend interacts with the database or equivalent technology and sends the response back to the frontend application.  
The backend task includes but not limited to storing, updating and deleting data, process frontend requests, encrypting and decrypting data and others.
### Key takeaways: 

- Authentication and Authorization
- Logging
- Throttling and Rate limiting
- Cron Jobs
- Continuous Integration
- Elastic Search
- Firewall

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @Josh4324

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 can be reopened once the first PR is merged.
