### ISSUE TITLE
Hosting a Web Server Using a Raspberry Pi

### ISSUE THREAD

**Issue by eunice-wanjiku** [section-engineering-education/engineering-education#3008]
### Proposed title of article
Hosting a webserver using raspberry pi

### Introduction paragraph (2-3 paragraphs):
This article is based on the mini computer raspberry pi.
 It aims at providing a guide on how to host a webserver using a raspberrypi.
By the end, the reader should have knowledge on how to host a fully functional webserver.

### Key takeaways: 
1. Installing needed applications on the raspberrypi.
2. Setting up the webserver.
3. Testing the server to ensure it is working as expected.

### References: 
N/A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @eunice-wanjiku

**Comment by hectorkambow** [comment]
@eunice-wanjiku 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by eunice-wanjiku** [comment]
Hi @hectorkambow , I used someone's computer to upload the solution to my issue but instead ended up pushing with his account. Kindly advise on how we can best resolve this. Thanks
