### ISSUE TITLE
Task-Tracker app with React.js using hooks

### ISSUE THREAD

**Issue by prince-joel** [section-engineering-education/engineering-education#3010]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article

Task-Tracker app with React.js using hooks

### Introduction paragraph (2-3 paragraphs):
In our everyday life we have tasks we plan on carrying out, and with the help of a Task-Tracker remembering those various tasks will be easy.
In this article, we will be learning how to build a Task-Tracker with react.js, where you can add, change and delete tasks.

### Key takeaways: 
*we will learn how to build a Task-Tracker using react.js
* we will learn how to use hooks in building our application 
* We will learn how to manage states and make use of props in our application 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @prince-joel

**Comment by hectorkambow** [comment]
@prince-joel 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@prince-joel 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by prince-joel** [comment]
Hello Ahmed, please can you reopen the topic, I have made the necessary
changes.
Thanks

**Comment by prince-joel** [comment]
Hello Ahmed
The issue you open was a wrong one. Here is the issue number to the correct
one. #5103
