### ISSUE TITLE
Integrating Node Express  Web Application With MongoDB Cloud Atlas

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#3012]
### Introduction 
This article shall be well versed on how to integrate a node and express framework web app with mongodb cloud atlas.
I shall introduce the reader to JavaScript web backend runtime and its framework. At the same time, connecting with the cloud provided by MongoDB Atlas.  

### Key takeaways: 
The following shall be the keys take away of this tutorial:
1. Getting started with NodeJS JavaScript runtime
2. Setting up of server with ExpressJS framework
3. How to use a NoSql like MongoDB database with node and express application
4. Lastly, How to integrate this created application with cloud on MongoDB Atlas server.

### References: 
https://www.mongodb.com/blog/post/quick-start-nodejs-mongodb--how-to-get-connected-to-your-database

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @Horlawhumy-dev

**Comment by Horlawhumy-dev** [comment]
Okay, thanks for the message.
