### ISSUE TITLE
How to implement Tree node classes and binary search tree in python

### ISSUE THREAD

**Issue by samtecinnovator** [section-engineering-education/engineering-education#3015]
### Proposed title of article
How to implement tree nodes classes and binary search tree

### Introduction paragraph (2-3 paragraphs):
. In this article we will learn how to construct binary search tree using nodes and references in python
  iterating  in all the keys of  the tree in order we will have a parent and child nodes.
### Key takeaways: 
1, it gives an understanding of how to insert new code in the tree
2. Implementing  retrieval of a value in a key 
3. How to handle insertion of a duplicate key during a search
 4. Deleting of a key in our binary search tree.
 5. How to traverse a binary tree using the  traversal algorithm

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @samtecinnovator

**Comment by samtecinnovator** [comment]
Thank you I am looking forward for the approval

**Comment by hectorkambow** [comment]
@samtecinnovator 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@samtecinnovator 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
