### ISSUE TITLE
Java JDBC And MySQL Connector/J

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#3025]
### Proposed title of article
Java JDBC And MySQL Connector/J

### Introduction paragraph (2-3 paragraphs):
JDBC stands for Java Database Connectivity .JDBC basically establishes a connection with a data source sends queries and update statements to the connected data source. MySQL provides connectivity for client applications developed in the Java programming language with MySQL Connector/J, a driver that implements the Java Database Connectivity (JDBC) API.

In this article, we will look at how to install java IDE and MySQL Connector/J in a beginner friendly way and use them to create a connection with data source.

### Key takeaways: 
- What's Java JDBC and MySQL Connector?
- How to install MySQL Java Connector?
- Use of MySQL Connector?
- How to connect Java JDBC with MySQL

### References: 
N/A

**Comment by hectorkambow** [comment]
@vincentkims49 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by paulodhiambo** [comment]
Hello @vincentkims49, this topic is already covered [here](https://www.section.io/engineering-education/java-jdbc/)

**Comment by vincentkims49** [comment]
Thank you @paulodhiambo
