### ISSUE TITLE
Data Preparation for Machine Learning Models in Python

### ISSUE THREAD

**Issue by FREDERICO23** [section-engineering-education/engineering-education#3027]
### Proposed title of article
Data Preparation for Machine Learning Models in Python

### Introduction paragraph (2-3 paragraphs):
Just as a motor car runs on fuel, Machine Learning algorithms run on data. For this simple yet critical part, most of the work in building Machine Learning models is data preparation. We need to provide the models with clean, precise, accurate, and relevant data. Those who maximize at the art of Data Preparation get awesomely rewarded. Be it better model performance or winning competitions, these guys are rewarded!

So what is Data Preparation? This is the process of transforming raw data to useful information so that data analysts and data scientists can run it through machine learning algorithms to uncover insights or make predictions.

In this tutorial, we will look at the data preparation process and the steps involved in preparing data.

### Key takeaways: 
By the end of this tutorial, the reader should be able to:
 - Understand the Data Preparation process
 - Importing data
 - Splitting a dataset into training and testing sets
 - Understand feature selection and feature engineering
 - Encoding categorical features
 - Handling missing data

### References: 
N/A

**Comment by hectorkambow** [comment]
@FREDERICO23 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
🤔 

Sounds like an interesting topic - let me ping our resident ML expert to see how we can draw any more substance from this particular topic @lalith1403

**Comment by lalith1403** [comment]
@FREDERICO23 Thanks for the topic suggestion. We just published an article on data pre-processing in Python. You may want to explore a niche area, such as, data pre-processing of images, text, time-series, etc. 

I will be closing this issue for now. Would love to review the new issue with updated topic. Ping me once opened. 

Cc: @hectorkambow
