### ISSUE TITLE
Controlling Android Phone on your Computer

### ISSUE THREAD

**Issue by nancymumbimaina** [section-engineering-education/engineering-education#3033]
Controlling Android Phone Using SRCPY
### Introduction paragraph (2-3 paragraphs):
SRCPY is a free and open-source screen mirroring tool that lets you operate an Android device from a desktop computer running Windows, Mac OS X, or Linux. Genymobile, which also created Genymotion, an Android emulator, is now working on the software.
The following are the steps of installing and running SRCPY  to mirror the Android phone on the computer By mirroring the Android phone on your computer ,you will be  able to control it from your computer.
### Key takeaways: 
* Mirror and control android device on Kali Linux via USB cable. 
* Mirror and control android device on  windows using TCP/IP.  
* Installing srcpy on Kali Linux.
* Remote controlling of an android phone

### References: 
N/A

**Comment by hectorkambow** [comment]
@nancymumbimaina 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@nancymumbimaina 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
closed #3033 via #3566
