### ISSUE TITLE
Building a chat application using Spring Boot, Rsocket and Angular

### ISSUE THREAD

**Issue by qawuor** [section-engineering-education/engineering-education#3040]
### Building a chat application using Spring Boot, Kotlin, Rsocket, and Angular
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

### Introduction paragraph (2-3 paragraphs):
RSocket is a binary protocol for use on byte stream transports such as TCP, WebSockets, and Aeron.  RSocket is message-based and requires some lower-level transport protocol to carry the messages. The requirements put on the transport protocol are that it should be reliable, connection-oriented, and byte stream-based, so protocols like TCP, Websockets, and Aeron can be used. If the transport protocol does not have framing (like TCP doesn't), then RSocket provides it.

In the article, I will be explaining step by step process of creating a chat application in Spring Boot(backend), Angular(frontend), and Rsocket(communication protocol).

### Key takeaways: 
1. Adding Rsocket to a Spring Boot application.
2. Creating real-time Spring Boot applications using Rsocket.

### References: 
[Rsocket Documentation](https://rsocket.io/)
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@qawuor 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@qawuor 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@qawuor 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
