### ISSUE TITLE
Sorting and Searching in Data Structures and Algorithms.

### ISSUE THREAD

**Issue by Jairusonkundi** [section-engineering-education/engineering-education#3057]
### Proposed title of article
Sorting and Searching in Data Structures and Algorithms.

### Introduction paragraph (2-3 paragraphs):
Searching is the process of identifying a certain value location in a list of values  . It determines whether or not a search key exists in the data. It is the mathematical process of locating a certain object within a set of elements.  It can be performed on either an internal or external data structure.

Sorting on the other hand is the operation or technique of ordering and rearranging groups of data in a specified order. These two data structures algorithms are very crucial when it comes to issues of data manipulation. In this article, we shall deeply look at the various searching and sorting techniques.

### Key takeaways: 
1. Definitions
2. Various searching techniques and implementation
3. Various sorting techniques and implementation

### References: 
N/A

**Comment by hectorkambow** [comment]
@Jairusonkundi 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
👀  

Is this similar to this topic #3039  

?

**Comment by Jairusonkundi** [comment]
I'm writing to  confirm that this topic is not similar to topic #3039.My
topic is searching and sorting in data structures while topic #3039 is on
searching and sorting in Matlab.

**Comment by louisefindlay23** [comment]
Thanks, @Jairusonkundi. Topic approved 🚀 Be sure to cover your outlined points in sufficient detail to provie value to our readers.
