### ISSUE TITLE
Flutter and dart

### ISSUE THREAD

**Issue by NdoloBonface** [section-engineering-education/engineering-education#3058]
**Proposed title of article**
Flutter and dart

**Introduction paragraph (2-3 paragraphs):**
Flutter is a UI development kit that was created by Google. It simplifies the development of cross-platform apps for Android, iOS, and Windows. Dart is a programming language that was developed by Google for the development of web and mobile apps. It is an object-oriented language that accepts garbage-collected data.

In this article, we will look at how to install flutter and dart in a beginner friendly way and use them to develop web and mobile apps.

**Key takeaways:**
-What's flutter and dart?
-How to install flutter and dart?
-How they are used.
-How to run flutter.

**References:**
N/A

**Comment by hectorkambow** [comment]
@NdoloBonface 

Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by paulodhiambo** [comment]
@NdoloBonface I think this is already covered in the published articles [here](https://www.section.io/engineering-education/search/?q=flutter). Choose a more focussed topic, i.e. dependency injection in Flutter (Provider package) is a good topic that's not yet covered.

**Comment by NdoloBonface** [comment]
Thank you @paulodhiambo 
I'll look at the topic right away
