### ISSUE TITLE
Why ip addresses on Android 11 Devices changes when interfaced with IOT Devices

### ISSUE THREAD

**Issue by KayTee24** [section-engineering-education/engineering-education#3062]
**Proposed title of article**
Why Ip addresses changes on android 11 Devices when interfaced with ioT Devices

**Introduction paragraph (2-3 paragraphs:)**
This will be my first article in this series. 
In this article, you will learn why network signals disconnect between android 11 devices and ioT devices.
        Of lately, some smart device industry have through their designers change the model structure to embed different sensors, processors, and memories in small-size electronic devices. Sensors are added to enhance the usability of these devices and improve the quality of experience through data collection and analysis. However, with the recency on update of big data and machine learning, sensors’ data may be processed by different techniques to infer various hidden information. The extracted information may be beneficial to device users, developers, and designers to enhance the management, operation, and development of these devices. However, the extracted information may be used to compromise the security and the privacy of humans in the world of Internet of Things (ioT). On this piece, i attempt to review the Provisioning of passpointConfiguration which is supported by the suggestion API. Before Android 11, provisioning a PasspointConfiguration required the use of the addOrUpdatePasspointConfiguration() API.
The framework enforces security requirements on TLS-based Enterprise suggestions (EAP-TLS, EAP-TTLS, and EAP-PEAP); suggestions to such networks must set a Root CA certificate and a server domain name.

**Key takeaways:**

You will learn how to;

- Why they is always a disconnection in signal during information transmission (i.e. why IP address changes after a successful connection within a short time interval between the android 11 device and the ioT Devices).
- Some common effects when the disconnection in signal occurs.
- How can this challenge be resolved.

**Reference :**
N/A

**Comment by KayTee24** [comment]
Of lately, some smart device industry have through their designers change the model structure to embed different sensors, processors, and memories in small-size electronic devices. Sensors are added to enhance the usability of these devices and improve the quality of experience through data collection and analysis. However, with the recency on update of big data and machine learning, sensors’ data may be processed by different techniques to infer various hidden information. The extracted information may be beneficial to device users, developers, and designers to enhance the management, operation, and development of these devices. However, the extracted information may be used to compromise the security and the privacy of humans in the world of Internet of Things (ioT).  On this piece, i attempt to review the Provisioning of   passpointConfiguration  which is supported by the suggestion API. Before Android 11, provisioning a PasspointConfiguration required the use of the addOrUpdatePasspointConfiguration() API.
The framework enforces security requirements on TLS-based Enterprise suggestions (EAP-TLS, EAP-TTLS, and EAP-PEAP); suggestions to such networks must set a Root CA certificate and a server domain name.

**Key takeaways**
- Why the disconnection in signal during information transmission.
- Effects following the disconnection
- How can this be resolved.

**Comment by hectorkambow** [comment]
@KayTee24 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
This topic seems abit all over the place an unstructured - not sure what the pain point you are solving is. 

The title is confusing - please revisit to make a easier to follow along.

**Comment by KayTee24** [comment]
Done.

**Comment by louisefindlay23** [comment]
@KayTee24, your topic suggestion form is still confusing to read because your introductory paragraph is very long and you haven't added line breaks to split the monolithic paragraph into several smaller ones and your form is split up into two messages instead of on.

See this [topic suggestion](https://github.com/section-engineering-education/engineering-education/issues/2133) from one of our content moderators as an example of the format the form should be submitted in.

**Comment by WanjaMIKE** [comment]
@KayTee24 I am going to close this topic to free up the queue. Feel free to suggest another topic. Thanks
