### ISSUE TITLE
PHP Sessions and Cookies to Create a Secure 'Remember Me' Section In a Login Script

### ISSUE THREAD

**Issue by Juskam** [section-engineering-education/engineering-education#3063]
### Proposed title of article
 PHP Sessions and Cookies to Create a Secure 'Remember Me' Section In a Login Script.
### Introduction paragraph (2-3 paragraphs):
The ‘Remember Me' functionality in the Login Script will allow the user to keep their logged in status. 
When a user selects the Remember Me option, the logged-in status is serialized in the PHP session or cookies.
While writing user login data to a session or cookie,It is critical to be alert of security problems that could jeopardize the program's authentication system.

Because plain passwords can be hacked, they should not be saved in the user's cookie.
This article will show you how to make a PHP web application with a persistent authentication system.
When a user tries to log in using the application, the entered login credentials are validated against the database.

If a match is detected, the user's logged-in status is preserved using the PHP session and cookies before being redirected to the dashboard. The unique member id from the member database is saved in a session after a successful login. The cookies are then set to save the login name and password for a given length of time. 
To prevent hacking, a random password and a token are produced and kept in the cookie instead of the users' plain password. When a user visits the application pages, the user's current logged-in session is checked and the user is redirected to the requested page. If the session is empty, the code will check the cookies to see if the user is logged in. The user will be sent back to the login page if neither the session nor the cookies include any information about the remembered login.

### Key takeaways: 
1.Create Cookies to Preserve the Logged-In State
2.Validate Remembered Login with PHP Session and Cookies
3.Clear Remembered Login with Session and Cookies on Logout

### References: 
N/A

**Comment by hectorkambow** [comment]
@Juskam 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Juskam 
After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topic.
That way a developer could see them in action.

**Comment by Juskam** [comment]
@hectorkambow Thanks for the heads up, I've opted to replicate the issue in order to produce a distinct, different, and beneficial idea.

**Comment by hectorkambow** [comment]
@Juskam 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites. (beyond a basic explanation - it would be best to reference your favorite intro article and build upon it).
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
