### ISSUE TITLE
Running MariaDB Docker Containers using Java Spring and JDBC

### ISSUE THREAD

**Issue by ephnjor2021** [section-engineering-education/engineering-education#3065]
### Proposed title of article
Running MariaDB Docker Containers using Java Spring and JDBC

### Introduction paragraph:
Developers have been adopting the use of MariaDB over the past decade. MariaDB is open-source and a relational database. As time passes MariaDB has been building up on MySQL by integrating many features with great functionality.
MariaDB is not new to Java and Java Virtual Machines environments, as developers have been using it to create their amazing applications.
In this guide, we will utilize MariaDB to create a simple maven-based to-do list application using Java Spring and expose several endpoints to perform various operations on the MariaDB database instance.

### Key takeaways: 
In this article, the reader will be able to:
- create a new MariaDB database instance using Docker
- create and connect to MariaDB database
- create a simple to-do list Java Spring-based maven application
- expose endpoints to perform CRUD(create-read-update-delete) tasks on the MariaDB database instance

### References: 
N/A

**Comment by hectorkambow** [comment]
@ephnjor2021 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Wanted to make sure that this topic will not overlap with this already published article.

https://www.section.io/engineering-education/getting-started-with-mariadb-using-docker-and-nodejs/

Or that it is not overly saturated throughout other blog sites.

**Comment by ephnjor2021** [comment]
@hectorkambow The MariaDB will work as the backend that is running in a Docker container, unlike the mentioned article above which deals with Node.js, here I will use Java Language to implement an API that can manipulate the database.

**Comment by louisefindlay23** [comment]
Hi, @ephnjor2021. There's seems to be an existing [Hackernoon article](https://hackernoon.com/how-to-connect-mariadb-docker-containers-with-java-spring-and-jdbc-ex243urb) with the same topic. Could you tell us how your tutorial will be different and unique from that?

**Comment by ephnjor2021** [comment]
@louisefindlay23 I will close the issue for now until I draw more attention to it. I will reopen it at a later date
