### ISSUE TITLE
How to develop a Business Directory using CodeIgniter and MySQL?

### ISSUE THREAD

**Issue by kerubo-tech** [section-engineering-education/engineering-education#3067]
### Proposed title of article
How to develop a Business Directory using CodeIgniter and MySQL?

### Introduction paragraph:
CodeIgniter is a PHP MVC framework which developers use to build web applications rapidly. It provides out-of-box libraries for connecting to the database such as MySQL and performing various tasks such as sending emails, uploading files, managing sessions among others.
This article will provide steps on how to build a simple web directory using CodeIgniter and MySQL. Since CodeIgniter is an MVC framework, the Model will be related to the database, View will be the HTML part seen on the web browser and Controller will be the logic that connects our Models with the Views.

### Key takeaways: 
At the end of the article the reader will be able to:
- set up MySQL database
- define and code the application's model
- create a controller that loads data from the model and pass it to the view
- create various views of the application and the routes to connect to those specific views

### References: 
N/A

**Comment by hectorkambow** [comment]
@kerubo-tech

Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@kerubo-tech 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
