### ISSUE TITLE
Exception handling in windows forms

### ISSUE THREAD

**Issue by mohamedgh16** [section-engineering-education/engineering-education#3070]
### Brief Summary: 
The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running. Exception handling uses the try, catch, and finally keywords to try actions that may not succeed, handle failures when you decide that it's reasonable to do so, and clean up resources afterward.

In windows forms, you should always take care of any wrong inputs when using some tools from the toolbox that takes all kinds of inputs from a keyboard, therefore we will use the exception handling methods to deal with any errors or unwanted inputs.

### Key Takeaways: 
1. Definition of exception handling.
2. Exception handling keywords (Try - Catch - Finally).
3. All the possible cases in exception handling in windows forms.
4. Examples

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by hectorkambow** [comment]
@mohamedgh16 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Wanted to make sure that is doesn't overlap with these topics.

https://www.section.io/engineering-education/search/?q=Exception%20handling

Please double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours.

**Comment by mohamedgh16** [comment]
@hectorkambow I won't be focusing on the concept of exception handling as much as I'm focusing on how windows forms can produce so many errors when the programmer allows the user to enter all kinds of inputs and how we can avoid that. Basically, we will focus on what and how we should implement the forms and their input bars to avoid any issues.

**Comment by louisefindlay23** [comment]
@zolomohan, could you take a look at this topic suggestion when you have the chance? Since you have expertise in C#, I thought you'd be the best person to access this topic's unique value.

**Comment by ahmadmardeni1** [comment]
I'm trying to clear the queue. Should we approve this one? @zolomohan

**Comment by zolomohan** [comment]
@ahmadmardeni1 yes we can approve this one.

**Comment by zolomohan** [comment]
@mohamedgh16 please make sure you cover all kinds of errors and corner cases that could arise while working with windows forms.
