### ISSUE TITLE
Your first app with kivy python

### ISSUE THREAD

**Issue by doloresmia** [section-engineering-education/engineering-education#3072]
### Proposed title of article
Your first app with kivy python

### Introduction paragraph (2-3 paragraphs):
Kivy is a cross-plaftform python framework for building mobile applications. Kivy was initially released in 2011 February. One major advantage of Kivy is that it build applications that can run on any platform. An app build in Kivy can run seamlessly on android, IOS, MACOS Linuc and Windows as well.

In this articke, we will look into Kivy by building and running a mobile app using Kivy. I will write  an application that calculates a user's BMI given the weight and height. We will also style oup application to give it a good look.

### Key takeaways: 
1. Setting up Kivy on your machine
2. Styling an app using Kivy
3. Building and testing a mobile app with Kivy
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@doloresmia 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@doloresmia 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
