### ISSUE TITLE
Getting started with Remote Management for System Administrators

### ISSUE THREAD

**Issue by OMONDIELLY** [section-engineering-education/engineering-education#3074]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### getting started with remote management for system administrators
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Remote management, also known as Remote IT management is an essential aspect in system administration. Whether you want to initiate a  simple help desk/IT support portal or gain 24/7 visibility of your systems and client applications, you are required to understand what remote management is. 
This article will give you an overview of remote management and why it is necessary. In the end, we'll see some of the tools that can get you started with remote management.

### Key takeaways: 
1. What is remote management?
2. Benefits of remote management
3. What to manage remotely as an administrator.
4. Working with popular remote management tools:
        - AnyDesk
        - AnyConnect
        - Dameware
        - RemotePC
        - Desktop Central MSP

5. Conclusion

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@OMONDIELLY 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
🤔 

This topic is a tricky one. 

I think this topic is a nice one - but it could be improved. 

The value to readers would come at the end. I think this topic can easily be found across other blog sites.

What can be done to make this topic more of a original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

**Comment by OMONDIELLY** [comment]
Thanks Hector for the review. I think improving it may make it a bit difficult to follow or kind of mixed in the long run. I would consider letting it go and find  a new one with a practitioner approach if that's okay.
Thanks.

**Comment by louisefindlay23** [comment]
Sure, @OMONDIELLY. Have closed this topic suggestion at your request. We look forward to reviewing your next topic idea. We're sure it will be a great one.
