### ISSUE TITLE
integration of ROS with Arduino

### ISSUE THREAD

**Issue by Newton-cyber** [section-engineering-education/engineering-education#3076]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction paragraph (2-3 paragraphs):
ROS is an operating system that contains softwares, tools and libraries to help build robot applications. ROS works in linux ubuntu or linux debian and therefore, integration of ROS with Arduino, a ROS driver for Arduino-based-Robots is used as a starting point and easily generalized to a wide variety of other robots also based on Arduino controller boards.
we will learn samples of arduino code through the the Arduino software. In order to emulate ROS language directly in Arduino code, we need rosserial stack.
### Key takeaways: 
1. what is ROS?
2. Code and connect an Arduino circuit
3. Interface ROS with arduino

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Newton-cyber 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Newton-cyber 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
