### ISSUE TITLE
Creating a responsive sidebar using Tailwind CSS and JavaScript

### ISSUE THREAD

**Issue by ianmasae** [section-engineering-education/engineering-education#3078]
### Proposed title of article
Creating a responsive sidebar using Tailwind CSS and JavaScript

### Introduction paragraph (2-3 paragraphs):
A sidebar is a user interface element like a column on the right or left side of a website. It is used to display a list of choices used for navigation purposes. A sidebar is, therefore, a useful component that helps website visitors to navigate through to different sections of the website.
This article goes through creating a simple responsive sidebar using Tailwind CSS and a little bit of JavaScript from scratch. We will use various Tailwind classes to style up our sidebar. We will use JavaScript to add functionality to our sidebar.

### Key takeaways: 
•	The reader will learn how to create a simple sidebar.
•	The reader will learn how to style their sidebar to their preference.
•	The reader will learn how to make a sidebar responsive.

### References: 
N/A

**Comment by hectorkambow** [comment]
@ianmasae

Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
I believe this topic has been published 

https://www.section.io/engineering-education/creating-a-responsive-navigation-bar-using-tailwind-css-and-javascript/


Please be sure to double check future topics - that they do not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours.
