### ISSUE TITLE
Creating a responsive HTML registration from

### ISSUE THREAD

**Issue by harshitab13** [section-engineering-education/engineering-education#3081]
### Introduction
In this tutorial we will learn how to create a Responsive HTML Registration Form. The registration form has multiple input fields with varied input details where the user must enter in his or her information in order to submit for a certain web page. There are many different sorts of registration forms, but the main goal of these form is to collect information or facts from the user.

### Key takeaways: 

- Creating basic Html template for registration form
- Adding CSS design 
- Creating responsive registration form

### References: 
N/A

**Comment by hectorkambow** [comment]
@harshitab13 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@harshitab13 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
**Please be sure to double check that it does not overlap with any existing EngEd** articles or incoming topic suggestions (if you haven't already) to avoid any **potential article closure**, please reference any relevant EngEd articles in yours. - Approved
