### ISSUE TITLE
10 of the most annoying UI/UX mistakes to avoid while crafting your products

### ISSUE THREAD

**Issue by wanjirualice6194** [section-engineering-education/engineering-education#3088]
### Proposed title of article
10 of the most annoying UI/UX mistakes to avoid while crafting your products

### Introduction paragraph (2-3 paragraphs):
The user interface(UI) plays a major role in how a user interacts with your products. From mobile apps, to web apps, to desktop applications, there are tiny details that make it hard or easy for a user to be served by your product. No matter how good your product logic is, the user only interacts with the UI. Good UI/UX practices allow users to spend more time using your product, it increases the chances of the user recommending the product to their colleagues, while bad practices do the exact opposite.

There are some details which when put into consideration, can improve your products' effectiveness. When neglected, they can be the only thing that made your awesome startup fail.

In this article, we look at 10 of the most annoying UI/UX mistakes to avoid while crafting your products.

### Key takeaways: 
We will touch on:
1. Images and image quality
2. Text and the reading area
3. Actions and notification
4. Proper layouts
5. Color palletes
6. Buttons
7. Clickability and clickable areas
8. Inconsistency in design
9. Fonts
10. Data validation

### References: 
N/A

**Comment by hectorkambow** [comment]
@wanjirualice6194 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@wanjirualice6194
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #3088 via #3408
