### ISSUE TITLE
Deploying Django Application Continuously to Heroku with Docker and GitHub Actions

### ISSUE THREAD

**Issue by khabdrick** [section-engineering-education/engineering-education#3089]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Deploying Django Application Continuously to Heroku with Docker and GitHub Actions

### Introduction paragraph (2-3 paragraphs):
It’s always a good idea to use GitHub Actions for your project because it makes it easy to automate processes through which include; testing and deploying your project. Docker helps make sure your app works the same way on all platforms. Adding these functionalities to your application can make it easy for continuous delivery and collaboration. 

### Key takeaways: 
- Learn how Docker and Docker-compose work together
- Introduction to continuous delivery
- How to deploy automatically to Heroku with GitHub Actions

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@khabdrick 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@khabdrick 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by khabdrick** [comment]
Hello @hectorkambow  I'm done with this article now.
Please what can I do?

**Comment by khabdrick** [comment]
https://www.dropbox.com/scl/fi/q9ucsw9p815mm2ed2ermv/Deploying-Django-Application-Continuously-to-Heroku-with-Docker-and-GitHub-Actions-1.paper?dl=0&rlkey=p2a1dp0rys5vsrrxmurfbz2io

@hectorkambow I have the article ready in the link above, if you can open as soon as possible that will be great. :)

**Comment by khabdrick** [comment]
Hello @hectorkambow is there any update on this?
