### ISSUE TITLE
Getting Started with PHP 7 without using a framework

### ISSUE THREAD

**Issue by lewe01** [section-engineering-education/engineering-education#3092]
### Proposed title of article
Getting Started with PHP 7 without using a framework

### Introduction:
In the past times, PHP developers were forced to use frameworks to maintain their projects professionally. Since the introduction of the composer package manager and PHP standards writing PHP code became easier and more manageable.
In this tutorial, we will build a small API project with basic routing, third-party packages, and testing without using a framework. 

The goal will be to create a simple blog API, each post will have an **id**, **title**, and **body**. The user will be able to list, create and view a post. We will use a JSON file as our database, and all the requests or responses will be in JSON format.

### Key takeaways: 
At the end of the tutorial the reader will be able to:
- create and setup a composer
- add logging and routing for the project
- implement the blog API
- add a testing module to the project

### References: 
N/A

**Comment by hectorkambow** [comment]
@lewe01 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@lewe01 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
