### ISSUE TITLE
Breaking Down the Production System in Artificial Intelligence

### ISSUE THREAD

**Issue by gracekary** [section-engineering-education/engineering-education#3094]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Breaking Down the Production System in Artificial Intelligence

### Introduction paragraph (2-3 paragraphs):
This article provides a breakdown of production system in AI. This system is important because it enhances the creation of AI-based programs and the automation of machines. The article will look at the features, components and examples of production systems in AI. 

### Key takeaways: 
1. What is production system in AI?
2. Features of a production system
3. Components of a production system
4. Classification of production systems in AI
5. Advantages and disadvantages of production systems
6. Examples of production systems in AI
7. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@gracekary 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Pinging our resident expert to help shed some more light on this topic @lalith1403

**Comment by lalith1403** [comment]
Can you explain what a production system means and it's relationship with AI?

**Comment by gracekary** [comment]
> Can you explain what a production system means and it's relationship with AI?

@lalith1403 A production system is a cognitive architecture that supports artificial intelligence through a set of rules and mechanisms for executing them. It consists of a global database that contains all the information required to execute tasks, a set of rules that are applied on the data from the global database, and a control system that applies the rules. Production systems are used in the creation of AI programs and automation of machines.

**Comment by lalith1403** [comment]
Hello, @gracekary. This article is a super helpful and important topic. Please start working on the topic proposed. Let's ignite all the boosters on this one and deliver superior value to the reader.

Let's be sure to provide value that we as developers feel is scarcely available out there on the web. Custom projects would be the best way to explain such concepts. We avoid projects and explanations easily available on documentation sites and blogs.

Cheers,
Lalith

**Comment by hectorkambow** [comment]
@gracekary 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by gracekary** [comment]
> @gracekary
> Just pinging you on this topic form - as I'm making some room in the topic queue.
> No rush if you're still working on this one - if you need more time we can always re-open at a later date.

@hectorkambow Please re-open this issue so that I can make a pull request. I have finished writing the article.

**Comment by gracekary** [comment]
@hectorkambow I finished writing the article. Please re-open this issue so that I can make a pull request.  

cc@lalith1403
