### ISSUE TITLE
Understanding Search Algorithms in AI

### ISSUE THREAD

**Issue by gracejolie** [section-engineering-education/engineering-education#3095]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Understanding Search Algorithms in Artificial Intelligence

### Introduction paragraph (2-3 paragraphs):
Search algorithms are important because they solve various problems in artificial intelligence. There are various search algorithms in AI. This article takes you through search algorithms, including their importance and properties. It will also provide the classification of search algorithms and identify the popular search algorithms in AI. 

### Key takeaways: 
1. What is a search algorithm?
2. Importance of search algorithms
3. Properties of search algorithms
4. Types of search algorithms	
5. Applications of search algorithms
6. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@gracejolie 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Pinging our resident expert to help shed some more light on the topic @lalith1403

**Comment by lalith1403** [comment]
Hey @gracejolie. Thanks for submitting the topic form. Can you explain what search algorithms are and how they solve problems in AI?

**Comment by gracejolie** [comment]
> Hey @gracejolie. Thanks for submitting the topic form. Can you explain what search algorithms are and how they solve problems in AI?

@lalith1403 Search algorithms are algorithms that help in solving search problems. A search problem consists of a search space, start state and goal state. Search algorithms help the AI agents to attain the goal state through the assessment of scenarios and alternatives. The algorithms provide search solutions through a sequence of actions that transform the initial state to the goal state. Without these algorithms, AI machines and applications cannot implement search functions and find viable solutions.

**Comment by lalith1403** [comment]
Yes. Can you discuss some of the algorithms that you will be going deep into. Post that, we can finalize the topic.

**Comment by gracejolie** [comment]
> Yes. Can you discuss some of the algorithms that you will be going deep into. Post that, we can finalize the topic.

@lalith1403 I will be discussing breadth-first, depth first, iterative deepening, uniform cost, bidirectional, greedy, A* graph, and A* tree algorithms.

**Comment by lalith1403** [comment]
Hello @gracejolie. This seems to be a super helpful and essential topic. Please start working on the topic proposed. Let's ignite all the boosters on this one and deliver superior value to the reader.

Let's be sure to provide value that we as developers feel is scarcely available out there on the web. Custom projects would be the best way to explain such concepts. We avoid projects and explanations readily available on documentation sites and blogs.

Cheers,
Lalith

**Comment by hectorkambow** [comment]
@gracejolie 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by gracejolie** [comment]
@hectorkambow Please re-open this issue so that I can open a pull request. I've been waiting for almost a month now. 

cc @louisefindlay23 
cc @lalith1403
