### ISSUE TITLE
How to follow system dark mode in a web app using JavaScript 

### ISSUE THREAD

**Issue by Njerikariuki** [section-engineering-education/engineering-education#3104]
### Proposed title of article
How to set and remember dark mode in a web app using JavaScript

### Introduction paragraph (2-3 paragraphs)
Dark mode is the second most best thing in a web app after a well crafted user interface. Dark mode is preferred by most user because it does not strain the eyes. It also saves the users' device battery life since rendering white or bright pixels on the screen, uses more power compared to rendering their dark counterparts. This however depends on the type of display used by the user.

One of the most beautiful features in a well crafted web app is: the ability to automatically switch to dark mode once the system is set to dark mode. This makes your app to integrate with the system naturally.

In this tutorial, we will build a simple project to demonstrate how to add dark mode to a website. We will also look at how to set the dark mode state dynamically by listening for the system dark mode state. We will finally look at how to remember the dark mode state by storing a variable in the cookies.

### Key takeaways: 
By the end of this tutorial, you will be able to:
1. Add dark mode to your web app.
2. **Toggle the dark mode state according to the system.**
3. Remember the dark mode state of the web app.

### References: 
N/A

**Comment by hectorkambow** [comment]
@Njerikariuki 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Njerikariuki 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by phinaomondi** [comment]
Hello @Njerikariuki, I covered this topic here https://www.section.io/engineering-education/adding-dark-theme-to-your-site/

cc: @hectorkambow
