### ISSUE TITLE
PHP Implode and Explode

### ISSUE THREAD

**Issue by amarawrite** [section-engineering-education/engineering-education#3106]
### Proposed title of article*

PHP Implode and Explode

### Introduction paragraph (2-3 paragraphs):

When working with arrays and strings in PHP, the functions PHP implode and PHP explode are frequently utilized. I will show the leader how to use implode in PHP with a code example in this article. With a code example, I will also demonstrate how to utilize explode in PHP.

I will also demonstrate how to generate an array from a string using the explode statement. The explode() function converts a string to an array, whereas the implode() function creates a string from an array's elements.

### Key takeaways:
 
1. PHP Implode Function
2. PHP Explode Function

### References: 
N/A

**Comment by hectorkambow** [comment]
@amarawrite 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@amarawrite 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

I know we have quite a few PHP articles in our EngEd library.
