### ISSUE TITLE
Building a simple translation app using Python for beginners

### ISSUE THREAD

**Issue by smkinyan** [section-engineering-education/engineering-education#3109]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.
### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Building a simple translation app using Python for beginners

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

Want to build your very own language translation app?

Well, in this tutorial, I'll show you how you can build one yourself using Hugging Face Transformers and Gradio! 

Hugging Face is a great open-source library which is doing powerful work in the Natural Language Processing (NLP) space. The library has a bunch of pre-trained models which you can leverage or fine-tune. Gradio, on the hand, allows us to quickly create customizable UI components around PyTorch models.

We'll be leveraging both Gradio and Hugging Face to build a simple translation app. 

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to understand how to:

1. Install Gradio and Transformers
2. Translate text using a deep learning translation pipeline
3. Building a lightweight machine learning app using Python and Gradio

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

1. [Hugging Face](https://huggingface.co/transformers/)
2. [PyTorch](https://pytorch.org/)
3. [Gradio](https://gradio.app/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@smkinyan 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
pinging our resident expert to help shed some more light on the topic @lalith1403

**Comment by smkinyan** [comment]
> pinging our resident expert to help shed some more light on the topic @lalith1403

I know this article isn't the typical type of article, both as a Computer Science student currently pursuing her Master's program, the biggest pain is in reading ML and DL research papers and not understanding a thing. So this topic idea was born out of the problems I faced and I know many computer science do. @lalith1403

**Comment by lalith1403** [comment]
@smkinyan This is a beautiful problem to have. Kudos to you on choosing a problem that everyone faces. However, I feel this is a very personal thing, and what works for you might not work for me. So, can you probably discuss the framework that you hope to discuss in the article. 

Once we have that piece of the puzzle, we can proceed with how to frame the article. This is definitely an exciting topic, but we want it to be useful to all edge cases as well.

**Comment by lalith1403** [comment]
By Framework I mean, Probably take a paper, and read through the sections that you would initially look at. Then, if you are interested in the results proposed, talk about the metrics and analysis that goes into understanding the results. Once done, if you are going to talk about PapersWithCode, a major problem is, how does one setup the repositories that vary so widely. This is a pain point. Please correct me if you feel otherwise. If you could present the entire process of taking a paper and reproducing it using the official and non-official code-bases(not all papers have code released. In such cases we rely on community Dev). 

This process would be really helpful in addition to the topics you have mentioned. This is a problem I face personally as well. So, I am passionate about the problem statement and would love to see a solution from the community. 

Kudos to you again on choosing a wonderful topic! :)

Cc: @hectorkambow
