### ISSUE TITLE
Working with zip files in Python

### ISSUE THREAD

**Issue by fely545** [section-engineering-education/engineering-education#3112]
### Proposed title of article
Working with zip files in Python

### Introduction paragraph (2-3 paragraphs):
ZIP is an archive file format that supports lossless data compression. This tutorial explains will on how you can perform various operations on a zip file using a simple python program.

### Key takeaways: 

- What is a zip file?
- Extracting a zip file
- Writing to a zip file
- Getting all information about a zip file

### References: 
N/A

**Comment by lalith1403** [comment]
Hello @fely545. Thanks for the topic suggestion. However, this is a fundamental topic and is widely covered over the net. We are looking for programmer-centric concepts explained in a fun and intuitive ways. I will be closing this issue for now. I encourage you to submit a new topic form. I look forward to it :).
