### ISSUE TITLE
Coming Soon Landing Page Using JavaScript Timers

### ISSUE THREAD

**Issue by EssyG10** [section-engineering-education/engineering-education#3118]
### Proposed title of article
Coming Soon Landing Page Using Javascript Timers

### Introduction paragraph (2-3 paragraphs):
A Coming Soon page is a placeholder home page that informs visitors that your website is being built or will be available soon. 
Visitors are unable to navigate to the remainder of your website since the coming soon page lacks a header or footer. 
Every coming soon page it includes a statement encouraging visitors to return at a later time, as well as any other pertinent information.This article will have a descriptive template to capture and familiarize learners with everything they need to know to have a coming soon landing page
### Key takeaways: 
1.Javascript Timers overview 
2.Working of the setTimeout() function 
3.Working of the setInterval() function 
4.Coming soon landing page template 

### References: 
N/A

**Comment by hectorkambow** [comment]
@essyg10
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @EssyG10. 

Thanks for submitting a topic. 

Can you tell me what makes your article unique from other JavaScript timer tutorial articles and resources that provide webpage templates such as Coming Soon?

**Comment by EssyG10** [comment]
@louisefindlay23,the outstanding thing that  this article will have is that,for those begginers in JavaScript who have not learnt any framework will be able to understand my code snippets.For those who are comfortable with Jquery,I will also demonstrate how to achieve the coming soon landing page with jquery and for those Learners who are quite comfortable with modern JavaScript will also benefit since my code snippets will be in modern JavaScript.

**Comment by louisefindlay23** [comment]
Good explanation, @EssyG10 - approved. Make sure your article is in-depth though and provides lots of value to our readers.

**One important note:** please ensure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)"

**Comment by EssyG10** [comment]
@louisefindlay23,thanks
