### ISSUE TITLE
 Flattening a dictionary in Python

### ISSUE THREAD

**Issue by mukono10** [section-engineering-education/engineering-education#3121]
### Proposed title of article
 Flattening a dictionary in Python

### Introduction paragraph (2-3 paragraphs):
There are a variety of reasons why you would require a flattened dictionary. One advantage is that it makes comparing two dicts much easier. The other advantage is that a flat structure is easy to browse and modify because it is only one level deep.

The purpose of this article is to present the reader with a variety of solutions to the flattening dictionary problem and to supply them with as much information as possible so that they can make an informed decision.

### Key takeaways: 
1. Using your Own Recursive Function
2. Using pandas json_normalize
3. Using your Own Recursive Function and Generators
4. Using the flatdict Library

### References: 
N/A

**Comment by hectorkambow** [comment]
@mukono10

Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by mukono10** [comment]
Thanks

**Comment by WanjaMIKE** [comment]
dictionaries have been covered here ```https://www.section.io/engineering-education/lists-and-dictionaries-python/```

**Comment by lalith1403** [comment]
Hello @mukono10. Thanks for the topic suggestion. However, this is a fundamental topic and is widely covered over the net. We are looking for programmer-centric concepts explained in a fun and intuitive ways. I will be closing this issue for now. I encourage you to submit a new topic form. I look forward to it :).
