### ISSUE TITLE
An overview of PHP file Functions

### ISSUE THREAD

**Issue by mbuthiajn** [section-engineering-education/engineering-education#3123]
### Proposed title of the article
An overview of PHP file Functions

### Introduction paragraph (2-3 paragraphs):
PHP file functions are the best and the convenient way of working with files we have with the help of PHP’s huge collection of built-in functions. Windows Operating System and MAC Operating Systems are not case sensitive. Adopting the lower case letters naming conversion for the file naming purpose is the best practice that ensures the maximum cross platform’s compatibility. There are some PHP File Functions that are very much helping in handling the data which is present in the file information.

### Key takeaways: 
1. PHP file Functions
2. Opening files using PHP file function
3. PHP filesystems and PHP file functions
4. Closing files using PHP file function
5. Customizing PHP file functions
6. Examples to complement PHP file Functions
- PHP file_exists Function
- PHP open Function
- PHP write Function
- PHP close Function
- PHP gets Function
- PHP Copy Function
- PHP file_get_contents Function
- Deleting a File (Unlink Function)

### References: 
N/A

**Comment by hectorkambow** [comment]
@mbuthiajn 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

Please feel free to suggest an alternate topic to explore. 🚀 
@mbuthiajn
