### ISSUE TITLE
An overview of javascript decorators

### ISSUE THREAD

**Issue by Robbiewanjau** [section-engineering-education/engineering-education#3125]
### Proposed title of article
An overview of javascript decorators
### Introduction paragraph (2-3 paragraphs):
In programming, decorating is just wrapping one piece of code around another to make it look nicer.
 A decorator (also known as a decorator function) is a design pattern that extends the capability of a function by wrapping it in another function.
Because of first-class functions, which are JavaScript functions that are treated as first-class citizens, this concept is attainable in JavaScript.
Higher-order functions are a type of function decorator, hence the concept of decorators is afterall not new in JavaScript.

### Key takeaways: 
1.Higher-order functions
2.Class Decorators
3.Class member decorators
### References: 
N/A

**Comment by hectorkambow** [comment]
@Robbiewanjau 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Robbiewanjau 
After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

Please feel free to suggest an alternate topic to explore. 🚀
