### ISSUE TITLE
Java: Arguably the King of Programming Languages but is it the Best Language for Artificial Intelligence Projects? 

### ISSUE THREAD

**Issue by BridgetMwikali** [section-engineering-education/engineering-education#3128]
### Proposed title of article
Java: Arguably the King of Programming Languages but is it the Best Language for Artificial Intelligence Projects? 

### Introduction paragraph (2-3 paragraphs):
A single, individual language for artificial intelligence has not been invented yet. Nevertheless, developers achieve great results using existing tools.

In many use cases, Java can be named the best language for AI projects. In general, it is one of the most loved and commonly used by programmers languages. If we take Java artificial intelligence programming, it is mostly used to create machine learning solutions, neural networks, search algorithms, genetic programming, and multi-robot systems.

But, how is Java used in AI and what benefits can Java bring to Artificial Intelligence solutions. This article will provide you with an answer to help your queries.

### Key takeaways: 

1. How Java is used in AI
2. Why develop AI in Java?
3. Java compared to other Artificial Intelligence programming languages 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@BridgetMwikali 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. 

Brining in our resident ML/AI expert for more insight @lalith1403

**Comment by lalith1403** [comment]
Hello, @jamesomina99.This article is a super helpful and important topic. This article will be putting forward your opinions about why Java is a good language for AI. Make sure to base it with relevant facts and mention any references or proofs required to validate the statements. This should be exciting to read. Topic approved :)

**Comment by WanjaMIKE** [comment]
Closed #3128 via #3641
