### ISSUE TITLE
Extracting Colors from Images using Palette API in Android

### ISSUE THREAD

**Issue by robert-muriithi** [section-engineering-education/engineering-education#3130]
### Introduction paragraph (2-3 paragraphs):
The palette library is a support library that extracts prominent colors from images to help you create visually engaging apps. 
You can use the palette library to design layout themes and apply custom colors to visual elements in your app. For example, you can use a palette to create a color-coordinated title card for a song based on its album cover or to adjust an app’s toolbar color when its background image changes.The Palette object gives you access to the colors in a Bitmap image while also providing six main color profiles from the bitmap to help inform your design choices. In this tutorial we will extract colors from an image and display them. 

### Key takeaways: 
- What is Palette API
-  How Does it Work
- Set up the library
- Extract color profiles

### References: 
https://developer.android.com/

**Comment by hectorkambow** [comment]
@robert-muriithi 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@robert-muriithi 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
