### ISSUE TITLE
How to Create a machine learning model using PyTorch

### ISSUE THREAD

**Issue by charles721** [section-engineering-education/engineering-education#3133]
### Proposed title of article
How to Create a machine learning model using PyTorch

### Introduction paragraph (2-3 paragraphs):
PyTorch is an open-source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing and classification. PyTorch is easier to learn and lighter to work with, and hence, is relatively better for passion projects and building rapid prototypes. 
PyTorch is the premier open-source deep learning framework developed and maintained by Facebook. At its core, it's a mathematical library that allows you to perform efficient computation and automatic differentiation on graph-based models.
In this tutorial, we will use Pytorch to build a basic machine learning form: 
1. data processing
2. training /testing our model and finally 
3. making predictions using the model.

### Key takeaways: 
1. getting started with the basics of PyTorch.
2. installing PyTorch in our machine.
3. Data preprocessing.
4. Training and Testing model.
5. Making predictions using our model.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@charles721 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
