### ISSUE TITLE
How to Integrate a Machine Learning Model to a Flask RESTful API

### ISSUE THREAD

**Issue by Inyrkz** [section-engineering-education/engineering-education#3136]
### Proposed title of article
How to Integrate a Machine Learning Model to a Flask RESTful API and Deploy to Heroku

### Introduction paragraph (2-3 paragraphs):
This will be the second article in a series of three articles. The first article was https://www.section.io/engineering-education/diagnose-diabetes-with-svm/. 
In this article, you will learn how to create a REST API for your machine learning model using Flask-Restful, and deploy to Heroku. The Flask-RESTful library in Flask enables us to build REST APIs with ease. We will start by serializing our machine learning model from the project in the link above. Serialization is the process of turning a Python object into a byte stream. The conventional method of serializing objects in Python is by using Pickle. With pickle, we can serialize our machine learning model. We can save the serialized format to a file. We do not have to retrain the machine learning model each time we want to use it. We can just load the saved file and deserialize it. Then, we use it to make new predictions. 
After building the API, you'll deploy it to Heroku. Heroku is a platform as a service (PaaS) that allows developers to build, run, and operate applications entirely in the cloud.

### Key takeaways:
You will learn how to:
-	create a virtual environment.
-	save your machine learning model to a file by pickling it, as well as how to load the saved model.
-	preprocess new data in incoming requests from clients before passing it to the model, 
-	integrate your model to a Flask REST API.
-	you will also learn how to deploy the Flask REST API to Heroku, so other developers can have access to your ML model. With the API, they can integrate it to web apps, android apps, etc.

### References: 
N/A

**Comment by hectorkambow** [comment]
@Inyrkz 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Inyrkz** [comment]
The issue has been modified.

**Comment by lalith1403** [comment]
Hello, @jamesomina99. This article is a super helpful and important topic. Please start working on the topic proposed. Let's ignite all the boosters on this one and deliver superior value to the reader.

Let's be sure to provide value that we as developers feel is scarcely available out there on the web. Custom projects would be the best way to explain such concepts. We avoid projects and explanations easily available on documentation sites and blogs.

Cheers,
Lalith

**Comment by lalith1403** [comment]
Hello, @Inyrkz. This article is a super helpful and important topic. Please start working on the topic proposed. Let's ignite all the boosters on this one and deliver superior value to the reader.

Let's be sure to provide value that we as developers feel is scarcely available out there on the web. Custom projects would be the best way to explain such concepts. We avoid projects and explanations easily available on documentation sites and blogs.

Cheers,
Lalith

**Comment by hectorkambow** [comment]
@Inyrkz 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by Inyrkz** [comment]
Hi!
My laptop is bad, but I've been able to use my friend's laptop to push the
article.

**Comment by lalith1403** [comment]
Reference this issue in the new PR. Please follow the contribution guidelines for a smooth and fast review process.

**Comment by Inyrkz** [comment]
I have referenced this issue in the PR.
