### ISSUE TITLE
Form Validation in Vue.js using VeeValidate

### ISSUE THREAD

**Issue by Njunu-sk** [section-engineering-education/engineering-education#3137]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Form Validation in Vue.js using Veevalidate

### Introduction paragraph (2-3 paragraphs):
Client-side validation is common in today's web applications and pages, it improves user experience and saves on application resources. In this article, we explore the VeeValidate library validating our form(experimenting on different fields), best practices of client-side validation, creating custom validation rules, and take a look at validation triggers.
I will also provide a tailwind form template for practice.

### Key takeaways: 
The reader will gain the following at the end of the article.
 - Understand the importance of client-side validation.
 - Understand the in's and out's of vee validate library.
 - Be able to validate your own forms.
 - Be able to create custom validation rules.
 - Understand and customize validation triggers.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
https://vee-validate.logaretm.com/v4/

### Templates to use as guides

- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Njunu-sk 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
@Njunu-sk, great topic. 

It's good that you've outlined a list of topics you'll cover and it's clear your article will be comprehensive covering why client-side validation is important to the vee validate library and understanding and being able to implement some of its important features. 

Topic approved 🚀
