### ISSUE TITLE
How to work with Getters and Setters in Java

### ISSUE THREAD

**Issue by mussooo** [section-engineering-education/engineering-education#3139]
### Proposed title of the article
How to work with Getters and Setters in Java

### Introduction paragraph (2-3 paragraphs):
When creating classes in Java, it is very important to use Getters and Setters to protect your data.

Getters and Setters play an important role in retrieving and updating the value of a variable outside the encapsulating class. A setter updates the value of a variable, while a getter reads the value of a variable.

Getters and Setters are also called accessors and mutators, respectively.

By convention, getters start with the word "get" and setters with the word "set", followed by a variable name. In both cases, the first letter of the variable's name is capitalized.

In this tutorial, we will look at everything that the reader needs to know on Getters and Setters which include the key takeaways below.

### Key takeaways: 

1. Review field variables
2. Reasons for having getter and setters methods
3. Learn how to write getter and setter methods
4. See getters and setters methods working in code demonstration

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@mussooo 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
@mussooo, great topic. Make sure you provide a good number of hacks and go into lots of detail to provide enough value and uniqueness to our readers. Topic approved 🚀. 

Also, template literals might be a nice thing to cover also.

**Comment by mussooo** [comment]
@louisefindlay23, I have changed my topic to [this](https://github.com/section-engineering-education/engineering-education/issues/3139). Please make your views.

Thank you.

cc @hectorkambow

**Comment by hectorkambow** [comment]
> @louisefindlay23, I have changed my topic to [this](https://github.com/section-engineering-education/engineering-education/issues/3139). Please make your views.
> 
> Thank you.
> 
> cc @hectorkambow

The link links back to this topic?? 
🤔

**Comment by mussooo** [comment]
@hectorkambow, Sorry for that. I have changed the whole topic. I wanted you to give me the way forward. Should I continue with the new topic?
