### ISSUE TITLE
How to Create a Web Component with Vanilla JS

### ISSUE THREAD

**Issue by LeahKui** [section-engineering-education/engineering-education#3140]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to Create a Web Component with Vanilla JavaScript

### Introduction paragraph (2-3 paragraphs):
Web components are reusable and encapsulated HTML elements created using JavaScript. They let us create functionality that can be reused on other applications that we built with different technologies.

Web Components work in any web standard environment that supports basic HTML, CSS, and JavaScript. This article is a step-by-step guide on how to create a Web Component using Vanilla JavaScript.

### Key takeaways: 
1. What is a web component?
2. How do web components work?
3. Building a web component

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@LeahKui 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @LeahKui 
I believe this article will be very helpful. Just make sure you have original content that isn't available on other blog sites. Also check that your content does not conflict with other articles already on section.

topic approved :rocket:
