### ISSUE TITLE
C++ Database connectivity programming with my sql

### ISSUE THREAD

**Issue by Newton-cyber** [section-engineering-education/engineering-education#3141]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction paragraph (2-3 paragraphs):
In this article, I shall describe specifically Relational database Management systems to define, control and manupulate data. For programming examples, we will use the default TCP port number 3306 for running MSQL server. To acess the MSQL server, we will write some programs in C++ to connect to the database server at the given IP address and TCP port number(3306), issue the SQL commands, and process the results received.

### Key takeaways: 
1. setting up MYSQL  
2. install C++ database connectivity driver
3. Allocate a Connection object, for connecting to the database server.
4. Allocate a Statement object, under the Connection created earlier, for holding a SQL command
5. Write a SQL query and execute the query, via the Statement and Connection created.
6.process the query results

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Newton-cyber 
 to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 can be reopened once the first PR is merged.
