### ISSUE TITLE
Creating a React app using Vite

### ISSUE THREAD

**Issue by Neema-2016** [section-engineering-education/engineering-education#3142]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Creating a React app using Vite

### Introduction paragraph (2-3 paragraphs):
React is a front-end library used to create web applications user interfaces. To initialize a react project, one needs to set up the required packages and dependencies required to initialize and run the app using the **"npx create-react-app app-name"** command. This article, therefore, intends to teach an alternative of setting up a react project using Vite, a build tool instead of the normally used ***npx create-react-app app-name*** way.

### Key takeaways: 
1. Learn what Vite is.
2. Understand why it is efficient to use.
3. Learn how to set up a new react app with Vite

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Neema-2016 Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Great topic 🚀 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, It should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @Neema-2016
