### ISSUE TITLE
Creating a Simple Python Note Application with Flask and MongoDB Database

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#3144]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

Python is a very easy-to-learn language due to its user-friendly syntax. Moreover, python has many open-source libraries, and almost every use case of python has an existing library for that. So no need for immense amounts of coding in the respective use-case.

Python has several web application frameworks such as Django and Flask. Flash is an open-source, lightweight python web application framework. Flask is designed to make getting started quick and easy as it has a simple boilerplate to get, a simple application running. Thus very easy for beginners to stated and scaled up to the complex application.

To implement a Flask application, we will use MongoDB as the database. MongoDB is a cross-platform document-oriented database platform, classified as a NoSQL database. It uses JSON objects as its data tuples. When working with a web application, you might not be aware of the exact data format being sent, and a NoSQL database such a MongoDB would be a good solution for data handling and storage.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

1. A brief discussion of Python, Flask, and MongoDB in relation to this topic
2. Implement a Note Python App using the above technologies

- Setup and Configuration
- MongoDB connection with Flask
- Adding Flask Endpints
- Accessing and Modifying data

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@kimkimani 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
The title is just Flask? No introduction paragraph or Key takeaways as well. @kimkimani 

I'm going to close it. Please @ me when your topic-suggestion is ready and I will re-open it.

**Comment by kimkimani** [comment]
@ahmadmardeni1, I think it's all good now, requesting reopening.

**Comment by ahmadmardeni1** [comment]
Great topic 🚀 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any [existing EngEd articles](https://www.section.io/engineering-education/search/?q=flask) or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.  @kimkimani
