### ISSUE TITLE
Dependency injection in Flutter (Provider package)

### ISSUE THREAD

**Issue by NdoloBonface** [section-engineering-education/engineering-education#3146]
**Proposed title of article:**
Dependency injection in Flutter (Provider package)

**Introduction paragraph (2-3 paragraphs):**
Dependency injection in Flutter is an object-oriented technique that sends the dependencies of another object to an object.
The provider package is an easy-to-use wrapper around Inherited Widgets. It makes it easier to manage ,use and also provides a state management technique that is used for managing a piece of data around the app.

In this article we shall shall know how to implement dependency in flutter and the reasons for dependency injections .

**Key takeaways:**
-What is dependency injection ?
-Why do we need dependency injection in Flutter?
-How do you implement dependency in Flutter?
-How to get rid of flutter package.

**References:**
N/A

**Comment by NdoloBonface** [comment]
@paulodhiambo I opened an issue I would like you to review as requested.

**Comment by hectorkambow** [comment]
@NdoloBonface 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Great topic 🚀 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @NdoloBonface
