### ISSUE TITLE
Unsupervised Machine Learning with PyCaret

### ISSUE THREAD

**Issue by francis966** [section-engineering-education/engineering-education#3147]
### Proposed title of article
Unsupervised Machine Learning with PyCaret.

### Introduction paragraph (2-3 paragraphs):
Unsupervised learning (UL) is a type of algorithm that learns patterns from untagged data. The hope is that, through mimicry, the machine is forced to build a compact internal representation of its world and then generate imaginative content unlike in supervised learning where the is tagged.
In unsupervised learning models, they find the hidden patterns and insights from the given data. Unsupervised learning is majorly concerned with clustering.
Clustering is a method of grouping the objects into clusters such that objects with the most similarities remain in a group and have fewer or no similarities with the objects of another group. Cluster analysis finds the commonalities between the data objects and categorizes them as per the presence and absence of those commonalities.
We shall use the PyCaret python library in building our model for clustering, here we shall use PyCaret for segmenting countries into their respective continents.

### Key takeaways: 
1. Basics of unsupervised learning.
2. PyCaret basic for unsupervised learning.
3. Preparing data.
4. Creating a model using PyCaret.
5. Conducting clustering.
6. Checking model accuracy and saving our model.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@francis966 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Hello @francis966. This seems to be a super helpful and important topic. Please start working on the topic proposed. Let's ignite all the boosters on this one and deliver superior value to the reader. 

Let's be sure to provide value that we as developers feel is scarcely available out there on the web. Custom projects would be the best way to explain such concepts. We avoid projects and explanations easily available on documentation sites and blogs.

Cheers,
Lalith
