### ISSUE TITLE
How Brute Force Attack Occurs 

### ISSUE THREAD

**Issue by jaykip** [section-engineering-education/engineering-education#3148]
### Proposed title of article
How Brute Force Attack Occurs 

### Introduction paragraph (2-3 paragraphs):
A brute force attack occurs when malicious hackers use forceful attempts to break into an account and gain access to private information. Hackers use this attack to collect data or steal personal information and sell it to others. Additionally, they can use it to spread malware, phish victims, or carry out other illegal activities.

This article discusses why brute force attack is on the rise and explains how brute force attack happens. It also explains how to protect your system against such attacks.  

### Key takeaways: 

1. Why brute force attack is on the rise
2. How brute force attack happens (Simple brute force attack, Dictionary attack, Hybrid brute force attack, Reverse brute force attack, Credential stuffing)
3. Examples of brute force attack
4. Protection against brute force attack

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@jaykip 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by jaykip** [comment]
@ahmadmardeni1 My focus is sensitizing the reader on how they may become victims of brute force attacks and how to avoid such occurrences by deploying various protection tactics.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @jaykip
But it is better to close it. We are looking for programmer-centric concepts explained in fun and intuitive ways.

Please feel free to suggest an alternate topic to explore. 🚀
