### ISSUE TITLE
Generating Machine Learning Pipelines with TPOT in Python.

### ISSUE THREAD

**Issue by kelvinkimani501** [section-engineering-education/engineering-education#3150]
### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
A machine learning pipeline is a way to codify and automate the workflow it takes to produce a machine learning model. Machine learning pipelines consist of multiple sequential steps that do everything from data extraction and preprocessing to model training and deployment.
Here we shall use TPOT for the machine learning pipeline, TPOT is a python library that uses genetic programming behind the scenes to generate an optimized ML pipeline. It uses the concept of natural selection, survival of the fittest, and mutation to find the best machine learning model and the required parameters to produce the best result.
TPOT will enable us to automate some of the stages of the ML life cycle such as feature engineering, model building.
TPOT utilizes these 3 concepts
1. Selection: selecting the best
2. Crossover: crossbreed the selected best over and over to get the best of the best
3. Mutation: mutate the best to become even better.

### Key takeaways: 
1. Data Preparation.
2. Installing TPOT.
3. Using three concepts of TPOT in building our model, Selection, crossover, and mutation.
4. Implementing machine learning pipelines to automate feature engineering and model building.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Hello @kelvinkimani501. This seems to be a super helpful and important topic. Please start working on the topic proposed. Let's ignite all the boosters on this one and deliver superior value to the reader. 

Cheers,
Lalith
