### ISSUE TITLE
Local GitLab Repository Mirroring to an External GitLab Repository

### ISSUE THREAD

**Issue by carteblanchemunene** [section-engineering-education/engineering-education#3155]
### Proposed title of article
Local GitLab Repository Mirroring to an External GitLab Repository

### Introduction paragraph (2-3 paragraphs):
If you have long considered self-hosting your own Git server to use for personal projects, but never took the time to do so. Now that there is Proxmox which is capable to run containers/virtual machines for everything, I thought it was time to set up a local GitLab installation.

Ideally, you would like to push all updates to the local GitLab server and in turn have the updates be migrated to the remote repository on GitLab.com automatically. Fortunately this is possible with the free version of GitLab with the repository mirroring functionality! You may mirror a repository either by pushing updates or pulling updates. Pushing updates is free while pulling updates is not. This works out well because you only need to push updates to accomplish your goal.
### Key takeaways: 
-  A guide for Installation for Ubuntu Running on LXC Container in Proxmox and setting up Ubuntu locale.
- GitLab configuration.
- how to Export GitLab Project from GitLab.com.
- how to Import GitLab Project into Your Local GitLab Server.
- Configuring Repository Mirroring.
- Switching to your Local GitLab Repository.
- Verifying Proper Mirror Configuration

### References: 
N.A

**Comment by hectorkambow** [comment]
@carteblanchemunene 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by carteblanchemunene** [comment]
hello @hectorkambow what about this topic suggestion. Thank you

**Comment by ahmadmardeni1** [comment]
What do you think of this topic? @louisefindlay23 @WanjaMIKE @kayere

**Comment by carteblanchemunene** [comment]
hello @ahmadmardeni1 the reviewers you referred replied with a thumbs up emoji. Waiting your instructions.

**Comment by ahmadmardeni1** [comment]
Great topic 🚀 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours - Approved. @carteblanchemunene
