### ISSUE TITLE
Using Realm Database as an Alternative to SQLite and Coredata in Android

### ISSUE THREAD

**Issue by JoelKanyi** [section-engineering-education/engineering-education#3158]
### Introduction paragraph (2-3 paragraphs):
Realm mobile database is a lightweight database that can be an alternative to both SQLite and Coredata in your Android projects. It is open source and developer-friendly.

Realm is faster and has lots of modern features, such as JSON support, a fluent API, data change notifications, cross-platform, fast querying, and  fully encrypted all of which make life easier for Android developers.

In this tutorial, we are going to learn the basics of Realm for Android.

### Key takeaways: 
- What is Realm mobile database.
- Why use Realm.
- How is it different from other Mobile Database.
- Getting started with Realm in Android

### References: 
- https://realm.io/

**Comment by hectorkambow** [comment]
@JoelKanyi Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by JoelKanyi** [comment]
Thank you @hectorkambow

**Comment by kayere** [comment]
Good topic @JoelKanyi - approved. Please make sure your article does not cover what is already available in the docs.
