### ISSUE TITLE
Java Swing for Desktop Application

### ISSUE THREAD

**Issue by JosephAyoma** [section-engineering-education/engineering-education#3162]
### Proposed title of article
Java Swing for Desktop Application 

### Introduction paragraph:
Java Swing is part of Java Foundation Classes. It is used to create window based application which makes it suitable for developing desktop based application. It is built on top of abstract windowing toolkit application programming interface written in Java programming language. 
In this article, I will demonstrate how the common Java swing components are used in desktop application development. We will learn the basic setters and getters methods of the Java Swing components commonly used in desktop application. At the end of the article we will be able to create a usefully application sample which can interact with a user. 

### Key takeaways: 
1.	Describing and defining Java Swing Components setters methods
2.	Describing and Defining Java Swing Components getters methods
3.	Getting Started with Java Swing Components Action and Event Methods

### References: 
https://www.javatpoint.com/java-swing
https://www.section.io/engineering-education/introduction-to-java-swing/

**Comment by hectorkambow** [comment]
@josephayoma
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
@JosephAyoma Unfortunately, we already have an article covering an introduction to Java Swing here `https://www.section.io/engineering-education/introduction-to-java-swing/`. How will this article be different?

**Comment by JosephAyoma** [comment]
@WanjaMIKE From my issue Introduction to Java is part of the reference to my proposal. I am the author of  the article. The proposed  article forms part of the continuation whereby I will be discussing into details the methods (getters and setters) of Java swing components i.e. Basic Java Swing components used for desktop application.
The main key takeaways will be;
1. Setter Method of Java swing components.
2. Getter Method of Java Swing components
3. Action Event Methods of Java Swing component (JButton)
The proposed article will discus these methods into details citing (code) examples. The previous article gave basic introduction to the Java Swing components and UI design.

**Comment by JosephAyoma** [comment]
@WanjaMIKE Not exactly a part 2, it is a newer topic which will discuss about Java Swing component setters and getters, with code examples.

**Comment by JosephAyoma** [comment]
@WanjaMIKE am patiently waiting for your advice
