### ISSUE TITLE
Working with File Uploads In Streamlit Python

### ISSUE THREAD

**Issue by jamesomina99** [section-engineering-education/engineering-education#3166]
### Proposed title of article
Working with File Uploads In Streamlit Python

### Introduction paragraph (2-3 paragraphs):
Streamlit is an open-source Python library that makes it easy to create and share beautiful, custom web apps for machine learning and data science. In just a few minutes you can build and deploy powerful data apps.
File upload is very important in any web application, which allows upload and processing of any file format. In this tutorial, we will be working with the file uploads feature of streamlit - how to process Images,PDF,Docx,Txt,CSV.
We will add functionality in order to process files being upload in the streamlit app we have build such as image processing.
In this tutorial, we will be exploring streamlit file upload feature. With this feature, you can upload any type of file and use them in your app. To work with the file uploads you will have to use the st.file_uploader() function.

### Key takeaways: 
1. installing streamlit into our machine.
2. Working streamlit to make an application interface.
3. Using the st.file_uploader() function to upload various files such as images, doc, pdf.
4. File processing packages.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
@jamesomina99 Thanks for the topic suggestion. However, this is a tiny part of the streamlit library. Moreover, this part is well documented, and therefore, I suggest you explore new topics and projects with streamlit. I encourage you to come up with excellent ideas. Hope to see your new topic form soon. I will be closing this topic for now. Thank you :)
