### ISSUE TITLE
How to solve initial value problem using ODE45 in Matlab

### ISSUE THREAD

**Issue by josephodhis** [section-engineering-education/engineering-education#3170]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
MATLAB’s standard solver for ordinary differential equations (ODEs) is the function ode45. This function implements a Runge-Kutta method with a variable time step for efficient computation. ode45 is designed to handle the following general problem:
dx/dt = f(t,x),                           x(t0)  = xo
where t is the independent variable, x is a vector of dependent variables to be found and f (t, x) is a function of t and x. The mathematical problem is specified when the vector of functions on the right-hand side of Eq. (1), f (t, x), is set and the initial conditions,
x = x 0 at time t 0 are given. 
### Key takeaways: 
- Basic understanding of the ODE45
- Implementation of ODE45 in Matlab
- Applications of ODE45
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@josephodhis 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
What do you think of this topic? @lalith1403

**Comment by lalith1403** [comment]
Hello @josephodhis. Thanks for submitting the topic suggestion. I have a couple of queries. 

1. ODEs have been covered extensively and it is backed by a rich math literature. Can we discuss the value proposition of the idea proposed?
2. How will this article be different from that of the documentation present for the same library. As far as I know, this is a well covered library.

**Comment by josephodhis** [comment]
@lalith1403, i will be looking on how to solve the ODE45 initial value problem. I will also look at how to find the concentration along plug flow reactor using the ODE45.

**Comment by josephodhis** [comment]
@lalith1403 what do you have to say?
cc @srishilesh

**Comment by lalith1403** [comment]
Yes, thank you for clarifying. This is an interesting problem to discuss. I would suggest focusing on building the application. Thank you.
