### ISSUE TITLE
Introduction to Python Decorators

### ISSUE THREAD

**Issue by FREDERICO23** [section-engineering-education/engineering-education#3171]
### Proposed title of article
Introduction to Python Decorators

### Introduction paragraph (2-3 paragraphs):

In Python, a decorator is any callable Python object that is used to modify an existing function or a class. They simply add functionality to an existing code.

If you are not experienced with decorators and some functional programming concepts, you will consider decorators as a complicated concept to get into. Even though using decorators is always a walk in the park, writing them is not always as easy. In this article, we shall look into decorators, their usage, and how they are written.
 
### Key takeaways: 

* Understanding decorators
* Creating decorators
* Using/Applying decorators

### References: 
N/A

**Comment by mia-roberts** [comment]
Hello @FREDERICO23 , I am already working on the topic #2718
