### ISSUE TITLE
Getting started with Termux

### ISSUE THREAD

**Issue by Ykz-Jnr** [section-engineering-education/engineering-education#3174]
**Introduction**
`Termux` is a Linux environment application designed for android mobile phones. It is easily available in the play store and it requires no root access. It can be used to perform Kali Linux attacks by running commands on the termux terminal.
We will take a look at why you might want to have termux on your android device. We will also run some major commands that can be executed via termux. The user will be able to install tools to be used by running commands on the termux terminal.
The learner will also know different types of termux and how will choose the best depending on the users' environment.
Lastly, we will run a test attack using termux so we can learn how much we can do with it. 

**Key Takeaways**
The user should be able to:
1. Familiarize and understand termux
2. Install Termux on your android device
3. Install useful tools to be used in termux
3. Perform an attack using Termux 

**Reference**
N/A

**Comment by hectorkambow** [comment]
@Ykz-Jnr 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Koros-Meshack

After some careful consideration, this topic is way out of our preferred topics. And it is a very sensitive path to explore, Termux can be used for hacking.
We are looking for programmer-centric concepts explained in fun and intuitive ways.

Please feel free to suggest an alternate topic to explore. 🚀
