### ISSUE TITLE
Introduction to Web Scraping with JavaScript and Puppeteer

### ISSUE THREAD

**Issue by kimanikevin254** [section-engineering-education/engineering-education#3177]
### Introduction to Web Scraping with Javascript and Puppeteer

When developers need data for their web apps, they usually lookup for an API (Application Programming Interface), hoping that it will have the data they need for the app. This API is created by someone else and we expect it to have the exact data that we need. But this is not always the case. We may also need data from a certain website which unfortunately does not have an API. This is where web scraping comes in.

In this article, we are going to learn how we can get data from any website using vanilla JavaScript and Puppeteer. Puppeteer is a Node library that provides a high-level API to control Chrome or Chromium over the DevTools Protocol.

### Prerequisites:
- Basic knowledge of HTML and CSS.
- Intermediate JavaScript knowledge.
- Understanding of arrow functions in JavaScript.
- Understanding of asynchronous JavaScript.

### Key takeaways: 
- How to get data from any website.

### References: 
N/A

### Templates to use as guides
N/A

**Comment by hectorkambow** [comment]
@kimanikevin254 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Great topic 🚀 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

We actively sell products that aim to prevent web scraping.
Some websites do not allow web scraping. Therefore, ensuring permissions should be front and center with this article, the topic is okay as long as you lead with the legal issues.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @NdoloBonface
