### ISSUE TITLE
PHPUnit: The bigger picture

### ISSUE THREAD

**Issue by odongoalbert** [section-engineering-education/engineering-education#3179]
### Proposed title of article
PHPunit: The Bigger Picture

### Introduction paragraph (2-3 paragraphs):

This article is the first one in the series of articles that focus on `Unit Testing`, a well known test methodology. I will use `PHPUnit` as the main test tool for PHP Unit Testing. Once you get hold of the basics, getting started with PHPUnit is not that difficult.

Even a small software development project usually takes hours of hard work. During the course of development, a number of major and minor bugs and problems creep in the structure and code of the application. Developers usually try to work out the bugs during the process of development.

The problem is that there is no surefire way of ensuring that all the bugs have been worked out of the final code.

Another important aspect is the possibility of the introduction of further bugs when existing bugs are fixed. To address these problems, testing and QA are integral components of the software development process.

In this tutorial I will explain why we should write unit tests to cover the codes we are writing and the power of PHPUnit. At the end, we will write a simple test using PHPUnit.

### Key takeaways: 
1.What is Unit Testing?
2.Why do Unit Testing?
3.How to Install PHPUnit?
4.Basic Conventions to Write Unit Test Case

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@odongoalbert 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
