### ISSUE TITLE
 Classless Routing using OSPF Protocol

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#3180]
### Proposed title of article
Classless Routing using OSPF Protocol
### Introduction paragraph (2-3 paragraphs):
When packets are sent in large, and complex networks, they take various routes from source to destination. Some routes are longer and others shorter. In networking, packets do not need to take the scenic route. The fastest available route is always the best. Hence we need a protocol that will handle multiple routing areas and find the fastest available path for a packet from source to destination. Open Shortest Path First (OSPF) classless routing protocol is the best solution as it uses a routing metric of “cost” that in Cisco’s implementation based mainly on the bandwidth of a link. 
This tutorial will show the reader how we can apply the classless routing protocol to create fast, available routes. How to configure OSPF on the network, its operations, and the features. Verify the implementation of the OSPF protocol. With OSPF, your network can combine the automated processes with your own choices to make a network that you could easily troubleshoot.

### Key takeaways: 
The reader will be able to:
-Understand the operations, features of the OSPF protocol.
-How to Configure OSPF to propagate a default route
-How to verify OSPF implementation in a network.
### References: 
N/A

### Templates to use as guides
N/A

**Comment by hectorkambow** [comment]
@dentonya 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@dentonya 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #3180 via #3401
