### ISSUE TITLE
Understanding how to Create and Query Data in Cosmos DB 

### ISSUE THREAD

**Issue by mercie-nyakio** [section-engineering-education/engineering-education#3181]
### Proposed title of article
Understanding how to Create and Query Data in Cosmos DB 

### Introduction paragraph (2-3 paragraphs):
Cosmos DB is a document database that can be run in SQL API or MongoDB API modes. So, we can perform the different types of Query and can interact with the database at the grain of schema-free documents. Documents of a similar type are organized into a collection. In this article, we will discuss how to design documents or collection to fulfill the business requirements. Also, we will discuss how to use the SQL API to build applications that use these documents. 

So, at the end of this article, the reader can be able to get an idea about the following points: The fundamental concept of document models in Azure Cosmos DB, partitioning collections in Azure Cosmos DB is a concept and query data in a Cosmos DB database using the SQL API

### Key takeaways: 
- Overview of Documents and Collection with Relations
- Documents Structure in the Document Database
- Document System Generated Properties
- Partitioning Collections in Cosmos DB
- Perform Different Types of Queries on SQL-API Based Cosmos DB

### References: 
N/A

**Comment by hectorkambow** [comment]
@mercie-nyakio 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
