### ISSUE TITLE
Recovering Deleted Files Using Foremost

### ISSUE THREAD

**Issue by FINCH285** [section-engineering-education/engineering-education#3183]
### Proposed title of article

Recover Deleted Files With Foremost

### Introduction paragraph (2-3 paragraphs):
Foremost is a forensic program used to recover lost files based on their headers, footers, and internal data structures. It implements a technique known as data carving. It is free and comes with most Linux platforms. This makes it ideal to use in recovering deleted data in hard disk drives and pen drives.

In this tutorial, we will be showing stepwise how to use foremost to recover deleted files from a pen drive. We will then show how to use foremost to recover deleted files from a whole hard disk drive or a specific partition of the hard drive.

### Key takeaways: 

1. Installing foremost in a Linux platform.
2. Tools included in the foremost package.
3. Use foremost to recover deleted files of all types.
4. Use foremost to recover a specific file type.

### References: 

N/A

**Comment by hectorkambow** [comment]
@FINCH285 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
