### ISSUE TITLE
Handling React state management with Hookstate

### ISSUE THREAD

**Issue by marienjus** [section-engineering-education/engineering-education#3187]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Handling React state management with Hookstate

### Introduction paragraph (2-3 paragraphs):
Building React applications has a major challenge with managing state. Many libraries such as redux exist but are highly opinionated forcing us to use actions and reducers.
This is where [Hookstate](https://hookstate.js.org/) library comes in to simplify state management in React apps. Hookstate works almost exactly like the React useState Hook. It utilizes React hooks, and a couple of other impressive techniques to deliver great development experience and performance. Among its advantages include:
- First-class Typescript support
- Plugins System making it easy to use, add features and feature-rich
- Development Tools to trace, set state values, and breakpoints on state changes

### Key takeaways: 
- Setting up Hookstate in React
- A guide on Hookstate and its features
- Building a React application with Hookstate
- Creating, updating, and handling events and global store in Hookstate 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@marienjus 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@marienjus 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by marienjus** [comment]
Had closed due to my inactivity as the platform recommends
