### ISSUE TITLE
Getting Started with Image Data Pre-processing in Python

### ISSUE THREAD

**Issue by FREDERICO23** [section-engineering-education/engineering-education#3188]
### Proposed title of article
Getting Started with Image Data Pre-processing in Python

### Introduction paragraph (2-3 paragraphs):
In a machine learning project, we always start with data collection followed by data preprocessing or cleaning step
which needs to be gotten right for a better performing model. There are several techniques used to preprocess data (in this case image data). Examples include; image resizing, converting images to grayscale, etc. 

In this tutorial, we shall be looking at data pre-processing of images. Image preprocessing involves converting image data into a form that allows machine learning algorithms to solve it. It is often used to reduce the complexity and increase the accuracy of the applied algorithm.  

### Key takeaways: 
*  Understanding image preprocessing techniques and processes 
*  Data standardization
*  Geometric and color transformation or converting color to grayscale
*  Data augmentation

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by FREDERICO23** [comment]
@lalith1403 I opened a new issue I would like you to review as requested.

**Comment by lalith1403** [comment]
Yes. This would be a great topic to cover. We encourage authors to come up with articles that contain in-depth code and corresponding explanations. It would be great if you can cover all the concepts with corresponding code written from scratch. For example, explain how data augmentation works. What are the various techniques, and how are they useful? 

Topic Approved :)

**Comment by WanjaMIKE** [comment]
Closed #3188 via #3306
