### ISSUE TITLE
How to create your first flask app

### ISSUE THREAD

**Issue by isaiaholadapo** [section-engineering-education/engineering-education#3193]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to create your first flask app

### Introduction paragraph (2-3 paragraphs):
Flask is a micro web framework written in Python. It is called a micro framework because it does not require any particular tool or library. Flask is very light so depends on pre-existing third-party libraries to provide common functions

In this tutorial, I will walk you through the step by step process of creating a todo app using the flask framework. This is not just about coding but it also involves the planning process and how to fix any problem that comes along. 

### Key takeaways: 
Setting up Flask
Creating a task
Deleting a task
Marking a task as done
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@isaiaholadapo 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
@isaiaholadapo This article here `https://www.section.io/engineering-education/complete-guide-on-installing-flask-for-beginners/` covered most of your key takeaways. How will it be different?

**Comment by isaiaholadapo** [comment]
I will talk about how they can save their tasks to database using Postgresql and how to deploy it on heroku. I will also talk about crud operations in flasks

**Comment by louisefindlay23** [comment]
@WanjaMIKE, does this article contain enough unique value to be approved?

**Comment by WanjaMIKE** [comment]
> @WanjaMIKE, does this article contain enough unique value to be approved?

@louisefindlay23 Unfortunately, I believe its key takeaways are already covered in other published articles. @isaiaholadapo please feel free to suggest another topic.
