### ISSUE TITLE
Model View Template and Model View Controller Comparison.

### ISSUE THREAD

**Issue by Bradley8555** [section-engineering-education/engineering-education#3194]
### Proposed title of article
Model View Template and Model View Controller Comparison.

### Introduction paragraph (2-3 paragraphs):
A comparison between two common design patterns; model view template and model view controller, analyzing their merits and demerits, use cases, and key differences. Model view template (MVT) is implemented in Django while model view controller (MVC) is implemented in Laravel, these two will form the basis of the comparison and the key differences. 
MVT architecture is a design pattern to handle web applications. It has the model, view and template. The model helps to handle database. It is a data access layer which handles the data. The template is a presentation layer which handles user interface part completely, and MVC implements a user interface giving emphasis on separating data representation from the components which interact and process data. 
This article will enable the reader understand the two design patterns and how they are compared.

### Key takeaways:
The reader will be able:
- To know differences between the two patterns .
- Differentiate their use cases.
- To know the advantage of using one case over the other.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Bradley8555 Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
🤔 
@Bradley8555 
After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
