### ISSUE TITLE
Setting Up Hotspot On Kali Linux

### ISSUE THREAD

**Issue by lizpart** [section-engineering-education/engineering-education#3196]
### Proposed title of article
Setting Up Hotspot On Kali Linux

### Introduction paragraph (2-3 paragraphs):
Hotspot enables you to share your network connection with other devices so that they can also be able to access the internet. The hotspot creates WiFi over which the devices connect to.
In Kali Linux by default, the hotspot is not configured.
In this tutorial, I will be showing you how to set up a hotspot in Kali Linux both in the terminal and graphically. 
### Key takeaways: 

- Finding wireless drivers.

- Setting up configuration files.

- Setting up a hotspot from Ethernet connection.

- setting up a hotspot from a wireless connection.

### References: 
N/A

**Comment by hectorkambow** [comment]
@lizpart 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@lizpart 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
