### ISSUE TITLE
Using GitHub Desktop to create a GitHub repository and add a new or existing project.

### ISSUE THREAD

**Issue by borosteve** [section-engineering-education/engineering-education#3197]
### Proposed title of article
Using GitHub Desktop to create a GitHub repository and add a new or existing project.

### Introduction paragraph (2-3 paragraphs):

Writing code and building solutions in accordance with requirements and processes is the essence of software development. With time and various contributors, code management gets more difficult. Multiple developers collaborate on the same project and produce code on a daily basis in the real world. Without the right tools or platforms, keeping track of modifications and merging such scripts is a headache and time-consuming task.

Source code management include not only the safe storage of code, but also the tracking of modifications, the resolution of conflicts, and the merging of various contributors' contributions. For source code management, there are a number of tools and platforms available, each with its own set of functionality.

This article focuses on GitHub, which is one of the most popular cloud-based open-source communities for managing source code and git repositories.

### Key takeaways:
 In this article, the reader will understand:

1. What is Git
2. What is GitHub
3. What is GitHub Desktop
4. Installation and Authentication of GitHub desktop
5. How to create a Git repository
6. Add a new project to the repository
7. Add an existing project to the repository
8. Make and commit changes to the project

### References: 
N.A

**Comment by hectorkambow** [comment]
@borosteve 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
🤔 
@borosteve 

After some careful consideration, it struck us that this topic may covered widely on the official docs or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

Please feel free to suggest an alternate topic to explore. 🚀
