### ISSUE TITLE
Power of software testing and clean code

### ISSUE THREAD

**Issue by Taiwrash** [section-engineering-education/engineering-education#3198]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article

**Power of software testing and clean code**

### Introduction paragraph (2-3 paragraphs):

Software failure could be hazardous and dangerous ranging from business loss, loss of life, economic degradation and other very dangerous things a failure in software can cause. This can be prevented when software are well tested while they were written in clean and maintainable way.

### Key takeaways: 
Readers will learn but not limited to the following.

- Importance of software testing
- Types of testing
- How to write clean code
- How to write maintainable code
- Best practices in variable naming, functions naming and code Maintenance.

### References: 
Book: Clean code and software testing

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Taiwrash 
NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)

**Comment by Taiwrash** [comment]
Sorry, I have completed this particular article if because of one PR at a time makes you close it. Please I will like it to be open for now and the other to be closed. Thanks

**Comment by hectorkambow** [comment]
@Taiwrash 
After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
