### ISSUE TITLE
Understanding PHP exception handling

### ISSUE THREAD

**Issue by awinomackrine** [section-engineering-education/engineering-education#3207]
### Introduction paragraph (2-3 paragraphs):

Exception handling is an important concept in PHP programming. It comes in handy when handling run-time errors which are also called exception errors. The main purpose of exception handling is to ensure maintenance of the normal application execution.

In this article we’ll be discussing at length What exceptions are, Why the need for execution handling and the different types of exception. We will also be discussing the events that occur when exception is triggered and finally the benefits of using execution handling as opposed to everyday error handling techniques.

### Key takeaways: 
1. The reader will be able to understand what exceptions are and the eventually understand exception handling.
2. The reader will be  well acquainted with various forms of exception handling and their applications.
3. The reader will be able to understand  The events associated with exception handling a the benefits associated with it as opposed to error handling.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@awinomackrine 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@awinomackrine 

Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
