### ISSUE TITLE
Introduction to PHP RegEx

### ISSUE THREAD

**Issue by stevekwachie** [section-engineering-education/engineering-education#3208]
### Introduction paragraph (2-3 paragraphs):
PHP regular expressions commonly known as RegEx are pattern matching algorithms that are performed in expressions. RegEx use everyday arithmetic operators to create complex expressions that can be used for email address and IP address validation.

In this article I will be explaining what regular expressions are, the need to use the regular expressions and finally the different types of regular expressions used in PHP and their functionalities. I will also be discussing how to implement the above discussed types of RegEx in detail.

### Key takeaways: 
1. The reader will understand what PHP RegEx is.
2. The reader will understand the different types of PHP RegEX.
3. The reader will be able to understand the different areas of implementation of RegEx and be able to use the Regular Expressions.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@stevekwachie 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@stevekwachie 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
