### ISSUE TITLE
Understanding PHP callback functions

### ISSUE THREAD

**Issue by achiengrhoda** [section-engineering-education/engineering-education#3209]
### Introduction paragraph (2-3 paragraphs):
A callback function is a function that is passed as an argument in another function and is executed in that function. Any existing function can be used as a callback function. Callback functions come in handy in practical coding in areas surrounding output buffering, time measurement, caching and also database transactions.

In this article I will  the different instances of use of callback functions, The reasons for preference of callback functions,  I will also discuss how to implement callback functions in PHP code and finally the practical use of callback functions in PHP.

### Key takeaways: 
1. The reader will be able to understand what callback functions are and why they are used in PHP.

2. The reader will be able to learn the different instances of use of callback functions. 
3. The reader will be able to learn how to use the PHP callback functions in practical coding.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@achiengrhoda 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@achiengrhoda 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@achiengrhoda 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
