### ISSUE TITLE
Methods in C#

### ISSUE THREAD

**Issue by dentex22** [section-engineering-education/engineering-education#3210]
### Proposed title of article
Understanding Methods in C#
### Introduction paragraph (2-3 paragraphs):
Methods play a crucial part in code reusability. They are blocks of code that allow programmers to pass data as parameters. They can only run when called. In C# this is not an exception. In this article, we will get more familiar with what methods are and why we need to use them. We will show the reader how to declare methods, what parameters are and what a method’s signature is, how to call a method, how to pass arguments of methods and how methods return values in C#. 

In the end, detailed examples of created methods will accompany the content of this article and how to use (invoke) whenever necessary. This will help the reader practice with learned material and familiarised with method creation and invocation.
### Key takeaways: 
The reader will learn:
- What methods are.
- Usage of methods.
- Method creation and invocation using C#
### References: 
N/A

### Templates to use as guides
N/A

**Comment by hectorkambow** [comment]
@dentex22 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
@dentex22 Kindly, how could this topic differ from the official documentation?

**Comment by dentex22** [comment]
> @dentex22 Kindly, how could this topic differ from the official documentation?

yes... it's going to base more on the practical implementation which will add value to the one reading it

**Comment by dentex22** [comment]
> > @dentex22 Kindly, how could this topic differ from the official documentation?
> 
> yes... it's going to base more on the practical implementation which will add value to the one readi

**Comment by dentex22** [comment]
> > > @dentex22 Kindly, how could this topic differ from the official documentation?
> > 
> > 
> > yes... it's going to base more on the practical implementation which will add value to the one readi

cc @WanjaMIKE

**Comment by WanjaMIKE** [comment]
@dentex22 
Upon giving your article an overview it seems that there is much we could add for the reader(s). We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or via many other blog sites.
