### ISSUE TITLE
Creating and using methods in C# 

### ISSUE THREAD

**Issue by Tonybishop11** [section-engineering-education/engineering-education#3211]
### Proposed title of article
Creating and using methods in C# 

### Introduction paragraph (2-3 paragraphs):
In this tutorial, C# programming, methods play a vital role, and if you want to be an efficient programmer, you must arrange your method controls effectively. If some methods include secret codes that you don't want your developers to see, you can make them private. Method in C# is a discrete code block that comprises a series of statements that conduct specific activities. Methods must be declared in either a class or a struct, with the relevant parameters specified.

Methods are generally useful for increasing code reusability by avoiding code duplication. If the same functionality is required in numerous places, we can write a single method with the required capability and utilize it elsewhere in the application.

### Key takeaways: 
1. What are Methods in C#
2. Syntax of C# Methods
3. Using methods in the C# programming language.
- Static Method in C# 
- C# Methods with No Return Type and Parameters.
- C# Passing Parameters to Methods

### References: 
N/A

**Comment by dentex22** [comment]
@Tonybishop11 hey what's up!! why are resubmitting the article suggestions I have already suggested and submitted.
#3210 
cc @hectorkambow @ahmadmardeni1

**Comment by WanjaMIKE** [comment]
This topic is already been covered.

**Comment by Tonybishop11** [comment]
the topic was suggested at the same time it seems we had the same topic in mind, now who suggested earlier?@WanjaMIKE

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Tonybishop11 
As @dentex22 said, it is the same topic, and he submitted it first.

Please feel free to suggest an alternate topic to explore. 🚀
