### ISSUE TITLE
How to implement Logging with Pino-logger in a Node.js application.

### ISSUE THREAD

**Issue by sardug10** [section-engineering-education/engineering-education#3214]
### Proposed title of the article
How to implement Logging with Pino-logger in a Node.js application?

### Introduction paragraph (2-3 paragraphs):
Logging on its own is an important aspect of any application. It is because it helps developers comprehend what it is that their code is doing, and can assist developers to save hours of debugging work. Also, one of the key features of logging is to store every bit of information about the flow of the application.
With Pino as a dependency for a node.js application (having 7.3k stars on Github) and since it is becoming more famous than Winston, it becomes very effortless to implement logging and even storing these logs in a separate log file.

### Key takeaways: 
* You will study how to configure logging services with different logging levels.
* You will learn how to prettify the logs in your terminal and whether or not to include the JSON response in your logs
or not.
* At the end of this tutorial, you will know how to implement logging in your application using Pino-logger. Also, how
to store those logs in a separate file for future references of your application.

### References: 
N/A

### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@sardug10 
Seems like a very cool topic - but regarding Node.js we have more than enough currently in our EngEd library as we did a big push the last few months and are currently not accepting any more Node.js articles to publish for the time being.

Please feel free to suggest an alternate topic to explore.
