### ISSUE TITLE
Serialization in C#

### ISSUE THREAD

**Issue by Tonybishop11** [section-engineering-education/engineering-education#3216]
### Proposed title of article
Serialization in C#

### Introduction paragraph (2-3 paragraphs):
The purpose of this article is to provide an overview of C# Serialization. Serialization is the process of converting an object instance into a data stream, and the state of the object instance is turned into a data stream so that it may be transferred over different networks and stored in a storage place.
This is an advantage of serialization because it allows you to send the converted data stream across different networks in a format that is cross-platform compatible and saves the converted stream data in a permanent or non-persistent object state so that a duplicate can be made at a later time.

### Key takeaways: 
1. Steps of C# Serialization Object
2. C# Serialization in action
3. Types of serialization that are supported by C#
4. C# program to demonstrate the concept of Serialization.

### References: 
N/A

**Comment by hectorkambow** [comment]
@Tonybishop11 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Tonybishop11 Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@Tonybishop11 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by Tonybishop11** [comment]
Hello, can anyone reopen this for me!
