### ISSUE TITLE
Getting Started With MongoDB Dashboard using Node.js

### ISSUE THREAD

**Issue by bhanjibrilliant** [section-engineering-education/engineering-education#3218]
### Proposed title of article
Getting Started With MongoDB Dashboard using Node.js

### Introduction paragraph (2-3 paragraphs):
For a pretty decent amount of time, doing analytics with MongoDB required additional overhead compared to modern SQL RDBMS and Data Warehouses associated with aggregation pipeline and MapReduce practices. While this approach allowed one to craft advanced custom tailored aggregation algorithms it required additional knowledge of how to build and maintain it.

To fill this gap, MongoDB released the MongoDB connector for BI, which acts as a MySQL server on top of your MongoDB data. Under the hood it bridges existing aggregation mechanisms to the MySQL protocol, allowing standard MySQL clients to connect and issue SQL queries.

In this  tutorial we’ll setup the MongoDB connector for your local MongoDB instance and spin up a Node.js application that provides an analytics API, query cache, and orchestration using the Cube.js analytics framework. Cube.js can be used as a standalone server or it can be embedded as part of an existing Node.js web application.

### Key takeaways: 
1.Setting up the MongoDB connector for BI
2.Importing test dataset
3.Spinning up a Cube.js application
4.Building a Dashboard

**Comment by hectorkambow** [comment]
@bhanjibrilliant 
Seems like a very cool topic - but regarding Node.js we have more than enough currently in our EngEd library as we did a big push the last few months and are currently not accepting any more Node.js articles to publish for the time being.

Please feel free to suggest an alternate topic to explore.
