### ISSUE TITLE
Machine Learning in Cybersecurity

### ISSUE THREAD

**Issue by James-Gitau** [section-engineering-education/engineering-education#3219]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Machine Learning in Cybersecurity

### Introduction paragraph (2-3 paragraphs):
In the recent past, Cybersecurity has been making headlines in many industries regularly there is no doubt that Machine Learning is picking up some slack in the field of cybersecurity.

This article describes the capabilities of how machine learning has evolved within cyberspace, it being a subset of Artificial Intelligence. It also seeks to explain the role of Machine Learning in Cybersecurity.

### Key takeaways: 
1.	The biggest barrier to human intelligence is language.
2.	The biggest battle in threat intelligence is balancing time and context of what is to capture and analysed as well as understanding the behaviour.
3.	Machines play a great role in strengthening cybersecurity, this is through Artificial Intelligence, Deep Learning, and Machine Learning processes.

### References: 
Lakshmanarao, A. & Shashi, M. (2020). A survey on machine learning for cybersecurity.International Journal of Scientific & Technology Research.
https://cset.georgetown.edu/wp-content/uploads/Machine-Learning-and-Cybersecurity.pdf
Apruzzese, G., Ferretti, L., Marchetti, M., Colajanni, M., & Guido, A. (2018). On the Effectiveness of Machine and Deep Learning for Cyber Security, Conference paper.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@James-Gitau 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Hello @James-Gitau, Thanks for submitting the topic suggestion. I would like to understand the aim of the article better. In the references, you have added a couple of papers. Will you be discussing the concepts in the paper? What would be the unique value proposition of the article.

**Comment by James-Gitau** [comment]
@lalith1403 My article will be uniques because 

1. It focuses on explaining why there is a growing need for cybersecurity automation through machine learning.  
2. It highlights the current enhancements and unique capabilities which are an improvement on traditional machine learning in cybersecurity.
3. New techniques currently implemented for machine learning in cybersecurity.

**Comment by lalith1403** [comment]
Thank you for the topic suggestion @James-Gitau, however, this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀

**Comment by James-Gitau** [comment]
@lalith1403 This is noted. However, From your previous articles on your page 
https://www.section.io/engineering-education/the-role-of-artificial-intelligence-for-smarter-cybersecurity/
explains the theoretical bits on machine learning the intentions of my article was to expound more on the  technicality interms of Threat hunting and Vulnerability Management.

**Comment by lalith1403** [comment]
Let's make sure to bring additional value than what is present on the web. We would love to see original content that dives deep into a few concepts than scratch the surface on many. Kindly keep the suggestion in mind while writing the article. Topic approved.

**Comment by hectorkambow** [comment]
@James-Gitau 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
