### ISSUE TITLE
Using developer tools in browsers

### ISSUE THREAD

**Issue by Ernest715** [section-engineering-education/engineering-education#3221]
### Proposed title of article
Using developer tools in browsers

### Introduction paragraph (2-3 paragraphs):

Developer tools are computer programs used by software developers to create, edit, maintain, support and debug other applications, frameworks and programs. Also referred to as Software Development, developer tools exists in many forms such as code editors, linkers, debuggers and performance analysis tools. The choice in choosing a developer tool is determined by usefulness of the tool, compatibility of the tool with other programs and company standards.

Developer tools must be compatible with the browser in which its to be installed in order for it to execute the functions effectively. Developer tools are used in browser such as Chrome, Mozilla Firefox and Microsoft Edge. Software developers need to check the compatibility and carry out test runs. Some of the uses of developer tools include improving efficiency through planning of workflows, maintaining networks and supporting other system applications.

### Key takeaways: 

•	Common developer tools and their uses
•	Installing developer tools in browsers
•	Running and checking compatibility of developer tools in browsers
•	Advantages of using developer tools in browsers
•	Challenges in using developer tools in browsers

### References: 
n/a

### Templates to use as guides
n/a

**Comment by hectorkambow** [comment]
@Ernest715 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Good afternoon @Ernest715 and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

Please feel free to suggest an alternate topic to explore.
