### ISSUE TITLE
Web Automation with Selenium

### ISSUE THREAD

**Issue by wobin1** [section-engineering-education/engineering-education#3224]
### Proposed title of the article
Web Automation With Selenium

### Introduction paragraph (2-3 paragraphs):
Selenium is a set of python libraries that helps developers interact with the web to enable the automation of web processes.
The ability to enable software robots to automatically perform processes and tasks on the web is known as 
WEB AUTOMATION. These processes may include; searching the web, deleting emails, filling forms, logging in to a website, and many other processes. The need for speed in performing tasks is a necessity in our modern world, This makes the automation of repetitive tasks necessary.
In this guide, we will be looking at how to use selenium to automate basic web tasks, to give you a background of how Selenium works.
### Key takeaways: 
At the end of this guide the reader will understand;
-How to install and set up Selenium
-How to automate a search in a browser
-how to automate login 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@wobin1 Kindly, `Automation with Selenium` is covered here `https://www.section.io/engineering-education/automation-testing-in-selenium/`. How will this article be different?

**Comment by wobin1** [comment]
@WanjaMIKE
The published article is on Automation testing using the selenium software while my article will be a guide on how to write a python script to automate interaction with a webpage using the selenium python library.
