### ISSUE TITLE
Automating Django deployments with Ansible and Fabric

### ISSUE THREAD

**Issue by elizabeth962** [section-engineering-education/engineering-education#3226]
### Automating Django deployments with Ansible and Fabric
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

### Introduction paragraph (2-3 paragraphs):
[Ansible](https://www.ansible.com) is an open-source software provisioning, configuration management, and application-deployment tool enabling infrastructure as code. Ansible Automation Platform provides an enterprise framework for building and operating IT automation at scale.

[Fabric](http://www.fabfile.org) is a high-level Python library designed to execute shell commands remotely over SSH, yielding useful Python objects in return.

The article will explain how to automate Django deployments from Github to a Google compute engines' virtual machine instance.

### Key takeaways: 
1. Setting up Google compute engines' virtual machine instance.
2. Writing Ansible configuration files.
3. Automating deployments from Github to virtual machine instances.

### References: 
[Introduction to Google compute engine](https://codelabs.developers.google.com/codelabs/cloud-compute-engine#0)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@elizabeth962 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@elizabeth962 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@elizabeth962 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
