### ISSUE TITLE
Getting started with Django polymorphic models

### ISSUE THREAD

**Issue by flavianadhiambo** [section-engineering-education/engineering-education#3228]
### Getting started with Django polymorphic models
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Microservices are a way to organize complex software systems. Instead of putting all your code into one app, you break your app into microservices deployed independently and communicate with each other.

[Flask](https://flask.palletsprojects.com/en/2.0.x/) is a micro web framework written in Python. It is classified as a microframework because it does not require particular tools or libraries.

[gRPC](https://grpc.io/) is a modern open-source, high-performance Remote Procedure Call (RPC) framework that can run in any environment. It can efficiently connect services in and across data centers with pluggable support for load balancing, tracing, health checking, and authentication.

 The tutorial will teach the readers how to develop Flask microservices using gRPC and deploy them to a Kubernetes cluster.

### Key takeaways: 
1. Creating Microservices in Flask.
2. Communication between the services.
3. Monitoring Flask application health.
3. Deploying Microservices to a Kubernetes cluster.

### References: 
1. [gRPC](https://grpc.io/)
2. [Flask](https://flask.palletsprojects.com/en/2.0.x/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@flavianadhiambo 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@flavianadhiambo 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@flavianadhiambo

**Comment by hectorkambow** [comment]
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by WanjaMIKE** [comment]
Closed #3228 via #6113
