### ISSUE TITLE
Next Generation Javascript

### ISSUE THREAD

**Issue by shegz101** [section-engineering-education/engineering-education#3231]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Next Generation Javascript

### Introduction paragraph (2-3 paragraphs):
  Basically , next generation JavaScript simply means the various versions of Ecmascript . One thing you should know is that as a web developer , improvement in languages is inevitable , even browsers get constantly updated , libraries constantly created . 
  In other words , it's the nature of human to constantly improve.Javascript was created by Netscape browser (specifically Brendan Eich ) , netscape submitted javascript to ECMA international to update and standardize it.
    Now , you should know that ECMA Script is javascript. The first version was created in 1997, ever since then it has grown to be one of the world's most widely used general-purpose programming language.
   In this article , i will walk you through next gen javascript , Es6 ( ECMA Script version6 ) which constitutes the greatest part of next gen javascript and some additional new features from Es7 , Es8 , Es10 . Es6 , created in 2015 has introduced a lot of new features that has made coding very nice and clean using javascript. 

### Key takeaways: 
  The 5 most important things a reader should know after reading this article are:
1.How to use arrow functions
2.Start replacing var with let and const
3.using template strings when fetching an api.
4.How to export and import when implementing libraries or frameworks
5.Have idea of the Es features from es6 to es10

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by FREDERICO23** [comment]
@shegz101 kindly re-work on your issue. Follow the laid guidelines

**Comment by ahmadmardeni1** [comment]
Kindly fill out your suggestion and add a title. @shegz101

**Comment by WanjaMIKE** [comment]
Thank you for the topic suggestion @shegz101 , however this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
