### ISSUE TITLE
Integrating YouTube videos into a Django app

### ISSUE THREAD

**Issue by Sajeyks** [section-engineering-education/engineering-education#3233]
### Proposed title of the article
Integrating YouTube videos into a Django app

### Introduction paragraph (2-3 paragraphs):
Modern Organisations are featuring both pictures videos on their websites to strengthen their content and to also promote their YouTube channels. It is very convenient because using YouTube unlike directly uploading a video saves you space, cost, and compatibility issues. And Django is on the rise, this seems like an important skill.

We will create a simple blogging app and embed youtube videos in it so that when we write a blog, we can add a youtube video in it.

### Key takeaways: 
1. You will create a simple Django app that you shall use to render YouTube videos .
2. Creating a frontend that supports embedded youtube videos.
3. Adjusting the Youtube videos into different sizes.

### References: 
N/A

**Comment by hectorkambow** [comment]
@Sajeyks 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
@Sajeyks could it just involve adding the `iframes` into the website or you will use an API?

**Comment by Sajeyks** [comment]
> @Sajeyks could it just involve adding the `iframes` into the website or you will use an API?

I will use a python package

**Comment by WanjaMIKE** [comment]
> > @Sajeyks could it just involve adding the `iframes` into the website or you will use an API?
> 
> I will use a python package

Okay, noted.

**Comment by hectorkambow** [comment]
@Sajeyks 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
