### ISSUE TITLE
Socket Programming in Php

### ISSUE THREAD

**Issue by fabulousDesigns** [section-engineering-education/engineering-education#3234]
### Proposed title of article
Socket Programming in Php

### Introduction paragraph (2-3 paragraphs):
Every programming language comes with a method for implementing server-client communication. The program uses this method to allow data to be sent between the server and the client. This technique is also available in PHP, as it is in other computer languages. Socket programming is a programming style in which the server and the client are both applications that require a connection to be created between them in order for them to communicate. In terms of PHP, it also allows us to apply the socket programming idea. In this article,you will learn how to use  PHP programming language to perform socket programming.
### Key takeaways: 
1.Socket Class Methods
2.Socket Client
3.Socket Server
4.Simple TCP/1P Server
5Simple TCP/IP Client

### References: 
N/A

**Comment by hectorkambow** [comment]
@fabulousDesigns 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by jerimkaura** [comment]
Hello @fabulousDesigns  how will your article be different from [this.](https://html.form.guide/snippets/javascript-form-validation-using-regular-expression/) or [this one](http://www.tutorialspark.com/javascript/JavaScript_Regular_Expression_Form_Validation.php)

**Comment by fabulousDesigns** [comment]
My article will have an overview of what Regex is all about and on top that I will use modern JavaScript and to wrap up the form will give learners some skills of what neumorphism is

**Comment by WanjaMIKE** [comment]
@fabulousDesigns check out this `https://www.section.io/engineering-education/password-strength-checker-javascript/`. I see regex is covered there

**Comment by fabulousDesigns** [comment]
@WanjaMIKE thanks for the heads up but i was going to write something totally different from what you had suggested earlier.I have decided to change the issue to Socket Programming in PHP😊.

**Comment by WanjaMIKE** [comment]
issue closed
