### ISSUE TITLE
Creating Serverless Functions ( Faas ) with AWS Lambda and Golang

### ISSUE THREAD

**Issue by Bamimore-Tomi** [section-engineering-education/engineering-education#3236]
### Introduction paragraph (2-3 paragraphs):
Serverless architecture is a new paradigm that is being used in the development of modern applications. The term "serverless" refers to the abstraction of "servers" from application development. Function-as-a-Service (FaaS) is a serverless method of running modular code on the cloud. FaaS allows you to write code that can be triggered by events. For example, when a user clicks on a button in your web application, a specific cloud function is executed.

In this article, we will not only look at how to use FaaS, but we will also create some for others to use. We'll be working in Golang, but the same method can be applied to Python, Node, Java, or any other language or framework you want.

### Key takeaways: 
* Readers will get familiar with Golang's syntax
* Readers will have a general understanding of what serverless computing is
* Readers will learn how to use AWS Lambda environment and related tools
* Readers will learn how to create and use serverless functions in their Go applications.

### References: 
https://www.cloudflare.com/learning/serverless/glossary/function-as-a-service-faas/

**Comment by hectorkambow** [comment]
@Bamimore-Tomi 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
Great topic 🚀 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any [relevant EngEd articles](https://www.section.io/engineering-education/search/?q=serverless) in yours and build a unique project - Approved. @NdoloBonface

**Comment by WanjaMIKE** [comment]
Closed #3236 via #3479
