### ISSUE TITLE
C++ or C# for Game Development?

### ISSUE THREAD

**Issue by del-ui** [section-engineering-education/engineering-education#3237]
### Introduction paragraph (2-3 paragraphs):
C# and C++ are both object oriented programming languages used in used different mutual application one of the being Game Development

C++ was developed first and has become one of the most popular language used for game development. Other languages developed later like C# have brought in factors to be considered when selecting the right language.

C# is growing popular due to its compatibility with different game engines. It is mostly used for .NET platforms and unity game engine.
Considerations to help a programmer chose his/ her right language will be discussed

### Key takeaways: 
1. Software requirements and installations
2. Compatible / Cross platform
3. User friendliness and complexity
4. When to use C#
5. When to use C++

### References: 
N/A

**Comment by hectorkambow** [comment]
@del-ui 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
@del-ui 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
