### ISSUE TITLE
Abstraction in Java

### ISSUE THREAD

**Issue by watosole** [section-engineering-education/engineering-education#3240]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Abstraction in Java

### Introduction paragraph (2-3 paragraphs):
Abstraction refers to the process of displaying the important details of a program while hiding the background details from the user. Only the essential details are displayed to the user while the non-essential or trivial are hidden because the user is not required to know them. The practice of identifying only the required attributes of an object while discarding the irrelevant information is known as data abstraction. 
The features and behaviors of an object assist to distinguish it from other things of the same sort, as well as classify and group them. Using a simple example, we can think of abstraction like driving a vehicle. We only deal and know what is required of us but don’t know the mechanism behind the movement. Interfaces and abstract classes are used to achieve abstraction in Java. This article will go through how we can accomplish complete data abstraction using interfaces and Java abstract class and methods.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.
1. What is abstraction
2. Ways to achieve data abstraction
3. Java abstract class and methods.
4. Complete abstraction using interfaces
5. Encapsulation vs Data Abstraction
6. Advantages of Abstraction

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@watosole 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
@watosole 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
