### ISSUE TITLE
How to create API using Flask and Python

### ISSUE THREAD

**Issue by isaiaholatunbosun** [section-engineering-education/engineering-education#3242]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to create API using Flask and Python

### Introduction paragraph (2-3 paragraphs):
Let me start by defining API according to IBM "An API is a set of defined rules that explain how computers or applications communicate with one another. APIs sits between an application and the web server, acting as an intermediary layer that processes data transfer between systems."

API stands for application programming interface, it acts as an intermediary that allows two applications to talk to each other. Let me give you an example if an e-commerce website wants to accept payment from its client using Stripe, they will need to integrate Stripe API on their platform for them to accepts payments from their client. So Stripe API is the intermediary between the e-commerce website and Stipe. It allows both platforms to communicate easily.

### Key takeaways: 
Learn what an API is and when you can you use it
Know how to create API
Know some principles of good API design

### References: 
https://www.ibm.com/cloud/learn/api

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@isaiaholatunbosun 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic is already covered here `https://www.section.io/engineering-education/flask-crud-api/`
