### ISSUE TITLE
What leads to Technical Debt in Software Development and how can we Manage it 

### ISSUE THREAD

**Issue by mumbi00** [section-engineering-education/engineering-education#3246]
### Proposed title of article
What leads to Technical Debt in Software Development and how can we Manage it 

### Introduction paragraph (2-3 paragraphs):
Technical debt (TD) is a broad concept that encompasses many of the decisions made and shortcuts taken during the software development cycle. It happens when teams are working through set tasks, updating features, and dealing with bugs – and it sometimes comes with negative consequences.

Negative outcomes caused by technical debt typically take the form of badly designed code, deterioration of productivity, additional unplanned costs, delivery delays, and degradation in the quality of the product. 

### Key takeaways: 

1. Causes of technical debt in software development. 
2. Types of technical debts and how to address them. 
3. Avoiding technical debts 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@mumbi00 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
@mumbi00 Kindly, is this a software-centric topic? Will you be building an application? We usually focus more on software topics rather other associated issues.

**Comment by louisefindlay23** [comment]
@mumbi00, it's been a while since we requested more information from you in order to access your topic suggestion's viability. We are closing this now to make more room in the queue but feel free to open it back up again when you're ready to provide the info, @WanjaMIKE requested.
