### ISSUE TITLE
Genie, Slide-in, Jelly, and scale Pop-up Notification effects

### ISSUE THREAD

**Issue by prograte** [section-engineering-education/engineering-education#3247]
### Proposed title of the article

Genie, Slide-in, Jelly, and scale Pop-up Notification effects

### Introduction paragraph (2-3 paragraphs)

Websites need notifications to display burning events or additional information. Pop-ups, used to pass notifications, are sweet if used effectively and at the right time. Notification effects depending on the main website theme bring a website's unique taste and signature look.

In this article, you will learn how to apply some of these notification effects. These are the Genie, Slide-in, Jelly, and scale Pop-up notification effects. You will see how eye-catching these effects are dependent on the type of information being displayed.

### Key takeaways

By the end of this article, you will learn how to apply some of these notification effects to a webpage. These are the:

- Slide-in effect
- Genie effect
- Scale growth effect
- Jelly pop-up effect

You will also get to know some of the notification effects which we can use on your webpage and when to use them.

### Pre-requisites

For you to flow easily with this article, you need to have some of these basics:

- Basics of HTML.
- Basics of CSS.
- JavaScript interactions.
- Web development IDE. I definitely recommend Visual Studio Code IDE. You can download it from [here](https://code.visualstudio.com/)

### References

N/A

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@prograte 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
@prograte 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@prograte 
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date.
