### ISSUE TITLE
Data Encryption and Decryption with Quick Response (QR) Codes in Android

### ISSUE THREAD

**Issue by MaurineM** [section-engineering-education/engineering-education#3252]
*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
Data Encryption and Decryption with Quick Response (QR) Codes in Android

### Introduction paragraph (2-3 paragraphs):
Quick response (QR) codes are a type of barcode, or scannable sequence, that can hold a variety of information such as website links, payment information, phone numbers, and even freebies.

Many apps employ QR codes to present data in a machine-readable format. These codes are used to represent data in a safe way that only machines, not humans, can read.

In this tutorial, We'll look at how to generate and scan a QR code in an Android App.

### Key takeaways:
By the end of this tutorial, the reader will:
1. Understand what are QR codes and how they encrypt data.
2. Learn how to generate and scan QR codes in an Android App.
3. Learn how to handle and configure camera operations and permissions.

### References: 
N/A

**Comment by hectorkambow** [comment]
@MaurineM 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
@MaurineM 
Great topic 🚀 , make sure it matches the following:

Adds value beyond what is in the official docs and what is covered in other blog sites.
To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.
Please reference any relevant EngEd articles in yours and build a unique project - Approved. @NdoloBonface
