### ISSUE TITLE
Setting up an environment for Python 3

### ISSUE THREAD

**Issue by Muchiri021** [section-engineering-education/engineering-education#3258]
### Proposed title of the article

Setting up an environment for Python 3

### Introduction paragraph (2-3 paragraphs):

When dealing with any programming language, the first step is to create an environment that will allow you to run your code. You may examine your work for syntax errors through a well environment. In addition to Python 3, you'll need an interpreter to translate your code to a machine-readable language for execution.
The environment paths on Windows, Mac OS, and Linux are all distinct. The environment for python 3 code execution should be compatible with the device operating system. This article will provide programmers with basic knowledge that will enable them to obtain the necessary software to run the codes on a new device.

### Key takeaways: 

1. Local environment setup
2. Getting python
3. Setting up python
4. Running python

### References: 
N/A

**Comment by hectorkambow** [comment]
@Muchiri021 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by lalith1403** [comment]
Good evening @Muchiri021. Thank you for submitting the topic suggestion form. This topic has been covered in this [article](https://www.section.io/engineering-education/data-science-setup/). I encourage you to submit another issue. I will be closing this issue for now. Thank you. 

Lalith
