### ISSUE TITLE
Understanding the Flutter Getx ecosystem for state management.

### ISSUE THREAD

**Issue by Lekwacious** [section-engineering-education/engineering-education#3259]
### Proposed title of article
Understanding the Flutter Getx ecosystem for state management.

### Introduction paragraph (2-3 paragraphs):
State management enables the sharing of application state between screens, across your app. Put differently, it allows you to share data from one UI to another so that when the state of your app changes, you change the state, and that triggers a redraw of the user interface. Flutter traditionally uses the Stateful Widget to manage state. While this works, but as your app grows bigger with nested widgets, it becomes a little difficult to pass data from a parent widget to a child widget and vice versa. In this kind of situation, you will have to pass the data through the constructors of the children widgets. The side effect is that data are passed to widgets that don't need them, just because they are within the widget tree. Also, the business logic will be tightly coupled to the User interface.

The GetX state management package solves this problem and many more. GetX is an extra-light and powerful solution for Flutter. It combines high-performance state management, intelligent dependency injection, and route management quickly and practically. It helps Developers achieve a high level of productivity through easy and pleasant syntax without sacrificing the maximum performance your application can deliver. It allows for total decoupling of the View, presentation logic, business logic, dependency injection, and navigation. This helps to achieve clean code by default.

 In this tutorial, we will build a simple Flutter mobile application to demonstrate the power of the GetX package.

### Key takeaways: 
- How to setup Flutter project and configure  dependencies
- How to use GetX as a state management tool
- Using Obx to maximize the power of reactive programming
- Exploring the Navigator Manager.
- How to use the GetBuilder sub ecosystem to manage state.
- Reusable component of the GetX ecosystem.
- Combining two approaches using MixinBuilder

**Comment by hectorkambow** [comment]
@Lekwacious 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
What do you think of this topic? @zolomohan You have experience with Flutter.

**Comment by WanjaMIKE** [comment]
@ahmadmardeni1 I think its okay. State management is a critical component in Flutter. I don't think the Getx component has been covered yet.

**Comment by ahmadmardeni1** [comment]
Thank you @WanjaMIKE 

Great topic 🚀 @Lekwacious, make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
