### ISSUE TITLE
Working with Access Modifiers in C#

### ISSUE THREAD

**Issue by Ushter21** [section-engineering-education/engineering-education#3261]
### Proposed title of article
Working with Access Modifiers in C#

### Introduction paragraph (2-3 paragraphs):
Access Modifiers are keywords in a program that describe how accessible a member, class, or datatype is. These are mostly used to prevent unintended data tampering by third-party programs or classes.  Access modifiers are used in C# to control the accessibility of types and type members.

### Key takeaways: 
1. Advantage and disadvantages of keyword in C#
2. Types of access modifiers with examples
3. Accessibility levels

### References: 
N/A

**Comment by hectorkambow** [comment]
@Ushter21 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
@Ushter21 I think just focusing on the private keyword by itself will not make a quality article. There are numerous articles already covering this. How will the article differ from this documentation?

**Comment by Ushter21** [comment]
hello, @WanjaMIKE I`ve decided to change the topic instead.

**Comment by WanjaMIKE** [comment]
Okay, create a new topic issue

**Comment by Ushter21** [comment]
@WanjaMIKE initially was to cover how to use private keyword in C# but changed the issue to Working with Access Modifiers in C#
