### ISSUE TITLE
How To Build A React App WithTypeScript

### ISSUE THREAD

**Issue by Babatunde13** [section-engineering-education/engineering-education#3262]
### Introduction paragraph (2-3 paragraphs):
React is one of the most popular and best front-end libraries as of today this has made a lot of developers make it their primary library used for creating front-end applications. Typescript on the other hand is a strict and statically typed programming language which makes our javascript code more predictable. As developers, our goal is not just to create products but to create products that we can always predict their behavior, this is one of the main reasons why Typescript was created. With Typescript, we can create predictable react applications. 

This article will demonstrate how to build a simple application while explaining the core concepts of React and Typescript.

### Key takeaways: 
1. How to create a react app with typescript
2. Declaring types in typescript
3.  State and props in functional components
4. State and Props in class based components
5. Event types

### References: 
1. [typescript - react](https://www.typescriptlang.org/docs/handbook/react.html)
2. [react docs](https://reactjs.org/)
3. [typescript docs](https://www.typescriptlang.org/)

**Comment by hectorkambow** [comment]
@Babatunde13 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by srishilesh** [comment]
@Babatunde13 

Sounds like a great topic. I don't find any such topics here at Section.

Please make sure you don't overlap with either of these articles:
- https://www.section.io/engineering-education/typescript-static-typing/
- https://www.section.io/engineering-education/a-friendly-beginner-guide-to-typescript/
- https://www.section.io/engineering-education/javascript-vs-typescript/

You could probably utilize these links in your article.

Topic approved
