### ISSUE TITLE
Auto reminder mail system using python

### ISSUE THREAD

**Issue by jamila-laureen** [section-engineering-education/engineering-education#3268]
### Proposed title of article
Auto reminder mail system using python

### Introduction paragraph (2-3 paragraphs):
Maybe you are prone to forgetting to send emails to your co-workers, tenants asking for rent or even monthly subscription pay request email to your subscribers. These tasks can be automated by a system that uses python to setup a reminder and sends it at the time specified.

Python comes with the built-in smtplib module for sending emails using the Simple Mail Transfer Protocol (SMTP). This library ensures secure and safe sending of emails. The library is light ans easy to use.  We are going to take advantage of this library to build a mailing system that sends emails upon schedule.

### Key takeaways: 
1. Setting up reminders in python
2. Using STMP to send secure emails in Python
3. Sending HTML into Python emails
4. Reminder mail system using python
5. Sending bulk emails

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@Babatunde13
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
We do already have [an article](https://www.section.io/engineering-education/how-to-send-email-in-django/) covering this topic using Django. @jamila-laureen 

Please feel free to suggest an alternate topic to explore. 🚀
