### ISSUE TITLE
Deploying a Flask application to Google Compute Engine

### ISSUE THREAD

**Issue by ryanjonnes** [section-engineering-education/engineering-education#3269]
### Proposed title of article
Deploying your application to Google Virtual Machine

### Introduction paragraph (2-3 paragraphs):
Google provides a deployment virtual machine that relieve users from the acquisition of complex and expensive infrastructure required to run some application. Through their Infrastructure as a Service (IaaS) platform, Google provides an underlying infrastructure with easy setup for deployment of most applications.

This tutorial is a guideline on how to deploy an application on Google Compute Engine. I am a JavaScript fanatic so in my explanation, I will use Python to build a Flask web application application as a starting point. I will take the reader through the process of building the application to final deployment where we access the application from a unique IP address.

### Key takeaways: 
1. Working with Google Cloud Platform(shell & editor)
2. Building application on Google Cloud Platform
3. Creating virtual machine on Google Cloud Shell
4. Deploying applications to Google Virtual Machines.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@Babatunde13
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by srishilesh** [comment]
@ryanjonnes 

Sounds like a good topic!

Could you brief a little about what application you're trying to build? Do you mean to dockerize them and deploy on Google cloud - like shown in [this](https://www.section.io/engineering-education/docker-images-on-google-cloud/) article?

I also see one [another article](https://www.section.io/engineering-education/building-serverless-contact-form/) on deployment in Google cloud. How would yours be different from that? (I understand that the application would be different, and it wouldn't be a server less application)

And, I think the title could be modified to "Deploying [SPECIFY THE TYPE OF APPLICATION] application using Google Compute Engine". What do you say?

For eg. "Deploying a React application using Google Compute Engine".

**Comment by ryanjonnes** [comment]
Hello @srishilesh , I think i might not have explained it clearly but i am working with Node.js.

**Comment by ryanjonnes** [comment]
I am not going to user Docker. I am focusing my development on NodeJs application, creation of a virtual machine and deployment to Google virtual machine.

Let me know if that sound alright.

**Comment by srishilesh** [comment]
@ryanjonnes 

Sounds great.

Topic approved.

**Comment by hectorkambow** [comment]
@ryanjonnes 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by ryanjonnes** [comment]
Hello @srishilesh , would you please open this issue, I have finished writing the article. Sorry for delay.

**Comment by srishilesh** [comment]
@ryanjonnes Reopened

**Comment by hectorkambow** [comment]
@ryanjonnes 
Thank you for suggesting another topic.

Seems like a very cool topic - but regarding Node.js we have more than enough currently in our EngEd library as we did a big push the last few months and are currently not accepting any more Node.js articles to publish for the time being.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by ryanjonnes** [comment]
Hello, this article will not be explicitly about Node.js. It covers deployment of compute engine using Node.js as one of the tech stack. Kindly let me know your thoughts.

Thank you @hectorkambow

**Comment by mercymeave** [comment]
Hello @hectorkambow 

As communicated by @ryanjonnes, He changed the article to deployment using flask.
