### ISSUE TITLE
Uses and benefits of using Grafana

### ISSUE THREAD

**Issue by Annpurity** [section-engineering-education/engineering-education#3273]

**Comment by WanjaMIKE** [comment]
@Babatunde13
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
@Annpurity I will suggest reopening a new issue with the appropriate information
