### ISSUE TITLE
understanding nmap commands

### ISSUE THREAD

**Issue by muyagafranklyne** [section-engineering-education/engineering-education#3274]
### Proposed title of article
Understanding nmaps commands

### Introduction paragraph (2-3 paragraphs):
Security is key in networks. To implement this we can use Nmap,  a network scanner used to manage and secure networks. It sends packets through networks and analyses the responses to discover host and services on a computer network.
Administrators can use nmap to be able to  map their networks and security scans.The tools also provides features for exploring networks,finding open ports, ping sweeps and OS detection. This article will help one understand the installation, how to run nmap and be able to do port scanning and network mapping. 

### Key takeaways: 
 1 . How to install and run nmap
 2 . Port scanning
 3. Network mapping
 
### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@muyagafranklyne 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
We do already have [an article](https://www.section.io/engineering-education/nmap-network-scanner/) covering this topic.

Please feel free to suggest an alternate topic to explore. 🚀
