### ISSUE TITLE
How to Connect an Android Application to a MySQL Server

### ISSUE THREAD

**Issue by domiwanja** [section-engineering-education/engineering-education#3277]
### Proposed title of article
How to Connect an Android Application to a MySQL Server

### Introduction paragraph
Database is an important component in any application. It allows developers to store and retrieve information easily. Today, many applications depend on the Firebase Realtime Database. However, as many users sign up, Firebase becomes difficult and costly to maintain.

Connecting your application to a MySQL server can help avoid these challenges. This database allows you to structure information and consume it in your application. Apart from hosting charges, a MySQL server does not have other extra costs.

### Key takeaways: 
- Understand what a MySQL server entails.
- Connect an Android app to MySQL server.
- Debug any errors.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@domiwanja 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by Kayere** [comment]
Good topic @domiwanja  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your android article very beneficial.

**Comment by hectorkambow** [comment]
@domiwanja 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
