### ISSUE TITLE
Implementing View Binding in Android using Kotlin

### ISSUE THREAD

**Issue by valerio140** [section-engineering-education/engineering-education#3278]
### Proposed title of article
Implementing View Binding in Android using Kotlin

### Introduction paragraph (2-3 paragraphs):
Viewbinding is an exciting feature that was introduced in Android development a few years ago. It allows one to link data to the main UI easily. In case of any data changes, the UI will update instantaneously. 

Viewbinding is, therefore, a critical component in Android app development. It can help developers in avoiding a lot of  boilerplate code. This means that it will much easy to deliver quality and productive applications.

### Key takeaways: 
- Understand viewbinding
- Implement viewbinding in an Android application
- Understand its benefits and advantages

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@valerio140 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by valerio140** [comment]
@Kayere I will create a new app that is completely unique to the existing documentation. Thanks

**Comment by Kayere** [comment]
Good topic - approved. Make sure to add more unique content to differentiate your article from the official documentation. Looking forward to reviewing your article🚀.

**Comment by hectorkambow** [comment]
@valerio140 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
