### ISSUE TITLE
Digital clock in C++

### ISSUE THREAD

**Issue by sabin254** [section-engineering-education/engineering-education#3281]
### Proposed title of article
Digital clock in C++

### Introduction paragraph (2-3 paragraphs):
It is an application that allows for a personal clock that starts at a custom set time and shows the time from that point onwards.
It is a simple digital plan clock developed using  basic C++ concepts that show hour,minute and second.The requirement for this program are just the basic concepts of the data types,variable,manipulators,control systems,conditional statements etc

### Key takeaways: 
1.What is the digital clock in C++
2.Steps involved in creating digital clock in C++
3.Examples in C++

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@sabin254 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
good topic @sabin254 - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.

**Comment by hectorkambow** [comment]
@sabin254 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by WanjaMIKE** [comment]
closed #4275 via #4547
