### ISSUE TITLE
How to build Simple server routing in php

### ISSUE THREAD

**Issue by Juskam** [section-engineering-education/engineering-education#3283]
### Proposed title of article
How to build simple server routing in php

### Introduction paragraph (2-3 paragraphs):
A routing system is the part of the web application that maps an HTTP request to a request handler. An HTTP request consists of a header and optionally a body. The header contains information about the request.

A routing system works by mapping an HTTP request to a request handler based on the request method and path specified in the URL of the request. 
### prerequisites: 
1. Basic PHP knowledge including familiarity with PHP global variables.
2. An understanding of object oriented PHP.
3.An understanding of basic http methods.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@Juskam 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@Juskam 

To help avoid a backlog queue, we are only accepting one article topic/pr approved at a time 👍 can be reopened once the first PR is merged.
