### ISSUE TITLE
Creating a Shopping Cart using Arrays and Objects using vanilla JavaScript

### ISSUE THREAD

**Issue by twish-254** [section-engineering-education/engineering-education#3284]
### Proposed title of article
Creating a Shopping Cart using Arrays and Objects using vanilla JavaScript

### Introduction paragraph (2-3 paragraphs):
There are many ways of building a shopping cart. In this tutorial, I will guide you on how to create a shopping cart using arrays and objects.

The approach that we will use looks as follows. 

We will initially have 2 arrays. One holding the curated list of items to buy, and the other one empty, to hold the items in the cart. We will first display the items in the first array. We will then add an item to the second array and increment the count property in each item, on click. We will decrement the counter and delete the item from the array when the counter reaches zero.

We will use the Javascript event listeners to handle these activities.

Before proceeding, you are required to have some knowledge on the following JavaScript methods:
- Array.push()
- Array.pop()
- EventTarget.addEventListener()

### Key takeaways:
By the end of this tutorial, the reader will be able to:
- Display the shopping list and cart.
- Add items to the cart on click.
- Decrement the item count on click using event listeners.
- Delete items from the cart.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@twish-254 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by louisefindlay23** [comment]
Hi, @twish-254. Thanks for submitting a topic suggestion. Can you tell me how your article differs from those of a similar topic such as this [Smashing Magazine article](https://www.smashingmagazine.com/2014/02/create-client-side-shopping-cart/) and also [this](https://www.smashingmagazine.com/2019/08/shopping-cart-html5-web-storage/) one?

**Comment by twish-254** [comment]
@louisefindlay23 Shopping cart using html5 and web storage uses local storage and has Paypal intergration while mine doesn’t.

The thing making my article different from those two is that it deals with the adding to cart mechanism only. It doesn’t deal with Checkout, Paypal. etc.

**Comment by louisefindlay23** [comment]
Thanks, @twish-254. Topic approved 🚀
