### ISSUE TITLE
Reversing array in python

### ISSUE THREAD

**Issue by owinojoseph** [section-engineering-education/engineering-education#3290]
### Proposed title of Article
Reversing array in python programming

### introduction
 An array is a collection of items stored at contiguous memory locations. The idea is to store multiple items of the same type together. This makes it easier to calculate the position of each element by simply adding an offset to a base value, i.e., the memory location of the first element of the array (generally denoted by the name of the array).

   Array can be handled in Python by a module named array. They can be useful when we have to manipulate only a specific data type values.

### Key takeaways: 
By the end of the tutorial, the reader should be able to understand how to:

-  Changes the sequence of elements of the given array and returns the reverse sequence
-  Returns an iterator that accesses the given sequence in the reverse order.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@owinojoseph 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @owinojoseph 
We believe that the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
