### ISSUE TITLE
Password validation form with CSS, JavaScript 

### ISSUE THREAD

**Issue by owinojoseph** [section-engineering-education/engineering-education#3293]
### Proposed title of article
How to create password validation form with CSS and JavaScript

### Introduction paragraph (2-3 paragraphs):
Password validation should contain strong input of numbers this can be: uppercase and lowercase letters, letters and numbers, special characters and should be 6 to 20 characters long.
### Key takeaways: 
The reader should be able to understand how to:

- Create strong password in there web development forms.
- Should know the properties of strong password during creation of application form.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@owinojoseph
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
@owinojoseph Unfortunately, you can only suggest one topic at a time - until the PR is published. I am closing this one.
