### ISSUE TITLE
Image Manipulation and upload with ReactJS, NodeJS and Cloudinary

### ISSUE THREAD

**Issue by NyongToro** [section-engineering-education/engineering-education#3294]
### Introduction:
The rise in popularity of social media websites and applications such as Instagram, Facebook, TikTok, twitter, etc. has seen an astronomical rise in media and multi-media media upload by users of the internet.  The essential feature of modern social networking websites is the ability to handle media optimization and upload.
	The genius combination of React and Cloudinary has provided an exceptional tool to developers around the world in solving the challenge of image manipulation, compression and upload while reducing the cost of operating a server and cloud storage infrastructures. Although there are a few methods of solving the above challenge, the primary focus of this article is in the use of ReactJS, NodeJS and Cloudinary.
### Key Takeaways:
At the completion of this article the reader is guaranteed to understand and also equipped with the knowledge of implementing the following
i.	Image resizing and cropping operations with ReactJS
ii.	Creating image read-stream and write-stream in NodeJS
iii.	Understand and implement lossless compression with react and Cloudinary
iv.	Image upload with ReactJS, NodeJS, and Cloudinary
v.	Adding and removing animations in images with ReactJS 
### References:
https://bestofreactjs.com/catalog/react-image-manipulation_newest_1

**Comment by WanjaMIKE** [comment]
@NyongToro 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@NyongToro 
Seems like a very cool topic - but regarding Node.js we have more than enough currently in our EngEd library as we did a big push the last few months and are currently not accepting any more Node.js articles to publish for the time being.

Please feel free to suggest an alternate topic to explore.
