### ISSUE TITLE
Solving Linear Equations in Matlab

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#3298]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction 
Mathematical problems involving equations of the form Ax=b, where A is a matrix and x and b are both column vectors are problems in linear algebra, sometimes called matrix algebra. Engineering and scientific disciplines are rife with such problems. Thus, an understanding of their setup and solution is a crucial part of the education of many engineers and scientists. 
MATLAB provides a powerful and convenient means for finding solutions to these problems, but, as we will also see, the solution is not always what it appears to be. We will see in this article how to solve these problems using Matlab since Matlab provides the best environment for solving matrix problems as it is a matrix laboratory 

### Key takeaways: 
- Basic understanding of linear algebra.
- Various ways of solving linear algebra.
- Matlab code for solving linear algebra.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@Koros-Meshack
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by srishilesh** [comment]
@jumapaul 

This sounds like a vast topic to me.

Could you please elaborate more on what type of linear algebra problems are you going to address? Would it be like explaining the mathematical concept behind it, and implementing them in Matlab?

**Comment by jumapaul** [comment]
@srishilesh basically, here I will be looking at the simultaneous linear algebraic equations, and the various types of problems such as undetermined problems, overdetermined problems and ill-conditioned problems. All this will be covered in this article.

**Comment by srishilesh** [comment]
@jumapaul 

Great.

In addition to these, based on [this](https://www.section.io/engineering-education/mathematics-for-machine-learning/) article, you could discuss on these topics as well:
- Eigenvalues and Eigenvectors
- Matrix Operations, i.e., addition, subtraction, multiplication, transpose, and inverse.
- Vector Spaces and Norms
- Orthogonalization and Orthonormalization
- Eigen decomposition of a matrix

This would be a great value add and continuation to the above mentioned article.

Just make sure to discuss these concepts, before getting into its implementation.

Topic approved.

Thanks.

**Comment by jumapaul** [comment]
Hello @srishilesh this the article I was telling you about,, it's linear algebra but specifically on simultaneous equations,, where under this I will talk about the various types of problems and how to handle them.

**Comment by srishilesh** [comment]
@jumapaul 

Great.

Since your article is more focused on solving Simultaneous linear equations in Matlab, I think it would be better if we rename the article title to "Solving Linear Equations in Matlab".

Please feel free to suggest if you come across a more catchy title.

Thanks.
