### ISSUE TITLE
Windows rootkit review, analysis and removal after a ransomware attack.

### ISSUE THREAD

**Issue by sheldonaswani** [section-engineering-education/engineering-education#3299]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Windows rootkit review, analysis and removal after a ransomware attack.

### Introduction paragraph (2-3 paragraphs):
A rootkit is a malicious computer program designed to provide continued privileged access to a computer while actively hiding its presence from the user. 
This article will explain to the end user what malicious activities a rootkit performs once after a ransomware attack on the end user computer. It will also explain how one can detect and remove the malicious software.

### Key takeaways: 
1. How to setup a windows rootkit?
2. How to detect a rootkit and use a backdoor?
3. How to remove the rootkit and disinfect the computer after a ransomware attack?

### References: 
N.A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@Koros-Meshack
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @sheldonaswani 
We are looking for programmer-centric concepts explained in fun and intuitive ways.

Please feel free to suggest an alternate topic to explore. 🚀
