### ISSUE TITLE
Manipulating object states in Django using Finite State Machine

### ISSUE THREAD

**Issue by teevyne** [section-engineering-education/engineering-education#3300]
### Proposed title of article
Manipulating object states in Django using Finite State machines

### Introduction paragraph (2-3 paragraphs):
Finite State Machine (FSM) is one of the most viable design patterns widely used in the software engineering world.  Imagine a requirement where, for any object, the present state of the object has to be changed to another state or a set of states, in response to internal or external inputs, it becomes pertinent that there is a provision - a system - that implicitly and dynamically helps you manipulate this state, without having to write too much code or worry much about unnecessary details

A real-life example where FSM works perfect is with the traffic light. The changing states here would be the colours; red to yellow and yellow to green and vice versa. The influencing factor here would be timing interval between each colour state. To demonstrate how this works, we would be working through a tutorial where we will be build a system  to track a cylinder's movement based on the state that it has per time. We will work with Django - a Python-based framework, with the embedded database - SQLite - that comes shipped with Django.

### Key takeaways: 
- What is finite state machines?
- How are they better than session operations and management
- Points to note when choosing approach to changing a state from one value to another
- Advantages of using FSM
- Other approaches that challenge FSM

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@teevyne 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Great topic 🚀 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @teevyne

**Comment by teevyne** [comment]
@louisefindlay23 Hi, I do not quite understand what you did about my issue. Could you please explain? I had been looking forward to having it assigned to someone

**Comment by teevyne** [comment]
@louisefindlay23 Hi. Thank you for checking. What would you say is the status of my PR? Asking to know.

**Comment by louisefindlay23** [comment]
> @louisefindlay23 Hi. Thank you for checking. What would you say is the status of my PR? Asking to know.

A reviewer has not been assigned yet, @teevyne. As soon as the articles submitted prior to yours have been reviewed, a peer reviewer will look at your article.

**Comment by teevyne** [comment]
> > @louisefindlay23 Hi. Thank you for checking. What would you say is the status of my PR? Asking to know.
> 
> A reviewer has not been assigned yet, @teevyne. As soon as the articles submitted prior to yours have been reviewed, a peer reviewer will look at your article.

thank you for replying. I was curious because most PR's before and even after mine have received some form of attention. So, I was thinking might had an issue. Thanks again
