### ISSUE TITLE
Building a simple JavaScript router using Window Event Listeners

### ISSUE THREAD

**Issue by nancy-maina** [section-engineering-education/engineering-education#3307]
### Proposed title of article
Building a simple JavaScript router using Window Event Listeners

### Introduction paragraph (2-3 paragraphs):
In a JavaScript application, the router is a component that is responsible for routing requests to their appropriate view.

It is responsible for displaying a view, and for determining which view to display based on the request. Consider a case scenario in a single page application where the user is first logged in and then navigates to the home page.

The router works by watching for changes in the URL and displaying the appropriate document. Every time the URL changes, the router checks to see if the new URL matches any of the routes that have been defined. If it does, the router displays the appropriate view.

In this tutorial, we will create a simple JavaScript router to demonstrate the basic concepts of routing in a JavaScript application.

### Key takeaways: 
By the end of this tutorial, the reader will be able to:
1. Define a route in a JavaScript application.
2. Register templates and views.
3. Create a simple JavaScript router.
4. Use the router to display a view.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@nancy-maina 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Good topic @nancy-maina - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. Please make sure your article does not overlap with any EngEd article and adds value to the official documentation.

**Comment by hectorkambow** [comment]
@nancy-maina 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by nancy-maina** [comment]
I have opened a pull request to fix this issue. Please reopen this issue @hectorkambow

**Comment by WanjaMIKE** [comment]
Closed #3307 via #3835
