### ISSUE TITLE
LRU Cache Implementation in Javascript

### ISSUE THREAD

**Issue by erixbiz** [section-engineering-education/engineering-education#3309]
Proposed title of the article
LRU Cache Implementation in C#

Introduction:
In-memory caches such as Memcached and Redis are key-value stores between your application and your data storage. Since the data is held in RAM, it is much faster than typical databases where data is stored on a disk. RAM is more limited than disk, so cache invalidation algorithms such as least recently used (LRU) can help invalidate 'cold' entries and keep 'hot'
data in RAM.

Key takeaways:
At the end of this article the learner will be able to:

Understand what LRU cache is
Data structures used to build an efficient LRU cache algorithm
Implement LRU cache using C#

References:
N/A

**Comment by WanjaMIKE** [comment]
@erixbiz 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
What do you think of this topic? @zolomohan You have experience with C#.

**Comment by erixbiz** [comment]
@ahmadmardeni1  I would wish to inquire about the progress of this topic. Thank you

**Comment by erixbiz** [comment]
I am also able to implement the same using Javascript

**Comment by erixbiz** [comment]
I am able to implement the same using Javascript

**Comment by ahmadmardeni1** [comment]
Great! It is not about the language you are going to use, it is about the concept and if it is unique.

Could you take a look at this topic suggestion when you have the chance? Since you have expertise in JavaScript, I thought you'd be the best person to reach. @Kayere

**Comment by Kayere** [comment]
Great topic @erixbiz - approved. Looking forward to review and hopefully publish your article.
