### ISSUE TITLE
Build RESTful services in Go with an idiomatic approach.

### ISSUE THREAD

**Issue by MahanteshR** [section-engineering-education/engineering-education#3311]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Build RESTful services using Go with an idiomatic approach.

### Introduction paragraph (2-3 paragraphs):
Go, also known as goLang, is the brainchild of Rob Pike, Robert Griesemer, and Ken Thompson.

Go is:
* a statically typed language: the type of the variable is known during the compile time.
* similar to C but has garbage collection and concurrency, making it stand out from the other languages.

RESTful services are some of the most common practices used across software industries. In this tutorial, we will see how to build RESTful services in Go with an idiomatic approach using the standard package. We will be building an API that returns a Coffee object data.

### Key takeaways: 
* the role of handler and serveMux interface.
* use the encoding/JSON package.
* write HTTP handlers with an idiomatic approach.
* implementing RESTful services in Go.

### References: 
* https://www.loggly.com/use-cases/logging-in-golang-how-to-start/
* https://pkg.go.dev/net/http#ServeMux
* https://pkg.go.dev/net/http#Handler

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@MahanteshR 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Great topic 🚀 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.  @MahanteshR
