### ISSUE TITLE
Indexers in C#

### ISSUE THREAD

**Issue by mukono10** [section-engineering-education/engineering-education#3313]
### Proposed title of article
Indexers in C#

### Introduction paragraph (2-3 paragraphs)
The concept of indexers is analogous to that of properties. In many aspects, indexers are similar to properties in terms of language features. Indexers make it possible to have indexed properties, which are properties that are referred by one or more arguments. Those arguments are used to create an index into a set of values. Indexers are most commonly used in types that have the primary goal of encapsulating an internal collection or array.

Smart arrays are the most common name for C# indexers. A C# indexer is also a class property that allows you to use the features of an array to access a member variable of a class or struct. This keyword is used to generate indexers in C#. In C#, indexers can be used on both classes and structs.

### Key takeaways: 
1. Indexer Syntax
2. Arrays and Vectors
3. Multi-Dimensional Maps

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@mukono10 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
@mukono10, thanks for submitting your topic suggestion. Can you tell me how your article differs from similae Indexers in C# tutorials?

**Comment by mukono10** [comment]
@louisefindlay23 I beg to pardon is it similae or similar

**Comment by louisefindlay23** [comment]
@mukono10, similar. Apologies for the typo.

**Comment by WanjaMIKE** [comment]
Closing due to the plagiarism report.
