### ISSUE TITLE
File handling with Flutter

### ISSUE THREAD

**Issue by jerimkaura** [section-engineering-education/engineering-education#3316]
### Proposed title of the article
File handling with Flutter

### Introduction paragraph (2-3 paragraphs):
There are instances where one would need to download a write into, read from upload, or download a file while using flutter. This is where one will apply file handling effectively. Take for instance an application like Google Photos that reads image files from your mobile device and uploads them to the server. The same happens with google drive.

In this tutorial, we will discuss how to use the `flutter_handle_file` package  to read and write into files and `firebase` to build and application that uploads and downloads file from a server.

### Key takeaways: 
1. Understanding the `flutter_handle_file` package.
2. Reading and writing into files
3. Uploading and downloading files using Firebase.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@jerimkaura 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @auxesis 
This topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
