### ISSUE TITLE
 How to Parse JSON in Dart/Flutter

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#3318]
### Proposed title of the article
How to Parse JSON in Dart/Flutter

### Introduction paragraph (2-3 paragraphs):
Parsing JSON is a very common task for apps that need to fetch data from the Internet. It is hard to imagine a mobile app not needing to communicate with a web server or store structured data at some point. When making network-connected apps,  it needs to consume some good old JSON.

This guide looks into ways of using JSON with Flutter. It covers which JSON solution to use in different scenarios.

### Key takeaways: 
-The reader will learn how to create a plain dart object.
-The reader will learn how to make the network request.
-The reader will learn how to map the JSON objects to Dart Objects.

### References:
N/A

**Comment by WanjaMIKE** [comment]
@vincentkims49 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @vincentkims49. 

Could you tell me how your article differs from those of a similar topic such as [Parsing JSON in Flutter](https://www.raywenderlich.com/4038868-parsing-json-in-flutter), [Parsing Complex JSON in Flutter](https://medium.com/flutter-community/parsing-complex-json-in-flutter-747c46655f51) and [How to Parse JSON in Flutter for Beginners](https://medium.com/flutter-community/how-to-parse-json-in-flutter-for-beginners-8074a68d7a79)?

**Comment by vincentkims49** [comment]
Hi, @louisefindlay23.
Depending on how much JSON data you need to manage, I'll write all of the JSON processing code manually. In my article, I'll also go through encoding and decoding JSON, parsing JSON within a factory constructor, dealing with nullable variables and serialization back to JSON. You'll also learn how to create model classes with strong JSON parsing and validation code by the conclusion of this tutorial.

**Comment by vincentkims49** [comment]
@louisefindlay23,
Thank you

**Comment by vincentkims49** [comment]
@hectorkambow @lalith1403 
I'll be providing original content.More than what is available in other websites since it's not available in github section and for learners to understand step by step on how to parse JSON .
Thank you.

**Comment by vincentkims49** [comment]
its a total different topic @louisefindlay23
