### ISSUE TITLE
Working with GeoDjango 

### ISSUE THREAD

**Issue by Anitaachu** [section-engineering-education/engineering-education#3320]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction paragraph (2-3 paragraphs):
GeoDjango is a Django contrib module that transforms the web framework into a world-class geographic framework. GeoDjango aims to make creating geographic Web applications, such as location-based services.
GeoDjango includes Python bindings for major spatial libraries like GEOS, GDAL, and GeoIP, which may be used in any Python application or interactively in the shell. 
GeoDjango works nicely with the Django ORM and offers a set of geometry fields established by the Open Geospatial Consortium (OGS) that may be used to map to various geometries in geospatial databases. This tutorial will focus on working with GeoDjango, by building a django project and integrating geolocation using GeoDjango.

### Key takeaways: 
1. How to working with GeoDjango
2. How to integrate Postgres in a Django project
3. Understanding GeoDjango dependencies

### References: 
https://docs.djangoproject.com/en/3.2/ref/contrib/gis/tutorial/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@Anitaachu 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Someone already submitted a [topic suggestion](https://github.com/section-engineering-education/engineering-education/issues/3275) about GeoDjango.

Please feel free to suggest an alternate topic to explore. 🚀 @Anitaachu
