### ISSUE TITLE
Transitioning from Bootstrap to Semantic UI React

### ISSUE THREAD

**Issue by NyongToro** [section-engineering-education/engineering-education#3321]
### Introduction:
Website styling and design is an integral part of front end web development and web developers are expected to make available a flawless web design to optimize user experience and interaction.
Bootstrap has been the leading library in web styling and favored by many developers untill now. Semantic UI React and other modern design libraries are reducing the complexity of web styling by providing advanced elements and features as we'll discuss in this article
### key takeaways:
At the end of this article, the reader is expected to understand and implement the following
i. The fundamentals of front end web design libraries
ii. Limitations of bootstrap
iii. Efficiencies and advanced features of Semantic UI React
iv. Implementing a simple web page with semantic UI React elements
v. Tricks and hacks in Semantic UI React
### Reference
https://www.tabnine.com/code/javascript/modules/semantic-ui-react

**Comment by WanjaMIKE** [comment]
@NyongToro 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Hey @Bayler, what do you think of this topic? You have experience with React. Thank you!

**Comment by srishilesh** [comment]
@NyongToro 

This sounds like a great topic!

It would also be great if you compare and contrast by building the same webpage using both Bootstrap and semantic ui, and reason out how semantic ui is more efficient than bootstrap, what other extraordinary features do we find in semantic ui.

cc. @ahmadmardeni1

**Comment by NyongToro** [comment]
@srishilesh 
Thank you, I'll be sure to accommodate all your recommendations in the article.
