### ISSUE TITLE
Getting started with Python PIP

### ISSUE THREAD

**Issue by Muchiri021** [section-engineering-education/engineering-education#3322]
### Proposed title of the article
Getting started with Python PIP

### Introduction paragraph (2-3 paragraphs):
A package is a piece of software that provides particular features while programming. A package contains all the resources which a module requires. Modules are sets of Python code that we can add to our project. Python pip is the package manager for Python packages.

### Key takeaways: 
- Understanding PIP.
- Installing PIP.
- Checking to see if PIP is installed.
- Downloading a package.
- Usage of a package.
- Finding and removing packages.
- Packages list.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@Muchiri021 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Muchiri021 
This topic is over-saturated throughout other blog sites and official documentation.

We believe that the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
