### ISSUE TITLE
Data encoding techniques

### ISSUE THREAD

**Issue by GeoffreyKangu** [section-engineering-education/engineering-education#3323]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article.
Data encoding techniques

### Introduction paragraph (2-3 paragraphs):
In a communication network, data is transmitted from the sender to the receiver. For this data to be transmitted properly it is encoded into binary digits 0s and 1s. 

This article intends to cover more on how data to be transmitted through a network is encoded. This therefore will emphasize more on different data encoding techniques. It also touches on Digital and analog data. 

The different data encoding techniques that shall be focused on include; Non-Return to Zero Level, Non-Return to Zero, Non-Return to Zero Inverted, Bi-phase encoding, and Block encoding. Data encoding types shall also be discussed.

### Key takeaways: 
A better understanding of data encoding.
A better understanding of different data encoding techniques e.g Non-Return to Zero Level(NRZ-L)
Be able to encode a data signal using any technique.
A better understanding of digital and analog signals.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@254-geo 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Sounds like a great topic @254-geo - approved. Please be sure to use a descriptive heading for your article; the current heading seems a bit ambiguous. Looking forward to reviewing and hopefully publishing your article.
