### ISSUE TITLE
Tcp/Ip and Subnet Masking Made Familiar

### ISSUE THREAD

**Issue by Robbiewanjau** [section-engineering-education/engineering-education#3324]
### Proposed title of article
Tcp/Ip and Subnet Masking Made Familiar

### Introduction paragraph (2-3 paragraphs):
Transmission Control Protocol/Internet Protocol (TCP/IP) is a set of communication protocols that are used to link network devices on the internet. In a private computer network, TCP/IP is also used as a communications protocol (an intranet or extranet).
TCP/IP refers to the whole IP suite, which includes a set of rules and processes. TCP and IP are the two most used protocols, although the suite also includes others. Between internet applications and the routing and switching fabric, the TCP/IP protocol suite serves as an abstraction layer.
A subnet mask is a 32-bit value made up of all 0s for the host bits and all 1s for the network bits. The subnet mask divides the IP address into network and host addresses in this fashion.A broadcast address is always allocated to the “255” address, whereas a network address is always assigned to the “0” address. Both cannot be allocated to hosts because they are only used for these purposes. 

### Key takeaways: 

1.How does TCP/IP work?
2.The 4 layers of the TCP/IP model
3.Pros and cons of TCP/IP
4.TCP/IP vs OSI model
5.IP Address and Subnet Mask
6.How Does Subnetting Work?
7.Network Addressing
8.Subnet Mask Calculator

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@Robbiewanjau 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Robbiewanjau 
We already have some articles covering TCP and subnet masking.

Please feel free to suggest an alternate topic to explore. 🚀
