### ISSUE TITLE
Creating a PDF file from a component in Vue

### ISSUE THREAD

**Issue by VickkyCletus** [section-engineering-education/engineering-education#3325]
### Introduction:
Vue provides an array of functionalities in web development and one of the numerous features includes creating and exporting a pdf file from a component. The implementation of the above will be discussed in detail along with the recommended packages and dependencies subsequently in this article.
### key takeaways:
This article will focus and enable the reader understand and implement the following
i. Getting started with Vue to PDF
ii. Creating and exporting a PDF document from a component in Vue
ii. Recommended packages and dependencies for pdf download in Vue.
iv. Creating canvases in Vue
### References
https://www.npmjs.com/package/vue-html2pdf

**Comment by WanjaMIKE** [comment]
@VickkyCletus 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @VickkyCletus 
What value will your article provide that is more than what is already there in the npm package. From my point of view, it seems your article will only address creating PDFs which is what the package is about. If you could provide more information to clarify this issue, we can give the green light to go on.

:question:
