### ISSUE TITLE
Working with Flutter timelines

### ISSUE THREAD

**Issue by mia-roberts** [section-engineering-education/engineering-education#3326]
### Proposed title of article
Working with Flutter timelines

### Introduction paragraph (2-3 paragraphs)::
You can think of timelines as progress indicators which shows the current level of a larger process. Timelines are useful when one needs to calculate percentage of completion of a task.

In this tutorial we will be building an example of task completion application in fluttuer to explain how uselful this can be.

### Key takeaways: 
1. Undertanding Flutter timelines
2. Flutter timeline_tile dependency
3. Using timeline dependency to build a flutter application.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@mia-roberts 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @mia-roberts 
This sounds like a really interesting topic. Please make sure you provide more original content than what is already there in the pub.dev registry. 

:rocket:

**Comment by hectorkambow** [comment]
@mia-roberts
