### ISSUE TITLE
 How to Build, Test and Deploy a NodeJs Application With Jenkins

### ISSUE THREAD

**Issue by Olanetsoft** [section-engineering-education/engineering-education#3327]
### Proposed title of the article
How to Build, Test and Deploy a NodeJs Application With Jenkins

### Introduction paragraph (2-3 paragraphs):
Node.js is a scalable network application builder that uses an asynchronous event-driven JavaScript engine. Furthermore, because Node.js has no locks, users do not have to worry about the process becoming deadlocked. Because almost no Node.js function does I/O directly, the workflow never comes to a halt. Because nothing blocks, Node.js is an excellent choice for building scalable systems.

Jenkins is a self-contained, open-source automation server that may be used to automate a variety of operations related to software development, testing, and delivery.

Jenkins can be installed via native system packages, Docker, or even run solo on any machine that has the Java Runtime Environment (JRE).

### Key takeaways: 
Readers will learn:

- Jenkins fundamentals
- How to connect git and deploy a nodejs application using Jenkins
- How to use Jenkins to perform a test on a nodejs application
- How to use Jenkins to create environment variables, run builds and so on

### References: 
- [https://www.jenkins.io/doc/](https://www.jenkins.io/doc/)
- [https://nodejs.org](https://nodejs.org)
- [https://www.section.io/engineering-education/what-is-jenkins/](https://www.section.io/engineering-education/what-is-jenkins/)

**Comment by WanjaMIKE** [comment]
@Olanetsoft 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Olanetsoft** [comment]
Thanks for the feedback 😊  @WanjaMIKE

**Comment by hectorkambow** [comment]
@Olanetsoft 
Seems like a very cool topic - but regarding Node.js we have more than enough currently in our EngEd library as we did a big push the last few months and are currently not accepting any more Node.js articles to publish for the time being.

Please feel free to suggest an alternate topic to explore.
