### ISSUE TITLE
Different Methods for Flattening a Dictionary in Python

### ISSUE THREAD

**Issue by IsaacMuthini** [section-engineering-education/engineering-education#3331]
### Proposed title of article
Different Methods for Flattening a Dictionary in Python

### Introduction paragraph (2-3 paragraphs):
A flattened dictionary? Why would i need that? There a couple of reasons why you need a flattened dictionary. 
One of them is that it makes it simpler to compare and contrast and also if that ain't enough a flattened dict is easier to navigate and manipulate.
In this tutorial am going to take you through different ways of flattening a dictionary by use of examples.
Throughout the tutorial I will outline the advantages and disadvantages of each flattening dictionary method.

### Key takeaways:
By the end of this tutorial, the reader will be able to:
- Flatten a dict using a recursive function
- Flatten a dict using a recursive function and Generators
- Flatten a dict using pandas
- Flatten a dict using the **flatdict** library

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@IsaacMuthini 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Check out this article on python dictionaries. `https://www.section.io/engineering-education/lists-and-dictionaries-python/`

**Comment by IsaacMuthini** [comment]
@WanjaMIKE I have checked and they are different as one talks about flattening the dictionary while the other is about dictionaries in python in general.

**Comment by IsaacMuthini** [comment]
@WanjaMIKE The article you asked me to check talks about dictionaries in general, that is its syntax, how to add items, how to remove and loop in dictionaries while my article solely talks on different methods of flattening the dictionary in python.
