### ISSUE TITLE
Implementing Flask API using Linked list Data Structure

### ISSUE THREAD

**Issue by OkothPius** [section-engineering-education/engineering-education#3334]
### Proposed title of article
Implementing Flask API using Linked list Data Structure

### Introduction paragraph (2-3 paragraphs):
Understanding data structures is an important aspect when developing applications. While this is an important aspect is a software lifecycle most developers struggle in implementing these core features when building real-world applications.

In this article, we will build a hands-on Flask API using a Linked list data structure. We will see how trivial and efficient it is in terms of insertion and deletion when creating applications.

### Key takeaways:
* Introduction to Flask
* Understanding Linked list Data Structure
* Implementing Flask API using Linked list
* Testing the API using Postman

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@OkothPius 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @OkothPius
