### ISSUE TITLE
Building a Recommendation System using Collaborative Filtering with Streamlit

### ISSUE THREAD

**Issue by willyngashu** [section-engineering-education/engineering-education#3346]
### Proposed title of article
Machine Learning Recommender App with Streamlit
### Introduction paragraph (2-3 paragraphs):
Recommender systems are systems designed to recommend things to the user based on many different factors.  They predict products that a user is likely to purchase on interested in, they also give users items with the highest rating.

The recommender system deals with a large volume of information present by filtering the most important information based on the data provided by a user and other factors that take care of the user’s preference and interest. It finds out the match between user and item and imputes the similarities between users and items for recommendation. 
Companies like Netflix, Amazon, and Youtube use recommender systems to help their users to identify the correct product or movies for them.
In this tutorial, I will use the Udemy dataset to build a simple recommender app that can be able to recommended courses with the highest rating to a particular user.
We shall use Streamlit in building the app. 
Streamlit is an open-source Python library that makes it easy to create and share beautiful, custom web apps for machine learning and data science
### Key takeaways: 
1. What are recommender sytems.
2. Types of Recommendation System
3. Getting started with streamlit for machine learning.
4. Building course recommender app using streamlit.
5. Making predictions.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@willyngashu 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by srishilesh** [comment]
@willyngashu 

Could you please ping the Udemy dataset that you're going to use?

Also, I already find one such article explaining in-detail about the concepts of Recommender systems [here](https://www.section.io/engineering-education/recommender-system-explained/). Make sure your article doesn't overlap much with this.

Instead, can't we focus on building a recommender system with a more specific concept - either collaborative filtering or content based filtering method?

By doing this, the reader will get a better insight by focusing on a specific topic, rather than just reading a generic tutorial on recommendation system.

**Comment by willyngashu** [comment]
This is the [dataset] used (https://drive.google.com/file/d/1KCUQlqJjzjGccvysO22A4Tf1InpXF0pd/view?usp=sharing)
In my tutorial, I will be building a model rather than explaining concepts.
I will start from data preparation to building the application using streamlit.

**Comment by willyngashu** [comment]
This is the [dataset](https://drive.google.com/file/d/1KCUQlqJjzjGccvysO22A4Tf1InpXF0pd/view?usp=sharing) used.
In my tutorial, I will be building a model rather than explaining concepts.
I will start from data preparation to building the application using streamlit.

**Comment by willyngashu** [comment]
This will guide the user to build a model @srishilesh

**Comment by hectorkambow** [comment]
@lalith1403

**Comment by srishilesh** [comment]
@willyngashu 
Thanks for the reply.

Could you have a look and answer the second part of the question?

**Comment by willyngashu** [comment]
We shall be building a model that deals with collaborative filtering, will recommend courses to a student according to test and preference.
@srishilesh

**Comment by srishilesh** [comment]
@willyngashu 

Alright.

Make sure to walk the reader through the concepts of Collaborative filtering.

Feel free to suggest any other article title.

Topic approved.

**Comment by lalith1403** [comment]
This is a wonderful topic suggestion. As suggested by @srishilesh, let's focus on implementing the recommender system and leave the theory to the great resources available online.
