### ISSUE TITLE
HTML Client for Web Services using DHTML Behavior

### ISSUE THREAD

**Issue by borosteve** [section-engineering-education/engineering-education#3349]
### Proposed title of article

HTML Client for Web Services using DHTML Behavior

### Introduction paragraph (2-3 paragraphs):

DHTML makes a webpage dynamic, but so does Javascript DHTML allows us to change the look, content, and style of a webpage after it has been loaded without changing or deleting anything that is already on the browser's webpage.

In this article, we will learn how DHTML can change the content of a webpage on demand without requiring the browser to erase everything else. We will learn how to create a web service as well as an HTML client.

### Key takeaways:
1. The reader will learn how to create the web service.
2. The reader will learn how to create the HTML client.
3. The leader will learn how to test web service and HTML client.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@borosteve 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @borosteve. 

Great topic suggestion. How will your article be different from those of a similar topic such as this [TechRepublic](https://www.techrepublic.com/article/modularize-your-web-design-with-dhtml-behaviors/) article and [CSharpCorner](https://www.c-sharpcorner.com/article/html-client-for-web-services-using-dhtml-behavior/) article.

**Comment by borosteve** [comment]
Hello, @louisefindlay23
   I will use a step by step procedure for easier comprehension by the reader. I will write a unique article where I will also add content on the importance of DHTML and differences Between HTML and DHTML which are not in the two articles.
Thanks.

**Comment by louisefindlay23** [comment]
Thanks, @borosteve for providing a detailed explanation. Topic approved 🚀.

**Comment by borosteve** [comment]
Thank you, @louisefindlay23  for the feedback.
