### ISSUE TITLE
Creating Loading Spinners and Progress bars for your site.

### ISSUE THREAD

**Issue by munubi254** [section-engineering-education/engineering-education#3353]
### Proposed title of the article
Loading Spinners and progress bars for your site.

### Introduction paragraph (2-3 paragraphs):
We need, at some point, to track the progress of underlying processes of our applications or display to the user that a process is going on. To do that, we need to implement Loading Spinners and Progress bars. In this article, we will look at creating these and apply them in various scenarios such as file reading, reading and writing records to the database, and during loop counters using JavaScript and CSS.

### Key takeaways: 
- Designing the spinners and bars using CSS.
- Displaying the elements for underlying processes.
- Controlling the display using JavaScript and a backend language(PHP).

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

**Comment by WanjaMIKE** [comment]
@munubi254 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
I found this PR similar to `https://github.com/section-engineering-education/engineering-education/issues/3186`. Please check it out.

**Comment by munubi254** [comment]
Please close it for me then
