### ISSUE TITLE
Understanding Script Tag Attributes: Async and Defer

### ISSUE THREAD

**Issue by codeInn001** [section-engineering-education/engineering-education#3354]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Understanding Script Tag Attributes: Async and Defer

### Introduction paragraph (2-3 paragraphs):
In modern websites, scripts are often “heavier” than HTML: their download size is larger, and processing time is also longer.

When the browser loads HTML and comes across a <script>...</script> tag, it can’t continue building the DOM. It must execute the script right now. The same happens for external scripts <script src="..."></script>: the browser must wait for the script to download, execute the downloaded script, and only then can it process the rest of the page.
Luckily, there are two <script> attributes that solve the problem for us: defer and async

### Key takeaways: 
1. Reader will learn how the browser parse HTML and Javascript.
2. Reader will know the similarities between async and defer.
3. Reader will know the difference between async and defer.
4. Reader will know how and when to use async and defer.

### References: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
https://developer.mozilla.org/en-US/docs/Web/Performance/How_browsers_work

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@codeInn001 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @codeInn001 
This sounds like a really great web article that would be super helpful. A few points to note as your work on the article; make sure you add more original content and that the content is rich enough. The article might still be closed if the value seen by the reviewers is not adequate. Also, ensure it does not conflict with content already available on section.

topic approved :rocket:

**Comment by codeInn001** [comment]
@LinusMuema . Thanks, I will try to make a great article.

**Comment by hectorkambow** [comment]
@codeInn001 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by codeInn001** [comment]
@hectorkambow, So sorry, I have been very busy lately, I am currently working on the article. It should be ready on or before this weekend.
 Can you please open the topic form.
