### ISSUE TITLE
Getting started with Arduino.

### ISSUE THREAD

**Issue by dancanmwai** [section-engineering-education/engineering-education#3355]
### Proposed title of article
Getting started with Arduino.

### Introduction paragraph (2-3 paragraphs):
Arduino is a prototype(open source) platform based on a easy-to-use hardware and software. Generally, we're linking up hardware and software in such a way that a code is generated for certain functionality, stored in a micro-controller, configured on a printed circuit board to perform the assigned task. Assume a simple automatic home-made amplifier that turns on at dawn (sunrise) and off at dusk- When it's dark. The hardware gadget need lines of code to operate automatically: Example; Linking sound operators with sensors (when light intensity is high, volume remains top and vice versa). An arduino is that component that will help us easily do such amazing projects.
How is that possible? It has an arduino IDE software for uploading the code into its micro-controller and -BRINGING THE AUTOMATION EFFECT. By this, software code drives the hardware to perform different tasks as per the user's wants. With Arduino, easy game!!

To explore a little more, we'll learn that arduino reads inputs like fingerprints, from sensors, etc However, this same arduino can output signals like light(LEDs), sound (Buzzers), among others. Just need simple lines of codes, easy to learn. Have you ever asked yourself how robots and drones work? By the end of the tutorial series, Arduino will help us build a simple automated robot for easening a daily domestic task like...
SUPER AMAZING 

### Key takeaways: 
1. What is an arduino?
2. How it works
3. Arduino components
4. Basics in arduino coding
5. Why arduino
6. 
### References: 
n/a

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@dancanmwai 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by dancanmwai** [comment]
Thanks

**Comment by lalith1403** [comment]
Thank you for the topic suggestion @dancanmwai, however, this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
