### ISSUE TITLE
How to implement Okta authentication in a React application?

### ISSUE THREAD

**Issue by ephnjor2021** [section-engineering-education/engineering-education#3358]
### Proposed title of article
How to implement Okta authentication in a React application?

### Introduction:
Authenticating the users is important for most applications. Buiding own authentication system seems to be an easy task. However, integrating it with third parties such as Google or Facebook for security reasons can be tedious and complex.
A solution would be to use a dedicated auth system to handle authentication such as Okta. Okta provides access to a dedicated team of security experts that handles the security of your user data.
This tutorial will cover the implementation of Okta authentication in a React application.

### Key takeaways: 
At the end of the tutorial, the learner will be able to:
- set up a React application and sign up for the developer edition of Okta
- integrate React application with Okta authentication system
- implement a custom sign-in form with a unique design and use Okta authentication without redirecting to the Okta page

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@ephnjor2021 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@ephnjor2021 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
