### ISSUE TITLE
Getting Started with Code Generation in Flutter

### ISSUE THREAD

**Issue by FranciscaNg** [section-engineering-education/engineering-education#3365]
### Proposed title of article
Getting Started with Code Generation in Flutter

### Introduction paragraph (2-3 paragraphs):
Flutter model code generation allows you to automate these time-consuming activities so you can focus on what matters. Simply write the repeated code pattern once and build a generator that generates files with code based on the pattern you defined.

In this article, you'll create a code generator that locates all of a class's variables, stores them in a map, then produces getters and setters to save and read from the map.

### Key takeaways: 
-When should code generation be used?
-What are annotations and how do I utilize them?
-A generator's method of generating code.
-In a Flutter project, how to produce models.

### References: 
N/A

**Comment by FranciscaNg** [comment]
@jerimkaura 
I just suggested a new issue. As requested I'd like you to look at it.

**Comment by WanjaMIKE** [comment]
@FranciscaNg 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @FranciscaNg 
I am sure you will be writing a lot about the build_runner package and I'd like to remind you to provide more original content. More than what is already available on other websites and the official documentation on pub.dev. Also, ensure it does not conflict with other articles already on section.

topic approved :rocket:

**Comment by NdoloBonface** [comment]
Thank you
@LinusMuema
