### ISSUE TITLE
Graphics in Java

### ISSUE THREAD

**Issue by Paul22691** [section-engineering-education/engineering-education#3366]
### Proposed title of article
Graphics in Java
### Introduction paragraph (2-3 paragraphs):
One of the main reasons why java is such a popular programming language is that it makes it easy to create programs that have an impressive graphics. This is mainly managed by Java vast graphics library known a s the Abstract Windows Toolkit (AWT).

The AWT library consists of over 25 packages which defines different types of classes. Some of this packages are the java.awt, java.awt.swing, java.awt.image, java.awt.event and many more other packages. The package java.awt.imagedefines a class named pixelGrabber. Every class is defined in the package java.awt.
### Key takeaways: 
In this tutorial we will be covering:
1. The frame and color class.
2. Components.
3. The button class.
4. Managing layouts.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@Paul22691 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
@BrianaNzivu Could you take a look at this topic suggestion when you have the chance? Since you have expertise in Java, I thought you'd be the best person to reach.

**Comment by BrianaNzivu** [comment]
Hey @ahmadmardeni1👋🏾 .
Seems like a good and interesting topic and definately unique. It's not something that has been written about. 

@Paul22691👋🏾. I really hope that you will provide a detailed tutorial.
By that I mean that each of the classes when it comes to using AWT should be explained properly and you should illustrate how to implement them.

Otherwise I think it's an amazing topic🚀

Regards.

**Comment by Paul22691** [comment]
Hello @BrianaNzivu 
I'll ensure a better and detailed tutorial with illustrations of the AWT classes.
Is the topic suggestion approved

**Comment by ahmadmardeni1** [comment]
Make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.  @Paul22691

**Comment by hectorkambow** [comment]
@Paul22691 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
