### ISSUE TITLE
Common Gateway Interface in python (CGI)

### ISSUE THREAD

**Issue by Georgewamama** [section-engineering-education/engineering-education#3367]
### Proposed title of article
Common Gateway Interface in python (CGI)

### Introduction paragraph (2-3 paragraphs):
The common gateway interface in a HTTP server invokes a python script that processes user input that any user may submit through a HTML  `<FORM> or<ISINDEX>` elements. This script lives in the servers special cgi.bin directory. It executes a script and sends the outputback to the client.

The python CGI module helps debug scripts and also lends support for uploading files from a form.

### Key takeaways: 
In this tutorial we will be covering:

1. Python CGI architecture.
2. Python CGI module.
3. Functions of python CGI module.
4. CGI environment variables.
### References: 
N/A

**Comment by WanjaMIKE** [comment]
@Georgewamama 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Georgewamama 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
