### ISSUE TITLE
Using Google Charts to Create an Attendance Graph

### ISSUE THREAD

**Issue by Mearytt** [section-engineering-education/engineering-education#3368]
### Proposed title of article
Using Google Charts to Create an Attendance Graph

### Introduction paragraph (2-3 paragraphs):
Pie chart, column chart, and other charts can be generated using the Google Charts API. 
Using this API, it's easy to create graphical reports for our charting application's charting application.
Using the Google Chart API, i'll show you how to create a graph of attendance data.

Using the students database, I will get the attendance data in this example.
 Using the Google Charts API, this data will be plotted on a graph. 
Pie chart and column chart will be used to display the attendance graph.

Using a pie chart, you can see how many students are present and absent at any given time. 
Student attendance counts will be shown in place of percentages in the column chart. 
For the variation in attendance data, I have used custom colors. 

### Key takeaways:
1.Google Charts API Initialization  
2. Get Attendance Data from the Database
3.Attendance Graph Output using Google charts
### References: 
N/A

**Comment by WanjaMIKE** [comment]
@Mearytt 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Mearytt** [comment]
This tutorial will have a good example of how you can implement and represent your actual data on a dashboard using google charts. The example will render an attendance graph chart and learners will be able to see how to go about it. The code snippets will be straightforward and easy to understand for the benefit of the community

**Comment by ahmadmardeni1** [comment]
Okay, then you have to build a unique project. Do you have something in mind? @Mearytt

**Comment by Mearytt** [comment]
@ahmadmardeni1, In my project example, I will obtain attendance data from an employee database. This data from the database will be plotted on a graph created with the Google Charts API. The attendance graph will be displayed in two formats: pie chart and column chart.
The pie chart will show the employee's percentage of presence and absence. Instead of the percentage, the employee attendance count will be shown in the column chart. I will use custom colors to demonstrate the variation in attendance data. Thank you

**Comment by ahmadmardeni1** [comment]
Great topic 🚀@Mearytt , make sure it matches the following: 
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by hectorkambow** [comment]
@Mearytt 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
