### ISSUE TITLE
Stacks in Data Structures ( using C++)

### ISSUE THREAD

**Issue by anubhavb11** [section-engineering-education/engineering-education#3370]
### Introduction paragraph (2-3 paragraphs):
Stack is a simple data structure used for storing data (similar to a linked list). Its most important feature is the way of inserting and deleting data, which happens in O(1) time complexity, making it so efficient. It stores data like a pile of plates in a cafeteria the plates are added to the stack as they are cleaned and placed on the top. When a plate, is required it is taken from the top of the stack. It is called LIFO ( last in first out) principle that stack follows.

### Key takeaways:
- Will cover everything about stacks 
- how stacks are used
- stacks ADT
- Applications
- Implementation
-  Stacks STL ( will help in coding questions)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @anubhavb11 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by anubhavb11** [comment]
I already posted 2 articles one about hashmaps and the other is about graphs
I wanna cover all types of data structures topic by topic but my issue got closed this time
I not only explain what's in the documentation  but I explain how one can code the implementation of stacks and all other data structures I learned it by doing some courses but now wanna explain others by writing articles,
Please look into the matter we wanna cover all the data structures
Linked list
Stacks
Queues
Tree
Graphs (done)
Hashmap (done)
Heap
Please look into the matter I really wanna write on all of them at section- engineering - education
@ahmadmardeni1  @hectorkambow

**Comment by ahmadmardeni1** [comment]
Replied to your message on Slack.👀 @anubhavb11
