### ISSUE TITLE
Place locator app using GeoJson

### ISSUE THREAD

**Issue by jamila-laureen** [section-engineering-education/engineering-education#3374]
### Proposed title of article
Place locator app using GeoJson

### Introduction paragraph (2-3 paragraphs):
GeoJson is a standard format for storing geographic points in a database based on JavaScript Object Notation. GeoJson is based on JSON format making it easy to use with JavaScript. Geographic features encode using GeoJson include Latitude, Longitude, line strings and Polygons.

In this article, we are going to use GeoJson to build a locator application using Nodejs. We will develop an application that adds a location (for instance a school) on a database and be able to display the locations encoded on the database on a map display.
. 

### Key takeaways: 
1. Understanding GeoJson
2. Setting up MongoDB with Node.js
3. Encoding location data into MongoDB using mongoose.
4. Using Mapbox with Node.js

### References: 
1. https://geojson.io/
2. https://www.mongodb.com/
3. https://www.npmjs.com/package/mongoose

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@jamila-laureen 
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@jamila-laureen 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by jamila-laureen** [comment]
Hello @ahmadmardeni1 , would you please open this issue so that i submit the article. Thanks for your patience as you waited for me to finish up.
