### ISSUE TITLE
Data transformation with LINQ

### ISSUE THREAD

**Issue by miriam015** [section-engineering-education/engineering-education#3375]
### Proposed title of article
Data transformation with LINQ

### Introduction paragraph (2-3 paragraphs):
LINQ (Language-Integrated Query) isn't just for retrieving data. It's also a useful tool for data transformation. You can utilize a source sequence as input and modify it in a variety of ways to create a new output sequence by using a LINQ query. Sorting and grouping can be used to change the sequence without changing the items.

The ability to generate new types is possibly the most powerful feature of LINQ queries. The select clause is used to accomplish this. You can, for example, do the following tasks:
1. Multiple input sequences are combined into a single output sequence with a new type.
2. Creating output sequences using only one or a few attributes from each element in the source sequence as the elements.
3. Creating output sequences with the outcomes of operations on the source data as their elements.
In the same query, these changes can be coupled in a variety of ways. A query's output sequence can also be utilized as the input sequence for another query.

### Key takeaways: 
1. Selecting a Subset of each Source Element
2. Joining Multiple Inputs into One Output Sequence
3. Transforming in-Memory Objects into XML.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@miriam015 
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @miriam015

**Comment by hectorkambow** [comment]
@miriam015 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
