### ISSUE TITLE
How to install TensorFlow Federated

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#3380]
### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

How to install TensorFlow Federated

### Introduction paragraph (2-3 paragraphs):

I'm writing a three part series on TensorFlow Federated. In my already published [tutorial](https://www.section.io/engineering-education/federated-learning-using-tensorflow-federated/), I had started discussing how to use Federated Learning API and how one can implement it. It was supposed to be followed with part 2 of the tutorial which was to discuss about the Federated Core API. But, I realized that I had skipped the process where I take the reader how on the 3 ways of installing the TensorFlow Federated . And that's what this article is about.  

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should understand the few ways to set up your environment to use TensorFlow Federated (TFF):

1. The easiest way to learn and use TFF requires no installation. We run the TensorFlow Federated tutorials directly in your browser using Google Colaboratory. That's what i used in this [tutorial](https://www.section.io/engineering-education/federated-learning-using-tensorflow-federated/).
2. One can also install TensorFlow Federated on a local machine; installing the TFF package with Python's pip package manager.
3. If you have a unique machine configuration, one can build the TFF package from source.

I will be taking the readers how they can use any of these three ways using code to install TFF. 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@Bayler 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
There is an article by @lalith that covered this topic `https://www.section.io/engineering-education/federated-learning-using-tensorflow-federated/`

**Comment by Bayler** [comment]
Hi @WanjaMIKE I'm the one who wrote the article, not @lalith1403 As I explained above, this is part of a three part series. So, I'm building on it. I linked that article in my topic issue description

**Comment by WanjaMIKE** [comment]
Ooh I think he reviewed it then. However, we are against a series format and tend to encourage contributors to cover all aspects in a single article.

**Comment by Bayler** [comment]
> Ooh I think he reviewed it then. However, we are against a series format and tend to encourage contributors to cover all aspects in a single article.

They are totally independent tutorials actually. It's only that one builds on the other. It's not a continuation.

**Comment by lalith1403** [comment]
I gather that building tensorflow federated is done using Bazel. Since that is the case, this article will be redundant. The other two methods mentioned here are quite obvious. I suggest you submit another topic suggestion form. Thank you.
