### ISSUE TITLE
How to Fetch Data from an API in JavaScript

### ISSUE THREAD

**Issue by essy258** [section-engineering-education/engineering-education#3382]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to Fetch data from an API in JavaScript

### Introduction paragraph (2-3 paragraphs):
Most times, you might want your system to communicate with other web servers to get information. This is achieved using an API.

An API, or Application Programming Interface, is just a set of rules that guide how one software or system communicates with another.

JavaScript has its built-in way to make API requests. This is the Fetch API, a new standard to make server requests data. In this article, we will learn how to use the Fetch API in JavaScript to get data from resources. Also, we will learn how to handle POST requests.
### Key takeaways: 
1. What is the Fetch API?
2. How to Use Fetch API
3. Using Fetch API to GET data from an API
4. Handling POST requests

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@essy258 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by essy258** [comment]
@WanjaMIKE I will use Async functions with the FETCH API

**Comment by WanjaMIKE** [comment]
Thank you for the topic suggestion @essy258 , however this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. There are numerous articles already using async functions to fetch data.
