### ISSUE TITLE
How To Secure Your Firebase App With Firebase Security Rules

### ISSUE THREAD

**Issue by julie-techie** [section-engineering-education/engineering-education#3383]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How To Secure Your Firebase App With Firebase Security Rules

### Introduction paragraph (2-3 paragraphs):
Most times, you might want your system to communicate with other This tutorial will help you learn how to make your firebase app secure. We'll dive deeper into how security rules work and show an advanced use case to help you secure your applications.

Security rules protect your data in both cloud storage and cloud Firestore from unauthorized access. 

### Key takeaways: 
1. What is Firebase?
2. Why Security is Important in Cloud Firestore
3. Securing your Firebase app with security rule

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@julie-techie 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
@julie-techie Kindly, how will your topic differ from the existing documentation?

**Comment by julie-techie** [comment]
@WanjaMIKE this topic will use a demonstrative study case to make the reader more comfortable building secure applications. Thus teaching the reader how to apply the rules in their projects

**Comment by WanjaMIKE** [comment]
Nice topic. Approved. Let's ensure that it adds value to the eng-ed community. Thanks

**Comment by WanjaMIKE** [comment]
Closed #3383 via #3752
