### ISSUE TITLE
 Writing a Flutter Web Plugin

### ISSUE THREAD

**Issue by FaithZawadi** [section-engineering-education/engineering-education#3384]
### Proposed title of article
 Writing a Flutter Web Plugin

### Introduction paragraph (2-3 paragraphs):
Flutter's web support provides the same mobile and online experiences. You can now create apps for iOS, Android, and the web using the same codebase, thanks to the flexibility of the Flutter framework. Because it is the same Flutter framework and the web is merely another device target for your project, you can convert current Flutter code written in Dart into a web experience. In addition to translating Dart to JavaScript, adding web functionality to Flutter requires creating Flutter's fundamental graphics layer on top of conventional browser APIs.

Aside from the Android and iOS plugins, I'll be utilizing a feasible technique for adding web support to a Flutter plugin in this article.

### Key takeaways: 
-How to add web support to a Flutter plugin.
-How to refactor your plugin.
-How to register the plugin.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@FaithZawadi 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
@FaithZawadi - Please provide more details on your topic.

**Comment by FaithZawadi** [comment]
@Kayere ,
I have added some details.
You may have a look.
Thank you.
