### ISSUE TITLE
How to Build a Task Manager with Angular

### ISSUE THREAD

**Issue by edidee** [section-engineering-education/engineering-education#3385]
### Proposed title of the article
How to build a task manager with angular

### Introduction paragraph (2-3 paragraphs):
If you are trying to learn a programming language or framework, it is good practice to build simple tasks which will go a long way to help solidify your knowledge in that language.  
In this article, I will work you through building a simple task manager app (popularly known as a To-do app) using angular a JavaScript framework.
A task manager is used to write, organize and rearrange tasks more efficiently. The task manager we are going to build will allow the user to add a task, mark a task as complete and also delete a task.

### Key takeaways: 
1. How to create and structure an angular project.
2. How to create modules and components in angular.
3. Build a simple application.
4. Save tasks to local storage.

### References: 
https://angular.io/docs

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@edidee 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@edidee 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
