### ISSUE TITLE
Building a Golang RESTAPI with mux and postgresql 

### ISSUE THREAD

**Issue by Anitaachu** [section-engineering-education/engineering-education#3389]
### Introduction paragraph (2-3 paragraphs):
Go or Golang is an open-source, robust-system-level programming language used to build large-scale network servers and distributed systems. Go was developed by Google in 2007 as a statically-typed compiled language. 

Considering Go is a member of the C-family, it has similar syntax with languages like Java and C++, but it has a more succinct syntax that makes it simpler to learn and understand. Making it easy to develop software that is fast, dependable, and efficient. This tutorial will focus on building a simple REST API application with Golang and Mux (A powerful URL router and dispatcher).

### Key takeaways: 
1. How to build a RESTAPI in GoI 
2. Integrating Postgresql in a Go application
3. Working with Gorilla Mux in Go

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Joakim-gakure** [comment]
@Anitaachu, Am covering this topic https://github.com/section-engineering-education/engineering-education/pull/3285
