### ISSUE TITLE
Building a scrollable floating modal with dart

### ISSUE THREAD

**Issue by jerimkaura** [section-engineering-education/engineering-education#3395]
### Proposed title of the article
Building a scrollable Floating modal with Dart

### Introduction paragraph (2-3 paragraphs):
A modal is like a mini screen on a mobile application that provides a smaller user space for interacting with the application other than accessing the entire application. Modals are useful when creating pop up on screens and giving users options to select from.

When modals have information that exceeds the screen size, they need to be made scrollable and float on the main application to ensure that the application looks clean.
This tutorial will teach the reader how to build a scrollable floating modal that ensures a cleaner app interface.

### Key takeaways: 
1. Understanding modals in mobile apps
2. Setting up clean user interfaces
3. Using scrollable modals to enhance the intuitiveness of android apps

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@jerimkaura 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
