### ISSUE TITLE
Bulk insert and bulk export in php

### ISSUE THREAD

**Issue by bastian-zab** [section-engineering-education/engineering-education#3396]
### Proposed title of article
Bulk insert and bulk export in php

### Introduction paragraph (2-3 paragraphs):
When dealing with dynamic data table records, there is a situation where one needs to insert a record. This can be done using a simple insert statement in PHP. However, the procedure is cumbersome when multiple records are to be inserted at once. Performing bulk insert helps one to add multiple records at once.

In this article, the reader will understand how to import and export multiple records using PHP.

### Key takeaways: 
1. Importing multiple records to a MySQL database.
2. Exporting table data to PDF
3. Working with PHP bulk insert

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@bastian-zab 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by WanjaMIKE** [comment]
Closed #3396 via #4193
