### ISSUE TITLE
Understanding Concurrency in GoLang

### ISSUE THREAD

**Issue by Anitaachu** [section-engineering-education/engineering-education#3397]
### Introduction paragraph (2-3 paragraphs):
Smaller sub-programs make up large programs. What is ideal is for these smaller sub-programs to be able to run at the same time. This is what is referred to as Concurrency. 
Concurrency refers to a program's ability to be divided into independent tasks that can be executed at the same time.
This simply means a program that has two or more tasks that can execute individually of each other but are still part of the same program.

Golang has in-built concurrency using goroutines and channels. Concurrency in Golang is also simple and easy to use. 
In this tutorial, we will be using goroutines to run concurrency within a Go application. 

### Key takeaways: 
1. Golang concurrency basics using goroutines. 
2. Difference between concurrency and parallel programming.
3. How to write your program as a collection of independent processes.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@Anitaachu 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Great topic 🚀@Anitaachu, make sure it matches the following:
- Adds value beyond what is in the [official docs](https://www.golangprograms.com/go-language/concurrency.html) and what is covered in other blog sites, like [this one](https://www.geeksforgeeks.org/goroutines-concurrency-in-golang/).
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
