### ISSUE TITLE
Utilizing Lerna and Codefresh to Manage a Typescript Monorepo

### ISSUE THREAD

**Issue by Wanyoike-shift** [section-engineering-education/engineering-education#3399]
### Proposed title of article
Utilizing Lerna and Codefresh to Manage a Typescript Monorepo

### Introduction paragraph (2-3 paragraphs):
Managing dependencies across many sources and simultaneously deploying updates to different repositories can be time-consuming and error-prone. As a result, corporations have adopted the strategy of maintaining several projects in a single repository, known as a Monorepo. With the correct tooling, the advantages of using a Monorepo become evident. Lerna is one of these tools, and it can be used to manage Monorepos based on Nodes.

### Key takeaways: 
In this article, we will cover:
- An overview of Monorepos, including examples and advantages;
- What is Lerna and how might it assist developers with their Monorepo management?
-  A simple demo to show the use of Lerna to create and maintain your Monorepo.
- 
### References: 
N/A

**Comment by WanjaMIKE** [comment]
@Wanyoike-shift 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Thanks for the clarification. Topic approved. Let's ensure that the article adds value to the community. Thanks

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
