### ISSUE TITLE
Creating a progress bar for the terminal/console using Python

### ISSUE THREAD

**Issue by munubi254** [section-engineering-education/engineering-education#3400]
### Proposed title of article
Creating a progress bar for the terminal/console using Python

### Introduction paragraph (2-3 paragraphs):
Maybe your application involves a file upload or download at some point through the terminal/console. You will at one point want to show the progress in the said interface. We will look at how to do that using file download in this article.

### Key takeaways: 
The reader will learn how to create this using:
1. File downloads
2. Python
3. Libraries such as tqdm, progress etc.

### References: 
N/A

**Comment by munubi254** [comment]
@WanjaMIKE, check this.I closed the other one.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
