### ISSUE TITLE
Using JavaScript's mathematical functions and HTML's canvas to create animations

### ISSUE THREAD

**Issue by vinstex** [section-engineering-education/engineering-education#3403]
### Proposed title of article
Using Javascript's mathematical functions and HTML's canvas to create animations

### Introduction paragraph (2-3 paragraphs):
Animations are a great way to catch a user's attention and enhancing the look of your website. In this article, we will look at how Javascript's built-in functions such as `math.min()`, `math.rand()`, `setTimeout()` etc can be applied to create the animations. We will be creating an animation to simulate the planet system so that we see how the functions are applied.

### Key takeaways: 
The reader will look at how these are used in creating animations:
1. JavaScript's shape functions
2. HTML's canvas
3. JavaScript's timing functions
4. CSS styling

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@vinstex 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
