### ISSUE TITLE
Neural Style Transfer with TensorFlow and Python

### ISSUE THREAD

**Issue by wilkistermumbi** [section-engineering-education/engineering-education#3404]
### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Neural Style Transfer with TensorFlow and Python

### Introduction paragraph (2-3 paragraphs):

Neural Style Transfer is a process that uses neural networks to apply the artistic style from one image to another. This means that you can take famous artworks and their styles and apply them to your own images. In this tutorial, we will be using Python and tools like TensorFlow and Matplotlib to apply the neural style transfer to our own image.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to:

1. Downloading a pre-trained model from TensorFlow Hub
2. Preprocessing images for neural style transfer
3. Apply and visualize the style transfer

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

- [TensorFlow Hub](https://www.tensorflow.org/hub)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@wilkistermumbi 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon @wilkistermumbi, and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. Instead, we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way, a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
