### ISSUE TITLE
Introduction to Ambient technology/intelligence

### ISSUE THREAD

**Issue by jonathanwambua** [section-engineering-education/engineering-education#3405]
The document can be downloaded here --> [Ambient technology.docx](https://github.com/section-engineering-education/engineering-education/files/7006161/Ambient.technology.docx)

### Proposed title of article
Introduction to Ambient technology/intelligence

### Introduction paragraph (2-3 paragraphs):

Ambient technology is basically a trending technology that allows electronic systems to be able to recognize and respond to humans hence supporting them in their daily activities. It is built upon several concepts that include, pervasive computing, ubiquitous computing, profiling, context awareness and human centric computer interaction design.

Its applications are diverse, from homes to work spaces, from public places, street lights to hospital systems. All these are areas in which this trending technology can be used to enhance efficiency of activities. The advancements in sensor technologies will be advantageous to this technology.

### Key takeaways: 

1. What ambient technology is.
2. How important it is to the current world.
3. How its connected to context aware systems

### References: 

1. WANG, L. C., MENG, X. W., & ZHANG, Y. J. (2012, March). Context-Aware Recommender Systems. Journal of Software, 1–20. https://doi.org/10.3724/sp.j.1001.2012.04100
2. Anh, V., Cuong, P., & Vinh, P. (2019, May). Context-Aware Mobility in Internet of Thing: A Survey. EAI Endorsed Transactions on Context-Aware Systems and Applications, 158875. https://doi.org/10.4108/eai.13-7-2018.158875

**Comment by WanjaMIKE** [comment]
@jonathanwambua 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Thank you for the topic suggestion @jonathanwambua , however this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore." 🚀
