### ISSUE TITLE
How to Auto Log Off Users Due to Inactivity Using Angular 12

### ISSUE THREAD

**Issue by owinowendy** [section-engineering-education/engineering-education#3406]
### Proposed title of article
How to Auto Log Off Users Due to Inactivity Using Angular 12

### Introduction paragraph (2-3 paragraphs):
An application I’ve been building has some very robust security requirements, one of which is a client side session expiration. This is a feature you’ve likely noticed when logging into mobile banking. You log into your account, switch to another tab, and return to that tab several minutes later to find that you’ve been logged out for inactivity. This helps prevent sensitive information from remaining on an idle user’s screen and reduces the likelihood of a malicious user from accessing the application.

The use case seemed common enough. I started scouring the internet for a solution using Angular 2+ and Ngrx. Alas, I struggled to find a clean solution and went on trying to roll my own. It turned out that implementing this is  simple and I wanted to share it with the interwebs.

### Key takeaways: 
1.Angular 12+ session expiry solution
2. Browsers events handling
3. Monitoring user inactivity on the site.

**Comment by WanjaMIKE** [comment]
@owinowendy 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
