### ISSUE TITLE
Java Singleton Design Pattern

### ISSUE THREAD

**Issue by carowanjiku** [section-engineering-education/engineering-education#3407]
### Proposed title of article

Java Singleton Design Pattern

### Introduction paragraph (2-3 paragraphs):

Singleton is a creational design pattern that assures that only one object of its kind exists and gives other code a single point of access to it. Singletons have nearly the same advantages and disadvantages as global variables. They are quite useful, yet they violate the modularity of our code.

In this article, the reader will learn about the singleton design pattern. Understand early Instantiation of Singleton Pattern and lazy Instantiation of Singleton Pattern.

### Key takeaways: 

 In this article we will cover the following;

1.  Singleton Design Pattern
2. Eager loading singleton object
3. Lazy loading singleton object
4. Synchronized with Thread in Lazy Loading
5. Using Thread with Lazy Loading (Double Check Locking Technique)
6. Enum with Singleton Pattern

### References: 
 N/A

**Comment by WanjaMIKE** [comment]
@carowanjiku 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
