### ISSUE TITLE
Animate elements using CSS

### ISSUE THREAD

**Issue by MahanthChouta** [section-engineering-education/engineering-education#3414]
### Proposed title of article
Animate elements using CSS

### Outline
You can animate elements of a webpage only using CSS. In this tutorial, I'll go through all of the CSS animation parameters in a detailed manner. This tutorial will teach you how to animate components in CSS without the usage of any third-party packages or frameworks. This tutorial is prepared in a way that makes it easy to understand for beginners.

### Key takeaways: 
By the end of this tutorial:
1) one can add any animations that they desire. 
2) one can add animations without prior knowledge of JavaScript.
3) making it simple for them to add animations into their websites.

**Comment by WanjaMIKE** [comment]
@MahanthChouta 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
@MahanthChouta I will encourage you to create a unique project to illustrate the concepts and add value to the readers.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
