### ISSUE TITLE
Getting Started with Google Maps in Angular 12 applications

### ISSUE THREAD

**Issue by bhanjibrilliant** [section-engineering-education/engineering-education#3416]
### Proposed title of article
Getting Started with Google Maps in Angular 12 applications

### Introduction paragraph (2-3 paragraphs):
You may have seen many websites, mobile applications with GIS Map integrations. There are many map solutions but Google Maps is one of the best nevertheless for commercial use, you must buy subscription. In this tutorial, we shall focus on only Google Maps for free usage.

This is a comprehensive tutorial about how to work with Google Maps in the Angular 12 application. In this tutorial, we will learn how to create an interactive Google Map in Angular.

We will learn how to add Google Maps using Google Maps API manually, we are going to rely on Open source Google API to achieve the task.

Also, we will use Angular Google Maps (AGM) Core plugin to embed the map in the Angular 12 application. It is a superb plugin to create Google Maps components in Angular.

### Key takeaways: 
- Create Angular Application
- Install Angular Google Maps Plugin
- Get Maps API Key
- Add Google Maps Module in App Module
- Create Google Map in Angular

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@bhanjibrilliant 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
