### ISSUE TITLE
Overview of Virtualization

### ISSUE THREAD

**Issue by kvardhan10** [section-engineering-education/engineering-education#3417]
### Proposed title of article
Overview of Virtualization

### Introduction paragraph (2-3 paragraphs):
The process of creating virtual environments by extracting the hardware of a single computer is referred to as virtualization. As a result, various environments are created that appear to operate on their own computer and may be considered as independent working operating systems. On any virtual computer, a user may switch between operating systems and work on them concurrently.

Virtual machine monitors (VMMs) or simply “Hypervisors” are utilized to do this. They are in charge of creating and monitoring virtual environments. The host machine is a computer that runs a hypervisor, while guest machines are virtual machines generated by the hypervisor. These guest machines run on the host machine's hardware, and a hypervisor is in charge of distributing those resources to virtual machines.

### Key takeaways: 
The readers will learn:
1. About Virtualization
2. How it works 
3. Why it is helpful
4. Types of Virtualization such as:
     a. Hardware virtualization
     b. Data virtualization
     c. Storage virtualization
     d. Memory virtualization
     e. Network virtualization

### References: 
https://www.redhat.com/en/topics/virtualization/what-is-virtualization
https://en.wikipedia.org/wiki/Virtualization

**Comment by WanjaMIKE** [comment]
@kvardhan10 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
We thank you for submitting your topic @kvardhan10 . After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to suggest another topic. Thanks
