### ISSUE TITLE
A Look at PHP Frameworks

### ISSUE THREAD

**Issue by mosesmoses12** [section-engineering-education/engineering-education#3420]
### Proposed title of the article
A Look at PHP Frameworks
### Introduction paragraph (2-3 paragraphs):
In recent years, many developers have been using frameworks to build their web applications since frameworks speed up the development process and are easy to use.

`PHP` is a popular server-side language that is used to build web applications. It has several frameworks that are used to build applications. A PHP framework provides a basic structure for streamlining the development of web apps.

Since they are several PHP frameworks, the question that every developer asks is: Which is the best framework for me?😕

In this article, we will go through the different frameworks and compare them. We will also look at the pros and cons of each framework and give reasons why a developer should use a certain framework.

By the end of this article, the developer will be able to make a decision on which framework to use for his next project.
### Key takeaways: 
1. Different PHP frameworks .
2. Reasons why a developer should use a certain framework.
3. The pros and cons of each framework.
4. Compare different frameworks.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@mosesmoses12 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Thanks for the clarification. Topic approved. Let's ensure that it adds value to the community. Thanks

**Comment by hectorkambow** [comment]
@mosesmoses12 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by mosesmoses12** [comment]
@hectorkambow am working on this article. Am almost through.
I had a problem with my laptop, but it's now ok.
Thanks
