### ISSUE TITLE
Building a Responsive and Collapsible Sidebar with Ant Design Library and React 

### ISSUE THREAD

**Issue by Tioumoh** [section-engineering-education/engineering-education#3423]
### Introduction:
The three-column web page design is the most widely used web design architecture by modern developers as it provides an efficient way of content presentation. Designing the perfect responsive sidebar, a decade ago was a difficult task that required element manipulation with CSS, but these days modern design libraries such as Ant design library has reduced the complexity of building the perfect sidebar.
### Key Takeaways:
At the completion of this article it is expected that the reader will understand and be able to perform the following
Getting Started with Ant Design Library.
Fundamentals of Ant Design Library.
Elements and Components of Ant Design Library.
Building a responsive sidebar with icons and links using Ant Design Library and React.
Error handling in Ant Design.
### References:
https://ant.design/docs/react/introduce

**Comment by WanjaMIKE** [comment]
@Tioumoh 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Closed #3423 via #3676
