### ISSUE TITLE
Integrating Hover SDK for Offline M-Pesa Payments in Android with Kotlin

### ISSUE THREAD

**Issue by JoelKanyi** [section-engineering-education/engineering-education#3424]
### Introduction paragraph (2-3 paragraphs):
Hover automates existing USSD sessions in the background of Android applications. 

The SDK can run virtually any USSD interaction on any mobile operator globally. This includes mobile money payments, banking services, airtime topup, bill pay, bundle purchases, and more. 

### Features of Hover SDK
- In-app payments - running any USSD-based mobile financial service at the tap of a button
- Data without internet access - doing the payments while offline (not connected to the Internet)
- Customizable UX - Make USSD-based services more accessible and design beautiful user experiences

### Key takeaways: 
- Get to know how Hover works
- What are Actions, how to create and configure the actions you'd like to support
- Integrating the SDK into your app
- Customize the user experience
- Testing and pushing to production

### References: 
- https://www.usehover.com/

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @JoelKanyi 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by JoelKanyi** [comment]
Thank you @ahmadmardeni1

**Comment by WanjaMIKE** [comment]
Closed #3424 via #3696
