### ISSUE TITLE
What Is Ansible?

### ISSUE THREAD

**Issue by Olanetsoft** [section-engineering-education/engineering-education#3426]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.
### Proposed title of the article
What Is Ansible ?

### Introduction paragraph (2-3 paragraphs):
Ansible is an open-source software provisioning, configuration management, and application-deployment tool enabling infrastructure as code. It runs on many Unix-like systems and can configure both Unix-like systems as well as Microsoft Windows.

### Key takeaways: 

- What is Ansible
- Why Ansible
- Ansible configuration
- Ansible architecture, playbook, and inventory.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
[Ansible](https://www.ansible.com/)
[Ansible Docs](https://docs.ansible.com/?extIdCarryOver=true&sc_cid=701f2000001OH7YAAW)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Olanetsoft 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Hi @Olanetsoft. How will your article defer from other pre-existing documentation?

**Comment by Olanetsoft** [comment]
Hello @WanjaMIKE , For better comprehension, I will use graphical/diagram depiction as well as a step-by-step tutorial.

**Comment by WanjaMIKE** [comment]
Check out this PR `https://github.com/section-engineering-education/engineering-education/pull/130`. I feel that you content duplicates what is already covered there. Feel free to suggest another topic. Thanks
