### ISSUE TITLE
Django currency exchange application with currencylayer.

### ISSUE THREAD

**Issue by mercymeave** [section-engineering-education/engineering-education#3427]
### Introduction paragraph (2-3 paragraphs):
Currencplayer API is one of the APIs that provide realtime currency exchange rates. It is easy and reliable to use given its reasdable JSON repsonses.

In this article, I will build a Django application that uses the API to gve realtime currency exchange rates. A user will enter the currencies and find the current conversion rate. Additionally, the application should give the user an opportunity to enter an ammount in one currecny and find the equivalnece in another currency.

### Key takeaways: 
1. Concuming APIs in a Django application
2. Understanding currency conversions 
3. Working withcurrencyplayer API

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @mercymeave 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@mercymeave 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
