### ISSUE TITLE
A beginners guide to Vue.js Router 

### ISSUE THREAD

**Issue by alloyking1** [section-engineering-education/engineering-education#3428]
### **Introduction**
As with everything else in technology, the web development ecosystem is fast paced and constantly evolving. There is always a new and better way to get things done. Prior to now, front end developers coded every functionality from scratch using vanilla JavaScript or a library like jQuery. This approach is time consuming and often times more difficult to maintain the code base as poor design patterns were not far fetched.
Vue.js is a JavaScript front end framework designed to simplify the process of front end development and provide organization to your code base by using components, routing, unique code structures and lots more.

In this post, We will explore routing in Vue.js and how to implement it using Vue router. We will explore the ins and outs of vue router with hands on example. With all this said, lets get right into it.

### **Prerequisite**
To follow along with this tutorial, you need basic knowledge of the follow:
HTML 
CSS 
JavaScript

### **Key takeaways**
It is expected that by the end of this article, readers should:

- Have a clear understanding of what vue.js  router is 
- Be able to install vue router and other dependencies and setup a new vue.js app using NPM or Yarn
- create routes and navigate between routes for the project
- understand router guard and how to implement it in vue

### **Further reading**
We have only scratched the surface of Vue router. For a more in depth study of Vuejs, check out the official documentation here.

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @alloyking1 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by alloyking1** [comment]
Nice, looking forward to it. Thanks.

**Comment by WanjaMIKE** [comment]
Sounds good - Ensure you update your key takeways

**Comment by alloyking1** [comment]
Yes, I’m on it.

**Comment by alloyking1** [comment]
hi @WanjaMIKE, I have made changes to the outline. Take a look and let me know if its good enough for me  to start writing now

**Comment by hectorkambow** [comment]
@alloyking1 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
