### ISSUE TITLE
Getting Started with DVWA

### ISSUE THREAD

**Issue by kimanthi777** [section-engineering-education/engineering-education#3435]
### Proposed title of article
getting started with dvwa

### Introduction paragraph (2-3 paragraphs):
Cyber attacks such as sql injections and cross site request forgery(CSRF) have increased in recent times. This is due to the transition or expansion of enterprises that were previously physical into online based platforms. Majority of these attacks occur due to vulnerabilities in web apps or outdated software that servers run on. Due to this, web developers should have an understanding of how this attacks take place so as to try and avoid them as much as possible.

DVWA is a vulnerable web app that is buggily coded intentionally so as to enable web developers and penetration testers to understand how attacks such as sql injections occur. It also helps them to test their hacking skills on a legal environment. It runs on Php logic and uses MySql database to store information. 

In this article, we shall cover how to setup our local dvwa web app on xampp environment on windows and linux. We shall also learn how to adjust the different security levels on DVWA.

### Key takeaways: 
> Install xampp
> Download and configure DVWA

### References: 
https://github.com/digininja/DVWA

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @kimanthi777 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
