### ISSUE TITLE
Passing data between Child Component and Parent Component in React

### ISSUE THREAD

**Issue by munyite-megzs** [section-engineering-education/engineering-education#3437]
### Introduction:

React is a JavaScript library for building user interfaces. React utilizes reusable components. This allows you to reuse your code, control how the components update, and control how they communicate with each other. Understanding how to pass data between these components is key. 

### Key Takeaways:

At the completion of this article it is expected that the reader will understand and be able to perform the following
Understand what a component is.
Understand what a prop is.
How to pass data from a child component to a parent component.
How to pass data from parent component to child component.

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @munyite-megzs 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
We thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to suggest another topic. Thanks
