### ISSUE TITLE
Authenticate Using Google Sign-In on Android

### ISSUE THREAD

**Issue by Collince-Okeyo** [section-engineering-education/engineering-education#3443]
### Introduction paragraph (2-3 paragraphs):
Sign In With Google is a secure authentication system that reduces the burden of login for your users, by enabling them to sign in with their Google account—the same account they already use with Gmail, Play, Photos and other Google services.
You can let your users authenticate with Firebase using their Google Accounts by integrating Google Sign-In into your app.

### Key takeaways: 
  -What is Google Sign In 
 - Features of Google Sign In
 - Implementation of Google Sign In on Android

### References: 
https://firebase.google.com/docs/auth/android/google-signin

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Collince-Okeyo 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
