### ISSUE TITLE
Understanding Android Studio Project Structure

### ISSUE THREAD

**Issue by anne-sogoli** [section-engineering-education/engineering-education#3444]
### Introduction 
Android Studio is the official IDE (Integrated Development Environment) developed by JetBrains community which is freely provided by Google for android app development.

 In this tutorial, we will learn about android app project structure created using android studio, during this process we will learn about different android file structure like build.gradle ,gradlew and folders like app/src etc.

### Key takeaways: 
- An understanding on android studio project structure
- Knowledge on how to create a new project
- Understanding all the files and folders contained in android studio

### References: 
[Tutorial wing](https://tutorialwing.com/android-project-structure-tutorial/)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @anne-sogoli 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
We thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to suggest another topic. Thanks
