### ISSUE TITLE
How to Create a Contact Form in WordPress

### ISSUE THREAD

**Issue by Robbiewanjau** [section-engineering-education/engineering-education#3445]
### Proposed title of the article
How to Create a Contact Form in WordPress

### Introduction paragraph (2-3 paragraphs):
A website's contact form is an essential component. It serves as a link between the customer and the provider. It's simple to make a contact form for the WordPress platform. To create a successful contact form for a WordPress site, you only need to follow a few simple steps.

In core PHP, we've seen far too many different types of contact form examples. The concept of writing the process flow is the same regardless of platform, framework, or CMS. So, if you know how a contact form works, you'll have no trouble understanding how the WordPress version works.

In this edge, we'll create a custom WordPress template for this contact form's user interface. Then, using the admin panel, map the template for the contact page.

### Key takeaways: 
1.Create a WordPress environment
2.Create a new contact page using WordPress admin
3.Create child-theme for the active theme
4.How to create a contact template
5.Send AJAX request using wp_ajax hooks
6.WordPress contact form output

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Robbiewanjau 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
