### ISSUE TITLE
Guide to development of a website that supports multi-language using php

### ISSUE THREAD

**Issue by Techwiz254** [section-engineering-education/engineering-education#3446]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title *Use keyword research to gain your article higher ranking.*
Guide to development of a website that supports multi-language using php. 
### Introduction paragraph (2-3 paragraphs):
 

A website with multi-language support attracts visitors from all around the world. 
It displays its content in a variety of languages depending on the user's preference.
There are numerous countries in the world that do not speak English. 
Readers from the region may choose to read articles written in their native tongue. 
You can expand your website's readership by supporting these languages.

More than 50 languages can be found on multilingual websites.
 The choice of the language that supports your website is based on different factors. 
It depends mainly on the information you write to and the audience to.
The following controls or features are provided on a website with multi-lingual support.
A content language menu or input.
By default the reader loads content.
To allow default language settings if the language of the reader is not supported.
Switching of dynamic and static content according to the chosen language.
Page URLs convert based on the language selected.

In this Article, we'll use PHP to develop a web page that supports multiple languages.
 It displays both static and dynamic information. The database provides the dynamic material.

### Key takeaways: 
1.why a website needs multiple language support? 
2.ways to add multi language support to a website. 
3.about this example 
4.PHP example files created to enable multi-language support 
5.database scripts
6.how to make a web page HTML for multi-language support 
7.how to switch the content language in PHP
8.multi-language PHP example demo
9.PHP example output of  a multilingual web page supporting two languages. 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Techwiz254 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Thanks for the clarification. Topic approved. Let's ensure that it adds value to the community. Thanks
