### ISSUE TITLE
Configuring EIGRP on a router

### ISSUE THREAD

**Issue by raboba2re** [section-engineering-education/engineering-education#3449]
### Introduction paragraph
Routers exchange information using either static or dynamic routing protocol. Organization can have multiple routers and subnets  configured using either static or dynamic routing protocols, configuring static networks requires a great deal of administrative overhead and it is error prone. 
 
Dynamic routing protocols are used to reduce this administrative overhead and errors. **Enhance Interior Gateway Routing Protocol (EIGRP)** is a dynamic routing protocol used to reduced this overhead and errors. 
This article will look at EIGRP in details and at the end of the article, the reader must have learned:

### Key takeaways: 
- what dynamic routing is
- What EIGRP is
-  How to configure EIGRPv4 on a router
- How to configure EIGRPv6 on a router

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @raboba2re 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@raboba2re 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
