### ISSUE TITLE
How to Use a Local DNS Resolver to Redirect All DNS Requests

### ISSUE THREAD

**Issue by Daniel-muriithi** [section-engineering-education/engineering-education#3452]
### Introduction paragraph (2-3 paragraphs):
A DNS query (also known as a DNS request) is a request for information delivered to a DNS server from a user's computer (DNS client). A DNS request is often performed to obtain the IP address associated with a domain name. An attempt to visit a domain is actually a DNS client requesting DNS servers to obtain the domain's IP address.

While setting up my home network, one can take the approach of allowing only the Unbound DNS service on OPNsense to be accessed and block access to all other DNS servers. This approach will work since any rogue access to external DNS servers is simply blocked. Only the DNS resolver on the local network is allowed (unless the DNS requests are encrypted).

There is, however, a different strategy that can be adopted. All DNS requests to alternate/external servers can be forwarded to your local DNS server with ease. This approach is useful not only for ensuring the proper operation of those devices on your network, but also allows you to restrict or filter DNS requests. The DNS redirect allows you to readily monitor DNS requests that would otherwise go unnoticed if a firewall rule had stopped them.

### Key takeaways:
In this article, the reader will understand:
1.  the reason for redirecting DNS requests to local DNS resolver.
2.  how to create a DNS redirection NAT port forward rule.
3.  the configuration of multiple Interfaces.
4.  how the redirection is tested.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Daniel-muriithi 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Daniel-muriithi** [comment]
Hello @WanjaMIKE and @ahmadmardeni1 what about this article suggestion please. 
Thankyou

**Comment by ahmadmardeni1** [comment]
Great topic 🚀@Daniel-muriithi, make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
