### ISSUE TITLE
How to Use Python Tkinter to Make a Music Player GUI

### ISSUE THREAD

**Issue by majiezra** [section-engineering-education/engineering-education#3460]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to Use Python Tkinter to Make a Music Player GUI

### Introduction paragraph (2-3 paragraphs):

A graphical user interface (GUI) allows users to interact with electronic devices using electronic symbols, as opposed to text-based user links, typed commands, or text exploration. GUIs were designed in response to command-line networks, an apparent steep learning curve, which requires command input via a computer keyboard.

In most cases, activities in a GUI are performed by directly manipulating the graphical elements. GUIs are utilized in a range of mobile gadgets, including MP3 players, gaming devices, workplaces, and industrial controllers, in addition to computers.
In this tutorial we will learn how to build a music player GUI using python.
### Key takeaways: 

- understand the basic concept of GUI and its functions.
- be able to build a music player GUI from scratch.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @majiezra 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Hello @majiezra, Upon a quick google search, there are several articles on this topic. Can you explain how your article will be different from the ones that exist? Thank you.

**Comment by majiezra** [comment]
Hello @lalith1403, This tutorial is a follow-up to a previously published essay on this platform by me (https://www.section.io/engineering-education/introduction-to-gui-in-python-using-tkinter/). This post will go over the pygame module and its basic tools and applications in greater depth, as well as educate the reader on how to create a music app.
thank you

**Comment by louisefindlay23** [comment]
@lalith1403, could you follow up on this when you have time? Thanks.

**Comment by lalith1403** [comment]
This is a good topic to explore. Be sure to focus on building the application and cover each step in detail. Thank you.

**Comment by hectorkambow** [comment]
@majiezra 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
