### ISSUE TITLE
Work on Data Streams in a Quarkus project using Reactive Streams Operator

### ISSUE THREAD

**Issue by RisoriTofa** [section-engineering-education/engineering-education#3461]
### Proposed title of the article

Work on Data Streams in a Quarkus project using Reactive Streams Operator

### Introduction paragraph (2-3 paragraphs)

Data Streams can be defined as continuous data which is being sent or received from a data source to a destination. Data Streams are important in applications.
This is because there are some data types that are expected to come in bits as time goes by.
An example of such data is that from weather forecasting instruments or that from a live video stream.
Since the data streams are continuously fetched, they can be filtered to give the required output as pleased.

In this article, you will learn how to use SmallRye Reactive Streams Operator to work with data streams in a Quarkus project.

### Key takeaways

At the end of this article, you will have gained the following knowledge:

- Setting up SmallRye Reactive Streams Operator in Quarkus
- Some Operations which can be carried out using Reactive Streams Operator in Quarkus
- Apply the operations in the project
- Running the application

### Pre-requisites

The basics of the article include the following:

- Java language knowledge and use
- A Java IDE setup in your machine.
- A stable internet connection.

### References

N/A

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @RisoriTofa 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
@LinusMuema Can you take a look at this topic? Thank you.

**Comment by LinusMuema** [comment]
Hi @RisoriTofa 
This article seems like a helpful one with a lot of room for content. Just make sure you add original content that doesn't conflict with content already on section.

Topic approved :rocket:

**Comment by hectorkambow** [comment]
@RisoriTofa 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by RisoriTofa** [comment]
@hectorkambow , I've finished writing the article...please could you open it so that I can attach the pr

**Comment by WanjaMIKE** [comment]
Closed #3461 via #4165
