### ISSUE TITLE
Design a Sign-up and Login GUI using JavaFX

### ISSUE THREAD

**Issue by blacklihgt** [section-engineering-education/engineering-education#3463]
### Proposed title of the article

Design a Sign-up and Login GUI using JavaFX

### Introduction paragraph (2-3 paragraphs)

JavaFX is an open-source Java framework that is used to create, develop, and deliver highly portable hardware-accelerated user interfaces.
It is used to create GUI's for Rich Internet Applications (RIA), Web, desktop, and embedded and mobile applications.
Login and Sign-up forms have a unique design which makes the site presentable and of a unique design.

In this article, you will learn how to build a JavaFX Login and Sign-up User Interface(UI).

### Key takeaways

At the end of this article, you will have gained the following knowledge:

- What is JavaFX
- JavaFX libraries
- Setting up a JavaFX project
- Designing the Login and Sign-up form
- Running the application

### Pre-requisites

The basics of the article include the following:

- Java language knowledge and use
- A Java IDE is set up in your machine.
- A stable internet connection.

### References

N/A

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @blacklihgt 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
