### ISSUE TITLE
Multi-Factor Authentication

### ISSUE THREAD

**Issue by kvardhan10** [section-engineering-education/engineering-education#3464]
### Proposed title of article
Multi-Factor Authentication

### Introduction paragraph (2-3 paragraphs):
When it comes to logging into anything, such as an account, website, database, etc, the usage of a username and password is a necessity. Username is the unique user ID and password is a string of characters that allows access to the same. However, this is not always reliable. Usernames may be made public, and passwords may be hacked using tactics such as brute force attacks, phishing, and so on. 
This is where Multi-factor authentication comes into the picture. As the name implies, to authenticate someone, more than simply a password is required. It is a method in which the user is asked to authenticate multiple times through several factors to gain access. This can help in safeguarding crucial and sensitive data such as banking information, PIN numbers, identity documents, and so on.

### Key takeaways: 
The readers will learn about:

- multi-factor authentication[MFA]
- the need for MFA
- different factors of MFA
- advantages and disadvantages of using MFA

### References: 
https://www.onelogin.com/learn/what-is-mfa
https://en.wikipedia.org/wiki/Multi-factor_authentication

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @kvardhan10 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by kvardhan10** [comment]
@WanjaMIKE My bad! I wasn't aware of that article. I think that it has almost everything I wanted to cover and even more. We can close this issue and I'll come up with something else. Is that okay?

**Comment by WanjaMIKE** [comment]
@kvardhan10 Yes, its okay. Feel free to suggest another topic. Thanks
