### ISSUE TITLE
How to obtain bloodvessel segmentation in retinal images using matlab

### ISSUE THREAD

**Issue by queenterbruce063** [section-engineering-education/engineering-education#3468]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
Retinal imaging takes a digital picture of the back of your eye. It shows the retina (where light and images hit), the optic disk (a spot on the retina that holds the optic nerve, which sends information to the brain), and blood vessels. This helps your optometrist or ophthalmologist find certain diseases and check the health of your eyes. Blood vessel segmentation involves the process of removing unwanted parts or features of the image that the convolution network might unwantedly learn.
This segmentation process is very important in the field of medicine. This is since when the vessels are segmented and viewed closely, then the solution of or the cause of a given problem may be defined. This makes it a good application in this field. In this article, we are going to look how we can obtain the blood vessel segmentation in case you have the retinal image.

### Key takeaways: 
- Basic understanding of blood vessel segmentation.
- Applications of blood vessel segmentation.
- Matlab code for obtaining the segmentation.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Good afternoon and thank you for submitting your topic suggestion. @queenterbruce063 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Hello @lalith1403, I trust you are doing well. Could you please have a look at this topic when you get a chance. It has been in the queue for quite some time. Thanks.

**Comment by lalith1403** [comment]
This is a great topic. Focus on explaining the steps involved with segmentation, how does segmentation work and then get into the code part of it. Topic approved.
