### ISSUE TITLE
Machine Learning for audio classification

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#3474]
### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Machine Learning for audio classification

### Introduction paragraph (2-3 paragraphs):

In this tutorial, you'll get an introduction to Machine Learning for audio classification and also some of the theory that is needed to understand it. We will also be implementing audio classification by using the TensorFlow machine learning framework. We will be taking into account a raw audio dataset and categorized it into speech and music. Followed by pre-processing, creating, and training a deep learning model to perform classification. This way we can classify incoming audio in one of the two classes, in either speech or music.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial a reader should be able to:

1. Set up the working environment.
2. Perform data exploration
3. Create a spectrogram
4. Perform data pre-processing
5. Create the model
6. Train the model
7. Make predictions

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Bayler 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @Bayler

**Comment by sridhatta** [comment]
Hi @Bayler  I am interested to take up this exercise. Please let me know if you can assign it.

**Comment by Bayler** [comment]
Hi @sridhatta do you mean to review?

**Comment by sridhatta** [comment]
I mean for creating the article.

**Comment by Bayler** [comment]
This one has already been issued. Please submit another topic issue that is different from this one.

**Comment by WanjaMIKE** [comment]
Closed #3474 via #3634
