### ISSUE TITLE
How to use Matlab to solve discrete logistic equations

### ISSUE THREAD

**Issue by peterAdongo** [section-engineering-education/engineering-education#3475]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
The logistic equation is a simple model of population growth in conditions where there are limited resources. The main objective of the model is to find the carrying capacity. Carrying capacity is the largest population that can be supported indefinitely, given the resources available in the environment. 
In ecology, for example, the logistic equation has been widely used to model the population growth where the rate of reproduction is proportional to both existing population and the amount of resources available. In this article, we will look at how to use Matlab to solve these logistic problems.

### Key takeaways: 
- Understanding of the logistic problems.
- How to use Matlab to solve these problems.
- Applications of the developed models.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Good afternoon and thank you for submitting your topic suggestion. @peterAdongo 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @peterAdongo
