### ISSUE TITLE
How to troubleshoot and monitor a Database

### ISSUE THREAD

**Issue by extravaganza77** [section-engineering-education/engineering-education#3476]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction paragraph (2-3 paragraphs):
Database monitoring is the process of examining database performance and resources in order to build and maintain a high-performance and high-availability application architecture.
Databases are at the heart of many organization's most important business procedures. The complexities of applications is increasing, and IT infrastructures are getting increasingly varied. Database troubleshooting that delivers rapid, accurate problem resolution is important for helping IT diagnose problems before they affect end-users, especially with complex applications working across heterogeneous infrastructures.

### Key takeaways: 
- how to monitor a database
- Database monitoring tools
- Database network traffic
- SQL server performance monitoring
- Decrypting an encrypted data 

### References: 
- N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @extravaganza77 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Closed #3476 via #3675
