### ISSUE TITLE
Why Use Load Balancing in an Application. 

### ISSUE THREAD

**Issue by munyite-megzs** [section-engineering-education/engineering-education#3477]
###Proposed title of article
Why Use Load Balancing in an Application?

###Introduction:
Load Balancing is a critical component of a distributed system. It Spreads traffic across a cluster of servers to improve responsiveness and availability of applications, websites or databases. Load balancers tracks availability of resources while distributing requests. If a server is not available or has an elevated error rate the Load Balancer will stop sending that server traffic.

###Key takeaways:
At the end of this article the learner will be able to:
1) Understand what a Load balancer is.
2) Know the Advantages of using Load balancers.
3) Know the different types of Load balancer algorithms that can be used in an application. 

References:
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @munyite-megzs 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by munyite-megzs** [comment]
@WanjaMIKE done with the write up
