### ISSUE TITLE
Create  a registration form using React.js ( Hooks )

### ISSUE THREAD

**Issue by anubhavb11** [section-engineering-education/engineering-education#3484]
### Introduction paragraph (2-3 paragraphs):
React.js is is the most popular javascript library used for building user interfaces. React js breaks down your site and complex UI into small components, In this article, you will get to learn the basics of React.js and be able to build an interactive registration form.
We’ll assume that you have some familiarity with HTML and JavaScript, but you should be able to follow along even if you’re coming from a different programming language. Will focus extensively on theory and functionality so you could learn the best out of it. 
### Key takeaways: 
- Creating a basic registration form
- Get to learn about React.js
- Get to learn about hooks

**Comment by anubhavb11** [comment]
@ahmadmardeni1  please look at it as per our conversation on slack

**Comment by ahmadmardeni1** [comment]
Thank you for submitting this topic.
But this topic is already covered widely and especially in the official docs. Maybe you can build a unique/original project using the concept? @anubhavb11

**Comment by anubhavb11** [comment]
I can include the firebase database setup in the article.
So that when users submit the form there data will be stored over there. 
@ahmadmardeni1  can we go with that?

**Comment by ahmadmardeni1** [comment]
We already have a couple of tutorials covering Firebase. What else can you add to the tutorial? @anubhavb11

**Comment by anubhavb11** [comment]
I have not found any article about react.js + firebase at engineering-education.
There are with node.js and react native but not with react.js I can't think of anything else we can do in the registration form if u have any idea I will be happy to research and write about it ( anything in we do in front-end dev would be great)  @ahmadmardeni1

**Comment by ahmadmardeni1** [comment]
@mercymeave @WanjaMIKE  Could you take a look at this topic suggestion when you have the chance? Since you have expertise in React. What can we add to the tutorial to make it unique/original?

**Comment by WanjaMIKE** [comment]
> @mercymeave @WanjaMIKE Could you take a look at this topic suggestion when you have the chance? Since you have expertise in React. What can we add to the tutorial to make it unique/original?

sure

**Comment by WanjaMIKE** [comment]
@anubhavb11 if you are linking the registration form to firebase that is nice. It will allow your article to be unique and valuable. Thanks

**Comment by hectorkambow** [comment]
@anubhavb11 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by anubhavb11** [comment]
I created pr for this topic yesterday only #4025  
@hectorkambow
