### ISSUE TITLE
Core Concepts Of Redux Store Management

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#3486]
Redux happens to be one of the libraries that brought about the concept of store management in application. Store management refers to the process of storing data provided by the  API coming from the backend to the frontend. Redux allows the data stored in 'store manager' to be available to all components of the application that need it.

### Key Takeaways
1. How to integrate redux with an application
2. Concept of store management
3. Meaning of action and reducer functions
4. How to connect the redux store to components.
5. Lastly, How to make asynchronous calls using redux thunk.

### References
https://redux.js.org/introduction/getting-started

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Horlawhumy-dev 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Horlawhumy-dev** [comment]
Hi!!

**Comment by Horlawhumy-dev** [comment]
Thanks and I am already working on the article.

**Comment by WanjaMIKE** [comment]
Closed #3486 via #3586
