### ISSUE TITLE
Null Safety Support For Flutter & Dart

### ISSUE THREAD

**Issue by FranciscaNg** [section-engineering-education/engineering-education#3489]
### Proposed title of article
Null Safety Support For Flutter & Dart
### Introduction paragraph (2-3 paragraphs):
In basic terms, null safety means that a variable cannot have a ‘null' value unless it was started with null. All runtime null-dereference problems will now be shown at compile-time, thanks to null safety. By catching null errors during development rather than at runtime, Null Safety helps you prevent a wide range of issues.

In this article, the learner shall understand all the null safety features and their benefits.

### Key takeaways: 
-What are Null Safety principles?
-What are Nullable and Nonnullable types?.
-When it comes to design principles, what do you mean by "no safety?"
-Unsound null safety.
-Making the use of a null safety easier
-Null-safety migration
-Null-safety migration in Flutter
-Reasons to migrate a Flutter app to null safety
### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @FranciscaNg 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
@FranciscaNg  will you be building an app to showcase the key takeaways?

**Comment by FranciscaNg** [comment]
@WanjaMIKE 
I'll be explaining all the key takeaways as well as providing an example of each one of them while developing an app.

**Comment by WanjaMIKE** [comment]
Okay. Let's ensure that it adds value to the community. Thanks

**Comment by FranciscaNg** [comment]
Thanks @WanjaMIKE

**Comment by WanjaMIKE** [comment]
Closed #3489 via #3733
