### ISSUE TITLE
Authentication Using Facebook in Android Studio

### ISSUE THREAD

**Issue by Owallah** [section-engineering-education/engineering-education#3493]
### Proposed article Title
Authentication Using Facebook in Android Studio

### Introduction:
Signing in with Facebook is a secure authentication system that reduces the burden of login for your users. This is because it enables users to sign in with their already existing Facebook account.
This is achieved by using Firebase's Authentication with Facebook as we will be discussing in this tutorial

### Key takeaways:
By the end of the article the reader will be able to:
- Understand what is Firebase.
- Understand What is Authentication.
- Understand Authentication with Facebook.

### References
[Authenticate using Facebook Login on Android](https://firebase.google.com/docs/auth/android/facebook-login)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Owallah 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Owallah 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by Owallah** [comment]
Hello @hectorkambow 
I'm ready with this article.
Would you please reopen it
