### ISSUE TITLE
Handling Memory Leaks In Android Using LeakCanary

### ISSUE THREAD

**Issue by Collince-Okeyo** [section-engineering-education/engineering-education#3494]
### Proposed title of article
Handling Memory Leaks In Android Using LeakCanary

### Introduction paragraph :
LeakCanary is a memory leak detection library for Android. LeakCanary’s knowledge of the internals of the Android Framework gives it a unique ability to narrow down the cause of each leak, helping developers dramatically reduce OutOfMemoryError crashes. 

### Key takeaways: 

- What is Memory leak and LeakCanary.
- Causes of Memory leak.
-  Advantages of LeakCanary in android development.
-  How to handle leaks in android applications using LeakCanary.

### References: 
- https://square.github.io/leakcanary/

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Collince-Okeyo 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Great topic 🚀@Collince-Okeyo, make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
