### ISSUE TITLE
How Java Virtual Machine Works 

### ISSUE THREAD

**Issue by Geofreytech** [section-engineering-education/engineering-education#3496]
### Proposed title of article
How Java Virtual Machine Works 

### Introduction paragraph (2-3 paragraphs):
The JVM (Java Virtual Machine) is a run-time engine that allows Java programs to run. The JVM is the program that executes the main function in java programming. JVM is a component of JRE (Java Runtime Environment). The compiler in other programming languages generates machine code for a specific system. The Java compiler, on the other hand, generates code for the Java Virtual Machine.

At the end of this article, the reader shall understand how a java virtual machine works.

### Key takeaways: 
-How does JVM execution engine work?
-How JVM Memory is used.
-The Java Native Interface (JNI).

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Geofreytech
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
