### ISSUE TITLE
Drug labels extraction using Deep Learning 

### ISSUE THREAD

**Issue by wilkistermumbi** [section-engineering-education/engineering-education#3497]
### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Drug labels extraction using Deep Learning 

### Introduction paragraph (2-3 paragraphs):

In this tutorial, you'll be able to leverage deep learning to extract prescription medication labels using PaddleOCR. PaddleOCR is an Optical Character Recognition (OCR) model developed by Chinese company, Baidu using the `PaddlePaddle` (PArallel Distributed Deep Learning) deep learning framework. This has a range of applications and could be used as part of a broader deep learning pipeline. You could use it in your project to integrate with a Text to Speech (TTS) system to make your own visual translation service. This would make it easier for people with accessibility issues to interpret their medications. 

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will learn how to:

1. Install PaddleOCR for Python
2. Applying OCR to images
3. Extract prescription medication labels using PaddleOCR

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

1. [PP-OCR: A Practical Ultra Lightweight OCR System](https://arxiv.org/pdf/2009.09941v3.pdf)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @wilkistermumbi 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @wilkistermumbi
