### ISSUE TITLE
Starting with jQuery

### ISSUE THREAD

**Issue by jakim34511171** [section-engineering-education/engineering-education#3499]
### Proposed title of article
Starting with J query
### Introduction paragraph (2-3 paragraphs):
To get started with JQUERY one need to Download the jQuery library from jQuery.com.
Include jQuery from a CDN, like Google After setting up the environment and including reference of jQuery library in your web page, it's time to use jQuery
JQUERY has some of the functions. Jquery () function
When you open your web page in a browser and load jQuery library successfully, it adds a global function named jQuery(). 

### Key takeaways: 
helps the learner to understand:
- Query makes use of powerful, clean, and simple syntax that makes it easier to pick the DOM elements on the webpage that you want to change with JavaScript 
-  enable you to chain effects and actions together for effective code

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @jakim34511171 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @jakim34511171. It's been some time since we suggested you should alter your topic to add more unique value to our readers. We are closing this now to make more room in our queue but feel free to reopen it once you're ready to tweak your topic to be more unique and provide more value to our readers.
