### ISSUE TITLE
Online Machine Learning with River Python

### ISSUE THREAD

**Issue by Bravinsimiyu** [section-engineering-education/engineering-education#3502]
### Proposed title of article
Online Machine Learning with River Python

### Introduction paragraph (2-3 paragraphs):
Online machine learning is a method of machine learning in which data becomes available in sequential order and is used to update the best predictor for future data at each step. This is different from traditional or offline machine learning which generates the best predictor by learning on the entire training data set at once on the dataset is locally available.

In online machine learning, it is necessary for the algorithm to dynamically adapt to new patterns in the data, or when the data itself is generated as a function of time. It represents a dynamic technique of supervised learning and unsupervised learning that can be applied when training data becomes available gradually over time or its size is out of system memory limits.

This is useful in sites where they use real-time data where it's important to update our estimates as each new data point arrives rather than waiting until “the end”. It's popular among streaming sites where the data is continuously changing.

The aim of online machine learning is for the learning model to adapt to new data without forgetting its existing knowledge.
In this tutorial, we shall use River Python which is a great library for online machine learning.

### Key takeaways: 
1. What is online machine learning.
2. What is the difference between online and offline/traditional machine learning.
3. Installing River Python.
4. Handling real-time data.
4. Building pipeline for online machine learning.
5. Building our model using RIver Python.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @Bravinsimiyu.
