### ISSUE TITLE
Creating a Function that Can Handle any Number of Arguments

### ISSUE THREAD

**Issue by Terripha** [section-engineering-education/engineering-education#3504]
### Proposed title of article
Creating a Function that Can Handle any Number of Arguments

### Introduction paragraph (2-3 paragraphs):
One of the most crucial considerations when writing a JavaScript function is the arguments your function will accept as input. A function in JavaScript is a block of code that performs a specific task.

In JavaScript, you can pass any number of arguments to a function, regardless of what the function declaration specifies. There is no limitation on the number of function parameters. This becomes a little more difficult if you don't know how many arguments you'll need or if you want your function to accept any number of parameters. If you are unfamiliar with the required syntax, it can be difficult to figure out on your own.

In this article, I will use some examples to demonstrate how this can be accomplished.

### Key takeaways: 
1 Ways of Creating a Function that Can Handle any Number of Arguments:
- Arguments object
-  Rest parameters
-  Arrow Functions
2. Examples to demonstrate how this can be accomplished 
3. Methods associated e.g `reduce()` method

### References: 
N/A

**Comment by louisefindlay23** [comment]
@Terripha, it's been some time since we've prompted you to rework your topic suggestion to be more unique so we're closing this now to make more room in the queue. Feel free to reopen it when you're ready.
