### ISSUE TITLE
PHP Forgot Password Recover Code

### ISSUE THREAD

**Issue by luis-mwangi** [section-engineering-education/engineering-education#3509]
### Proposed title of article
PHP Forgot Password Recover Code

### Introduction paragraph (2-3 paragraphs):
In this article, we will look at an example of how to recover a forgotten password.
  we will create a forgot password form that collects the username or email address in order to recover the password. 
After the form is submitted, we will send the user an email with a password recovery link. 
The Password Reset email contains a link to a page where we can reset the password.

### Key takeaways: 
1.Password reset
2.Reset password form
3.Recover Password Database Structure
4.Forgot password recovery email
### References: 
N/A

**Comment by luis-mwangi** [comment]
@WanjaMIKE  No i won't be using the PHP framework you can use JS or python

**Comment by WanjaMIKE** [comment]
@luis-mwangi Okay. Let's ensure that it adds value to the community. Thanks

**Comment by luis-mwangi** [comment]
thank you waiting for the approval
