### ISSUE TITLE
Debugging with Stetho in Android

### ISSUE THREAD

**Issue by anne-sogoli** [section-engineering-education/engineering-education#3510]
### Introduction
 Stetho is an open-source debug library developed by Facebook. It allows you to use chrome debugging tools to troubleshoot network traffic., thus it provides a rich, interactive debugging experience for android developers.

With this library, you need to have an active emulator or device running, and you use with Chrome to connect to the device by typing chrome://inspect.

### Key takeaways: 
-you will be able to debug with stetho
-you will gain knowledge on how stetho works
-you will know the problems solved by stetho

### References: 
[tutsplus](https://code.tutsplus.com/tutorials/debugging-android-apps-with-facebooks-stetho--cms-24205)
[better programming](https://betterprogramming.pub/stetho-the-best-debugging-tool-for-android-applications-1b1f0b99dc0e)

**Comment by hectorkambow** [comment]
@anne-sogoli 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by anne-sogoli** [comment]
Hello, I am ready to push the article, can someone reopen the issue for me?

cc @hectorkambow @LinusMuema  @ahmadmardeni1
