### ISSUE TITLE
Building a Gmail Swipe to Delete Gesture & Animated FAB 

### ISSUE THREAD

**Issue by Newton-cyber** [section-engineering-education/engineering-education#3512]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction paragraph (2-3 paragraphs):
In this tutorial, we will implement an animated fab button and a special behaviour to slide and delete items from an Ionic list.
All of this will be possible through the usage of Ionic gestures and the Animation API, which are truly powerful as we will see.
The fist part will be a bit easier, we simply want to expand or shrink a fab button when we scroll up or down.
### Key takeaways: 
1. Creating a FAB Animation while scrolling
2. Sliding Item to Archive and Delete
3. Using the Swipe Item
4. Fade and move out the text inside the span of the fab
5. Reverse this operation when we scroll up again.

### References: 
kotlin/android

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Thanks for the clarification. Topic approved. Let's ensure that it adds value to the community. Thanks

**Comment by hectorkambow** [comment]
@Newton-cyber 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
