### ISSUE TITLE
Build a CRUD Serverless API with AWS Lambda, API Gateway and a DynamoDB 

### ISSUE THREAD

**Issue by joni-kano** [section-engineering-education/engineering-education#3515]
### Introduction paragraph (2-3 paragraphs):
Lambda is AWS’s serverless compute service that lets you run code without provisioning or managing servers. Serverless computing is a cloud computing service where the cloud provider (e.g., AWS) owns the server, runs the server and dynamically manages the allocation of machine resources. Pricing of a serverless computing service is based on the actual amount of resources consumed by an application, rather than on pre-purchased units of capacity.

DynamoDB is AWS’s NoSQL database service that supports both document and key-value data models and is typically used for applications that need consistent, millisecond latency at any scale. Its flexible data model and reliable performance make it a great fit for mobile, web, gaming, ad-tech, IoT and many other applications. There is a way where we can use both the DynamoDB using the lambda to achieve the serverless service to our advantage. 
 
### Key takeaways: 
-understand the concept of not needing provision or managing servers.
-Understand concept of horizontal scaling.
-Minimize cost of Idle and increase reliability 
### References: 
-https://jinmeister.com/aws/individual-services/dynamodb
-https://jinmeister.com/aws/individual-services/lambda
-https://github.com/felixyu9/serverless-api-tutorial-code/blob/main/index.js

**Comment by louisefindlay23** [comment]
@WanjaMIKE, happy to help out with this topic suggestion. What sort of help are you looking for?

**Comment by joni-kano** [comment]
I would like someone to help me in the coding process

**Comment by joni-kano** [comment]
I will share the details in a few minutes

**Comment by joni-kano** [comment]
API Gateway and on Dynamo Database but with additional time I can handle
task individually
