### ISSUE TITLE
History of Programming Languages

### ISSUE THREAD

**Issue by Ingasha-Sharon** [section-engineering-education/engineering-education#3516]
### Proposed title of article
History of Programming Languages

### Introduction
 Computer programming languages allow us to tell machines what to do. Machines and humans “think” very differently, so programming languages are necessary to bridge that gap. The first computer programming language was created in 1883, by a woman named Ada Lovelace.

### Key takeaways: 
- What is Programming
- Programming languages
- Features of Programming languages.

### References: 
https://www.onlinecollegeplan.com/computer-programming-languages/
https://devskiller.com/history-of-programming-languages/

**Comment by ahmadmardeni1** [comment]
We are focusing on programmer-centric concepts. I don't think we should approve it. @WanjaMIKE

**Comment by Ingasha-Sharon** [comment]
Can I therefore raise another issue or i wait for its approval @ahmadmardeni1 @WanjaMIKE

**Comment by WanjaMIKE** [comment]
@Ingasha-Sharon please feel free to suggest another topic. Thanks
