### ISSUE TITLE
Java Native Interface

### ISSUE THREAD

**Issue by Shikomary** [section-engineering-education/engineering-education#3521]
### Proposed title of article
Java Native Interface

### Introduction paragraph (2-3 paragraphs):

As we know, one of Java's key advantages is its portability, which means that when we create and compile code, the outcome is platform-independent bytecode. Simply put, this can run on any machine or device that can run a Java Virtual Machine, and it will run as smoothly as possible.

However, there are situations when we need to use natively compiled code for a specific architecture. In this article the reader will be able to understand  Java Native Interface and how to implement it. 

### Key takeaways: 

   The reader will understand the following;

- Native Methods.
-  JNI Elements in Code (Java).
-  Creating the Java Class.
-  Compiling and Linking.
- Adding Parameters To Our Native Methods.
- Using Objects and Calling Java Methods From Native Code.
- Advantages and disadvantages of Using JNI.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Okay. Topic approved. Let's ensure that it adds value to the community. Thanks
