### ISSUE TITLE
How to choose the appropriate microservices framework for your project?

### ISSUE THREAD

**Issue by martha-ngugi** [section-engineering-education/engineering-education#3524]
### Proposed title of article
How to choose the appropriate microservices framework for your project?

### Introduction:
Microservices architecture allows developers to split a huge monolithic single application into small applications and services that perform lightweight tasks.
Business capabilities and independently deployable models are the primary goals of microservices development. Microservices architecture is built using different programming languages, they can be deployed and interconnected.

Businesses and developers face challenges in choosing the right microservice framework when building their robust applications as fast as possible and at a minimal cost. The article will equip the learners with the aspects to consider when selecting a microservice framework for their projects and compare between different frameworks available.

### Key takeaways: 
At the end of the article, the learner will be able to:
- understand the benefits offered by microservices
- understand critical aspects to consider when selecting the right framework for the project
- highlight different frameworks for developing microservice architecture

### References: 
N/A

**Comment by louisefindlay23** [comment]
Hi, @martha-ngugi. Great topic suggestion. 

Can you tell me more about the frameworks your article would highlight? How does your article differ from similar ones such as this [Clariontech blog post](https://www.clariontech.com/blog/5-best-technologies-to-build-microservices-architecture)?

**Comment by martha-ngugi** [comment]
> Hi, @martha-ngugi. Great topic suggestion.
> 
> Can you tell me more about the frameworks your article would highlight? How does your article differ from similar ones such as this [Clariontech blog post](https://www.clariontech.com/blog/5-best-technologies-to-build-microservices-architecture)?

@louisefindlay23 Thank you for getting back to me.
The article will concentrate on:
- outline pros and cons offered by microservices architecture
- look at aspects to consider when selecting the right microservices framework interns of planning and organizing, microservices design, development, data storage and management, microservices deployment and hosting, and microservices maintenance and operations.
- explain popular frameworks used to develop microservices such as Spring Boot, Eclipse Vert.x, Oracle Helidon, GoMicro, and Molecular.

**Comment by louisefindlay23** [comment]
Thanks, @martha-ngugi. Topic approved 🚀. 

Be sure to cover those areas in plenty of detail to add lots of value to oir readers.

**Comment by martha-ngugi** [comment]
> Thanks, @martha-ngugi. Topic approved 🚀.
> 
> Be sure to cover those areas in plenty of detail to add lots of value to oir readers.

@louisefindlay23 Noted. 
Thank you

**Comment by WanjaMIKE** [comment]
Closed #3524 via #3753
