### ISSUE TITLE
Static Web Hosting with Firebase Hosting

### ISSUE THREAD

**Issue by greatnessss** [section-engineering-education/engineering-education#3525]
### Introduction paragraph (2-3 paragraphs):
Everybody wants to show what they do to the world. Probably what made you be interested in becoming a Web Developer is the ability to show what you do to the world with just a link, and firebase helps you achieve this, by enabling you to deploy your Static Website seamlessly and cost-free.

So you are done writing your codes and you need to serve these static contents which include your HTML, JS, CSS files as well as images and other assets that your client-side app needs to run. In this tutorial, I will be walking you through deploying your static website on Firebase with Firebase

### Key takeaways: 
By the end of this tutorial, you should be able to:
1. Deploy Static Websites with Firebase Hosting
2. Know how to add a custom domain to your firebase project?
3. Know how to remove .html in the URL of your firebase project?
4. How to set up redirect URLs on firebase project?

### References: 
For more details and further information, kindly follow the official documentation, through this link: https://firebase.google.com/docs/hosting

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @greatnessss 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
