### ISSUE TITLE
How to Create a URL Shortener with JavaScript

### ISSUE THREAD

**Issue by JudyNduati** [section-engineering-education/engineering-education#3526]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to Create a URL Shortener with JavaScript

### Introduction paragraph (2-3 paragraphs):
This guide will show you how to build a URL shortening service like bit.ly or goo.gl using JavaScript. A URL shortener is useful for shortening long URLs so that you can easily share them with your friends or co-workers. 

To understand how these things work, we need to take a closer look at an URL shortener, so we’ll be building a simple URL shortener. With that task, we’ll be learning some new things and understanding how URL shortener works.

### Key takeaways: 
1. URL shortener
2. How does a URL shortener works?
3. Building a URL shortener

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Qodestackr** [comment]
Hey @JudyNduati make sure that your article  does not overlap this: https://www.section.io/engineering-education/nodejs-url-shortener/
cc: @hectorkambow

**Comment by Kayere** [comment]
@JudyNduati - Could you please explain how your article will be different from the one mentioned by @Qodestackr.

**Comment by JudyNduati** [comment]
@Kayere, @Qodestackr This tutorial will guide learners to create a URL shortener with JavaScript and HTML. The URL shortener won't need a database system to host it. Instead, we'll use jsonstore.io

**Comment by Kayere** [comment]
Good topic @JudyNduati - approved. Make sure to link any related Section engineering education articles in your article.

**Comment by hectorkambow** [comment]
@JudyNduati 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by JudyNduati** [comment]
@hectorkambow, I opened a PR. Please re-open this issue
