### ISSUE TITLE
Life Cycle Methods Vs useEffect Hook in React

### ISSUE THREAD

**Issue by Umoren** [section-engineering-education/engineering-education#3529]
### Proposed title of article
Life Cycle methods Vs useEffect Hook in React

### Introduction paragraph (2-3 paragraphs):
Having to constantly switch between functions, classes, higher-order components, and render props in a react project could be so tricky to wrap your head around. The react core team came up with the hooks which make us write reusable logic seamlessly. In this article we will explore how to replace the life cycle methods with the `useEffect` hook.

### Article Structure

- Component Lifecycle methods
- `useEffect` Hook
- `useEffect` Vs `componentDidMount`
- `useEffect` Vs `componentDidUpdate`
- Conclusion

### Key takeaways: 
> What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

The reader at the end of the article will be able to:
- Understand how to use the `useEffect` hook effectively
- Learn how the `useEffect` hook replaces `componentDidMount` and `componentDidUpdate`
- Learn from code examples how to migrate a class-based component lifecyle to functional component `useEffect`
- Get tips on how to use dependencies when using the `useEffect` especially when calling API endpoints

### References: 
> Please list links to any published content/research that you intend to use to support/guide this article.
- [React Documentation](https://reactjs.org)

**Comment by louisefindlay23** [comment]
Hi, @Umoren. Thanks for submitting your topic suggestion. Can you please fill out the remaining sections of the topic suggestion form I've added back in for you?

**Comment by Umoren** [comment]
Hi @louisefindlay23. I've updated the topic suggestion form.

**Comment by Umoren** [comment]
Oh didn't see this.
It covers most of my outline except the dependencies part.

**Comment by louisefindlay23** [comment]
@Umoren, we focus on original and unique content so I would suggest you expand your proposed article to cover additional adjacent topics or tell me how you will be write about a unique viewpoint or take on this. Alternatively, choose a different topic which has not been covered extensively elsewhere.

**Comment by WanjaMIKE** [comment]
Thank you for the topic suggestion @Umoren , however this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. cc @louisefindlay23
