### ISSUE TITLE
Building Backend Applications using Astra DB

### ISSUE THREAD

**Issue by Qodestackr** [section-engineering-education/engineering-education#3531]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
Building Backend Applications using Astra DB

### Introduction paragraph (2-3 paragraphs):
Astra DB is a Multi-cloud DBaaS built on Apache Cassandra. Normally, cloud-native Cassandra application development is complicated. Astra DB simplifies this by reducing deployment time to deliver an unprecedented combination of serverless, pay-as-you-go pricing with the freedom and agility of multi-cloud and open source.

This database runs on Apache Cassandra, which uses the Cassandra Query Language (CQL) to create tables which is similar to SQL. The main difference is that Apache Cassandra databases are non-relational, so they use different concepts to store and retrieve data.

### Key takeaways: 
1. An introduction to distributed, wide-column store, NoSQL database management system such as Apache Cassandra.
2. Features that Astra DB offers such as Serverless, Stargate APIs that work natively with Document (JSON), REST, and GraphQL APIs, Scalability, Security, and more.
3.Creating a DataStax Astra database, generating tables, inserting some data, and how to retrieve data.
4. Use React and Nodejs to build an application

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @Qodestackr 
This sounds like an informative tutorial. Please make sure it does not conflict with content already available on section and that it has more original content. Otherwise, topic approved.

:rocketP:

**Comment by WanjaMIKE** [comment]
To help avoid a backlog queue (and longer review times) we are currently only accepting ONE article TOPIC/PR approved at a time 👍. We can re-open this topic - once the 1st one has been merged/published.
