### ISSUE TITLE
How to Build a digital Clock with only HTML, CSS, and JavaScript

### ISSUE THREAD

**Issue by Frank-dev20** [section-engineering-education/engineering-education#3536]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### Proposed title of article
How to build a digital clock with only HTML, CSS, and JavaScript

### Introduction
The web made almost everything possible, and the emergence of JavaScript as the programming language of the web enables us to see our code live as they appear on the web and give us the ability to interact with web content. This article seeks to use this feature of the web to build a digital clock that runs on the web using web-based technologies such as HTML, CSS, and JavaScript.

### Key takeaways:

By the end of this article, readers should be able to
1. Know how to declare JavaScript function
2. Know how to use JavaScript setInterval method
3. Know how to use JavaScript Date class and its methods
4. Know how to use JavaScript ternary operator
5. Understand JavaScript function call
6. Create a project they can add to their portfolio

### References
N/A

**Comment by WanjaMIKE** [comment]
> @WanjaMIKE, the currently posted Section article is very light on detail and reads more of provided code snippets rather than explaining how the code works which this article proposes to do (as well as a slightly different tech stack). I think this would provide more value to readers though the topic idea itself isn't unique.

Okay @louisefindlay23

**Comment by WanjaMIKE** [comment]
@Frank-dev20 Topic approved. Let's ensure that it adds value to the community. Thanks

**Comment by Frank-dev20** [comment]
@WanjaMIKE  article submitted for review. I await your wonderful comment.
