### ISSUE TITLE
Getting started with graphics programming in Csharp

### ISSUE THREAD

**Issue by nicasious** [section-engineering-education/engineering-education#3537]
### Proposed title of article
Getting started with graphics programming in Csharp

### Introduction paragraph (2-3 paragraphs):
Graphics plays an important part in every application you develop. For instance, if you are developing a paint application or code-editor software, you will want to add color and font dialog box functionality. Sometimes, you may have to print text in the form areas of the software. There may be cases where you have to decorate your text or place it within a rectangle or inside a circle. You may want to simply insert a picture as the background. The possibilities are endless. This customizations are only possible with the careful and judicious use of the appropriate concepts. This article, which is the first of two parts, explains the concepts as laid out in the Microsoft .NET Framework using C# programming language.

This section shows how to get started using GDI+ in a Windows Forms application. The following topics show how to complete several GDI+ tasks such as drawing and filling shapes and text.

### Key takeaways: 
In this tutorial the reader will understand:
- how to change the unit of Measurement
- Working with ColorDialog Box
- Working with FontDialog Box
- how to use System.Drawing.Drawing2D Namespace
- Working with Pen objects
- Working with Brush objects
- Working with Images

### References: 
  N/A

**Comment by louisefindlay23** [comment]
Hi, @nicasious. Great topic suggestion. 

Can you tell me how your article will be unique from similar articles such as [this one](https://www.developer.com/microsoft/c-sharp/graphics-programming-using-c/)?

**Comment by nicasious** [comment]
Hello, @louisefindlay23 
I have looked at the  article you suggested and is significantly swallow. In my tutorial I will add more information on working with images ,working with brush object,  and working with pen object which are not in the article you have suggested me to look at .
I will write a unique  tutorial with  a better explanation.
Thank you.

**Comment by louisefindlay23** [comment]
Thanks, @nicasious for the explanation. Topic approved 🚀.
