### ISSUE TITLE
Introduction to Static Application Security Testing Method

### ISSUE THREAD

**Issue by RuthAMare** [section-engineering-education/engineering-education#3538]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Introduction to Static Application Security Testing Method

### Introduction paragraph (2-3 paragraphs):
This article will introduce a reader to application vulnerability testing, outlining the various ways of performing the same. The article will further focus on the static secutity testing method outlining how it works and its advantages.
This article will try to make a brief comparison between the static testing method and dynamic method and any other methods in existences.

### Key takeaways: 
The reader should master:
1. What is SAST
2. How SAST works
3. Advantages and Disadvantages SAST
4. Differences between SAST and DAST

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Great topic @RuthAMare - approved.

**Comment by Kayere** [comment]
Great topic @RuthAMare - approved.
