### ISSUE TITLE
Access specifiers in Java

### ISSUE THREAD

**Issue by Jerusa254** [section-engineering-education/engineering-education#3540]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
**Access specifier in Java**

### Introduction paragraph (2-3 paragraphs):
In java, members  and data members of a class/interface can have one of the different types of specifiers. the acess specifiers/modifiers are used to set the visibility of classes, interfaces and data members.
There are 3 types of access specifiers namely; private, public and protected.

### Key takeaways: 
1. What is an access specifier
2. Types of access modifiers and how they are implemented.

### References: 
N/A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Sounds like a great topic @Jerusa254 - approved.
Please make sure your article is unique and adds value to what is available in the official documentation.

**Comment by hectorkambow** [comment]
@Jerusa254 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by Jerusa254** [comment]
i am ready to go on with the topic

**Comment by Jerusa254** [comment]
Am ready to continue with  the topic..
Can you kindly make open so that I may get to work with it.
