### ISSUE TITLE
Abstractive Summarization using Deep Learning

### ISSUE THREAD

**Issue by smkinyan** [section-engineering-education/engineering-education#3542]
### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Abstractive Summarization using Deep Learning

### Introduction paragraph (2-3 paragraphs):

Text summarization aims at generating accurate and concise summaries from input documents. In contrast, abstractive summarization may generate novel words. A good abstractive summary covers principal information in the input and is linguistically fluent.

The [Pegasus](https://arxiv.org/pdf/1912.08777.pdf) model is built using a Transformer Encoder-Decoder architecture and is ridiculously powerful when it comes to summarizing big blocks of text. In Pegasus, important sentences are removed/masked from an input document and are generated together as one output sequence from the remaining sentences. This tutorial will walk you through how use the Pegasus model to perform abstract summarization from start to finish. We will perform abstractive summarization on some Wikipedia, News and Scientific Journals documents.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this article, a reader should be able to:

1. Install Dependencies for Transformers in Python
2. Import and Configure the Pegasus Model
3. Perform abstractive summarization on Wikipedia, News and Scientific Journals

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

- [PEGASUS: Pre-training with Extracted Gap-sentences for Abstractive Summarization](https://arxiv.org/pdf/1912.08777.pdf)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
I loved the topic! please @ me when we publish it. @smkinyan 🚀

Make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
