### ISSUE TITLE
Adding Google Maps API Using Flutter SDK

### ISSUE THREAD

**Issue by mumbi00** [section-engineering-education/engineering-education#3544]
### Proposed title of article
Adding Google Maps API Using Flutter SDK

### Introduction paragraph (2-3 paragraphs):
Flutter is Google's UI toolkit that helps developers build beautiful and native apps in a single codebase. Flutter’s Google Maps SDK enables developers to create native apps for iOS and Android. It gives native execution to the apps and lets them run their code one time. Since Google Maps give native execution to both Android and iOS, Flutter developers can easily implement their code in their respective apps.

The Google Maps Flutter plugin allows you to add Google maps data to your web application. It sends HTTP requests to the Google servers and displays the maps in response to the user's gestures.

### Key takeaways: 
•	How to create a new Flutter application.
•	How to configure a Google Maps Flutter plugin.
•	How to add Markers to a map, using location data from a web service.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
https://flutter.dev/
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
