### ISSUE TITLE
Getting Started With Linux Bash Scripting

### ISSUE THREAD

**Issue by Julius-1996** [section-engineering-education/engineering-education#3550]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting Started With Linux Bash Scripting

### Introduction paragraph (2-3 paragraphs):
Linux is a powerful open-source operating system. The Linux shell allows you by use of commands to interact with your computer and abstract away its intricate details such as retrieve or storing data, process information, and many more extremely complex tasks. Shell is a macro processor which allows for interactive command execution. With the power of Scripting, we can automate commands execution that would otherwise be executed interactively one by one.

In this tutorial, we will use Bourne again Shell (Bash) and cover:
- Case and switch statements
- Arrays and Dictionaries data structures
- Control flow using programming conditional statements such as if/else
- Writing loops, functions, and variables

### Key takeaways: 
1. Introduction to bash
2. Writing Scripts in bash
3. Major concepts and automating scripts using bash

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
There are multiple guides/tutorials covering this topic. How are you planning on making your article unique/original? @Julius-1996

**Comment by Julius-1996** [comment]
After going through the Linux Bash scripting, we will demonstrate with ideas like:
- send emails from shell scripts
- Adding batch extensions and Cronjobs
- Cleaning Log files
- System maintenance
- Bash socket Programming
- A comparison with compiled programs and many more
@ahmadmardeni1 @WanjaMIKE

**Comment by Julius-1996** [comment]
I'm going to build something interactive in the end. I hope that this gives depth in this article :rocket:

**Comment by Julius-1996** [comment]
Let's just close it if it violates any of what's needed. I'll be pushing my first PR when I make a new issue :rocket:
