### ISSUE TITLE
Building a multi-source video player with Reactjs

### ISSUE THREAD

**Issue by SamoraCletus** [section-engineering-education/engineering-education#3552]
# Building a multi-source video player with Reactjs
### Introduction:
Video playing capabilities is expected of modern websites such as blogs, social media, and educational websites. Building a video player with the ability to render video from multiple sources can be implemented with Reactjs. We will discuss in details the various steps and dependencies required to achieve the set goal.
### Key Takeaways:
This article is expected to equip the reader with the understanding and necessary skills to implement the following
i. Getting started with Reactjs
ii. Using React video components to view videos from multiple sources.
iii. Video dependencies in Reactjs
iv. Styling the video components using semantic UI
v. Error handling and testing

**Comment by ahmadmardeni1** [comment]
Great topic 🚀@SamoraCletus , make sure it matches the following: 
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by hectorkambow** [comment]
@SamoraCletus Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
