### ISSUE TITLE
How to Build a Weather App with Vanilla JavaScript

### ISSUE THREAD

**Issue by Nomzy-kush** [section-engineering-education/engineering-education#3553]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
How to Build a Weather App with Vanilla JavaScript
### Introduction paragraph (2-3 paragraphs):
In this article, I would take you through building a full weather application with HTML, CSS, Javascript, and the modern ES6 practices while also using the OpenWeatherMap API to get the correct weather for the different timezones in several countries around the world.  This is a must-do Javascript project. 

### Key takeaways: 
1. Readers will understand the different functions involved in building a full weather application without using any Javascript framework.
2. Readers will learn how to work with the OpenWeatherMap API which will deliver real-life weather data for different countries.
3. Readers will get an overall understanding of how to build real-life applications with just HTML, CSS, and JavaScript.  

### References: 
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Hi, @Nomzy-kush. Thanks for submitting your topic suggestion. Could you tell me how your proposed article would differ from similar vanilla JS weather app tutorials such as this [Tutsplus](https://webdesign.tutsplus.com/tutorials/build-a-simple-weather-app-with-vanilla-javascript--cms-33893) article?

**Comment by Nomzy-kush** [comment]
In this app, I am going to show the readers how to get real-life
weather data from the  OpenWeatherMap API. It is a great tutorial for
beginner JavaScript developers.

Thanks,
Onome

**Comment by ahmadmardeni1** [comment]
But that tutorial is also using the OpenWeather API @Nomzy-kush

**Comment by ahmadmardeni1** [comment]
But that tutorial is also using the OpenWeather API @Nomzy-kush
