### ISSUE TITLE
How password hashing occurs

### ISSUE THREAD

**Issue by Koros-Meshack** [section-engineering-education/engineering-education#3554]
**Introduction**
`Password hashing` is the process of converting a raw password into a series of characters using a hashing algorithm. This process of hashing can be referred to as `SHA-1(Secure Hashing Algorithm)`. It can be further modified to be more secure by adding random data into the series of characters through a process known as `salting`. This improves the security of the password by making it more complex for a third party to decode the password hash.

In this article, we will learn through processes that occur from when you input your password to how it is converted to a hash. We will further see how the password is decoded back to a raw format by the computer. With that, we will learn how to protect our password so as it is now easily decoded by unauthorized parties.

**Key Takeaways**
In this article, we will learn:
1. different types of encryption
2. different formats in password encryption such as SHA-1, MD5, AES, etc
3. Accessing your password hash in both Windows and Kali Linux OS.
4. Protecting your password from a brute-force attack and unauthorized personnel.

**Reference**
N/A

**Comment by Kayere** [comment]
Good topic @Koros-Meshack - approved. Please make sure your article is unique and adds value to what is available in official documentation.

**Comment by WanjaMIKE** [comment]
Closed #3554 via  #3718
