### ISSUE TITLE
Handling Web App authentication using Auth0, ASP.NET Core and Nuxt.js

### ISSUE THREAD

**Issue by ogoti-lilian** [section-engineering-education/engineering-education#3556]
### Proposed title of article
Handling Web App authentication using Auth0, ASP.NET Core and Nuxt.js

### Introduction paragraph:
Authenticating and authorizing users in a system can be difficult and time-consuming. If not done right it can also lead to serious security consequences such as malicious users accessing and stealing personal or sensitive information from the system.

Large organizations can implement complex authorization/authentication systems which tend to consume time and are expensive. However, businesses and developers can opt to go for cost-effective and minimize the development time by using existing solutions for secure authentication and authorization. In this tutorial, we will use Auth0 to authenticate the users into the system.

### Key takeaways: 
At the end of the guide, the learner will be able to:
- configure and use Auth0 to generate an access token for authentication
- configure ASP.NET Core to authenticate the request
- use Nuxt.js to implement the frontend of the app and handle routing

### References: 
N/A

**Comment by LinusMuema** [comment]
Hi @ogoti-lilian 
This seems like a great article and would be quite helpful. Please ensure your content does not conflict with articles already available on section. Also, check that it provides more original content than the one available on other websites and documentation. 

topic approved :rocket:

**Comment by ogoti-lilian** [comment]
> @ogoti-lilian
> Just wanted to follow up on this topic, as we will be clearing up the queue where possible.
> 
> Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

@hectorkambow Please reopen this topic, I was planning to upload it by today since it is ready. Thank you
cc @LinusMuema @WanjaMIKE

**Comment by WanjaMIKE** [comment]
Reopened @ogoti-lilian

**Comment by WanjaMIKE** [comment]
Is it Nuxt.js or Next.js?

**Comment by ogoti-lilian** [comment]
@WanjaMIKE Thank you, it is Nuxt.js
