### ISSUE TITLE
Java Program to Store Unicode Characters Using Character Literals

### ISSUE THREAD

**Issue by Dianapeter** [section-engineering-education/engineering-education#3558]
### Proposed title of article
Java Program to Store Unicode Characters Using Character Literals
### Introduction paragraph (2-3 paragraphs):
As the name suggests, literals are data elements with fixed or constant values. As a result, literals in Java are also referred to as constants. There are many different types of values that can be represented by literals. Strings are objects in Java. 
Java's virtual machine can only store a single String object in memory if we declare the same string in several string variables.
Unicode characters are a standard for encoding universal characters. It represents the many characters that can be represented in various documents such as text files and websites. The Unicode supports 4 bytes for the characters. The data type that can store char literals is char.

In this article, I shall take you as the reader to all of the literals in java step by step.
### Key takeaways: 
- Assigning ASCII values to char data types.
- Assigning Unicode values to char data types.
-  Assigning Unicode to the char data types.

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Could you take a look at this topic suggestion when you have the chance? Since you have expertise in Java, I thought you'd be the best person to reach. @BrianaNzivu

**Comment by BrianaNzivu** [comment]
Hey @ahmadmardeni1 👋🏾.
I think this is topic is widely covered by many blogs and also in the main documentation.
I don't think there is anything new to be added to it.

Hey @Dianapeter 👋🏾.
Do you think maybe you can enhance this article by maybe implementing something unique using literals? Can be a feature or even a function. 

Regards. 🚀

**Comment by Dianapeter** [comment]
I have done some enhancement @BrianaNzivu . Please have a look.

**Comment by BrianaNzivu** [comment]
This is now OK.
Looks like an interesting and unique read.

Regards🚀

Cc @ahmadmardeni1

**Comment by ahmadmardeni1** [comment]
Great, thank you! @BrianaNzivu

Great topic 🚀 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.  @Dianapeter

**Comment by WanjaMIKE** [comment]
Closed #3558 via #3808
