### ISSUE TITLE
Method Overriding and Overloading using Covariant Return Type in Java

### ISSUE THREAD

**Issue by MarkMoki** [section-engineering-education/engineering-education#3560]
### Proposed title of article
Method Overriding and Overloading using Covariant Return Type in Java
### Introduction paragraph (2-3 paragraphs):
By allowing you to return a subtype of the actual return type of the overridden method, covariant method overriding eliminates client-side type casting and eliminates the need for typecasting. Using covariant method overriding for overriding methods that return objects can be extremely helpful. By overriding the Covariant technique, you can return the subtype of the actual return class of the overridden method. As a result, the programmer is relieved of the burden of typecasting.

Using covariant return type, we can override a method in java, and this tutorial describes how to do that. You will learn how to use covariant return type and its advantages in this tutorial.
### Key takeaways: 
-Method overriding using covariant return type in Java.
-Covariant return type overriding rules.
-The reader will know how to override the Covariant approach.

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Could you take a look at this topic suggestion when you have the chance? Since you have expertise in Java, I thought you'd be the best person to reach. @BrianaNzivu

**Comment by BrianaNzivu** [comment]
Hey @ahmadmardeni1 👋🏾.
I think this is topic is widely covered by many blogs. 
I don't think there is anything new to be added to it.

Hey @MarkMoki 👋🏾.
Do you think maybe you can enhance this article by maybe implementing something unique using the overriding method? Can be a feature or even a function. 

Regards. 🚀

**Comment by MarkMoki** [comment]
@BrianaNzivu 
I have done some enhancement you may have a look please.

**Comment by BrianaNzivu** [comment]
Hey @MarkMoki 👋🏾.
I still think this is the same thing as what you had initially. 
Quick question  - can method overloading be also implemented using the covariant method?

If so, how about you write about both method overriding and overloading.

Regards 🚀

Cc @ahmadmardeni1

**Comment by MarkMoki** [comment]
@BrianaNzivu  sounds great too I can as well write both of them. Thank you.
I will implement a few enhancements on the topic.

**Comment by BrianaNzivu** [comment]
Great then I think if you write about both your article will be unique.
Please make it as detailed as possible.

@ahmadmardeni1 👋🏾 
The suggestion is now enhanced to a better article.

Regards🚀

**Comment by MarkMoki** [comment]
@BrianaNzivu THANKS

**Comment by ahmadmardeni1** [comment]
Great, thank you! @BrianaNzivu 

Great topic 🚀 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.  @MarkMoki
