### ISSUE TITLE
How to design the logistic map using matlab

### ISSUE THREAD

**Issue by simonmwaniki** [section-engineering-education/engineering-education#3562]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
One of the most challenging topics in science is the study of chaos. As an example of chaos, consider fluid flowing
round an object. If the velocity of the fluid is not very large the fluid flows in a smooth steady way, called "laminar
flow", which can be calculated for simple geometries. However, if the velocity is increased the flow becomes more
complicated, and depends on time and space in a non-trivial way which is essentially impossible to calculate. This
"turbulent" behavior is called "chaos".
The logistics map is a classic example of transition from stable to chaotic behavior as a single parameter changes value. This script plots the semi-stable values of x(n+1) = r*x(n)*(1-x(n)) as r is varied. Historically it has been one of the most important and paradigmatic systems during the early days of research on deterministic chaos. In this article, we will look on how to design logistic map in Matlab

### Key takeaways: 
- Proper understanding of the logistic map.
- Matlab code for logistic map.
- Applications of logistic map.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Great topic 🚀 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.  @simonmwaniki
