### ISSUE TITLE
Implementation of fuzzy logic in Matlab

### ISSUE THREAD

**Issue by collince777** [section-engineering-education/engineering-education#3563]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
Fuzzy logic is a way to model logic reasoning where the truth of the statement is not binary true or false but its is a degree of truth that ranges from zero to one. In this case, zero is referred to as absolutely false while one is the absolutely true. This fuzzy logic can be used to model the fuzzy inference system which is a function that maps the input to the set of output which uses the human-interpretable rules more than extract mathematics. These types of applications are mostly used in control systems applications in which the reference and the inputs are fed in and using the set of rules based on fuzzy logic, actuating signals are produced.
Generally, fuzzy Logic are not control systems but can be used in any set of applications that requires decisions. For example, it can be used in a banking system that decides the risk of lending a loan to a person based on the personal and financial information. In this article, we will look on how to apply this in Matlab using the fuzzy logic toolbox in Matlab

### Key takeaways: 
- Understanding the fuzzy logic.
- Implementing the fuzzy logic in Matlab.
- Applications of fuzzy logic.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Great topic 🚀@collince777 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
