### ISSUE TITLE
Object Serialization and Deserialization in Java

### ISSUE THREAD

**Issue by gracy20** [section-engineering-education/engineering-education#3565]
### Proposed title of article
Object Serialization and Deserialization in Java

### Introduction paragraph (2-3 paragraphs):
In this tutorial, I will shed light on the mechanism of serialization, and its benefits. It will also explore how to serialize an object, and how to serialize using different Java concepts, with examples.
Serialization in Java is the concept of representing an object’s state as a byte stream. The byte stream has all the information about the object. Usually used in Hibernate, JMS, JPA, and EJB, serialization in Java helps transport the code from one JVM to another and then de-serialize it there.
Deserialization is the exact opposite process of serialization where the byte data type stream is converted back to an object in the memory. The best part about these mechanisms is that both are JVM-independent, meaning you serialize on one JVM and de-serialize on another.

### Key takeaways: 
By the end of this tutorial, the reader will have understood:
- What is serialization
- How to serialize and deserialize an object.
- Serialization with Inheritance
- Serialization with Aggregation
- Serialization with Static Data Member
- What is the Transient Keyword

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @gracy20 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @gracy20 
This sounds like an interesting article and has a lot of content. Please ensure you provide more original content that doesn't conflict with the one already available in section. 

topic approved :rocket:
