### ISSUE TITLE
Understanding and implementing graphs in Java

### ISSUE THREAD

**Issue by terry254** [section-engineering-education/engineering-education#3569]
### Proposed title of the article
Understanding and implementing graphs in Java

### Introduction paragraph (2-3 paragraphs):
In Java, the Graph is a data structure that stores a certain of data. The concept of the graph represents a network that connects multiple points. In this tutorial, we will learn Java Graph data structure in detail. Also, we will learn the types of graphs, their implementation, and traversal over the graph as well as basic concepts of a graph as a data structure together with exploring its implementation in Java along with various operations possible on a graph.

### Key takeaways: 
By the end of this tutorial the reader will understand:
- What is a graph and the terminologies used
- Various types of graphs
-  Implementation using Java collections
- Methods to mutate the graph data structure
- Possible ways to traverse a graph

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @terry254 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @terry254 
Thanks for submitting the article. It sounds really informative and helpful. Please make sure you provide more original content that isn't available on other blog sites and official docs. Also, check that it doesn't conflict with the articles already published on section.

topic approved :rocket:

**Comment by hectorkambow** [comment]
@terry254 
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by terry254** [comment]
Hello. Can anyone reopen this for me? Thank you.
