### ISSUE TITLE
Authentication using GitHub in android

### ISSUE THREAD

**Issue by Emmah-Lashly** [section-engineering-education/engineering-education#3570]
### Proposed title of article
Authentication using GitHub in android

### Introduction 
Signing in with GitHub is a secure authentication system that reduces the burden of login for your users. This is because it enables users to sign in with their already existing GitHub account.
This is achieved by using Firebase's Authentication with GitHub as we will be discussing in this tutorial.

### Key takeaways: 
By the end of the article the reader will be able to:
- Understand what is Firebase.  
-  Understand What is Authentication.
-   Understand Authentication with Facebook.

### References: 
https://firebase.google.com/docs/auth/android/github-auth

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Emmah-Lashly 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @Emmah-Lashly 
This is an interesting article but I think it wouldn't really provide enough content for readers. 
For starters, a firebase auth [article](https://www.section.io/engineering-education/google-authentication-for-android/) has already been written by @BrianaNzivu. She has covered Google auth which is still similar to Github auth. They both use OAuth2 so it would be a repetition of a technology. 

First, check the articles on section before submitting another suggestion. It will save you time.
