### ISSUE TITLE
Custom Animations with Jetpack Compose in Android

### ISSUE THREAD

**Issue by Janenjoki** [section-engineering-education/engineering-education#3571]
### Proposed title of article

Custom Animations with Jetpack Compose in Android

### Introduction paragraph (2-3 paragraphs):

Jetpack Compose is a modern framework for creating native UI with composable functions on Android.
It makes Android UI development easier and faster.
With less code, powerful tools, and intuitive Kotlin APIs, you can quickly bring your project to life. Composable functions make it easier to reuse code.

In order to achieve a seamless and clear user experience in a modern mobile app, animations are required. Many Jetpack Compose Animation APIs are composable functions, similar to layouts and other UI elements, and are powered by powerful and extensible APIs.

### Key takeaways: 

By the end of this tutorial, the reader will be able to:
1. Understand what Jetpack Compose Animations are
2. Use default Animations provided by Compose APIs
3. Differentiate between high-level and low-level Animation APIs 
4. Implement custom Animations

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Janenjoki 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @Janenjoki 
This sounds like a really helpful article. I however think that a lot of the information you intend to cover has already been covered on the official docs. Please ensure you provide more original content so as to avoid the closing of articles in the future.

topic approved :rocket:

**Comment by WanjaMIKE** [comment]
To help avoid a backlog queue (and longer review times) we are currently only accepting ONE article TOPIC/PR approved at a time 👍. We can re-open this topic - once the 1st one has been merged/published.
