### ISSUE TITLE
Jar files in Java

### ISSUE THREAD

**Issue by jgesare** [section-engineering-education/engineering-education#3573]
### Proposed title of article
Jar files in Java

### Introduction paragraph (2-3 paragraphs):
A JAR (Java Archive) is a file format for aggregating several Java class files and associated information and resources (text, graphics, etc.) into a single file for distribution of Java platform application software or libraries.
A JAR file is a compressed version of.class files, audio files, image files, or directories, in simple terms. A.jar file can be thought of as a compressed file (.zip) produced with WinZip software. WinZip may also be used to extract the contents of a.jar file. You can use them for lossless data compression, archiving, decompression, and archive unpacking, among other things.
### Key takeaways:
1 Create a JAR file
2 View a JAR file
3 Extracting a JAR file
4 Updating a JAR File 
5 Running a JAR file
### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @jgesare 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Hello @jgesare, it seems your introduction borrows from this [article](https://www.google.com/amp/s/www.geeksforgeeks.org/jar-files-java/amp/). How is yours going to differ from it?

**Comment by WanjaMIKE** [comment]
Thank you for the topic suggestion @jgesare , however this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore.
