### ISSUE TITLE
Object Pool Design Pattern in Java

### ISSUE THREAD

**Issue by Edylene-Nyairaw** [section-engineering-education/engineering-education#3574]
### Proposed title of article
Object Pool Design Pattern in Java

### Introduction paragraph (2-3 paragraphs):

The Object Pool design in Java is based on the principle of recyclability in object generation. When creating objects is expensive, this pattern is most efficient, However it can cause memory concerns if several objects are created. It aids in the enhancement of the application's functionality.
In this tutorial, the reader will understand the concept of Object Pool design in java and how to use it.

### Key takeaways: 
By the end of this tutorial, the reader will be able to understand the following concepts;

- Overview of object pool pattern.
- Working principle of object pool pattern.
- Queue class.
- Stack class.
- Implementation of object pool design.
- When to use object pool pattern and the advantages of using object pool design.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Edylene-Nyairaw 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Check the topic suggestion below this one #3573 . They appear to be similar.

**Comment by Edylene-Nyairaw** [comment]
Hi, @WanjaMIKE 
I checked the topic and decided to change to a new one from Multi-Release Jar files to Object Pool Design Pattern in Java.
Waiting for your approval feedback.
Thank you.

**Comment by hectorkambow** [comment]
Good afternoon___ and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout [other blog sites](https://www.google.com/search?q=Object+Pool+Design+Pattern+in+Java&rlz=1C1CHBF_enUS891US891&oq=Object+Pool+Design+Pattern+in+Java&aqs=chrome..69i57j69i59i450l8.173j0j15&sourceid=chrome&ie=UTF-8) and official documentations. 

How do we plan to make this articles a unique piece of content as more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

cc @WanjaMIKE - please correct me if I'm mistaken - as Im not too familiar with this topic in general.

**Comment by WanjaMIKE** [comment]
You are right @hectorkambow. Feel free to suggest another topic @Edylene-Nyairaw
