### ISSUE TITLE
How to build a web contact form using Form Spree

### ISSUE THREAD

**Issue by 1-creator** [section-engineering-education/engineering-education#3575]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
The easy way to build contact form in your website  using formspree

### Introduction paragraph (2-3 paragraphs):
To build a contact form in a website you may need to build both backend and fronted part of it .Either using PHP ,Javascript or any language you prefer for backend .But  in formspree you will only need to work on frontend part of the contact form.
Well, what is the easy way to do it?
 With form spree you don't need to  write lots of code.Formspree handles the server side for you.
What is form spree?
Formspree is a form backend, API, and email service for HTML & JavaScript forms. It's the simplest way to embed custom contact us forms, order forms,or email capture forms. Formspree is a tool in the Web Forms category of a tech stack.

### Key takeaways: 
-Uderstand  how to build fully functioning javascript contact form
-Uderstand how to build simple html forms
-Uderstand how to build easy popup forms
-uderstand how to build powerful Javascript forms
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
https://formspree.io/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @1-creator 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
This is already covered in their docs. Can you tell me how are you planning on making your article unique/original? @1-creator

**Comment by 1-creator** [comment]
I was planning to write a tutorial using my own code. And add more
information that I have been researching on.

Regards Valentine.

**Comment by ahmadmardeni1** [comment]
What is the information? Share it with me, please. @1-creator

**Comment by 1-creator** [comment]
-dealing with errors in formspree
-building forms using css,html and javascript

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @1-creator
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
