### ISSUE TITLE
Authentication using Google Sign-in on android

### ISSUE THREAD

**Issue by lokalawashington** [section-engineering-education/engineering-education#3578]
### Introduction paragraph (2-3 paragraphs):
Sign In With Google is a secure authentication system that reduces the burden of login for your users. You can let your users authenticate with Firebase using their Google Accounts by integrating Google Sign-In into your app.
 

### Key takeaways: 
-What is google sign in
-Features of google sign in
-Implementation of google sign in on android

### References: 
-https://firebase.google.com/docs/auth/android/google-signin

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @lokalawashington 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @lokalawashington 
Sorry but this article has already been covered by @BrianaNzivu in [this article](https://www.section.io/engineering-education/google-authentication-for-android/). Please check existing content before submitting article suggestions.
