### ISSUE TITLE
Functional programming with Java Lambda

### ISSUE THREAD

**Issue by popsoft01** [section-engineering-education/engineering-education#3583]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials promptly. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an article to be reviewed and/or published.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
Functional programming with Java Lambda

### Introduction paragraph (2-3 paragraphs):

Java has been an Object-Oriented-programming language which recommends encapsulation of all variable and method of the class, which mean all code block is “associated” with class and object, before java 8 the process of passing a behaviour to method takes extra work and load because we are passing a class with another attribute. 

In java 8 Lambda was introduced to represent the Functional interface of java, which mean lambdas expression is basically the expression of functional interface. The introduction of Lambda was to implement behavioural code to be easier by letting you create a function that performs a specific task that does not belong to a class and be treated as a value

At the end of the article, the reader will be able to understand java functional programming, assigning lambdas to an interface, working with lambda expression with different number of parameters, The reader will also be able to convert object or class method to lambdas function with less code, The reader will also understand the importance of using function programming

Prerequisites
The reader should have:
At least a basic knowledge of Java.
Have Java installed on your computer
Have any IDE of your choice.
Understanding class and static methods will also be of great help.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.
At the end of the article, 

- The reader will be able to understand java functional programming

- The reader will also be able to convert object or class method to lambdas function with less code

- The reader will be able to work with lambda expression with different number of parameters

- The reader will also under the importance of using function programming

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
Java - How to Program 10th Ed - Early Objects Version  by Pual Deitel and Harvey Deitel
Introduction to Java Programming, Comprehensive Version by Y. Daniel Liang of Armstrong Atlantic State University
https://www.w3schools.com/java/java_lambda.asp
https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @popsoft01 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Could you take a look at this topic suggestion when you have the chance? Since you have expertise in Java, I thought you'd be the best person to reach. @BrianaNzivu

**Comment by BrianaNzivu** [comment]
Hey @ahmadmardeni1 👋🏾.
Seems like a good interesting topic. Also very key considering Android studio uses Java Lambda nowadays when it comes to Android development using Java.

Hey @popsoft01 👋🏾.
This is a good suggestion but please make the article more detailed and even better than the reference articles you have linked since they are not as detailed.
Give us a proper solid background, pros and cons and then a tutorial of various features in Java lambda.

Regards 🚀

**Comment by popsoft01** [comment]
I will review and rewrite my introduction to capture all the details mention by @BrianaNzivu and more details of the lambda will also be discussed in the  tutorial

**Comment by Kayere** [comment]
Thank you @BrianaNzivu 🚀.
@popsoft01 - topic approved.
