### ISSUE TITLE
A Complete guide to Laravel Toastr package With Example Tutorial

### ISSUE THREAD

**Issue by vincentoriyo** [section-engineering-education/engineering-education#3584]
### Proposed title of article
A Complete guide to Laravel Toastr package With Example

### Introduction paragraph (2-3 paragraphs):
Toastr is awesome JavaScript library that help to display message in the form of notification, the message could be type of info, success, warning or error . When a user signs up on your website or performs an action that needs a notification. A good option is to use the ToastrJS library. 

In this tutorial i will show you how to use toast message in laravel 8. Toastr is awesome plugin to show awesome messages to user. So let's start how to add toastr js in Laravel application.

### Key takeaways: 
Getting started with Toastr notification package
- Configuring Toastr package in a Laravel applicaiton
- Creating Success and Error Toasts
- Accessing Toasts Everywhere
- Toast Stacking Implementation

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @vincentoriyo 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@vincentoriyo 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites. (beyond a basic explanation - it would be best to reference your favorite intro article and build upon it).
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@vincentoriyo Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by WanjaMIKE** [comment]
Closed #3584 via #4542
