### ISSUE TITLE
 Adding custom methods for LINQ queries (C#)

### ISSUE THREAD

**Issue by Joshuathuo** [section-engineering-education/engineering-education#3591]
### Proposed title of article
Adding custom methods for LINQ queries (C#)

### Introduction paragraph (2-3 paragraphs):
By introducing extension methods to the IEnumerableT> interface, you may expand the set of methods available for LINQ queries. You may, for example, develop a custom aggregate method to compute a single value from a sequence of data in addition to the usual average and maximum procedures. You can also build a method that returns a new series of values and acts as a custom filter or a specialized data transform for a sequence of variables. Distinct, Skip, and Reverse are examples of such techniques.

You may apply your own methods to any enumerable collection when you extend the IEnumerableT> interface.  In this article, we shall deeply take a look at various custom methods that are used in LINQ queries in C#.

### Key takeaways: 
1. Adding a method that returns a sequence
2. Overloading an Aggregate Method to Accept Various Types
3. Adding an aggregate method

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Joshuathuo 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Joshuathuo 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites. (beyond a basic explanation - it would be best to reference your favorite intro article and build upon it).
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
