### ISSUE TITLE
Class Data Sharing in Java with Examples

### ISSUE THREAD

**Issue by Wangui80** [section-engineering-education/engineering-education#3595]
### Proposed title of the article
Class Data Sharing in Java with Examples

### Introduction paragraph (2-3 paragraphs):
The Class data sharing (CDS) feature helps reduce the startup time and memory footprint between multiple Java Virtual Machines (JVM).
When you use the installer to install the Oracle Java Runtime Environment (JRE), the installer loads a default set of classes from the system Java Archive (JAR) file into a private internal representation, and dumps that representation to a file called a shared archive. If the JRE installer is not being used, then you can generate the shared archive manually.
When the JVM starts, the shared archive is memory-mapped to allow sharing of read-only JVM metadata for these classes among multiple JVM processes. Because accessing the shared archive is faster than loading the classes, startup time is reduced.

### Key takeaways: 
By the end of this tutorial, the learner will understand:
- What is data class sharing?
-  Application Class Data Sharing in Java Platform
- Process of Application Class Data Sharing
-  How to regenerate the shared archive for all supported platforms
- How to manually Control Class Data Sharing

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Wangui80
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @Wangui80 
This sounds like an interesting read and I would like to see the output. Please ensure your article provides more original content and that it does not conflict with content already published on section.

topic approved :rocket:

**Comment by Wangui80** [comment]
Hello, @hectorkambow @LinusMuema can you please reopen this for me. Thank you

**Comment by Wangui80** [comment]
Can anyone reopen this for me.

**Comment by WanjaMIKE** [comment]
Closed #3595 via 4757
