### ISSUE TITLE
Implementing multiple ViewHolder classes in Android using Kotlin

### ISSUE THREAD

**Issue by MaurineM** [section-engineering-education/engineering-education#3602]
### Proposed title of article
Implementing multiple ViewHolder classes in Android using Kotlin

### Introduction paragraph (2-3 paragraphs):
In the imperative programming paradigm in Android, a RecyclerView is a widget used to display numerous items. Normally, developers use a single type of item to populate data in the RecyclerView. Have you ever asked yourself how you can employ different types of data items in the same RecyclerView while maintaining a seamless experience?

This is where multiple ViewHolders come in. They allow us to pass different data objects during the RecyclerView callbacks. This way we can create more interactive and scalable applications.

### Key takeaways: 

By the end of this tutorial, the reader will be able to:
1. Understand why we need more than one ViewHolder class.
2. Implement two-typed ViewHolders.
3. Manage ViewHolder states and interactions.
4. Easily debug callback errors.

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @MaurineM
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Sounds like a great topic @MaurineM - approved. Please make sure your content is unique and adds value to what is available in the official documentation.
