### ISSUE TITLE
MySQL C# connector in windows form.

### ISSUE THREAD

**Issue by MICHELLENGEI** [section-engineering-education/engineering-education#3603]
### Proposed title of article
 MySQL C# connector in windows form.

### Introduction paragraph (2-3 paragraphs):
Windows forms is a user interface framework for creating Windows desktop applications. Based on the Visual Studio visual designer, it provides one of the most productive ways to create desktop apps .It is critical to save data collected from windows forms while constructing them. Using Xampp and MySQL C# connector It is possible to transfer information collected from the windows form to phpmyadmin.
Apache Friends developed XAMPP, a free and open source cross-platform web server solution stack bundle that includes the Apache HTTP Server, MariaDB database, and interpreters for PHP scripts. With the integrated phpmyadmin module, Xampp makes it simple to setup and maintain databases. The MySQL C# connector allows you to run phpmyadmin queries from your Windows form.

### Key takeaways: 
-Reader should be able to download and install MySQL C# connector.
-Reader should be able to add MySQL C# connector to a windows form project.
-Reader should be have good understanding of the MySQL connection string for C#.
-Reader should be able to create a connection between a form and a MySQL database.

### References: 
N/A.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @MICHELLENGEI 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Good afternoon @MICHELLENGEI and thank you for submitting your topic to the EngEd program.

After some careful consideration it struck us that this topic may be a bit over saturated (or well covered) throughout [other blog sites](https://www.google.com/search?q=MySQL+C%23+connector+in+windows+form&rlz=1C1CHBF_enUS891US891&ei=3fQ3Yc79B4OuqtsPhO-IsAE&oq=MySQL+C%23+connector+in+windows+form&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeMggIIRAWEB0QHjIICCEQFhAdEB46BwgAEEcQsANKBQg6EgEySgQIQRgAUNrACljawApgscIKaAJwAngAgAFxiAFxkgEDMC4xmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwiO4Mygge7yAhUDl2oFHYQ3AhYQ4dUDCA4&uact=5) and official documentations. 

How do we plan to make this articles a unique piece of content as more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

cc @ahmadmardeni1 - please correct me if I'm mistaken - as Im not too familiar with this topic in general.
