### ISSUE TITLE
Race conditions in JavaScript

### ISSUE THREAD

**Issue by vinmugambi** [section-engineering-education/engineering-education#3605]
A software system is in a race condition when its overall behaviour varies depending on the order and time of execution of uncontrollable events. Such software might produce unexpected results or behave in an unintended manner hurting user experiences and in some cases causing critical damage.

In this article, we'll explore race conditions, what causes them and how to avoid them when writing applications in JavaScript.

**Key takeaways**

At the end of the article, the reader will:

- understand race conditions
- identify JavaScript code that might result in a race condition
- resolve identified race conditions
- Write code that avoids race conditions

**References**

- [https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/async %26 performance/ch1.md](https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/async%20%26%20performance/ch1.md)
- [https://buttondown.email/stately/archive/race-conditions-are-human-issues/](https://buttondown.email/stately/archive/race-conditions-are-human-issues/)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @vinmugambi 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
