### ISSUE TITLE
 Star Rating Script using PHP and MySQL with Ajax

### ISSUE THREAD

**Issue by Wakanyaben254** [section-engineering-education/engineering-education#3606]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article

Star Rating Script using PHP and MySQL with Ajax
### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 
star rating enables you to know your readers or customers thought concerning  your website content.
this feature enables you to collect customers opinion and is used across different domains in a variety of ways.
it helps you know how people rank your content and also brings more reader to your page by the gained rating.
diffrent types of users visits a website and the scope is wide, through star rating other users visiting the website
are able to rate the content and get review concerning the website content.

this feature loads the rating element based on the PHP constant defined in a common configuration file.
the rating element will show clickable 5 stars icons,on clicking the rating element it invokes a
jquery script to send AJAX requests to save ratings.
The UI displays 5 stars with rating value ranges from 1-5. 
in this tutorial will be using PHP,jquery functions to handle user rating action and and storing user rating to MYSQL database from PHP.
### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.
1.why a website needs star rating. 
2.ways of implementing a dynamic star rating. 
3.advantages of creating a custom star rating script. 
4.jquery star rating example script. 
5.UI design to render star rating option 
6.jquery functions to handle user rating action
7.storing user rating to MYSQL database from PHP
8.rating database script. 
9.output screenshot of star Rating example. 
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Wakanyaben254 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Wakanyaben254 
Good afternoon and thank you for submitting your topic to the EngEd program.

After some careful consideration it struck us that this topic may be a bit over saturated throughout [other blog sites and official documentations.](https://www.google.com/search?q=Star+Rating+Script+using+PHP+and+MySQL+with+Ajax&rlz=1C1CHBF_enUS891US891&ei=KvY3Yei2HI-pqtsP_NyYoAk&oq=Star+Rating+Script+using+PHP+and+MySQL+with+Ajax&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABOgcIABBHELADSgUIOhIBMkoECEEYAFDakgdY2pIHYOeUB2gCcAJ4AIABtgGIAbYBkgEDMC4xmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwjo88W_gu7yAhWPlGoFHXwuBpQQ4dUDCA4&uact=5)

How do we plan to make this articles a unique piece of content as more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

cc @ahmadmardeni1 - please correct me if I'm mistaken - as Im not too familiar with this topic in general.

**Comment by Wakanyaben254** [comment]
My article will be much simple but rich in content which will enhance readers understanding furthermore my code snippets will be clear, easy to read and internalize

**Comment by ahmadmardeni1** [comment]
Correct, this topic is already covered by other blog sites. He needs to build a unique project. @hectorkambow

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Wakanyaben254 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
