### ISSUE TITLE
Getting Started with Recursion using Java

### ISSUE THREAD

**Issue by olu-damilare** [section-engineering-education/engineering-education#3610]
### Introduction paragraph (2-3 paragraphs):
Recursion is a very useful programming approach for solving complex algorithms, whereby a method reduces its initial input by a certain value and repeatedly calls itself until a base case is reached. Each resulting output is then returned up the hierarchy of the method call stack.

In this article, we will be introduced to the concept of recursion in Java. We'll understand the basic structure of a recursion method, compare and contrast the recursion method approach to an iterative approach such as loops, method call stack, the recursion depth, Java's `RecursiveTask<V>` API and we'll also demonstrate how to solve a number of challenges using recursion.

### Key takeaways:
At the end of the article, the reader should be able to:

 * Identify the best use cases of recursion in solving a problem.
 * Determine how the base case for a recursion method should be  
 * Have a thorough understanding of the Java `RecursiveTask` API
 * Have an understanding of the advantages of using recursion over iterations
 * Interprete method call stack

References:
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/RecursiveTask.html
https://developer.mozilla.org/en-US/docs/Glossary/Recursion
https://www.w3schools.com/java/java_recursion.asp
https://deitel.com/java-how-to-program-11-e-early-objects-version/

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @olu-damilare 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@olu-damilare 
Good afternoon and thank you for submitting your topic to the EngEd program.

After some careful consideration it struck us that this topic may be a bit over saturated throughout [other blog sites and official documentations.](https://www.google.com/search?q=Recursion+using+Java&rlz=1C1CHBF_enUS891US891&ei=oPY3Ye2AJ9SlqtsP56-ioAQ&oq=Recursion+using+Java&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCABDIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BwgAEEcQsANKBQg6EgEySgQIQRgAUOLZBVji2QVgr9sFaAJwAngAgAFtiAFtkgEDMC4xmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwjt0PL3gu7yAhXUkmoFHeeXCEQQ4dUDCA4&uact=5)

How do we plan to make this articles a unique piece of content as more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

cc @WanjaMIKE - please correct me if I'm mistaken - as Im not too familiar with this topic in general.

**Comment by WanjaMIKE** [comment]
You right @hectorkambow Feel free to suggest another topic @olu-damilare
