### ISSUE TITLE
BigDecimal and Primitive Data Type Arithmetic Program in Java

### ISSUE THREAD

**Issue by NdoloBonface** [section-engineering-education/engineering-education#3611]
### Proposed title of article
BigDecimal and Primitive Data Type Arithmetic Program in Java
### Introduction paragraph (2-3 paragraphs):
As a result, floating-point data formats cannot be employed in financial calculations due to their inaccuracy. This is the reason why Java provides a separate class called "BigDecimal" for performing operations and minimizing the likelihood of errors in calculations. The BigDecimal class offers arithmetic, scale management, rounding, comparison, format conversion, and hashing operations on double numbers. However, it compensates for the time complexity by handling very big and very small floating-point integers with remarkable precision.
These basic arithmetic operations can be done on BigDecimal and between BigDecimal and primitive data types and this is what we will be discussing in our article.
### Key takeaways: 
-Arithmetic operations that can be performed on BigDecimals.
-Using performed arithmetic operations between BigDecimals and primitive data types.
-Reasons for using the separate class BigDecimal.
### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @NdoloBonface 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites. (beyond a basic explanation - it would be best to reference your favorite intro article and build upon it).
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
@NdoloBonface
