### ISSUE TITLE
Understanding blockchain as a service

### ISSUE THREAD

**Issue by crezyj** [section-engineering-education/engineering-education#3612]
### Proposed title of article
Understanding blockchain as a service (Baas)*

### Introduction paragraph (2-3 paragraphs):
BaaS –Blockchain-as-a-service (BaaS) is the third-party creation and management of cloud-based networks for companies in the business of building blockchain applications. BaaS is based on the software as a service (SaaS) model and allows customers to leverage cloud-based solutions to build, host, and operate their own blockchain apps and related functions on the blockchain. BaaS help the customers in a faster application development, low maintenance cost and fast adoption of Blockchain technologies.

### Key takeaways: 

- understanding deeper concepts of blockchain
- how to offer blockchain as a service.
- implementation of blockchain as a service

### References: 
-https://www.trustradius.com/blockchain-as-a-service-baas

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @crezyj 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@crezyj 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites. (beyond a basic explanation - it would be best to reference your favorite intro article and build upon it).
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by crezyj** [comment]
Thanks I am working on  the topic almost done.
