### ISSUE TITLE
Intelligent Smart Contracts for Innovative Supply Chain Management

### ISSUE THREAD

**Issue by crezyj** [section-engineering-education/engineering-education#3614]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Intelligent Smart Contracts for Innovative Supply Chain Management

### Introduction paragraph (2-3 paragraphs):
I propose blockchains and smart contracts as enabling technologies for an innovative type of supply chain management, with the goal of achieving higher levels of collaboration between the companies participating in the chain, which in turn pays in the form of higher levels of profitability and economic health for the participating enterprises. Our proposal goes far beyond simply using blockchains as decentralized systems to track the origin and delivery of goods, which is what most of the current blockchain projects on supply chains are focused on. In fact, we introduce a type of smart contract aimed to solve two of the main problems that hinder the efficiency and effectiveness of supply chains, namely trust and coordination. Solving the problem of trust amounts to the capability of establishing quickly and cheaply contractual relationships based on convergent business needs among parties that may not know each other, and therefore need to protect themselves from opportunistic or incorrect behavior. Solving the problem of coordination consists in creating, at convenient management costs, a control system capable of directing the objectives of the supply chain as a whole, so as to achieve a greater common good in the medium term, as an alternative to the state of affairs in which each participant pursues, on its own behalf, lower but immediate returns.

 Our smart contracts for innovative supply chain management replace human coordinators in tackling the problems above, thus eliminating one major obstacle to their effective solution, namely the need to trust the coordinator itself. Furthermore, in this way, by automating the process of coordination, they unburden the supply chain of a considerable management cost. Contracts of this kind not only automate contract execution as in standard smart contracts, but also adjust costs and compensations of the members of a supply chain, effectively taking up the role that was of human coordinators. Thus, we refer to them as “intelligent smart contracts.” In the course of the paper, we will illustrate an innovative supply chain architecture based on intelligent smart contracts running on blockchain, we will detail the algorithmic methodologies underlying the decision-making process of these contracts and we will outline the wider socio-economic perspectives opened by our approach.

### Key takeaways: 
-What is an intelligent smart contract 
-Uses of intelligent smart contract
-coding a intelligent smart contract
-Trends with intelligent smart contract 

### References: 
-https://www.frontiersin.org/articles/10.3389/fbloc.2020.535787/full
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @crezyj 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
To help avoid a backlog queue (and longer review times) we are currently only accepting ONE article TOPIC/PR approved at a time 👍. We can re-open this topic - once the 1st one has been merged/published.
