### ISSUE TITLE
Role of Blockchains in Multi-Stakeholder Transactive Energy Systems

### ISSUE THREAD

**Issue by joni-kano** [section-engineering-education/engineering-education#3615]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
The Role of Blockchains in Multi-Stakeholder Transactive Energy Systems

### Introduction paragraph (2-3 paragraphs)
Power grids are undergoing major changes due to rapid growth in renewable energy and improvements in battery technology. Prompted by the increasing complexity of power systems, decentralized solutions are emerging that arrange local communities into transactive microgrids. This paper addresses the problem of implementing transactive energy mechanisms in a distributed setting, providing both privacy and safety. Specifically, we design and implement an automated auction and matching system that ensures safety (e.g., satisfaction of line capacity constraints), preserves privacy, and promotes local trade and market efficiency for transactive energy systems. This design problem is challenging because safety, market efficiency, and privacy are competing objectives. We implement our solution as a decentralized trading platform built on blockchain technology and smart contracts. To demonstrate the viability of our platform, we analyze the results of experiments with dozens of embedded devices and energy production and consumption profiles using an actual dataset from the transactive energy domain.

### Key takeaways: 
-understand Role of Blockchains in Multi-Stakeholder Transactive Energy Systems
-show effects of Role of Blockchains in Multi-Stakeholder Transactive Energy Systems
### References: 
-https://www.frontiersin.org/articles/10.3389/fbloc.2020.593471/full#h5

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @joni-kano 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
To help avoid a backlog queue (and longer review times) we are currently only accepting ONE article TOPIC/PR approved at a time 👍. We can re-open this topic - once the 1st one has been merged/published.
