### ISSUE TITLE
Race conditions in JavaScript

### ISSUE THREAD

**Issue by vinmugambi** [section-engineering-education/engineering-education#3618]
A software system is in a race condition when its overall behaviour varies depending on the order and time of execution of uncontrollable events. Such software might produce unexpected results or behave in an unintended manner hurting user experiences and in some cases causing critical damage.

In this article, we'll explore race conditions, what causes them and how to avoid them when writing applications in JavaScript.

**Key takeaways**
At the end of the article, the reader will:

- understand race conditions
- identify JavaScript code that might result in a race condition
- resolve identified race conditions
- write code that avoids race conditions

References
- https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/async %26 performance/ch1.md
-  https://buttondown.email/stately/archive/race-conditions-are-human-issues/

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @vinmugambi 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites. (beyond a basic explanation - it would be best to reference your favorite intro article and build upon it).
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

@vinmugambi

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 can be reopened once the first PR is merged.
