### ISSUE TITLE
Understanding the map data type in Dart

### ISSUE THREAD

**Issue by OMONDIELLY** [section-engineering-education/engineering-education#3626]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Understanding the map data type in Dart.

### Introduction paragraph (2-3 paragraphs):
It is agreeable that mastering a language requires a good understanding of its data types/ data structures, how they are implemented and how to manipulate them. In any case you'd want to cement your understanding of Dart fundamentals, then this article is for you.
In this article, we will learn about the map data type, its syntax and features. In the end, we'll see how to manipulate elements in maps and how to output map data.
 
 
### Key takeaways: 
1  An introduction to Dart and its data types/data structures.
2.  What are maps?
3.  The map syntax and declaration.
4. Features of a map.
5. How to manipulate map elements.
6. Conclusion.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @OMONDIELLY 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites. (beyond a basic explanation - it would be best to reference your favorite intro article and build upon it).
Please be sure to double check that it does not overlap with any existing EngEd articles, [articles on other blog sites](https://www.google.com/search?q=the+map+data+type+in+Dart&rlz=1C1CHBF_enUS891US891&ei=oPk3Ycj_JvezqtsP4oWr0As&oq=the+map+data+type+in+Dart&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGABQ6FdYxl9g42JoAHACeACAAbcBiAGNApIBAzEuMZgBAKABAcABAQ&sclient=gws-wiz&ved=0ahUKEwjIz43mhe7yAhX3mWoFHeLCCroQ4dUDCA4&uact=5), or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

cc @WanjaMIKE

**Comment by OMONDIELLY** [comment]
> I'm going to close this topic to clear the queue. It can be reopened.

Hello @ahmadmardeni1, kindly reopen for me this issue , I have the article ready for PR.

**Comment by LinusMuema** [comment]
Hi @OMONDIELLY 
You can continue working on the article.

**Comment by OMONDIELLY** [comment]
> Hi @OMONDIELLY You can continue working on the article.

Sure, thanks
