### ISSUE TITLE
Understanding Collection in Java

### ISSUE THREAD

**Issue by david-muchiri** [section-engineering-education/engineering-education#3627]
### Proposed title of article
Understanding Collection in Java

### Introduction paragraph (2-3 paragraphs):
The Collection in Java is a framework that provides an architecture to store and manipulate the group of objects. Java Collections can achieve all the operations that you perform on a data such as searching, sorting, insertion, manipulation, and deletion. Java Collection means a single unit of objects.

 In Java, a separate framework named the `Collection Framework` has been defined in JDK 1.2 which holds all the collection classes and interface in it. The Collection interface (java.util.Collection) and Map interface (java.util.Map) are the two main `root` interfaces of Java collection classes.

### Key takeaways: 
By the end of this tutorial the reader will have understood:
1. What framework in Java is.
2. Hierarchy of the Collection Framework.
3. Java Collections API Interfaces
-  Collection interface.
- Iterator Interface
- Set Interface
- List Interface
- Queue Interface
- Dequeue Interface
- Map interface
4. Java Collections Classes

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @david-muchiri 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Good afternoon @david-muchiri and thank you for submitting your topic to the EngEd program.

After some careful consideration it struck us that this topic may be a bit over saturated throughout [other blog sites and official documentations.](https://www.google.com/search?q=Collection+in+Java&rlz=1C1CHBF_enUS891US891&ei=r_k3YZ8du6iq2w-YsoqACA&oq=Collection+in+Java&gs_lcp=Cgdnd3Mtd2l6EAMyCAgAEIAEELEDMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgcIABBHELADSgUIOhIBMkoECEEYAFD1xQRY9cUEYKLHBGgCcAJ4AIABcogBcpIBAzAuMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwjfsPrshe7yAhU7lGoFHRiZAoAQ4dUDCA4&uact=5)

How do we plan to make this articles a unique piece of content as more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

cc @WanjaMIKE - please correct me if I'm mistaken - as Im not too familiar with this topic in general.

**Comment by WanjaMIKE** [comment]
You right @hectorkambow. Feel free to suggest another topic. Thanks
