### ISSUE TITLE
Importing External Files using Webpack Loaders

### ISSUE THREAD

**Issue by greatnessss** [section-engineering-education/engineering-education#3629]
### Introduction paragraph 
Using Webpack for the first time can be quite demanding. You may have external files, that you need to import and may find it difficult to import these files using webpack. 

In this tutorial, I will be giving a detailed step-by-step approach to import various files using webpack loaders. 

### Key takeaways: 
By the end of this tutorial readers should be able to:
1. Install Webpack
2. Learn how to interact with Webpack using CLI
3. Make use of Webpack loaders to import various types of files. 

### References: 
The best reference is the official [Webpack Documentation] (https://webpack.js.org/concepts/)

### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @greatnessss 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
