### ISSUE TITLE
 Intent Classification with Rasa and Spacy

### ISSUE THREAD

**Issue by kelvinkimani501** [section-engineering-education/engineering-education#3632]
### Proposed title of article
 Intent Classification with Rasa and Spacy

### Introduction paragraph (2-3 paragraphs):
Intent classification is the automated categorization of text data based on customer goals. Intent classification uses machine learning and natural language processing to automatically associate words or expressions with a particular intent. For example, a machine learning model can learn that words such as buy or acquire are often associated with the Intent to Purchase.
Intent recognition forms an essential component of chatbots and finds use in sales conversions, customer support. This has been applied in many chatbot systems to engage customers thus knowing the needs of customers. Within a chatbot, intent refers to the goal the customer has in mind when typing in a question or comment.
In this tutorial, we shall use Rasa and Spacy in building our model. 
Rasa is a tool to build custom AI chatbots using Python and natural language understanding (NLU). Rasa provides a framework for developing AI chatbots that uses natural language understanding (NLU). It also allows the user to train the model and add custom actions

### Key takeaways: 
1. What is Intent Classification.
2. Difference between NLU and NLP.
3. Installing Rasa and Spacy.
4. Building our customer-specific model.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @kelvinkimani501 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @kelvinkimani501

**Comment by WanjaMIKE** [comment]
Closed #3632 via #3790
