### ISSUE TITLE
KEY DIFFERENCES BETWEEN JAVASCRIPT AND CSS

### ISSUE THREAD

**Issue by Gacheru-sudo** [section-engineering-education/engineering-education#3638]
### Proposed title of article
KEY DIFFERENCES BETWEEN JAVASCRIPT AND CSS

### Introduction paragraph (2-3 paragraphs):
in this tutorial, you will get a brief introduction in Javascript and CSS
       Both javascript and CSS are used in web pages but for different roles.
we will look deeper into the main key differences between the two basing our argument on websites and users.

### Key takeaways: 
1.what is javascript and its benefits
2.what is CSS and its benefits
3.key differences that spilt javascript and CSS apart

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Gacheru-sudo 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Thank you for the topic suggestion @Gacheru-sudo , however this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore.
