### ISSUE TITLE
Cross-site Request Forgery (Anti-CSRF) Protection in PHP

### ISSUE THREAD

**Issue by EssyG10** [section-engineering-education/engineering-education#3640]
### Proposed title of the article
Cross-site Request Forgery (Anti-CSRF) Protection in PHP

### Introduction paragraph (2-3 paragraphs):
The Cross-Site Request Forgery (CSRF) attack is a common security breach that occurs on the internet. Protecting the server from this attack is a first-level defense mechanism for a website.
Malicious internet users used to clone requests in order to attack vulnerable servers. The malicious site link may be cloned by embedding it in the user's web page.
Anti-CSRF implementation reduces the website's vulnerability. The website rejects malicious access that sends requests with no or incorrect CSRF tokens using this protection. 
In this article, we will look at an example PHP contact form with CSRF protection. This form of protection ensures the genuineness of the request before processing it.
There will be A PHP service that handles security validation against CSRF attacks. Requests from users who do not have a token or have an invalid token will be rejected by the server.

### Key takeaways: 
1. Generate CSRF token and create PHP session
2. Render contact form with CSRF token
3. Anti-Cross-Site Request Forgery (CSRF) validation in PHP
4. Security service to generate, insert, validate CSRF token
5. Output: CSRF validation response from server

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @EssyG10 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
@EssyG10 Good topic. Approved. Please ensure that it is not similar to `https://github.com/section-engineering-education/engineering-education/pull/3372`
