### ISSUE TITLE
Organizing program execution with timers in Matlab

### ISSUE THREAD

**Issue by vitalisodhis** [section-engineering-education/engineering-education#3642]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction paragraph (2-3 paragraphs):
A timer is an automated mechanism for activating a device or a process at a predetermined time or time intervals. Matlab provides timer objects that can be used to organize the execution of Matlab commands. Timers enables control of an events' sequences at fixed intervals and program running time.
In this article I will discuss how one can create a timer object, start the timmer running and specify the processes to be performed when the amount of time specified by the timmer object elapses, stopping and deleting the timer objects from the memory. Timer helps in keeping track of a program hence becomes handy when tracing for troubleshooting.

### Key takeaways: 
- Basic understanding of timer objects in Matlab.
- Matlab codes for implementing timer objects.
- Deleting timer objects from the memory.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @vitalisodhis 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Good topic. Approved. Let's ensure that it adds value to the community. Thanks

**Comment by WanjaMIKE** [comment]
Closed #3642 via #4330
