### ISSUE TITLE
 How to get an Enumerator that Iterates Through the Stack In C#

### ISSUE THREAD

**Issue by AshaIha** [section-engineering-education/engineering-education#3643]
### Proposed title of article
 How to get an Enumerator that Iterates Through the Stack In C#
### Introduction paragraph (2-3 paragraphs):
To support a foreach loop, a data structure must be a subtype of either IEnumerable<T> or IEnumerable, where T is the type of the data structure's members. IEnumerable and IEnumerable are interfaces, we will need to declare any subtypes that implement these interfaces. Stack<T>.GetEnumerator method is used to retrieve an IEnumerator that iterates through the Stack. And it's all part of the System.Collections.Generic namespace.
In this article, you will learn how to get an enumerator that iterates through the stack in C# using the Stack<T>.GetEnumerator method.

### Key takeaways: 
-The learner will understand the use of enumerators in the collection.
-The learner shall understand the purpose of foreach statement.
-The learner shall know how to use the Stack<T>.GetEnumerator Method.
### References: 
N/A

**Comment by WanjaMIKE** [comment]
Are you Thank you for the topic suggestion @AshaIha }, however this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore.
