### ISSUE TITLE
Getting Started with Custom Class Importation in Java

### ISSUE THREAD

**Issue by LynnMumo** [section-engineering-education/engineering-education#3644]
### Proposed title of article
Getting Started with Custom Class Importation in Java
### Introduction paragraph (2-3 paragraphs):
Among all programming languages, Java is the most popular. Use of the Java programming language has various advantages, whether it's for security or large-scale distribution operations. Classes, inheritance, polymorphism, and other Java ideas are used to try to tie every concept in the language to the real world. For a specific purpose, users develop custom classes. These classes do not exist in the project's system library.
How to import custom classes from one project into another, or within the same project, will be discussed in this article.
### Key takeaways: 
-Importing classes from one project into another.
-Importing classes within the same project.
-Reasons for importing custom class in java.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @LynnMumo 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Thank you for the topic suggestion @LynnMumo, however this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore.
