### ISSUE TITLE
Using Java's Queue Interface

### ISSUE THREAD

**Issue by SteveadeNick** [section-engineering-education/engineering-education#3645]
### Proposed title of article
Using Java's Queue Interface
### Introduction paragraph (2-3 paragraphs): 
For example, the FIFO(First In First Out) order of elements is maintained by the Queue interface, which is part of the java.util package. FIFO, or First-In-First-Out, is an ordered list of objects whose use is limited to inserting elements at their end and removing elements from their beginning.
In this article, I will show you all the operations are done in the queue interface.
### Key takeaways: 
-Operations on Queue Interface.
-Classes that implement the Queue Interface.
-Methods of Queue Interface.
-Creating Queue Objects.
### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @SteveadeNick 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Unfortunately, focusing on the Queue interface alone will not make a detailed tutorial. Feel free to suggest another topic. Thanks
