### ISSUE TITLE
Developing Database Applications Using MySQL Connector/C++

### ISSUE THREAD

**Issue by Tonnysage** [section-engineering-education/engineering-education#3650]
### Title

Developing Database Applications Using MySQL Connector/C++

### Introduction paragraph (2-3 paragraphs):

This tutorial will walk you through the processes to create and install the MySQL Connector/C++ driver, including simple examples of how to connect to a MySQL database, input data, and retrieve data. Because the focus of this paper is on database connectivity from a C++ application, it is assumed that a MySQL database is already up and running on the client system.

This lesson is intended for application developers who are unfamiliar with MySQL Connector/C++ but not with C++ programming or the MySQL database.

MySQL Connector/C++ is one of the latest connectors for MySQL, developed by Sun Microsystems. The MySQL connector for C++ provides an object-oriented application programming interface (API) and a database driver for connecting C++ applications to the MySQL Server.

### Key takeaways: 
1. IDE for Developing C++ Applications
2. Testing the MySQL Database Connectivity With the Connector/C++
3. Establish a Connection to the MySQL Server
4. Execute the SQL Statements
5. Retrieving the Data From the Result Set
6. Accessing Result Set Metadata
7. Catching Exceptions
8. Debug Tracing with MySQL Connector/C++

### References: 
- Relational database management system

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Tonnysage 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @Tonnysage. Thanks for submitting your topic suggestion. 

Since we focus on original and unique content, can you tell me how your article would differ for similar C++, MySQL and MySQL/C++ connector tutorials?

**Comment by WanjaMIKE** [comment]
Unfortunately, we already have numerous articles focusing on MySQL connectors.
