### ISSUE TITLE
Arduino Robotics

### ISSUE THREAD

**Issue by owinojoseph** [section-engineering-education/engineering-education#3655]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Arduino Robotics

### Introduction paragraph (2-3 paragraphs):
In this tutorial we will discuss libraries in Arduino and how they are used in robotics. 
The Arduino Robot is the first Arduino-powered vehicle in the world. The Motor Board is in control of the motors, whereas the Control Board is in charge of reading sensors and determining how to operate them. Each board is a fully functional Arduino board that can be programmed with the Arduino IDE.

### Key takeaways: 
By the end of this tutorial the learner will be able to:

- Identify the best Arduino for robot
- know how to code Arduino robot
- some importance of Arduino robot
- setting up the robot
- how to connect the robot to my computer
- understand the libraries used in Arduino for robotics
- Know the board used in Robotics
- simple Arduino program in Robotics

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @owinojoseph 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
@owinojoseph is this a software centric topic?

**Comment by WanjaMIKE** [comment]
@owinojoseph I am closing this topic to free up the queue we can reopen it later when you are ready. Thanks
