### ISSUE TITLE
Firebase Realtime Database Vs MySQL.

### ISSUE THREAD

**Issue by puritymutunga** [section-engineering-education/engineering-education#3663]
### Proposed title of article
Firebase Realtime Database Vs MySQL.
### Introduction paragraph (2-3 paragraph)
 A dependable, robust database is essential for a successful business. However, with so many options available, it's not easy to determine which one to use. MySQL and Firebase are two database technologies that are developed very differently. 
 Firebase is a real-time, cloud-based NoSQL database that synchronizes and stores data between users which allows expressive searches that scale with the size of the result set via Android, iOS, and JavaScript SDKs. Users collaborate and create server less applications across several devices. MySQL, as a relational database management system, it organizes data into tables based on related data types. SQL is used by programmers to manipulate and extract data from the RDMS. MySQL manages users, network access, and other computer storage system components when integrated into an operating system.
In this article we will discuss the features, advantages and disadvantages of both MySQL and Firebase by which will be able to determine when and where to use each database.

### Key takeaways:

1. Features of both MySQL database and Firebase database.
2. Advantages of both MySQL database and Firebase database.
3. Disadvantages of both MySQL database and Firebase database

### References: 
N/A.

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @puritymutunga 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Unfortunately, there are many tutorials that have already covered on each of these technologies. Feel free to suggest another topic. Thanks
