### ISSUE TITLE
Creating ransomware in python3 from scratch

### ISSUE THREAD

**Issue by kimanthi777** [section-engineering-education/engineering-education#3664]
### Proposed title of article
Creating ransomware in python3 from scratch

### Introduction paragraph (2-3 paragraphs):
In recent times, there has been a surge in the number of ransomware attacks targeting various organizations. This may be due to reasons such as lack of cyber training of the employees, poor user practices, inadequate capital to fund security solutions and many more reasons.

A ransomware is a malicious program which restricts a user's access to a computer until they pay ransom to unlock it. It uses file encryption which renders the files unusable thus the user has to obtain a key so as to decrypt the files. This programs are mostly written by hackers motivated by financial gain. Examples include Wannacry and Cryptolocker. An understanding on how they work will be vital to help combat them.

In this tutorial, we are going to learn how ransomware works and we will create our own in Python3. We are going to design our own encryption algorithms from scratch.

### Requirements
> A desktop/laptop
> Python3
> A text editor
> Virtualbox

### Key takeaways: 
> Learn what is a ransomware
> Understand how a ransomware works
> Design an encryption algorithm in Python3
> Create our own ransomware from scratch with python3
> Convert the python file to a windows executable

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)@

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @kimanthi777 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @kimanthi777 
This can be used for malicious activities. Please feel free to suggest an alternate topic to explore. 🚀
