### ISSUE TITLE
Data Visualization with Tables in React.

### ISSUE THREAD

**Issue by Caleb335** [section-engineering-education/engineering-education#3667]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Data Visualization with Tables in React.

### Introduction paragraph (2-3 paragraphs):
Working with tables in React has always been a burden for a very long time now. issue related to the styling, responsiveness, and the proper rendering of data on tables has been encountered by a lot of developers whenever they're trying to render a lot of data onto the UI of a web-application

In this article, we are going to look at an approach that would enable us to properly visualize data on tables with an npm package, called `react-table`. It is a library that focuses on the React Hooks pattern, therefore abstracting the need to manually create or write out HTML table elements. 

### Key takeaways: 
The reader(s) will be able to:

- Create extensively rich tables that would be accessible for people
- Interact with JSON dummy data that would be rendered on the table UI
- Get an understanding of how columns works, how to create an instance of such column with the JSON data that is available.

### References: 
None

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Caleb335 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Caleb335** [comment]
Thank you for the feedback @ahmadmardeni1

**Comment by ahmadmardeni1** [comment]
Great topic 🚀 @Caleb335 , make sure it matches the following:
- Adds value beyond what is in the official docs and what is covered in other blog sites.
- To avoid any potential article closure, it should not overlap with any existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by Caleb335** [comment]
Thank you @ahmadmardeni1! ✊

I'd take note of all that you've mentioned.
