### ISSUE TITLE
How to build Real-time search with Laravel and React

### ISSUE THREAD

**Issue by vicradon** [section-engineering-education/engineering-education#3668]
## Summary
In this how-to guide, I'll guide readers through building a real-time search experience with a Laravel API and React.js. This tutorial will cover the basics of building such an experience in React and how best the backend can handle requests so as not to exceed Laravel's default rate limit.

## Outline

- What is real-time search and why is it important?
- Setting up the React Single Page Application (SPA)
- Setting up the Laravel API
- Architectural overview of the React SPA with code examples
- Architectural overview of the Laravel API with code example
- How to implement caching to reduce API calls
- Conclusion

**Comment by LinusMuema** [comment]
Good afternoon and thank you for submitting your topic suggestion @vicradon.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @vicradon. Great topic suggestion. Your outline shows a very comprehensive article including not only the setup but caching and architectural overviews. Topic approved 🚀. Be sure to cover these areas in plenty of detail to ensure your article is unique over similar articles.
