### ISSUE TITLE
List Initialization in Java

### ISSUE THREAD

**Issue by SusanKiptoo** [section-engineering-education/engineering-education#3670]
### Proposed title of article
List Initialization in Java
### Introduction paragraph (2-3 paragraphs):
Collection has a child interface called Java.util.List. It's a sorted collection of objects that can store duplicate values. List supports positional access and insertion of members because the insertion order is preserved. ArrayList, LinkedList, Vector, and Stack classes implement the List Interface.
In this article, we will learn how to initialize these lists in java.
### Key takeaways: 
-Initializing a list using Collections class methods.
-Initializing a list using List.add() method.
-Initializing a list using Arrays.asList().
-Initializing a list using Java 9 List.of().

### References: 
N/A

**Comment by LinusMuema** [comment]
Good afternoon and thank you for submitting your topic suggestion @SusanKiptoo.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
@SusanKiptoo Unfortunately, this topic is already covered in numerous tutorials and official documentation. Feel free to suggest another topic. Thanks
