### ISSUE TITLE
 Using BlockingQueue in Java  to Create a Producer-Consumer Solution.

### ISSUE THREAD

**Issue by KelvinMwangag** [section-engineering-education/engineering-education#3671]
### Proposed title of article
 Using BlockingQueue in Java to Create a Producer-Consumer Solution.
### Introduction paragraph (2-3 paragraphs):
The Producer-Consumer problem is a synchronization difficulty that occurs when one or more threads generate data and store it in a buffer, and then consume data from the same buffer at the same time.
This can result in a race condition, in which the threads compete with one another to perform their task. Nothing prevents them from entering methods at the same time and producing incorrect results in this circumstance.
Furthermore, because there is no inter-thread communication, the consumer may attempt to remove a piece even though the buffer is empty. When the buffer is full, the producer may try to add another element.
In this article, we will look at the possible solution using BlockingQueue.
### Key takeaways: 
-Implementation of BlockingQueue.
-Production-Consumer Solution.
-Producer-Consumer Problem Solution.
### References: 
N/A

**Comment by LinusMuema** [comment]
Good afternoon and thank you for submitting your topic suggestion @KelvinMwangag.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
good topic @KelvinMwangag  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your {article type} very beneficial.
