### ISSUE TITLE
Working with strings in C++

### ISSUE THREAD

**Issue by duncandegwa** [section-engineering-education/engineering-education#3679]
### Proposed title of article
Working with strings in C++

### Introduction paragraph (2-3 paragraphs)
One of the most useful data types supplied in the C++ libraries is the string. Strings are used for storing text. A `string` variable in C++ contains a collection of characters surrounded by double quotes. In this tutorial, we will discuss the manipulation with character arrays which we simply call **Strings**. We’ll cover all the various operations that you can do with strings.

### Key takeaways: 
By the end of this article the reader should have learned the following:

- C++ String Concatenation
- C++ String Length
- C++ Access Strings
- C++ User Input Strings
- C++ String Namespace

### References: 
N\A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @duncandegwa
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
To help avoid a backlog queue (and longer review times) we are currently only accepting ONE article TOPIC/PR approved at a time 👍. We can re-open this topic - once the 1st one has been merged/published.

**Comment by duncandegwa** [comment]
Hello 👋 Mike
How is the topic suggestion please

**Comment by WanjaMIKE** [comment]
Could you suggest a new topic. Working on strings seems too basic. Thanks
