### ISSUE TITLE
Network Switching Techniques

### ISSUE THREAD

**Issue by Ghassany** [section-engineering-education/engineering-education#3686]
### Proposed title of article
Network Switching Techniques

### Introduction paragraph (2-3 paragraphs):
There are various switching techniques used to transmit the data across the networks. Here are the different types of switching techniques employed to provide communication between two computers:`Circuit Switching`, `Message Switching`, and `Packet Switching`. This tutorial will teach us about the above listed switching techniques one by one. 

### Key takeaways:
At the end of this guide the learner should have understood:
- Circuit Switching
- Message Switching
- Packet Switching.

### References: 
N\A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Ghassany 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Network+Switching+Techniques&rlz=1C1CHBF_enUS891US891&ei=AbdAYdSUJI7Y-gTg_o-ABA&oq=Network+Switching+Techniques&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCABDIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgUIABCGAzIFCAAQhgM6BwgAEEcQsANKBAhBGABQwNUPWMDVD2Cn1w9oAnACeACAAWeIAWeSAQMwLjGYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz&ved=0ahUKEwiUmdDD2_7yAhUOrJ4KHWD_A0AQ4dUDCA4&uact=5)

**Comment by Ghassany** [comment]
Hello @hectorkambow,
I have looked at the article you have suggested and it is much shallow than what am going to write in this tutorial. I will write a unique article and add some concepts that are not in the article you suggested article. In my article I will include the advantages and disadvantagesof each switching technique. Furthermore I will add

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Ghassany 
This topic is already covered by a lot of blog sites. Please feel free to suggest an alternate topic to explore. 🚀
