### ISSUE TITLE
How to use Web Share API?

### ISSUE THREAD

**Issue by giridhar7632** [section-engineering-education/engineering-education#3691]
### Outline
Many modern developers are unaware of the web share API. Using the Web Share API, you can make your content shareable. It enables us to use native share dialog of a device directly from a website or web application. This API can also be used to share files. In this tutorial, you'll learn what is Web Share API and how to use it with some examples.

### Key takeaways: 
By the end of this tutorial:
- one can discover about web share API.
- one can add share button to their application and make their content sharable.
- one can understand how to enable sharing the elements of their web page.

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @giridhar7632 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
To help avoid a backlog queue (and longer review times) we are currently only accepting ONE article TOPIC/PR approved at a time 👍. We can re-open this topic - once the 1st one has been merged/published.
