### ISSUE TITLE
Understand How to Create and Publish Your Own Android Library

### ISSUE THREAD

**Issue by JoelKanyi** [section-engineering-education/engineering-education#3697]
### Introduction paragraph (2-3 paragraphs):
Every android developer always thinks of how they can re-use their code other than always redoing it, also by creating a library, developers participate in open-source ecosystem, because the library is used by other developers. Libraries are an integral part of development that no developer can imagine working without. They help you accelerate your development speed by orders of magnitude through allowing you to use a ready-made solution instead of writing all that code yourself.

An Android library is structurally the same as an Android app module. It can include everything needed to build an app, including source code, resource files, and an Android manifest. However, instead of compiling into an APK that runs on a device, an Android library compiles into an Android Archive (AAR) file that you can use as a dependency for an Android app module.

### Key takeaways: 
- What is a library
- Creating a library module
- Publishing a library

### References: 
[Android Documention](https://developer.android.com/studio/projects/android-library)

**Comment by LinusMuema** [comment]
Good morning and thank you for submitting your topic suggestion. @JoelKanyi 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. :rocket:

**Comment by WanjaMIKE** [comment]
To help avoid a backlog queue (and longer review times) we are currently only accepting ONE article TOPIC/PR approved at a time 👍. We can re-open this topic - once the 1st one has been merged/published.

**Comment by Ericgacoki** [comment]
Reopening since the [previous article](https://github.com/section-engineering-education/engineering-education/pull/3696) was merged.

cc: @WanjaMIKE

**Comment by WanjaMIKE** [comment]
Topic approved. Let's ensure that it adds value to the community. Thanks

**Comment by hectorkambow** [comment]
to help avoid a backlog queue we are only accepting one article topic/pr approved at a time 👍 can be reopened once the first PR is merged.

**Comment by JoelKanyi** [comment]
Hello @hectorkambow my last article was merged on September 22, 2021
I currently don't have an open PR
