### ISSUE TITLE
Simulating the Lorenz system in Matlab

### ISSUE THREAD

**Issue by florenceakinyi** [section-engineering-education/engineering-education#3699]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
The Lorenz system describes the motion of a fluid between two layers at different temperatures.  Specifically, the fluid is heated uniformly from below and cooled uniformly from above. By rising the temperature difference between the two surfaces , we observe initially a linear temperature gradient, and then the formation of the convection cells. This system uses a Lorenz Attractor which defines a 3-dimensional trajectory by the differential equation.
The Lorenz system is deterministic, which means that if you know the exact starting values of your variables then in theory you can determine their future values as they change with time. Lorenz demonstrated that if you begin this model by choosing some values for x, y, and z, and then do it again with just slightly different values, then you will quickly arrive at fundamentally different results. In real life you can never know the exact value of any physical measurement, although you can get close 
### Key takeaways: 
- Basic understanding of the Lorenz system.
- Matlab code for simulating Lorenz system.
- Applications of the Lorenz system.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @florenceakinyi 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
🤔 

@florenceakinyi 
Thank you for the topic suggestion, however I believe this topic may be a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
