### ISSUE TITLE
Responsive Contact Form using Foundation Front-end Framework

### ISSUE THREAD

**Issue by Danco10** [section-engineering-education/engineering-education#3704]
### Proposed title of article
Responsive Contact Form using Foundation Front-end Framework

### Introduction paragraph (2-3 paragraphs):
The Foundation front-end framework is one of the popular choices these days to build the UI. It provides front-end templates, UI components, building blocks and etc.
This framework helps to build modern, responsive UI templates for websites and applications.
It provides customizable UI blocks and supports building a website easily. It has the code snippet for displaying form overlay, site menu and more
This article will help you build a responsive contact form using foundation css

### Key takeaways: 
1. Features of Foundation framework
2. How to integrate the Foundation framework?
3. Front-end themes with Foundation framework classes
4. Configure form rendering directives
5. Contact form backend routine (validation, mail sending) 

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Danco10 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Responsive+Contact+Form+using+Foundation+Front-end+Framework&rlz=1C1CHBF_enUS891US891&ei=QL1AYZi2F87y-gS7ja-ABA&oq=Responsive+Contact+Form+using+Foundation+Front-end+Framework&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABMgUIIRCgATIFCCEQqwI6BwgAEEcQsANKBAhBGABQvowGWL6MBmC1jgZoA3ACeACAAZkBiAGZAZIBAzAuMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwiY1v694f7yAhVOuZ4KHbvGC0AQ4dUDCA4&uact=5)

**Comment by Danco10** [comment]
@hectorkambow,my article will be straight on point and my code snippets will be understood by both beginners and those comfortable with foundation css

**Comment by ahmadmardeni1** [comment]
I think this topic may be over-saturated throughout other blog sites and official documentation.. Please feel free to suggest an alternate topic to explore. 🚀 @Danco10
