### ISSUE TITLE
Watermarking Images with OpenCV in Python

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#3708]
### Proposed title of article
Watermarking Images using OpenCV in Python.

### Introduction paragraph (2-3 paragraphs):
Watermarks play an important part of businesses and online content credit making. They provide ownership or credits to the creator of objects in the digital world, preventing the content from being stolen or replicated without owner's consent. They may be present as a logo, signature, or stamp that is distinctive and unique to the creator. Making these watermarks is now easier than ever using OpenCV.
We will cover as much as possible in this article to make the reader understand OpenCV, a python library that allows us to do several operations like, tracking camera movements, extracting 3D models of any objects, tracking moving objects as well as creating text or image watermarks. The reader will learn how to use this python library to make image watermarks.

### Key takeaways: 
The reader will be able to:
- Understand what OpenCV python library is.
- How to use OpenCV to create image watermarks either textual or image.
- How to define functions to add an image.
- How to adjust the position of the text to suit the content.

### References: 
N/A

### Templates to use as guides
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @dentonya 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Watermarking+Images+with+OpenCV+in+Python&rlz=1C1CHBF_enUS891US891&ei=BrxAYYKbAY3c-gTsj7r4Aw&oq=Watermarking+Images+with+OpenCV+in+Python&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeOgcIABBHELADSgQIQRgAUL_3Eli_9xJgrvkSaAFwAngAgAFmiAFmkgEDMC4xmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwiCtouo4P7yAhUNrp4KHeyHDj8Q4dUDCA4&uact=5)

**Comment by dentonya** [comment]
The article will focus more on how to add a single watermark to multiple images automatically at once  instead of watermarking each image manually.
@hectorkambow

**Comment by ahmadmardeni1** [comment]
Okay, automation is a great idea. But please make sure you build a unique project. @dentonya 

Let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by dentonya** [comment]
Thanks for the feedback I will for sure @ahmadmardeni1
