### ISSUE TITLE
Getting Started with Plugins in Android Studio

### ISSUE THREAD

**Issue by Wkd-Cyber** [section-engineering-education/engineering-education#3712]
### Introduction
Android Studio is a platform that provides a developer-friendly environment to develop android studio applications. It contains `plugins` that extend and add fancy functionality to Android Studio. The plugins provide a comfortable environment for the developer.
In this article, we will take a look at some commonly used plugins and how to set up and install them. We will also learn how to develop a plugin. We will learn to write the plugin using java and Kotlin since these are the supported programming languages.
Lastly, we will learn how we can install and uninstall plugins and also see different roles in Android Studio.

### Key Takeaways
By the end of the tutorial, the user will have learned:
1. What Plugins are and their roles.
2. Commonly used PLugins 
3. Developing Plugin in Java and Kotlin.
4. Installing and Uninstalling Plugins.

### Reference
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Wkd-Cyber 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Wkd-Cyber 
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Getting+Started+with+Plugins+in+Android+Studio&rlz=1C1CHBF_enUS891US891&ei=TbtAYdLhFdfT-wTt74f4Aw&oq=Getting+Started+with+Plugins+in+Android+Studio&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeMggIIRAWEB0QHjoHCAAQRxCwA0oECEEYAFD8gQtY_IELYNSFC2gDcAJ4AIABaYgBaZIBAzAuMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwiSvITQ3_7yAhXX6Z4KHe33AT8Q4dUDCA4&uact=5)

**Comment by ahmadmardeni1** [comment]
This topic may be a bit over-saturated throughout other blog sites and official documentation.

We are looking for programmer-centric concepts explained in a fun and intuitive ways - Please feel free to suggest an alternate topic to explore. 🚀 @Wkd-Cyber
