### ISSUE TITLE
Composition in Java

### ISSUE THREAD

**Issue by Ykz-Jnr** [section-engineering-education/engineering-education#3713]
#### Introduction
`Composition` is one of the most common fundamentals in the java programming language. Composition describes a class that references one or more objects of other classes. It allows for Code re-use by modeling a has-a association between objects, help in design APIs among other of its `advantages` we will discuss. 

In this tutorial, we will introduce composition in OOP and also learn the `implementation` of composition in java. We will further use an example to fully explain and evaluate the idea of composition in java. 
We will also see the `benefits` of composition in oop. Moreso, we will learn the `difference` between inheritance and composition since people often confuse the two fundamentals.

Moreover, the article proposed will use a detailed code snippet to explain to the user how composition occurs. There will also be an example that will help the user practice and try to see their level of understanding of Composition in Java. 

Besides the variety of examples, we will have a sample project that the user will be able to run on their Editors to further grasp the idea of Composition. We will use this project to differentiate Composition in Java and other OOP languages.

### Key Takeaways
1. Advantages of Composition
2. Roles of Composition
3. Implementation of Composition
4. Benefits
5. Difference between composition and Inheritance

### Reference
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Ykz-Jnr 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Ykz-Jnr 

How will this article differ from [what is published our other blog sites](https://www.google.com/search?q=Composition+in+Java&rlz=1C1CHBF_enUS891US891&ei=X8dAYf-2LtOV-wTS-6b4Aw&oq=Composition+in+Java&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgcIABBHELADOgcIABCwAxBDSgQIQRgAULjbBli42wZgyNwGaAJwAngAgAFeiAFekgEBMZgBAKABAqABAcgBCsABAQ&sclient=gws-wiz&ved=0ahUKEwi_4tOR6_7yAhXTyp4KHdK9CT8Q4dUDCA4&uact=5)

**Comment by Ykz-Jnr** [comment]
Update on the question made @hectorkambow

**Comment by WanjaMIKE** [comment]
> Update on the question made @hectorkambow

How will your article differ from existing documentation?

**Comment by Ykz-Jnr** [comment]
Greetings @hectorkambow 

Different from the official documents article will use a tech tutorial and code snippets to illustrate the idea of composition using a real-life example to help the user understand composition in depth.
For the terms used, a simpler explanation and examples will be used so the reader won't tire from the official complex explanations commonly used.

**Comment by WanjaMIKE** [comment]
Topic approved. Let's ensure that it adds value to the community. Thanks
