### ISSUE TITLE
Linux/Unix Commands Cheatsheet 

### ISSUE THREAD

**Issue by Gacheru-sudo** [section-engineering-education/engineering-education#3717]
### Proposed title of article
Linux/Unix Commands Cheat sheet 

### Introduction paragraph (2-3 paragraphs):
Linux/Unix command list provides the linux users(from beginner to expert) with a list of commands and shortcuts that will make their work easier and faster when using the Linux/Unix operating system.

The use of the command line in Linux/Unix OS makes its efficient and reliable for the users to precisely write commands, execute them, terminate them and also manage his file, network and data systems. This command list will help the users do that in a faster and easier way

### Key takeaways: 
-File commands 
-Installation commands
-SSH commands
-Network commands
-System info commands 

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Gacheru-sudo 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
I feel that this topic is already covered in numerous tutorials and official documentation. I would advise you to suggest a new topic and create a unique project. Thanks
