### ISSUE TITLE
How to use a MySQL database in C#

### ISSUE THREAD

**Issue by Amoh-writer** [section-engineering-education/engineering-education#3721]
### Introduction paragraph (2-3 paragraphs):
How to write MySQL in C# is demonstrated in this tutorial. It teaches you how to use C# to program MySQL. C# 8.0+ is required to run the examples. The C# lesson offers a detailed introduction to the C# programming language.
MySQL is a popular database management system that is free and open source. It's a database management system for multiple users and threads
### Key takeaways: 
-What is MySQL?
-C# MySQL version
-C# MySQL SELECT statement
-Creating C# MySQL table

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Amoh-writer 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Unfortunately, this article appears to be covered here `https://www.section.io/engineering-education/java-jdbc/`.

**Comment by Amoh-writer** [comment]
Hello @WanjaMIKE Have changed the topic title from How to use a MySQL database in java  to How to use a MySQL database in C#

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appeared to have been suggested here `https://github.com/section-engineering-education/engineering-education/issues/3603`. Feel free to suggest another topic thanks.
