### ISSUE TITLE
ASYMMETRIC ENCRYPTION

### ISSUE THREAD

**Issue by njerigitahi** [section-engineering-education/engineering-education#3722]
### Proposed title of the article
DHKE and ElGamal algorithm in asymmetric encryptions*

### Introduction paragraph (2-3 paragraphs):
Computer security: involves maintaining integrity, availability, and confidentiality of information system resources.
Can be done using encryption. Encryption involves enciphering data in transit and using the private keys by authorized personnel to access it.
It may be of two types:
Symmetric- use one key
Asymmetric- use two keys a good example of a key generation algorithm is *DHKE* used in algorithms such as *ElGamal.

### Key takeaways: 
1.	Understand asymmetric encryption.
2.	Gain basic knowledge on modular exponential
3.	Finding modular exponential in python
4.	Working of DHKE protocol
5.	Application of DHKE in ElGamal

### References: 
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @njerigitahi 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
👋  
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=ASYMMETRIC+ENCRYPTION&rlz=1C1CHBF_enUS891US891&ei=B8FAYZ_kHZbY-wSZmquABA&oq=ASYMMETRIC+ENCRYPTION&gs_lcp=Cgdnd3Mtd2l6EAMyCAgAEIAEELEDMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgcIABBHELADSgQIQRgAUN2AY1jdgGNghINjaAFwAngAgAFYiAFYkgEBMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwjfg5KL5f7yAhUW7J4KHRnNCkAQ4dUDCA4&uact=5)

**Comment by njerigitahi** [comment]
Am majorly dealing with the understanding of the Diffie Helman Key Generation process while examples for clarity. In addition, I'll also explain how the Elgamal algorithm uses DHKE to generate keys and it's encryption and decryption process. I will briefly explain modula exponential and a code in python to generate it. This is because modula exponential is used in Elgamal during descryption to generate key inverse. This has not been handled in other sites.
@WanjaMIKE

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved  @njerigitahi

**Comment by njerigitahi** [comment]
@louisefindlay23 I have removed the backticks from the line
