### ISSUE TITLE
How to work with Getters and Setters in Java

### ISSUE THREAD

**Issue by mussooo** [section-engineering-education/engineering-education#3725]
### Proposed title of article
How to work with Getters and Setters in Java

### Introduction paragraph (2-3 paragraphs):
When creating classes in Java, it is very important to use Getters and Setters to protect your data.

Getters and Setters play an important role in retrieving and updating the value of a variable outside the encapsulating class. A setter updates the value of a variable, while a getter reads the value of a variable.

Getters and Setters are also called accessors and mutators, respectively.

By convention, getters start with the word "get" and setters with the word "set", followed by a variable name. In both cases, the first letter of the variable's name is capitalized.

In this tutorial, we will look at everything that the reader needs to know on Getters and Setters which include the key takeaways below. 

### Key takeaways: 

 1. Review field variables
 2. Reasons for having getter and setters methods
 3. Learn how to write getter and setter methods
 4. See getters and setters methods working in code demonstration

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic is already covered in numerous tutorials and articles. Feel free to suggest another topic. Thanks
