### ISSUE TITLE
Understanding loops in C

### ISSUE THREAD

**Issue by GeoffreyKangu** [section-engineering-education/engineering-education#3726]
### Introduction paragraph (2-3 paragraphs):
In C programming language, sometimes to need a given block of code to be executed number of times. For this to be effective, you will need to use loops. Loops are usually used to give instructions on which conditions a given block of code is to be executed.

In this tutorial, we shall be looking at while loops, do...while loops, for loops and nested loops. This shall include sample codes illustrating the above mentioned loops.

**Comment by WanjaMIKE** [comment]
While, for, do, and nested loops are already covered in numerous tutorials. I would advise you to suggest a new topic that adds more value to the community. Thanks
