### ISSUE TITLE
Pagination with Python Django

### ISSUE THREAD

**Issue by dentex22** [section-engineering-education/engineering-education#3727]
### Proposed title of article
Pagination with Python Django

### Introduction paragraph (2-3 paragraphs):
While working on modern web application often you will need to paginate the app for better user experience and readability, more so when displaying a huge list of content sliced in multiple pages. To do this, with ease,Django comes with pre-built class, Paginator, which creates and manages paginated data of applications.
In this article will look into how one can use the pre-built class to split content the content of a website or web app into discrete pages. Various ways on how to paginate will be discussed, with code examples given, that is pagination using class based views and function based views.

### Key takeaways: 
The reader will be able to:
- Understand what pagination is and its importance.
- How to paginate web app using Django.
- Various ways of pagination.

### References: 
N/A

### Templates to use as guides
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @dentex22 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Hello @dentex22  , Upon a quick google search, there are several articles on this topic. Can you explain how your article will be different from the ones that exist. Thank you.

**Comment by dentex22** [comment]
> Hello @dentex22 , Upon a quick google search, there are several articles on this topic. Can you explain how your article will be different from the ones that exist. Thank you.

My article will take the reader through a step by step process of how one can split web content, deal with all the ways invol ved each with clear examples with code snippets. I will offer the best guidelines regarding web pagination, its uses and show the reader how its done.Its going to be unique.
