### ISSUE TITLE
Understanding arrays in c

### ISSUE THREAD

**Issue by Ricardojoe** [section-engineering-education/engineering-education#3728]
### Introduction paragraph (2-3 paragraphs):
What are arrays. Arrays in C programs are just a collection of similar data types. This data types are stored in a memory location. Arrays is an example of derived data types such as double, double, int,  char e.t.c.

In this tutorial we shall be looking on how to work with arrays and its advantages and disadvantages.

**Comment by WanjaMIKE** [comment]
Thank you for the topic suggestion @Ricardojoe , however this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore.  - Arrays are already covered in numerous tutorials and official documentation.
