### ISSUE TITLE
ValueTuple and ValueTuple structure in C#

### ISSUE THREAD

**Issue by MICHELLENGEI** [section-engineering-education/engineering-education#3732]
### Proposed title of article
ValueTuple in C#

### Introduction paragraph (2-3 paragraphs):
The value type Tuple is represented by the ValueTuple structure, which was introduced in C# 7.0.It lets you save a data set with several values that may or may not be connected to one another. It can hold elements ranging from 0 to 8, as well as elements of various sorts. Duplicate components can also be stored in a value tuple.
In this article we will talk about the creating and initializing ValueTuple , accessing ValueTuple named and unnamed members, returning ValueTuple from a method, using ValueTuple helper, ValueTuple deconstruction, and lastly ValueTuple structure.
### Key takeaways: 
1.  Creating and initializing ValueTuple.
2.  Accessing ValueTuple named and unnamed members.
3.  Returning ValueTuple from a method.
4.  Using ValueTuple helper.
5.  ValueTuple deconstruction.
6.  ValueTuple structure.

### References: 
N/A.

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @MICHELLENGEI 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=ValueTuple+in+C%23&rlz=1C1CHBF_enUS891US891&ei=N75AYbihCI_r-wTm7L_4Aw&oq=ValueTuple+in+C%23&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeOgcIABBHELADSgQIQRgAUPbvB1j27wdg2PEHaANwAngAgAFWiAFWkgEBMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwj4mNOz4v7yAhWP9Z4KHWb2Dz8Q4dUDCA4&uact=5)

**Comment by hectorkambow** [comment]
@MICHELLENGEI

**Comment by MICHELLENGEI** [comment]
@hectorkambow 
 instead of writing about  ValueTuple alone I will add ValueTuple structure to my article and use well defined and explained examples to explain the contents of the topic. I have made changes please have a look at it now.

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
