### ISSUE TITLE
Add an external CSS file to a JavaFX Application

### ISSUE THREAD

**Issue by blacklihgt** [section-engineering-education/engineering-education#3734]
### Proposed title of the article

Add an external CSS file to a JavaFX Application

### Introduction paragraph (2-3 paragraphs):

Are you having trouble attaching an external CSS file to a JavaFX application? Having issues on how to link an externally designed styling sheet to your program? Worry no more! In this article, you will find answers to these problems.

By now, as you have noticed that JavaFX is easy to work with. Challenges come when one decides to style the JavaFX application. It's a cumbersome procedure since each element requires its style. Issues of the designer remembering previously used styles on different elements arises again and again. This is pretty challenging. In the FXML file, it also is hard to follow up with the styling in the code since it is not continuous. You may also have noticed that the keywords used during styling are different from those of an HTML file. Well, there is a solution to this problem.

### Key takeaways: 

At the end of the article, you will gain the following knowledge:

- Saving a repetitive style for easier use on other elements
- Adding an external stylesheet to the application
- Referencing elements in the stylesheet by adding JavaFX classes
- Linking the stylesheet to multiple scenes

### References: 

- N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by blacklihgt** [comment]
@hectorkambow, I had closed since I read the policy and it states that one is only allowed one issue at a time. So now I've re-opened it

**Comment by louisefindlay23** [comment]
@blacklihgt, how does your proposed topic differ from similar ones on the same topic such as [these](https://www.google.com/search?client=firefox-b-d&q=Add+an+external+CSS+file+to+a+JavaFX+Application)?
