### ISSUE TITLE
Destructuring and Spread Operator in Vanilla JavaScript

### ISSUE THREAD

**Issue by IsaacMuthini** [section-engineering-education/engineering-education#3735]
### Proposed title of article
Destructuring and Spread Operator in Vanilla JavaScript

### Introduction paragraph (2-3 paragraphs):
We all know the amazing data structures in JavaScript which help in writing clean and efficient code. Handling the data structures can be hard some times. In this article we are going to learn about destructuring in arrays and objects in JavaScript together with the Spread Operator

### Key takeaways: 

After reading this article the learner will understand:
- Array Destructuring
-  Object Destructuring
- How to Use Object Destructuring with Functions
- The spread OPerator
### References: 
N/A

**Comment by Qodestackr** [comment]
Hello, @IsaacMuthini Kindly check as I had a similar issue closed:
https://github.com/section-engineering-education/engineering-education/issues/1370
You'll need to ensure that your content doesn't overlap :+1:
