### ISSUE TITLE
Running Background Tasks in Django with Celery

### ISSUE THREAD

**Issue by remiljw** [section-engineering-education/engineering-education#3737]
### Proposed title of article
Scheduling Background Tasks in Django with Celery

### Introduction paragraph (2-3 paragraphs):
When it comes to building web apps and APIs, no doubt Django assist developers with lots of inbuilt features. But have you ever thought you could run tasks separately without having to interfere with the Django server itself?

In this article, I will be showing how you can run background tasks with celery without disrupting the flow of your Django application. We will be building a news app and use Celery to fetch news from a source to populate our database and display the news on an HTML page.

### Key takeaways: 
After reading the article, a reader would be able to:
- Set up a Redis server
- Schedule tasks with Celery
- Run tasks with Celery

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @remiljw 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@remiljw 
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or [what is covered in other blog sites](https://www.google.com/search?q=Running+Background+Tasks+in+Django+with+Celery&rlz=1C1CHBF_enUS891US891&ei=BshAYe68BYLY-gTZi7yABA&oq=Running+Background+Tasks+in+Django+with+Celery&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeOgcIABBHELADOgcIABCwAxBDSgQIQRgAUMeJVVjHiVVgiYtVaANwAngAgAFSiAFSkgEBMZgBAKABAqABAcgBCsABAQ&sclient=gws-wiz&ved=0ahUKEwju1_vg6_7yAhUCrJ4KHdkFD0AQ4dUDCA4&uact=5). (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@remiljw 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
