### ISSUE TITLE
ADD TO CART FUNCTIONALITY IN REACTNATIVE

### ISSUE THREAD

**Issue by ngahika01** [section-engineering-education/engineering-education#3741]
We are going to design a cart page using reactnative and implement the add to cart features using react redux.
The cart has an increment and decrement button.
Thunk middleware will also be used.
We are going to use the expo cli because of the many benefits expo brings into our app.

**Comment by louisefindlay23** [comment]
@ngahika01, please use the topic suggestion form provided so we can adaquately review your article and refrain from typing your topic suggestion title in all caps. 

I've added the template back in to your article. Please fill it in and then reopen once you have done so.
