### ISSUE TITLE
Building a Spotify Playlist Recommendation Engine from scratch

### ISSUE THREAD

**Issue by tanmay69** [section-engineering-education/engineering-education#3742]
### Proposed title of article
Building a Spotify Playlist Recommendation Engine from scratch

### Introduction paragraph (2-3 paragraphs):
Suppose you are browsing through Netflix to watch a TV show and you cannot decide which show to watch, or you are surfing through Spotify and not able to decide which song to listen to. There are many more instances where we have abundant data, and we cannot decide what we need. This is where the Recommendation Systems come into the picture. Recommender systems are designed to recommend things to the user based on many different factors. These systems predict the most likely product to which the users are most likely to purchase and are of interest.

In this blog, we will design a Recommendation Engine from scratch using content-based filtering that will take the user's current playlist as input and recommend new songs according to the current playlist. First, we will start with the basics of recommendation systems, their types, the mathematics behind the recommendation systems, and then dig deeper into its programming aspects.

### Key takeaways: 

- Understanding the working of Recommendation Systems
- Types of Recommendation Systems
- Mathematics behind Recommendation Systems
- Implementing a Spotify Recommender Engine from scratch using Python

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @tanmay69 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @tanmay69
