### ISSUE TITLE
How to use XmlSerializer in C#?

### ISSUE THREAD

**Issue by Amoh-writer** [section-engineering-education/engineering-education#3746]
### Introduction paragraph (2-3 paragraphs):
Serialization/ De-serialization allow communication with another application by sending and receiving data. With XmlSerializer, you can control how objects are encoded into XML.
You'll need the following two classes to execute XML Serialization:

The class StreamWriter is used to write data into a stream.

The XmlSerializer class is a class that allows you to serialize XML documents.                                                                                           
 When data about objects must be transmitted from one application to another, the concepts of serialization and deserialization are utilized. To export application data to a file, serialization is used.

### Key takeaways: 
- StreamWriter
-XmlSerializer class 
- serialization and deserialization
- How to interact with XML file using C# objects
- what is code explanation

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Amos-writer
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Amoh-writer 
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=How+to+use+XmlSerializer+in+C%23%3F&rlz=1C1CHBF_enUS891US891&ei=KtpAYcD0MsTn-wS8zpiABA&oq=How+to+use+XmlSerializer+in+C%23%3F&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEBYQHjIGCAAQFhAeOgcIABBHELADSgQIQRgAUJeiFliXohZg2KMWaANwAngAgAFciAFckgEBMZgBAKABAqABAcgBAsABAQ&sclient=gws-wiz&ved=0ahUKEwjAseCH_f7yAhXE854KHTwnBkAQ4dUDCA4&uact=5)

**Comment by Amoh-writer** [comment]
Hello @hectorkambow,
I have looked at the article you have suggested and it is much shallow than what am going to write in this tutorial. I will write a unique article and add some concepts that are not in the article you suggested article.  For example, they have not described how to serialize objects to  XML and how to interact with XML files using C# objects. Also, my article code snippets will be beginner-friendly and I will explain every bit of the snippet.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @Amoh-writer

**Comment by Amoh-writer** [comment]
Please reopen the topic for me

**Comment by Amoh-writer** [comment]
Hae there can you please reopen this topic for me

**Comment by Amoh-writer** [comment]
Am ready to work on my topic,please reopen it for me

**Comment by Amoh-writer** [comment]
> @Amoh-writer Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

Please can you reopen this topic ,I am ready to work on it
