### ISSUE TITLE
Java Fork/Join Framework

### ISSUE THREAD

**Issue by dorky1** [section-engineering-education/engineering-education#3748]
### Proposed title of article
Java Fork/Join Framework

### Introduction paragraph (2-3 paragraphs):

The fork/join framework is a wrapper around the Executor Service interface that allows you to use two or more processors. It is made for tasks that can be broken down into smaller chunks over and over again. The goal is to maximize the processing power available to increase the efficiency of your application.

In this tutorial, the reader will understand what is fork/join framework plus what it entails and fork-join pool instantiation.

### Key takeaways: 
- Fork/join framework overview
- Fork join pool
- Fork Join Pool Instantiation
- Fork Join Task
- How to submit tasks to the Fork Join Pool

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @dorky1 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@dorky1 
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Java+Fork%2FJoin+Framework&rlz=1C1CHBF_enUS891US891&ei=mdtAYb6hPNjj-gTPlLeABA&oq=Java+Fork%2FJoin+Framework&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjoHCAAQRxCwA0oECEEYAFCyrAJYsqwCYOOtAmgDcAJ4AIABW4gBW5IBATGYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz&ved=0ahUKEwj-0em2_v7yAhXYsZ4KHU_KDUAQ4dUDCA4&uact=5)

**Comment by dorky1** [comment]
Hi, @hectorkambow
This tutorial will include all the concept of the topic with a better explanation to help the reader understand the concepts better and in an easier way. This will be a unique article from the rest  with much more explanation and illustrations.
Thank You
