### ISSUE TITLE
Smell your Kotlin Code with Detekt

### ISSUE THREAD

**Issue by 1-creator** [section-engineering-education/engineering-education#3750]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction paragraph (2-3 paragraphs):
Detekt  is a static code analysis tool that keeps your codebase tidy. You can enforce a wide range of rule sets in your code. You can configure the rules or add your own custom rules. It gives hints about code blocks that are getting a bit complicated, enforce formatting standards, and sniff out potential bugs before they hatch!

### Key takeaways: 
- Get to know what  is Detekt
- Key features of Detekt
- Integrating Detekt into your codebase

### References: 
- [Detekt Official Site](https://detekt.github.io/detekt/)
- [Detekt on Github](https://github.com/detekt/detekt)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @1-creator 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@1-creator 

How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Smell+your+Kotlin+Code+with+Detekt&rlz=1C1CHBF_enUS891US891&ei=wttAYdaFGtav-gTxhq_4Aw&oq=Smell+your+Kotlin+Code+with+Detekt&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABOgcIABBHELADSgQIQRgAUMamVFjGplRg86dUaAJwAngAgAF1iAF1kgEDMC4xmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwjW7o3K_v7yAhXWl54KHXHDCz8Q4dUDCA4&uact=5)
