### ISSUE TITLE
Understanding the Insides of the SMTP Mail Protocol

### ISSUE THREAD

**Issue by Amoh-writer** [section-engineering-education/engineering-education#3756]
### Introduction paragraph (2-3 paragraphs):
Anyone who owns a computer or a mobile device is familiar with email. The mail system is based on a simple protocol that has been around for a long time. The goal of this tutorial is to show you how to create the SMTP protocol in C#.
SMTP and POP3 were the first two mail protocols. IMAP was added after that. SMTP is covered in this article. SMTP stands for Simple Mail Transfer Mechanism. It is a protocol that allows you to send email.

### Key takeaways: 
-Open connection
              SocketClient.cs
-Authenticate
-Hello
-Authenticate
-From
-RcptTo
-Data
-Quit
### References:
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Amoh-writer 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Unfortunately, you can only propose one topic at a time. Thanks
