### ISSUE TITLE
Getting started with Data Visualization using P5.js

### ISSUE THREAD

**Issue by JuliusGikonyoNyambura** [section-engineering-education/engineering-education#3766]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Getting started with Data Visualization with P5.js

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

With the digitalization globalization, data has evolved from limited, expensive, difficult to find and gather to collect to abundant and cheap. Data may be simply acquired from many important consumers in the present digitalization. However, with such a massive volume of data, it might not be easy to store, process, analyze, and comprehend each piece of information. This modest quantity of data is so large that traditional software cannot gather, store, comprehend, or analyze it. As a result, the notion of big data arose.

These resources are only as excellent as what we can produce out of it as individuals and corporations. The concept of big data processes terabytes of raw data into meaningful value that can be used by businesses and individuals, such as predictive analytics. This way, data doesn't sit in a data center unused. Instead, it is turned into digital gold.

Data visualization represents raw data and transforms it into graphs, charts, and pictures that show how the raw data is represented. It enables us to acquire insights, identify new patterns, and identify trends. The original raw data is given meaning and purpose by a visual depiction of it. As a consequence, patterns and trends emerge, and actionable insights can be generated.

In this tutorial, we will learn about data visualization and how to use JavaScript to represent data in graphs and charts in this lesson. We will use P5.js. P5.js is an open-source JavaScript library that makes data visualization accessible to a webpage.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

What is Data Visualization
Why we use Data Visualization
Using P5.js to represent raw data
Other Data Visualization Tools

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @JuliusGikonyoNyambura 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or [what is covered in other blog sites](https://www.google.com/search?q=Getting+started+with+Data+Visualization+with+P5.js+&rlz=1C1CHBF_enUS891US891&ei=7u5AYcusGpH--gTZnJOABA&oq=Getting+started+with+Data+Visualization+with+P5.js+&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABQguQDWILkA2Dj5QNoAnACeACAAYMBiAGDAZIBAzAuMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwjL27bukP_yAhURv54KHVnOBEAQ4dUDCA4&uact=5). (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
