### ISSUE TITLE
Understanding Data Encryption standard(DES algorithm)

### ISSUE THREAD

**Issue by awinomackrine** [section-engineering-education/engineering-education#3768]
### Introduction paragraph (2-3 paragraphs):
DES is a symmetric block cipher that was used by the American government for data protection. It was very secure that it was in the front line in encrypting classified information for the US government. Its use later spread to other sectors of the economy and was used effectively until its retirement after it was successfully broken in 1999.

In this article ill be discussing DES broadly by discussing its history, description, full in-depth functionality, strengths and even its reasons for retirement

### Key takeaways: 
1.  The reader will be able to clearly understand what Data encryption standard is and its origin and evolution.
2.  The reader will be able to understand the functionality of DES(encryption and decryption)
3.  The reader will be able to learn the strengths and weakness of DES and the reasons for its retirement.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @awinomackrine 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@awinomackrine 
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Understanding+Data+Encryption+standard%28DES+algorithm%29&rlz=1C1CHBF_enUS891US891&ei=MO9AYbnaCM6m-wSElKT4Aw&oq=Understanding+Data+Encryption+standard%28DES+algorithm%29&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeMggIIRAWEB0QHkoECEEYAVDoyQtY6MkLYInNC2gCcAB4AIABXYgBXZIBATGYAQCgAQKgAQHAAQE&sclient=gws-wiz&ved=0ahUKEwi5suGNkf_yAhVO054KHQQKCT8Q4dUDCA4&uact=5)

**Comment by awinomackrine** [comment]
@hectorkambow ....l'll use simpler vocabulary with easy to understand example...I'll also discuss the topic extensively adding to what is already in publication

**Comment by hectorkambow** [comment]
Thank you for the follow up 🤔 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

And in order to approve the topic it has to serve value to the larger developer community at large. 

>Please feel free to suggest an alternate topic to explore. 🚀
