### ISSUE TITLE
Introduction to Storage Area networks(SAN)

### ISSUE THREAD

**Issue by elphazesedah** [section-engineering-education/engineering-education#3769]
### Introduction paragraph (2-3 paragraphs):

Storage area networks sometimes called storage network is a computer network that is used for directly accessing block level storage devices. SAN is mainly used in getting access to storage devices such as disk arrays and tape libraries from servers. This allow for the storage devices to appear to be directly attached to a host device.

In this article, we will be discussing the current trends in data storage, the differences between SAN and NAS and their convergence trends, the protocols and Devices used in SAN and finally the iSCSI products used with SAN.

### Key takeaways: 

1. The reader will understand the clear meaning and use of the Storage area networks.
2. The reader will be able to understand the different trends in data storage.
3. The reader will learn the protocols used to implement storage area networks and the iSCSi products involved

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @elphazesedah 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@elphazesedah 
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=ntroduction+to+Storage+Area+networks%28SAN%29&rlz=1C1CHBF_enUS891US891&ei=8u9AYeKcC9LY-gSHu7yABA&oq=ntroduction+to+Storage+Area+networks%28SAN%29&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeMggIIRAWEB0QHjIICCEQFhAdEB4yCAghEBYQHRAeOgcIABBHELADSgQIQRgAUNfrAljX6wJg0-0CaAJwAngAgAFjiAFjkgEBMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwji3aTqkf_yAhVSrJ4KHYcdD0AQ4dUDCA4&uact=5)

**Comment by elphazesedah** [comment]
@hectorkambow ...l will use simple vocabulary with easy to understand examples...I will also discuss the topic deeply adding to what is already published

**Comment by hectorkambow** [comment]
Thank you for the follow up 
🤔 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. _We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts._ 

And in order to approve the topic it has to serve value to the larger developer community at large. 
>Please feel free to suggest an alternate topic to explore. 🚀
