### ISSUE TITLE
Address Discovery using ARP Protocol

### ISSUE THREAD

**Issue by RuthAMare** [section-engineering-education/engineering-education#3770]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Address Discovery using ARP Protocol

### Introduction paragraph (2-3 paragraphs):
This article will give an introduction to the protocol ARP as applied in network communication and packet transmission, what ARP does, explain the process of address resolution by ARP and where it is used.
It will also, give the application scenarios of ARP protocol.
 
### Key takeaways: 
At the end of this article the learner should know:
1. What is ARP.
2. The process of Address resolution.
3. Application of ARP protocol.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Unfortunately, you can only propose one topic at a time. Thanks
