### ISSUE TITLE
Implement Apache Kafka In .NET Application

### ISSUE THREAD

**Issue by peshbiz** [section-engineering-education/engineering-education#3771]
Kafka is an open-source distributed stream-processing platform that is capable of handling over trillions of events in a day. This massive platform has been developed by the LinkedIn Team, written in Java and Scala, and donated to Apache.

### Key Take Away

1. Learn how to install configure and run Kafka.
2. Learn How Kafka Works.
3. Learn How to implement Kafka in .NET Application

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @peshbiz 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@peshbiz 

How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Implement+Apache+Kafka+In+.NET+Application&rlz=1C1CHBF_enUS891US891&ei=JPBAYbOQIM7f-gTP0JX4Aw&oq=Implement+Apache+Kafka+In+.NET+Application&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEBYQHjoHCAAQRxCwA0oECEEYAFDN6gRYzeoEYPbrBGgAcAR4AIABaogBapIBAzAuMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwizsqWCkv_yAhXOr54KHU9oBT8Q4dUDCA4&uact=5)

**Comment by peshbiz** [comment]
In the implementation, I shall also show how to integrate the Apache Kafka with the Azure Event Hub.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @peshbiz 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
