### ISSUE TITLE
Step by step guide on connecting Firebase to a contact form

### ISSUE THREAD

**Issue by Pauline-Mwangi** [section-engineering-education/engineering-education#3772]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Step by step guide on connecting Firebase to a contact form
### Introduction paragraph (2-3 paragraphs):
In this tutorial, we will create a responsive contact form. Then, we will implement the back-end using Firebase, a cloud service for database and authentication. Finally, Firebase will receive data sent from the contact form.

We will connect the project to Firebase using JavaScript and the Firebase library. JavaScript will send data to Firebase.
### Key takeaways: 
1. Step1: Create a Firebase project
2. Step2: Initialize the project
3. Step3: Create a contact form
4. Step4: Create the JavaScript file
5. Step5: Review data submitted to Firebase
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Pauline-Mwangi 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Pauline-Mwangi 

How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=connecting+Firebase+to+a+contact+form&rlz=1C1CHBF_enUS891US891&ei=ePBAYdqlGNTw-wS684qQCQ&oq=connecting+Firebase+to+a+contact+form&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEOgcIABBHELADSgQIQRgAUNvFAljbxQJg8McCaANwAngAgAFhiAFhkgEBMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwjawaSqkv_yAhVU-J4KHbq5ApIQ4dUDCA4&uact=5)

**Comment by Pauline-Mwangi** [comment]
@hectorkambow 
This tutorial will give a step-by-step demonstration and explanation of creating a responsive contact form and implementing the backend using Firebase.  It will be descriptive, easy to understand and offer unique content to the readers. 
After a successful connection, we will review data submitted from the contact form to Firebase.

**Comment by hectorkambow** [comment]
@Pauline-Mwangi 

Thank you for the follow up 🤔 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. _We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts._ 

And in order to approve the topic it has to serve value to the larger developer community at large. 

>Please feel free to suggest an alternate topic to explore. 🚀
