### ISSUE TITLE
Bootstrap Contact Form with JavaScript Validation and PHP 

### ISSUE THREAD

**Issue by Njambi254** [section-engineering-education/engineering-education#3774]
### Proposed title of the article
Bootstrap Contact Form with JavaScript Validation and PHP 
### Introduction paragraph (2-3 paragraphs):
Bootstrap is a framework that enables developers to create UI components that are optimized for mobile.
Often, many readers are aware of a Bootstrap contact form code, So I thought of creating a basic example for a Bootstrap enabled PHP contact form.
Bootstrap is an in-built framework that provides features to enable developers to create responsive UIs, form validation, and more.
A well-designed contact form makes it attractive to people. Also, it allows the developers to create something that's already built-in.
This article will have one of the best and sleek contact form components you can ever get.

### Key takeaways: 
1. Contact form with vs without Bootstrap
2. Slim UI layout with the Bootstrap contact from
3. Contact form validation with plain JavaScript
4. Processing contact form data in PHP code

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, we have too many tutorials focusing on contact forms. Feel free to suggest another topic. Thanks
