### ISSUE TITLE
Track Individual Logged in Users using Google Analytics

### ISSUE THREAD

**Issue by Nancy245** [section-engineering-education/engineering-education#3778]
### Proposed title of the article
Track Individual Logged in Users using Google Analytics

### Introduction paragraph (2-3 paragraphs):
Google Analytics is a tool that helps us monitor the website's traffic. It collects information about the visitors who visit the site. Often people ask if it is really possible to track individual users in Google Analytics. And the answer is: It is possible if your application is a member-based application and has an authenticated mechanism.
For instance, if yours is a task management system or a shopping cart, Google Analytics can be used to monitor the activity of the users who are logged in.
In this article, we will demonstrate how to implement the same functionality of Google Analytics without the need for Google Tag Manager. Both tools are very different,in that Google tag manager is like a container for adding different tags. Wherein Google Analytics is one such tag that is used to collect and analyze your website traffic.
 

### Key takeaways: 
1. log in to Google Analytics and then create an Account.
2. Create Property.
3. Create View with User-ID enabled.
4. Create Custom Dimensions to track user types.
5. Modify tracking code to include user-id and custom dimensions.
6. Create custom reports, view and analyze data.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Nancy245
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Track+Individual+Logged+in+Users+using+Google+Analytics&rlz=1C1CHBF_enUS891US891&ei=JPJAYbHGGcnY-gTvoZaABA&oq=Track+Individual+Logged+in+Users+using+Google+Analytics&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCGAzIFCAAQhgMyBQgAEIYDMgUIABCGAzIFCAAQhgM6BwgAEEcQsANKBAhBGABQxaQFWMWkBWCJpgVoA3ACeACAAXGIAXGSAQMwLjGYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz&ved=0ahUKEwix6LD2k__yAhVJrJ4KHe-QBUAQ4dUDCA4&uact=5)

**Comment by Nancy245** [comment]
@hectorkambow, This article will be simple and straight on point

**Comment by WanjaMIKE** [comment]
Let's ensure that it adds value to the community. Thanks
