### ISSUE TITLE
Trello Like Drag and Drop Cards for Project Management Software

### ISSUE THREAD

**Issue by Cecy140** [section-engineering-education/engineering-education#3779]
### Proposed title of the article
Trello Like Drag and Drop Cards for Project Management Software

### Introduction paragraph (2-3 paragraphs):
Effective project management is a critical need for project success. To ensure that, we cannot depend only on human resources for managing projects. Managers need to be armed with the best project management software.
In this competitive fast-moving world, we need a rapid, never dying, efficient routine for managing projects. The project management software should play an efficient role by enabling the people managing the projects.

There is too much project management software out there in the market and I am not going to recommend one in this article. But we are going to see a killer feature that is dominating the project management software industry these days. Project management systems like Trello, Mingle have the interactive card-like status-based grouping of projects and tasks. This card-based task grouping is intuitive to use.

Many of the project management software applications, provide the project management functionality with the traditional list-based design methodology. That is, by having a long list task managed in a tabular form and controls to perform CRUD via HTML forms. With my personal opinion and expertise, I found the card-based interface comfortable to organize the tasks. In this article, we will find out how to implement cards with drag and drop using PHP, which can be used in project management software.

### Key takeaways: 
1. Interactive Task Board UI
2. jQuery Drag and Drop to Move Task Cards between Status Lanes
3. PHP ProjectManagement Model Class
### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Cecy140 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Cecy140 

It looks like this article was published elsewhere. 

We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
