### ISSUE TITLE
How to Migrate Website from PHP 5.6 to PHP 8

### ISSUE THREAD

**Issue by Njoroge455** [section-engineering-education/engineering-education#3780]
### Proposed title of the article
How to Migrate Website from PHP 5.6 to PHP 8

### Introduction paragraph (2-3 paragraphs):
PHP 5.6 version active releases ended in early 2017 and reached its end of life (EOL) by 2018 end. That was once I
This article will guide you for the migration of the PHP application or website only. Upgrading the server environment like the Apache version or the installed PHP version is not discussed in this article since it is a sysadmin thing.

If you are on a shared web hosting server, you will have an option in your control panel. It should be a single click easy work. Otherwise, your hosting provider will do it for you. You may have to raise a ticket to get it done. Unless if you are in a dedicated server environment, you need not worry about.

Whatsoever, migration of the website or the PHP application should be done by you. It is not in the hosting provider or sysadmin’s scope. It should be done by the PHP developer.

### Key takeaways: 
1. PHP versions, support, and EOL
2. Why should you migrate from PHP 5.6?
3. Security
4. Performance
5. New PHP features
6. Backwards compatibility
7. Deprecated features in PHP 8
8. Steps to do the PHP website migration

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Njoroge455 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
@Njoroge455 Please check the latest version of PHP

**Comment by Njoroge455** [comment]
@WanjaMIKE, I have rectified the issue

**Comment by WanjaMIKE** [comment]
Please check out this article -> https://www.section.io/engineering-education/getting-started-with-php7-without-using-a-framework/

**Comment by WanjaMIKE** [comment]
Closing since the topic suggested has already been covered in other published articles. Feel free to suggest another topic. Thanks
