### ISSUE TITLE
Introduction to Staggered RecyclerView Implementation in Android studio

### ISSUE THREAD

**Issue by Wachira48** [section-engineering-education/engineering-education#3781]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*
Introduction to Staggered RecyclerView Implementation in Android studio
### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 
RecyclerView is an android widget for displaying large data sets that can be scrolled efficiently by maintaining a limited list of items/views. The RecyclerView widget is a more advanced and flexible version of ListView and GridView. This list of items could be just Java objects. These Java objects could be an array of strings or a collection of strings, or custom Java objects. This list of objects is referred to as non UI elements. RecyclerView uses an adapter as the data transformation objects to convert a list of objects into a list of views. I.e., scrollable UI elements with data collections whose elements change at runtime based on user action or network events. RecyclerView creates enough view components that the user will see at any one time. As the user scrolls through the list, it uses the same view components to show data that is further down in the list. This makes efficient use of the UI components. essentially it is recycling these UI components, which is why it's called a RecyclerView

The RecyclerView class simplifies the display and handling of large data sets by providing Layout managers for positioning items and default animations for common item operations, such as removing or adding items. A layout manager positions item views inside a RecyclerView and determines when to reuse item views that are no longer visible to the user. For example, to reuse (or recycle) a view, a layout manager may ask the adapter to replace the view's contents with a different element from the dataset. You also have the flexibility to define custom layout managers and animations for RecyclerView widgets. This means you can modify your RecyclerView widget to fit the represented data set. For example, you can build RecyclerViews such as nested lists, expandable lists, staggered lists, etc.

In this article, we are going to implement staggered RecyclerView in the android studio.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.
- What is RecyclerView
- Why do we need RecyclerView
- What is staggered RecyclerView
- Set up Gradle Dependencies
- Create an Activity Layout with RecyclerView
- Create a Layout that will be used as a Grid in the RecyclerView
- Setup Adapter and ViewHolder for the staggered RecyclerView.
- Setup recycler view manager (staggered grid manager)
- Setup RecyclerView adapter
- Setup the staggered RecyclerView.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
https://developer.android.com/guide/topics/ui/layout/recyclerview

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Wachira48 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
This topic suggestion seems to be over saturated and just the intro here seems to have many overlaps with other articles via our 3rd plagiarism checker. 

We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

[Introduction to Staggered RecyclerView Implementation in Android studio #3781.pdf](https://github.com/section-engineering-education/engineering-education/files/7164589/Introduction.to.Staggered.RecyclerView.Implementation.in.Android.studio.3781.pdf)

**Comment by Wachira48** [comment]
@hectorkambow, I didn't know plagiarism check is run on an issue. The few highlighted flags are some basic concepts that can apply to any RecyclerView topic. The flags are only on the introductory paragraph. The highlighted blogs do not explain the concept of Staggered RecyclerView, as I intend to do. I will also make sure the submitted will be original or add a reference to any necessary sources and dive deeper into the overall Staggered RecyclerView topic.

I am requesting if this topic can be reponed so that I can discuss this concept of Staggered RecyclerView.
