### ISSUE TITLE
Extract images from URL in excel with PHP using PhpSpreadsheet 

### ISSUE THREAD

**Issue by Eliud200** [section-engineering-education/engineering-education#3783]
### Proposed title of the article
Extract images from URL in excel with PHP using PhpSpreadsheet 

### Introduction paragraph (2-3 paragraphs):
There are various ways to extract images from a given URL. PHP contains built-in functions for extracting data including the images with a URL.
This article is for PHP code to extract images from URLs existing in an excel file.
I have used PhpSpreadsheet to read the URLs from an Excel file. Then, I will create a cURL script to extract images from the URL.
PhpSpreadsheet library supports Excel read-write operations. It provides enormous features like formatting content, manipulating data, and more. It has a rich set of built-in classes and thereby makes the development process easy.
Working with spreadsheets is a common need while handling excel data via programming. PhpSpreadsheet library reduces the developer’s effort on building applications with excel data handing.

### Key takeaways: 
1. Uses of extracting images from URL from Excel
2. Advantages of PhpSpreadsheet Library
3. Existing PHP libraries used to import-export
4. File Structure
5. About this example
6. PHP code to load and extract image data
7. Render extracted images in a gallery
8. Database script
9. Extract images from URL in excel using PhpSpreadsheet Output
### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Eliud200 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Eliud200 

How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Extract+images+from+URL+in+excel+with+PHP+using+PhpSpreadsheet&rlz=1C1CHBF_enUS891US891&ei=7PVAYaWBMc3C-gTmmJDgAw&oq=Extract+images+from+URL+in+excel+with+PHP+using+PhpSpreadsheet&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABQ9-cCWPfnAmC06QJoAnACeACAAXWIAXWSAQMwLjGYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz&ved=0ahUKEwilp5LEl__yAhVNoZ4KHWYMBDwQ4dUDCA4&uact=5)

**Comment by Eliud200** [comment]
@hectorkambow , I'll be using php 8 which is something lacking to other similar content in the Internet

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
