### ISSUE TITLE
Getting Started With Stripe in SpringBoot

### ISSUE THREAD

**Issue by davidmbochi** [section-engineering-education/engineering-education#3784]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting Started With Stripe in SpringBoot

### Introduction paragraph (2-3 paragraphs):
Stripe is an online payment system that is almost similar to PayPal and it allows transactions to take place between seller and buyer by leveraging their credit cards.
In this tutorial, the reader will learn how to use the Stripe API to charge a credit card that was provided by the customer using a Java library.

### Key takeaways: 
- [Registering a stripe account]()
- [Adding Stripe library for Java]()
- [How to implement the transaction ]()

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @davidmbochi 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@davidmbochi 
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Getting+Started+With+Stripe+in+SpringBoot&rlz=1C1CHBF_enUS891US891&ei=HvZAYc6ZK9L7-gTJoIsw&oq=Getting+Started+With+Stripe+in+SpringBoot&gs_lcp=Cgdnd3Mtd2l6EAMyBwghEAoQoAEyBwghEAoQoAE6BwgAEEcQsANKBAhBGABQ7dUCWO3VAmDG1wJoAnACeACAAXmIAXmSAQMwLjGYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz&ved=0ahUKEwjOoPjbl__yAhXSvZ4KHUnQAgYQ4dUDCA4&uact=5)

**Comment by davidmbochi** [comment]
@hectorkambow 
This article will teach the reader how to ensure that the payments are secure and confidential details are protected from unauthorised access.

**Comment by WanjaMIKE** [comment]
Let's ensure that it adds value to the community. Thanks
