### ISSUE TITLE
Introduction to Low-code and BaaS with Hypi

### ISSUE THREAD

**Issue by Pato-254** [section-engineering-education/engineering-education#3785]
### Proposed title of the article
Introduction to Low-code and BaaS with Hypi

### Introduction paragraph (2-3 paragraphs):
Year 2021! If a developer is still writing all the code from scratch for developing applications, he is living in the ’90s! We are in the future and the future is low code!

In this article, we will check the features of Low Code first. And then I will introduce you to BaaS (Backend as a Service) and the most feature-rich Low Code backend – Hypi!

### Key takeaways: 
1. What is Low Code?
2. What is Low Code Development Platform?
3. Why Low Code Platform?
4. What projects are being delivered using Low Code?
5. Infographic Text
6. What is BaaS?
7. What are the features of BaaS?
8. Hypi – The most feature-rich Low code backend
9. What can you do with Hypi?
10. What does Hypi Offer?
11. How to get started with Hypi?
### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Pato-254 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Pato-254 
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Introduction+to+Low-code+and+BaaS+with+Hypi&rlz=1C1CHBF_enUS891US891&ei=TfZAYYiKMJXv-gSoxJaIDw&oq=Introduction+to+Low-code+and+BaaS+with+Hypi&gs_lcp=Cgdnd3Mtd2l6EAMyBwghEAoQoAEyBwghEAoQoAEyBwghEAoQoAE6BwgAEEcQsANKBAhBGABQrOoHWKzqB2Cs7AdoAXABeACAAZQBiAGUAZIBAzAuMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwjI5LHyl__yAhWVt54KHSiiBfEQ4dUDCA4&uact=5)

**Comment by Pato-254** [comment]
@hectorkambow, simplicity will be key so as to  create a favorable learning site for both experts and begginers

**Comment by hectorkambow** [comment]
🤔 

Thank you for the follow up. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

And in order to approve the topic it has to serve value to the larger developer community at large. 

>Please feel free to suggest an alternate topic to explore. 🚀
