### ISSUE TITLE
13 best IP geolocation APIs & services for PHP

### ISSUE THREAD

**Issue by Achie10** [section-engineering-education/engineering-education#3786]
### Proposed title of the article
13 best IP geolocation APIs & services for PHP

### Introduction paragraph (2-3 paragraphs):
APIs enable mission-critical capabilities for many platforms. Fraud detection for online stores and banking can depend on IP geolocation services using IP lookup to detect whether a user’s IP address matches their stated country.
But location information can be faked by VPNs, proxies, and anonymizers (TOR) to circumvent IP lookup. So if you’re looking to geolocate an IP address in PHP, can any detect this?
This article will contain 10 of the best IP geolocation APIs for determining a user’s location as well as three other potentially useful APIs. All use PHP, the well-known scripting language and many offer free IP geolocation plans.
But even when APIs have similar functions, there can be significant differences between them. Functionality can be different or locked behind pricing tiers.

### Key takeaways: 
1. Abstract API
2. MaxMind
3. Ipgeolocation
4. Ip2location
5. Ipstack
6. DB-IP
7. Ip-info
8. Ipapi
9. Positionstack
10. Ipdata
11. meteoblue
12. Mapquest

Skyscanner flight search
### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Achie10 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
[13 best IP geolocation APIs & services for PHP #3786.pdf](https://github.com/section-engineering-education/engineering-education/files/7164651/13.best.IP.geolocation.APIs.services.for.PHP.3786.pdf)

This topic suggestion seems to be over saturated and just the intro here seems to have many overlaps with other articles via our 3rd plagiarism checker.

We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
