### ISSUE TITLE
Image Editor: Move Scale Skew Rotate and Spin with CSS Transform

### ISSUE THREAD

**Issue by Ethan-155** [section-engineering-education/engineering-education#3787]
### Proposed title of article
Image Editor: Move Scale Skew Rotate and Spin with CSS Transform

### Introduction paragraph (2-3 paragraphs):
An image editor will have a range of tools. It can be very basic with only tools like resize, rotate and crop. Or it can be super extensive like Photoshop.
Rotate is a basic and essential tool that is part of any image editor. Let us start with something easy and basic like rotate then add some more essential tools.
I will be using CSS transform property as the core and add JavaScript to enrich the tool.

This can become a basic starter toolkit that can be expanded to a full-fledged image editor in the future. 

### Key takeaways: 
1. How to edit an image?
2. A quick glance at CSS transform and image editing
3. Examples and demo on image editing
4. Conditions and exceptions on applying transform property
5. Importance of respecting system preferences

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Ethan-155 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
[Image Editor Move Scale Skew Rotate and Spin with CSS Transform #3787.pdf](https://github.com/section-engineering-education/engineering-education/files/7164666/Image.Editor.Move.Scale.Skew.Rotate.and.Spin.with.CSS.Transform.3787.pdf)


This topic suggestion seems to be published somewhere else.

We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
