### ISSUE TITLE
Getting started with Java Logger

### ISSUE THREAD

**Issue by Dawe-7** [section-engineering-education/engineering-education#3791]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting started with Java Logger

### Introduction paragraph (2-3 paragraphs):
We frequently encounter errors while developing Java programs, which must be debugged.  Java developers need a way to eradicate these errors so that they don’t cause downtime when programming. With the aid of logs provided by the Java programming language, we can quickly learn about what's going on in the program. Including a history of errors and unexpected events. Logging is a crucial feature that developers should consider in order to track down errors. The API offered by the `java.util.logging ` package and the `org.apache.log4j.*` package makes logging in Java much easier. This article will discuss how Java developers can use this feature to enable extensible logging in Java. 

### Key takeaways: 
1. The Need for logging
2. Logging Components
3. What is Logger?
4. Create new Logger,  Log Levels,  Properties File,  Logging Events
5. Appender or Handlers
6. Layout or Formatters

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Dawe-7 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Dawe-7 
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Getting+started+with+Java+Logger&rlz=1C1CHBF_enUS891US891&ei=g_xAYYzGD4KGtQbf8LSQDg&oq=Getting+started+with+Java+Logger&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeSgQIQRgBUNfEBFjXxARgmcYEaAJwAHgAgAF0iAF0kgEDMC4xmAEAoAECoAEBwAEB&sclient=gws-wiz&ved=0ahUKEwjMk6fonf_yAhUCQ80KHV84DeIQ4dUDCA4&uact=5)

**Comment by WanjaMIKE** [comment]
Closing since there is no feedback for a while. We can reopen later. Thanks
