### ISSUE TITLE
Synchronized Java Collections 

### ISSUE THREAD

**Issue by wanjadeno** [section-engineering-education/engineering-education#3793]
### Proposed title of article
Synchronized Java Collections 

### Introduction paragraph (2-3 paragraphs):
The fact that Java objects can be "locked" is a fascinating feature. This is the java.lang package. The Object interface provides an implicit locking mechanism that allows any Java object to be locked while a synchronized method or synchronized block is being executed. So that the thread in possession of the lock has exclusive access to the object for the length of the method call or block's scope. Until the thread that holds the lock "releases" the item, no other thread can "acquire" it. Mutual exclusion is provided by this synchronization policy.
In this tutorial, the reader will understand the concept of synchronized java collections in depth.
 
### Key takeaways: 
- Synchronization overview.
- Different method used in synchronized java collections.
- Why we use array List when vector is synchronized.
- Synchronized vs Concurrent Collections.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @wanjadeno 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@wanjadeno 
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Synchronized+Java+Collections&rlz=1C1CHBF_enUS891US891&ei=0fxAYYjPMtS4tQaQ3IeQBQ&oq=Synchronized+Java+Collections&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMggIABAWEAoQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BwgAEEcQsANKBAhBGABQoZ-lA1ihn6UDYImhpQNoA3ACeACAAVSIAVSSAQExmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwjI--KNnv_yAhVUXM0KHRDuAVIQ4dUDCA4&uact=5)

**Comment by wanjadeno** [comment]
@hectorkambow 
This will be a detailed article including a step by step explanation to make sure that the readers to have better understanding including all concepts. I will write a unique article all through.
Thank you.
