### ISSUE TITLE
understanding  comments in programming (codding  in C,C++&Java)

### ISSUE THREAD

**Issue by Njengab** [section-engineering-education/engineering-education#3794]
Understanding comments in programming (codding in C,C++ & Java)

Introduction

Comments are code description (s) that tell what a piece of code or block of code does.Comments are very important in program design.They are much more useful when it comes to debugging.

Comments can illustrate how or what the program does to programmers or even end users.
Comments can be used in commenting to make code maintenance much easier. 

     
    Key Takeaways

1. Types of comments
2. Comments syntax 	
3. Use of comments in codding
4. Importance of comments

References
n/a

**Comment by WanjaMIKE** [comment]
Unfortunately, focusing on comments alone cannot make a detailed tutorial. Feel free to choose another topic. Thanks

**Comment by Njengab** [comment]
Hello i have made another  suggestion kindly have a look. thanks
