### ISSUE TITLE
Variable Scopes In C Programming Language

### ISSUE THREAD

**Issue by IsaacMuthini** [section-engineering-education/engineering-education#3795]
### Proposed title of article
Variable Scopes In C Programming

### Introduction paragraph (2-3 paragraphs):
The scope of a variable is a topic that comes up frequently in programming. The scope of a variable defines whether or not it may be accessed and modified within a given code block.
Variable scope in the C programming language will be covered in this course. To help you grasp the distinctions between local and global variables, you'll see several code examples.

### Key takeaways: 
After going through this article the learner will learn:
- What a Scope is
- Local scope
- Global Scope
- How each scope is used by use of examples

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @IsaacMuthini 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@IsaacMuthini 
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=Variable+Scopes+In+C+Programming+Language&rlz=1C1CHBF_enUS891US891&ei=zBdBYfcegc-1BtaMuKgD&oq=Variable+Scopes+In+C+Programming+Language&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeOgcIABBHELADSgQIQRgAUP_SA1j_0gNgw9QDaAJwAngAgAFQiAFQkgEBMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwj3tPLqt__yAhWBZ80KHVYGDjUQ4dUDCA4&uact=5)
