### ISSUE TITLE
The C# type system

### ISSUE THREAD

**Issue by neheMaish** [section-engineering-education/engineering-education#3796]
### Proposed title of article
The C# type system
### Introduction paragraph (2-3 paragraphs):
For example, C# is a strongly-typed language. Any expression that evaluates to a value has a type. For each argument and return value, a method declaration provides the name, number, type and kind (value, reference, or output). Numeric types and more complicated types are defined in the.NET class library, including representations of the file system, network connections, arrays, and dates. Types from the class library and user-defined types are used in a typical C# program to model the notions that are specific to the application's issue domain.

A type's information can comprise the following:
1. How much memory a variable of that type requires.
2. The basic type from which it derives
3. There are a number of members that it contains (methods, fields, events and so on).
4. . The types of operations allowed. 
5. Implementation of the interface.
6.  There is a maximum and a minimum value that it represents.

Type information is used by the compiler to ensure that all actions in your code are type-safe. An int variable declared by the programmer, for example, can be used in addition and subtraction operations. Any attempt to do the same procedures on a bool variable results in an error.

In this article, we shall deeply take a look at the C# type system step by step.

### Key takeaways: 
1. Specifying types in variable declarations
2. The common type system
3. Generic types
4. Implicit types, anonymous types, and nullable value types

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @neheMaish 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@nehemaish

this articles seems to be published somewhere else. 

We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
