### ISSUE TITLE
PHP user authentication with MYSQL

### ISSUE THREAD

**Issue by Techilla254** [section-engineering-education/engineering-education#3798]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
PHP user authentication with MYSQL

### Introduction paragraph (2-3 paragraphs):

user authentication is a process of validating users with some keys, tokens or any other credentials then authentication process will be successfully.
after succsseful authentication ,users will be allowed to the system as authenticated users.
in this tutorial we are going to create a php user authentication system with mysql database.
it has a login panel to let users enter their login details for our case is(username and password)
by submitting these login credentials it will be posted to a php page,the php code executes a SELECT query to check if a  user found in the database with entered login credentials 
.if a match found then the authentication process will be cleared by the user who attempts to login,after successful login the authenticated user will be allowed to enter into the 
application. 
### Key takeaways: 
1.Create a MYSQL database with users table.
2.create a user login panel to submit login details to Php. 
3.Generate query to compare user login details with the MYSQL user database. 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Techilla254 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@techilla254
How will this article differ from what is [published our other blog sites](https://www.google.com/search?q=PHP+user+authentication+with+MYSQL&rlz=1C1CHBF_enUS891US891&ei=ChhBYcHVBsi2tAaVqIPADQ&oq=PHP+user+authentication+with+MYSQL&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeMggIIRAWEB0QHjIICCEQFhAdEB46BwgAEEcQsANKBAhBGABQ3u0aWN7tGmC57xpoAnACeACAAVGIAVGSAQExmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwjBgsGIuP_yAhVIG80KHRXUANgQ4dUDCA4&uact=5)

**Comment by Techilla254** [comment]
Codes snippets for my article will be direct and simple and it will enhance readers understanding through my UI and UX designs

**Comment by WanjaMIKE** [comment]
Unfortunately, we have many articles focusing on the concepts that will be covered here. Thanks  -> https://www.section.io/engineering-education/maria-data-base/
