### ISSUE TITLE
PASSWORD ENCRYPTION WITH BCRYPT IN A NODEJS APPLICATION

### ISSUE THREAD

**Issue by Mudia07** [section-engineering-education/engineering-education#3799]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Password Encryption with Bcrypt in A Nodejs Application

### Introduction paragraph (2-3 paragraphs):
Password encryption is the act of scrambling a password in order to make it difficult for hackers to breach and there are a few trusted programs that help with this one of which is Bcrypt. It is important to encrypt passwords as if offers added protection to your application and users in the digital space.

Bcrypt is an inbuilt password hashing program available as a module in Nodejs. It comes with a password salt generator which accepts salt rounds(difficulty level of a generated password hash); note that the higher the rounds, the more time it takes to encrypt the password. A password salt generator is an extra set of characters automatically added to a password before it is hashed or encrypted and stored in a database.

When authenticating a user, Bcrypt has the ability to compare the passwords and retrieve it from the database without the salt that was generated initially. This means that we do not have to store salts in a separate location as the whole process of encrypting and decrypting passwords is entirely handled by Bcrypt.

### Key takeaways: 
1) Understanding the concept of password encryption and salting.
2) The importance of password encryption in an application.
3) How to encrypt passwords with bcrypt in a Nodejs application.

### References: 
https://www.npmjs.com/package/bcrypt

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Mudia07 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Mudia07** [comment]
Okay,thank you very much sir

**Comment by hectorkambow** [comment]
@Mudia07 
Seems like a very cool topic - but regarding Node.js we have more than enough currently in our EngEd library as we did a big push the last few months and are currently not accepting any more Node.js articles to publish for the time being.

Please feel free to suggest an alternate topic to explore.
