### ISSUE TITLE
[Security]Performing A Phishing Attack Using Socialphish

### ISSUE THREAD

**Issue by FINCH285** [section-engineering-education/engineering-education#3803]
### Proposed title of article
How to perform a phishing attack

### Introduction paragraph (2-3 paragraphs):
Phishing is a form of cyber attack used to steal personal credentials from unsuspecting users. A hacker uses a fake website identical to the real one. When a user enters his/her credentials into the fake website, the hacker acquires them. He/she can use these credentials for malicious purposes.

Due to the increase in social media platforms and online services, phishing attacks have increased rapidly. This has raised a concern in the cyber security sector. In this tutorial, we are going to use socialphish to demonstrate how a phishing attack is conducted. It is a free tool available on the internet used in conducting phishing attacks by most cyber criminals.

### Key takeaways: 

- Installing socialphish in Kali Linux.
- Step by step process of using socialphish to perform a phishing attack.
- Ways of preventing a phishing attack from occuring.

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @FINCH285 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
This article is not legal, and black-hat hackers can use it to perform malicious activities.

Please feel free to suggest an alternate topic to explore. 🚀 @FINCH285
