### ISSUE TITLE
[Nodejs] Personalized Node.js Library

### ISSUE THREAD

**Issue by pkalynan** [section-engineering-education/engineering-education#3809]
### Proposed title of article
Create Your Own Personalized Node.js Library

### Introduction paragraph (2-3 paragraphs):

Among several conveniently pre-made Node.js libraries in open-source repositories, has there ever been one that seemed to be unavailable to you? This article provides Node.js users information to create their own customized Node.js library. The library can range from mathematics and statistics to creative activities.

In this case, the purpose is to create a workable package that cannot be found from any available open source website or to find flaws in other pre-made Node.js libraries and develop a robust version. For example, a Node.js library for [image recognition](https://github.com/xc0d3rz/npm-imagerecognition/blob/master/imagerecognition.js) may not be compatible to other packages that can convert images into sequential patterns forming possible alphanumerical values. Instead, the library just extracts content stored and categorized in elements from a specified web code layer, usually in either HTML or CSS. The article provides readers and users alike an opportunity to expand knowledge bases from many tools, including ones that are performed manually and apply them to Node.js codes. 

### Key takeaways: 

* How to create a customized library in Node.js to resolve an issue.
* Write and test a library created in Node.js.
* Apply concepts from various sources and tools into Node.js codes.
* Enjoy the versatility of Node.js.

### References: 

[GitHub Image-Recognition Source Code](https://github.com/xc0d3rz/npm-imagerecognition/blob/master/imagerecognition.js)
[Image-Recognition Node.js NPM Package](https://www.npmjs.com/package/image-recognition)
[Node.js Statistical Functions](https://medium.com/analytics-vidhya/statistical-functions-in-node-js-12303286de4a)
[Node.js Documentation](https://nodejs.org/dist/latest-v14.x/docs/api/)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @pkalynan 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
