### ISSUE TITLE
Generic Constructors and Interfaces in java

### ISSUE THREAD

**Issue by jgesare** [section-engineering-education/engineering-education#3811]
### Proposed title of article
Generic Constructors and Interfaces in java

### Introduction paragraph (2-3 paragraphs):
Generics allow a class or interface to take into account all kinds that are dynamically passed in as input. In this way, you can rest assured that your data is secure. As specify generic class parameters in the same way to instance variables, use angle brackets ">". 
Generic constructors and generic methods are the same. If you're using generic constructors, you'll need to add the type parameter after public and before class. After establishing a generic constructor, constructors can be called with any type of parameter. In a constructor, the newly generated object is initialized by a block of code. It's an instance method that doesn't have a return type. The constructor has the same name as the class.

### Key takeaways: 
- How to implement Constructors and Interfaces in java
- The benefits of Generic Interface
- Uses of generic types
### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @jgesare 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @jgesare 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
