### ISSUE TITLE
Fintech

### ISSUE THREAD

**Issue by eunice-wanjiku** [section-engineering-education/engineering-education#3817]
### Proposed title of article
FinTech

### Introduction paragraph (2-3 paragraphs):
Financial technology entails the incorporation of technology into operations mainly by companies providing financial services. This is with the objective of increasing their purpose and enhancing efficient customer delivery. It has highly diversified its engagement and involved sectors such as retail banking, nonprofit,and education among others. It also entails advancement and utilization of crypto-currencies.  

Generally, Fintech involves the description of various financial based operations such as check depositing, procuring money for business startups, handling investments, money transfers, applying for credit among others without the assistance of an individual. However, there are various issues associated with Fintech as it has grown to have highly diversified services. 

### Key takeaways: 
1. What is Fintech
2. How Fintech is in practice
3. The growth of Fintech
4. Technologies associated with Fintech
5. Fintech Regulation

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Thank you for the topic suggestion @eunice-wanjiku , however this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore.
