### ISSUE TITLE
Java Chained Exceptions

### ISSUE THREAD

**Issue by Bonimum** [section-engineering-education/engineering-education#3821]
### Proposed title of article
Java Chained Exceptions

### Introduction paragraph (2-3 paragraphs):
With `chained exceptions feature`, you can associate another exception with an exception. The second exception accounts the cause of first exception. For instance, imagine a situation in which a method throws an ArithmeticException because of an attempt to divide-by-zero. Nevertheless, the actual cause of problem was that an I/O error occurred, which caused the divisor to be set improperly.

Even though the method must certainly throw an ArithmeticException, since that is the error that occurred, you might want to let the calling code know that the underlying cause was an I/O error. Chained exceptions let you to manage this, and any other situation in which layers of exceptions exist. 

### Key takeaways: 

- What are Chained Exceptions in Java ?
- How to allow Chained Exceptions in Java ?
- Java Chained Exception Example

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, this topics and the key takeaways appear to be well-covered in the official documentation. Feel free to suggest another topic. ```https://docs.oracle.com/javase/tutorial/essential/exceptions/chained.html```
