### ISSUE TITLE
Java Startup Detection of Missing Modules in a Module with Examples

### ISSUE THREAD

**Issue by nmercy21** [section-engineering-education/engineering-education#3824]
### Proposed title of article
Java Startup Detection of Missing Modules in a Module with Examples

### Introduction paragraph (2-3 paragraphs):
A Java module is a packaging mechanism that enables you to package a Java application or Java API as a separate Java module. A Java module is packaged as a modular JAR file. A Java module can specify which of the Java packages it contains that should be visible to other Java modules which use this module. A Java module must also specify which other Java modules is required to do their job.

### Key takeaways: 
By the end of this tutorial, the reader will understand:
- What is a Module
- How to Write Modular Code
- How to create Java Modules
- How to run a Java Module
- Java Module Benefits
### References: 
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by nmercy21** [comment]
Can anyone reopen this for me?
