### ISSUE TITLE
Basic network attacks on a computer network

### ISSUE THREAD

**Issue by Mercycar** [section-engineering-education/engineering-education#3829]
### Proposed title of article
Basic network attacks on a computer network

### Introduction paragraph (2-3 paragraphs):
Nowadays, many people rely on the internet to perform most of their personal, professional and business activities. In contrary most of them are in great danger of network attacks on the internet. 

This article intends to take the reader through the types of attacks on the internet that most of the are likely to face while performing their daily activities on the net.

###Key takeaways
After reading this article, the reading should be able to know the types of networks attacks that occur on computer networks.

The reader should be able know how to prevent himself/ herself from attacks on the internet.

The reader should be able to understand how certain types of attacks on the internet are performed.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Mercycar  

How will this article differ from what is [published on other sites](https://www.google.com/search?q=Basic+network+attacks+on+a+computer+network&ei=Tn9HYcG1F72sqtsPjKKU2AQ&oq=Basic+network+attacks+on+a+computer+network&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEBYQHjIFCAAQhgMyBQgAEIYDMgUIABCGAzIFCAAQhgM6BwgAEEcQsANKBAhBGABQ6J8VWOifFWDroRVoA3ACeACAAVmIAVmSAQExmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwjBlKey04vzAhU9lmoFHQwRBUsQ4dUDCA4&uact=5)

**Comment by Mercycar** [comment]
Hello @hectorkambow, in this article I will be using my networking knowledge that I was taught in school, and perhaps I have a different view in regards to this article that I want to address if it is approved. Thank you, I hope you will consider my opinion.

**Comment by hectorkambow** [comment]
Thank you for the follow up 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

Please feel free to suggest an alternate topic to explore. 🚀
