### ISSUE TITLE
Getting Started with Bash Shell Scripting

### ISSUE THREAD

**Issue by eunice-wanjiku** [section-engineering-education/engineering-education#3830]
### Proposed title of article
Getting Started with Bash Shell Scripting

### Introduction paragraph (2-3 paragraphs):
Bash is a widely available command line interface that is found in different operating systems. It is known to be a default command interpreter that is found on Mac OSX, and GNU or Linux systems. Shell is a macro processor that allows you to run commands interactively or non-interactively while scripting enables for the execution of instructions that would have to be executed individually interactively. This shows that you can be able to process information and retrieve data among other simple and complex operations.

Shell scripts are mainly for systems handling administration tasks such as system logs evaluation, and disk backups among others. They are also required in cases where the programs are complicated and used as installation scripts. The Bash shell script is a program written in a programming language, Bash.  
### Key takeaways: 
1. Basics of Bash shell script
2. What are Bash scripts
3. How Bash shell scripting works
4. How to run a bash shell script

### References: 
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
@eunice-wanjiku Closing this issue since you already have another topic suggest. Thanks

**Comment by eunice-wanjiku** [comment]
@WanjaMIKE Kindly reopen this issue. I no longer have a pending isssue

**Comment by WanjaMIKE** [comment]
What about this one -> https://github.com/section-engineering-education/engineering-education/issues/3665

**Comment by eunice-wanjiku** [comment]
@louisefindlay23 kindly review this issue for me.Thank you
