### ISSUE TITLE
MySQL Database and Java swing desktop Graphical user Interface

### ISSUE THREAD

**Issue by JosephAyoma** [section-engineering-education/engineering-education#3832]
### Proposed title of article
MySQL Database and Java swing desktop Graphical User Interface

### Introduction paragraph (2-3 paragraphs):
Java Swing is suitable for desktop application development. Desktop applications should provide an interface where the user can enter data. Through interaction with the desktop application components, the data should be saved in a database (MySQL) for processing or any other manipulation .i.e. future retrieval.   
In this article, we will get to learn how the Java Swing desktop application can communicate with the MySQL database. We will create a simple application that will be able to demonstrate saving and getting data store in MySQL database.  At the end of the article, the learner will be able to design a simple Java Swing application that can connect to the MySQL database, save data and retrieve data back to the UI. The application will be able to interact with the user whereby the user can provide connection details for MySQL.

### Key takeaways: 
1.	Java swing MySQL Connector
2.	 MySQL creating database and tables
3.	Insert, update and delete data from MySQL database from Java GUI
4.	Java Swing desktop graphical user interface design

### References: 
https://www.javatpoint.com/java-swing

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@JosephAyoma

**Comment by hectorkambow** [comment]
@JosephAyoma 
How will this article differ from what is [published on other sites](https://www.google.com/search?q=MySQL+Database+and+Java+swing+desktop+Graphical+user+Interface&ei=rIBHYaOOD7y4qtsPta-AmAs&oq=MySQL+Database+and+Java+swing+desktop+Graphical+user+Interface&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABQz6MEWM-jBGCzpQRoA3ACeACAAU2IAU2SAQExmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwijlJHZ1IvzAhU8nGoFHbUXALMQ4dUDCA4&uact=5)

**Comment by WanjaMIKE** [comment]
Unfortunately, mysql connector logic is already covered here -> https://www.section.io/engineering-education/java-jdbc/

**Comment by JosephAyoma** [comment]
@hectorkambow in this article, I will discuss how to connect to MySQL from a graphical user interface designed in Java Swing. Unlike in the article cited by @WanjaMIKE my article will demonstrate how to get connection string from graphical user interface, save the connection string in a file and retrieve them for connection purposes. This makes it easier to manager desktop application MySQL database connection from a GUI platform. 

I will be able to give a flowing example demonstration and a complete application which can be run outside IDE to demonstrate the concept fully.

I seek for your advice on the issue.

**Comment by JosephAyoma** [comment]
@WanjaMIKE  @hectorkambow I am patiently waiting for your guidance and advice on this issue, could it be opened and approved that I may do that article based on my previous comment? Please advise and I stand guided.
