### ISSUE TITLE
How To Create Custom Eslint Rules

### ISSUE THREAD

**Issue by Babatunde13** [section-engineering-education/engineering-education#3833]
### Introduction paragraph (2-3 paragraphs):
ESLint is a static code analysis tool for identifying problematic patterns found in JavaScript code and can also be used to fix them. Nicholas C. Zakas created it in 2013. Rules in ESLint are configurable, and customized rules can be defined and loaded. Eslint rules save us(the developers) from syntax errors, and it also allows developers working on a group project to enforce a code style. 

### Key takeaways: 
1. What is eslint
2. What are eslint rules
3. How to use eslint
4. Understanding and exploring AST
5. How to create and use your own custom eslint rules

### References: 
1. [eslint](https://eslint.org/)
2. [eslint rules](https://eslint.org/docs/rules/)
3. [AST explorer](https://astexplorer.net/)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Babatunde13 
How will this article differ from what is [published on other sites](https://www.google.com/search?q=How+To+Create+Custom+Eslint+Rules&ei=9IBHYeX2JIemqtsPhdiPyAI&oq=How+To+Create+Custom+Eslint+Rules&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEBYQHjoHCAAQRxCwA0oECEEYAFCg5RBYoOUQYJvnEGgCcAJ4AIABXIgBXJIBATGYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz&ved=0ahUKEwjlwNH71IvzAhUHk2oFHQXsAykQ4dUDCA4&uact=5)

**Comment by Babatunde13** [comment]
@hectorkambow So most articles if not all articles on this do not explain how to write unit test for `eslint` rules. So this article will include unit testing using `mocha`

**Comment by WanjaMIKE** [comment]
I think most of the takeaways in your topic suggestion will coincide with this article. Feel free to suggest another topic. Thanks
 ```https://www.section.io/engineering-education/node-eslint/```
