### ISSUE TITLE
The Builder Pattern in java

### ISSUE THREAD

**Issue by Wambuajuma** [section-engineering-education/engineering-education#3834]
### Proposed title of article
The Builder Pattern in java

### Introduction paragraph (2-3 paragraphs):
Among Erich Gamma and colleagues' 23 Gang of Four (GoF) design patterns, the Builder pattern is a step-by-step construction design pattern that enables you build complicated objects. Using the same construction code, you can create a variety of distinct types and representations of a single product. While it's possible to build distinct immutable objects using the same process, it's not recommended.
The Builder design differs only slightly from the Abstract Factory pattern, another significant GoF creational structure. Building an object from scratch is a focus of Builder pattern, while Abstract Factory pattern is focused on creating a family of Product objects.The Abstract Factory design returns the finished Product immediately, but the Builder pattern returns it as a last step.

Despite the fact that design patterns are language agnostic, their implementation changes based on the properties of each language, making some patterns obsolete.
### Key takeaways: 
- The Pattern
- Solving too many constructor arguments. 
- Solving incorrect object state. 

### References: 
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Wambuajuma 
How will this article differ from [what is published on other sites](https://www.google.com/search?q=The+Builder+Pattern+in+java&ei=CYJHYajuMZ2zqtsP47WpwAI&oq=The+Builder+Pattern+in+java&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BwgAEEcQsANKBAhBGABQ0ZUDWNGVA2CllwNoAnACeACAAVCIAVCSAQExmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwjolun_1YvzAhWdmWoFHeNaCigQ4dUDCA4&uact=5)

**Comment by ahmadmardeni1** [comment]
I'm going to close this PR to clear the queue. @Wambuajuma 
It can be reopened.
