### ISSUE TITLE
Documenting your REST API's in Go using Swagger

### ISSUE THREAD

**Issue by MahanteshR** [section-engineering-education/engineering-education#3838]
### Proposed title of article
Documenting your REST API's in Go using Swagger

### Introduction paragraph (2-3 paragraphs):. 
In today's modern digital era, APIs are the glue of these digital platforms. They enable the expansion of a platform by adding more users and services to the existing one. It is the developer's responsibility to enable these new services, but not only that; the developer has to maintain documentation as part of good practice so that it is easy for new developers to get started with the developments quickly. 

This tutorial will document the RESTful services that we wrote in our previous tutorial(Building RESTful in Go using an idiomatic approach).

API Documentation is a technical handbook containing all the information about using and integrating with an API. It contains all the information required to work with an API, including the method type, classes, arguments etc. 

### Key takeaways: 
* The significance of API documentation.
* Overview about swagger
* Implement swagger in Go

### References: 
https://github.com/go-swagger/go-swagger

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@MahanteshR 
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
