### ISSUE TITLE
Uncovering WiFi Passwords From Windows 

### ISSUE THREAD

**Issue by LucidRay** [section-engineering-education/engineering-education#3839]
### Proposed title of article
Uncovering WiFi Passwords From Windows

### Introduction paragraph (2-3 paragraphs):

In windows Wi-Fi passwords from saved Wi-Fi networks are hidden from the user, unlike other OS i.e. android, windows has terminals that can be used to acquire the Wi-Fi passwords from the saved Wi-Fi networks in the device.
With the use of PowerShell and cmd (also known as command prompt) we can be able to find the hidden Wi-Fi passwords by using simple cmd and PowerShell commands. This will enable users to use the passwords to connect other devices to the same Wi-Fi networks.

### Key takeaways: 
What is PowerShell?
What is cmd?
Which Windows versions have PowerShell installed?
Steps to find the WiFi password using cmd
Steps to find the WiFi password using PowerShell

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
👋  Good afternoon @LucidRay seems like a helpful topic. 

Yet before we can approved the topic - we'd like to flush out how will this article differ from [what is published on other sites](https://www.google.com/search?q=Uncovering+WiFi+Passwords+From+Windows&ei=GoNHYc2dLIOoqtsPjreGkAc&oq=Uncovering+WiFi+Passwords+From+Windows&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBQgAEIYDMgUIABCGAzoHCAAQRxCwA0oECEEYAFCJoANYiaADYKihA2gCcAJ4AIABX4gBX5IBATGYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz&ved=0ahUKEwjNkvqB14vzAhUDlGoFHY6bAXIQ4dUDCA4&uact=5)

**Comment by LucidRay** [comment]
Unlike those articles, my article will involve using of terminals like cmd and window powershell to uncover/find wifi passwords of saved networks and it will not only include windows 10 but alalmost all window versions.

**Comment by LucidRay** [comment]
Unlike those articles, my article will involve using of terminals like cmd and window powershell to uncover/find wifi passwords of saved networks and it will not only include windows 10 but alalmost all window versions.

**Comment by LucidRay** [comment]
Unlike those articles, my article will involve using terminals like cmd and window PowerShell to uncover/find wifi passwords of saved networks and it will not only include windows 10 but also almost all Windows versions.

**Comment by hectorkambow** [comment]
@LucidRay 
Sounds like a helpful topic - lets please be sure it adds v**alue beyond what is in any official docs and/or what is covered in other blog sites.** (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
