### ISSUE TITLE
Introducing Bring Your Own Key(BYOk) in your systems

### ISSUE THREAD

**Issue by ROYFORDWANYOIKE2001** [section-engineering-education/engineering-education#3840]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Introducing Bring Your Own Key(BYOk) in your systems
### Introduction paragraph (2-3 paragraphs):
Data integrity forms a crucial thing in an enterprise and incase of compromisation an organization feels like it back to start line again. Data breach has become a vital and daily talk in the current world with hackers leaking alot of data. This is all because weka encryption or even unsecured data which ends up on unsafe hands. From the launch of Bring Your Own Key technique the organizations and other premises will be in a position to generate and have authority over the entire key and sharing process. using devices which are well off and tamper resistant will be the only way to strengthen the security. These devices will work on a principle of hardware security module which will help keep track of the secure export of all keys generated. For a safer data store consider implementing Bring Your Own Key where you will be the pilot.

### Key takeaways: 

1. Data security and integrity is a crucial thing in an organization which proves the genuinity of data stored.
2. Breaching of data can result to loss of income and also lose of clients due to lack of enough trust. 
3. Bring Your Own Key is a topology which is controled from personal level and has no third party outside the organization operating to store the data.

### References: 
Ulz, T., Pieber, T., Steger, C., Haas, S., Bock, H., & Matischek, R. (2017, March). Bring your own key for the industrial Internet of Things. In 2017 IEEE International Conference on Industrial Technology (ICIT) (pp. 1430-1435). IEEE.
`https://cpl.thalesgroup.com/encryption/key-management`

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ROYFORDWANYOIKE2001** [comment]
Hello, thank you for letting me know. Am glad.

**Comment by louisefindlay23** [comment]
Hi, @ROYFORDWANYOIKE2001. How does your proposed article differ from existing articles on this topic such as [this one](https://id-3.co.uk/blog/2019/04/09/bring-your-own-key-what-is-it-and-what-are-its-benefits/) and those [listed here](https://id-3.co.uk/blog/2019/04/09/bring-your-own-key-what-is-it-and-what-are-its-benefits/)?

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by ROYFORDWANYOIKE2001** [comment]
@hectorkambow @ahmadmardeni1 Hello my pull request is ready, kindly reopen my issue. Thank you
