### ISSUE TITLE
Shifting to a world of Wireless Sensing

### ISSUE THREAD

**Issue by Alex-Githinji** [section-engineering-education/engineering-education#3843]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
 ***Shifting to a world of Wireless Sensing***

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

### Introduction paragraph (2-3 paragraphs):
The launch of computers was accompanied by the urge to transfer and store data. Computer being a device which allows input of data through various components like keyboard, mouse and also touchpad has to process the data collected. Using the central processing unit the computer converts the data to the required format and then generates it as output. How do you share the data?
Initially, sharing of data began with wired transfer. However the growth of technology has ended up with launch of several wireless means to transfer data. from transfer now sensing has become one of the best part of data transmission with networking and Internet of Things coming together for rescue. This article will be explaining how the two have contributed to the growth of a wireless sensing world.

### Key takeaways: 

1. What is Internet of Thing and how does it operate?
2. How is data transfered wireless?
3. How can sensors be integrated to collect data and share it wireless to the desired destination?

### References: 
Zhang, R., Jing, X., Wu, S., Jiang, C., Mu, J., & Yu, F. R. (2020). Device-free wireless sensing for human detection: the deep learning perspective. IEEE Internet of Things Journal, 8(4), 2517-2539.
Gupta, A., Girerd, C., Dunna, M., Zhang, Q., Subarraman, R., Morimoto, T., & Bharadia, D. (2020). Wi-chlorian: Wireless sensing and localization of contact forces on a space continuum. arXiv preprint arXiv:2012.15412.
`https://www.hindawi.com/journals/js/2020/9592836/`

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Unfortunately, we have numerous articles covering Internet of Things. Feel free to suggest another topic. Thanks

https://www.section.io/engineering-education/search/?q=iot
