### ISSUE TITLE
Choosing the best Linux Distro for your machine

### ISSUE THREAD

**Issue by tiffy-keshie** [section-engineering-education/engineering-education#3844]
### Proposed title of article

[Security] **Choosing the best Linux Distro for your machine**

### Introduction paragraph (2-3 paragraphs):

Choosing the wrong operating system can give one a headache. Have you ever kept on changing operating system simply because they do not grant you the priviledges you feel need acquinted to? Many people assume that linux distros are for hacking  purposes and forget some do not even contain the cybersecurity tools. Some distros are meant to only facilitate software development needs while others act as servers and only few majorly concern on cybersecurity. Many developers end up choosing wrong distros only to uninstall and select another. This article will be a close view of what linux operating systems do and what level of need they will end up making one to install. answers to these and many more questions will be tackled and definite solutions granted.
### Key takeaways: 

- what is linux?
- Which role do you want to play with the linux distro you want to install?
- How to install the operating system to fit to the needs.

### References: 
Castro, J. D. (2016). Linux Distro Selection Criteria. In Introducing Linux Distros (pp. 17-32). Apress, Berkeley, CA.
Ambaka, P. (2021). Best Linux Distro To Run From USB.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @tiffy-keshie. This is a widely popular topic that has been covered extensively elsewhere. We focus on publishing unique and original content so how will you take be unique and different?

**Comment by Alex-Githinji** [comment]
Hi @louisefindlay23 i will be giving a broad understanding on which operating system can be suitable especially for developers who get stuck in chosing one. I have encountered situations where most of the OS freeze while running applications android studio. Others are penetration tester and still using operating systems like Ubuntu. Moreover, there are some who want to know why use KDE and not XFCE. i will be helping to distinguish between the two. Thank you for the great question

**Comment by hectorkambow** [comment]
Is there a way to flush out more from the topic than what is available via other sites? Can we take a developer-centric approach?

**Comment by Alex-Githinji** [comment]
Hello how about the tools available for instance the terminal centric which gives developers a good platform to interact with and learn more from it.
