### ISSUE TITLE
How to create a responsive React navigation bar using PrimeReact

### ISSUE THREAD

**Issue by Geraldoeze** [section-engineering-education/engineering-education#3847]
**Proposed title of article**

   How to create a responsive React navigation bar using PrimeReact.

**Introduction paragraph:**

  React.js is one of the most common JavaScript library used for building client-side rendering websites. This allows developers to make their website entirely rendered in the browser with JavaScript. 

   In this article, we will create a responsive React navigation bar using PrimeReact, which is a UI component library for React.js.

**Key takeaways:**
 
1.  What is PrimeReact.
2.  How to add PrimeReact library to react.js project.
3.  How to import and use PrimeReact components.
4.  How to make our navigation bar responsive using PrimeReact.

**References:**
N/A

**Comment by WanjaMIKE** [comment]
Topic approved. Let's ensure that it adds value to the community. Thanks

**Comment by Geraldoeze** [comment]
Thank you 
I'll ensure it does
