### ISSUE TITLE
[Languages] Handling NullPointer Exception in Java

### ISSUE THREAD

**Issue by neheMaish** [section-engineering-education/engineering-education#3849]
### Proposed title of article
[Java] Handling NullPointer Exception in Java

### Introduction paragraph (2-3 paragraphs):
Any time an application uses an object reference which has no value, NullPointerException is thrown. Null references can be used in methods, for example. Any attempt to use an object reference that has the null value results in NullPointerException... Use array-like methods to access and modify the slots of the null object. You can throw the value "null" as a Throwable value. A null object is synchronized with.

After understanding that, one have to handle or even stop the NullPointerException and it can be done in several ways.
1. Use valueOf() instead of toString() ; and both return the same result.
2. Use equals() and equalsIgnoreCase() method with String literal instead of using it on the unknown object that can be null.
3. Use Java annotation @NotNull and @Nullable.

In this article, we are going to see how NullPointerException is handled in Java
 

### Key takeaways: 

1. Lombok Null Check.
2. Lists and Nulls
3. Maps and Nulls

### References: 
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @neheMaish 
This sounds like an interesting and informative article. Please ensure you provide more original content and that your article does not conflict with articles already published in eng-ed. For instance, [this article](https://www.section.io/engineering-education/exception-handling-in-java/) already addresses exception handling in Java.

topic approved :rocket:
