### ISSUE TITLE
How to create a stopwatch in javascript

### ISSUE THREAD

**Issue by iankamau20** [section-engineering-education/engineering-education#3850]
### Proposed title of article

How to create a stopwatch in javascript

### Introduction paragraph (2-3 paragraphs):

In this article i will be explaining how to create stopwatch from scratch using javascript, html and css.I will also explain how to align and center elements using css, which a bit challanging to beginners.
This article is for beginner or intermidiate who what to have better understanding of javascript events,function and conditionals.

### Key takeaways: 
1.click event in javascript
2.basic css styling
3.javascript conditional
4.javascript function

### References: 
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @iankamau20 

I did a direct search of this suggestion on the browser and I got a lot of articles, videos, and StackOverflow questions. So I was wondering if it really provides enough material that hasn't been done before.

**Comment by iankamau20** [comment]
Hello!  Yes, I am including css styling and JavaScript conditional which
are not implemented in most articles.Also I will explain different events
other than click event, which can  trigger the stopwatch.
I intend to make my article easier to understand since I will  include
documentation explaining what is happening at each line of code.

Thank you!

**Comment by LinusMuema** [comment]
Hi @iankamau20 
After several inquiries and research, we have decided that the article would not provide enough content that hasn't already been published. There was just a lot on the internet that has the same exact content.
We also have [another](https://www.section.io/engineering-education/how-to-build-a-clock-with-javascript-and-svg/) article that seems to have a similar topic and technologies as yours so we felt it did not provide enough "new" material.
We hope you understand.
