### ISSUE TITLE
Linear and Binary Search in Java Data Structures and Algorithms.

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#3851]
### Introduction 
In the world of programming languages, data structures and algorithms are key problem-solving skills that all engineers must-have. Linear and Binary Search are required when there is a problem with sorted arrays in Java or any other language. So, in this article, I will be sharing the ways of utilizing the methods in interview questions.

### Key takeaways: 
In the end, readers would have knowledge of the following concepts;

1. what are data structures and algorithms in Java.
2. when and how to use linear search.
3. concepts of binary search in sorted java arrays problems.
4. solutions to interview questions provided from Leetcode.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Horlawhumy-dev** [comment]
Yes sir.

**Comment by LinusMuema** [comment]
Hi @Horlawhumy-dev 
This sounds like a good DSA article and I have no doubt it would be super helpful. Please make sure to provide more content that is original. There are many DSA articles on the web like [this one](https://www.programiz.com/dsa/linear-search) so please keep that in mind. Also check that it does not conflict with content already on section.

**Comment by Horlawhumy-dev** [comment]
Sure and I am promising to make it quite a helpful DSA article.
