### ISSUE TITLE
[languages]Advanced Concepts of Programming using Dart

### ISSUE THREAD

**Issue by Eze4Manuel** [section-engineering-education/engineering-education#3853]
[languages]Advanced Concepts of Programming using Dart

### Key takeaways: 
- In-depth grasp of concepts like classes, objects, polymorphism, abstraction, encapsulation, inheritance, Access modifiers, static classes, e.t.c
- Appreciation of the concepts of object-oriented programming using dart
- See how feasible to pick up dart programming language coming from a Java background or a JavaScript background
-  Detailed concentrated coding tutorial sessions showing examples of all the concepts

### References: 
- https://dart.dev/guides/libraries
- https://dart.dev/guides/language/language-tour
- https://dart.dev/guides/libraries/library-tour

**Comment by WanjaMIKE** [comment]
@Eze4Manuel am closing this issue since it appears you have another open PR. Thanks
