### ISSUE TITLE
 [Languages] Paytime loading effect from scratch 

### ISSUE THREAD

**Issue by phinaomondi** [section-engineering-education/engineering-education#3862]
### Proposed title of the article
[Languages] Paytime loading effect from scratch 

### Introduction paragraph (2-3 paragraphs):
Most websites lack the loading effect that captures the user's attention while the components of the website are being loaded. However, according to modern conventions, loading effects are more than just animations. They are meant to communicate to the user information about the site and get in line with the website's content.

Modern websites use pre-made gifs for their loading effects which might be less subjected to customization. For this reason, this article gives the reader a stepwise implementation of a loading effect/gif from scratch. According to a website's theme, the reader will have the drive to make customizations and colour scheme changes. In the implementation, we will build a pay time loading effect from scratch and test it in a web browser.

### Key takeaways: 
1. Understanding the working of loading effects in websites
2. Building a website loader from scratch
3. Customization of a loader to suit the websites theme colours

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by phinaomondi** [comment]
I am done with the article. Would you please open this for me?

@WanjaMIKE 
@ahmadmardeni1 
@jerimkaura

**Comment by WanjaMIKE** [comment]
Reopened
