### ISSUE TITLE
How to Build a Responsive Image Carousel in React 

### ISSUE THREAD

**Issue by kimanikevin254** [section-engineering-education/engineering-education#3864]
### How to Build a Responsive Carousel in React 
An image carousel is a slideshow of images that helps improve the user's experience of a website. The slideshow can be automated(where the transition from one image to another is controlled by timers), controlled by a click of buttons, or a combination of both.

In this article, we will cover how we can create the image carousel in React and style it with CSS to make our website more interactive improve the user experience.

### Prerequisites: 
To follow along in this tutorial, you need to have:
- Basic CSS knowledge
- Basic React Knowledge

**Comment by louisefindlay23** [comment]
Hi, @kimanikevin254. Thanks for submitting your topic suggestion. Can you tell me how it will differ from similar tutorials such as [this one]()?

**Comment by kimanikevin254** [comment]
Hello, @louisefindlay23 
I hadn't come across the referenced article. It seems to cover almost everything I had in mind.

What I would have done differently is to:
- Use **class components** instead of the functional components.
- Use Tailwind CSS for styling which would help the reader to get started with React and Tailwind.
- Add media queries so that the slide functionality is only available is small screens and on larger screens, there are buttons to help in navigation.
- Add slides autoplay, pause autoplay on mouse hover.
- Use a different npm package for the swiping functionality.
- Make it more appealing to the user by adding animations.

Does that make it unique?

**Comment by louisefindlay23** [comment]
Yes, thanks, @kimanikevin254 for the detailed explanation. Topic approved 🚀. Be sure to cover these unique points in plenty of detail to add extra value for our readers.

**Comment by kimanikevin254** [comment]
Thanks. I sure will
