### ISSUE TITLE
How to Create a REST API Using Golang and MongoDB 

### ISSUE THREAD

**Issue by KayveTech** [section-engineering-education/engineering-education#3867]
### How to Create a REST API Using Golang and MongoDB 
GoLang is an open-source, compiled programming language that makes it easy for developers to create simple, powerful, reliable, and efficient applications. Golang is syntactically similar to C but with memory safety and garbage collection.

After developing your application with Go, you might need a database to store data. One of the databases you can use is MongoDB which is a cross-platform NoSQL database. This tutorial will guide the reader on how to create a REST API using Golang and MongoDB.

### Prerequisites: 
- Basic Golang knowledge
- Basic understanding of MongoDB.
- What a REST API is.

### Key takeaways: 
- How to create a REST API using Golang and MongoDB.

**Comment by louisefindlay23** [comment]
Hi, @KayveTech. Thanks for submitting your topic suggestion. How will it differ from similar articles such as this [one](https://betterprogramming.pub/building-a-restful-api-with-go-and-mongodb-93e59cbbee88) or in the [list](https://www.google.com/search?client=firefox-b-d&q=How+to+Create+a+REST+API+Using+Golang+and+MongoDB)?
