### ISSUE TITLE
Java timer Tasks

### ISSUE THREAD

**Issue by Joesongoma** [section-engineering-education/engineering-education#3868]
### Proposed title of article
Java Timer Tasks

### Introduction paragraph (2-3 paragraphs):
Java Programing language Timer Class provides a facility for the threads to be able to schedule tasks for future execution. Timer tasks are the tasks that can be scheduled for a one time or repeated execution by the time in the future.

In this tutorial we shall be looking at an example to schedule a timer to execute a task at a given time. We shall also look at Timer Task Methods and how they are used in program codes. 

### Key takeaways: 
After reading this tutorial,  the reader should be able to know and understand what timers are and timer tasks do.
The reader should be able to understand Timer Task Methods and be able to use them in a program.
The reader should be able to write a program that schedules a task for future execution.

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Joesongoma** [comment]
Hello @hectorkambow , thank you for the question. In my tutorial I will put all the knowledge about Java Timer Tasks together since in other websites it is covered only in bits making someone someone to search from more than one site to get what he /she needs. Again in my tutorial I will create a google calendar like example program that reminds someone that it is time to do what he/she wanted to do. My code example will be unique from the others and it will take through a step by step procedure on how he/she can create his/ her own schedule reminder. I think this makes it unique. Thank you.

**Comment by Joesongoma** [comment]
@ahmadmardeni1 
Hello, I suggested a topic 16 days and answered the question asked but my topic has not been looked at. Please help. Thank you.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Joesongoma 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
closed #3868 via #4227
