### ISSUE TITLE
[Android] Java vs Kotlin for Android

### ISSUE THREAD

**Issue by vifabulous** [section-engineering-education/engineering-education#3870]
### Introduction paragraph (2-3 paragraphs):
 Java is a reputable programming language with vast open source tools and libraries to help developers.
On the other hand, Kotlin is an expressive and concise programming language that reduces common errors.

New Android developers want to know which language they should learn for building modern Android applications. Development teams want to be sure that Kotlin will not have a negative impact on their app’s performance, their ability to hire qualified engineers, or on their overall developer productivity.

### Key takeaways: 
1. Requirements/installations
2. Differences/comparison
3. Performance and compatibility
4. Syntax
5. Best choice for beginners

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic is already covered here `https://www.section.io/engineering-education/difference-between-kotlin-and-java/`. Feel free to suggest another topic. Thanks
