### ISSUE TITLE
[Languages] Explaining Priority Queues in Java with Examples

### ISSUE THREAD

**Issue by mukono10** [section-engineering-education/engineering-education#3877]
### Proposed title of article
[Languages] Explaining Priority Queues in Java with Examples

### Introduction paragraph (2-3 paragraphs):
Priority queues in Java are special types of queues in which all elements are ordered according to their natural ordering or according to a custom Comparator specified at the time of construction.  As a result, when you remove an element from the priority queue, the least element according to the provided ordering is removed first.

It's utilized in data compression methods like Huffman code.  Priority queues are used to select the next process to run, ensuring that high-priority activities are executed before low-priority ones. As well as load balancing and interrupt handling, it is also used in this way.

When it comes to real-world applications, priority queues are fairly common. How to use priority queues in Java is explained in this article.
### Key takeaways: 
1. Priority queue with Java objects.
2. Priority queues with natural ordering.
3.  Having a custom ordering.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Could you please expand upon how your content will differ from what is already available through the [other websites](https://www.google.com/search?q=%5BLanguages%5D+Explaining+Priority+Queues+in+Java+with+Examples+%233877&ei=tvBRYfLJEP_O0PEPkdSw4Ao&oq=%5BLanguages%5D+Explaining+Priority+Queues+in+Java+with+Examples+%233877&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABQw5cwWMOXMGDmmDBoA3ACeACAAWCIAWCSAQExmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwjy_OT5yJ_zAhV_JzQIHREqDKwQ4dUDCA8&uact=5) and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

@mukono10

**Comment by mukono10** [comment]
Thanks @hectorkambow  for the question. What I shall be covering in this article is that first I will define what a priority queue in Java entails and then I will have to cover the priority queues that have got natural ordering with well-explained samples so that it may be understood better, then I will go a step further covering the priority queues with Java objects accompanied by well-explained examples

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @mukono10 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
