### ISSUE TITLE
Architecturing a flutter application with MobX state manager

### ISSUE THREAD

**Issue by faithsiaji** [section-engineering-education/engineering-education#3878]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Architecturing a flutter application with Mobx state manager
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*
**Use the following format as the title of the issue: [Category of Topic] Title for the article.**

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

### Introduction paragraph (2-3 paragraphs):
MobX is a scalable library developed to ease the process of state management in frontend applications. In the course of the article, the reader will learn how to manage the state of a Flutter applications using MobX.

Using MobX for managing state management in Flutter apps utilizes three of the library’s main concepts - the observable state, actions, and computed values. By the end of the tutorial, the reader shall have created a todo application that saves data to firebase firestore and state managed by MobX.

### Key takeaways: 
1. Integrating flutter application with firebase firestore.
2. Flutter application state management with MobX.

### References: 
[Flutter fire](https://firebase.flutter.dev/docs/overview/)
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or [what is covered in other blog sites](https://www.google.com/search?q=Architecturing+a+flutter+application+with+MobX+state+manager&ei=zvNRYePIPJ2S0PEP4LSeyAk&oq=Architecturing+a+flutter+application+with+MobX+state+manager&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABQwV5YnGxg4W5oA3ACeACAAXmIAZEFkgEDNi4xmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwjj5-Tzy5_zAhUdCTQIHWCaB5kQ4dUDCA8&uact=5). (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
