### ISSUE TITLE
How to Use map() Method to Iterate Through Elements in an Array in JavaScript

### ISSUE THREAD

**Issue by IsaacMuthini** [section-engineering-education/engineering-education#3886]
### Proposed title of article
How to Use map() Method to Iterate Through Elements in an Array in JavaScript

### Introduction paragraph (2-3 paragraphs):
 In JavaScript, the built-in array method `Array.prototype.map()` is used to iterate across the items of an array collection.
 This article is for you if you are a newbie who is having trouble understanding how to utilize the map() method or what it does.
I'll describe the map() method and show how it works with some easy examples in this article.

### Key takeaways: 
After going through this article the learner will understand how:
- The map() Method Works in JavaScript
- To Use the map() method 
- To Use the Index Argument
- To Multiply All Items in the Array by 2
- To Round to the Nearest Integer
- To Change Strings to Numbers
- To Separate Out a Function
- The Array Argument Works

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@IsaacMuthini 
 
We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites](https://www.google.com/search?q=How+to+Use+map%28%29+Method+to+Iterate+Through+Elements+in+an+Array+in+JavaScript&ei=ZvlRYYv_B8mx0PEP9bKG2As&oq=How+to+Use+map%28%29+Method+to+Iterate+Through+Elements+in+an+Array+in+JavaScript&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABQ88QRWPPEEWDjxhFoA3ACeACAAV-IAV-SAQExmAEAoAECoAEByAEGwAEB&sclient=gws-wiz&ved=0ahUKEwiLypqe0Z_zAhXJGDQIHXWZAbsQ4dUDCA8&uact=5).

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @IsaacMuthini 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
