### ISSUE TITLE
 Execution Context and Hoisting in Vanilla JavaScript

### ISSUE THREAD

**Issue by Vanessa-Karimi** [section-engineering-education/engineering-education#3887]
### Proposed title of article
 Execution Context and Hoisting in Vanilla JavaScript

### Introduction paragraph (2-3 paragraphs):
In comparison to many of its competitors, JavaScript is a simple to learn programming language. However, if you want to understand, debug, and write better code, you'll need to pay a little more attention to a few basic ideas.
We will learn about two of these principles in this essay.
- Hoisting
- Context of Execution
### Key takeaways: 
The following are the main things a learner will understand from this article:
- Execution Context in JavaScript
- Global Execution Context (GEC) in JavaScript
- Function Execution Context (FEC) in JavaScript
- Hoisting in JavaScript

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Vanessa-Karimi 
 
We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites](https://www.google.com/search?q=Execution+Context+and+Hoisting+in+Vanilla+JavaScript&ei=h_pRYareGP_O0PEPkdSw4Ao&oq=Execution+Context+and+Hoisting+in+Vanilla+JavaScript&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKsCOgcIABBHELADSgQIQRgAUInlCFiJ5Qhgq-gIaANwAngAgAGGAYgBhgGSAQMwLjGYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz&ved=0ahUKEwjqvZKo0p_zAhV_JzQIHREqDKwQ4dUDCA8&uact=5).

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by ahmadmardeni1** [comment]
I'm going to close this PR to clear the queue. @Vanessa-Karimi
It can be reopened.
