### ISSUE TITLE
[Blockchain] Double-Edged Sword: Cryptocurrency both as an Enabler and a Solution to Ransomware

### ISSUE THREAD

**Issue by BashiirIsla** [section-engineering-education/engineering-education#3890]
### Proposed title of article
Double-Edged Sword: Cryptocurrency both as an Enabler and a Solution to Ransomware

### Introduction paragraph (2-3 paragraphs):
Ransomware continues to emerge in a big way amid information security specialists’ warnings about this problem for years. The presence of newer malware enablers is only making matters worse. Cryptocurrency is one of such factors contributing to increasing ransomware popularity.   

A number of players in the tech industry propose banning cryptocurrency use to mitigate these attacks. However, banning crypto may not work. Luckily, there are steps that we can take to limit the spread of ransomware attacks enabled by cryptocurrency usage.

### Key takeaways: 

1. The ransomware problem with Crypto
2. Cryptocurrency Mining Malware
3. Cryptocurrency as a solution to ransomware

 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@BashiirIsla 
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or [what is covered in other blog sites](https://www.google.com/search?q=Double-Edged+Sword%3A+Cryptocurrency+both+as+an+Enabler+and+a+Solution+to+Ransomware&ei=rvZRYa-qM6PB7gKPgpDoDQ&oq=Double-Edged+Sword%3A+Cryptocurrency+both+as+an+Enabler+and+a+Solution+to+Ransomware&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABQutoaWLraGmCX3BpoAnACeACAAVeIAVeSAQExmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwivudXSzp_zAhWjoFsKHQ8BBN0Q4dUDCA8&uact=5). (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
