### ISSUE TITLE
Stream Filter in Java using Lambda Expressions

### ISSUE THREAD

**Issue by carowanjiku** [section-engineering-education/engineering-education#3891]
### Proposed title of article
Stream Filter in Java using Lambda Expressions

### Introduction paragraph (2-3 paragraphs):

The filter() function in the Java stream allows you to filter stream elements based on a provided criterion. This method accepts a predicate as a parameter and returns a stream of resulting elements as a result.

 In this tutorial, we will look at how to use the Stream. filter() function in Java when working with Streams. We will look at how to utilize it and how to deal with checked exceptions in specific instances and lambda expressions. 

### Key takeaways: 
The reader will learn the following concepts:

- Overview of Stream Filter in java.
- How we use Stream.filter().
- Collection filtering.
- Using Multiple criterial to filter collection.
- Ways of handling exception.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
@carowanjiku Unfortunately, we can only suggest one topic at a time. Thanks
