### ISSUE TITLE
MultiDimensional And Jagged Arrays In C#

### ISSUE THREAD

**Issue by mutheu21** [section-engineering-education/engineering-education#3893]
### Proposed title of article
MultiDimensional And Jagged Arrays In C#

### Introduction paragraph (2-3 paragraphs):
In this tutorial, I will focus on explaining Multidimensional Arrays and Jagged Arrays in C# moreso with examples. Multidimensional arrays are also referred to as Rectangular Arrays.
Multi-dimensional array stores data in the tabular format while jagged arrays are used to store arrays instead of other data types.

### Key takeaways: 
By the end of this tutorial the learner will understand:
- C# Multi-Dimensional Arrays
- 2-Dimensional Arrays
- Jagged Arrays In C#
- Jagged Array Declaration
- Filling Element Inside Jagged Array
- Retrieve Data From A Jagged Array

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@mutheu21 
 
We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites](https://www.google.com/search?q=MultiDimensional+And+Jagged+Arrays+In+C%23&ei=Z_hRYYbuO__O0PEPkdSw4Ao&oq=MultiDimensional+And+Jagged+Arrays+In+C%23&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BwgAEEcQsANKBAhBGABQhMIKWITCCmCNxApoAnACeACAAViIAViSAQExmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwjGvYKl0J_zAhV_JzQIHREqDKwQ4dUDCA8&uact=5).

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by ahmadmardeni1** [comment]
I'm going to close this PR to clear the queue. @mutheu21
It can be reopened.
