### ISSUE TITLE
Implementing a parallel Sieve of Eratosthenes in C and exploring basic concepts of MPI

### ISSUE THREAD

**Issue by csamuelsm** [section-engineering-education/engineering-education#3895]
### Proposed title of article
*Implementing a parallel Sieve of Eratosthenes in C and exploring basic concepts of MPI*

### Introduction paragraph (2-3 paragraphs):
MPI stands for Message Passing Interface. It’s exactly what it says: it defines the syntax and semantics of several routines of message passing that users of several languages are able to use. But what messages? From who? To whom? Well, the messages are the data, transmitted between processes, in order to execute a task in parallel using that data. Thus, MPI is a pattern of data communication for parallel computing.

For this article, we are going to use the Open MPI implementation for C. But first, we need to choose a suitable algorithm for a parallel implementation. There are several algorithms that we can implement. In this article, we are going to implement the Sieve of Eratosthenes because:

- It’s simple to understand and implement;
- It’s good to parallelize and we can clearly see the effects of parallelization with a large number of elements.

### Key takeaways: 

- Understanding what MPI is;
- Understanding the concepts of Ranks, Messages, and the basics of MPI routines;
- Parallelizing an algorithm using Open MPI in C;
- Measures of Speed Up and Efficiency for a parallel algorithm.

### References: 

- [Open MPI: Open Source High Performance Computing](https://www.open-mpi.org/)
- [Message Passing Interface - Wikipedia](https://en.wikipedia.org/wiki/Message_Passing_Interface)
- [Sieve of Eratosthenes - Wikipedia](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

### Templates to use as guides

- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@csamuelsm 

 
We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites.](https://www.google.com/search?q=Implementing+a+parallel+Sieve+of+Eratosthenes+in+C+and+exploring+basic+concepts+of+MPI&ei=F_lRYa_yJs_F0PEPwpmsgAI&oq=Implementing+a+parallel+Sieve+of+Eratosthenes+in+C+and+exploring+basic+concepts+of+MPI&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABQ7MkEWOzJBGCJywRoAnACeACAAVCIAVCSAQExmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwjv2eP40J_zAhXPIjQIHcIMCyAQ4dUDCA8&uact=5)

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by csamuelsm** [comment]
Well, actually I did my research but I didn't find those results you showed and because of this, I wanted to write about this theme. But now, seeing all those results, I really think there's no need. Thank you for pointing this. I'll close this issue and think about another theme.
