### ISSUE TITLE
Getting Started With Servo Library(Servo motors) and Arduino

### ISSUE THREAD

**Issue by Collince-Okeyo** [section-engineering-education/engineering-education#3896]
### Proposed title of article
[Servo] Getting Started With Servo Library(Servo motors) and Arduino

### Introduction paragraph 
Servo is an open-source library that is used to  control a great number of servos. It makes careful use of timers: the library can control 12 servos using only 1 timer. On the Arduino Due you can control up to 60 servos. 
This library allows an Arduino board to control RC (hobby) servo motors. Servos have integrated gears and a shaft that can be precisely controlled. Standard servos allow the shaft to be positioned at various angles, usually between 0 and 180 degrees. Continuous rotation servos allow the rotation of the shaft to be set to various speeds.

### Key takeaways
- Understanding Servo library
- Connecting Servo motors to Arduino board
- Understanding the working of Servo motor

### References
- https://www.arduino.cc/reference/en/libraries/servo/
- https://www.arduino.cc/en/Guide
- https://www.section.io/engineering-education/search/?q=Arduino

**Comment by WanjaMIKE** [comment]
@Collince-Okeyo kindly, wait for the other PR to be published first. Thanks
