### ISSUE TITLE
Understanding Different Gestures in Android with Kotlin

### ISSUE THREAD

**Issue by calvinombati** [section-engineering-education/engineering-education#3898]
### Introduction paragraph (2-3 paragraphs):
Making use of different Android gestures is critical to offering an outstanding user experience. 

When a user places one or more fingers on the touch screen, your application understands that sequence of touches as a specific motion. The detection of gestures is divided into two stages:
- Collect information about touch events.
- Examine the data to see if it satisfies the criteria for any of the motions supported by your app.

In  this tutorial, you will learn how to recognize motion such as:
- Touching
- Scrolling
- Double-tapping
- Swiping
- Dragging
- Scaling 
- Time-delayed touching 

At the end of this tutorial, you will have a solid understanding of detecting and responding to gestures, which will aid you in developing responsive mobile applications.

### Key takeaways: 
- Understand the different gestures in Android
- Creating custom gestures.
- Adding gestures to a Recyclerview

### References: 
- [Android documentation] (https://developer.android.com/training/gestures)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@calvinombati 
 
We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites.](https://www.google.com/search?q=Understanding+Different+Gestures+in+Android+with+Kotlin&ei=GftRYfe5DubE0PEP8rC6gAE&oq=Understanding+Different+Gestures+in+Android+with+Kotlin&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKsCMgUIIRCrAjoHCAAQRxCwA0oECEEYAFCSuQNYkrkDYL66A2gCcAJ4AIABfogBfpIBAzAuMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwi3qtft0p_zAhVmIjQIHXKYDhAQ4dUDCA8&uact=5)

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.


Also pinging our resident expert on Kotlin @LinusMuema  for more insight.

**Comment by LinusMuema** [comment]
Hi @calvinombati 
I would also like to see what more does your article offer. When it comes to gestures, there are a lot of articles and even the official docs have more info on them.

There are youtube videos explaining your second takeaway and section already has three articles on recyclerviews. It will be more helpful if you gave a clear explanation of what makes your article unique?
