### ISSUE TITLE
[Languages] Creating Pinterest like layout in NuxtJs with Masonry

### ISSUE THREAD

**Issue by ravgeetdhillon** [section-engineering-education/engineering-education#3899]
### Proposed title of article

[Languages] Creating Pinterest like layout in NuxtJs with Masonry

### Introduction paragraph (2-3 paragraphs):

Creating a Pinterest like Layout is little tricky using normal CSS or frameworks like Bootstrap as it doesn't align to a grid structure In this tutorial, we will first look at how we can do this using Flexbox and its drawbacks. Then we will design a Pinterest like layout in NuxtJs with the help of Masonry npm library. In this process, we will learn why Flexbox is not a right way to build such a layout.

**The overall outline would be:**

```
## Intro

- Attach screenshot of the end result

## Setup Development Environment

- Setup Nuxt project
- Setup Bootstrap
- Setup Masonry for Nuxt

## Design layout using Flexbox

- Create a simple web page with rows and cols using Bootstrap
- Use FlexBox to achieve the above use case
- Discuss the drawback of FlexBox
- Add code
- Attach screenshots for visual help

## Design layout using Masonry

- Update the Flexbox code with Masonry
- Add code
- Attach screenshots for visual help

## Conclusion

- Link to Github Repo with source code for the tutorial
- Thank the reader for reading the article

## Resources

- Source code for the entire tutorial will be available in a public GitHub Repo
```

### Key takeaways: 
- Understand how to create a complex layout in a Web application
- Learn to add new libraries to Nuxt that do not support SSR

### References: 

- https://nuxtjs.org/
- https://www.npmjs.com/package/vue-masonry

### Templates to use as guides

- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites](https://www.google.com/search?q=Creating+Pinterest+like+layout+in+NuxtJs+with+Masonry&ei=VPtRYeKrO7rB0PEPi-qLuAo&oq=Creating+Pinterest+like+layout+in+NuxtJs+with+Masonry&gs_lcp=Cgdnd3Mtd2l6EAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsANKBAhBGABQvMYMWLzGDGC_xwxoAnACeACAAQCIAQCSAQCYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz&ved=0ahUKEwjipZWK05_zAhW6IDQIHQv1AqcQ4dUDCA8&uact=5).

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.
