### ISSUE TITLE
Stream Filtering using Lambda Expressions in Java

### ISSUE THREAD

**Issue by wanjadeno** [section-engineering-education/engineering-education#3901]
### Proposed title of article
Stream Filtering using Lambda Expressions in Java

### Introduction paragraph (2-3 paragraphs):

The Java stream's filter() function allows you to filter stream components based on a given criterion. As a result, this method takes a predicate as an input and returns a stream of result elements.

We will look at how to use the Stream. filter() function in Java while working with Streams in this tutorial. We will also look at how to use Stream Filter in Java and how to deal with checked exceptions in lambda expressions and specific instances.

### Key takeaways: 
The reader will learn the following;
1. Overview of Stream Filter in java.
2. Collection filtering.
3. How we use Stream.filter(). 
4. Using Multiple criterial to filter collection.
5. Ways of handling exception.

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
This topic was suggested here -> https://github.com/section-engineering-education/engineering-education/issues/3891. She will cover it in future. Feel free to suggest a new topic.
