### ISSUE TITLE
Vectors in Java – The Dynamic Arrays

### ISSUE THREAD

**Issue by dorky1** [section-engineering-education/engineering-education#3902]
### Proposed title of article
Vectors in Java – The Dynamic Arrays

### Introduction paragraph (2-3 paragraphs):

A growable array of items is implemented by the Vector class. It has components that may be retrieved using an integer index, just like an array. A Vector's size can be adjusted as needed to accommodate the addition or removal of objects after it has been generated. Vector is synchronized, unlike the new collection implementations. If a thread-safe implementation is not required, Array List should be used instead of Vector.

In this tutorial, we will look at arrays that are dynamic for this purpose we will use vectors in java that implements dynamic arrays.

### Key takeaways: 
-  The vector class of java.
- How to declare vector?
- Creating vector from other collection type.
- Adding elements at specific position by add method
- Getting the length of vector by using size method

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @dorky1 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
