### ISSUE TITLE
Prototypical Inheritance in JavaScript.

### ISSUE THREAD

**Issue by jmuchina** [section-engineering-education/engineering-education#3903]
### Proposed title of article
Prototypical Inheritance in JavaScript.

### Introduction paragraph (2-3 paragraphs):
JavaScript is an Object Oriented programming language based on prototypes. JavaScript now supports "prototypal inheritance," which means that objects and methods can be shared, extended, and copied after the ES6 modifications. Structure (data fields), behavior (functions / methods), and state can all be inherited easily when objects are shared (data values).

In this tutorial, we will look into prototype inheritance and how it's implemented in JavaScript.

### Key takeaways: 
We will cover the following in details;

- What is prototypical inheritance?
- Cons of prototypical inheritance
- Inheriting methods
- Setting up prototypical relationships
- Three-Tier Inheritance and Scalability
- Wrapping up and resources

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
