### ISSUE TITLE
[Machine Learning]Youtube Spam Detection Model

### ISSUE THREAD

**Issue by jamesomina99** [section-engineering-education/engineering-education#3907]
### Proposed title of article
[Machine Learning]Youtube Spam Detection Model

### Introduction paragraph (2-3 paragraphs):
Spam detection means detecting spam messages or comments by understanding text content in order that you’ll only receive messages or notifications that are crucial to you. If spam messages are found, they’re automatically transferred to a spam folder and you’re never notified of such alerts. This helps to enhance the user experience, as many spam alerts can bother many users.

Spam detection is a supervised machine learning problem. This means you must provide your machine learning model with a set of examples of spam and ham messages and let it find the relevant patterns that separate the two different categories.
The Implementation of spam filtering is exclusively important for all organizations. The major role of spam filtering is to keep the garbage out of peoples inboxes and notification sections and in today’s scenario, we can’t afford our security to lose so easily, we ensure that we implement systems that protect us from such spam.

In this tutorial, we will be building a  machine learning model that will detect Youtube comments as spam or not. We will use a dataset spam and ham comments that will be able to train our model. This dataset is a list of comments from popular Youtube channels. This will be implemented using the Naive Bayes with a bag of words approach using TF-IDFNaive Bayes classification algorithm.

### Key takeaways: 
1. What is spam filtering.
2. The different types of spam filtering(SMS, Email, Youtube etc)
3.  Preprocessing our dataset(Dataset contains list of spam and non spam comments)
4.  Installing our dependacies and packages.
5. Building our model using TF-IDFNaive Bayes classification algorithm.
6. Using our model to make predictions(If a comment is Spam or not)

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Thank you for the topic suggestion @jamesomina99  , however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
