### ISSUE TITLE
How can we run an external process with Node.js?

### ISSUE THREAD

**Issue by neshmacharia** [section-engineering-education/engineering-education#3910]
### Proposed title of article
How can we run an external process with Node.js?

### Introduction paragraph (2-3 paragraphs):
In this tutorial, you will build your first program using the Node.js runtime. You'll start with a few Node-specific ideas and work your way up to creating an application that allows users to explore system environment variables. To do this, you will learn how to output strings to the console, receive user input, and access environment variables.

### Key takeaways: 
By the end of this tutorial, the learner will understand:
- How to output strings to the console
- How to receive User Input via Command Line Arguments
- How to access Environment Variables
- How to handle Undefined Input
### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Thank you for suggesting another topic.

Seems like a very cool topic - but regarding Node.js we have more than enough currently in our EngEd library as we did a big push the last few months and are currently not accepting any more Node.js articles to publish for the time being.

Please feel free to suggest an alternate topic to explore. 🚀
