### ISSUE TITLE
Float Containment in CSS

### ISSUE THREAD

**Issue by djayjames** [section-engineering-education/engineering-education#3911]
### Proposed title of article
Float Containment in CSS

### Introduction paragraph (2-3 paragraphs):
The float property specifies how an element should float. The float property in CSS is used for positioning and layout on web pages. Common usage might be floating an image to one side and letting text wrap around it. While it is seemingly simple on the surface – Either float to the left, to the right, or none at all. The results can often be the opposite of what you wanted.

### Key takeaways: 
By the end of this tutorial, the learner will understand:
1. What Does Float Mean and its properties
2. How to make Elements Float
3. How to imitate float
4. How to control Overflow
5. Float Vs Align

### References: 
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Unfortunately, focusing on the float concept alone cannot make a detailed tutorial. Feel free to suggest another topic. Thanks
