### ISSUE TITLE
Feature suggestion: Using Vlang alongside Tailwind CSS to develop faster loading and lighter websites using the WebUI and import pdf library

### ISSUE THREAD

**Issue by ROYFORDWANYOIKE2001** [section-engineering-education/engineering-education#3913]
**Is your feature suggestion related to a current problem or issue? Please describe.**
A clear and concise description of what the problem is. Ex. I''ve found it difficult when [...]

**Describe the solution you'd like to implement to the program**
Building fast websites which are well optimized and uses less memory to handle requests.
**Describe alternatives you've considered or seen**

**Additional context on how you could go about building this**
Many languages have been much on improving efficiency but haven't checked on memory and speed. Using V programming a less commonly used language the Web UI will and its libraries are helping to come up with a fast and memory load optimized website which you won't spend much waiting to load.

**Comment by hectorkambow** [comment]
@ROYFORDWANYOIKE2001 

Was this a topic suggestions on what you wanted to write up or a feature enhancement suggestion to improve the EngEd program?

**Comment by ROYFORDWANYOIKE2001** [comment]
yes
