### ISSUE TITLE
Feature suggestion: I would urge the engineering education team to add a search feature where one can search the available articles before suggesting his or her article. 

### ISSUE THREAD

**Issue by ROYFORDWANYOIKE2001** [section-engineering-education/engineering-education#3915]
**Is your feature suggestion related to a current problem or issue? Please describe.**
A clear and concise description of what the problem is. Ex. I''ve found it difficult when [...]
After going through most of the articles especially closed ones, I have found that most of the people submitting articles are not aware if the idea had been implemented before and hence ends up publishing a similar article. Addition of the search feature in the engineering program issue part will help them to avoid replication and hence making the task easy for even the content moderator to review them.

**Describe the solution you'd like to implement to the program**
Addition of the search feature in the engineering program issue part will help them to avoid replication and hence making the task easy for even the content moderator to review them. This feature will make even the entire process easy to handle and complete within a short duration of time. 

**Describe alternatives you've considered or seen**
Alternatively, grouping all the articles to their domains will also make this simple to access. 
**Additional context on how you could go about building this**
Using Javascript a similar algorithm can be used to implement the search bar

function findUserInfo(article title, searchString){
    return userName.toLowerCase().substr(0,searchString.length).includes(searchString.toLowerCase());
}

**Comment by LinusMuema** [comment]
Hi @ROYFORDWANYOIKE2001 
I'm not sure I get your question well but. There are various ways a writer can check if the article has been published or not. In addition to the search bar on the website (as you have mentioned), you can also look for pull requests and issues submitted. Github does a really good job in the search bar. 
You can also check the repo for similar article titles, i.e, the names of the directories. You can just search the names of folders for specific topics. For instance, if you search `docker` you can get all articles related to the same topic provided the name is in the title.

I hope this helps.

**Comment by ROYFORDWANYOIKE2001** [comment]
Hello, i was basing the idea on grouping the articles like machine learning
in one group, android and also similar to web. Its just an idea which i
thought i would have been easier. Thank you

**Comment by hectorkambow** [comment]
@ROYFORDWANYOIKE2001 

Thank you v much for the suggestions. Do you mean a different method than the topic (categories) on the website?
