### ISSUE TITLE
Heap and Stack Memory Errors in Java

### ISSUE THREAD

**Issue by AshaIha** [section-engineering-education/engineering-education#3917]
### Proposed title of the article
Heap and Stack Memory Errors in Java

### Introduction paragraph (2-3 paragraphs):
Java's virtual machine oversees memory allocation. It separates the memory into heap and stack portions. Stack is only used for the method or methods presently running, however, Java Heap Space is used throughout the application. All items are produced in the Heap Space, but only references to those things are stored in the Stack. A LIFO (last-in, first-out) memory allocation system is used to access the Stack.
Every time we call a method, the stack memory is freed. In the event that your methods continue to stay in the stack, the stack will be full, and we will be unable to push because we will receive the java.lang.StackOverflowError error from the JVM. java.lang.OutOfMemoryError will be thrown by the JVM if there is not enough heap memory to accommodate the number of new objects being created. This tutorial will go into great detail about all of that.
### Key takeaways: 
- Stack and Heap memory.
- Stack memory in Java.
- Heap Memory Error.
### References: 
N/A

**Comment by LinusMuema** [comment]
Hello @AshaIha  and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
