### ISSUE TITLE
Using Instance Blocks in Java

### ISSUE THREAD

**Issue by LynnMumo** [section-engineering-education/engineering-education#3918]
### Proposed title of article
Using Instance Blocks in Java

### Introduction paragraph (2-3 paragraphs):
In order to set up the instance data member, we use the Instance Initializer block. Every time a new object of the class is created, it gets run once. When initializing the instance variable in the initializer block, additional operations can be performed while the instance variable is still being initialized.
As the nameless method in Java, the instance block may be described as a place where logic can be defined and it has some characteristics such as classes can define them, but methods cannot, all objects share instance block logic and the instance block will only be executed once during the construction of each object. We will see all these characteristics in application in this tutorial.

### Key takeaways: 
- The use of instance blocks.
- The advantage and drawbacks of instance blocks.
- Difference between instance block and constructor in Java.
### References: 
N/A

**Comment by LinusMuema** [comment]
Hello @LynnMumo  and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites (like https://www.javatpoint.com/instance-initializer-block) and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
