### ISSUE TITLE
Java Program to Implement Stack API

### ISSUE THREAD

**Issue by jgesare** [section-engineering-education/engineering-education#3919]
### Proposed title of article
Java Program to Implement Stack AP

### Introduction paragraph (2-3 paragraphs):
A stack is a data structure that keeps track of the order in which insertions and deletions are made. Only one end of the stack, referred to as Top, allows insertion and removal. This happens when the stack is totally full, and this happens when the stack completely empties (overflows).
This Java program will put the Stack API into action. The Stack class depicts a last-in, first-out (LIFO) stack of items. It adds five new operations to the Vector class that allows it to be used as a stack. The standard push and pop operations are available, as well as methods for peeking at the top item on the stack, testing whether the stack is empty, and searching the stack for a specific item to see how far it is from the top.
### Key takeaways: 
- Stack API Implementations
- Methods in Stack.
- Stack interface.
### References: 
N/A

**Comment by LinusMuema** [comment]
Hello @jgesare   and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
