### ISSUE TITLE
How to Pass ArrayList Object as Function Argument in java

### ISSUE THREAD

**Issue by SteveadeNick** [section-engineering-education/engineering-education#3920]
### Proposed title of article
How to Pass ArrayList Object as Function Argument in java

### Introduction paragraph (2-3 paragraphs):
The ArrayList class in Java is a resizable array, which means it can expand and decrease in size dynamically based on the values we add or remove from it. The java.util package contains it.
To resolve your issue, use the new keyword to create a new ArrayList and then add all of the objects, or use the clone() method. This is due to the fact that passing an ArrayList as a parameter allows the called method to modify the contents of the array. References to Objects are stored in the ArrayList.

### Key takeaways: 
- How Java is passed by Value
- Writing an ArrayList method
- Array and ArrayList
### References: 
N/A

**Comment by LinusMuema** [comment]
Hello @SteveadeNick  and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
An arry list is passed to a function as illustrated below
```java
public static void test(ArrayList lst){
    //do something here
    
    System.out.println(lst.toString()) ;

    
}
```
Feel free to suggest another topic. Thanks
