### ISSUE TITLE
Creating authentication API with laravel Passport

### ISSUE THREAD

**Issue by Adebogunabdulroheem** [section-engineering-education/engineering-education#3921]
### Introduction 
Understanding how API's work is very critical as a software developer, in this tutorial we will learn how to implement API authentications in Laravel.

API stands for 'Application Programming Interface', API's are essential tools that help third-party authentication communicate with other apps. An example of API is posting on Twitter and have it auto-post on Facebook, in other to make these functionalities possible Twitter had to use Facebook API in other to post on Facebook on the users' behalf. When working with API it is typically important to ensure that requests are being made by valid third-party applications.

API's authentication is a process that oversees that only authorized applications will be able to interact with your program, this seems like a basic concept because you are used to username and password each time you log into a site like section.io, Facebook, and the likes. While API authentication is different than the normal login process, it has to be completed 100% encode including information that contains username, password, API keys, etc. this information will be tracked by the receiving application to make sure the request is coming from a valid app you can compare this to a site like a Facebook checking your email and password against their database this ensure validity 

### Key takeaways: 
At the end of this tutorial the reader should be able to:
- Install Laravel application.
- Create a  controller and model for testing Laravel Passport authentication.
- Create necessary middleware for the authentication API.
- Set up basic Laravel API authentication: registering, logging in, and logging out.
- Set up Laravel default password reset functionality.

### References: 
- [Laravel Docs](https://laravel.com/docs/6.x/passport)

**Comment by LinusMuema** [comment]
Hello @Adebogunabdulroheem and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
I found multiple mistakes in your introduction. Please make sure to spellcheck and grammar check your article before submitting it - Tools: [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/Free) - [Grammarly](https://app.grammarly.com/).

Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
Someone already covered this topic: https://www.section.io/engineering-education/laravel-passport/

Please feel free to suggest an alternate topic to explore. 🚀
