### ISSUE TITLE
Parameter Passing Techniques in Java

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#3922]
### Proposed title of article
Parameter Passing Techniques in Java
### Introduction paragraph (2-3 paragraphs):
In Java, a parameter is a value you can give to a method as an argument. The parameter can then be used as if it were a local variable, with the value of the variable provided to it by the calling method as its initial value.
Parameter data can be supplied to and from methods and functions in a variety of ways. To use Pass by Value as the first method implies to make and save a duplicate of the data by using the parameter's name. The second technique of passing data is known as Pass by Reference, and it uses the original data from the caller function. This tutorial will go over all of them.
### Key takeaways: 
- Types of parameters
- Important methods of Parameter Passing
- Purpose of a parameter

### References: 
N/A

**Comment by LinusMuema** [comment]
Hello @vincentkims49  and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Unfortunately, parameters seem to be basic in Java. There are already numerous articles that are using params to pass values to functions. Feel free to suggest another topic. Thanks
