### ISSUE TITLE
[Software Development] How to Use the Canary Deployment Strategy for Zero-Downtime 

### ISSUE THREAD

**Issue by Snzovi** [section-engineering-education/engineering-education#3928]
### Proposed title of article
How to Use the Canary Deployment Strategy for Zero-Downtime 

### Introduction paragraph (2-3 paragraphs):
Regularly deploying code and making it revertible are fundamental DevOps problems. Canary deployment is a cautious deployment strategy that uses two similar deployment environments operating simultaneously to handle many of these problems. 

In this article, we will discuss what canary deployments are, when they are most effective and when they're not effective. We will also compare canary deployment to other deployment strategies. 

### Key takeaways: 

1. When to use and not to use canary deployments 
2. Why canary deployment is important 
3. Canary deployment and other deployment strategies (blue-green deployment, Feature Flag based Deployment) 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
Great topic. But a lot of other blog sites already covered it.

We are looking for programmer-centric concepts explained in fun and intuitive ways.
Please feel free to suggest an alternate topic to explore. 🚀
