### ISSUE TITLE
[C++] Dynamic memory allocation in C++

### ISSUE THREAD

**Issue by Njengab** [section-engineering-education/engineering-education#3929]
[C++]Dynamic Memory Allocation  in C++ 
Introduction:

Have you ever wondered how to avoid memory leaks in a C++ program? Don't worry, dynamic memory allocation has you covered.
Dynamic memory allocation can be done at the runtime of program execution. This aids in the resolution of memory leaks caused by static memory allocation. C++ accomplishes this through the use of pointers.
With the use of pointers one can update memory in one location and change can be reflected in another location in the program. This scenario is useful in memory saving.

         Key Takeaways 

1.	Why dynamic memory allocation
2.	Allocation and deallocation
3.	Dynamic allocating arrays
4.	Pros of dynamic memory allocation

   References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by Njengab** [comment]
Thanks
