### ISSUE TITLE
 Integrating Razorpay Payments with React JS and Node JS

### ISSUE THREAD

**Issue by Gautham495** [section-engineering-education/engineering-education#3935]
### Proposed title of article

Integrating Razorpay Payments with React JS and Node JS

### Introduction paragraph (2-3 paragraphs):

Razorpay is an Indian Payment Processing Platform which enables startups and enterprises around the world to collect payments from its customers from India with ease. As India has a unique way of paying online with a method called UPI(Unified Payments Interface), capturing this particular segment of people is crucial. As India is rapidly adopting digital ways to pay and access their products via websites, Razorpay provides the best Solution to get payments from Indian users.

In this tutorial you will get to know how you can integrate Razorpay with React JS in the Frontend and then how to integrate the Razorpay SDK in the backend Node JS server.

I will go through the concept of webhook with help of ngrok which will be used to get data from the Razorpay serverwhen payment is retreived from the user.  From this tutorial you can setup a full stack React and Node JS project with Razorpay Payments.

### Key takeaways: 
 1. Understand How Indians pay online which will be crucial for your startup
 2. Setting up Razorpay SDK in a React JS project.
 3. Making a Node JS Server with Razorpay SDK. 
 4.  Understanding how webhook works with Razorpay Server

### References: 
https://razorpay.com/
https://ngrok.com/
https://reactjs.org/
https://nodejs.org/en/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
https://www.section.io/engineering-education/search/?q=razorpay  - how will it differ from this topic suggestion?

**Comment by Gautham495** [comment]
That blog is for react native mobile app development. This is for react web development. The process of integrating the software in web is vastly different from mobile app development which has been described in the above mentioned article.

**Comment by hectorkambow** [comment]
@Gautham495 

Thank you for suggesting another topic.

Seems like a very cool topic - but regarding Node.js we have more than enough currently in our EngEd library as we did a big push the last few months and are currently not accepting any more Node.js articles to publish for the time being.

Please feel free to suggest an alternate topic to explore. 🚀
