### ISSUE TITLE
Creating a lexer/tokenizer with Plex

### ISSUE THREAD

**Issue by koech13** [section-engineering-education/engineering-education#3936]
### Proposed title of article
Creating a lexer/tokenizer with Plex

### Introduction paragraph (2-3 paragraphs):
One can write a complex lexer by hand. However for more complex and real lexer, you will be required to use a toll to build your lexer. This tool in our case is the Plex which is used to produce a tokenizer/lexer for a recursive decent parser. To use Plex, One has to download it and add it to PYTHONPATH.

### Key takeaways: 
1. Downloading and installing plex
2. Describing Plex
3. Creating a lexer/tokenizer with Plex

### References: 
N/A

### Templates to use as guides
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
How are planning to make your article different from the [official docs](https://pythonhosted.org/plex/tutorial.html)?

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
