### ISSUE TITLE
[Android] Media file storage with Firebase Storage SDK

### ISSUE THREAD

**Issue by Antonymuriuki** [section-engineering-education/engineering-education#3937]
### Proposed title of article
Media file storage with Firebase Storage SDK in Android

### Introduction paragraph (2-3 paragraphs):

The Firebase SDKs for Cloud Storage are used by developers to upload and download files (such as audio or videos) directly from service users. If the network connection is poor, the client can resume the operation from where it left off, saving time and bandwidth for your users.

Cloud Storage for Firebase saves your files in a Google Cloud Storage bucket, allowing users to access them from both Firebase and Google Cloud. The Firebase SDKs for Cloud Storage gives you the freedom to upload and download files from mobile clients.

In this tutorial, we will learn how to use the Firebase Storage SDK to upload images and retrieve them on Android.

### Key takeaways: 

By the end of this tutorial, the reader will be able to:
- Understand what Firebase Storage is and how it works.
- Use the Firebase Storage SDK to upload and download images directly in an Android App.
- Track and update users on the ongoing or completed tasks.
- Avoid the most common mistakes when working with Firabase Storage.

### References: 
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
