### ISSUE TITLE
How to build a currency converter with JavaScript

### ISSUE THREAD

**Issue by Nomzy-kush** [section-engineering-education/engineering-education#3938]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*
**Use the following format as the title of the issue: [Category of Topic] Title for the article.**

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

### Introduction paragraph (2-3 paragraphs):
This tutorial will show you how to build a simple currency converter with HTML, CSS, and Vanilla JavaScript. The app allows you to input a value in a particular currency. It automatically shows you the equivalent value in any other currency of your choice at that specific time. We will get the actual currency data from the Exchange Rate API provided by the European Central Bank. It is a must-do JavaScript Project. 

### Key takeaways: 
1. Readers will learn the various functions involved in building a real-life currency converter with JavaScript.
2. Readers will learn how to get the Real currency data from the Exchange Rate API.
3. At the end of this article, readers will get an insight into how to create any real-life application with plain Vanilla JavaScript. 

### References: 
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites](https://www.google.com/search?q=How+to+build+a+currency+converter+with+JavaScript&ei=zEdSYdT0Eovb-wShoLjYDA&oq=How+to+build+a+currency+converter+with+JavaScript&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEBYQHjoHCAAQRxCwAzoHCAAQsAMQQzoJCAAQsAMQChBDSgQIQRgAULaT4ilYtpPiKWDXmeIpaAJwAngAgAFmiAFmkgEDMC4xmAEAoAECoAEByAEKwAEB&sclient=gws-wiz&ved=0ahUKEwjUirWAnKDzAhWL7Z4KHSEQDssQ4dUDCA8&uact=5).

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.
