### ISSUE TITLE
Implementation of eigenvalues, eigenvectors, eigendecomposition, orthogonalization and orthonormalization in Matlab 

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#3941]
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
In mathematics, a matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns.  is a nonzero vector that changes at most by a scalar factor when that linear transformation is applied to it while eigenvalue is the factor by which the eigenvector is scaled. eigendecomposition is the factorization of a matrix into a canonical form, whereby the matrix is represented in terms of its eigenvalues and eigenvectors.  orthogonalization is (mathematics) the process of converting a set of functions or vectors into orthogonal ones while orthonormalization is (mathematics) a form of orthogonalization in which the resulting vectors are all unit vectors.
All these processes form the basics of the matrix. In daily life and daily activity, engineers and data analysts use more of these processes in their daily activities.  Since Matlab is a matrix laboratory, then it means that it has tools that make working these processes easier. In this article, we will look at how the above processes can be applied in Matlab and their uses.

### Key takeaways: 
- Basic understanding of the processes.
- Implementation of these processes in Matlab.
- Uses of such processes.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@jumapaul 
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double check that it does not overlap with any existing EngEd articles, [articles on other blog sites](https://www.google.com/search?q=Implementation+of+eigenvalues%2C+eigenvectors%2C+eigendecomposition%2C+orthogonalization+and+orthonormalization+in+Matlab&ei=951TYe4O5sTQ8Q_987WwBw&ved=0ahUKEwiu5uio4qLzAhVmIjQIHf15DXYQ4dUDCA4&uact=5&oq=Implementation+of+eigenvalues%2C+eigenvectors%2C+eigendecomposition%2C+orthogonalization+and+orthonormalization+in+Matlab&gs_lcp=Cgdnd3Mtd2l6EAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsANKBAhBGABQsvYCWLL2AmCE-AJoAnACeACAAQCIAQCSAQCYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
