### ISSUE TITLE
[API] Embracing API-first Approach Beyond Product Designing 

### ISSUE THREAD

**Issue by Polojigide** [section-engineering-education/engineering-education#3950]
### Proposed title of article
[API] Embracing API-first Approach Beyond Product Designing 

### Introduction paragraph (2-3 paragraphs):
An API-first approach is steadily becoming a popular way of designing products, but the principle is not only relevant in products. The approach is also relevant to app development and automation. 
In this piece, I’ll be making the case for why an API-first approach is relevant to automation as well as app development.

### Key takeaways: 
What Is API-First App Development? 
What is API-first design? 
Why API first? 
Why developers need API-first approach. 
Why API is relevant to automation. 
### References: 
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@Polojigide 
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or [what is covered in other blog sites](https://www.google.com/search?q=API-first+Approach+Beyond+Product+Designing&ei=M59TYYObCZ2S0PEPke-KgAg&ved=0ahUKEwjDgMm_46LzAhUdCTQIHZG3AoAQ4dUDCA4&uact=5&oq=API-first+Approach+Beyond+Product+Designing&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABQ9s8FWPbPBWCc0QVoAnACeACAAXWIAXWSAQMwLjGYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz). (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
