### ISSUE TITLE
[languages]Advanced Concepts of Programming using Dart

### ISSUE THREAD

**Issue by Eze4Manuel** [section-engineering-education/engineering-education#3952]
Key takeaways:
In-depth grasp of concepts like classes, objects, polymorphism, abstraction, encapsulation, inheritance, Access modifiers, static classes, e.t.c
Appreciation of the concepts of object-oriented programming using dart
See how feasible to pick up dart programming language coming from a Java background or a JavaScript background
Detailed concentrated coding tutorial sessions showing examples of all the concepts
References:
https://dart.dev/guides/libraries
https://dart.dev/guides/language/language-tour
https://dart.dev/guides/libraries/library-tour

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@Eze4Manuel 

Sounds like a helpful topic - lets please be sure it adds value beyond what is in any **official docs** and/or [what is covered in other blog sites.](https://www.google.com/search?q=Advanced+Concepts+of+Programming+using+Dart&ei=B6FTYaaUDP-_0PEPn8OwyAk&ved=0ahUKEwjms-Ce5aLzAhX_HzQIHZ8hDJkQ4dUDCA4&uact=5&oq=Advanced+Concepts+of+Programming+using+Dart&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABOgcIABBHELADSgQIQRgAULCvCFiwrwhgmLIIaANwAngAgAF1iAF1kgEDMC4xmAEAoAECoAEByAEIwAEB&sclient=gws-wiz) (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
