### ISSUE TITLE
[AI] Integrating Arduino With SparkFun Line Follower

### ISSUE THREAD

**Issue by Hepatrique** [section-engineering-education/engineering-education#3953]
### Proposed title of article
[Arduino] Integrating Arduino With SparkFun For Line Follower

### Introduction 
The SparkFun Line Follower Array is a long board consisting of eight IR sensors that have been configured to read as digital bits! We have designed the SparkFun Line Follower Arrays to follow a dark line of about ¾ inch width or smaller (spray paint or electrical tape) on a light background. The line follower functions by taking an 8-bit reading of reflectance for use with following lines or reading dark/light patterns and can see from about 1/4 to 3/4 inches away.

Arduino is an open-source electronics platform based on easy-to-use hardware and software. Arduino boards are able to read inputs - light on a sensor, a finger on a button, or a Twitter message - and turn it into an output - activating a motor, turning on an LED, publishing something online.

### Key takeaways: 
- What is Arduino.
- What is SparkFun.
- How To Integrate Arduino With SparkFun.
- How To Implement Line Follower Code.

### References: 
- [Arduino](https://www.arduino.cc/en/guide/introduction)
- [SparkFun](https://learn.sparkfun.com/tutorials/sparkfun-line-follower-array-hookup-guide/all#installing-the-arduino-library)
- [Integration of ROS With Arduino](https://www.section.io/engineering-education/integration-of-ros-with-arduino/)

**Comment by lalith1403** [comment]
This is an interesting topic. @hectorkambow need your feedback on this hardware basic suggestion. Approved on my end.
