### ISSUE TITLE
React Hooks : Understanding useState

### ISSUE THREAD

**Issue by PastorCoder** [section-engineering-education/engineering-education#3958]
### Proposed title of article
React Hooks : Understanding useState

### Introduction paragraph (2-3 paragraphs):
A Hook is a special function that lets you “hook into” React features. React Hook was first released in October  2018(the first stable release was in  React 16.8), the React hook APIs provide an alternative to writing class-based components, and offer an alternative approach to state management and lifecycle methods.

useState is a Hook that allows you to have state variables in functional components. You pass the initial state(could be an empty string) to this function and it returns a variable with the current state value and another function to update this value.

### Key takeaways: 
At the end of the article, the reader should know:

* What useState does.
* Rules for using useState.
* How to declare a state in React.
* Answer the question: “Should I use class or functional components with React.useState”?
* How to update state.

### References: 
https://reactjs.org/docs/hooks-state.html 
https://stackoverflow.com/questions/53165945/what-is-usestate-in-react 
https://dev.to/sarah_chima/destructuring-assignment---arrays-16f 
https://reactjs.org/blog/2019/02/06/react-v16.8.0.html

**Comment by WanjaMIKE** [comment]
I already covered useState. The article was about consuming an API in react.js

**Comment by WanjaMIKE** [comment]
https://www.section.io/engineering-education/how-to-consume-data-from-an-api-in-react/

**Comment by PastorCoder** [comment]
Just went through your article, you are great technical writer.

 But you only mentioned and applied useState in your article, this mention of useState cannot teach/explain useState to someone that is totally new to react.

I am going do elaborate discussion of useState such that a total dummy will understand what useState is and be able to use it after going through the article.

I don't think that this mention of useState in this your article can help a total novice understand what useState is.

**Comment by ahmadmardeni1** [comment]
Can we approve this topic suggestion now? @WanjaMIKE

**Comment by WanjaMIKE** [comment]
Yes, you can proceed @ahmadmardeni1

**Comment by PastorCoder** [comment]
Hi,
Is the topic approved?.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @PastorCoder 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
