### ISSUE TITLE
Building data driven  application in react

### ISSUE THREAD

**Issue by 1-creator** [section-engineering-education/engineering-education#3968]
#### Proposed article introduction
It is not very convenient to have to upgrade components  every time we have a change in our application data .Hard-cording data  in our application  is inflexible and makes modifying data later on much more troublesome hence its not the perfect solution. Lets learn  about data-driven applications in react 
#### key takeaways
- Get to know what is data driven applications 
- data-driven components 
- Best practices when designing and developing data-driven applications
-  How to build data-driven  application

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
I already built a data-driven react application. How will yours be different? -> https://www.section.io/engineering-education/how-to-consume-data-from-an-api-in-react/

**Comment by 1-creator** [comment]
-I will be using relay framework  which is a javascript framework for building data driven react applications
-here is the summary of the code i will be using https://github.com/1-creator/relay-starter-example
-I will add some examples of apps in github e.g https://github.com/dkozar/react-data-menu
-I will describe more about data driven applications

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @1-creator 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
