### ISSUE TITLE
Image Recognition for Arduino and Raspberry PI using Pixy2 Camera 

### ISSUE THREAD

**Issue by brianalusa** [section-engineering-education/engineering-education#3972]
### Topic Suggestion
Image Recognition for Arduino and Raspberry PI using Pixy2 Camera 

Introduction
The Pixy2 is a low-cost, high-performance camera that can recognize objects, track lines, and read simple barcodes. The Pixy Cam is the latest iteration of a project developed by Charmed Labs in collaboration with Carnegie Mellon University's Robotics Institute.

The Pixy2 can be used with an Arduino and Raspberry Pi. In this blog, we will understand how the pixy2 camera works in Arduino and Raspberry PI 4 Model B

Key takeaways:
- Pixy2 Introduction
- Pixy2 features
- Pixy2 Unboxing
- Using PixyMon
- Color Signature Training
- Arduino Hookup
- Line Tracking 

References:
https://dronebotworkshop.com/pixy2-camera/

**Comment by lalith1403** [comment]
This is a wonderful topic. @hectorkambow need your feedback on hardware based topic suggestion.

**Comment by hectorkambow** [comment]
👋 

Thank you for the topic suggestion , however this is a bit outside of our preferred topic areas. (the hardware portion)
We're more interested in original, software based, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
