### ISSUE TITLE
[Android] Creating Custom Extendable and Expandable Floating Action Button In Android Using Kotlin

### ISSUE THREAD

**Issue by omondi-alex** [section-engineering-education/engineering-education#3974]
#### Proposed title of article
 Creating Custom Extendable and Expandable Floating Action Button In Android Using Kotlin

#### Proposed article introduction
A floating action button (FAB) is a circular button that triggers the primary action in your app's UI. A FAB performs the primary, or most common, action on a screen. It appears in front of all screen content, typically as a circular shape with an icon in its center.

#### Key takeaways 
- What is FAB
- How to create extendable FAB
- How to create expandable FAB

#### Article quality
My article is going to be unique since am going to use material deign and as well implement it using Kotlin programming language

#### References
- https://material.io/components/buttons-floating-action-button/android
- https://developer.android.com/guide/topics/ui/floating-action-button

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@omondi-alex 

We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites](https://www.google.com/search?q=Creating+Custom+Extendable+and+Expandable+Floating+Action+Button+In+Android+Using+Kotlin&ei=W6JTYYP-C__O0PEP84aqyAc&ved=0ahUKEwjDl_DA5qLzAhV_JzQIHXODCnkQ4dUDCA4&uact=5&oq=Creating+Custom+Extendable+and+Expandable+Floating+Action+Button+In+Android+Using+Kotlin&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABQzJUMWMyVDGCWlwxoAnACeACAAXaIAXaSAQMwLjGYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz).

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by omondi-alex** [comment]
The article will differ from what is in the other sites since am I going to use kotlin language where as the other sites are using java. It will also be easy to understand for beginners.

**Comment by omondi-alex** [comment]
Hello @hectorkambow 
The article will differ from what is in the other sites since am I going to use Kotlin programming language where as the other sites are using java. It will also be easy to understand for beginners.

**Comment by omondi-alex** [comment]
@hectorkambow 

I also realized that the other articles did not handle memory leaks and exceptions which can lead to crushing of an app. I have included these two concepts to make the article not only unique but also confirming to android development principles.
