### ISSUE TITLE
[Languages] Lexical Scope in JavaScript 

### ISSUE THREAD

**Issue by MichaelmichaelW** [section-engineering-education/engineering-education#3980]
#### Proposed title of article
Lexical Scope in JavaScript.

#### Proposed article introduction
In JavaScript, lexical scope refers to the ability of a variable declared outside of a function to be accessed from within another function declared after the variable declaration. The variables defined within a function, on the other hand, are not accessible outside of that function.

In this article, we are going to have a look in detail the working of the Lexical Scope using well-explained examples. 

#### Key takeaways 
1.  Scope chain in Javascript.
2.  Working of the Scope Chain in Javascript
3.  Understanding Lexical Scope in Javascript.
4.  Working of the Lexical Scope in Javascript

#### Article quality
In this article, we are going to see the working of Lexical scope in Javascript and also providing detailed examples that will make the understanding of this topic easier. It is an article that will fit everybody including beginners.

#### References
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@MichaelmichaelW 

We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites.](https://www.google.com/search?q=Lexical+Scope+in+JavaScript&ei=aaRTYf3_F__O0PEP84aqyAc&ved=0ahUKEwi92OS76KLzAhV_JzQIHXODCnkQ4dUDCA4&uact=5&oq=Lexical+Scope+in+JavaScript&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yCAgAEBYQChAeMgYIABAWEB46BwgAEEcQsANKBAhBGABQrZkEWK2ZBGCYmwRoAnADeACAAWOIAWOSAQExmAEAoAECoAEByAEIwAEB&sclient=gws-wiz)

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by MichaelmichaelW** [comment]
@hectorkambow what I will have to do is that I will take a serious look at the topic digging deep with well-explained examples so that the content in the end result shall be unique and well understood by everybody.

**Comment by MichaelmichaelW** [comment]
I will also aim in expanding what is meant by a scope chain and how it works using detailed examples so that whoever will read about this topic will have to understand in a way that completely minimizes struggles when learning.
