### ISSUE TITLE
Introduction to Programming Loops in Stata.

### ISSUE THREAD

**Issue by Pelmak** [section-engineering-education/engineering-education#3982]
#### Proposed article introduction
Loops are a very useful tool for collecting, altering, and presenting information because they allow you to execute the same function for multiple variables at the same time without writing multiple lines of code.
Loops are simple to explain, and they will make your do-file brief and tidy by reducing the number of lines in it.
They're also less dangerous than reusing code.

Loops are difficult to master at first, but they will spare you time in the long run.

#### Key takeaways 
The learner will be able to understand, generate and utilize the following Stata loops:
-Forvalues
-Foreach of
-Foreach in
-Nested loops

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, loops can easily be found in the documentation. Feel free to suggest another topic. Thanks
