### ISSUE TITLE
jquery AJAX autocomplete feature

### ISSUE THREAD

**Issue by Wakanyaben254** [section-engineering-education/engineering-education#3986]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
jquery AJAX autocomplete feature 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
autocomplete feature is used to provide the auto suggestion for users while entering input.its frequently used in modern websites to provide the users a list of suggestion while typing the beginning word in textbox .it facilitates the user to select an item from list,which will be displayed in the input field.Jquery autocomplete function is called on the key-up event of the input field.In this tutorial ,we are going to suggest country names for the users based on the keyword they entered into the input field by using jqueryAJAX.This function requests PHP for the list of countries via AJAX by sending the value of the input field.In PHP,it reads  country names from the database that starts with the keyword entered by the user.

#### Key takeaways 
1. Jquery autocomplete feature.
2. Benefits of autocomplete feature.
3. Input field with autocomplete feature.
4. Jquery autocomplete script.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Closing since you already have another topic suggestion. Thanks

**Comment by Wakanyaben254** [comment]
I have only make a suggestion about one topic (jquery AJAX autocomplete feature) kindly check on it
