### ISSUE TITLE
[Languages] OOP Concept: Understanding Inheritance and Polymorphism in Java

### ISSUE THREAD

**Issue by Frank-dev20** [section-engineering-education/engineering-education#3987]
#### Introduction
Java is object-oriented programming, which means everything is considered an object. 
There are about four major concepts in the OOP programming paradigm that every developer intending to learn OOP is expected to know. 
In this tutorial, we will explore the concept of inheritance and Polymorphism.

#### Key takeaways
At the end of this tutorial, the reader should understand:
- What is polymorphism
- What is an inheritance
- Multiple inheritance
- The importance of polymorphism and inheritance
- Inheritance hierarchy
- Implementation of inheritance and polymorphism in Java

#### Article quality
Since I will explore these concepts in-depth using easy-to-understand English language and simple examples, this article will be a beginner-friendly article and also useful for already established java developers. This can be seen as a continuation of this article I wrote [oop concepts](https://www.section.io/engineering-education/oop-in-java-abstraction-and-encapsulation/)

#### Reference
[oop concepts](https://www.section.io/engineering-education/oop-in-java-abstraction-and-encapsulation/)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
Is this article part of a series with ```https://github.com/section-engineering-education/engineering-education/pull/3239```. We usually encourage contributors to cover all aspects in a single article. Thanks

**Comment by Frank-dev20** [comment]
> Is this article part of a series with `https://github.com/section-engineering-education/engineering-education/pull/3239`. We usually encourage contributors to cover all aspects in a single article. Thanks

OOP is a very wide concept and conceptual understanding of the core principles is very necessary. This article seeks to give an in-depth explanation of the principle of inheritance and Polymorphism. The pull request referred to explained abstraction and encapsulation but that isn't all there is in OOP. Although this article can be as seen a continuation of the one you're referring to as they both explain OOP principles, they are all altogether different OOP principles explained in each.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
