### ISSUE TITLE
[API]Working with superhero API

### ISSUE THREAD

**Issue by victorelvice** [section-engineering-education/engineering-education#3989]
#### Proposed title of article
[API]Working with superhero API

#### Proposed article introduction
The superhero API is a collection of data from all the superheroes from the comic world. It consists of information such as name,  Intelligence,  Strength,   Speed,   Durability,   Power,   Combat among others. This information is presented in JSON format for accessibility.

This article focuses on building an application that fetches information about all the superheroes and display them efficiently. We will build a web application to consume the API data with bootstrap styling. Should this article be published,  the reader will be able to consume an API endpoints in their projects.
 
#### Key takeaways 
1. Working with JSON
2. Data presentation from an API
3. Consuming the Superhero API data

#### Article quality
This article covers an API that most developers have not tried working with. Besides, most APIs are only tried using Postman and Insomnia but the real implementation in a web app is rare. For this reason, this article illustrates how to consume Superhero API in webpage and provided addition bootstrap styling. It emulates working on a full-stack web project with a backed but in this case we have data already.

#### References
- https://superheroapi.com/

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@victorelvice 
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any [official docs and/or what is covered in other blog sites. ](https://www.google.com/search?q=Working+with+superhero+API&ei=sKRTYeOhMqPB7gLh672gAw&ved=0ahUKEwjjuezd6KLzAhWjoFsKHeF1DzQQ4dUDCA4&uact=5&oq=Working+with+superhero+API&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABMgUIIRCgAToHCAAQRxCwAzoHCAAQsAMQQ0oECEEYAFDD8AFYw_ABYLTyAWgCcAJ4AIABeIgBeJIBAzAuMZgBAKABAqABAcgBCsABAQ&sclient=gws-wiz)(the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by victorelvice** [comment]
Hello can someone please open this issue for me. I am done working on the article.
