### ISSUE TITLE
Difference in Inheritance, Abstraction and Encapsulation

### ISSUE THREAD

**Issue by jamarh35** [section-engineering-education/engineering-education#3995]
**Introduction**
Inheritance in OOP is where a class commonly known as the child class inherits the attributes and methods of another class which is the parents class.
Abstraction on the other hand is a concept in OOP that allows the programmer to hide unnecessary information. It's main purpose is to hide non-essential information from the users.
Lastly, Encapsulation is a mechanism of bundling or hiding data in to restrict direct access to some components of an object. It hides values of data objects inside class. 

The article proposed is aimed to help the user grasp the main pillars in OOP and get the differences in them.
Different from the official documents, the article will use easily understood codes and programs to help the user get the idea in depth. A tech tutorial will also be used so as the user can engage themselves as they learn.

**Reference**
N/A

**Comment by WanjaMIKE** [comment]
**https://github.com/section-engineering-education/engineering-education/pull/3239**

**Comment by WanjaMIKE** [comment]
Check the above PR

**Comment by WanjaMIKE** [comment]
they seem to be similar
