### ISSUE TITLE
USING AIRCRACK-NG IN KALI LINUX

### ISSUE THREAD

**Issue by Wkd-Cyber** [section-engineering-education/engineering-education#3996]
**Introduction**
Wireless connectivity has become a norm nowadays. It's efficient in running some of the day-to-day activities. It's therefore important to ensure you have a secure WiFi connection. As a Pentester, Aircrack-ng is your tool. 

Aircrack-ng is a network software suite consisting of a detector, packet sniffer, WEP and WPA/WPA2-PSK cracker, and analysis tool for 802.11 wireless LANs. It works with any wireless network interface controller whose driver supports raw monitoring mode you can use it to monitor WiFi security, capture data packets, and export them to text files for additional analysis. You can also use it to attack and crack WPA and WEP protocols

**Reference**
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@Wkd-Cyber 

We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites.](https://www.google.com/search?q=USING+AIRCRACK-NG+IN+KALI+LINUX&ei=HKZTYdf4E_e90PEPhvOlqAE&ved=0ahUKEwjX9paL6qLzAhX3HjQIHYZ5CRUQ4dUDCA4&uact=5&oq=USING+AIRCRACK-NG+IN+KALI+LINUX&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjoHCAAQRxCwAzoICC4QkQIQkwI6BQgAEJECOg4ILhCABBCxAxDHARCjAjoOCC4QgAQQsQMQxwEQ0QM6CAguELEDEIMBOgsILhCABBDHARCjAkoECEEYAFCiuQhYlckIYITNCGgDcAJ4AIABeogB6wGSAQMwLjKYAQCgAQGgAQKwAQDIAQjAAQE&sclient=gws-wiz)

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by Wkd-Cyber** [comment]
Hi @hectorkambow 
Different from the official documentation, this article is clear-to-follow-through with clear illustrations on how to install some of the crucial programs and major obstacles to avoid during the penetration testing process.
It uses the dictionary attack which generates greater results and has little limitations compares to other methods used eg PTW approach(Pyshkin, Tews, Weinmann) which can only crack 40 and 104 bit WEP keys.

Terms used are easy to understand and relevant examples simple to understand are used so that the reader can be able to follow through without any glitches even if he/she is a beginner in computer networking and programming. Thanks

**Comment by ahmadmardeni1** [comment]
This is a sensitive topic and Aircrack-Ng can be used by black hat hackers. Please feel free to suggest an alternate topic to explore. 🚀 @Wkd-Cyber
