### ISSUE TITLE
How to plot a candlestick chart in python using the matplotlib finance API and moving average

### ISSUE THREAD

**Issue by smkinyan** [section-engineering-education/engineering-education#4002]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

[Machine Learning] How to plot a candlestick chart in python

#### Proposed article introduction

`matplotlib finance` API makes it easier to create financial plots. It interfaces nicely with Pandas DataFrames. The new API automatically does the extra `matplotlib` work that the user previously had to do "manually" with the old API. In this tutorial, we'll be using the matplotlib finance api to plot share prices. We will use data from yahoo finance in this tutorial.
This tutorial will be important to anyone looking to start plotting share prices using Python.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to:
1. Learn how to install the matplotlib finance API
2. Learn how to acquire datasets from Yahoo finance.
3. Plot share prices using Python.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [Matplotlib Finance API](https://github.com/matplotlib/mplfinance#newapi)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@smkinyan 

We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites.](https://www.google.com/search?q=How+to+plot+a+candlestick+chart+in+python+using+the+matplotlib+finance+API&ei=Aq1TYae2Fo6r0PEP4oKBmAI&ved=0ahUKEwinv6XV8KLzAhWOFTQIHWJBACMQ4dUDCA4&uact=5&oq=How+to+plot+a+candlestick+chart+in+python+using+the+matplotlib+finance+API&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABQ394EWN_eBGCh4ARoA3ACeACAAViIAViSAQExmAEAoAECoAEByAEIwAEB&sclient=gws-wiz)

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by smkinyan** [comment]
@hectorkambow Thank you for asking. In addition to using the `mpllfinance api`, this tutorial will also implement the moving average function which is commonly used when analyzing cryptocurrencies. Many blog sites have used candlestick to plot in Python, but not many have used Candlestick charts in Python with Moving Average. I'll also show how this can be applied to some cryptocurrencies using data from [CoinAPI](https://www.coinapi.io/)

**Comment by smkinyan** [comment]
@hectorkambow @lalith1403

**Comment by WanjaMIKE** [comment]
closed #4002 via #4212
