### ISSUE TITLE
[Android] Understanding Different Types of Menus in Android with Kotlin

### ISSUE THREAD

**Issue by benta-odek** [section-engineering-education/engineering-education#4003]
#### Proposed article introduction
In Android applications, menus are essential building blocks. In this tutorial, you will learn how to design and show menus in your Android apps. 

Why do we need menus:
- To free up screen space
- To perform different operations
- Navigating to other part of the application

We'll look at three different types of menus:
- Options menu
- Contextual menu
- Popup menu

#### Key takeaways 
- You'll learn about the different types of menus.
- How to create  menus
- You'll learn how to build advanced menus like checkable menus and intent-based menus.
- Design guidelines and best practices for Menus

### Conclusion
After completing this tutorial, you'll have the skills and understanding of Android menus necessary to create efficient and user-friendly menus in your Android apps.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
Pinging our resident expert on Kotlin @LinusMuema 

For some added insight. 🚀

**Comment by benta-odek** [comment]
hello @LinusMuema and @hectorkambow 
I understand there is an official documentation on menus and to avoid the duplication of the same,  adding custom approach to the tutorial so as to prevent the conflict would be appropriate. In the tutorial:
-  i will explain on how to integrate different menus to work together in a fully production application.
- when people create menus they are often confused or not sure of what menu to use in different part of the application ,so in the article I'll clarify and eliminate this confusion.
- Also it would be appropriate to clarify the guidelines and best practices when it come to designing menus.
