### ISSUE TITLE
Implementing web animations using jquery

### ISSUE THREAD

**Issue by GeoffreyKangu** [section-engineering-education/engineering-education#4004]
#### Proposed title of the article
Implementing web animations using Jquery.

#### Proposed article introduction
In modern days, many people prefer to visit attractive web pages. This brings in the use of animations on a web page. Jquery is a javascript library that is better used for implementing web animations. It is used to make HTML document traversal and manipulation, event handling, and animation much simpler with an easy-to-use API that works across a multitude of browsers

In this tutorial, we shall discuss the following three sub-topics:
 * DOM manipulation using Jquery
 * Web animations using JQuery
 * Events using jquery
This tutorial will take us through how these sub-topics are implemented in an HTML document.

#### Key takeaways 
After reading through this tutorial, the reader should be able to have a better understanding of Jquery.
The reader should be able to animate website content using Jquery.
Since this tutorial also takes us through events using Jquery, the reader should be able to understand the concept of event handling.
After reading this tutorial, the reader should be able to have a better understanding of the Document Object Model as I will focus on it.

#### Article quality
In this tutorial, we shall have a different web page, that is I shall create a web page that shall be used to implement the three topics that I shall discuss above. This shall be a simple web page to implement DOM manipulation, Web animations, and Event handling using Jquery.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by hectorkambow** [comment]
@GeoffreyKangu 
We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites.](https://www.google.com/search?q=Implementing+web+animations+using+jquery&ei=q61TYaXxKdXR9APF-ZKYBA&ved=0ahUKEwjl8oOm8aLzAhXVKH0KHcW8BEMQ4dUDCA4&uact=5&oq=Implementing+web+animations+using+jquery&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeOgcIABBHELADSgQIQRgAULiOBVi4jgVg4ZAFaAJwAngAgAFciAFckgEBMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz)

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.
