### ISSUE TITLE
[Networking] Understanding the Basic WLAN  Networking Architecture

### ISSUE THREAD

**Issue by LynetteMwe** [section-engineering-education/engineering-education#4010]
#### Proposed title of article
[Networking] Understanding the Basic WLAN  Networking Architecture

#### Proposed article introduction
Network devices and services are structured in different ways in order to enable the connection of client devices to the network.

This article intends to give the reader an understanding of the Fat AP and Fit AP + AC architectures and the applicable scope of both architectures.

#### Key takeaways 
1. Introduction to the Basic WLAN Networking Architecture
2. Fat AP Architecture
3. Fit AP Architecture
4. Applicable scope for both the Fat AP and Fit AP + AC architecture.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

We are looking for programmer-centric concepts explained in fun and intuitive ways.
Please feel free to suggest an alternate topic to explore. 🚀
