### ISSUE TITLE
[Languages] Stream Filter in Java using Lambda Expressions

### ISSUE THREAD

**Issue by carowanjiku** [section-engineering-education/engineering-education#4011]
### Topic Suggestion
Stream Filter in Java using Lambda Expressions

### Proposed article introduction
The filter() function in the Java stream allows you to filter stream elements based on a provided criterion. This method accepts a predicate as a parameter and returns a stream of resulting elements as a result.

In this tutorial, we will look at how to use the Stream. filter() function in Java when working with Streams. We will look at how to utilize it and how to deal with checked exceptions in specific instances and lambda expressions. 

### Key takeaways 
The reader will learn the following concepts:

- Overview of Stream Filter in java.
- How we use Stream.filter().
- Collection filtering.
- Using Multiple criterial to filter collection.
- Ways of handling exception.

#### Article quality
This will be a unique article explaining  Java Stream Filter with Lambda Expression in depth. It will have a step-by-step explanation to help the reader understand the concepts in a better way.

### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
This topic is already covered by other blog sites - How are you planning to make this article unique/original? @carowanjiku

**Comment by carowanjiku** [comment]
Hi, @ahmadmardeni1 
This article will be beginner-friendly, and I will make the code snippets short and simple for all the audiences to understand easily. I will write a unique article that adds value beyond other official docs or what is covered in other blog sites. My article will go beyond a basic explanation and include a step by step explanation to ensure that it helps the rest of  EngEd.
Thank you.

**Comment by ahmadmardeni1** [comment]
Okay, make sure you are building a unique project. @carowanjiku 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
