### ISSUE TITLE
HTML to PDF in Javascript using jsPDF with Example Download

### ISSUE THREAD

**Issue by Danco10** [section-engineering-education/engineering-education#4012]
#### Proposed title of article
HTML to PDF in Javascript using jsPDF with Example Download

#### Proposed article introduction
It's easier to convert HTML to PDF in JavaScript than it is to create PDF on the server. It should be flexible to acquire the source in any manner when adding a feature to make PDF from HTML. HTML string HTML object with selector reference HTML string HTML object with selector reference HTML object with selector reference HTML object with selector reference HTML object with selector reference HTML object with selector reference HTML object with selector reference HTML object with selector
HTML documents
jsPDF To create a PDF, the JavaScript library accepts a variety of input formats. It uses the dompurify dependency to make PDF from HTML, for example.
The best JavaScript library for creating PDFs on the client-side is jsPDF. This tutorial will show how to use JavaScript to create a PDF from an HTML file.

#### Key takeaways 
1. Existing tools to create PDF
2.Create UI to upload source HTML
3.jsPDF function to create PDF in JavaScript
4.upload HTML file

#### Article quality
I will use modern javascript and the code snippets will be easy to understand and implement by both novices and experts

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

We are looking for programmer-centric concepts explained in fun and intuitive ways.
Please feel free to suggest an alternate topic to explore. 🚀
