### ISSUE TITLE
[Networking]Understanding Cellular Communication Systems

### ISSUE THREAD

**Issue by lizpart** [section-engineering-education/engineering-education#4013]
#### Proposed title of article

[Networking]Understanding Cellular Communication Systems

#### Proposed article introduction

Cellular communications systems are wireless mobile communications systems that divide a large geographic area into cells, each with a low-power wireless transmitter, for the purpose of utilizing the use of a limited number of frequencies.
Different power levels make cells to be divided usually in the shape of hexagons according to user population and demand in a specific geographic region.
As the mobile subscriber travels from one cell to another, the conversation is maintained by "hand-off" between cells to maintain smooth service.
Cells can as well be increased and channels are reused to facilitate the increasing number of subscribers.
In the article, we will learn and understand the basic concepts of cellular communication systems and their architecture.

#### Key takeaways 

1. Learner will understand the cell concept.
2. Learner will understand how cell sizing and shaping are done.
3. Learner will learn capacity improvement methods.
4. Learner will understand how frequency reuse occurs.
5. Learner will understand how handoff occurs.

#### Article quality

This article contains up-to-date information and has improvements on other existing articles. It is easier to understand since the language used has reduced the technical terms.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

We are looking for programmer-centric concepts explained in fun and intuitive ways.
Please feel free to suggest an alternate topic to explore. 🚀
