### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by NyongToro** [section-engineering-education/engineering-education#4014]

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
Please make sure that you are building a unique project, not repeating what is already in the docs. @NyongToro 

Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by ahmadmardeni1** [comment]
And also please explain other charts, not only line and bar charts. @NyongToro

**Comment by Tioumoh** [comment]
@ahmadmardeni1 
I'll be sure to accommodate all your recommendations. Thanks
