### ISSUE TITLE
[Languages]Understanding CSS pseudo classes and pseudo elements

### ISSUE THREAD

**Issue by AmosAsuquo** [section-engineering-education/engineering-education#4015]
**Proposed title of article**
[Languages]Understanding CSS pseudo classes and pseudo elements

**Proposed title introduction**
	Cascading style sheet (CSS) is an independent language used for styling web applications. A very useful feature of CSS is its pseudo classes and pseudo elements.
	In this tutorial, with the aid of a handful of examples we will be exploring the possibilities of pseudo elements and pseudo classes, their peculiarities and differences as well as compatibility in other to make implementation as easy as possible.

Key takeaways 
i.	Understanding what a pseudo class is, its uses and limitations in CSS.
ii.	Understanding what a pseudo element is, its uses and limitations in CSS.
iii.	Using CSS pseudo elements to alter HTML.
iv.	Using CSS pseudo class to add interactivity.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
This topic is already covered by [other blog sites](https://www.google.com/search?q=CSS+pseudo+classes+and+pseudo+elements&oq=CSS+pseudo+classes+and+pseudo+elements&aqs=edge..69i57j69i61.418j0j1&sourceid=chrome&ie=UTF-8). How are you planning to make your article unique/original? @AmosAsuquo

**Comment by AmosAsuquo** [comment]
Thank you for the observation. I plan to go beyond the basics of the topic and make it more practical oriented. At the end of the tutorial users would get a grasp of the implementation and how CSS pseudo elements/classes can be consumed in real life scenarios. I'll be supporting this with a ton of unique examples to make it beginner friendly and also an envy by experts. Cheers ☺

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @AmosAsuquo 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
