### ISSUE TITLE
[Languages] Creating Queries in C# using LINQ

### ISSUE THREAD

**Issue by neheMaish** [section-engineering-education/engineering-education#4019]
#### Proposed title of article
Creating Queries in C# using LINQ

#### Proposed article introduction
The LINQ extension methods for the IEnumerableT> interface are used when searching local in-memory collections (often referred to as LINQ to Objects).... The method is implemented as an iterator to achieve deferred execution, which means the values are returned using the yield return statement.

The LINQ in c-Sharp is what shall be used in creating the queries. In this article, we will have to look deeply at how the queries are created until they become functional producing an end result.

#### Key takeaways 
1.  How to create an in-Memory Data Source.
2.  How to create a query after developing the data source
3. How to modify the created query

#### Article quality?
This article will be majoring on covering content that will provide an in depth knowledge to the learner on how queries are created and how they perform their task.

#### References
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
This topic is already covered by the [official docs](https://docs.microsoft.com/en-us/dotnet/csharp/linq/write-linq-queries).

Please feel free to suggest an alternate topic to explore. 🚀 @neheMaish
