### ISSUE TITLE
[Languages] JavaScript asynchronous programming concepts.

### ISSUE THREAD

**Issue by wanjadeno** [section-engineering-education/engineering-education#4024]
### Topic Suggestion
JavaScript asynchronous programming concepts.

#### Proposed article introduction
A function must wait until an API's data is fetched. When a process is called, it may take some time before the value it returns is returned. Asynchronous programming addresses this problem.
Apps would take an eternity to load without asynchronous programming.

In this tutorial, we will talk about asynchronous programming and how it helps a user flow smoothly through an application.

#### Key takeaways 
- What is asynchronous programming?
- How asynchronous programming works
- Asynchronous functions
- Common use cases
- When to use asynchronous functions

#### Article quality
This article will be a detailed step-by-step guide on asynchronous programming concepts in JavaScript. It also focuses on how we can use this concept. 

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by WanjaMIKE** [comment]
Unfortunately, asynchronous functions are already used in numerous react and node articles. For instance, this one -> ```https://www.section.io/engineering-education/how-to-consume-data-from-an-api-in-react/``` Feel free to suggest another topic. Thanks
