### ISSUE TITLE
How to remove write protection from USB flash drive

### ISSUE THREAD

**Issue by ghost** [section-engineering-education/engineering-education#4026]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
How to remove write protection from USB flash drive
Use keyword research to improve your article's SEO.

#### Proposed article introduction
If your USB drive gives you an error on a Windows computer, you might think it's broken and useless. The flash drive becomes read-only, and you are unable to manipulate data on it, such as copying, deleting, or writing files to the disk. How do you unprotect a read-only flash disk from being written to? In Windows 10/8/7, we'll show you how to disable write protection on a flash drive, SD card, or pen drive.

#### Key takeaways 
By the end of this topic the learner will be able to understand:

- Read-only flash drive
- Why is the USB drive read-only
- How to remove read-only flash drive on windows
- How to remove read-only flash on mac

#### Article quality
The article is unique since I have not found any topic dealing with such an article in  search box

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by ahmadmardeni1** [comment]
We are looking for programmer-centric concepts explained in fun and intuitive ways.

Please feel free to suggest an alternate topic to explore. 🚀
