### ISSUE TITLE
Introduction to Hibernate

### ISSUE THREAD

**Issue by morwabe1234** [section-engineering-education/engineering-education#4029]
#### Proposed title of the article
Introduction to Hibernate

#### Proposed article introduction
Hibernate is a Java framework that makes it easier to create Java applications that interface with databases. Hibernate also allows you to query and retrieve data.
It creates SQL calls, freeing the developer from having to manually handle and convert the query results. In this article, we are going to at an overview of hibernate, the architecture of hibernate, installation process, advantages and disadvantages of hibernate and a hibernate example.

#### Key takeaways 
What is hibernate?
The architecture of Hibernate.
installation process.
Advantages and disadvantages of hibernate.
Hibernate example

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Can you build a unique/original project using Hubernate? The tutorial can't just be about the installation process. @morwabe1234

**Comment by morwabe1234** [comment]
> Can you build a unique/original project using Hibernate? The tutorial can't just be about the installation process. @morwabe1234

@ahmadmardeni1 I have made additional changes as requsted.

**Comment by ahmadmardeni1** [comment]
Okay great, make sure the example is a unique/original project. @morwabe1234 

Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
