### ISSUE TITLE
[Machine Learning] Building a Deep Learning Selfie Segmentation Web App using Gradio

### ISSUE THREAD

**Issue by lcheptoo** [section-engineering-education/engineering-education#4034]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

[Machine Learning] Building a Deep Learning Selfie Segmentation Web App using Gradio

Use keyword research to improve your article's SEO.

#### Proposed article introduction

In this tutorial, we are going to build a selfie segmentation model using Mediapipe, Gradio and Python. The selfie segmentation model allows us to quickly and easily strip out the background from photos using a pre-built machine learning model.

We’re going to take it one step further and integrate it to a Gradio app!

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to:
- Install Mediapipe and Gradio
- Apply selfie segmentation using OpenCV
- Integrate the selfie model into the Gradio app

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [MediaPipe](https://mediapipe.dev/)
- [Gradio](https://www.gradio.app/)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by WanjaMIKE** [comment]
Closed #4034 via #4141
