### ISSUE TITLE
Basic Networking Routing Protocols

### ISSUE THREAD

**Issue by apondi-911** [section-engineering-education/engineering-education#4046]
#### Proposed title of article

Basic Networking Routing Protocols

#### Proposed article introduction
Routing is a process by which packets choose an optimal path from one network to another.

A routing protocol is a formula that routers use to determine the appropriate path onto which data should be forwarded. These routing protocols help routers to learn about the routes, by having each router advertise the routes it knows. Routing protocols are categorized into three : 
 - Static routing protocols
 - Default routing protocols
 - Dynamic routing protocol
 
 We will dig in deep on the types of routing protocols like : Interior Gateway Protocol (IGP), Exterior Gateway Protocol
(EGP). These protocols do not move the information from the source but only update the routing table that contains the information.

#### Key takeaways 
- Learn the available routers present in the  enterprise network
- Build routing tables
- Selecting the most optimal path through the network
- Learn how to use Cisco packet tracer

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
👋  

@apondi-911 Follow - up question.

We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or via many other blog sites.

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by apondi-911** [comment]
I will be doing much of the commands used in Cisco packet tracer that are used to make connections
