### ISSUE TITLE
Introduction to Spring Framework

### ISSUE THREAD

**Issue by BarasaG** [section-engineering-education/engineering-education#4048]
#### Proposed title of article
Introduction to Spring Framework

#### Proposed article introduction
The Pivotal Software Company invented and built Spring, a Java-based application framework.
Spring is a programming framework for developing enterprise applications. Because of its extensive library and features, we can easily construct web-based apps.
We'll talk about Spring 5 in this tutorial, which is the most recent and updated version of the traditional Spring framework.

#### Key takeaways 
1. Introduction
2. Dependency Injection and Inversion of Control (IOC)
3. Advantages of spring framework
4. Modules
5. Examples
#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Make sure to build a unique/original project, and not just repeating the docs.

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any [existing EngEd articles](https://www.section.io/engineering-education/search/?q=spring), articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
