### ISSUE TITLE
 [SECURITY] INTRODUCTION TO PHISHING ATTACKS

### ISSUE THREAD

**Issue by kwennB** [section-engineering-education/engineering-education#4053]
#### Phishing Attack: 
This is the act of sending impersonated messages or links of various forms to people. Whilst appearing to be from a reliable source. The aim of a phishing attack is to steal delicate information. This includes data like login details, bank account passwords, etc. 
They have spoofed messages outlined to trick people to share confidential details. In this article, we will discuss the various kinds of phishing attacks. Also, the precautions to take to avoid their implications. 

#### KEY TAKEAWAY

* What is a phishing attack
* Types of phishing attack
* Examples and characteristics of phishing attacks
* How to identify Phishing attacks
* Recommended ways to protect your systems and ways to prevent phishing attacks

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.

We are looking for programmer-centric concepts explained in fun and intuitive ways.
Please feel free to suggest an alternate topic to explore. 🚀
