### ISSUE TITLE
[Machine Learning] Understanding Support Vector Machine(SVM) algorithm 

### ISSUE THREAD

**Issue by jmuchina** [section-engineering-education/engineering-education#4055]
#### Proposed title of article
Understanding Support Vector Machine(SVM) algorithm 

#### Proposed article introduction
This supervised machine learning approach, known as the Support Vector Machine (SVM), can be used to tackle problems in classification and regression. Classification problems are the most common application for this technique. N is the number of features you have, and the value of each component is the value of a specific coordinate. 

The SVM algorithm plots each data point as a point in n-dimensional space. This tutorial will talk about Support Vector Machine(SVM) algorithm in detail.

#### Key takeaways 
By the end of this tutorial the reader will have understood the following;

- What is Support Vector Machine?
- How does it work?
- How to implement SVM in Python and R?
- How to tune Parameters of SVM?
- Pros and Cons associated with SVM

#### Article quality
My article will be approachable for readers, and my code examples will be clear and concise so that they can be understood by a wide range of people.
The Support Vector Machine(SVM) algorithm will be demonstrated in my article by creating an actual file, which will make the tutorial more practical and more straightforward to grasp.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @jmuchina 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@jmuchina 

We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites.](https://www.google.com/search?q=Understanding+Support+Vector+Machine%28SVM%29+algorithm&ei=TKNXYfvZK8vbtAaYnqfIDw&ved=0ahUKEwj7r4X8t6rzAhXLLc0KHRjPCfkQ4dUDCA8&uact=5&oq=Understanding+Support+Vector+Machine%28SVM%29+algorithm&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEBYQHjIFCAAQhgMyBQgAEIYDMgUIABCGAzoHCAAQRxCwA0oECEEYAFDjmwVY45sFYIGeBWgGcAJ4AIABZIgBZJIBAzAuMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz)

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by jmuchina** [comment]
Hello, @hectorkambow 
I have looked at the suggested articles; I will write a well-explained article for readers to grasp the concepts more efficiently. I will also add more information on it such as (how to select vector machines kernels) which is not in the blogs you mentioned to make the article more unique and more helpful
Thank you.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by jmuchina** [comment]
Hello, @hectorkambow 
Would you open this suggestion the article is ready I'm sorry for the delays.
Thank You

**Comment by jmuchina** [comment]
can anyone reopen this for me please

**Comment by jmuchina** [comment]
@Ericgacoki  thank you.
