### ISSUE TITLE
[Node.js] How to deploy a Node.js + Docker API to Heroku

### ISSUE THREAD

**Issue by olumidayy** [section-engineering-education/engineering-education#4057]
#### Proposed title of article

[Node.js] How to deploy a Node.js + Docker API to Heroku

#### Proposed article introduction

The deployment of an app is the final and most important stage in it's development life cycle. There are some tools that help us with this stage and make it easier for us. In this article, we will cover how two of these tools namely, Docker and Heroku, can be used hand-in-hand to deploy Node.js apps.

#### Key takeaways 

At the end of the article, readers should:
- Be able to build a server with Express.
- Have a basic understanding of docker and why we use it.
- Be able to dockerize a Node.js app.
- Be able to deploy a dockerized Node.js app to Heroku. 

#### Article quality

This article doesn't just go straight to the deployment process but explains the steps involved, one after the other. It explains what we're trying to do and why we're doing it. While there are some articles that cover segments of this article, it's one of the very few that covers both the containerization and deployment of Node.js apps.

#### References

- https://docs.docker.com/language/nodejs/build-images/
- https://devcenter.heroku.com/articles/container-registry-and-runtime

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @olumidayy 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@olumidayy 

👋 
Welcome - Hector here.

Seems like a very cool topic - but regarding Node.js we have more than enough currently in our EngEd library as we did a big push the last few months and are currently not accepting any more Node.js articles to publish for the time being.

Please feel free to suggest an alternate topic to explore. 🚀
