### ISSUE TITLE
[Machine Learning]Deploying an Image Classification Model Using FastAPI

### ISSUE THREAD

**Issue by TimedH** [section-engineering-education/engineering-education#4059]
###[Machine Learning]Deploying an Image Classification Model Using FastAPI
### Proposal Submission

####[Machine Learning]Deploying an Image Classification Model Using FastAPI

#### Proposed article introduction
The quality and quantity of annotated data are critical components of any machine learning effort. When the API is implemented, it is one of the important aspects that will influence the quality of the forecasts.

You may use the Image Classification API to classify various objects in your application. It allows you to create your own classification model for categorizing photographs in a category using your dataset. Nanonets are cloud-based services for developing, training, and deploying deep learning models.

#### Key takeaways 
What is FastAPI?
Making API
Image Recognition API
Annotation of Data
Data Augmentation
Deploying the App

#### Article quality
My article will be easily understood and approached by the readers because i will explain step by step sequence on how to deploy an image classification using FastAPI.And by the end of the article the reader will be able to deploy an image classification by themselves.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @TimedH 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Hello @TimedH, Upon a quick google search, there are several articles on this topic. Can you explain how your article will be different from the ones that exist. Thank you.

**Comment by TimedH** [comment]
Hello, unlike the other articles, my article will be easily understood and approached by the readers because I will explain step by step sequence on how to deploy an image classification using FastAPI.

**Comment by TimedH** [comment]
Hello @lalith1403, unlike the other articles, my article will be easily understood and approached by the readers because I will explain step by step sequence on how to deploy an image classification using FastAPI.

**Comment by lalith1403** [comment]
There are many articles on this topic in the eng ed repository. I feel this topic is covered well in the already published articles.

**Comment by TimedH** [comment]
ok...thanks
