### ISSUE TITLE
Integrating Firebase Notifications in React Native 

### ISSUE THREAD

**Issue by Gautham495** [section-engineering-education/engineering-education#4064]
### Topic Suggestion

Integrating Firebase Notifications in React Native 

#### Proposed title of article
Firebase Notifications in React Native 

#### Proposed article introduction

Notifications are integral part of a mobile application which will grab the user attention and will increase the engagement of your app. Apps like Instagram have used notifications to make users come back to their application when some events like when someone comments in your post or if some one follows your account.

Firebase offers a service called Firebase Notifications which enables developers to send notifications from the firebase dashboard or from their own server. We will be grabbing the FCM Token of the particular user's mobile phone and then we can send personalised notifications just like how Instagram does. In this article we will be looking into how we can integrate firebase in our react native application and send notifications from our firebase dashboard and as well as from postman.

#### Key takeaways 

1. Understanding how Firebase notifications work.
2. Understanding the concept of FCM Tokens and using them to send personalised notifications.
3. Integrating Firebase notifications in React Native
4. Getting to know how we can send notifications from firebase dashboard, postman and as well as our own server. 

#### Article quality

There are very few articles in the internet which discuss about firebase notifications with react native and many of them are outdated with article containing react native version less than 60.0 and a lot of them do not work right now when we try to integrate with the help their articles.
This article will focus on React Native 65.0 and will feature step by step integration of firebase notifications in react native.
This article will focus on each and every step needed to integrate firebase notifications in a react native app. 
As I am a react native developer and I have successfully integration firebase notifications in my react native application in google play store, I can explain what I am doing in all the steps.

So this article will be unique from any other article in the internet and will be up to date with the current react native version and provide a lot of value to developers who are struggling to integrate firebase notifications in their react native app.

#### References
https://firebase.google.com/docs/cloud-messaging
https://stackoverflow.com/questions/37671380/what-is-fcm-token-in-firebase
https://reactnative.dev/docs/next/getting-started

### Conclusion

By reading the whole article about integrating firebase notifications in react native, developers will have all the knowledge to start sending notifications to their app users.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Gautham495 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@Gautham495 

We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites.](https://www.google.com/search?q=Firebase+Notifications+in+React+Native&ei=h6RXYfH6AcHRtAbH97-QDw&ved=0ahUKEwix2vWRuarzAhXBKM0KHcf7D_IQ4dUDCA8&uact=5&oq=Firebase+Notifications+in+React+Native&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEAgQHjoHCAAQRxCwA0oECEEYAFCRPVjVQGCARGgCcAJ4AIABdIgBwAGSAQMxLjGYAQCgAQHIAQjAAQE&sclient=gws-wiz)

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by Gautham495** [comment]
In my article,
1. I will discuss about how to integrate notifications in a react native android platform from the scratch.
2. After integrating the firebase notifications in the code, I will explain what is FCM Token and how can we store it in the backend and send personalised notifications to users.

After clearly explaining about the above topics, I will explain how to change notification icons in your react native application. I have seen big enterprises use wrong notification icons and their notification icons will not show properly. There are not a lot of articles which explain about integrating notification icons in your react native application which will improve user experience in the long run.

So I will explain in detail all there is to integrate notifications in react native with firebase, what is FCM token and how to use notification icons in firebase notifications.

By the reading my article the developer will be able to integrate firebase notifications in both his react native application and get a way to integrate firebase messaging in his backend.
