### ISSUE TITLE
[Time Triggered Azure Functions] A Guide To Background Tasks Using C# 

### ISSUE THREAD

**Issue by nicasious** [section-engineering-education/engineering-education#4068]
#### Proposed title of article
[Time Triggered Azure Functions] - A Guide To Background Tasks Using C# 

#### Proposed article introduction
In this post, we will learn about schedule background activities using Time-Triggered Azure Functions.
With the assistance of the Time Trigger Azure Function, we may execute a particular activity or function at a predetermined time. To put it another way, this function may be used for processing jobs in the background. It can assist you in running a characteristic according to a custom schedule. CRON expression (timing information) is kept in an Azure storage account and then provided to the element on execution, as opposed to HTTP-induced Azure features. As a result, once you have uploaded a timer-triggered function for the first time, you may have to take additional procedures to run your function app business domestically.

#### Key takeaways 
- Project Setup
- What we are going to Build?
- Table Schema - SQL Database
- What is CRON expression?
- Configure the CRON expression
- Configure the Functions
- Disabling a Function
- Testing the Functions

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @nicasious 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@nicasious 

Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double check that it does not overlap with any existing EngEd articles, [articles on other blog sites](https://www.google.com/search?q=Background+Tasks+Using+C%23&ei=zqRXYZrPHoG5tQbw7aWoCQ&ved=0ahUKEwia7v-zuarzAhWBXM0KHfB2CZUQ4dUDCA8&uact=5&oq=Background+Tasks+Using+C%23&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEM0CMgUIABDNAjIFCAAQzQI6BwgAEEcQsANKBAhBGABQuZAEWPqbBGDOngRoAXACeACAAd0BiAGlBZIBBTQuMS4xmAEAoAEByAEIwAEB&sclient=gws-wiz), or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
