### ISSUE TITLE
PROBABILITY DISTRIBUTION WITH MATLAB

### ISSUE THREAD

**Issue by alpho361** [section-engineering-education/engineering-education#4070]
#### Proposed article introduction
Probability is a numerical reflection of the likely occurrence of a particular event. The probability distribution function is the function that relates to the probability of occurrence of different results that can come in an experiment.
 Matlab provides us with inbuilt functions that can be used in the calculation of probability distribution functions(PDF), also the probability distribution objects in Matlab allows the user to fit a probability distribution to sample data, from the sample data one can perform analyses on the distribution object.
Probability knowledge helps in making predictions and estimates, this is a useful part in research and investigation.

#### Key takeaways 
-Skill for using probability objects in matlab.
-Plotting probability distribution graph.
- Solving probability distribution problems with Matlab.
- Data analysis based on probability.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @alpho361 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Thank you for the topic suggestion  @alpho361 , however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
