### ISSUE TITLE
[Languages] Everything you need to know about Ionic Angular

### ISSUE THREAD

**Issue by john-amiscaray** [section-engineering-education/engineering-education#4074]
#### Proposed title of article

Everything you need to know about Ionic Angular

#### Proposed article introduction

Nowadays, the line has begun to blur between mobile applications and web applications. Through the use of new native APIs, you can use the web to create applications indistinguishable from native mobile apps. One cool tool you can use to do this is the Ionic framework.

In this guide, we will have a look at everything you need to know to get started with Ionic Angular. As someone who just learned this technology to build a large app, my goal is to get you started well. This includes avoiding pitfalls and answering any questions I had in my learning process. With this, you can start building cross-platform applications of your own!

#### Key takeaways 

- What is Ionic?
- How to get started with an Ionic Angular project.
- Project structure and architecture.
- Generating an android application from your project.
- A few tools to add mobile features into your application.

#### Article quality

This guide is a getting started guide based on what I personally wish I knew when getting started with this technology, and my teaching styles. While the Ionic documentation gives a good in-depth explanation of many of the fundamental concepts in separate modules, I thought I'd give a more general overview of everything and a more condensed format. Along the way, I'll add my own commentary about things I personally was confused about, and add in some extra things I wish I knew as a beginner. Then afterward, if the beginner needs more depth about each concept, they can go back to the official docs.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
👋 

Thank you for submitting an article suggestion - it seems like its could be a helpful topic.
We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites.](https://www.google.com/search?q=Everything+you+need+to+know+about+Ionic+Angular&ei=ladXYdWDEMy0tQbcvKOQAQ&ved=0ahUKEwiVovWGvKrzAhVMWs0KHVzeCBIQ4dUDCA8&uact=5&oq=Everything+you+need+to+know+about+Ionic+Angular&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABMgUIIRCgATIFCCEQqwIyBQghEKsCMgUIIRCrAjoHCAAQRxCwA0oECEEYAFDanw9Y2p8PYPurD2gCcAJ4AIABeIgBeJIBAzAuMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz)

Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by john-amiscaray** [comment]
> 
> 
> 👋
> 
> Thank you for submitting an article suggestion - it seems like its could be a helpful topic. We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or [via many other blog sites.](https://www.google.com/search?q=Everything+you+need+to+know+about+Ionic+Angular&ei=ladXYdWDEMy0tQbcvKOQAQ&ved=0ahUKEwiVovWGvKrzAhVMWs0KHVzeCBIQ4dUDCA8&uact=5&oq=Everything+you+need+to+know+about+Ionic+Angular&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABMgUIIRCgATIFCCEQqwIyBQghEKsCMgUIIRCrAjoHCAAQRxCwA0oECEEYAFDanw9Y2p8PYPurD2gCcAJ4AIABeIgBeJIBAzAuMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz)
> 
> Could you please expand upon how your content will differ from what is already available through other websites and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

Hello there, thanks for your concern. The approach I was going for was to try to give an overview of the different things Ionic has to offer and how, mostly at a higher level but with some more specifics sprinkled in there. Along with this, I would give my own perspective on some of the things I was confused about when I first started off or fascinated me. So as a couple of key examples: when I first generated an android project using Ionic I was very curious about how to customize the splash screen and icon they give you but struggled for a while to figure it out and was confused about it. I decided I'd add a section on that which other beginner tutorials didn't have. As well, when I first opened up an Ionic Angular project I was confused about what was going on with the stylesheets and what is SCSS, what is this extra *themes.scss* file so I add explanations about those. I was also planning to add a section on what capacitor plugins which I don't remember many tutorials I've seen talk much about them. I would then show some examples of capacitor plugins that might interest them or some that I've used.

In contrast to other tutorials I've seen, one of the very first ones I've watched started off with UI components from ionic which I decided to omit because personally I've found using the UI components to be intuitive based on just the docs. [This other tutorial](https://ionicacademy.com/get-started-with-ionic/)[https://youtu.be/r2ga-iXS5i4] I've seen as one of the first google searches seems to target a different audience than I intend to target. It goes over some of the basics of Angular (events and data-binding) but I plan to target an audience who, like myself when I starting learning Ionic, already knew that kind of stuff. As for the official docs, while it gives good in-depth explanations for different foundations of the framework, I thought I'd take a more general approach to give them a direction as to what Ionic is like and then they can look to the docs for further depth.

That is the approach I've decided I'll try to take as opposed to the other guides I've seen.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - this can be REOPENED at anytime when ready to link up to the PR as well.
 👍
