### ISSUE TITLE
voice identification using classification algorithms 

### ISSUE THREAD

**Issue by JOEOBY** [section-engineering-education/engineering-education#4077]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
[Machine learning] voice identification using classification algorithms 

#### Proposed article introduction
Many high-tech goods gradually invaded our daily lives during the information age, drastically altering our lifestyles. Information technologies, on the other hand, are continuing to progress towards a more human-centered approach. Biometric identification technology has gradually superseded several of the previous authentication methods that need to be investigated before people can properly manage them. Biometric identification results include face recognition technologies used in public areas, law enforcement agencies, and Siri voice mobile assistant on iPhone and Bixby Voice on Galaxy.

#### Key takeaways 

1.  Classification
2.  Feature extraction and configuration parameters
3. The proposed speech identification system

#### Article quality
The classification techniques for the problem of personality recognition by voice using machine learning approaches are discussed in this article. In the speech preprocessing procedure, we used the MFCC method. A comparative examination of five classification methods was performed to answer the problem.
#### References
machine learning

### Conclusion
In this article, a number of classification algorithms and speech preprocessing issues will be considered.
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @JOEOBY 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
