### ISSUE TITLE
[API] How to run Contentful CMS as Headless with Next.js

### ISSUE THREAD

**Issue by Catemacharia** [section-engineering-education/engineering-education#4078]
#### Proposed title of the article

How to run Contentful CMS as Headless with Next.js

#### Proposed article introduction
> We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.

> We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecker, and grammar-checked.

Contentful is a headless CMS, this means that it's built as a content repository making content available via an API (RESTful or GraphQL) to be displayed on any device. In this article, we will set up simple blog posts on the CMS and then display them to the users using Next.js. We will query the data from the CMS using an API. We will use the content model. A content model refers to a Schema, which will allow the generation of similarly structured pieces of content. For example, for every blog post, we want to have a title, an excerpt, a description, a cover image, and a date. The composition of all these fields to a blog post makes up the schema. Below are some of the topics that this guide will cover.

#### Key takeaways

What is Contentful CMS
What Next.js Framework
What is a headless CMS
Headless CMS vs Traditional CMS
Running Contentful as Headless CMS
Why Contentful?
Other CMSs that you can use

#### Article quality

This article will explain the concept of Contentful CMS and the concept of a headless CMS. Once the reader understands the two We will dive in and Implement and run Contentful as a headless CMS using technologies such as Next.js. In the end, the reader will understand the importance of running CMSs as headless.

#### References
> Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @Catemacharia. Thanks for submitting your topic suggestion. Could you fill in the proposed article introduction section of the template so I can accurately review your topic suggestion?

Thanks,
Louise

**Comment by louisefindlay23** [comment]
Hi, @Catemacharia. Thanks for the adding the description. Your article seems very comprehensive and will cover a variety of areas. It would be great if you could add some of your opinions and experiences of using these technologies especially in suubjective areas such as Why Contentful in order to make your article more unique.

**Comment by WanjaMIKE** [comment]
Closed #4078 via #4208
