### ISSUE TITLE
Extract images from URL in excel with PHP using PhpSpreadsheet

### ISSUE THREAD

**Issue by Kafi140** [section-engineering-education/engineering-education#4080]
#### Proposed title of article
Extract images from URL in excel with PHP using PhpSpreadsheet

#### Proposed article introduction
There are several methods for extracting photos from a URL. PHP has utilities for extracting data, including images with URLs, built-in.
The PhpSpreadsheet library allows you to read and type up Excel files. It has a lot of capabilities including text formatting, data manipulation, and so on. It comes with a large number of built-in classes, which makes the development process much easier.
Working with spreadsheets is a regular requirement when programming with Excel data. The PhpSpreadsheet library makes it easier for developers to create apps that use Excel data.

#### Key takeaways 
1.Applications for extracting photos from URLs in Excel                                                 2.PhpSpreadsheet Library Benefits
3.Code for loading and extracting picture data in PHP
4.Create a gallery using the photographs you've extracted.

#### Article quality
This article is easy to understand and it is straight
to the point.
#### References
N/A

Happy coding

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @Kafi140. There's an [existing article](https://phppot.com/php/extract-images-from-url-in-excel-with-php-using-phpspreadsheet/) that seems to cover everything that your topic suggestion proposes to. How will yours be unique? Being easy to understand isn't enough. It must have some unique value.

**Comment by Kafi140** [comment]
I will use the modern PHP version. This will make my article more unique. I also go further by showing a worked-out example, this will make my article more factual

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
