### ISSUE TITLE
How to Add Image in WordPress Sidebar

### ISSUE THREAD

**Issue by Danco10** [section-engineering-education/engineering-education#4081]
#### Proposed title of article
How to Add Image in WordPress Sidebar

#### Proposed article introduction
The sidebar of a WordPress theme layout will display many components such as search, archives, and more. The administrator could create the existence and positioning of these components.
The sidebar is an important section of a website layout that receives more attention than the other layout elements. As a result, to attract readers, people usually place the most important content in the sidebar. Graphical content, such as photos, icons, and charts, attracts greater attention and is also utilized to swiftly express the summary to visitors.
If your WordPress theme supports widgets, you can use sidebar widgets to add an image to the sidebar.

#### Key takeaways 
1. Making use of the WordPress Image Widget
2.Application of the Text Widget
3.Application of a Custom HTML Widget
4.Widgetize the theme and make a custom widget to display an image in the sidebar.
5.Output of the WordPress Sidebar Widget

#### Article quality
This article will be straight to the point and it's code snippets will understandable by both professional and beginners

#### References
N/A
Happy coding

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
@Danco10, thanks for submitting your topic suggestion.

After some careful consideration, it struck us that this topic may be a bit over saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in-depth topic - or continue working on this one by flushing it out a bit more (i.e. making it more in depth - "such as covering other widgets in addition to sidebar and how to "widgetize" a theme).
