### ISSUE TITLE
How to create a font chooser app using python

### ISSUE THREAD

**Issue by majiezra** [section-engineering-education/engineering-education#4082]
#### Proposed article introduction
Font chooser app is a simple application that lets you browse the installed fonts on your computer and then narrow down that selection till you find the perfect font for your design project or write-up. By Clicking on the sample text to change it to your chosen desirable text. we will build this GUI app using tkinter in python.

#### Key takeaways 
the reader should be able to 
- know all GUI methods
- the role and function of tkinter as a GUI method and in data science.
- how to build a font chooser app.
#### Article quality
How is your article unique? there are few or no articles publish on this subject and it is going to be more detailed and easy to understand for a reader who is a beginner in a programming language

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @majiezra 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
