### ISSUE TITLE
[Languages] Random Joke Generator in Javascript: A Complete Guide

### ISSUE THREAD

**Issue by EssyG10** [section-engineering-education/engineering-education#4088]
#### Proposed title of the article
 Random Joke Generator in Javascript: A Complete Guide 
#### Proposed article introduction
In programming, there are regular cases where you need to recover an arbitrary number. For instance, you might be making a speculating game and need your program to create an arbitrary number each time the client runs your program. Or on the other hand, you might need to run a capacity an irregular number of times. 
That is the place where the JavaScript Math.random() work comes in. Math.random() is an implicit strategy that can be utilized to create irregular numbers in JavaScript. The capacity returns a worth between 0 (comprehensive) and 1 (elite), yet we can utilize another capacity called Math.floor() to transform our number into an entirely arbitrary number. 
In this instructional exercise, we will investigate the nuts and bolts of JavaScript irregular number age, and talk about how you can utilize the Math.random() work in your code.
#### Key takeaways 
1. JavaScript Math Refresher
2. JavaScript Math.random()
3. JavaScript Random Number Between Two Values
4. Random Joke Generator
#### Article quality
By reading this article, learners will have a good understanding of randomness in javascript. In addition to that, they will be in a position to implement random password generators in their application let's say when registering new members or subscribers in their system.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @EssyG10 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
