### ISSUE TITLE
How to Create Horizontal Scrolling Menu using jQuery and PHP

### ISSUE THREAD

**Issue by Njengab** [section-engineering-education/engineering-education#4090]
#### Proposed title of article
How to Create Horizontal Scrolling Menu using jQuery and PHP

#### Proposed article introduction

Menu is a basic part of a site. It is the passage for clients to investigate the pages. Essential menu is important for the header and one of the most conspicuous thing that gets the client consideration first. 
We need to hit the nail on the head. When there are gigantic number of classifications thus pages, then, at that point, it is hard to make the menu so the clients can undoubtedly explore them. 
Level looking over menu is an answer for the situation of not insignificant rundown of things in a solitary menu bar. 
Various measure of outsider modules or libraries are accessible on the lookout for executing looking over menu highlight for your application. 
Nothing beats our custom code. In this article, we will perceive how a basic flat looking over menu can be fabricated effectively with a model. The menu interface is made as scrollable by the utilization of CSS and jQuery liveliness. The looking over property is added to the menu holder by means of CSS and the level parchment position is overseen by jQuery content to make a liveliness impact.

#### Key takeaways 

1. Uses of horizontal scrolling menu
2. Available plugins and libraries to enable horizontal scrolling
3. Advantages of using custom code to implement horizontal scrolling
4. About this menu example
5. Code implementation to show menu with horizontal scrolling
6. HTML code to display menu
7. jQuery script to handle horizontal scrolling
8. Fetch menu items from the database using PHP MySQL

#### Article quality
My article will be understood by both beginners and experts. It will also differ with other articles available across the internet since they  have relied  their ideas from the official documentation. This article will be helpful to intermediate web developers as they nature their skills.
#### References
n/a

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Could you please expand upon how your content will differ from what is [already available through other websites](https://www.google.com/search?q=Create+Horizontal+Scrolling+Menu+using+jQuery+and+PHP&oq=Create+Horizontal+Scrolling+Menu+using+jQuery+and+PHP+&aqs=edge..69i57j69i64l2j69i61.5096j0j1&sourceid=chrome&ie=UTF-8) and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics. @Njengab

**Comment by Njengab** [comment]
Apart from the basic introduction on the menus the article explains dynamic parallax scrolling effects which is a modern customization. The article will be information oriented   thus allowing visitors to practice through the available clear and precise code snippet that will be well documented. Thank you.

**Comment by Njengab** [comment]
Njengab <https://github.com/Njengab> commented now
<https://github.com/section-engineering-education/engineering-education/issues/4090#issuecomment-934190162>

Apart from the basic introduction on the menus the article explains dynamic
parallax scrolling effects which is a modern customization. The article
will be information oriented thus allowing visitors to practice through the
available clear and precise code snippet that will be well documented.
Thank you.
