### ISSUE TITLE
MySQL Aggregate Functions in Multiple Tables with Subqueries

### ISSUE THREAD

**Issue by AndrewOdera** [section-engineering-education/engineering-education#4097]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
MySQL Aggregate Functions in Multiple Tables with Subqueries
Use keyword research to improve your article's SEO.

#### Proposed article introduction
MySQL aggregate functions are self-contained modules built into the database that perform calculations on multiple user-defined values and return a single value. SUM(), AVG(), MIN(), and MAX() are some of the most common examples.
When creating a summary value for reporting purposes based on different tables in a database, aggregate functions come in handy. Instead of saving summary data in a table permanently, you simply retrieve a dynamic value based on a function result. This increases the scalability and ease of maintenance of your MySQL applications.

#### Key takeaways 
By the end of this tutorial, the reader will be able to:

- Use MySQL Aggregate Function to retrieve current stock
- Check the Aggregate Function after the new insert
- WIll be able to understand some queries in MySQL

#### Article quality
Creating MySQL Aggregate Function in Multiple Tables with Subqueries

#### References
N/A

### Conclusion

In this article, you'll gain knowledge on how to use MySQL aggregate functions and subqueries to generate columns for reporting. This is a timely and efficient method for creating summaries for various related columns that you can use in your applications.
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀 @AndrewOdera
