### ISSUE TITLE
[API]Implementing an authentication system using Twitter API in PHP

### ISSUE THREAD

**Issue by ephraa** [section-engineering-education/engineering-education#4107]
### Topic Suggestion
Implementing an authentication system using Twitter API in PHP
#### Proposed article introduction
In modern days, social media login is the preferred method of authenticating users into the system. The reason is millions of users have registered with the platforms and it is much easier to login into the system where security is guaranteed.
Twitter is an internet giant which has provided the support of OAuth authentication through the use of their detailed and well-documented API.
There are many client libraries available that implements Twitter OAuth login but in this tutorial, we will use plain core PHP since it is lightweight and sufficient.
#### Key takeaways 
At the end of the tutorial, the learner will be able to:
- get and configure the Twitter API keys
- perform the 3-step authentication flow
- create and handle responses during the authentication flow
- store authenticated user data into the database

#### Article quality
- I will use an object-oriented PHP coding style that unlike the existing articles that are using older PHP versions
- The article will not use libraries but plain core PHP to implement Twiter OAuth authentication

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Could you please expand upon how your content will differ from what is already available through [other websites](https://www.codexworld.com/login-with-twitter-using-php/) and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics. @ephraa

**Comment by ephraa** [comment]
@hectorkambow Kindly do not close this topic as am working on it and will upload the article very soon. Thank you.
Copy @ahmadmardeni1

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
