### ISSUE TITLE
Getting started with AssemblyScript

### ISSUE THREAD

**Issue by josax01** [section-engineering-education/engineering-education#4109]
#### Proposed title of article
Getting started with AssemblyScript

#### Proposed article introduction
AssemblyScript is a language made specifically for WebAssembly. It resembles TypeScript, therefore it is well suitable for beginner developers as most of us are familiar with TypeScript (which is a superset of JavaScript).

In this guide, readers will learn how to install AssemblyScript, and the syntax of AssemblyScript as well as the differences between AssemblyScript and TypeScript.

#### Key takeaways 
- How to install AssemblyScript
- How to compile AssemblyScript to WebAssembly
- How to optimize AssemblyScript code
- Differences with TypeScript
- How to configure VS code to recognize AssemblyScript
- How to use import in AssemblyScript 

#### Article quality
It helps reader to get started with AssemblyScript.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
We are looking for programmer-centric concepts explained in fun and intuitive ways. And your guide may be a bit over-saturated throughout other blog sites and official documentation. Can you build a unique project using AssemblyScript? @josax01

**Comment by josax01** [comment]
@ahmadmardeni1 yes, for this guide we'll be building a Todo application while explaining some of the concepts stated in the **key takeaways**

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @josax01 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
