### ISSUE TITLE
[Languages] Understanding Babel and how will it help you write JavaScript

### ISSUE THREAD

**Issue by Robbiewanjau** [section-engineering-education/engineering-education#4110]
#### Proposed title of the article
[Languages] Understanding Babel and how will it help you write JavaScript
#### Proposed article introduction
Babel is a JavaScript transpiler that converts edge JavaScript into regular ES5 JavaScript that can run in any program (even the old ones). 

It makes accessible all the linguistic sugar that was added to JavaScript with the new ES6 determination, including classes, fat bolts, and multiline strings.
This article will get you started with Babel.
#### Key takeaways 
1. Installation
2. Classes
3. Multiline Strings
4. Fat Arrows
#### Article quality
most articles out there are not in-depth and after going through some of them it's clear that some learners may not be in a position to actually know how to apply babel and write quality javascript programs. This article will be easy and simple for understanding and executing the snippets that will be involved. 

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @Robbiewanjau
