### ISSUE TITLE
Create beautiful and Dynamic Alert/Confirm and Prompt Dialog Box in JavaScript and SweetAlert

### ISSUE THREAD

**Issue by chalo316** [section-engineering-education/engineering-education#4111]
#### Proposed title of article
Create beautiful and Dynamic Alert/Confirm and Prompt Dialog Box in JavaScript and SweetAlert

#### Proposed article introduction
Every so often, you'll need to show an alert ,confirm or prompt box to your clients to tell them about a blunder or warning. The issue with the default alert boxes given by programs is that they're not extremely alluring. At the point when you're making a site with extraordinary shading blends and extravagant activity to further develop the perusing experience of your clients, the unstyled alert boxes will appear to be awkward.
  This article explains  the use of sweet alert box  that is more appealing and simpler to employ .SweetAlert is an approach to modify alerts in your and sites .It permits you to transform from a standard JavaScript button. We can add buttons, change the shading text, and even add extra alerts that change contingently upon client click.

#### Key takeaways 
1.Brief overview of  Dialogue boxes(Alert, Confirm, Prompt)
2. code snippets with explanations/texts
3. installation of sweetAlert and use.
4. importance of of dialogue boxes.

#### Article quality
My article will help  individuals with basic knowledge  understand dialogue boxes and also help intermediate  web developers improve their styling features of dialogue boxes with the use of sweetalert2.

#### References
n/a

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Could you take a look at this topic suggestion when you have the chance? Since you have expertise in Java, I thought you'd be the best person to reach. @Kayere

**Comment by Kayere** [comment]
Hello @chalo316, I can see that the [official documentation](https://sweetalert2.github.io/) offers sufficient information to help one create the dialog boxes. How is your article going to add value to what is available?

**Comment by Njengab** [comment]
Hello my article will try to add the knowledge on dialogue boxes based on the low level understanding of the basics to advance approaches. the articles tries to capture the ideal approaches to dialogue boxes to beginners and advanced intellectuals in the field of web design.
the article will be well directed  to the context and clarity will be the key aspect bearing in mind the available documentation. thank you! @Kayere.

**Comment by chalo316** [comment]
my article will attempt to include the information dialogue boxes dependent on the low level comprehension of the fundamentals to propel approaches. the articles attempts to catch the ideal ways to deal with dialogue boxes to amateurs and progressed intellectuals in the field of website architecture 

The article will be very much coordinated to the unique situation and clearness will be the key viewpoint remembering the accessible documentation. much thanks to you

**Comment by chalo316** [comment]
My article will attempt to include the information dialogue boxes dependent
on the low level comprehension of the fundamentals to propel approaches.
the articles attempts to catch the ideal ways to deal with dialogue boxes
to amateurs and progressed intellectuals in the field of website
architecture

The article will be very much coordinated to the unique situation and
clearness will be the key viewpoint remembering the accessible
documentation. much thanks to you @Kayere <https://github.com/Kayere>.

**Comment by Kayere** [comment]
Good topic @chalo316 - approved.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
