### ISSUE TITLE
[Languages]Advancement of Swing Frameworks in Java

### ISSUE THREAD

**Issue by lizpart** [section-engineering-education/engineering-education#4112]
#### Proposed title of article

Advancement of Swing Frameworks in Java

#### Proposed article introduction

Swing in Java is an Application Programming Interface (API) for providing graphical user interface elements to Java Programs. It was created mainly to provide more powerful and flexible components than Java AWT (Abstract Window Toolkit). The AWT is still a crucial part of Java, its component set is no longer widely used to create graphical user interfaces. Today, most programmers are using Swing for this purpose.
Swing is a set of classes that usually provides more powerful and flexible GUI components than does the AWT. Simply put, Swing provides the feel and look of the modern Java GUI.
In this article, we will learn all you need to get started with swings in Java.

#### Key takeaways 

1. Learners will have a clear understanding of Lightweight swing components. 
2. Learners will know how swing supports pluggable look and feel.
3. Learners will understand how painting in Swing is done.
4. Learners will understand the concept of event handling.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Could you take a look at this topic suggestion when you have the chance? Since you have expertise in Java, I thought you'd be the best person to reach. @BrianaNzivu

**Comment by BrianaNzivu** [comment]
Hey @ahmadmardeni1 .
This is a good topic🚀.

Hey @lizpart. Good topic...
Please ensure you make it as detailed as possible to make it a fantastic article.
You can even try and illustrate using code snippets most features covered by swing.
I would like to read this article once you open a PR after approval . Please ping me on the PR if you do not mind.

Regards🚀

**Comment by lizpart** [comment]
Consider it done @BrianaNzivu

**Comment by WanjaMIKE** [comment]
@lizpart it should not be similar to https://github.com/section-engineering-education/engineering-education/pull/3036

**Comment by lizpart** [comment]
Yeah

**Comment by lizpart** [comment]
Have taken a look at #3036 and my topic of discussion is different @WanjaMIKE
