### ISSUE TITLE
Polymorphism and Inheritance in C++

### ISSUE THREAD

**Issue by Bikorir** [section-engineering-education/engineering-education#4114]
#### Proposed title of the article
Polymorphism and Inheritance in C++
#### Proposed article introduction
The word polymorphism means having many forms. Polymorphism usually occurs when there is a hierarchy of classes that are related through inheritance. C++ polymorphism means that a call to a member function will cause a different function to be executed depending on the type of object that invokes the function.  
Inheritance refers to a class's capacity to derive features and traits from another class. One of the most significant features of Object Oriented Programming is inheritance.
 In this article these two subtopics will be discussed in depth and their application in C++  programming will be made easy for the reader.
#### Key takeaways 
1.Introduction to polymorphism and Inheritance
2.Programming fundamentals of polymorphism and inheritance in C++
3.Modes and Types of Inheritance
4.Types of polymorphism.
5.Differences between polymorphism and Inheritance
6.What is new in polymorphism  and Inheritance?
7.Why And When To Use "Inheritance" and "Polymorphism"?
#### Article quality
I intend to incorporate programme-centric concepts of polymorphism and inheritance in C++ that have been overlooked by other writers who have tried writing about these topics. My content will also be original and written in a format that a beginner shall understand what is discussed and the information shall remain useful and relevant to high end programmers.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Other students already covered Polymorphism and Inheritance in C++.

Please feel free to suggest an alternate topic to explore. 🚀 @Bikorir
