### ISSUE TITLE
[Languages] Using data adapters to update data sources

### ISSUE THREAD

**Issue by mukono10** [section-engineering-education/engineering-education#4116]
#### Proposed title of article
[Languages] Using data adapters to update data sources

#### Proposed article introduction
The DataAdapter's Update function is used to resolve updates from a DataSet to the data source. The Update method, like the Fill method, accepts a DataSet instance as well as an optional DataTable object or DataTable name as inputs. The DataSet instance represents the DataSet that holds the changes, while the DataTable specifies the table from which the changes should be retrieved. The first DataTable in the DataSet is utilized if no DataTable is supplied.

The DataAdapter examines the changes made and executes the relevant command when you call the Update method (Insert, Delete or Update). When the DataAdapter finds a change to a DataRow, it processes the change using the InsertCommand, UpdateCommand, or DeleteCommand. This helps you to optimize the efficiency of your ADO.NET application by specifying command syntax at design time and using stored procedures when possible. Before running Update, you must explicitly set the commands.
Therefore in this article, we shall take a look on how one can update the data source using detailed examples. 

#### Key takeaways 
1. To retrieve and update data using a  DataAdapter.
2. How to Map Values to a DataSet Using UpdatedRowSource.
3. Autoincrementing columns

#### Article quality

This article aims in producing an original content that will have a positive impact to the reader who will have a need in exploring in such a topic.

#### References
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @mukono10. How will your proposed article differ from the [official docs](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/updating-data-sources-with-dataadapters) which seem to cover all the key takeaways you've outlined?

**Comment by mukono10** [comment]
I am focusing on improving the already published content by producing a more original content.

**Comment by mukono10** [comment]
@louisefindlay23 I prefer closing this issue and at least suggest a more strong issue.
