### ISSUE TITLE
Deploying a Django REST API serverless application with AWS and Zappa

### ISSUE THREAD

**Issue by Anitaachu** [section-engineering-education/engineering-education#4117]
#### Proposed article introduction
Serverless computing was created with the main goal of enabling developers build, run applications without having to interact or manage servers. This does not mean the application runs without a server, but that the management of the server would be done by AWS. 
This process is quite exciting although implementing serverless applications in Django may be challenging. However, we will be using Zappa, an open-source python tool for creating, deploying, and managing serverless python applications on AWS Lambda. 

In this tutorial, we will be building a serverless Django REST API and deploying the application to AWS Lamba using Zappa.

#### Key takeaways 
1.  Building a serverless Django RESTAPI application
2. How to implementing Zappa 
3. Working with AWS Lamba

#### Article quality
In this tutorial I intend on first, giving a detailed explanation for what serverless application means and how it aids developers. Also explaining concepts such as Zappa, AWS Lamba, etc., and how they work. The tutorial will contain a step-by-step guide on how these processes work right from building a REST API to the deployment process.

#### References
N/A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Anitaachu 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by Anitaachu** [comment]
Hello @hectorkambow Please I would love this project to be reopened. My apologies for the delay in response. Thank you!
