### ISSUE TITLE
[Node.js] How To Build GraphQL APIs with ExpressJS and Typescript

### ISSUE THREAD

**Issue by Babatunde13** [section-engineering-education/engineering-education#4120]
#### Introduction
GraphQL is a query language for APIs and a runtime for fulfilling those queries with existing data. It's an API specification like REST, but with GraphQL, we can use one query to get all we need. Instead of making multiple requests to the server, we can also specify the fields that we need. Say, for example, we have a user model and a posts model, with REST to get the posts made by a user, we first need to get the user then make another request to get posts of a user. Still, with graphql, we can do all of these with one query. We specify that we need posts made by the user alongside the user data. Aside from fetching data, we can also mutate data on the database using mutations.
For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

#### Key takeaways 
1. What GraphQL is
2. How to build a simple graphql API in express javascript that does not persist data
3. Adding database support
4. Switching to Typescript

#### Article quality
Most articles on graphQL and express do not use Typescript, but being a great fan of Typescript, I'd be explaining how to migrate our Javascript code in this article to Typescript.

#### References
1. [GraphQL Website](https://graphql.org/)
2. [Typescript docs](https://www.typescriptlang.org/)
3. [Express GraphQL](https://www.npmjs.com/package/express-graphql)
4. [Mongoose ODM](https://mongoosejs.com/)

### Conclusion
This article will give you an in-depth guide to what you need to get started with Express, GraphQL and Typescript.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any [existing EngEd articles](https://www.section.io/engineering-education/search/?q=graphql), articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
