### ISSUE TITLE
[Languages]Using Amazon Web Service For Django Media Files Storage    

### ISSUE THREAD

**Issue by OkothPius** [section-engineering-education/engineering-education#4122]
#### Proposed title of article
Using Amazon Web Service For Django Media Files Storage

#### Proposed article introduction
Using cloud storage services has been trivial in recent years for the ease of application scalability. They enable large files to be served in the web pages without causing heavy traffic and load to the application database reducing the system load time and offering a good user experience to the user. In this article, we will be using Amazon Web Service to store our media files which will run on a Django backend server. We’ll have an introduction on how to get started with Django then later move on to prerogatives of using cloud service in this case AWS S3. 

#### Key takeaways 
1. Setting up Django application
2. Introduction to Amazon Web Services S3
3. AWS S3 configurations
4. Setting AWS S3 in Django Application
5. Test our application 

#### Article quality
In this article, we'll go in-depth and extensively in building a gallery web application that allows admin users to upload pictures and have them stored in S3 bucket.This ensures efficient serving of media files when the application is deployed as most free local hosting platforms does not handle media files. This article differs from a similar article which was more focused on Django Rest Framework and uploading media files through API endpoints to AWS S3.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @OkothPius
