### ISSUE TITLE
Working with a Designer UI File - Using Qt Designer and Python to Create Main Windows

### ISSUE THREAD

**Issue by neshmacharia** [section-engineering-education/engineering-education#4123]
#### Proposed title of the article
Working with a Designer UI File - Using Qt Designer and Python to Create Main Windows

#### Proposed article introduction
To build a graphical user interface (GUI) for your PyQt windows and dialogs, you have two options: utilize Qt Designer or manually write the GUI in plain Python code. The first route may significantly increase your productivity, while the second option gives you complete control over your application's code.

A primary window and numerous dialogs are standard components of graphical user interface (GUI) programs. If you want to build these visual components quickly and easily, Qt Designer is the solution for you. This article will teach you how to use Qt Designer to build GUIs efficiently.

#### Key takeaways 
By the end of this tutorial, we will understand:
1.  An overview of Qt Designer.
- Installing and Running Qt Designer
- Using Qt Designer's New Form Dialog
- Using Qt Designer vs. Hand Coding Your GUIs
2. Building Main Windows With Qt Designer and Python
- Creating the main menu
- Adding and populating toolbars
- Laying out widgets
3. Conclusion

#### Article quality
I will be building Main Windows With Qt Designer and Python, thus making my article unique
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by neshmacharia** [comment]
hello @ahmadmardeni1 what about this topic suggestion

**Comment by neshmacharia** [comment]
hello @ahmadmardeni1 what about this topic suggestion

**Comment by neshmacharia** [comment]
hello @hectorkambow , @ahmadmardeni1 what's up with this topic suggestion. I have tried to ping several times with no reply.
