### ISSUE TITLE
Implementation of convolution Integral of Continuous Time Linear Time Invariant Systems in Matlab

### ISSUE THREAD

**Issue by queenterbruce063** [section-engineering-education/engineering-education#4127]
####   Introduction
LTI are systems that gives output from a given input. In this systems, the input is known as the excitation while the output is the response. These systems follows linearity and time invariance. Linear systems are those that follows homogeneity and superposition principles. If we have an input x(t) which gives an output y(t), that system is referred to as homogeneity. Also, if we have an output y_1(t) for input x_1(t) and y_2(t) for input x_2(t), this is the principle of super position. If both are combined, the input ax_1(t) + ax_2(t) gives a corresponding output as ay_1(t) + ay_2(t).
LTI systems can be characterized entirely by a single function called system impulse response. It is represented by h(t) for continuous system. For any input x(t), the inputs can be obtained by convolution of inputs and impulse response. Convolution is an integral that expresses the amount of overlap of one function when it is shifted over another function. In this article, we will dive more into this so as to make more sense and understand what we are talking about here.

#### Key takeaways 
- Understanding the concept of the LTI.
- Understanding the convolutional integral.
- How to implement this in Matlab.

#### Article quality
This article uses the convolutional concept in LTI to improve efficiency.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Hello @queenterbruce063 , Upon a quick google search, there are several articles on this topic. Can you explain how your article will be different from the ones that exist. Thank you.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
