### ISSUE TITLE
Object Classification using Histogram of Oriented Gradients(HOG) features and ECOC Multi-Class Support Vector Machine(SVM) in Matlab

### ISSUE THREAD

**Issue by josephodhis** [section-engineering-education/engineering-education#4128]
#### Proposed article introduction
The Histogram of Oriented Gradients(HOG) is a feature descriptor that is used in computer visions and image processing for the purpose of object detection. The technique counts the occurrence of the gradient orientations in localized portion of an image. Support vector machine(SVM) is a supervised machine learning algorithm that helps in the classification. It aims to find an optional boundary between the possible outputs.
SVM tries to find a line that maximizes the separation between a two-class data set of 2-dimensional space points. To generalize, the objective is to find a hyperplane that maximizes the separation of the data points to their potential classes in an n-dimensional space. The data points with the minimum distance to the hyperplane (closest points) are called Support Vectors.
In this tutorial, We will look at the multi-class object classification with the help of HOG features. For classification, we use the ECOC based multi-class SVM.
   
#### Key takeaways 
- Scheme for object classification.
- Image database preparation.
- ECOC based multi-class SVM.
- Appropriate cell-size selection for HOG features.
- Matlab code for shape classification(Multi-class).
- Matlab code for discrete testing.
#### Article quality
This article is in-depth and provide an additional example on how you can use this technique.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
