### ISSUE TITLE
Empowering everyone to code with Google's Eye

### ISSUE THREAD

**Issue by Aniket762** [section-engineering-education/engineering-education#4130]
### Topic Suggestion
Empowering everyone to code with Google's Eye

#### Proposed title of article
[API] Empowering everyone to code with Google's Eye

#### Proposed article introduction
In India, more than 95% of schools don't allow smartphones in class. Being a Computer Science teacher becomes very difficult as it is nearly impossible to check the handwritten code of each student line by line. Also talking in India, in most schools, the students don't have the privilege to have one computer each for them so that they can run their code on their own. So it becomes a nightmare for the teacher as they might have to manually type each code of each student and run it or take the risk of missing out on bugs. While in recent times, the world has started moving towards Codelisation, being a good programmer is not easy it requires consistency, determination, problem-solving ability, and a lot more but, most importantly it requires you to get started. I did a small survey in my community and got to know more than 80% of them started properly coding after joining university and the major reason was lack of the personal computers and laptops. In developing countries, 3 out of 10 people have access to computers in comparison to 8 out of 10 people who have access to smartphones. Let's see how project playground solves this problem and empowers even someone from a remote village in India to start coding.

#### Key takeaways 
1. Realising a new dimension to coding
2. How to use `Google Vision API `to extract handwritten code
3. How to build a simple language compiler with `Nodejs`
4. How to embed a theme-based code editor in `Nextjs`
5. How to do `file handling` in Node and run vision API to extract text

#### Article quality
The idea upon which the article is written is first of all unique, the prototype which we have built is open-sourced and free to use. The article will not only contain what playground does and its inspiration and give readers a new dimension to think, but will also include a guide on how to use files system in Node, run Google vision API to extract code, fetch it from API and get it on the theme-based editor.  Moreover, it will also give readers a basic understanding of simple compiler design with CPP and python as language support. 

#### References
Link to getting started blog: https://dev.to/aniket762/empowering-everyone-to-code-with-google-s-eye-49e9
Link to Github repo: https://github.com/Aniket762/playground

## Conclusion
We developed Playground in an MLH hackathon in which we were the overall winners. But being a beginner developer it's difficult for me to take this prototype to production. Getting the article published will help the project get reach and ultimately the finished product with the community support can help 85% more people get started with coding because our project playground empowers everyone to code, people who cannot afford a personal computer can now code with Playground.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Aniket762** [comment]
> Good afternoon and thank you for submitting your topic suggestion. Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

Thanks a lot, @ahmadmardeni1 excited for the review! Have a good day

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
