### ISSUE TITLE
[Languages] Hashing in C++ using std::hash

### ISSUE THREAD

**Issue by Shikomary** [section-engineering-education/engineering-education#4131]
#### Proposed title of article

Hashing in C++ using std::hash

#### Proposed article introduction
To generate a hash of any C++ object, we will use the standard C++ library's (std:hash) inherent support for hashing. We unknowingly utilize a hash function whenever we use an associative container. Key-value pairs used in map, multimap, unordered map, and other data structures are mapped to one another. The hash function and hashcode creation form the foundation of mapping. There are no arguments or initialization values required to create an object in the hash class by default. The hash value of the argument supplied to it is returned by this method. The value stays the same if the argument doesn't.

In this tutorial, we will discuss in details about Hashing in C++ using std::hash and how we can implement it in programming.

#### Key takeaways 
By the end of this tutorial the reader will understand the following concepts.

- How to create an object in std::hash?
- Character hashing
- String hashing
- Integer hashing
- Vector hashing
- Hashing and collision

#### Article quality
So that it adds value beyond what is already in the official blogs and documentation, I plan on making this article unique and beginner-friendly. To aid the rest of EngEd, this article will go beyond a basic explanation and give a step-by-step approach.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Shikomary 
This library is over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
