### ISSUE TITLE
Thread and Isolate in Flutter

### ISSUE THREAD

**Issue by waigwakanoi** [section-engineering-education/engineering-education#4136]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Thread and Isolate with Flutter
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
An isolate is a thread that has an event loop that continuously processes events in its own memory space. In effect when the main dart function executes, it executes in an isolate that scans for available events and hangs when none are available, an opportunity for the system to decide to run the garbage collector for example.
Dart can execute multiple threads by spawning additional isolates. Creating more isolates can be useful for heavy computation processing but most Flutter apps do not need spawning additional isolates unless it becomes an issue and impacts the frame rate.
For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
- Understand how to use isolate with flutter
- Understand event loops in asynchronous way
- code the implementation of the thread and isolate

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
-https://flutter.dev/docs/development/packages-and-plugins/background-processes
- https://medium.com/flutter-community/thread-and-isolate-with-flutter-30b9631137f3

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by waigwakanoi** [comment]
Awaiting response from @WanjaMIKE

**Comment by waigwakanoi** [comment]
Hello @ahmadmardeni1 .What is the current status of this issue? I am still waiting for @WanjaMIKE to respond..

**Comment by WanjaMIKE** [comment]
Topic approved. Let's ensure that it adds value to the community. It should be different from those published on other sites including medium. Thanks
