### ISSUE TITLE
[Android] How to Pick PDF Files and Images from Phone Storage in Android Using Kotlin

### ISSUE THREAD

**Issue by Hepatrique** [section-engineering-education/engineering-education#4137]
#### Proposed title of article
[Android] How to Pick PDF Files and Images from Phone Storage in Android Using Kotlin

#### Proposed article introduction
This tutorial is based on Android and is  going to help android developers to pick PDF files and images from the phone storage and display in the TextView and ImageView respectively. The tutorial is going to be in Kotlin programming language and also easy for beginners to read and understand.

Because the user is involved in selecting the files or directories that your app can access, this mechanism doesn't require any system permissions, and user control and privacy is enhanced. Additionally, these files, which are stored outside of an app-specific directory and outside of the media store, remain on the device after your app is uninstalled.

#### Key takeaways 
- Understanding explicit intent for navigating to the phone storage.
- How to choose images and PDF files.
- How to set the files in the Views.

#### Article quality
My article is unique since the content is not covered in the official documentation. It is also beginner friendly and written in Kotlin.

#### References
- https://developer.android.com/training/data-storage/shared/documents-files
- https://developer.android.com/guide/components/intents-filters

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation. Can you build a unique/original project? @Hepatrique

**Comment by Hepatrique** [comment]
Hello @ahmadmardeni1 ,
As I was researching on the topic I realized that what is in the internet is quite shallow and not even easy to understand for Android beginners. More so, on the uploading PDF files there is no single article covering the topic although, it is very essential for android users. I would be glad if you grant the opportunity to cover the topics uniquely as you have suggested.
