### ISSUE TITLE
[C#] Environment Variables and Environment Classes  in C#

### ISSUE THREAD

**Issue by Bikorir** [section-engineering-education/engineering-education#4139]
#### Proposed title of article
  Environment Variables and Environment Classes  in C#.
#### Proposed article introduction
   Environment class is static class which Provides the system configuration,Current program execution Environment and some properties for string manipulation whereas environment variable indicates the runtime environment in which an application is currently running.
In this article we will learn about the Environment  class of C#,which provides the machine configuration details,Program execution Environment details as well as some properties which is used to break the one line into new line which is written in the program for output.

#### Key takeaways 
1.introduction to environmental classes
2.Application of environmental variables
3.Examples to work with environmental classes
4.Setting environmental variables permanently in C#
5.Set and get environmental variables in C#
6.Uses of system.Environment class.
#### Article quality
 I intend to incorporate programme-centric concepts of Environment class and variables that have been overlooked by other writers who have tried writing about these topics. My content will also be original and written in a format that a beginner shall understand what is discussed and the information shall remain useful and relevant to high end programmers.
#### References
 N/A.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
