### ISSUE TITLE
[API]Managing Spring Boot database migrations using Flyway database migration tool

### ISSUE THREAD

**Issue by sumbaelvis** [section-engineering-education/engineering-education#4140]
#### Pre-submission advice
By following our pre-submission advice and reviewing our Resources folder, you will maximise the chances that your topic is approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials promptly.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article promptly from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Managing database migration using Flyaway database migration tool
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Hibernate DDL creation is a nice feature for small projects. However, in large projects that have a complex deployment workflow and features like version rollback in case of a significant issue, the solution is not sufficient.

Flyway is a tool that lets developers version control incremental changes to the database to migrate it to a new version quickly and confidently.

The article will explain how to build a Spring Boot application with MySQL Database & Spring Data JPA and learn how to integrate Flyway in the app to manage database migrations and rollbacks.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.
1. Integrating Spring Boot application with MYSQL database.
2. Integrating Flyway database migration tool into Spring Boot application.
3. Managing database migrations and rollbacks using flyway migration tool.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
closed #4140 via #4274
