### ISSUE TITLE
Servlet: Filter API.

### ISSUE THREAD

**Issue by Tumorbenson** [section-engineering-education/engineering-education#4142]
#### Proposed title of article
Servlet: Filter API.

#### Proposed article introduction
When an application is pre-and post-processed, the object being invoked is filters. You can use and configure filters for some filtering tasks. This is included in the Servlet API. The filter interface is found in the javax.servlet package. In order to create a filter, we have to implement the filter interface.
You can have a number of filters for pre-and post-processing requests. In the deployment descriptor of the web application, filters are configured.

Interfaces available in servlet filters, and their methods will be discussed in this article.

#### Key takeaways 
1. Introduction.
2. Filter usage and its advantages.
3. Filter interface
4. FilterChain interface
5. FilterConfig interface
6. An example showing the use of a servlet filter

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
