### ISSUE TITLE
[Languages] Build data-driven and type-driven algorithms using pattern matching

### ISSUE THREAD

**Issue by neheMaish** [section-engineering-education/engineering-education#4143]
#### Proposed title of article
Build data-driven and type-driven algorithms using pattern matching

#### Proposed article introduction
The practice of testing whether a specified sequence of characters/tokens/data exists among the given data is known as pattern matching. It can also be used to locate a matching pattern in a text or code and replace it with another text or code. Pattern matching is used in some fashion by every application that includes search capabilities.

In this article, we shall to understand some points like
1. To construct full algorithms, combine pattern matching with various approaches
2. To implement behavior depending on types and property values, use pattern matching expressions.
3. Recognize circumstances in which pattern matching is appropriate

The early versions of c-Sharp introduced the basic pattern matching features which have been continually extended to the later versions. You can create functionality that acts as if you were extending types from other libraries. Patterns can also be used to provide functionality to your application that isn't a core feature of the type being extended. 

In this article, we are going to deeply have a look at this topic.

#### Key takeaways 
1.  Scenarios for pattern matching
2. Pattern matching designs
3. Implementing the basic toll calculations

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by neheMaish** [comment]
I'm just nearly completion and make a pr

**Comment by WanjaMIKE** [comment]
Seems the PRs linked tp this issue were closed.
