### ISSUE TITLE
[API] Unsplash API in Javascript

### ISSUE THREAD

**Issue by joanalividza** [section-engineering-education/engineering-education#4145]
#### Proposed title of article
Unsplash API in Javascript
#### Proposed article introduction
Completing this project taught me how to use JavaScript’s built in fetch to make API requests. Before building this project, I was completely unaware that the Unsplash API existed. It was interesting to learn that many established companies integrate this API into their website. It’s also cool to have an image generator for whenever you need a new wallpaper on your desktop.
By reading this article learners will find it cool like I did and will be able to integrate Unsplash API in their applications
#### Key takeaways 
By reading this article learners will gain the following :
- DOM manipulation
- Event listeners
- Control structures
- Promises
- Functions
- Fetch

#### Article quality
This article will be of great importance to those learning JavaScript as the project example in it will help them test their JavaScript coding skills. Furthermore the code in it will be in modern JavaScript.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by hectorkambow** [comment]
Student requested to reopen

**Comment by joanalividza** [comment]
thanks I'm working on it

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to be published. 👍

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
