### ISSUE TITLE
[Languages] A look at C-Sharp coding conventions.

### ISSUE THREAD

**Issue by amosnjoro** [section-engineering-education/engineering-education#4147]
#### Proposed title of article
[Languages] A look at C-Sharp coding conventions.

#### Proposed article introduction
Coding conventions are a set of recommendations for programming style, practices, and methods for each aspect of a program written in a specific programming language. 

Coding conventions serves various purposes as listed below.
1. They make it easier to copy, change, and maintain code.
2. They help readers grasp the code more quickly by allowing them to make assumptions based on prior knowledge.
3. They give the code a uniform appearance so that readers can concentrate on the content rather than the layout.

The standards are what makes a code look neat because it has met almost everything and the probability of it having an error is very low. Such standards include the layout conventions, naming conventions and many others.

#### Key takeaways 
1. Layout conventions.
2. Naming conventions
3. Commenting conventions.

#### Article quality
In this article, I want to provide content that clearly shows that 
there are rules that are applied when programming. Many people just code but I  will have to deeply explain what this rules entails and how how to go about it
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Closing this issue since the PR was closed.
