### ISSUE TITLE
Building Myers Briggs Personality Test App with Python

### ISSUE THREAD

**Issue by CaptainBKola** [section-engineering-education/engineering-education#4150]
#### Introduction
This article focuses on how to implement python data structure with a substantial flow with python functions that enable  I/O operations in a python data structure such as list and format specifiers which display a string of characters in a table. 
According to  Isabel Briggs Myers, there are sixteen types of personalities identities and there are four key elements of categorizing people into the various sixteen personalities identities. The four key elements are:
- Introversion (I) vs. Extraversion (E)
- Sensing (S) vs. Intuition (N)
- Thinking (T) vs. Feeling (F)
- Judging (J) vs. Perceiving (P)
  More information on personality typing is here (https://www.truity.com/page/16-personality-types-myers-briggs)
The test contains the four stages above and provides the personalities of the user base on the most common options in the user's test answers. In order words, the questions are structured to determine if the user is an introvert or extravert, sensing or intuition, thinking or feeling, judging or perceiving. In this test app,  we prompt users for questions related to each of the four stages above and categorizes people into the below personality types: INFP, INTJ, INFJ, INTP, ENFP, ENTJ, ENTP, ENFJ, ISFJ, ISFP, ISTJ, ISTP, ESFJ, ESFP, ESTJ, ESTP. For more information about personality identities kindly follow the link below: https://www.truity.com/page/16-personality-types-myers-briggs

#### The goals of this tutorial are to:

1. Makes convincing concepts clearer and understanding enough for beginners.
2. Shows the implementation of python list in a way that enables the reader how list can be used in I/O applications such as quiz app.
3. Makes a clean implementation of formatting strings in python in relation to data representation in a table.
4. Shows how to write python functions for the list, string, and floating-point manipulations.

#### Reference
- [Myers Briggs Personality Interpretation](https://www.truity.com/page/16-personality-types-myers-briggs)
- [introduction to computer and python](https://deitel.com/wp-content/uploads/2019/11/intro-to-python-for-computer-science-and-data-science-table-of-contents.pdf)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
