### ISSUE TITLE
How to upload files to Cloudinary in a flutter application

### ISSUE THREAD

**Issue by Lekwacious** [section-engineering-education/engineering-education#4151]
#### Proposed title of article
How to upload files to Cloudinary in a flutter application

#### Proposed article introduction
Uploading files directly from you android phone in a flutter application to your backend servers requires some heavy server-side processing, bandwidth and storage space. Processing and storing your files in the database is a costly operation as it increases the storage space of your database. A way to solve this problem is to transfer files such as images, pdfs, Docs to a cloud storage. While some developers handle file upload operation on their  servers and then transfer them to the cloud, this works but it is a waste of server resources.

This tutorial will teach you how to turn this costly operation into a lightweight operation that bypasses the backend servers entirely.

#### Key takeaways 
In this tutorial, you will learn:
- How to pick any from you android device and upload it to your flutter application.
- How to upload upload a file to Cloudinary and send the file URL to the backend server
- How to check the size of your file.
- How to limited the upload of certain types of files etc.

#### Article quality
This article provides more depth to what is available out there. It covers the upload of any type of files and  provides a production-grade coding style.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Lekwacious 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
