### ISSUE TITLE
Using PHP, create a Shopify-style shopping cart with sticky checkout.

### ISSUE THREAD

**Issue by Danco10** [section-engineering-education/engineering-education#4152]
#### Proposed title of the article
Using PHP, create a Shopify-style shopping cart with sticky checkout.

#### Proposed article introduction
PHP is the primary technology that powers the majority of online shopping cart software. Creating a full-featured PHP shopping cart application is not as simple as it appears.

We'll look at how to make a featured sticky shopping cart script in PHP in this tutorial. Sticky shopping cart checkout is a feature of Shopify, which is an eCommerce platform.

#### Key takeaways 
1. Benefits of a Stuck Shopping Cart
2. Product gallery and shopping cart components on a landing page
3. Create a gallery of product tiles.
3. Show items in the cart from a PHP session 4. Edit, delete and empty the cart

#### Article quality
This article will be unique and easy to comprehend 

#### References
N/A

Happy coding

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
