### ISSUE TITLE
[Java] Understanding Enum Types in Java: Building A Card Dealing and Shuffling App that  determines the hand ranking category of the player’s hand

### ISSUE THREAD

**Issue by ehizman** [section-engineering-education/engineering-education#4154]
#### Proposed title of Article
[Java] Understanding Enum Types in Java: Building A Card Dealing and Shuffling App that  determines the hand ranking category of the player’s hand

#### Proposed article introduction
Enums types are powerful tools in Java. Enums could be used to define a class of named constants and offer the advantage of type safety. They could also be used as keys in a switch statement or expression. 

This article explains the basic structure of an enum class and then takes it a step higher by exploring the relationship between enums and classes(enums implementing interfaces, instance variables, methods and constructors), exploring how to set custom enum ordinals. Finally, the article concludes by demonstrating the application of enums in building an app that determines the hand ranking category of a player’s hand in a poker game.

#### Key takeaways
At the end of the tutorial, the reader should understand the following;
- The basic structure of an enum type
- The relationship between enums and classes:
      - Defining constructors, instance and methods variables in enum classes
      - Enums implementing interfaces
- Defining custom ordinals for enum types and accessing ordinal values for enum constants.
- The application of enums in building a card shuffling and dealing application that determines the hand ranking category of a player’s hand in a poker game.
- The reader will also gain an understanding of some Java Lambda functions

#### Article quality
During my research about enum types in Java, I discovered that most tutorials offer only a basic explanation about enum types and their uses. My article offers an exhaustive exploration of the topic curated from a number of sources from the internet. Also, my article contains demonstrations on how to use enums by building a part of a poker app that determines the hand ranking category of a player’s hand utilizing Java Lambda functions in the process.

#### References
https://stackoverflow.com/questions/5372855/can-i-specify-ordinal-for-enum-in-java
https://en.wikipedia.org/wiki/List_of_poker_hands
https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html
https://www.w3schools.com/java/java_enums.asp

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ehizman** [comment]
Okay, thank you

**Comment by louisefindlay23** [comment]
Thanks for your detailed explanation about what makes your proposed article unique, @ehizman. Topic approved 🚀.
