### ISSUE TITLE
[Languages] Create a JavaScript Covid 19 Tracker: A complete guide

### ISSUE THREAD

**Issue by djayjames** [section-engineering-education/engineering-education#4157]
#### Proposed title of the article
[Languages] Create a JavaScript Covid 19 Tracker: A complete guide

#### Proposed article introduction
In this tutorial, we'll use HTML, CSS, and Javascript to create a web-based COVID 19 tracker that monitors coronavirus cases across the world over the past three months and displays them in a bar graph. The project is straightforward and simple. 

The project in this article will be ideal for the novices and experts to test their skills in JavaScript

#### Key takeaways 
By the end of this tutorial, the reader will have understood:

- API
- Promises
- Bootstrap
- ChartJS
- Brain!

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
