### ISSUE TITLE
Difference between File handling in Java and C#

### ISSUE THREAD

**Issue by apondi-911** [section-engineering-education/engineering-education#4159]
#### Proposed title of article
[Languages] Difference between File handling in Java and C#

#### Proposed article introduction
 A file is a unit of storage that stores data permanently in the form of a sequence of bytes on a disk. File handling now is a process of storing data in a file using a program.

In Java, we use FileReader and FileWriter classes respectively to read and write data from text files whereas, for C# we will use the FileStream class which is used to read from and write to any location within the file. C# also uses the StreamWriter class which we will discuss more in this article. 

File handling helps in preserving the data or information generated after running the program. File handling in Java and C# permits, creating, deleting, updating, and reading files.

#### Key takeaways 
- How to use the classes specific for file handling
- How to create, delete, update and read  files 
- Importance of file handling

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
