### ISSUE TITLE
Introduction to Deep Learning using Python 

### ISSUE THREAD

**Issue by mbuguac** [section-engineering-education/engineering-education#4168]
#### Proposed title of article
Introduction to Deep Learning with Python. 

#### Proposed article introduction

Deep learning is a type of machine learning  and Artificial intelligence based on artificial neural network. For one to achieve high level features from data it is essential to use Deep learning. It imitates the way humans gain certain types of knowledge which then becames useful in data science which includes statistics and predictive modeling. 
    This article will be a very important tool to get you started in the field of Deep learning.You will be guided through every single step of Deep learning. What you thought was hard will be the simplest thing you have ever tried to understand.A journey of a thousand steps begins with a single step. This is your first step into the journey of Deep learning. 

#### Key takeaways 
a) what is deep learning and why python for deep learning. 
b) How deep learning works. 
c) Application Areas of deep learning. 
d) The need for deep learning today
e) instalation of softwares and tools to get you started with deep learning. 

#### Article quality
This article will give simple and understandable examples of deep learning and how to use deep learning using simple and understandable grammar. It will make it easier for someone who doesn't know programming to understand and be more interested to venture in to this field. 

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by mbuguac** [comment]
@mercymeave  I am now ready.
