### ISSUE TITLE
[Machine Learning] Getting started with Azure Machine Learning Service

### ISSUE THREAD

**Issue by Pelmak** [section-engineering-education/engineering-education#4171]
### Topic Suggestion
Machine Learning
#### Proposed title of article 
Getting started with Azure Machine Learning Service.

#### Proposed article introduction
Azure Machine Learning (Azure ML) is a cloud-based service for creating and managing machine learning solutions.
In this tutorial, I am going to show you how to create an Azure account and AMLS workspace. After you've got built a workspace, you will need to construct several sorts of compute to execute Python code and system mastering responsibilities over a cluster of computer systems. Then, with the use of the Azure dataset and datastore systems, you may discover ways to engage with information.

lastly, we're going to go over AutoML briefly. Your ability to create can be enhanced because of these fashions that work well.

#### Key takeaways 
The learner will be able to;
- Create a workspace.
- Construct compute to run AutoML tasks.
- Work with data in AMLS.
- Understand how AutoML works in Azure.

#### Article quality
This tutorial is direct to the point such that beginners and experts
 will find it easy to understand every detail in a simple way.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
