### ISSUE TITLE
Creating a Browser Extension in Vuejs

### ISSUE THREAD

**Issue by EspiraMarvin** [section-engineering-education/engineering-education#4175]
### Topic Suggestion

[Nodejs] Creating a Browser Extension in Vuejs

#### Proposed article introduction

A Browser Extension (BEX) is an application that runs in the browser's context and is used to customize the web browser in some way adding specific features to it. 
This is useful when one needs a specific feature on their browser that is not available to them by default.
Browser Extensions can do the following

- Override page content
- Add to (or alter) the browser’s interface. Such as dark mode readers, screen/tab recording.
- Intercept page requests 
- Be a full-featured app that runs in the browser.
- Interact with and alter the development tools of the browser.

#### Key takeaways 

In this article, the reader will be able to.

- Understand what a browse extension is
- Know the different types of Browser Extensions namely New Tab, Web Page, Dev Tools Options, or Popup. 
- Create a simple time browser extension using Vuejs
- Install the browser extension in their browsers

#### Article quality

This article will be unique as it will be able to cover the four different types of browser extensions, it will be able to describe the browser extension hooks (Content and Background hooks) and finally one will be able to install the browser extension.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
