### ISSUE TITLE
[Languages] Convert HTML to PDF with DocRaptor

### ISSUE THREAD

**Issue by taves-hub** [section-engineering-education/engineering-education#4179]
#### Proposed title of article
Convert HTML to PDF with DocRaptor

#### Proposed article introduction
Producing PDFs is a typical programming task. PDFs are utilized to make solicitations, receipts, eBooks, distributing reports and the sky is the limit from there. Tragically, automatic age of PDF can be troublesome, particularly in the event that you need to create numerous PDFs quickly. 
DocRaptor is a HTML-to-PDF API that extraordinarily improves on the issue, and they have a PHP library for simple joining. In this instructional exercise, learners will be able to  stroll through how to change over HTML into a PDF with DocRaptor:
#### Key takeaways 
After reading this article learners will be conversant in:
- Installation
- Authentication
- Add HTML or a URL
- API Options
- Get the document!

#### Article quality
This article will help learners with the basics they need to get started with DocRaptor. Many articles out there  only rely on official documentation and some of the examples they offer are a bit too harsh for novices in PHP. This article will be ideal for novices and the code snippets involved will be illustrated clearly and will be straight on point.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
