### ISSUE TITLE
[Machine learning] How to deploy machine learning model as an app in Python using Gradio

### ISSUE THREAD

**Issue by kelvinkimani501** [section-engineering-education/engineering-education#4190]
#### Proposed title of article
[Machine learning]How to deploy machine learning model as an app in Python using Gradio.

#### Proposed article introduction
Gradio is an open-source python library that permits you to rapidly make simple to utilize, adjustable UI parts for your ML model and any API.  Gradio also provides customizable components like buttons, textboxes, check boxes, file dialogs which make it easier to make beautiful user interfaces.

Gradio can be embedded in Python notebooks or presented as a webpage and doesn't require a separate python script.. A Gradio interface can automatically generate a public link you can share with colleagues that lets them interact with the model on your computer remotely from their own devices also once you've created an interface, you can point Gradio towards the GitHub repository where it is contained. Gradio will host the interface on its servers and provide you with a link you can share. This has made Gradio be a great and popular tool for machine learning.

Gradio is more useful in the following ways:
- Creating demos of your machine learning code for clients/collaborators/users
- Getting feedback on model performance from users
- Debugging your model interactively during development

In this tutorial, we will build a machine learning model from scratch and then deploy the model as an app using Gradio by creating a user interface for the model.

#### Key takeaways 
1. What is Gradio.
2. How to install Gradio.
3. Building a custom machine learning model.
4. Working with Gradio user interface.
5. Deploying the machine learning model as app using Gradio.

#### Article quality
This article undergoes all the stages of machine learning. We start we preprocessing our dataset, after cleaning the data we will build and train the model and we get the best prediction.
From there we introduce Gradio, we start with basics before we go deeper and implement the model user interface.

Using this custom model, a person can be able to follow from the start and be able to deploy an machine learning model using Gradio.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Closed #4190 via #5369
