### ISSUE TITLE
How To Build Deep learning Models Using Tensorflow With Python 

### ISSUE THREAD

**Issue by TimedH** [section-engineering-education/engineering-education#4194]
#### Proposed article introduction
Google designed and distributed TensorFlow, a Python library for fast numerical computing.
It's a foundation library that can be used to develop Deep Learning models directly or via wrapper libraries built on top of TensorFlow to make the process easier.
In this article, readers will be able to learn more about the TensorFlow Deep Learning library.

#### Key takeaways 
What's Tensorflow?
Importance of deep learning
Steps of Tensorflow Algorithm

#### Article quality
This article goes over the entire machine learning process. We begin by preprocessing our data, after which we will create and train the model to obtain the best prediction.

Unlike the other articles my article will give step to step procedure on how to deploy deep learning models using Tensorflow  with python. I'll use simple grammar, and with all these my article will be useful to readers who are still beginners in machine learning.

**Comment by louisefindlay23** [comment]
Please fill in the article quality section, @TimedH so we can accurately review your topic suggestion?
