### ISSUE TITLE
How To Manage Your Linux Server Using The Command Line Interface

### ISSUE THREAD

**Issue by IsaacMuthini** [section-engineering-education/engineering-education#4195]
#### Proposed title of article

How To Manage Your Linux Server Using The Command Line Interface

#### Proposed article 
When working with cloud-based servers, you should be able to execute administrative activities using simple Linux commands. These commands are useful for a variety of tasks, including installing applications, monitoring server resources, and managing the file system.

Although you may control your server with a variety of GUI-based apps, the command-line interface is free, quick, and simple to use. It gives you additional control, especially if you're using an OpenSSH Client to connect to your server remotely. You'll learn how to use the most powerful and common Linux commands on your server with this tutorial.
#### Key takeaways 
From this article a learner will be able to learn the following:
1. Linux Server Administration Commands
2. Linux File Management Commands
3. User Management Commands
4. Memory, Disk, and CPU Management Commands
5. File Searching Commands

#### Article quality
In this article I will be going in depth how each command is used.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by IsaacMuthini** [comment]
This article is designed for new users of the Linux operating system and also those interested. It will be simple and to the point and am going to show all the results in a way every learner will understand what they are doing.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
