### ISSUE TITLE
How to Automate Keyboard and Mouse Control Using Python

### ISSUE THREAD

**Issue by Naomibitutu** [section-engineering-education/engineering-education#4197]
Automation of the keyboard and mouse is the process of using python scripts to control the mouse and keyboard. This is made possible by the use of a python module known as PYAUTOGUI.

PYAUTOGUI is not an in-built python module and therefore, we need to import it and use it as a library function. The beauty of this feature is that, it helps to avoid doing repetitive tasks such as dragging and clicking the mouse.

### Pre-requisites
The following needs to be done for you to follow along this tutorial:
- Have basic Python knowledge.
- Install python in your laptop or in the  machine you are using. 
- A code editor of your choice but for this particular tutorial, we will use VS Code.
- Install PYAUTOGUI.

#### Key takeaways 
By the end of this interesting By the end of this interesting tutorial, you should be able to:
- Know how to do keyboard and mouse automation.
- Apply automation of keyboard and mouse in your real life activities. should be able to:

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Closed #4197 via #4580
