### ISSUE TITLE
[Android] Implementing Security Rules In Android Applications

### ISSUE THREAD

**Issue by Collince-Okeyo** [section-engineering-education/engineering-education#4201]
#### Proposed title of article
[Android] Implementing Security Rules In Android Application

#### Proposed article introduction
When you safeguard the data that you exchange between your app and other apps, or between your app and a website, you improve your app's stability and protect the data that you send and receive. 

The article is going to cover the security rules that are required to make an android app secured. It will cover on how to:
- Apply network security measures
- Disallow access to your app's content providers
- Store data safely
- Share data securely across apps
- Provide the right permissions
- Add a network security configuration
- Ask for credentials before showing sensitive information
- Apply signature-based permissions
All these ensures that the application's security is maintained as well as user's data. 

#### Key takeaways 
- What are the android security rules.
- Reasons for Android security rules.
- How to implement security rules.

#### Article quality
My article has covered a wide range of security rules in android. It also have hands-on practical codes showing the implementation of security rules.

#### References
https://developer.android.com/topic/security/best-practices

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
@Collince-Okeyo - please add more content on your article introduction so we can guage it's quality. Thanks.

**Comment by Kayere** [comment]
Approved @Collince-Okeyo

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
