### ISSUE TITLE
Integrating MongoDB with Java

### ISSUE THREAD

**Issue by muthoni2-lucy** [section-engineering-education/engineering-education#4206]
#### Proposed title of article
How MongoDB integrate with JAVA 

#### Proposed article introduction
Here, we are going to learn how to connect MongoDB with java. MongoDB is based on a document model and can be written in C++, JavaScript and python.

#### Key takeaways 
After reading the article the reader should have learnt the following:
1. What MongoDB is
2. MongoDB vs Relational database structure
3. Required tools for connection
5. Creating MongoDB collection
6. Selecting a created MongoDB collection
7. What a document is and how it works with different anomalies(insert, update and delete)

#### Article quality
My topic involves basic knowledge that is easy to understand.

#### References
N/A

**Comment by Kayere** [comment]
@muthoni2-lucy - could you please add more content on your introduction for us to gauge the quality of your article.

**Comment by muthoni2-lucy** [comment]
In my article I will also compare integrating MongoDB with java in Eclipse and IntelliJ

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by muthoni2-lucy** [comment]
hello @ahmadmardeni1 can you open my topic I'm ready to PR

**Comment by hectorkambow** [comment]
@muthoni2-lucy 

Has there been a pull request attached to this issue??

**Comment by muthoni2-lucy** [comment]
i'm working on it

**Comment by muthoni2-lucy** [comment]
hello @ahmadmardeni1 can you check my PR #6743

**Comment by hectorkambow** [comment]
This issue has been linked to 4 PRs.
