### ISSUE TITLE
[Languages] Building GraphQL APIs in Django with Strawberry

### ISSUE THREAD

**Issue by Samuel-2626** [section-engineering-education/engineering-education#4210]
#### Proposed title of article
Building GraphQL APIs in Django with Strawberry

#### Proposed article introduction
[GraphQL](https://graphql.org/), which was released publicly by Facebook in 2015, is a data query engine that allows clients to specify exactly what data they want to retrieve from the server. Before GraphQL, REST, which stands for Representative State transfer, was the standard convention that dictated how HTTP communication should be done. Using REST, you can create, retrieve, or modify resources in a system by using HTTP verbs or commands. GraphQL only works with one REST endpoint. In addition, it is a piece of code that runs on your server. It works by assigning an endpoint, usually called `/qraphql`, to a piece of code (or software) that is a GraphQL-server. The server will then take the endpoint from the client and convert them into a map of data it needs to send back to the client.

GraphQL's three major concepts are **Queries** to perform a backend call that does not mutate data, **Mutations** to alter data and **Subscriptions** to enable clients to subscribe for events.

GraphQL is schema-based. This means that you must define exactly what can go to the server and what can leave it. This leads to the concept of "No over-fetching", i.e. The client can specify the field that should be returned to back to it.

#### Key takeaways 
- Building a GraphQL API in Django with Strawberry
- Testing the GraphQL API

#### Article quality
This tutorial would be project-based, readers would be building a **zoo** keeping GraphQL API backend.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
