### ISSUE TITLE
[Languages] Introduction To Pragmatic Functional Java

### ISSUE THREAD

**Issue by Shikomary** [section-engineering-education/engineering-education#4217]
### Topic Suggestion
Introduction To Pragmatic Functional Java

#### Proposed article introduction
Practical Java (PFJ) is an effort to develop and define a whole new programming style for the popular programming language Java. coding approach which utilizes both existing and future Java capabilities to the fullest extent possible and makes use of a compiler to assist programmers in creating code that is both succinct and dependable while still being easy to understand and follow.

While Java 8 may still utilize this style, Java 11 makes it considerably more streamlined and readable. With Java 17, it becomes even more expressive and gains from every new feature of the Java language.
Even yet, the benefits of PFJ don't come for free. Developers will have to make substantial adjustments to their working practices. Making a habit change is difficult, and classic necessary ones are particularly difficult.
In this article, we will discuss this concept in a more detailed way.

#### Key takeaways
By the end of this tutorial the reader will understand the following;

 - Elements Of Pragmatic Functional Java
 - Avoid null As Much As Possible (ANAMAP rule)
 - No Business Exceptions (NBE Rule)
 - Transforming Legacy Code Into PFJ Style Code
 - Interfacing With Legacy Code
 - Providing Legacy API
 - Managing Variable Scopes
 - Brief Technical Overview of Option<T> and Result<T>

#### Article quality
This article will be a unique article. Where I will explain the concepts in a more detailed way to add value beyond what is in the official documentation. I will make sure the article adds value to the rest of EngEd.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
