### ISSUE TITLE
[Android] Side-effects and Effects Handling in Jetpack Compose

### ISSUE THREAD

**Issue by tanscy-cassie** [section-engineering-education/engineering-education#4223]
#### Introduction
Composables should be side-effect free. However, when they're necessary to mutate the state of the app, they should be called from a controlled environment that is aware of the lifecycle of the composable. When you need to make changes to the state of the app, we use the Effect APIs so that those side effects are executed in a predictable manner.
A side effect is simply anything that escapes the scope of a function, such effects can cause our app to fail. Effects Handler is safe environment where we do side-effects handling.

#### Key takeaways 
- What are Side-effects and how they occur
- How to create side-effect free Composables
- How to handle side-effects on our code

#### References
https://developer.android.com/

**Comment by WanjaMIKE** [comment]
Closed #5042 via #4223
