### ISSUE TITLE
[Languages] How to create popup contact form dialog using PHP and jQuery.

### ISSUE THREAD

**Issue by Kamau-ke** [section-engineering-education/engineering-education#4225]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed article introduction

A contact form is an essential component of your website. It promotes interaction and serves as a link between you and your users. It allows users to provide feedback, comments, and questions, among other things.

It assists you in obtaining thoughts and perspectives that can help your company expand. It is one of the most crucial factors that will determine your success.

Designing a PHP contact form is a straightforward task. I've seen a lot of examples of how to make a contact form in PHP. The fundamental code skeleton is shown in the simple contact form example. It includes only a few fields and a straightforward mail-sending script.

#### Key takeaways 
1. Purpose of the contact form on a web application
2. Things to remember while creating a contact form
3. About this example
4. File structure
5. Create HTML interface for the contact form
6. PHP script to send contact email
7. PHP contact form popup with jQuery Output

#### Article quality
My article will be simple and understandable by people at different skill level.
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
