### ISSUE TITLE
Integrating OTP Verification in Android

### ISSUE THREAD

**Issue by Brian3811** [section-engineering-education/engineering-education#4233]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed article introduction
OTP (One Time Password) verification has become an important aspect of user verification, whether it's for E-commerce transactions or login / sign up checks. Because it is difficult to hack, it is more widely used and safe.
It is, in fact, the first step in user validation for practically every Android app.
There are a few factors to consider while choosing your SMS OTP messaging gateway / service provider in order to make this as simple as possible for the user and clients.

#### Key takeaways 
What is OTP verification?
Data Confidentiality
Steps of Intergrating OTP verification in Android

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
This topic suggest appears to be similar to https://github.com/section-engineering-education/engineering-education/issues/3520 Feel free to suggest another one. Thanks
