### ISSUE TITLE
WhatsApp Sentimental Analysis using Dialogflow Twilio Integration

### ISSUE THREAD

**Issue by Jethro-magaji** [section-engineering-education/engineering-education#4234]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
WhatsApp Sentimental Analysis using Dialogflow Twilio Integration

Use keyword research to improve your article's SEO.

#### Proposed article introduction
In this tutorial, we will build a WhatsApp chatbot that will tell you how people feel about a topic based on sentiment analysis of tweets on that topic. We will build this chatbot using Dialogflow and the Google Cloud Natural Language Processing API to analyze the tweets, and Twilio for WhatsApp integration.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

#### Key takeaways 
- The reader will learn how to perform sentimental analysis on using Google cloud natural language processing API
- The reader will learn how to build chatbots with custom intents using Dialogflow
- The reader will learn how to work with Twitter API
- The reader will learn how to connect the build API's using Twilio
- The reader will learn how to connect a chatbot to WhatsApp using Twilio

#### Article quality
Compared to other articles on the web on Dialogflow chatbots mine gives an in dept explanation how to integrate a chat application to multiple API's like Twilio, Google cloud natural processing API and Twitter API, and also perform sentimental analysis on responses.
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
- https://www.twilio.com/docs/voice/twiml/stream/connect-to-dialogflow
- https://levelup.gitconnected.com/dialogflow-twilio-integration-using-google-cloud-3b4b7adbccbd
- https://cloud.google.com/dialogflow/es/docs/integrations/twilio

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
