### ISSUE TITLE
How to Automate Tests for Dockerized Django Application with GitHub Actions

### ISSUE THREAD

**Issue by khabdrick** [section-engineering-education/engineering-education#4237]
#### Proposed title of article
How to Automate Tests for Dockerized Django Application with GitHub Actions

#### Proposed article introduction
It’s always a good idea to use GitHub Actions for your project because it makes it easy to automate processes through which include; testing and deploying your project. Docker helps make sure your app works the same way on all platforms. Adding these functionalities to your application can make it easy for CI/CD and collaboration.

#### Key takeaways 
- Learn how Docker and Docker-compose work together
- Introduction to continuous delivery
- How to Automate Django tests with GitHub Actions

#### Article quality
This article is not available on the web

#### References
https://testdriven.io/blog/deploying-django-to-digitalocean-with-docker-and-github-actions/

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by khabdrick** [comment]
> @khabdrick I think Heroku is a competing company to section. Kindly, modify your topic suggestion. Thanks

Hello @WanjaMIKE I have editted the topic suggestion

**Comment by khabdrick** [comment]
I'll start working on this, how much should I expect from this article @WanjaMIKE

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
