### ISSUE TITLE
Queries or Stored Procedures in SQL ? 

### ISSUE THREAD

**Issue by AdahMilly** [section-engineering-education/engineering-education#4239]
#### Proposed title of article
Queries or Stored Procedures in SQL ?

#### Proposed article introduction
This article is aimed at equipping a reader with knowledge to help them create  a database, tables, views.
It will also guide one on writing stored procedures and queries, and the one that is easier to use.

#### Key takeaways 
Introduction to SQL, creating database, tables.
What are queries?
Writing queries.
What are stored procedures
Writing stored procedures.
Stored procedures vs queries.
Stored procedures in action using Nodejs. 

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
