### ISSUE TITLE
[Security] How Kerckhoff's Principle is Applied in Cryptography.

### ISSUE THREAD

**Issue by leence00** [section-engineering-education/engineering-education#4247]
#### How Kerckhoff's Principle is Applied in Cryptography.
Kerckhoff's state that a cryptographic system should be secure even if everything about the system except the key is publicly known
According to Kerckhoff's Principle, a cryptographic system's security is solely dependent on the secrecy of its keys, and everything else, including the algorithm itself, should be regarded public knowledge. 

#### Key takeaways 
- Understand the state principle of kerckhoff's principle
- Get to know the origin of kerckhoff's principle
- Have an understanding on various fundamental principles of crypto system
- The relationship between Kerckhoff's principle and Shannon's Maxim principle
- Difference between kerckhoff's principle and Security by Obsecurity

#### Article quality
This article aims to explain how to develop secure systems with this kerckhoff's principle which is not covered in most article

#### References
[kerckhoff's principle](http://www.crypto-it.net/eng/theory/kerckhoffs.html)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by leence00** [comment]
Hello @WanjaMIKE  following the available documentation that has already covered Kerckhoff's principle my article will differ with it in that  it will cover..
 the  understanding on various fundamental principles of crypto system explained by the Kerckhoff's principle ,
the difference between Kerckhoff's principle and Security by Ob-security and I am aiming at writing a simplified article and easy to understand by any individual.

**Comment by WanjaMIKE** [comment]
Okay. Topic approved. Let's ensure that it adds value to the community. Thanks
