### ISSUE TITLE
Custom Pagination  Using Django rest framework and Vue.

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#4250]
#### Proposed title of article
Understanding Custom Pagination Using Django rest framework and Vue.

#### Proposed article introduction
On most modern web applications and websites, one will need to split the app content for better user experience and readability. This makes the app users focus on small content at a time. To do this with ease, Django comes with a pre-built class: Paginator, which creates and manages paginated data of applications using the default pagination styles.
Sometimes, one may want to customize and use a modified format to paginate data. This article will enable the reader to understand how to customize and modify the default pagination styles to suit users' needs using Django REST APIs with Vue. The reader will also learn the various ways to paginate data; Class-based views and Function-Based views and the importance of web pagination.
#### Key takeaways 
The reader will be able to:
- Understand what pagination is and its importance.
- Various ways of paginating web apps using Django.
- Understand how to customize and modify pagination styles using Django REST API with Vue.

#### Article quality
The article will help one understand how to use a modified format of the pagination styles by customizing the default pagination styles using Django REST Framework with Vue.
#### References
N/A

### Templates to use as guides
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
This topic may crash with another one that was closed some few weeks ago. @dentonya what do you think https://github.com/section-engineering-education/engineering-education/issues/3727
