### ISSUE TITLE
[machine Learning]Interfacing spark with python through PySpark

### ISSUE THREAD

**Issue by immah-mul** [section-engineering-education/engineering-education#4252]
### Topic Suggestion
Interfacing spark with python through PySpark
#### Proposed title of article
Interfacing spark with python through PySpark, the part that is often ignored by most authors.

#### Proposed article introduction
When it comes to dealing and working with Big Data, Apache Spark is one of the most extensively used frameworks, and Python is one of the most widely used programming languages for Data Analysis, Machine Learning, and much more.
Python integration with Spark was a huge boost to the community. Spark was written in the Scala programming language, which is quite similar to Java. It converts computer code to bytecode for Spark large data processing on the JVM. PySpark was created by the Apache Spark community to support Spark with Python.
In this tutorial, I will explain the following found in keytakeaways.

#### Key takeaways 
1. Introduction to Apache Spark and its features
2. Why go for Python?
3. Setting up Spark with Python (PySpark)
4. Spark in Industry
5. PySpark SparkContext and Data Flow
6. PySpark KDD Use Case

#### Article quality
I will elaborate on why Scala(programming language for Spark) lacks data visualization

#### References
- python languge

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
