### ISSUE TITLE
Asynchronous JavaScript: Fetching Data from external API using AJAX 

### ISSUE THREAD

**Issue by gmcodes20** [section-engineering-education/engineering-education#4253]
#### Proposed article introduction
[API] This tutorial is focused on creating a JavaScript application that fetches random jokes from an external API using the Chuck Noris Jokes API.

#### Key takeaways 
The user will have a basic idea of what APIs can do
At the end of this tutorial, the reader should be able to make a call to an external API to get a result
Readers should be able to understand how AJAX works.

#### Article quality
My tutorial is unique because it is a detailed step-by-step guide on creating your first API request using AJAX. it is suitable for beginners and easy to understand

#### References

[Using AJAX with vanilla JavaScript to get Data from External API](https://medium.com/@muniratolayiwola/using-ajax-with-plain-javascript-to-get-data-from-external-api-afc6561894d9)

[How to use simple API using AJAX ?](https://www.geeksforgeeks.org/how-to-use-simple-api-using-ajax/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Okay. Topic approved. Let's ensure that it adds value to the community. Thanks
