### ISSUE TITLE
[Blockchain] Blockchain as a form of e-voting

### ISSUE THREAD

**Issue by csamuelsm** [section-engineering-education/engineering-education#4254]
### Introduction

Satoshi Nakamoto, in his famous paper *Bitcoin: A Peer-to-Peer Electronic Cash System* begins by talking about how the Internet's commerce and transaction system suffers from a trust-based model. Furthermore, Nakamoto mentions this model's need for a central authority that acts as an intermediary for transactions, that is, any and all transactions must go through this central authority. Think, for example, of a bank. Nakamoto's proposal in his paper is precisely that of a decentralized and highly secure technology as an alternative to this current model: the Blockchain.  

Drawing a parallel with a voting process, its integrity and effectiveness also depend on voters' trust and in the authorities that organized it. Electronic voting can improve some aspects of manual voting such as the speed, simplicity, and flexibility of the process. On the other hand, they bring red flags that deserve attention and care, such as issues of secrecy, privacy, transparency, and security.  Some places around the world have used some form of electronic voting or experimented with this voting model. In my country, Brazil, electronic voting machines have been used for elections since the 1990s, for example. In Moscow, an e-voting experiment was recently carried out using Blockchain as a backend.

In the words of The Economist, the Blockchain is a way of *" creating and preserving truths"*. In fact, the technology has promising properties for an electronic voting system such as anonymity, decentralization, transparency, immutability, and encryption. In this article, we will briefly see what Blockchain is, then we will see how this technology can be used in electronic voting, its advantages and problems, and end by talking a little about Moscow's experience using Blockchain in an election.

### Key Takeaways

- Quick revision of Blockchain, how it works, and its basic properties;
- How can Blockchain be used in e-voting systems;
- Advantages and problems of using Blockchain in e-voting;
- Example: how was Moscow's e-voting experience using Blockchain.

### References

- [Blockchain for Electronic Voting System — Review and Open Research Challenges.](https://www.mdpi.com/1424-8220/21/17/5874)
- [The great chain of being sure about things.](https://www.economist.com/briefing/2015/10/31/the-great-chain-of-being-sure-about-things)
- [Bitcoin: A Peer-to-Peer Electronic Cash System.](https://bitcoin.org/bitcoin.pdf)
- [How Moscow organized voting on a Blockchain in 2020.](https://ict.moscow/en/news/how-moscow-organized-voting-on-blockchain-in-2020/)

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. It should be different from already published articles on other sites. Thanks
