### ISSUE TITLE
How to ground truth label your datasets for creating autonomous driving systems using Matlab ground truth App

### ISSUE THREAD

**Issue by linetachieng** [section-engineering-education/engineering-education#4255]
#### Introduction
Ground truth labelling is the process of checking the results of machine learning for accuracy in the real world. Autonomous driving systems are cars that can move without a human driver or human intervention. These types of cars perceive the environment using sensors. The ground truth labeller app allows us to label videos and images for automotive applications.
We all know that labelling is a tedious and time consuming process but necessary to create test data to evaluate our perception algorithms. The ground truth labeler is a tool that we have created to alleviate some of this pinpoints. In this tutorial, we will look at how to create ground truth data for object detection and semantic segmentation. We will use algorithms to automate the labelling process and integrate ground truth information from other sensors.

#### Key takeaways 
- Create ground truth data for object detection and segmentation.
- Using algorithm to automate labelling process.
- Integrate ground truth information from other sensors.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@lalith1403 could you check this one out. Thanks

**Comment by linetachieng** [comment]
@lalith1403 the uniqueness of this is that it takes the learner through the step to step process up to the end making it more practical.
