### ISSUE TITLE
Introduction To ASP.NET Core

### ISSUE THREAD

**Issue by GeoffreyKangu** [section-engineering-education/engineering-education#4260]
#### Proposed title of the article.
Introduction To ASP.NET Core

#### Proposed article introduction.
ASP.NET Core is an open-source cross-platform and high-performance framework for developing modern, cloud-enabled, and internet-connected web applications. 

This article intends to take the reader through all the knowledge that he/she needs to know about ASP.NET Core. This includes:
- What is ASP.NET Core.
- Why should he/she use ASP.NET Core.
- The main features of ASP.NET Core.
- The architecture of ASP.NET Core.
- Benefits of using ASP.NET Core.
 
Finally, I shall have a demo project of the ASP.NET Core framework.

#### Key takeaways 
After going through this tutorial, the reader should be able to know:
- what ASP.NET Core is.
- why he or she should use ASP.NET Core.
-  the main features of ASP.NET Core.
- the architecture of ASP.NET Core.
- the benefits of using ASP.NET Core.

#### Article quality
This article intends to take the reader through the importance of ASP.NET Core and enable him or her to make decisions why he or she should use the ASP.NET Core framework to develop his or her projects.

I shall also show the reader how he or she shall be able to come up with an ASP.NET Core project using Microsoft Visual Studio in the demo project part.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
I think these articles here already cover the introductory aspects of ASP.Net Core

https://github.com/section-engineering-education/engineering-education/issues?q=ASP.NET

Most of the key takeaways can easily be found in official documentation. Feel free to suggest another topic. Thanks
