### ISSUE TITLE
How to use LinkedIn API to share content in PHP

### ISSUE THREAD

**Issue by Lucy-300** [section-engineering-education/engineering-education#4264]
#### Proposed title of the article
How to Text Share on LinkedIn using API in PHP

#### Proposed article introduction
This will come in handy if you wish to use the LinkedIn API to allow your PHP website to exchange material with the social network.

LinkedIn has a developer interface that allows users to construct and manage applications that use its API. It offers a variety of APIs as well as specialized services.

It has good instructions on how to use the API. Following the API documentation makes preparing the appropriate API params and handling responses a breeze.

It takes two steps to use the LinkedIn API to share content. The initial step is to verify a person or organization's identity, followed by sharing on LinkedIn.

This post will show you how to use the LinkedIn API in PHP and share it with others.

#### Key takeaways 
1. How to make a LinkedIn text share
2. Develop a LinkedIn API app
3. Create API keys and configure them
4. Get a code of authorization

#### Article quality
This article will be written in the modern PHP version and I will demonstrate how to retrieve a code of authorization. This will make my article more unique than the other articles on other blogs

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
@Lucy-300 I made a modification to the topic title. Is that what you wanted to focus on? Please watch out for grammar and sentence structure.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
