### ISSUE TITLE
Files and Objects Encryption and Decryption in Java using Spring Boot

### ISSUE THREAD

**Issue by teevyne** [section-engineering-education/engineering-education#4268]
#### Pre-submission advice
Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
Files and Objects Encryption and Decryption in Java using Spring Boot

#### Proposed article introduction
Encryption is a mechanism applied in many facets of life, that ensure that data being transmitted is enciphered and kept sealed and secured against prying, unwanted eyes. On one end of the communication channel, the message being sent is encrypted such that only the person, on the other end of the communication channel,; for whom the message is meant, can decipher this cryptic message and get the actual message intended for him.

In software engineering, owing to the growing case of sniffing and security vulnerabilities, it has become even more essential for encryption and decryption to take centre stage in data and message exchange over a network - local or internet-based; especially over HTTP. 

In this tutorial, we will build a gateway for data encryption and decryption in Java using the Spring Boot framework.

#### Key takeaways 
Learners will learn the following:
i.  Symmetric and Asymmetric Encryption Algorithms
ii. Mechanisms for implementing encryption and decryption
iii. Understand why creating a gateway filter for intercepting IO files and object requests is a more viable approach
iv. Implement this algorithm comfortably 

#### Article quality
This tutorial will teach from start to finish how data encryption is done, why it is necessary and where best to put up this mechanism.

How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

This is a unique, more-indepth tutorial. Similar one describe the process but do not show how it is implemented, with a code-focused approach. The approach applied here is via a gateway rather than an in-method one and covers links to additional topics for easier understanding

#### References
N/A

### Conclusion
Data sent over networks would be secured

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Topic approved. Let's ensure that it adds value to the community. It should also be different from other preexisting articles on the internet. Thanks
