### ISSUE TITLE
Delegates and Events in C#

### ISSUE THREAD

**Issue by Jeddy947** [section-engineering-education/engineering-education#4270]
#### Proposed title of article
Delegates and Events in C#

Use keyword research to improve your article's SEO.

#### Proposed article introduction
A delegate is an object or a type that can refer to a method (holds a reference to a method). This concept is similar to function pointers in C/C++ programming language. A delegate holds references only to those methods whose signature (parameter list) matches with the delegate. A delegate is useful when you want to pass a function as a parameter, and which can be achieved by declaring a delegate using `delegate` keyword followed by a function signature.

An event is an occurrence of a particular action. It can occur when you press the keyboard key, mouse clicks or movements, etc. Events are built upon the foundation of delegates hence they are co-related. Moreover, events are based on the publisher-subscriber model, which means when a class raises an event its called publisher, whereas when a class receives or handles the event, its called subscriber.

In this article, we will look at delegates and events giving the reader a better understanding between the two concepts.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
1. What are delegates?
2. What are events in C#
3. Advantages and important features of delegates
4. Examples to better understanding of the two concepts

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
