### ISSUE TITLE
Hibernate Query Language(HQL)

### ISSUE THREAD

**Issue by Jairusonkundi** [section-engineering-education/engineering-education#4273]
#### Proposed title of article
Hibernate Query Language(HQL)

#### Proposed article introduction
The Hibernate Query Language (HQL) is similar to SQL (Structured Query Language), except that it is not dependent on the database table. In HQL, we utilize class name instead of table name. As a result, it is a query language that is database agnostic.

HQL queries are translated by Hibernate into conventional SQL queries, which in turns perform action on the database. In this article we will  discuss about HQL ,its advantages,its disadvantages,hibernate queries and examples.

#### Key takeaways 
- What is hibernate Query Language?
- Advantages of Hibernate Query Language
- Disadvantages of Hibernate Query Language
- Query Interface
- Hibernate queries and their examples like FROM,SELECT,AS,ORDER BY,GROUP BY, UPDATE,DELETE and INSERT query
- Aggregate methods supported by HQL
- Pagination using query and an example in pagination using query

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, most of the key takeaways in this article appear to be covered or implemented here https://github.com/section-engineering-education/engineering-education/pull/1814/files Feel free to suggest another topic. Thanks
