### ISSUE TITLE
Sentiment Analysis With Naive Bayes Algorithms

### ISSUE THREAD

**Issue by wizardcalidad** [section-engineering-education/engineering-education#4276]
#### Proposed title of the article
Sentiment Analysis With Naive Bayes Algorithms

#### Proposed article introduction
Naive Bayes is one of the most popular and beginner-friendly algorithms that anyone can use. In this tutorial, we are going to explore the Naive Bayes Algorithm.
We want to make a simple sentiment analysis project using Naive Bayes models and discover which of its algorithms is best. Algorithms of Naive Bayes that will be discussed in this tutorial are:
Complement NB, Bernoulli NB, Multinomial NB amidst others. 
Also, it is not a work of which algorithm is best for sentiment analysis, but rather, which of the Naive Bayes Algorithms is best. 
Naive Bayes is a fast, easy to understand, and highly scalable algorithm.

#### Key takeaways 
Understand the working of Naive Bayes, its types, and use cases.
Understanding how to compare algorithms of Naive Bayes best for our case study.

#### Article quality
It's not easy to see the Naive Bayes algorithm working at its full potential, especially trying out its algorithms on a case study. This tutorial is going to use it to the fullest introducing some machine learning concepts that may look unreachable for many students of ML/AI. 
Then again, the project will simulate an NLP use case that can be further integrated into a web app by anyone.

#### Reference(s)
[Introdcution to naive bayes](https://www.analyticsvidhya.com/blog/2021/03/introduction-to-naive-bayes-algorithm/)

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @wizardcalidad

**Comment by wizardcalidad** [comment]
and whats your name on slack so I can reach out for any question Sir

**Comment by lalith1403** [comment]
Hey @wizardcalidad, You can reach me via Slack @Lalith
