### ISSUE TITLE
[Languages] A look at Bootstrap Rating widget

### ISSUE THREAD

**Issue by MichaelmichaelW** [section-engineering-education/engineering-education#4279]
#### Proposed title of article
[Languages] A look at Bootstrap Rating widget

#### Proposed article introduction
Users can utilize the star rating widget to express their feelings on a product, a documentation page, a photo, and more. It's a method of displaying a user's reaction or feedback to a product or service.

With the help of Bootstrap, we'll make a star rating widget in this article. We'll start by learning the fundamentals of the bootstrap rating widget. Following that, with the help of several examples, we'll learn how to construct a bootstrap rating widget. And this will come in line with well detailed examples.

#### Key takeaways 
1. What is bootstrap rating widget?
2. Implement a bootstrap rating widget.
3. Importance of bootstrap in website development

#### Article quality
The main purpose of this article is to provide an in-depth content that will help the learners to understand bootstrap at an advanced level.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic has already been covered here https://www.section.io/engineering-education/a-look-at-some-bootstrap-examples/ Feel free to suggest another topic. Thanks
