### ISSUE TITLE
[API] API Authentication with Django Knox and Postman Testing

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#4281]
### Introduction

Knox provides easy-to-use authentication for Django REST Framework. The aim is to allow for common patterns in applications that are REST-based, with little extra effort; and to ensure that connections remain secure. I will be discussing how to use it, by making a simple API and testing with the postman.

#### Key takeaways 
In this tutorial,  the following are the subjects to be covered:
1. Why Knox is used with Django Rest Framework
2. Designing Rest API endpoints with class-based views
3. Securing endpoints with Django-Knox
4. Testing API with postman application

#### References
https://james1345.github.io/django-rest-knox/

### Templates to use as guides

- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/knox/arafat-olayiwola/index.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Most of your key takeaways appear to be covered by other articles such as https://github.com/section-engineering-education/engineering-education/pull/1475/files. This article will, therefore, focus only on Django Knox which does not make a detailed tutorial. How could you enhance it?

**Comment by Horlawhumy-dev** [comment]
I will dive deep and share more about the Django Knox. 

I will be using it to build an applicattion from scratch by consuming the authenticated rest endpoints with react and redux frontend.  

I can assure that this will make a massive difference and help a lot of engineers out there. Thank you.
