### ISSUE TITLE
[Node.JS]Securing Node.JS web apps with JSON Web Tokens(JWTs) - A comprehensive guide 

### ISSUE THREAD

**Issue by Tee-Stark** [section-engineering-education/engineering-education#4285]
#### Proposed title of article
* Securing Node.JS web apps with JSON Web Tokens(JWTs) - A comprehensive guide

#### Proposed article introduction
* Security is a very important driving factor to be considered when creating any form of software for use, this also includes websites and applications. One way or the other, a website or web app always has some sensitive data to hold as entrusted by its users. At the most minimal level, websites are required to store user login information I.e username or email and password which serve as credentials to verify registered or recognized users.
    At the same time, there are always people who would want to gain unauthorized access to these data and it lies in the hands of the owner or creator of an application to ensure that the best measures possible are implemented to secure their users' information.
There are so many popular ways by which hackers gain unauthorized access to networks, databases, people's credentials, and many more entities on the internet. Almost all of these methods or attacks have countermeasures, and it is very important to be aware of the threats posed by these attacks and how to prevent falling victim to the attacks. A few examples of these attacks are SQL injection, Cross-Site Scripting(XSS), Cross-Site Request Forgery(CSRF), etc. A reasonable amount of the attacks have a goal which is: the attacker impersonating the original user to carry out actions on behalf of the user on the web application. It is therefore the responsibility of every developer to gain some knowledge of the most popular attacks and ways to defend their websites, applications, and users against them.
    In this article, you'll learn how to JSON Web Tokens to authenticate and authorize users of your application, eliminating XSS and CSRF attacks as well as possible.

#### Key takeaways 
* At the end of this article, the reader must have learned:
* The importance of web security and different forms of web attacks
* What JWTs are and what they do
* The pros and cons of JWTs
* How to create a CRUD app with user authentication in Node.JS
* How to store JSON Web Tokens securely

#### Article quality
* This article is unique in the sense that it gives its reader a basic idea of why security is very important in web development today, how important it is to ensure that users won't regret entrusting an application with their information and card details, and many more expo on why it is such a necessity to take the security of web apps seriously. It also adds the bonus of teaching the reader a simple, secure, and optimized method to store JWTs on the client side.

#### References
[jwt.io/introduction](jwt.io/introduction)
[https://fusionauth.io/learn/expert-advice/tokens/pros-and-cons-of-jwts/](https://fusionauth.io/learn/expert-advice/tokens/pros-and-cons-of-jwts/)
[https://jcbaey.com/authentication-in-spa-reactjs-and-vuejs-the-right-way/?utm_source=medium&utm_campaign=spa-authentication](https://jcbaey.com/authentication-in-spa-reactjs-and-vuejs-the-right-way/?utm_source=medium&utm_campaign=spa-authentication)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Unfortunately, we are not accepting more Node.js articles. We have plenty of them at the moment. Feel free to suggest another topic. Thanks
