### ISSUE TITLE
[Languages] A look at Bootstrap Spinners

### ISSUE THREAD

**Issue by MichaelmichaelW** [section-engineering-education/engineering-education#4286]
#### Proposed title of article
[Languages] A look at Bootstrap Spinners

#### Proposed article introduction
A loading indicator is sometimes known as a spinner. It's utilized to show/indicate the state of our projects' loading. To make a Spinner, Bootstrap uses the.spinner class.

They're made entirely with HTML and CSS, so no JavaScript is required to make them. Toggling their visibility will, however, necessitate some special JavaScript. Therefore in this article we will take a deep look  at this topic and with well detailed examples.

#### Key takeaways 
1. Types of spinners.
2. Changing spinners alignment.
3. Changing spinner size.
#### Article quality
I am aiming at producing an original content based on this topic in such a way that it will defer from any other materials that may be published anywhere.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
