### ISSUE TITLE
[Machine Learning] Exploratory Data Analysis with the Binance API using Python and Pandas 

### ISSUE THREAD

**Issue by lcheop** [section-engineering-education/engineering-education#4293]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

[Machine Learning] Exploratory Data Analysis with the Binance API using Python and Pandas 

#### Proposed article introduction

It is a good practice to understand the data first and try to gather as many insights from it. Exploratory Data Analysis (EDA) is all about making sense of data in hand before getting them dirty with it.
In this tutorial,  we're going to take a look at how to apply machine learning and data science to trading and finance. In this first episode we'll take a look at how to extract and analyze real time securities and crypto data from Binance using the API and Pandas.

The Binance API is a method that allows you to connect to the Binance servers via Python or several other programming languages. With it, you can automate your trading.

In addition, we'll also use the `mplfinance` api , a matplotlib utility for the visualization, and visual analysis, of financial data. We'll plot the data with candlesticks, trade volumes and moving averages. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.By the end of this tutorial, a reader will be able to:
1. Setup the Binance API for Data Analysis.
2. Pull OHLCV, Depth and Ticker data from Binance using Python
3. Perform Exploratory Data Analysis with Binance Data
4. Visualise Candlesticks/trade volumes/moving averages using MPLFinance library

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [Python-Binance API](https://python-binance.readthedocs.io/en/latest/)
- [Mplfinance](https://github.com/matplotlib/mplfinance)

**Comment by lalith1403** [comment]
![EB7D0CAC-34E1-47EA-91E9-00BF74211344](https://user-images.githubusercontent.com/26842636/137004863-481bba42-2ca3-4efb-aa26-f42a0f603e76.png)
We discourage plagiarism of any kind. Please submit original ideas.
