### ISSUE TITLE
How to use Web Share API

### ISSUE THREAD

**Issue by giridhar7632** [section-engineering-education/engineering-education#4304]
Title: How to use Web Share API?

Outline

Many modern developers are unaware of the web share API. Using the Web Share API, you can make your content shareable. It enables us to use native share dialog of a device directly from a website or web application. This API can also be used to share files. In this tutorial, you'll learn what is Web Share API and how to use it with some examples.

Key takeaways:

By the end of this tutorial:
- One can discover about web share API.
- One can add share button to their application and make their content sharable
- One can understand how to enable sharing the elements of their web page.

**Comment by WanjaMIKE** [comment]
How does this article differ from official documentation such as https://www.w3.org/TR/web-share/?

**Comment by giridhar7632** [comment]
The official docs contain all the information about the API, like it defines all the properties and methods. In this tutorial, I'm gonna write the required information about the Web Share API along with using them for building a demo application. This is gonna be a project based tutorial rather than a simple reference for adding Social Share functionality for real-world applications.
