### ISSUE TITLE
Creating an XML File from Java Swing GUI

### ISSUE THREAD

**Issue by JosephAyoma** [section-engineering-education/engineering-education#4305]
#### Proposed title of the article
Creating an XML File from Java Swing GUI

#### Proposed article introduction
 Java Swing is suitable for desktop application development. Desktop applications should provide an interface where the user can enter data. Through interaction with the desktop application components, the information entered from the GUI can be used to create an XLM file that can be accessed by the same application.   
In this article, learners will get to learn how the Java Swing desktop applications can be used to create an XLM file and access the same file. I will create a simple application that will be able to demonstrate how to get the components of the GUI and create an XLM file.   At the end of the article, the learner will be able to design a simple Java Swing application that will create, read and update the XML file. I.e. I will use a simple swing going for connecting to MySQL DB, whereby from the user interface connection strings will be provided by the user, collect this information and use them to create the file and later access the file to get the connection strings and connect to the database.

#### Key takeaways 
1.	Creating XML file using Java Swing application
2.	 Reading XML file from java GUI
3.	Updating XML file from Java swing GUI
 
#### References
 https://www.javatpoint.com/java-swing

**Comment by WanjaMIKE** [comment]
@JosephAyoma How will you create the XML file. Will you the scenebuilder?

**Comment by WanjaMIKE** [comment]
Most modern apps now days use JavaFX. Swing is slowly becoming outdated. The tutorial will be more helpful when it focuses on JavaFX. Please suggest a more updated topic to add more value to the community. Thanks
