### ISSUE TITLE
Building, Testing and  Deploying of Student Profile App with PostgreSQL and Django Framework 

### ISSUE THREAD

**Issue by harafah97** [section-engineering-education/engineering-education#4308]
### introduction

This tutorial aims to deliver and walk readers through the stages of developing a mini backend website. The project shall be a students profile app connected to a relational database in Django. Nonetheless, the app will be deployed by explicitly break down the deployment process for the framework having passed the unit tests.

### Key Takeaway
In this tutorial, I will be covering all areas of development, testing and deployment in Django and the following shall be covered;
1. Initialization and configuration of models, views and urls,
2. A walking through with POSTGRESQL database and its connection with Django,
3. Unit testing of the written code,
4. Deployment processes.

### Reference
N/A

**Comment by WanjaMIKE** [comment]
Most of your key takeaways are already covered in this article https://github.com/section-engineering-education/engineering-education/pull/1026/files. There are also numerous already published articles that focus on Django including aspects such as views and models. Feel free to suggest another topic. Thanks
