### ISSUE TITLE
[Microservices] Using Nest.js to build a simple microservice architecture

### ISSUE THREAD

**Issue by ephnjor2021** [section-engineering-education/engineering-education#4311]
#### Proposed title of article
Using Nest.js to build a simple microservice architecture

#### Proposed article introduction
Building huge applications in JavaScript requires dynamic programming, especially when the application grows uncontrollably. New features and updates are released each day and may require the developer to fix the bugs to maintain the code.

To achieve this, new developers are needed to be added to the project, which even makes tasks complex. The structure of modules and packages cannot downsize to simplify the application.

To run the application smoothly, it is important to break down a large homogenous structure into small independent pieces of programs. Such complexities are easily solved when JavaScript applications are built on microservices. In this article, we will build a simple microservice architecture using Next.js.

#### Key takeaways 
At the end of the article, the reader will be able to:
- understand the benefits of using the Nest.js framework in microservices
- create different microservices that interact with each other
- use Backend For Frontend (BFF) service to merge data from different microservices and return it back to the client

#### References
https://docs.nestjs.com/microservices/basics

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appears to be covered here https://www.section.io/engineering-education/building-nest-js-application-using-redis/ Feel free to suggest another topic. Thanks
