### ISSUE TITLE
[Artificial Intelligence] Reactive Machine for Artificial Intelligence

### ISSUE THREAD

**Issue by kwennB** [section-engineering-education/engineering-education#4313]
#### Proposed title of the article

Reactive Machine for Artificial Intelligence

#### Proposed article introduction

Reactive Machines: They perceive and react to the information stored in them. They respond to the same situations in exact and precise forms, all the time. They are no disparity; they do not conceive nor perceive the future. They also do not work with past information. 
An easy-to-remember example of reactive AI is; the spam filter (in mails). Also, Netflix recommendations. 

#### Key Takeaways

· What Reactive Machines AI is and what they do.
· Real-life examples of Reactive Machine
. Explanation of Artificial Intelligence
· Types of AI systems
· The usefulness of Reactive Machines in the world. 

#### Article Quality

This article will cover more on the role of AI in our daily life. Also, write on where to find them if you are not already familiar with them. It will always highlight and explain related terms to Artificial Intelligence.

In this article, I want to discuss the core basics of Artificial Intelligence that is reactive AI. I will discuss its usefulness in our world now and how well it has made decisions easier for humans. 

Thus, pointing to readers that AI is not doomsday coming to wipe out the human race. It is a brilliant advancement and addition to our world that we should embrace. I will discuss the types of Artificial intelligence based on functionality. While also sharing my thoughts on the said type of Artificial Intelligence.

#### References
Nil

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Please fill in the topic suggestion form that I've readded to your issue so we can adaquately review your topic suggestion.

**Comment by kwennB** [comment]
@louisefindlay23  I have edited it.

**Comment by louisefindlay23** [comment]
@kwennB, you don't seem to have filled in the article quality section?

**Comment by kwennB** [comment]
@louisefindlay23I I will see to it now.

**Comment by collins-a** [comment]
Hi @kwennB, interesting topic of choice. This is definitely an article I'd love to read.

However:

1. Consider editing your topic submission to remove the template that Section provides such that only your submission under each heading remains.

2. In the _article quality_ section, you have outlined your approach to the article as more of a "why", but not the "how" that makes your angle unique; compared to other content that for instance, talks about the types of AI, or how AI (or a subset of AI) eases or threatens our everyday lives.

Make these adjustments then ping us to complete the review.

**Comment by kwennB** [comment]
@collins-a Thank you. I have made the adjustments.

**Comment by collins-a** [comment]
@kwennB unless covering an angle that hasn't been taken by an author on Section, perhaps replace the _explanation of AI_ and _types of AI sections_ with an in-depth technical section on _how reactive machines work_.

Now that's an article I'd love to read.

**Comment by kwennB** [comment]
Alright @collins-a 
I will update the issue and ping you when it's done.

**Comment by WanjaMIKE** [comment]
Per the above chats, this issue appears to be saturated. We focus more on unique projects. Feel free to suggest another issue. Thanks
