### ISSUE TITLE
Inheritance and polymorphism in  C++ 

### ISSUE THREAD

**Issue by elphazesedah** [section-engineering-education/engineering-education#4316]
#### Proposed article introduction
Inheritance is the procedure in which one class uses the attributes and methods of another class. The class whose attributes and methods are being used is known as the Parent class. And the class that uses the properties of the parent class is the Child class.

Polymorphism is the method in an object-oriented programming language that performs different things as per the object's class, which calls it. With Polymorphism, a  message is sent to multiple class objects, and every object responds appropriately according to the properties of the class.

The above concepts are core in C++ programming and are used to achieve different objectives. In this article ill be discussing in detail what inheritance and polymorphism are and how they are implemented in object oriented programming. I’ll the go ahead and discuss the different forms of inheritance and polymorphism used in C++ . Finally I’ll discuss the goal of inheritance and polymorphism in C++ programming.
#### Key takeaways 
1. The reader should be able to clearly understand and comprehend what polymorphism and inheritance are  a in C++ program.
2. The reader will be able to adequately and correctly  implement inheritance and polymorphism in their C++ programs.
3. The reader should understand the different forms/types of inheritance and polymorphism and also be clear on when to use what type/form .
4. The reader should be able to definitively  understand the role of inheritance and polymorphism in C++ programming. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
I am closing due to the feedback here -> https://github.com/section-engineering-education/engineering-education/issues/4114

These topic suggestions are the same.
