### ISSUE TITLE
To demonstrate Gmail email inbox using PHP with IMAP

### ISSUE THREAD

**Issue by Edylene-Nyairaw** [section-engineering-education/engineering-education#4317]
#### Proposed title of article
To demonstrate Gmail email inbox using PHP with IMAP
#### Proposed article introduction
Gmail is the premier email service, and nothing can compare to it. Unlimited storage and an excellent user interface are what made it so popular. We'd like it if we could design our own Gmail user interface instead of having to use the standard one.

In this post, I'll show you how to create an inbox in PHP using Gmail's email as a source. This code may be improved and turned into a full-featured email web client powered by PHP.
The protocols IMAP and POP may be used to connect to a mail server and view messages. The mail server messages data will be utilized for a variety of reasons, including displaying emails in a mailbox and sending out notifications when new messages arrive.

The Gmail server is contacted to get email data using the PHP IMAP extension. Access requests including credentials such as host, username, and password are used to establish a connection.
#### Key takeaways 
- How to enable IMAP in PHP
- Working with IMAP Configuration in PHP Environment and Gmail.
- Use of PHP Code to List Emails from Gmail.
- Use of PHP Gmail Email Inbox Output
- Connect Email Servers with PHP imap_open
#### References
N/A

**Comment by Kayere** [comment]
How is your article going to differ from [this one](https://phppot.com/php/gmail-email-inbox-using-php-with-imap/).

**Comment by Edylene-Nyairaw** [comment]
Hello, @Kayere to make my article unique,  I will present the content by providing PHP code for creating an inbox with the emails from Gmail, then enhance the code further and make a complete email web client using PHP also I will show how to read mailbox with file attachments using PHP Imap class.
Thank you
