### ISSUE TITLE
Building UI with ReactJs, Redux and SASS Language

### ISSUE THREAD

**Issue by harafah97** [section-engineering-education/engineering-education#4320]
### Introduction 
Sass is a stylesheet language that’s compiled to CSS. It allows you to use variables, nested rules, mixins, functions, and more, all with a fully CSS-compatible syntax. Sass helps keep large stylesheets well-organized and makes it easy to share design within and across projects.

### Key Take away
Here , I will demonstrating the core concepts to get started with Sass. The following shall be the point of discussion:

1. Meaning and why Sass exists,
2. How to integrate Sass in application,
2. Preprocessing in Sass, 
3. Partials and Mixins,
4. Concept of inheritance,
5. Lastly, Integrating Sass with ReactJs and Redux.
### Reference
https://sass-lang.com/documentation

**Comment by Kayere** [comment]
Hello @harafah97, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.

**Comment by harafah97** [comment]
@Kayere sir please.
