### ISSUE TITLE
Using Twilio To send SMS In Flutter Apps

### ISSUE THREAD

**Issue by gideonkaruga** [section-engineering-education/engineering-education#4321]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposal Submission

####Using Twilio To send SMS In Flutter Apps
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Flutter is an open source mobile UI framework to build native apps for iOS and Android from a single codebase. It is very powerful if we compare it with react-native or any other  cross platform frameworks. One of the main point of flutter app development  is,  it uses widgets instead views to build the UI. So, the main advantage of flutter is that we can use all widgets like Image,Textbox,Button etc., which are available in Android and iOS platform. Now let's discuss how to send SMS using this Cross Platform Framework

Flutter doesn't provide any built-in library for sending SMS instead it provides an API for making HTTP requests to get the job done. So, we have to depend on third party library for sending SMS from our app. There are many third party libraries available for this purpose .In this article I am going to use a third party plugin called Flutter Sms Messaging Plugin  developed by Rohan Taneja.

This plugin provides a very easy API to send SMS. It is very light weight library with less than 100 lines of code. Using this plugin we can send  SMS to single number or group of numbers at once .

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
- What is Twilio?
- Application of Twillio in flutter.
- How to Implement Twilio in flutter application
- Build a simple application to illustrate Twillio.

#### Article quality
To better understand this article , let's consider a scenario where one of your friends request the information about the nearest gas station that has a working back pump. You wish to build an app that can send you the address of the gas station with a working back pump based on your location through SMS using programmatic printing from Twilio. It's quite simple isn't it? Let's get started!
In this article, we will see how Flutter works with Twilio SMS Cloud Service to send and receive messages programmatically.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @gideonkaruga, please provide more info in your suggestion, also be sure to fill the article quality section.

**Comment by gideonkaruga** [comment]
Updated @Kayere

**Comment by Kayere** [comment]
Approved @gideonkaruga
