### ISSUE TITLE
[Languages] Getting Started with JOIN in MySQL Database

### ISSUE THREAD

**Issue by LeahKui** [section-engineering-education/engineering-education#4323]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
Getting Started with JOIN in MySQL Database

#### Proposed article introduction
Join is a tool to connect multiple tables. This is an important concept in any database.
In this tutorial, we will learn how and where we can use JOIN to get the MySQL database's desired output.
We will also use a sample database for demonstration purposes.

#### Key takeaways 
1. What is JOIN in SQL?
2. What JOIN does in MySQL Database
3. How to Join Three or more tables in MYSQL?
4. Compound Join

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
https://www.w3schools.com/sql/sql_join.asp
https://dev.mysql.com/doc/refman/8.0/en/join.html

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Unfortunately, the following articles have already covered JOIN adequately. Feel free to suggest another topic. Thanks

https://www.section.io/engineering-education/mysql-query-optimization-using-indexes-with-examples/

https://www.section.io/engineering-education/mysql-query-performance-optimization-tips/
