### ISSUE TITLE
[Machine Learning] AutoML with TPOT

### ISSUE THREAD

**Issue by francis966** [section-engineering-education/engineering-education#4334]
#### Proposed title of article
[Machine Learning] AutoML with TPOT

#### Proposed article introduction
Automated machine learning (AutoML) is the process of automating the tasks of applying machine learning to real-world problems. AutoML covers the complete pipeline from the raw dataset to the deployable machine learning model. A pipeline is a way to codify and automate the workflow it takes to produce a machine learning model. Machine learning pipelines consist of multiple sequential steps that do everything from data extraction and preprocessing to model training and deployment.

It automates the process of applying machine learning end-to-end additionally offers the advantages of producing simpler solutions, faster creation of those solutions, and models that often outperform hand-designed models furthermore, automated Machine Learning provides methods and processes to make Machine Learning available for non-Machine Learning experts, to improve the efficiency of Machine Learning, and accelerate research on Machine Learning. It does this by automating the selection, composition, and parameterization of machine learning models.

In this tutorial, we shall use the Tree-based Pipeline Optimization Tool (TPOT). TPOT as the AutoML library.  TPOT is a python library that uses genetic programming behind the scenes to generate an optimized ML pipeline. It's an unbeatable asset and is a real bargain if you want to get a classification accuracy that is very competitive.

It uses the concept of natural selection, survival of the fittest, and mutation to find the best machine learning model and the required parameters to produce the best result.
TPOT will enable us to automate some of the stages of the ML life cycle such as feature engineering, model building.
TPOT utilizes these 3 concepts:

1. Selection: selecting the best
2. Crossover: crossbreed the selected best over and over to get the best of the best
3. Mutation: mutate the best to become even better.

#### Key takeaways 
1. What is Automl.
2. Discuss various packages for AutoML.(Before now focusing on  TPOT)
3. Data Preparation.
3. Installing TPOT.
4. Using three concepts of TPOT in building our model, Selection, crossover, and mutation.
5. Implementing machine learning pipelines to automate feature engineering and model building.

#### Article quality
This tutorial is unique since it uses two approaches in building the machine learning model. First, we build a model following the long process of machine learning. We follow all the stages from the dataset preparation to model building and testing so that a user can easily follow.
The second approach we now use TPOT to build our model. TPOT will be used to automate all the processes and make our work easier.

We now compare the two approaches so that we can see the real benefit of AUTOML. By the end of the tutorial, one should easily know how to use both approaches to build the model. This is a practical guide that can be followed easily.

In this tutorial, we shall also briefly discuss the other AutoML packages before focusing on TPOT.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
This topic returns an 80% plagiarism score which indicates its already saturated. Feel free to suggest another topic. Thanks

![pp](https://user-images.githubusercontent.com/38399942/137307354-fb862689-00ef-4929-a491-07b617c22622.png)
