### ISSUE TITLE
[Artificial Intelligence] Understanding Intelligent Document Processing

### ISSUE THREAD

**Issue by martha-ngugi** [section-engineering-education/engineering-education#4341]
#### Proposed title of article
Understanding Intelligent Document Processing

#### Proposed article introduction
Intelligent document processing augments human understanding of unstructured data through the use of data science tools. It is becoming popular nowadays since it provides disruptive solutions to automate data extraction that were previously complex to solve.
The enterprise data keeps growing each day and most of that data is unstructured. The high volumes of unstructured data present a problem and handling such data can be difficult for the human workforce. However, enterprises can make use of this data and draw real business value out of it without overburdening the employees. Intelligent document processing might be the answer to the problem.

#### Key takeaways 
At the end of the article the reader/learner will be able to understand:
- the concept of intelligent document processing
- the document processing stages and how it works
- the technologies used in intelligent document processing
- the industries utilizing intelligent document processing
- the possible reasons and challenges of adopting the intelligent document processing

#### References
N/A

**Comment by martha-ngugi** [comment]
> Can you elaborate on the techniques you will be covering?

@lalith1403 Am glad you got back to me. I will cover the below technologies used in intelligent document processing:
- Optical Character Recognition (OCR)
- Machine Learning algorithms such as computer vision and Natural Language Processing (NLP)
- Robotic Process Automation (RPA)
- Artificial Intelligence

Looking forward to topic approval.
Thank you. cc @WanjaMIKE

**Comment by martha-ngugi** [comment]
@lalith1403 The issue has taken a long time before getting the feedback. Kindly advice. 
Thank you 
cc @WanjaMIKE

**Comment by lalith1403** [comment]
I am sorry about the delay. It would be better if you could cover this practically. A theoretical explanation of document processing may seem redundant in the context of the web, where this has been covered widely.

**Comment by lalith1403** [comment]
Closing issue to make room for active issues.
