### ISSUE TITLE
Data Encryption

### ISSUE THREAD

**Issue by Koros-Meshack** [section-engineering-education/engineering-education#4344]
### Introduction
Data Encryption is the process of converting or scrambling plain text into ciphertext so it cannot be easily decoded or interpreted by unauthorized parties. Symmetric and Assymetric are the types of data encryption and we are going to look in-depth at how they differ and how they relate to data encryption.
they relate to data encryption.
We will also look at `Data Encryption Standards` which symmetric-key algorithm for the encryption of digital data. By the end, you will also have understood the types of encryption standards which include: DES, RSA, and AES.
Furthermore, we will learn how you can know your encryption type and use this to choose more secure encryption types in your WIFI, mobile device, etc.
The article will use flowcharts to get to explain the relations of different entities and how they work.

### Reference
N/A

**Comment by WanjaMIKE** [comment]
It seems we have many articles covering this topic -> https://github.com/section-engineering-education/engineering-education/issues?q=Data+Encryption Feel free to suggest a new topic. Thanks
