### ISSUE TITLE
[Machine Learning] Text Preprocessing in Natural Language Processing (NLP) with python

### ISSUE THREAD

**Issue by felixMuia** [section-engineering-education/engineering-education#4346]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Text Preprocessing in Natural Language Processing (NLP) with python
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Text preprocessing is a technique for cleaning text data and preparing it to feed data to the NLP model. Text data contains various kinds of noise, such, emotions, punctuation, text in a different cases. Also, it's common for the same sentence of Human Language to have different meanings depending on the context in which it's used. Humans can exactly understand the intention in those statements, but for machines to understand, it's not an easy thing. To enhance our machine understanding in such a challenging situation, we need to present our text data to be converted to numbers efficiently, i.e. a text dataset free from noise.

In the text data preprocessing, we have the following stage:

- Tokenization
- Lower casing
- Stop words removal
- Stemming
- Lemmatization
- Emoticons removal
- Emoticons conversion

Using a text data sample, in this article, we shall walk through each of the above steps and learn how we can get rid of all noises from our data so that it's suitable to implement reliable NLP models.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
- Learner know all techniques involved in text data preprocessing.
- Learner will step by step know how to carry out text preprocessing in python.
- Learner will be able to apply this knowledge to future text data cleaning tasks.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
It seems this topic is over covered. Articles on sentiment analysis have explained how to clean text and use it for analysis. https://www.section.io/engineering-education/search/?q=text%20processing

A perfect example is https://www.section.io/engineering-education/sentiment-analysis-with-spacy-and-scikit-learn/ Feel free to suggest a new topic. Thanks
