### ISSUE TITLE
Designing a Java Program to Read a Large Text File Line by Line and into ArrayList

### ISSUE THREAD

**Issue by NdoloBonface** [section-engineering-education/engineering-education#4355]
### Topic Suggestion
Designing a Java Program to Reads a Large Text File Line by Line and into ArrayList

### Proposed article introduction
This article explains how to efficiently read a huge text file line by line in Java.

In Java, there are various techniques for reading a text file. This tutorial, on the other hand, is focused on reading large text files, and we will go over the three most efficient methods for reading large text files quickly. We will be creating a program that does so with ease.
We use the utility method `Files.readAllLines()` to read all lines of a text file into a List. This method returns a List of String that contains all lines of files. Later you can convert this List to ArrayList, LinkedList, or whatever list you want to.
### Key takeaways
We will discuss deeply on BufferedReader class method
We will also discuss on Scanner class method
The reader shall understand which method is efficient and why.
### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Focusing on BufferedReader and the Scanner class cannot make a detailed tutorial. There are numerous articles that have already covered these two concepts. Feel free to suggest another topic. Thanks
