### ISSUE TITLE
 Matching Lambdas to Interfaces and Working with Lambda Expressions in Java

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#4361]
#### Proposed title of article
Matching Lambdas to Interfaces and Working with Lambda Expressions in Java

#### Proposed article introduction
The core technique to functional programming in Java is to match Lambdas to Interfaces in Lambda expressions. It is an anonymous function that does not have a name and does not belong to any class. This is a large topic that has already been explored. And you must have some understanding of what we're talking about before you can understand what we're saying.

We will discuss all ideas before deciding how to match lambda expressions with interfaces in this tutorial.

#### Key takeaways 
- Functional Interface
- Anonymous classes
- Lambda expression with zero parameter

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Lambdas in Java are adequately covered here -> https://github.com/section-engineering-education/engineering-education/issues?q=Lambda Feel free to suggest another topic. Thanks
