### ISSUE TITLE
How to exchange XML-based messages over computer networks using SOAP(Simple Object Access Protocol)

### ISSUE THREAD

**Issue by mulwasteveh** [section-engineering-education/engineering-education#4362]
#### Proposed title of article
How to exchange XML-based messages over computer networks using SOAP(Simple Object Access Protocol)

#### Proposed article introduction [Languages-JAVA]
SOAP (formerly an acronym for Simple Object Access Protocol) is a messaging protocol specification for exchanging structured information in the implementation of web services in computer networks. It uses XML Information Set for its message format, and relies on application layer protocols, most often Hypertext Transfer Protocol (HTTP), although some legacy systems communicate over Simple Mail Transfer Protocol (SMTP), for message negotiation and transmission.

SOAP allows developers to invoke processes running on disparate operating systems (such as Windows, macOS, and Linux) to authenticate, authorize, and communicate using Extensible Markup Language (XML). Since Web protocols like HTTP are installed and running on all operating systems, SOAP allows clients to invoke web services and receive responses independent of language and platforms.
This article will be explaining and showing how to go about to exchange xml based messages using SOAP api over different computer network. It will be simple and easy for a newbie to catch up and get to know what it entails and cheap like a mint. 
#### Key takeaways 
- What is SOAP?
- what is xml and the code?
- soap xml
- configuring the protocol to send messages.

#### Article quality
this article will be a good grasp for learners on how SOAP xml works which has not been covered in any platform before.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

**Comment by WanjaMIKE** [comment]
Based on the attached plagiarism score, this topic seems to be heavily saturated. Feel free to suggest another topic. Thanks
![pap](https://user-images.githubusercontent.com/38399942/137445293-2ae3224c-4c50-491a-89e3-2f6692d43d8b.png)
