### ISSUE TITLE
(Machine Learning)Machine Learning Regression Evaluation Metrics

### ISSUE THREAD

**Issue by FINCH285** [section-engineering-education/engineering-education#4365]
#### Proposed title of article
Machine learning regression evaluation metrics

#### Proposed article introduction
We can determine the performance of a regression model  by  the error rate of the predictions the model makes. We can also measure the performance by knowing how well the regression line fit the dataset. Choosing a proper metric is crucial while evaluating regression models.

 In this article we are going to discuss the regression evaluation metrics. we are also going to discuss the advantages and disadvantages of each one of them. Finally we will discuss what a good regression model is.

#### Key takeaways 

- Regression evaluation metrics.
- Advantages and disadvantages of each discussed metric.
- Understand what a good regression model is.

#### Article quality
The available articles explain these metrics in a shallow way. Some discuss only the popular metrics. This article will be more in-depth and will be covering all the metrics.

#### References
N/A

**Comment by lalith1403** [comment]
Can you list the metrics?
