### ISSUE TITLE
multivariate data processing and correlation analysis in Advanced Machine Learning

### ISSUE THREAD

**Issue by Simoh8** [section-engineering-education/engineering-education#4368]
#### Proposed title of article
**multivariate data processing and correlation analysis in Advanced Machine Learning**

#### Proposed article introduction
Multivariate analysis deals with the statistical analysis of data collected on more than one dependent variable. Multivariate techniques are popular because they help organizations to turn data into knowledge and thereby improve their decision making. 
The data are presumed to be a set of multivariate observations collected by sampling a population or observing a process. An example of a process is the stream of price quotations generated by trading activity on the NASDAQ stock exchange

#### Key takeaways 
- What is multi-variance?
- what is correlation analysis?
- Behavioral Risk Factor Surveillance System
- Notations and Terminologies
- Using python libraries to do the correlation analysis

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @Simoh8

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by Simoh8** [comment]
hello @lalith1403  can i push this article?
