### ISSUE TITLE
[JAVA] Hello Earthrise program: First JavaFX Program Development.

### ISSUE THREAD

**Issue by mprotus** [section-engineering-education/engineering-education#4369]
#### Proposed title of article
[JAVA] Hello Earthrise program: First JavaFX Program Development.

#### Proposed article introduction
The javafx.animation package contains convenience classes for animating nodes. This Translate Transition instance (created by the Translate Transition Builder class) translates the Text node referenced by the textRef variable from its original Y position of 100 pixels to a Y position of -820 pixels, over a duration of 75 seconds. The Interpolator.LINEAR constant is assigned to the interpolator property, which causes the animation to proceed in a linear fashion. A look at the API docs for the Interpolator class in the javafx.animation package reveals that there are other forms of interpolation available, one of which is EASE_OUT, which slows down the animation toward the end of the specified duration.
This article will be showing how to run a Earthrise Program from the command-Line in a simple way. It will still give a simpler way in which one can compile a JavaFX program using the NetBeans IDE.

#### Key takeaways 
- Running the Program from the Command-Line.
- Apprehension of the Hello Earthrise Program.
- Running and compiling the program with NetBeans.

#### References
N/A

**Comment by WanjaMIKE** [comment]
How will this article differ from official documentation? Note that running the program in NetBeans is not a key takeaway

**Comment by mprotus** [comment]
Hello, I intend to make the article simple and easy to understand for beginners. Most of the articles presented cover the exact what is Earthrise program but do not show how it is developed . My aim, I will be glad to make it more than mint to everyone who comes across it and hence comprehensible. Thank you
