### ISSUE TITLE
Building Chat Application Using Django Channels

### ISSUE THREAD

**Issue by damikanye** [section-engineering-education/engineering-education#4370]
### Introduction

In this article,  we will be developing from scratch a simple chat application by implementing the chat server using Django Channels.  Channels wraps Django’s native asynchronous view support, allowing Django projects to handle not only HTTP but protocols that require long-running connections too like WebSockets, chatbots, and more.

### Keys Take away
1. Introduction to Channels and its concepts
2. Setting up Django project
3.  Configuration of the chat server 
4. Testing the chat app using different browsers.

### Reference
https://channels.readthedocs.io/en/latest/introduction.html

**Comment by WanjaMIKE** [comment]
@damikanye How will this topic differ from official documentation?
