### ISSUE TITLE
[Machine Learning] Effects of Feature scaling on a machine learning model

### ISSUE THREAD

**Issue by Sajeyks** [section-engineering-education/engineering-education#4378]
### Topic Suggestion
Machine Learning
#### Proposed title of article
Effects of Standard scaling on a machine learning model 

#### Proposed article introduction
Datasets that are used for training models in machine learning have unpredictable values that might end up varying from each other in a broad scale. Nimerical values might have big differences amongst themselves while other non numerical values might not be helpful while working with in their original format ie: booleans and gender.

Standard scaling is introduced inorder to solve this challenge. It standardizes the numbers in a manner that makes it easy to compare the values that are out of each others scope and some of those that are not numerical. In this approach, we will first build a prediction model that is not standardised then build one that is standardised and compare the results to note the advantage of implementing standardisation. 

#### Key takeaways 
1. What is Standard scaling
2. How to implement standard scaling
3. Advantages of standard scaling

#### Article quality
I will be approaching the effect of Standard Scaling in a more practical manner by actually creating two models for comparison using their results and I will also be looking at hyperparameter tuning in addition.

#### References
N/A

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @Sajeyks

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by Sajeyks** [comment]
Could you please reopen the topic for me? I want to PR today.
