### ISSUE TITLE
Implementing a Generic, singly Linked List data structure in Java

### ISSUE THREAD

**Issue by LynnMumo** [section-engineering-education/engineering-education#4382]
#### Proposed title of article
Implementing a Generic, singly Linked List data structure in Java
#### Proposed article introduction
Linear Data Structures that store values in nodes are known as Linked Lists. As we know, each Node has two properties: the value of the node and, if present, a connection to the next node. Linked Lists can be of any data type, including String, Boolean, Float, Character, and so on. 
We will be creating a generic Linked List Data Type that can store data of any type.

#### Key takeaways 
- Primary member functions of a linked list
- Creating a generic linked list
- What is a generic linked list and how we implement them

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Sounds like a good topic @LynnMumo, please make sure your article is unique and adds to what is available in official documentations and other sources.
