### ISSUE TITLE
 MySQL Connection Graphical User Interface design Using JavaFX and Scene builder

### ISSUE THREAD

**Issue by JosephAyoma** [section-engineering-education/engineering-education#4384]
#### Proposed title of the article
  MySQL Connection Graphical User Interface design Using JavaFX and Scene builder

#### Proposed article introduction
JavaFX is suitable for desktop application development and other applications. Desktop applications should provide an interface where the user can enter data. Through interaction with the desktop application user interface, the data can be saved in a database (MySQL) for processing or any other manipulation .i.e. future retrieval.   
In this article, we will get to learn how JavaFX through scene builder can be used to design a desktop application that can connect to the MySQL database. 
I will demonstrate how to create and design a simple graphical user interface using scene builder and JavaFX where the user can input database connection string, save the connection string in an XML file, retrieve them from the file and connect to the database

#### Key takeaways 
1.	Getting started with JavaFX using Netbeans
2.	 Getting started with scene builder
3.	Intergrading scene builder with Netbeans

#### Article quality
In this article I will be able to demonstrate using a code (FXML and JavaFX) snippet how JavaFX through scene builder can be user to design a user interface which connects to the MySQL database directly. In most of the articles in the internet, concept of connecting Java to MySQL has  no provision  for doing this through graphical user interface. I will therefore bridge this gap through using scene build to design a GUI, bind the resulting FXML file to the application  which from the GUI will provide a means of connecting to the database in any application without going deep to changing the code i.e.  the connection is controlled at the UI level.

#### Reference
https://www.oracle.com/java/technologies/javase/javafxscenebuilder-info.html

**Comment by Kayere** [comment]
Approved @JosephAyoma
