### ISSUE TITLE
How to Use Command Line Tools to Find and Remove Duplicate Files on Linux by Name

### ISSUE THREAD

**Issue by jgesare** [section-engineering-education/engineering-education#4386]
#### Proposed title of article
How to Use Command Line Tools to Find and Remove Duplicate Files on Linux by Name

#### Proposed article introduction
Most of us have a propensity of downloading various sorts of content from the internet, which is why we may frequently discover that we have downloaded the same files and other extensions. Duplicate files waste disk space unnecessarily, and if you want the same files in different locations, you can always set up a soft link or hard link that doesn't use the space unnecessarily and stores the data in only one area on your drive. This will consume unnecessary system space, and manually discovering this duplicate file is a difficult task.
There are some decent tools in Linux for locating duplicate files and eliminating them to free up system space, whether you're using Linux on your desktop or on a server. In this article, we'll take a close look at these tools.

#### Key takeaways 
- Using `FSlint`
- Using `Fdupe`
- Using `Rdfind`

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Thank you for the topic suggestion @jgesare.

However, this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternate topic to explore.
