### ISSUE TITLE
[Languages] Fruit mania game in javaScript : javascript for game Development

### ISSUE THREAD

**Issue by EssyG10** [section-engineering-education/engineering-education#4387]
#### Proposed title of the article
[Languages] Fruit mania game in javaScript : JavaScript for game Development
#### Proposed article introduction
It is my intention to create a fruit madness game entirely in JavaScript, HTML, and CSS throughout this tutorial. It will be a one-of-a-kind demonstration of how to drag and drop components in Javascript, making it really unique. The fact is that this is one of the most often used components in many javaScript applications. In addition to this, we will learn about and practice the built-in javaScript methods that will be useful in achieving the desired result for our project.

#### Key takeaways 
**By the end of this instructional exercise learners will get the following** 
  - Attaching EventListeners to elements using `addEventListener()` method.
  - using `setAttribute()` method.
  - Timers with `setInterval()` method
  - Node navigation: `createElement()`,`appendChild`.
  - Fruit maina game
#### Article quality
Creating a basic game in Javascript is the goal of this essay, which is designed to educate learners of more of what they already know about Javascript and assist them in honing their abilities. The description of the code will be precise in order to increase the understandability of learners in the community.
#### References
N/A

**Comment by Kayere** [comment]
Hello @EssyG10, there seem to be several articles online that demonstrate the same. How is this one going to be any different?

**Comment by EssyG10** [comment]
@kayere, my intention is only to demonstrate to learners how they can utilize javascript for game development. Furthermore, the suggestions online are totally different from this one
