### ISSUE TITLE
variables in JavaScript

### ISSUE THREAD

**Issue by tetie** [section-engineering-education/engineering-education#4391]
variables are memory locations that keep on changing. Variable often change depending on conditions or information passed since programs contain a set of instructions that command the computer on what to do and which data to be used in the running of the program. In this article, we will introduce variables and discuss using various examples of how variables are used/ implemented in JavaScript.
furthermore, we will give detailed information in each sub-topic under variables as well as providing clarity in each.

**key takeaways**
In this article  the  user will be able to  learn:
1. introduction to variables
2. variable creation & declaring
3. assignment operators
4. JavaScript datatypes
5. JavaScript arithmetic

**reference**
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, variables in JS are already covered in numerous articles. Feel free to choose another topic. Thanks
