### ISSUE TITLE
[Machine learning] Step-by-Step implementation of Support Vector Machine algorithm in R

### ISSUE THREAD

**Issue by felixMuia** [section-engineering-education/engineering-education#4393]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Step by step implementation of Support Vector Machine algorithm in R
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Support vector machine is a supervised machine learning model used for classification and regression analysis. However, it's mostly used in classification problems. This algorithm uses a technique known as the kernel trick to transform the data, and then based on these transformations, it finds an optimal boundary( hyper-plane) between the possible outputs. 

In this article, we will try to deliver a high-level intuition on how SVMs work and later dive into implementing these intuitions in R. However, in the article, we shall not go into the mathematical rigour on SVMs. We shall only focus on the intuition of the working principle that will enable us to implement this model on a dataset.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
- The learner will have a clear understanding of the intuition behind the SVM
- The learner will know how to classify the dataset using the support vector machine in R.
- The learner will be able to implement this model on the future dataset by themselves as they will deeply understand the implementation phase.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
This topic is already suggested here https://github.com/section-engineering-education/engineering-education/issues/4055 Feel free to suggest another topic. Thanks
