### ISSUE TITLE
SQL Joins and their applications

### ISSUE THREAD

**Issue by Ndolo-Boniface** [section-engineering-education/engineering-education#4394]
In SQL join clause is used to link two or more tables. These tables must contain a linked column(s).
Depending on the user's expectations, different joins are used to achieve this. 
These include: 
- cartesian product
- inner join
- left join
- right join
- self join
All these joins specify how an SQL server can use data from a particular table to be able to select rows from a different table or rather joins are used to query and access multiple tales' data depending on their logical relationships.

***Key takeaways**
- Be able to define an SQL join
- Identify and implement different types of joins
- Ability to differentiate the joins and their appropriate application
- Be able o perform SQL queries in any database using joins

***References***
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, the following articles have already covered JOIN adequately. Feel free to suggest another topic. Thanks

https://www.section.io/engineering-education/mysql-query-optimization-using-indexes-with-examples/

https://www.section.io/engineering-education/mysql-query-performance-optimization-tips/
