### ISSUE TITLE
(Python)Creating A Screen Recorder Using Python And Pycharm

### ISSUE THREAD

**Issue by kirurisimon** [section-engineering-education/engineering-education#4402]
#### Proposed title of article
How to create a screen recorder using python

#### Proposed article introduction
Screen recorders come in handy in some tasks, e.g when creating tutorials to enhance training effectiveness. Some of these recorders come in subscriptions that may not be pocket-friendly. Python helps us create our own screen recorder hence saving us on cost.

In this tutorial, we are going to demonstrate how to create a screen recorder that will also be performing webcam recording. We will be using the following python packages:

- Datetime.
- Python image library
- NumPy.
- win32api
- cv2

#### Key takeaways 

1. Creating a screen recorder.
2. Working with the mentioned python packages.
3. Integrating a webcam recorder into the screen recorder.

#### Article quality
Most articles don't integrate the webcam recorder. In this article, we will show the reader how to integrate a webcam recorder into the screen recorder.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @kirurisimon 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
