### ISSUE TITLE
[Machine Learning]  Getting started with Kernel PCA algorithm in python

### ISSUE THREAD

**Issue by felixMuia** [section-engineering-education/engineering-education#4406]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Getting started with Kernel PCA algorithm in python
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Standard PCA is widely used in the tasks of dimensionality reduction but no matter how famous it is, this algorithm can only handle dataset that are only in linear form. Thus standard PCA always finds linear principal components to represent the data in lower dimension. Sometime, we need non-linear principal components. Applying the started PCA on the none-linear data, it fails to find good representative direction. Kernel PCA (KPCA) rectifies this limitation.

Kernel PCA performs PCA in a new space know as kernel space obtained through transformation of the original dataset from low dimensional to high dimensional space. It uses Kernel trick to find principal components in such new space.

In the article, we shall learn how to reduce the dimension of non-linear dataset using Kernel PCA algorithm with the aid of the sklearn library in python.

#### Key takeaways 
- The learner will know what kernel PCA is.
- The learner will have a good understanding of how the Kernel PCA compresses data.
-  The learner will be able to implement the Kernel PCA algorithm in python on the tabular data and solve the problem curse associated with models build on high dimensional dataset. 

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date
