### ISSUE TITLE
[JAVA] How to invoke RESTful web services in JAVA

### ISSUE THREAD

**Issue by mulwasteveh** [section-engineering-education/engineering-education#4409]
### Topic Suggestion
[JAVA] How to invoke RESTful web services in JAVA

#### Proposed article introduction
Java webservices are broadly used of late. At the point when a human collaborates with a website page, HTML is utilized to send and get demands. At the point when you associate with a site page, your program sends a solicitation, which is consequently delivered and shown in HTML. Web administrations use solicitation and reaction similarly, however as XML, JSON, or plain text.
RESTful Web Services are fundamentally REST Architecture based Web Services. In REST Architecture everything is an asset. RESTful web administrations are light weight, profoundly adaptable and viable and are usually used to make APIs for online applications. This instructional exercise will show you the nuts and bolts of RESTful Web Services and contains parts examining every one of the essential parts of RESTful Web Services with appropriate models.

#### Key takeaways 
- An introductory knowledge on Web Services Description Language
- RESTful web service Endpoint interface
- Web service Execution
- RESTful API

#### Article quality
I intend to make the article simple and easy to understand for beginners. I will be giving bit by bit measure from making a few catalogs, creating hits for web administration and how to distantly get to web administrations, which most sites or articles frequently overlook. My main aim, I will be glad to make it more than mint to everyone who comes across it and hence comprehensible.

#### References
N/A

**Comment by Kayere** [comment]
Sounds like a helpful topic @mulwasteveh, please make sure your article is unique and adds value to what is available online.

This is to avoid article closure in the PR section👍.

**Comment by hectorkambow** [comment]
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date
