### ISSUE TITLE
[Languages] Use NumPy to create a vector in Python 

### ISSUE THREAD

**Issue by MichaelmichaelW** [section-engineering-education/engineering-education#4410]
#### Proposed title of article
[Languages] Use NumPy to create a vector in Python 

#### Proposed article introduction
NumPy may be used to conduct a wide range of array-based mathematical operations. It extends Python with sophisticated data structures that ensure fast computations with arrays and matrices, as well as a large library of high-level mathematical functions that work with these arrays and matrices.

In this article, we'll learn how to use the Numpy library to generate a vector. We'll also look at basic vector operations like adding two vectors, subtracting two vectors, dividing two vectors, multiplying two vectors, and performing vector dot product and vector scalar product.

#### Key takeaways 
1. Creating Vector in Python
2. Basic Operation of Python vector
3. Vector Dot Product

#### Article quality
I am looking ahead to come up with original and well based content understandable and meaningful to the readers
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @MichaelmichaelW 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
