### ISSUE TITLE
[Languages] Use GEOPY to Calculate the Distance between Two Points.

### ISSUE THREAD

**Issue by Joshuathuo** [section-engineering-education/engineering-education#4412]
#### Proposed title of article
[Languages] Use GEOPY to Calculate the Distance between Two Points.

#### Proposed article introduction
Geopy is a Python package that aids in the calculation of geographic distance. Using third-party geocoders and other data sources, geopy makes it simple for Python developers to get the coordinates of addresses, cities, countries, and landmarks all around the world.

In this article, we'll go through various ways for calculating the distance between two points on the globe. We shall show how this is possible using the Python library Geopy.

#### Key takeaways 
Here, we shall be looking at various methods or techniques that are used in finding the distance between two pionts as shown below
1. By using the Geodesic Distance method
2. Using the Great Circle Distance method
3. Through implementing the Haversine Formula

#### Article quality
My aim in this article is to produce an original content based purely on the topic in order to come up with reliable and well versed content.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Okay, please make sure you are building a unique project @auxesis 
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
