### ISSUE TITLE
[Machine Learning] Getting started with Polynomial regression in python

### ISSUE THREAD

**Issue by Faith034** [section-engineering-education/engineering-education#4419]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Getting started with polynomial regression in python
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
 Polynomial Regression is a form of linear regression in which the relationship between the study variable x and explanatory variable y is modeled as an nth degree polynomial. This algorithm, it fits a nonlinear relationship between the values of x and the corresponding conditional mean of y, denoted E(y |x). This, model is thus suitable for modeling non-linear relationship between two variables and in such situations linear gression can't fit as the suitable modelling technique.  Polynomial regression is used in the problems such as, salary prediction, pandemic spread prediction, and many others areas of study.

In our article, we shall learn what's the polynomial regression, and precisely walk through the intuition behind this algorithm. We shall then proceed and implement our algorithm using a business datau in python. Finally, we will use our model and predictions using new data points.
#### Key takeaways 
By the end of the article, reader will know:
- What is the polynomial regression
- Situation under which polynomial regression is the suitable model for modelling our data.
- Intuition behind the polynomial regression upon which the we build our algorithm.
- How to implement the polynomial regression model in python.
- How to use and make predictions using the implemented  model  in python.
#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Wasn't this topic suggested by another topic here -> https://github.com/section-engineering-education/engineering-education/issues/4417 ?
