### ISSUE TITLE
How to Make Online Photo Editing Effects like Blur Image, Sepia, Vintage

### ISSUE THREAD

**Issue by Jah100** [section-engineering-education/engineering-education#4422]
#### Proposed title of article
How to Make Online Photo Editing Effects like Blur Image, Sepia, Vintage

#### Proposed article introduction
Graphic elements will become expressive as a result of photo editing effects. You may express an idea with a simple photograph and the right effects.
Image blur, transparency, and shadowing are some of the visual effects that can be used to produce appealing visual effects. There are numerous visual effects to choose from. There are hundreds of them to choose from.
To apply the effects on a target image, online photo editing software use a variety of approaches. A CSS filter property or an SVG filter primitive, for example, can be used to generate an image blur effect.

#### Key takeaways 
1. User interface for applying blur sepia effects to photos online
2. Using a jQuery slider to control image editing effects
3. Blur the image with CSS and SVG.
4. How to create a sepia tone in an image
5. Using a variety of tones and vintage effects
6. Image Blur Sepia and Vintage effects from the editing tool

#### Article quality
This article is not similar to many blogs. I will use the latest version of CSS and HTML to make it more attractive 
#### References
N/A

**Comment by hectorkambow** [comment]
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date
