### ISSUE TITLE
[Android] How to use LolliPin Library to Secure Android Apps

### ISSUE THREAD

**Issue by nonimdiana** [section-engineering-education/engineering-education#4424]
### Proposed title of article

How to use LolliPin Library to Secure Android Apps

### Proposed article introduction

Android app security knowledge is indeed an element that may set devs apart in today's unpredictable online world. Despite the fact that Android delivers a wealth of potential for developers, it is frequently targeted by hostile attackers looking to penetrate software products. When building and deploying your Mobile App, cybercriminals may examine and try to attack it.

You should ensure that you have a thorough understanding of the Android ecosystem, from how to design, develop to deploying your apps. You should, however, have a good experience in security controls, encryption, or android app security in general. 

LolliPin is an Android confidentiality library made with material design guidelines. The above-mentioned hazards and vulns are considerably reduced while using it.

### Key takeaways

By the end of this tutorial, the reader will:

- Understand why and how security is a critical area in Android apps.
- Be able to set up LolliPin library.
- Learn how to secure apps with LolliPin.
- Be able to fix bugs.

### Article quality

With the rising need for secure applications, developers need to be equipped with technical skills to deliver valid solutions. This article will cover exactly that in a simple, beginner friendly approach.

### References

N/A

**Comment by Kayere** [comment]
Sounds like a helpful topic @nonimdiana, please make sure your article is unique and adds value to what is available online.

This is to avoid article closure in the PR section👍.

**Comment by hectorkambow** [comment]
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date
