### ISSUE TITLE
Learn the basic commands in Git using Git Bash

### ISSUE THREAD

**Issue by June-Johnson** [section-engineering-education/engineering-education#4425]
#### Proposed title of article
Learn the basic commands in Git using Git Bash

#### Proposed article introduction
Git is an open-source version control system. It allows multiple developers to collaborate together on a project, assists in supervising files and can also unify modifications at once. This means that three developers can work on separate parts of the same project and merge their changes without overwriting issues.

Git Bash is an emulator used to run Git commands in order to commit changes, merge, switch branches, etc. on a project.

**An emulator allows one distinct system to act like another computer system.**

In this article, I'll show you how to work with all the basic commands like, add, push, commit, status, using Git Bash.

#### Key takeaways 
The reader will know how to install git, and by the end of this article, the reader will be able to run basic commands using git bash.

#### Article quality
This article is unique because it is simple, clear, and straight to the point. It is basically for beginners who are finding it hard to understand git and how it works.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @June-Johnson 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
