### ISSUE TITLE
[Machine Learning] How to build an NLP based emotion detection model using NeatText and Scikit-learn

### ISSUE THREAD

**Issue by francis966** [section-engineering-education/engineering-education#4433]
#### Proposed title of article
[Machine Learning] How to build an NLP based emotion detection model using NeatText and Scikit-learn

#### Proposed article introduction

Natural language processing helps computers to understand and understand speech and written text like a human being. For example, NLP makes it possible for computers to read and analyze text, hear speech, interpret it and measure sentiment.

The newest type of NLP application is emotion text in text. The emotion detection model is a type of model that is used to detect the type of feeling in a given text. It may be a feeling of anger, joy, or happiness.

This emotion detection model can be used by different businesses to know if the customers are satisfied with their products. This helps the businesses to know if they can improve the quality of their product.

In this tutorial, we will use NeatText and Scikit-learn in building our model. NeatText is a Python library that is used to preprocess our dataset. NeatText will be used to clean the text dataset and remove stop words, these makes it easy for the model to use this dataset.

We then use Scikit-learn in building our model, it contains all the algorithms required for classification. This is a practical guide from data preprocessing to model building and testing.

#### Key takeaways 
1. What is mention detection.
2. How to install and use NeatText.
3. Dataset preprocessing.
4. Building the emotion detection model using Scikit-learn.
5. Testing the model.
#### Article quality
We will build the emotion detection model, this is a very crucial type of sentiment analysis. That's why in this tutorial we will start from scratch so that any user can easily follow along. This being a custom model it will be easy to explain key concepts about emotion detection.
This article is also unique because we use NeatTecx, for dataset preprocessing. This ensures we have a clean dataset to be used by the model. This tutorial follows all the stages from data preprocessing to model building and testing.

By the end of the tutorial, the model build can be applied to any business and help to solve real-world problems. This helps businesses to scale and know what adjustments they should make on their products to give them a competitive advantage.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
@lalith1403, should this topic be approved?

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
