### ISSUE TITLE
Python range() Function

### ISSUE THREAD

**Issue by Jairusonkundi** [section-engineering-education/engineering-education#4442]
Proposed title of article
Python range() Function

Proposed article introduction
Range () function is a Python built-in function. It returns a number sequence that starts at zero and increments by one by default, stopping before the provided number.
In this article, we will learn how to utilize the range() function in a variety of ways, including with explicit start and finish indices, custom step sizes, and negative step sizes and explained code examples of each.

Key takeaways
-Overview of Python range() Function 
-How to Loop Through Any Iterable Using Python's range() Function
-How to Use Python's range() Function with Explicit Start and End Indices
-How to Use Python's range() Function with a Custom Step Size
-How to Use Python's range() Function with a Negative Step Size
-How to Use Python's range() and reversed() Functions to Reverse a Sequence
References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic is already covered adequately in already published articles and official documentation. Feel free to suggest another topic. Thanks
