### ISSUE TITLE
Configuring Spring Boot Zuul microservices gateway proxy server

### ISSUE THREAD

**Issue by Nicholasodhiambo962** [section-engineering-education/engineering-education#4451]
#### Proposed article introduction
Zuul Server is a gateway application that handles all the requests and does the dynamic routing of microservice applications. Zuul is built to enable dynamic routing, monitoring, resiliency, and security. It is also known as the Edge server. It handles all the requests and performs the dynamic routing to microservice applications. It works as a front door for all the requests. It is also known as Edge Server.

The article will explain how to set up a Zuul gateway service to handle dynamic routing to different microservices.

#### Key takeaways 
1. Setting Up Zuul API gateway service.
2. Dynamic routing of requests to different services.
3. Microservices health checks and monitoring.

#### Article quality
This article will demonstrate how to build microservices, route the requests to different services using the Zuul gateway service, and finally deploy the microservices to docker-compose. Unfortunately, several articles only demonstrate how to build the services but do not go beyond that to deploy the services. Therefore, at the end of the article, the reader will build and deploy microservices to docker-compose with the Zuul gateway service.

#### References
[Docker](https://docs.docker.com/compose)

**Comment by Nicholasodhiambo962** [comment]
@Kayere I have updated the topic as suggested.

**Comment by ahmadmardeni1** [comment]
How does your article differ from the [official docs](https://spring.io/guides/gs/routing-and-filtering/)? @Nicholasodhiambo962

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
