### ISSUE TITLE
How to use Visual Studio with Azure Boards as part of CI/CD process. 

### ISSUE THREAD

**Issue by peshbiz** [section-engineering-education/engineering-education#4452]
#### Proposed article introduction

Many organizations today are embracing CI/CD process. This has improved the efficiency and speed of shipping software. Azure Devops is one of the tools that organizations are using. 

For beginners in the Agile world, Azure DevOps, Work items might sound a little confusing. This article will explain what they are and their differences.

It shall go ahead and explain how these work items can be moved from azure boards to visual studio or how to create them right from Visual Studio. The articles will also explain how we can perform git operations from visual studio to your azure board to improve the development speed. 

#### Key takeaways 
- The reader will understand what Azure boards is. 
- The reader will get to understand what a work item is.
- Create a login API in c# to help one understand how to create the work items.
- Understand how to integrate Visual Studio with Azure boards. 
- How to Perform different git operations from Visual studio to the Azure board that has the work items. 

#### Article quality

Having had a few challenges initially with this integration,I shall explain a step by step process of achieving this. 

#### References 
N/A

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
