### ISSUE TITLE
Building a Heap using siftUP with Java

### ISSUE THREAD

**Issue by simonmutu** [section-engineering-education/engineering-education#4455]
### Topic Suggestion
 using siftUP  library in java to build heaps

#### Proposed title of article
 [JAVA] BUILDING A HEAP USING siftUP with java

#### Proposed article introduction
Heaps are extensively added in our projects but the problem now emerges when the need to add more heaps arises which requires newKey. Suppose we have a heap which we need to add more heaps like 40 new ones. this is only possible using siftUP  which helps to store and rearrange the data again after storage.  A heap is considered a binary tree with unordered values. Build of heaps in software's helps to check the amortization analysis. This article will be showing step by step on how to build a heap in java using the siftUP library.

#### Key takeaways 

1. What is a newKey?
2. What is siftup?
3. Using the siftUp library?
4. What is a heap?
5. How to use the siftup library to build heaps.

**Comment by louisefindlay23** [comment]
Could you tell us more about the small issue you plan to cover which haven't been in previous articles?

**Comment by WanjaMIKE** [comment]
I don't think this topic adds much value to the community. most of the takeaways are already covered in the official documentation. Feel free to suggest another issue. Thanks
