### ISSUE TITLE
[Languages]How to plot multiple markers on a Leaflet map using Jquery

### ISSUE THREAD

**Issue by muyiwexy** [section-engineering-education/engineering-education#4457]
#### introduction
Have you been giving a bunch of coordinates to plot on a map and you don't know where to start from? Don't fret, I've got a solution for that.
With the use of a front end design and jquery, we will show you how to plot countless markers on a leaflet map on a whim. This implementation would be made with bootstrap for the frontend design, the use of loops and jquery.

#### Key takeaways 
This tutorial will guide the reader on how to:
- Create a simple modal popup.
- Create a simple OSM layer.
- Create a seamless add and delete feature using jquery.
- Make use of loops to add multiple markers.

#### Article quality
The article relieves the reader of a lot of continuous stress. Instead of adding a bunch of coordinates, methods and functions in your code, the work will simply be done on the frontend. The article will make the reader's code less cumbersome.

#### References
- https://www.section.io/engineering-education/building-simple-maps-using-leaflet-js/

**Comment by WanjaMIKE** [comment]
Topic approved. Let's ensure that it adds value to the community. Thanks
