### ISSUE TITLE
Database implementation using java

### ISSUE THREAD

**Issue by tetie** [section-engineering-education/engineering-education#4458]
**topic suggestion**
Database implementation using java

Database  is a collection of  organized information /data stored in electronically in a computer. It helps in quick data recovery together with other data management activities. In this article we will look into details about interaction of the two and give relative examples where possible.
**key takeaways**

1. Interaction of java and database
2. Which database works  with java
3. How to secure database in java
4. Procedure to get  into database using  java

**reference**
N/A

**Comment by WanjaMIKE** [comment]
There is already an article on MYSQL in Java. Which other unique area will your article focus on?
