### ISSUE TITLE
A dive into Iterators in C++

### ISSUE THREAD

**Issue by Ndichu254** [section-engineering-education/engineering-education#4463]
#### Proposed title of the article
[Languages] A dive into Iterators in C++

#### Proposed article introduction
With the Iterator in C++, a standard template library component, traversing through your very complex data stored in various kinds of containers such as an Array or Vector takes the least amount of time feasible during execution. As a pointer, it's nothing more than that. It makes your algorithm independent of the container type you choose by providing a standard interface for all kinds of container, like a bridge between algorithm and container. Iterators don't only simplify programs; they also speed up their execution.
Iterator enables generic Algorithms to be applied to data structures straightforwardly. Data structures may use an Iterator to expose a variety of components.

#### Key takeaways 
By the end of this tutorial, the reader will understand:
- What are iterators and the various categories
- Various operations using the Iterators in C++
- Implementation of iterators in C++
- Advantages and disadvantages of iterators in C++
- Purposes of iterators in C++

#### Article quality
I will ensure a simple language throughout the tutorial, making it easier for the reader to understand.
To make it practicable, I will include practical implementation of the same.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appears to be over saturated. We focus more on unique projects. Feel free to suggest another topic. Thanks
