### ISSUE TITLE
[API] Updating a spatial database via API using Flask-restful

### ISSUE THREAD

**Issue by isaiaholadapo** [section-engineering-education/engineering-education#4466]
#### Proposed title of article
[API] Updating a spatial database via API using Flask-restful

#### Proposed article introduction

Geographic Information Systems (GIS) have various industrial applications, and technological advancements have significantly enhanced GIS data, specifically how it can be used and what can be achieved as a result. They are powerful decision-making tools for any business or industry since it allows the analyzation of environmental, demographic, and topographic data.

In this tutorial, readers will learn how to create an API that can save and retrieve spatial data to a geospatial database using Flas-restful. The API can be connected to a website, mobile app or pc software. We will also create tokens and set the expiry date for each token, any request without a token will be rejected.

#### Key takeaways 

Readers will learn how to:

- To build API with Flast-Restful and also verify users via api
- Create and retrieve data from a spatial database
- Create JWT-token payload and also set token expiry

#### Article quality

Readers will be able to create and retrieve spatial data using POST and GET requests, the database records can be accessed from different platforms such as web, mobile and desktop apps.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Please do not submit any other PRs. @isaiaholadapo Feel free to take this course: https://developers.google.com/tech-writing before submitting a new topic suggestion.
