### ISSUE TITLE
How create a well designed user interface using  C#  and explain properties of a good interface

### ISSUE THREAD

**Issue by Ndolo-Boniface** [section-engineering-education/engineering-education#4468]
C# is one of the most used programming language in the creation
of well designed user interfaces.  User interfaces helps a user to interact with a computer systems without much strain.
This helps even the illitrates to access a system with little or no training. In this article we will learn how to design user interfaces in C# as well as the properties  of  a more user friendly interface

***Key takeaways***
-introduction to c#
-how to create a c# project
-creation of a user interface in c#
-Properties of a good user interface

***References***
N/A

**Comment by WanjaMIKE** [comment]
Introductory aspects of UI in C# are already covered in numerous articles based on this search -> https://github.com/section-engineering-education/engineering-education/issues?q=C%23 Feel free to suggest another topic. Thanks
