### ISSUE TITLE
Introduction to Staggered RecyclerView Implementation in Android studio

### ISSUE THREAD

**Issue by Wachira48** [section-engineering-education/engineering-education#4471]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

The RecyclerView is an Android component that displays large data sets with a limited list of items and views. The RecyclerView is an improved and more versatile version of the ListView and GridView widgets. This list of items could be just Java objects. These Java objects could be an array of strings or a collection of strings, or custom Java objects. This list of objects is referred to as non UI elements. RecyclerView uses an adapter as the data transformation objects to convert a list of objects into a list of views. I.e., scrollable UI components with data sets whose elements alter based on user interaction or network events during runtime. RecyclerView generates a sufficient number of view components for the user to see the item list at any given time on the visible screen. As the user scrolls through the list, it uses the same view components to show data that is further down in the list. This makes efficient use of the UI components. essentially it is recycling these UI components, which is why it's called a RecyclerView

The RecyclerView class makes it easier to view and manipulate huge data sets by facilitating Layout managers for item positioning and configurable animations for basic item events like deleting and adding items. A layout manager arranges item views within a RecyclerView and decides whether or not to reuse views that are no longer visible to the user. A layout manager, for instance, can request the adapter to replace the view's contents with a different item from the dataset in order to reuse (or recycle) a view. RecyclerView widgets also offer the ability to set custom layout managers and animations. This implies you can change the size of your RecyclerView widget to fit the data collection it represents. For example, you can build RecyclerViews such as nested lists, expandable lists, staggered lists, etc.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- What is RecyclerView
- Why do we need RecyclerView
- What is staggered RecyclerView
- Set up Gradle Dependencies
- Create an Activity Layout with RecyclerView
- Create a Layout that will be used as a Grid in the staggered RecyclerView
- Setup Adapter and ViewHolder for the staggered RecyclerView.
- Setup recycler view manager (staggered grid manager)
- Setup RecyclerView staggered adapter
- Setup the staggered RecyclerView.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

https://developer.android.com/guide/topics/ui/layout/recyclerview

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Based on the attached plagiarism score, this topic appears to be over saturated. Feel free to suggest another topic. Thanks

![ba](https://user-images.githubusercontent.com/38399942/137742805-52ab8d60-5726-4f44-995f-7f1c1605e548.png)
