### ISSUE TITLE
[API]Handling Angular base64 images in a RESTFul API with Laravel

### ISSUE THREAD

**Issue by NaomiSeint** [section-engineering-education/engineering-education#4480]
#### Proposed title of article
Handling Angular base64 images in a RESTFul API with Laravel

#### Proposed article introduction
In this  tutorial, we’ll learn How to create a file upload section to display selected image and convert it into Base64 format. While selecting a file we’ll add validation for the file type, height & width of images.  

Uploading media files like profile images or PDF or Word documents to the server via a web form is a common practice in data-centric applications.
In Angular application where data is sent via HTTP calls, we can easily convert images and docs to the Base64 string and send them to the server is using HTTP Post.

We will then process this image using Laravel and store in our database.

#### Key takeaways 
- Working with images in Angular application
- Making HTTP request to upload images
- Handling base64 images with Laravel 8
- Storing image on the server
#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date
