### ISSUE TITLE
A quickstart to route async in Angular 12

### ISSUE THREAD

**Issue by vincentoriyo** [section-engineering-education/engineering-education#4482]
#### Proposed title of article
[Languages]A quickstart to route async in Angular 12

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Route async is an approach to limit the modules that are loaded to the ones that the user currently needs. This can improve your application’s performance and reduce the initial bundle size.

By default, Angular uses eager loading to load modules. This means that all the modules must be loaded before the application can be run. While this may be adequate for many use cases, there may be situations where this load time begins to affect performance.

#### Key takeaways 
-  Using loadChildren feature in Angular
- Setting Route Configuration in the Feature Module
- Running Lazy Load

**Comment by louisefindlay23** [comment]
@vincentoriyo, to make room in the queue we are closing this. Feel free to reopen when you are ready to answer our questions.
