### ISSUE TITLE
How To Create PDF files in Django

### ISSUE THREAD

**Issue by shosenwales** [section-engineering-education/engineering-education#4485]
#### Proposed title of article
How To Create PDF files in Django

#### Proposed article introduction

This article seeks to introduce the reader to how you can create pdf files in a django project. Also showing you can attach images to the pdf files

#### Key takeaways 

At the end of this article, the reader should:
- Be able to build django projects containing pdf files
- Be able to add images to pdf files
-Be able to convert html to pdf

#### Article quality

Asides creating pdf files, i will also be showing the readers how to add images to their generated pdf files

#### References
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @shosenwales 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
