### ISSUE TITLE
How to install a Linux Distro on android

### ISSUE THREAD

**Issue by 07munene** [section-engineering-education/engineering-education#4489]
A Linux Ditro (Linux Distribution) is an operating system made from a software collection that is based upon the Linux Kernel.
A typical Linux Distro comprises of a Linux kernel, GNU tools and libraries, additional software, documentation, a window system, a window manager and a desktop environment.
One of the most popular desktop Linux Distributions is Ubuntu. 
For users who want to experience a complete desktop OS on their android phones as they don’t want to carry around their laptops or tablets, it’s safe to say that it’s possible to install a fully functional Linux OS on your android phone.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @07munene 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by 07munene** [comment]
Thanks. Will consider
