### ISSUE TITLE
Creating a Book Cover Using JavaScript and p5.js

### ISSUE THREAD

**Issue by Michaelmurimi** [section-engineering-education/engineering-education#4506]
### Topic Suggestion
Creating a Book Cover Using JavaScript and p5.js

#### Proposed article introduction
Sketching is at the core of p5.js, which is a drawing and creative coding toolkit. p5.js is founded on the premise of writing the least amount of code to transfer your visual, interaction, or animation ideas to the screen, similar to how sketching may be thought of as a simple method to drawing to quickly prototype an idea. A JavaScript implementation of Processing's popular library, p5.js, is available as a free download from the p5.js website.

Using JavaScript and p5.js, this tutorial will show you how to create this exact visual effect.

#### Key takeaways 
By the end of this tutorial, the reader will have knowledge on the following concept;
- p5.js Basics
- Setup and draw functions
- Colors & Shapes in p5.js
- p5.js transformation functions
- push & pop
- Creating the Ring Shapes

#### Article quality
This will be a step-by-step tutorial with simple language to help anyone understand the concepts better. I will also use the simple illustration for better grasping of the concepts and make sure that this tutorial enriches the rest of EngEd with this great concept.

#### References
N/A

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
