### ISSUE TITLE
Immutable collections in java web

### ISSUE THREAD

**Issue by tiffy-keshie** [section-engineering-education/engineering-education#4517]
#### Proposed title of article
**Immutable collections in java web**

#### Proposed article introduction
Initially, making java functions immutable was not easy till the rise of javaFX which made this as cheap as a gym. This article will be showing step by step how to make the factory methods in java immutable. 

#### Key takeaways 
- what is a factory method?
- what is unmodifiableXXX?
- Initialization of immutable lists?
- Benefits of immutable collection using JavaFX.

#### Article quality
This article will be explaining a step by step to a writer on how immutable in javaFX are created and how they are use. It will form a basis for newbies to learn and understand immutable collection in the new JavaFX.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @tiffy-keshie

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
