### ISSUE TITLE
Currying concept in Javascript

### ISSUE THREAD

**Issue by Jairusonkundi** [section-engineering-education/engineering-education#4522]
#### Proposed title of article
Currying concept in Javascript

#### Proposed article introduction
Currying is a technique for converting a function with many parameters into a succession of single-argument functions. When a function accepts the first argument and returns a new function that takes the second argument and returns a new function that takes the third parameter, and so on until all arguments have been satisfied.
It makes it easier to avoid supplying the same variable over and over again. In this article, we will discuss more about currying function in Javascript , uses of curry function, examples of usage of currying, and advanced curry implementation.

#### Key takeaways 
-Definition of currying in Javascript
-Various ways in which the currying function is used 
-Examples of usage of currying function
-Implementation of advanced curry

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A

**Comment by WanjaMIKE** [comment]
As I said on this PR -> https://github.com/section-engineering-education/engineering-education/issues/4493 The topic is over saturated
