### ISSUE TITLE
[languages] Caching, Logging and Typography in Flutter

### ISSUE THREAD

**Issue by somtobe** [section-engineering-education/engineering-education#4523]
Proposed title of article
 Caching, Logging and Typography in Flutter

Proposed article introduction
In this tutorial, we’ll learn how to implement some advanced topics of caching, logging and Typography in our flutter applications.
In flutter these are important concepts. e.g caching our applications enables the development of fast, high performant applications.

Key takeaways
- Implement caching in flutter applications
- Know the importance of caching and logging when developing applications
- Know when to cache our data and when not to.
- Know when to set up logging in our application and where not to.
- Know how to implement multiple fonts by working with typography.

References
Please list links to any published content/research that you intend to use to support/guide this article.
- https://flutter.dev/docs
-

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by somtobe** [comment]
Hello, I have created my tutorial and opened a PR for this issue. Please do check it out.
