### ISSUE TITLE
Implementation of Linear Quadratic Regulator (LQR) Control for the Inverted Pendulum on a Cart

### ISSUE THREAD

**Issue by atienodorine3** [section-engineering-education/engineering-education#4541]
#### Introduction
The Linear Quadratic Regulator (LQR) controller is a well-known method that provides optimally controlled feedback gains to enable the closed-loop stable and high-performance design of systems. The LQR algorithm reduces the amount of work done by the control systems engineer to optimize the controller. However, the engineer still needs to specify the cost function parameters, and compare the results with the specified design goals. It is essentially an automated way of finding an appropriate state-feedback controller.
In this tutorial, we will see how to implement the LQR in Matlab. Here we design an optimal full-state feedback controller for the inverted pendulum on a cart example using the linear quadratic regulator (LQR).  Full-state feedback  is a feedback which gives a clear relationship between controller parameters and controller behaviour. In Matlab, we find that this is a simple one-line command `lqr`.

#### Key takeaways 
- Basic understanding of linear quadratic regulator.
- Application of a linear quadratic regulator.
- Matlab code to implement LQR.
#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @atienodorine3 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
