### ISSUE TITLE
[Networking] Introducing Threads in Java Socket Programming

### ISSUE THREAD

**Issue by SteveadeNick** [section-engineering-education/engineering-education#4554]
#### Proposed title of article
Introducing Threads in Java Socket Programming
#### Proposed article introduction
We don't want just one client to connect to the server at a time, but many clients to connect at the same time. We want our architecture to be able to support multiple clients at once. As a result, threads must be used on the server side so that whenever a client request comes in, a separate thread can be assigned to handle each request.
Assume that two requests arrive at the server. With our basic server-client program, the request that arrives even a nanosecond first will be able to connect to the server, while the other request will be rejected because no mechanism for handling multiple requests concurrently is provided. Threading is used in network programming to solve this problem.
#### Key takeaways 
- Why use threads in-network programming
- Server-Side Programming
- Client-Side Programming

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by SteveadeNick** [comment]
Hello, @WanjaMIKE 
Please look at this topic. It's been 10 days already.
Thanks.

**Comment by SteveadeNick** [comment]
@ahmadmardeni1 
Could you please look at this issue whenever you are free?
 Thanks

**Comment by ahmadmardeni1** [comment]
Hey @SteveadeNick
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
