### ISSUE TITLE
 Introduction to Kernel Methods in Machine Learning

### ISSUE THREAD

**Issue by Brian3811** [section-engineering-education/engineering-education#4567]
#### Proposed article introduction
Kernel method in machine learning is defined as a class of pattern analysis algorithms that are used to study and find general types of relations (such as correlation, classification, ranking, clusters, principle components, and so on) in datasets by explicitly transforming raw data representation into feature vector representation using a user-specified feature map, allowing the high dimensional implicit feature space of these data to be operated with computer systems.

#### Key takeaways 
Principle components analysis
Support vector machine
spectral clustering

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Brian3811** [comment]
Hi @LinusMuema 
unlike the other contents, my article will add a bit of SVM (Support Vector Machines) and Kernel Tricks. In my article, I'll take the reader step by step to the introduction to kernel methods in Machine learning. I'll be using simple grammar in my article hence it will be beginner-friendly

**Comment by LinusMuema** [comment]
okay...topic approved :rocket:
