### ISSUE TITLE
[API/Mobile]Haptics API with CapacitorJs

### ISSUE THREAD

**Issue by jerimkaura** [section-engineering-education/engineering-education#4600]
#### Proposed title of the article
Haptics API  with CapacitorJs

#### Proposed article introduction
Haptic respond to feel or touch in a mobile application.

 Capacitor JS takes advantage of the modern 'feel' functionality available in mobile devices. Through the haptics, an application can respond by vibrating or ringing when triggered.

This article aim at guiding the reader through implementing haptics in a Native mobile application using CapacitorJs. Capacitor js is a relatively new technology in software development, and this is the base of the insight to this article. While every programmer uses stable tech stacks, this article opens up to a new way of development.

#### Key takeaways 
1. Working with CapacitorJS
2. Implementing haptics on a Native application.
3. Building a cross-platform web/mobile applications

#### References
Please list links to any published content/research you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @jerimkaura 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just pinging you on this topic form - as I'm making some room in the topic queue.
No rush if you're still working on this one - if you need more time we can always re-open at a later date
