### ISSUE TITLE
[Machine Learning] Object Detection using YOLOV5  and PyTorch 

### ISSUE THREAD

**Issue by FREDERICO23** [section-engineering-education/engineering-education#4636]
#### Proposed title of article
Object Detection using YOLOV5 and PyTorch

#### Proposed article introduction
Object detection is a computer vision task that involves identifying objects in image and video data. Object detection is mostly applied in security, autonomous vehicles, face recognition, etc. 

In this tutorial, we will be building an object detection model using the YOLOV5 algorithm. YOLOV5(You Only Look Once) is a fast and accurate object detection algorithm that works by splitting images into a grid where each grid cell identifies an object by itself.

We will be implementing the YOLO object detection model in PyTorch and training it using the COCO dataset.

#### Key takeaways 
- Understanding YOLOV5
- Understanding object detection
- Using Pytorch

#### Article quality
This article provides more handy tips and dives deeper into object detection with YOLOV5.

#### References
- https://cocodataset.org/#download
- https://pytorch.org/hub/ultralytics_yolov5/

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @FREDERICO23 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
