### ISSUE TITLE
[Machine Learning] An Introduction to PyTorch Lightning

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#4642]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

An Introduction to PyTorch Lightning

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Pytorch lightning is a framework built on top of Pytorch. As we know, Pytorch is already great. Pytorch lighning is in a lot of ways even greater. PyTorch Lightining can be compared to the Keras API model which is built on top of TensorFlow. It is a lightweight PyTorch wrapper for high-performance primarily built for use by researchers and computer science PhD students.
This tutorial will give a gentle introduction to PyTorch lighting and implement an example to demonstrate how the framework can be used in code.  

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to understand:
1. What is PyTorch
2. What is PyTorch Lightning
3. The advantages of PyTorch Lightning over unstructured PyTorch
4. Who is PyTorch Lightning for?
5. Implement an example to demonstrate how PyTorch Lightning is used 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [PyTorch Lightning](https://www.pytorchlightning.ai/)
- [PyTorch Lightning GitHub Repo](https://github.com/PyTorchLightning/pytorch-lightning)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Bayler 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #4642 via #4816
