### ISSUE TITLE
[Blockchain] An Overview of Web 3.0 

### ISSUE THREAD

**Issue by JudyNduati** [section-engineering-education/engineering-education#4645]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
An Overview of Web 3.0 

#### Proposed article introduction
Web 3.O is an internet powered by Blockchains. It is the internet that was not possible before all the benefits that Blockchain provides. These benefits include the internet of value, decentralization, trust minimization, secure digital identity, and more. All these characteristics help Web 3.O create new business models and reinvent how the internet works.

When people talk of Web 3.O, they often ask how the future internet will be different from what we have today and what we have had in the past.

The emergence of Blockchain means we will be able to consciously build Web 3.O in a way that works for everyone. This article will outline how the web has evolved, where it's going, and why we need Web 3.O.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.
1. The Evolution of the Web
- What is Web 1.O
- What is Web 2.O
- What is Web 3.O
2. Why we need Web 3.0
3. How Blockchain works
4. What the Web 3.0 Stack looks like

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Great! Please @ me when you open your PR. And make sure it does not overlap with any articles on other blog sites. @JudyNduati  Approved.
