### ISSUE TITLE
[Security] How to perform a WordPress site Security Audit

### ISSUE THREAD

**Issue by LeahKui** [section-engineering-education/engineering-education#4648]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
How to perform a WordPress site Security Audit

#### Proposed article introduction
WordPress is one of the most widely used CMS around the world. However, multiple WordPress sites are running on vulnerable tools (plugins and themes). Shockingly, most admins of these sites don't know if they are vulnerable or not.

Most WordPress users haven't prioritized their website's security until something bad happens. You have a responsibility to your visitors, their data, and your WordPress site is generally safe. This is where the WordPress security audit comes in. 

This is a step-by-step guide on how to do a security audit on your WordPress site.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Overview of WordPress Security Audit
2. Why WordPress Security Audit is Essential
3. Step by Step guide on how to do a WordPress security Audit
- Software Updates
- Evaluate Themes and Plugins
- Examine user accounts and passwords
- Make sure your WordPress site has a 2FA
- Carry out a WordPress security website's analytics
- Check your 
- Have a  backup solution for your WordPress site

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LeahKui** [comment]
@LinusMuema, This tutorial is about WordPress (WP) security and specifically how to keep a WP website secure. WP site security can be a complicated topic, but this tutorial will make it perfectly digestible for both techies and non-techies. 

This tutorial will be more detailed for anyone who wants to make their website secure from common vulnerabilities. It will first take a look at the common WordPress vulnerabilities that make your site to be insecure. Then give the step-by-step process on how to do a WP security audit and a detailed explanation to prevent these vulnerabilities.

**Comment by LeahKui** [comment]
@LinusMuema, The content this tutorial will cover will be unique and add value beyond any published documents.

**Comment by LinusMuema** [comment]
That is exactly what the article I linked in the previous comment does so the article won't really differ from it.

You can explore other articles but we have to close this one.
