### ISSUE TITLE
[Machine Learning] Getting Started with Question Answering (Q&A) using BERT

### ISSUE THREAD

**Issue by splashtonia** [section-engineering-education/engineering-education#4653]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Getting Started with Question Answering (Q&A) using BERT

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Bidirectional Encoder Representations from Transformers (BERT), is a method of pre-training language representations which obtains state-of-the-art results on a wide array of Natural Language Processing tasks. One can get the pre-trained BERT model from [Tensorflow.JS](https://www.tensorflow.org/js/models).
This tutorial will show you how to build an NLP powered Question Answering (Q&A) with the popular BERT model developed by Google's research team in 2018.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, you should be able to understand:
1. What is BERT?
2. Learn how to install the BERT model and import its dependencies.
3. Using React.js, we'll create an interface to capture the questions and answers.
4. Learn how we can perform evaluations and score readings from the model

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [Question and Answer Pretrained Model](https://github.com/tensorflow/tfjs-models/tree/master/qna)
- [Create a New React App](https://reactjs.org/docs/create-a-new-react-app.html)

**Comment by ahmadmardeni1** [comment]
Could you please expand upon how your content will differ from what is already available through [other websites](https://towardsdatascience.com/question-answering-with-a-fine-tuned-bert-bc4dafd45626) and documentation?

**Comment by splashtonia** [comment]
First, most tutorial I've seen on Q & A with BERT tend to be very long and tend to overwhelm reader. My tutorial will be short and easy to follow as it'll only be a few lines of code. We need to democratize AI and we need to write code simple enough for beginners to understand. Secondly, not many tutorials have used the React framework in their build. My tutorial will do that. I'll also show my readers how they can build using Gradio, a new web user interface. Finally, evaluating how well models  perform is important in Machine Learning. Many tutorials tend to miss this step. I'll show my readers how to perform real-time BERT evaluation and scoring.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @splashtonia

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
