### ISSUE TITLE
SendRedirect in Servlet Collaboration.

### ISSUE THREAD

**Issue by Chaun864** [section-engineering-education/engineering-education#4655]
#### Proposed title of article
SendRedirect in Servlet Collaboration.

#### Proposed article introduction
Page redirection is commonly used when a document or any files are moved to a different location and we need to send the client there, or to balance the server load generated by more visitors accessing the page.
The HttpServletResponse interface's SendRedirect() method can be used to redirect a response to another resource, such as a servlet, jsp, or html file.

I'll go over the SendRedirect() in depth in this article.
#### Key takeaways 
1. Introduction
2. SendRedirect () and its significance.
3. Difference between SendRedirect() and RequestDispatcher.
4. An example of how to use SendRedirect()

#### Article quality
This article is very similar to Evans Lodoctor's Servlet Request and Servlet Collaboration article. The main difference is that Lodoctor tags in ServletDispatcha in the servlet collaboration section, whereas I'm going to use servlet collaboration in a different way. The SendRedirect()method will be used in this case. I'll also explain the differences between the two methods to help readers understand them better.

I'll make sure that this article is unique and useful to both new and experienced Java programmers. Thank you very much!

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Chaun864 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
