### ISSUE TITLE
How to build a Task Manager like app with C# in WinForms

### ISSUE THREAD

**Issue by Bonimum** [section-engineering-education/engineering-education#4656]
### Proposed title of article
How to list all Windows Processes and their attributes (Task Manager like) with C# in WinForms

### Introduction paragraph (2-3 paragraphs):
This article will teach us how to create a custom Task Manager or simply a create a Widget for your app that displays information about the processes in Windows. In this article you will learn how to get information about the processes in Windows and how to create a Task Manager like application easily.
### Key takeaways: 
By the end of this article the reader should have learned the following:

- Use the Diagnostics namespace
- List and retrieve basic information of all processes
- Creating a Task Manager like application

### References: 
N\A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Bonimum 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
