### ISSUE TITLE
How to work with Lombok on Quarkus

### ISSUE THREAD

**Issue by RisoriTofa** [section-engineering-education/engineering-education#4657]
#### Proposed title of the article

How to work with Lombok on Quarkus

#### Proposed article introduction

[Languages] Java language is a simple language for app development. The only turn-off to newbies is that it has so many syntactical terms to cram all at once.
This makes the newcomers confused and also wish for any way to shorten the code for them. Frameworks such as SpringBoot, Micronaut, Quarkus, and others have tried to come up with ingenious ways to do this.
This includes the use of easy-to-use libraries. These libraries provide annotations that can be quickly and easily used to replace blocks of codes.

Lombok is an example of one of these libraries. 'Project Lombok' as it's known, is a java library that plugs into your editor or IDE and builds tools simplifying Java.
It takes away the writing of getters, setters, or equals methods again. This is by use of one annotation.  The class will have a fully-featured builder, Automated logging variables, and much more.

#### Key takeaways

At the end of this article, the following will have been learned:

- How to set up Lombok in a Quarkus project
- IntelliJ lombok setup
- How to set up tests in Quarkus to test the Lombok project functionality
- How to deal with Getters and Setters in Lombok
- Access levels and constructors in Lombok
- EqualsAndHashCode and ToString annotations in Lombok
- Exclude and Data annotations
- Accessors and NotNull
- Builder, BuilderDefault, and Singular annotations in Lombok
- Slf4j, Lombok configurations, and custom logs

#### Article quality

This is an in-depth article on how to use the Lombok library in Quarkus. It also integrates the use of tests to the code to prove the functionality of the library.

#### References

- [Lombok source code](https://github.com/projectlombok/lombok)

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
good topic @RisoriTofa  - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
