### ISSUE TITLE
[Languages] Build simple moving average indicator with python.

### ISSUE THREAD

**Issue by Titusian72** [section-engineering-education/engineering-education#4660]
#### Proposed title of article
Build simple moving average indicator with python

#### Proposed article introduction
Moving averages are progress indicators used in various fields, including natural sciences and stock market trading. These calculations calculate momentum as observed values over time. In the stock market, for example, the simple moving average can help signal trend reversals.
Calculating the moving average in Python is straightforward, and it can be accomplished using custom functions, a combination of standard library functions, or powerful third-party libraries such as Pandas. In this article, we'll look at how to compute some common moving averages in Python and visualize them with Plotly.

#### Key takeaways 
1. What is the moving average indicator
2. How to use it in your technical analysis
3. DataFrames and Native pandas function
4. Using the pandas_ta Library

#### References
N/A

**Comment by ahmadmardeni1** [comment]
This topic is widely covered - Could you please expand upon how your content will differ from what is already available through other websites? @Titusian72

**Comment by Titusian72** [comment]
@ahmadmardeni1 , I believe knowledge cannot be exhausted and looking at the almost similar content online majority are not novice friendly and they are not engaging as much as possible. This article will be of course be one of a kind and it will  gracefully address this issues as much as possible in order to maintain quality and add value in the community. Thanks

**Comment by ahmadmardeni1** [comment]
Let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Titusian72

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
