### ISSUE TITLE
How to detect stop traffic using deep R-CNN in both real-time and offline mode in Matlab

### ISSUE THREAD

**Issue by florenceatieno45** [section-engineering-education/engineering-education#4661]
#### Introduction
R-CNN(Region with convolution neural network) is a deep learning approach that is used to detect various objects in an image. It finds its application in the area of autonomous vehicles, smart surveillance systems and facial expressions e.t.c. The models for object detection using R-CNN are based on three processes. The first process is finding the region in the image that may contain an object, that is, the region of the proposal. It then extracts the CNN features from the region and lastly classifies the object using the extracted features.

There are three variants of R-CNN. These are R-CNN, Fast R-CNN and Faster R-CNN. As the name suggests, the speed of training and detection improves from the first to the last. In this tutorial, we are going to use the R-CNN. We will use the image labeller application to create our pre-trained image database. Here, transfer learning is used where a pre-trained R-CNN is re-trained on its own image dataset.

#### Key takeaways 
- The proposed scheme when using deep R-CNN.
- Understanding Matlab's image labeller for image database creation.
- Matlab code for training and testing
#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Could you please expand upon how your content will differ from what is already available through other websites and [documentation](https://www.mathworks.com/help/vision/ug/object-detection-using-deep-learning.html;jsessionid=a6af3ceeaed5a34cce2a124978e2)? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by florenceatieno45** [comment]
It provides an outlook on the available deep learning frameworks, application program Interface services, and specific datasets used for object detection applications.
It also puts forth the idea of deploying deep learning models into various embedded platforms for real-time object detection. In the case of a pre-trained model being adopted, replacing the feature extractor with an efficient backbone network would improve the real-time performance of the R-CNN.
It describes how an R-CNN object detection framework would improve real-time detection performance on edge devices.

**Comment by florenceatieno45** [comment]
@LinusMuema 
It provides an outlook on the available deep learning frameworks, application program Interface services, and specific datasets used for object detection applications.
It also puts forth the idea of deploying deep learning models into various embedded platforms for real-time object detection. In the case of a pre-trained model being adopted, replacing the feature extractor with an efficient backbone network would improve the real-time performance of the R-CNN.
It describes how an R-CNN object detection framework would improve real-time detection performance on edge devices.

**Comment by LinusMuema** [comment]
Hi @florenceatieno45 
Sorry for the late response.

You can proceed with the article.
