### ISSUE TITLE
[Security] Why DevSecOps Need Security as Code

### ISSUE THREAD

**Issue by nellyat** [section-engineering-education/engineering-education#4662]
#### Proposed title of article
Why DevSecOps Need Security as Code

#### Proposed article introduction
DevOps was introduced to make the software development life cycle shorter. While software development organizations breathed a sigh of relief with DevOps making the process smoother, there was another challenge. Implementing security in the software became difficult. And to solve this issue, DevSecOps was introduced.

Security as code is key to achieving DevSecOps. It requires that security be defined at the beginning of a project and codified for repeated and consistent use. In this way, it gives developers a self-service option for ensuring their code is secure.

#### Key takeaways 

- What is security as code and DevSecOps? 
- Continuous delivery as a foundation of security as code.
- How security as code enables development teams to address security. 
- How security as code addresses risks in development and runtime.

#### Article quality
Most of the content available related to this topic are video conferences. 
#### References
N/A

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
