### ISSUE TITLE
[Languages] Scaling your Frontend with Micro-Frontends

### ISSUE THREAD

**Issue by mumbi00** [section-engineering-education/engineering-education#4663]
#### Proposed title of article
Scaling your Frontend with Micro-Frontends

#### Proposed article introduction
Every web service is bound to become a real nightmare as it grows. The codebase gets lengthier, the development team expands and the time spent on new feature deployment increases. While modern microservices architecture helps web applications become scalable, it still doesn’t seem to solve the issues entirely. And the reason is – the large frontend monolith hanging above all the microservices. Luckily, you can unlock microservices’ full potential by applying this pattern on both the backend and frontend of your application.

Micro-frontends is a relatively new architectural style for building web-based applications. They are an extension of the popular microservices pattern where the vertical slice of functionality that a microservice provides is extended all the way to the front-end. The application itself becomes a loosely coupled composition of micro-frontend components, with the pattern promising the same benefits as microservices

#### Key takeaways 

- What is a micro-frontend? 
- Why micro-frontends? 
- Common problems with app scaling.
- How micro-frontends help in scaling applications. 

#### Article quality
The few articles available concentrate on explaining micro-frontend architecture. In this article, I will explain how to scale applications using this architecture. 
#### References
N/A

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
