### ISSUE TITLE
[Machine Learning] A Gentle Introduction to the Python-Binance API

### ISSUE THREAD

**Issue by wilkistermumbi** [section-engineering-education/engineering-education#4665]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

A Gentle Introduction to the Python-Binance API

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Binance is a cryptocurrency exchange which is currently the largest exchange in the world in terms of daily trading volume of cryptocurrencies. The Binance API is a method that allows you to connect to the Binance servers via Python or several other programming languages.
This tutorial will give you a gentle introduction to the Python-Binance API. Later, we'll show you how to apply ML to trading and finance using this library.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will:
- Be introduced to the Python-Binance API.
- Learn about python-binance for crypto trading and finance.
- Learn how to install and import python-binance
- Learn how to apply ML to trading and finance using Python-Binance.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [Python-Binance](https://python-binance.readthedocs.io/en/latest/)

**Comment by ahmadmardeni1** [comment]
The API is explained very well in their documentation. And there are too many articles covering the same topic. What algorithms are you going to use in your ML model? @wilkistermumbi

**Comment by wilkistermumbi** [comment]
Well. The main library I'll be using is the Python-Binance library. Other algorithms I'll be using is mplfinance for visualizing financial data making it easier to create financial plots. In addition, I'll be using pandas and matplotlib which interface nicely with mplfinance.

**Comment by ahmadmardeni1** [comment]
Great! You didn't answer my question, what algorithms are you going to use in your ML model? @wilkistermumbi

**Comment by wilkistermumbi** [comment]
@ahmadmardeni1 I will be using the [Auto Regressive Integrated Moving Average](https://en.wikipedia.org/wiki/Autoregressive_integrated_moving_average) (ARIMA). It is a forecasting algorithm based on the idea that the information in the past values of the time to predict the future value of the series.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @wilkistermumbi
