### ISSUE TITLE
How to create a simple accordion menu using HTML, CSS & JavaScript

### ISSUE THREAD

**Issue by Terripha** [section-engineering-education/engineering-education#4670]
#### Proposed title of article
How to create a simple accordion menu using HTML, CSS & JavaScript

Use keyword research to improve your article's SEO.

#### Proposed article introduction
You can make attractive and dynamic web elements with HTML, CSS, and JavaScript. An accordion menu is another important element you may create. 

When a user hits a button, accordion menus expand and collapse. It's a great way to avoid having to show all of the information about a topic up front and instead allow users to see only what they require.

Accordion menu is a vertically stacked collection of numerous bits of information. Each list has a labeled header that links to the relevant material. By default, the content of each list is concealed. The content of a label can be expanded by clicking on it.

#### Key takeaways 
1. What is an Accordion Menu?
2. How to Style the Accordion with CSS
3. Adding JavaScript to our Accordion

#### References
N/A

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
