### ISSUE TITLE
Building FAQ page using React-styled components and React.js

### ISSUE THREAD

**Issue by KingsleyJack** [section-engineering-education/engineering-education#4673]
#### proposed title of article
[Languages] Building FAQ page using React-styled components and React.js

#### proposed article Introduction:

Addressing users questions and concerns is a priority for corporations and online vendors. One way of handling user's queries is by having a comprehensive frequently asked questions page. To build an attractive and informative FAQ page with React-styled components which is a modern front end design library will be discussed in this tutorial. We will take a deep dive into the requirements and steps to set up a unique FAQ page with Reactjs and React-styled components.

#### Key Takeaways:
At the completion of this tutorial, the reader is expected to have understand and knowledge to perform the following
i. Creating FAQ page with React-styled components and Reactjs
ii. Adding and using React-styled components
ii. Styling and viewing the page
iii. Adding dummies questions and answers with JSON
iv. Why you should choose React-styled components in your next React application
v. Creating reusable and customizable components with React-styled components

#### References
https://www.styled-components.com/

#### Article quality
This article is a project based application of the elements and modules of React-styled components and Reactjs. In this tutorial, we'll use React context api to monitor the state of our components, ie. when a user clicks a question, the corresponding answer opens up. The article will also walk the reader through the steps involved in integrating questions and answers from a JSON file which will be created during development.

**Comment by louisefindlay23** [comment]
Please fill in the topic suggestion form posted below in your form, @KingsleyJack.

**Comment by KingsleyJack** [comment]
@louisefindlay23 
Done as requested.

**Comment by KingsleyJack** [comment]
@louisefindlay23 i have updated the article quality section as you requested. thanks
