### ISSUE TITLE
[API] Building a News App API with Django REST framework and Deploying it to Heroku

### ISSUE THREAD

**Issue by norah254** [section-engineering-education/engineering-education#4678]
#### Proposed title of article
Building a News App API with Django REST framework and Deploying it to Heroku

#### Proposed article introduction

Django REST framework is a flexible and powerful library for building web APIs which allow applications to communicate with each other. It is built on top of the Django framework, a Python web development framework. Heroku is a platform as a service (PaaS) that enables developers to build, run, and operate applications entirely in the cloud. It is used for deploying apps to production.

In this tutorial, we will learn how to build a news app API using the Django REST framework and then how to deploy it to production on Heroku.

#### Key takeaways 
At the end of this tutorial, the reader should be able to:

1. Understand APIs and their use.
2. Understand CRUD features.
3. Learn how to set up and run Django REST framework.
4. Learn how to deploy Django apps on Heroku

#### Article quality
This article covers more in-depth content by providing handy tips for developing a web API using the Django REST framework to production on Heroku.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @norah254 

We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings such as heroku
