### ISSUE TITLE
[Languages] Understanding and working with JavaScript objects

### ISSUE THREAD

**Issue by rene-shigolah** [section-engineering-education/engineering-education#4681]
#### Proposed title of article
[Languages] Understanding and working with JavaScript objects

#### Proposed article introduction
An object in JavaScript has attributes and a type. Like a cup, for example. A cup is a property. A cup has a color, a pattern, a weight, and a material. Objects in JavaScript may also have properties that determine their attributes. 

Objects are composed of attributes or properties and functions/methods. Object properties describe the object while objects methods are functions that manipulates an object. 

#### Key takeaways 
In this article, we will learn about:
- How to create an object
- Array objects 
- String objects
- Math objects 
- date objects 
- A project to demonstrate the use of the JavaScript objects.

#### Article quality
To make my article unique, I will create a project to show how to use the above JavaScript objects.
#### References
N/A

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
