### ISSUE TITLE
[LANGUAGES] Using JSP, SERVLET, JDBC and MySQL to make a fully functional login/logout system.

### ISSUE THREAD

**Issue by hereliethgreatness** [section-engineering-education/engineering-education#4684]
Proposed title of article

[LANGUAGES] Using JSP, SERVLET, JDBC and MySQL to make a fully functional login/logout system.

Proposed article introduction

Login forms are an essential element in every website. They are the first UI that users interact with. We will be making a login\logout system which will be generally easier to comprehend because the number of programming languages needed will have been reduced to one.
We will incorporate JSP (java servlet page) which is a server-side programming technology incorporated in JAVA, we will use it together with HTML to make up the frontend. SERVLET PAGES are java classes which extend the capabilities of a server, they will be used as the primary back-end tool. JDBC (java database connectivity) is a method of specifying an application programming interface(API) which will allow JAVA as a programming language to communicate with a database. 
In our case we will use MySQL as our relational database management system which will function to store data and allow easier manipulation of said data. The logout button will be more secure as it will not save cache files to the login successful page. This will therefore disable the browser back button from accessing data after logging out.

Key takeaways 

1.	Making a login form using HTML\CSS and a registration form if need be.
2.	Manipulating a relational database such as MySQL using java code(JDBC).
3.	Learning how to use JSP and Servlet pages.
4.	Learning how to prevent cache files from being saved for logout.
5.	Learning how to call a class using method forName.
6.	Learning how to set up a dynamic web project in java.

Article quality
 Instead of overwhelming a novice in programming with long lines of code, this tutorial will be simplified enough to make sure that the learner gets more knowledge than what a fifty-page book could teach. This will be done by implementing key issues that most programming sources don’t cover.

References
N/A

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
