### ISSUE TITLE
Color layout descriptor(CLD) of MPEG-7 for content based image retrieval in Matlab

### ISSUE THREAD

**Issue by florenceakinyi** [section-engineering-education/engineering-education#4685]
#### Introduction
Content-based image retrieval(CBIR) refers to retrieving expected images from an extensive image database according to the content of the query image. The content mainly refers to the colour, texture and shape features of that image. These features can be extracted from images using various feature extraction techniques. CBIR gives the flexibility to search focusing on the content which has no predefined criteria. MPEG-7 is a standard for describing features on multimedia content. It provides the world richest set of audiovisual descriptions. 
These descriptors help users search, browse and retrieve content more efficiently and effectively than they could when using text-based search engines. For example, the colour layout descriptor is designed to capture the spatial distribution of dominant colours in an image. Colour is perhaps the most expressive of all the visual features and has been extensively studied in image retrieval research. In this tutorial, we will see how to implement all these in Matlab.  

#### Key takeaways 
- Basic understanding of CBIR.
- MPEG-7 visual descriptor.
- Basic understanding of Color layout descriptor(CLD).
- Steps to compute CLD.
- Matlab code to implement CLD.
- Applying CLD on two images and getting their closeness.
- Showing effectiveness of CLD in image retrieval. 
#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
