### ISSUE TITLE
Understanding Cross-Site Scripting Attacks

### ISSUE THREAD

**Issue by shosenwales** [section-engineering-education/engineering-education#4686]
#### Proposed title of article
Understanding Cross-Site Scripting Attacks

#### Proposed article introduction
[Security]Cross-site scripting (XSS) is a web security flaw that allows an attacker to compromise user interactions with a susceptible application. It enables an attacker to get around the same-origin policy, which separates websites. Cross-site scripting flaws allow an attacker to impersonate a target user and do any actions or access any of the victim's data.

#### Key takeaways 
- Overview of Cross-Site Scripting Attacks
- Types of XSS 
- How to mitigate XSS attacks

#### Article quality
I'll be using a practical approach to explain.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @shosenwales 

Could you please provide more information on the article. Especially the introduction.

**Comment by shosenwales** [comment]
Hi @LinusMuema 

Edited. Kindly go through
