### ISSUE TITLE
[API]Sending push notifications from Spring Boot backend server to Android mobile application

### ISSUE THREAD

**Issue by qawuor** [section-engineering-education/engineering-education#4688]
#### Proposed article introduction
A push notification is a message that pops up on a mobile device. Push notifications can be sent from the backend when a particular operation is carried out. Users don’t have to be in the app or using their devices to receive them.  For example, when an order is placed in a shopping application, the order is immediately confirmed. A push notification is sent to the users, informing them that the order has been confirmed.

Firebase Cloud Messaging (FCM) allows us to send messages to Android, iOS, or web applications, also known as push notifications. The article will explain the stepwise way of sending push notifications from a Spring Boot server to an Android application through Firebase Cloud Messaging.

#### Key takeaways 
1. Sending Push notifications from a Spring Boot server.
2. Setting up Firebase Cloud Messaging.
3. Receiving Push notifications from a Firebase Cloud Messaging.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have been published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?
Most of the already published articles do not explain how to send push notifications from a Spring Boot backend server to an Android application. The article will explain how to send push notifications from the backend server to the Android application.

#### References
[Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging)

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
