### ISSUE TITLE
[Languages] How to protect class objects from garbage collection in Java

### ISSUE THREAD

**Issue by munenekelvin** [section-engineering-education/engineering-education#4689]
#### Proposed title of the article
[Languages] How to protect class objects from garbage collection in Java

#### Proposed article introduction
A garbage collector is a component of software that manages memory. Its role is to remove unneeded memory and prevent memory from being freed while in use. In other programming languages like C/C++, the programmer creates and destroys objects. Useless objects are usually ignored by programmers Because of this while creating new objects, there may be insufficient memory and the application may crash due to OutOfMemoryErrors.

in Java's programming language, the garbage collector is automated, thus the user never has to manually free dynamically allocated memory. How does a trash collector pick what to delete? A lost reference causes an item to be deleted from the heap memory.

#### Key takeaways 
1. An overview of garbage collection in java
   In this key takeaway I will discuss:
- In Java, what is garbage collection?
- In Java, how do you dereference an object?
- How Java Garbage Collection Works
- java garbage collection roots
2.  Understanding the terms used:
- Unreachable objects
- Collection eligibility
3. Methods for making an item garbage-collectible
4. Methods for invoking the Garbage Collector in the JVM
5. Finalization
6. We employ the notion of the garbage collector in a real-life scenario.

#### Article quality
By the end of this article, we will have covered an introduction of Garbage collection and also the ways to prevent class objects from garbage collection in java thus completing two tasks at once.
Also, I will use a real-life example for a better understanding for the beginner.

#### References
N/A

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
