### ISSUE TITLE
[API] Running Laravel migrations on an existing database.

### ISSUE THREAD

**Issue by Agusioma** [section-engineering-education/engineering-education#4690]
#### Proposed title of article
Running Laravel migrations on an existing database

#### Proposed article introduction
Let's imagine your company needs to make a change and use Laravel from the raw PHP technology, or it needs to shift from another framework to Laravel. In addition to that, there is an existing database with thousands, if not millions, of records. Would you delete the database first and run fresh Laravel migrations? Or would you create fresh migrations and do some fragile data exportations? You can give up as well and advise the company on the complexity of the issue, right?

All the options given are not suitable and we need a way to carefully run our migrations on the existing tables. In this article, we will learn how to do that without interfering with any preexisting data. We will run our migrations on a live hosted database using a sample table without the need of installing any package.

#### Key takeaways 
1. Running migrations on an existing database.
2. Running the migrate command in scripts rather than the terminal.
3. Protecting fields from mass assignment.

#### Article quality
It will definitely provide more information about running terminal commands in the scripts for the live environment. Additionally, no package will be used.

#### References
N/A

**Comment by LinusMuema** [comment]
Could you please expand upon how your content will differ from what is already available through other website and [documentation](https://laravel.com/docs/8.x/migrations)? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by Agusioma** [comment]
Greetings @LinusMuema. The official documentation only covers running migrations on a 'freshly' created database. That is ,if you are creating one for the first time. But in this scenario, I'm looking at a case where there is an existing database, an already created database with records. Also, we will be deploying it on a live server(Apache), then configure the ```.htaccess``` files.

**Comment by LinusMuema** [comment]
Okay...awesome
