### ISSUE TITLE
Python Metaclasses for Metaprogramming

### ISSUE THREAD

**Issue by Dick7603** [section-engineering-education/engineering-education#4692]
#### Proposed title of the article
[Languages] Python Metaclasses for Metaprogramming

#### Proposed article introduction
As strange as it may seem, if you've ever dealt with decorators or metaclasses, you've already done some kind of metaprogramming. Metaprogramming, in a nutshell, is code that manipulates other code.
We'll talk about Metaclasses in this article, including when and why to use them and what to do instead.

#### Key takeaways 
Before beginning this tutorial, students should review "Decorators in Python" and "OOPS principles in Python."
By the end of this tutorial, the reader will be able to understand:
- What are metaclasses
- Cases where the users can use the metaclass
- What it entails in customizing the metaclass
- How to use a metaclass to fix issues even those involving complicated programming

#### Article quality
I will provide an in-depth explanation of the concept as well as incorporate a language easy to be understood by the reader. The reader will appreciate the fact that this tutorial shall provide practicable examples, therefore, making it beginner-friendly.

#### References
N/A

**Comment by LinusMuema** [comment]
good topic @Dick7603  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.
