### ISSUE TITLE
[Machine Learning] How to handle Imbalanced Data with SMOTE and Near Miss Algorithm in Python

### ISSUE THREAD

**Issue by mutheu21** [section-engineering-education/engineering-education#4693]
#### Proposed title of the article
[Machine Learning] How to handle Imbalanced Data with SMOTE and Near Miss Algorithm in Python

#### Proposed article introduction
The distribution of data is unbalanced when observations in one class are significantly greater or lower than those in the other classes Because machine learning algorithms aim to reduce error rather than enhance accuracy, they don't take the distribution of classes into account. This issue is common in applications such as facial recognition, fraud detection, and anomaly detection.
Standard machine learning algorithms like Decision Trees and Logistic Regression favor the majority class while ignoring the minority. They only accurately anticipate the majority group, which leads to serious misclassification of the minority group. We have an uneven distribution of data in our dataset where the minority class has a negligible or extremely low recall, hence our model is more prone to this situation.

#### Key takeaways 
By the end of this tutorial, the reader will be able to understand:
- What is Synthetic Minority Oversampling Technique (SMOTE) with what it entails
- What is Near Miss as an under-sampling technique with what it entails
- How to use SMOTE and Near Miss Algorithm

#### Article quality
By reading this article, you will have a better knowledge and practical experience on how to choose the appropriate strategy for managing imbalanced data. It will be in-depth explaining all aspects of this concept. I will use examples and with a language a reader can easily understand making it beginner friendly.

#### References
N/A

**Comment by LinusMuema** [comment]
good topic @mutheu21  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
