### ISSUE TITLE
JavaScript Monorepos with Lerna

### ISSUE THREAD

**Issue by borosteve** [section-engineering-education/engineering-education#4696]
### Topic Suggestion
JavaScript Monorepos with Lerna

#### Proposed article introduction
Monorepo To put it another way, it's a method that stores all of your various projects in an one repository rather than dealing with separate repositories. Assume you work for a company that has a variety of online applications that all follow the same style guide, have comparable setups, and so on. As a result, without monorepo, we have a variety of options. 
Lerna is a JavaScript project monorepo manager. It aids in the division of a big codebase into deployable packages that may be used separately. To make the release process as seamless as possible, Lerna handles everything from obtaining dependencies to linking packages and publishing new versions to the NPM registry.

In this tutorial we will discuss more on JavaScript Monorepos with Lerna and its implementation.

#### Key takeaways 
By the end of this tutorial, the reader will get the following concepts.
- Overview on what is Lerna
- Versioning modes in Lerna
- Creating a new monorepo
- Publishing your packages
- Configuring the CI/CD pipeline
- Continuous Deployment

#### Article quality
This will be a unique article with a detailed information.  In this article I will use a simple language for anyone to understand easily. I will make sure that it goes beyond other official docs and it adds value to the rest of EngEd.

#### References
N/A

**Comment by louisefindlay23** [comment]
How will your article differ from [this existing one](https://semaphoreci.com/blog/javascript-monorepos-lerna) on the same  topic?

**Comment by borosteve** [comment]
Hello, @louisefindlay23 
I have looked at the topic you suggested and I will make sure to write a unique article other than that one. In my article I will use a simple language and also add more information on it. Concepts such as usefulness of monorepo will be discussed which are a not in the suggested article.
Thank You.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by borosteve** [comment]
Hello can anyone open for me this please?

**Comment by WanjaMIKE** [comment]
Closed due to inactivity
