### ISSUE TITLE
[Android] Creating Settings in Android with Jetpack's Settings Preference

### ISSUE THREAD

**Issue by sheecodes** [section-engineering-education/engineering-education#4699]
#### [Android] Creating Settings in Android with Jetpack's Settings Preference

Users can adjust an application's functionality and behavior by changing its settings.
Settings can influence background behavior, such as how frequently the program synchronizes data with the cloud, or they can have a broader impact, such as changing the user interface's content and design.

The AndroidX Preference Library is the recommended method for integrating user-configurable options into your app.
This library controls the user interface and interacts with storage, allowing you to specify only the parameters that the user can change.
A Material theme is included in the library, ensuring a uniform user experience across devices and OS versions.

In this tutorial we will look at how to create settings for both Fragments and Activities. 

#### Key takeaways 
- Under what are the importance of having settings in an App
- Understand why you should use the new Settings Preference
- Customizing the different items in a Preference XML
- Understand how to preserve the state of the modified settings

#### Article quality
The Android Documentation is very shallow and beginners might find it hard to understand. In this tutorial, I will try and write a short and concise article that is beginner friendly and rich in original content.

#### References
N/A

**Comment by Ericgacoki** [comment]
Hello @sheecodes, this seems to be a duplicate if [this](https://github.com/section-engineering-education/engineering-education/issues/3909).

**Comment by JoelKanyi** [comment]
Thank you @Ericgacoki, I had not seen that

**Comment by sheecodes** [comment]
Thank you @Ericgacoki
