### ISSUE TITLE
An introduction to Sanity Headless CMS

### ISSUE THREAD

**Issue by Julius-1996** [section-engineering-education/engineering-education#4700]
### Topic Suggestion
Getting started with Sanity and Headless CMS
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposal Submission
The rise of [JAMstack](https://jamstack.org/) applications has revolutionized the way we write our front-end applications. Tools that act as content platforms treat the content on a web app as data. Sanity is a headless CMS. It comes with an open-source editing environment called Sanity Studio that you can customize with JavaScript and a real-time hosted data store.
#### Proposed title of article
Getting started with Sanity and content platforms

Use keyword research to improve your article's SEO.

#### Proposed article introduction
A headless CMS is a backend-only content management system, making content accessible via an API on any client device, without a built-in presentation layer. Headless CMS relies on JAMstack stands for (JavaScript, APIs, and Markup) to turn your web application content into a cloud-based API where it can be accessed from any application. In JAMstack, Sanity is the A or (API) as it is decoupled from your app giving you a single source of truth for your database to model and custom tail the content. Sanity provides an open-source studio to manage content where the data is stored in a [content lake](https://www.sanity.io/docs/datastore). It supports queries from a CDN using GraphQL, webhooks, and real-time updates. 

We'll get started with Sanity Studio which is an open-source headless CMS that connects to a hosted real-time data store. By the end of this, the learner should be able to get started with Sanity to power content in React or any JavaScript framework.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
1. Introduction to JAMstack and Headless CMS
2. Introduction to Sanity
3. Sanity features such as customizing fields and content types, data query and more
4. Building a blog app using 

#### Article quality
My article is unique as it just uses the docs as a reference while diving deeper to guide the learner on how to build stuff with sanity. Instead of diving direct to sanity, we get the learner to understand the trend that gives the rise of JAMstack and headless CMS.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
[Sanity docs](https://www.sanity.io/)

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
