### ISSUE TITLE
C# vs C++

### ISSUE THREAD

**Issue by mbuthiajn** [section-engineering-education/engineering-education#4702]
#### Proposed title of article
C# vs C++
#### Proposed article introduction

C# is a multi-paradigm general object-oriented programming language and is designed for common language infrastructure (CLI) language whereas C++ is a C++ is a general object-oriented programming language with imperative and generic programming features. It is an extension of the C programming language.
In this article, C++ and C# will be discussed in depth with focus on the way they work, similarities,key differences and when to use each language. 
This information shall be written in a way a beginner shall understand and can be used comprehensively by high end programmers.
#### Key takeaways 
 1.What is C# and C++?
2.Features and properties of C# and C++.
3.Head To Head Comparison Between C++ and C# (Infographics).
4.Key differences between C++ and C# with examples.
5.C++ vs C# Comparison
6.Cross-platform - Which of the languages is easily compatible to other platforms
7.Project - Where does each language suit the best. i.e, suited for complex web-based concurrency projects or game development projects
8.Syntax - which one offers developer friendly syntax
9.Conclusion.
#### Article quality
 I plan to cover in depth C# and C++ programming languages and clear off misconceptions and false ideologies that other ingenious have made programmers misunderstand. 
This concept shall also be in a way that a beginner will understand and still remain relevant to high end programmers.
#### References
 N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic - or continue working on this one by flushing it out a bit more (i.e. making it more in depthand/or providing more detail.
