### ISSUE TITLE
[Languages] In-Page Filtered Search With Vanilla JavaScript

### ISSUE THREAD

**Issue by Shee254** [section-engineering-education/engineering-education#4703]
### Topic Suggestion
In-Page Filtered Search With Vanilla JavaScript

#### Proposed article introduction
For a website with a lot of data, it's a good idea to allow people to search through the material to get the information they're seeking. When We say search, we are  not talking about searching via a database or even looking through JSON data; I am talking about searching through text on a single generated web page. Users can already do this search using their browser's built-in search feature, but we can make it even more convenient by providing our own search capability that filters down the page, making matched results simpler to locate and understand.

In this tutorial we are going to discuss more about In-Page Filtered Search With Vanilla JavaScript and its implementation.

#### Key takeaways 
By the end of this tutorial, the reader will understand the following concepts:
- Overview of In-Page Filtered Search With Vanilla JavaScript
- The basic markup
- The JavaScript baseline
- Adding a delay
- What about fuzzy searches?
- Wrapping up

#### Article quality
This will a detailed and unique article. I will use simple language for anyone reading this tutorial to grasps the concepts in an easier way. I will make sure that it goes beyond other official docs and that it adds value to the rest of EngEd.

#### References
N/A

**Comment by LinusMuema** [comment]
good topic @Shee254 - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
