### ISSUE TITLE
[Languages]Android Dashboard UI Design With Dark Mode in Android Studio using Kotlin

### ISSUE THREAD

**Issue by vifabulous** [section-engineering-education/engineering-education#4704]
#### Introduction
One of the important features that engage the user with the application's functioning is the dashboard design. It gathers information on the application's entire functionality in one place. Color being one of the biggest factors to consider when developing a human-computer interface, these modes are essential to implement in your application. 

In this article, we will get to know how one can develop a representable UI design dashboard with the implementation of dark/light mode. It will give a step-by-step directive on creating and implementing it all over your application.

#### Key takeaways 
- Requirements
- Modern UI/UX Design Basics
- Creating a Switch button
- Dark mode/Light mode creation
- Dark mode/Light mode Impact on UI/UX Design

#### Article quality
This article is intended to demonstrate how you can create and implement dark/light mode in an application. Unlike other articles, this will show how the mode can be applied in all application pages.
Besides that, it will be easy to understand with clearly explained steps.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Could you please expand upon how your content will differ from what is already available through [this article](https://morioh.com/p/44c2e770b2bf) with the same title? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by del-ui** [comment]
The dark mode in that article is accessed from the overall phone settings, meaning that the dark mode can only be applied in all applications instead of the intended one only.

In my article I intend to create an inbuilt and internally controlled button to switch between dark and light mode from within.

**Comment by vifabulous** [comment]
@LinusMuema  The dark mode in that article is accessed from the overall phone settings, meaning that the dark mode can only be applied in all applications instead of the intended one only.

In my article I intend to create an inbuilt and internally controlled button to switch between dark and light mode from within.

**Comment by LinusMuema** [comment]
Okay...

Make sure you provide more unique content than just the toggle button.

**Comment by del-ui** [comment]
Okay
