### ISSUE TITLE
How to set up a Python Web Socket with aiohttp

### ISSUE THREAD

**Issue by wanjcarol** [section-engineering-education/engineering-education#4711]
#### Proposed title of article

How to set up a Python Web Socket with aiohttp
#### Proposed article introduction

A socket consists of two major endpoints. One end sends data, and the other end receives data. Take an example of what you can do over the internet. In this case, different nodes/computers are connected to establish a connection that will allow you to send or receive data. A node can be a server or a client. A client sends a request, and the server will send back a response. These connections between the server and client are achieved through sockets. A socket acts as the communication endpoint.

This guide will discuss the socket concept in detail and build client-server socket architecture using the aiohttp.

#### Key takeaways 

- What are sockets
- The client-server architecture
- An introduction to aiohttp
- Build a client with aiohttp
- Build a server with aiohttp
- Send data between the client and the server

**Comment by LinusMuema** [comment]
Could you please expand upon how your content will differ from what is already available through the [documentation](https://docs.aiohttp.org/en/v0.18.2/client_websockets.html)? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by wanjcarol** [comment]
@LinusMuema, I believe this doc shows the very basics of a client WebSocket, just like any doc shows a hello world based on a certain technology. An creating an extensive socket that has a client and a server and exchanges data between the two.
