### ISSUE TITLE
Databinding in ASP.NET

### ISSUE THREAD

**Issue by stanleywambui435** [section-engineering-education/engineering-education#4713]
### Topic Suggestion
Data Binding in ASP.NET

#### Proposed article introduction
ASP.NET also provides the feature of Databinding, using Databinding you can attach any server controls to various expressions, collections, even methods, or properties. There is also the simplicity to select a data source, which can be a static file, a database or any other source.
So ASP.NET Databinding provides a simple and easy way to build a link between server management and application data.
#### Key takeaways 

1. Concepts of Databinding in ASP.NET
2. What is Databinding.
3. How to create Databinding in ASP.NET.

#### Article quality
This article will be unique because I will use a very different approach from what has been published in other blogs. My article will go beyond these articles by providing handy tips in Databinding in ASP.NET, 
#### References
N/A

**Comment by LinusMuema** [comment]
good topic @stanleywambui435  - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
