### ISSUE TITLE
Deserialization in C#

### ISSUE THREAD

**Issue by swambui1** [section-engineering-education/engineering-education#4715]
#### Topic suggestion
Deserialization in C#
#### Proposed article introduction
The accompanying article gives the Deserialization structure in C #. Allow us first to think about the course of serialization. Serialization is the method involved with changing an object into a structure over to be written in a stream and can be stored in a file, database or in a memory. Its fundamental design is to keep up with the state of the object. 
Presently, deserialization is the contrary course of serialization. It is the most common way of changing over an information stream back to an object to load to memory. This interaction empowers us to rebuild an object at whatever point needed.

#### Key takeaways 

1. Syntax and explanation
2. How deserialization works in c#.
3. Examples of deserialization in c#.

#### Article quality
This article will be different from what has been published in other blogsites. I will use simple language for anyone reading this tutorial to grasps the concepts in an easier way. I will make sure that it goes beyond other official docs and that it adds value to the rest of EngEd.
#### References
N/A

**Comment by louisefindlay23** [comment]
Hi, @swambui1. You should be more specific in your article quality section. How will you go beyond other official documentation? Can you tell me what additional areas or information you include that isn't covered elsewhere?

**Comment by swambui1** [comment]
Hello, @louisefindlay23. This article goes beyond what has been provided in official documentation,by covering areas such as,
1.Steps followed to deserialize an object using binary formatter.
2.Xml serialization and deserialization of custom class.
Which has not been covered in the official documents, and I hope this will be very helpful to the engineering community at large.
