### ISSUE TITLE
Authentication with Spring boot LDAP

### ISSUE THREAD

**Issue by olu-damilare** [section-engineering-education/engineering-education#4718]
###  Introduction paragraph (2-3 paragraphs):
Lightweight Directory Access Protocol mostly referred to as LDAP is an open and cross-platform protocol used for directory services authentication. It provides the communication language that applications use to communicate with other directory services servers that store the user details including their password, roles and any other necessary information.

In this article, we will be introduced to LDAP, its overview and also dive into what it entails. We'll explore the authentication mechanisms that are applicable when using LDAP, we'll build a very simple application that demonstrates how user details can be loaded from a file and used to authenticate the user through the Springboot LDAP authentication configuration. 

### Key takeaways:
At the end of the article, the reader should be able to:

Have a good knowledge of what LDAP entails and its applications
Understand the structure of the content of the access directory for loading the user details
Secure a Springboot rest API using the LDAP mechanism
Provide custom username and password for users of the application for user authentication

References:
https://www.baeldung.com/spring-data-ldap
https://spring.io/guides/gs/authenticating-ldap/

**Comment by LinusMuema** [comment]
Could you please expand upon how your content will differ from what is already available through the [documentation](https://spring.io/guides/gs/authenticating-ldap/)? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by olu-damilare** [comment]
The referred documentation simply contains an illustrative example. My tutorial is going to explore the fundamentals of LDAP, its structure and its usages. I will also guide the readers on the authentication mechanisms of LDAP then put all of it together by building a simple application that implements the techniques explored in the tutorial.

**Comment by WanjaMIKE** [comment]
I think the referred article already covers most of your key takeaways. Feel free to suggest another issue. Thanks
