### ISSUE TITLE
[DevOps] DevOps test automation strategy for a successful CI/CD adoption

### ISSUE THREAD

**Issue by Kama-144** [section-engineering-education/engineering-education#4722]
#### Proposed title of the article
DevOps test automation strategy for a successful CI/CD adoption
#### Proposed article introduction
The foundation of DevOps culture is test automation. The outbreak of the COVID-19 pandemic has compelled several institutions to adopt automated testing throughout the SDLC for CI/CD, even if they had previously recognized its importance and necessity. Work from home (WFH) reality necessitates enhanced test automation, which makes implementation more difficult. Many hats are worn by IT developers, operations engineers, and testers, all of whom work in independent operating units as distinct organizations. Going forward, the key question is whether QA can improve and speed up product delivery by integrating the many clusters under the DevOps banner. And if such is the case, how might automated testing scenarios be implemented? We'll answer all of these issues and show you how to implement a solid testing automation plan in this article.

#### Key takeaways 
1. Project’s scope of automation
2. Appropriate testing automation tool
3.  Setting up a cloud-based test environment
4. Test case risk assessment
5. Run and manage test cases
6. Analyze continuously and remodel the strategy for improvement
#### Article quality
Automated testing is the first move in the right direction when you embark on your automation journey and due to that, this article will be one of a kind as it will explain the concept of automation testing and it will be straightforward for the novices to grip the content in it. In contrast with the almost similar content on the internet, this article will be in the context and the examples that will be offered in this article will be basic to attract both intermediates and beginners in automation testing
#### References
N/A

**Comment by louisefindlay23** [comment]
Hi, @Kama-144. How does your article differ from [this](https://www.softwebsolutions.com/resources/devops-automation-strategy.html) similar one?

**Comment by Kama-144** [comment]
@louisefindlay23, I believe knowledge can never be exhausted and In contrast to the article you referred to me it is not in-depth as it addresses some critical issues like how to `Conduct a test case risk assessment` and it somehow tends to raise some flags on this argument `Run and manage test cases` as it is somewhat unclear of which in my article will gracefully address clarity and in-depth content will be provided accordingly to enhance community growth and development. Thanks

**Comment by louisefindlay23** [comment]
Topic approved, @Kama-144 but be sure to provide additional and unique value in your article.

**Comment by WanjaMIKE** [comment]
closed #4722 via #5027
