### ISSUE TITLE
Creating Responsive Line and Bar charts with React and Semantic-ui

### ISSUE THREAD

**Issue by FredBenson** [section-engineering-education/engineering-education#4724]
### Introduction:
Graphic illustration is an essential form of content presentation in front-end web development. Line and bar charts may have various applications such as, to show statistics of user engagements, user growth, ratings, etc. React.js, semantic-ui and CSS can be used to generate various line and bar charts as we will discuss in this article.
### Key Takeaways:
It is expected that at the completion of this article the reader will be equipped with the knowledge and necessary skill to understand and perform and the following: 
i.	Installing and adding the semantic-ui dependency to your web project
ii.	Getting started with React functional components
iii.	Creating reusable components with React.js
iv.	Generating Line and Bar charts with React.js
v.	Styling the components with CSS and semantic-ui
### References:
https://react.semantic-ui.com/elements/

#### Article quality
This article will walk the reader through the various steps required to generate line and bar charts from an array of numbers used as coordinates. The article will also teach the reader how to create a reusable chart component. Using semantic UI design libraries in creating charts is a unique concept that will be discussed in-depth.

**Comment by louisefindlay23** [comment]
Hi, @FredBenson. Please fill in the Article Quality section I've just readded to your topic suggestion form so we can adequately review your topic.

**Comment by FredBenson** [comment]
@louisefindlay23 
Done Ma'am. Thank you
