### ISSUE TITLE
[API]Create a Basic Browser GraphiQL Tool Featuring React.js, Node.js, MongoDB and Apollo

### ISSUE THREAD

**Issue by Catemacharia** [section-engineering-education/engineering-education#4725]
#### Proposed title of article

Create a Basic Browser GraphiQL Tool Featuring React.js, Node.js, MongoDB and Apollo

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

GraphQL is a query language for APIs used to communicate data between a client and a server. This allows you to structure data-driven applications much more flexibly and efficiently than the REST AND SOAP approach. GraphQL provides a complete and understandable description of the data in your API. It gives clients the power to ask for exactly what they need and nothing more. This makes it easier to evolve APIs over time and enables powerful developer tools. It also gives developers more control over how they use data in their apps.

GraphiQL is an interactive development environment. It's a tool built into many GraphiQL graphical services that allow you to interact with your app data and GraphQL APIs.

We will build a GraphiQL tool with React.js, Node.js, MongoDB, and Apollo server.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- What is GraphQL
- How does GraphQL work?
- What is GraphiQL
- How does GraphiQL work?
- Build a GraphiQL with React.js, Node.js, MongoDB and Apollo

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

A number of articles explain the concept of GraphQL with the likes of MERN and MEVN stack. However, GraphQL uses a mechanism that queries data and then displays that data with the GraphQL schema. This uses GraphiQL. You might want to query data from your application. A good example is how WordPress uses [wpGraphQL](https://www.wpgraphql.com/) to fetch WordPress-driven data. This guide will help the reader create a GraphiQL tool to perform such GraphQL tasks to provide an extendable GraphQL schema and API within your application.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
@Catemacharia, please fill in the article quality section of the Topic Suggestion form so we can review your topic for consideration.

**Comment by Catemacharia** [comment]
> @Catemacharia, please fill in the article quality section of the Topic Suggestion form so we can review your topic for consideration.

@louisefindlay23, I have filled in the article quality section
