### ISSUE TITLE
An Introduction to Solidity Programming

### ISSUE THREAD

**Issue by corpsgeek** [section-engineering-education/engineering-education#4728]
#### Proposed title of article
An Introduction to Solidity Programming

#### Proposed article introduction
This article will lay a basic foundation for the solidity programming language and use Remix Ethereum to compile and deploy smart contracts code to the blockchain. 

#### Key takeaways 
- Learn how to use Remix Web IDE
- Compile and Deploy Smart Contracts on the Blockchain
- Basic Introduction to Variables, Data Types and Structs in Solidity

#### Article quality
There are little to no content available that provides content on blockchain programming for beginners. This article will provide a strong educational reference material for newbies in blockchain programming to pick up Solidity pretty fast.

#### References
N/A

**Comment by lalith1403** [comment]
Can you modify the proposal to include the content in a single post. We don’t encourage series-based articles.

**Comment by corpsgeek** [comment]
@lalith1403  updated

**Comment by corpsgeek** [comment]
Great.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
