### ISSUE TITLE
[Kubernetes] Invoking the Kubernetes API in Node.js

### ISSUE THREAD

**Issue by Achie10** [section-engineering-education/engineering-education#4729]
#### Proposed title of the article
Invoking the Kubernetes API in Node.js

#### Proposed article introduction
If you have the ability to directly invoke the Kubernetes API, it makes life a little bit easier. As a result, GoDaddy developed Kubernetes-client, a Node.js client for Kubernetes that is simple to use.
It is mentioned as the officially supported Kubernetes client library for JavaScript on the official Kubernetes client library page. This is significant because it has the support of the Kubernetes SIG API Machinery, which implies that it is kept up to date with modifications to the Kubernetes API definition as they occur. It also implies that your support requests and concerns will be far more likely to receive a prompt response as a result of this. By the end of this instructional exercise, you will be able to invoke Kubernetes API in Node.js like a pro!

#### Key takeaways 
1. Installation
2. configuration
3. Deployments
4. Custom resources
5. watching resources
6. Error Handling

#### Article quality
By reading this article learners will appreciate how Kubernetes API lets you query and manipulate the state of objects in Kubernetes. Furthermore, understand the core of Kubernetes' control plane is the API server and the HTTP API that it exposes. And lastly understand how Users, the different parts of your cluster, and external components all communicate with one another through the API server.
#### References
N/A

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
