### ISSUE TITLE
[API] How to fetch data from external API in React.js

### ISSUE THREAD

**Issue by verah-tech** [section-engineering-education/engineering-education#4731]
#### Proposed title of article
How to fetch data from external API in React.js

#### Proposed article introduction
React.js is the most used JavaScript library to build modern applications. APIs are also gaining popularity and most developers are utilizing them in developing their web applications.
Fetching data from external API and rendering React components with that data is common practice in developing React applications.
In this guide, we will create a React application that searches a city name and displays the weather data about that city. We will use functional components alongside React Hooks to achieve the above.

#### Key takeaways 
At the end of this guide the learner will be able to:
- create a React application
- create a search box component and import it into the main application
- handle the operations of state using the useState hook
- integrate the API with our React components for fetching data and rendering the fetched data in our application

#### Article quality
In this guide, we will utilize the functional components and React Hooks, unlike most of the articles which are using class components and life cycle methods

#### References
- https://reactjs.org/
- https://getbootstrap.com/

**Comment by WanjaMIKE** [comment]
https://www.section.io/engineering-education/how-to-consume-data-from-an-api-in-react/

**Comment by WanjaMIKE** [comment]
Isn't this already covered

**Comment by verah-tech** [comment]
@WanjaMIKE Noted with thanks
