### ISSUE TITLE
Getting started with NLTK WordNet in Python.

### ISSUE THREAD

**Issue by K-jacinta** [section-engineering-education/engineering-education#4733]
#### Proposed title of article
Getting started with NLTK WordNet in Python.

#### Proposed article introduction
WordNet is a Python dictionary that is part of the Natural Language Tool Kit (NLTK). This is a large library aimed at making Natural Language Processing (NLP) simple. This article will go through some fundamental functionalities.
We are going to be discussing about every thing there is to know about Synsets, Hypernyms and Hyponyms .Meronyms and Holonyms and finally Entailments

#### Key takeaways 

- Getting Synsets, definition of a Synset and all Lemmas of a Synset.
- Hypernyms and Hyponyms.
- Meronyms and Holonyms.
- Entailments

#### Article quality
At the end of this article the reader will have better understanding of how to use WordNet which is a part of Python's Natural Language Toolkit to perform a good number of functionalities.  

#### Reference
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Is it theoretical or code-based?

**Comment by K-jacinta** [comment]
> Is it theoretical or code-based?

@lalith1403
the article will have both theory and  code to enable the reader understand the theory I will be using codes to show the reader the practical part of the theory.
Thank you

**Comment by lalith1403** [comment]
@K-jacinta Topic Approved.
