### ISSUE TITLE
How to write and call functions in python

### ISSUE THREAD

**Issue by Samrosh** [section-engineering-education/engineering-education#4738]
#### Proposed article introduction
Functions are an important aspects of the Python programming language, you may have already come across and used some of the many great functions that come with the Python language or its library ecosystem. As a Data Scientist, though, you'll frequently be required to build your own functions in order to address difficulties that your data presents.
As a result, this article will introduce you to Python functions and take you through how you can call them.
It will also include new methods in the current world of python programming language.

#### Key takeaways 
- Python's functions:-
1 Method vs. Functions
2 Arguments vs. Parameters
- User-Defined Functions: How to Define a Function (UDFs)
1 The statement of return
2 What Is the Best Way to Call a Function?
3 Adding docstrings to python function
4 Python Function Arguments
5 Variables at a Global and Local Level
- Python Anonymous Functions
- How to use main() as a function
#### References
N/A

**Comment by lalith1403** [comment]
Aren’t these topics covered widely on the net?

**Comment by Samrosh** [comment]
I will provide an in-depth explanation of the concept as well as
incorporate a language easy to be understood by the reader. The reader will
appreciate the fact that this tutorial shall provide practicable examples,
therefore, making it beginner-friendly

**Comment by lalith1403** [comment]
This is thoroughly covered throughout the web and we are looking for developer centric unique content. Please suggest alternative topics that satisfy the above criteria. Thank you.

I will be closing this issue.

**Comment by Samrosh** [comment]
Thank you for the clarification.
