### ISSUE TITLE
[Machine Learning] Building a Toxicity Classifier with Python Lightning and Transformers 

### ISSUE THREAD

**Issue by lcheptoo** [section-engineering-education/engineering-education#4742]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Building a Toxicity Classifier with Python Lightning and Transformers

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

The toxicity classifier model detects whether text contains toxic content such as threatening language, insults, obscenities, identity-based hate, or sexually explicit language. This tutorial will use the toxicity pre-trained model to recognize sentences that are toxic. We will also integrate this model into the [Gradio app](https://gradio.app/) to build an interactive application that will allow the user to enter a sentence and the model will in turn give an output if the sentence is toxic or not.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to:
1. Learn how to install and import the necessary dependencies.
2. Learn how to import the toxic classifier model into our Jupyter notebook/Google Colab.
3. Build the toxic classifier with PyTorch and integrate it into the Gradio app.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [Dataset](https://www.kaggle.com/c/jigsaw-multilingual-toxic-comment-classification/data)
- [Toxicity classifier model](https://github.com/tensorflow/tfjs-models/tree/master/toxicity)

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

**Comment by louisefindlay23** [comment]
@lcheptoo, please fill in the article quality section of the Topic Suggestion form I've readded so we can review your topic for consideration.

**Comment by lcheptoo** [comment]
@louisefindlay23 My tutorial is unique. The tutorials I've seen on this subject used the old toxicity classification [dataset](https://www.kaggle.com/c/jigsaw-unintended-bias-in-toxicity-classification) which had unintended bias with respect to mentions of identities. I'll be using a newer dataset called the [Jigsaw Multilingual Toxic Comment Classification](https://www.kaggle.com/c/jigsaw-multilingual-toxic-comment-classification/data) which is more robust and takes into account toxic comments across multiple languages and minimizes this bias.
