### ISSUE TITLE
[Languages] Learn Localization and Internationalization In Standard C++ - A Beginner's Guide

### ISSUE THREAD

**Issue by Tee-Stark** [section-engineering-education/engineering-education#4745]
#### In the modern world of software development, websites and applications are mostly built to function for the location or part of the planet where they are being used. It is valuable to know how to use the "out-of-the-box" features of a language to build localized software. 
In this article, we will learn how to use the standard library's `std::locale` class in C++ to internationalize program entities like numbers, currencies, date & time, etc.

#### Key takeaways 
At the end of this article, the reader would have learned:
- What a locale is, and its applications
- The different entities that can be localized in C++
- The meaning of a facet and its uses.
- How to use the `std::locale` class in C++ to localize entities of a program

#### Article quality
This article is unique in that it brings to the reader all that is required to build localized software using built-in functions of the C++ standard library. Most tutorials on the internet explain only some parts and to the best of my knowledge, a beginner wouldn't find them very explanatory without having to reference questions on StackOverflow or other articles. This tutorial is here to eliminate that.

#### References
- [https://www.geeksforgeeks.org/clocale-header-file-in-c/](https://www.geeksforgeeks.org/clocale-header-file-in-c/)
- [http://www.cplusplus.com/reference/locale/locale/facet/](http://www.cplusplus.com/reference/locale/locale/facet/)

**Comment by Tee-Stark** [comment]
Hi I'm sorry I haven't made the article submission of this topic yet, i had some health issues to battle with over the last one month, so I just got back to fitness and will do well to make my submission very soon. Thanks

**Comment by hectorkambow** [comment]
Not a problem>
Just and FYI we will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
