### ISSUE TITLE
Polymorphism in Java

### ISSUE THREAD

**Issue by Kimosop-Wakanda** [section-engineering-education/engineering-education#4746]
### Introduction
Polymorphism is the ability of an object to have more than one form. In other words, polymorphism is a feature in Java that allows a single task to be performed in different ways.
An example of polymorphism is the human body. The human body has organs like heart to pump blood, stomach for food and lungs to breathe.
In this article, we will break down polymorphism and give a detailed explanation with clear examples.
We will take a look at how it is implemented in java and how it relates to inheritance.
Furthermore, we'll discuss different types of polymorphism and how they differ from one another. Run time polymorphism will also be discussed.
Lastly, we'll use a code snippet of a real life example to illustrate the point of polymorphism.

### Key Takeaways
By the end the article, the following should have been covered:
1. Introduction to Polymorphism.
2. Examples of polymorphism.
3. Implementation of Polymorphism in java.
4. Types of Polymorphism.
5. Run time Polymorphism.
6. Real Life example of Polymorphism.

#### Article quality
The article proposal will provide an in-depth  explanation on the topic. There will be use of code snippets flow charts where applicable to help the user understand. The language used will be clear easy to follow through. The content will help a beginner to fully understand what polymorphism entails.

#### Reference
N/A

**Comment by louisefindlay23** [comment]
@Kimosop-Wakanda, please fill in the article quality section of the Topic Suggestion form I've readded so we can review your topic for consideration.

**Comment by Kimosop-Wakanda** [comment]
Greetings @louisefindlay23 
I have added the Article quality section 
Please continue with the revision
