### ISSUE TITLE
History of Microsoft from Bill Gates to Satya Nadella and various programming languages used in developing windows Operating System.?

### ISSUE THREAD

**Issue by mose-254** [section-engineering-education/engineering-education#4748]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
@mose-254, please fill in the article quality section of the Topic Suggestion form so we can review your topic for consideration.

**Comment by mose-254** [comment]
Microsoft is a software company that was founded in 1975 by Bill gates and Paul Allen, the company distributes diverse nature of products to both companies and business users across the globe. Mostly, the Microsoft products were desktop application in few years ago, but now the company offers a lot of standalone web and mobile apps globally for individual interests. A good example of Microsoft product is Windows Operating Systems of various versions such as windows 7,10 and now windows 11, apart from windows, Microsoft also offers Microsoft Office, Outlook, Microsoft Store apps among many other more services. Among the programing languages that Microsoft has been using ever since include, C#, C++,  F#, Python, Java among other more programming languages.

References
Taft, D. K. (2020). Microsoft Programming Languages. eWEEK.

**Comment by louisefindlay23** [comment]
Hi, @mose-254. Thanks for the additional information but it doesn't tell me how your article will benefit readers? What value does it provide?

**Comment by mose-254** [comment]
Hi louise, At the end of this topic the readers should be able to:
1. Have an in-depth understanding of Microsoft and the steps it has taken to come through.
2. My fellow engineers will be able to understand over ten programing languages that Microsoft is using to develop its products.
3. The readers will have a detailed information on Microsoft without which they would have not gotten without my article.

Most importantly, it will expand the knowledge of the readers on various languages that they had no idea whether it would have been of benefit to Microsoft and raise the readers' interest to learn the languages like F# and VB.Net
