### ISSUE TITLE
[Machine Learning] How to Implement  K Means Clustering Algorithm in Python

### ISSUE THREAD

**Issue by Madrinmarison** [section-engineering-education/engineering-education#4750]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed article introduction
K-Means clustering is an unsupervised learning algorithm that sample data points with similar characteristics together. This algorithm is widely used in clustering tasks. The good thing with the K Means algorithm, it works with datasets in both low and high dimensional spaces. This algorithm involves finding the centroids of the clusters and assigning each data point to the cluster with the closest centroid. The K in the K Means means the number of clusters.  There are defined methods used to choose the value of k from the data, i.e., the elbow method.

Below are the steps involved K Mean Algorithm :

* Step 1: Choose the number of clusters

* Step 2: Choose at random the k initial centroids

* Step 3: Assign each observation to the closest centroid

* Step 4: Recompute the centroids

* Step 5: Reassign each data point to the new closest centroid. If any reassignment occurs, we repeat step four; otherwise, we finish and declare our model ready for classification tasks.

As this is an implementation guide, instead of covering all unnecessary statistical presentations for the K Means algorithm, we will only talk about what happens under each of the above steps with the aid of a visual example, i.e., a scatter plot. By so doing, the learner will have a clear understanding of this algorithm rather than throwing them all the confusing statistical presentations that do not contribute much to its implementation.

So, in our study, we will be restrained within the steps. After we have considered what happens, we will implement this intuition in python using the sklearn library.

#### Key takeaways 
1. The learner will know what the K Means algorithm is.
2. The learner will, step by step, know how the K Means algorithm works.
3. The learner will know some of the methods to choose the number of clusters k.
4. The learner will know how to implement the K Means algorithm in python.

#### Article quality
What will make my article different is the way I will deliver the intuition behind this algorithm. To my best, I'll ensure the learner is exposed to what is important for this session. What is not essential will be regarded as noise for this session and thus will not be considered in the study.

The coding session will explain each step in a clear and precise way, and thus the learner will not struggle with following along with all this material

#### References
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
