### ISSUE TITLE
How to build a Currency Converter with React and its Material UI

### ISSUE THREAD

**Issue by Nomzy-kush** [section-engineering-education/engineering-education#4751]
### Writing sample(s): 
https://www.section.io/engineering-education/how-to-build-a-quiz-app-with-vanilla-javascript-and-tailwind-css/
https://www.section.io/engineering-education/how-to-build-a-music-player-with-vanilla-javascript/
https://blog.logrocket.com/svelte-material-ui-advanced-material-design-components/

#### Proposed title of the article
 How to build a Currency Converter with React and its Material UI

#### Proposed article introduction
This tutorial will teach you how to build a currency converter with React and style its components with Material UI. I will walk you through how hooks like `useState` and `useEffect` will be used to build this project. You will also learn how to handle API calls, two-way data binding, and so much more. It is a must-do beginner/intermediate project for React developers. 

#### Key takeaways 
1. Readers will learn how to import components from React’s Material UI that will help with the application’s UI.
2. Readers will learn about hooks and how they can help in building this application.
3. Readers will learn how to get the Real currency data from the Exchange Rate API.

#### Article quality
This article is unique because it doesn't only teach the readers how to build a currency converter with React, it also shows them how they can style their application with React's CSS framework: Material UI. Readers will also learn how to use React hooks like `useState` to implement some functionalities like state management in their application. 

#### References
N/A.

**Comment by louisefindlay23** [comment]
Hi, @Nomzy-kush. Topic approved but please ensure your article is in-depth to provide value to our readers and is unique enough from similar articles such as [this one](https://dev.to/epranka/currency-exchange-web-app-in-100-lines-using-the-cra-create-react-app-2fmk)
