### ISSUE TITLE
Gitting Started with Kernel SVM Algorithm in Python

### ISSUE THREAD

**Issue by Muthami-John** [section-engineering-education/engineering-education#4753]
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

### Kernel Support Vector Machine (SVM)
Kernel SVM is a machine learning algorithm used in data classification tasks. This algorithm is used when the data is linearly inseparable, i.e.,  data classes cannot be distinguished with a line. This is unlike the support vector machine(SVM) algorithm, which assumes that the data is linearly separable and, therefore, its classes can be distinguished with a linear decision boundary.

Finding an optimal decision boundary when the data is linearly separable using the SVM algorithm becomes an easy task. However, with linearly inseparable data, it's impossible to obtain a straight line that can classify different categories of the data. In such a scenario, it's where the Kernal SVM steps in.

To classify linearly inseparable data using a kernel SVM algorithm, we first transform the data by mapping it to higher dimensions and efficiently navigate all mathematics associated with high dimensions with the aid of the kernel trick.

In this article, we shall learn how all this is done.

### Things this article will cover are:
1. Why Kernel SVM algorithm.
2. How we map low dimensional data to high dimensions in kernel SVM.
3. What's the kernel trick.
4. How the Kernel trick deal with high dimensional calculations effectively
5. Parameter tuning for Kernel SVM
6. Types of kernel functions.
7. Implementing the Kernel SVM algorithm in python

#### Key takeaways 
By the end of this tutorial, the learner will know:

1. What's the Kernel SVM algorithm.
2. How to map low dimensional data to high dimensions.
3. What's the kernel trick.
4. How does the Kernel trick deal with high dimensional calculations effectively.
5. Types of kernel functions.
6. How to Implement the kernel SVM algorithm in python

#### Article quality
The approach to this algorithm will be beginner-friendly. All concepts of kernel SVM will be clearly explained so that it's easy to understand, and our coding session will ensure all implementation steps are presented in the same manner.

#### References
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Several grammatical errors in the proposal. Kindly correct.

**Comment by Muthami-John** [comment]
@lalith1403 
I've made the grammatical corrections on the issue above.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
