### ISSUE TITLE
Build a weather forecast app in next js

### ISSUE THREAD

**Issue by oyedeletemitope** [section-engineering-education/engineering-education#4754]
#### Proposed title of article
Build a weather forecast app in Next.js

#### Proposed article introduction
In this tutorial, I'll be creating a weather application in next js. We'll be using an external API to grab live web data from cities around the world. We'll also use the API to check out the weather forecast of the week.
It's a really basic starter project and for those who have a basic react knowledge and want to go into server side rendered react app with next js then this article is for you. The only prerequisites is for you to have a basic react knowledge

#### Key takeaways 
Use this area to get your ideas down on the bulk of your article or tutorial.
At the end of this tutorial the readers should be able to:
- know what next js is
- when to use it
-Know the  key advantages next js has over react
- Install next js
- Be able to create application in next js
- fetch an external API in next
#### Article quality
This tutorial doesn't just dive into building the app but I'll also take my time to explain what next js is all about and also give tips on when to use it based on my experiences whilst also comparing using the create react app with create next app

#### References
https://nextjs.org/docs/api-reference/create-next-app

### Conclusion
So in this tutorial we've learnt what next js is all about, when to use them, we also compared it with just using the create react app and let's not forget we  built a weather app in next js. Job well done guys would you please share if you found this helpful.

Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Outline
- Title
- Introduction
- What is Next.js
- Why should you use it
- Comparing Next.js with React
- Building the weather app (this includes requirements)
- Conclusion

**Comment by louisefindlay23** [comment]
Hi, @oyedeletemitope. Please fill in the topic suggestion form I've readded so we can accurately review your topic.

**Comment by oyedeletemitope** [comment]
Please how do I find the topic suggestion form

**Comment by oyedeletemitope** [comment]
Any update on the review?

**Comment by oyedeletemitope** [comment]
Hello Louise, I'm almost done with writing the article but I noticed that it might need to be a two part series because of how long it is... hope that won't be a problem.

**Comment by louisefindlay23** [comment]
We don't mind longer articles as long as it adds value and isn't filler-type content. Unless, the two articles can stand alone as seperate entities, we'd prefer one longer article.
