### ISSUE TITLE
Working with coroutine in python

### ISSUE THREAD

**Issue by Nganga89** [section-engineering-education/engineering-education#4759]
#### Proposed title of the article
[Languages] Working with coroutine in python

#### Proposed article introduction
Coroutines are subroutines that have been expanded. They are used for cooperative multitasking, in which a process voluntarily yields (gives up) control on a periodic or idle basis to allow other programs to execute at the same time.
Coroutines are similar to generators in Python, but with a few extra methods and subtle differences in how yield statements are used. Coroutines can consume data as generators produce data for iteration.
The reader should have prior knowledge of Generators in python.

#### Key takeaways 
By the end of this tutorial, the reader should be able to understand:
- What are coroutines in python
- The difference between coroutine and subroutine
- How to execute and close coroutines in python
- Chaining coroutines

#### Article quality
This will be an in-depth tutorial in terms of coverage of the concept. I will also cover how coroutine is different from threads and To make it more practicable I will include examples relevant and to be well understood by the reader including explanations to enhance understanding. This article will include an easy but understandable language making it beginner-friendly.

#### References
N/A

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by WanjaMIKE** [comment]
Closed #4759 via #4902
