### ISSUE TITLE
collection in c++

### ISSUE THREAD

**Issue by tetieb** [section-engineering-education/engineering-education#4763]
Introduction
Collection in c++ is a framework that provides an architecture for you to store and manipulate data. In fact talk about containers. It is often used when storing or manipulating data during runtime. In this article, we will introduce collection and discuss using various examples of how we can manipulate data at runtime without having to specify storage or size.
Furthermore, we will use  clear explanations to understand the Collection interface hierarchy. We will see how the sub-interfaces like list, queue, set, etc relate to each other.
Moreover, we will learn how to implement the collections sub-interfaces since we cannot implement collection itself. We will further discuss the classes of collection which some of include ArrayList, LinkedList,  among others.

**Key Takeaways**
In the article, the user will get to learn:

Introduce Collections in c++
The Collection interface hierarchy
Relation of Collection sub interfaces
Implementation of interfaces
Classes of collection
**Reference**
N/A

**Comment by hectorkambow** [comment]
@auxesis 
Please be sure to use this [topic suggestion form](https://github.com/section-engineering-education/engineering-education/issues/new?assignees=&labels=topic+suggestion&template=enged-content-idea-suggestion.md&title=)
