### ISSUE TITLE
PHP filesystem functions

### ISSUE THREAD

**Issue by Ndolo-Boniface** [section-engineering-education/engineering-education#4764]
These are functions which allows a user to access and manipulate the filesystem.
They are part of the PHP core, therefore, need no installation. 

**Key takeaways**
-file functions examples
-Their examples
-Default filesystem functions
-Specification in different platforms

**References**
N/A

**Comment by hectorkambow** [comment]
@Ndolo-Boniface 
Please be sure to use this [topic suggestion form](https://github.com/section-engineering-education/engineering-education/issues/new?assignees=&labels=topic+suggestion&template=enged-content-idea-suggestion.md&title=)
