### ISSUE TITLE
 Introduction to Powershell Write-Host 

### ISSUE THREAD

**Issue by EssyH** [section-engineering-education/engineering-education#4765]
#### Proposed article introduction
The output is displayed in the PowerShell console using the write-host cmdlet. You can change the text color and background color of the displayed output. Write-host does not treat the object as an object when it is supplied to the pipeline; instead, it treats it as a name parameter or value and simply shows output in the console.

#### Key takeaways 
Parameters in Write-host
Write-host with -seperate
Write-host with -background color
Write-host with -no new line
syntax of Write-host
Merits of write-host in powershell

#### Article quality
In my article, I'll take the reader step by step to the introduction to Powershell Write-Host. I'll be using simple grammar in my article hence it will be beginner-friendly

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@EssyH 

Please be sure to use this [topic suggestion form](https://github.com/section-engineering-education/engineering-education/issues/new?assignees=&labels=topic+suggestion&template=enged-content-idea-suggestion.md&title=)
