### ISSUE TITLE
How to overload operators in python

### ISSUE THREAD

**Issue by Ndichu254** [section-engineering-education/engineering-education#4766]
#### Proposed title of the article
[Languages] How to overload operators in python

#### Proposed article introduction
Overloading an operator refers to providing them more meaning than their established operational meaning. The operator +, for example, may be used to add two numbers, connect two strings, and merge two lists. Because the `+` operator is overloaded by the int and str classes, it is possible. This is known as Operator Overloading, and it occurs when the same built-in operator or method behaves differently for objects of various classes.

#### Key takeaways 
By the end of this tutorial, the reader will understand:
- What it means by overloading the operators in Python and how to do it.
- How to overload a binary + operator in Python
- Some of the methods and functions for overloading an operator in python

#### Article quality 
I will ensure well coverage of this concept in an in-depth approach. This will be beginner-friendly as it will ensure easy and understandable language all through the article. Where there will be examples I will ensure explanations in all my examples and with this, it will be more practicable. It will also include overloading comparison, equality and less-than operators in Python

#### References
N/A

**Comment by hectorkambow** [comment]
@Ndichu254 

Please be sure to use this issue template:
https://github.com/section-engineering-education/engineering-education/issues/new?assignees=&labels=topic+suggestion&template=enged-content-idea-suggestion.md&title=
