### ISSUE TITLE
Collection in c++

### ISSUE THREAD

**Issue by tetie** [section-engineering-education/engineering-education#4767]
**topic suggestion**
Collection in c++

**Introduction**
Collection in c++ is a framework that provides an architecture for you to store and manipulate data. In fact talk about containers. It is often used when storing or manipulating data during runtime. In this article, we will introduce collection and discuss using various examples of how we can manipulate data at runtime without having to specify storage or size.
Furthermore, we will use clear explanations to understand the Collection interface hierarchy. We will see how the sub-interfaces like list, queue, set, etc relate to each other.
Moreover, we will learn how to implement the collections sub-interfaces since we cannot implement collection itself. We will further discuss the classes of collection which some of include ArrayList, LinkedList, among others.

**Key Takeaways**
In the article, the user will get to learn:

1. Introduce Collections in c++
2. The Collection interface hierarchy
3. Relation of Collection sub interfaces
4. Implementation of interfaces
5. Classes of collection

**Reference**

N/A

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

**Comment by louisefindlay23** [comment]
@tetie, please fill in the article quality section of the Topic Suggestion form I've readded so we can review your topic for consideration.

**Comment by tetie** [comment]
Hi, @louisefindlay23. This article goes beyond what as been covered in official documentations, by covering areas such as:
Classes of collection in c++,The collection interface hierarchy, implimentation of interfaces.
Which are not covered in the official documents. Furthermore,  i will also use  simpler language for user to understant the article without strain. I also hope that my article will add value to the entire engineering community.
