### ISSUE TITLE
Introduction to PHP graphic techniques 

### ISSUE THREAD

**Issue by SarahAsuquo** [section-engineering-education/engineering-education#4768]
####Proposed title of article
[Languages] Introduction to PHP graphic techniques 

####Proposed title introduction
PHP has the Inherent ability to create and manipulate graphics independently. The scope and capabilities of PHP graphics handling is indeed deep and powerful. It does this with the aid of the GD library which currently supports image formats in JPEG, png, gif and wbmp. 
    This tutorial aims at giving a solid foundation to intended readers on the first steps to take in this graphics journey. It is an intended intro to follow up graphics tutorials that I intend to publish here. 

Key takeaways
i.	Readers will learn how to create a canvas, ink and paint brush.
ii.	Readers will learn how to draw geometric shapes such as rectangles, polygons e.t.c
iii.	Readers will learn how to write words on the canvas.

**Comment by LinusMuema** [comment]
good topic @SarahAsuquo  - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
