### ISSUE TITLE
A Complete Guide on JavaScript Design Patterns

### ISSUE THREAD

**Issue by EssyWanjira** [section-engineering-education/engineering-education#4769]
### Topic Suggestion
A Complete Guide on JavaScript Design Patterns
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction

JavaScript is the programming language of the browser. As developers, we always strive to write quality and clean code. Design patterns are what make solutions that can be reused to commonly occurring software design problems at scale. The benefit of adopting such proven techniques is that we get proven and reusable solutions that improve communication among developers.
This article will cover:
- The factory pattern
- Visitor pattern
- Strategy pattern
- Observer pattern
- Singleton, mediator, and iterator patterns
For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
1. Introducing software design patterns from a JavaScript developer perspective
2. Exploring various techniques to implement design patterns
3. Quality explanations with examples

#### Article quality
Design patterns are useful to developers. Therefore, this article goes beyond to explore this design patterns with unique and useful examples. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @EssyWanjira 

Could you please expand upon how your content will differ from what is already available through the [toptal website](https://www.toptal.com/javascript/comprehensive-guide-javascript-design-patterns)? We lean towards content that offers an original viewpoint/approach around programming-centric topics.
