### ISSUE TITLE
Understanding memoization in Python

### ISSUE THREAD

**Issue by markiesar57** [section-engineering-education/engineering-education#4772]
#### Proposed title of article
Understanding memoization in Python.

#### Proposed article introduction
In the year 1968, Donald Michie coined the term "memoization." It comes from the Latin word memoranda, which means "to remember." It isn't a typo of the word memorization, though it does have some similarities. Memoisation is a computer technique for speeding up applications. This is performed by remembering the outcomes of processed input calculations, such as function call results. The previously saved results can be utilized again if the same input or a function call with the same parameters is used, avoiding redundant calculation.
In this article we will discuss what  memoization in python is, which functions can be memoized, the Memoization Algorithm, how to use memoization in Python programs, and how to inspect the Function Results Cache

#### Key takeaways 
1.What is memoization in Python.
2.Which functions can be memoized.
3.The Memoization Algorithm.
4.How to use memoization in Python programs.
5.Inspecting the Function Results Cache.

#### Article quality
This article gives an in-depth understanding of memoization in python which is a very important aspect for applications today. The reader will be able to apply memoization comfortably after reading this article

#### References
N/A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @markiesar57 

We closed a similar article #4590 so we cannot move forward with this article. 

Feel free to explore other options.
