### ISSUE TITLE
[Languages] Working with CSV files in Python

### ISSUE THREAD

**Issue by carteblanchemunene** [section-engineering-education/engineering-education#4773]
#### Proposed title of article
[Languages] Working with csv files in Python

#### Proposed article introduction
CSV (Comma Separated Values) is a straightforward file format for storing tabular data in spreadsheets and databases. A CSV file is a plain text file that contains tabular data (numbers and text). A data record is represented by each line in the file. Each record has one or more fields, which are separated by commas. The name for this file format comes from the usage of the comma as a field separator.

#### Key takeaways 
By the end of this tutorial, the reader should be able to understand:
- what CSV is
- how to read a CSV file
- how to write a CSV file
- how to write a dictionary to a CSV file
- how to work with large CSV files in Python
- how to convert multiple JSON files to CSV Python
- Creating a dataframe using CSV files
- Conclusion

#### Article quality
By the end of this article, the reader will have acquired the needed knowledge on CSV  and the working of CSV files.

#### References
N/A

**Comment by louisefindlay23** [comment]
How will your article differ from those that cover the exact same topics such as [this one](https://realpython.com/python-csv/)? That is what you should specify in the article quality section, @carteblanchemunene.

**Comment by carteblanchemunene** [comment]
Hello @louisefindlay23,  I have checked the suggested article and also other documentation.
The articles, tutorials do not give a detailed explanation on working with CSV files, they only cover the introductory part and writing and reading CSV files. This article will cover in detail: the Introductory part of reading and writing CSV files, working with large CSV files in Python, converting multiple JSON files to CSV Python, and creating a data frame using CSV files. Also, the code snippets and content explanations will be simple, making them suitable for beginners, intermediates, and specialists alike.
