### ISSUE TITLE
Using filtering to create angular data grids

### ISSUE THREAD

**Issue by wanjadeno** [section-engineering-education/engineering-education#4774]
### Topic Suggestion
Using filtering to create angular data grids

#### Proposed article introduction
IgniteUI for Angular Grid's filtering options include Quick filtering, Excel style filtering, and Advanced filtering, allowing users to display just entries that fit specific criteria. The Material UI grid component in Ignite UI provides angular filtering features as well as a comprehensive filtering API via the Data Container to which the Grid is linked.
In this tutorial, we will discuss how to Build an Angular Data Grid With Filtering concept.

#### Key takeaways 
1.  Consider the angular grid component.
2. Filtering
   - Importing the component first
   - Calling the component
   - Configuring the component
   - Marking up the rest of the UI
   - Binding the data
    
#### Article quality
This will be a unique article which will help the reader understand the concept of creating angular data grids with filtering by the end of the tutorial.

#### References
N/A

**Comment by WanjaMIKE** [comment]
You can only suggest one topic at the moment.
