### ISSUE TITLE
[Languages] How to overload operators in python

### ISSUE THREAD

**Issue by Ndichu254** [section-engineering-education/engineering-education#4777]
#### Proposed title of article
[Languages] How to overload operators in python

#### Proposed article introduction
Overloading an operator refers to providing them more meaning than their established operational meaning. The operator +, for example, may be used to add two numbers, connect two strings, and merge two lists. Because the + operator is overloaded by the int and str classes, it is possible. This is known as Operator Overloading, and it occurs when the same built-in operator or method behaves differently for objects of various classes.
Consider the following scenario: we have two objects that are physical representations of a class (user-defined data type), and we need to add them using the binary '+' operator. The compiler throws an error because it doesn't know how to add two objects. As a result, we define a method for an operator, a technique known as operator overloading. All current operators can be overloaded, but no new operators may be created. Python offers a custom function or magic function that is automatically run when it is associated with a certain operator to conduct operator overloading.

#### Key takeaways 
By the end of this tutorial, the reader will understand:
- What it means by overloading the operators in Python and how to do it.
- How to overload a binary + operator in Python
- Some of the methods and functions for overloading an operator in python

#### Article quality
I will ensure well coverage of this concept in an in-depth approach. This will be beginner-friendly as it will ensure easy and understandable language all through the article. Where there will be examples I will ensure explanations in all my examples and with this, it will be more practicable. It will also include overloading comparison, equality and less-than operators in Python.

#### References
N/A

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
