### ISSUE TITLE
[Language] Python program to build flashcard using class in Python

### ISSUE THREAD

**Issue by FranciscaNg** [section-engineering-education/engineering-education#4779]
#### Proposed title of article
Python program to build flashcard using class in Python

#### Proposed article introduction
In this tutorial, we will look at how to create a flashcard in Python using a class. 
A flashcard is a card with information printed on both sides that can be used to aid in the memorization of information. Flashcards are often divided into two parts: a question on one side and a response on the other. This article will focus on creating flashcards that will contain both the word and the meaning of the word on the card itself.
#### Key takeaways 
- We will look at different types of flashcards and their approaches 
- We will look at implementations of these approaches 
- We will build a flashcard step by step using python
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @FranciscaNg 

Could you please expand upon how your content will differ from what is already available through other websites and youtube videos? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by FranciscaNg** [comment]
@LinusMuema 
This article will focus on creating flashcards that will contain both the word and the meaning of the word on the card itself. It will take the word and its meaning as input from the user.
Create a class named flashcard, use functions to assign values for Word and Meaning then print all the stored flashcards using loops. Thanks.

**Comment by LinusMuema** [comment]
Hi @FranciscaNg 

I don't think the article would provide more unique content than what is available on the other articles. 

You can explore other options
