### ISSUE TITLE
 [Machine Learning] Cancer cell classification using Scikit-learn

### ISSUE THREAD

**Issue by MeshiJohn** [section-engineering-education/engineering-education#4780]
#### Proposed title of article
 Cancer cell classification using Scikit-learn

#### Proposed article introduction
In Artificial Intelligence, a subfield known as `Machine Learning` studies how computers can learn on their own, without having to be explicitly programmed. Many real-world issues can be solved with the help of machine learning.
The characteristics of cancer cells can be used to determine if they are `malignant` or `benign,` so let's start with that. To solve a machine learning challenge, we'll be utilizing scikit-learn. Scikit-learn is a free and open-source Python framework for machine learning, data mining, and data analysis.
#### Key takeaways 
- The dataset
- Implementation of classification using Scikit-learn
- Organizing the data
- Evaluating the trained model’s accuracy

#### Article quality
We will be classifying cancer cells based on their features and identifying them if they are malignant or benign using scikit-learn library for python programming language. We will be using breast cancer Wisconsin dataset for our machine learning problem.
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Please fill in the article quality section so we can review your topic suggestion.

**Comment by MeshiJohn** [comment]
Done @louisefindlay23
