### ISSUE TITLE
Enhancing security for free BSD using IPFW and SSH Guard 

### ISSUE THREAD

**Issue by Vivianbarry** [section-engineering-education/engineering-education#4783]
#### Proposed title of article
Enhancing security for free BSD using IPFW and SSH Guard 

#### Proposed article introduction
VPS servers are frequently targeted by intruders. A common type of attack shows up in system logs as hundreds of unauthorized ssh login attempts. Setting up a firewall is very useful, but by itself may not adequately control disruptive intrusion attempts.

This tutorial shows how to construct an enhanced intrusion barrier for FreeBSD using two programs, the ipfw firewall and sshguard. SSHGuard is a small add-on program that monitors system logs for "abusive" entries. When offenders attempt to gain access, sshguard instructs ipfw to block traffic originating from the offender's IP address. The offender is then effectively shut out.

Once it's understood how these programs work, managing server protection is pretty simple. Though this guide is focused on configuring FreeBSD, parts of it apply to other OS and firewall software.
#### Key takeaways 
1. Configuring IPFW
2. Install and configure SSHGuard
3. Create a rules script
4.  Startup and testing
5. Keeping vigilant.

#### References
n/a

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

**Comment by louisefindlay23** [comment]
Please fill in the article quality section so we can review your topic suggestion.

**Comment by WanjaMIKE** [comment]
Please ensure that all sections are filled appropriately before submitting a topic for approval
