### ISSUE TITLE
Deploying kubernetes with terraform

### ISSUE THREAD

**Issue by Wyclife1** [section-engineering-education/engineering-education#4784]
#### Proposed title of article
Deploying kubernetes with terraform

#### Proposed article introduction
As Kubernetes continues to dominate the container orchestration space in the technology industry, infrastructure automation products are all expanding their feature sets to include a method to connect to and configure Kubernetes so it can be managed along with the other resources you are already managing with your choice of automation tool.

As a leading infrastructure-as-code product, Terraform has a connector called the Kubernetes provider. Let’s take a look at what you can do with it.
#### Key takeaways 
1.  Configure the provider
2.  Deploy NGINX in a pod
3. Create a service to expose NGINX externally

#### References
n/a

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

**Comment by louisefindlay23** [comment]
Please fill in the article quality section so we can review your topic suggestion.

**Comment by WanjaMIKE** [comment]
Please ensure that you fill all sections before submitting a topic for approval. Thanks
