### ISSUE TITLE
[Languages] Creating Sequential Stream from an Iterator in Java

### ISSUE THREAD

**Issue by Wambuajuma** [section-engineering-education/engineering-education#4786]
#### Proposed title of article
Creating Sequential Stream from an Iterator in Java

#### Proposed article introduction
In this tutorial, I'll show you how to use an iterator to generate a sequential stream in Java.
In order to convert an Iterator to a Stream, the process is a bit complicated. Next, you convert the Iterator (or Splitter) to be a Splitterator. In the next step, you'll convert the Spliterator into a Flow. For this two-step process, the explanation is that there are options you need to offer that don't have suitable default values. Instead, you may wish to create an unordered Spliterator, which may have a performance advantage in some situations. The order in which the components exit the Iterator may or may not have any significance. In this circumstance, we refer to it as a disorderly situation.

#### Key takeaways 
- Sequential Streams
- Using Iterable.Spliterator() to create  a sequential stream from an Iterator
- Using Spliterator to create  a sequential stream from an Iterator

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Wambuajuma** [comment]
@ahmadmardeni1 
[This](https://github.com/section-engineering-education/engineering-education/issues/3834) topic was closed and I requested you to reopen it but I guess you did not get my requests. I have opened a new topic, you may have a look whenever you are free. Thanks.

**Comment by ahmadmardeni1** [comment]
Hey @Wambuajuma I'm sorry, I didn't see the notification. We will review your topic suggestion soon. It is in the queue now.

**Comment by ahmadmardeni1** [comment]
Hey @Wambuajuma I'm sorry, I didn't see the notification. We will review your topic suggestion soon. It is in the queue now.

**Comment by ahmadmardeni1** [comment]
Can you give this topic a review, please? @LinusMuema

**Comment by LinusMuema** [comment]
Hi @Wambuajuma 

[This article](https://www.techiedelight.com/create-sequential-stream-from-iterator-java/) seems to be providing more content than what you're suggesting and also, from a simple google search, your article title brings up multiple blogs and websites covering the same issue. How will your article differ from all of these?

**Comment by WanjaMIKE** [comment]
I think this topic appears to be too saturated. Feel free to suggest another topic. Thanks
