### ISSUE TITLE
[language] Semaphore in Java

### ISSUE THREAD

**Issue by MarkMoki** [section-engineering-education/engineering-education#4787]
#### Proposed title of article
Semaphore in Java

#### Proposed article introduction
Java's semaphore clock. A counter on a semaphore restricts access to a shared resource. Access is granted if the counter is higher than zero. Zero indicates that access has been denied. Permits that allow access to the shared resource are being counted by the counter. As a result, a thread needs a semaphore permit in order to access the resource in question.
An attempt is made to obtain permission from the resource owner to utilize a semaphore.
Semaphores with counts bigger than zero have a permit to decrement their count, and so do threads with counts greater than zero. In the absence of a permit, the thread will be suspended. The count of the semaphore is incremented when a thread releases a permit to use a shared resource. It is possible that another thread is waiting for a permit at the same time as this one.

#### Key takeaways 
- Working of semaphore in Java
- Constructors in Semaphore class 
- Using Semaphores as Locks

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

#### Article quality
Other blogs don't go into great length on a semaphore in Java, but they do cover the fundamentals of the concept. It will be covered in great length in this article how semaphores work, how constructors in the Semaphore class work, and how semaphores can be used to lock and unlock objects. As a result, because of their simplicity, code snippets and content descriptions will be understandable to novices, intermediates, and professionals alike.

**Comment by louisefindlay23** [comment]
Please fill in the article quality section so we can review your topic suggestion.

**Comment by MarkMoki** [comment]
Done @louisefindlay23
