### ISSUE TITLE
Creating a Blazor Server-Side Application Using ASP.NET Core To Perform CRUD Operations

### ISSUE THREAD

**Issue by Joesongoma** [section-engineering-education/engineering-education#4790]
### Topic Suggestion
Creating a Blazor Server-Side CRUD Application Using ASP.NET Core

### Writing sample(s): 
https://www.section.io/engineering-education/java-timer-tasks/

#### Proposed title of the article
Creating a Blazor Server-Side CRUD Application Using ASP.NET Core

#### Proposed article introduction
Server-side processing occurs when a page is requested for the first time and when pages are posted back to the server. For example, validation, saving and retrieving data, and navigating to other pages are all examples of server-side processing. 

In this tutorial, we will learn how to make a Blazor Server-Side Application from scratch and perform CRUD operations in it.
The types of CRUD operations we will perform include;
- creating a data list
- reading data from the list
- updating the list
- deleting data from the list.

#### Key takeaways 
After reading through this tutorial, the reader should be able to;
have a better understanding of what CRUD operations are.
be able to create a blazor server-side CRUD application using ASP.NET Core that adds, deletes, and edits data in a blazer server app.
If the reader is a beginner, be able to have a syntax of C# from this article.

#### Article quality
In this article, I will be taking the reader through step by step process on how he or she can be able to create a Blazor Server-Side CRUD Application Using ASP.NET Core and a detailed explanation of what the code he or she writes in each model does.

#### References
N/A

**Comment by Kayere** [comment]
Sounds like a good topic @Joesongoma - Approved.
