### ISSUE TITLE
[Machine Learning] Handpose Detection using MediaPipe and React.js

### ISSUE THREAD

**Issue by smkinyan** [section-engineering-education/engineering-education#4794]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Handpose Detection using MediaPipe and React.js

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Handpose recognition is a deep learning technique that allows you to detect different points on your hand. These points on your hand are commonly referred to as landmarks. These landmarks consist of joints, tips, and bases of your fingers. The handpose model is provided by tensorflow.js and is able to detect 21 different distinct points in your hand. The model is a lightweight ML pipeline consisting of two models: A palm detector and a hand-skeleton finger tracking model. It predicts 21 3D hand key-points per detected hand.

This tutorial will show our readers how to build our very own Handpose detector using mediapipe and Python. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to:
1. Learn how to install and setup the pre-trained handpose model
2. Learn how to build the handpose application using a video camera/webcam
3. Learn how to detect these landmarks on the hand in real-time using the camera

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [MediaPipe HandPose](https://github.com/tensorflow/tfjs-models/tree/master/handpose)
- [Create a New React App](https://reactjs.org/docs/create-a-new-react-app.html)

### Article quality

How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Tensorflow.js has many pre-trained models. The handpose model is one of their latest releases. Not many articles exist on the subject. Those that are present are either too complex to understand. We need to democratize AI and the use of such amazing pre-trained models should be understood with only a few lines of code. My tutorial aims to do just that. Keeping it simple but still unique.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @smkinyan
