### ISSUE TITLE
[Machine Learning] Feature Selection with Recursive Feature Elimination (RFE) Algorithm in Python

### ISSUE THREAD

**Issue by Madrinmarison** [section-engineering-education/engineering-education#4796]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Feature Selection with Recursive Feature Elimination (RFE) Algorithm in Python

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Feature Selection with Recursive Feature Elimination (RFE) Algorithm in Python
 Feature Selection is the process of automatically or manually selecting those features which contribute most to the predictive model. The Feature Selection method is a crucial technique because having irrelevant features in a dataset can increase the model's complexity and lower its accuracy. Therefore, it helps us select only those features that are statistically significant for Predictive Analysis. Among various techniques used in the Feature selection, Recursive Feature Elimination (RFE) is one.

### Recursive Feature Elimination
RFE is a Wrapper-based feature selection method that searches for a subset of relevant features from the feature space by starting with all features in modelling and then successfully removing less important features until the desired number remains. This is achieved by fitting the given machine learning algorithm used in the model's core, ranking features by importance, discarding the least important features, and re-fitting the model. This process is repeated until a specified number of features remains.

When the whole model is created, a measure of variable importance is computed. These measures rank the predictors from most important to the least. At each search stage, the least important predictors are iteratively eliminated before rebuilding the model. Features are scored either using the provided machine learning model, such as some Tree-Based algorithms like decision trees or Random Forest, which offers importance scores or a statistical method.

In this article, we shall intuitively cover the principal concepts of the RFE algorithm and later learn how to implement it in python.

#### Key takeaways 
By the end of this tutorial, the reader is expected to know the following.
1. What's the Feature Selection and why is it important.
2. What are different techniques used in the feature selection.
3. What's the Recursive Feature Elimination technique.
4. How does the RFE algorithm work.
5. How to implement the RFE algorithm in python.

#### Article quality
Although this is an implementation article, I'll spend a reasonable amount of time and try to provide the learner with an intuitive introduction to the RFE algorithm that is easy for a beginner to understand. In this article, I will not dive into the implementation session unless the beginners are aware of what they are implementing. In short, this article will not assume learners have prior knowledge of the intuition behind the RFE algorithm as many online articles assume. The coding session will ensure all code snippets are clearly explained.

I believe in presenting the content in this article uniquely in a manner that is of high benefit to learners.

#### References
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Please fill in the article quality section so we can review your topic suggestion.

**Comment by Madrinmarison** [comment]
Hello @louisefindlay23 
I have  fill in the article quality section. Now you can review the topic.
Thank you!
