### ISSUE TITLE
Comparison of Inheritance in C++ and Java

### ISSUE THREAD

**Issue by mbuthiajn** [section-engineering-education/engineering-education#4798]
#### Proposed title of article
Comparison of Inheritance in C++ and Java
#### Proposed article introduction
The purpose of inheritance is the same in C++ and Java. Inheritance is used in both languages for reusing code and/or creating an ‘is-a’ relationship.
In this article I will use examples that 
demonstrate the differences between Java and C++ that provide support for inheritance. For instance, when creating a class in Java it automatically inherits from the Object class. In C++ however, there is a forest of classes; when we create a class that doesn’t inherit from another, we create a new tree in a forest. 
#### Key takeaways 
1.Understanding inheritance and its application in C++ and Java
 2..Simple inheritance using Java and C++
3.Level inheritance using  Java and C++
4.Multiple inheritance using Java and C++
5.Class Hierarchy in Java and C++
6.Conclusion
#### Article quality
 I plan to use examples to illustrate differences and similarities of inheritance in C++ and Java.My content will be written in a language that a beginner will understand without loosing the enthusiasm of programming.

#### References
 N/A

**Comment by Kayere** [comment]
Hello @mbuthiajn, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
