### ISSUE TITLE
[Artificial Intelligence] How Intelligent Automation is Powering Machine Vision

### ISSUE THREAD

**Issue by nellyat** [section-engineering-education/engineering-education#4799]
#### Proposed article introduction
With the development of artificial intelligence and robotic process automation (RPA), intelligent automation has become a new norm in business process automation. Fundamentally, an intelligent automation system spots and generates voluminous data and can automate entire workflows. 

Computer vision plays an essential role in intelligent RPA solutions. Computer vision is an AI technology that helps computers “see” and understand the content in digital images such as photographs, PDFs, diagrams, drawings, videos, and more. This technology is already powering intelligent automation applications, becoming one of the most rapidly developing areas in automation.

#### Key takeaways 

- What is machine vision? 
- How is intelligence automation relevant to machine vision? 
- Where is computer vision technology used? 
- The future of computer vision technology and intelligent automation. 

#### Article quality
Computer vision is a relatively new AI technology. As such, there are not many blogs taking about it beyond its definition and some use cases. This article is different in that it discusses a newly added technology into machine vision, that is, intelligent automation.

**Comment by lalith1403** [comment]
Can you describe the scope of the article? What is the value added? There are several articles on computer vision. It is well documented.

**Comment by nellyat** [comment]
@lalith1403 This article explains computer vision in connection with intelligent automation. Intelligent automation is a relatively added technology to computer vision and its explanation has not been exhausted in other blogs.

**Comment by lalith1403** [comment]
What do you mean by intelligent automation?

**Comment by nellyat** [comment]
Intelligent automation (IA) combines robotic process automation (RPA) with advanced technologies such as artificial intelligence (AI), analytics, optical character recognition (OCR), intelligent character recognition (ICR), and process mining to create end-to-end business processes that think, learn and adapt on their own. @lalith1403

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
