### ISSUE TITLE
[Networking] 5G: the Long-Awaited Enterprise Internet Failover

### ISSUE THREAD

**Issue by mumbi00** [section-engineering-education/engineering-education#4803]
#### Proposed title of article
5G: the Long-Awaited Enterprise Internet Failover

#### Proposed article introduction
Even today, businesses often pay for two fixed-line corporate internet services from two different carriers, providing them with route and service provider diversity if one of the services has an outage. This ensures they can work around issues that would otherwise be disruptive to their operations.

With the advent of 5G comes a new option for businesses wanting a backup internet service. Instead of paying for that second fixed-line service, they can instead provide a 5G service and cut traffic across it as and when necessary.

Also, the influx of remote work, IoT devices, and cloud services is an absolute necessity to implement a 5G failover solution in any modern-day business setting. Availability, Reliability, and Bandwidth are the three main connectivity categories to consider for a failover solution. A 5G failover solution is the best bet when looking to meet these categories.

#### Key takeaways 

1. What is Failover Connectivity?
2. Is redundancy the same as failover? 
3. How 5G enhances network failover.
4. How failover ensures business continuity. 

#### Article quality
Most of the available articles are a bit shallow in content when it comes to explaining 5G as a failover. 

#### References
N/A

**Comment by Kayere** [comment]
Hello @mumbi00 , we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
