### ISSUE TITLE
[Internet of Things]How to control a Servo Motor using a Raspberry Pi 3

### ISSUE THREAD

**Issue by RuthAMare** [section-engineering-education/engineering-education#4807]
### Topic Suggestion
How to control a Servo Motor using a Raspberry Pi 3

#### Proposed title of article
How to control a Servo Motor using a Raspberry Pi 3

#### Proposed article introduction
This article will seek to explain how a raspberry pi can be programmed to control a servo motor. The aim is to simulate a simple  IoT scenario where the motor simulates a car engine and the Raspberry Pi the control system.
We will attempt to start and stop the simulated car engine through the Raspberry pi to explore the importance of IoT in automobile.

#### Key takeaways 
1. Introduction to Motors
2. Comparison of Servos and DC motors
3. Step by Step programming of Raspberry Pi to control Servo motors.

#### Article quality
This article will include both the theory of DC and motors and the steps of how the servo motors can be controlled by a raspberry pi.

#### References
N/A

**Comment by Kayere** [comment]
Good topic @RuthAMare - Approved.
