### ISSUE TITLE
php freestyle function

### ISSUE THREAD

**Issue by tetieb** [section-engineering-education/engineering-education#4808]
**topic suggestion**
php freestyle functions
**introduction**
These are functions which allows a user to access and manipulate the filesystem.
They are part of the PHP core, therefore, need no installation. in this article we will  introduce to freestyle functions  in php and give various examples.

Key takeaways
-file functions examples
-Their examples
-Default filesystem functions
-Specification in different platforms

References
N/A

**Comment by Kayere** [comment]
Hello @tetieb, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
