### ISSUE TITLE
Understanding StackOverflowException in c#

### ISSUE THREAD

**Issue by davismunene** [section-engineering-education/engineering-education#4812]
### Topic Suggestion
StackOverflowException in c#.
#### Proposed title of article
Understanding StackOverflowException in C#.
#### Proposed article introduction
StackOverflowException is the exception that is raised when we are invoking too many methods nested inside together and every call generates a stack in memory on top of another, resulting in an unchecked recursion which is boundless and ends the program without issuing an error message. Recovery of the program is hard, and the exception cannot be caught by the try and catch blocks.
The StackOverflowException is thrown by MSIL(Microsoft Intermediate Language) instruction called OpCodes.LocalLoc instruction. There are several methods of StackOverflowException class like, StackOverflowException(string message),StackOverflowException( ) etc.
#### Key takeaways 
1. Working of C# StackOverflowException.
2. Examples of C# StackOverflowException.
3. How to avoid StackOverflowException in C#.
#### Article quality
This article goes beyond what has been provided in the official documentation, by  covering areas such as, working of C# stackoverflowexception, which I will take the reader through, also how one can avoid StackOverflowException in C#, and I hope that this article would be of great value to the entire engineering community.
#### References
N/A

**Comment by Kayere** [comment]
Hello @julie-techie, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
