### ISSUE TITLE
Evolution of C#

### ISSUE THREAD

**Issue by Graceshee** [section-engineering-education/engineering-education#4814]
#### Proposed title of article

Evolution of C#

#### Proposed article introduction

In recent years, C# has become one of the most dynamic languages. This language is open source, and it is primarily driven by a group of software engineers who have lately made a number of significant changes to improve the language and add functionality to deal with the difficulties of existing languages.
Generics, LINQ, Dynamics, and the async/await pattern are just a few of the main enhancements proposed for the language

#### Key takeaways 
Phase 1: The Java copy and the Visual Basic age (C# 1 - C# 2)
Phase 2: The new favorite (C#3 - C#4)
Phase 3: The innovator (C# 5 - C# 6)
Phase 4: The most complete (C# 7 - C# 8)
Phase 5: The minimalist (C#9 - C# 10)

#### References
N/A

**Comment by Kayere** [comment]
Hello @Graceshee , we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
