### ISSUE TITLE
Building Scalable Projects using the Multi-Module Architecture with Spring Boot and Maven

### ISSUE THREAD

**Issue by teevyne** [section-engineering-education/engineering-education#4818]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community members to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Building Scalable Projects using the Multi-Module Architecture with Spring Boot and Maven

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammar-checked.

A three-man organisation in 2019 grew to become a twelve-man team fourteen months later. The growth in team members was necessitated by the growth in the project. However, for them also came an increase in the cost of building, maintaining and scaling the project; they were running the microservices architecture.

In this tutorial, we will be going through the multi-module architecture - which is an drastic improvement on the monolith approach, yet offering as much possibilities of the microservices architecture, while evading the huge demands of microservices. We will be building a model of a hospital management system, taking into account some of the departments that make for a successful medical application, using the multi-module architecture, using Spring Boot and Maven.

#### Key takeaways 
- Why is the multi-module approach better than the monolith
- Advantages of multi-module over microservices architecture
- Gaining the benefits of microservices architecture from the multi-module architecture
- Passing dependencies and avoiding setup roadblocks in multi-module architecture

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

This article is unique as it helps address the issue of scalability and maintenance for growing projects. Much focus has been on Microservices being the only way to achieving smooth functionality. Not much attention has been put into multi-module approach as being as viable for growth, expansion, scalability and maintenance.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by Kayere** [comment]
Great topic @teevyne -Approved.
