### ISSUE TITLE
Building web application with Kotlin and Typescript

### ISSUE THREAD

**Issue by 07BLAIZER** [section-engineering-education/engineering-education#4821]
### Topic Suggestion
Building web application with Kotlin and Typescript

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Building web application with Kotlin and Typescript

#### Proposed article introduction
The context of the integration is a Web Application that uses a JVM on the server side (backend) and the Browser Application (frontend) is developed using a TypeScript based framework such as Angular or React (with the TypeScript option).
On the JVM side Kotlin integration is easy, with an appropriate build tool (i.e. Gradle and the Kotlin Multiplatform plugin), the Kotlin code is built into an easy to use jar module. This can be used just like any other JVM jar.
The JavaScript side is a little more tricky. The build tool will compile the Kotlin code and provide (by default) a jar that contains a UMD JavaScript module. The tricky part is integrating this into the Node.js based build for the browser application.

#### Key takeaways 
- The Build Scripts
- The information module
- The client module
- Unpacking the Kotlin modules
- Using Kotlin generated modules in TypeScript code
- TypeScript types for Kotlin code
- TypeScript declarations for third party libraries

#### Article quality
This article describes the problems encountered whilst integrating Kotlin generated modules with a TypeScript browser application and how to overcame them.

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Good topic. However, you seem to have copied the whole introduction from [this site](https://javascript.plainenglish.io/building-applications-with-kotlin-and-typescript-8a165e76252c).
