### ISSUE TITLE
[Networking} Smart Out-of-Band Management and End-to-end network resilience for a Resilient SD-WAN

### ISSUE THREAD

**Issue by jesmweni** [section-engineering-education/engineering-education#4822]
#### Proposed title of article
Smart Out-of-Band Management and End-to-end network resilience for a Resilient SD-WAN

#### Proposed article introduction
Now more than ever, the efficiency gained by SD-WAN will prove pivotal, but the ability to minimize downtime is equally important. Networks are becoming more geographically dispersed to support data-rich applications and Internet-connected devices. Additionally, as we are seeing with the current pandemic, unexpected issues can lead to new working conditions as well as network traffic surges of unprecedented duration and intensity.

This means networks must handle a lot of traffic economically and be resilient enough to withstand disruptions, security breaches, and behavioral changes in users. To handle this, organizations will need to implement a plan for end-to-end resilience into their overall enterprise networking ecosystem that will work in conjunction with SD-WAN to ensure efficiency and security.

Out-of-band management minimizes the need for truck rolls and mean time to recover (MTTR) from a disruption. And this dependability is available for a cost that is a small fraction of the savings when enterprises move from traditional to SD-WAN.

#### Key takeaways 

1. The importance of SD-WAN.
2. Why network resilience matters to businesses. 
3. How end-to-end network resilience ensures running of SD-WAN.
4. Out-of-Band management and SD-WAN. 

#### Article quality
This article covers additional topics beyond what is available on other blogs. 

#### References
N/A

**Comment by Kayere** [comment]
Hello @jesmweni, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
