### ISSUE TITLE
[Languages]  How to Add Pure CSS Wave Animations to Your Website

### ISSUE THREAD

**Issue by lin-chez** [section-engineering-education/engineering-education#4825]
#### Proposed title of the article
How to Add Pure CSS Wave Animations to Your Website

#### Proposed article introduction
 Adding animations can take you to the next level when you need to make your website seem more lively and attractive to your users.  The downfall of adding animations to a website using Javascript, as that is the widely used language in adding dynamicity to a website, is animations lead to the website loading slower especially when the developer fails to select an optimized library. However, there is a turnaround to such a problem and that is using CSS and HTML only.
#### Key takeaways
1. The reader will get to know what CSS animations are, and a few of their advantages over Javascript animations.
2. A demonstration and detailed explanation of how to use the CSS animation property.
3. A detailed tutorial on how to make pure CSS wave animations on your website. 
#### Article quality
The article does not only provide a simple tutorial it also adds a detailed explanation of the difference between animations in CSS and Javascript and also introduces the reader to CSS animations.

**Comment by Kayere** [comment]
Good topic @lin-chez - approved.
