### ISSUE TITLE
Electrocardiogram's(ECG's) QRS peak and heart rate detection using DWT using Matlab

### ISSUE THREAD

**Issue by collince777** [section-engineering-education/engineering-education#4829]
#### Proposed article introduction
The QRS combines three deflections (Q, R and S) seen on a typical ECG. It corresponds to the depolarization of the right and left ventricles of the human heart and contraction of the large ventricular muscles. In numerical and functional analysis, a discrete wavelet transform (DWT) is any wavelet transform for which the wavelets are discretely sampled. The discrete wavelet transform has many applications in science, engineering, mathematics and computer science. Most notably, it is used for signal coding to represent a discrete signal in a more redundant form, often as preconditioning for data compression.

The `sym4` wavelet resembles the QRS, which is good for QRS detection. This process can help to diagnose various heart diseases. In this tutorial, we will look at how to obtain the peak and rate of detection of these ECGs using the ECG database.  This method is widely applicable in the health area to manage the heart.

#### Key takeaways 
- Understanding QRS complex in ECG signal.
- Introduction to Symlet4 wavelet.
- Proposed DWT based algorithm for R-peak detection and Heart Rate estimation.
- Matlab code for R-peak detection and Heart Rate estimation.
- 
#### Article quality
This article uses a special wavelet type `sym4`. This wavelet is more effective for detections. Also it is into depth on the proposed DWT based QRS detection. It gives the reader a step by step ways of working this out.

**Comment by Kayere** [comment]
Good topic - Approved.
