### ISSUE TITLE
[Machine Learning] Machine Learning Image Classification with Javascript and Nyckel

### ISSUE THREAD

**Issue by vifabulous** [section-engineering-education/engineering-education#4833]
#### Introduction

Artificial intelligence has become the future of technology and everyone is trying to apply it in all areas. Artificially intelligent applications are a huge contribution to AI technology with the likes of trading bots and others.

This article shows how you can implement machine learning models in a web application to classify images. In this case, we will classify and identify the images of people that are wearing and those who are not wearing a mask.

#### Key takeaways 
- Make an image classification model
- Develop a simple web app
- Integrate the classification model into the application
- Test the application(AI-based)
- Evaluate the application performance.

#### Article quality
This article is intended to show how machine learning can be implemented in web applications, unlike other articles that only teach how to make machine learning models.
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
