### ISSUE TITLE
[Languages] A look at pair plotting in Python

### ISSUE THREAD

**Issue by MichaelmichaelW** [section-engineering-education/engineering-education#4834]
#### Proposed title of article
A look at pair plotting in Python

#### Proposed article introduction

In this article, we'll learn about Seaborn Pairplot using the Python programming language's pairplot() function. This feature can significantly aid in the analysis of exploratory data for machine learning applications. We'll also look at the syntax of the seaborn library's pairplot() method and run through various examples.

We will also get to understand some libraries such as seaborn and their implementation in real life situations. Apart from that, we will get to deeply understand what is pair plot function and also how it works.
#### Key takeaways 
1. Installing seaborn library
2. Seaborn pairplot function
3. Seaborn library in python
#### Article quality
Producing an original and unique content is what  I am focusing       
#### References
N/A

**Comment by lalith1403** [comment]
Thank you for the topic suggestion , however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
