### ISSUE TITLE
Mock  a Datasource for React using JSON Server

### ISSUE THREAD

**Issue by blacklihgt** [section-engineering-education/engineering-education#4836]
#### Proposed title of the article

Mock  a Datasource for React using JSON Server

#### Proposed article introduction

[Language] When building a React project, if it endpoints, developers end up needing some quick-to-use data sources. This provides test data to test the package if it works correctly.
Datasource mostly used may include DBMS systems such as MySQL, Postgres, SQL among many others. The problem with this approach is that during prototyping e.g. in Rapid Prototyping Approach if the application prototype is seemed to be not as expected it will be quickly discarded.
The extra setup and configurations will be both tedious and useless since they will be quickly discarded.

This produces a need to create a data source that can be quickly set up and discarded, yet it performs the same functionality as the DBMS.
It should also be small enough for fewer storage requirements and produce correct and accurate results as expected.
Such data sources problems can be solved by the use of the Json-Server library.

The Json-Server library is quick to install, configure, use and discard in a React application.
In this article, one will learn how to do the following on the package mentioned above in a React app.

#### KeyTakeaways

By the end, the following will be learned:

- What is the JSOn-Server library
- Set up the JSOn-Server library in a React application
- Connect the app to the library
- Use the library acts as a data source in place of a real DBMS
- Removing the dependency from the application and discarding the prototype

#### Pre-requisites

For the article, the following are required for easy article follow-up:

- A good React IDE or text editor set up on the machine
- A stable internet application
- React development environment already setup
- React development skills

#### Article quality

The article will be a span of broad content. It will begin with the basics before delving into more detailed but in-depth content on the library options.
This makes the user move from a beginner to expert level quickly.

#### References

- JSON Server [Documentations](https://www.npmjs.com/package/json-server)

#### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Good topic @blacklihgt - Approved. Please make sure you run your article through grammar checker tools such as Grammarly and Hemingway before submitting it for review.
