### ISSUE TITLE
[Languages] Create a Temperature converter using NextJs, Tailwind CSS and Strapi

### ISSUE THREAD

**Issue by vila-dev** [section-engineering-education/engineering-education#4837]
#### Introduction
With new inventions and innovations everyday, several disciplines can be brought together to create  a good application. Utilisation of NextJs, Tailwind and Strapi combination brings up the idea in this article.

This article will show you how to build a Temperature Converter with Next.js and Tailwind CSS as frontend and Strapi headless CMS as backend.

#### Key takeaways 
- Requirements/Prerequisites
- Scaffolding a Strapi project
- Seeding Strapi
- Scaffolding a Next Js project
- Building a temperature collection
- Compile the App
- Testing the App.

#### Article quality
I intend to simplify my article to be easy for developers at every skill level.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @vila-dev, how is your article going to be different from [this one](https://strapi.io/blog/create-a-temperature-converter-using-next-js-tailwind-css-and-strapi)?

**Comment by del-ui** [comment]
@Kayere The intention is to bring simplicity, I went through that article and from my point of view, a beginner in strapi can't really capture the content.....My article will be simplified and will give the reader flexibility in coding without errors.

Besides that, my converter app will be of a different interface design presentation.

**Comment by vila-dev** [comment]
@Kayere The intention is to bring simplicity, I went through that article and from my point of view, a beginner in strapi can't really capture the content.....My article will be simplified and will give the reader flexibility in coding without errors.

Besides that, my converter app will be of a different interface design presentation.

**Comment by Kayere** [comment]
Hello @vila-dev, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
