### ISSUE TITLE
Introduction to Big Data

### ISSUE THREAD

**Issue by EssyH** [section-engineering-education/engineering-education#4839]
#### Proposed title of article
Introduction to Big Data

#### Proposed article introduction
Data that is large and complicated cannot be processed using traditional methods. As a result, we employ big data to analyze, extract information, and gain a deeper understanding of the data. For large data, we examine volume, velocity, diversity, validity, and value. People's data collected through social media is an example of big data. Big data assists in the analysis of data trends in order to better understand people's and organizations' behavior. This facilitates efficient processing and, as a result, increased client satisfaction. Big data can contain organized or unstructured data, natural or processed data, and data that is time related.

#### Key takeaways 
what is Big data?
Main components of Big Data
Charasteristics of Big Data
Merits and Demerits of Big Data
Application of Big Data
Big Data Techniques

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Thank you for the topic suggestion @ , however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
