### ISSUE TITLE
JAVA: Introduction to Auto type promotion when overloading

### ISSUE THREAD

**Issue by root5086** [section-engineering-education/engineering-education#4840]
#### Proposed article introduction
Type promotion is done while doing method overloading in Java. When the datatype is not the same then we promote one datatype to another datatype. We cannot de-promote one datatype to another datatype. when a class has multiple methods with the same name but have different parameters, it is known as method overloading and is a very common scene in java programming.

In this article I will be discussing a brief introduction to auto type promotion and method overloading and their relationships, reasons or circumstances under which you may be required to apply automatic type promotion and the different types or ways of implementing type promotion. Finally I will go ahead and outline come illustratory code examples just to clearly explain the concept in question.

#### Key takeaways 
1.  The reader should be able to understand what Auto  type promotion is with respect to java programming.
2. The reader should be able to understand what method overloading is in java programming.
3. The reader should be able to understand the circumstances under which auto type promotion is imminent and how it id implemented.
4. The reader should be able to know the different types of Auto type promotions that can be implemented in java programming.
5. The reader will be able to understand  the rules required to achieve auto type promotion in java programming.

#### Article quality
This article will provide an in-depth tutorial on how automatic type promotion works and how to implement it in java. Unlike other articles, this article will show the rules required for auto type promotion to be achieved. In addition, it will show illustratory code examples clearly implementing the concept in question.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Sound like a good topic @root5086. Please make sure your article is unique and adds to what is available online.
