### ISSUE TITLE
How To: Use Office 2007 OCR Using C#

### ISSUE THREAD

**Issue by Walucy98** [section-engineering-education/engineering-education#4842]
####introduction
If there are any photos in a specified directory, the sample program looks for them and reads the text from them. It automatically stores the text from each image in a text file with the same name. It is capable of dealing with image-related issues or exceptions.
The OCR component is available for you to utilize if you have Office 2007 installed. Office 2007 is the only new dependent in your code. It may or may not be appropriate to need the installation of Office (2007 or 2003) in order for your code to operate. This option is excellent for you if your customer can ensure that the computers on which your code will execute have Office installed (2007 or 2003).

####key takeaways 
What is OCR?
What is Document Imaging?
Its Weakness and Strengths

####conclusion
In this tutorial the reader will be to learn what OCR and its purpose in data processing .He or She ill also be able to know what is Document Imaging and how it works.

**Comment by Kayere** [comment]
Hello @Walucy98 , we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
