### ISSUE TITLE
[python]Getting started with python plug-ins for GIMP

### ISSUE THREAD

**Issue by kmwangi-ken** [section-engineering-education/engineering-education#4843]
#### Proposed title of the article
Getting started with python plug-ins for GIMP
#### Proposed article introduction
GIMP is an open-source picture control program that many individuals use as a feasible option in contrast to a portion of the business contributions. GIMP handles convoluted components like layers and ways. GIMP upholds various diverse picture organizations and accompanies generally complex channels. GIMP has solid local area backing and inclusion, so it is generally simple to track down data concerning how to utilize or expand GIMP.
This article will turn out how to utilize GIMP-Python, which is an assortment of Python modules that permit you to program in Python to computerize errands in the GNU Image Manipulation Program (GIMP). These Python modules are basically coverings for the libgimp library. GIMP-Python isn't as old as Script-Fu expansions. To run scripts in Script-Fu, a module is utilized. The Python script becomes the dominant focal point in GIMP-Python and behaviors the work. You might run the GIMP-Python scripts straightforwardly from GIMP, or you can utilize GIMP's clump mode to begin it from the order line. 

#### Key takeaways 
- Enrolling your content
- Scripting the resize
- Running the resize module script
- Prearranging the picture change
- Running the refreshed module script
- Running both on a folder
#### Article quality
In this article, you will figure out how to foster Python code to computerize two unique cycles in GIMP: picture resizing and document saving. It will likewise help the student on the best way to use GIMP-python.
#### References
N/A

**Comment by lalith1403** [comment]
There are several grammatical errors. Topic approved. However, make sure PR is error free
