### ISSUE TITLE
[Languages]Build a static Next.js Markdown files blog with Typescript, MDX, Tailwind CSS, Next SEO, and Github Actions.

### ISSUE THREAD

**Issue by Rose-stack** [section-engineering-education/engineering-education#4844]
### Topic Suggestion
Enter topic suggestion here...

Build a static Next.js Markdown files blog with Typescript, MDX, Tailwind CSS, Next SEO, and Github Actions

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article

Build a static Next.js Markdown files blog with Typescript, MDX, Tailwind CSS, Next SEO, and Github Actions

#### Proposed article introduction

Next.js is a framework that is built on React. Next.js first came about because react is a client-side rendering library. everything changes on the client-side in the user's browser. Next.js brought in server-side rendering to react. First and foremost, it was for server-side rendering where you can render components on the server-side and show them to the user. Next.js further supports static sites generation. This means you can easily build both server-side rendering applications and static site-generated applications.

Building an application with Next.js is made powerful by some of the cool features that it has. This includes;

- Hot code reloading - when you're working on your application it'll reload quickly on the side you don't have to refresh the page.

- Static File Serving - it helps you serve any static files such as images, icons, `robots.txt`, `.html`, etc.

- Integrative with many different styling options. With Next.js styling options just come out of the box. You can use jsx CSS, less, sass, Tailwind, CSS modules, etc.

- Provides Typescript support out of the box. You don't have to install anything special to make Typescript work with Next.js. Typescript is a superset of JavaScript.  Typescript is a static type version of JavaScript. Next.js provides one-time `create-next-app` command that will help you bootstrap Typescript supported templates. You can also change your files `.js` names to `.ts` and it'll still work the same with environment variables.

#### Key takeaways 

In this guide, we are going to build a  static Next.js Markdown files blog with Typescript, MDX, Tailwind CSS, Next SEO, and Github Actions. We will discuss technologies and build an entire application from the scratch using this stack. Finally set up the whole stack to the CI/CD Github Actions.

#### Article quality

I have found articles that use Next.js to build markdown-supported blogs. However, this article will not only use Next.js but also combine other technologies that feature Next.js. We will use Typescript code to take advantage of that Typescript provides such as static typing and type checking. We will also use Tailwind CSS to style the whole application and make sure the built application has SEO features that Next.js provides. Finally set up the whole stack to the CI/CD Github Actions.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by Kayere** [comment]
Good topic @Rose-stack - Approved.
