### ISSUE TITLE
React Component  Instantiation

### ISSUE THREAD

**Issue by gatwirival** [section-engineering-education/engineering-education#4847]
#### Proposed title of article
React Components  Instantiation

#### Proposed article introduction
There are different types of react components: Functional Components,  Class Components, Pure Components and Higher-Order Components.React Component is a small,reusable chunk of code that is responsible  for one job which often involves rendering HTML.
JSX  stands for JavaScript XML. JSX  allows us to write HTML in React. JSX makes it easier to write and add HTML in React. JSX elements can  be either HTML like or component instances .JSX uses capitalization to distinguish between the two .That is the react specific reason why component class names must begin with capital letters.In JSX that first letter means its a component instance and not an HTML tag.In the case of the class component, React creates an instance of the class using the `new` keyword.

#### Key takeaways 
- What is component instantiation
- How to instantiate a component using react
- Difference between HTML like  and Component instances in JSX elements
- New keyword meaning and how it is used in react
- How React creates an instance of class using `new` keyword

#### Article quality
In this article the reader will learn about `new` keyword in react.js and how it is used.The reader will also learn how to instantiate react components ,what is react components and the  difference between HTML like  and Component instances in JSX elements

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Sounds like a good topic @1-creator - Approved.
