### ISSUE TITLE
Python:  Installing Kivy In Windows

### ISSUE THREAD

**Issue by 07munene** [section-engineering-education/engineering-education#4849]
INTRODUCTION
 Kivy is a free open source Python framework for developing mobile apps and other multi-touch application software with a Natural User Interface (NUI).
Using Kivy on your computer, you can create apps that run on desktop computers, iOS devices, android devices and any other touch enabled device supporting Tangible User Interface Objects (TUIO).

                KEY TAKEAWAYS

1. What is Kivy
2. Why use Kivy
3. Advantages of using Kivy applications
4. How to install Kivy on your computer

              ARTICLE QUALITY
This article will help the reader to successfully install Kivy on a windows PC. Each step will be well explained so that it's easy even for a first time Python user to install Kivy.

**Comment by lalith1403** [comment]
Thank you for the topic suggestion @ , however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
