### ISSUE TITLE
[Languages] Create a Java getter-setter generator using Python

### ISSUE THREAD

**Issue by munenekelvin** [section-engineering-education/engineering-education#4855]
#### Proposed title of the article
[Languages] Create a Java getter-setter generator using Python

#### Proposed article introduction
Getters and setters in Python are different from those in other object-oriented programming languages. Using getters and setters in object-oriented applications is mostly used to maintain data encapsulation. In contrast to most object-oriented languages, private variables in Python are not hidden fields. In Python, getters and setters are frequently used when:

 - validating logic around retrieving and setting a value, we utilize getters and setters.
 - preventing external users from having direct access to a class field, private variables cannot be accessed or edited directly.

#### Key takeaways 
By the end of this tutorial, the reader will have learned:
- what getters and setters are.
- how to get getters and setters behavior using normal functions.
- how to get getters and setters behavior using @property decorators.
- how to get getters and setters behavior using property() function.
- project algorithm.
- implementation of the algorithms.
- Conclusion

#### Article quality
In this article, I will cover the introduction to getters and setters in python programming and create a java getter-setter generator using python, unlike other blog sites which cover only the documentation part. Also, my content will be beginner-friendly and well-explained code snippets.

#### References
N/A

**Comment by Kayere** [comment]
@lalith1403 - could you please check this topic when you get a chance.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
