### ISSUE TITLE
Working with Ktor-Client: How to Build and Make HTTP Requests With Ktor-Client in Android

### ISSUE THREAD

**Issue by manmusa100** [section-engineering-education/engineering-education#4858]
#### Proposed title of article

Working with Ktor-Client: Build Simple REST API to Make HTTP Requests With Ktor-Client

#### Proposed article introduction

Ktor is a server-side framework that helps us build applications in kotlin. It is a modern framework which means it is an asynchronous framework built on top of kotlin coroutines. It is not only a back-end framework with kotlin but also a client, so a network library such as okhttp and Retrofit. We can use it to make network requests HTTP requests to an API to get the response back to an application. This will learn more about Ktor. We will set up Ktor-Client to make HTTP Requests And finally build a simple REST API with Ktor.

#### Key takeaways 

- Ktor architecture
- Ktor features
- Ktor vs Retrofit
- Build and Make HTTP Requests With Ktor-Client Android

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
What will you build @manmusa100?

**Comment by manmusa100** [comment]
@Kayere, a todo or a note app will get a got start to make everything beginner friendly.

**Comment by Kayere** [comment]
Good topic @manmusa100 - Approved.
