### ISSUE TITLE
Getting Started with Bash Shell Scripting

### ISSUE THREAD

**Issue by eunice-wanjiku** [section-engineering-education/engineering-education#4859]
### Proposed title of article

Getting Started with Bash Shell Scripting
### Introduction paragraph (2-3 paragraphs):

Bash is a widely available command line interface that is found in different operating systems. It is known to be a default command interpreter that is found on Mac OSX, and GNU or Linux systems. Shell is a macro processor that allows you to run commands interactively or non-interactively while scripting enables for the execution of instructions that would have to be executed individually interactively. This shows that you can be able to process information and retrieve data among other simple and complex operations.

Shell scripts are mainly for systems handling administration tasks such as system logs evaluation, and disk backups among others. They are also required in cases where the programs are complicated and used as installation scripts. The Bash shell script is a program written in a programming language, Bash.
### Key takeaways:

1. Basics of Bash shell script
2. What are Bash scripts
3. How Bash shell scripting works
4. How to run a bash shell script

### References:

N/A

**Comment by Kayere** [comment]
Hello @eunice-wanjiku, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
