### ISSUE TITLE
Catch block and type conversion in C++

### ISSUE THREAD

**Issue by Matsukatm** [section-engineering-education/engineering-education#4862]
### Topic Suggestion
Catch block and type conversion in C++

#### Proposed title of the article
Catch block and type conversion in C++

#### Proposed article introduction
Exceptions can be thrown of any type in C++, however, it is generally advised to use std::exception-derived exceptions. It is possible to catch a C++ exception by using a catch handler that is capable of handling any sort of exception.
To catch an exception of this type, handlers must take base classes (or references to base classes) of the exception's type, as well as base classes (or references).
A try block's catch handlers occur in a specific order, thus the order in which they appear is important. The handler for a base class should not be placed before the handler for a derived class, as an example. All further catch handlers are ignored after a match has been found. Therefore, the handler for an ellipsis catch must be the final handler for the try block.

#### Key takeaways 
- Try blocks
- Catch handlers
- Types of catch handlers

### Conclusion
The ability to use try blocks effectively. Types of catch handlers and catch handlers in general. All of the details and explanations are provided in a straightforward and concise manner, with no ambiguity or ambiguity.

**Comment by Kayere** [comment]
Hello @Matsukatm, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
