### ISSUE TITLE
[Languages] Introduction to Java Server Pages (JSP)

### ISSUE THREAD

**Issue by Katul1234** [section-engineering-education/engineering-education#4863]
#### Proposed title of article
Introduction to Java Server Pages (JSP)

#### Proposed article introduction
JSP is a programming language that is similar to Servlet technology in terms of utility and flexibility for creating web applications. Servlets are more difficult to write than JSP pages, which makes JSP pages more polar. A Servlet inserts HTML code into Java code, whereas a JSP uses JSP tags to insert Java code into HTML.

JSP allows us to create HTML pages with tags that we can use to include powerful Java programs. A web designer can design and update JSP pages to provide the presentation layer, while a java developer can write server side complicated computational code without worrying about the web design. Furthermore, both layers can easily communicate via HTTP queries.

#### Key takeaways 
1. Introduction to JSP
2. Advantages of JSP 
3. JSP over Servlet
4. The JSP Pages' Lifecycle.
5. simple JSP Page
6. JSP directory structure
#### Article quality
I looked through some of the published articles in Section Engineering and discovered that the JSP part has yet to be tweaked. The Core Java section and the Servlet section have been mentioned in the majority of the articles. I'll make certain that what I go over is original and hasn't been published on the Section Engineering website.
#### References
N/A

**Comment by Kayere** [comment]
Hello @Katul1234, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
