### ISSUE TITLE
[Languages] Scripting Elements in JSP

### ISSUE THREAD

**Issue by Kipkopus** [section-engineering-education/engineering-education#4867]
#### Proposed title of article
Scripting Elements in JSP

#### Proposed article introduction
The opening "<%" tag and the closing "% >" tag are used to write JSP scripting elements. JSP Tags, specifically Directive, Declaration, Scriptlet, and Expression Tags, will be used to embed Java code inside an HTML page in this case.

Everything inside the aforementioned tags is considered Java code, and the JSP program will be converted to Servlet code by the compiler during execusion. Other text on the JSP page outside of the JSP tags, on the other hand, is treated as HTML code or plain text.
In this article, I'll go over all of the JSP elements and what they do in detail.

#### Key takeaways 
1. Introduction
2. Comment in JSP
3. Directive Tag
4. Declaration Tag
5. Scriptlet tag
6. Expression Tag
#### Article quality
Contributors of the Engineering Section.io does not yet mention JSP. To make my content more useful to back-end developers who like to use Java, I'll go deeper and deeper into this article. I'll make sure that what I'm teaching is different from the Java and Servlet articles on Section.io, and I'll try to incorporate more information that isn't covered in the other blocks. Thank you very much.

#### References
N/A

**Comment by Kayere** [comment]
Hello @Kipkopus, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
