### ISSUE TITLE
[API]Flutter Authentication Using Flask API

### ISSUE THREAD

**Issue by wobin1** [section-engineering-education/engineering-education#4869]
#### Introduction
Softwares or applications are mostly made to solve problems for a particular set of people. 
Most times software or applications hold data that is not supposed to be accessible to everyone. 
this has made Authentication a core aspect of software or application development.

Flutter is a UI toolkit created by google, it is used to build cross-platform mobile applications for Android and IOS, and desktop applications for Windows, Mac, and Linux. UIs built with Flutter always depend on backend technologies for functionalities like authentication, one of these backend technologies is Flask.
Flask is a micro web framework written in python.

Authentication is the process of proving if a user trying to access a system has the permission to do so. It verifies users by comparing credentials provided to those on a file in a database of the 
authorized user’s information on a local operating system or within an authentication server.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

#### Key takeaways 
After reading this article the reader will;
- Learn to build a login and register form
- how to make a post and a get request using flutter
- Understand how authentication works.

#### Article quality
The article will explain in-depth how API works with frontends applications, and how developers can communicate or make a request to backend applications.

**Comment by Kayere** [comment]
Sounds like a helpful topic @wobin1 - Approved.
