### ISSUE TITLE
Graphing Data with Chart.js - Fetching Data from APIs.

### ISSUE THREAD

**Issue by abimbolataofeek** [section-engineering-education/engineering-education#4872]
#### Graphing Data with Chart.js - Fetching Data from APIs.
Your title should be descriptive of the article/tutorial. Be Specific. 

#### Introduction
Chart.js is a free open-source JavaScript library for data visualization, which supports 8 chart types: bar, line, area, pie (doughnut), bubble, radar, polar, and scatter. 

Simple, clean, and engaging HTML5 based JavaScript charts. Chart.js is an easy way to include animated, interactive graphs on your website for free. 

#### Key takeaways 
At the end of this tutorial the reader would be able to:
1. Understand what Chart.js Is
2. Installation and configuration of Chart.js
3. Visualize and render data using Chart.js
4. Draw Chart using your own data
5. Select and change the type of chart 

#### Article quality
I will show step by step how to render and visualize your data using chart.js

#### References
https://www.chartjs.org/

**Comment by Kayere** [comment]
Hello @abimbolataofeek, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
