### ISSUE TITLE
[Machine Learning]A practical guide of Label Encoding vs One-Hot Encoding

### ISSUE THREAD

**Issue by Donel254** [section-engineering-education/engineering-education#4880]
#### Proposed title of article
A practical guide of Label Encoding vs One-Hot Encoding

#### Proposed article introduction: [Machine Learning]
The datasets we use to train machine learning models have columns that come in various formats. Some contain numerical data, dates, categorical data, etc. Categorized data is very common to find in datasets, and the categories can be very critical in the training of the desired model.

Some models might go as far as to require the categorical column as the target(Y) for the model. Considering that categories are mostly represented in  object format i.e. string, this becomes a problem since machine learning algorithms deal with numerical data only. This is where `Categorical encoding` comes in. 

Using categorical encoding we are able to encode the categorical data into numerical values that can be understood by the learning algorithms. Two of the most common categorical encoding techniques are:
1. Label Encoding
2. One-Hot encoding

#### Key takeaways 
1. Introduction to dataset encoding in machine learning.
2. Why you need encoding.
3. Different approaches of encoding techniques.
4. Implementing One-hot-encoding
5. Implementing Label Encoding
6. When to use one over the other

#### References
N/A

**Comment by lalith1403** [comment]
What are the different encoding schemes covered?

**Comment by Donel254** [comment]
One hot encoding and Label Encoding(Ordinal). I'll cover both then compare them.

**Comment by lalith1403** [comment]
These have been widely covered on the net. We are looking for original content that helps developers. I will be closing this issue for now. Feel free to suggest a new suggestion. Thank you.
