### ISSUE TITLE
How to use SSH to connect to a remote server in Linux 

### ISSUE THREAD

**Issue by Wakanyaben254** [section-engineering-education/engineering-education#4882]
### Topic Suggestion

[networking]how to use SSH to connect to a remote server in Linux 

#### Proposed title of article
How to use SSH to connect to a remote server in Linux 
#### Proposed article introduction
Secure Socket Shell is a protocol which allows you to connect securely to a remote computer or a server by using a text-based interface.When a secure SSH connection is established, a shell session will be started, and you will be able to manipulate the server by typing commands within the client on your local computer.Accessing machines remotely became a necessity a long time ago and we can barely imagine how it would be if we couldn’t control computers from remote locations.This protocols use the client and server applications to establish a remote connection. These tools allow you to gain access and remotely manage other computers, transfer files, and do virtually anything you can do while physically sitting in front of the machine

#### Key takeaways 
1.What is SSH?
2.How Does SSH Work?
3.How to Enable an SSH Connection
4.How to Install an OpenSSH Client
5.How to Install an OpenSSH Server
6.How to Connect via SSH

#### Article quality

This article will take the reader through a step by step process in connecting to a remote server via ssh,  in both old and latest linux version as opposed to other articles that focus on linux older version only

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @Wakanyaben254, how is your article going to be different from [this one](https://phoenixnap.com/kb/ssh-to-connect-to-remote-server-linux-or-windows)?

**Comment by Wakanyaben254** [comment]
Hey @ kayere my article will explore the basics fundamentals of SSH, give detailed content about it  with a simple and understandable language guiding readers on how to use SSH to connect to a remote server remotely

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

**Comment by WanjaMIKE** [comment]
https://www.google.com/search?q=How+to+use+SSH+to+connect+to+a+remote+server+in+Linux&sourceid=chrome&ie=UTF-8
