### ISSUE TITLE
[Languages] Coroutine in Python

### ISSUE THREAD

**Issue by FranciscaNg** [section-engineering-education/engineering-education#4890]
### Topic Suggestion
Coroutine in Python
#### Proposed article introduction
Functions, often known as subroutines, procedures, sub-processes, etc., are well-known to everyone. The term "function" refers to a set of instructions that are used to accomplish a certain activity. A complex function's logic is broken down into a series of separate, self-contained phases, which are known as helper functions or subroutines.

Python subroutines are called by the main function, which coordinates the use of these subroutines. Single point of entry for subroutines Coroutines are subroutines in general form. A process can deliberately give up control to allow for numerous apps to execute at the same time via cooperative multitasking.
#### Key takeaways 
- The difference between coroutine and subroutine
- Coroutine Vs Thread
- Python Coroutine
- Execution of Coroutine

#### Article quality
 The articles in other blogs don't go into great detail about Coroutine in Python; they just cover the basics. Introduction, Execution, Closing, and Chaining Coroutines for Pipelines will all be covered in detail in this article. As a result, the code snippets and content explanations will be easy to understand, making them suitable for novices, intermediates, and experts.
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by munenekelvin** [comment]
hello @lalith1403 and @FranciscaNg  this article is already covered by #4902
