### ISSUE TITLE
NEW ERA AUTHENTICATION METHODS

### ISSUE THREAD

**Issue by domiwanja** [section-engineering-education/engineering-education#4895]
### Topic Suggestion
New era authentication methods

#### Proposed article introduction
These are new ways of authentication that have replaced the traditional authentication methods. A traditional method such as the use of a username and one-time password (OTP). These old methods are secure but cumbersome for those who lack sharp memory and instead focus on "remember me" pop up.

Multi-factor authentication is continually evolving. Passwordless authentication knocks out passwords as a form of authentication. The following are some of the ways it can be achieved: Voice recognition through text-dependent and text-independent verification. Face recognition in browsers through face-api.js. Biometrics is a good example of this new augmented way of authentication too.

#### Key takeaways 
What is augmented authentication?
Explanations of different ways of augmented authentication while giving examples
Pros and cons of using augmented authentication methods
Discuss about-face-api.js
#### Article quality
This article will explain in-depth authentication methods in this era, unlike other articles which are shallow. The published articles haven't covered the face-api-js in connection with face recognition and face verification.

#### References
N|A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
God topic @domiwanja - Approved. Please make sure your topic is unique and adds value to what is available online.
