### ISSUE TITLE
Getting Started with Support Vector Regression in Machine Learning

### ISSUE THREAD

**Issue by BejaminNaibei** [section-engineering-education/engineering-education#4897]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Article introduction
Rooted in Vapnik-Chervonenkis (VC) theory, support vector machines (SVMs) are well-positioned to generalize yet-to-be-seen data. When dealing with regression problems, the SVM concepts can be generalized to become applicable in such situations. As in classification with SVM, support vector regression (SVR) is characterized by the use of the sparse solution, kernels, and VC control of the margin and the number of support vectors. Although not as popular as SVM, SVR has been proven to be an effective tool in real-value function estimation. As a supervised-learning approach, SVR trains using asymmetrical loss function, which equally penalizes high and low misestimates.

Using Vapnik’s *e -insensitive* approach, a flexible tube of the minimal radius is formed symmetrically around the estimated function, such that the absolute errors value less than a certain threshold *e* are ignored both above and below the optimal hyperplane. However, points outside the tube are penalized, but those within the tube, either above or below the function, are not. One of the importance of SVR is that its computational complexity does not depend on the dimensionality of the input space. Additionally, it has excellent generalization capability with high prediction accuracy.

This article will be designed to provide a profound overview of SVR. Subsections we shall spend our time on includes its concepts, mathematical model and graphical representation. Later after providing a deep intuition for this model, we shall implement this model in python. Our implementation will ensure each bit of the code is clearly explained.

#### Key takeaways 
By the end of the session:
1. The reader will know the difference between SVM and SVR.
2. The reader will have learned all the essential concepts needed to get started with SVR.
3. The reader will know in what kind of problem statement they should apply the SVR model.
4. Finally, the reader will be able to implement this model in python by themselves.

#### Article quality
As our study will be under the SVR concepts, mathematical model and graphical representation, we shall dive deeper and make every bit under the above areas of consideration as clear as possible. Thus this material will deliver clarity of the concept and a well-explained implementation.
#### References
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @lalith1403, could you please check this topic when you get a chance?

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
