### ISSUE TITLE
[Languages]Callable and Future in Java

### ISSUE THREAD

**Issue by jgesare** [section-engineering-education/engineering-education#4899]
### Topic Suggestion
Callable and Future in Java

#### Proposed article introduction
Unlike the runnable interface, the callable object can deliver the result of a computation that was performed by a thread instead of just running the thread itself. Monitoring the progress of a thread's task is made possible by the Future object that the Callable object returns. Check the status of a Callable and then receive its outcome from a future object whenever a thread completes. It also has a built-in timeout feature.

To create a thread, you may either extend the Thread class or create a thread with a Runnable instance. When a thread ends, we can't have it produce a result, which is an important component of Runnable. Java's Callable interface is used to implement this capability.

#### Key takeaways 
- Callable vs Runnable
- Future
- Using ExecutorService to carry out activities and get the outcome using Future.
- Cancelling a Future
- Adding Timeouts
#### Article quality
Java's Callable and Future aren't explained in great detail in other blogs, but they do cover the basics. Using ExecutorService to carry out tasks and receive the results using a Future, canceling the Future, and adding timeouts will all be explained in this article in great detail. As a result, novices, intermediates, and professionals alike will be able to follow the code snippets and content descriptions due to their simplicity.
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @jgesare, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
