### ISSUE TITLE
[Machine Learning] How machine learning is revolutionizing sports industry

### ISSUE THREAD

**Issue by Njeri44** [section-engineering-education/engineering-education#4900]
#### Proposed title of article
[Machine Learning] How machine learning is revolutionizing sports industry

#### Proposed article introduction
Over the past decade, there have been significant changes in sports due to the integration of technology in the industry
Machine learning is one of the most important branches of artificial intelligence, which could be very significant in the sports industry
The purpose of the article is to assess the role that machine plays in making substantial changes in sports industry

#### Key takeaways 
1. How machine learning works in the sports industry
2. Why should one use machine learning to other technologies in sports
3. For example, how machine learning is used in weight training

#### Article quality
The article is unique since it provides more in-depth information and handy tip on using machine learning in sports industry
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Not applicable

**Comment by lalith1403** [comment]
Thank you for the topic suggestion , however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
