### ISSUE TITLE
[Languages]Java Locks and Atomic Variables for Thread Synchronization

### ISSUE THREAD

**Issue by Dianapeter** [section-engineering-education/engineering-education#4901]
### Topic Suggestion
Java Locks and Atomic Variables for thread synchronization

#### Proposed article introduction
To get access to an object's member fields, Java's synchronized keyword uses the object's intrinsic lock.

Java's Concurrency API provides a variety of Locking classes that can be used instead of an intrinsic lock via the synchronized keyword for more precise control over the locking mechanism.

In this lesson, we'll learn how to synchronize access to shared variables using these Java Locking classes.

Finally, we'll take a look at the Java concurrency API's different Atomic classes for thread synchronization.

#### Key takeaways 
- Atomic Variables
- Locks
- How to use Locks and Atomic Variables for thread synchronization

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @Dianapeter, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
