### ISSUE TITLE
[Languages] Thread synchronization and concurrency concerns in Java

### ISSUE THREAD

**Issue by SusanKiptoo** [section-engineering-education/engineering-education#4903]
### Topic Suggestion
Thread synchronization and concurrency concerns in Java

#### Proposed article introduction
There are several hazards associated with concurrent/multithreaded programming, and we'll learn how to avoid them in this tutorial.

To maximize the system's resources, multithreading is a highly powerful tool, but we must be careful when reading and writing data shared by different threads.

#### Key takeaways 
- Thread Interference Errors (Race Conditions)
- Memory Consistency Errors
- Memory Consistency Errors
- Volatile Keyword
#### Article quality
In this lesson, we'll look at how synchronized methods and blocks can help us avoid common concurrency problems in multi-threaded applications. Please keep in mind that a synchronization is a great tool, but excessive synchronization can lead to issues like deadlock and hunger.
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @SusanKiptoo, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
