### ISSUE TITLE
IoT-Based Smart Farming 

### ISSUE THREAD

**Issue by Greggmun** [section-engineering-education/engineering-education#4905]
#### Proposed title of article
IoT-Based Smart Farming 

#### Proposed article introduction
IoT is one of the most revolutionary technologies in modern wireless communications. The basic concept is the interaction between a variety of physical things or objects using specific addressing schemes to being connected to the Internet. 

In an agricultural environment, IoT devices provide useful information on a wide range of physical parameters to enhance cultivation practices. The role of Wireless Sensor Networks (WSNs) in IoT technology is of paramount importance since the vast majority of IoT applications in various markets is based on wireless data transmission.

#### Key takeaways 
IOT-based drones
Remote sensing
Computer imaging
Robotics 
#### Article quality
Most articles explaining the use of IoT in agriculture are non-technical. This article will focus on the technical aspects of the use of IoT in agriculture. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by Kayere** [comment]
Hello @Greggmun, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
