### ISSUE TITLE
Socket Programming in C#

### ISSUE THREAD

**Issue by Nicholas-Obare** [section-engineering-education/engineering-education#4907]
#### Proposed title of article
Socket Programming in C#

#### Proposed article introduction
In this article, First, we'll look at how to build a C# socket and set up a listener server node that begins listening for messages sent to it through the IP and protocol specified. We'll also show how to use Sockets to develop a client application that sends messages to a listening server and reads them. 

Sockets are used in computer networks to create a connection between two or more machines and to transport data from one to the other.

#### Key takeaways 
What is socket programming?
How to create a socket
setup a listener server node 
create a client application
Test and Run  the two projects

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A

**Comment by Kayere** [comment]
Hello @Nicholas-Obare, how is your topic going to be different from [this one](https://www.c-sharpcorner.com/article/socket-programming-in-C-Sharp/)?

**Comment by morwabe1234** [comment]
Hello@Kayere,my topic will be more detailed with the good and clear examples .

**Comment by WanjaMIKE** [comment]
I think this topic is over saturated. Feel free to suggest another area. Thanks
