### ISSUE TITLE
Implementing authentication and authorization in Server-Side Blazor

### ISSUE THREAD

**Issue by Mercycar** [section-engineering-education/engineering-education#4909]
### Topic Suggestion
Implementing authentication and authorization in Server-Side Blazor

### Writing sample(s): 
https://www.section.io/engineering-education/razor-pages-web-app-tutorial/

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

#### Proposed article introduction
Today, there are many websites providing important services to society. In order to do this process, they need to protect their websites from unethical users. This leads to the introduction of authentication and authorization in their websites.

 Authentication is the process or action of verifying the identity of a user or process. User authentication for each device ensures that the individual using the device is recognized by the company and authorization is giving users permission to access a service.

In this tutorial, I shall be looking at how authentication and authorization is implemented on the three basic different layers. This layers include;
- The user interface(UI) layer: This layer enables users to register, log in, recover passwords and manage user profiles.
- Functionality layer: This layer is used to authenticate and authorize user information.
- Object Relation Mapping/ Data base: This layer stores, operates and updates user information.

#### Key takeaways 
After going through this tutorial, the reader will have a better understanding of:
- User interface authentication and its functions.
- Functionality layer and how its authentication is implemented
- DB/ORM layer and its functions and how authorization is done at this layer.

#### Article quality
The uniqueness of this article is that I will be looking at each of the three layers of authentication in depth providing each bit of information that the reader needs to know. Also I shall be creating a project for demonstration of how the three layers work.

#### References
N/A

**Comment by Kayere** [comment]
Good topic @Mercycar - Approved.
