### ISSUE TITLE
[Language]Java ExecutorService and Thread Pools

### ISSUE THREAD

**Issue by FranciscaNg** [section-engineering-education/engineering-education#4912]
#### Proposed title of article
Java ExecutorService and Thread Pools
#### Proposed article introduction
We'll learn how to use executors and thread pools to manage our application's threads in this lesson.

This becomes a problem if your program needs to run 20 or 30 threads at once, making it difficult to start one at a time.
There will be hundreds, if not thousands, of threads running in huge multi-threaded programs at the same time. Separating thread creation and management from application logic makes sense in this case.
#### Key takeaways 
- Executors Framework
- ExecutorService
- Shutting down the ExecutorService
- Thread Pool

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @FranciscaNg, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
