### ISSUE TITLE
[Machine Learning] Pathways: A General Purpose Intelligence System

### ISSUE THREAD

**Issue by monicada** [section-engineering-education/engineering-education#4915]
### Topic Suggestion
[Machine Learning] Pathways: A General Purpose Intelligence System

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Pathways: A General Purpose Intelligence System

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Today's artificial intelligence models are trained to accomplish only a single task. However, Google's new Pathways model aims to perform different tasks in an effective manner. Google aims to build one model that can perform different tasks; a general purpose intelligence system. The model they aim to build is similar to the way our brain actually works. Instead of having a single neural network that you can train, you have this giant neural network that can do all the tasks at once. It is a relatively new model released by Google on 28th October 2021. This article will discuss this new model.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

In this article, a reader will get to understand the Pathways model, a promising new approach to AI, how it's actually intended to work, and what such a model would mean to the AI industry.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Pathways is a relatively new model released by Google on 28th October 2021 . So, not a lot of articles exist out there on the subject. This makes this article unique and I believe it will benefit most of our readers.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [Introducing Pathways: A next-generation AI architecture](https://blog.google/technology/ai/introducing-pathways-next-generation-ai-architecture/)

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
