### ISSUE TITLE
How to implement Linear Time Invariant(LTI) systems analyzer using Matlab Graphical User Interface(GUI)

### ISSUE THREAD

**Issue by florenceakinyi** [section-engineering-education/engineering-education#4916]
#### Proposed title of article
How to implement Linear Time Invariant(LTI) systems analyzer using Matlab Graphical User Interface(GUI)

#### Proposed article introduction
LTI are systems that give output from a given input. In this system, the input is known as the excitation, while the output is the response. These systems follow linearity and time invariance. Linear systems are those that follow homogeneity and superposition principles. If we have an input x(t) that gives an output y(t), that system is called homogeneity. Also, if we have an output y_1(t) for input x_1(t) and y_2(t) for input x_2(t), this is the principle of superposition. If both are combined, the input ax_1(t) + ax_2(t) gives a corresponding output as ay_1(t) + ay_2(t).

A graphical user interface is how the user interacts with the electronic devices through visual indicators. Matlab is software that allows the implementation of various systems using a user interface. In this tutorial, we will see how to implement GUI using Matlab to analyze any LTI systems. The GUI can show the various time response curves such as tap response, impulse response, and ramp response. It can also show you very stability curves such as root locus, bode plots, log magnitude curve and pole-zero plot. We will see how to do all these using GUI in Matlab.

#### Key takeaways 
- Introduction to LTI systems.
- Various(time domain/Frequency domain) analysis of LTI systems.
- Creating Matlab GUI for LTI systems analyzer uisng GUIDE.
- Matlab code of Call Back function for various GUI components.
- Program simulation.

#### Article quality
This articles takes the learner deep on how to use the GUIDE for complex systems. I believe that after handling a complex system such as LTI systems uisng GUIDE, then there is a high probability that you could solve a lot of GUIDE problems.
#### References
N/A

**Comment by Kayere** [comment]
Good topic @florenceakinyi - Approved.
