### ISSUE TITLE
[Languages] Understanding Collections in python

### ISSUE THREAD

**Issue by leah-wangari** [section-engineering-education/engineering-education#4919]
#### Proposed title of the article
[Languages] Understanding Collections in python

#### Proposed article introduction
A collection is a programming class that represents a group of related data type elements as a single entity. These unit classes are used to organize and manage things that are linked. A collection has a data structure below it that allows for efficient data handling and storage.

Different kinds of containers are available in Python's collection module. A Container is a kind of object that may be used to hold several objects and offer a mechanism to access and iterate over them. Tuple, List, Dictionary, and other built-in containers are examples. 

The various containers given by the collections module will be discussed in this article.

#### Key takeaways 
By the end of this article, the reader will have understood:
- What are collections in python
- The collections data types in the Python
- The Collection Data Structures
  1. namedtuple( )
  2. OrderedDict
  3. defaultdict
  4. ChainMap
  5. Counter
  6. deque
  7. UserList
  8. UserDict
- Data Processing using Python Collections
-  Conclusion

#### Article quality
This article goes beyond what as been covered in official documentations, by covering areas such as:
data processing using python collections, The collection data structures, and collection data types.
Which are not covered in the official documents. Furthermore, I will also use simpler language for users to understand the article without strain. I also hope that my article will add value to the entire engineering community.

#### References
N/A

**Comment by Kayere** [comment]
Hello @lalith1403 - could you please check this topic when you get a chance?

**Comment by lalith1403** [comment]
These are well documented in Python’s documentation. Can you explain how your article will stand out?

**Comment by leah-wangari** [comment]
Hello @lalith1403, In this advanced python 06 tutorial, I will let the leader learn about the collections modules, how these modules implement special container datatypes, and provides alternatives with some additional functionality compared to the general built-in containers. Also, I will be precise with my content and code snippets.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by leah-wangari** [comment]
can anyone open this for me please
