### ISSUE TITLE
Building web application with Kotlin and Typescript

### ISSUE THREAD

**Issue by 07BLAIZER** [section-engineering-education/engineering-education#4920]
### Topic Suggestion
Building web application with Kotlin and Typescript

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Building web application with Kotlin and Typescript

#### Proposed article introduction
The integration occurs in the context of а web application (bасkend) that runs on а JVM and а browser application (frоntend) that еmрlоys а TypeScriрt-bаsed frаmewоrk like ngulаr оr Reасt (with the TypеScriрtiоn). On the JVM side, Kоtlin integration is simple, and with the right build tool (i.e., Grаdle and the Kоtlin Multiрlаtfоrm Plugin), Kоtlin code is built into a simple jаr mоdule. This JVM JAR can be used just like any other JVM JAR. The JаvаSсriрt side of things is a little more difficult. The build tool will compile the Kotlin code and generate a jаr containing the UMD JаvаSсriрt mоdule (by default). The interesting part is incorporating this into the node. JS-based integrated browser application programming interface

#### Key takeaways 
- The Build Scripts
- The information module
- The client module
- Unpacking the Kotlin modules
- Using Kotlin generated modules in TypeScript code
- TypeScript types for Kotlin code
- TypeScript declarations for third party libraries

#### Article quality
This article describes the problems encountered whilst integrating Kotlin generated modules with a TypeScript browser application and how to overcome them.

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Good topic @07BLAIZER - Approved.
