### ISSUE TITLE
[Languages] Understanding when to use JSP and when to use servlet

### ISSUE THREAD

**Issue by Katul1234** [section-engineering-education/engineering-education#4923]
#### Proposed title of article
Understanding when to use JSP and when to use servlet

#### Proposed article introduction
A JSP is compiled into a servlet the first time it is run. That is to say, there isn't much of a difference between them in terms of runtime. Most people, on the other hand, have a habit of using servlets for controllers and JSPs for views. Because controllers are merely java classes, all IDEs may provide full tool support (code completion, etc.). In comparison to JSPs, this results in higher quality and shorter development timeframes. Some more powerful IDEs (IntelliJ IDEA comes to mind) provide excellent JSP support, obviating the need for that argument.
I'll focus on when to use each of the aforementioned two technologies, their important differences and similarities, and how compilers convert JSP code to servlet code during compilation in this article.

#### Key takeaways 
1. Introduction

2. When to Use JSP

3. Illustrating with a simple program:

4. When Should You Use a Servlet?

5. Using a simple code as an example,

6. JSP and Servlet Similarities and Dissimilarities

7. How compilers convert code written in JSP to a corresponding servlet code

8. Using an Example from the NetBeans IDE to Demonstrate

9. Conclusion

#### Article quality
Most blocks have yet to explain to readers whether to use JSP and when to use Servlet, and the Majorly JSP Concept has yet to be enmeshed in Section Engineering.

In this essay, I'd want to introduce both novices and experts working with Java as a back-end programming language so that they may understand when to use each of the two technologies(Servlet and JSP).

#### References
N/A

**Comment by Kayere** [comment]
Goot topic @Katul1234 - Approved. Please make sure your topic is unique and adds value to what is available online.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by hectorkambow** [comment]
👀
