### ISSUE TITLE
FILESTREAM CLASS IN C#

### ISSUE THREAD

**Issue by duncandegwa** [section-engineering-education/engineering-education#4924]
### Proposed title of article
FILESTREAM CLASS IN C#

### Introduction paragraph (2-3 paragraphs)
`FileStream` Class is used to perform the basic operation of reading and writing operating system files. `FileStream` class helps in reading from, writing and closing files. In this tutorial, we will discuss all the various operations that you can do with the filestream class in c# .

### Key takeaways: 

1. How to use filestream class in c#
2. File access and file modes
3. Create a blank .txt file using filestream
4. Open csharpfile.txt and write some text in it
5. Read data from csharpfile.txt file

### References: 
N\A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @duncandegwa, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
