### ISSUE TITLE
[Languages]Swift memory management and optimization using ARC

### ISSUE THREAD

**Issue by sumbaelvis** [section-engineering-education/engineering-education#4926]
### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.
[Spring Boot Webflux](https://www.section.io/engineering-education/spring-webflux/)

#### Proposed title of article
Swift memory management and optimization using ARC

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Memory management functions and its usage are handled in Swift language through Automatic reference counting (ARC). ARC is used to initialize and deinitialize the system resources thereby releasing memory spaces used by the class instances when the instances are no longer needed. ARC keeps track of information about the relationships between our code instances to manage the memory resources effectively.

- ARC allocates a chunk of memory to store the information each and every time when a new class instance is created by init().
- When the class instance is no longer needed it automatically frees the memory space by deinit() for further class instance storage and retrieval.
- ARC keeps in track of currently referring class instances properties, constants and variables so that deinit() is applied only to those unused instances.
- ARC maintains a 'strong reference' to those class instance property, constants and variables to restrict deallocation when the class instance is currently in use.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.
1. Swift memory management.
2. Handling IOS memory leaks.
3. IOS performance optimization.

#### Article quality
The article explains in details how to manage memory in Swift applications, none of the articles already published explains how to manage memory in an IOS and Macos applications using ARC. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

**Comment by Kayere** [comment]
Hello @sumbaelvis - You seem to have copied the whole introduction from [this article](https://www.tutorialspoint.com/swift/swift_arc_overview.htm). Please make sure you submit topic suggestions that are unique.
