### ISSUE TITLE
How to classify ECG signals using continuous wavelet transform and AlexNet via transfer learning

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#4929]
### Topic Suggestion
Enter topic suggestion here...

#### Introduction
ECG signals represent the heart's electrical activity observed from a strategic point of the human body, characterized by Quasi-periodic voltage. AlexNet is a convolutional neural network that has eight different layers. This method I commonly used in the science sector and for image studies. Transfer learning (TL) is a research problem in machine learning that focuses on storing knowledge gained while solving one problem and applying it to a different but related problem. For example, knowledge gained while learning to recognize cars could use when trying to recognize trucks.

This tutorial will classify the ECG signals using pre-trained deep CNN(AlexNet) via transfer learning in Matlab. For this purpose, we utilized the strength of a container wavelet transforms to represent the 1-D ECG signals as images. It is to make it possible to be used as an input in the AlexNet. 

#### Key takeaways 
- Types of ECG Signals for Classification.
- Converting 1D ECG signals to Image using CWT Scalogram.
- Transfer Learning via pre-trained AlexNet deep CNN.
- MATLAB Code for CWT Scalogram Image database creation.
- MATLAB Code for AlexNet Training and Validation.

#### Article quality
In this article, we combine two deep learning methods, that is, AlexNet and transfer learning to help classify the ECG signals. Also, it gives details about the ECG signals.
#### References
N/A

**Comment by Kayere** [comment]
Good topic @jumapaul - Approved. Please consider using a shorted heading.
