### ISSUE TITLE
Deploying a Django REST API serverless application with AWS and Zappa

### ISSUE THREAD

**Issue by Anitaachu** [section-engineering-education/engineering-education#4930]
### Topic Suggestion
Deploying a Django REST API serverless application with AWS and Zappa

### Writing sample(s): 
https://www.section.io/engineering-education/integrating-graphql-api-in-a-django-application/
https://www.section.io/engineering-education/concurrency-in-go/

#### Proposed article introduction
Serverless computing was created with the main goal of enabling developers to build, run applications without having to interact or manage servers. This does not mean the application runs without a server, but that the management of the server would be done by AWS.
This process is quite exciting although implementing serverless applications in Django may be challenging. However, we will be using Zappa, an open-source python tool for creating, deploying, and managing serverless python applications on AWS Lambda.

In this tutorial, we will be building a serverless Django REST API and deploying the application to AWS Lamba using Zappa.

#### Key takeaways 
1. Building a serverless Django RESTAPI application
2. How to implement Zappa
3. Working with AWS Lamba

#### Article quality
In this tutorial I intend on first, giving a detailed explanation for what serverless application means and how it aids developers. Also explaining concepts such as Zappa, AWS Lamba, etc., and how they work. The tutorial will contain a step-by-step guide on how these processes work right from building a REST API to the deployment process.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Thank you for the topic suggestion @Anitaachu.

However, this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternate topic to explore.
