### ISSUE TITLE
Get started with a Lexical Analyzer

### ISSUE THREAD

**Issue by franciskaguongo** [section-engineering-education/engineering-education#4931]
#### Proposed title of article

Get started with a Lexical Analyzer.

#### Proposed article introduction

[Languages] In the older computer generations, running simple codes were much trickier than thought. This is because everything was done in Machine languages written on punch cards. It then went to mnemonics as used in the Assembly language. These were simpler but still required much understanding of machine language.
The need for high-level languages was higher than ever since computers seem effective in repetitive tasks.

The invention of a high-level language compiler was a significant breakthrough in the computer growth phase. This breakthrough was because high-level languages are understandable by people though much overhead is needed. Hence, for one to be able to appreciate the compilers and their work in code conversion from source to optimized object code, one has to understand how they are designed.

Compiler design involves several phases. Such phases include the following:

- Lexical analysis
- Syntax analysis
- Semantic analysis
- intermediate code generation
- Code optimization
- Target code generation
- Error handling
- Symbol table generation

A Lexical analyzer is found in the first phase of compiler construction.

#### Key takeaways

In this article, one will learn the following:

- What is Lexical analysis
- Lexical analysis core principles
- Importance of a lexical analysis
- Application of the principles in creating a lexical analyzer
- Building a lexical analyzer with code examples

#### Article quality

The article focuses on the core principles used in the creation of a lexical analyzer. It then speaks of how to use the principles in creating a lexical analyzer.
Running a lexical analyzer with code samples is also among the key points to be discussed.

#### References

- Lexical analysis [definitions](https://en.wikipedia.org/wiki/Lexical_analysis)
- Lexical analysis research [document](https://webcache.googleusercontent.com/search?q=cache:XJzw8xH2YtgJ:https://www.iith.ac.in/~ramakrishna/Compilers-Aug14/doc/flex.pdf+&cd=9&hl=en&ct=clnk&gl=ke)
- Lexical analyzer [IBM documentation](https://www.ibm.com/docs/en/zos/2.2.0?topic=section-lexical-analyzer)

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Good topic @franciskaguongo - Approved. Please make sure your article is unique and adds value to what is available online.
