### ISSUE TITLE
[Languages] Understanding Exceptions and Runtime Error Handing in C#

### ISSUE THREAD

**Issue by Wanyoike-shift** [section-engineering-education/engineering-education#4932]
#### Proposed title of the article
[Languages] Understanding Exceptions and Runtime Error Handing in C#

#### Proposed article introduction
The try-catch and finally block supports exception handling in C#, which is a means for detecting and addressing code runtime issues. For common exceptions, the.NET framework has built-in classes. Anomalies that occur while a program is being executed are referred to as exceptions. User, logic, or system mistakes may be to blame. The.NET runtime environment provides a default method for handling these abnormalities, which ends the application execution.

#### Key takeaways 
By the end of this article the reader will have understood:
- try..catch..finally
- Uncaught Exceptions
-  Throwing an Exception
- Standard Exceptions
- Multiple Catch Blocks 
- User-defined Exceptions
- Catching all Exceptions
- User-defined Exceptions
- Handling Runtime Exceptions In C#

#### Article quality
This article covers topics not addressed in official documentation, such as comprehending exceptions in the.NET framework and managing runtime exceptions in C#. I will also use simpler language so readers may grasp the material easily. My essay should also benefit the broader technical community.

#### References
N/A

**Comment by Kayere** [comment]
Hello @Wanyoike-shift, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
