### ISSUE TITLE
[Networking] Working with VPCs and Subnets - Amazon VPC complete guide

### ISSUE THREAD

**Issue by neshmacharia** [section-engineering-education/engineering-education#4933]
#### Proposed title of article
[Networking] Working with VPCs and Subnets - Amazon VPC complete guide

#### Proposed article introduction
It is possible to create a private cloud computing environment inside a public cloud. Virtual private clouds (VPCs) isolate portions of the public cloud to create a private virtual environment. VPC resources may be scaled up and down on demand, and they can be extensively customized. A subnetwork divides an IP network logically. Subnetting is the technique of splitting a network into two or more. Computers on the same subnet have the same most-significant bit group in their IP addresses.

AWS VPCs and subnets Connecting on-premises resources to AWS infrastructure via a virtual private network is made possible by Amazon VPC, an AWS feature. Using this virtual network, you may take advantage of AWS's scalability while maintaining the security of your own network.

#### Key takeaways 
- Create a Virtual Private Cloud (VPC)
- Get a look at your virtual private server
- Set up a subnet in your VPC
- Assign a second IPv4 CIDR block to your virtual private network (VPN)
- Make sure your VPC and subnet are linked using an IPv6 CIDR block
- Initiate an instance in your private network
- Remove your subnet.
- Disconnect your VPC from an IPv4 CIDR block!
- Disassociate an IPv6 CIDR block from your VPC or subnet
- Remove your Virtual Private Cloud (VPC)
- 
#### Article quality
In this tutorial, I will manually create a VPC and subnets.  Also  manually add gateways and routing tables. Alternatively, one can use the Amazon VPC wizard to create a VPC plus its subnets, gateways, and routing tables in one step.

#### References
N/A

**Comment by Kayere** [comment]
Hello @neshmacharia, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
