### ISSUE TITLE
[Languages] How to build Discord Bot with javascript

### ISSUE THREAD

**Issue by Kamau-ke** [section-engineering-education/engineering-education#4940]
#### Proposed title of article
 How to build Discord Bot with javascript

#### Proposed article introduction
Discord is a robust communication app used by a large community of gamers, developers, and cryptocurrency enthusiasts. Admins can add a plethora of unique Discord bots to their servers. There are also powerful APIs for creating Discord bots for those who prefer to take matters into their own hands.
With Discord.js, it is relatively simple to create a Discord bot using Javascript. In this Discord bot tutorial, we'll go over everything you need to know to get a bot up and running on the Discord server.
#### Key takeaways 
1. Create a New Project and Initialize as Node.js Project
2.  Install Dependencies
3. Register Discord Application
4. Code the Bot
#### Article quality
My article will be simple, straight to the point, and will go beyond documentation.

#### References
N/A

**Comment by louisefindlay23** [comment]
Hi, @Kamau-ke. There are many [articles](https://www.google.com/search?client=firefox-b-d&q=How+to+build+Discord+Bot+with+javascript) that already exist on this topic as well as the official documentation. How is yours unique?

**Comment by Kamau-ke** [comment]
@louisefindlay23 I believe that knowledge cannot be exhausted, and looking at nearly similar content online, the majority are not novice-friendly and are not engaging as much as it could be. This article will, of course, be unique, and it will address these issues as gracefully as possible in order to maintain quality and add value to the community. Thanks

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by Kamau-ke** [comment]
hello sir, I have written the article and has already been merged
