### ISSUE TITLE
[Python]Data Wrangling Using Pandas

### ISSUE THREAD

**Issue by Geofreytech** [section-engineering-education/engineering-education#4942]
### Topic Suggestion
data wrangling using pandas

#### Proposed article introduction
Data Wrangling is an essential part of data science and data analysis. Use the Pandas Framework of the Python programming language for data manipulation. Pandas is a free and open-source data analysis and data science library. Sorting, filtering, grouping, etc. are all examples of this.

Python has built-in features to apply these wrangling methods to various data sets to achieve the analytical goal by use of DataFrames.

#### Key takeaways 
Data Discovery
Data Structuring
Data Cleaning
Data Enriching
Data Validating
#### Article quality
The learner will be able to master the data wrangling concept with ease and faster

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Hi, @Geofreytech. Your article quality section doesn't tell me how your article is unique. What content does that cover that [existing articles](https://www.google.com/search?client=firefox-b-d&q=Data+Wrangling+Using+Pandas) do not? Please update your Article Quality information to reflect this so we can accurately review your article's unique value.

**Comment by WanjaMIKE** [comment]
I think the author needs to work more on grammar. The current submission seems to have random sentences that cannot make a quality article.
