### ISSUE TITLE
[Language]Using Python to Create an Infinite Timer

### ISSUE THREAD

**Issue by FranciscaNg** [section-engineering-education/engineering-education#4947]
#### Proposed title of article
Using Python to Create an Infinite Timer

#### Proposed article introduction
Using Python's libraries, an infinite timer can be created. It's a kind of infinite timer, in that it notifies you or other users at regular intervals about tasks you've set.

Consider someone who is notoriously bad at remembering to take breaks or complete duties. He will be reminded of the task at regular intervals by using this program.
#### Key takeaways 
- Uses of Infinite Timer
- Making an infinite timer
- What is this Infinite Timer

#### Article quality
In this article, we shall create an Infinite Timer that notifies you or other users at regular intervals about tasks you've set. In addition, you will not want to run this program manually then you can automatically run this on startup. The user will be able to change the minutes or seconds or even change the contents of the message or title. Also, he/she can customize the program according to her/his wish.  Also, I will be going to use some python libraries to make it. These libraries: plyer module, speech recognition, pyttsx3 (python text-to-speech) module, Time module, and Regex or re module will allow in notifying purpose, voice commands, to interact with the user and reminder. 

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Please fill in the article quality section so we can review your article.

**Comment by FranciscaNg** [comment]
@louisefindlay23 Done

**Comment by louisefindlay23** [comment]
Thanks, @FranciscaNg, however you've explained what you are going to write about rather than justifying why your article is unique. The article quality section should state what makes your article different from others covering the same topic. Do you cover additional content that no one else does, do you provide a unique perspective or developer tips or a novel type of tutorial as an example?

**Comment by FranciscaNg** [comment]
@louisefindlay23 
I have done some edits.

**Comment by FranciscaNg** [comment]
> Thanks, @FranciscaNg, however you've explained what you are going to write about rather than justifying why your article is unique. The article quality section should state what makes your article different from others covering the same topic. Do you cover additional content that no one else does, do you provide a unique perspective or developer tips or a novel type of tutorial as an example?

I will be developing an infinite timer that reminds at regular intervals like various built-in software can be used for the 1-time reminders.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
