### ISSUE TITLE
[Language]Dealing with Python's Missing Values: A Complete Guide

### ISSUE THREAD

**Issue by jgesare** [section-engineering-education/engineering-education#4949]
### Topic Suggestion
Dealing with Python's Missing Values: A Complete Guide
#### Proposed article introduction
How to deal with missing values in data pre-processing will be the subject of our discussion today (which is part of Data Cleaning). Machine Learning methodologies, Deep Learning architectures, or any other advanced approaches in the data science field have nothing to do with cleaning data

On the topic of Data Cleaning, which is part of pre-processing, we'll look at it in this piece. Data cleaning is the process of removing duplicates, corrupted, badly structured, erroneous, or otherwise flawed data from a dataset.
#### Key takeaways 
- Importance of filling the missing values
- Problems due to missing values
- Missing data – Types
- Overcoming Missing data in our dataset

#### Article quality
In this post, we'll take a look at Data Cleaning, which is part of the data pre-processing module. Furthermore, in the absence of evidence, the reader will be able to overcome statistical power or the chance that the test would reject the null hypothesis when it is incorrect. Furthermore, the loss of data may cause parameter estimations to be skewed, the ability to reduce the representativeness of the sample, and the analysis of the study to be more difficult. 

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Please fill in the Article Quality section so we can review your article.

**Comment by jgesare** [comment]
@louisefindlay23 I have added. Thanks

**Comment by louisefindlay23** [comment]
Thanks, @jgesare. However, we're looking more for what makes your article unique rather than what you plan to cover. For example, what part of Data Cleaning will you cover that no other article does or do you bring a unique perspective?

**Comment by jgesare** [comment]
@louisefindlay23 I will be looking at an intriguing issue in data pre-processing: how to deal with missing values (which is part of Data Cleaning). Published articles don't go into details about overcoming missing data in our dataset but I will provide more ways and in addition, go into details on imputations. Thanks.
