### ISSUE TITLE
[Language]The LRU technique for Python's caching

### ISSUE THREAD

**Issue by SusanKiptoo** [section-engineering-education/engineering-education#4952]
### Topic Suggestion
The LRU technique for Python's caching
#### Proposed article introduction
Just two lines of code are needed to implement LRU caching in Python: import the @lru_cache decorator and declare it. Using examples, we demonstrate how and why it is beneficial to utilize.

The use of caching can dramatically speed up and minimize the burden on computational resources if utilized correctly. Using the Least Recently Used (LRU) method, the output of functions can be cached using a decorator implemented in the Python standard library module. 

#### Key takeaways 
- Caching strategies can be implemented using decorators
- It's important to know what LRU is and how it works
- How to use a decorator to speed up an application
- After a predetermined amount of time, how to extend the decorator's usefulness and stop caching

#### Article quality
In this lesson, we will learn about caching techniques, how LRU caching works in Python, how to use the @lru cache decorator, and how the recursive strategy combined with caching helps to solve the problem rapidly. The article will be comprehensive, and the code provided will be simple to grasp.
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Please fill in the Article Quality section so we can review your article.

**Comment by SusanKiptoo** [comment]
@louisefindlay23 done

**Comment by louisefindlay23** [comment]
Hi. Your article quality section is more about what you're writing about rather than what makes your article unique? Can you tell me what aspects of your article are not covered [elsewhere](https://www.google.com/search?client=firefox-b-d&sxsrf=AOaemvKjIEZS7C2upl0ZVKcrb9j14JQJDA:1636802633276&q=The+LRU+technique+for+Python+caching&spell=1&sa=X&ved=2ahUKEwjM7pf8nJX0AhUHXsAKHWXwAo8QBSgAegQIARA0&biw=1374&bih=998&dpr=1.25) or your unique perspective that you plan to bring?

**Comment by SusanKiptoo** [comment]
@louisefindlay23 The already published articles only cover the introductory part on how caching works. My article will include more and the distinguishing part is that I will include a section on how the recursive approach in combination with caching helps to solve the problems quickly enough. Thanks.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by SusanKiptoo** [comment]
> I'm going to close this topic due to inactivity. It can be reopened.

@ahmadmardeni1 please open this topic. Thanks.
