### ISSUE TITLE
[Language] Working with system information in a windows form C# program

### ISSUE THREAD

**Issue by Kipkopus** [section-engineering-education/engineering-education#4954]
#### Proposed title of article
Working with system information in a windows form c# program

#### Proposed article introduction
System Information is a program that allows users to see all of their computer's information. It is made up of two terms, namely: system and information.

The term "system" refers to the computer components that work together to accomplish a specific task, such as the operating system, the RAM installed in a computer, the OS version, and so on. On the other hand, information is the summarization of data and how it is conveyed to the user in the form of output.

In this article, we'll go over how to check system information and the classes that can be used to do so, as well as write a C# program to demonstrate it. This article will be 70% practical, which will necessitate a lot of coding.

#### Key takeaways 
1. Introduction
2. Classes used in checking system information in C# programming.
2. Get Machine name and User name
3. CPU and Monitor size
3. Get OS installed, OSVersion and OS platform
4. Check the processor if it is x64-based processor or x32 based processor and System type:  64-bit operating system or 32 bit system
5. Virtual Screen among others
6. Conclusion
#### Article quality
This article focuses on both the practical and theoretical aspects of using C# to check system information in Windows form applications. This article is less well-known on the internet, and the section engineering website does not have it. I believe that having a good understanding of this topic will be very beneficial to all C# programmers.
#### References
N/A

**Comment by louisefindlay23** [comment]
Be sure to emphasise unique points such as virtual screens because there have been previous articles available online that cover similar topics.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by Kipkopus** [comment]
> I'm going to close this topic due to inactivity. It can be reopened.

@ahmadmardeni1 working on this pr

**Comment by Kipkopus** [comment]
> > I'm going to close this topic due to inactivity. It can be reopened.
> 
> @ahmadmardeni1 working on this pr

@ahmadmardeni1 please reopen this, I have already submitted the pr
