### ISSUE TITLE
Understanding Control Structures in C#

### ISSUE THREAD

**Issue by annkambua** [section-engineering-education/engineering-education#4960]
**Topic suggestion**
understanding control structures in c#

**introduction**
Control structures  are widely covered in c#. These are blocks which analyze variables and choose direction in which to go  given different parameters. In  this  article we will get introduce to control structures, talk about the control statement offered in c#.furthermore will give various examples on each statement for better understanding.
** key takeaways** 
The user will get to learn :

1. Selection statements
2. Iteration statements
3. Jump statements

**reference**
N/A

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

**Comment by louisefindlay23** [comment]
Please fill in the Article Quality section so we can review your article.

**Comment by annkambua** [comment]
Hi, @louisefindlay23 .This article goes beyond what has been covered in other official documentations, by covering areas such as:introducing control structures in c#, selection statements, iteration statements, jump statements. Which are not covered in other official documents. Furthermore,  i will use a simpler language which will be easy for users to understand  the article without strain. I also hope my article will add value to entire engineering education community.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by annkambua** [comment]
Hi @ahmadmardeni1 ,kind open this issue  I want to make a pr it

**Comment by annkambua** [comment]
Hi @ahmadmardeni1 , kindly i request you to open this issue so that i can do pr
