### ISSUE TITLE
[Language] Creating a customize Data structure with java generic

### ISSUE THREAD

**Issue by popsoft01** [section-engineering-education/engineering-education#4964]
### Topic Suggestion
[Language] Creating a customize Data structure with java generic

#### Proposed title of the article
Creating a customize Data structure with java generic

Use keyword research to improve your article's SEO.

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*

Java generic is a concept in programming that allows type and method to perform an operation on any variable type or object. Java generic was introduced in 2004 to extend the type system of java.

Java generic method and classes allow you to declare a method that could be used to manipulate any data type

The generic data structure is a container that can hold any type of data. This means a class or method can be declared for different types of variables or objects without overloading the method

#### Key takeaways 
understand the core concept of each collection
implementing each data structure with generic
understand the linear and non-linear data structure

#### Article quality
This article will explain the core in-depth concept of each data structure and its generic properties. it will also explain the approach in the usage of each data structure.

#### References
[Tutorialspoint](https://www.tutorialspoint.com/java/java_generics.htm)
[Geeksforgeeks](https://www.geeksforgeeks.org/generics-in-java/)
[Section.io](https://www.section.io/engineering-education/getting-started-with-generics-in-java/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by popsoft01** [comment]
@ahmadmardeni1 I need your help to re-open this topic

**Comment by popsoft01** [comment]
@ahmadmardeni1 I already make a pull request

**Comment by louisefindlay23** [comment]
@popsoft01, I have corrected linked your pull request for you to this issue. Please amend the title of your PR to your article name and follow the other PR instructions such as deleting the article checklist notes in blockquotes for a swift review.
