### ISSUE TITLE
[Languages] Understanding IComparable and IComparer Interface In C#

### ISSUE THREAD

**Issue by markiesar57** [section-engineering-education/engineering-education#4965]
### Topic Suggestion
Understanding IComparable and IComparer Interface In C#

#### Proposed article introduction
IComparable's purpose is to offer a way for comparing two objects of the same type. It's required if you want your object to have any sort of ordering functionality. Consider IComparable to be a sorting algorithm for your items. IComparer's function is to give more comparison techniques. You could wish to give class ordering on several fields or attributes, ascending and descending order on the same field, or both.
These two interfaces are commonly combined. Despite the fact that the interfaces and titles are identical, they serve different objectives.

#### Key takeaways 

1.What are IComparable and IComparer Interfaces
2. How to use  IComparable and IComparer Interfaces
3. When to use each interface.
4. Difference between the two interfaces.

#### Article quality
This article will be giving an in-depth understanding of the interfaces to the reader. I will be using examples in each interface which help the reader  to get a better understanding of the concept.  
#### References
N/A

**Comment by louisefindlay23** [comment]
How does your article provide unique value from the [others](https://www.google.com/search?client=firefox-b-d&q=Understanding+IComparable+and+IComparer+Interface+In+C%23) that exist? What unique additions or perspective do you bring?

**Comment by markiesar57** [comment]
@louisefindlay23
Majority of the articles on the sites in the link above only cover  the differences between the two interfaces. Knowing the differences will be helpful to the reader if the reader knows how to use the interfaces. The  aspect of how to use the interfaces which has not been covered will be the unique perspective of my article. I will be incorporating codes to make it easier for understanding.
Thank you

**Comment by markiesar57** [comment]
Hi @louisefindlay23 I see a question label but no question. Is there a problem?

**Comment by markiesar57** [comment]
@louisefindlay23 
Thank you

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
