### ISSUE TITLE
[Java] How to generate reports in a SpringBoot App leveraging Jasper

### ISSUE THREAD

**Issue by davidmbochi** [section-engineering-education/engineering-education#4968]
####  introduction
We use reports in our day to day activities whether we are purchasing products and services online or managing the transactions of an information system in an organisation. 

These reports include summary reports, financial reports, inventory reports, sales report and budget report just but to mention a few. These reports help in generating insights to an organisation and making the right decision based on the knowledge generated from them.

For example, an  inventory report can help an organisation on deciding on the appropriate reorder level to use during acquisition of products.

In this tutorial, the reader will learn how to design an inventory report, integrate it in a SpringBoot application and use custom products to generate a standard report that can be used in an organisation.

#### Key takeaways 
- What is Jasper
- What is Jasper Studio
- How to design a report
- How to integrate Jasper in our application
- How to generate the report using our custom data from the database

#### References
N/A

#### Article quality
This article focuses on how to add the functionality of printing a report in a web page allowing the user to realise the action with just the press of a button.
The article also explains in details how to implement a report having the format of a pdf and clues on how other type of formats can be generated where necessary.

**Comment by louisefindlay23** [comment]
Please fill in the Article Quality section so we can review your article.

**Comment by davidmbochi** [comment]
@louisefindlay23 I have added the Article Quality section

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
