### ISSUE TITLE
[Android] Getting Started with Kotlin Flows API Zip Operator for Parallel Multiple Network Calls in Android

### ISSUE THREAD

**Issue by Emmah-Lashly** [section-engineering-education/engineering-education#4969]
### Topic Suggestion
[Android] Getting Started with Kotlin Flows API Zip Operator for Parallel Multiple Network Calls in Android

#### Proposed title of article
Getting Started with Kotlin Flows  Zip Operator for Parallel Multiple Network Calls in Android

#### Proposed article introduction
Flow API in Kotlin is a better way to handle the stream of data asynchronously that executes sequentially.  Zip Operator is an operator that combines the emissions of two flow collections together via a specified function and emits single items for each combination based on the results of this function.

Parallel Multiple Network Calls is used in Android when we want to make two network calls in parallel and want the results of both the network calls in a single callback when both the network calls are completed.

#### Key takeaways 
- What is Kotlin Flow API.
- What is Kotlin Flow Zip operator.
- Uses of Kotlin Flow Zip operator.
- Advantages of Using Kotlin Flow Zip Operator in Android.
- How to make the multiple network calls in parallel using Kotlin Flow Zip Operator.

#### Article quality
 The article is going to be unique since am going to make it beginner friendly. Since it is a new concept in Android development I researched and realized that there are are less content in the internet for reference and this is going to help developers to learn and understand it.

#### References
- https://blog.mindorks.com/kotlin-flow-zip-operator-parallel-multiple-network-calls
- https://developer.android.com/kotlin/flow

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
