### ISSUE TITLE
[Artificial Intelligence]Turing Test in AI

### ISSUE THREAD

**Issue by LeemaH2** [section-engineering-education/engineering-education#4976]
#### Proposed title of article
[Artificial Intelligence]Turing Test in AI

#### Proposed article introduction
This article will provide an overview of the Turing Test in AI, which was introduced in 1950 by renowned mathematician Alan Turing. The purpose of the test was to determine whether a machine can exhibit Human-like Intelligence in its work or thought process. The test was dubbed 'The Imitation Game' in Alan Turing's research paper. He considered a computer/machine to be intelligent only if it could mimic human-like responses. If the interrogator (Judge) cannot determine whether the response is from a machine or a human, the machine passes the test.
#### Key takeaways 
How turing test is performed
Requirements for passing turing test in AI
Feartures of Turing Test in AI
Limitations of Turing test.

#### Article quality
The Modern Day Turing test. Machine is tested using respondents to determine if it is  human or a computer. This article uses simple grammar and it is user friendly.
 
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Please fill in the Article Quality section so we can review your article.

**Comment by LeemaH2** [comment]
> Please fill in the Article Quality section so we can review your article.

The changes requested has been made. Thank you

**Comment by louisefindlay23** [comment]
Hi, @LeemaH2. Your article quality section is more about what you're writing about rather than what makes your article unique? Can you tell me what aspects of your article are not covered [elsewhere](https://www.google.com/search?client=firefox-b-d&q=Turing+Test+in+AI) or your unique perspective that you plan to bring?

**Comment by LeemaH2** [comment]
Hi @louisefindlay23 
Unlike the other articles, my article will cover a bit of Turing test history and the critics of turing test. I'll take the reader step by step through the turing test in Artificial Inteligence, i will also use simple grammar hence my article will be beginner-friendly.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by WanjaMIKE** [comment]
Closed #4976 via #5550
