### ISSUE TITLE
Recursion in C++

### ISSUE THREAD

**Issue by Romans70** [section-engineering-education/engineering-education#4977]
#### Introduction
Recursion is the procedure of calling a component by itself as a subroutine to fix the complicated program. Instead of using the iterative technique, which requires a lot of work and time to tackle a similar problem, recursion divides the program into sub-tasks and calls it repeatedly. As a result, a recursive function is one that calls itself, and the act of invoking a function by itself is referred to as recursion. The most crucial aspect of the recursion is that it should have a base case for terminating it. Because the recursive function calls itself indefinitely, the program can always end up in an endless loop. Depending on the language used, recursion poses a slight difference.  In this post, we'll explore at how we can utilize the C++ language to accomplish recursion.

#### Key takeaways 
1. Introduction to Recursion
2. How Recursion occurs
3. Types of Recursion
4. Direct vs Indirect Recursion
5. Examples of Recursion

#### Article quality
This will be a distinctive article with detailed information. In this article, I will use basic language to ensure that anybody reading it understands the contents. I'll make sure that this article is useful to the whole EngEd and that it goes above and beyond official documentation.
#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in-depth topic.
