### ISSUE TITLE
[Machine Learning] Is a Knowledge Graph Just Another Means of Knowledge Visualization?

### ISSUE THREAD

**Issue by mumbi00** [section-engineering-education/engineering-education#4981]
#### Proposed title of article
Is a Knowledge Graph Just Another Means of Knowledge Visualization?

#### Proposed article introduction
Businesses have to face the pace of constantly evolving data needs. Knowledge graphs can help companies move away from traditional databases and use the power of natural language processing, machine learning, and semantics to better leverage data.

knowledge graphs are the foundation of modern data and analytics, with capabilities to enhance and improve user collaboration, machine learning models, and explainable AI. Although graph technologies are not new to data and analytics, there has been a shift in the way they are used. A knowledge graph brings together machine learning and graph technologies to give AI the context it needs.

#### Key takeaways 

1. What is a knowledge graph?
2. Knowledge graph and visualizations 
3. Knowledge graphs as a solution to machine learning problems
4. Where are Knowledge Graphs used today 

#### Article quality
This article is in-depth and covers additional topics. 

#### References
N/A

**Comment by louisefindlay23** [comment]
Please add more depth in your Article Quality section so we can review your proposed article. What additional topics do you cover that no other article does?

**Comment by mumbi00** [comment]
@louisefindlay23 This article will show the ready why the knowledge graph is more than just visualizations. An argument that is not available in other blogs. It will also explain how knowledge graph is assisting to solve machine learning issues.

**Comment by louisefindlay23** [comment]
Approved but make sure to add enough unique value and content. See [this](https://www.linkedin.com/pulse/knowledge-graphs-just-visualization-andreas-blumauer/) for an article on a similar topic to yours.
