### ISSUE TITLE
Conversions Tracking using Google Analytics

### ISSUE THREAD

**Issue by LeahKui** [section-engineering-education/engineering-education#4982]
### Topic Suggestion
Conversions Tracking using Google Analytics

#### Proposed title of article

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Conversions are used to report on the most important activities taking place on your website or application. For example, you might want to report on the number of people who have purchased a particular product or service on your web app or any other important action.
To track conversions, we use Google Analytics. This tutorial will be a complete guide on how to track your conversions inside Google Analytics.

#### Key takeaways 
1. What are conversions
2. How Google Analytics conversion tracking works
3. Step-by-step guide on how to track your conversions using google analytics

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by louisefindlay23** [comment]
Please fill in the Article Quality section so we can review your article.

**Comment by WanjaMIKE** [comment]
I think Google has proper documentation for its products. I don't think this topic is that unique.
