### ISSUE TITLE
Access Specifiers in OOP languages

### ISSUE THREAD

**Issue by Dankosgei911** [section-engineering-education/engineering-education#4983]
### Introduction
Access Specifiers are keywords in OOP languages that determine the accessibility of classes, methods, and other attributes in a class. The three access specifiers include private, public, and protected. With different OOP languages, access specifiers are implemented differently. In this article, we are going to take a look at how access specifiers are implemented in the four main OOP languages that is in Java, C++, C and Python. We will further look at how implementation differs in syntax and other ways. 
Moreover, we will use code snippets from all the languages mentioned to ensure the user gets a clear understanding of access specifiers in depth.

### Key Takeaways
1. Introduction to Access specifiers.
2. Implementation of Access specifiers in OOP languages.
3. Code snippets to explain the implementation of access specifiers.
4. How to access specifiers differ in OOP languages.

### Article quality
The article proposed will refrain from the use of complex keywords that is not suitable for beginners. The code snippets that will be used will be brief and detailed to ensure quick understanding by the user. Moreover, when highlighting the differences, a clear format that will be tireless to the user will be used.

### Reference
N/A

**Comment by louisefindlay23** [comment]
Can you provide more detail about the unique aspects of your article? Are there parts of your content that are not covered elsewhere or do you bring a unique perspective? [Similar Articles](https://www.google.com/search?client=firefox-b-d&q=Access+Specifiers+in+OOP+languages)

**Comment by WanjaMIKE** [comment]
I don't this topic adds much value. The access modifiers are well documented in all programming languages.
