### ISSUE TITLE
How to send otp via sms in springboot using twilio

### ISSUE THREAD

**Issue by curiouslove** [section-engineering-education/engineering-education#4990]
#### Proposed title of article
How to send OTP via SMS in Spring Boot using Twilio

#### Proposed article introduction
In this tutorial, we will build a simple Spring Boot application with SMS capability to send messages to a phone number when a user registers. We would be using Twillio, which is a cloud communications platform that allows you to add SMS functionality to an application. 

#### Key takeaways 
Below are some of the important things you would be able to do after reading this article, you would be able to:

* Create Restful APIs using Spring boot frame work
* Generate OTP using Twilio
* Test your APIs using postman
* Authenticate and Authorize a user in an application

#### Article quality
This is an in-depth article on authentication via OTP, it covers Restful APIs, spring security and testing APIs, A basic knowledge of java would be required of the readers

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by curiouslove** [comment]
@ahmadmardeni1  Sorry for the delay. I was a little busy with academics. I am now free and done with the draft.  Can you please reopen the issue so I can submit my draft. Thanks.

**Comment by hectorkambow** [comment]
> @ahmadmardeni1 Sorry for the delay. I was a little busy with academics. I am now free and done with the draft. Can you please reopen the issue so I can submit my draft. Thanks.

Has a final draft been submitted?

**Comment by ahmadmardeni1** [comment]
No. @hectorkambow
