### ISSUE TITLE
Getting started with Gmail API in python

### ISSUE THREAD

**Issue by davismunene** [section-engineering-education/engineering-education#4992]
### Topic Suggestion
Getting started with Gmail API in python
### Proposed title of article
Getting started with Gmail API in python
### Proposed article introduction
Gmail is one of the most dominant mail service, used globally, by most people and many organizations.
Over the past years, many Gmail features have been improved with the application of Artificial Intelligence, including suggestions while writing emails and security features.
Gmail API is found on RESTful APIs, that authorizes it's users to interact with our Gmail account, and it enables us to access it's elements using a python text.

### Key takeaways 
- Installing the required libraries.
- Enabling Gmail APIs
- Sending Emails
- Searching Emails
- Reading Emails
- Marking Emails as Read
- Marking Emails as Unread
- Deleting Emails

### Article quality
In this article am going introduce users to Gmail APIs in python, I will take the user through installation of required libraries, and how to work with Gmail APIs in python, like sending, searching, reading, deleting, and marking as read or unread, using the Gmail API in python.

**Comment by louisefindlay23** [comment]
There are many existing [articles](https://www.google.com/search?q=Getting+started+with+Gmail+API+in+python&client=firefox-b-d&sxsrf=AOaemvLAy9q_1xwtLeS-4FPS44FYxs5pfQ%3A1636804017898&ei=saWPYeW1NsrrgAbD75WoCA&oq=Getting+started+with+Gmail+API+in+python&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeOgcIABBHELADOgcIIxDqAhAnSgQIQRgAUNoDWP4NYL4QaAJwAXgAgAHoAYgB6AGSAQMyLTGYAQCgAQGgAQKwAQrIAQjAAQE&sclient=gws-wiz&ved=0ahUKEwil0raQopX0AhXKNcAKHcN3BYUQ4dUDCA0&uact=5) on this topic, some of which detail all the topics you plan to cover. Can you tell me what unique content you plan to cover or unique perspective you will bring?

**Comment by davismunene** [comment]
Hi @louisefindlay23 , am going to use a beginner friendly language and simplify the content. My article also introduces a new concept, installing required libraries, which has not been covered in official documents.

**Comment by stanleywambui435** [comment]
Hello @louisefindlay23 ,am seeing two labels, question and topic approved. Am not understanding please help.

**Comment by davismunene** [comment]
Hello @louisefindlay23 ,am seeing two labels question and approved, am not understanding kindly help.
