### ISSUE TITLE
Understanding computer network services

### ISSUE THREAD

**Issue by gorleroy** [section-engineering-education/engineering-education#4993]
#### Proposed article introduction
Network service is an operand in the network provided by a server. The application runs at the network
application layer and above, and include; IP addressing, Domain Name System (DNS), Internet access,
security products (firewalls), primary domain service, web content filtering, VPN termination and
intrusion prevention systems (IPS), and the tools to support these services.
A server component for each service is usually run on one or more computers which is accessed via a network by client components running on other devices. Clients and servers often have a user interface
and sometimes other hardware associated with it.
In this context we are going to cover :
- Basic Network Design Requirements
- Scaling a network
- Network services and their functions (DHCP, DNS, File Server Services, Printing, Authentication,
etc)
- Automatic Network Services
- Configuring Network Services.

#### Key takeaways 
    i. The reader should understand the basics in designing a computer network.
    ii. The reader should be able to figure out factors to consider when scaling a network.
    iii. The reader should be able to understand the different network services and their functions.
    iv. The reader should be able to understand configuration of the network services
#### Article quality
This article will provide an in-depth tutorial on how a network can be developed from scratch and the services that will be provided by the network. Unlike other articles, this article will explain definitively the concepts surrounding network authentication, file server services and DHCP.  In addition, it will show illustratory diagrams clearly explaining the concept in question.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
