### ISSUE TITLE
Implementing Africa's talking API using Node.js

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#4994]
#### Proposed title of article
Implementing Africa's talking API using Node.js

#### Proposed article introduction
Africa's talking API is built to power communications solutions across Africa.

It enables software developers to be able to build scalable solutions by providing powerful  SMS, USSD, voice, airtime, and payments API's.

In this article, we will implement the Africa's talking SMS API using Node.js

#### Key takeaways 
- How to set up a sandbox project on Africa's talking.
- How to set up a restful API using Node.js and TypeScript.
- How to implement Africa's talking SMS API using Node.js and TypeScript.

#### Article quality

- In-depth guide particularly with Node.js.
- Step by step guidelines for beginners.

#### References
- https://developers.africastalking.com

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
