### ISSUE TITLE
[Languages]Creating a PySpark DataFrame: A Beginner's Guide

### ISSUE THREAD

**Issue by FranciscaNg** [section-engineering-education/engineering-education#5003]
### Topic Suggestion
Creating a PySpark DataFrame: A Beginner's Guide
#### Proposed article introduction
We can distribute data and conduct calculations on several nodes of a cluster using Spark, a cluster computing platform. It is easier to process large datasets when the data is distributed.
In this example, each node is described as a discrete computer that is focused on a certain subset of data. This node would also be responsible for some of the calculations that take place during dataset operations. In addition to Scala, Spark also supports Java, Python, R and SQL programming languages.

#### Key takeaways 
- PySpark DataFrame From an Existing RDD
- PySpark DataFrame From an External File
- Additional Useful Method

#### Article quality
In this lesson, we will learn about creating PySpark DataFrames. PySpark DataFrames and two techniques for creating them will be covered in this article. This article differs from others in that I'll generate a PySpark DataFrame from an existing RDD, generate PySpark DataFrame from List and from external file sources using Google Colaboratory for practice. As a bonus, we'll cover certain approaches that aren't already covered in the published papers on PySpark. The article will be comprehensive, and the code provided will be simple to grasp.
### Reference
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
The explanation isn’t sufficient. Please explain in detail, how this article will add value to the reader.

**Comment by FranciscaNg** [comment]
@lalith1403 Done 
Thanks.
