### ISSUE TITLE
Introduction to JSP

### ISSUE THREAD

**Issue by TumorEvanzo** [section-engineering-education/engineering-education#5004]
Proposed title of article
Introduction to JSP

Proposed article introduction
JSP is a programming language for constructing web applications that is similar to Servlet technology in terms of usefulness and versatility. Because servlets are more difficult to code than JSP pages, JSP pages are more polar. A Servlet inserts HTML code into Java code, whereas a JSP inserts Java code into HTML using JSP tags.

JSP enables us to generate HTML pages that contain tags that can be used to embed powerful Java programs. A web designer can create and maintain JSP pages to provide the display layer, whilst a java developer can write server-side complex computational code without having to bother about web design. Additionally, both levels can communicate easily using HTTP requests.

Key takeaways
Introduction to JSP
Advantages of JSP
The JSP Pages' Lifecycle.
simple JSP Page
JSP directory structure
Example

Article quality
I checked over some of Section Engineering's published writings and realized that the JSP section has yet to be adjusted. In the majority of the articles, the Core Java and Servlet sections have been mentioned. I'll make sure that anything I talk about is original and hasn't already been published on the Section Engineering website.

References
N/A

**Comment by Kayere** [comment]
Sounds like a good topic @TumorEvanzo - Approved. Please make sure your article is unique and adds value to what is available online.
