### ISSUE TITLE
Beginners intro to Generative Modeling

### ISSUE THREAD

**Issue by tanmay69** [section-engineering-education/engineering-education#5007]
#### Proposed title of article
Beginners intro to Generative Modeling

#### Proposed article introduction

As we know, deep learning has been the most evolving area in Artificial intelligence since the last decade due to research advancements in this area. However, Generative Modeling is a specific field in Deep Learning that has been a topic of interest for the last few years. In this article, we will be looking forward to the concept of Generative Modeling from scratch and understanding its significance.
Before we dig deeper, I will try to present a basic notion of Generative Modeling for our readers by taking an example. Let us suppose we want to classify an image into a dog or a cat. We can solve this problem simply by feeding the image as an input to a convolutional neural network that can output the image's corresponding category. What if we want this process to be reversed? We describe what we want as an input to the model and get the image as output, and this is generative modeling in its simplest.
In this blog, we will dig deep into the concepts of Generative Modeling and also try to understand how it can impact the future of ML.

#### Key takeaways 

- Introduction to Generative Modeling.
- Generative vs Discriminative Modeling
- Why generative modeling is future of AI.
- GANs

#### Article quality
Most of the articles present on the Internet about Generative Modeling are vague and filled with jargon. This blog clears the basic concepts of Generative Modeling using many examples that a reader can relate to.

#### References
NA

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by tanmay69** [comment]
@lalith1403 Please see this topic suggestion.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
