### ISSUE TITLE
[Android]Localization and internationalization in android

### ISSUE THREAD

**Issue by nia-vee** [section-engineering-education/engineering-education#5011]
[Android]Localization and internationalization in android

#### introduction
Android is used on a wide range of devices in a variety of countries. Your app should handle text, audio files, numbers, money, and visuals in ways that are acceptable to the locations where your app is utilized to reach the most customers.

This article will go through the Android localization process in great depth, as well as how to apply best practices to your translation efforts.

#### Key takeaways 
The key takeaways are:-
- localizing strings,images and simple media
- understanding localization resources in android
- organizing resources with configuration types and qualifiers
- providing localized resources considering various factors
- understanding how SDK deals with your localized resources
- Applying best practices to your localization app effort

#### Article quality
This article will aim to guide readers on the best practices to apply on a localized app and show the relevant and best way to perform localization in android application and resources.

#### References
N/A

**Comment by Kayere** [comment]
Good topic @nia-vee - Approved. Please make sure your topic is unique and adds value to what is available in the official documentation.

**Comment by WanjaMIKE** [comment]
Closed #5011 via #5554
