### ISSUE TITLE
[Machine Learning] Imbalanced-Learn Python Package for Machine Learning

### ISSUE THREAD

**Issue by charles721** [section-engineering-education/engineering-education#5012]
#### Proposed title of article
[Machine Learning] Imbalanced-Learn Python Package for Machine Learning

#### Proposed article introduction
Imbalanced-Learn is a Python package that is used to handle imbalanced datasets during machine learning. An imbalanced dataset is a dataset in which the number of observations is not equal to the number of classes in a classification dataset. This imbalance leads to inconsistent and inaccurate prediction results.

Most models that are built using the imbalanced data will have a bias towards predicting the majority classes in the dataset and ignore the minority classes. Class imbalance is identified by observing the distribution of classes within your data or using visualizing libraries to plot the class distributions. 

Imbalanced-Learn has various techniques that will be used to handle this problem. These techniques are such as Random Undersampling technique: resample all classes but the majority class, Random Oversampling technique: resample all classes but the majority class.
In this tutorial, we shall discuss these techniques in detail and implement them practically using Python.

#### Key takeaways 
1. What is Imbalanced-Learn?
2. How to install Imbalanced-Learn.
3. Exploring Imbalanced-Learn methods and techniques.
4. Implementing Undersampling technique and Oversampling technique.
5. Model building with Class weight balancing

#### Article quality
In this tutorial we will use two approaches to handle the imbalanced dataset as follows:
1. Random Undersampling: Here we resample all classes but the minority class to reduce model bias.
2. Random Oversampling: Here we resample all classes but the majority class to ensure that the model learns from every dataset.
We will perform Model building with both oversampled balanced class and undersampled balanced class. After that, we will compare the results using class weight balancing to evaluate the model performance. This ensures we have a more reliable model.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Fill the section on Article Quality.

**Comment by charles721** [comment]
Hello @lalith1403, I have added the article quality section.
Thanks

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
