### ISSUE TITLE
[Networking] Stateful vs. Stateless Architectures

### ISSUE THREAD

**Issue by Su-sid** [section-engineering-education/engineering-education#5013]
### Proposed title of the article
Stateful vs. Stateless Architectures

### Introduction paragraph (2-3 paragraphs):
Networks protocols control how data is transferred between different devices in a network. However, you should understand that networking protocols are divided into two: stateful and stateless protocols. Additionally, whether something is stateful or stateless depends on how long the state of interaction with it is being recorded and how that information needs to be stored. 

### Key takeaways: 
- Definition and basic history of stateful and stateless architectures
- The various protocols that utilize the two architectures
- The differences between the two architectures 
- Some of the advantages of each of the architectures 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
https://github.com/section-engineering-education/engineering-education/issues/2966
