### ISSUE TITLE
Solving a one way anova with Excel and testing for normality and homogeneity using python 

### ISSUE THREAD

**Issue by Mirror98** [section-engineering-education/engineering-education#5017]
#### Solving a one way ANOVA with Excel and testing for normality and homogeneity using Python 
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Over the years, data has been an essential part of how the world works. These data range from GDP to blood samples to every aspect of the world. As data grew, statistics found ways to make meaning of them. One of them is the analysis of variance. ANOVA is a collection of statistical models and their associated estimation procedures to analyse the differences among means.

As we entered more technologically advanced stages, tools were created for ease in analysing this data. For ANOVA, Microsoft came up with statistical add-ins within Excel to solve some of these problems. Though the effort, Microsoft Excel was still limited. There came tools like R-studio and Python. With Python, the test for normality and homogeneity became easy. 

This tutorial will focus on box plots to test the normality of a one way ANOVA and Bartlett's rule for homogeneity with Python.

#### Key takeaways 
At the end of the tutorial, the reader will be able to:
- Use Excel to create an ANOVA table. 
- Install necessary Python dependencies to create a box plot 
- Test for normality using a box plot 
- Test for homogeneity using Bartlett's rule
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @lalith1403, please check this topic when you get a chance.

**Comment by Mirror98** [comment]
@lalith1403 sir don't forget about this review.

**Comment by lalith1403** [comment]
Hello @Mirror98, Can you check for grammatical errors? There are several grammatical errors in the proposal. Use services such as Grammarly.

**Comment by lalith1403** [comment]
Topic is really interesting.

**Comment by Mirror98** [comment]
@lalith1403, I've made the necessary changes

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
