### ISSUE TITLE
Introduction to D3DImage

### ISSUE THREAD

**Issue by Walucy98** [section-engineering-education/engineering-education#5023]
###Introduction
The goal of this tutorial is to introduce a new feature called D3DImage. D3DImage is a new Image Source object that allows a custom Direct3D (D3D) surface to be blended with WPF's native D3D surface, enabling a whole new level of interoperability between WPF and DirectX. Despite Tim's earlier declaration, D3DImage was not included in the beta release of SP1.

#### Key takeaways 
- What is an Image Source?
- Creating the D3DImage
- Enter D3DImage... Exit Airspace Restrictions
- Composing a Custom D3D Scene with the WPF Scene
### Conclusion
At the end of this tutorial, the reader will be able to understand what is D3DImage and how to create it. The reader will also understand what is image source and how to compose a custom D3D Scene with the WPF scene.

happy reading

**Comment by Kayere** [comment]
Hello @Walucy98, please provide more information on the topic.

**Comment by Walucy98** [comment]
> torial is to introduce a new feature called D3DImage. D3DImage is a new Image Source object that allows a custom Direct3D (D3D) surface to be blended with WPF's native D3D surface, enabling a whole new level of interoperability between WPF and DirectX. Despite Tim's earlier declaration, D3DImage was not included in the beta release of SP1.
> 
> #### Key takeaways
> * What is an Image Source?
> * Creating the D3DImage
> * Enter D3DImage... Exit Airspace Restrictions
> * Composing a Custom D3D Scene with the WPF Scene
> 
> ### Conclusion
> At the end of this tutorial, the reader will be able to understand what is D3DImage and how to create it. The reader will also understand what is image source and how to compose a custom D3D Scene with the WPF scene.
> 
> happy reading

**Comment by Walucy98** [comment]
> Hello @Walucy98, please provide more information on the topic.

Hey @Kayere please i have  provided more information

**Comment by WanjaMIKE** [comment]
This topic is still not unique enough. We usually refrain from publishing articles found on other numerous blog sites such as https://www.codeproject.com/Articles/28526/Introduction-to-D3DImage
