### ISSUE TITLE
[Languages] Introduction to  PostCSS: A Beginner's Guide

### ISSUE THREAD

**Issue by njorosirmie** [section-engineering-education/engineering-education#5025]
#### Proposed title of article
Introduction to  PostCSS: A Beginner's Guide

#### Proposed article introduction
PostCSS is a solution that uses JavaScript plugins to transform CSS. It comes with a large ecosystem of plugins that may help you improve  CSS authoring experience. You have the option of selecting your own plugin or writing your own.
PostCSS plugins, in general, allow you to write basic CSS as normal, and when called, they will step through your code to do the change you need.
 In this tutorial, we are going to discuss more on Getting started with PostCSS

#### Key takeaways 
By the end of this tutorial, the reader will have understood the following concepts.

- Overview on what is PostCSS
- Why we should use PostCSS
- PostCSS, Sass, and Less differences
- Quick PostCSS setup using Codepen
- Other setup methods

#### Article quality
This will be a unique article with detailed information on PostCSS. This article will help the reader to understand the concept of PostCSS in a simpler and better way. It will also have more information on the concept of Quick PostCSS setup using Codepen which is shallowly covered in other official docs.

#### References
N/A

**Comment by Kayere** [comment]
Hello @njorosirmie, we thank you for submitting your topic.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to explore another more in-depth topic.
