### ISSUE TITLE
Understanding the downsides of load balancing

### ISSUE THREAD

**Issue by martha-ngugi** [section-engineering-education/engineering-education#5029]
#### Proposed title of article
Understanding the downsides of load balancing

#### Proposed article introduction
A single server cannot handle all the workload of a given application. It is likely to experience issues with performance, availability, and economics.
In order to handle increased traffic, increasing the capability if processing requests is required and can be achieved either by scaling up or scaling out.
However, the machine fails at times and the cost of using high specification machine may be huge to even afford. Spreading the workload over multiple machines may be a better approach, hence use of load balancing is recommended. But this approach may experience several challenges. In this article, we will cover some of the challenges and possible solutions.

#### Key takeaways 
At the end of this article the leaner will understand:
- the concept of load balancing and several approaches to achieve it
- the advanced challenges of load balancing
- the possible solutions that can be implemented to curb the challenges

#### Article quality
The article will concentrate more on the advanced challenges and their possible workarounds experienced with load balancing

#### References
N/A

**Comment by Kayere** [comment]
Good topic @martha-ngugi - Approved.

**Comment by WanjaMIKE** [comment]
Closed #5029 via #5288
