### ISSUE TITLE
[Languages] Mocking with Junit and Mockito- The Why and How

### ISSUE THREAD

**Issue by ehizman** [section-engineering-education/engineering-education#5031]
#### Proposed title of Article
[Languages] Mocking with Junit and Mockito- The Why and How

#### Proposed article introduction
In the real world, software has dependencies. We usually have services that depend on a database or on some other third party service. The concept of mocking enables us to verify that our code works without addressing concerns about dependencies. The theory is that if my code works as designed and the external dependencies work as designed, then when integrated my system should work as designed.

Mockito is a mocking framework in Java. It can be integrated with Java's testing framework JUnit. Mockito allows us to mock objects whose behaviour we can specify within our test.

In this tutorial we will cover:
1. A brief explanation of how Mock objects work
2. Some theories about when to use Mockito and why you want to use Mockito
3. Setting up Mockito as a dependency to a Java project
4. Stubbing the data that a method returns
5. verifying interactions with side effects
6. using argument captors
7. returning custom mocked responses form methods

#### Key takeaways
At the end of this tutorial, the reader should:
1. have a basic understanding of how mock objects work and about the two main types of mocking frameworks
2. understand why mocking is important and when mocking should be done.
3. know how to add Mockito to a Java project
4. know how to stub using Mockito and how to use simple stubbing mechanisms
5. know to verify arguments using ArgumentCaptor
6. know how to create custom responses from mocks that depend on the arguments of the call.

#### Article quality
The theory behind mocking and stubbing is so vast and can be confusing for newbies to unit testing.
My article provides an insight into the two main types of mocking frameworks. As per my research,
this is rarely discussed by tutorials on mocking and Mockito. 
My article gives an exploratory analysis of mocking and stubbing using Mockito's static methods, why mocking is important, scenarios when mocking should be done and how mocking should be done.
Finally, my article demonstrates how to perform mocking in unit tests by leading the readers through the process of building a hostel management system using Java, Mockito and Java spark framework

#### References
https://site.mockito.org/
https://reflectoring.io/spring-boot-web-controller-test/
https://dzone.com/articles/the-concept-mocking
https://blog.cleancoder.com/uncle-bob/2014/05/10/WhenToMock.html
https://www.thoughtworks.com/insights/blog/mockists-are-dead-long-live-classicists

**Comment by Kayere** [comment]
Good topic @ehizman - Approved.

**Comment by ehizman** [comment]
Thank you @Kayere

**Comment by WanjaMIKE** [comment]
Closed #5031 via #5693
