### ISSUE TITLE
[Blockchain] Understanding the 51% attack on blockchain

### ISSUE THREAD

**Issue by ephnjor2021** [section-engineering-education/engineering-education#5036]
#### Proposed title of article
Understanding the 51% attack on blockchain

#### Proposed article introduction
A 51% attack occurs a single person or group of people gains control of over 50% of a given blockchain's hashing power. This is achieved by renting mining hash power from a third party.
The attackers gain the ability to block new transactions being confirmed and also change the ordering of new transactions. The malicious agents can then rewrite parts of a blockchain and reverse the transactions.
In the proposed article, we will cover in-depth the 51% attack on blockchain and bitcoin, understand what it entails, and possible ways to prevent it. 

#### Key takeaways 
At the end of the article, the learner will understand:
- what is 51% attack and its impact on blockchain and bitcoin
- the risks involved with 51% attack
- the difference between the 51% attack and 34% attack
- highlight some of the blockchain platforms that have experienced 51% attack
- the ways to prevent the 51% attack and if it can reoccur

#### Article quality
The article will cover the in-depth analysis of the 51% attack and compare it with another attack method as highlighted in the proposed topic key takeaways unlike the other articles in the blog sites which have not covered the subject in detail.

#### References
N/A

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
