### ISSUE TITLE
[Containers]Offloading CPU intensive Back-ends using Docker, Docker-Compose and HAProxy

### ISSUE THREAD

**Issue by WilliamOtieno** [section-engineering-education/engineering-education#5039]
#### Proposed title of article
Offloading CPU intensive Back-ends using Docker, Docker-Compose and Ha-proxy

#### Proposed article introduction
Most web app back-ends are normally deployed in form of containers. In this article, we will learn how to orchestrate those containers as well as enable horizontal scaling by offloading the requests among the different containers.  We will spin up a simple web server in a few lines of code using NodeJS/ExpressJS then create containers from its image.

#### Key takeaways 
By the end of this article, you will be able to confidently perform the following tasks:
 - Create your custom Docker images.
 - Manage containers using Docker-Compose.
 - Understand how load balancers and reverse proxies work.
 - Horizontally scale CPU intensive tasks in your backend.

#### Article quality
 - Step-by-step in-depth guide for beginners
 - Use HA-Proxy as the load balancer instead of the common Nginx
 - Get an overview of how container orchestration is performed and apply the knowledge in other techniques e.g Kubernetes

#### References
N/A

### Conclusion
This article is not limited to NodeJS/ExpressJS servers. It can be applied to different kinds of servers including Django. Conversely, container orchestration knowledge acquired from this article can be applied in other platforms other than Docker-compose e.g Kubernetes.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @WilliamOtieno

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
