### ISSUE TITLE
Building a playlist exporter in Python using Mutagen

### ISSUE THREAD

**Issue by wanjirualice6194** [section-engineering-education/engineering-education#5041]
### Writing sample(s): 
[Top Ten UI/UX mistakes to avoid - Section EngEd](https://www.section.io/engineering-education/ten-uiux-mistakes-to-avoid/)
### Building a playlist exporter in Python using Mutagen

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Audio files play an important role in our daily lives. We store sound recordings and most of all music as audio files.

There are many types audio file in use today. Most popular being the MP3 and FLAC audio files. MP3s are a more compressed version of the FLAC audio. Generally, FLAC audio files are larger but provide better and lossless audio qualities.

Sometimes, you need to export your playlists into some format. It can be text, JSON, or whatever you may prefer. How would you go about it?

In this tutorial, we will build a program that dumps audio file tags in a JSON file.

#### Key takeaways
By the end of this tutorial, the reader will be able to do the following:

1. Setup Mutagen audio tag manipulation library.
1. Read MP3/FLAC meta tags from a single audio file.
2. Read MP3/FLAC meta tags from multiple audio files
3. Write audio tags to files.
4. Dump the audio tags to a JSON file.

#### Article quality
This article provides deep explanation on what is expected in each step and how it works.

#### References
N/A

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
