### ISSUE TITLE
Working with CSV files in java 

### ISSUE THREAD

**Issue by tesswambui** [section-engineering-education/engineering-education#5043]
#### Topic Suggestion
Working with CSV files in java 
#### Proposed title of article
Working with CSV files in java
#### Proposed article introduction
The CSV represents Comma-Separated Values. It is a basic document design which is utilized to store plain information in straightforward text structure, like an accounting page or data set. The documents in the CSV organization can be imported to and sent out from programs (Microsoft Office and Excel) which store information in tables. The CSV document utilized a delimiter to recognize and isolate various information token in a record. The CSV record design is utilized when we move plain information between programs that locally work on incongruent organizations.

#### Key takeaways 
- Step by step instructions to make CSV document, utilizing notepand and Microsoft Excel.
- Java String.split() technique. 
- Java scanner class. 
- Using open CSV API.

#### Article quality
In this article I will acquaint client with CSV documents utilizing java,am additionally going to take the client through the strategies of making a csv record utilizing note pad and Microsoft Excel, likewise I will disclose to the client how CSV records are perused and deciphered utilizing various techniques. I trust the client will appreciate to know how csv documents work in java.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
This topic is already covered by a lot of blog sites - How does your article differ from them? @tesswambui

**Comment by tesswambui** [comment]
hello @ahmadmardeni1, I have looked at those articles published in those blogsites and I found them offering very shallow content. Also its hard to understand the content published. In my article am going to dive deep into csv files in java and how they work, I will use a beginner friendly language to deliver the content unlike the already published articles.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @tesswambui
