### ISSUE TITLE
[Android] Text Styling in Android Jetpack Compose

### ISSUE THREAD

**Issue by codewithjudy** [section-engineering-education/engineering-education#5044]
#### Proposed article introduction
Text is an essential component of any user interface, and Jetpack Compose makes it easier to display or write text.
Compose makes use of composition in its building blocks, which means you don't have to overwrite properties and methods or extend large classes to get a specific composable design and logic to work the way you want it to. 

To style its content, the Text composable has a number of optional parameters. 

In this article, we'll explore a set of attributes that we can use to customize the appearance of our text. 

#### Key takeaways 
- Understand the Text Composable.
- A quick overview of normal text styling.
- Adding an external font family to the Text.
- Build annotated strings.
- Styling the annotated strings.

#### Article quality
Because Jetpack compose is a new Android technology that acts as a replacement of the normal XML layouts, the article will be simple to read, for those readers who are coming from using XML to using Jetpack Compose. It will be clear and concise.

#### References
 - Jetpack Compose Documentation

**Comment by WanjaMIKE** [comment]
Unfortunately, most of your key takeaways appear to be covered in numerous tutorials. Feel free to suggest another topic. Thanks
