### ISSUE TITLE
[API] Deploy a Django App With Gunicorn, Nginx, & HTTPS without PostgreSQL

### ISSUE THREAD

**Issue by vila-dev** [section-engineering-education/engineering-education#5045]
### Introduction
Building a Django application from concept to completion is a time-consuming but rewarding process. This tutorial will walk you through the cycle step by step, providing an inside and out guide that starts with a simple Django application and progresses through Gunicorn, Nginx, area enlistment, and security-focused HTTP headers. After going over this tutorial, you'll be better prepared to put your Django application into production and serve it to the rest of the world.

#### Key takeaways 
- Starting With Django and WSGIServer
- Setting Up a Cloud Virtual Machine (VM)
- Using Django’s WSGIServer in Development
- Putting Your Site Online With Django, Gunicorn, and Nginx
- Making Your Site Production-Ready With HTTPS

#### Article quality
Many articles have applied the use of PostgreSQL. My article is intended to avoid bulky operations to bring simplicity for beginners. It will be simple to understand, to add more knowledge to programmers and developers

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @vila-dev

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.
