### ISSUE TITLE
How to set up Svelte with vite, TypeScript and Tailwind CSS

### ISSUE THREAD

**Issue by Joakim-gakure** [section-engineering-education/engineering-education#5047]
#### Proposed title of the article

How to set up SvelteKit with Vite, TypeScript, and Tailwind CSS 

#### Proposed article introduction

Svelte is a JavaScript front-end framework for building reactive and interactive UI components like React, Angular, and Vue. Unlike its peers would ship a JavaScript runtime to the browser to make your code work, Svelte is a compiler. It converts the declarative code that you write into imperative code that works with native browser APIs. This produces highly performant applications in a very small codebase, allowing you to write complex applications. Svelte also runs with no virtual DOM. This guide will build a portfolio application that shows how to use Vite, TypeScript, and Tailwind CSS in a Svelte application.

#### Key takeaways 

- What is Svelte
- What is Vite
- What is TypeScript
- What is Tailwind CSS
- Bootstrap a Svelte template
- Set up Vite
- Set up TypeScript
- Set up Tailwind CSS
- Build a Svelte portfolio web app using TypeScript and Tailwind CSS

#### Article quality

This guide will explain how to set up Vite, TypeScript, and Tailwind CSS in a Svelte application. We will build a simple app using Svelte with Vite, TypeScript, and Tailwind CSS.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Only suggest one topic at a time

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Joakim-gakure 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #5047 via #5396
