### ISSUE TITLE
[LANGUAGES]Creating a pie chart from scratch using JavaScript, HTML Canvas, and CSS

### ISSUE THREAD

**Issue by munubi254** [section-engineering-education/engineering-education#5048]
### Topic Suggestion
Creating a pie chart from scratch using JavaScript, HTML Canvas, CSS

### Writing sample(s): 
[My samples](https://www.section.io/engineering-education/authors/sandra-moringa/)

#### Proposed title of the article
Creating a pie chart from scratch using JavaScript, HTML Canvas, CSS

#### Proposed article introduction
Suppose you don't want to use any chart library, you will have to implement yours from scratch. We will see how to do that using JavaScript, HTML Canvas, and CSS. We will pull data from an API and also add ours using loops or any other tool.

#### Key takeaways 
- Creating charts
- Manipulating the HTML Canvas for the charts
- Formatting the charts using CSS

#### Article quality
It's unique in that it doesn't use any library or any other third-party tool.

#### References

**W3Schools**
1. https://www.w3schools.com/html/html5_canvas.asp
2. https://www.w3schools.com/html/html_css.asp

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @munubi254
