### ISSUE TITLE
Understanding 20 AWS Services using Facebook Architecture as a Case Study

### ISSUE THREAD

**Issue by Moscode** [section-engineering-education/engineering-education#5051]
#### Proposed title of article
Understanding 20 AWS Services using Facebook Architecture as a Case Study

#### Proposed article introduction
AWS services are web services provided by the cloud company for seamless usage and development for the developers using the cloud as a service. 

AWS services that will be discussed are:
* EC2
* ELB
* S3
* Route53
* Lambda
* SNS
* SES
* SQS
* CloudWatch
* Kinesis
* ElastiCache
* RDS
* DynamoDB
* Glue
* Edge Location
* CloudFront
* Rekognition
* EMR
* RedShift
* Anthena

#### Key takeaways 
-The reader will be able to setup a free tier plan on AWS for experimental purpose
- The reader will be familiar with 20 AWS services 
- The reader will have the full understanding of how AWS services can be implemented in a product

#### Article quality
Unlike other articles, this article will focus on the implementation of AWS services using Facebook.com as a use case.

#### References
+ https://allcode.com/top-aws-services/
+https://aws.amazon.com/free/

### Templates to use as guides

**Comment by ahmadmardeni1** [comment]
We are looking for programmer-centric concepts explained in fun and intuitive ways. @Moscode 
Please feel free to suggest an alternate topic to explore. 🚀
