### ISSUE TITLE
[Machine Learning] How to build a GlassBox Model using InterpretML Python

### ISSUE THREAD

**Issue by charlesndirutu33** [section-engineering-education/engineering-education#5052]
#### Proposed title of article
[Machine Learning] How to build a GlassBox Model using InterpretML Python

#### Proposed article introduction
Glass box models are models that are transparent to the user. In a glass box model, all the features and parameters are known to the user and they know the criteria used by the model to reach its prediction results and conclusion. This gives full transparency and one can know how the model works and functions behind the scene.

Over the years, many machine learning engineers have been building black-box models. Black-box models, the users do not know the internal workings and the functionality of the model. Users cannot understand these models and they end up accepting the model blindly.  Developers hide the actual risk of using these models, Glassbox model is the better alternative that gives you exposure to the model.

In this tutorial, we will use InterpretML to build a glass box model. It will build a model that will be able to explain itself and give a more transparent view to the users. This will improve quality products, machine learning processes, and research. Examples of glass box models are decision tree models and linear models.

#### Key takeaways
1. Black box models vs Glass box models.
2. Example of the Glass box model.
3. How to work with InterpretML Python
4. Building a transparent.
5. Analysing the model results.

#### Article quality
This tutorial will compare two concepts of building machine learning models: Black box models and Glass box models. It will look into the traditional black-box models and some of their limitations that led to the introduction of glass box models. We will dive into a glass box model and build a custom transparent model from scratch.
Finally, we will analyze the prediction results made by the model so that we can have a better understanding of the model.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
