### ISSUE TITLE
Understanding the Resilient Packet Ring Technology

### ISSUE THREAD

**Issue by eunice-wanjiku** [section-engineering-education/engineering-education#5058]
#### Proposed title of article
Understanding the Resilient Packet Ring Technology

#### Proposed article introduction
The Resilient Packet Ring technology is MAC-Level Ethernet based that is created for metro networks. It guarantees a bigger bandwidth efficiency by allowing the sharing of links by the bandwidth. It also allows both high and low priority classes of service.

It is designed and set up to provide SDH networks resilience to increase the efficiency of the IP as well as the Ethernet services. Operations are run through ringlets set up from the creation of RPR stations for traffic flow. 

#### Key takeaways 
1. Basics of Resilient Packet Ring
2. Adopted types of transmission media.
3. Traffic queues and Class of Service
4. Limitations related to Resilient Packet Ring

#### References
N/A
### Templates to use as guides
N/A

**Comment by ahmadmardeni1** [comment]
How does your article differ from what is already published? @eunice-wanjiku

**Comment by eunice-wanjiku** [comment]
@ahmadmardeni1 Although I will research different sources and understand the various ideas, I will ensure this article is original by individually analyzing my concepts.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @eunice-wanjiku 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
