### ISSUE TITLE
Object-Oriented Programming in Python vs Java

### ISSUE THREAD

**Issue by Romans70** [section-engineering-education/engineering-education#5062]
#### Introduction
In object-oriented programming, a set of data properties is combined with functions to form a "object." OOP languages are often class-based, which implies that a class describes the data characteristics and methods that are used to create objects, which are members of the class. In this article we'll contrast OOP between java and Python. Moving from Java to Python can be difficult because of Python's methodology towards object-oriented programming (OOP). Python and Java adopt quite distinct approaches to working with objects, variable types, and other language features. It might be difficult to switch between the two languages.

#### Key takeaways 
1. Create a simple Java and Python class.
2. Examine the differences between Python and Java in terms of object characteristics.
3. Java methods and Python functions.
4. Learn about inheritance and polymorphism methods.
5. Examine the differences between Python and Java in terms of reflection.
6. Apply everything in a full class implementation.

#### Article quality
This will be a distinctive article with detailed information. In this article, I will use basic language to ensure that anybody reading it understands the contents. I'll make sure that this article is useful to the whole EngEd and that it goes above and beyond official documentation.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, objected oriented programming in Java and Python has already been covered in numerous articles. Feel free to suggest another topic. Thanks
