### ISSUE TITLE
[Machine Learning]: Converting Datasets in PASCAL VOC to COCO format for Object Detection

### ISSUE THREAD

**Issue by srishilesh** [section-engineering-education/engineering-education#5067]
### Topic Suggestion
Machine Learning

### Writing sample(s): 
**https://www.section.io/engineering-education/authors/srishilesh-p-s/**

#### Proposed title of article
Converting Datasets in PASCAL VOC to COCO format for Object Detection

#### Proposed article introduction
Object detection refers to the capability of computer and software systems to locate objects in an image/scene and identify each object. Detection of objects are either represented using XML files or JSON files. Each representation has it's own pros and cons. In this article, we will be understanding these representations in-detail, and how to convert an XML file (PASCAL VOC) into a JSON file (COCO).

#### Key takeaways 
This article will be an introduction to:
- Understanding PASCAL VOC and COCO formats
- Understand how these help in detection of objects
- Understanding the structure of both the formats in-detail
- Learning to convert PASCAL VOC format to COCO format, from scratch. (Conversion of COCO to PASCAL VOC will be part 2 of this)

#### Article quality
- Most of the articles on the internet explains what these dataset formats are and how to use them, but we don't have any explaining how to convert from one to another, or why we use them.
- Firstly, we will be understanding both the formats, and then building python scripts from scratch, to convert from one format to another
- We have automated tools that converts, but by reading this article, the author can build one such tool.

#### References
- https://paperswithcode.com/dataset/pascal-voc
- https://towardsdatascience.com/how-to-work-with-object-detection-datasets-in-coco-format-9bf4fb5848a4
- https://towardsdatascience.com/coco-data-format-for-object-detection-a4c5eaf518c5

### Conclusion
The reader will understand how to:
- Work with PASCAL and COCO formats
- Understand why they are used for
- Convert from PASCAL to COCO format

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @srishilesh

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic due to inactivity.
It can be reopened.

**Comment by srishilesh** [comment]
Hey @lalith1403 ,

On thinking through the topics that I could cover under this, I felt that this article would be informative/understandable, only the reader has some basic idea on what PASCAL VOC and COCO is - which I think is already an extensive topic.

Putting all (PASCAL VOC, COCO and Conversion implementation) together in a single article would make it too lengthy.

So, can I have this issue as "Part 2"? while the "Part 1" discusses about the concepts of why and how annotation is done, what bounding boxes are, history behind PASCAL VOC and COCO, how are they different from each other, what types of problems does each type support, and so on.

What do you think? Shall I create a new topic suggestion for the "Part 1"?

Thanks.

**Comment by lalith1403** [comment]
I think covering it in a single article would be better for the readers. That way, this can be a single article for everything related to object detection data formats.
