### ISSUE TITLE
[Languages] How to Build an IP Address Tracker with Mapbox API and Vue.

### ISSUE THREAD

**Issue by Abiola-Farounbi** [section-engineering-education/engineering-education#5068]
### Writing sample(s): 
- https://egghead.io/blog/how-to-use-the-animate-on-scroll-aos-library-in-vue
- https://www.freecodecamp.org/news/build-accessible-vue-applications/

#### Proposed title of the article
How to Build an IP Address Tracker with Mapbox API and Vue.

#### Proposed article introduction

An IP address is dynamic and can be used for different purposes in an application. With given access to a user's IP address, it's easy to find the location, time zone, and ISP of the user.
In this guide, we’ll build an  IP Address Tracker Application from scratch, using the vue.js framework and the Mapbox API. We’ll cover the process from building the front-end scaffolding up to implementing the API to handle the user's IP address, then go further to visualize the location on the map using the Mapbox API. At the end of this tutorial, readers would also be able to build and deploy the application on Netlify.

#### Key takeaways 
- Understanding of an IP Address.
- The Features of the IP Address Tracker.
- Scaffolding The Front End With Vue.js.
- Integrating the APIs in the Vue App.
- Creating Interactive Map Display with Mapbox API.

#### Article quality
- In-depth guide particularly with Vue.js.
- Step-by-step guidelines for beginners.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @Abiola-Farounbi
