### ISSUE TITLE
[Android] Creating an Custom Animated Shimmer Effect Jetpack Compose 

### ISSUE THREAD

**Issue by kirwa-elyjah** [section-engineering-education/engineering-education#5070]
#### Introduction
In this tutorial, I'm going to show the reader how to implement an Animated Shimmer effect in android applications using a modern UI toolkit Jetpack Compose. The shimmer effect gives the impression of extra light on the desired areas of the face. It makes the app look radiant and get a beautiful glow. Usually, the shimmer effect is used to show that the app is loading some data which maybe from the internet. When data is loaded, the shimmer effect stops and the user can get a view of the items that were being loaded.

#### Key takeaways 
- Implementing Shimmer Effect in Jetpack Compose
- Creating Shimmer Grid Items
- How to customize time, color, and Animate the Shimmer effect

#### Article quality
My topic is unique in that most of the written articles on the Jetpack Compose Shimmer Effect uses libraries. In this article, I will show the reader on how to create the Shimmer Effect by writing code only without using any library.

#### References
https://developer.android.com/jetpack/compose/animation

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks

**Comment by WanjaMIKE** [comment]
Closed #5070 via #5753
