### ISSUE TITLE
[Android] Creating A Password Strength Checker Using Kotlin in Android

### ISSUE THREAD

**Issue by essy-shiro** [section-engineering-education/engineering-education#5072]
#### Introduction
As an Android developer, one of the most important things to remember is to protect your app. It's necessary to double-check user inputs and raise awareness about the need of using a strong password. In this article, I'll show the reader how to develop a Password Strength Checker in your app,  which will check user inputs, and provide information on how the user may enhance their password strength.

#### Key takeaways 
- Importance of password strength checker in an android app
- How to create a single class that will handle checking of password strength as the user types in the password
- 

#### Article quality
In this article, I will not use any third-party libraries to check the strength as it is done in most articles. I will also use Kotlin language since it is the preferred android development language in 2021

#### References
- https://developer.android.com/

**Comment by WanjaMIKE** [comment]
How will your article differ from other existing documentations such as https://codesource.io/create-a-password-strength-calculator-using-kotlin/

**Comment by essy-shiro** [comment]
@WanjaMIKE i am going to do it in a simpler way for better understanding. This will be beginner friendly to those who have understanding of kotlin language

**Comment by essy-shiro** [comment]
Hello @WanjaMIKE

**Comment by essy-shiro** [comment]
@WanjaMIKE @ahmadmardeni1 @louisefindlay23  I never got a response about this issue

**Comment by louisefindlay23** [comment]
@essy-shiro, your article still needs to have some unique value. Is there any adjacent topics you can cover to round out your article or any valuable perspective you can bring or tips to add?

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
