### ISSUE TITLE
[Language] INTRODUCTION TO TRIES IN C#

### ISSUE THREAD

**Issue by munyite-megzs** [section-engineering-education/engineering-education#5077]
### Topic Suggestion
INTRODUCTION TO TRIES IN C#

#### Proposed article introduction

 Trie is a very useful data structure that is mostly used to perform auto-completion and searching. Using Trie, search complexities can be brought to optimal limit (key length).  In this article, we shall get to know what Tries are. We shall get deeper into giving practical examples of how they can be used in real-life scenarios. 

#### Key takeaways 
By the end of this article, the user will be able to:-
1. Understand what a Trie is. Know the time and space complexity of operations performed in it.
2. Build a Trie from Scratch. 
3. Lookup a Word using Tries,
4.  Know how to traverse a Trie. 
5. Remove a Word
6. How to perform autocompletion using Tries.

#### Article quality

This will be a step-by-step guide that will give the reader a clear picture of what a Trie is. It will use visuals a lot to explain the concept. I will give several examples of how one can apply tries as one develops software. 

#### References
N/A

**Comment by WanjaMIKE** [comment]
@munyite-megzs How does this article differ with other pre-existing documentation such as https://cis300.cs.ksu.edu/trees/tries/intro/#:~:text=A%20trie%20is%20a%20nonempty,a%20word%20in%20the%20set.

**Comment by WanjaMIKE** [comment]
I think most of your key takeaways are covered in numerous articles as suggested above. Feel free to suggest another topic. Thanks
