### ISSUE TITLE
[Android] Getting started with Intents in Android development using Kotlin

### ISSUE THREAD

**Issue by davidginmaina** [section-engineering-education/engineering-education#5079]
### Topic Suggestion
Getting started with Intents in Android development using Kotlin

#### Proposed article introduction
Android application components can communicate with one another. This connection is based on an Intent object that represents a task description. Intents are asynchronous messages that allow application components to ask other Android components for help. You may use intents to communicate with components from the same application as well as components from other apps.

In this tutorial, we will discuss more on intents and how we can implement it in Android using Kotlin.

#### Key takeaways 
- Overview of what is  Intents
- Types of Intents
- How to build an intent
- Examples of explicit and Implicit intents
- Detect suspicious  launches of intents
- Intent resolution

#### Article quality
This will be a detailed article and a unique one. I will use simple language for anyone to understand the concepts easily. I will also add more information on the concept of Intent resolution and Detect suspicious launches of intents which are shallowly discussed in other official documentation.

#### References
N/A

**Comment by WanjaMIKE** [comment]
@davidginmaina will you build an application showcasing all these types of intents?

**Comment by Davidmaina870** [comment]
Hello, @WanjaMIKE 
 Yes it will be an application that will employ all the mentioned types of intents. It will use simple concepts of Android and kotlin language to allow all the readers to understand and implement this in their applications they will be building.
Thank You.

**Comment by WanjaMIKE** [comment]
Okay, let's ensure that it adds value to the community. Thanks
