### ISSUE TITLE
[Languages] Exploring Set and Map in JavaScript

### ISSUE THREAD

**Issue by LeahKui** [section-engineering-education/engineering-education#5087]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
[Languages] Exploring Set and Map in JavaScript

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Exploring Set and Map in JavaScript

Use keyword research to improve your article's SEO.

#### Proposed article introduction
In JavaScript, developers frequently spend a significant amount of effort determining which data structure to employ. This is because choosing the right data structure might make it easier to manipulate that data, later on saving time and making code more understandable. Objects and Arrays are the two most used data structures for storing collections of data. Objects are used to store key/value pairs, whereas Arrays are used to store indexed lists.
However, in 2015 JavaScript introduced ECMAScript 6 (ES6) to provide a better development experience for developers. The ES6 introduced maps and sets to eliminate the need for developers to create them using primitive data types. Maps are like objects, and Sets are like arrays.
In this article, we will dig deeper into the concepts of  Set and Map. Also, we will have a look at their methods and properties and include practical examples.
#### Key takeaways 
1. Understanding Set in JavaScript
Set methods and properties with real use case scenarios
Add method
Delete method
Clear method
Has method
Size property

2. Understanding Map in JavaScript
Map methods and properties with real use case scenarios
Set method
Delete method
Clear method
Has method
Size property

3. The differences between ES6 Set and Map
4. The advantages of ES6 Set and Map over arrays and methods

#### Article quality
This tutorial will explore in-depth the concept of Map and Set in JavaScript. It will look at their differences and advantages over using normal arrays and objects.
It will also use real use case scenarios for readers to gain more understanding.

#### References
[MDN Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set)
[JavaScript Sets](https://www.w3schools.com/js/js_object_sets.asp)
[JavaScript Maps](https://www.w3schools.com/js/js_object_maps.asp)
[Set and Map](https://javascript.info/map-set)

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appears to be oversaturated. We usually focus more on unique projects. Feel free to suggest another topic. Thanks
