### ISSUE TITLE
Creating road layout programmatically using Matlab functions

### ISSUE THREAD

**Issue by vitalisodhis** [section-engineering-education/engineering-education#5089]
#### Proposed title of article
Creating road layout programmatically using Matlab functions.

#### Proposed article introduction
Road layout can be designed using Matlab codes. Matlab supports a variety of functions that can be used to define road layouts programmatically. Through these functions, different road layouts like straight roads, junctions, roundabouts, and road lanes can be achieved. These structures can be joined to form a road network.
In Matlab, road layout created programmatically has points defined as coordinates in a 2D graph or 3D graph for a complex road network. Also, a driving scenario can be created by inserting blocks in the road layout to simulate traffic flow.
In this article, we are going to discuss how to create different road layouts using codes and then graphically displaying the plotted roads. This is helpful in road designs simulation andtraffic simulations to help solve traffic problems. 

#### Key takeaways 
- Defining and plotting coordinates in 2D and 3D graphs.
- Designing road layout using codes.
- Using driving scenario functions.
- Basic understanding of traffic simulation.

#### Article quality
In this article, we implement road layout design and driving scenario  programmatically  using codes other than using the driving scenario designer app.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
