### ISSUE TITLE
Diving into Svelte by building a TodoList

### ISSUE THREAD

**Issue by dro-1** [section-engineering-education/engineering-education#5098]
#### Proposed title of article
Diving into Svelte & Firebase by building a TodoList

#### Proposed article introduction
[Node.js] You might be wondering ' What is Svelte? '. Well, Svelte is a relatively new Javascript Framework created by Rich Harris that has brought about a radical change in how frameworks go about editing the DOM(Document Object Module). The big three frameworks (React, Angular, Vue) we currently have mostly advise developers to use declarative code when building out components as opposed to imperative code. For context, writing declarative code is a programming paradigm that encourages developers to simply define the end state of a particular component and the framework handles how to go about getting to that state. Imperative code on the other hand encourages developers to follow through with the updating of the component at every step of the way till we get to our final destination.

Svelte instead runs at build time, compiles our code, and spits out imperative code that updates our DOM in the most efficient way possible. This eliminates the need for a Virtual DOM which is used in React and Vue to update the DOM based on the difference between the current DOM and what the DOM is supposed to be. It also takes the good parts of Vue as components can have scoped styles that don't affect nested elements as well as updating state by simply changing the value of a variable. Topping all of these, Svelte ships with its in-built methods of storing state ( think Redux for React or VueX for Vue ) and it is more lightweight and performant when compared to React App.

#### Key takeaways 
1. Learners will have learned about Svelte and its perks
2. Learners will learn how to set up a Svelte App
3. Learners will learn how to build basic Apps with Svelte
4. Learners will learn how to use Svelte with Firebase

#### Article quality
My article is unique as I take a beginner through the motions of explaining what Svelte is, the advantages it brings as well as its disadvantages, and we finally go-ahead to use it in building a project. We also go through the motions of using Firebase as our backend. Lastly, I take into consideration how I would like an article to be if I were to read it (as a beginner) and use that to tailor how my article should be.

#### References
[Svelte 3 Blog Post](https://svelte.dev/blog/svelte-3-rethinking-reactivity)
[Svelte's Homepage](https://svelte.dev/)
[Svelte vs React Comparison](https://massivepixel.io/blog/svelte-vs-react/)

**Comment by Qodestackr** [comment]
How's your article unique from this merged: https://www.section.io/engineering-education/getting-started-with-fastify-and-svelte/
Cc: @hectorkambow @lalith1403

**Comment by dro-1** [comment]
The article in question seems to be focused on Fastify rather than Svelte. But I could add Firebase for the backend of the app to make it more unique.

**Comment by Qodestackr** [comment]
> The article in question seems to be focused on Fastify rather than Svelte. But I could add Firebase for the backend of the app to make it more unique.

Sure💯. It's still possible to cover something unique as the ecosystem is huge.

**Comment by WanjaMIKE** [comment]
> The article in question seems to be focused on Fastify rather than Svelte. But I could add Firebase for the backend of the app to make it more unique.

Could you update your key takeaways then. Thanks

**Comment by dro-1** [comment]
I've made the changes @WanjaMIKE .

**Comment by dro-1** [comment]
Hello, do you need me to make any more changes?

**Comment by dro-1** [comment]
Am I supposed to close this issue and open a new one? @WanjaMIKE

**Comment by hectorkambow** [comment]
@dro-1 

 
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved


cc @WanjaMIKE - please any any other comments you think would help - or if it needs anything else 👍

**Comment by dro-1** [comment]
Hello @hectorkambow , I'm still working on the PR for this issue. Am I to open a new one?

**Comment by dro-1** [comment]
@srishilesh , this issue has been closed though I am working on thw article here.
https://github.com/section-engineering-education/engineering-education/pull/6083

What does this mean?

**Comment by srishilesh** [comment]
Hey @dro-1 ,

You need not worry about it. Once you finish working on the changes and create a new PR, it'll be re-opened on request.
