### ISSUE TITLE
[Android] Managing Android Navigation Component Dynamically With Single Activity

### ISSUE THREAD

**Issue by kibettheophilus** [section-engineering-education/engineering-education#5100]
### Introduction
Navigation refers to the interactions that allow users to navigate across, into, and back out from the different pieces of content within your app. Android Jetpack's Navigation component helps you implement navigation, from simple button clicks to more complex patterns.

When working with a singe activity and multiple fragments(recommended), it might not be easy to control navigation component dynamically especially when you have three or more fragments that can act as start destinations.

In this tutorial, we will learn how to control the start destination dynamically e.g decide if the start destination will be on-boarding screens, login screen or dashboard screen.
### Key takeaways:
- Deep dive into navigation component
- Control start destination dynamically
- Save navigation state to shared preferences
### References
[Android Documentation](https://developer.android.com/guide/navigation)

**Comment by WanjaMIKE** [comment]
This article by @LinusMuema cover navigation components. https://github.com/section-engineering-education/engineering-education/pull/905 How will your article be different?

**Comment by kibettheophilus** [comment]
Have gone through the article and noted it was an introductory one, mine will be focused on single-activity architecture and navigation component. Which is more advanced hence readers will be supposed to have basics of navigation component(Covered by Linus' article)

**Comment by WanjaMIKE** [comment]
Unfortunately, the two articles seem similar. You will appear to duplicate content. Feel free to suggest another topic. Thanks
