### ISSUE TITLE
Setting up OpenAPI Specification in Quarkus

### ISSUE THREAD

**Issue by justusmbuvi** [section-engineering-education/engineering-education#5101]
#### Proposed title of the article

Setting up OpenAPI Specification in Quarkus

#### Proposed article introduction

[Languages] OpenAPI is extremely useful in applications. It provides a standardized platform to abstract an application but makes it accessible to other developers for development purposes. It does this by visualizing the API and allowing interactions with it without any logic implementation.

MicroProfile Specifications currently allow the use of OpenAPI 2.0 after the version 4.1 release.
This release means that Quarkus can be able to integrate it into a Reactive application for development, testing, and API visualization.
It also facilitates ongoing documentation of APIs as they are being added.

This article is focused on the integration of OpenAPI specification on a QUarkus application, configuring it, and making it available in the project.

#### Key takeaways

By the end of the article, the reader would have known the following:

- Adding OpenAPI specification for Quarkus on a project
- Configuring it in the application
- Running it
- Testing it with actual data
- Packaging an application with an OpenAPI 2.0 specification

#### Pre-requisites

For a quick and easy follow-up to this article, the following will be necessary:

- Java is installed in the environment. The latest JDK is recommended.
- A good Java IDE. IntelliJ Ultimate edition is also recommended due to its supply of necessary tools that make the app creation process easy.
- A good internet speed to be able to create the application.

#### Article quality

The article is precise and will clearly show how to use the specification for large Microprofile projects using Quarkus. It will speak of its profits as it points them out.

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Please submit one topic at a time.

**Comment by justusmbuvi** [comment]
@WanjaMIKE, I thought that this Issue: #4335  was closed when its pr #4575 was merged. Turns out it hadn't but was rather the last in the queue. Sorry, the mistake was mine but next time I will be more cautious. Thank you!!!

**Comment by justusmbuvi** [comment]
@WanjaMIKE @hectorkambow I have seen that the article that was in the queue was merged successfully, ( #4575 ) Could you re-open this issue please as we will be waiting for its approval, Thank you!

**Comment by justusmbuvi** [comment]
Thanks

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @justusmbuvi 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles(https://www.section.io/engineering-education/getting-experiential-on-a-quarkus-project/ - https://www.section.io/engineering-education/data-streams-in-quarkus-using-reactive-streams-operator/), articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
