### ISSUE TITLE
[Android] Flutter timelines in Action

### ISSUE THREAD

**Issue by diannesandra** [section-engineering-education/engineering-education#5105]
### Topic Suggestion
Flutter timelines in Action

### Writing sample(s): 
https://www.section.io/engineering-education/deploy-flask-to-gce/

#### Proposed title of article
Using Flutter Timelines to demonstarte EngEd Review Process 

#### Proposed article introduction
Timelines are progress indictors that show the level of completion of a task in the system. In most cases, timelines are used to visualiza how the progress of a task is and the percentage of completion.

Take for instance a delivery applictation that track the delivery of a rider/driver. Timelines could be used to show when the delivery guy picks up the product, when he is packaging, when he begins the journey and when he arrives at his destination.

In this article, we will demonstrate the process of reviewing articles in section using Flutter timelienes.

#### Key takeaways 
- Getting to know Flutter timelines
- Working with Flutter tielines from scratch
- Building an application that demonstarte EngEd review procedure.

#### Article quality
The uniqueness of this article is how it approaches the concept with a real life example relatatble to many readers. The most conveninet way of learning something is by using it , so besides just reading the documentation, this tutorial builds an application.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
