### ISSUE TITLE
How to Build a Full Stack Application With Tailwind CSS and Supabase in NextJs

### ISSUE THREAD

**Issue by Olanetsoft** [section-engineering-education/engineering-education#5106]
### Topic Suggestion
How to Build a Full Stack Application With Tailwind CSS and Supabase in NextJs

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

- [https://www.section.io/engineering-education/how-to-build-authentication-api-with-jwt-token-in-nodejs/](https://www.section.io/engineering-education/how-to-build-authentication-api-with-jwt-token-in-nodejs/)
- [https://www.section.io/engineering-education/how-to-build-a-clock-with-javascript-and-svg/](https://www.section.io/engineering-education/how-to-build-a-clock-with-javascript-and-svg/)
- [https://www.section.io/engineering-education/a-friendly-beginner-guide-to-typescript/](https://www.section.io/engineering-education/a-friendly-beginner-guide-to-typescript/)

#### Proposed title of the article
How to Build a Full Stack Application With Tailwind CSS and Supabase in NextJs

#### Proposed article introduction

The React Framework for Production, Next.js, provides the finest developer experience with all the capabilities you need for production: hybrid static and server rendering, TypeScript support, smart bundling, route pre-fetching, and more. There is no need to configure anything.

Supabase is a free and open-source Firebase alternative.
It includes all of the backend services you'll require to create a product. You can utilize it entirely or just the services you need, such as database, authentication, and file storage.

Tailwind is a CSS framework with a focus on utility for quickly creating bespoke user interfaces.

#### Key takeaways 
In this article, the reader will learn
- How to scaffold a NextJs project and also the basics
- How to integrate supabase into a NextJs application
- How to build a full-stack application with supabase and tailwind CSS

#### Article quality
This article provides a step-by-step tutorial to building a full-stack application with tailwind CSS and supabase in a NextJs application.

#### References
- [https://supabase.io/docs/](https://supabase.io/docs/)
- [https://nextjs.org/](https://nextjs.org/)
- [https://tailwindcss.com/](https://tailwindcss.com/)

**Comment by WanjaMIKE** [comment]
What is the focus of the article? Is it on supabase, Next.js, or Tailwind css?

**Comment by WanjaMIKE** [comment]
This topic here also seems to be covering the technologies you are suggesting https://github.com/section-engineering-education/engineering-education/issues/5033

**Comment by Olanetsoft** [comment]
@WanjaMIKE the focus is on supabase using nextJs, but the tailwind CSS is the CSS module for styling the entire app.

**Comment by Olanetsoft** [comment]
I propose to use the serverless CRUD activity in the NextJS app instead of authentication as described in the link you shared concerning similar technologies.

**Comment by WanjaMIKE** [comment]
Okay. Let's ensure that it adds value to the community. Thanks

**Comment by Olanetsoft** [comment]
Thank you
