### ISSUE TITLE
[Android] Implementing Offline Caching In Room For Data Fetched From Firebase Using Kotlin

### ISSUE THREAD

**Issue by Sephens** [section-engineering-education/engineering-education#5107]
### Topic Suggestion
[Android] Implementing Offline Caching With Room For Data Fetched From Firebase Using Kotlin

#### Proposed title of article
Implementing Offline Caching With Room For Data Fetched From Firebase Using Kotlin

#### Proposed article introduction
The Room persistence library provides an abstraction layer over SQLite to allow fluent database access while harnessing the full power of SQLite.

The most common use case is to cache relevant pieces of data so that when the device cannot access the network, the user can still browse that content while they are offline.

#### Key takeaways 
- How to use Room database
- How to cache data offline using Room.

#### Article quality
- It is user friendly for beginners  since it is easy to read and understand. The contents are arranged and organized in a way such that the reader will be able to gather crucial information on caching with room with ease. 
- This article will explain how to cache data fetched from database using Room.

#### References
- [Offline Caching In Room](https://developer.android.com/training/data-storage/room)

**Comment by WanjaMIKE** [comment]
I know there are several articles that have already covered room database. How will this topic be unique?

**Comment by Sephens** [comment]
> I know there are several articles that have already covered room database. How will this topic be unique?

This article will address room database, particularly when looking at data fetched from Firebase in order to reduce the time needed to load up data and also to enable curb difficulties resulting from poor network connectivity hence making it unique.

**Comment by WanjaMIKE** [comment]
Okay. Let's ensure that we add value to the community. Thanks

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by Sephens** [comment]
Am ready,, please reopen the topic
