### ISSUE TITLE
[Android] Implementing a Multi-Select LazyColumn in Jetpack Compose the Easiest Way

### ISSUE THREAD

**Issue by Rose-Meghan** [section-engineering-education/engineering-education#5110]
### Topic Suggestion
[Android] Implementing a Multi-Select LazyColumn in Jetpack Compose the Easiest Way

#### Proposed title of article
Implementing a Multi-Select LazyColumn in Jetpack Compose the Easiest Way

#### Proposed article introduction
A LazyColumn is a vertically scrolling list that only composes and lays out the currently visible items. It’s similar to a Recyclerview in the classic Android View system. Multi-Select LazyColumn allow one to select multiple items at once in the List.

#### Key takeaways 
- How to use Jetpack compose.
- How to create LazyColumns in Jetpack Compose.
- How to implement Multi-Select in LazyColumn.

#### Article quality
Since Jetpack compose is a new Android feature for creating Layout designs, understanding it requires simple and well explained article. Have researched on the topic and made it easy for biginners to understand. The articles present in other sites also do not cover on selecting multiple items in the List of a LazyColumn.

#### References
- https://developer.android.com/jetpack/compose/lists
- https://foso.github.io/Jetpack-Compose-Playground/foundation/lazycolumn/

**Comment by ahmadmardeni1** [comment]
What do you think of this topic? @WanjaMIKE

**Comment by WanjaMIKE** [comment]
@ahmadmardeni1 let me check it.

**Comment by WanjaMIKE** [comment]
@Rose-Meghan I believe a huge part of your key takeaways will replicate this existing article https://github.com/section-engineering-education/engineering-education/pull/3485/files

**Comment by ahmadmardeni1** [comment]
Thank you @WanjaMIKE 

Thank you for submitting your topic. @Rose-Meghan 

Please suggest an alternate topic to explore. 🚀
