### ISSUE TITLE
[Security] Firewalls and Intrusion Detection Systems

### ISSUE THREAD

**Issue by Romans70** [section-engineering-education/engineering-education#5111]
#### Introduction
Firewalls block precise actions from stepping into them at the same time as intrusion detection structures look for intruders and notify structure directors while the machine is breached. Firewalls are very black and white due to the fact that the wall is up or down. Therefore, a firewall is much like a volt at a financial institution due to the fact that no one can get in without a right of entry code. Intrusion detection structures are larger, much like the officials staffed to observe the financial institution's clients for feasible abnormalities, intruders, and bizarre behavior. When the officials discover a problem, they delve deeper into it to find not only the best solution to the problem, but also to keep it from happening again in the future.

#### Key takeaways 
* What is a firewall and its architecture
* Firewall pros and cons
* Firewall classification
* Firewall identification
* Intrusion detection system (IDS)
* Types of IDS
* Anomaly detection model
* Defenses against IDS attacks
* Intrusion Prevention System
#### Article quality
This will be a distinctive article with detailed information. In this article, I will use basic language to ensure that anybody reading it understands the contents. I'll make sure that this article is useful to the whole EngEd and that it goes above and beyond official documentation.

#### References
N/A

**Comment by WanjaMIKE** [comment]
This article -> https://www.section.io/engineering-education/comparing-intrusion-detection-systems-ids-and-intrusion-prevention-systems-ips/ already covers IDS. How will yours be unique?

**Comment by Romans70** [comment]
@WanjaMIKE 
The article will contain the ways of defending IDS against attacks and also detailed information about firewalls which are not covered in the article.

**Comment by WanjaMIKE** [comment]
Unfortunately, I don't think this topic adds much value. Feel free to suggest another one. Thanks
