### ISSUE TITLE
(Python) Creating A Hand Gesture Volume Controller Using Python And Pycharm

### ISSUE THREAD

**Issue by leeseshawn** [section-engineering-education/engineering-education#5112]
### Topic Suggestion
(Python) Creating A Hand Gesture Volume Controller Using Python And Pycharm

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Creating a hand gesture volume controller using python and pycharm

#### Proposed article introduction
In this technological era, computers are crucial to our lives. We use them for working on documents, coding, entertainment, etc. These devices are also easily damaged by water and dust. We therefore cannot handle them with dirty or wet hands. When using them for entertainment, we wash or dry our hands before touching the computer e.g while increasing the volume of our favorite song. This interrupts us from whatever we were doing.

Python helps us solve this issue by enabling us to create a hand gesture volume controller. This software will enable us to control the volume level of our computer by using a hand gesture. We, therefore, do not need to be hands-on on our computers.

In this tutorial, we are going to learn how to use gesture control to change the volume of a computer. We are also going to explain in detail the python packages we will require. We will use the following packages:

- numpy
- cv2
- mediapipe
- math
- time
- ctypes
- comtypes
- pycaw

#### Key takeaways 
The reader will be able to:

- Have an in-depth understanding of how the above packages are used.
- Use python to track hand gestures.
- Create a hand gesture volume controller.

#### Article quality
Unlike other articles, the code will be well explained and not just copy-pasted. The article will also cover in detail the python packages used and why we are using them not just installing them in our project.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @leeseshawn 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
