### ISSUE TITLE
How to Create a Data Science App Using Streamlit and Python

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#5117]
### Topic Suggestion
How to Create a Data Science App Using Streamlit and Python

#### Proposed article introduction
With the help of the free python library Streamlit, data scientists and machine learning researchers may create and share web apps. Using just a few lines of code, the library makes it easy to quickly build and deploy a data science solution.

NumPy, Pandas, Matplotlib, Scikit-learn, and a slew of other well-known Python data science libraries may all be utilized smoothly with Streamlit.

> The data is shown on the screen using the React frontend framework from Streamlit.
#### Key takeaways 
1. Introduction to Streamlit
2. Installation and Set up 
3. Develop the Web App 
4. Test the Web App
5. Conclusion
#### Article quality
With a few lines of code, we will create a simple data science web app that can receive a movie review and predict if it is a positive review or a negative review. We will develop the web app and test it. The article will be comprehensive, and the code provided will be simple to grasp.
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @vincentkims49 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
