### ISSUE TITLE
[Node.js] Building a Microservice with Node.js

### ISSUE THREAD

**Issue by OkothPius** [section-engineering-education/engineering-education#5122]
#### Proposed title of article
Building a Microservice with Node.js

#### Proposed article introduction
Building applications is more than just meeting the client's needs; as the system grows in size developers, experience various issues such as the maintenance of the codebases, implementation of new features, bug fixing, and managing user roles. These considerations are trivial, and developers have to use various methods when architecting systems to avoid them.

The best way to resolve issues in monolithic structures is by using distributed systems. The distributed system is an environment where various components are spread out across the network and function independently. One of the systems is microservices which structures an application as a collection of loosely coupled services. Developers use several languages to implement microservices such as Java, C#, .NET framework, and Python.

In this article, we'll demonstrate how to get started on building microservices with Node.js as it is a more embraced platform by most developers, as we'll discuss in later chapters.

#### Key takeaways 
1. Challenges of monolithic structures
2. What is a microservice architecture
3. Setting up Node.js structure
4. Making an external API call
5. Execution
6. Testing our application

#### Article quality
The tutorial will cover how to approach microservices by consuming external an external API to make calls to our microservice. Available published articles does not go in-depth in such topics. Most articles done on the same also just cover the importance of using microservices and how Node.js is suitable for the job but does not dive deep into it. 

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately we are shifting from Node.js articles. We seem to have enough in our pipeline.
