### ISSUE TITLE
[Languages] How to call a web API in C# from a .NET application

### ISSUE THREAD

**Issue by mercymumo** [section-engineering-education/engineering-education#5125]
### Topic Suggestion
How to call a web API in C# from a .NET application 

#### Proposed title of article
How to call a web API in C# from a .NET application

#### Proposed article introduction
This tutorial will take the reader on how to create a web app that sends HTTP queries to a GitHub REST service. The application then reads data in JSON format and converts it to C# objects. The process of converting JSON into C# оbjeсts is known as deseriаlizаtiоn.
#### Key takeaways 
- Send HTTР requests.
- Deseriаlize JSОN resроnses.
- Соnfigure deseriаlizаtiоn with аttributes.

#### Article quality
This article will take the reader through making a HTTP request in a .NET console using C#, as opposed to other articles in web that only focus on making a call in C#.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @mercymumo 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
