### ISSUE TITLE
[Networking] - Heterogeneous networks / Heterogeneous computing

### ISSUE THREAD

**Issue by kwennB** [section-engineering-education/engineering-education#5128]
#### Proposed title of article
Heterogeneous networks / Heterogeneous computing

#### Proposed article introduction
A heterogeneous network 
This network connects devices and computers with different protocols or operating systems. An example of a heterogeneous network is the Local Area Network (LANs). 
Corporate enterprises use heterogeneous networks. This is because of the increase in efficiency using different protocols and OS.   

#### Key takeaways 
* Features of heterogeneous networks including their benefits
* Standards for a heterogeneous computing environment
* Disadvantages/Issues to consider in heterogeneous networks
* Tips for choosing heterogeneous networks

#### Article quality
This article will share how to connect diverse operating systems or protocols. Also share tips to note about heterogeneous networks.

#### References
NIL

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @kwennB 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
