### ISSUE TITLE
Getting started with MongoDB transactions using Node.js

### ISSUE THREAD

**Issue by murewaashiru** [section-engineering-education/engineering-education#5130]
#### Proposed title of the article

Getting started with MongoDB transactions using Node.js

#### Introduction

The need to maintain database integrity cannot be overemphasized. One of the ways to ensure this is by performing [ACID](https://en.wikipedia.org/wiki/ACID) transactions; this simply means that actions are meant to be completed as a 'whole' are either all completed or not completed at all.

While the emphasis on NoSQL databases is scalability, implementing ACID transactions in the logic layer cannot suffice in all scenarios.

#### Key takeaways

By the end of this tutorial, the reader will be able to understand:
- What database transactions are
- When to use database transactions
- How to implement database/ACID transactions using MongoDB

#### Article quality

This will be in-depth coverage of this concept; including the history of the concept and a demonstration of how it works.

#### References

- [What are ACID Transactions?](https://www.mongodb.com/basics/acid-transactions)
- [ACID Transactions in NoSQL? RavenDB vs MongoDB](https://ravendb.net/articles/acid-transactions-in-nosql-ravendb-vs-mongodb)

**Comment by WanjaMIKE** [comment]
Unfortunately, we are currently shifting from Node.js articles. We seem to have enough in the pipeline?
