### ISSUE TITLE
Test Serverless functions using Jest and Next.js API Routes

### ISSUE THREAD

**Issue by prograte** [section-engineering-education/engineering-education#5134]
#### Proposed title of the article

Test Serverless functions using Jest and Next.js API Routes

#### Proposed article introduction

[Language] Testing is a critical part of system development where the project is made sure to be running as expected.
Serverless functions are server-side functions hosted on third-party services.
They can be run on someone's else server with the profit of writing them on the project where the front-end code lives.
If new to serverless technology, learn more about serverless functions in [this](https://www.section.io/engineering-education/how-to-build-apps-with-serverless-architecture/) article.

Next.js is a web framework built on top of React. What's cool with it is that it allows one to build API endpoints using Serverless functions.
This is accomplished by the use of API Routes wherein the routes a function is defined and a response to the invocation.
There are currently many great ways of testing applications. In this case, the code and the response need to be tested hence Jest will be used.
Jest is a Test(s) runner library for javascript frameworks. It allows one to test serverless functions, utility functions among many more.

In this article, testing serverless functions using Jest and Next.js API Routes will be tackled.

#### KeyTakeaways

By the end, the following will be discussed and learned:

- Creating an instance of a serverless function in a Next.js app
- Installing and configuring testing modules for the app
- Import the serverless functions into the tests
- Abstract code to harden tests for the serverless functions
- Running the tests on the code

#### Pre-requisites

For the article, the following are required for easy article follow-up:

- A good JavaScript IDE or text editor set up on the machine
- A stable internet application
- Next.js development environment already setup
- Next.js development skills
- Basic project testing skills

#### Article quality

The article will be a span of broad content. It will begin with the basics before delving into more detailed but in-depth content on the serverless function tests to be carried out.
This makes the user move from a beginner to expert level quickly.

#### References

- Next.js Testing [documentation](https://nextjs.org/docs/testing)

#### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @prograte 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
