### ISSUE TITLE
[Machine Learning]Using Python to detect and name most dominant colors in an image

### ISSUE THREAD

**Issue by Donel254** [section-engineering-education/engineering-education#5136]
### Topic Suggestion
[Machine Learning] Using Python to detect and name most dominant color in an image

#### Proposed article introduction
In every image that we come across, there is always a dominant color. Some can simply be identified by just looking at them but for some, you cant tell. We can use K-means clustering to identify the dominant color in an image, which is faster and more efficient.
We shall start by identifying the colors in our image, identifying the color that is most dominant, and then name the color. After that, we shall look at the applications of dominant color identification.

#### Key takeaways 
1. Checking number of colors in an image.
2. Building a clustering model using K-means.
3. How to get the most dominant colors in an image.
4. How to get color names in python.
5. Applications of dominant color extractions.

#### Article quality
1. Unlike the other tutorials which have a static number of clusters, this one shall have a dynamic number of clusters which shall be determined by the number of colors in an image. 
2. Also unlike the others, we shall incorporate a way of naming colors using python.
 
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Donel254 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
