### ISSUE TITLE
[Android] Get started with Activities and Recycler view Android with Kotlin 

### ISSUE THREAD

**Issue by dvoredave** [section-engineering-education/engineering-education#5141]
#### Proposed title of article
Get started with Activities and Recycler view Android with Kotlin 

#### Proposed article introduction
You're starting to build a good fundamental grasp of how apps are developed and how the various pieces of the app interact at this stage. This tutorial will expand on that foundation by presenting various themes and features that will be relevant in the vast majority of subsequent apps you write. Our objective for the next several classes will be to design and construct a full-fledged app, introducing and discussing subjects as they arise during the app development process.

That means that in this tutorial, we'll go through how to call other Activities, how to transport data across Activities, and how to save it in the form of a recycler view in the connected activity, making it easier to show vast amounts of data quickly. We will provide the data and describe how each item should appear, and  how the Recycler View library builds the elements as needed.

#### Key takeaways 
By the end of this tutorial, the reader will have covered thee following concepts:

- Launching  Main Activity
- Introduction on what is Recycler View
- Implementation of Recycler View Activity
- Recycler View Activity Explanation
- Linking Activities using Intents
- Passing Data to Another Activity
- Retrieving data passed in an Intent

#### Article quality
This will be a unique article with a step by step explanation of the concepts. It will also use simple language with illustration of every activity to help the reader have better understanding.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic is well covered in numerous articles that have already been published. Feel free to suggest another topic. Thanks
