### ISSUE TITLE
Data Validation and Analysis in Excel

### ISSUE THREAD

**Issue by majiezra** [section-engineering-education/engineering-education#5144]
### Topic Suggestion
Data validation and analysis in Excel.

### Writing sample(s): 
[how to create font chooser app](https://www.section.io/engineering-education/how-to-create-font-chooser-app/)
#### Proposed title of article
Data validation and analysis in Excel.

#### Proposed article introduction
Data analysis is defined as a process of cleaning, transforming, and modeling data to discover useful information for business decision-making. The purpose of Data Analysis is to extract useful information from data and make decisions based upon the data analysis.
Data validation is a form of data cleansing. It means checking the accuracy and quality of source data before using, importing, or otherwise processing data to extract meaningful insights, conclusions, or identifying hidden trends.
It is important to note that data never sleeps and the importance of the role of a data analyst in cleaning, mining, and extracting meaningful details in raw data can not be over emphasized. 
In this tutorial, we will learn about the steps in data analysis, types of analysis, data types, and also the validation of data using excel.

ONLY viable topics to pick from:
- Machine Learning

#### Key takeaways 
- Understanding the role of a data analyst in processing data and the various programming languages an analyst is required to be familiar with.
- Types of data analysis
- Types of data
- Classification of data
- Understanding the concept of using excel to validate data.

#### Article quality
This article will be well-written and contain unique data analysis information and details; additionally, there are few or no articles written on this topic suggestion.

**Comment by WanjaMIKE** [comment]
I think most of the key takeaways that you seek to cover are already analyzed in numerous tutorials. Feel free to suggest another topic. Thanks
