### ISSUE TITLE
Create Machine Learning Model User Interfaces Using Gradio in Python

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#5148]
#### Proposed title of article
Create Machine Learning Model User Interfaces Using Gradio in Python.

#### Proposed article introduction
Making Machine Learning models these days is turning out to be progressively simple because of many open-source and exclusive-based administrations, because of this smooth user interfaces are required to test the finished models. The interface must be simple and user-friendly enough to exhibit the dynamics of the project to a non-technical person. Hence a module is required to help data analysts, data scientists, programmers generate an easy-to-use user interface for machine and deep learning models. 
One potential module for this is the Gradio, an open-source python library that permits you to rapidly make simple to use, adjustable UI parts for your ML model. This article will cover as much to help the reader understand how Gradio can be used in creating and generating user interfaces easy to be used by the users.
#### Key takeaways 
The reader will be able to:
- Understand Machine Learning Models.
- Get to learn more about the Gradio python library.
- Know how to implement the Gradio module in creating User Interfaces in Machine and Deep learning models.

#### Article quality
This article will equip the reader with all the knowledge and practical implementation of the Gradio module in creating user-friendly interfaces in machine learning.

#### References
N/A

### Conclusion
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Unfortunately, the following articles already show how to use Gradio to build UIs. Feel free to suggest another topic. Thanks
https://github.com/section-engineering-education/engineering-education/pulls?q=Gradio
