### ISSUE TITLE
Getting Started With .NET MAUI To Build Cross-Platform Apps In Visual Studio

### ISSUE THREAD

**Issue by Geo-free** [section-engineering-education/engineering-education#5150]
### Topic Suggestion
Getting Started With .NET MAUI To Build Cross-Platform Apps In Visual Studio

### Writing sample(s): 
https://www.section.io/engineering-education/different-techniques-of-encoding-data-for-transmission/

#### Proposed title of the article
Getting Started With .NET MAUI To Build Cross-Platform Apps In Visual Studio

#### Proposed article introduction
.NET MAUI is a cross-platform framework that is used to create native desktop and mobile applications. It is the most productive way to create, performant Android, iOS, macOS, and Windows Apps, all from a single code base. It is an evolution of Xamarin.Forms and extended from desktop scenarios with UI controls.

In this tutorial, I will be taking the reader through the concept of .NET MAUI in visual studio. I will implement this by use of a demo project that will take the reader through the procedure of building a .NET MAUI Application.

#### Key takeaways 
From this tutorial, the reader will understand;
- the concept of the .NET MAUI framework.
- how to build cross-platform applications using the .NET MAUI framework
- the importance of the .NET MAUI framework to the .NET developers

#### Article quality
This tutorial targets developers who want to write cross-platform apps in XAML and C#, from a single shared code-base in Visual Studio, and share UI layout and design across platforms. I will be getting information from different sites to ensure that I cover each and every part and provide the knowledge needed to the reader.

#### References
N/A.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Geo-free 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
