### ISSUE TITLE
Gestures handling in flutter

### ISSUE THREAD

**Issue by linet-ciku** [section-engineering-education/engineering-education#5152]
#### Proposed title of article
***Handling gestures in flutter***

Use keyword research to improve your article's SEO.

#### Proposed article introduction
This article will form a basis to explain about gesture handling in flutter using dart containers.

#### Key takeaways 
- Flutter basics
- gestures
- detecting input gestures

**Comment by ahmadmardeni1** [comment]
This suggestion is not ready. Please take a look at other topic suggestions submitted by other students and revisit yours.
