### ISSUE TITLE
Getting started with QGIS and some of its features

### ISSUE THREAD

**Issue by muyiwexy** [section-engineering-education/engineering-education#5156]
#### Proposed article introduction
Do you want to view, edit or analyse your geospatial data? Then this tutorial is for you. Geospatial information describes the location and names of features beneath, on or above the earth's surface. GIS isn't one of the widespread things though it covers a large area of what we do. These data are either vector or raster data.

In this tutorial, we'll talk about an open-source geographic information system known as QGIS. QGIS supports both raster image and vector data(lines, polygon, point). QGIS opens a whole new possibility as it integrates with numerous personal databases such as Postgis, dxf etc.

#### Key takeaways
We will focus on some of the raster and vector features in this tutorial, these are:

- Raster georeferencing.
- Coordinate references system.
- Creating vectors (shp, kml) and some cool vector features for ease of work.
#### Article quality
My article is going to talk more about the application of QGIS in a growing real estate idea. We will be creating a live vector project. 

References
N/A.

**Comment by ahmadmardeni1** [comment]
How does your article differ from what is already published and the official docs? @muyiwexy

**Comment by muyiwexy** [comment]
@ahmadmardeni1 this article will talk about how a growing real estate company called HouseAfrica has used this tool for its accuracy and speed to represent property cells using some leaflet properties.

**Comment by ahmadmardeni1** [comment]
I think this topic is focusing more on geospatial content instead of programming concepts. What do you think? @lalith1403 @louisefindlay23 @WanjaMIKE @LinusMuema

**Comment by WanjaMIKE** [comment]
Yeah I also think so. Could you suggest another topic. Thanks
