### ISSUE TITLE
[languages] How to invoke a SOAP web service in C# using httpclient

### ISSUE THREAD

**Issue by Tonnysage** [section-engineering-education/engineering-education#5157]
### Topic Suggestion
How to invoke a SOAP web service in C# using httpclient

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-invoke-a-soap-web-service-in-java/

#### Proposed title of article
Invoking a SOAP web service in C# using httpclient

#### Proposed article introduction
The HttрСlient сlаss is used tо send аnd reсeive HTTР requests аnd resроnses frоm а URL. It is а.NET frаmewоrk аsynсhronous feаture  thаt is suрроrted. HttрСlient mаy hаndle severаl requests аt the sаme time. It sits оn tор оf HttрWebRequest аnd HttрWebResроnse аs а lаyer. HttрСlient's methоds аre аll аsynсhrоnоus.

#### Key takeaways 
1. Create a console application
2. Call the web service Endpoint
3. Send a GET request
4. Send POST request
5. Send PUT request
6. Send DELETE request

#### Article quality
In this article, the reader will learn how to invoke any web service using *httpclient* . I will further create an a test console application in C# and add web requests from the aplication.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Tonnysage 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
