### ISSUE TITLE
Step-by-Step Guide to Implement Kernel SVM using Scikit learn in Python

### ISSUE THREAD

**Issue by jacksonjate1** [section-engineering-education/engineering-education#5169]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed article introduction
Kernel Support Vector Machine (SVM)
Kernel SVM is an unsupervised learning algorithm used in classification tasks involving non-linearly separable datasets. A data is non-linearly separable if different classes in the dataset can not be separated using a linear hyperplane. Kernel SVM is like a generalized linear support vector machine(SVM) version. SVM assumes that the data is linearly separable. Thus data classes can perfectly be separated using a linear hyperplane(hard SVM) or with a line with minimum misclassifications possible(soft SVM).

When the data is linearly inseparable, it's not possible to find a hyperplane to classify data points optimally. When this is the, a kernelized version of SVM comes into play.

When dealing with non-linear separable datasets, one way to make them linearly separable is mapping them to higher dimensionality and learning the relationships in their higher space. However, mapping the dataset to higher dimensions and then analyzing them is inefficient as it requires more time and increased computational power. Now, kernel SVM is a way to solve this problem.

As kernel SVM employs the kernel trick on non-linearly separable datasets, it makes it possible to learn the relationship in a higher-dimensional space of data even without transforming(mapping) the data to a higher dimension. When considering space and time complexity, this approach is very efficient compared to mapping the datasets to higher space. This grants the kernel trick its popularity in machine learning.

In this article, we shall revisit the linear SVM and discuss its two versions, i.e., hard ans soft SVM, from which we will introduce the Kernel SVM. In the kernel SVM, we will understand its applicable situations and how it works.

First, we shall learn how to map non-linearly separable data to higher space to make them linearly separable and talk of the disadvantages of this approach.

Secondly, to correct the downfalls of the above approach, we shall discuss what the kernel trick is and how it simplifies complex computations. Finally, before we dive into our implementation using Scikit learn library, we shall outline various types of the kernel function. Since the Gaussian kernel is the most popular and widely used kernel function, we shall discuss how it works.

#### Key takeaways 
The learner is expected by the end of this tutorial to know;
1. The two types of linear SVM and how they classify data classes.
2. What is the kernel SVMs and how it works.
3. How to map la data from low dimensional space to higher dimensional space
4. What is the kernel trick, and how does it simplify complex computations.
5. Different types of kernel functions.
6. How the kernel SVM classifies the data using the Gaussian kernel with scikit learn library in python

#### Article quality

This article provide all the learner need to know about the kernel SVMs. It is a good article to start with because, unlike many articles online which dive into the concept of the kernel SVM, this article will start building up from the linear SVM which will help the learner to have deep grasp of the kernel SVM. The concept of the kernel SVM presented in this article will be kept very precise, only focusiing on the most crucial part of this algorithm.

#### References
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Unfortunately, we are only accepting one topic per contributor at the moment. Thanks
