### ISSUE TITLE
[Languages] Creating a Python Package and Distributing it on GitHub

### ISSUE THREAD

**Issue by norah254** [section-engineering-education/engineering-education#5172]
### Topic Suggestion
Creating a Python Package and Distributing it on GitHub

### Writing sample(s): 
N/A

#### Proposed title of the article
Creating a Python Package and Distributing it on GitHub

#### Proposed article introduction
Many a time we write Python scripts and projects which we wonder what to do with afterward. Instead, we could package these scripts and projects to be able to share and reuse in new upcoming projects instead of rebuilding the wheel.

In this article, we will be packaging a Python script and distributing it on GitHub. We will first transform our code into a python package for reusability(It can be installed). We’ll then distribute the package to a Github repository for accessibility.

#### Key takeaways 
By the end of this tutorial, the reader should be able to:

- Understand the requirements of a Python package.
- Build a Python package or transform an existing project into a package.
- Install the self-built package from the repository using `pip`.
- Update an existing package.
- Distribute a package on GitHub.

#### Article quality
This article will cover more in-depth content that the documentation doesn't cover.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
