### ISSUE TITLE
Understanding System Development Principles

### ISSUE THREAD

**Issue by Muthoni-Irungu** [section-engineering-education/engineering-education#5173]
Proposed title of article
Understanding System Development Principles

Proposed article introduction
A system is an entity with inter-related and interdependent parts that work together in order to achieve a certain objective. A system has three basic implementation i.e.:
- A system must be designed to achieve pre-determined objective 
- interrelationships and interdependence must exist among the components.
- The objectives of the organization as a whole have higher priority than the objectives of its subsystems.
A change in one part of the system affect the other part and the whole system.
In this article I'm going to cover:
- System theory
- Characteristics of systems
- Information system
- Methods of system development
- Stages of system development

Key takeaways

- After reading the article the reader will know the different types of systems.
- Will understand the Purpose of an information system.
- Will learn the roles of a system analyst.
- And will get to know why we develop new systems.
- They will learn different types of feasibility studies

Prerequisites
The reader should have basic knowledge of programming languages and how to develop software's.

Article quality
Unlike other articles, this article will be precise and easy to understand.

Conclusion

**Comment by WanjaMIKE** [comment]
Let's wait until the other PR is closed or published. Thanks

**Comment by Muthoni-Irungu** [comment]
Hello @WanjaMIKE can you open my issue,,,my previous PR has been closed,,

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
