### ISSUE TITLE
Working with SSHGuard to Improve FreeBSD's Security with IPFW

### ISSUE THREAD

**Issue by beckie03** [section-engineering-education/engineering-education#5175]
#### Proposed title of article
 Working with SSHGuard to Improve FreeBSD's Security with IPFW

#### Proposed article introduction
Intruders regularly target VPS servers. Hundreds of unauthorized ssh login attempts are a prevalent sort of attack. Setting up a firewall is helpful, but it may not be enough to stop intrusion attempts.

Create a stronger infiltration barrier for FreeBSD using the ipfw firewall and sshguard. In short, SSHGuard examines system logs for "abusive" entries. As soon as an offender attempts to obtain access, ipfw is told to restrict communication from that IP address. The culprit is successfully ejected.

Managing server security is straightforward once you understand how these applications function. In addition to FreeBSD, this information applies to other operating systems and firewall software.

#### Key takeaways 
-IPFW Configuration
-Install and configure SSHGuard
-Set up a rule-based program
-Getting started and testing
-Maintaining vigilance...

####Article quality
This article will be of great assistance to beginners, intermediate, and even expert users in detecting intruders on their servers, as well as unwanted login attempts, and will therefore help them to manage server security more effectively and efficiently.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @beckie03 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
