### ISSUE TITLE
String Validators

### ISSUE THREAD

**Issue by duncandegwa** [section-engineering-education/engineering-education#5180]
#### Proposed title of article
String Validators in Python

#### Proposed article introduction
Often times, we work with strings and want to quickly check if they are of a particular type or contain specific data. While we can do the same by either storing the characters of the string in a data structure or explicitly writing down statements to verify, string validators in Python can simplify our task. This can be useful when validating a password string or any other user input. String validators are essentially functions that allow us to check if a string meets certain criteria. 

#### Key takeaways
- Checking if a Given String Is Alphanumeric 
- Checking if a Given String Is Alphabetic 
- Checking if a Given String Is All Numbers
-  Checking if a Given String Is Lowercase 
- Checking if a Given String Is Uppercase 
- Checking if a Given String Is Blank 
- Checking if a Given String Is Title Cased

#### Article quality
This article is an introduction to string validators and assumes no prior knowledge of them. We will build a simple application that will accept user input eg login credentials then we validate the entered user input.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @duncandegwa 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
