### ISSUE TITLE
[Networking]An Introduction to Supernets in Networking and their history

### ISSUE THREAD

**Issue by jonathanwambua** [section-engineering-education/engineering-education#5185]
### Topic Suggestion
An Introduction to Supernets in Networking

#### Proposed article introduction

As days go by, data is shifting online and networking has become a field that is growing day in day out. Due to the reason that most companies and individuals are shifting online due to the Covid 19 pandemic, network traffic continues to increase as the days go by. This is the rationale for this article that the reader of this article will understand the concept of super nets and how they work in a simplified manner.

This article also aims to cover the historical evolution of super nets and possible ways to address the challenges of the over growing network capacity. This is due to over dependency on the network hence the need to accommodate  more data.

#### Key takeaways 

i) Introduction to supernets.
ii) The concept of supernets in networking.
iii) The history of supernets.
iv) Ways of improving networks to accommodate higher capacity.

#### Article quality

This article is unique from the rest in that it uses easy to understand language to enable the reader understand more in depth the topic of concern. It also straight forward, uses images and examples that will help the user to understand the concepts to be illustrated in this article.

#### References
NA

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @jonathanwambua 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites.
We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
