### ISSUE TITLE
Data classification with Kernel SVM in Scikit learn Library

### ISSUE THREAD

**Issue by mbici** [section-engineering-education/engineering-education#5188]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed article introduction
Kernel SVM is an unsupervised learning algorithm used in non-linear classification problems. When the data is linearly separable, we use SVM to obtain a classifier with an optimal margin. With the SVM, data can be perfectly classified using a linear hyperplane. This type of SVM is called Hard SVM. In other cases, the data might not be linearly separable, but still, we can classify them with minimum classification error. This type of SVM is known as the Soft SVM.

Although we can approach non-linear data using the soft SVM, it turns out that there are cases when the data is highly mixed up, and if we try to classify them using the soft SVM, we may end up obtaining a model whose accuracy is below 50%. In such situations, we use a kernelized SVM.

Typically, when dealing with non-linear data, one way to make the data linearly separable is by mapping it to higher dimensions. We then learn the existing relationships between features on the newly transformed data. The challenge with this approach is that it's time-consuming and requires high processing power. To overcome this challenge, we employ the kernel tricks, which utilize the original feature space, learn the underlined relationship in their higher dimensions. So the beauty of the kernel trick is that we don't need to map the data to higher dimensions to classify them optimally. This makes this approach to classification more efficient.

In this article, we will introduce the two types of linear SVM. After that, with the aid of a plot, we shall try to understand what we mean by referring to the data as non-linearly separable and how to map it to higher dimensions to make it linearly separable. Then, using an example, we shall then learn how the kernel trick works, and the kernel functions used when handling non-linear data. Finally, we shall understand the Gaussian kernel, and it's used with SVM to classify non-linear data.

#### Key takeaways 
The reader is expected to know;
- How does the SVM algorithm classify data classes.
- What's the kernel SVMs and in which scenario is applicable.
- How to transform non linearly separable datasets from low dimensional space to higher dimensional space to make them linearly separable
- How to define the kernel trick and how does it work.
- Various types of kernel functions are used with SVM.
- Most utilized kernel function when dealing with non-linear data
- How to implement the kernel SVM classifier on a dataset using Scikit-learn library in python

#### Article quality
This article will build up from the linear SVM from which we shall introduce the concept of the kernel SVM before we dive deeper into it; thus, the learner will have a firm understanding of the topic. Furthermore, all discussion will be to the point; hence, there will be no unnecessary explanation, making the content wordy and boring to fall along. Finally, we will visualize how our model classified our dataset, unlike many articles online, which only implement the model and leave it hugging without showing the learner how they can visualize classification classes.

#### References
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @mbici 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
