### ISSUE TITLE
Application Monitoring and Observability

### ISSUE THREAD

**Issue by Ernest715** [section-engineering-education/engineering-education#5192]
### Topic Suggestion
Application Monitoring and Observability

#### Proposed article introduction
Application monitoring is fundamentally different from observability. Each solution is
characterized with distinct attributes. However, departments dealing with IT and development
have termed the difference between the two to be somewhat blurry as they are closely related. To
address this close interrelation, industrial professionals have coined definitions and conceptions
to help distinguish between the two IT solutions.
Present dispensed applications are not monitored efficiently using legacy approaches that are
based on controlling foreseeable elements. The modern microservice designs are only functional
on observable systems to permit web applications, proper debugging and testing. The element of
observability implies that its internal condition can be deduced via observation of the output.
These facts provide the foundation basis of the close association between monitoring and
observability. In this article, comprehensive discussions of the two IT solutions will be provided
and the interrelation between the two consequently reviewed.

#### Key takeaways 

After reading this article, the readers should be able to:

    Comprehensively define monitoring and some of its benefits upon implementation.

    Give a detailed elaboration on observability, significance of its execution and the three
      key pillars it is categorized into.

    List tools incorporated in observability.

    Explain the interrelation between the two elements and identify the underlying
differences.

**Comment by Ernest715** [comment]
hey @collins-a you suggested if i could consider this topic sometime back. I intend to cover it extensively under the mentioned key take a ways.

**Comment by collins-a** [comment]
As long as it goes into extensive and unique technical detail, it's a good topic. However, let's wait for confirmation from @ahmadmardeni1

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Ernest715 
We lean towards content that offers an original viewpoint/approach around **programming-centric** topics.
Please feel free to suggest an alternate topic to explore. 🚀
Cc @collins-a
