### ISSUE TITLE
Methods of Detecting Fraud in Organizations

### ISSUE THREAD

**Issue by Juskam** [section-engineering-education/engineering-education#5202]
#### Proposed title of article

Methods of Detecting Fraud in Organizations

#### Proposed article introduction
Extortion in many associations, whether or not business for-benefit, isn't absolutely preventable. At the point when business visionaries or ranking directors perceive and recognize that extortion could happen in their association, their consideration will probably move to misrepresentation identification. 

Early location can lessen misrepresentation misfortunes in many cases in light of the fact that authoritative cheats will more often than not be progressing. In this post, we examine a few different ways that extortion may be distinguished.

#### Key takeaways 
1.Fraud detection by external auditors
2.Fraud detection by internal auditors and inspector generals
3.Fraud detection by tip lines
4.Fraud detection by dedicated departments
5.Fraud detection by accident

#### Article quality
This will be an in-depth article explaining all aspects of this concept.To ensure it's beginners friendly, I will employ easy use of language to enhance understanding.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Based on this check -> https://github.com/section-engineering-education/engineering-education/issues?q=fraud+detection, this topic appears to be well-covered. Feel free to suggest another topic. Thanks
