### ISSUE TITLE
[Languages] Getting Started with Nuxt 3 

### ISSUE THREAD

**Issue by LeahKui** [section-engineering-education/engineering-education#5203]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
[Languages] Getting Started with Nuxt 3 

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Getting Started with Nuxt 3 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Nuxt 3 beta is the Hybrid Vue Framework that allows you to create server-side rendered applications using Vue.js and more importantly Vue.js 3. Nuxt 3 was launched on October 12 2021 and will be used in Vue and Nuxt developer ecosystems. This is an updated version that has been redesigned for better performance and lighter builds.
This article will look at Nuxt 3 installation process, go through its features, plugins, and why you need to use it in the next project.

#### Key takeaways 
1. Starting a new project
2. Nuxt 3 features
3. Nuxt 3 plugins
4. Why you need to use Nuxt 3

#### Article quality
This article will discuss Nuxt 3 beta in details. It will be an interactive and exiting topic as readers will know the installation process and get started with a new project. Readers will get to know its features as well as plugins and know why they need to use Nuxt 3 in their next projects.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
https://v3.nuxtjs.org/docs/usage/data-fetching
https://vueschool.io/articles/news/whats-coming-in-nuxt-3/
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @LeahKui 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
