### ISSUE TITLE
[Edge Computing] Solving Database Re-Platforming Challenge with Adaptive Data Virtualization

### ISSUE THREAD

**Issue by Greggmun** [section-engineering-education/engineering-education#5206]
#### Proposed title of article
Solving Database Re-Platforming Challenge with Adaptive Data Virtualization

#### Proposed article introduction
One of the fundamental problems facing enterprises needing to take advantage of cloud technologies is how to move their databases to the cloud without rewriting the entire application stack. Typically, conventional database re-platforming projects can take several years and cost many millions besides being risk-prone.

Adaptive Data Virtualization (ADV) technology solves the problem of migrating to cloud data warehouses effectively and at a fraction of the cost of other approaches. The ADV approach enables database or data warehouse applications—originally developed for a specific database or data warehouse on-premises—to run instantly and natively in the cloud, without requiring modifications to the applications.

#### Key takeaways 

- What does database re-platforming entail. 
- The problem of application rewriting in database migrations. 
- Adaptive data virtualization for seamless data visualization. 
- Adaptive data virtualization vs conventional migration

#### Article quality
This article is in-depth and covers a rarely talked about topic of adaptive data virtualization and its application to solving data migration challenges. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Greggmun

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
