### ISSUE TITLE
[Languages]Creating Password Random Generator in Python Using PyCharm

### ISSUE THREAD

**Issue by lizpart** [section-engineering-education/engineering-education#5208]
#### Proposed title of article
Creating Password Random Generator in Python Using PyCharm

#### Proposed article introduction

In this article, you will learn how to create and generate random strings and passwords in Python. We will be using a random module so that you will write your own string or password generator.
Passwords provide the first line of defense against unauthorized access to your computer, accounts, and personal information.
Being that it is easier for hackers to have our accounts hacked by predicting combinations of our passwords from our date of birth, memorable events, etc.
Randomly generated passwords are usually stronger, the stronger the password the safer your computer will be from hackers and malicious software.
 

#### Key takeaways 

1. Creating a random sting
2. Random string without repeated characters.
3. Creation of Random Password with Special characters, letters, and digits.
4. Generation of random alphanumeric string of letters and digits.
5. Importance of using randomly generated passwords.

#### Article quality

In this article, I will be extensively covering even the importance of using randomly generated passwords.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @lizpart
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
