### ISSUE TITLE
[Android] Creating A Custom Spelling Checker Using Spelling Checker Framework in Android with Kotlin

### ISSUE THREAD

**Issue by robert-muriithi** [section-engineering-education/engineering-education#5209]
#### Introduction
The Spelling Checker framework improves the text-input experience on Android by helping the user quickly identify and correct spelling errors. When an app uses the spelling checker framework, the user can see a red underline beneath misspelled or unrecognized words so that the user can correct mistakes instantly by choosing a suggestion from a drop-down list.
The Spelling Checker APIs let you create your own spelling checker service with minimal steps. In this article, I will explain to the reader how to create and implement spelling checker service in an android app.

#### Key takeaways 
- Understanding what is Spelling Checking Service
- How to create own spelling checker using the Spelling Checker Framework
- How to implement your own spelling checker to your android app

#### Article quality
I am going to focus on creating a custom spelling checker service. This will be purely in kotlin programming language. I will use a simple approach which will be beginner friendly for those looking to venture in trying to implement this feature in their app.

#### References
https://developer.android.google.cn/reference/kotlin/android/service/textservice/SpellCheckerService

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
