### ISSUE TITLE
[Machine Learning] A 3D Object Detection Solution for Everyday Objects

### ISSUE THREAD

**Issue by splashtonia** [section-engineering-education/engineering-education#5218]
### Topic Suggestion

A 3D Object Detection Solution for Everyday Objects

#### Proposed title of article

A 3D Object Detection Solution for Everyday Objects

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Object detection is a relatively mature studied computer vision problem, but most of the research has only focused on 2D object prediction. While 2D prediction only provides 2D bounding boxes, by extending prediction to 3D, one can capture an object’s size, position and orientation in the world, leading to a variety of applications in robotics, self-driving vehicles, image retrieval, and augmented reality. 
Objectron is a mobile real-time 3D object detection solution for everyday objects. It detects objects in 2D images, and estimates their poses through a machine learning (ML) model, trained on the [Objectron](https://github.com/google-research-datasets/Objectron) dataset. This tutorial will show our readers how to build this 3D Object Solution. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to understand:
- What is Objectron
- Why 3D detection is important
- How to obtain real-world 3D training data
- Detect and track 3D objects using this model

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

This tutorial is unique because most articles on the web has only focused on 2D object prediction. My tutorial will cover about 3D object detection and this will help solve everyday problems.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [MediaPipe Objectron](https://google.github.io/mediapipe/solutions/objectron)
- [Objectron: A Large Scale Dataset of Object-Centric Videos in the Wild with
Pose Annotations](https://arxiv.org/pdf/2012.09988.pdf)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

Please @ me when we publish your article. I would love to read it@splashtonia
