### ISSUE TITLE
Developing simple Blockchain app In flutter

### ISSUE THREAD

**Issue by johnniembugua** [section-engineering-education/engineering-education#5220]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Developing simple Blockchain app In flutter
Developing simple Blockchain app In flutter

Use keyword research to improve your article's SEO.

#### Proposed article introduction
A blockchain is a decentralized database that everyone can access. They have an intriguing property where once data is stored in a blockchain, changing it becomes incredibly difficult.
Smart contracts (also known as decentralized applications or DApps) are similar to conventional contracts; the only distinction being they are electronic. A smart contract is a small computer program that is stored in a blockchain. They can eliminate existing third-party entities from many trustless ecosystems.
In this article we will see how one can implement the blockchain technology in our flutter applications.We are going to design a simple application that will run ion blockchain technology and will be used to keep track of transactions.
For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
- Whats is blockchain
- what are smart contracts?
- How to build a customized blockchain for a flutter application 
- Build a simple application that allow transactions  running on a blockchain technology

#### Article quality
I have created an app called "Transactions". It shows different types of transaction happening at present time on blockchain . The transactions includes purchase, donation and sell.

I have used Material design in the app along with RecyclerView for showing information to the user . This article will be updated when new feature is added in this application.
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
-https://hackernoon.com/learn-blockchains-by-building-one-117428612f46

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Please fill in the article quality section. @johnniembugua

**Comment by johnniembugua** [comment]
@ahmadmardeni1 I have added the article quality section.I am looking forward to your response on the same.

**Comment by ahmadmardeni1** [comment]
What did you use to build your Blockchain?  @johnniembugua

**Comment by johnniembugua** [comment]
dart programming language

**Comment by johnniembugua** [comment]
@ahmadmardeni1 I used Dart

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @johnniembugua 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by johnniembugua** [comment]
Thank you @ahmadmardeni1

**Comment by samkanoi** [comment]
@hectorkambow  kindly reopen this one

**Comment by johnniembugua** [comment]
@hectorkambow kindly open this issue
