### ISSUE TITLE
How to Build a FullStack Reactive Svelte application with MongoDB

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#5227]
#### Proposed title of article

How to Build a FullStack Reactive Svelte application with MongoDB

#### Proposed article introduction

Svelte is a new fronted JavaScript approach to building user interfaces. This introduces a new alternative that use can use besides React, Angular, Vue. However, Svelte is a compiler, whereas the other alternatives are frameworks/libraries. When you build your apps with Svelte, you run the Svelte compiler that automatically goes over your code and files. This creates bundled JavaScript instructions that execute in the DOM at runtime. Instead of using techniques like virtual DOM diffing, Svelte writes code that surgically updates the DOM when the state of your app changes.

With such amazing backend technology, connecting to backend services and accessing data from a server will be essential. In this guide, we learn more about Svelte and how to create a Svelte application with MongoDB.

#### Key takeaways 

- What is Svelte
- Svelte Features
- Set up a Svelte basic application
- Set up a  Svelte backend
- Connect Svelte backend with MongoDB

#### Article quality

Svelte is used to build a frontend application just like the likes of React, Angular, and Vue. There might be a need to connect to a backend server that uses a database such as MongoDB. This guide will help the reader build a complete full-stack reactive Svelte-inspired application.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Please fill in the article quality section @kimkimani

**Comment by kimkimani** [comment]
> Please fill in the article quality section @kimkimani

Check that out @ahmadmardeni1

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @kimkimani 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
