### ISSUE TITLE
How to Automate Python Tests with Travis CI

### ISSUE THREAD

**Issue by khabdrick** [section-engineering-education/engineering-education#5228]
### Writing sample(s): 
https://okteto.com/blog/develop-and-deploy-a-flask-and-reactjs-app-in-okteto/
https://adamtheautomator.com/docker-save-image/

#### Proposed title of article
How to Automate Python Tests with Travis CI

#### Proposed article introduction
In this article, you will learn how automated testing works; the reader will be able to differentiate between manual tests and automated tests, how to write unit tests for Python code with Pytest and how to automate running of those tests with Travis CI.

ONLY viable topics to pick from:
- Languages

#### Key takeaways 
-  How to write test for Python code
- Difference between manual and automated tests
- How to automate tests with Travis CI

#### Article quality
It is one of a kind.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @khabdrick 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
