### ISSUE TITLE
creating a blob menu using VanillaJS

### ISSUE THREAD

**Issue by beatrice-w** [section-engineering-education/engineering-education#5232]
### Topic Suggestion
**creating a blob menu using VanillaJS**

#### Proposed title of article
**creating a blob menu using VanillaJS**
Use keyword research to improve your article's SEO.

#### Proposed article introduction
How to create a simple blob menu which can be implemented in projects.

#### Key takeaways 
- Basics of Javascript
- Good grasp of html
- Good command of tailwind css
- working with CLI tools

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @beatrice-w 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
