### ISSUE TITLE
Understanding Next..JS by Building a Create-Next-App starter kit

### ISSUE THREAD

**Issue by Moscode** [section-engineering-education/engineering-education#5233]
#### Proposed title of article

Understanding Next..JS by Building a Create-Next-App starter kit

#### Proposed article introduction

Next.js is an open-source development framework built on top of Node.js enabling React based web applications functionalities such as server-side rendering and generating static websites. A starter kit is a set of pre-existing code that you can launch to automate your repetitive tasks. It has a language, a framework, and a pattern for a specific use case. So this article will show you the pre-existing code of create-next-app and how they fit together to offer the features that next.js provided.

#### Key takeaways 

-The readers will be able to understand the technologies that are incorporated to offer the next.js features.
-The readers will be able to understand next.js errors better since everything under its hood will be well explained.
-The readers will understand next.js project structure better and the features that its offers.

#### Article quality

Unlike other articles, this article will focus on how to start a next.js project manually while explaining the technologies that offer its features.

#### References

-https://dev.to/calguzman/how-to-create-a-basic-structure-for-a-next-js-app-manually-or-using-a-boilerplate-tool-3h9g
-https://nextjs.org/docs/api-reference/create-next-app

### Templates to use as guides

**Comment by ahmadmardeni1** [comment]
What do you think of this topic? @WanjaMIKE

**Comment by WanjaMIKE** [comment]
I think it's over saturated @ahmadmardeni1 We already have articles on different aspects of Next.js. We can close it

**Comment by ahmadmardeni1** [comment]
Thank you @WanjaMIKE 

Thank you for submitting your topic. @Moscode 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
