### ISSUE TITLE
[Languages] Learn how to improve SEO in your Next.js Web App

### ISSUE THREAD

**Issue by essy258** [section-engineering-education/engineering-education#5234]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
[Languages] Learn how to improve SEO in your Next.js Web App

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
[Languages] Learn how to improve SEO in your Next.js Web App

Use keyword research to improve your article's SEO.

#### Proposed article introduction
SEO is among the most important digital marketing techniques. Without good SEO practices, it is hard for any online business to thrive. SEO is made up of several elements, and to understand SEO as a whole, you need to know how these elements work. This article will look at how you can improve SEO in Next.js.

Next.js is a React framework that is SEO friendly. This framework enables server-side rendering, which speeds up the loading of your apps and websites and makes it easier for search engines to index your React sites.

#### Key takeaways 
1. What is Next.js
2. Search Engine Optimization (SEO)
3. Challenges associated with single-page applications (SPA)
4. SEO in Server-side rendering
5. How to optimize Next.js app for SEO
- Make your website index
- Create a sitemap
- Add meta tags

#### Article quality
This is a detailed guide on how you can improve SEO in Next.js. It is an interactive topic as readers will learn and practice how to optimize a Next.js web app for SEO. They will also learn the problem with single-page applications (SPA) and why they should work with server-side rendered applications to create a performant application and have good SEO at the same time.

#### References
[Please list links to any published content/research that you intend to use to support/guide this article.](https://nextjs.org/learn/seo/introduction-to-seo)

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @essy258 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
