### ISSUE TITLE
[Machine Learning] Building a deep learning model using Imbalanced dataset techniques.

### ISSUE THREAD

**Issue by jamesomina99** [section-engineering-education/engineering-education#5238]
#### Proposed title of article
[Machine Learning] Building a deep learning model using Imbalanced dataset techniques.

#### Proposed article introduction
An imbalanced dataset is a dataset in which the number of data points is not uniform among the classes. In an imbalanced dataset, we have a majority class and a minority class. Due to this imbalance, the model will have inaccurate results and model bias. We have various techniques that can be used to build a deep learning model. 

In this tutorial, we will build a customer churn prediction is to measure why customers are leaving a business. We will build a deep learning model to predict the churn and use precision, recall, `f1-score` to measure the performance of our model. We will then handle the imbalance in data using various techniques and improve the `f1-score`. We will build the deep learning model using TensorFlow.

The following techniques will be used: Under sampling majority class technique, oversampling minority class by duplication, and ensemble method technique.

#### Key takeaways 
1 What is an Imbalanced dataset.
2. Implementing the Under-sampling majority class technique and oversampling minority class by duplication.
3.  Ensemble method technique.
4.  Building a deep learning model using TensorFlow.

#### Article quality
This tutorial is a practical implementation of the techniques. We will implement the three techniques:  Under sampling majority class technique, oversampling minority class by duplication, and ensemble method technique. This will balance our dataset before we build the deep learning model using TensorFlow. In this tutorial, we will build a custom model. We will build a customer churn prediction model to measure why customers are leaving a business. This model can be implemented in any business.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @jamesomina99 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
