### ISSUE TITLE
The Necessary Elements of a WordPress Landing Page

### ISSUE THREAD

**Issue by Bennykillua** [section-engineering-education/engineering-education#5249]
### Topic Suggestion
The Necessary Elements of a WordPress Landing Page

### Writing sample(s):
https://www.section.io/engineering-education/building-excel-spreadsheets-using-python/

#### Proposed title of the article
The Necessary Elements of a WordPress Landing Page

#### Proposed article introduction
Take a look at any high-performing company today and you can bet that their landing page is simple, appealing, and easily accessible on any device, with a clear call to action.

In case you’re unfamiliar with the term, a landing page is a standalone web page and is a prerequisite for any marketing or advertising campaign. Typically, they’re designed to funnel your viewers/visitors toward a specific action; visitor comes, the visitor understands, and the visitor acts. The act here could be to simply sign-up or perhaps, to join your mailing list or even to make a purchase. If your visitor has to spend time to understand what you want them to do, you have crushed any attempts to gain clicks and perhaps, missed out on prospective customers/subscribers. 

This article will talk about the necessary elements you need in your WordPress landing page to stand out, why these elements are needed, and how to test your landing page after customization.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

- The reader will understand what a landing page is.
- The reader will learn the elements needed in a landing page to make it stand out 
- The reader will learn why these elements are necessary.
- The reader will learn how to test your site's responsiveness, which is one of the elements needed.

#### Article quality
Besides just listing the elements, I would mention why I feel the elements mentioned in this article matter. This should imprint a roadmap in our reader's mind of the elements needed. I would also show how to test your site's responsiveness.

#### References
[How to Create a Landing Page With WordPress](https://www.wpbeginner.com/wp-tutorials/how-to-create-a-landing-page-with-wordpress/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Bennykillua 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
