### ISSUE TITLE
Adversarial attacks on neural networks

### ISSUE THREAD

**Issue by DeewakarChakraborty** [section-engineering-education/engineering-education#5250]
### Topic Suggestion
Machine Learning

### Writing sample(s): 
[Blog Samples](https://www.section.io/engineering-education/authors/deewakar-chakraborty/)

#### Proposed title of article
Adversarial attacks on neural networks

#### Proposed article introduction
With the current research advancements in deep learning since the past decade, we can say that we live in the era of neural networks and expect them to play more significant roles in the coming years. From suspicious activity monitoring to self-driving cars, we are harnessing its abilities in countless dimensions. Now imagine a scenario where you are using a deep learning-based security system in your home, and some thief comes and fools the security system just by manipulating his appearance. In human eyes, we could quickly tell that someone unknown is entering your house, but the security system treats them as house owners. Yes, this can happen, and these types of attacks are termed Adversarial attacks. If you have trained a neural network without keeping an adversarial attack in your mind, you can easily be exposed to such security threats. And therefore, it can easily be fooled. This article will look at why and how neural networks are prone to adversarial attacks, implement an adversarial attack, and finally discuss how to prevent it.

#### Key takeaways 

The article will cover:

- Introduction to Adversarial attacks and their types.
- Why adversarial attack fools a neural network?
- Implementing an adversarial attack.
- How to prevent these attacks?

#### Article quality
Most of the articles present on the Internet about adversarial attacks on neural networks are vague and theoretical. In this article, not only we will discuss the maths behind it but also implement it from scratch.

#### References

- https://pytorch.org/tutorials/beginner/fgsm_tutorial.html
- https://towardsdatascience.com/how-to-fool-a-neural-network-958ba5d82d8a

### Conclusion
The reader will understand how to carry an adversarial attack and how to prevent it.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @DeewakarChakraborty 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
