### ISSUE TITLE
[Android]Remote Configuration and A/B Testing with Firebase on Android

### ISSUE THREAD

**Issue by benta-odek** [section-engineering-education/engineering-education#5252]
####  introduction
Firebase Remote Config is a free cloud service that allows you to change your app's behavior and appearance without prompting users to download an update.
A/B testing on the other hand removes the guesswork from deciding whether or not a modification to your app's features or content is useful.
You can now make changes to your app without having to publish an update. This article will show you how to use Firebase Remote Configuration in conjunction with A/B testing to alter the behavior of your app remotely and track the impact of those changes.

#### Key takeaways 
- What is remote configuration and what problem does it solves.
- what is AB testing and how does it work hand in hand with remote configuration.
- Integration of remote configuration
- How to perform AB test

#### Article quality
This article aims at explaining the basic and most appropriate way to integrate remote configuration,it also explains how AB testing is done and set up in conjunction with remote configuration.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @benta-odek 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
