### ISSUE TITLE
[Nodejs]: How to build a bookstore application API with authentication in Nodejs.

### ISSUE THREAD

**Issue by devteni** [section-engineering-education/engineering-education#5253]
## Topic Suggestion.
How to build a bookstore application API with Nodejs and MongoDB.

## Writing sample(s):
* https://hevodata.com/learn/etl-code-processes/
* https://hevodata.com/learn/data-science-visualization/
* https://www.stackhawk.com/blog/react-broken-access-control-guide-examples-and-prevention/

### Proposed title of the article.
How to build a bookstore app API with authentication in Nodejs.

### Proposed article introduction.
A bookstore application is a perfect starting point to understanding how CRUD operations work on the server side. This article would guide you through authenticating API routes with JWT by building a bookstore application with CRUD functionalities. 
 
While building this project, I would highlight best practices when handling asynchronous processes in terms of security and performance, and also alternative methods that can be opted for when building larger projects in Nodejs.

### Key takeaways.
In this article, the reader will learn:
* How to perform CRUD operations in MongoDB.
* How to implement user authentication alongside best practices.

### Article quality.
This article will be a step-by-step tutorial with an attempt to implement how CRUD operations work on the backend while building an authenticated API with Nodejs, Express, and MongoDB.

### References.
* https://nodejs.org
* https://expressjs.com
* https://mongodb.com
* https://mongoosejs.com

**Comment by hectorkambow** [comment]
👋  @devteni 

Welcome - Hector here.

This seems like a very cool topic - but regarding Node.js we are currently not publishing as many Node.js articles because we have more than enough currently in our EngEd library. 

As we did a big push the last few months and we are currently not accepting any more Node.js articles to publish for the time being.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by devteni** [comment]
Hi Hector. Sure!
