### ISSUE TITLE
(Python) License Plate Detection And Recognition Using Opencv And Pytesseract

### ISSUE THREAD

**Issue by kirurisimon** [section-engineering-education/engineering-education#5255]
### Topic Suggestion
(Python) License Plate Detection & Recognition Using Opencv And Pytesseract

### Writing sample(s): 
[Sample](https://www.section.io/engineering-education/create-a-screen-recorder-using-python-and-pycharm/#:~:text=%20Creating%20a%20Screen%20Recorder%20Using%20Python%20and,Datetime%3A%20We%20will%20need%20this%20package...%20More%20)
#### Proposed title of article
License plate detection and recognition using opencv and pytesseract

#### Proposed article introduction
License plate detection and recognition software are used in traffic management, car identification, surveillance, etc. You may have seen them in action in your favorite tech-based movie. You probably have always been curious about how they accomplish this.

Python helps us accomplish this using the following libraries:

- opencv
- imutils
- pytesseract

In this tutorial, we will learn how to use the above libraries together with Python for license plate detection and recognition. 

#### Key takeaways 

- The processes a software passes to detect and recognize a license plate.
- What are the above-mentioned libraries and how they are used in license plate detection and recognition.
- How to create a  program that detects and recognizes license plates using opencv and pytesseract.

#### Article quality
This article will combine both license plate detection and recognition. It will also have a well-explained code, not just a copied and pasted one.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @kirurisimon 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
