### ISSUE TITLE
[Android] Implementing Pre-Loading and Buffering Videos in Android with ExoPlayer

### ISSUE THREAD

**Issue by codewithjudy** [section-engineering-education/engineering-education#5256]
#### Proposed article introduction
Just like Youtube App, it is the wish of every Android Developer to understand how a video can be loaded so that a user doesn't have to wait while a video is loading.

For video streaming,  buffering happens when the app downloads a certain amount of data before it begins playing the video. You can see the data stored in the buffer while the next portion of the file downloads in the background.

The video can be loaded and cached before the user opens it. When the user finally opens the video. It just plays. Google has a library called ExoPlayer.

ExoPlayer is an application-level media player for Android. It provides an alternative to Android’s MediaPlayer API for playing audio and video both locally and over the Internet. ExoPlayer supports features not currently supported by Android’s MediaPlayer API, including DASH and SmoothStreaming adaptive playbacks. Unlike the MediaPlayer API, ExoPlayer is easy to customize and extend and can be updated through Play Store application updates.

#### Key takeaways 
- Understand what is pre-loading and buffering.
- Understand how Exoplayer can be used to pre-load a video.
- Implementing the caching of the video

#### Article quality
The article will be beginner-friendly whereby, I will take the reader from understanding the theories behind pre-loading, buffering, and caching. I will then make a systematic tutorial (step by step) on implementing the video preloading. The article will also be short.

#### References
N/A

**Comment by LinusMuema** [comment]
good topic @codewithjudy - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.
