### ISSUE TITLE
DevOps Pipelines Automation  with Cloud Build and Triggers

### ISSUE THREAD

**Issue by damikanye** [section-engineering-education/engineering-education#5258]
### Introduction

DevOps is a set of practices or stages that every application will go through before and after production deployment in the industry.  There are varieties of tools that can be used to automate these practices. All six stages of DevOps will be defined in this tutorial.
Cloud Build makes these stages very simple by using the infrastructure of the provider.  

### Objectives
In this tutorial, we will be learning how to automate DevOps pipelines using the cloud build. You will learn how to perform the following tasks;

1. Defining the stages of DevOps pipelines 
2. Create a Git Repository
3. Create a Simple Python Application
4. Test your Web Application in Cloud Shell
5.  Define a Docker build
6. Manage Docker images with Cloud Build and Container Registry
7. Automate build with Triggers
8. Test your build changes

### Article Goal
This tutorial targets the problem behind how to use cloud build to automate DevOps pipelines. This will clear the doubt of beginners or junior engineers at all levels on DevOps with the Cloud.

**Comment by LinusMuema** [comment]
good topic @damikanye  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.
