### ISSUE TITLE
How to Use Google Invisible reCAPTCHA in a Webpage and Customize It

### ISSUE THREAD

**Issue by EssyG10** [section-engineering-education/engineering-education#5259]
#### Proposed title of the article
[Languages] How to Use Google Invisible reCAPTCHA in a Webpage and Customize It
#### Proposed article introduction
"Completely Automated Public Turing Test to Tell Computers and Humans Apart" is what CAPTCHA stands for. The acronym itself highlights the significance of using captcha in a web application.

Google reCaptcha is the most popular captcha service, with unbeatable results in distinguishing humans from robots. In this article, we'll learn how to use PHP to integrate and customize Google's hidden reCaptcha.
#### Key takeaways 
- By the end of this article learners will be able to:
1. Automatically bind the reCaptcha challenge to a button element.
2. Programmatically bind the challenge to a button element.
3. Programmatically invoke the challenge.

#### Article quality
This article will be in context, brief and informative. Looking at the almost similar content on the internet, most of them are somewhat too harsh for beginners to understand and implement the code snippets provided in them. All his issues will be addressed in this article to ensure that it adds value to whoever comes across it.

#### References
N/A

**Comment by LinusMuema** [comment]
good topic @EssyG10  - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
