### ISSUE TITLE
[Languages]Building a Keylogger in Python

### ISSUE THREAD

**Issue by GeekEdmund** [section-engineering-education/engineering-education#5263]
#### Proposed title of article
Building a Keylogger in Python

#### Proposed article introduction
Keyloggers are a type of monitoring software used to record keystrokes made by the user with their keyboard.
They are often used for monitoring network usage and business networks as well as troubleshooting technical problems.
The goal of this tutorial is to make you aware of these kinds of scripts as well as learn how to implement such programs on your own for educational purposes.
We will be using python libraries such as pip3 keyboard, pip pynput : using cmd, PowerShell, or any other terminal to install them.

#### Key takeaways 
1. Importation and installing of modules to be used.
2. Implementing Press and release keys using Python.
3. Creation of a sample log file.
4. Creation and implementation of simple keylogger using Python code.

#### Article quality
The main insight of this article is creating awareness for the existence of such programs. Since it's designed in an easy-to-learn language having straightforward steps to follow.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @GeekEdmund 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
