### ISSUE TITLE
[API] JWT Authentication in Ktor

### ISSUE THREAD

**Issue by osirevaline** [section-engineering-education/engineering-education#5264]
#### Proposed article introduction
JSON Web Token (JWT) is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. This information can be verified and trusted because it is digitally signed. 

When a server receives a JWT, it can guarantee the data it contains can be trusted because it’s signed by the source. No middleman can modify a JWT once it’s sent.

In this tutorial, we will see how to create a REST API with Ktor that has JWT Authentication.

#### Key takeaways 
- Understand what is JWT
- Understand the pros and cons of using JWT
- Understand the components of JWT
- Understand what are Tokens
- Create a Ktor API with JWT Authentication feature

#### Article quality
The article will be short and clear, taking the readers from the point of not knowing about Ktor API to implementing JWT Authentication. The tutorial will be beginner friendly.

#### References
Ktor documentation

**Comment by LinusMuema** [comment]
Hi @osirevaline 

Could you please expand upon how your content will differ from what is already available through the [official docs](https://ktor.io/docs/jwt.html)? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by osirevaline** [comment]
Hello @LinusMuema 
From the Jetbrains official documentation for Ktor, the docs only show how to include Ktor in your project. But with this tutorial, I will create a simple REST API that has registration and login functionality. I will try and not replicate the docs.

**Comment by LinusMuema** [comment]
Hi @LinusMuema 
I'm not talking about the official docs for adding ktor. The link I sent was for an article specifically discussing JWT in ktor which is basically your article's subject matter. I wanted to know if it will be different from the one I sent. From your #key-takeaways, it seems the article won't be any different.

**Comment by osirevaline** [comment]
Thanks @LinusMuema 
Let me look for another topic
