### ISSUE TITLE
[Languages] Using Raspberry Pi and PHP to Get Started with IoT

### ISSUE THREAD

**Issue by fabulousDesigns** [section-engineering-education/engineering-education#5265]
#### Proposed title of article
Using Raspberry Pi and PHP to Get Started with IoT

#### Proposed article introduction
In this instructional exercise, We will have a prologue to IoT, Raspberry Pi fundamentals, and an essential LED On/Off with straightforward code models. Utilizing this article students will be in a situation to arrange a headless Raspberry Pi by introducing OS. We will have a walkthrough of how to introduce Raspbian OS in the Raspberry Pi zero W model. 

You can utilize any model of Raspberry Pi to go through this instructional exercise. By introducing Apache and PHP we will have established the PHP climate in the Raspberry Pi and went through the standard PHP Hello Word program. 
To launch this IoT projects venture, we will have a straightforward PHP program

#### Key takeaways 
By reading this article learners will  grasp the following:
- How to Install Raspbian OS in Raspberry Pi
- How to Install Apache
- How to Install PHP
- Raspberry Hello World using PHP
- Raspberry Pi Circuit Diagram for LED On / Off
- Programming LED ON / OFF using PHP on Raspberry Pi

#### Article quality
By taking a diversion from the contiguous, diehard learning of as usual PHP programming, we will have some fun by getting started with Raspberry Pi IoT projects in PHP and I swear this experience will boost learners enthusiasm towards programming. By reading this article learners will appreciate how you can use PHP and interact with other programs. In contrast with almost similar content in the internet, this article will go deeper in analyzing and giving more in depth snippets and explanations in order to boost learners creativity and adding immense value and quality in the community.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @fabulousDesigns 

This issue seems to be copied verbatim from [this article](https://phppot.com/php/getting-started-with-iot-using-raspberry-pi-and-php/) especially in the #articl-quality section. We are focused on more original content. 
Feel free to explore other options.
