### ISSUE TITLE
[Languages]Introduction to Python Overloading

### ISSUE THREAD

**Issue by LucidRay** [section-engineering-education/engineering-education#5271]
#### Proposed article introduction
Method overloading is a technique for adding new functionality to an already defined function, thereby overloading it. There are many other languages that support method overloading, and Python is one of them. The plus operator, for example, is an example of operator overloading because it can add both integers and strings. Then there's the minus operator, which can subtract integers, sets, and lists, and that's how Python has overloading features in its operators and functions.

Python overloading can be accomplished in two ways, which are listed below.

Function Overloading (Overloading of functions or methods  ).
 Operator Overloading (Overloading of operators ).

#### Key takeaways 
 Function overloading in python
              - overloading user-defined functions
              - overloading pre-defined functions
Operator overloading in python
Method overloading in python
#### Article quality
Unlike other articles, my article will take the reader step by step on the Introduction to Python Overloading. I,ll also use simple grammar in my article hence my article will be beginner-friendly.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @LucidRay 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
