### ISSUE TITLE
[Languages]Getting Started with Tuples in Python

### ISSUE THREAD

**Issue by EssyH** [section-engineering-education/engineering-education#5275]
#### Proposed title of article
Getting Started with Tuples in Python

#### Proposed article introduction
Tuples are used in Python to define, declare, and perform operations on a collection of values, and are represented by the parenthesis (). These tuples have a limited set of pre-defined functions, and the values are of fixed length and cannot be updated or changed after they are created. Tuple functions are immutable in Python programming, and the program does not allow copy functions.

#### Key takeaways 
What's a Tuple?
What's immutable in Tuple?
How are Tuples used in Python?
How to create a Tuple
Types of Tuples

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @EssyH 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
