### ISSUE TITLE
Building animated sign-in routes with React.js and bootstrap

### ISSUE THREAD

**Issue by KingsleyJack** [section-engineering-education/engineering-education#5279]
#### Proposed title of article
Building animated sign-in routes with React.js and bootstrap

#### Proposed article introduction

Building Animated sign-in routes with React.js and bootstrap

Proposed introduction: user registration and authentication is required in most modern websites, where visitors are requested to provide certain information to have access to contents and services offered such as social media websites, blogs, news websites, etc. Creating the perfect sign-in routes to enable and entice visitors or users register and login to your platform is a focal point in web development.
In this article, we will walk through the necessary steps and packages required to build animated sign-in routes with React.js.

Article quality:
#### Key takeaways 
It is expected that at the end of this tutorial the reader will understand and implement the following
- Building animated sign-in routes with React.Js and bootstrap
- using  Reactstrap in react application
- getting started with React.js
-  creating a from with Reactjs and bootstrap
- Adding animations with CSS and bootstrap.

#### Article quality
This article is a project based application of React.js and bootstrap in building animated routes not just for registration and sign-in but can be adapted to other routes and pages built with React.js.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by LinusMuema** [comment]
good topic @KingsleyJack  - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)

There are several grammatical errors in your article suggestion so please proof read your final draft.
