### ISSUE TITLE
[Machine Learning] Implementing Holistic Tracking using Python

### ISSUE THREAD

**Issue by smkinyan** [section-engineering-education/engineering-education#5280]
### Topic Suggestion
[Machine Learning] Holistic Tracking using Python

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Holistic Tracking using Python

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Human pose, face landmarks, and hand tracking in real-time can enable various modern life applications. The MediaPipe library already provides fast and accurate, yet separate, solutions for these tasks. Holistic tracking aims to combine them all in real-time into a semantically consistent end-to-end solution. This is a uniquely difficult problem requiring simultaneous inference of multiple, dependent neural networks.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to understand:
- What is Holistic tracking?
- Components of the Holistic tracking model and how they combine
- Implement holistic tracking in real-time

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

I haven't found many tutorials that have implemented the holistic tracking model. This is a unique tutorial.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [Holistic tracking](https://google.github.io/mediapipe/solutions/holistic)

**Comment by LinusMuema** [comment]
Hi @smkinyan 

Could you please expand upon how your content will differ from what is already available through the [GeeksForGeeks](https://www.geeksforgeeks.org/python-facial-and-hand-recognition-using-mediapipe-holistic/) website and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by smkinyan** [comment]
A couple of differences:
1. In that article, they've used a video feed input. I will be explaining to our readers how one can use a static image as input instead of a video feed.
2. I'm implementing this project using Google Colab. It's a web-based IDE different from what has been used in that article. In addition, accessing webcam feed using Google Colab isn't as straightforward as the other example which run on local runtime. Google Colab runs on the cloud and accessing the computers webcam isn't the same. My tutorial will take readers though that.
3. The article's difficulty level is rated as only to be understood by experts. As is the case with my previous articles, l always assume that my articles are read by beginners. Thus, this read will be much easier to follow and understand
 
@LinusMuema

**Comment by LinusMuema** [comment]
Hi @smkinyan 
Make sure to capitalise on your differences and originality as the article can still be closed on the plagiarism level. 

topi  approved :rocket:
