### ISSUE TITLE
[Machine Learning] Real-Time Iris Tracking using WebGazer.js

### ISSUE THREAD

**Issue by lcheptoo** [section-engineering-education/engineering-education#5281]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Real-Time Iris Tracking using WebGazer.js

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

WebGazer.js is an eye tracking library that uses common webcams to infer the eye-gaze locations of web visitors on a page in real time. It have a self-calibrator that trains a mapping between the features of the eye and positions on the screen. The library can be imported into your custom application or project as a script and only needs a standard webcam and a Node.js installation to get you started. It is written entirely in JavaScript and with only a few lines of code, can be integrated in any website that wishes to better understand their visitors and transform their user experience.
In this tutorial, you'll learn how to get started using using this super fast library.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to:
- Learn about the WebGazer.js javascript library.
- Implement an example using the WebGazer.js library.
- Learn about some use cases for this library.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [WebGazer](https://webgazer.cs.brown.edu/)

**Comment by LinusMuema** [comment]
Hi @lcheptoo 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
