### ISSUE TITLE
Reactive Flow with MongoDB, Kotlin, and Spring WebFlux

### ISSUE THREAD

**Issue by Simsamrosh** [section-engineering-education/engineering-education#5283]
### Topic Suggestion
Reactive Flow with MongoDB, Kotlin, and Spring WebFlux
#### Proposed article introduction
In this article, I will create a basic application that uses Spring Data Reactive MongoDB and Spring SSeEmitter to showcase a fully reactive flow

On the one hand, I will use Spring Data Reactive MongoDB to save data in a Mongo reactive database and combine it with the Server-Sent-Events technique to alert subscribers about new data . Additionally, I will make use of Spring Boot's Kotlin support.
And, because this is a Maven-based project, I'll launch the Spring Boot application after the Mongo DB server is up and running.

This method proposes a solution to the database blocking issues that plague typical non-reactive applications.

#### Key takeaways 
By the end of this article the reader should be able to:-
- setup for Maven-based project
- configure reactive mongo
- document by storing data in a MongoDB database
- Spring Data Reactive Repository
- send and receive data

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @Simsamrosh 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other [blog sites](https://www.baeldung.com/kotlin/mongodb-spring-webflux) and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
