### ISSUE TITLE
How to create combinations without using itertools in python

### ISSUE THREAD

**Issue by gracy20** [section-engineering-education/engineering-education#5285]
### Writing sample(s): 
https://www.section.io/engineering-education/object-serialization-and-deserialization-in-java/

#### Proposed title of article
[Languages] How to create combinations without using itertools in python

#### Proposed article introduction
Itertools is a Python package that uses techniques that operate with iterators to generate complicated iterator structures. Fast and memory-efficient, this module may be used in conjunction with other modules to construct iterator algebra.
In this tutorial, we'll learn how to use Python's built-in itertools to find distinct combinations of text.

#### Key takeaways 
By the end of this tutorial, the reader should be able to understand:
- What are combinations and the different combination methods that can be used.
- How to implement combinations using the iteration approach
- How to implement combinations using the recursion approach

#### Article quality
This will be in-depth covering all the aspects of this concept. The reader will appreciate easy language use with practicable examples where relevant. It will be beginner-friendly. I will also cover some parts of the combination using itertools

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @gracy20 

This article suggestion has various parts that have been paraphrased from [this article](https://www.geeksforgeeks.org/combinations-in-python-without-using-itertools/) therefore we can't continue with this article at the moment. Feel free to explore other options.
