### ISSUE TITLE
Creating decorators that accept parameters in python

### ISSUE THREAD

**Issue by Ushter21** [section-engineering-education/engineering-education#5286]
#### Proposed title of article
[Languages] Creating decorators that accept parameters in python

#### Proposed article introduction
When it comes to modifying a function or class's behavior, decorators are a strong and valuable tool for Python developers. With the assistance of several examples, we'll learn about Decorators with Parameters in this tutorial.
Because functions in Python are First-Class Citizens, they may be used in the same way as objects. With parameters, decorators are the same as conventional decorators.
The learner should have had prior exposure to decorators in python and function decorators.

#### Key takeaways 
By the end of this tutorial, the learner should be able to understand:
- What are decorators with parameters
- An overview of decorators in python
- How to create and use decorators with parameters

#### Article quality
I will use an easily understandable language that a beginner can easily understand. It will be an in-depth article exploring all the aspects of this concept. I will provide relevant examples that are practicable.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @Ushter21 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
