### ISSUE TITLE
[Languages]How to Design and Build Automated Mouse and Keyboard Using Python.

### ISSUE THREAD

**Issue by lizpart** [section-engineering-education/engineering-education#5287]
#### Proposed title of article
How to Design and Build Automated Mouse and Keyboard Using Python. 

#### Proposed article introduction

Python provides a library called keyboard which is used to get full control of the keyboard. 
It’s a small Python library that can hook global events, register hotkeys, simulate key presses, sticky keys, and much more.
This tutorial illustrates how to automate movements of mouse and keyboard using pyautogui module in python.
Since this module is not by default in the python library, we will be downloading it using any terminal or even windows cmd.
`pyautogui` is the module used here.
Python tracks and controls of the mouse using the coordinate system of the screen.
For instance, if your screen size or resolution is 1280x1024 pixel you will have a defined size defined by the size() function.

#### Key takeaways 

1. Controlling mouse movements using pyautogui module
2. Keyboard module in Python.
3.Designing and creating moveTo() function.
4.Designing and creating moveRel() function.
5. Designing and creating click() function.

#### Article quality
This article is designed in a fun and interesting way, with simple code snippets and steps to follow. Intended also to make the reader enjoy the page visited. 

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @lizpart 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
