### ISSUE TITLE
Getting Started with Singular Value Decomposition(SVD) Algorithm in Machine Learning

### ISSUE THREAD

**Issue by Faith034** [section-engineering-education/engineering-education#5290]
#### Proposed article introduction
Singular Value Decomposition(SVD) is a powerful technique that is widely used to solve a wide variety of problems in dimensionality reduction tasks. This algorithm works with a data matrix of the form m x n, where m is the number of rows and n is the number of columns. Thus the general idea for the SVD is that a rectangular matrix can be broken down into a product of three other matrices as shown in the following formula;
$A=U. \Sigma. V^T$

Where;
- A is our m x n matrix that we are interested in decomposing. This rectangular matrix can be for real numbers or for complex numbers.

- U is an orthogonal matrix
- $\Sigma$ is an m x n diagonal matrix, and 
- $V^T$ is the  transpose of an orthogonal matrix

For instance, if we have a rectangular matrix A of size m x n, then there exists an orthogonal matrix U of size m x m, an m x n diagonal matrix $\Sigma$ of size m x n, and an orthogonal matrix V^T of size n x n.

These three matrices have the following features;
First, the columns of U and V are made of the eigenvectors of A.

- Columns of U are orthonormal of eigenvectors of $AA^T$
  These columns are called the left singular vectors of A.

- Columns of V are orthonormal eigenvectors of $A^TA$
    These columns are called the right singular vectors of A.

- $\Sigma$ is an m x n diagonal matrix containing the square root from the eigenvalues from U or V in descending order.
 This diagonal entry of $\Sigma$ is called the singular value of matrix A.

All the calculations involved in obtaining these three matrices will be outlined in the article using a real matrix A. Since we shall be using a huge matrix in the real application, i.e., an image matrix, we shall also show how we can automate this computation in python.

#### Key takeaways 
By the end of this study, learner will have known;
- What is Singular Value Decomposition, and the kind of a matrix can be decomposed using this algorithm.
-  All steps and mathematical computations associated with each step of the SVD algorithm. They will understand this by having real matrix computation that we shall outline in the article. 
- Real-world applications of SVD, i.e., at Google in PageRank algorithm, previously at Facebook in image recognition, etc.
- How to perform SVD in python using a matrix sample.

#### Article quality
Since this algorithm has a wide range of applications in real world, the learner should be prepared with a deep understanding of the concept, and therefore this article will focus on offering all needed to get started with SVD such that an absolute beginner has an undoubt understanding of the concept. If that is not enough, the learner will know what function they need to run in order to decompose a matrix using SVD and how they can reconstruct the decomposed matrix in python.

#### References
N/A

**Comment by Daniel695** [comment]
@ahmadmardeni1 @Faith034

how do you say about this topic.

**Comment by louisefindlay23** [comment]
How does you article differ from those on the same topic? That is what your article quality section should cover.

**Comment by Faith034** [comment]
@louisefindlay23 
Most articles on the SVD algorithm only outline the steps involved in this algorithm without illustrating how they are performed. To cover their unclarity, they jump to implementation where staffs are computed with the aid of the machine and only attach an explanation to the machine's output. This article seeks to combine both educative intuition and coding sessions. So, we shall cover all mathematics involved at each stage of the SVD algorithm and later implement all we will have theoretically learned. This is what will make this article stand out from those already tried to cover the same topic.
