### ISSUE TITLE
How to Create a Custom URL Shortener with React, Django Rest Framework and SQLite Database

### ISSUE THREAD

**Issue by KayveTech** [section-engineering-education/engineering-education#5291]
#### Proposed article introduction
In this article, we are going to cover how we can build a Uniform Resource Locator (URL) shortener service. A URL shortener service simply takes in a long URL and converts it to an equivalent short URL that redirects you to the same webpage as the long URL. The short URL is better in that it is more suitable for posting on short media platforms and sharing with friends.

Our project will have a frontend part that will be used by the user to interact with the system, and a backend that will include server-side code and a database. We will build the front end using React and the server using Django. We will use the default SQLite database provided b Django for our database.

#### Prerequisites
-  Basic understanding of the Django Rest Framework.
- Basic understanding of the React `useState()` and `useEffect()` hooks.
- Understanding of the Fetch API.

#### Key takeaways 
- How to create a custom URL shortener.
- Working with React and Django.
- Fetching data from a database using Django and displaying it on React webpage.

**Comment by LinusMuema** [comment]
good topic @KayveTech  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.

Check the content however, we have several articles that cover the Django part but don't have a frontend like yours. Capitalise on that.
