### ISSUE TITLE
Things you need to take into consideration when building a backend software

### ISSUE THREAD

**Issue by Josh4324** [section-engineering-education/engineering-education#5292]
### Proposed title of article
Things you need to take into consideration when building a backend software.

### Introduction paragraph (2-3 paragraphs):
Backend can be referred to the part of a software that cannot be directly interacted it, it is also know as the data access part of the Application or software. It is the middleman between the frontend and the database. The frontend application sends the request to the backend and the backend interacts with the database or equivalent technology and sends the response back to the frontend application.  
The backend task includes but not limited to storing, updating and deleting data, process frontend requests, encrypting and decrypting data and others.
### Key takeaways: 

- Authentication and Authorization
- Logging
- Throttling and Rate limiting
- Cron Jobs
- Continuous Integration
- Elastic Search
- Firewall

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
good topic @Josh4324  - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
