### ISSUE TITLE
[Big Data] Why Move from ETL to ELT for your Fintech Products? 

### ISSUE THREAD

**Issue by jesmweni** [section-engineering-education/engineering-education#5294]
#### Proposed title of article
Why Move from ELT to ETL for your Fintech Products?
#### Proposed article introduction

Many fintech companies now find themselves collecting more data than ever before. But this data won't be of much use if it is just sitting in an Excel spreadsheet somewhere. So these firms need a fast, effective way of importing this into their analytics solutions. And for many, this is where ETL technology comes in. 

Standing for Extract, Transform and Load, these solutions take raw data from whatever initial form it arrives in, cleans and transforms it into a more standardized format that is easier for data scientists to work with, and add it to a data warehouse where it can be processed. This has become an everyday activity for many firms, but it's not the only way of getting information from the source and into a data warehouse. Increasingly, there's another similar, but not identical, alternative to consider in the form of ELT solutions.

#### Key takeaways 
ETL vs ELT. 
Should you use ETL or ELT for fintech data? 
ETL and ELT security. 
ETL and ELT tools.
#### Article quality
This article is not just another general comparison of ETL and ELT. It is unique in that it compares ELT and ETL in terms of their application in extracting fintech data. 

#### References
N/A

**Comment by ahmadmardeni1** [comment]
This is out of our preferred topics area. 
Please feel free to suggest an alternate topic to explore. 🚀 @jesmweni
