### ISSUE TITLE
Methods for Obtaining Data from an API in React

### ISSUE THREAD

**Issue by Walucy98** [section-engineering-education/engineering-education#5296]
#### Proposed title of article

Methods for Obtaining Data from an API in React
#### Proposed article introduction

This blog article discusses how to receive data from an API in React.
You should be acquainted with the React library and the Application Programming Interface before reading this post (API).
We will use the Game of Thrones API (aptly dubbed the API of Fire and Ice) to get and show all 12 Game of Thrones novels, as well as individual book data.
library is an excellent tool for creating complex, adaptable client interfaces. One of its most significant features is the ability to collect data from the external and react with it through the web application.

To get data from the API, we'll utilize JavaScript's built-in Fetch API. You can utilize any HTTP library, such as axios, for your program. We're utilizing the built-in Fetch one because we don't need to install anything.
#### Key takeaways 

-What is the Purpose of Data Fetching?
-Where Can You Get Data Fetching?
-Data Obtaining Methodologies
#### Article quality

This article will be of great help to those who are willing and interested in finding the know how of obtaining data from  an  API  with the help of React. In addition to that it will equip the user with knowledge of the powerful features of React which enables him or her to fetch data and interact with it.
#### References

N/A
.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Walucy98 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
