### ISSUE TITLE
[Networking] How Mobile IoT (LPWA) is Enhancing IoT Connections

### ISSUE THREAD

**Issue by jaykip** [section-engineering-education/engineering-education#5297]
#### Proposed title of article
How Mobile IoT (LPWA) is Enhancing IoT Connections

#### Proposed article introduction
Mobile IoT refers to low power wide area (LPWA) 3GPP standardized secure operator managed IoT networks in licensed spectrum. In particular, LPWA networks are designed for IoT applications that are low cost, use low data rates, require long battery lives, and often operate in remote and hard-to-reach locations. 

Due to the diversity of IoT application requirements, a single technology is not capable of addressing all of the LPWA use cases. For this reason, the mobile industry has focused on two complementary licensed 3GPP standards: Long-Term Evolution for Machines (LTE-M) and Narrowband-Internet of Things (NB-IoT). 

#### Key takeaways 

1. What mobile IoT entails
2. Why we need low power wide area networks
3. LTE-M vs NB-IoT
4. Mobile IoT deployments in real-life
    
#### Article quality
This article is more in-depth and uses an easy-to-understand language for beginners.

**Comment by ahmadmardeni1** [comment]
This is out of our preferred topics area. We are looking for programmer-centric concepts explained in fun and intuitive ways.
Please feel free to suggest an alternate topic to explore. 🚀 @jaykip
