### ISSUE TITLE
[AI] What makes automation smart? 

### ISSUE THREAD

**Issue by BridgetMwikali** [section-engineering-education/engineering-education#5298]
#### Proposed title of article
What makes automation smart? 

#### Proposed article introduction
Today, business leaders are using more robotic process automation (RPA), which is software that’s programmed for basic and repetitive tasks. Intelligent automation (IA) goes a step further by combining RPA with artificial intelligence for greater automation of business processes.

Today Intelligent automation is hailed as RPA’s worthy successor, leveraging machine learning, NLP, deep learning, computer vision technologies to reduce or eliminate manual efforts. Intelligent Automation interacts and executes processes a human might have done in the past but in a more efficient, and more effective manner.

IA incorporates algorithms capable of tasks such as handling exceptions, orchestrating decisions or even looping in chatbots for conversational messaging. 

#### Key takeaways 
1. What is Intelligent Automation?
2. Core technologies that make automation smart 

 •	Cognitive Agents
 •	Natural-Language Generation
 •	Machine Learning/Advanced Analytics
 •	Smart Workflow
 •	Robotic Process Automation

3. The value of Intelligent Automation
4. The future of intelligence automation

#### References
n/a

**Comment by ahmadmardeni1** [comment]
This is out of our preferred topics area. We are looking for programmer-centric concepts explained in fun and intuitive ways.
Please feel free to suggest an alternate topic to explore. 🚀 @BridgetMwikali
