### ISSUE TITLE
Getting Started with Python Data Preprocessing

### ISSUE THREAD

**Issue by 1992munorumark** [section-engineering-education/engineering-education#5299]
#### Proposed title of article

Getting Started with Python Data Preprocessing
#### Proposed article introduction

The initial stage in machine learning is data preprocessing, which involves converting raw data from diverse sources into a format that can be used to create reliable machine learning models. We'll go through every stage of the data pretreatment procedure in this post.
The adjustments we apply to our data before feeding it to the algorithm are referred to as pre-processing. Data Preprocessing is a technique for converting raw data into a tidy collection of data. To put it another way, anytime data is obtained from many sources, it is retrieved in raw format, which makes analysis impossible.
#### Key takeaways
 
-The libraries are being imported.
-Bring the data into the program.
-Taking care of the info that isn't there
-Categorical data processing
-Creating training and test sets from the database
-Scaling of features
#### Article quality

These article will enable the predecessor and immediate predecessor to solve problem of data processing and data wrangling.
Since in the article there are clear steps involved in the data preprocessing phase, the leaner will acquire the necessary skills to create and test set from respective databases and scale the features.
#### References

N/A

**Comment by WanjaMIKE** [comment]
This topic is already covered. Please suggest a new topic. Thank https://github.com/section-engineering-education/engineering-education/issues?q=Getting+Started+with+Python+Data+Preprocessing
