### ISSUE TITLE
[Languages] Implementing a serverless user authentication in React Native

### ISSUE THREAD

**Issue by ogoti-lilian** [section-engineering-education/engineering-education#5303]
#### Proposed title of article
Implementing a serverless user authentication in React Native

#### Proposed article introduction
React Native is one of the languages of building modern mobile applications. It is fast, cross-platform, and hook into native modules. It uses the language and patterns familiar to the frontend developers.
On the other hand, serverless technology has enabled developers to build modern applications without relying on traditional server infrastructure. This means that the developers need not worry about the backend since a third party takes care of it, and thus increasing their productivity.
This kind of plug-and-play infrastructure works well with the frameworks such as React and React Native, which makes it easy for small teams to grow their applications with minimum overhead costs.
In this guide, we will build a React Native application with user authentication and later connect it to a serverless database.

#### Key takeaways 
At the end of the guide, the learner will be able to:
- install and configure the easybase-react library
- use React hooks to implement the sign-up and sign-in workflow
- connect the React Native application with the serverless backend for handling user authentication and token administration

#### Article quality
In this proposed article we are developing our frontend using React Native unlike in the most published articles which are using React. We will later connect with the serverless backend database using an easy-react library instead of the physical database which needs regular maintenance from the developers.

#### References
- https://easybase.io/react/
- https://reactnative.dev/docs/getting-started

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @ogoti-lilian 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
