### ISSUE TITLE
Using the Reference log to Restore Lost Commits

### ISSUE THREAD

**Issue by Graceshee** [section-engineering-education/engineering-education#5305]
#### Proposed title of article
Using the Reference log to Restore Lost Commits
#### Proposed article introduction
What is Reference log?
Reference log is a mechanism to record when the tip of branches are updated. This command is to manage the information recorded in it. Basically every action you perform inside of Git where data is stored, you can find it inside of the reference log.This means that you can use it as a safety net: you shouldn’t be worried that a merge, rebase, or some other action will destroy your work since you can find it again using this command.

#### Key takeaways
1.Difference between git log and git reference log
2.Recovering deleted commits
3.Recovering deleted branches
4.Keep calm and keep track

#### Article quality
This will be an in-depth article explaining all aspects of this concept to ensure it is beginners friendly i will employ easy use of language.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
This is out of our preferred topics area. We are looking for programmer-centric concepts explained in fun and intuitive ways.
Please feel free to suggest an alternate topic to explore. 🚀
