### ISSUE TITLE
introduction to implementing a blockchain database in javascript.

### ISSUE THREAD

**Issue by KING-CYBERTON** [section-engineering-education/engineering-education#5310]
**Proposed title of article**
An introduction to implementing a blockchain database in javascript.

**Proposed article introduction**
In a quickly developing technological world,newbies tend to be discouraged by how fast new trends are being adopted in to the latest systems. Blockchain,being one of trends that is quickly advancing and might seem intimidating for new programmers to join in the fun of creating and improving software through implementing blockchain. Hence a good foundation is key to ease their way in it.

 Thus this article provides a comprehensive  look on blockchain and ways of implementation.It also
 gives a  tutorial on how to create you own blockchain in Javascript which is secure and shows proof of work.

**Key takeaways** 
1:What are the key things to have for blockchain  to function properly.
2:How to enhance security design on your blockchain.
3:To show proof of work on your blockchain.
4:its transformative potential.

 **Article quality**
There are little to no content available that provides content on blockchain programming for beginners. This article will provide a strong educational reference material for newbies in blockchain programming to pick up blockchain implementation in their day to day software need in programming.

 **References**
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - Please make sure to spellcheck and grammar check your article before submitting it - Tools: Write&Improve - ProWritingAid - Grammarly. @KING-CYBERTON 
Let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
