### ISSUE TITLE
[Cloud Computing] Overview of developing serverless applications in c#

### ISSUE THREAD

**Issue by ephraa** [section-engineering-education/engineering-education#5313]
#### Proposed title of article
Overview of developing serverless applications in c#

#### Proposed article introduction
Serverless computing has with no doubt revolutionalized the world of computing. Developers are finding fun using it since it has made their development efficient and more productive.
Before serverless, developers had to deal with resources that support their code. Since the launch of serverless, developers worry no more about the operating system and hardware architecture since serverless handles the server infrastructure. This gives developers more time to focus on writing good and quality code. 
This article will draw more attention to building a serverless function using c# and later be deployed on cloud providers such as AWS and Azure.

#### Key takeaways 
At the end of the article, the reader will understand:
- the usage of c# with Azure Functions and AWS Lambda
- the steps of writing c# code for AWS Lambda with Visual Studio
- how to run and publish to AWS Lambda

#### Article quality
The proposed article will focus in detail on both serverless platforms, Azure Functions, and AWS Lambda, unlike the existing articles which focus on the specific platforms.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @ephraa 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
