### ISSUE TITLE
[Machine Learning] Unsupervised machine learning using K-Means Clustering Algorithm

### ISSUE THREAD

**Issue by jamesomina99** [section-engineering-education/engineering-education#5317]
#### Proposed title of article
[Machine Learning] Unsupervised machine learning using K-Means Clustering Algorithm.

#### Proposed article introduction
Unsupervised machine learning is a category of machine learning which enables algorithms to identify patterns in data sets containing data points that are neither classified nor labeled. This allows algorithms to identify patterns and learn on their own. There is no guidance of the model but with time the model becomes better and better on its own. 

Some of the popular algorithms used are K-Means Clustering, Principal Component Analysis, and Hierarchical Clustering. In this tutorial, we will use the K-Means algorithm in building our model. K Means clustering algorithm is unsupervised machine learning technique used to cluster data points. A cluster is a collection of data points grouped together because of similarities within them.

We will implement the K-Means from scratch and build a custom model that solves the income group clustering problem.

#### Key takeaways 
1. What is unsupervised machine learning.
2. Clustering algorithms.
3. Elbow technique in clustering.
4. Exploring K-Means functions.
5. Implementing the model using the K-Means algorithm.

#### Article quality
In this article, we will discuss both the theoretical part of K-Means and Implement the algorithm practically by building a custom model.  We solve income group clustering problem using s-klearn, k-means, and python. The model will be able to cluster different people into income groups This tutorial will cover all the basics so that a reader is comfortable and can follow along easily. It gives an in-depth explanation to make a reader fully grasp unsupervised machine learning.

#### References
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @jamesomina99 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
