### ISSUE TITLE
How are Telemedicine Apps Enhancing Urgent Care? 

### ISSUE THREAD

**Issue by Annpurity** [section-engineering-education/engineering-education#5319]
#### Proposed title of article
How are Telemedicine Apps Enhancing Urgent Care? 
#### Proposed article introduction

A telemedicine application is a piece of software used to provide different healthcare services to patients. Patients can communicate with physicians in real-time with this custom telemedicine app. Besides, physicians can monitor patients’ health remotely using integrated IoT devices. Moreover, patients can share their medical data seamlessly using this app. These data get stored in physicians’ cloud servers.

Telemedicine apps have been very critical during the Covid-19 pandemic. There are different telemedicine apps available today and we will discuss the best ones in this article. 

#### Key takeaways 

1. Telemedicine vs telehealth 
2. Why telemedicine apps are significant to providing urgent care
3. Usage of telemedicine apps in the wake of Covid-19
4. Challenges in telemedicine software development
5. Top 5 telemedicine apps (their features, strengths, and drawbacks) 

#### Article quality
Besides providing a solid argument on why telemedicine apps are significant to enhancing urgent care, this article compares the top telemedicine apps to help patients choose the one that fits their needs, 
#### References
N/A

**Comment by LinusMuema** [comment]
good topic @Annpurity  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your {article type} very beneficial.

**Comment by Annpurity** [comment]
How are Telemedicine Apps Enhancing Urgent Care?
A telemedicine application is a piece of software used to provide different healthcare services to patients. Patients can communicate with physicians in real time with this custom telemedicine app. Besides, physicians can monitor patients’ health remotely using integrated IoT devices. Moreover, patients can share their medical data seamlessly using this app. These data get stored in physicians’ cloud servers.
Telemedicine apps have been very critical during the covid-19 pandemic. To minimize the risk of transmission of this disease, most people have adopted the application of telemedicine. There are different telemedicine apps available today and we will discuss the best ones in this article.
I.	MDLIVE                                                                                                                                                            
This app connects to medical and pediatric doctors. It is used in accessing behavioral health therapy services and psychiatry where you can make an appointment with a psychiatrist to discuss medication options for treatment. It offers fast, easy and convenient access to a doctor for nonemergency issues. This app can also be used to get a prescription for birth control pills. For behavioral health, MDLIVE professionals can provide support for mental health conditions such as depression, anxiety, panic disorder an phobia, substance use disorders and post-traumatic stress disorder. It is commonly preferred when primary care physician is not available. Average wait time is less than 15 minutes and a patient consults with a licensed and board-certified physician. Some of the pros of using this app include;
•	It accepts insurance
•	The patient is able to choose his/her own therapist or psychiatrist
•	Psychiatry or therapy appointments for children of ages 10 years and up is available
•	In case of someone who is deaf, live chat can be used during the appointment and this feature complies with the Health Insurance Portability and Accountability Act
•	One can request an appointment any time and day of the year
•	Therapy appointments are available over video or telephone
This app however has some shortcomings which include;
•	Even if you can request an appointment at any time, you may have to wait for some time to see a doctor
•	Because of limited availability of therapists, a patient may have a harder time scheduling for evening or weekend appointment
•	There are certain psychiatric medications such as stimulant medications and benzodiazepines that MDLIVE psychiatrists cannot prescribe

II.	Lemonaid
This app provides all services via its snazzy mobile app, video call or phone call. Professionals here are medical doctors and nurse practitioners. Over thirty conditions are treated with each condition having its own guidelines and process of treatment. They have their own lemonaid pharmacy where you can get your prescribed medication after consultation. Its extensive FAQ page enables you to get answers about the platform as well as each condition that its healthcare professionals treat. Lemonaid has its pros which include;
•	It has a mail order pharmacy
•	It is great for treating a single condition
•	It is convenient for a professional visit from your home
•	Professionals are transparent with their qualifications
•	It is an easy to use website and app
Some of the cons of this app are;
•	Certain conditions will require you to in person to complete testing
•	There’s a risk of something being missed because you’re not seeing a professional in person
•	It does not replace regular long-term medical care
III.	LiveHealth Online Mobile
This app remotely provides medical care for common health issues and urgent conditions as well as psychotherapy, therapy and psychiatric treatment. Patients meet with medical providers through video visits on their electronic devices. Some of the benefits of this app include;
•	It accepts many major insurance plans
•	It is free to sign up for livehealth online with no monthly fees
•	It is around-the-clock access to medical care for common health concerns
LiveHealth online has its own shortcomings which include;
•	A physician in LiveHealth does not prescribe certain medications such as muscle relaxants and weight loss prescriptions.
•	Customers must have a high-speed internet and use a digital device with a working camera and audio in order to use LiveHealth Online service
•	Except in cases of extreme emergencies, the law prohibits LiveHealth online doctors from providing controlled substances.
IV.	PlushCare
This platform provides urgent care, chronic condition treatment, prescription refills among others. This platform is straightforward and easy to use and it comprises of a high-quality doctor who can treat a variety of acute and chronic conditions. Patients can choose a same day appointment or schedule an appointment in advance. Some of the pros of this platform include;
•	Patients can schedule appointments at the time that works best for them
•	It accepts insurance from major health insurances
•	Customers can try plushcare for free for 30 days before committing to a paid membership
Things that customers need to consider about this platform are;
•	There’s a monthly membership fee that PlushCare customers are charged
•	PlushCare’s doctors cannot write prescriptions or refills for controlled substances due to laws regulating telehealth and prescription services
•	Customers must have a phone or computer with a camera since consultations here occur via video chat
V.	Doctor on Demand
This platform connects customers with certified, experienced medical and mental health care professionals. It offers help in conditions such as chronic health conditions, coughs and colds, skin conditions, flu symptoms, seasonal allergies among others. You can use Doctor on Demand for preventive health and wellness checkups.
Doctor on Demand pro and cons include;
	Pros
•	Patient’s insurance might cover the cost
•	You can schedule the appointments on any day of the week
•	Mental health support for children is available
•	A patient can choose his/her own therapist or psychiatrist bases on their qualifications
	Cons
•	You may need to wait for a few days for an appointment
•	Depending on the location of the customer, he/she may only have a few therapists to choose from
•	This service cannot treat severe mental health symptoms. In person treatment may be recommended
•	Without insurance, online teletherapy might be expensive compared to an in-person therapy
Although telemedicine is a promising technology dealing with a broad scope of healthcare services, there are a number of challenges facing its software development.
I.	Local legislations
There are regulatory standards which must be adhered to making telemedicine a challenging sphere. These regulations and legislations vary from one country to another.
II.	Security
Patients fear that their medical data may be hacked or sold as telemedicine applications deal with personal and confidential information. As a result, government has put in place some standards for clinical data sharing which makes it hard for developers.
III.	lack of trust
There is a need to provide a guarantee of the professionalism and social evidence in form of reviews of your doctors so as to gain the trust of patients.
IV.	Multi-state licensure
In the USA, practice of medicine across state borders is not allowed in order to protect their local licenses.
Adopting telemedicine comes with numerous benefits which include;
•	It is convenient as patients have unlimited access to medical care. Patients who cannot take time off from work as well as those living in remote areas can access care virtually.
•	Telemedicine is cost effective as it eliminates transportation expenses for regular checkups and also unnecessary non-urgent visits.
•	Medical staff can access without the need to find paper records due to the availability of electronic healthcare records.
•	 Telemedicine offers better access to more specialists regardless of their location.
•	Administrative staff can control the workload of doctors who have a super busy schedule.
To ensure continuous care to the community, medical care providers and patients should embrace and apply telemedicine as an appropriate option due to its convenience.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
