### ISSUE TITLE
How Polkadot Addresses Blockchain's Scalability and Security Limitations

### ISSUE THREAD

**Issue by Snzovi** [section-engineering-education/engineering-education#5321]
#### Proposed title of article
How Polkadot Addresses Blockchain's Scalability and Security Limitations

#### Proposed article introduction
The Polkadot crypto project is a next-generation blockchain that attempts to promote a heterogeneous multi-chain framework. It has garnered extreme attention from an entire community of investors, developers and users and is considered to be one of the most innovative projects in the cryptocurrency space.

Powered by the DOT, the network’s native coin, the Polkadot ecosystem tries to resolve many of the limitations that blockchains currently hold, like scalability and security. It serves as a solution that implements the technology’s distinctive features conjointly. 

#### Key takeaways 

- What is the Polkadot network? 
- How Polkadot addresses blockchain scalability issues
- How Polkadot addresses blockchain security issues
- Polkadot vs other major cryptocurrencies (Ethereum, Bitcoin, etc) 

#### Article quality
This article digs deeper into solving blockchain issues relating to scalability and security. While some published articles focus on other solutions, this article focuses on Polkadot, a leading interoperability blockchain. 
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Polkadot has its own blog and they covered the network in detail. 
Please feel free to suggest an alternate topic to explore. 🚀
