### ISSUE TITLE
The Roles of Artificial Intelligence in IoT Technology

### ISSUE THREAD

**Issue by Khadijah62** [section-engineering-education/engineering-education#5324]
#### Proposed title of article

**The Roles of Artificial Intelligence in IoT Technology**

#### Proposed article introduction
**This article gives a brief introduction on what Artificial Intelligence and IoT(internet of things) entails. 
It also explains the roles that Artificial Artificial Intelligence plays in IoT Technology**

#### Key takeaways 
1. The reader, would at the end of reading this article, completely understand what AI and IoT technology is simply about
2. The reader, would at the end of this article, understand the the roles that AI plays in IoT Technology and how they simply relate.
3. The reader would better comprehend the benefits of Including Artificial intelligence in IoT projects

#### Article quality
**This article would adopt a different approach in helping the reader understand the roles of AI in IoT Technology**

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @Khadijah62 

You haven't really added your article suggestion. Closing this to clear the queue. Ping me to re-open once you finish writing the suggestion. Read the instructions clearly to understand the submission process. :rocket:

**Comment by WanjaMIKE** [comment]
This topic appears to be oversaturated. Feel free to suggest another topic. Thanks
