### ISSUE TITLE
How to set up Go with the Prisma ORM

### ISSUE THREAD

**Issue by mosesreigns** [section-engineering-education/engineering-education#5325]
#### Proposed article introduction

Prisma allows you to write type-safe database schemas. When setting a database, everything needs to be well set to define what that database will look like. In this case, Prisma abstracts you from writing database queries. Thus you have to make sure you write safe database access schemas.

It provides a Prisma client that offers a way to write/type-safe query builder. Prisma abstracts you from writing queries. It provides Prisma client as a way to set up and write your database the data modeling, data validation, describing the relationships between different data fields, etc. Prisma client then enables you to generate queries and connect to the database of your choice.

As of now, Prisma supports different languages. Prisma has support for three major languages. These are TypeScript, JavaScript, and Go. In this guide, we will learn how to set up and connect a Go application with Prisma.

#### Key takeaways 

- What is Prisma
- What is Prisma Client
- Set up a Prisma Client
- Create Prisma Models
- Set a Go Prisma API

#### Article quality

This guide will help the reader get started with Go and Prisma. We will build a handy Todo rest API that lets the reader learn how to get started with a Go and Prisma application.

**Comment by LinusMuema** [comment]
good topic @mosesreigns  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your {article type} very beneficial.
