### ISSUE TITLE
AbstractRoutingDatasource using java

### ISSUE THREAD

**Issue by Samrosh** [section-engineering-education/engineering-education#5326]
#### Proposed title of article
AbstractRoutingDatasource using java

#### Proposed article introduction
AbstractRoutingDataSource is an abstract data source implementation that uses a lookup key to route getConnection() calls to one of several target DataSources. The latter is frequently (but not always) decided by the context of a thread-bound transaction.
In this article I will take the reader through Spring's AbstractRoutingDatasource as a means to dynamically determine the actual DataSource depending on the current context .
And finally demonstrate how we can keep DataSource lookup logic out of the data access code.

#### Key takeaways 
-Introduction to AbstractRoutingDatasource.
-Maven Dependencies.
-Datasource and holder contexts.
-Datasourse router and configurations.
-How to operate it.

#### Article quality
Unlike other articles, I will first introduce the reader to the context if he or she is a beginner, and then guide the reader through the context using simple but classic language that he or she will easily understand, using relevant examples in each topic to ensure that the reader finds it more practicable.
#### References
N/A

**Comment by LinusMuema** [comment]
Hi @Samrosh 

Could you please expand upon how your content will differ from what is already available through the [Baeldung](https://www.baeldung.com/spring-abstract-routing-data-source) website and documentation? We lean towards content that offers an original viewpoint/approach around programming-centric topics.

**Comment by Samrosh** [comment]
Hello, @LinusMuema I have checked the suggested article and other documentations.
To make my article unique, I will use AbstractRoutingDataSource to dynamically change the database schema/catalog which is not covered by other online blog sites. The article will also be written in an easy-to-understand manner to raise awareness of this open-source library among its users. The article will also be entertaining and expressed in a unique manner.

**Comment by LinusMuema** [comment]
Hi @Samrosh 
The Baeldung website also covers the same when it comes to data source so the article won't be providing much to the readers. You are more than welcome to pursue another more in depth topic.
