### ISSUE TITLE
Getting Started With Strapi, React and GraphQL

### ISSUE THREAD

**Issue by kimanikevin254** [section-engineering-education/engineering-education#5328]
#### Getting Started With React, Strapi, and GraphQL
Strapi is an open-source fully customizable headless CMS written JavaScript that enables developers to create APIs easily through a user interface. When working with Strapi and React, most developers use Axios or the Fetch API to get data from Strapi and display it on the frontend. In this article, we will cover a different approach which is to use GraphQL on the Strapi backend and Apollo on the frontend. We will use React to create our frontend.
We will create a blog application from scratch without using any templates. This blog application will enable the user to fetch all the blogs from Strapi, fetch a single blog by `id`, and also access blogs with tags.

#### Prerequisites
- Basic React knowledge.
- A basic understanding of how a headless CMS works.
- Basic GraphQL knowledge. 

#### Key takeaways 
- How to work with a headless CMS.
- How to use GraphQL in a Strapi powered website.
- Working with Apollo and React.

**Comment by WanjaMIKE** [comment]
Kindly, only submit one topic at a time. Let's wait until the other article is published. Thanks
