### ISSUE TITLE
[Databases] Understanding hybrid data models

### ISSUE THREAD

**Issue by g-wekesa** [section-engineering-education/engineering-education#5329]
#### Proposed title of article
Understanding hybrid data models

#### Proposed article introduction
Relational databases hold a leading position in the database industry and are better known as workhorses of the database industry. They are one of the most popular and commonly used mediums for recording, manipulating, and retrieving data. They find its application in varied and protean requirements including data mining, business intelligence, and analytical querying.

However, new requirements from database developers started coming up with the arrival of web 3.0 and data explosion with big data and social networks. These requirements focused more on relationships in data, thus making graph-structured data important. Graph
databases provide flexible structure to address graph data. 
However, there are various domains that give rise to graph and relational queries, which leads to the development of the hybrid database. 

Hybrid model design is the integration of two popular database models in a single framework in order to abolish the drawbacks of each system. In this proposed guide, we will use some of the JSON functionalities that are also available in MariaDB to demonstrate the concept of hybrid data models.

#### Key takeaways 
At the end of the proposed guide, the learner will be able to understand:
- how to model structured and semi-structured data
- how to index and query JSON data with MariaDB
- how to enforce the data integrity of JSON data

#### Article quality
The proposed article will explain in detail hybrid data models and how to implement them using examples that would be easy to understand by beginner readers. Unlike most of the articles found online which assume the reader is at the advanced level. The examples used and command are simple and straightforward.

#### References
N/A

**Comment by LinusMuema** [comment]
good topic @g-wekesa  - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)

**Comment by g-wekesa** [comment]
@hectorkambow @ahmadmardeni1 @LinusMuema Kindly do not close the topic, am finishing up on the article and i will pull request in a few days
