### ISSUE TITLE
[Languages] How to create a WinForms I/O manager for removable drives in C#

### ISSUE THREAD

**Issue by Donel254** [section-engineering-education/engineering-education#5331]
#### Proposed title of article
[Languages] How to create a WinForms I/O manager for removable drives in C#

#### Proposed article introduction
We use removable IO devices every now and then to transfer files to and from our PCs and to also store files. Sometimes we might need a tool to manage these devices and how they interact with our computers for security, privacy and other reasons.

In this tutorial we will create a tool that shall enable us to enable and disable USB ports on our computers and also change Read/Write permissions the removable drives. We shall start by going through a detailed guide of creating the UI then we shall work on the Code behind the above operations.

#### Key takeaways 
1. Designing WinForms 
2. Working with windows I/O manager
3. Implementing Read-Write permissions.
4. Enabling and disabling USB ports
5. Working with windows permissions

#### Article quality
Most articles don't go into details about this topics therefore I intend to explain this topic in a beginner friendly manner.
 
#### References
N/A

**Comment by LinusMuema** [comment]
good topic @Donel254 - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
