### ISSUE TITLE
[Android] Collapsing Action-Tool-Bar with Android Material Design  in  Kotlin

### ISSUE THREAD

**Issue by dvoredave** [section-engineering-education/engineering-education#5333]
### Topic Suggestion
Collapsing Action-Tool-Bar with Android Material Design  in  Kotlin

#### Proposed article introduction
In Material Design API level 30, the Android Toolbar is added as an Action Bar in the intended Activity. The activity title, navigation icons, and other views can be displayed in the Android toolbar.  Collapsing toolbar is a more advanced variant of the conventional toolbar widget that is used in conjunction with the Collapsing Toolbar Layout widget. This widget allows us to build an incredible toolbar motion called expanding and collapsing toolbar on-screen scrolling. This feature will raise the toolbar size that was initially specified in the App Bar Layout widget automatically. 

In this tutorial, we will discuss more on collapsing action toolbar with the android material design using a  step-by-step instruction for the Android Material Design Collapsing using a nested scrollable layout.

#### Key takeaways 
- Overview on what is Collapsing Action-Tool-Bar
- Step by Step Implementation
  1.  Create a New Project
  2. Adding application dependencies
  3. Adding a menu toolbar
  4.  Creating activity_main.xml layout file.
-  Testing our application 

#### Article quality
This will be a unique tutorial that will include a step-by-step explanation to allow all the readers to have a better understanding of the concepts used. It will also include an illustration (Application) to allow the reader to grasp the content covered easily.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @dvoredave 

If I may ask, will you be using coordinator layout for this article? And if so, what is Kotlin's role in the article.

:question:

**Comment by davidginmaina** [comment]
Hello, @LinusMuema 
I will be using coordinator layout for XMl design. I will also include Kotlin in creating the  scrolling effect with dynamic text appearance and toolbar coloring according to Image that I will use in the action tool bar. That is, I'll provide the bitmap of my picture view to the Palette API, which will produce the color in a PaletteAsyncListener depending on the image's background. After that, we can choose the color we want and assign it to our CollapsingActionbarLayout, which will then color our Actionbar as we scroll up.
Thank You.

**Comment by dvoredave** [comment]
Hello, @LinusMuema 
I will be using coordinator layout in the XML design. I will also include Kotlin for the scrolling effect with dynamic text appearance and toolbar coloring according to image's background color. That is, I'll provide the bitmap of my picture view to the Palette API, which will produce the color in a PaletteAsyncListener depending on the image.  After that, we can choose the color we want and assign it to our Collapsing Actionbar Layout, which will then color our Actionbar as we scroll up.
Thank You.

**Comment by LinusMuema** [comment]
Hi @dvoredave 
You can proceed with the article. However, watch out for official docs as the article can be closed if the content matches.

Topic approved :rocket:

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by dvoredave** [comment]
Can anyone reopen this for me?
