### ISSUE TITLE
How to build a client server application using Rust

### ISSUE THREAD

**Issue by wanjcarol** [section-engineering-education/engineering-education#5334]
#### Proposed title of article

How to build a client-server application using Rust 

#### Proposed article introduction

A web app is a service built on top of the Internet to allow computers to share and exchange data easily and reliably. In this case, the web services will be referred to as a client-server model. Communications are established between the two to exchange data. Clients will ask for data, and the computer that serves this data is called a server. This blog will discuss the concept of the client-server model as we implement the whole scenario using Rust.

The reader will be able to understand the concept of the client-server communication. The reader will then learn how to achieve this using Rust.

#### Key takeaways 

- What is a Client
- What is a Server
- How Client-Server works
- Set up Rust
- Create a Client with Rust
- Create a Server with Rust
- Exchange data between the Client and Server

#### Article quality

The reader will be able to understand the concept of the client-server communication. The reader will then learn how to achieve this using Rust.

**Comment by WanjaMIKE** [comment]
Kindly, only submit one topic at a time. Let's wait until the other article is published. Thanks

**Comment by wanjcarol** [comment]
Hello, @WanjaMIKE my previous article was published, am requesting if you can reopen this topic.

**Comment by WanjaMIKE** [comment]
Okay. Let's ensure that it adds value to the community. Thanks
