### ISSUE TITLE
How to use a raspberry pi as a firewall

### ISSUE THREAD

**Issue by ruphus-muita** [section-engineering-education/engineering-education#5336]
### Introduction

 Security is a critical aspect of any network setup. While firewalls can be deemed as expensive, there exists other alternatives to achieving their function. This article seeks to elaborate and educate the user on how they can spend less money while getting visibility and control of their network. The article is as a result of a project conducted after extensive research on the topic.

#### Key takeaways 
1. Why network security is important
2. Functions of a firewall in the network
3. How to use raspberry pi as a firewall

**Comment by LinusMuema** [comment]
Hi @ruphus-muita 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
