### ISSUE TITLE
[Machine Learning] Getting Started with NLP Transformers

### ISSUE THREAD

**Issue by norah254** [section-engineering-education/engineering-education#5338]
### Topic Suggestion
Getting Started with NLP Transformers

### Writing sample(s): 
N/A

#### Proposed article introduction
A transformer is a deep learning model that adopts the mechanism of self-attention, differentially weighting the significance of each part of the input data. It is mostly used in the field of natural language processing (NLP) and in computer vision (CV). Transformers are mainly used in areas like machine language translation, conversational chatbots, and powering better search engines. 

Natural language processing()NLP) is a subfield of linguistics and artificial intelligence concerned with the interactions between computers and human language, i.e programming computers to process and analyze large amounts of natural language data.

In this tutorial, we will look at transformers in NLP and their advantages over the traditional deep learning algorithms like recurrent neural networks (RNN). We will then build an NLP model using a transformer.

#### Key takeaways 

- Understanding the Model Architecture of the Transformer in NLP
- Understanding the working principles behind Transformers
- Modeling NLP using a transformer.

#### Article quality
This article gives in-depth information and handy tips on what has already been covered.

#### References
N/A

**Comment by LinusMuema** [comment]
good topic @norah254  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.

**Comment by WanjaMIKE** [comment]
Closed #5338 via #5760
