### ISSUE TITLE
[Languages]Using Computer Vision to Design and Create an Eye Tracker in Python

### ISSUE THREAD

**Issue by lizpart** [section-engineering-education/engineering-education#5341]
#### Proposed title of article
Using Computer Vision to Design and Create an Eye Tracker in Python

#### Proposed article introduction
We will be performing a video eye tracking, but as well get started with image because its simpler, since video is just a number images per second, making use of your the webcams or even typical computer camera.
In general, "detection" procedures are classifications based on machine learning that distinguish between object and non-object images.
For example, whether a photograph has a face and, if so, where the face is located.
This article is an in-depth tutorial for detecting and tracking your pupils’ movements with Python using the OpenCV library.
Since it is a step-by-step guide with detailed explanations, it provides a platform friendly even to starters.

#### Key takeaways 

1.How to perform classification.
2.Big to small object detection rule.
3.The face detection algorithm put into function.
4.Using and implementing the blob detection algorithm.

#### Article quality
The article is designed in a simpler to understand mode, creating awareness to users of such existing programs.  Codes expressed in fun and interesting ways influencing the user take more time in the page as well as frequently visiting it for more.
#### References
N/A

**Comment by LinusMuema** [comment]
Hi @lizpart 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
