### ISSUE TITLE
Data Visualization with Chartify

### ISSUE THREAD

**Issue by Bennykillua** [section-engineering-education/engineering-education#5342]
### Topic Suggestion
Data Visualization with Chartify

#### Proposed title of article
Data Visualization with Chartify

#### Proposed article introduction
While exploring data visualization in Python, I came across Chartify. Chartify is an open-sourced plotting library built by the Spotify team. It was built with the intent to make data visualization easier for data scientists.

Data visualization is an important skill and perhaps one of the most utilized features in data analysis and science today. This skill allows you to communicate insights to your shareholder in a visually appealing, easily digestible way. Talking about data science, Python is the language of choice; Python comes with different plotting libraries like Matplotlib, Seaborn, Plotly, Ggplot2, D3, and Bokeh. However, these libraries aren’t as ‘intuitive’ as Chartify.

In this article, you'll learn all about what Chartify is and how it differs from the other plotting libraries mentioned earlier. Later in the article, you will learn how to use Chartify to visualize your data.

#### Key takeaways 
- The reader will learn all about Chartify, the open-source visualization library.
- The reader will learn what makes chartify so ‘intuitive’
- I would do a data visualization project using the library so readers can have a step-by-step tutorial on how it can be used.

#### Article quality
This article will be an in-depth tutorial on how to use Chartify. Besides Spotify announcement, there hasn't been much talk or articles about this library. Also since it will be a step-by-step guide with detailed explanations, it provides a platform friendly even to starters.

The article will also be designed in a simpler-to-understand way and will create awareness to users of this open-source library. The article will also be fun and will be expressed in an interesting way.

#### References
[Introducing Chartify: Easier chart creation in Python for data scientists](https://engineering.atspotify.com/2018/11/15/introducing-chartify-easier-chart-creation-in-python-for-data-scientists/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Bennykillua 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by Bennykillua** [comment]
> Thanks @ahmadmardeni1 and will keep all the tips in mind and include some EngEd articles as references.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by Bennykillua** [comment]
Hi @hectorkambow The [article](https://www.section.io/engineering-education/data-viz-chartify/) and PR has been merged. Thanks
