### ISSUE TITLE
Continuous Integration and Deployment of Pipelines using Flask, Docker, and GitHub Actions

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#5343]
### Introduction
The CI and CD pipelines are the set of practices used in the industry to develop and maintain every deployed application. Developing applications from the ground up requires so many practices and keeping track of every change in order not to break the already deployed application in the production.

GitHub Actions is an automation tool provided by Github that makes continuous integration very smooth and easier. Applications docker containers are packaged into the swarm. In this article, we will experience building an interactive application.

### Key takeaways
In this tutorial, readers would experience how pipelines are been built and maintained using the mentioned tools and steps. The following shall be the point of discussion;

1. Development and Operations Overview
2. CI and CD pipelines Architecture
3. Clone Flask Application Repository
4. Docker Images and Containers Basics
5.  Continuous Integration and deployment with Github Actions

### Article Quality
This tutorial will focus on the continuous integration and the deployment of pipelines from development to production using GitHub Actions, Docker, and Flask. This will also help learners to understand the practices and how application pipelines are been maintained.

### References
N/A

**Comment by LinusMuema** [comment]
good topic @Horlawhumy-dev - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.
