### ISSUE TITLE
A dive into data encapsulation in java

### ISSUE THREAD

**Issue by gracy20** [section-engineering-education/engineering-education#5347]
#### Proposed title of article
[Languages] A dive into data encapsulation in java

#### Proposed article introduction
Using Java, encapsulation is the process of combining both code and data into a single unit. An encapsulation tries to hide the execution flow from the end-user. If the data member is private, it can only be accessed within the same class. The private member of another class cannot be accessed by any other class.

#### Key takeaways 
By the end of this tutorial the learner will be able to grasp and understand:
- What is data encapsulation in java and it entails
- Reasons as to why there is a need to use the concept of data encapsulation in java
- How to implement data encapsulation in java
- Data abstraction vs encapsulation in java

#### Article quality
As opposed to other almost similar articles on other sites, this will be more detailed and in-depth coverage. I will ensure there is understandability of the learner in that I will employ easy language use. This will be beginner-friendly as the examples will be more practicable and easy for the beginner to understand. As I look forward to covering this topic, the learner will also appreciate also the advantages and disadvantages of data abstraction in java.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @gracy20 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
