### ISSUE TITLE
How to work with coroutines in C++

### ISSUE THREAD

**Issue by Rachael06** [section-engineering-education/engineering-education#5349]
#### Proposed title of article
[Languages] How to work with coroutines in C++

#### Proposed article introduction
In C++, a coroutine is a function that may be restarted at any moment after it has been paused during execution. Coroutines and subroutines are sometimes referred to interchangeably, however, there are some subtle differences between the two. In several phases of development, coroutines are employed like asynchronous code execution with a good sequential code. When a coroutine returns a result to the caller, it does so by restarting a previously specified coroutine that is kept in a distinct place or stack that is already declared.

#### Key takeaways 
By the end of this tutorial the learner will understand:
- What are coroutines in C++ with what they entail
- Why or the need for coroutines in C++
- How to put the coroutines into practice which will form the part of its implementation
- The things you are supposed to do while working with coroutines in C++

#### Article quality
This article will be in-depth covering all the aspects of this concept. This article will make use of simple and easy language throughout with aim of enhancing understanding. The overall goal is to make it beginner-friendly moreso with language use and practicable examples where applicable. I will offer a description of my codes. I will also be covering subroutines as well as their relation to coroutines in C++.

#### References
N/A

**Comment by LinusMuema** [comment]
good topic @Rachael06 - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
