### ISSUE TITLE
 Using Composer 2.0 to Create a Chatbot Without Writing a Line of Code.

### ISSUE THREAD

**Issue by Juskam** [section-engineering-education/engineering-education#5350]
#### Proposed title of article
 
Using Composer 2.0 to Create a Chatbot Without Writing a Line of Code.

#### Proposed article introduction

Microsoft's Bot Framework SDK allows programmers to create interactive encounters in their preferred programming languages, such as C#, JS, Python, and Java.The Bot Framework Composer is an open-source integrated development environment based on the Bot Framework SDK. You get to have a visual designer tool as a programmer to visualize your convos.You can even assess your bot and allocation it to Azure from that canvas.This low code tool is a great introduction on your very first chatbot.

#### Key takeaways 

By the end of this tutorial the learner will be able to;
1.Pick a template
2.Name the bot 
3.Start the bot
4.Find the greeting response
5.Customize the bot response to "hello world"
6.The final run in webchat and emulator

#### Article quality

This article will be in context, brief and informative. My approach to this article is unique because it is broken down into bits and the explanation is straight to the point. I have used simple language to ensure it is beginner-friendly.

#### References

N/A

**Comment by LinusMuema** [comment]
Hi @Juskam 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
