### ISSUE TITLE
Basics of XAML in Easy Samples for Multiplatform Avalonia .NET Framework

### ISSUE THREAD

**Issue by chepnelly** [section-engineering-education/engineering-education#5351]
### introduction
In this tutorial, I provide a short Avalonia XAML tutorial with easy-to-understand examples. It covers topics such as utilizing XAML to represent classes and properties, the XAML namespace, simple markup extensions, the XAML resource, and using XAML for non-visual projects.
Avalonia is a new open source package that closely resembles WPF but, unlike WPF or UWP, operates on a wide range of platforms, including Windows, MacOS, and many varieties of Linux, and is more powerful in many ways than WPF.
This tutorial's goal is to continue presenting sophisticated Avalonia ideas using basic coding examples. The following subjects are explored in particular: Avalonia Commands, Avalonia User Controls, Avalonia Custom Controls, Data Templates, and View Models are all examples of Routed Events.
### key takeaways
- multiplatform UI Coding with AvaloniaUI in Easy Samples
- about AvaloniaUI
- what is XAML?
- Avalonia XAML Resources
### conclusion
At the end of this tutorial the reader will be to understand what XAML and Avalonia XAML Resources .He will also be able to learn more about AvaloniaUI  and multiplatform UI Coding with  AvaloniaUI in easy samples.

**Comment by LinusMuema** [comment]
Hi @chepnelly 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
