### ISSUE TITLE
Getting Started With React, Strapi, and GraphQL

### ISSUE THREAD

**Issue by kimanikevin254** [section-engineering-education/engineering-education#5356]
#### Getting Started With React, Strapi, and GraphQL
Strapi is an open-source fully customizable headless CMS written JavaScript that enables developers to create APIs easily through a user interface. When working with Strapi and React, most developers use Axios or the Fetch API to get data from Strapi and display it on the frontend. In this article, we will cover a different approach which is to use GraphQL on the Strapi backend and Apollo on the frontend. We will use React to create our frontend.
We will create a blog application from scratch without using any templates. This blog application will enable the user to fetch all the blogs from Strapi, fetch a single blog by `id`, and also access blogs with tags.

#### Prerequisites
- Basic React knowledge.
- A basic understanding of how a headless CMS works.
- Basic GraphQL knowledge. 

#### Key takeaways 
- How to work with a headless CMS.
- How to use GraphQL in a Strapi powered website.
- Working with Apollo and React.

#### Article quality
My article will be unique in the following ways:
- It will explain to the user the concept of CMS and how a headless CMS works.
- It will take the user through the basics of Strapi and Apollo (This will help new readers to follow along).
- It will contain attached screenshots to show the user how to set up Strapi.
- I'll explain the process of setting up a blog site fro scratch without using any template

**Comment by louisefindlay23** [comment]
Please fill in the article quality section.

**Comment by annemwangi** [comment]
#### Article quality
My article will be unique in the following ways:
- It will explain to the user the concept of CMS and how a headless CMS works.
- It will take the user through the basics of Strapi and Apollo (This will help new readers to follow along).
- It will contain attached screenshots to show the user how to set up Strapi.
- I'll explain the process of setting up a blog site fro scratch without using any template

**Comment by kimanikevin254** [comment]
#### Article quality
My article will be unique in the following ways:
- It will explain to the user the concept of CMS and how a headless CMS works.
- It will take the user through the basics of Strapi and Apollo (This will help new readers to follow along).
- It will contain attached screenshots to show the user how to set up Strapi.
- I'll explain the process of setting up a blog site fro scratch without using any template

**Comment by kimanikevin254** [comment]
done @louisefindlay23 🚀

**Comment by louisefindlay23** [comment]
Approved but ensure you cover the unique aspects (no templates and screenshots) with plenty of detail.

**Comment by WanjaMIKE** [comment]
Closed #5356 via #6194
