### ISSUE TITLE
[Languages] Building a User Signup and Login logic using MERN Stack

### ISSUE THREAD

**Issue by OMONDIELLY** [section-engineering-education/engineering-education#5359]
### Topic Suggestion
Building a User Signup and Login logic in MERN

### Proposal Submission
Building a User Signup and Login logic using MERN Stack

#### Proposed title of article
Building a User Signup and Login logic using MERN Stack

#### Proposed article introduction
[Languages]  Building a User Signup and Login logic using MERN Stack

MongoDB, Express, ReactJS, and NodeJS - popularly grouped as MERN is a growing tech stack among developers, capable of building fully-fledged application. Its desirability arise from the stack's simplicity, vast community support and reference point, and the flexibility each tool comes with.
In this article, we will learn how to build a simple user sign up and login system component using MERN logic. In the end, we will have an interactive form that sends user's data to a database from where a user can log in.

#### Key takeaways 
1. What is MERN.
2.  How to setup developer environment, project and other prerequisites.
3.  Creating Sign up and Login components
4.  Creating server instance in Node and a database schema in Mongo
5.  Sending form data to the backend tier.

#### Article quality
This article will be a step by step tutorial, highlighting to readers the art of clean coding, data validation and how to catch errors in various steps.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
