### ISSUE TITLE
Understanding AES encryption and its implementation 

### ISSUE THREAD

**Issue by Daniel-muriithi** [section-engineering-education/engineering-education#5360]
#### Proposed title of the article
Understanding AES encryption and its implementation 

#### Proposed article introduction
Data is live blood for every organization. Organizations that manage data and individuals who own it should not take data security and data privacy lightly. Data security and data privacy are two different terms that look almost similar in meaning. However, Data Security is a process of protecting data from unauthorized access, use, and corruption throughout the data lifecycle. While data privacy means using sensitive data of organizations and individuals with the consent of its owner. The user informs upfront what data the user will collect and how he’ll use it before using sensitive data.

Moreover, there are a few methods to protect data from unauthorized access, such as data encryption, Hashing, tokenization, and key management practices over the different platforms, etc. Further, encryption is a very secure method to protect data as it produces different codes for the same set of data. There are various types of data encryption techniques. The Advanced Encryption Standard (AES) is the most secure and advanced data encryption technique.

The implementation of AES involves doing a set of simple operations repeatedly. Each repetition is called a `round.` Depending on the size of the key (128, 192, or 256 bit), the input (block of 16 bytes) goes through 10, 12, or 14 rounds. In applying the 2 Big Ideas - Diffusion and Confusion, AES makes sure that each bit in the 16-byte block depends on every bit in the same block from 2 rounds previously. 

#### Key takeaways 
- What is AES encryption
- Understanding the different features of AES
- Understanding how does AES Encryption work
- Understanding the AES algorithm
- Implementation of AES encryption

#### Article quality
To make the article unique and more in-depth I will cover every concept of  AES and how to implement it, unlike other documentations that only give the theory part of the AES encryption. Also, my article will be beginner-friendly with using relevant examples to illustrate.

### References
N/A

**Comment by louisefindlay23** [comment]
What are the unique concepts you plan to cover about AES?

**Comment by Daniel-muriithi** [comment]
Hello @louisefindlay23, This article will provide an in-depth knowledge in AES encryption . Since other blog sites only provide documentation for the AES encryption, I'll show the reader how to use Cryptographic Algorithms Interpretation and Implementation using Python programming language. The article will also be written in an easy-to-understand manner to raise awareness of this open-source library among its users. The article will also be entertaining and expressed in a unique manner.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
