### ISSUE TITLE
Build a complete signup and login page using PHP and JavaScript and connect to MySQL database.

### ISSUE THREAD

**Issue by samtecinnovator** [section-engineering-education/engineering-education#5362]
**Topic Suggestion**
Build a complete signup and login page using PHP and JavaScript and connect to MySQL database.

**Proposal Submission**
Build a complete signup and login page using PHP and JavaScript and connect to MySQL database.

**Proposed title of the article**
Build a complete signup and login page using PHP and JavaScript and connect to MySQL database.

**Proposed article introduction**
Build a complete signup and login page using PHP and JavaScript and connect to MySQL database.

Structured Query Language (SQL) is a special-purpose programming language designed for managing data held in a
Relational Database Management System (RDBMS). SQL-like languages can also be used in Relational Data Stream
Management Systems (RDSMS), or in "not-only SQL" (NoSQL) databases.

**Key takeaways**
create a responsive user interface for login and signup page.
use javascript to give parameters when the user wants to signup or log in.
Creating database schema in Mysql and connecting it with our page using PHP.
Authenticate and authorize users from the backend using PHP-Mysql API.

**Article quality**
This article will be a step-by-step tutorial, highlighting to readers the art of clean coding, data validation, and how to catch errors in various steps.

References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
