### ISSUE TITLE
[Machine Learning] Leveraging GPT-Neo to Generate AI-based Blog Content

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#5372]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Leveraging GPT-Neo to Generate AI-based Blog Content

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

In this Python tutorial, we'll learn how to create an ML web app that gives you AI-generated Blog Content. The model that's used is GPT-Neo from Eleuther AI which is a GPT-3 Alternative. GPT-Neo model is used with Minimaxir's AiTextgen for text Generation. Gradio App is used for quickly creating a Web App UI for the AI Generated Blog Content. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to learn:
1. About GPT-Neo
2. How to leveraging GPT-Neo to Generate AI-based Blog Content
3. Integrate it into the Gradio app

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

GPT-Neo is a fairly new algorithm released early this year. Not a lot of content is available on it. In addition, most of the tutorials I've checked are very long with a lot of boilerplate code. My tutorial aims to show our readers how they can build an AI based blog content generator and learn how to get setup and leverage the model for a whole range of use cases with only 4 lines of code. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [Gradio](https://gradio.app/)
- [GPT Neo](https://github.com/EleutherAI/gpt-neo)

**Comment by louisefindlay23** [comment]
Please fill in the article quality section

**Comment by Bayler** [comment]
> Please fill in the article quality section

Done @louisefindlay23

**Comment by WanjaMIKE** [comment]
Closed #5372 via #5564
