### ISSUE TITLE
Getting started with Database recovery

### ISSUE THREAD

**Issue by Legitimacy426** [section-engineering-education/engineering-education#5373]
### Topic Suggestion
Database recovery

#### Proposed title of article
Getting started with Database recovery

#### Proposed article introduction
 [Database]Damage to a database may occur due to one or some of the following causes;  human initiated errors, invalid or incorrect  inputs,  viruses in the computer, natural catastrophes or program errors. Besides one or some of the above  mentioned risks occurring, the organization still depends on the database. It is up to the database management system to have a way of restoring  the database  quickly  and accurately after  damage 

#### Key takeaways 
1.What is Database recovery
2.Types of Database failures
3.Recovering facilities

#### Article quality
Since most articles focus on database creation and usage and forget on the key point that databases also fail at some point,
This article will help readers understand everything to do with database failures and how to recover the database

#### References
N/A

**Comment by louisefindlay23** [comment]
Will you cover a specific type of database (SQL vs NoSQL) or several?

**Comment by Legitimacy426** [comment]
Several databases in general

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
