### ISSUE TITLE
Understanding how to implement java packages

### ISSUE THREAD

**Issue by Nganga89** [section-engineering-education/engineering-education#5374]
#### Proposed title of article
[Languages] Understanding how to implement java packages

#### Proposed article introduction
Classes, sub-packages, and interfaces can all be contained within a single Java package. All that has to be done is to group together classes that are similar. A simple import class from existing packages is all we need to do after this. Packages are collections of related classes, some of which are meant to be disclosed to the outside world and others that are meant to be kept private. Packages' existing classes can be used as many times as necessary in our application. There is a strong correlation between package name and directory structure.

#### Key takeaways 
By the end of this tutorial, the learner will understand:
- What are java packages
- Why use packages in java
- Steps that are required in the implementation of java packages
- Various types of packages

#### Article quality
I will ensure in-depth coverage of this article. I will provide a step-by-step and a procedural way towards the implementation of java packages. I will ensure the article is beginner-friendly throughout the article and to enhance understanding I will make use of easy and simple but understandable language. In the end, the learner will be able to create and name packages as well as import them and this will create awareness about this concept. 

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appears to be over saturated. Java packages are already used in numerous articles. Feel free to suggest another topic. Thanks
