### ISSUE TITLE
Working to implement Blockchain Application in ASP.NET Application

### ISSUE THREAD

**Issue by sabin254** [section-engineering-education/engineering-education#5376]
#### Proposed title of article
Working to implement Blockchain Application in ASP.NET Application.

#### Proposed article introduction
Such an article explains how to use C# and.NET to implement a Smart contract in an ASP.NET Core application.The article explains and provides instructions for developers who want to create blockchain-based applications by incorporating Smart Contracts into their own custom software.In this case, we'll make use of the contract address to communicate with the ASP.Net Core app.

#### Key takeaways 
By the end this tutorial, learners will be able to;
1Create an entity Model to return the API response within it.
2.Add Api Request Service samle
3.Add Smart Contract service
4.Add Smart Contract service
5.Create Action Method and View Page for Contract Call
6.Add Contract Call Controller under the Controller Folder
7.Button click Event using Ajax Post
8.Testing Contract Call
9.conclusion

#### Article quality
This will be an indepth article explaining all aspects of this concept.To ensure it is begginner's friendly i will employ easy use of languages to enhance understanding

#### References
N/A

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
