### ISSUE TITLE
[Android] Passing numerous data between activities - Android fundamentals

### ISSUE THREAD

**Issue by davigin** [section-engineering-education/engineering-education#5378]
### Topic Suggestion
Passing numerous data between activities - Android fundamentals

#### Proposed article introduction
Using Kotlin as our language and Android Studio as our IDE,  we  can utilize objects of the type Intent to pass data. Intent is usually used to initiate an activity, transmit a broadcast receiver, initiate a service, and sending  messages between two or more activities.  We can start a new second Activity and send some data to it, much more easily with the aid of Kotlin Extension Functions.  The ids of the start and destination activities must be sent to the intent object that aids in communication purpose.

In this tutorial, we will discuss about Passing numerous data between activities - Android fundamentals in details and also see how to send data from one Activity to another on Android Activities.

#### Key takeaways 
- Introduction to what is datapassing
- Creating a new project 
- Creating and working with first activity xml_file
- Implementing First_Activity.kt
- Creating and working with Second Activity xml_file
- Implementing Second_Activity.kt
- Linking the activities using Manifest xml layout
- Debugging your code for output

#### Article quality
This will be a unique tutorial  that will use simple language with illustrations to explain its concepts for the reader understanding. It will also go beyond other official documentation to help the rest of EngEd.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appears to be over saturated. We focus more on unique projects. Feel free to suggest another topic. Thanks
