### ISSUE TITLE
[Networking]Getting to comprehend IP Addresses, Subnets, and CIDR documentation.

### ISSUE THREAD

**Issue by cathy-254** [section-engineering-education/engineering-education#5380]
### Topic Suggestion
Getting to comprehend IP Addresses, Subnets, and CIDR documentation.

#### Proposed article introduction
Understanding networking is a core part of configuring complicated internet setups. This has repercussions when attempting to communicate quickly across servers, creating secure network regulations, and keeping your nodes organized.
In this article, I will go over some of the more particular principles involved in developing or communicating with networked computers. I will specifically examine network classes, subnets, and CIDR format for grouping IP addresses.
#### Key takeaways 
1. IP addresses
2. Classes of IPv4 Addresses and Reserved Ranges
3. Subnets and Netmasks
4. CIDR documentation
#### Article quality
This article will help the learner to have a working understanding of some of the networking implications of the IP protocol. It will also help the learner to understand what is going on while configuring network software and components.
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic or make this one more in-depth by covering additional networking concepts or packages.
