### ISSUE TITLE
understanding the essentials of a good programming environment for different languages

### ISSUE THREAD

**Issue by CT2034-hash** [section-engineering-education/engineering-education#5381]
**Proposed title of article**
Understanding the essentials of a good programming environment for different languages

**Proposed article introduction**
Though Environment Setup is not an element of any Programming Language, it is the first step to be followed before setting on to write a program. Thus it is not something to be over looked as a good foundation and preparation is key to any programming language. Environment could be the difference between how fast you get to complete a task and the quality of product.

Over the years many languages have been created and some are different from the other and require different environment set ups to start programming. In this article we are going to tackle the different needs in  some of the main and popular languages before  starting to program and developing software.

**Key takeaways** 

1. What are IEDS and the best to use for particular tasks.
2. Resource needed to program I.e libraries and compilers.
3. Operating systems well suited for different types of programming and software development.

**Article quality**
There is little information on what one nees before starting to code  since it is presumed obvious. This is rarely the case,finding the best IEDs(Integrated development environment Software)for a programming language that is new to you may prove to be difficult as there many such software out there but may not  serve your needs.

Thus this article takes a deep dive into the dos and don’t of set up an environment for optimum programming experience and productivity

**References**
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
I think the needs and basics of programming are well covered in numerous articles and tutorials. This topic, therefore, does not add much value. Feel free to suggest a new topic. Thanks

**Comment by KING-CYBERTON** [comment]
Thank you for the feed back.
