### ISSUE TITLE
[Languages]How to Create a Doubly Linked List in Python

### ISSUE THREAD

**Issue by LucidRay** [section-engineering-education/engineering-education#5382]
### Topic Suggestion
How to Create a Doubly Linked List in Python

#### Proposed title of article
How to Create a Doubly Linked List in Python

#### Proposed article introduction
In Python, we also have doubly linked lists, which allow us to traverse in both directions. With a single linked list, we can only traverse in one direction, but with a doubly linked list, we can traverse in both directions, forward and backward. When we talk about a doubly-linked list in general, it always has three components inside it: data, a reference to the previous node, and a reference to the next node. However, this is not the case with a single-linked list. We can also traverse and search elements in both directions by using it. In the following section of the tutorial, we will see how to implement the linked data structure in Python so that beginners can better understand it.
#### Key takeaways 
How does doubly link work in python
Advantages and disadvantages of DLL
Steps needed to implement the linked list in python

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Please fill in the article quality section so we can review your article.

**Comment by LucidRay** [comment]
Hello @louisefindlay23 
Unlike the other articles, my article will cover a bit of Doubly Linked List in Python, its advantages and disadvantages. I'll take the reader step by step through how to create a Doubly Linked List in Python, i will also use simple grammar hence my article will be beginner-friendly

**Comment by louisefindlay23** [comment]
There are other articles that exist that cover all the topic you plan to cover such as [this one](https://www.geeksforgeeks.org/doubly-linked-list/). Please extend your article to make it more unique or suggest another topic.

**Comment by LucidRay** [comment]
hey I've checked the article.....it talked more about singly linked list.....i believe my article will be unique just give me a chance

**Comment by louisefindlay23** [comment]
There are several [articles](https://www.google.com/search?client=firefox-b-d&q=How+to+Create+a+Doubly+Linked+List+in+Python+), not just the one I used as an example. Are there any other areas you could add to make yours unique?
