### ISSUE TITLE
Next.js custom Favicons that dynamically update with React

### ISSUE THREAD

**Issue by RisoriTofa** [section-engineering-education/engineering-education#5384]
#### Proposed title of the article

Next.js custom Favicons that dynamically update with React

#### Proposed article introduction

[Language] Have you come across websites which the Favicons change on certain state changes.
Such state changes may occur when there is a new email, the favicon displays a blinking mail with a new email counter on the show.
Another best example is when the Favicon displays loading animations when webpage resources are loading. This shows that the Favicon is being dynamically updated on state changes.

In this tutorial, you will have hands-on knowledge on how to create custom Next.js Favicons that dynamically update with React.
The tutorial will enable you to understand how to use this knowledge on your website to make it more modern and attractive.

#### KeyTakeaways

By the end, the following will be discussed and learned:

- What are Favicons and their importance to websites
- Adding custom Next.js Favicons
- Make the custom Favicons update dynamically by automatic or manual trigger with React

#### Pre-requisites

For the article, the following are required for easy article follow-up:

- A good JavaScript IDE or text editor set up on the machine
- A stable internet application
- Next.js development environment already setup
- Next.js development skills

#### Article quality

The article will be a span of broad content. It will begin with the basics before delving into more detailed but in-depth content on the useful functions to make the Favicons dynamically update in Next.js applications.
It will cover the importance of dynamically updating Favicons on modern websites.
This makes the user move from a beginner to expert level quickly.

#### References

- Next.js [documentation](https://nextjs.org/docs)

#### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
There are [several articles](https://www.google.com/search?client=firefox-b-d&q=Next.js+custom+Favicons+that+dynamically+update+with+React) that already cover this topic. How is yours unique?

**Comment by RisoriTofa** [comment]
They have employed only the use of manual triggers, in mine, there is the employment of automatic triggers by use of functions to mimic real website notifications. Besides, theirs are outdated. I am using the new features of Next.js 12 for the article so that it may be up to date with the latest trends in technology. The article will also be short so that it may not be tiresome to the readers.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
