### ISSUE TITLE
Everything Developers Need To Know About Figma

### ISSUE THREAD

**Issue by duncandegwa** [section-engineering-education/engineering-education#5386]
#### Proposed title of article
Everything Developers Need To Know About Figma

#### Proposed article introduction
Figma is a design tool that is rapidly gaining popularity and becoming more common in companies around the world. Unlike most design software, Figma is free and browser-based so developers can easily access the full design files making the developer handoff process significantly smoother. 
Since many developers don’t have a lot of experience playing around in design tools we’ll cover all the basics developers need to know about so you can confidently navigate around Figma and extract any information you might need when working with the designs sent to you by a designer.

#### Key takeaways 

- Navigating Figma
- Project Styles 
- Selecting Elements
- User Flow And Animations
- Exporting Assets

#### Article quality
This article teaches developers who have nothing but a basic understanding of design tools everything they need to know to work with Figma.

**Comment by WanjaMIKE** [comment]
We focus more on program-centric topics rather than design. Please feel free to choose another topic. Thanks

**Comment by duncandegwa** [comment]
Thought programming includes design since we must build user interfaces
