### ISSUE TITLE
[Machine Learning] Hands-on Matplotlib With Workable Examples

### ISSUE THREAD

**Issue by Kama-144** [section-engineering-education/engineering-education#5390]
#### Proposed title of the article
Hands-on Matplotlib With Workable Examples

#### Proposed article introduction
After you have gotten done with Numpy and Pandas, you may be keen on playing with imagining for static and intelligent visuals in Python. Consequently, Matplotllib can be utilized to convey or to extract visuals of information upon required result so the client can comprehend it better with the two information graphically and in a visual way.

#### Key takeaways 
- By the end of this article learners will be able to:
1.  Line Plot using Matplotib
2.  Histogram using Matplotib
3.  Scatter Plot using Matplotib
4.  BarPlot using Matplotib
5.  SinWave using Matplotib
6.  3D Surface Plot using Matplotib

#### Article quality
Based on what is almost similar in other blogs, this article will be simple and easy to understand. The content in some articles online are a bit hindrance to those beginners who maybe want to jump on Matplotlib and this article will be in a position to address these issues and ensure it adds value to our abled community
#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in-depth topic or extend your article in some way to provide unique value.
