### ISSUE TITLE
Working with Flutterwave API

### ISSUE THREAD

**Issue by ngalasteven427** [section-engineering-education/engineering-education#5391]
### Topic Suggestion
Getting started with working with Flutterwave API

#### Proposed title of article
Working with Flutterwave API

#### Proposed article introduction
 [API]
Flutterwave offers several  services that enable you to send and receive money all over the world. On this article, we'll go over the fundamentals of the Flutterwave API services as well as  how one can integrate  the API in their projects.
The API offers variety of payments method options including  Mpesa payments, Card payments, Account payments ,Ussd payments etc.

#### Key takeaways 
1.What Flutterwave offers
2.What Flutterwave API entails
3.How to integrate the Flutterwave API in real world projects

#### Article quality
Besides other articles explaining different payment APIs such as Paypal API, Daraja Safaricom API , this article will focus on The flutterwave API and clearly demonstrate on how to integrate it in real world projects
#### References
Flutterwave documentation

**Comment by louisefindlay23** [comment]
Approved but please ensure your article is unique from the developer docs.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
