### ISSUE TITLE
C Command Line Arguments

### ISSUE THREAD

**Issue by Tonybishop11** [section-engineering-education/engineering-education#5395]
#### Proposed title of article
[Languages] C Command Line Arguments

#### Proposed article introduction
The arguments passed to the operating system's command prompt during processing are known as command line arguments. We used main() without parameters previously. The main() method handles the command line inputs. The user is required to define the main() method with two arguments in order to pass command line parameters . The number of command line arguments is specified by the first argument, and the list of command line arguments is the second argument.

#### Key takeaways 
By the end of this tutorial, the reader will be in a position to understand in details:
- What is entailed in Command Line Arguments in C
- Command Line Arguments functionality in C
- Command-Line Arguments illustrations in C
- Relevance of Command-Line Arguments in C

#### Article quality
We will purpose in detail on every aspect of this topic. I Am purposing to manoeuvre throughout this topic to ensure easy understanding of the concept to the reader. This article will be prepared using basic foundational language that will be beginner-friendly to ensure easy comprehension by the reader. I will ensure that examples and illustrations are laid down where need be, including properties of Command-Line arguments in C to ensure practicability to the reader.

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
