### ISSUE TITLE
Build Vue Application with Django REST API and Axios

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#5401]
#### Proposed title of article
Build Vue Application with Django REST API  and Axios

#### Proposed article introduction
When building web applications one may want to consume and display data from an API. This also applies to Vue.js applications where Django, a backend framework based on python is purely used as an API using a package called Django rest framework to build web applications together with Axios, a HTTP client library for fetching and displaying data.
To understand this, we will cover as much in this article to equip the reader with the understanding of how to combine Django and Vue.js to build web applications using Django rest framework together with Axios . The reader will understand how to configure rest API, Axios and their integration in building Vue web applications.
#### Key takeaways 
The reader will be able to:
- Understand how to build Django rest API using Django REST Framework.
- How to combine Django and Vue.js.
- How to build Vue application using Axios.

#### Article quality
This article will be of high quality different from the others, as it not only shows how to combine Django with Vue.js but also its implementation on how one can build Vue web applications using Django rest api together with Axios.

#### References
N/A

### Conclusion
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
There are articles that already exist about these topics. Can you alter your article to become a tutorial about how to build a tye of web app using these technologies that hasn't been covered elsewhere?

**Comment by dentonya** [comment]
> There are articles that already exist about these topics. Can you alter your article to become a tutorial about how to build a tye of web app using these technologies that hasn't been covered elsewhere?

@louisefindlay23 done with the changes

**Comment by louisefindlay23** [comment]
So can you tell me what type of web app your tutorial will cover?

**Comment by dentonya** [comment]
> So can you tell me what type of web app your tutorial will cover?

@louisefindlay23 the tutorial will cover a Tod application just to show how we can implement the three technologies Django API, Axios and Vue.js
