### ISSUE TITLE
functional programming in Javascript and functional programming in LINQ in C#

### ISSUE THREAD

**Issue by Graceshee** [section-engineering-education/engineering-education#5405]
#### Proposed title of article
functional programming in Java script and functional programming in LINQ in C#

#### Proposed article introduction

As a C# developer, I've used JS on the front end for a few years now and have gotten quite proficient at it .The methods I'm looking to compare between JS and C# are related to arrays and collections (using LINQ). For JS or C#, I want to show you how to select the appropriate method based on your needs.

#### Key takeaways

1.What is the difference between filter (js) and Where (LINQ).
2.orderBy (js) versus sort (js) (LINQ)
3.C# (without LINQ) vs. js (forEach)
4.Reduction (js) versus aggregation (LINQ)
5.the difference between concact (js) vs. Concact (LINQ) 

#### Article quality

My approach to this article is unique because it is broken down into bits and the explanation is straight to the main points. This article will be in depth, explaining all aspects of this concept. To ensure it is beginner-friendly, I will employ easy use of language to enhance understanding.

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
