### ISSUE TITLE
Functions in socket programming

### ISSUE THREAD

**Issue by Emmanuelsultan** [section-engineering-education/engineering-education#5406]
### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Functions in socket programming

#### Proposed article introduction
In this article we are going to describe socket programming function and some of the programs dealing with the functions in socket programming.

#### Key takeaways 
By the end of this tutorial the learner will be able to:
- understand function in Socket programming.
- will be write codes dealing with functions in socket programming

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A.

**Comment by WanjaMIKE** [comment]
Which programming language will you use?

**Comment by louisefindlay23** [comment]
Please fill in the article quality and writing sample sections.

**Comment by Emmanuelsultan** [comment]
Java language

**Comment by louisefindlay23** [comment]
You still need to fill in the article quality and writing sample sections so we can review your article. Let me know when you are ready to do this and I will reopen your topic suggestion.
