### ISSUE TITLE
[LANGUAGES] Using the Android NDK(C++) to create a simple traffic jam path recommender app

### ISSUE THREAD

**Issue by Agusioma** [section-engineering-education/engineering-education#5408]
### Topic Suggestion
Using the Android NDK(C++) to create a simple traffic jam path recommender app

### Writing sample(s): 
My samples are found [here](https://www.section.io/engineering-education/authors/terrence-aluda/)

#### Proposed title of the article
Using the Android NDK(C++) to create a simple traffic jam path recommender app

#### Proposed article introduction
Many times, one may be caught in traffic jams during rush hours. It may be in the morning when late for that office meeting, or in the evening when you have an urge to see your pet😃. Due to this, the person may want to know the shortest route to navigate through the jam, right? 
We are going to see how to create an app to do that using Dijkstra's Shortest Path First algorithm. Think of the one found in Google Maps but a very simpler version.

To achieve high speed in updating the dynamic traffic changes, we will need to be as native as much as we can. That's why we are using the Native Development Kit. Note that such a feature may be integrated into a car dashboard too(no execution latencies will be needed here😃).

We will be using C++ for the path computation and then feed and display the results to the user using Kotlin.

#### Key takeaways 
The user will learn about:
- Setting up the Android NDK
- The Java Native Interface(JNI)
- Using C++ in developing android native code
- The Dijkstra's Shortest Path First(DSPF) Algorithm

#### Article quality
- It talks about the DSPF algorithm, its uses, and how to tailor it to compute the shortest route in a traffic jam. 
- It not only talks about an introduction to the Android NDK but also creating a simple app out of it.

#### References
- [ProAndroidDev](https://proandroiddev.com/android-ndk-interaction-of-kotlin-and-c-c-5e19e35bac74)

- [MindOrks](https://blog.mindorks.com/getting-started-with-android-ndk-android-tutorial)

- [Official NDK documentation](https://developer.android.com/ndk)

**Comment by WanjaMIKE** [comment]
Closed #5408 via #5544
