### ISSUE TITLE
[Android]Understanding and Solving the Problem of Multidex in Android

### ISSUE THREAD

**Issue by omondi-alex** [section-engineering-education/engineering-education#5412]
### Topic Suggestion
[Android]Understanding and Solving the Problem of Multidex in Android

#### Proposed title of article
Understanding and Solving the Problem of Multidex in Android

#### Proposed article introduction
When your app and the libraries it references exceed 65,536 methods, you encounter a build error that indicates your app has reached the limit of the Android build architecture. Both these error conditions display a common number: 65536. This number represents the total number of references that can be invoked by the code within a single Dalvik Executable (DEX) bytecode file.

Android app (APK) files contain executable bytecode files in the form of Dalvik Executable (DEX) files, which contain the compiled code used to run your app. The Dalvik Executable specification limits the total number of methods that can be referenced within a single DEX file to 65,536—including Android framework methods, library methods, and methods in your own code.

#### Key takeaways 
- What is Multidex.
- How to avoid Multidex.
- How to solve Multidex error when you encounter it.
- How to configure your app for multidex.
- Limitations of Multidex.

#### Article quality
The article is will consider android beginners since it is going to be beginner friendly. 

#### References
- https://developer.android.com/studio/build/multidex#mdex-pre-l

**Comment by louisefindlay23** [comment]
Are there any unique aspects of your article except for its beginner friendliness?

**Comment by omondi-alex** [comment]
@louisefindlay23, the article is not only going to be beginner friendly. After careful research I realized that other sites does not cover handling Multidex in Kotlin. The article is going to be in Kotlin which is the widely used android programming language.
