### ISSUE TITLE
[LANGUAGES]Implementing an auto-logout feature for Android(Kotlin)

### ISSUE THREAD

**Issue by vinstex** [section-engineering-education/engineering-education#5413]
### Topic Suggestion
[LANGUAGES]Implementing an auto-logout feature for Android(Kotlin)

### Writing sample(s): 
My latest article is found [here](https://www.section.io/engineering-education/javascript-math-animations/)

#### Proposed title of article
Implementing an auto-logout feature for Android(Kotlin)

#### Proposed article introduction
Handling sensitive data in an app may require some checks to see if the user is still active and decide whether to keep him logged in or not. We will use a very simple approach to do that - using gesture detectors and the Handler class to set timeouts. The same logic is being used [here](https://www.section.io/engineering-education/autologout-js/), but we will do that for Android.

#### Key takeaways 
The user will learn about:
- Using the Handler class to create an auto-logout feature(though the latter will not be that necessary).
- Using Kotlin to implement this.
- Using gesture detectors to implement this.

#### Article quality
We will do that in a very simple manner without invoking too many classes like in other blogs. We will additionally use [gesture detectors](https://developer.android.com/training/gestures/detector) to do the timer resets.

#### References
N/A

**Comment by louisefindlay23** [comment]
Are there any unique aspects of your article except for its simplicity?

**Comment by vinstex** [comment]
@louisefindlay23, I've updated the issue description to additionally use. We may also use gesture detectors to do the timer resets which the blogs haven't covered. Note that I've also removed the Java language and used only Kotlin since I have to do more research on the gesture detectors.
