### ISSUE TITLE
Working with C Inline Function

### ISSUE THREAD

**Issue by BoldTony1** [section-engineering-education/engineering-education#5414]
#### Proposed title of article
[Languages] Working with C Inline Function

#### Proposed article introduction
In C programming, inline functions play a significant role in both small and large programs. It saves a significant amount of time and memory. Using the `inline` keyword is the only way to define an inline function in Programming language. A function can be defined inline and then used as many times as necessary in a code, which will speed up the execution time of the code by a significant amount. Defining it is easy, and it may be used again and over again.

#### Key takeaways 
- What is meant with inline function in C and what it entails
- Why choose Inline Function in C language
- How to work with Inline Function in C
- Advantages and disadvantages of Inline Function in C
- Inline function within classes

#### Article quality
My outlook to this article is to ensure that it is unique by breaking down its aspects into bits that are explained straight to the point. I am looking forward to making it more beginner-friendly by using basic foundational language that is easy and simple to understand. I will ensure proper coverage of this article exploring all the aspects of this concept and in an in-depth manner. I will ensure proper demonstration of this concept and with practicable examples where relevant.  The learner will also be entitled to how to handle Inline function for integers in addition as well as subtraction.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @BoldTony1 

Thank you for your suggestion and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
