### ISSUE TITLE
 Factory Design Patterns And Implementation

### ISSUE THREAD

**Issue by Simsamrosh** [section-engineering-education/engineering-education#5415]
#### Proposed title of article
 Factory Design Patterns And Implementation.

#### Proposed article introduction
The factory method pattern is a creational pattern that uses factory methods to solve the problem of creating objects without having to specify the exact class of the object to be created. It simply states that you should define an interface or abstract class for creating an object and then let the subclasses decide which class to instantiate.
In this article, I'll walk the reader through the entire notion of factory design patterns, then take him or her through numerous classes on the subject and involve him or her in multiple real-world examples and applications.
#### Key takeaways 
Introduction to factory design patterns .
Classes of the above mentioned subject and how to apply them.
Implementation in JDK
Applicable example and implementation

#### Article quality
In this article, I'll use simple but technical terminology that's easy to comprehend for beginners.
To demonstrate the applicability of the subject matter, I will use the popular example of paying an electric bill.
#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
