### ISSUE TITLE
Build A Userlist Application using Next js

### ISSUE THREAD

**Issue by oyedeletemitope** [section-engineering-education/engineering-education#5416]
#### Proposed title of article
Build A Userlist Application using Next js

#### Proposed article introduction
[Web development] in this tutorial I'll be writing on how to build a Userlist Application using Next js.

#### Key takeaways 

Users will be able to 
- create next app and layout
- make use of userouter to add a class
-  make use of next js link
- make use of getStaticProps to get user data
#### Article quality
The article is meant to add to a list of projects for readers who are interested in learning Next js. It will help make them farmilar with steps and methods in Next.

### Conclusion
This article will be a great read to users both at beginner and professional level.

**Comment by WanjaMIKE** [comment]
Unfortunately, introductory aspects of Next.js are already covered in numerous articles. Feel free to suggest another area
