### ISSUE TITLE
[Languages] Learning Typescript by implementing its features in a simple React app.

### ISSUE THREAD

**Issue by deverten** [section-engineering-education/engineering-education#5417]
#### Introduction
React is a dynamically typed Javascript library used for building user interfaces. This means the code has to be run before certain behaviors and errors can be noticed. Typescript on the other hand was built on top of Javascript with a little extra – in that it is statically typed, meaning code behaviors and errors are detected before the code is run. Contrasting between the Static-typed and Dynamically-typed languages we discover Typescript (static typed) enables us to save time while building software. 

Programmers come across numerous errors with the most common being type errors. Typescript solves this challenge and more, hence the name “Type-script” (type-checker). It helps you understand the behavior of your code giving you some control during development. Typescript can be used for editing code, as well as providing code completion when we type in the code editor, it pops up suggestions on which property of a variable we may want to use. Typescript helps in catching typo errors, uncalled functions, and detecting basic logic errors. 

While this article requires you to have some knowledge of React, little to no knowledge of typescript is required. We will learn and implement the basics of typescript by building a simple app that collects data using forms and displays data of gym members by updating states using react and typescript. 

#### Key takeaways 
At the end of the article the reader should:
-	Know how typing works when dealing with state in React
-	Be able to define complicated states  using Interface
-	Know how typing works with props
-	Be able to define Functional Components in React
-	Be able to implement typing in functions
-	Understand how to handle events in typescript 
-	Be able to interpret suggestions thrown in the code editor while building with typescript.

#### Article quality
This article aims to get beginners up to speed with typescript by building a simple project which covers important typescript concepts in detail. By learning the basics and building along, the knowledge sticks.

#### References
-	https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html
-	https://www.youtube.com/watch?v=bjnW2NLAofI
-	https://www.youtube.com/watch?v=I9jfsIRnySs

**Comment by WanjaMIKE** [comment]
Based on this PR - https://github.com/section-engineering-education/engineering-education/issues/3262 and attached comments in it, this topic appears a bit over saturated. We focus more on unique projects. Thanks
