### ISSUE TITLE
[Android] Creating a Flipped Box Card in Android Jetpack Compose

### ISSUE THREAD

**Issue by osirevaline** [section-engineering-education/engineering-education#5420]
#### Proposed article introduction
Just like how a paper looks when it is flipped on one side, as a developer you may like to create a card that is flipped on one side. This card may be used to display some notes or items in your app.

When using XML to design layouts, this is nearly impossible. With Jetpack Compose, there is no direct Modifier that can be used to achieve this. This is when Canvas in Compose comes in handy.

In this tutorial, we will go through some Canvas concepts in Compose, then we will jump directly to create a Flipped Card. 

#### Key takeaways 
- A quick recap of some advanced concepts of Canvas in Jetpack Compose
- Clipping a shape - Rectangle
- Cutting edges in a shape.
- Creating a Flipped Card Composable

#### Article quality
This article will be very helpful to those developers who are not yet into Compose and would like to use some features of Canvas to customize the default Box Composable. It will be beginner friendly and concise.

#### References
- Canvas for Jetpack Compose

**Comment by LinusMuema** [comment]
good topic @osirevaline  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial. I would suggest you make a deep dive into canvas and all its capabilities to make your article stand out as there are articles using `Card` composable.
