### ISSUE TITLE
What is DataOps and Why Data Engineers need it

### ISSUE THREAD

**Issue by essy258** [section-engineering-education/engineering-education#5422]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
What is DataOps and Why Data Engineers need it

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
What is DataOps and Why Data Engineers need it

Use keyword research to improve your article's SEO.

#### Proposed article introduction
DataOps (Data Operations) is the practice of data analysts, data scientists, developers, and operations participating together in the entire lifecycle from data collection to design, development, and production support. It brings together DevOps teams with data engineers and data scientists to provide the tools, processes, and organizational structures to support the data-focused enterprise.
The purpose of DataOps in the enterprise is to increase analytic velocity and create analytical outcomes for data consumers. 

DataOps aims to streamline application design, development, and maintenance based on data and data analysis. The goal is to improve the management of data and products created and align these improvements with the business's goals.

This article will first look at the challenges for which we need DataOps, and dig deeper on what is DataOps and why data engineers need it.

#### Key takeaways 
1. Overview of DataOps
2. Who is a DataOps engineer
3. DevOps vs DataOps
4. DataOps best practices
5. Implementing DataOps
6. Why data engineers need DataOps

#### Article quality
This is a more detailed article about DataOps as the demand for data products and access to data assets is growing exponentially.  It will look at the benefits of DataOps, the steps to implementing a successful DataOps practice, and give insights into why data engineers need DataOps. This article will be understandable at a beginner level and provide unique and quality content.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
good topic @essy258  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.

Also, in future suggestions please remove the Pre-submission advice as stipulated in the conclusion. This will allow the CMs get your content easily.
