### ISSUE TITLE
[Android] Getting Started With Android Application Components in Kotlin

### ISSUE THREAD

**Issue by Rose-Meghan** [section-engineering-education/engineering-education#5424]
### Topic Suggestion
[Android] Getting Started With Android Application Components in Kotlin

#### Proposed title of article
 Getting Started With Android Application Components in Kotlin

#### Proposed article introduction
Application components are the essential building blocks of an Android application. These components are loosely coupled by the application manifest file AndroidManifest.xml that describes each component of the application and how they interact.

Application components are very essential for building Applications. They work as an entry point for users or system to enter your application. There are four different types of components. Each component has its own purpose and distinct life cycle.

#### Key takeaways 
At the end of this tutorial, the reader will:
- Understand what are Application components.
- Uses of Application components.
- How to work with application components in kotlin.

#### Article quality
This article is going to be one of its kind since all the implementation is going to be in Kotlin. It is also going to follow the recommend Android Architectural design which is MVVM.

#### References
- Android Application Components

- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @Rose-Meghan 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
