### ISSUE TITLE
[Network Security] Understanding DNS | Protect your network from DNS hijacking and DNS poisoning Attacks

### ISSUE THREAD

**Issue by JudyNduati** [section-engineering-education/engineering-education#5425]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
[Network Security] Understanding DNS | Protect your network from DNS hijacking and DNS poisoning Attacks

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Understanding DNS | Protect your network from DNS hijacking and DNS poisoning Attacks

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Domain Name System (DNS) is a system that maps a Web URL to an IP address of the server where the request has to go. Internet communication takes place using an IP address. This article aims to dive deeper into DNS and a few security issues associated with it.

DNS hijacking is a common attack methodology deployed by hackers. In a DNS hijack, the attacker replaces the genuine DNS server with the fake server. That means that all the URL requests will go to the fake server, and the hacker can send you the wrong IP addresses and route you to different web pages other than the original ones. You can be redirected to pages with malware or fake login pages to help hackers steal your credentials. 

DNS server configuration is done in your router. Hackers mostly carry out DNS hijacking by breaking into your router and replacing the DNS configuration with their fake server. The best way to prevent a DNS hijacking attack is to configure the DNS server details in your computer itself rather than your router. When it's configured in your computer, your computer asks the router to use a particular DNS server irrespective of whatever the server's configuration is.

#### Key takeaways 
1. What is a DNS and a DNS Server
2. How the DNS works
3. DNS hijacking
4. DNS poisoning
5. Protect your network from DNS hijacking and DNS poisoning

#### Article quality
This is an exciting and interactive topic as readers will learn how to prevent DNS hijacking and DNS poisoning attacks by configuring DNS manually on Windows.

#### References
https://en.wikipedia.org/wiki/DNS_spoofing
https://developers.google.com/speed/public-dns/docs/using

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @JudyNduati 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
