### ISSUE TITLE
[Android] Implementing Custom Searching and Filtering in Firebase Database in Android with Kotlin

### ISSUE THREAD

**Issue by brandy-kay** [section-engineering-education/engineering-education#5428]
#### Proposed article introduction
The Firebase Realtime Database is a NoSQL database from which we can store and sync the data between our users in real-time. It is a big JSON object which the developers can manage in real-time..By using a single API, the Firebase database provides the application with the current value of the data and updates to that data. Real-time syncing makes it easy for our users to access their data from any device, be it web or mobile.

In relational database such as MySQL ,SQLite it is relatively easy to filter and search data with different attributes using query commands. In comparison to Firebase Realtime database which is non-structured in nature, filtering and searching is quite complicated even when making simple data queries

In this tutorial we'll get to explore several ways of searching and filtering data in Firebase real-time database

#### Key takeaways 
- How Firebase Realtime database structures its data
- Different ways of searching and filtering data in Firebase Realtime database 
- How to filter data by passing search parameters
- Understanding how to filter data with unknown child id
-  Implementing search and filtering methods in Android

#### Article quality
Most developers don't find the right blogs and articles that explains how to search and filter Firebase Realtime database data.This article will be short, concise,  beginner friendly and explain the ways to implement custom search and filter  data in Realtime  database Firebase. 

#### References
N/A

**Comment by LinusMuema** [comment]
good topic @brandy-kay  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your {article type} very beneficial.

Most articles I have seen make use of Java capitalise on the kotlin aspect and provide more original content as the article can be closed during the plagiarism check level.
