### ISSUE TITLE
Creating  Custom Page Preloader Using Vue.js

### ISSUE THREAD

**Issue by dentex22** [section-engineering-education/engineering-education#5430]
#### Proposed title of article
Creating Custom Page Preloader Using Vue.js

#### Proposed article introduction
Loading is very crucial for our website success. It keeps users engaged for those milliseconds to wait for a while before they can actually see all the content. Sometimes users may even think that the site is down, adding a well-designed pre-loader fills this gap and shows the user a progress indicator during the page load.
In this article, we will cover as much as possible to help the reader understand how one can create custom page preloaders (what users see on websites before the main content of the web page is loaded) using Vue.js. The reader will also understand its design, how to add and hide the preloader once the web page loads.

#### Key takeaways 
The reader will understand:
- The importance of page preloaders.
- How to design and create preloaders using Vue.js
- How to add preloaders to web pages after creation.

#### Article quality
This article not only will it equip the reader with the knowledge of preloaders and how they are applied in websites but also the implementation using Vue.js in web page creation.

#### References
N/A.

### Conclusion
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @dentex22 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
