### ISSUE TITLE
Introduction to Ensemble Methods in Machine Learning

### ISSUE THREAD

**Issue by EssyH** [section-engineering-education/engineering-education#5431]
### Topic Suggestion
Introduction to Ensemble Methods in Machine Learning

#### Proposed title of article
Introduction to Ensemble Methods in Machine Learning
#### Proposed article introduction
In Machine Learning, the ensemble method is defined as a multimodal system in which different classifiers and techniques are strategically combined into a predictive model (grouped as Sequential Model, Parallel Model, Homogeneous and Heterogeneous methods etc.) 
The ensemble method also aids in reducing variance in predicted data, minimizing bias in the predictive model, and accurately classifying and predicting statistics from complex problems.

#### Key takeaways 
Types of Ensemble Methods in Machine Learning
Technical Classification of Ensemble Methods
Heterogeneous Ensemble
 Homogeneous Ensemble

#### Article quality
Since heterogeneous Ensemble and homogeneous Ensemble are the major types of Ensemble methods, in my article I will give the reader a clear understanding about tem and even go a step further to elaborate about technical classification of Ensemble Methods. I'll make sure to use simple grammar hence my article will be beginner friendly.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Please fill in the article quality section.

**Comment by EssyH** [comment]
Hello @louisefindlay23 the requested update is in line

**Comment by louisefindlay23** [comment]
Thanks, @EssyH. How is your article different from those that [already exist](https://www.google.com/search?client=firefox-b-d&q=Introduction+to+Ensemble+Methods+in+Machine+Learning)?

**Comment by EssyH** [comment]
Unlike the other articles, my will give more about heterogeneous Ensemble and homogeneous Ensemble which are the major types of Ensemble methods, I'll also use simple grammar for beginners to easily understand.
