### ISSUE TITLE
[Security] Overview of Rootkits

### ISSUE THREAD

**Issue by kvardhan10** [section-engineering-education/engineering-education#5432]
#### Proposed title of article
Overview of Rootkits

#### Proposed article introduction
Security and privacy have nearly become myths in this digital age of computers and technology. As much as data has become crucial, its protection has become even more valuable. Today, securing our data and information is our top priority. There are numerous ways for someone to get unauthorized access to our systems and steal the data. Rootkits are one such method.
 
Rootkits are malicious software that targets the operating system, firmware, or various system applications in order to gain root privileges. They have the ability to go undetected by the system and deploy various malware that allows them to steal data.

#### Key takeaways 
- Understand what are rootkits
- What makes them vulnerable
- How they affect our system
- How they can be used to improve existing systems
- Different types of rootkits

#### Article quality
This article provides a quick overview of rootkits and gets the reader started. It is intended for beginners and anyone interested in learning more about one of the many topics in cybersecurity. The types of rootkits, how they function, how to detect and avoid them, and so on should be able to help them comprehend the type of threat that exists that one might face in the future.

#### References
https://en.wikipedia.org/wiki/Rootkit
https://www.kaspersky.com/resource-center/definitions/what-is-rootkit

**Comment by louisefindlay23** [comment]
Approved but be sure to include plenty of detail to make your article more substantial over existing ones.

**Comment by WanjaMIKE** [comment]
Closed #5432 via #5920
