### ISSUE TITLE
Morphological operations in image processing using OpenCV python.

### ISSUE THREAD

**Issue by samtecinnovator** [section-engineering-education/engineering-education#5435]
### Proposed title of the article
Morphological operations in image processing using OpenCV python.

### Proposed article introduction
In this tutorial, we will learn about morphological operations. 
What are morphological operations? -These are image processing transformations applied to either grayscale or binary images. These operations require a structuring element, which is used to define the neighborhood of pixels the operation is applied to. how to use morphological operations to increase the size of objects in images as well as decrease them.
We also discuss on  the most important morphological operations that you’ll use inside your own applications:

### Key takeaways
The reader of this article will understand:

The concept of smoothing technique.
The concept of structuring element.
Commonly used operation(s) i.e erosion,dilation 
Edge detection using Canny filter.
How to convert the color image into grayscale shades.
Performing opening and closing operations
Concept of the morphological gradient.
Know the difference between tophat/whitehat and black hat operations. 

### Article quality
This article will not only equip the reader with the knowledge of morphological techniques but also assist him/her with applications of these operations using proper code samples and generating their output.

### References
N/A.

**Comment by louisefindlay23** [comment]
There are many [articles](https://www.google.com/search?client=firefox-b-d&q=Morphological+operations+in+image+processing+using+OpenCV+python) that already exist on this topic such as [this one](https://www.pyimagesearch.com/2021/04/28/opencv-morphological-operations/). What makes yours unique?

**Comment by samtecinnovator** [comment]
it will be more of practical approach to real-world problems
