### ISSUE TITLE
[Android] Comparing the New Database Framework  (SQL Delight) to Room Database in Android

### ISSUE THREAD

**Issue by sheecodes** [section-engineering-education/engineering-education#5440]
#### Proposed article introduction
In the world of mobile development, databases are often used for local data storage on client devices. One of the options for working with databases for Android projects is the Room library. The Room persistence library provides an abstraction layer over SQLite to allow fluent database access while harnessing the full power of SQLite.

On the other hand we have SQL Delight which is a cross platform SQL library that generates type-safe Kotlin APIs from SQL statements for various relational databases. SQL Delight also provides a multiplatform implementation of the SQLite driver.

It verifies your schema, statements, and migrations at compile-time and provides IDE features like autocomplete and refactoring which make writing and maintaining SQL simple.

In this article, we are going to dive into the strength and weakness of SQL Delight, also we will compare its performance, syntax and many more with the Room database.

#### Key takeaways 
- Understand what SQL Delight is and how it works.
- Features of SQL Delight database.
- Differences between SQL Delight with Room Database.
- Advantages and disadvantages of SQL Delight.
- Understand if SQL Delight is the right choice for multi-table databases with different types of relationships.

#### Article quality
The article will try and bring comparisons of both databases, it will be rich in unique content that will be good for beginner looking the right choice of a database to use in their projects. It will be clear sentences that are concise. Other than the theories, the article will contain some technical parts of implementing the SQL Delight database in Android.

#### References
- SQL Delight Documentation.
- Room Database Documentation.

**Comment by WanjaMIKE** [comment]
Closed #5440 via #5912
