### ISSUE TITLE
[Android] Understand How to Migrate Your Existing Android XML Project to Jetpack Compose

### ISSUE THREAD

**Issue by feswalsalim** [section-engineering-education/engineering-education#5441]
#### Proposed article introduction
If you are a developer and you have a big project that is written in XML, you may  be in need of migrating that Project to Jetpack Compose which is  Android’s modern toolkit for building native UI. It simplifies and accelerates UI development on Android. Quickly bring your app to life with less code, powerful tools, and intuitive Kotlin APIs. 

In this tutorial, we will go through step by step of migrating an existing project into fully being a compose project. Also we will look into ways of using XML views in Jetpack compose.

#### Key takeaways 
- A detailed guide on how to migrate an XML project to Compose, step by step.
- Understanding How to Migrate a single Activity or a Fragment.
- Understanding How to Include Views in Compose that don't yet have a composable e.g (Google Maps)

#### Article quality
This article takes the reader beyond what is provided in the official documentation and teaches the reader the way of migrating an existing project to compose. Also, the article tries and explains how to use XML Views in Compose in components that do not have composables yet e.g Google Maps. The same content isn't fully explained well on other blog sites.

#### References
N/A

**Comment by WanjaMIKE** [comment]
https://www.youtube.com/watch?v=Pur_0KroFR8

**Comment by feswalsalim** [comment]
> https://www.youtube.com/watch?v=Pur_0KroFR8

Hello @WanjaMIKE thank you pointing out
I agree that the video also tries to explain what I am planning to write, but some people prefer understanding something that is written rather than watching a video and forwarding it to the part that he/she wants.
An article is easy to skim and scan to the part that interests you. 

Thank you in advance.

**Comment by LinusMuema** [comment]
Also @WanjaMIKE 
Google has a codelab on the same which has a lot of content and well explained steps so I don't think your article would provide a lot of original content.
