### ISSUE TITLE
[Artificial Intelligence] What makes automation smart?

### ISSUE THREAD

**Issue by BridgetMwikali** [section-engineering-education/engineering-education#5444]
#### Proposed title of article
What makes automation smart? 

#### Proposed article introduction
Today, business leaders are using more robotic process automation (RPA), which is software that’s programmed for basic and repetitive tasks. Intelligent automation (IA) goes a step further by combining RPA with artificial intelligence for greater automation of business processes.

Today Intelligent automation is hailed as RPA’s worthy successor, leveraging machine learning, NLP, deep learning, computer vision technologies to reduce or eliminate manual efforts. Intelligent Automation interacts and executes processes a human might have done in the past but in a more efficient, and more effective manner.

IA incorporates algorithms capable of tasks such as handling exceptions, orchestrating decisions or even looping in chatbots for conversational messaging.
#### Key takeaways 
1. What is Intelligent Automation?
2. Core technologies that make automation smart
• Cognitive Agents
• Natural-Language Generation
• Machine Learning/Advanced Analytics
• Smart Workflow
• Robotic Process Automation

3. The value of Intelligent Automation
4. The future of intelligence automation

#### Article quality
Intelligent automation (IA) is a fairly new technology that is slowly replacing robotic process automation (RPA). A few of the already published articles are not discussing IA in-depth or its connection with artificial intelligence. This article discusses IA and does deeper to explain the AI technologies that apply to IA.
#### References
N/A

**Comment by louisefindlay23** [comment]
Please fill in the article quality section

**Comment by BridgetMwikali** [comment]
Intelligent automation (IA) is a fairly new technology that is slowly replacing robotic process automation (RPA). A few of the already published articles are not discussing IA in-depth or its connection with artificial intelligence. This article discusses IA and does deeper to explain the AI technologies that apply to IA. 
@louisefindlay23
