### ISSUE TITLE
Abstract class vs Interface distinction and their implementation in C#

### ISSUE THREAD

**Issue by gracy20** [section-engineering-education/engineering-education#5445]
#### Proposed title of article
[Languages] Abstract class vs Interface distinction and their implementation in C#

#### Proposed article introduction
Unnecessary details can be hidden using Abstraction in C#. There will be less emphasis on how things work and more on what they do. It's a popular choice for large, intricate implementations. This is accomplished through the use of abstract classes and interfaces in C#. We can create the functionality required by a derived class in an abstract class. Functionality or functionalities can be defined, but the interface cannot be implemented. As the name suggests, this is a subclass derived from an interface.

#### Key takeaways 
By the end of this article the learner will be able to understand:
- What are abstract classes and interface in C#
- The distinguishing feature or factors between an abstract class and interface in C#
- How to work with the abstract class as well as an interface in C#
- The advantages and disadvantages while working with abstract classes as well as an interface in C#

#### Article quality
This article will be more of differentiating between abstract classes and interface in C#. I aim at using a well and elaborate approach and in an in-depth manner while working with these concepts. The article will be more interesting and I will provide relevant examples and with an easy simple but understandable language more friendly to beginners. I will also provide detailed head-to-head comparisons with key differences between these concepts.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @gracy20 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
