### ISSUE TITLE
How to use Abstract Classes and Inheritance in Disbursing University Staffs Salaries Using OOP in Java

### ISSUE THREAD

**Issue by kingsleynwafor54** [section-engineering-education/engineering-education#5448]
####  Introduction
At the point when we think about a class, we accept that programs will make objects of that sort/type. Sometimes it's valuable to declare classes-called abstract classes for which you won't ever mean to
make objects. 

Since they're utilized uniquely as superclasses in the inheritance hierarchies,  we allude
to them as abstract superclasses. These classes can't be utilized to launch or instantiate an object, because, as we'll before long see, abstract classes are patchy. 

Subclasses are expected to declare the "missing pieces" to turn into "concrete" classes, from which you can instantiate objects. In any case, these subclasses, as well, will be abstract.

#### Key takeaways 
- To enable individuals to distinguish between abstract and concrete classes.
- To enable individuals to know how to declare abstract methods to create abstract classes.
- To enable individuals to be able to use overridden methods to effect polymorphism.

#### Prerequisites
- Basic understanding of Java
- Basic understanding of OOP concept from any programming language
- A computer device

#### Article quality
Here I will reveal the hidden pattern to using abstract classes when to use abstract classes and why you should use an abstract class. You will understand how to implement various forms of the same type of an object using inheritance.  You will also be confident working with concrete and abstract methods.

#### References
Paul Dietel, Harvey Dietel - How to Program in Java

### Conclusion
Abstract classes are majorly used when you think of an object that exists but is not tangible. Such examples of abstract classes(object) are the account, salary payment scheme, and so on.

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appears over saturated based on this search https://github.com/section-engineering-education/engineering-education/issues?q=Inheritance we focus more on unique projects. Feel free to suggest another topic. Thanks

**Comment by kingsleynwafor54** [comment]
@WanjaMIKE  Thank you, sir!

**Comment by kingsleynwafor54** [comment]
@WanjaMIKE  Thanks, sir.  I would love to ping you when I suggest a new topic, should I?
