### ISSUE TITLE
[Android] Implementing SIM Card Based Mobile Authentication using tru.id in android

### ISSUE THREAD

**Issue by robert-muriithi** [section-engineering-education/engineering-education#5451]
#### Introduction
Validating user identity is incredibly important in mobile applications. Most developers have been using SMS-based verification to verify app users. This can result in poor UX such as long waits, failed delivery, and the risk of SIM Swap attacks.
The solution to this problem can be solved by Authentication based on the SIM card, which can confirm the ownership of a mobile phone number by verifying the possession of an active SIM with the same number. It also indicates when the SIM card associated with a phone number was last changed as a signal for SIM swap detection.

SIM card-based authentication improves the user experience by adding cryptographically secure phone verification to an application and safeguarding the user from SIM swap attacks. There will be no more one-time code exchanges, bespoke logic to handle mistyped PINS, or SMS delivery failure retries. The user remains in the app throughout the entire verification process.

#### Key takeaways 
- How to set up tru.ID for use in an android app
- Understanding  SubscriberCheck service offered by tru.id
- How to add SIM Card based Authentication to an android app
- 

#### Article quality
Most common approaches for verification used in social media apps like Whatsapp, Telegram, etc use the old SMS verification procedure to perform verification. My article will help developers in learning this better security and safe way to verify a user's phone number. 

#### References
https://developer.tru.id/

**Comment by louisefindlay23** [comment]
How will your article expand upon existing blog posts from the developer and its docs?

**Comment by robert-muriithi** [comment]
Hello @louisefindlay23 , In my article, I will use mobile number hint where the user will not need to type in his/her phone number. The mobile number(s) currently on the phone will be displayed and the user will only click the number and proceed to verification without typing anything.
Thank you

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
