### ISSUE TITLE
Managing User State in Vue and Firebase Applications

### ISSUE THREAD

**Issue by annemwangi** [section-engineering-education/engineering-education#5452]
Vuex is a state management library for Vue applications. State management in Vue applications is important as it enables any component within the application to directly access and mutate the state as required. We will take a look at how we can use Vuex 4 and the composition API to set up a state management system for authenticating users with firebase v9 auth. With the state management system in place, we will be able to access the logged-in state from any component and take the necessary actions.

Some of the topics that will be covered in this article include:
- Basics of Vuex and the Composition API.
- Setting up Firebase Auth.
- Setting up an auth store.
- Signing up users.
- Logging in users.
- Logging out users.

#### Key takeaways 
- Working with the Composition API and Vuex 4.
- Managing user state in Vue applications.
- Working with Vue and Firebase.

#### Article quality
The article will be beginner-friendly as it will guide the user on how to achieve the above-stated goals from scratch. Also, articles published on the web that cover this topic use the older versions of Vue, Vuex and, Firebase. We will cover this article using the Vue 3.0, Vuex 4, and Firebase v9, which are all the latest versions. The other articles also use the Options API but in this article, we are going to use the composition API.

#### References
N/A

### Templates to use as guides
N/A

**Comment by WanjaMIKE** [comment]
Closed #5452 via #6282
