### ISSUE TITLE
Introduction to Hibernate

### ISSUE THREAD

**Issue by morwabe1234** [section-engineering-education/engineering-education#5453]
Introduction to Hibernate

Proposed article introduction
Hibernate is a Java framework that makes it easier to create Java applications that interface with databases. Hibernate also allows you to query and retrieve data.
It creates SQL calls, freeing the developer from having to manually handle and convert the query results. In this article, we are going to at an overview of hibernate, the architecture of hibernate, installation process, advantages and disadvantages of hibernate and a hibernate example.

Key takeaways
What is hibernate?
The architecture of Hibernate.
installation process.
Advantages and disadvantages of hibernate.
Hibernate example

Article quality
This article is unique in that covers tghis topic in-depth with additional information about hibernatew in Java.

References
N/A

**Comment by LinusMuema** [comment]
Hi @morwabe1234 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
