### ISSUE TITLE
Working with method hiding in C#

### ISSUE THREAD

**Issue by Ushter21** [section-engineering-education/engineering-education#5454]
#### Proposed title of article
[Languages] Working with method hiding in C#

#### Proposed article introduction
In C#, polymorphism and method overriding are already well-known. Method Hiding is a feature in C# that allows you to conceal the base class's methods from the derived class. Method Shadowing is another name for it. A base class's methods can be hidden using the new keyword in the derived class's implementation. In other words, you can use the new keyword to redefine a base class method in a derived class while employing method hiding.

#### Key takeaways 
By the end of this article, the learner will understand:
- What is method hiding and what it entails, as well as the fundamental aspects of this concept
- The rules that govern method hiding
- Reasons to work with method hiding
- How to hide the method of a base class from the derived class.
- How to invoke a hidden method

#### Article quality
I will explain all the concepts related to the topic covering all possible approaches. I will also provide proper examples with precise outputs and comments and add images wherever necessary. This concept will be covered in an in-depth and interesting manner that is beginner-friendly. The learner will appreciate easy and simple use of language enhancing understanding. I will also be covering method hiding vs overriding and overloading. The learner will also be entitled to the various types of shadowing.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @Ushter21 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
