### ISSUE TITLE
Implementation of Nested Classes in Java

### ISSUE THREAD

**Issue by Nicholas-Obare** [section-engineering-education/engineering-education#5455]
Implementation of Nested Classes in Java

Proposed article introduction
Java allows you to write a class within a class.Nested classes are used to arrange classes that belong together, making your code easier to understand and maintain. Nested class has full access to the outer class's members, such as private data members and functions.IN this article we will discuss on nested classes, categories of nested classes,advantages of nested classes and example of programs to implement nested classes.

Key takeaways
What is a nested class?
Categories of nested classes.
The purpose using the nested class
Benefits of using nested classes.
Examples to implement nested classes.

Article quality
This article iS unique as it covers more on nested classes and clearly shows how to implement the nested classes in programs.

References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for the topic suggestion @Nicholas-Obare  , however this is a bit outside of our preferred topic areas. -
This content can be found on the internet via blogs or official documentation.

We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
Please feel free to suggest an alternate topic to explore. 🚀
