### ISSUE TITLE
Working with data structures in Python

### ISSUE THREAD

**Issue by mbuthiajn** [section-engineering-education/engineering-education#5458]
#### Proposed title of article
Working with data structures in Python
#### Proposed article introduction
 
 Data structures are a way of organizing and storing data so that they can be accessed and worked with efficiently. They define the relationship between the data, and the operations that can be performed on the data. There are many various kinds of data structures defined that make it easier for the data scientists and the computer engineers, alike to concentrate on the main picture of solving larger problems rather than getting lost in the details of data description and access.

In this tutorial, you'll learn about the various Python data structures and see how they are implemented:
#### Key takeaways 
1.Abstract data types
2.Primitive data structure-integers,float, boolean and strings
3.Non primitive data structures-arrays,lists,tuples and files
4.Examples to understand and work with each data type.
5.Data type conversion.

#### Article quality
 This article will provide an in-depth knowledge in data structures in Python . Since other blog sites only provide documentation for the data structures, I'll show the reader how to use primitive data non primitive data structures and Implementation using Python programming language. The article will also be written in an easy-to-understand manner to raise awareness of this open-source library among its users. The article will also be entertaining and expressed in a unique manner.
#### References
N/A

**Comment by LinusMuema** [comment]
good topic @mbuthiajn  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.
