### ISSUE TITLE
Getting started with Blog Posts into Facebook Instant Articles

### ISSUE THREAD

**Issue by cathy-254** [section-engineering-education/engineering-education#5459]
### Topic Suggestion
Getting started with Blog Posts for Facebook Instant Articles
#### Proposed article introduction
Facebook Instant Articles is a mobile-optimized format that allows publishers to distribute interactive articles that load quickly on the Facebook app and share their information.
The good thing about these articles is that no plug-ins are required or integrations. All we require is a text editor to work with our HTML source code.
It will be a lively event because we will be interacting with instant generated output from our session and because the majority of people are social media netheads.
#### Key takeaways 
1. Obtaining a Banner Image
2.  Obtaining Metadata.
3. Taking a Copy of the Body Content.
4. Adding the tracker ChartBeat
5. Launch your Instant Article
#### Article quality
This article will help novices who have always wanted to share their business model or any other news with their peers, and in return, generate revenue. I will be pleased to explain the ins and outs of Facebook Instant Articles and how to put them up on your site in this article.
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
This is out of our preferred topics-area. Feel free to suggest another topic to explore. @cathy-254
