### ISSUE TITLE
[Languages] String Data Structure in Python- A Complete Guide

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#5460]
### Topic Suggestion
String Data Structure in Python- A Complete Guide
#### Proposed article introduction
Python has a built-in Data type called a string. Each application programming language has a string data type in order for developers to communicate with the end-users of the application. Instead of making software that communicates with humans, system software programming languages like C focus on interacting with hardware, hence the string data type may be absent.

While working on real-world applications, you'll come to appreciate the importance of Python's string data type. Strings are frequently used as problem statements in interviews and written assessments because they appear simple, but solving problems isn't. Strings will be covered from A to Z in this tutorial.

#### Key takeaways 
- Accessing substrings from a string
- Editing and deleting string in Python
- Operations on string
- String functions in python

#### Article quality
My article goes above and beyond the original documentation by focusing more on the structure of strings. It also has short and easy-to-follow codes that are written in exciting ways that are easy for beginners to understand. We will start by getting some ideas about strings. We'll cover how to use, make and play with strings, as well as how to use string and string functions in Python in great detail.

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @vincentkims49 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
