### ISSUE TITLE
The layers of edge computing

### ISSUE THREAD

**Issue by ruphus-muita** [section-engineering-education/engineering-education#5467]
#### Proposed title of article
The layers of edge computing

Use keyword research to improve your article's SEO.

#### Proposed article introduction

The terms ‘cloud’, ‘fog’and ‘edge’are very common in the world of technology. But many people do not understand what they are and how they are interlinked. This article will be educating the reader on  what these words mean and what they represent in computing.

#### Key takeaways 
1. Whats is fog layer?
2. What is cloud layer?
3. What is edge layer?
4. Summary.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
