### ISSUE TITLE
How to use json_serializable to Serialise Flutter Models

### ISSUE THREAD

**Issue by Jeddy947** [section-engineering-education/engineering-education#5468]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
How to use json_serializable to Serialise Flutter Models

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Serialization is the process in computer science to convert an object into something that can be saved in a database or be sent via a network request. Flutter’s built-in dart:convert package contains methods like json.decode and json.encode, which convert a JSON string to a Map<String, dynamic> and back. 

#### Key takeaways 
1. How to setup a Flutter project
2. Build a simple application to help us manipulate data
3. Using JsonConverter
4. Using json_serializable
5. Serialising/Deserialising our application

#### Article quality
In this tutorial, we'll look at how to utilize the json_serializable package in Flutter to parse from/convert to json model instances. We'll also look at how to build custom conversions for non-primitive types using JsonConverterX, Y>.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, your key takeaways are not enough to cover a quality article. Most of the contents are already covered in other articles. Feel free to suggest another topic. Thanks
