### ISSUE TITLE
How to Adjust Image to Higher or Lower Resolution using Python

### ISSUE THREAD

**Issue by lizpart** [section-engineering-education/engineering-education#5469]
#### Proposed title of article

How to Adjust Image to Higher or Lower Resolution using Python

#### Proposed article introduction

Low-resolution image is at times annoying. I will be showing you how to enhance such a image.
When increasing the dimensions of an image, the extra pixels need to be interpolated somehow. Basic image processing techniques do not give good results as they do not take the surroundings in context while scaling up.
Deep learning and, more recently, GANs come to the rescue here and provide much better results not leaving out making use of openCV.

#### Key takeaways 

- Fixing the colors.
- Implementing contrast enhancement.
- Implementing LapSRN.
- Scaling Factor (Downscale/Upscaling)
- How to use a pillow. 
- Application fields for adjusting image and video resolution.

#### Article quality

The main insight of this article is creating awareness for the existence of such programs . Since it's designed in an easy-to-learn language having straightforward steps to follow, coded in fun and interesting ways making use of modules such as pillow and many others.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @lizpart 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
