### ISSUE TITLE
How To Implement Search Functionality In Your Nuxt App Using Algolia InstantSearch

### ISSUE THREAD

**Issue by duncandegwa** [section-engineering-education/engineering-education#5471]
### Topic Suggestion
How To Implement Search Functionality In Your Nuxt App Using Algolia InstantSearch 

#### Proposed article introduction
Many websites have some sort of search feature because it helps users navigate through their content easily. Implementing it the right way can be tricky and might not give a good user experience. In this tutorial, we’ll be looking at how to integrate this search functionality into our Nuxt app using Algolia. Algolia is a third-party service that we can integrate into our app and provides us with a set of tools that allow us to create a full search experience in our sites and applications.

#### Key takeaways 

- Setting Up Our Nuxt App
- Create Blog Page To List Our Articles
- Install And Set Up Algolia Search And Vue-InstantSearch 
- Create A Search Component
 - Styling Our Search Component 

#### Article quality
In this tutorial, we will be integrating Algolia, a popular and powerful search service for the best experience on our Nuxt site. We’ll build a Nuxt site with Nuxt Content with a search feature using Algolia InstantSearch.

**Comment by ahmadmardeni1** [comment]
Fill in the form please @duncandegwa

**Comment by duncandegwa** [comment]
> 

Done @ahmadmardeni1

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @duncandegwa 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
