### ISSUE TITLE
Introduction to Tree Data Structure in CSS

### ISSUE THREAD

**Issue by chepnelly** [section-engineering-education/engineering-education#5472]
### Introduction
In this tutorial we are going to learn about Tree Data Structure. A tree data structure is a structure where each node is connected to a previous or parent node in a hierarchical order.
In the tutorial ,we will also discuss about a binary tree and its uses in data storage. Binary Tree is a special data structure used for data storage purposes. A binary tree has a special condition that each node can have a maximum of two children. 

#### Key takeaways 
- What is a tree data structure?
- data structure and Algorithms 
- facts about Tree
- types of tree Data Structures.
- binary tree
### Conclusion
At the end of this tutorial the reader will have understood what is a tree data structure and the types of tree data structures. He or She will also learn more about types of the tree data structures and most importantly the binary tree.
Happy reading.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
