### ISSUE TITLE
Understanding race conditions with JavaScript examples

### ISSUE THREAD

**Issue by vinmugambi** [section-engineering-education/engineering-education#5474]
# Introduction

A race condition is a situation where software behavior is affected by ordering and timing of uncontrollable events. This events include OS signals, user inputs and hardware interrupts among others. Race conditions often result in bugs that are hard to detect and which are detrimental to software performance and  user experience.

In this article I will demonstrate how race conditions can occur in JavaScript much as the JS engine being single threaded. I will also suggest tactics to prevent undesired race condition

## Prerequisites

- Fundamental knowledge of JavaScript
- Basic understanding of JS promises

## Key takeaways

- Understand effects of race conditions and how to mitigate them
- Write concurrent logic that you can trust

## Quality

Race conditions is a fairly old issue often explained in the context of multi-threaded languages. Even then, its an issue that many developers are yet to grasp. A myth goes by that single threaded languages are not affected by race conditions.
JavaScript has grown from being a web scripting language to a language that runs on all devices and developers are using it to build huge applications that utilize concurrency. Given that race conditions are hardly caught during test, It's important that JS developers, and other developers, understand how to prevent race condition bugs to build software they can trust and deploy in confidence.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
