### ISSUE TITLE
Implementing exception handling in C++

### ISSUE THREAD

**Issue by Wainich21** [section-engineering-education/engineering-education#5478]
#### Proposed title of article
[Languages] Implementing exception handling in C++

#### Proposed article introduction
It's quite uncommon for a huge program or piece of software to operate flawlessly the first time. It might include inaccuracies. Programmers can troubleshoot these issues by putting their debugging and testing skills to the test. However, in addition to logic and syntax faults, programmers frequently encounter other unique issues. Exceptions are the name for certain sorts of problems. Run-time anomalies or odd logical circumstances that may occur when executing the C++ program are referred to as exceptions.
We handle exceptions so that the application's usual flow may be maintained even when runtime issues occur.
In C++, an exception is a runtime event or object that is thrown. The std::exception class is the root of all exceptions. It's a runtime mistake that can be dealt with. If we don't handle the exception, the application will print an error message and end.

#### Key takeaways 
The reader should be able to understand:
- What is meant and entailed with exception handling in C++
- Various types of exceptions
- Why exception handling and its advantages
- Exception handling in action which will be part of its implementation

#### Article quality
I will provide a detailed explanation of this concept with proper steps and output. Also, I will explain further the types of errors that are likely to be committed, exception classes as well as the keywords to perform exception handling. I will ensure working codes with outputs and comments. I aim to make it more interesting, simple to understand, and more beginner-friendly. The reader will appreciate easy-to-understand language use.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
We have already covered this topic - Please suggest another topic to explore @Wainich21
