### ISSUE TITLE
How To Serialize And De-serialize JSON Data In Python

### ISSUE THREAD

**Issue by Simsamrosh** [section-engineering-education/engineering-education#5484]
#### Proposed title of article
How To Serialize And De-serialize JSON Data In Python

#### Proposed article introduction
In computing, serialization is the process of translating a data structure or object state into a format that can be stored or transmitted and reconstructed later. The opposite operation, extraction of  data structure from a series of bytes, is called deserialization.

When it comes to dealing with data and APIs, we encounter either a dictionary or a JSON format of data. At times, we need functions that enable us to perform interconversion amongst them. We will be having a look at some of the methods to have the data serialized as well as de-serialized.

#### Key takeaways 
-Serialization v/s encoding
-General overview of python json module
-Serializing and de-serializing simple built-in datatypes
-Serializing and decoding custom objects

#### Article quality
Unlike other articles of similar topic in various sites, my article will be suitable to beginners. As I have illustrated in my key takeaways, I will first help the reader differentiate serialization and encoding which sounds ambiguous and then introduce Him/her to the json module. This will equip reader with basic tips before embarking to the actual task. This tutorial also goes a notch higher to differentiate serialization of  simple built-in datatypes and custom objects.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
