### ISSUE TITLE
How to Build a Simple CRUD Application Using Flutter & Strapi

### ISSUE THREAD

**Issue by CT2034-hash** [section-engineering-education/engineering-education#5485]
#### Proposed title of the article

*How to Build a Simple CRUD Application Using Flutter & Strapi*

#### Proposed article introduction
Strapi is a JavaScript framework that simplifies the creation of REST APIs. It allows developers to create content types and their relationships between them. It also has a media library that will allow you to host audio and video assets.
In this article I aim to help n programmers understand how to build a Create, Retrieve, Update and Delete (CRUD) application using Flutter and Strapi. We will also call End-points provided to us by Strapi using the HTTP package in our app. We will build screens where different operations will take place like adding/creating a new user, Retrieve User data, Update user data and Delete data.

#### Key takeaways 
* learn how to boost productivity with strapi.
* what is headless cms.
*  Fetching single and multiple contents
* The importance of strapi and different ways of implementation.
* how building screens several screens.

#### Article quality
My article will be unique as it is a step by step tutorial in that-:

It will explain to the user the concept of CMS and how a headless CMS works.
It will take the user through the basics of Strapi (This will help new readers get a better understanding).
It will contain attached screenshots to show the user how to set up Strapi.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Ensure that your article is unique to avoid potential closure.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by CT2034-hash** [comment]
Requesting reopening of this topic ready to complete it.

**Comment by CT2034-hash** [comment]
> Just wanted to follow up on this topic, as we will be clearing up the queue where possible.
> 
> Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. +1

Requesting reopening of this topic. I'm ready to complete it.

**Comment by hectorkambow** [comment]
Is the article complete and ready to be reviewed and published?

**Comment by CT2034-hash** [comment]
> Is the article complete and ready to be reviewed and published?

Thank you for reopening it. Almost done a day or two it will be ready for review

**Comment by hectorkambow** [comment]
We can open this then 👍
