### ISSUE TITLE
How to build a Search Engine for Reddit with JavaScript

### ISSUE THREAD

**Issue by khabdrick** [section-engineering-education/engineering-education#5486]
### Topic Suggestion
How to build a "Google" for Reddit

### Writing sample(s): 
https://adamtheautomator.com/docker-save-image/https://adamtheautomator.com/github-actions-environment-variables/
https://okteto.com/blog/develop-and-deploy-a-flask-and-reactjs-app-in-okteto/index.html
https://www.section.io/engineering-education/dockerized-django-application-with-github-actions/

#### Proposed title of the article
How to build a "Google" for Reddit

Use keyword research to improve your article's SEO.

#### Proposed article introduction
The main objective of this article is to show the reader how to build an application that can go through Reddit and search for content and it returns related news and content on Reddit

I will add functionality in which the user of the application can add extra queries to their search results. The reader will learn how to do all that using Javascript, Reddit API.

ONLY viable topics to pick from:
- API
- Languages

#### Key takeaways 
- How to query Reddit API
- How to fetch API's basically with JavaScript
- How to limit queries when fetching Reddit API

#### Article quality
This article is unique as it has not been written by anybody before.

**Comment by WanjaMIKE** [comment]
Could you update your topic/title to reflect more on what you will build.

**Comment by khabdrick** [comment]
Hello, @WanjaMIKE I've made a change in the title.

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
