### ISSUE TITLE
 Getting Started with Ray Tracing Algorithm in Machine Learning

### ISSUE THREAD

**Issue by LucidRay** [section-engineering-education/engineering-education#5491]
### Topic Suggestion
Getting Started with Ray Tracing Algorithm in Machine Learning

#### Proposed title of article
Getting Started with Ray Tracing Algorithm in Machine Learning
#### Proposed article introduction
The most successful image synthesizing technique is the Ray Tracing Algorithm. This technique has a greater ability than other scanline rendering methods to produce a high level of realism virtually. However, the computational cost is higher. In today's digital world, computer graphics are the most basic requirement. 

When we need to create a virtual image that looks very real and is indistinguishable from a regular photograph, we use computer graphics. There are numerous approaches that can be taken in order to accomplish this. One such rendering method is ray tracing. This is used to generate an image by tracing the path of light as pixels in an image plane and simulating its effects when it encounters virtual objects.

#### Key takeaways 
Types of Ray Tracing Algorithm
How Ray Tracing Algorithm works?
Hybrid Ray Tracing Algorithm
A Brief History of Ray Tracing Algorithm

#### Article quality
In my article I'll take the reader vividly through Hybrid Ray Tracing Algorithm and other types of Ray Tracing Algorithm, I'll also give a brief history of it and elaborate how it works. I'll make sure to use simple grammar hence my article will be beginner-friendly

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@lalith1403 what do you think of this topic?

**Comment by ahmadmardeni1** [comment]
I think this is a great topic. @WanjaMIKE

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by LucidRay** [comment]
Hello @hectorkambow @WanjaMIKE  kindly reopen the issue so that I can submit the PR

**Comment by LucidRay** [comment]
> Hello @hectorkambow @WanjaMIKE kindly reopen the issue so that I can submit the PR

sorry for the delay.... I've been having my exams that's why it has taken me this long
