### ISSUE TITLE
[Android]How To Prevent And Allow Taking Screenshot In An Android App Using Kotlin To Improve App Security

### ISSUE THREAD

**Issue by Rose-Meghan** [section-engineering-education/engineering-education#5498]
### Topic Suggestion
[Android]How To Prevent Taking Screenshot In An Android App Using Kotlin To Improve App Security

#### Proposed title of article
How To Prevent And Allow Taking Screenshot In An Android App Using Kotlin To Improve App Security

#### Proposed article introduction
Certain apps contains confidential information for instance, PayPal android app which is a finance or banking app that restricts the users from taking screenshots. This mechanism helps in securing the app's data. For example if a user wants to share the information of the app via a screenshot.

Implementing this feature in Android applications hasn't been easy for developers. With this article I hope it's going to help the developers task to implement this feature in their apps and secure the user's data.

#### Key takeaways 
- What is an app screenshot
- How to prevent taking screenshot
- How to allow taking screenshot
- Advantages of using this feature

#### Article quality
This article is going to be in Kotlin. As I was doing research on this topic I also happened to realize that the issue has been challenging as per this question on [StackOverflow](https://stackoverflow.com/questions/28606689/how-to-prevent-screen-capture-in-android). This article is therefore going to be unique to help in solving the issue fully.

#### References
[Preventing taking of screenshots in Android](https://stackoverflow.com/questions/28606689/how-to-prevent-screen-capture-in-android)

**Comment by WanjaMIKE** [comment]
Unfortunately, his topic appears to be adequately covered in numerous documentations. Feel free to suggest another topic. Thanks
