### ISSUE TITLE
Performing exception handling using C#

### ISSUE THREAD

**Issue by Samrosh** [section-engineering-education/engineering-education#5499]
#### Proposed title of article
[Languages] Performing exception handling using C#

#### Proposed article introduction
An exception is an occurrence that occurs during the execution of a program that the program code does not expect. Exception Handling is a process of dealing with such errors. We handle exceptions so that the application's usual flow can be maintained even when runtime issues occur.
In C#, exception is an event or object which is thrown at runtime. System is the source of all exceptions. This is an exception class. It's a runtime error that can be dealt with. If we don't handle the exception, the application will print an error message and terminate.

#### Key takeaways 
By the end of this article the reader will understand:
- Basically what exception is as well as exception handling in C# and some of it's classes 
- How to perform exception handling using try-catch block
- What to do when we are not sure about the type of exception that may be generated using multiple try-catch blocks
- What to do with exception not defined by the language 

#### Article quality
I'll go through all of the principles linked to the topic in detail, taking into account all alternative methods. I'll also include proper examples with accurate outputs and comments, as well as any images that are required. This idea will be discussed in depth and in an engaging manner that is suitable for beginners. The reader will appreciate how simple and easy it is to use language to improve understanding. In my scope of coverage I will ensure the reader gets to know the key words used as well as the advantages of exception handling in C#. I will entitle the reader into how to catch non-CLS-Exceptions.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
