### ISSUE TITLE
[Android]Comparing RxKotlin to Kotlin Coroutines in Performing Background Task

### ISSUE THREAD

**Issue by benta-odek** [section-engineering-education/engineering-education#5500]
#### Introduction
Reactive programming is not just another API. It’s a whole new programming paradigm concerned with data streams and the propagation of change. RxKotlin is a light weight library which adds a simple extension function to RxJava, this extension function can streamline the usage of Rxjava. While on the other hand, Kotlin Coroutines are light weight thread which are basically used to simplify codes that execute asynchronously.

One of the most important things and a great advantage of RxKotlin is the decreasing of the memory leak in 90%, possible by replacing standard Android mechanisms, which much like garbage collection was important in C, becomes really useful when you are developing Android applications that no longer need to take that into much consideration . It could optimize code to improve an application’s responsiveness and it’s very easy to scale.

#### Key takeaways 
- Understanding difference between Rx Kotlin and Kotlin Coroutines
- Implementing Rx Kotlin in android
- Pron and Cons of Rx Kotlin
- When to use Rx Kotlin and when to use Kotlin Coroutines

#### Article quality
This article will highlight the main difference between RxKotlin and Kotlin Coroutines which is not well explained in many cases. It will also guide both novice and expert readers on the implementation of RxKotlin as compared to Kotlin Coroutines and give the merits and demerits of RxKotlin as compared to Kotlin Coroutines

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
N/A

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
