### ISSUE TITLE
[Machine Learning] Understanding embeddings in Machine Learning

### ISSUE THREAD

**Issue by ogoti-lilian** [section-engineering-education/engineering-education#5502]
#### Proposed title of article
Understanding embeddings in Machine Learning

#### Proposed article introduction
Working with non-dimensional data can be tough, even for experienced data scientists. A typical machine learning model expects the data to be numbers and not words, emails, website pages, lists, graphs, or probability distributions. For the data to be useful, it has to be transformed into a vector space first.
Existing approaches are not that useful and applicable as they tend to have flaws when transforming the data. A better approach would be to use embedding which is a low dimensional representation of high dimensional data.
In the proposed article, we will look at embeddings in detail and how they can be used to solve real-world problems that involve complex data.

#### Key takeaways 
At the end of the proposed article, the learner would be able to understand:
- the concept of embedding in data transformation
- how embeddings are created
- most commonly used embeddings models
- various embedding operations
- how embeddings operate in today's world.

#### Article quality
Unlike most articles found online which provides scattered information about the topic, the proposed article covers comprehensively the whole concept of embeddings in Machine Learning, highlighting the real-world use of embeddings. The article will be essential for beginners and readers at an advanced level.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @ogoti-lilian 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by ogoti-lilian** [comment]
@ahmadmardeni1 Kindly do not close this topic am currently finishing up on it and I will upload it within the week. Thank you
cc @hectorkambow
