### ISSUE TITLE
Using Dictionary Collections in VB.NET to Work With Key Value Pair

### ISSUE THREAD

**Issue by Joesongoma** [section-engineering-education/engineering-education#5508]
### Topic Suggestion
Using Dictionary Collections in VB.NET to Work With Key Value Pair

### Writing sample(s): 
https://www.section.io/engineering-education/creating-a-blazor-server-side-application-using-aspdotnet-core-to-perform-crud-operations/
https://www.section.io/engineering-education/java-timer-tasks/

#### Proposed title of article
Using Dictionary Collections in VB.NET to Work With Key Value Pair

#### Proposed article introduction
A dictionary is used to store an array of data that consists of virtually any data type including custom objects and classes. The main difference between a dictionary collection and other collections is that a dictionary allows us to create a key value that can be used as a sort of custom index based upon a data type of the choosing. This can simplify retrieval of data from your collection and make it feel much intuitive and logical.

In this VB.NET tutorial, we will be learning how to use the dictionary collection to store and retrieve various types of data. We will create a dictionary array, add, update, and remove items by their index key. We will also learn how to return our dictionary values to a ListBox using a For Each Loop.

We shall be looking at each of the following;
- Collections
- Form controls
- Loops
- Subs (Menu update)

#### Key takeaways 
The reader will learn about:
- Dictionary collections
- How to use ListBoxes, Labels, TextBoxes, Buttons under Form controls.
- How to update menu in Subs

#### Article quality
This tutorial intends to take the reader through the concept of dictionary collections and how the reader can work with key values in the dictionary collections. I will be taking the reader through a step by step showing him or her how dictionary collections are implemented in VB.NET.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

**Comment by WanjaMIKE** [comment]
https://www.google.com/search?q=Using+Dictionary+Collections+in+VB.NET+to+Work+With+Key+Value+Pair&sourceid=chrome&ie=UTF-8
