### ISSUE TITLE
Fundamental Concepts Of Linux

### ISSUE THREAD

**Issue by gladwel-kieya** [section-engineering-education/engineering-education#5514]
**Proposed title of article**

Fundamental Concepts Of Linux

**Proposed article introduction**

Linux is an operating system that runs different servers for example, apache web servers, database servers, mail servers and proxy servers.
Linux has built up a strong set of networking capabilities, including network tools for providing and managing routing, bridging, DNS, DHCP, network troubleshooting, virtual networking and network monitoring. It also allows users to talk to the hardware in a productive operation.
In this topic I'll cover the following:
- Introduction to Linux
- Linux Environment
- Root in Linux
- Linux file system essentials
- Command line basics in Linux
- TCP/IP networking basics
- Linux distros

**Key takeaways**

After reading the article the reader should understand why Linux is used by most people and the different versions of Linux.

**Article quality**

Unlike other articles, this article will be precise and easy to understand.

**References**

N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

**Comment by WanjaMIKE** [comment]
https://www.google.com/search?q=Fundamental+Concepts+Of+Linux&sourceid=chrome&ie=UTF-8
