### ISSUE TITLE
[Android] Creating Custom Parallax Effects in Jetpack Compose

### ISSUE THREAD

**Issue by nonimdiana** [section-engineering-education/engineering-education#5515]
### Writing sample(s): 
So far, I have published the following articles on Section:
- [Integrating Cloud Firestore database in Android-Kotlin](https://github.com/section-engineering-education/engineering-education/pull/2601)
- [Image processing with Coil in Android](https://github.com/section-engineering-education/engineering-education/pull/2850)
- [Firestore data modeling and query customization in Android](https://github.com/section-engineering-education/engineering-education/pull/3730)

#### Proposed article Introduction
Parallax is a computer graphics manipulation technique, where background images or layers move slower than foreground content. This gradual process creates an illusion of depth in a 2D scene and adding to the immersion. When correctly applied to scrollable and static components simultaneously, parallax effects can create a unique and impressive visual effect thus improving the user experience while using the app.

In Android development, Parallax can be achieved by either using the XML layouts or by using Jetpack Compose APIs. The latter is the preferred method for creating parallax effects in the modern era of declarative UI development.

#### Key takeaways 
By the end of this tutorial, the reader will be able to:
1. Understand what Frames and graphics layers are.
2. Understand what Parallax is and how it is related to UI/UX in general.
3. Implement Parallax effects in Android using Jetpack Compose.
4. Create custom and animated parallax effect.
5. Learn the `don'ts` when working with Parallax.

#### Article quality
This tutorial will go beyond what can be found in [the official documentation](https://developer.android.com/jetpack/compose/phases) as it will cover the modern and best practices (based on my experience) of creating and customizing graphics. Since Compose is still a new framework, similar articles aren't provided by other blog sites yet!

#### References

N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @nonimdiana 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
