### ISSUE TITLE
Forms And Validation In Ionic React

### ISSUE THREAD

**Issue by Bonimum** [section-engineering-education/engineering-education#5519]
#### Proposed title of article
Forms And Validation In Ionic React. 

#### Proposed article Introduction
Ionic Framework is a UI Toolkit for building cross-platform mobile applications using HTML, CSS, and JavaScript. The release of Ionic 5 in early 2020 came with official support for React, enabling React developers to easily build mobile applications using their favorite tools. There isn’t much support for working with forms, however, and many of the existing libraries available for building forms in the React ecosystem do not play nicely with Ionic Framework’s components.

You will learn how to build forms using Ionic React’s UI input components in this tutorial. You will also learn how to use a library to help with detecting form input changes and responding to validation rules. Finally, you will learn to make your forms accessible to screen readers by adding helpful text to your inputs’ ARIA attributes.
#### Key takeaways 
By the end of this tutorial the learners should:

- Ionic’s Form Components
- React Hook Form: Small And Fast React Forms Library
- Building A Signup Form 
- How About Field Validation?

#### Article quality
In this tutorial, you will learn how to build forms when working with Ionic React and how to make these forms interactive by adding validation rules with helpful text hints.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Bonimum 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
