### ISSUE TITLE
[LANGUAGES] Neumorphism Vs. Glassmorphism and Their Implementation Using CSS and HTML

### ISSUE THREAD

**Issue by lin-chez** [section-engineering-education/engineering-education#5520]
### Topic Suggestion
Neumorphism Vs. Glassmorphism and Their Implementation Using CSS and HTML

### Writing sample(s): 

- [How to Add Pure CSS Waves to Your Website](https://www.section.io/engineering-education/pure-css-wave-animations-website/)

#### Proposed article introduction
An interactive and captivating user interface design has the capability of ensuring that a user remains intrigued and fulfilled by a webpage when implemented correctly. There are numerous ways developers can ensure that their user interface design makes their creations stand out from the rest. In this article, we are going to explore how using neomorphism, and glassmorphism can change the look and feel of your next webpage.

#### Key takeaways 

By reading this article, you will get to learn about:
-The two UI design strategies 
-The importance of an intriguing and captivating user interface design.
-How the two design strategies will improve your web user interface.
-The various points of your page that each design strategy fits appropriately. 
-How to implement the two design patterns to a login page with ease using CSS and HTML.

#### Article quality
This article features a detailed discussion on how the two design patterns compare and contrast. The article includes suggestions on the various application areas of each design pattern and places extra emphasis on the login page of a website.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
What do you think of this topic? @WanjaMIKE

**Comment by WanjaMIKE** [comment]
This topic appears to be too broad could you narrow it down. Thanks

**Comment by lin-chez** [comment]
@WanjaMIKE Hallo! Kindly review the changes and advice.

**Comment by WanjaMIKE** [comment]
Let's ensure that it adds value to the community. Thanks

**Comment by WanjaMIKE** [comment]
Closed #5520 via #5872
