### ISSUE TITLE
 learn the most effective method to Implement OTP SMS Mobile Verification in PHP with TextLocal

### ISSUE THREAD

**Issue by Robbiewanjau** [section-engineering-education/engineering-education#5523]
#### Proposed title of the article
[Languages] learn the most effective method to Implement OTP SMS Mobile Verification in PHP with TextLocal
#### Proposed article introduction
OTP is an effective way to validate users. This type of validation is widely used in banking applications, e-commerce software, and many other industries. In this tutorial, you will learn how to implement OTP SMS mobile number verification using PHP.

#### Key takeaways 
> By the end of this article learns will have a grip on the following :
1. Get Mobile Number to Send OTP
2. Submit OTP for Verification
3. Requesting OTP Sending and Verification code

#### Article quality
well-formatted, in context, precise and informative content will be provided to enhance and encourage the good growth of the community. We will have a simple example with simple code snippets to further understand OTP sending and verification.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Robbiewanjau 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
