### ISSUE TITLE
[Languages] Learn how to use PHP with chart.js Recipes to create Dynamic stacked Bar, Doughnut and pie charts

### ISSUE THREAD

**Issue by Pato-254** [section-engineering-education/engineering-education#5528]
#### Proposed title of the article

Learn how to use PHP with chart.js Recipes to create Dynamic stacked Bar, Doughnut, and pie charts

#### Proposed article introduction

Users can digest data and statistics more easily with the help of visualization and charts. Do you need the means to display complex statistics in your application? If you want to learn how to make a chart in PHP, then read on. We'll look at how we can implement data visualization using PHP in this post.

#### Key takeaways 
> By the end of this article the following outcomes are expected:

1. Creating HTML canvas to create a chart
2. Initializing Chart.js and loading data into dynamic charts
3. Creating PHP Models and Utils to prepare charts data
4. Article Example: 
              - create a chart in PHP. 
              - Read data from the database
              - load data into dynamic charts created using Chart.js.

#### Article quality

The main insight of this article is creating awareness for the existence of data visualization in PHP. Since it will be designed in easy-to-learn language snippets having straightforward steps to follow. 

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Pato-254 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
