### ISSUE TITLE
Getting Started with HackTheBox

### ISSUE THREAD

**Issue by shosenwales** [section-engineering-education/engineering-education#5531]
### Topic Suggestion
Getting Started with HackTheBo

### Writing sample(s): 
https://www.section.io/engineering-education/understanding-cross-site-scripting-attacks/

#### Proposed title of article
Getting Started with HackTheBox 

#### Proposed article introduction
HackTheBox is a ethical hacking platform, where you get to practice hacking in a controlled environment.

#### Key takeaways 
By reading this article learners will be able to:

1. Use the hackthebox platform
2. Practice hacking
3. Improve hacking skills

#### Article quality
The main purpose of this article to provide an overview of the HackTheBox platform, and how to start practicing hacking.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
