### ISSUE TITLE
[Languages] Learn how to Create a Dynamic XML Sitemap for Your Website Using PHP

### ISSUE THREAD

**Issue by Eliud200** [section-engineering-education/engineering-education#5533]
#### Proposed title of the article

Learn how to Create a Dynamic XML Sitemap for Your Website Using PHP

#### Proposed article introduction

A sitemap is a mapping file that has the specification about the site page URLs and more related details. It may also map other content URLs of the posts, products, images, videos, news, and more in a conventional structure.
There are conventions for the XML schema for the sitemap protocol.
It lets the search engine crawlers parse the sitemap XML and provide valuable details. These details are useful to optimize the web pages, content, and the relationship between them.
The search engine crawlers capture the recently updated pages among the others. It will help to gain reputations based on the change frequencies.
In this article, we will discuss generating sitemaps for a website and their importance more in the upcoming sections.

#### Key takeaways 

> Expected outcomes are as follows :
1. Generate sitemap dynamically in PHP
2. Retrieve pages from the database
3. Sitemap service in PHP to construct XML
4. Output sitemap XML data format

#### Article quality

The main point of this article is to raise knowledge about how to Create a Dynamic XML Sitemap for Your Website Using PHP. Because it is created in an easy-to-learn language with simple steps to follow, it is developed in exciting and engaging ways that make use of modules such as XML Sitemap and many others.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
What do you think of this topic? @WanjaMIKE

**Comment by WanjaMIKE** [comment]
Seems like a helpful article @ahmadmardeni1 Let's ensure that it adds value to the community @Eliud200 . Thanks

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
