### ISSUE TITLE
[Machine Learning] Multi-Output Classification with Machine Learning

### ISSUE THREAD

**Issue by willyngashu** [section-engineering-education/engineering-education#5535]
#### Proposed title of article
[Machine Learning] Multi-Output Classification with Machine Learning

#### Proposed article introduction
Multi-Output classification is a type of machine learning that predicts two different outputs at the same time. In Multi-Class machine learning, the model usually predicts only a single output but in multi-output classification, we have more than one output. Therefore, the model will be able to give more than one prediction at the same time.

For Example,  a multi-output classification model predicts the “type of fruit” and “color” of fruit at the same time.  The “type of fruit” cab be, “orange”, “mango” and “pineapple”. The “color” can be, “red”, “green”, “yellow”, and “orange". The multi-output classification can be used to solve this problem and give two prediction results.

In this tutorial, we will build a machine learning model that will be able to classify the `genre` of a movie or a series such as `drama`, `comedy`, `action`, or `thriller`.  The model will also be able to predict the `rating` of a movie or series such as `PG`, `TV14` or `TV18`. The output after prediction will be both the `genre` and `rating` of movies or series. We will use Scikit-Learn `MultiOutputClassifier` to build this model.

#### Key takeaways 
1. Multi-Class vs Multi-Label vs Multi-Output classification.
2. Techniques used to handle multi-output classification.
3.  Dataset preprocessing(Netflix dataset).
4. Building the multi-output prediction model.
5. Model predictions. (Predicts the `genre` and `rating` of movies or series)

#### Article quality
This tutorial is unique because we will compare the types of classification, Multi-Class vs Multi-Label vs Multi-Output classification. This will give us a deeper understanding of the problems before we start working on Multi-Output classification.  We will build a custom model using  Scikit-Learn `MultiOutputClassifier` algorithm. This is a practical approach and it will explain all the steps to build the model.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @willyngashu 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
