### ISSUE TITLE
[languages] A guide on how to text-share on LinkedIn API using php.

### ISSUE THREAD

**Issue by Briton97** [section-engineering-education/engineering-education#5536]
#### Proposed title of article
A guide on how to text-share on LinkedIn API using php.
#### Proposed article introduction
This tutorial will show you how to use the LinkedIn API in PHP and share text on LinkedIn using a model. This will allow your PHP site to automatically share material with the social network LinkedIn via API. To access LinkedIn's API, developers can use a developer console to create and manage applications and therefore utilize them in sharing their thoughts .

#### Key takeaways 
1. Make LinkedIn API application
2. Create and arrange API keys 
3. Recover approval code 
4. Exchange approval code for getting access token 
5. Get LinkedIn profile id
6. Post text on LinkedIn

#### Article quality
The main idea of ​​this article is to raise awareness of how to use PHP to share text on the LinkedIn. The article will be designed in a clear to understand language snippets therefore ideal to follow and learn.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
