### ISSUE TITLE
[Machine Learning] Classification of GitHub Issues Using Machine Learning.

### ISSUE THREAD

**Issue by charles721** [section-engineering-education/engineering-education#5537]
#### Proposed title of article
[Machine Learning] Classification of GitHub Issues Using Machine Learning.

#### Proposed article introduction
Classification of Github issues involves classifying the different GitHub issues and assigning different labels to them. In Github, we have in-built labels such as `help wanted`, `revision needed`, `enhancement`, and `question`. We also have custom labels that one can create. The classification model will be able to assign these labels automatically. 

For example, if a user opens a new issue, the model will analyze the given issue and assign the label automatically.  For example, if an issue requires a revision or enhancement, it will assign the `enhancement` and `revision needed` labels. 

In this tutorial, we will use the Github dataset to train our model. The model will be implemented using the Scikit-Learn library.
 
#### Key takeaways 
1. What are Github issues.
2. Prepare and transform the dataset.
3. Train and evaluate the model.
4. Predict with the trained model(assign labels)
5. Save model using Pickle and Joblib.

#### Article quality
This is article is unique, because we will build a custom model from scratch. We will follow all the steps from data preprocessing to using the trained model to make predictions. The model will be implemented practically and able to assign different labels to GitHub issues automatically. The steps are simple and easy to follow. A reader can easily follow and build a classification model.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@lalith1403 what do you think of this topic

**Comment by lalith1403** [comment]
Will you integrate this with a GitHub repo?

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
