### ISSUE TITLE
[Languages] Send Email by means of SMTP Server in Laravel utilizing PHPMailer

### ISSUE THREAD

**Issue by Freshiah** [section-engineering-education/engineering-education#5539]
#### Proposed title of article
Send Email by means of SMTP Server in Laravel utilizing PHPMailer
#### Proposed article introduction
You normally utilize the local mail() method to send messages from a PHP-based web application. however, PHP's mail() work now and then and may neglect to send messages or to send information to spam directories. Hence, it is constantly suggested that SMTP servers send messages from scripts in web applications. The PHPMailer library gives a simple method for sending email through a SMTP server utilizing PHP. This article e tells the best way to utilize PHPMailer to send an email through Laravel's SMTP server.

#### Key takeaways 

1. Command to install PHPMailer via Composer in your Laravel application
2. Load exception classes and PHPMailer
3. Initialize the PHPMailer and configure SMTP and mail
4. Send email via Gmail SMTP server in Laravel 
      - Gmail (my account page) and two-step verification 
5. Setting credentials in Laravel
#### Article quality
This article explains in detail how to send email via SMTP Server in Laravel and PHP in a precise manner for easy understanding and practice thereafter.
#### References
N/A

**Comment by WanjaMIKE** [comment]
This article here also uses PHPMailer to send emails. Check it out

**Comment by Freshiah** [comment]
> This article here also uses PHPMailer to send emails. Check it out
Hello, @WanjaMIKE  I've checked the possibility of there being a similar article but I couldn't get feedback.

**Comment by WanjaMIKE** [comment]
This article here https://github.com/section-engineering-education/engineering-education/pull/3371

**Comment by Njengab** [comment]
> This article here #3371

checked.

**Comment by Freshiah** [comment]
@WanjaMIKE  it appears to be a duplicate .thanks

**Comment by WanjaMIKE** [comment]
Thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value. Feel free to suggest another topic. Thanks
