### ISSUE TITLE
Quick Instructions to Create Custom User Model and Form in Django with basic advances

### ISSUE THREAD

**Issue by akenz1901** [section-engineering-education/engineering-education#5541]
## Proposed title of Article

Quick Instructions to Create Custom User Model and Form in Django with basic advances

#### Proposed Article Introduction

Django's built-in User model permits us to begin working with users immediately. However, the official Django documentation enthusiastically suggests using a custom user model for new tasks. The explanation is that to roll out any improvements to the User model down the road, for example, adding a "date_of_birth" field using a custom user model from the start makes this very simple. But, if you do not create a custom user model, updating the default User model in an existing Django project is very, very challenging.
It's quite better to consistently use a custom user model for all new Django projects. Be that as it may, the methodology exhibited in the official documentation model is not what numerous Django expertise suggest.

#### Key takeaways
- Include additional fields to an existing User Model.
- Use preferred User Creation Form rather than the limited default one.
- Initialize a preferred Signup page using Username, First Name, Last Name and Date of birth form fields.
- Use class AbstractUser for quick and easy start.

#### Article quality
The motivation behind this article is to order the quick clear start of using Custom User Model and understanding why it's better to utilize Custom User toward at the beginning of a project before migrating to the database, additionally this article will clarify the distinction between class AbstractUser and AbstractBaseUser, and why AbstractUser is better for a quick start.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @akenz1901 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by akenz1901** [comment]
Thank you so much for the quick response.
