### ISSUE TITLE
[Languages]How To Build a URL shortener Using React, Firebase and Python Flask

### ISSUE THREAD

**Issue by codeInn001** [section-engineering-education/engineering-education#5549]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
How To Build a URL shortener Using React, Firebase and Python Flask

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-ship-zero-javascript-with-astro/

#### Proposed title of article
[Languages] How To Build a URL shortener Using React, Firebase and Python Flask

#### Proposed article introduction
Using links or URLs has been the norm for surfing the web for a long time. Sometimes we need to advertise our businesses on social media. Long URL links are not the best way to post these links, especially on social media. Doing this will help you promote your products or any services with the links provided.

You might be wondering how these things work. To understand how, we need to take a closer look at an URL shortener — so we’ll be building a simple one! With that task, we’ll be learning some new things as well as understanding how a URL shortener works.

#### Key takeaways 
1. How to build a url shortener using React
2. Readers will learn how to work with Firebase
3. Readers will learn how to Fetching data from a database using Flask and displaying it on React webpage.

#### References
reactjs.org
https://flask.palletsprojects.com/en/2.0.x/
firebase.google.com

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by codeInn001** [comment]
In the article, I will use React to build the front end of the application, this is hardly covered in articles about URL shortener.
Also, we will be using firebase as our database, this also is hardly covered in most articles.

Thanks.

**Comment by ahmadmardeni1** [comment]
Anyone can learn how to build a React app or a Firebase database on the official documentation. @codeInn001 Also, there are a lot of articles covering the same topic. 

Thank you for submitting your topic.

Please feel free to suggest an alternate topic to explore. 🚀
