### ISSUE TITLE
Building scalable interactive forms using Xstate and Vue 3

### ISSUE THREAD

**Issue by vinmugambi** [section-engineering-education/engineering-education#5553]
**Proposed introduction**

Users don't enjoy filling forms especially they are long. But we can always make them more interesting by making them interactive and reduce mental burden on users. 
In this tutorial we'll design and build a multi-step form a static JSON configuration. We'll use Xstate explicitly model form behaviour and vue 3 with composition for the interface. 

**Contents**
- Why xstate
- Brief introduction to xstate, state machines and statecharts
- Template/configuration driven form
- Validating form inputs
- Split long forms into shorter steps

**Prerequisites**

- Basic understanding of Vue and general JS
- Understand JS promises

**Key takeaways**

- Understand state machines and statecharts
- Managing complex application state in a predictable manner
- Separating business logic from view logic
- Vue composition api
- Visualize business logic with statecharts
- Reduce duplication with Vue 3 composition API

**Quality** 

This article will gently introduce ideas to define  and visualize application behaviour in a manner that even those without programming knowledge can understand using Xstate. in addition, We'll build along a scalable dynamic multiple step  form whose inputs are generated from a static template, meaning that inputs an be removed, added or changed without modifying code.

**Comment by WanjaMIKE** [comment]
There are some significant readability challenges in your description that raise concerns over how much review/editing would be required from our peer review team. We don't provide editing services and recommend that students leverage online editing services (there are both free and paid services that you can explore), or try engaging with the community or other peers in your network to have them review prior to submitting a revised proposal. Thank you.

**Comment by vinmugambi** [comment]
Should I edit the description and reopen the issue?
