### ISSUE TITLE
[Security] Network Access and Security Control

### ISSUE THREAD

**Issue by Romans70** [section-engineering-education/engineering-education#5555]
#### Introduction
Network Access Control is a unified method of security that focuses on network visibility and limited user access within multiple users by adopting policies and regulations. The goal of network access control is to regulate network access, as the term itself implies. The goal of network access management is to prevent uninvited devices or users from accessing a protected business's networks. Security monitoring is the practice of identifying network threats and data breaches. Security monitoring is a critical component of cyber risk management because it allows organizations to identify cyber-attacks in their early stages and deal with them before they cause harm and inconvenience.

#### Key takeaways 
* How Network Access Control works
* Network Access Control capabilities
* Network Access Control List
* Types of security monitoring
* Security monitoring policy
* Security monitoring process
* Tools and Techniques in security monitoring

#### Article quality
The article will have simple language that anybody can understand easily. The details in the the article will be unique and will be useful to the whole EngEd community.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Romans70 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
