### ISSUE TITLE
Build a markdown Editor using React

### ISSUE THREAD

**Issue by oyedeletemitope** [section-engineering-education/engineering-education#5559]
#### Proposed title of article
Build a markdown Editor using React

Use keyword research to improve your article's SEO.

#### Proposed article introduction
*In this tutorial we'll be building a markdown Editor. A markdown is a markup language for creating formatted text using plaintext. Many àre farmilar with it but it actually seems fun to build it ourselves. And as I frontend developer, I choose to do it with React*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
In this article we'll be able to:
- Understanding of React
- How does it rank among other frontend framework
- why you should use React
- Build a markdown Editor in React

#### Article quality
It's not just about building the markdown but understanding how the framework works, why does it stand out, what gives it the edge amongst others. This article covers that. Also If you want to add to a list of projects you done. Then this article is for you.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @oyedeletemitope 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
