### ISSUE TITLE
[Artificial Intelligence]How To Control Multiple Servo Motors Using Arduino And Adafruit PCA9685 PWM Servo Driver 

### ISSUE THREAD

**Issue by Rose-Meghan** [section-engineering-education/engineering-education#5565]
### Topic Suggestion
[Artificial Intelligence]How To Control Multiple Servo Motors Using Arduino And Adafruit PCA9685 PWM Servo Driver 

#### Proposed title of article
How To Control Multiple Servo Motors Using Arduino And Adafruit PCA9685 PWM Servo Driver 

#### Proposed article introduction
Servo motors are electric motors that are very efficient, compact and low cost.  It is applied in artificial intelligence to drive and contorl the operations of robots. Artificial Intelligence is a field of computer science that deals with robots as well.

Driving servo motors with the Arduino Servo library is pretty easy, but each one consumes a precious pin - not to mention some Arduino processing power.  The Adafruit 16-Channel 12-bit PWM Servo Driver will drive up to 16 servos over I2C with only 2 pins.  

#### Key takeaways 
- What is Servo Motor
- What is an Arduino
- How to connect servo motor to an Arduino
- Advantages of servo motors to Artificial intelligence

#### Article quality
This article is going to be unique since since its going to be based on Arduinoo Mega 2560 which is a more powerful model of arduino than Arduino Uno model. The article is as well going to solve the problem of contoling more than one servo motor.

#### References
[Adafruit PCA9685 PWM Servo Driver ](https://learn.adafruit.com/16-channel-pwm-servo-driver?view=all)
[Servo Motors](https://www.section.io/engineering-education/how-to-control-a-servo-motor-using-a-raspberry-pi-3/)

**Comment by ahmadmardeni1** [comment]
We are looking for programmer-centric concepts explained in a fun and intuitive ways. We don't approve any hardware topics.
Please feel free to suggest an alternate topic to explore. 🚀
