### ISSUE TITLE
[language]In Python, learn how to scrape data from a website.

### ISSUE THREAD

**Issue by Graceshee** [section-engineering-education/engineering-education#5570]
#### Proposed title of article
[language]In Python, learn how to scrape data from a website.

#### Proposed article introduction
Web scraping is a computer-assisted way of extracting unstructured data from a website and storing it in a logical manner. Scratching sites can be done in a variety of methods, including using web-based services, APIs, or writing your own code. In this article, we'll learn how to scratch the web using Python.

#### Key takeaways 
1. Definition of Web Scraping
2. Why is Python a useful language for scraping the web?
3. How does web scraping work?
4. What is the procedure for web scraping?
5. For web scraping, there are a variety of tools and libraries that can be utilized

#### Article quality
To ensure it is beginner's friendly I will employ easy use of language to enhance understanding.
This article will be in-depth explaining all aspects of this concept straight to the point.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appears to be over saturated. We focus more on unique projects. Feel free to suggest another area. Thanks https://www.google.com/search?q=Python%2C+learn+how+to+scrape+data+from+a+website&oq=Python%2C+learn+how+to+scrape+data+from+a+website&aqs=chrome..69i57j69i61.705575j0j7&sourceid=chrome&ie=UTF-8
