### ISSUE TITLE
[Android] Handling Permission Appropriately in Jetpack Compose

### ISSUE THREAD

**Issue by tanscy-cassie** [section-engineering-education/engineering-education#5571]
#### Introduction
App permissions help support user privacy by protecting access to restricted data such as system state and Restricted actions, such as recording audio. 
With Jetpack Compose there are some changes in the approach and how we can request permissions.
Most developers do not handle these permissions correctly. In this article, I will explain the easiest ways in which one can handle single or multiple permissions in the android app at runtime.  

#### Key takeaways 
- What is permission handling
- What are runtime permissions
- How to implement single and multiple permissions at runtime

#### Article quality
This article will focus on showing a learner how to handle permissions correctly and with ease. It will be beginner-friendly to those who are venturing into Jetpack Compose and easy to follow along

#### References
- Permissions Handling in Android

**Comment by WanjaMIKE** [comment]
Nice topic. Let's ensure that it adds value to the community. Thanks

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by tanscy-cassie** [comment]
Hello @hectorkambow . Kindly open this issue. My PR is ready
