### ISSUE TITLE
[Android] Navigation in Jetpack Compose

### ISSUE THREAD

**Issue by essy-shiro** [section-engineering-education/engineering-education#5573]
#### Introduction
Navigation is a Jetpack library that enables navigating from one destination within your app to another, along specific routes. The Navigation library also provides a specific artifact to enable consistent and idiomatic navigation within screens built with Jetpack Compose
You can navigate between composables while taking advantage of the Navigation component’s infrastructure and features.

#### Key takeaways 
- Navigating between composables
- Navigating with required and optional arguments
- Navigating using deep links
- Testing navigation

#### Article quality
This article will focus on demystifying Jetpacks' navigation within composables. This article will help a reader gain firm knowledge and skills on navigating in compose. It will be easy to follow along for newbies in compose.

#### References
- Jetpack Compose Navigation Documentation

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appears to be well-covered in the official documentation. Feel free to suggest another topic. Thanks
