### ISSUE TITLE
[Machine Learning] An Overview of Jina AI

### ISSUE THREAD

**Issue by wilkistermumbi** [section-engineering-education/engineering-education#5577]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

An Overview of Jina AI

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Jina AI is a cloud-native neural search framework for building state-of-the-art and scalable deep learning search applications in minutes for any kind of unstructured data (videos, images, source code, long text etc.). In this tutorial, I will walk through our readers on how to use this framework to get their ML tasks done. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to understand:
- What is Jina AI?
- Components of Jina AI.
- How to install Jina AI.
- Implement an example to demonstrate how one can use the framework. 

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Jina AI is a fairly new framework released recently. Many many tutorials are available on it's use. This tutorial will give our readers a high-level overview of the framework and implement an example on how one can use the framework. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [Jina AI](https://jina.ai/)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @wilkistermumbi 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
