### ISSUE TITLE
[Android]Getting Started With Debugging In Android Using Chucker

### ISSUE THREAD

**Issue by Hepatrique** [section-engineering-education/engineering-education#5579]
### Topic Suggestion
[Android]Getting Started With Debugging In Android Using Chucker

#### Proposed title of article
Getting Started With Debugging In Android Using Chucker

#### Proposed article introduction
Chucker simplifies the inspection of HTTP(S) requests/responses fired by your Android App. Chucker works as an OkHttp Interceptor persisting all those events inside your application, and providing a UI for inspecting and sharing their content.

Apps using Chucker will display a push notification showing a summary of ongoing HTTP activity. Tapping on the notification launches the full Chucker UI. Apps can optionally suppress the notification, and launch the Chucker UI directly from within their own interface.

#### Key takeaways 
- What is Chucker and its applications in Android development.
- How Chucker simplifies the inspection of HTTP(S) requests/responses fired by your Android App.
- How to display a push notification when using Chucker.
- Advantages of using Chucker.

#### Article quality
This article is going to be unique since am going to use MVVM pattern to illustrate the concept of Chucker debugging. I am also going to make it beginner friendly to allow easy understanding. I am also going to show a push notification which is an added advantage to the reader. Although there are certain sites about Chucker, there are still problems with developers understanding the concept.

#### References
[Chucker](https://github.com/ChuckerTeam/chucker)

**Comment by WanjaMIKE** [comment]
What are your main key takeaways. Please list them. Thanks

**Comment by Hepatrique** [comment]
Hello @WanjaMIKE , I have edited the issue and added key takeaways as suggested. Please check for approvement. Thanks in advance.

**Comment by Hepatrique** [comment]
Hello @ahmadmardeni1 and @louisefindlay23 . I had added the key takeaways as suggested by @WanjaMIKE . Can I go ahead with writing the article.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Hepatrique 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
