### ISSUE TITLE
How to send emails using Emails.js in Vue3

### ISSUE THREAD

**Issue by mercybassey** [section-engineering-education/engineering-education#5580]
### Topic Suggestion
How to send emails using Emails.js in Vue3

### Writing sample(s): 
https://adanna-io.medium.com/checking-your-vue-application-with-the-vue-devtools-7563fb750f46
https://adanna-io.medium.com/angular-vue-or-react-which-is-better-and-why-d4e590fc72f8
https://ada.hashnode.dev/libraries-you-should-know-to-add-beauty-to-your-website-appearance-as-a-front-end-developer

#### Proposed title of article
How to send emails using Emails.js in Vue3

#### Proposed article introduction
[LANGUAGES] How to send emails using Emails.js in Vue3
Email.js is a javascript library that helps send emails using different client-side technologies. It is completely serverless and easy to set up. It is a library that supports multiple email services like Gmail, Fastmail, Outlook, Yahoo, and many others whichever suits our needs.

The Email.js library becomes very handy when receiving and sending emails. Let's say you have a portfolio and in there, you have a contact form where your potential employer can connect with you, with email.js all you have to do is connect it to one of the supported email services, create an email template and use it to trigger an email. So any message sent through that contact form will be sent right into your mailbox. No backend code is needed.

I will be walking you through the steps of signing up, choosing a supported email service, creating a template and also, showing you how to set it up on a Vue application using Vue3 composition API.

#### Key takeaways 
  1.  For Frontend developers having little or no knowledge about server-side technologies, By the end of this article one will be able to know how to integrate this library in Vue of which no server-side code is needed.
   2. After reading this article the reader should be able to know and understand how DOM manipulation is done on Vue3 as we will be manipulating the form element in the app to fully see the library's power in action.

#### Article quality
Vue3 is a new version of Vuejs that was recently released as a more efficient way of building Vue applications. There are not enough tutorials out there about it. That is to say, a whole lot of developers are yet to get a grasp of it. In this article I will be using this library with a different approach. On the email.js documentation, integrating it on a Vue3 application is not available. I refactored the code to make it work on vue3 which is a lot easier. I will not just be talking about how to use this library on a Vue application, I will also be talking about how to use this library specifically for Vue3.

#### References
(https://www.emailjs.com/docs/)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @mercybassey 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
