### ISSUE TITLE
Innovative Techniques To Simplify Sign-Ups And Log-Ins

### ISSUE THREAD

**Issue by Bonimum** [section-engineering-education/engineering-education#5581]
### Proposed title of article
Innovative Techniques To Simplify Sign-Ups And Log-Ins

### Introduction paragraph (2-3 paragraphs):
There are many ways to design sign-up and log-in forms. Most designers are familiar with the conventional ways. But understanding and applying a few innovative techniques could make your forms simpler and more efficient to fill out. In this article, we’d like to present a couple of new ideas that might be useful for your next designs. Please notice that before using these techniques, you should make sure that they make sense in the context in which you are going to use them. 

#### Simplifying Sign-Ups
ASK FOR A USER NAME AFTER THE USER HAS SIGNED UP 
REQUIRE USERS TO TYPE THEIR PASSWORD ONLY ONCE
AUTO-FILL CITY AND STATE FIELDS BASED ON USER’S ZIP CODE 
COMBAT SPAM BY HIDING A TEXT FIELD WITH JAVASCRIPT, INSTEAD OF USING CAPTCHA 
#### Simplifying Log-Ins 
LOG USERS IN WITHOUT LEAVING THE PAGE
ALLOW USERS TO LOG IN WITH THEIR EMAIL ADDRESS
AUTO-FOCUS THE FIRST TEXT FIELD 
ALLOW USERS TO UNMASK THEIR PASSWORD 
USE A QUESTION MARK ICON FOR THE PASSWORD RECOVERY LINK 

###  Article Quality
Your sign-up and log-in forms shouldn’t make the user’s life difficult. Spending time filling out a form is no one’s idea of a party. These innovative techniques included in this article will make your forms simple and efficient, so that users can sign up and log in quickly and start enjoying your content.

**Comment by WanjaMIKE** [comment]
I think you lack enough key takeaways to write a quality article. This current submission feels somehow shallow. Please suggest another topic. Thanks
