### ISSUE TITLE
End-to-End speech Recognition Guide in Python

### ISSUE THREAD

**Issue by josephotienoowino** [section-engineering-education/engineering-education#5583]
### Topic Suggestion
End-End speech Recognition Guide in Python

#### Proposed title of the article
End-End speech Recognition Guide in Python

#### Proposed article introduction
Speech recognition is the process of enabling computers to identify and respond appropriately to human voices or other sounds. In the tutorial, we will discuss an End-End Speech Recognition Guide in Python. Companies like Amazon uses speech recognition to help their customers in product finding. Even speech recognition allows physically disabled people, the visually impaired, or young children to interact with them, with the added benefit of not requiring a graphical user interface (GUI). By seeing speech recognition everywhere why not be possible in making your system. This tutorial guides show some working principles of speech recognition and the different speech recognition used.
#### Key takeaways 
By the end of this tutorial, the reader will be able to gain skills in:
- Working principle of speech recognition 
- Packages involved in speech recognition
- How the packages are used in speech recognition
- Top projects having text to speech recognition

#### Article quality
The article is unique since more sites only show speech recognition building, they don't show steps or guides towards building speech recognition.
#### References
N/A

### Conclusion
By completing this article, the learner will have basic knowledge in speech recognition, packages involved in speech recognition, the working principle,s and top projects having speech-to-text Recognition.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @josephotienoowino 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
