### ISSUE TITLE
Creating A Shopping Cart API In Java 

### ISSUE THREAD

**Issue by kingsleynwafor54** [section-engineering-education/engineering-education#5585]
### Creating A Shopping Cart API In Java(Spring-boot)

A shopping cart is an object you use to move stuff you purchase in the market or supermarket. Sometimes in a major shopping mall, the cart representation is also known as trolley which enables the cashier to recognize your collection of items that you want to buy. This similarly is what you find in many e-commerce web apps and it is majorly placed by the top right corner of the web page.

In this course, I will run you through how to build a simple shopping cart without a database but with data structures as this shows how and why we are using a database nowadays. Also, this tutorial only focuses on the basic functionality of a shopping cart.

#### Prerequisite
- Full understanding of object-oriented programming in java
- Basic understanding of spring-boot 
- Basic understanding of postman

#### Key Takeaway
- This will help beginners in spring-boot find fitting and will be able to do more projects.
- This will encourage individuals to pick up projects and enable them to see everything as an object.
- This will serve as a road map for more similar and complex projects.
- This will broaden beginners on how to code to interface 
- This will teach beginners how to write unit testing in spring-boot

Conclusion
By the end of this tutorial, the reader would have gotten an insight into how interfaces are very useful to reusable software development, how to write unit testing in spring-boot and how to write your own custom API.

Reference
https://www.baeldung.com/
https://spring.io/guides/gs/spring-boot/

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @kingsleynwafor54 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
