### ISSUE TITLE
How to record audio signal in single-channel microphones, multi-channel microphones and from external sources via audio cable

### ISSUE THREAD

**Issue by peterAdongo** [section-engineering-education/engineering-education#5588]
### Topic Suggestion
How to record audio in single, multi-channel and from external sources via audio cable.

#### Proposed article introduction
An audio signal represents a sound in the form of a signal. Therefore, they can be defined as signals audible to human beings. Single and multi-channel microphones are laptops in-built microphones used to record audio. There are many signal processing-based projects which are very popular among science students. These include speech recognition, voice command for robots, voice-based control of machines and equipment, etc. To implement such projects, we must capture the audio signals first and then take them into Matlab for processing and applying the appropriate algorithm for their analysis.

This article will look at how we can record these signals using single microphones, multi-channel microphones, and from external sources using the audio cable. We will also see how Matlab uses the `analogue input recorder app` for this process. Finally, we will read these files and compare `play` and `sound`.

#### Key takeaways 
- Recording audio using single channel.
- Recording audio using multi-channel.
- Reading, writing and comparing `play` and `sound` of the signals.
- Recording audion from external source via audio cable.
- How to use the matlab app `Analogue input recorder`.

#### Article quality
In this article, we will do deep, that is apart from just using matlab to record you audio, we are using the laptops in-built features. Also we look at how to record from external source using audio cable. Apart from this, we look at how you can use the anlogue input recorder app in matlab.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
seems to be a duplicate issue.
