### ISSUE TITLE
REST API - Examples using the product resource

### ISSUE THREAD

**Issue by Wazecky** [section-engineering-education/engineering-education#5591]
REST API Examples using the product resource

Introduction

REST stands for Representational State Transfer. A REST API also known as RESTful API is an application programming interface that conforms to the constraints of REST architectural style and allows for interaction with RESTful web services. REST API is a way of accessing web services in a simple and flexible way without having any processing. It is preferred to the more robust Simple Object Access Protocol technology because REST uses less bandwidth, simple and flexible making it more suitable for internet usage.

Key takeaways
Different examples:
GET
GET(list)
Update product data
Delete a product data
Delete a product
And many other examples with their results

Article quality
This article will focus on explaining a learner different examples of resource usage for different operations and their results. It will be beginner-friendly to those who are venturing into API related ventures.

References

REST API product resource

**Comment by WanjaMIKE** [comment]
What are you proposing to do and which language will you use? Am not understanding these aspects.

**Comment by Wazecky** [comment]
I'm proposing to expound more on REST API, explain what it's all about
basing my argument on product resource.
I'll be using English language.

**Comment by WanjaMIKE** [comment]
Unfortunately, we already have numerous articles on REST APIs. Feel free to suggest another topic. Thanks
