### ISSUE TITLE
Building Audio File Input in Python flask framework

### ISSUE THREAD

**Issue by Roy-Wanyoike** [section-engineering-education/engineering-education#5594]
### Topic Suggestion
**Building Audio File Input in Python flask framework**

#### Proposed title of article
Building Audio File Input in Python flask framework

#### **Proposed article introduction**
Python has extended and grown drastically to produce the best tools for developers in the work. Recently, they launched flask a very powerful framework which has been well optimized for backend development. This article will be showing how to create a simple audio file which can also transcribe. It requires just basics in python and you're good to go. 

#### Key takeaways 
- Basic Python 
- Installed flask
- Basic web skills preferably, html,css and Javascript
- A code editor installed.
- Using speech recognition module
- Stable internet to install the packages.

#### Article quality
This article will be helping a python learner who is just a novice to be able to learn both front end and backend at the same time. It will also help him to understand how to use GET and POST to get data.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Roy-Wanyoike 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
