### ISSUE TITLE
Implementation of binomial random variables in java

### ISSUE THREAD

**Issue by Ushter21** [section-engineering-education/engineering-education#5597]
#### Proposed title of article
[Languages] Implementation of binomial random variables in java

#### Proposed article introduction
The reader should be familiar with Random Variables. We are going to discuss about binomial random variable which is a discrete random variable that counts the number of times a specific event occurs in the given number of attempts or trials.
There are some requirements that must be met for a variable to be a binomial random variable.

#### Key takeaways 
By the end of this tutorial, the reader should understand:
- What is meant by a binomial random variable
- Conditions that must be met for a variable to be a binomial random variable.
- The various characteristics of a binomial random variable
- How to implement binomial random variable in java

#### Article quality
I will take the reader through all the aspects of binomial random variables an in-depth. This will be a simple and easy walk through this concept for a beginner to understand. I will ensure proper use of language and with practicable examples and screenshot where relevant. Additional information on how to solve binomial variables will be handled. I will also take the reader through understanding whether binomial random variable is a binary variable. Discrete vs continuous variable will be covered.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Based on this search, this topic appears to be over-saturated. We usually focus more on unique topics. Feel free to suggest another area. Thanks

**Comment by WanjaMIKE** [comment]
https://www.google.com/search?q=Implementation+of+binomial+random+variables+in+java&oq=Implementation+of+binomial+random+variables+in+java&aqs=chrome..69i57j69i61.293j0j9&sourceid=chrome&ie=UTF-8
