### ISSUE TITLE
How to  Write a Rust GraphQL Server With MongoDB, Juniper and Actix Web

### ISSUE THREAD

**Issue by Catemacharia** [section-engineering-education/engineering-education#5600]
#### Proposed title of article

How to Write a Rust GraphQL Server With MongoDB, Juniper, and Actix Web

#### Proposed article introduction

GraphQL is an open-source query language. It is intuitive and well-designed for building APIs. GraphQL is built around HTTP to set how you get and receive resources from a server. It gives you a single endpoint that allows you to determine what data you get back based on the query that you send to that endpoint. This gives you a more flexible way to interact with your server as compared with a REST API. A REST API is based on executing different endpoints to get specific data. This will also return extra information that you don't want at the moment. However, with GraphQL API, you only get data that is specified in a GraphQL query. This way, you only make a single request to the server that queries different resources and return the data you need. Instead of sending different endpoints to different resources to return the same data.

This guide aims to create a fully-functional GraphQL server using the Rust programming language.

#### Key takeaways 

- What is a GraphQL API
- Set up a MongoDB database
- Configure a GraphQL server using Rust
- What is the Actix-Web framework
- What is the Juniper framework
- Configure a Rust GraphQL server using Juniper and Actix-Web frameworks

#### Article quality

This guide aims to introduce the Rust programmer to the concept of GraphQL. We will explain this concept and how it works. The build and application stack that has GraphQL, Rust, and MongoDB. The reader will also understand the frameworks and libraries we will use to achieve this.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Catemacharia 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #5600 via #6612
