### ISSUE TITLE
How JSP code gets converted to Servlet code

### ISSUE THREAD

**Issue by Chaun864** [section-engineering-education/engineering-education#5604]
#### Proposed title of article
How JSP code gets converted to Servlet code

#### Proposed article introduction
Our compilers are unable to run JSP pages, as we all know. In this case, a JSP program must be converted into a corresponding Servlet page before it can be executed. 
Although JSP does not contain servlet classes or methods, you can use HTML tags and Java code inside JSP tags to create a JSP page, which will get converted into corresponding Servlet page during compilation. To demonstrate how this process works, we'll use a simple JSP in this article.

#### Key takeaways 
1. Definitions
2. The JSP web page
3. The conversion process
4. The corresponding servlet code
5. Conclusion

#### Article quality
I observed that many queries have been asked about this area, and it has yet to be toggled in both other blocks and the section engineering page.

In this tutorial, I'll show learners how to convert JSP code to servlet code. Furthermore, I will inform them that it is the work of compilers but that we require the understanding behind it. Thank you very much.

#### References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @Chaun864.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
