### ISSUE TITLE
 Resolve the 500 internal server error , NextJs server side api call on deployement.

### ISSUE THREAD

**Issue by unholydisaster** [section-engineering-education/engineering-education#5609]
Topic Suggestion
 Resolve the 500 internal server error , NextJs server side api call on deployement.
Proposed title of article

 Resolve the 500 internal server error , NextJs server side api call on deployment.
Proposed article introduction
IMPORTANT  NOTE:Error messages are here to help us.
After diving into React as a front-end developer, I was excited and I had so Many positive expectations, but all this may change when you start getting all the annoying error messages that React may decide to through at your code and life decides to go hard on you.While I was on my coding tour I bumbed into a NextJs error that got me searching for a solution for weeks.
I am here now with a solution to the 500 internal server error in NextJs server side api call, the most used method in fetching data in NextJs is getServerSideProps and am going to show how to use a package in resolving this error. 
I will take you through the solution with code examples.

Article quality

N/A

**Comment by ahmadmardeni1** [comment]
Please feel free to suggest an alternate topic to explore.
