### ISSUE TITLE
[Machine Learning] How to build a chatbot using Rasa NLU & Rasa Core

### ISSUE THREAD

**Issue by charlesndirutu33** [section-engineering-education/engineering-education#5610]
#### Proposed title of article
[Machine Learning] How to build a chatbot using Rasa NLU & Rasa Core

#### Proposed article introduction
A chatbot is an application of natural language processing that is used to simulate natural human conversation. It enables different users to communicate via the chat interface or by voice. Chatbots offer assistance to many people and businesses by offering directions to customers seeking help. 

 Chatbots are used to interpret the customer's question and give the appropriate responses, this forms a logical dialogue that people can understand and follow. Organizations use chatbots to engage with customers this provides feedback to the business, this helps them to make necessary improvements. Chatbots are very helpful in collecting suggestions and reviews from customers.

In this tutorial, we will use  Rasa NLU & Rasa Core in building our chatbot model. These are Python packages best suited for conversation AI and they use the concept of natural language understanding in building the chatbot.

#### Key takeaways 
1. What is a chatbot?
2. Advantages of using chatbots in an organization.
3. Rasa NLU & Rasa Core.
4. Training the chatbot to understand conversations.
5. Using a chatbot to give responses.

#### Article quality
This tutorial is unique because it builds a chatbot from scratch. We will build a custom chatbot that can be used by businesses to explain the goods and services offered by the organization. 
This will provide a good platform where customers can easily get the necessary assistance in the shortest time possible. The chatbot will enable to give real dialogue. The chatbot will be trained so that it can understand different conversations.  The tutorial will use simple steps and explain them in detail so that anyone can easily follow them.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @charlesndirutu33 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
