### ISSUE TITLE
[Language] Differentiate while(p!=null) and while(p.link!=null) In Linked List

### ISSUE THREAD

**Issue by munyite-megzs** [section-engineering-education/engineering-education#5611]
### Topic Suggestion
Differentiate while(p!=null) and while(p.link!=null) In Linked List

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Some students have a problem understanding the difference between while(p!=null) and while(p.link!=null), so I have written this article with a full explanation. A Linked list is a dynamic data structure that is made up of nodes. Dynamic data structure means we can allocate memory while the program is running.

#### Key takeaways 
- What a Linked List is and its advantages.
-  Traversing and searching a Linked List
- Finding References in a Single Linked List.
- Find the reference to the predecessor of the kth node
- Differentiate while(p!=null) and while(p.link!=null) In Linked List

#### Article quality

My article will have a step-by-step explanation using graphics to relay information. Many articles on this topic haven't given the difference between while(p!=null) and while(p.link!=null) In Linked List which I have seen confusing many of us, students. This article will go ahead and give a comprehensive explanation of that.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, the key takeaways are not enough to complete a quality article. Feel free to suggest another issue. Thanks
