### ISSUE TITLE
How to build a simple currency exchange rate converter API with python and flask

### ISSUE THREAD

**Issue by supazuko** [section-engineering-education/engineering-education#5612]
### Writing sample(s):
https://www.section.io/engineering-education/understanding-react-useeffect/

#### Proposed title of article
How to Build a simple currency exchange rate converter API with Python and Flask

#### Proposed article introduction
This article is a simple to introduction to python and the flask framework and how to consume APIs.

#### Key takeaways
By the end of this tutorial, the reader will be able to understand:
* What are APIs and what are the benefits.
* Benefits of using flask framework.
* How to consume API in flask and process response.
* Understanding HTTP methods

#### Prerequisites
To follow through with this article, the reader should have:
* Python 3.0 or newer installed on your machine.
* A working understanding of Python.
* Basic knowledge of Flask.
* A suitable text editor of your choice.

#### References
https://flask.palletsprojects.com/en/2.0.x/api/
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xxiii-application-programming-interfaces-apis
https://www.youtube.com/watch?v=Z1RJmh_OqeA

#### Conclusion
With flask, it becomes quite easy and straightforward to consume and manipulate APIs in your program and then process responses, all in one page. Building this currency exchange rate converter is a simple and efficient way to understand RESTful API and how to use HTTP methods and status codes.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @supazuko 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
