### ISSUE TITLE
Comparing AWS Shared Responsibility Models for Different Products 

### ISSUE THREAD

**Issue by BashiirIsla** [section-engineering-education/engineering-education#5615]
#### Proposed title of article
Comparing AWS Shared Responsibility Models for Different Products 

#### Proposed article introduction
Organizations are moving their workloads from on-premise to the cloud.  As a result, they benefit from enhanced user performance, increased business efficiency, and a shorter time-to-market. Amazon Web Services (AWS) is one such cloud platform where organizations can deploy their workloads. 

However, one area of concern for these organizations as they capitalize on this strategy is the security of their AWS environment.  You need to understand the security of the AWS environment to reap the benefits that it comes with. Ideally, understanding the AWS shared responsibility model is a significant starting point to improving the security of the organization's ASW environment. 

This article will discuss what AWS shared responsibility model is and why it is important to businesses. We'll also compare AWS shared responsibility models for different products and discuss the best practices for working with these models.

#### Key takeaways 

1. What are the AWS Shared Responsibility Models?
2. Why AWS Shared Responsibility Models Matter?
3. Comparing AWS Shared Responsibility Models for different products 
- Amazon EC2
- AWS Lambda
- Elastic Beanstalk
- VMWare Cloud on AWS
- Amazon EKS
- Amazon EC2

4. Best practices for working with AWS Shared Responsibility Models

#### Article quality
This article explains beyond what is available in the official documentation by comparing different AWS Shared Responsibility Model products, discussing their strengths and weaknesses. it also shares the best practices for working with AWS Shared Responsibility Models - something which is not available in other blogs.

**Comment by ahmadmardeni1** [comment]
This is out of our preferred topics area - We are looking for programmer-centric concepts explained in fun and intuitive ways.
Please feel free to suggest an alternate topic to explore. 🚀
