### ISSUE TITLE
Why DevSecOps Need Security as Code

### ISSUE THREAD

**Issue by nellyat** [section-engineering-education/engineering-education#5618]
#### Proposed title of article
Why DevSecOps Need Security as Code

#### Proposed article introduction
DevOps was introduced to make the software development life cycle shorter. While software development organizations breathed a sigh of relief with DevOps making the process smoother, there was another challenge. Implementing security in the software became difficult. And to solve this issue, DevSecOps was introduced.

Security as code is key to achieving DevSecOps. It requires that security be defined at the beginning of a project and codified for repeated and consistent use. In this way, it gives developers a self-service option for ensuring their code is secure.

#### Key takeaways 

1. What is security as code and DevSecOps?
2. Continuous delivery as a foundation of security as code.
3. How security as code enables development teams to address security.
4. How security as code addresses risks in development and runtime.

**Comment by Kayere** [comment]
Sounds like a helpful topic @nellyat - Approved. Please make sure your article is unique and adds value to what is available online.

**Comment by WanjaMIKE** [comment]
Closed #5618 via #5773
