### ISSUE TITLE
[Language] How To Work With Static Data Members in  C++

### ISSUE THREAD

**Issue by Samrosh** [section-engineering-education/engineering-education#5619]
#### Proposed title of article
How To Work With Static Data Members in C++

#### Proposed article introduction
C++ is a programming language that allows programmers to have significant control over system resources and memory. It's most commonly utilized to create high-performance apps. Static is a C++ mechanism for creating variables, objects, and functions that have a dedicated space for the duration of the program. The static keyword is used with variables, functions, and data members, and it prevents them from being changed again. The compiler only needs to initialize the static members once, and it keeps the variable until the program is finished.
The static variables are allowed to be defined inside the function or outside of it. Zero is the default value of the static variables. In this article, we'll discuss the different Syntax of C++ such as syntax of static variables and syntax of static functions. Static members of class which include static objects of class and static function in a class will be covered using relevant examples and codes.

#### Key takeaways 
By the end of this article the reader will have understood how to use:
- Static variable in a function
- Static variable in the class
- Static objects of class
- Static function in a class

#### Article quality
I'll go through all of the static member variables and functions of C++ in details. I'll also include examples of working with each variable and function with accurate outputs and descriptions. These concepts will be discussed in depth and in an engaging manner that is suitable for beginners and relevant to high-end programmers. The  article will also be written in an easy to understand manner to raise awareness for this open source library. The article will be unique and entertaining. 

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appears to be well-covered in official documentation and blog sites. Feel free to suggest another topic. Thanks
