### ISSUE TITLE
Cryptocurrency Hashing Algorithms Explained with Examples 

### ISSUE THREAD

**Issue by Snzovi** [section-engineering-education/engineering-education#5621]
#### Proposed title of article
Cryptocurrency Hashing Algorithms Explained with Examples 
#### Proposed article introduction
The data contained in Bitcoin’s blockchain is stored across numerous nodes all across the world while the owners of these nodes have free access to this data. If you can control some part of the network, what a big temptation it must be to edit the transactional history in your own favor. 

However, this is not something we can observe in the case of Bitcoin. We are totally sure of the network’s protection and that such a thing can never come to reality. All this is possible thanks to the hashing algorithm that is the backbone of security in the world of cryptocurrencies.
#### Key takeaways 

- What is a hash function 
- How does hash function relate to cryptocurrency 
- How does hashing secure Bitcoin?
- Examples of cryptocurrency hashing algorithms

#### Article quality
This article will explain hashing algorithms in cryptocurrency in detail. It will provide examples to make the article more unique and easy to understand. 

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Snzovi 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
