### ISSUE TITLE
Email Spam Detection using Python and Machine Learning

### ISSUE THREAD

**Issue by amchilos01** [section-engineering-education/engineering-education#5622]
### Topic Suggestion
Email Spam Detection using Python and Machine Learning.

#### Proposed article introduction

Technically, a spam can be defined as an electronic text that is attributed with two conditions: if the receiver’s individual identification and context are not pertinent since the text is equally related to several other prospective receivers, and if the receiver has not bestowed valid willing, explicit and flexible permission for the message transmission. Spam, as incorporated in electronic mail, means unsolicited bulk email. The term unsolicited implies that the receiver has not bestowed valid consent for conveyance of the message. On the other hand, the term bulk implies that the sent information is encompassed within a large message collection. These collections have substantively similar content. For a message to be termed as spam, it has to be both unsolicited and bulk.

Spam electronic mails are mainly detected using spam filters. These filters identify the unsolicited and irrelevant mails, consequently preventing them from entering the main inboxes. Spam cleaners inspect trials for receiver deception and differentiate addresses to the blocked lists of familiar spammers to remove those that match by default. The internet service providers (ISPs) incorporate spam filters to ascertain they are not dispensing unsolicited messages. Medium-sized enterprises also ensure they employ spam cleaners to safeguard their workers and network grids. Spam filtering is essential as it prevents the destruction of documents by infected mails or phishing attempts.

Email spam detection can also be performed using python and machine learning. Python is a top-level, versatile programming language employed in various projects due to its immense coding benefits. The spam detection process using python employs a sequence of procedures such as loading of the dependencies, data, visualization and train-assessment splitting. Machine learning basically implies feeding the system with examples of unsolicited and permitted texts, and letting it discover the necessary trends for identification of both categories. In this essay, a comprehensive analysis of how python and machine learning is employed in spam data detection is performed. 

#### Key takeaways 

Upon completion of this article, the reader should be able to:
•	Define spam and email spam detection
•	Describe some spam filtering techniques
•	Describe the spam detection process using python and machine learning

#### References

n/a

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @amchilos01 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
