### ISSUE TITLE
How to make a switch-case statement in Python

### ISSUE THREAD

**Issue by Nicholas-Obare** [section-engineering-education/engineering-education#5628]
#### Proposed title of  the article
How to make a switch-case statement in Python

#### Proposed article introduction
A  switch statement enables a parameter to be compared against a set of attributes for equality. The switch statement is used in many programming languages, including C++, Visual Basic, Java, Ada, and others. It is a powerful programming tool that lets you change the flow of your program based on the value of a variable or expression. In this article, we will look at how to implement switch-case statements in python through various methods and demonstrate with program examples e.g using if-elf-else, dictionaries and classes. We will also look  at the advantages of implementing switch cases 
#### Key takeaways 
1. What is a switch case statement
2. Example of a switch statement
3. advantages of using a switch case statement.
4. Methods to implement switch-case in python
5.  Advantages of implementing switch-case in python.
#### Article quality
This article is unique since it covers a unique topic. Switch case statement does not exist in python but in this article, we will look at ways on how to implement it using various methods.
#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, the key takeaways are not enough to complete a quality article. Feel free to suggest another issue. Thanks
