### ISSUE TITLE
[Languages] How to split a monolithic architecture into micro-frontends

### ISSUE THREAD

**Issue by ephnjor2021** [section-engineering-education/engineering-education#5629]
#### Proposed title of article
How to split a monolithic architecture into micro-frontends

#### Proposed article introduction
There exists several open-source and third-party libraries that reduce the development effort while keeping the complexity minimal. But, in reality, applications tend to grow in complexity over time hence demanding higher scalability and responsiveness.

A monolithic application tends to contain a lot of components and have complex logic. It is also hard to maintain and scale the application product. Integrating new developers is also challenging.

A better approach would be to split the application logic into smaller pieces which is easier to maintain and also analyze its codebase. Also, it is easy to assign different components to different teams which makes them independent.

In the proposed topic, we will look into details about micro-frontends and their benefits over monolith architectures. We will also implement an example application to demonstrate the breaking down of monolithic applications to a micro-frontend.

#### Key takeaways 
At the end of the article, a learner will be able to understand:
- the concept of monolith architecture and micro-frontend architecture
- the features and advantages of micro-frontends
- the technical demonstration of how to create a micro-frontend in Angular

#### Article quality
The guide focuses more on splitting a monolith application into micro-frontends using a practical example for the learner to grasp firmly the concepts laid down. Unlike the other articles online which focus more on building the micro-frontends.

#### References
N/A

**Comment by Kayere** [comment]
Sounds like a great topic @ephnjor2021 - Approved. Please make sure your article is unique and adds value to what is available online.

**Comment by ephnjor2021** [comment]
@Kayere Kindly do not close this topic as I will be uploading the article soon. Thank you
cc @ahmadmardeni1 @hectorkambow
