### ISSUE TITLE
How to Remotely Wipe All Data From Lost or Stolen Computer with Windows 10/11

### ISSUE THREAD

**Issue by Wazecky** [section-engineering-education/engineering-education#5631]
**Proposed title of the article**

How To Remotely Wipe All Data From Lost or Stolen Computer With Window 10/11

**Proposed article introduction**

It is very necessary to safeguard our devices, but what if your laptop is lost or stolen? In such a scenario, if proper safeguards aren’t in place, it can bring you many troubles. Your important files such as personal secrets, financial information, and many more will be in danger. It’s therefore best to set up remote wiping on a device to be on the safe side. In this article, you will learn more on how you can wipe your data.

**Key take aways**

1. After reading this article, one will be able to know more about Prey software, a thirty party anti-theft recovery software and how to use it.
2. For every computer user, after this article one will have adequate knowledge on enhancing security of their devices.

**Article quality**

Many tutorials have only explained how one can safeguard his or her device to avoid accessed by other parties, there are only few tutorials explaining on how to wipe your data in case of lost or theft of device. In this tutorial, I will introduce a software called Prey which greatly and easily help in wiping data. I will also explain steps to follow in wiping your data from other device.

**Reference**

Techviral

**Comment by WanjaMIKE** [comment]
This does not appear to be a software-centric topic. Please submit another issue. Thanks
