### ISSUE TITLE
[Languages]How to Build a Covid-19 Vaccine statistics Application Using Covid-19 World Vaccination API 

### ISSUE THREAD

**Issue by codeInn001** [section-engineering-education/engineering-education#5634]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
How to Build a Covid-19 Vaccine statistics Application Using Covid-19 World Vaccination API 

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
How to Build a Covid-19 Vaccine statistics Application Using Covid-19 World Vaccination API 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Since 2019 the world has been battling with covid-19. As of then, there was no vaccination, and this led to a total lockdown. With the invention of the vaccine, it is now appropriate for everyone to get vaccinated. Having a web app that shows the statistics of those vaccinated will help towards the goal of getting everyone vaccinated.

The app will be built using the popular react framework, Next.js, and the Covid-19 World Vaccination API

#### Key takeaways 
-Readers will learn how to fetch data from Covid-!9 World Vaccination API using Axios.
-Readers will learn how to use Next.js `getSeverSideProps`.
-Readers will learn how to use RapidApI Hub.

#### Article quality
In this article, we will build a covid-19 vaccine statistic app that will display numbers of people vaccinated based on the country searched for. We will be using Next.js to build our web app and also we will explore some Next.js features.

#### References
https://rapidapi.com/jamesrabels@gmail.com/api/covid-19-world-vaccination-data/
https://Nextjs.org

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Fetching data from an API in `React.js` and `Next.js` is already covered in numerous articles. Feel free to suggest another topic. Thanks
