### ISSUE TITLE
[LANGUAGES] A Christmas Wisher Using HTML,CSS and JS

### ISSUE THREAD

**Issue by Su-sid** [section-engineering-education/engineering-education#5638]
### Topic Suggestion
A Christmas Wisher Using HTML,CSS and JS

### Writing sample(s): 

[Stateful vs Stateless Architectures](https://www.section.io/engineering-education/stateful-vs-stateless-architectures/)
[Network Troubleshooting using Traceroute](https://www.section.io/engineering-education/network-troubleshooting-using-traceroute/)

#### Proposed title of article
A Christmas Wisher Using HTML,CSS and JS

#### Proposed article introduction

We are in the season of giving and spreading the joy and love. To spread the love to all of you, the article teaches how you can create a fantastic webpage that displays random wishes when one of your users visits the site.

#### Key takeaways 
After reading the article you will be able to:
- Develop your own Christmas wishing website.
- Be able to use the java script functions to randomly select string variables.
- Gain insight on how to design an attractive user interface.

#### Article quality
There are no other blogs or websites that include such a unique idea.

#### References
N/A

**Comment by WanjaMIKE** [comment]
I believe your key takeaways are already covered in numerous articles and projects. Feel free to submit another topic. Thanks
