### ISSUE TITLE
How to use symbolic math's toolbox in Matlab to analyze the Fourier series.

### ISSUE THREAD

**Issue by linetachieng** [section-engineering-education/engineering-education#5639]
### Topic suggestion
How to use symbolic math's toolbox in Matlab to analyze the Fourier series.

#### Introduction
Symbolic Math Toolbox provides functions for solving, plotting, and manipulating symbolic math equations. You can create, run, and share symbolic math code. The toolbox provides functions in common mathematical areas such as calculus, linear algebra, algebraic and differential equations, equation simplification, and equation manipulation. We want to see how this toolbox can be used to solve fourier series.
In this tutorial, the Fourier series is implemented and simulated using Symbolic Math's Toolbox of MATLAB. Both the forms of the Fourier series i.e. Trigonometric and Exponential are implemented. The proposed programs are versatile and have the capability to receive any function of t. The program gives plots of harmonics, original function and approximated function, Magnitude spectrum and Phase spectrum.

#### Key takeaways 
- Trigonometric Fourier Series.
- Exponential Fourier Series.
- MATLAB Code to implement Trigonometric Fourier Series.
- MATLAB Code to implement Exponential Fourier Series.

#### Article quality
Using this toolbox maybe so tricky for a student and this article is to explain clearly and make it easy for the student to solve their problems using this toolbox.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @
