### ISSUE TITLE
Click-Through Rate Prediction with Machine Learning

### ISSUE THREAD

**Issue by Wazecky** [section-engineering-education/engineering-education#5643]
Proposed article title

**Click-Through Rate Prediction Model with Python**

Proposed article introduction

In any advertising agency, it is needful to predict the most profitable users who are very likely to respond to targeted advertisements. In this article, I’ll take you through how to train a model for the task of click-through rate prediction with Machine Learning using Python. 
By predicting the click-through rate, an advertising company select the most potential visitors who are most likely to respond to the ads, analyzing their browsing history and showing the most relevant ads based on the interest of the user. In thid article you will get to learn steps to follow to do that.

Key take aways

1. Creation of a model.
2. Deployment of an imported dataset for this task.

Article quality.

Since not all business men and women are computer experts, in this article, I will explain my steps in such a way that even a computer novice can understand. I'll will also introduce a dataset which will easen our task.

Reference
Techviral.com

**Comment by Kayere** [comment]
Hello @Wazecky - Your introduction paragraph seems to be paraphrased from [this article](https://thecleverprogrammer.com/2021/01/24/click-through-rate-prediction-with-machine-learning/). How is your article going to be different?

**Comment by Wazecky** [comment]
I'll make my introduction to be more appealing, explained with some base
and create more avidity for the reader.

**Comment by Wazecky** [comment]
My article will aslo entail a clear view of what a Click Through Rate
Prediction is, its applications, priorly show and explain abit on the steps
and finalize by pratically expounding on the steps using python.

**Comment by OkothAlvan** [comment]
Hello @Kayere.
I would want to know your final feedback.

**Comment by Wazecky** [comment]
Hello @Kayere, I would wish to know your feedback.
Thank you

**Comment by hectorkambow** [comment]
@section-engineering-education/content-moderator-team  

Does this issue require any attention 

 cc @Kayere  
 
 cc @Wazecky  
 
 Otherwise we can close it

**Comment by Wazecky** [comment]
I was asked a question by @Kayere, I answered his question but till then I
haven't been given a go ahead.

**Comment by Kayere** [comment]
I think it is okay - Please proceed @Wazecky.

**Comment by Wazecky** [comment]
Fine.
