### ISSUE TITLE
(Python) Pathlib vs OS Modules for File and Directory System Operation utilizing Comparable Scenarios

### ISSUE THREAD

**Issue by akenz1901** [section-engineering-education/engineering-education#5644]
## Pathlib vs OS Modules for File and Directory System Operation utilizing Comparable Scenarios

In this article, we will run through different viable contexts to discover an agreeable decision of utilizing either Pathlib or OS for file system operation. Also, I will utilize this article to perform distinguished tasks for significant reference these tasks are not restricted to writing and reading a file, describing a document information, renaming files, creating directories and so on

The thought behind this article is to clear the examining choice knowing where every one of them fit in when working with File System Operation neither censuring a specific module, additionally to develop a quick consulting reference that is based on File System Operation.

### Key Takeaway
- It will help beginners in python or data analytics to confidently propose the right file system operation module.
- It will provide a simple road map for a quick guide at whatever point individuals intend to work with files.
- It will theoretically enhance beginners' comprehension of file system operation.
- It will eliminate the manual way of working with file system operations for individuals while working on a project.
- It will teach beginners how to reference an object in python, and this is pattern is called composition.

### Conclusion
At the end of this article I believe individuals would have understood the difference between Pathlib and OS, also I believe individuals would have been able to know where each module fit in and individuals would have been more familiar with File System Operation using two different types of File System Operation module.

Reference
[OS documentation](https://docs.python.org/3/library/os.html#querying-the-size-of-a-terminal)
[Pathib documentation](https://docs.python.org//pathlib.html)

**Comment by Kayere** [comment]
Good topic @akenz1901 - Approved. Please make sure your article is unique and adds value to what is available online.

**Comment by akenz1901** [comment]
@Kayere Thanks so much for the approval, Trust me I will bring the great quality out of this.
