### ISSUE TITLE
How to Build a Todo App with Svelte and its Material UI

### ISSUE THREAD

**Issue by Nomzy-kush** [section-engineering-education/engineering-education#5645]
### Writing sample(s): 
https://www.section.io/engineering-education/how-to-build-a-currency-converter-with-react-and-its-material-ui/

https://blog.logrocket.com/whats-new-webkit-safari-15/

https://www.section.io/engineering-education/how-to-build-a-quiz-app-with-vanilla-javascript-and-tailwind-css/

#### Proposed title of the article
How to Build a Todo App with Svelte and its Material UI

#### Proposed article introduction
Svelte is a relatively new component-based JavaScript framework that interacts with the DOM by collecting code and converting them to pure JavaScript. This article will show you how to create a Todo app with Svelte and style your components with Svelte’s Material UI.

#### Key takeaways 
1. Readers will get the basis of building a Todo App with Svelte and its Material UI.
2. Readers will learn how to import Svelte’s Material UI components and use them to style their Svelte application UI.
3. Readers will learn how to perform CRUD operations with Rest API in their Svelte project     

#### Article quality
This article is unique because readers will get in-depth information on Svelte and how to use its Material UI to style their applications. Since Svelte is a relatively new framework, this article will be very much sort after.  

#### References
N/A

**Comment by WanjaMIKE** [comment]
The basic aspects of material-ui have already been covered in numerous articles such as https://www.section.io/engineering-education/search/?q=Material-UI. Creating a todo application with svelte is also covered here https://github.com/section-engineering-education/engineering-education/issues/5098. Feel free to suggest another topic.
