### ISSUE TITLE
[Security]Understanding Sensitive data exposure  and how to prevent it

### ISSUE THREAD

**Issue by Dyrstiu** [section-engineering-education/engineering-education#5647]
.

### Topic Suggestion
Understanding Sensitive data exposure  and how to prevent it

### Writing sample(s): 
https://www.section.io/engineering-education/getting-started-with-visual-basic-net/

#### Proposed title of article
Understanding Sensitive data exposure  and how to prevent it. 

#### Proposed article introduction
Sensitive data exposure is among the OWASP Top 10 list released this year (2021). It comes in at Number 2. According to data by OWASP, the incidence rate is medium (OWASP,2021). Sensitive data exposures are most common in Web applications that are not strict on their data handling procedures. These procedures include encoding data while in transport, storing only necessary data, etc. When we ignore those procedures, the applications end up exposing the data to the public.

#### Key takeaways 
- What is sensitive data 
- Overview of Sensitive data exposure
- Testing Sensitive data exposure
- How to prevent Sensitive data exposure

#### Article quality
The article will be beginner friendly and will also focus on highlighting the difference between Sensitive data exposure and data breaches which has been is lacking in other blogs.  

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by ahmadmardeni1** [comment]
This is out of our preferred topics area - Please feel free to suggest an alternate topic to explore. 🚀

**Comment by Dyrstiu** [comment]
@ahmadmardeni1 hello 
Can you kindly share the Preferred Topic area.
My assumption was security was among them. thank you

**Comment by Dyrstiu** [comment]
@ahmadmardeni1
