### ISSUE TITLE
How to Build a Tic-Tac-Toe game with Vanilla JavaScript and Materialize.

### ISSUE THREAD

**Issue by Nomzy-kush** [section-engineering-education/engineering-education#5650]
### Writing sample(s): 
https://blog.logrocket.com/svelte-material-ui-advanced-material-design-components/

https://www.section.io/engineering-education/how-to-build-a-quiz-app-with-vanilla-javascript-and-tailwind-css/

https://www.section.io/engineering-education/how-to-build-a-currency-converter-with-react-and-its-material-ui/

#### Proposed title of the article
How to Build a Tic-Tac-Toe game with Vanilla JavaScript and Materialize.

#### Proposed article introduction
A Tic-Tac-Toe game involves two players trying to score a straight three with their respective letters while still trying to cancel each other out. This tutorial will take a deep dive into creating a Tic-Tac-Toe game with just Vanilla JavaScript and styling the application’s UI with Materialize. We will use ES6 classes to implement the game’s logic.

#### Key takeaways 
1. Readers will learn how to design the game logic for a regular Tic-Tac-Toe game. 
2. Readers will learn all about Materialize and how to use its in-built classes to style any web application.
3. Readers will learn how to use ES6 classes to validate player moves in the game and create listeners who have a call-to-action towards certain situations.     

#### Article quality
This article is unique simply because it will be very interactive and fun for the reader to follow through. CSS's Materialize will also handle the app's UI.  

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Nomzy-kush 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
