### ISSUE TITLE
Deploying Static Website on Apache2 Linux Server

### ISSUE THREAD

**Issue by Charity10** [section-engineering-education/engineering-education#5652]
### Introduction
Linux is an open-source operating system with many distributions and flavors. Apache2 is a Linux based web server software that can be  used to serve applications. Every website application shall be hosted on a particular server which allows request-response cycle from the client side.  In this tutorial, readers would have knowledge of deploying static site on Linux OS server based.

### Prerequisite
The learner is expected to have basics of the following;
- Linux OS Experience
- Familiarity with software application 

### Key takeaways
At the end of this tutorial, learners would have known the following;
- Overview of web servers
- Introduction to Linux/Apache2 server
- How to interact with Linux distro terminal
- Lastly, how to deploy static site on Apache2 server.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Charity10 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
