### ISSUE TITLE
Internationalization of servlets

### ISSUE THREAD

**Issue by swambui1** [section-engineering-education/engineering-education#5653]
#### Topic Suggestion
Internationalization of servlets.

#### Proposed title of article
Internationalization of servlets.
#### Proposed article introduction
Internationalization, is the method involved in making page accessible in various languages.
Web applications should have the option to adjust to dialects and configurations of the clients, with the fast advancement of web and remarkable development in the user base. This implies that web pages ought to be modified for customers, in light of their languages.
Internationalization drives the servlets to rear the page content as indicated by customer languages.

#### Key takeaways
- Utilizing Resource package.
   - get bundle(String baseName, Locale locale)
   - get bundle (String baseName, Locale locale, Class loader loader)
    - get bundle (String key)
    - get bundle (String BaseName)
    - getStringArray(String key)
    - setParent(ResourceBundle parent)
- Dates formatting
     - Customizing formats.
     - Using predefined formats.
     - getDateInstance()
     - getDateTimeInstance()
     - getTimeInstance()
     - parse()
#### Article quality
In this article am going to take user through internationalization of servlets.
I will use a beginner friendly language, something that has not been done on the published articles, which are complex to understand. I hope this article will add great value to the engineering community.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @swambui1 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
