### ISSUE TITLE
Text to Speech in C#

### ISSUE THREAD

**Issue by mosesmwangi442** [section-engineering-education/engineering-education#5654]
### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Text to Speech in C#

#### Proposed article introduction
Using Text to Speech in.NET is a simple, and you can get all of the features you need by adding just one reference to your project. In this article, I will go through how to make a basic Windows Forms application that allows you to write in some text, define some settings for it, and then have the computer say it back to you.

#### Key takeaways 
1. Setting up the project
2. Use of `Speech.Synthesis` namespace

#### Article quality
I read various articles on how to utilize Text to Speech, but when I wanted to learn how to do it , I noticed there were few simply understood publications on the subject.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
