### ISSUE TITLE
Drawing and moving a cycle in C++ computer graphics. 

### ISSUE THREAD

**Issue by mose-254** [section-engineering-education/engineering-education#5657]
Civil engineers need the knowledge of computer graphics to come up with an overview of the outcome of their development. Therefore, if the issues manage to go through, I am sure it must be of great help to the civil engineering family. In this tutorial, I will use Turbo as my IDE and C++ as the base language.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic - Always use the template provided by us. 
We lean towards content that offers an original viewpoint/approach around programming-centric topics. 
Please go through our docs then feel free to suggest a new topic. @mose-254 
Also, do not change the labels.
