### ISSUE TITLE
[Security] Future Vulnerabilities of Biometrics

### ISSUE THREAD

**Issue by augustinemagero** [section-engineering-education/engineering-education#5659]
### Topic Suggestion
Future Vulnerabilities of Biometrics

#### Proposed article introduction
Biometric concept uses combination of algorithm and pseudocode which is generated by automated systems to give identity based on biological and behavioral features. These biological technologies involves fingerprint, voice-recognition, face recognition and retina scanner. The biometric technologies are stored in a specific file (like the database), which is later used to match the identity of the owner. Incase hackers get access to these file, they can easily extract information within these file to match the identity of the owner without there consent, which is insecure and makes data to be vulnerable, hence compromises the confidentiality integrity and availability of information. 
#### Key takeaways 
1. biometrics
2. Types of biometrics 
3. Storage of biometrics
4. Vulnerabilities

#### Article quality
The concept will be theoretical with evidence to proof the whole idea.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
We lean towards content that offers an original viewpoint/approach around programming-centric topics.

Please feel free to suggest an alternate topic to explore. 🚀
