### ISSUE TITLE
How to set up Prisma Client Server Schema that uses MongoDB as the database

### ISSUE THREAD

**Issue by Rose-stack** [section-engineering-education/engineering-education#5660]
### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

https://www.section.io/engineering-education/authors/rose-waitherero/

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

How to set up Prisma Client Server Schema that uses MongoDB as the database

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Prisma is an ORM that allows you to write type-safe database schemas. Prisma will enable you to write type-safe database schemas. When setting a database, everything needs to be well set to define what that database will look like. In this case, Prisma abstracts you from writing database queries. Thus you have to make sure you write safe database access schemas.

Prisma supports databases structures such as SQL and NoSQL. This allows you to create an ORM schema for various structured database data. This guide teaches how to set up a Prisma Client server with MongoDB and use it to create an API.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- Set MongoDB Atlas cloud
- Data modeling using Prisma for a MongoDB database
- Setting up a MongoDB Prisma client
- Connect MongoDB to Prisma client
- Create a MongoDB Prisma REST API 

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

SQL and NoSQL have different data structures. This guide will use Prisma as an ORM to generate schemes for a MongoDB JSON document. The reader will learn how to structure schemas for a MongoDB database. The reader will also be able to connect this prima schema to a MongoDB and create a server that leverages the advantages of running Prisma with MongoDB

Most existing tutorials only have the MongoDB-Prisma connector. This tutorial will still have this as a heading but still, go ahead and create a RESTFUL API that will show the reader how to use this MongoDB-Prisma connector in a typical project (edited) 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Thank you for submitting your topic @Rose-stack.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.

**Comment by Kayere** [comment]
Approved @Rose-stack - Please make sure your article is unique and adds value to what is available online.
