### ISSUE TITLE
How to build a web crawler with Java

### ISSUE THREAD

**Issue by olu-damilare** [section-engineering-education/engineering-education#5668]
#### Introduction paragraph (2-3 paragraphs):
A web crawler is a bot or an automated script designed to traverse or explore the world wide web in a specific manner.

This tutorial will guide readers on how to inspect the HTML code base of a web page using the "view-source" mechanism, we'll explore the real-life use cases and application of a web crawler, we'll have a basic understanding of the breadth-first search algorithm of a Graph data structure, as well as the challenges involved when building a web crawler. We'll also build a web crawler that traverses the embedded URL's on a web page. The web crawler we shall build will demonstrate the theoretical knowledge I'll be providing in this tutorial.

#### Key takeaways:
At the end of the article, the reader should be able to:

* Have a thorough knowledge of the uses cases of a web crawler
*  Build a web crawler that suits a broad range of use cases
*  Obtain additional knowledge of the Graph data structure and the bread-first search algorithm.
* Understand the challenges involved with building a web crawler.

#### Article quality
This article will not only focus on the concept of web crawling but by extension, will explore the engineering and data structure involved in building the script. Before pitching this topic, I studied other articles that have been published on this topic. I noticed that there aren't sufficient contents that have been published on this topic, and even those published, all approached the topic from a complex perspective, with some of them applying Java API's that are not beginner-friendly such as database integration, Java Document API and so on. 

This article will be as beginner-friendly as possible and will approach the topic in a way that is applicable in any kind of system. I aim to take it from the granular level of the data structures involved in building a web crawler, extend it to cover the challenges of building a web crawler and ensure that it is understood by Software Engineers of varying levels of expertise.

**Comment by Kayere** [comment]
Hello @olu-damilare - Please fill in the article quality section which explains how your topic is unique and should be considered.

**Comment by olu-damilare** [comment]
Hello @Kayere, this has been updated.

**Comment by Kayere** [comment]
Approved.
