### ISSUE TITLE
[Machine Learning] Building and Deploying a Language Detection System using Flask

### ISSUE THREAD

**Issue by FREDERICO23** [section-engineering-education/engineering-education#5669]
### Topic Suggestion
Building and Deploying a Language Detection System using Flask

### Writing sample(s): 
N/A

#### Proposed title of article
Building and Deploying a Language Detection System using Flask

#### Proposed article introduction

Natural language processing(NLP) is a subfield of linguistics and artificial intelligence concerned with the interactions between computers and human language, i.e programming computers to process and analyze large amounts of natural language data.
With companies like Google applying NLP into their products like language detection in Chrome browser, it is a real-world project that will not only build your understanding of NLP but also your portfolio.

Flask is an easy-to-use Python micro web framework that does not require particular tools or libraries. 

In this tutorial, we will be using [Language detection](https://www.kaggle.com/basilb2s/language-detection) dataset from Kaggle to build a language detection system and deploy it on a flask app.

#### Key takeaways 

At the end of this article, the reader should be able to:
* Building ML models
* Understanding and implementing Natural Language Processing
* Understanding and using Flask to deploy ML models

#### Article quality
This is an in-depth article that covers the topic of NLP and deployment on Flask which provides not only knowledge but hands-on skills.

#### References
N/A

**Comment by Kayere** [comment]
Good topic @FREDERICO23 - Approved. Please make sure your article is unique and adds value to what is available online.
