### ISSUE TITLE
[Language]Getting started with nagivation between views in Vuejs

### ISSUE THREAD

**Issue by jaredphelix** [section-engineering-education/engineering-education#5671]
### Topic Suggestion
Enter topic suggestion here...

### Writing sample(s): 
https://www.section.io/engineering-education/authors/jared-phelix/

#### Proposed title of article
[Language]Getting started with nagivation between views in Vuejs

#### Proposed article introduction
Vue is already a great JavaScript library that allows you to create some really cool, dynamic, front-end applications. Vue is also great for single-page applications (SPA). SPAs work a little differently than your standard backend web application built in something like PHP. Instead of making requests to different routes on the backend and getting a fully rendered page as a response, a SPA does all the page rendering on the front-end and only sends requests to the server when new data is needed or needs to be refreshed or saved.

In this tutorial, we’ll set up a simple SPA that will show some information about popular cryptocurrencies. We’ll call it “Crypto Info”. It will have a few pages and link those pages using vue-router. You should already be familiar with Vue as well as creating and using Vue components. Having experience with .vue files is helpful but not required.

#### Key takeaways 
1. Vue installation and getting started
2. Navigation configurations using ib built Vue packages.
3. Using the parameters inside the routers

**Comment by WanjaMIKE** [comment]
Kindly, we only accept one topic at a time at the moment. Thanks
