### ISSUE TITLE
[Language] Getting started with  search techniques in ES2015 arrays

### ISSUE THREAD

**Issue by jaredphelix** [section-engineering-education/engineering-education#5672]
### Writing sample(s): 
https://www.section.io/engineering-education/authors/jared-phelix/
#### Proposed title of article
[Language] Getting started with  search techniques in ES2015 arrays
#### Proposed article introduction
In JavaScript, you will often be working with data that is stored in Arrays. A common task will be searching the array to find if it contains a value (or values) that satisfies certain search criteria. Depending on the task at hand, you may be interested in a boolean value for confirmation, an index for the position of the value in the array, or a separate array containing all the search results.

Prior to ECMAScript 6, you probably would have used a for loop to iterate through all the items in the array and perform operations on each item. Now there are several built-in utility methods that solve some of the common tasks for searching for values in an array.

In this article, you will learn about Array.includes(), Array.indexOf, Array.find(), and Array.filter.

#### Key takeaways 
1.Using includes()
2.Using indexOf()
3.Using find()
4.Using filter()

**Comment by WanjaMIKE** [comment]
Kindly, we only accept one topic at a time at the moment. Thanks

**Comment by jaredphelix** [comment]
I'm ready to work on this! Thank you
