### ISSUE TITLE
[Language]Getting started with decision making in PHP 8

### ISSUE THREAD

**Issue by jaredphelix** [section-engineering-education/engineering-education#5673]
#### Proposed title of article
[Language]Getting started with decision making in PHP
#### Proposed article introduction
Decisions are an integral part of life. From the mundane decisions about what to wear, to the life-altering decisions of jobs and family. So too in development. For a program to do anything useful, it must be able to respond to some sort of input. When a person clicks the contact button on a website, they expect to be taken to a contact page. If nothing happens, or they are taken to the wrong page, the user may choose to stop using that website or company completely.

Decisions written in code are formed using conditionals: “If x, then y.” Even a button click is a form of condition: “If this button is clicked, go to a certain page.” Conditional statements are part of the logic, decision making, or flow control of a computer program. You can compare a conditional statement to a “Choose Your Own Adventure” book, or a flowchart.

#### Key takeaways 
1.Overview of Comparison Operators
2.Writing Conditional Statements
3.Nested Conditional Statements

**Comment by WanjaMIKE** [comment]
Unfortunately, conditional statements in PHP are covered in numerous tutorials on other blog sites. We focus more on unique projects. Feel free to suggest another topic. Thanks
