### ISSUE TITLE
Is Ruby on Rails the Answer to Fintech Woes? 

### ISSUE THREAD

**Issue by Polojigide** [section-engineering-education/engineering-education#5675]
#### Proposed title of article
Is Ruby on Rails the Answer to Fintech Woes? 

#### Proposed article introduction
Financial technologies (fintech) are one of the booming areas in the modern startup community. Numerous projects are appearing to design new solutions for online banking, investment, payment automation, management, financial consulting and management. Their goal is to automate and simplify the process of working with money.

Fintech is a rather specific area of business and a challenge both for business owners and developers.Ruby with Rails framework can tackle all the challenges of fintech startups, as it has all the required tools. It allows having high-quality code for a short amount of time, and for a much more reasonable price. 

#### Key takeaways 

1. Security, analytics, and high traffic challenges in the fintech industry 
2. How Ruby on Rails can help overcome these challenges 
3. Rails in action in the finance sector
- Square
- Fundera
- EarlyShares
- Kin 

#### Article quality
My article is more in-deph and, unlike other articles, it shows how Ruby on Rails is implemented on fintech products,. 

#### References
https://rubyonrails.org/

**Comment by Kayere** [comment]
Sounds like a helpful topic @Polojigide - Approved. Please make sure your article is unique and adds value to what is available online. This is to help avoid article closure in the PR section.
