### ISSUE TITLE
Data representation with react and ant design

### ISSUE THREAD

**Issue by Mirror98** [section-engineering-education/engineering-education#5676]
#### Proposed article introduction
Data representation or visualisation is a process of representing information in the form of charts, pictures, etc. In JavasScript, numerous frameworks have been used to represent data with the most popular being react and d3.js. The use of react and d3.js has been described by a few as "powerful but confusing", "the best data visualisation framework".

In this tutorial, we'll take you on a journey of data representation using react and Antd. Implemented as a react ui library, Antd is a collection of high quality components for building rich, interactive user interfaces. 

#### Key takeaways 
This tutorial aims at showing readers how to:
- Integrate Antd into a react project. 
- Visualisation of data with Basic line using Antd. 
- Building Step line data representation using Antd.

#### References
N/A.

### Conclusion
At the end of the tutorial, the reader should be able to achieve the goals listed above and on further learning, improve their data visualisation skills using Antd. 

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Sounds like a good topic @Mirror98 - Approved. Please make sure your article is unique and adds value to what is available in the [official documentation](https://ant.design/docs/spec/visual).
