### ISSUE TITLE
[Blockchain] How Blockchain Promotes Secure Medical Data Sharing 

### ISSUE THREAD

**Issue by jaykip** [section-engineering-education/engineering-education#5678]
#### Proposed title of article
How Blockchain Promotes Secure Medical Data Sharing 

#### Proposed article introduction
The popularity of mobile health apps and other connected devices has created an opportunity to access previously unavailable personal health data. Integrated pathways allowing researchers to access this data could advance proactive, personalised healthcare and preventive medicine. 

Data that expands beyond traditional tests, which could alter clinical trial implementation by combining genomic and ‘internet of things’ sensor data, could provide new insights to develop effective disease prevention interventions. However, to create meaningful links between patient-generated data, healthcare services and research organisations, there is a need for innovative systems for data sharing and consent. 

Current systems are disconnected and often incompatible, while patients need to be actively recruited and consented for studies, limiting opportunities for data sharing. The secure and decentralised structure of blockchain presents an opportunity to build novel pathways, for integrated mechanisms for data sharing.

#### Key takeaways 

1. Need of blockchain in healthcare
2. Blockchain and medical data sharing
3. Blockchain and protection of healthcare data. 
4. How blockchain ensures secure remote monitoring of IoT devices in heathcare. 

#### Article quality
Most of the available blogs write about the general applications of blockchain technology in healthcare. However, we'll take a different perspective in this article. We'll explain blockchain can protect healthcare data and discuss how it promotes secure sharing of medical data and enhances preventive care. 

#### References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @jaykip.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
