### ISSUE TITLE
A Look at some SQL commands

### ISSUE THREAD

**Issue by mosesmoses12** [section-engineering-education/engineering-education#5680]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of the article
A Look at some SQL commands

Use keyword research to improve your article's SEO.

#### Proposed article introduction
A database is a collection of data or information that is stored in an electronic way. There are some commands that are used to communicate with the database to do a certain task.

The acronym SQL stands for Standard Querry Language.  These are the commands that are used to communicate with the database. Different commands perform a different functions.  In this tutorial, we will look at some SQL commands and the function they perform  

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
1) Brief introduction to database.
2) Downloading database for storing data
3) Definition of the SQL commands
4) Syntax of the SQL commands
5) A look at the task of each SQL command

#### Article quality
The database is an important section as far as a web application or website is concerned. It is the backbone of everything, Therefore it is very important to learn the necessary hacks required to communicate with it. In this article developers and especially the beginners will be equipped with the necessary skills on how to communicate with the database using SQL commands

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, this content appears to be over-saturated. We usually focus more on unique projects. Feel free to suggest another topic. Thanks
