### ISSUE TITLE
Build a Digital Clock using Java

### ISSUE THREAD

**Issue by ozo-vehe** [section-engineering-education/engineering-education#5681]
### Topic Suggestion
[Languages] Build a Digital Clock using Java

#### Proposed title of article
Build a Digital Clock using Java

#### Proposed article introduction
Digital clock are one of the most useful invention of the century. While we all use everyday in our homes and office, it is paramount as a programmer to know how a digital clock works under the hood, and how you can build one for your own use.
In this article, we will be building a digital clock from scratch using the Java programming language. 
The implementation of the clock will be achieved using the Java OOP principles and it will be displayed in form of a GUI using the built-in spring framework as well as a layout manager to properly align the components.

#### Key takeaways 
- The readers will get to know the internal workings of a digital clock and be able to implement them in any programming language of their choice
- The readers will know how to implement a digital clock using Java while learning the application of OOP principles as well.
- The readers will know how to use built-in layout managers to present their ideas which which is more friendly to users.
- The readers will get to learn concepts like exception handling which will be used in this article to avoid the program from terminating  abruptly on encountering an error.
- Application and usage of built-in `Thread` class

#### Article quality
This article aims to build a custom digital clock from scratch utilizing the object-oriented principles of Java. It also teaches the readers some important concepts like exception handling and its application in real life programs, the concept of using layout managers to represent their ideas which is more user friendly. And also, it uses some core concept like threading to achieve the full implementation of a digital clock. 
By the end of this article, the readers will be able to build a digital clock in other object-oriented programming languages as a result of understanding the core concepts from this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Thank you for submitting your topic @ozo-vehe.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
