### ISSUE TITLE
Creating a Graphical Password Authenticator using Django

### ISSUE THREAD

**Issue by omoshII** [section-engineering-education/engineering-education#5682]
### Topic Suggestion
Creating a Graphical Password Authenticator using Django

### Writing sample(s): 
N/A

#### Proposed title of article
Creating a Graphical Password Authenticator using Django

#### Proposed article introduction
Today, millions of websites and applications compete to get you to subscribe or signup to their applications. To subscribe to their applications, you need a username and a password. To access your accounts, you need to authenticate using a password and a username. While passwords are the industry's standard for accessing your accounts on software applications, they are often easy to forget due to the numerous accounts you have.

This is why some authentication methods like graphical passwords came up. This is where a user selects a variety of images in a specific pattern only known to them. These images and the pattern in which the user chose them is what will be used when the user tries to log into his/her accounts.

In this tutorial, we will be implementing this method of authentication using Django, a Python web development framework.

#### Key takeaways 
At the end of this tutorial, the reader should be able to:
* Understand the basics of security in an application
* Understanding the process of authentication
* Understanding and implementing projects using Django

#### Article quality

This is an in-depth tutorial that covers not only the basics about authentication, but also it's implementation using Django.

#### References
N/A

**Comment by Kayere** [comment]
Hello @omoshII, this seems to be a helpful article. It is approved. Just one note, make sure you create a unique project - different from the ones available online.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
