### ISSUE TITLE
[Languages] Introduction to PHP 8 numbers

### ISSUE THREAD

**Issue by vincentoriyo** [section-engineering-education/engineering-education#5688]
#### Proposed title of article
[Languages] Introduction to PHP 8 Numbers

#### Proposed article introduction
Numbers are extremely common in programming. They are used to represent things like screen size dimensions, geographic locations, money, points, the amount of time that passes in a video, positions of game avatars, and colors through assigning numeric codes.

Being able to effectively perform mathematical operations in programming is an important skill to develop because of how frequently you’ll be working with numbers. Though a high-level understanding of mathematics can certainly help you become a better programmer, it is not a prerequisite. If you don’t have a background in mathematics, try to think of math as a tool to accomplish what you would like to achieve, and as a way to improve your logical thinking.

This tutorial will go over many different operators that can be used with numerical data types in PHP, as well as how PHP handles “type juggling” and built-in math functions.

#### Key takeaways 
- Working with operator precedence
- Arithmetic Operators
- Arithmetic Assignment Operators
- Increment Operator
- Decrement Operator
- Grouping Operations
- Type Juggling

**Comment by WanjaMIKE** [comment]
Kindly, we only accept one topic at a time at the moment. Thanks
