### ISSUE TITLE
Using Carbon for dates in PHP 8

### ISSUE THREAD

**Issue by vincentoriyo** [section-engineering-education/engineering-education#5689]
#### Proposed title of article
[Languages]Using Carbon for dates in PHP 8

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Carbon is a PHP package developed by Brian Nesbit which prolongs PHP’s DateTime class. It offers some of the excellent functionality to handle with dates in PHP; It primarily deals with date timezones.

You will learn to add minutes on a current date with the help of Carbon package in Laravel 8, and this tutorial will demonstrate the Carbon in Laravel and specifically show you how to use addMinute(), addMinutes(), subMinutes() methods using Carbon date object.

In this article, you will install Carbon and explore the features and functionality that it provides.
#### Key takeaways 
- Define Minute with Laravel Carbon
- Define Sub Minutes with Carbon
- Getting a Specific Date and Time

**Comment by WanjaMIKE** [comment]
Kindly, we only accept one topic at a time at the moment. Thanks

**Comment by vincentoriyo** [comment]
Hi, kindly reopen this, am ready to work on it. Thank you!
