### ISSUE TITLE
Getting started with MySQL seeding in Laravel 8

### ISSUE THREAD

**Issue by vincentoriyo** [section-engineering-education/engineering-education#5690]
#### Proposed title of article
Getting started with MySQL seeding in Laravel 8 

#### Proposed article introduction
Laravel’s Seeders are special classes that live in the database/seeders directory in a Laravel project that allow you to programmatically insert a collection of default or sample records in the database. The demo application has a seeder class that imports links from a links.yml file in the root of the application folder.

I will explain step by step tutorial laravel 8 seeder example. this example will help you laravel 8 database seeder example. it's simple example of how to create seeder in laravel 8. it's simple example of create seeder command in laravel 8.

#### Key takeaways 
- Getting started with seeders in Laravel
- Using MySQL engine in Laravel
- populating database with fake data using faker class

**Comment by Kayere** [comment]
Thank you for submitting your topic @vincentoriyo.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
