### ISSUE TITLE
[Machine Learning] Building a Time Series Weather Forecasting Application in Python

### ISSUE THREAD

**Issue by monicada** [section-engineering-education/engineering-education#5691]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Building a Time Series Weather Forecasting Application in Python

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

NeuralProphet is a simple forecasting package that bridges the gap between traditional time-series models and deep learning methods. It is built on PyTorch and can be installed using a quick pip install. We will use this open-source package to build a time series weather forecasting application in Python. We will be able to predict the temperature in the future using this package.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to:
- Learn about the Neural Prophet package.
- Learn how to install it.
- Learn how to preprocess the data and load it onto the notebook,
- Learn how to train the forecasting model. 
- Learn how to forecast the temperature into the future. 

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Neural Prophet is a fairly new library that has been built on top of AR-Net and [Facebook Prophet](https://facebook.github.io/prophet/) (also a forecasting model). My tutorial will discuss how to use the model with only a few lines of code and how the model is better compared to the previous time series forecasting models.  

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [Neural Prophet](https://github.com/ourownstory/neural_prophet)

**Comment by Kayere** [comment]
Sounds like a good topic @monicada - Approved. Please make sure your topic is unique and adds value to what is available online and the official documentation.
