### ISSUE TITLE
How to Setup the Glassmorphism Frosty Effect a React.js App with TypeScript

### ISSUE THREAD

**Issue by mosesreigns** [section-engineering-education/engineering-education#5694]
### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article

How to Setup an Add the Glassmorphism Frosty Effect a React.js Application with TypeScript

#### Proposed article introduction

Glassmorphism is a cool UI design trend in the graphic design world that allows you to create an amazing illusion of glass in your application artwork. This guide will discuss the concept of Glassmorphism and a step by step illustrations on how you can achieve the Glassmorphism effect in a React.js application.

#### Key takeaways 

What are Glassmorphism
Overview
Set up React with CRA
A step by step Glassmorphism implementation using React
Conclusion

#### Article quality

Glassmorphism can be implemented in any application of your choice. This guide will help the reader implement a Glassmorphism effect in React.js. We will create a Handy React application that will help the reader understand and implement Glassmorphism In any React.js app.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Please fill the issue form properly.

**Comment by mosesreigns** [comment]
I have update this @kayere

**Comment by Kayere** [comment]
Cool topic @mosesreigns - Approved.
