### ISSUE TITLE
[Language] Understanding Java Aggregation, Association and Composition

### ISSUE THREAD

**Issue by Frank-dev20** [section-engineering-education/engineering-education#5696]
#### [Language] Introduction to Understanding Java Aggregation, Association, and Composition
Java is an object-oriented programming language, meaning it mimics real-life objects.
Understanding the relationships that exist between these objects is key to implementing OOP in Java. In this tutorial, we'll focus on the three commonly misused relationships in Java object-oriented programming paradigm and how they can be properly used.

#### Key takeaways
In this tutorial reader should:
- Understand Aggregation, Association, and Composition in Java
- Be able to use these concepts in Java OOP programming
- Be able to differentiate between aggregation, association, and composition
- Become familiar with the Java is-a and has-a relationships

#### Article quality
In this article, I will explain these concepts using code snippets to illustrate how they are used.
I will also go as deep as using UML diagrams to illustrate these relationships

#### References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @Frank-dev20.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
