### ISSUE TITLE
[Machine Learning] Getting Started with Optical Character Recognition (OCR)

### ISSUE THREAD

**Issue by lcheptoo** [section-engineering-education/engineering-education#5697]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Getting Started with Optical Character Recognition (OCR)

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Optical character recognition (OCR) is a technology that is used to turn scanned images and other visuals into text. This turns paper-based documents into editable and searchable digital mediums and enables the development of automated systems. This tutorial will leverage EasyOCR, a Python package that makes it easy to use this technology in the simplest way possible.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to understand:
- What is Optical Character Recognition?
- How to set up and install EasyOCR. EasyOCR is a package that makes it easy to perform OCR.
- How to use EasyOCR to extract text from different images.
- How to visualize results using the OpenCV library.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

My goal is to make people understand AI in the most simplest way. This tutorial will take our readers through how to get started using EasyOCR  which is a package that makes it easy to use OCR. This will be accomplished with only a few lines of code.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @lcheptoo

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
