### ISSUE TITLE
Working with the trie data structure in C++

### ISSUE THREAD

**Issue by gracy20** [section-engineering-education/engineering-education#5703]
#### Proposed title of article
[Languages] Working with the trie data structure in C++

#### Proposed article introduction
Tree-based implementations of a certain form of data structure, known as the "Trie Data Structure" in C++, allow for the fast and efficient retrieval of keys stored in a vast pool of different strings. To put it another way, a trie-based data structure implementation has a time complexity that is proportional to the maximum string length, but a binary search tree has a time complexity that is proportional to the number of keys in a binary search tree. Trie storage constraints are obviously sacrificed for efficiency. To better understand how trie data structures function, we'll take a look at how they're implemented in C++.

#### Key takeaways 
By the end of this article, the reader will understand:
- What is a trie data structure and what it entails
- What is the use of trie data structure
- Components of a trie node
- Implementation of trie data structure in C++

#### Article quality
In order to make this article stand out, I'll go into great detail on every aspect of the subject. In this article, you'll find examples and explanations for all the many ways to approach this idea. When appropriate, I'll also incorporate screenshots in my articles. My goal is to make it more engaging and beginner-friendly by using simple terminology. I will take the reader through the complexity of a trie data structure for insertion, deletion, and search operation. 

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @gracy20 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
