### ISSUE TITLE
Getting Data from a Database without refreshing using AJAX and PHP

### ISSUE THREAD

**Issue by Adespscientist** [section-engineering-education/engineering-education#5705]
### Getting Data from a Database without refreshing using AJAX and PHP

Most Websites that operate without AJAX will have to reload the whole web page as soon as content changes from the database.

While searching from a search engine and having to click the search button to get information and reloading the whole web page can be frustrating Most times.

As web developers, we want to build a search engine that can throw out information from the database immediately after a search has been initiated in the search engine. AJAX (Asynchronous JavaScript and XML) is a technique used for creating fast and dynamic web pages, AJAX allows web pages to be updated asynchronously by communicating with the database in the background and carrying out small data exchange. This implies that it is possible to update parts of a web page, without reloading the whole page.

### Key takeaways 
At the end of the tutorials the reader should be able to:
1. Understanding AJAX and PHP
2. Create a database with xampp
3. Connecting Database to PHP
4. Create a Search engine with AJAX 

### Article quality
In this article, I will be teaching you the fundamentals of AJAX and how to build a search engine operating with AJAX and PHP

### Reference:
https://www.tutorialspoint.com/php/php_and_ajax.htm

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Adespscientist 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by Adespscientist** [comment]
I write about cybersecurity but most of my topics are rejected why
That what i do

**Comment by Adespscientist** [comment]
https://github.com/section-engineering-education/engineering-education/issues/5699

This my topic was rejected
Why?
