### ISSUE TITLE
[ANDROID || LANGUAGES] - Downloading, extracting, and zipping(compressing) files using Kotlin

### ISSUE THREAD

**Issue by munubi254** [section-engineering-education/engineering-education#5707]
### Topic Suggestion
[ANDROID||LANGUAGES] - Downloading, extracting, and zipping(compressing) files using Kotlin

### Writing sample(s): 
My samples are found [here](https://www.section.io/engineering-education/authors/sandra-moringa/).

#### Proposed title of article
Downloading, extracting, and zipping(compressing) files using Kotlin

#### Proposed article introduction
At times, we may want to automate a file handling process like downloading, extracting, and zipping(compressing it) for a particular reason. That's what we will be looking at in this article. We will download a compressed dataset, place it in a directory, then zip it. Finally, we will compress it back to its original state. All this will be done using Kotlin. (There are a couple of resources for doing the same in Java which I will list the links pointing to them at the end of the article).

#### Key takeaways 
The reader will have knowledge in:
1. Downloading a file from the internet
2. Extracting the file
3. Compressing the file

#### Article quality
It will be an easy walkthrough in all the steps. We will also look at other compressed file types like **tar.gz**, not only the **zip** type. It will also be in Kotlin as many existing blogs use Java.

#### References
1. [Baeldung](https://www.baeldung.com/java-compress-and-uncompress)

2. [Codexpedia](https://www.codexpedia.com/android/android-download-a-zip-file-and-unpack-it/)

3. [Mobikul](https://mobikul.com/zip-unzip-file-folder-android-programmatically/)

4. [Official Android File Docs](https://developer.android.com/reference/kotlin/java/io/File) and [Zip Docs](https://developer.android.com/reference/kotlin/java/util/zip/ZipFile)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @munubi254 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by munubi254** [comment]
Oh wow. Thank you for letting me know. I never knew there were so many
resources on doing the same for Kotlin though. I'll do more research on
that.
