### ISSUE TITLE
Building a checkout form with stripe elements 

### ISSUE THREAD

**Issue by Geo-free** [section-engineering-education/engineering-education#5708]
### Topic Suggestion
Building a checkout form with stripe elements 

### Writing sample(s): 
https://www.section.io/engineering-education/getting-started-with-dot-net-maui-for-cross-platform-apps/
https://www.section.io/engineering-education/using-mldotnet-for-object-detection-in-winforms/
https://www.section.io/engineering-education/different-techniques-of-encoding-data-for-transmission/

#### Proposed title of the article
Building a checkout form with stripe elements 

#### Proposed article introduction
Stripe elements provide developers with prebuilt UI components that allow them to create beautiful checkout flows for their applications. Stripe elements are good when you want to change your application into a payment solution. 

In this article, we will look at how to integrate Stripe elements into an ASP.NET Core project. We shall have a look at each of the following subtopics.
- Introduction to stripe elements
- Explore a custom form
- Payment collection workflow
- Add a stripe checkout to our application
- Customize our payout form
- How taxation is handled

#### Key takeaways 
From this article the reader will be able to;
- Add a stripe checkout to the application
- Know how taxation is handled
- customize a payout form
- Have knowledge of stripe elements

#### Article quality
In this article, I will be taking the reader through the reader through the content and knowledge of stripe elements and how they can be added to a .NET Core application.

#### References
N/A

**Comment by Kayere** [comment]
Sounds like a helpful topic @Geo-free - Please make sure your article is unique and adds value to what is available online and in the official documentation.
