### ISSUE TITLE
[Machine Learning] Detecting Malicious URL using Machine Learning

### ISSUE THREAD

**Issue by Bravinsimiyu** [section-engineering-education/engineering-education#5709]
#### Proposed title of article
[Machine Learning] Detecting Malicious URL using Machine Learning

#### Proposed article introduction
A malicious URL is a link created with the purpose of promoting scams, attacks, and frauds. By clicking on an infected URL, you can download ransomware, virus, trojan, or any other type of malware that will compromise your machine or even your network, in the case of a company.

A malicious URL can also be used to persuade you to provide sensitive information on a fake website. This makes people share sensitive information with unknown people. The potential harm is so big that malicious links are considered one of the biggest threats to the digital world, especially when we talk about attacks and threats that arrive by email.

In this tutorial, we will build a machine learning model that can be able to detect this URL.  We train a model using a dataset with different URL's both bad and good. The model will learn from the dataset and use the knowledge gained to make predictions. We will build the model using Scikit-learn.

#### Key takeaways 
1. What is a Malicious URL.
2. Impacts of Malicious URL.
3. Dataset preparation.
4. Model building using Scikit-learn.
5. Using the trained model to detect Malicious URLs.

#### Article quality
This tutorial is unique because we will be building a custom model. We will also use a large dataset that contains various URLs to train our model to ensure the model adequately learns. The tutorial will use simple steps that a reader can easily follow. This ensures that we have a model that can detect Malicious URLs. This model is very important and can be used in many companies to protect them against attacks using Malicious URLs. This is a practical approach.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Bravinsimiyu 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
