### ISSUE TITLE
Getting started with Handling files in PHP

### ISSUE THREAD

**Issue by swambui1** [section-engineering-education/engineering-education#5710]
#### Topic Suggestion
Getting started with Handling files in PHP

#### Proposed title of article
Handling files in PHP

#### Proposed article introduction
In a web application, file handling is a very significant piece, because you will need to open and process files for various errands regularly. In PHP files are handled almost the same way they are handled in other programming languages such as CPP . PHP has a ton of typical file capacities to work with.

#### Key takeaways
- File formats supported.
- Functions of handling files.
- Use cases of file handling in PHP.
#### Article quality
In this article am going to take the reader through file handling in PHP and explain the different file formats supported when handling files in PHP. Also, I will show the user how to perform different file operatorations in PHP using different functions of file handling. Further more, am going to use a simple and direct language to enhance the understanding of the article.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @swambui1 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
