### ISSUE TITLE
[WEB / LANGUAGES] - Creating a drag and droppable dashboard using pure JavaScript

### ISSUE THREAD

**Issue by vinstex** [section-engineering-education/engineering-education#5711]
### Topic Suggestion
[WEB / LANGUAGES] - Creating a drag and droppable dashboard using pure JavaScript

### Writing sample(s): 
My writing samples are found [here](https://www.section.io/engineering-education/authors/vincent-ngunzulu/).

#### Proposed title of the article
Creating a drag and droppable dashboard using pure JavaScript

#### Proposed article introduction
Owing to the demand for dynamic web pages, we may need to create a dashboard with a drag and drop feature. A very relatable example is GitHub's pinned items dashboard. It allows us to sort the repositories in the pinned board by simply dragging them to where we want. We will build something close to that(but a simple 'minified' version😃) using pure JavaScript. For persistence purposes, we will store the items and the order in a MySQL database.

> We will also populate the dashboard items from the same database.

#### Key takeaways 
The reader will gain knowledge in:
1. Using the JavaScript Drag and Drop API
2. DOM manipulation for reordering nodes
3. Persisting the order in a database(linking with backend)

> We will use PHP for simplicity. I avoided Node or Python because I do not want to include frameworks in the article. Furthermore, the user can use his/her preferred technology once he/she gets a grasp of the concept.

#### Article quality
The article will not only guide the user through the Drag and Drop API but it will show him/her how to link the script with the backend. As usual, it will be simple,  using pure JavaScript. No library. No framework.

#### References
1. [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)

2. [HTML DOM Dev Blog](https://htmldom.dev/drag-and-drop-element-in-a-list/)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @vinstex 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by vinstex** [comment]
Thank you Ahmad. Could you please share with me some of the sites that have
done the same thing that I wanted to write about? I'm just curious

**Comment by vinstex** [comment]
@ahmadmardeni1
