### ISSUE TITLE
[LANGUAGES] Getting Started With Python Timezone

### ISSUE THREAD

**Issue by HEking2** [section-engineering-education/engineering-education#5715]
### Topic Suggestion
[LANGUAGES] Getting Started With Python Timezone

#### Proposed title of article
[LANGUAGES] Getting Started With Python Timezone

#### Proposed article introduction
This article will go over timezones in Python. In general, the timezone is used to display the conversion of date and time between timezones, which means it is used to display the timezone that is being used to print the time and date.

The timezone is related to time concepts in Python, and two modules display timezones: the time module and the datetime module. In Python, using the time module with timezone is simple and error-free, but using the datetime module with timezone is more difficult and error-prone. As a result, Python does not properly support datetime timezones. To make timezone work properly, we must import various modules, as we will see in the section.
#### Key takeaways 
What's python timezone
How does python timezone work?
How to demonstrate timezone
Examples to Implement Python Timezone

#### Article quality
The article is intended to be precise and clear to the point, illustrated by codes making it more practical and interesting, to increase time spent on the page.

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
This is a very simple topic, and it should NOT be a tutorial.
Please feel free to suggest another topic after going through our docs. Read some of our published articles to know what exactly we are looking for. @HEking2
