### ISSUE TITLE
Validating Form Data with Regular Expression in VanillaJs and TailwindCSS

### ISSUE THREAD

**Issue by Charity10** [section-engineering-education/engineering-education#5716]
### Introduction
VanillaJs is the writing of raw JavaScript codes. Knowing how to write the raw codes is still expected of developers without total dependent on the overwhelming frameworks out there. Form is a crucial part of every application and the data has to be validated before submission. In this tutorial, we will build a concise form page with tailwindcss and learn how the validation works using regular expression ie RegEx.

### Key takeaways
Readers would have subtle experience on how to validate form data using regular expression. The following shall be the point of discussions;
- VanillaJs overview
- Building from scratch the form page
- Integrating TailwindCSS for styling
- Learning regular expression in JavaScript for validation

### Article Quality
The quality of this article will not rely on any other article whatsoever. I will make sure readers doubt is cleared on how the regular expression works with JavaScript.

**Comment by Kayere** [comment]
Thank you for submitting your topic @Charity10.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
