### ISSUE TITLE
[Language] Debouncing technique implementation in Javascript

### ISSUE THREAD

**Issue by Eze4Manuel** [section-engineering-education/engineering-education#5719]
### Topic Suggestion
[Language] Debouncing technique using Javascript

#### Proposed article introduction
Improving application performance is vital in modern applications which have a lot of functionalities to execute. Such functionalities range from users interactions to system operations down to external interactions like API calls. Due to the rapid nature of these operations debouncing can be vital in various app functionalities like HTTP requests being sent to servers on every keyboard press, rapid operations like user scrolling down a webpage and the application responding to the scroll e.t.c such implementation can greatly preserve system resources and give the user a better experience interacting with your application.

#### Key takeaways 
- What debouncing technique is all about
- The importance of debouncing and when it is beneficial to implement debouncing.
- How to implement debouncing in javascript

#### Article quality
This article is unique in that it provides users with an actual implementation example to better enable them to see the benefits of debouncing and know-how and when it can best be implemented

#### References
- https://www.freecodecamp.org/news/javascript-debounce-example/
- https://www.geeksforgeeks.org/debouncing-in-javascript/

**Comment by Kayere** [comment]
Thank you for submitting your topic @Eze4Manuel.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
