### ISSUE TITLE
Building a Blazor Chat App With SignalR

### ISSUE THREAD

**Issue by Joesongoma** [section-engineering-education/engineering-education#5721]
### Topic Suggestion
Building a Blazor Chat App With SignalR

### Writing sample(s): 
https://www.section.io/engineering-education/creating-a-blazor-server-side-application-using-aspdotnet-core-to-perform-crud-operations/
https://www.section.io/engineering-education/java-timer-tasks/

#### Proposed title of the article
Building a Blazor Chat App With SignalR

#### Proposed article introduction
Web Assembly is a modern low-level assembly-like language with a compact binary format that runs with near-native performance and provides languages like C#, F#, C, C++ a compilation target so that they can run on the web. 

With the knowledge of Web Assembly, we can use SignalIR in a blazer app to build a chat app. SignalR is an ASP.NET that lets your server-side code push content to your connected clients in real-time with client SDKs.

In this article, I will be showing the reader how he or she can build a real-time web assembly chat app in blazor using SignalR.

#### Key takeaways 
From this tutorial, the reader will understand:
- the  concept of web assembly
- how signalR works
- how to integrate signalR into a blazor web assembly app 

#### Article quality
In this article, I will be showing the reader a step, how to use signalR to build a blazor chat app. I will also put all the needed knowledge together in this article to ensure that the reader gets a quality understanding of the signalR concept.

#### References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @Joesongoma.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
