### ISSUE TITLE
[Machine Learning] Building a Password Strength Classifier Model Using Machine Learning

### ISSUE THREAD

**Issue by kelvinkimani501** [section-engineering-education/engineering-education#5722]
#### Proposed title of article
[Machine Learning] Building a Password Strength Classifier model using machine learning

#### Proposed article introduction
Password strength is a measure of the effectiveness of a password against guessing or brute-force attacks. In its usual form, it estimates how many trials an attacker who does not have direct access to the password would need, on average, to guess it correctly. The strength of a password is a function of length, complexity, and unpredictability.

Data breaches and identity theft are on the rise, and the cause is often compromised passwords. After stealing credentials, cybercriminals can use passwords to start disinformation campaigns against companies, use people’s payment information for purchases, and spy on users through WiFi-connected security cameras. Therefore, we need to build a model that can determine the strength of a given password, this enables us to have more secure systems that can not be easily cracked.

In this tutorial, we will build a password classification model using Scikit-Learn. The model will give the password from strength from the lowest strength to the highest strength depending on the password inputted by the user.

#### Key takeaways 
1. What are the impacts of having a week password.
2. How to generate secure passwords.
3. Dataset preprocessing.
4. Model building and training.
5. Using the model to classify the strength of a password.

#### Article quality
In this tutorial, we will build a machine model that we will be used to classify the strength of a given password. This ensures people use more secure passwords in order to prevent data breaches. We will implement this model from scratch so that any reader can easily follow the steps and come up with the model. In this tutorial, we will ensure the model makes accurate predictions. We thoroughly train the model to make sure it effectively learns.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Sounds like a helpful topic @kelvinkimani501 - Approved. Please make sure your article is unique and adds value to what is available online.
