### ISSUE TITLE
[Machine Learning] Building a Web Crawler using BeautifulSoup and Scrapy Python Framework

### ISSUE THREAD

**Issue by Adespscientist** [section-engineering-education/engineering-education#5723]
### Building a Web Crawler using BeautifulSoup and Scrapy Python Framework

With the advent of enormous data and the need for networking transmission has expanded globally. Various associations retrieve remote data from the web for various reasons. Pursuit updates in specific markets, collect daily supply and analyze rivals. In other words, Web crawlers are heading to become very important to the internet.

Web Crawler is essential in our search engines if we want to be able to gather updates from prominent websites. That is why I will be showing you how to build this spider robot using python. With specified rules, web crawlers which are also called spider or spider bots automatically surf or grab information from the internet.

### Key takeaways 
At the end of this tutorial you should be able to:

- Understand basic Python syntax 
- Set up Python Environment
- Understand the BeautifulSoup Library.
- Understand the Scrapy Python Framework.
- Build a Web crawler with the Information Gathered.

### Article quality
 I have been thinking about this project for a while and I found out that there are other tutorials on web crawlers, that is why I will be using BeautifulSoup and Scrapy python framework which are some of the most helpful python projects to find up-to-date information. You will need to use a multi-thread idea for this tutorial and I will be showing you how to use Python’s request module to make the crawler bot. It is Python’s open-source web crawling framework explicitly designed for web scraping and pulling data by using APIs.

### Conclusion
With the quick advancement of technology over the internet, the web crawler is one of the most needful parts of our search engines to keep up with updates from favorite websites and blogs.
Thank you.

**Comment by Kayere** [comment]
Thank you for submitting your topic @Adespscientist.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
