### ISSUE TITLE
[ANDROID || LANGUAGES] - Creating a data visualization dashboard using MPAndroid Chart library

### ISSUE THREAD

**Issue by munubi254** [section-engineering-education/engineering-education#5724]
### Topic Suggestion
Creating a data visualization dashboard using MPAndroid Chart library and SQLite

### Writing sample(s): 
My writing samples are found [here](https://www.section.io/engineering-education/authors/sandra-moringa/).

#### Proposed title of article
Creating a data visualization dashboard using MPAndroid Chart library and SQlite

#### Proposed article introduction
The easiest way for a user to get insight from information is through the use of data visualization. The most common tool for that is charts. In this article, we will create an admin dashboard that allows the user to view his/her data using different kind of charts. Kotlin and an open-source chart library, MPAndroidChart, will be used.

#### Key takeaways 
The reader will gain knowledge in:
1. Using the Kotlin and MPAndroidChart library
2. Getting data from an sqlite database
3. Creating a dashboard using cards

#### Article quality
The article will not only guide the user on using the MPAndroidChart library but it will show him/her how to dynamically populate the charts using data from a database. 

#### References
1. [MPAndroidChart GitHub code examples](https://github.com/PhilJay/MPAndroidChart)
2. [Vishal Kamboj Youtube videos](youtube.com/channel/UC92ii7ym_NNs_grqya_zsgg)

**Comment by munubi254** [comment]
@ahmadmardeni1

**Comment by Kayere** [comment]
Good topic @munubi254 - Approved. Please make sure you don't copy content from any youtube tutorial or any other article on this topic. This is to avoid article closure in the PR section.
