### ISSUE TITLE
[Languages]Improving Accessibility With Prefers-Reduced-Motion

### ISSUE THREAD

**Issue by codeInn001** [section-engineering-education/engineering-education#5725]
### Topic Suggestion
[Languages]Improving Accessibility With Prefers-Reduced-Motion
#### Proposed title of article
Improving Accessibility With Prefers-Reduced-Motion 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
The prefers-reduced-motion CSS media feature is used to detect if the user has requested that the system minimize the amount of non-essential motion it uses.

When working with motion on the web, it’s important to consider that not everyone experiences it in the same way. What might feel smooth and slick to some might be annoying or distracting to others — or worse, induce feelings of sickness, or even cause seizures.

We also need to acknowledge that not every device that can access the web can also render animation, or render animation smoothly. When animation is used on a low-power or low-quality device that “technically” supports it, the overall user experience suffers. Some people even deliberately seek this experience out as a feature.

#### Key takeaways 
1. Learn how to properly implement prefers-reduced-motion in css.
2. Learn how to implement prefer-reduced-motion if animation is done in Javascript.
3. Learn how to create explicit motion toggle

#### Article quality
The article serves to sensitize front-end developers on the importance of accessibility when animating websites. This is mostly ignored by front-end developers.

It will also talk about how to create explicit motion toggles for users as most users don't even know how to set reduced motion on their machines.

#### References
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by Kayere** [comment]
Thank you for submitting your topic @codeInn001.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
