### ISSUE TITLE
Learn SSH {Secure Shell} from Scratch to Mastery

### ISSUE THREAD

**Issue by abimbolataofeek** [section-engineering-education/engineering-education#5727]
### Learn SSH {Secure Shell} from Scratch to Mastery

 SSH or Secure Shell is a protocol. What does that mean, you may have heard of other protocols like HTTP, HTTPS, FTP. These are all ways to connect to the computer and have a shared agreement on how to communicate. That is their protocol or language that they can speak and SSH is a way for machines to communicate with one another.

 For example, HTTP or Hypertext Transfer Protocol, allows you to send files over the internet like HTML, CSS, and Javascript files between browsers and servers. FTP or File Transfer Protocol allows you to send files as well and is often used when you upload files like Hostgator or a generic hosting platform from your computer. HTTPS is similar to HTTP but is encrypted, which means third parties can't read the files being transferred if they intercept the messages. And just like these, SSH is another protocol that allows us to communicate between two computers over the Internet. It allows users to share files as well as control and modify remote computers over the internet. It was created as a secure way of communication that encrypts all the data so bad actors can't monitor you. Just like a web browser uses the HTTPS protocol to talk with servers, and display Web sites a shell neds a certain protocol to enable data exchange or communication between two devices and not just a browser and a server, and that is why SSH is called a secure shell protocol. It's a protocol to use over shell. Shell, unlike a browser, allows you to talk to the operating system, you've used the command line before right?

### Article quality
In this tutorial, I will teach SSH from scratch to mastery. Even if you don't know or have never used SSH, I will be covering how to use SSH, Talk about why this is useful for a web developer also cover some advanced topics in SSH.

### Key takeaways:
At the end of this tutorial the reader will fully understand and be able to:

- Introduction to SSH
- SSH Commands
- Saving the day through SSh
- How SSH Works
- Symmetric Encryption
- Asymmetric Encryption 
- Hashing
- Password 0r SSH
- SSH into A Server
- Setup SSH on Github
- Difference between HTTPS and SSH

References:
https://www.ssh.com/

**Comment by Kayere** [comment]
Thank you for submitting your topic @abimbolataofeek.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
