### ISSUE TITLE
[LANGUAGES]How to perform unit testing in Flask

### ISSUE THREAD

**Issue by Gracey2** [section-engineering-education/engineering-education#5729]
### Topic Suggestion
.[LANGUAGES]How to perform unit testing in Flask

#### Proposed article introduction
Flask unit testing is defined as a method of testing individual portions of source code that consist of one or more modules programmed together, which takes care of usage procedures, operation procedures, and the data associated with it to be tested to determine their fitness for usage. These tests are performed by software developers to ensure that the section of code written for a specific task accomplishes the task in addition to meeting the design requirements and behavior. These tests are typically automated and are aimed at specific functions or procedures.

#### Key takeaways 
Storing the Unit tests
Creation of the basic unit test file
Running of Unit Tests
code coverage
Examples of Flask unit testing

#### Article quality
The article is intended to be precise and clear to the point, illustrated by codes making it more practical and interesting, to increase time spent on the page.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Sounds like a helpful topic @Gracey2 - Approved. Please make sure your article does not reference any youtube tutorial or other articles covering this topic.

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
