### ISSUE TITLE
[API] How to use Brotli compression method for web applications

### ISSUE THREAD

**Issue by Newton-cyber** [section-engineering-education/engineering-education#5731]
### Topic Suggestion
How to use Brotli compression method for web applications

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-troubleshoot-and-monitor-a-database/
https://www.section.io/engineering-education/integration-of-ros-with-arduino/

#### Proposed title of article
How to use Brotli compression method for web applications

#### Proposed article introduction
Static assets such as **.js** ,**.CSS** and **.json** text files are commonly used in web application projects, with redundancy and compression playing an important role. Compression reduces the amount of bandwidth required for website rendering, which speeds up the process.
Brotli is a lossless compression algorithm that combines a current form of the LZ77 algorithm, Huffman coding, and 2nd order context modeling to compress data. 

#### Key takeaways 
1. what is Brotli
2. How brotli works
3. Application of brotli
4. Configuring with Nginx
5. Configuring with AWS CloudFront distribution

#### Article quality
This article will add an instance of brotli compression to an already existing instance of Nginx, while also taking the reader through a step by step process in creating a dynamic brotli module.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Good topic @Newton-cyber - Approved.
