### ISSUE TITLE
API Authentication With Laravel Passport in Laravel Lumen

### ISSUE THREAD

**Issue by AbdullahiAbdulkabir** [section-engineering-education/engineering-education#5732]
### Writing sample(s): 
[Laravel on subdomain](https://link.medium.com/LTQL1ECiemb) 

#### Proposed title of article
API Authentication With Laravel Passport in Laravel Lumen 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
In these article, I will be discussing how to use laravel lumen, a light weight and fast framework for building APIs. It a framework that comes with lesser and little dependencies as against laravel framework. I will be talking about how to setup passport for access token and authorization of each request, setting middlewares and building a basic CRUD app for testing out the passport tokens.

#### Key takeaways 
Setting up Laravel Lumen
Setting up passport
Creating simple CRUD app

#### Article quality
The article is intended to be clear and precise. It is meant to be practical with illustration and code snippet. Many online articles doesn't explain with snippet and don't really explain the predefined routes in the passport.

#### References
[Lumen website](https://lumen.laravel.com/) 
[Laravel Passport](https://laravel.com/docs/8.x/passport) 

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Thank you for submitting your topic @AbdullahiAbdulkabir.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
