### ISSUE TITLE
Building a food store using redux and angular

### ISSUE THREAD

**Issue by JOEOBY** [section-engineering-education/engineering-education#5734]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Building a food store using redux and angular

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Building a food store using redux and angular

#### Proposed article introduction
We will discover ways to use  Redux in the process  of building a food store that shows objects and shall we customers upload them to a buying cart. We’ll also be constructing a food store by the use of Angular. On this store, a consumer will view the gadgets displayed in the store and can be able to add and remove items from the cart. We’ll be setting up a minimum server using express so that it will serve the goods to the Angular application

#### Key takeaways 
1.  Installing dependencies
2.  Building a server
3. Styling the: a) home component
               b) Header component
                c) App component
4. Angular/redux store
5. Creating and registering a reducer
6. Fetching items from our server
7. Viewing product list

#### Article quality
This article will provide a step by step elaborated ways of building a food store using redux an angular. It is unique since its very understandable and its a beginner friendly guide.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
N/a

### Conclusion
We’ve built a simple food store in which items can be introduced and removed from cart. We’ve been able to manage the software’s state using the Angular/Redux library. As we’ve seen, it is less difficult to control statistics go with the flow in the application while side results and data go with the flow are abstracted from components.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Thank you for submitting your topic @JOEOBY.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
