### ISSUE TITLE
[Artificial Intelligence] Overview of Quantum AI 

### ISSUE THREAD

**Issue by Romans70** [section-engineering-education/engineering-education#5735]
#### Introduction
Quantum AI, as the title suggests, is the application of quantum technology to the calculation of machine learning procedures. Quantum technology and machine learning are both game-changing innovations that will change how people work and operate daily. Artificial intelligence, on the other hand, will almost certainly needs a better knowledge of quantum computing and quantum physics before it can acquire true life form intellectual ability. In this article we will discuss about quantum computing and how quantum AI works to make human works more easier.

#### Key takeaways 
1. Quantum AI and quantum computing definitions
2. How quantum AI works
3. Possible application of quantum computing in AI
4. Critical milestones for quantum AI

#### Article quality
This will be a unique article with more details on the topic. In my article, I will use simple language for any person reading to have a better understanding of the concepts in quantum AI. I will make sure that this article helps the rest of EngEd and goes beyond other official documentation.

#### References
N/A

**Comment by Kayere** [comment]
Sounds like a great topic @Romans70 - Approved.

**Comment by WanjaMIKE** [comment]
Closing since PR was also closed

**Comment by Romans70** [comment]
Hello @WanjaMIKE 
I would like to create a PR for this issue. Can you help me open the issue.
Thanks.
