### ISSUE TITLE
Using Tensorflow to implement Deep Q-Learning

### ISSUE THREAD

**Issue by gracy20** [section-engineering-education/engineering-education#5739]
#### Proposed title of article
[Machine Learning] Using Tensorflow to implement Deep Q-Learning

#### Proposed article introduction
TensorFlow has received a lot of attention in recent years because of its deep learning capabilities. An AI subclass known as Deep Learning mimics the human brain's neural network in order to learn. There are many similarities between the human nervous system and the network created by Deep Learning models. It simulates the human brain's thought process. There are nodes in deep learning, each of which acts as a neuron. There is a great deal of discussion about deep learning.

#### Key takeaways 
By the end of this article the reader will be able to understand:
- What deep learning entails in TensorFlow
- The reasons why we need Deep Learning Models in solving complex problems
- Stepwise implementation of TensorFlow Algorithm
- Reinforcement learning vs Q-learning

#### Article quality
It is imperative that I go into great detail to make my article stand out. Many approaches to the topic will be discussed in this article, with examples and explanations provided. Screenshots may also appear in my article when suitable. It's my intention to make it more appealing and accessible to beginners by simplifying the vocabulary. I will incorporate the significance of TensorFlow-based deep learning as well as its advantages. The implementation will be step by step.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @gracy20 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
