### ISSUE TITLE
How to work with Hooks in Angular 12

### ISSUE THREAD

**Issue by NaomiSeint** [section-engineering-education/engineering-education#5740]
#### Proposed title of article
How to work with Hooks in Angular

#### Proposed article introduction
Angular is a TypeScript framework for building web applications, mobile or desktop with over 49,000 stars on GitHub. Maintained by the Angular team at Google and a host of community members and organizations, it combines declarative templates, dependency injection, end to end tooling, and integrated best practices to solve development challenges. Angular empowers developers to build applications that live on the web, mobile, or the desktop. It has a very useful CLI tool for beginners to easily get started, there is even a GUI client called Console.

#### Key takeaways 
- Lifecycle hooks
- ngOnDestroy()
- ngOnChanges()

**Comment by NaomiSeint** [comment]
@ahmadmardeni1 I think this could be a great one for the community.

**Comment by ahmadmardeni1** [comment]
How is your article unique? Tell us what makes your approach different from similar articles that have been published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

What do you think of this topic? @WanjaMIKE

**Comment by WanjaMIKE** [comment]
Based on this search, the topic appears oversaturated @ahmadmardeni1 https://www.google.com/search?q=How+to+work+with+Hooks+in+Angular&oq=How+to+work+with+Hooks+in+Angular&aqs=chrome..69i57j35i39i362l6j69i61.344j0j7&sourceid=chrome&ie=UTF-8

**Comment by NaomiSeint** [comment]
> Based on this search, the topic appears oversaturated @ahmadmardeni1 https://www.google.com/search?q=How+to+work+with+Hooks+in+Angular&oq=How+to+work+with+Hooks+in+Angular&aqs=chrome..69i57j35i39i362l6j69i61.344j0j7&sourceid=chrome&ie=UTF-8

@WanjaMIKE when a topic already exists, it doesn't necessarily mean that the content will be the same! As @ahmadmardeni1  asked, this is to cover more in-depth about the hooks which is a very key life cycle concept in Angular! Kindly reconsider!  Other articles cover an overview of the entire concept!

cc @ahmadmardeni1 @ahmadmardeni1 @WanjaMIKE

**Comment by WanjaMIKE** [comment]
Unfortunately, the topic still appears over-saturated on other blog sites. Could you suggest another topic. Thanks
