### ISSUE TITLE
Getting started with heatMaps in Angular 12

### ISSUE THREAD

**Issue by NaomiSeint** [section-engineering-education/engineering-education#5741]
#### Proposed title of article
Getting started with heatMaps in Angular 12
#### Proposed article introduction
In the article, I would like to describe a way to easily implement a simple heat map in an Angular application. For that, I will use two external libraries, which are going to be Leaflet.js and Heatmaps.js. Before the implementation of the heat map, I prefer to begin with a brief introduction to the libraries I mentioned above. Leaflet.js It is one of the most popular JavaScript libraries for interactive maps. It has over 30k stars on GitHub. There is an alternative to it such as OpenLayers. But in my example, I picked a leaflet.

#### Key takeaways 
- intro to leaflet.js
- working with heatmaps
- Module injection

**Comment by NaomiSeint** [comment]
@louisefindlay23 this is coudl be a great article for community!

**Comment by ahmadmardeni1** [comment]
Only open 1 topic suggestion at a time.
You can resubmit this one when we publish your article. @NaomiSeint
