### ISSUE TITLE
[Languages]How to Perform Countdown Timer in Python

### ISSUE THREAD

**Issue by HEking2** [section-engineering-education/engineering-education#5742]
### Topic Suggestion
[Languages]How to Perform Countdown Timer in Python

#### Proposed article introduction
What should you do if you need to run a specific piece of code after a certain amount of time? Assume you need to update a file every 30 minutes. Will, you submit the same thing every time. Isn't that correct? This is where the Python Countdown Timer comes in, as it can be used to wait for a certain amount of time in the idle state before reiterating the same piece of code in the loop as needed.

#### Key takeaways
Importing the time library
creating an alias for the library
Examples of Python Countdown Timer

#### Article quality
The article is intended to be precise and clear to the point, illustrated by codes making it more practical and interesting, to increase time spent on the page.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
This is a very simple concept. It can't be a tutorial. Please feel free to suggest an alternate topic to explore. 🚀 @HEking2
