### ISSUE TITLE
Applying Bokeh to Manage Categorical Data In Python

### ISSUE THREAD

**Issue by Ndichu254** [section-engineering-education/engineering-education#5743]
#### Proposed title of article
[languages]Applying Bokeh to Manage Categorical Data In Python

#### Proposed article introduction
Bokeh may also be used to plot categorical data on categorical ranges in addition to numerical data on continuous ranges.
In Bokeh, basic categorical ranges are represented as string sequences. A list of the four seasons, for example. Bokeh is capable of managing hierarchical categories as well. To represent the distinct months inside each yearly quarte, for example, you can use nested sequences of strings. Various types of charts, such as bar charts, category heatmaps, jitter plots, and others, can be used depending on the nature of your data. In this article, I'll go through a few different forms of categorical data plots.

#### Key takeaways 
- What is Python bokeh used for?
- What method do you use to manage categorical data?
- What is bokeh plotting, and how does it work?
- How do you draw a line in bokeh?

#### Article quality
To make this article stand out, I will go into great detail on every aspect of the subject. This article will provide examples and explanations for the many techniques related to this topic. In my article, I will also provide screenshots as needed. By employing basic terms, I aim to make it more engaging and friendly to beginners.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Ndichu254 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
