### ISSUE TITLE
In-Memory Caching In C#

### ISSUE THREAD

**Issue by Joesongoma** [section-engineering-education/engineering-education#5744]
### Topic Suggestion
In-Memory Caching In C#

### Writing sample(s): 
https://www.section.io/engineering-education/java-timer-tasks/
https://www.section.io/engineering-education/creating-a-blazor-server-side-application-using-aspdotnet-core-to-perform-crud-operations/

#### Proposed title of article
In-Memory Caching In C#

#### Proposed article introduction
During app development, application performance is important. The fact that your application works well during app development doesn't mean it will work well when thousands of people start using it. One main area to look at is the data access. Toking your data can be very expansive especially when your data might not change very often. This is where data caching comes in. This data can be cached in a number of ways that we do not indicate going back to the data base. 

In this article, I shall be looking at a caching method in .NET called in-memory caching in C#. I will create an application without caching, observe its performance and then introduce caching and observe how the performance is improved.

#### Key takeaways 
- Understand the concept of in-memory caching
- Understand how to implement in-memory caching using C#
- Understand the concept of .net in our app development

#### Article quality
In this article, I will be creating an app, observe its performance without caching, implement caching in our app and observe the performance.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Joesongoma 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
