### ISSUE TITLE
Working with CSV files in C#

### ISSUE THREAD

**Issue by swambui1** [section-engineering-education/engineering-education#5746]
#### Topic Suggestion
Working with CSV files in C#.
#### Proposed title of article
Working with CSV files in C#.
#### Proposed article introduction
Comma separated Values in csharp are very important because they are utilized for transportating data between programs. CSV, is a basic document design utilized to store plain information in a straight forward text structure.
In csharp, handling comma separated values is almost similar to handling CSV file in other programming languages such as Java.
#### Key takeaways 
- Creating a CSV file.
- Reading a CSV file in Csharp.
- Writing and Appending in a CSV file.
#### Article quality
In this article I will guide user on creation of comma separated values, reading, writing in the CSV file and Appending. Am going to use a beginner friendly language and code samples which are easier to understand the concept.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @swambui1 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
