### ISSUE TITLE
Blazor : QR Code Or Bar Code Generator

### ISSUE THREAD

**Issue by Mercycar** [section-engineering-education/engineering-education#5747]
### Topic Suggestion
Blazor : QR Code Generator Or Bar Code

#### Proposed title of article
Blazor : QR Code Generator Or Bar Code

#### Proposed article introduction
QR Codes are formed with a 2D array of pixels with two colors, black and white, one color represents 0 and the other color 1. They range from version one which is 21 by 21 pixels to version forty which is 177 by 177 pixels. QR-Codes have patterns which enables easy identification of the codes.

In this article, I will be looking at how this codes are created by creating a QR-Code in blazor. 

#### Key takeaways 
From this article, the reader will be equipped with the knowledge of:
- QR and Bar-Codes
- Building a QR and Bar-Codes in blazor
- Understand the knowledge of QR and Bar Codes

#### Article quality
In this article, I will be taking the reader through the concept of QR and Bar Codes, build a QR and Bar Code generator.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Mercycar 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
