### ISSUE TITLE
How  to use a Math equation in building a Linear Regression model

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#5748]
### Topic Suggestion
How  to use a Math equation in building a Linear Regression model

#### Proposed article introduction
 Regression is a way to show how the mean of one thing is linked to the mean of another variable. Let's try to think of regression in normal terms. It's an effort to figure out how one dependent and a group of other independent variables are linked together.

Linear Regression is a machine learning algorithm that helps us figure out the relationship between the feature and the columns we want to learn more about. A simple straight line can be drawn between the features and the target column, so we always look for this kind of relationship. We then build a linear model, which is what we do when this is the case.

To help us build a linear regression model in the world of machine learning, we're going to use equations such as *y=mx+c* in this post.
#### Key takeaways 
- Types of Linear Regression
- Variables
- How a simple linear equation is used in the ML Linear Regression algorithm
#### Article quality
 I will show how a simple linear equation in math is used in Machine Learning algorithms and how we can use it to build an ML model that can predict the target values. Our method for finding the best values for model coefficients in Linear Regression is called `gradient descent` and we use it to make sure that the model we build doesn't fit too many things. If there is no multicollinearity (where two or more feature columns show the same relationships), we will also make sure there are no feature columns with the same relationships among them.
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Thank you for the topic suggestion , however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
