### ISSUE TITLE
Optimizing ML Models with Optuna

### ISSUE THREAD

**Issue by NdoloBonface** [section-engineering-education/engineering-education#5749]
### Topic Suggestion
Optimizing ML Models with Optuna
#### Proposed article introduction
Optuna is the SOTA algorithm used to make changes to ML and deep learning models. It all depends on the Bayesian fine-tuning method. It stops trying combinations that don't improve our score any more and only tries combinations that do.

People who work on ML models have a hard time. In order to make it easier for us to fine-tune our model, there are a lot of tools out there. You need to make sure that our data is important and that our ML model fits on it perfectly. Here, we'll learn how to make an Xgboost regressor work even better.

When you use machine learning, a hyperparameter is a parameter that can be changed to change how the learning process works.  The values of hyperparameters can't be guessed from the data. It's important to set these parameters so that the model can learn from our data. You can change the learning parameters so that the model fits our data and learns from it to make smart predictions.
#### Key takeaways 
- Visualization of Tuning
- Comparing the Tuned Model and Base Model
- Creating Hyper-Parameters Space

#### Article quality
In this article, we'll learn how to improve ML models and how to find the best parameters for the models we make. The code will be easy to read and understand.
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @NdoloBonface 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by NdoloBonface** [comment]
> Just wanted to follow up on this topic, as we will be clearing up the queue where possible.
> 
> Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. +1

Hello @hectorkambow this is the topic I'm currently writing on . I mentioned it earlier via slack when  I was asking about being a peer reviewer.
