### ISSUE TITLE
[Languages]Python Pickle Vs JSON

### ISSUE THREAD

**Issue by kipkoech88** [section-engineering-education/engineering-education#5750]
### Topic Suggestion
[Languages]Python Pickle Vs JSON

#### Proposed article introduction
Pickling, also known as serialization, is the process of converting a Python object (lists, dicts, tuples, and so on) into byte streams that can be saved to disks or transferred over the network. The byte streams saved to the file contain all of the information required to reconstruct the original Python object. De-serialization refers to the process of converting byte streams back to Python objects.

JSON is an abbreviation for JavaScript Object Notation. It is based on JavaScript but is not limited to that language. JSON is a standardized format that is supported by almost every language. JSON is similar to Pickling in that it stores data in human-readable text format rather than binary format.

#### Key takeaways 
- It will enlighten the reader on the advantages and disadvantages of both pickle and JSON
- It will help beginners in python or data analytics to confidently propose the right object serialization module.
- It will provide a simple road map for a quick guide at whatever point individuals intend to work with files.
- It will give the key differences between Python Pickle and JSON

#### Article quality
This article features a detailed discussion on how the two object serialization module compare and contrast. The article includes suggestions on the various application areas of each object serialization module and places extra emphasis on which one one is preferred depending on the user.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value. Feel free to suggest another topic. Thanks
