### ISSUE TITLE
How to denoise images using curvelet transform in Matlab

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#5754]
#### Proposed article introduction
Curvelet transform is a very powerful tool which has the capability to capture details along the curvature in images. It is a very useful tool for feature extraction in area of pattern recognition. It is also efficient in image denoising. Denoising of images is the removal of the noise signals in an image.
In this tutorial, we will look into details the curvelet transform analysis and denoising of images. We will also look at the Matlab code for doing this. Also in curvelet analysis, there is a curvelet toolbox that we will see how to use.

#### Key takeaways 
- Theoritical background of curvelet transform.
- Curvelab.
- Curvelet transform of images.
- Curvelet based denoising of an image 

#### Article quality
This article looks deeply into the curvelet transform analysis and how we can use this analysis to denoise images.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @jumapaul 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #5754 via #5953
