### ISSUE TITLE
Getting started with Burpsuite

### ISSUE THREAD

**Issue by shosenwales** [section-engineering-education/engineering-education#5756]
### Topic Suggestion
Getting Started with Burpsuite

### Writing sample(s): 
https://www.section.io/engineering-education/understanding-cross-site-scripting-attacks/

#### Proposed title of article
Getting Started with Burpsuite

#### Proposed article introduction
This article seeks to introduce the reader to one of the most popular web application hacking tool.

[Security] Getting started with Burpsuite.

#### Key takeaways 

Readers will:
1. Be able to test for common web application vulnerabilities
2. Be able to intercept network traffic.
3. Be able to perform application security testing.

#### Article quality

This article will taking a practical approach in introducing the tool to the user.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Approved. Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it. (There are some great free tools that we reference in EngEd resources.) @shosenwales

**Comment by WanjaMIKE** [comment]
Closed #5756 via #5843
