### ISSUE TITLE
Building ComposeWidget using jetpack glance

### ISSUE THREAD

**Issue by JOEOBY** [section-engineering-education/engineering-education#5757]
### Topic Suggestion

Building a ComposeWidget using Jetpack Glance

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Building a ComposeWidget using Jetpack Glance

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Jetpack Glance offers a handy, streamlined way to create widgets with a long way less code. The framework offers a base set of compostables which may be leveraged to create lovely and practical person studies. As an introduction into using glance, a easy app widget might be designed to maintain tune of how many pushups a person has performed in a day.
 
#### Key takeaways 
1. Creating and setting up the application
2. Declaring and previewing the widget 
3. Android manifestation 
4.  Initializing and creating the widget layouts 
5.  Writing composable content 
6.  The Glance actioncallbacks 
7.  State in Glance 
8.  Encapsulation components together 

#### Article quality
This article will give a step by step walk through of how to build a ComposeWidget using the jetpack Glance. It is a beginner friendly guide, easy to follow using understandable steps.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
N/a

### Conclusion
We've developed a ComposeWidget using jetpack Glance, and we have shown how it keeps track on the amount of pushups a person takes in a day. Using the right steps will as shown in the article you will be able to have the widget on your home screen layout on any android.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
I think this topic suggestion is adequately covered here https://android-developers.googleblog.com/2021/12/announcing-jetpack-glance-alpha-for-app.html Feel free to suggest another topic. Thanks
