### ISSUE TITLE
FUTURE VULNERABILITIES OF MACHINE LEARNING

### ISSUE THREAD

**Issue by MBITHE4760** [section-engineering-education/engineering-education#5764]
Machine learning (ML) is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence. Machine learning algorithms build a model based on sample data, known as training data, in order to make predictions or decisions without being explicitly programmed to do so. 

However, machine learning would lead to a high consumption of time and space. Many ML algorithms might take more time than anticipated.  If your data is large and advanced, the system will take time. This may sometimes cause the consumption of more CPU power. Even with GPUs alongside, it sometimes becomes hectic. Also, the data might use more than the allotted space.

**Comment by lalith1403** [comment]
Please follow the topic form submission template. Go through the contribution guidelines for more details.
