### ISSUE TITLE
How to build a Meme Generator with Vanilla JavaScript, Skeleton and the HTML 5 Canvas.

### ISSUE THREAD

**Issue by Nomzy-kush** [section-engineering-education/engineering-education#5765]
### Writing sample(s): 
https://stackoverflow.blog/2021/10/20/why-hooks-are-the-best-thing-to-happen-to-react/?cb=1&_ga=2.218645726.618497180.1634907321-1032916238.1629601197

https://www.section.io/engineering-education/how-to-build-a-currency-converter-with-react-and-its-material-ui/

https://www.section.io/engineering-education/building-a-calculator-a-javascript-project-for-beginners/

#### Proposed title of the article
How to build a Meme Generator with Vanilla JavaScript, Skeleton and the HTML 5 Canvas. 

#### Proposed article introduction
Memes are a stimulating and fun way to pass messages across to people. In this article, we will take a step-by-step guide on creating a Meme Generator with pure Vanilla JavaScript and style its components with [Skeleton](http://getskeleton.com/). With the use of the HTML 5 Canvas, users will be able to use images and texts of their choice locally and or from an online source to create comical memes for a mass online audience. It is a must-do JavaScript project for beginners.

#### Key takeaways 
1. Readers will learn how to import images to this application both locally and from an online source and use them to create Memes.
2. Readers will learn how to use Skeleton(a dead simple and responsive boilerplate to kickstart any responsive project) to style any application.
3. Readers will learn how to use the HTML 5 Canvas to update the memes created in the application. 

#### Article quality
This is an in-depth article targeted at beginner JavaScript developers. This tutorial will cover the entire process of importing Skeleton to your application and using it to design the UI. It also provides handy tips on how to go about using the HTML 5 Canvas in your JavaScript project. 

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Nomzy-kush 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
