### ISSUE TITLE
Introduction to unity engine 

### ISSUE THREAD

**Issue by mohamedgh16** [section-engineering-education/engineering-education#5767]
### Writing sample(s): 
https://www.section.io/engineering-education/getting-started-with-game-development-windows-forms/
https://www.section.io/engineering-education/getting-started-with-inheritance-using-c/
https://www.section.io/engineering-education/understanding-polymorphism-using-abstract-classes-in-c/

#### Proposed title of article
Introduction to unity engine using c#

#### Proposed article introduction
Unity engine is one of the strongest engines in game development and it's one of the easiest engines that would help a programmer begin his journey in the gaming development industry. In this tutorial, we will explain the interface of the engine and understand how to create different objects, manipulate them and compose them together, we will also use prefabs to enhance the ability to reuse and edit different objects.

#### Key takeaways 
- engine interface
- create, edit, compose objects
- prefabs

#### Article quality
This tutorial will go in depth on how to understand the interface of the engine and will explain in detail how to work with unity objects. The reader will be able to work step by step while reading this tutorial.

#### References
https://unity.com

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @mohamedgh16

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
