### ISSUE TITLE
Adding A layer Of Security To Flask APIs

### ISSUE THREAD

**Issue by Curiouspaul1** [section-engineering-education/engineering-education#5768]
#### Introduction

When building web applications, it is important to keep your applications as secure as possible to keep your information safe and unsniffed from cyberbullies and hackers. This is why in this article, I am going to be showing you how to add security to your Flask web applications, more specifically I will go into detail about the different options you have for adding security to your REST APIs using some common security measures. I won't be showing you how to invent your own security standard in this article - I don't think I could even if I wanted to, I would however be showing you the different options available to you, with some examples on how to implement them in Flask applications, and even show you how to make some use of more than one of them to improve the overall security and resilience of your application to attacks.

#### Key Takeaways:

At the end of the tutorial, readers would have learned the following:

- Difference between Authentication and Authorization
- Flask Sessions to manage user sessions between requests
- Security using JWTs (access tokens, refresh tokens, CSRF)
- Security using CORS policies
- Role-Based Access Control
- Rate Limiting

**Comment by lalith1403** [comment]
Isn’t this topic covered widely? How will this article be different from what exists already?

**Comment by Curiouspaul1** [comment]
For one, its tailored to flask developers, and it aggregates all the information in one place. Typically you'd have to search for the info from all the different sources online. My aim is to show flask developers how to implement these concepts into their flask applications.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @Curiouspaul1

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
