### ISSUE TITLE
[Languages]Quick Response code crash course using Angular 12

### ISSUE THREAD

**Issue by owinowendy** [section-engineering-education/engineering-education#5770]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

#### Proposed title of article
Quick Response code crash course using Angular 12

#### Proposed article introduction
In this short course, I will help readers understand the concepts of quick response codes using Angular. We will build a sample project with all key concepts on how to build real-world apps using such codes that help in user authentications.
#### Key takeaways 
- What are the quick response codes in Angular?
- How quick response codes work in Angular?
- How to integrate quick response codes in Angular
- Testing our sample project.

**Comment by owinowendy** [comment]
A very unique content that aims at walking readers through by building a real-world project.

**Comment by lalith1403** [comment]
What is the real-world project under consideration?

**Comment by lalith1403** [comment]
Also, update the topic submission according to the issue template and resubmit.

**Comment by owinowendy** [comment]
> What is the real-world project under consideration?

A sample project that will help readers build real-world applications such as authentications.

**Comment by owinowendy** [comment]
> Also, update the topic submission according to the issue template and resubmit.
done!

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by owinowendy** [comment]
I'm ready to work on this!
