### ISSUE TITLE
How to setup distributed database (MySQL) using Virtualbox and Linux VMs

### ISSUE THREAD

**Issue by ochienglydia** [section-engineering-education/engineering-education#5771]
#### Proposed title of article
How to setup distributed MySQL using virtualbox and Linux VMs
#### Proposed article introduction
In this article, I will walk the reader through the concepts of database replication. We set up the entire system on the virtual machine and setup the IP addresses, using the DHCP. The machines are then set up to be able to communicate with each other remotely.

We then ensure that the fragmented and replicated databases affect are in sync with each other.
#### Key takeaways 
- Intro to concepts of database fragmentation and replication
- Intro to virtual machines and how they work
- Setting up our VMs to use remote IPs instead of localhost
- Enabling communication among the 4 devices
- Testing the distributed MySQL.

**Comment by WanjaMIKE** [comment]
Is this a software-centric topic? It seems to sway more on the hardware side.

**Comment by ochienglydia** [comment]
This is software related topic @WanjaMIKE!

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
