### ISSUE TITLE
[Languages]How to Deploy a PHP application using Docker-compose

### ISSUE THREAD

**Issue by Tonnysage** [section-engineering-education/engineering-education#5777]
### Topic Suggestion
How to Deploy a PHP application using Docker-compose

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-invoke-a-soap-web-service-in-java/

#### Proposed title of article
How to Deploy a PHP application using Docker-compose

#### Proposed article introduction
A webserver, a relational database database systems, and the language interpreter make up most PHP application. In this article I will use docker to run a full PHP application stack.
I will make a simple application that pulls a list of cities from a database and present it on a web page.

#### Key takeaways 
1. Configure out a working environment
2. Configure PHP container
3. Execute commands inside the container
4. Configure Nginx container
5. Configure MYSQL container
6. Build a PHP application

#### Article quality
My article will focus on making  simple a application that pulls a list of things from a database and present it on a web page. Most contents from the web usually ignore developing application examples, which will be my major concern.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
How is this topic different from these issues https://github.com/section-engineering-education/engineering-education/issues?q=Docker-compose+  ?

**Comment by Tonnysage** [comment]
@WanjaMIKE 
In this topic, I will create and configure a PHP project to develop an application. I will also develop basic application functionality and test it against the data entered in a sample database as opposed to what are in these https://github.com/section-engineering-education/engineering-education/issues?q=Docker-compose+

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by kimkimani** [comment]
> @WanjaMIKE In this topic, I will create and configure a PHP project to develop an application. I will also develop basic application functionality and test it against the data entered in a sample database as opposed to what are in these https://github.com/section-engineering-education/engineering-education/issues?q=Docker-compose+

https://www.section.io/engineering-education/dockerized-php-apache-and-mysql-container-development-environment/
