### ISSUE TITLE
How to Build a Discord Bot that gives Workout Tips 

### ISSUE THREAD

**Issue by khabdrick** [section-engineering-education/engineering-education#5778]
### Writing sample(s): 
https://www.section.io/engineering-education/dockerized-django-application-with-github-actions/
#### Proposed title of article
How to Build a Discord bot that gives Workout Tips 

#### Proposed article introduction
The Discord Bot the reader will be building will send fitness tips to people on the Discord server when a particular message is sent. Members of the server can create, delete and view a list of workout tips. 

ONLY viable topics to pick from:

- Languages

#### Key takeaways 
The Discord Bot the reader will be building will send fitness tips to people on the Discord server when a particular message is sent. Members of the server can create, delete and view a list of workout tips. 

#### Article quality
My article is unique

**Comment by WanjaMIKE** [comment]
Building Discord bots is covered in these articles https://github.com/section-engineering-education/engineering-education/issues?q=discord+bot How will your topic be unique?

**Comment by khabdrick** [comment]
@WanjaMIKE I checked the blog and the link to the article about discord bot in Python is broken so I can't tell how I can make mine more unique.

I will show how to build CRUD functionalities on the bot and also use Flask to make the bot run independent.

**Comment by khabdrick** [comment]
Hello @WanjaMIKE  will this work or should I pitch another topic?

**Comment by khabdrick** [comment]
@WanjaMIKE can you please take a look at this again?

**Comment by WanjaMIKE** [comment]
You seem to have another open PR. Let's wait until its published. Thanks
