### ISSUE TITLE
[Android] Implementing Subscriptions And In-App Purchases In Android Using Qonversion

### ISSUE THREAD

**Issue by Collince-Okeyo** [section-engineering-education/engineering-education#5780]
### Topic Suggestion
[Android] Implementing Subscriptions And In-App Purchases In Android Using Qonversion

#### Proposed title of article
Implementing Subscriptions And In-App Purchases In Android Using Qonversion

#### Proposed article introduction
Qonversion is the data platform to power in-app subscription revenue growth. Qonversion allows fast in-app subscriptions implementation. It provides the back-end infrastructure to validate user receipts and manage cross-platform user access to paid content on your app, so you do not need to build your own server. Qonversion also provides comprehensive subscription analytics and out-of-the-box integrations with the leading marketing, attribution, and product analytics platforms.

#### Key takeaways 
- What is Qonversion
- Reasons for using Qonversion
- Implementing Subscriptions And In-App Purchases using Qonversion
- Limitations of using Qonversion

#### Article quality
The article will be unique because of the following reasons:
- It will help beginners understand Qonversion easily.
- It will be in Kotlin programming language
- It will use Jetpack Compose for layout design
- It will be beginner friendly

#### References
- https://documentation.qonversion.io/docs/android-sdk

**Comment by WanjaMIKE** [comment]
https://www.youtube.com/watch?v=GontvAmFTcM

**Comment by WanjaMIKE** [comment]
I think this article covers same concepts such as those in the above YouTube video (check link). How will it be different?

**Comment by Collince-Okeyo** [comment]
Hello @WanjaMIKE , am pleased with the question you asked. This article is going to allow the reader to learn how to make the subscriptions purchases with the payment services like M-PESA and PayPal which are not covered in the tutorial. I will major more on making the purchases with M-Pesa Daraja integration.  This article will also provide a documented reference which is missing the Youtube tutorial.

**Comment by Collince-Okeyo** [comment]
Hello @ahmadmardeni1 and @louisefindlay23 . Can I please proceed with writing this article

**Comment by ahmadmardeni1** [comment]
Let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Collince-Okeyo

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just wanted to follow up on this topic, as we will be clearing up the queue where possible. 
 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍
