### ISSUE TITLE
[Android] How To Implement Slices In Android Using Kotlin

### ISSUE THREAD

**Issue by Rose-Meghan** [section-engineering-education/engineering-education#5781]
### Topic Suggestion
[Android] How To Implement Slices In Android Using Kotlin

#### Proposed title of article
How To Implement Slices In Android Using Kotlin

#### Proposed article introduction
In Android Pie, Google released a new API called Slices. Slices are part of Android Jetpack Support library. Slices are part of smaller UI template to display content of your app in Google Search App. It helps user perform the work at faster rate outside of your app.

#### Key takeaways 
- What is Slice
- How to implement Slices in Android
- Advantages of Slices in Android app
- How to design slices using Jetpack compose

#### Article quality
In this article I will use Jetpack compose to design the Slices and implement their functionality using Kotlin. This will ensure that it is beginner friendly. Being Jetpack Compose is a new native design for designing layouts, it will help learners to know new things.

#### References
- https://developer.android.com/guide/slices

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
