### ISSUE TITLE
Understanding Smart Contract in ASP.NET Application 

### ISSUE THREAD

**Issue by munenekelvin** [section-engineering-education/engineering-education#5786]
#### Proposed title of article
Understanding Smart Contract in ASP.NET Application 

#### Proposed article introduction
A smart contract is a computer program in which the parties agree on the terms of the agreement. Self-executing smart contracts are stored and executed on the blockchain. When the predetermined criteria are satisfied, it begins to run. Transactions may be done without the need for a third party and the transactions are irreversible, transparent, and traceable thanks to smart contracts. 

Using the Strati's blockchain, this article explains how to get started with C# Smart Contracts. C# Smart Contract creation utilizing the Stratis blockchain will be covered in this post, including how to set up a Visual Studio environment for creating a Stratis Smart Contract template. And in addition, I'll walk you through the process of setting up a Stratis private blockchain network in your development environment. This article provides a beginner's introduction to C# Smart Contract creation on the Stratis Blockchain using Stratis C#.

#### Key takeaways 
- Installing and configuring the Stratis Smart Contract Template in Visual Studio
- Using the Stratis Smart Contract Template in C#, create a smart contract project.
- What is the purpose of the Sct Program?
- How to Verify a Smart Contract's Integrity
- Smart Contract Bytecode may be generated using this method
- Defintion of Full Node
- Full Node in a Development Environment: How to Make It Work

#### Article quality
This tutorial will go in depth on how to understand the smart contract in ASP.NET application and will explain in detail how to write a smart contract. The reader will be able to work step by step while reading this tutorial.

#### References
N/A

**Comment by WanjaMIKE** [comment]
I found this article quite similar to https://www.c-sharpcorner.com/article/implementing-smart-contract-in-asp-net-application/ Therefore, I believe it will not add much value to readers. Feel free to suggest another issue. Thanks
