### ISSUE TITLE
Getting Started with Naive Bayes Algorithm in ML

### ISSUE THREAD

**Issue by HEking2** [section-engineering-education/engineering-education#5787]
### Topic Suggestion
Getting Started with Naive Bayes Algorithm in ML

#### Proposed article introduction
Naive Bayes is a probabilistic machine learning algorithm that can be used to solve a wide range of classification problems. Typical applications include spam filtering, document classification, sentiment prediction, and so on. It is named after Rev. Thomas Bayes (1702?61) and is based on his works. But why is it referred to as 'Naive'? The term naive refers to the assumption that the features that comprise the model are independent of one another. That is, changing the value of one feature has no direct effect on or affects the value of any of the other features used in the algorithm.

#### Key takeaways 
- What's Naive Bayes Algorithm?
- Uses of  Naive Bayes Algorithm 
- Advantages and disavantages of Naive Bayes Algorithm in ML
- How Naive Bayes Algorithm works

#### Article quality
In my article I'll take the reader vividly through the introduction to  Naive Bayes Algorithm works, it's advavantages and disadvantages. I'll also give a brief  elaboration on how to build a  basic model using Naive Bayes Algorithm and how Naive Bayes Algorithm works. I'll make sure to use simple grammar hence my article will be beginner-friendly

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Introductory aspects of Naive Bayes Algorithm are already covered in numerous articles including https://github.com/section-engineering-education/engineering-education/issues?q=Naive+Bayes+Algorithm+ Feel free to suggest another topic. Thanks
