### ISSUE TITLE
[Node.js] How to apply the Node Package Manager on windows

### ISSUE THREAD

**Issue by Emma-UON** [section-engineering-education/engineering-education#5788]
### Topic Suggestion
 How to apply the Node Package Manager on windows

### Writing sample(s): 
N/A

#### Proposed title of article
 How to apply the Node Package Manager(NPM) on windows 

#### Proposed article introduction
Node.js is a lightweight and scalable JavaScript runtime environment for the backend. It is used to create Realtime applications like video streaming apps. Node.js developers designed a package manager to make development easier. The Node.js command line is controlled by this package manager. It is used to set up modules and get projects started.

#### Key takeaways 
1. Install NPM in windows
2. Initialize a project using NPM
3. Setting _config_ options for the _init_ command
4. Install modules using NPM
5. Install Modules Globally on my System

#### Article quality
This article will guide the reader through the entire process of installation and updating Node.js and NPM on a windows PC or desktop, as well as other essential Node.js commands.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value. Feel free to suggest another topic. Thanks
