### ISSUE TITLE
How to install Word press on LEMP with ubuntu or debian

### ISSUE THREAD

**Issue by Lavenda99** [section-engineering-education/engineering-education#5789]
### Topic Suggestion
How to install Word press on LEMP with Ubuntu or Debian

### Writing sample(s): 
N/A
#### Proposed title of article
How to install Word press on LEMP with Ubuntu or Debian

#### Proposed article introduction
Today, WordPress is the most popular content management system (CMS) on the web. The open source platform has a variety of tools and themes that make website creation simple for various types of users. WordPress websites, on the other hand, require a high performance web server like Nginx to rank well in search engines and improve user experience.

This guide will show you how to install WordPress using the LEMP stack on Ubuntu 20.04 or Debian 11. The abbreviation LEMP stands for Linux, Nginx, WySQL and PHP.
#### Key takeaways 
1, Create the WordPress Database
2. Configure Nginx
3. Install and Configure WordPress

#### Article quality
This article will guide the reader on how to install WordPress using the LEMP stack on Ubuntu 20.04 or Debian 11. The abbreviation LEMP stands for Linux, Nginx, WySQL and PHP with deep explanation and examples in each step. 

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Based on this search https://www.google.com/search?q=How+to+install+Word+press+on+LEMP+with+ubuntu+or+debian&oq=How+to+install+Word+press+on+LEMP+with+ubuntu+or+debian&aqs=chrome..69i57j69i61.358j0j4&sourceid=chrome&ie=UTF-8, the content seems to be easily accessible or over saturated on other blog sites. Feel free to suggest another topic. Thanks
