### ISSUE TITLE
[API] Hand on understanding Low-code and BaaS with Hypi

### ISSUE THREAD

**Issue by fabulousDesigns** [section-engineering-education/engineering-education#5798]
### Writing sample(s): 
- https://www.section.io/engineering-education/learn-how-to-set-up-linux-quagga-routing-suite/
- https://www.section.io/engineering-education/sql-injection-made-familiar/
- https://www.section.io/engineering-education/understanding-and-working-with-javascript-cookies/

#### Proposed title of article
Hand on understanding Low-code and BaaS with Hypi

#### Proposed article introduction
Low code is a method of developing software that requires little or no coding. Low code saves developers time and allows them to produce apps faster. Citizen developers can employ low code to construct Apps. Expert developers can employ low code to save time. Businesses use low-code technology to release apps faster. First, we'll look at Low Code's features, then Hypi, the most feature-rich Low Code backend!

#### Key takeaways 
- By the end of this article learners will be proficient in the following:
1. Understand what exactly Low Code is
2. Low Code Development Platform
3. Importance of Low Code Platform
4. Understand the projects being delivered using Low Code
5.  Getting started with BaaS
6.  Features of BaaS?
7. What can you do with Hypi
8. What does Hypi Offer
9. How to get started with Hypi

#### Article quality
The year is 2021! If a developer is still writing all of the code for developing applications from scratch, he is living in the 1990s! We are in the future, and the future is low code, therefore it is great for developers  at all levels to understand the trend of constructing an application without writing a single line of code, or even developing serverless applications for the growth of IT organizations in general. Learners will find this article to be one-of-a-kind because it will provide developers of any expertise with everything they need to get started with Hypi and develop applications like pros.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, what you are proposing to write is already covered in this article https://phppot.com/web/introduction-to-low-code-and-baas-with-hypi/. In fact, you appear to copy some content directly from it such as ```The year is 2021! If a developer is still writing all of the code for developing applications from scratch, he is living in the 1990s! We are in the future, and the future is low code.``` Feel free to suggest another topic. Thanks
