### ISSUE TITLE
Analyzing Tabular Data With Python and Pandas

### ISSUE THREAD

**Issue by Ainea-Amush** [section-engineering-education/engineering-education#5800]
### Writing sample(s): 
N/A

#### Proposed title of article
Analyzing Tabular Data With Python and Pandas

#### Proposed article introduction
Python is one of the best programming languages which has the capability to analyze data of different forms.it is also a very useful language in data visualization where data analyzed can be represented into charts, graphs, and other visuals. Pandas is a python package that provides highly optimized performance for data manipulation and performance.

In this article, I will be showing how to fetch collected and stored in tables and make analysis from and come up with conclusions which the reader will be able to implement in the decision he or she wants to make.

#### Key takeaways 
From this article, the reader will get an understanding of:
- How to analyze tabular data with python and pandas
- How to fetch data in tables and work with it in Pandas package
- Be able to interpret data analyzed and represented in charts, graphs, and other visuals

#### Article quality
In this article, I will be taking the reader step by step on how to analyze tabular data using Python and Pandas.
In addition,the readers will get to know how to download pandas package and how to implement it in data analysis.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appears to be adequately covered based on this search https://github.com/section-engineering-education/engineering-education/issues?q=pandas Feel free to suggest another topic. Thanks
