### ISSUE TITLE
Getting started with pragmatic navigation in SwiftUI

### ISSUE THREAD

**Issue by okeloviolet** [section-engineering-education/engineering-education#5801]
### Topic Suggestion
Getting started with pragmatic navigation in SwiftUI

### Writing sample(s): 
Include any links or writing samples to help our team gauge your writing quality better.

#### Proposed article introduction
The navigation APIS that SwiftUI comes with is biased towards user interaction. Therefore, the navigation is handled based on the system response to user interaction, i.e., the user taps on a button or a link.

If we want to control how our application navigation is handled, we can use the Navigation APIS provided by SwiftUI. However, they are not as flexible as the ones provided by UIKit. SwiftUI provides a few ways to handle pragmatic navigation using the NavigationLink API within the views we create.

The SwiftUI navigation system is not as flexible and easy to implement as the ones provided by UIKit. However, it gives many ways to handle different use cases, mainly with SwiftUIs state management APIS.

The article will explain how to implement dynamic view navigation in SwiftUI in an IOS application.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.
1. Controlling navigation stacks.
2. Navigating through tabs.
3. Pragmatic/Dynamic navigation between views.

#### Article quality
The article covers dynamic navigation, switching through tabs, and controlling navigation stacks in depth. Unfortunately, the published articles only cover this topic in UIKit, making it hard to implement in SwiftUI.

#### References
Would you please list links to any published content/research that you intend to use to support/guide this article?
N/A

**Comment by WanjaMIKE** [comment]
Will you create an app to demonstrate these concepts? @okeloviolet

**Comment by okeloviolet** [comment]
Hello @WanjaMIKE, I will create an app to demonstrate these concepts

**Comment by WanjaMIKE** [comment]
Closed #5801 via #6237
