### ISSUE TITLE
How to secure PHP resources with HTTP authentication

### ISSUE THREAD

**Issue by JOEOBY** [section-engineering-education/engineering-education#5803]
### Topic Suggestion
How to secure PHP resources with HTTP authentication
#### Proposed title of article
How to secure PHP resources with HTTP authentication
#### Proposed article introduction
HTTP authentication is the procedure of figuring out and verifying customers' credentials to ensure they are permitted to get right of entry to an internet resource. To save you unauthorized get right of entry to to your php web application, you can defend sensitive files or endpoints the use of a username and a password. One commonplace manner of achieving this is with the aid of the use of simple HTTP authentication. on this protection design sample, each person making a request to a aid to your server should publish an Authorization header containing Base64 encoded credentials.
#### Key takeaways 
1. Editing the Apache configuration file
2. Enabling Apache ```mod_rewrite``` module
3. Creating a password protected PHP file
4. Modifying the ```.htaccess``` file
5. Testing HTTP Authentication
#### Article quality
In this article, a step by step procedure of how to create a password protected PHP web resources will be elaborated well and in a clear steps. It is a beginner friendly article with easy to understand illustrations.

#### References
N/a
### Conclusion
We've created a password protected PHP files for web resources using HTTP Authentication with Ubuntu server. This is useful since many users are forced to pass their information through secure HTTP.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
How does your article differ from other [articles ](https://www.google.com/search?q=How+to+secure+PHP+resources+with+HTTP+authentication&oq=How+to+secure+PHP+resources+with+HTTP+authentication+&aqs=edge..69i57j69i60.5277j0j4&sourceid=chrome&ie=UTF-8)? @JOEOBY

**Comment by JOEOBY** [comment]
Hey @ahmadmardeni1 my article will explore the basics fundamentals of PHP resources, give detailed content about it with a simple and understandable language guiding readers on how to use HTTP Authentication to secure it.
The referred documentation simply contains an illustrative example but my article will explain step by step elaboration on how to secure PHP resources with HTTP Authentication. My tutorial is going to explore the fundamentals of how to create a password protected PHP files for web resources using HTTP Authentication with Ubuntu server.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @JOEOBY 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by ahmadmardeni1** [comment]
I'm closing this topic-suggestion due to inactivity.
It can be reopened.

**Comment by JOEOBY** [comment]
@ahmadmardeni1 i have finalized and i can PR now you can reopen, sorry for the inconveniences caused,
