### ISSUE TITLE
Getting started with MySQL subqueries

### ISSUE THREAD

**Issue by faithsiaji** [section-engineering-education/engineering-education#5804]
### Topic Suggestion
Getting started with MySQL subqueries

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Getting started with MySQL subqueries
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
MySQL subquery is a query executed within the context of another query. They are also known as inner queries or nested queries. The query within which the subquery is performed is called the parent query or an outer query.

Subqueries can be within SELECT, INSERT, UPDATE, DELETE, and REPLACE statements. Subqueries are often written after the WHERE and FROM clauses to fetch data as a column.

Dynamic execution in SQL is a technique that allows a query to be executed at runtime. This is done by using a subquery within a query. The result of the subquery is used as the value of a column in the main query.

When subqueries are not used, the query is first executed, and the result is stored in a temporary table. Then the query is executed again, and the result is stored in another temporary table. The result of the second query is then used as the value of a column in the first query. This involves performing two queries that could have been performed in one when we used the subquery.

I  will explain how to use subqueries in a Spring Boot application and MySQL database.

#### Key takeaways 
1. Types of subqueries.
2. MySQL subqueries.
3. Setting up MySQL subqueries in a Spring Boot application.

#### Article quality
The article will explain various types of MySQL queries in-depth and implement them in a Spring Boot application. Most of the published articles only explain how to perform SQL subquery calls but not how to use subqueries in real-world application scenarios.

#### References
N/A

**Comment by WanjaMIKE** [comment]
After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to suggest another topic. Thanks
