### ISSUE TITLE
[LANGUAGES] Improving User Experience With Code Splitting and Content Delivery Networks

### ISSUE THREAD

**Issue by Su-sid** [section-engineering-education/engineering-education#5806]
### Topic Suggestion
Improving User Experience With Code Splitting and Content Delivery Networks

### Writing sample(s): 
[stateful-vs-stateless-architectures](https://www.section.io/engineering-education/stateful-vs-stateless-architectures/)
[network-troubleshooting-using-traceroute](https://www.section.io/engineering-education/network-troubleshooting-using-traceroute/)
[understanding-quality-of-service](https://www.section.io/engineering-education/understanding-quality-of-service/)

#### Proposed title of the article
Improving User Experience With Code Splitting and Content Delivery Networks

#### Proposed article introduction

Websites are a great source of information in this modern era. However, every website is measured as per its appeal to its users in terms of its general performance. There has been an increase in website performance and user experience(UX) from developers who have implemented content delivery network(CDN) services and efficient coding techniques such as code splitting. But, how can one archive fast page loading with the stated techniques? This article seeks to expound on the art of code splitting and how to implement Sirv, a CDN service, to boost page performance and improve UX for your next creation.

#### Key takeaways 
- A look into the art of code splitting.
- Implementation of code splitting in vanilla JS and Jquery.
- How to use Sirv, an image optimization, processing and hosting service.
- A bonus on how to refactor your code to increase performance.

#### Article quality
While other blogs only feature a shallow dive into one of the topic areas to be covered in this article, the article will feature a deeper dive into how to implement code splitting using two popular js frameworks and how to use Sirv.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Su-sid 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
