### ISSUE TITLE
Introduction to handle and handle pruning in compiler design

### ISSUE THREAD

**Issue by root5086** [section-engineering-education/engineering-education#5808]
#### Proposed article introduction
A handle is defined as a right-sentential-form that matches the right side of  a production and whose reduction to the left side non-terminal represents a single step along the reverse of a rightmost derivation.  

Handle pruning on the other hand is the process of identifying a handle and reducing it to the appropriate left hand side and it forms the basis of bottom up parsing in compiler design. Being that most compilers uses bottom up parsing strategy, handle pruning is considered key and very important in achieving parsing.

In this article I will be introducing a reader to the concept of handles through definition and discussing it at length for good understanding. I will then go ahead and introduce the reader to the concept of handle pruning and concluding with a formal definition of both. We will then go ahead to discuss using example the implementation of handle pruning as used in bottom up parsing.
A handle is defined as a right-sentential-form that matches the right side of  a production and whose reduction to the left side non-terminal represents a single step along the reverse of a rightmost derivation.  

#### Key takeaways 
1. The reader will be able to understand the concept of handle and handle pruning as used in bottom up parsing.
2. The will be able to identify a handle in a production and be able to reduce it to the start non-terminal during bottom up parsing.
3.  The reader will be able to implement handle pruning using code illustrations for bottom up parsing.

#### Article quality
This article will be made up of  illustrative content that is easy to understand even in the case of first time readers. It will also be exhaustive of all the concepts involved in handle and handle pruning based with a clearly defined introductory base. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @root5086 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
