### ISSUE TITLE
[LANGUAGES] Manipulating Excel(Spreadsheet) data and files in Android using the Apache POI library

### ISSUE THREAD

**Issue by vinstex** [section-engineering-education/engineering-education#5810]
### Topic Suggestion
[ANDROID || LANGUAGES] Manipulating Excel(Spreadsheet) data and files in Android using the Apache POI library

### Writing sample(s): 
My samples are found [here](https://www.section.io/engineering-education/javascript-math-animations/)

#### Proposed title of the article
Manipulating Excel(Spreadsheet) data and files in Android using the Apache POI library

#### Proposed article introduction
Maybe you are trying to preprocess data for some custom on-device model or you want to create your own spreadsheet app, you have to know how to first manipulate the spreadsheets. In his article, we will look at creating a spreadsheet file, opening it, and then performing common statistical functions in it.

#### Key takeaways 
The user will learn about:
- Accessing spreadsheets in Android.
- Using Kotlin to implement this.
- Performing common statistical functions such as mode, median, variance, standard deviation, etc.
- Additionally, how Retrofit plays a hand in this.

#### Article quality
It will be simple to follow and guide the user on getting the files from local storage. We will also perform the statistical functions, something other blogs haven't shown.

> We might also look at saving changes done to a spreadsheet. I'm still doing my research on this.

#### References
I used [this](https://www.geeksforgeeks.org/how-to-read-data-from-google-spreadsheet-in-android/) to get insights. It talks about reading one from Google Sheets.

**Comment by LinusMuema** [comment]
good topic @vinstex - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
