### ISSUE TITLE
Concatenated strings vs ES6 template literals in React

### ISSUE THREAD

**Issue by gatwirival** [section-engineering-education/engineering-education#5811]
#### Proposed title of article
Concatenated strings vs ES6 template literals in React

#### Proposed article introduction
String concatenation is the process of joining one string to the end of another string, for example  concatenation of "happy" and "holiday" is "happy holiday"
Template literals are literals bound with back-ticks (`) allowing embedded expressions called substitutions.Template string are sometimes informally called template strings, however they are not string literals and can not be used everywhere a string literal can be used. Template literals provide us with an alternative to string concatenation .They also allow us to insert variables  in to a string.

#### Key takeaways 
- What is concatenated strings
- What is ES6 template literals
- How to concatenate strings in React
- How to use template literals in React
- Difference between concatenated strings and template literals
- Adding variables in to string using ES6 template literals

#### Article quality
In this article the reader will learn about how to use concatenated strings and es6 template literals, what they are,their differences, how to add variables in to string using es6 template literals and their advantages and disadvantages.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appears to be oversaturated on other blog sites and official documentation. Feel free to suggest another topic. Thanks
