### ISSUE TITLE
Introduction to Logical Operators in Java

### ISSUE THREAD

**Issue by Gladysoby** [section-engineering-education/engineering-education#5815]
### Topic Suggestion
Introduction to Logical Operators in Java

#### Proposed title of article
Introduction to Logical Operators in Java

#### Proposed article introduction
Logical operators are used for performing the operations on one or  variables for evaluating and retrieving the logical outcome. normally, the return value for logical operations is in boolean format and is applied in a software to establish better control inside the program’s execution float. In Java, the logical operators used are ‘&’ for acting AND operation, ‘|’ for OR operation, ‘!’ for now not operation, and ‘^’ for XOR operation.

#### Key takeaways 
a) features of logical Operator
b) Logical AND Operator “&”
c) Logical OR Operator “ |.”
d) Logical NOT Operator “!” or “ ~.”
e) Logical XOR Operator “ ^.”

#### Article quality
This article will provide a step by step elaboration on the Logical operators condition statements. Its a beginner friendly guide on easy understand of logical Operator in Java.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
n/a
### Conclusion
We've learned the basics of logical Operator in Java and in an understanding way. The most essential gain of the logical operator is it reduces the code complexity. as an instance, it reduces the number of if…else conditional statements. This circuitously blessings in code compilation, run time and so forth.…normal code performance is extended.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to suggest another topic. Thanks
