### ISSUE TITLE
Getting started with mix package in flutter applications

### ISSUE THREAD

**Issue by joni-kano** [section-engineering-education/engineering-education#5816]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Getting started with mix package in flutter applications

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Today, I am going to introduce you guys about how use mix package that provides by flutter team. For those who don't know flutter yet, you can read  other article  for introduction of flutter.

Mix is the first class support by Flutter Team for native app development in dart programming language. It defines a set of tools and APIs to help you write, build and test your Flutter app.

In this article I will show you how to use Mix Package in flutter apps.

1. Add dependency of mix package in your pubspec.yaml file.

dependencies: flutter_tools: sdk: flutter mix: ^0.4.3+2

After add this line you need to restart your IDE so that the IDE will get new dependencies list automatically and it can find which libraries are using in project folder.

2. Now create a new directory inside lib folders named as mix . Define main function which will use to run our app for now. The main method is necessary at the moment because you need to hold your app until flutter tools finish it's magic work before exit from main function.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
(1) How to use Mix Package For Widget development

(2) How to use Mix Package For Unit Test

(3) How to get information about your flutter project

(4) How to use Autotest for your flutter project

(5) How to add the missing dependency in your flutter project.

#### Article quality
This article is unique because it will teach you how to work with mix package which provide by flutter team.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
There are some significant readability challenges in your description that raise concerns over how much review/editing would be required from our peer review team. We don't provide editing services and recommend that students leverage online editing services (there are both free and paid services that you can explore), or try engaging with the community or other peers in your network to have them review prior to submitting a revised proposal. Thank you.
