### ISSUE TITLE
Python Machine Learning for Cross-Sale Prediction

### ISSUE THREAD

**Issue by MeshiJohn** [section-engineering-education/engineering-education#5821]
### Topic Suggestion
Python Machine Learning for Cross-Sale Prediction

#### Proposed article introduction
If you're new to data science or machine learning, it's critical to have a mentor and exposure to a diverse range of projects.

To get started with machine learning, we'll go over a simple cross-sell prediction project. You'll learn the fundamentals of tackling a prediction problem.
#### Key takeaways 
- Problem Statement for Cross-Sell Prediction Problem
- Implementation of Cross Sell Prediction in Python
- Cross-Sell Prediction – Model training and prediction

#### Article quality
This article talks about cross-sell prediction in great detail. Cross-sell prediction is a very common problem with machine learning that is important in the business. Codes are shown in the article to make it easier for people to understand and to keep them on the page for a longer time. The article is meant to be short and to the point, but not too long or too short.
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @MeshiJohn 

We have to close the article as your suggestion has various sections copied verbatim from [this](https://www.analyticsvidhya.com/blog/2021/09/cross-sell-prediction-using-machine-learning-in-python/) article. We lean towards original content and so to prevent the inevitable closure in the plagiarism stage of the review, we have to close the article.


Feel free to explore other topics and areas of interest.
