### ISSUE TITLE
[Languages] Dart List Datatype Methods

### ISSUE THREAD

**Issue by Eze4Manuel** [section-engineering-education/engineering-education#5823]
### Topic Suggestion
[Languages] Dart List Datatype Methods

#### Key takeaways 
- Clear understanding of all the methods available in the dart for its List data type
- Practical examples that are applicable during programming on a project
- Hub of all methods available. 

#### Article quality
While working on a mobile application project  I came across the need to check out what method to apply to a List in dart. I looked up the methods dart programming language has for its List data type, I could not find a singular hub where all the methods are explained with simplicity and clear example codes. They are a handful of recently added methods to the dart List and one source I came across was written as far back as 2019, was not up to date, and did not explain the functions of the methods in a clear simple way.

#### References
https://api.dart.dev/stable/2.15.1/dart-core/List-class.html
https://medium.com/flutter-community/useful-list-methods-in-dart-6e173cac803d

**Comment by WanjaMIKE** [comment]
Concepts on List data types are well-covered in numerous tutorials and documentations. Therefore, this topic will not be of much value. Feel free to suggest another topic. Thanks

**Comment by Eze4Manuel** [comment]
> Concepts on List data types are well-covered in numerous tutorials and documentations. Therefore, this topic will not be of much value. Feel free to suggest another topic. Thanks

The topic is List Data type in Dart programming Language ( The language used in flutter applications ) and not just any language. There are few in-depth resources on this topic. If you check around. The available ones are not all that in-depth and do not cover all the recently added methods. Dart has a lot of methods that you cannot find online as I myself tried searching for a quick description while working on a project. This is a topic lacking on the internet.
