### ISSUE TITLE
Understanding Selenium Architecture and Frameworks

### ISSUE THREAD

**Issue by stanley886** [section-engineering-education/engineering-education#5824]
### Topic Suggestion
Understanding Selenium Architecture and Frameworks.
#### Proposed title of article
Understanding Selenium Architecture and Frameworks.
#### Proposed article introduction
Selenium is an open source software automation testing which is commonly used. It makes it possible to test any kind of web application because it supports  automation framework.
Selenium is composed of four elements which are, integrated Development environment for selenium, remote control, grid and Web Driver. The four elements combined makes, are utilized for automation testing.
Selenium framework, is the workspace created to mould a code for automation process of a web-base application. This framework makes it easier to maintain a code, enhance efficiency and allow multiple programmers to comfortably enhance the code. Several framework are supported by selenium which we are going to cover.
#### Key takeaways 
- Architecture for Selenium
   - Remote control.
   - Web drive.
   - Integrated Development Environment.
   - Grid.
- Framework
  - Types of Frameworks supported by selenium.
  - Components of Selenium framework.
  - supported file formats.
  - Creating a framework.
  - Advantages of selenium framework.
#### Article quality
In this article am going to take the user through the architecture of selenium and the numerous framework that selenium supports. Am going to user a beginner friendly language for the user to understand.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @stanley886 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by stanley886** [comment]
want to link with a PR
