### ISSUE TITLE
A Flappy bird game coding tutorial using HTML,CSS, and Javascript

### ISSUE THREAD

**Issue by KanizoRGB** [section-engineering-education/engineering-education#5825]
### Topic Suggestion
A Flappy bird game coding tutorial using HTML, CSS, and Javascript

### Writing sample(s): 

1. https://www.section.io/engineering-education/how-to-make-an-image-carousel-for-your-website/
2. https://www.section.io/engineering-education/machine-learning-libraries-in-cplusplus/

#### Proposed title of article
[Languages] A Flappy bird game coding tutorial using HTML, CSS, and Javascript 

#### Proposed article introduction
The world of gaming has been around for some decades starting from the late 20th Century. Games have provided entertainment both to children and adults alike. They have evolved from monochromatic, pixelated screens to more complex displays incorporating virtual reality. The number of gamers has also increased steadily and now around 30% of the world's population is made up of gamers. That's around 2 billion people.
As the world becomes nostalgic, evidenced by the remake of formerly loved films and the retro dressings in fashion, the gaming industry has taken a similar shift. Gamers have shown interest in simple graphics, easy-control vintage game designs. This is evidenced by the popularity of games such as Among us, Minecraft, and Fortnite.
In this tutorial, you will learn how to create a popular simple game from scratch called flappy bird, using HTML, CSS, and Javascript. The game requires input from a single control button by the user to enjoy the game. It is a good game to break the monotony of work and also an amazing project for programming beginners to hone their skills.

#### Key takeaways 

1. The reader will understand how to implement game logic in code.
2. The reader will better understand the use of events in Javascript.
3. The reader will appreciate the importance of CSS in making a project presentable to the naked eye.

What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

#### Article quality
The article is unique in the sense that it explains the code line by line, telling the reader what each statement does. Other tutorials similar to this only provide the code to be implemented and thus it is up to the user to debunk each line of code. My approach is easy to follow for someone with little knowledge of the three languages.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Based on this search https://www.google.com/search?q=A+Flappy+bird+game+coding+tutorial+using+HTML%2CCSS%2C+and+Javascript&oq=A+Flappy+bird+game+coding+tutorial+using+HTML%2CCSS%2C+and+Javascript&aqs=chrome..69i57j69i64j69i60j69i61j69i60.594j0j4&sourceid=chrome&ie=UTF-8, this topic appears to be oversaturated. We usually focus more on unique projects. Feel free to suggest another topic. Thanks

**Comment by KanizoRGB** [comment]
Hello @WanjaMIKE those tutorials you see there don't give a break down of the code line by line. It is very hard for newbies to follow along with those tutorials and thus mine would be very suitable.

**Comment by WanjaMIKE** [comment]
Unfortunately, the topic still appears to be oversaturated on other sites. Could you suggest an alternative topic. Thanks
