### ISSUE TITLE
Data representation using brython

### ISSUE THREAD

**Issue by ayodele96** [section-engineering-education/engineering-education#5827]
#### Proposed article introduction
When you hear `Brython`, it sounds like a made-up name or typography of Python. Brython is short for browser python. It is the implementation of python3 for Web development. Brython aims to replace Javascript as the language of the Web. Brython interacts with some of JavaScript's libraries to create projects they include; vue.js, phaser, bokeh, highcharts and, so on.

We aim to show readers how to represent data on the web using Brython.
#### Key takeaways 
It is a journey and, we want to take you along. We'll show the readers how to;
- Install the Brython module using the node package manager (npm).
- Create a piechart using Brython.
- Create a scatter plot using Brython.

#### Article quality
The article talks about the implementation of Python with the web without flask, rather a relatively unpopular library. 

#### References
N/A
### Conclusion
At the end of this article, the reader should be able to achieve the key takeaways listed above.

**Comment by LinusMuema** [comment]
good topic @ayodele96 - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your tutorial very beneficial.

**Comment by WanjaMIKE** [comment]
Closed #5827 via #6156
