### ISSUE TITLE
MONGO DB VS CASSANDRA DB: THE 2’S CONSIDERATION

### ISSUE THREAD

**Issue by Bankanthony** [section-engineering-education/engineering-education#5828]
#### Proposed article introduction
Database management also known as DBM, refers to the actions a business takes to manipulate and control data needed to meet the necessary conditions throughout the entire data life-cycle. In practice, numerous tools have been created and utilized for the purpose of managing different forms and volumes of data with one of the most widely used being Mongo DB and Cassandra DB. 

In this article, we'll take you on a journey of database management using Mongo DB and Cassandra DB with the end goal of providing sufficient information to future users on the suitability of these two tools particularly in the area of Speed and Security (2’S).
#### Key takeaways 
This article aims at providing information regarding:
- Mongo DB and Cassandra DB. 
- Similarities and Positives that exists in Mongo DB and Cassandra DB. 
- Evaluation of in-use difference between Mongo DB and Cassandra DB particularly on the basis of Database Security and Speed.
#### Article quality
This article provides an in-depth view of two of the most in vogue data management systems.

#### References
N/A

### Conclusion
At the end of the tutorial, the reader should be able to achieve the goals listed above and on further learning, improve their database management knowledge and usability.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. :rocket:

**Comment by Bankanthony** [comment]
@hectorkambow Good day sir. Please has this topic suggestion been overlooked? Hope there's no issue with it

**Comment by louisefindlay23** [comment]
There are several existing [articles](https://www.google.com/search?client=firefox-b-d&q=MONGO+DB+VS+CASSANDRA+DB) on this topic. Can you tell me how yours will be unique?

**Comment by Bankanthony** [comment]
Good day,

Other articles relating to the variables on review were aimed at studying
them on an individual basis.

What makes my article different from other body of knowledge is the fact
that I would be looking at both MONGO DB and CASSANDRA DB which is
different from what other articles have explored and I would now further be
doing a comparison of the usability of both databases on this basis of
speed and security.

My comparison of these databases on the basis of database speed and
security is something that hasn't been well explored by other authors.

Thank you.

Regards,
Mobolaji Femi-Ige

**Comment by Bankanthony** [comment]
@hectorkambow I have not gotten a response to this issue

**Comment by Bankanthony** [comment]
@ahmadmardeni1, the content is ready now
