### ISSUE TITLE
Getting Started With Python IDE on Linux/windows

### ISSUE THREAD

**Issue by HEking2** [section-engineering-education/engineering-education#5829]
### Topic Suggestion
Getting Started With Python IDE on Linux/Windows

#### Proposed article introduction
Python is the most widely used and versatile programming language. On Linux, there are numerous Python IDEs. An integrated development environment (IDE) is a software interface that connects the motherboard's data path to disk storage and includes an interpreter, debugger, code editor, and GUI access. It stands for Integrated Development Environment, which is software that is used to develop software using programs for creating automation tools.

So you'll need an IDE to get started writing Python programs or codes. On Linux, a variety of Python IDEs are available, including Pycharm, PyDev, Spyder, and others. The majority of Python IDEs come with code compilation, debugger, GUI builder, and other features.

#### Key takeaways 
List of Best Python IDE
Features of different python IDEs in both linux and windows
Eclipse with Pydev
IDLE

#### Article quality
This article is intended to give an step by step introduction to intergrated development environment in Python, listing out best IDEs to use in Linux and Windows operating Systems. Features of the IDEs will be discussed in this article. In my article I'll use simple grammar hence it will be beginner-friendly. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to suggest another topic. Thanks
