### ISSUE TITLE
[Language & API] Building a real-time currency converter in Django

### ISSUE THREAD

**Issue by Sajeyks** [section-engineering-education/engineering-education#5831]
### Topic Suggestion
Enter topic suggestion here...

#### Proposed title of article
[Language & API] Building a real-time currency converter in Django

#### Proposed article introduction
There are hundreds of currencies around the world and due to various reasons, we are always converting one currency to the other. The most common applications would be how e-commerce sites convert the prices of goods to the user's local currency from from the sellers currency and also comparisons of cryptocurrencies with different currencies for performance evaluation.

We will build a Django app that converts the selected currency to the desired currencies with the real-time exchange rates provided by a third party API. This will help us attain accuracy and practicality.

#### Key takeaways 
1. Setting up a Django project
2. Integrating third party APIs with Django
3. Converting Currencies in real-time
4. Securing third party APIs in Django

#### Article quality
My approach converts the currency in real-time as their exchange rates change around the world. This will make the article withstand the test of time. I also intend to explain the topic in more details.
#### References
N/A

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
