### ISSUE TITLE
[LanguageBuild Calendar in React Using React-Calendar Library 

### ISSUE THREAD

**Issue by codeInn001** [section-engineering-education/engineering-education#5832]
### Topic Suggestion
Build Calendar in React Using React-Calendar Library 

#### Proposed title of article
Build Calendar in React Using React-Calendar Library 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
React-Calendar is a simple calendar library that provides the ability to pick days, months, years, or even decades. It also supports date range selection and a variety of languages for more complex use cases.

A React calendar component is a good choice when you need to allow users to select a specific date, like if your app has a form field for date of birth or employee start date. Another good example would be an application that allows users to book appointments. A user would be able to select a specific date and time slot from available options. For scenarios like this, a calendar component is probably the best bet.

It’s a very flexible and versatile library that you can use in virtually any application.

#### Key takeaways 
The tutorial will show readers how to:

1. Integrate react-calender library into a react application.
2. How to enable date range feature using selectRange.
3. How to style and customize react-calendar
4. 
#### Article quality
The article will give a detailed guide into react-calendar library. It will explain key concepts to readers which is unavailable in the documentations and other platforms.  

#### References
N/a

### Conclusion
At the end of the tutorial, the reader should be able to achieve the goals listed above while also learning how to create useful calendars in their applications.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @codeInn001 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by codeInn001** [comment]
@ahmadmardeni1 Can you please reopen this issue, I am almost through with article.
Thanks
