### ISSUE TITLE
 understanding permission handler in flutter apps

### ISSUE THREAD

**Issue by jasminemilito** [section-engineering-education/engineering-education#5833]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
 understanding permission handler in flutter apps.

Use keyword research to improve your article's SEO.

#### Proposed article introduction
 

In android when a user wants to switch off a permission, there is always an option to switch off permissions.

Users can turn off access to required permissions for particular applications. This reason creates confusion among people who are new to android & flutter. Especially when they try to do similar activities with Flutter apps. There is no option to switch off the access for any permission.

So, what will happen if a user tries to revoke permission from flutter apps? Will it create issues in android or not? This article attempts to answer these questions.

In this article, we are going to see how Flutter apps ask permission from the user. We will also learn how to implement the logic to avoid crashes when the user revokes the permissions. We will discuss how to add the permission options in flutter apps. 

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
- adding permission requests to a flutter app.
- how the flutter engine manages permissions.
- what use cases are best for custom permission handlers.

#### Article quality
 This article explains flutter's permissions model in detail. We will be teaching you how to make custom handlers. We will show the workflow for both iOS and Google Play store permission systems. We will show use cases for custom handlers. covers Android custom permissions at a very low level, although not required knowledge.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
good topic @jasminemilito - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your tutorial very beneficial. 

From your description I can easily predict that you will use the permission_handler package. Please make sure to provide more in-depth information as you have stated in your description.

🚀

**Comment by LinusMuema** [comment]
Also, in future suggestions, please take note of this section in the conclusion:

> Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.

Make your suggestion clean so we can easily review it.
