### ISSUE TITLE
[API] Improving Availability of API Services through Rate Limiting using Bucket4j Library (Java/Spring Boot)

### ISSUE THREAD

**Issue by teevyne** [section-engineering-education/engineering-education#5838]
### Topic Suggestion
[API] Improving Availability of API Services through Rate Limiting using Bucket4j Library (Java/Spring Boot)

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
[API] Improving Availability of API Services through Rate Limiting using Bucket4j Library (Java/Spring Boot)

#### Proposed article introduction
In this tutorial, we will go into the world of API availability, security and availability. We will learn about the efficacy of the Bucket4j library and how it is used to rate-limit an Spring REST API. 

Rete Limiting in a software engineering strategy that allows creators and maintainers of API Infrastructures control access to their APIs. The number of calls that any consumer can make is checked during a particular time. By doing this, API's can be defended against abuse and unnecessary use. Rate Limiters can also serve as a means of placing consumers on payment plans, by controlling how much calls with they make within a certain plan.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- Readers will be able to secure their API's in a new way
- Readers will learn the benefits of introducing rate limiting to projects and how to do with the a lightweight Java library
- Readers will know what error codes are generated for rate limiting and how to configure error response

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Many articles out there teach you how to create REST APIs. Some teach about attack, fairly. However, not many teach you about attacks that come from multiple hits on your APIs and how to deal with this. This article goes beyond just securing APIs but securing them well, while also using this mechanism for business-related purposes.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @teevyne 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
