### ISSUE TITLE
How to Set up Rust API Servers with the Diseal ORM and the PostgresSQL

### ISSUE THREAD

**Issue by wanjcarol** [section-engineering-education/engineering-education#5840]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

ORM (Object Relation Mapping) is a common technique for storing, retrieving, updating, and deleting data from a database specifically within a relational database. Common languages such as Node.js have different ORM libraries that help you achieve the general application of ORM when connecting the database and the application. The application wants to access the data from a database. However, it cannot do that directly. An ORM helps your application connect to a database. The big advantage is that an ORM helps you create data schemas and relations within your application. Whenever you need to change a specific database field, you only so it in your application with just a few lines of codes to change. This helps you avoid the hectic work of recreating your databases every time to match your new data registry.

The concept of ORM is widely supported by a number of languages such as Rust. Rust uses the Diseal framework to help you write your schema queries within your rust application. In this guide, we learn more about the Rust Diseal and finally set up a Rust API that uses Diseal to communicate with a PostgreSQL relational database.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- What is an ORM
- What is Diseal
- Why the Diseal ORM
- Diesel migration
- Setup postgres
- Setup diesel
- Set up a Diseal Rust API server
- Write a new record to the PostgresSQL
- Show all the PostgresSQL records

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

This tutorial will help the reader learn more about the ORM and understand how to use ORM in Rust using Diseal. The reader will also be able to create a Rust API server that uses Diseal to connect to PostgreSQL then create and retrieve the data that the application has stored in the database. This will help the reader understand the use of the concept of ORM using the Rust Diseal in an ideal application.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @wanjcarol 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
