### ISSUE TITLE
 Continuous Monitoring using Nagios Plugins and ELK Stack

### ISSUE THREAD

**Issue by damikanye** [section-engineering-education/engineering-education#5844]
### Introduction
Continuous Monitoring is the ability to detect risk, compliance, and security issues in an operational environment. This acts as an auditing tool, where it can navigate through old monitoring data to analyze and improve the performance of the system. 

Roles of CM in application lifecycle :)
- Assists in the design of the reliable system
- Displays application behavior during peak business hours
- Reduces cost by acquiring precise knowledge of software asset duplication

### Key takeaways
In this tutorial, readers would have knowledge of the following:)
- Overview of the continuous monitoring
- CM with Nagios Plugins 
- CM with ELK  stack
- CM demo with Elastic-Search, Kibana, and Jenkins

### Prerequisites
- Linux/Ubuntu Os
- Basic knowledge of Jenkins

### Article Quality
I will ensure this passes subtle knowledge and meet up with the standard of this great community.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. :rocket:

**Comment by damikanye** [comment]
@LinusMuema sir, can you please review this issue?
cc: @hectorkambow

**Comment by damikanye** [comment]
@ahmadmardeni1 sir, kindly review this, please. 
CC: @hectorkambow

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @damikanye 
This topic is out of our preferred topics area - We lean towards content that offers an original viewpoint/approach around programming-centric topics.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by damikanye** [comment]
Feel like crying now! After all the waits. 

This topic is a pressing one that requires attention, sir. I am sure you cannot find it online. 
Please do let me talk about this!!
