### ISSUE TITLE
Build A 3d Portfolio Website With Vite js and Three js

### ISSUE THREAD

**Issue by oyedeletemitope** [section-engineering-education/engineering-education#5849]
#### Build a 3d portfolio website with vite and three js
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Most visual mindblowing websites in the world seem to follow a similar pattern, they use 3d animations that bring the content to life when the page is scrolled. In this tutorial, I'll be working you through how to make something similar by building a portfolio website with threejs.Three. JS is a cross-browser JavaScript library/API which is used to create and animate 3D computer graphics to display in a web browser.

#### Key takeaways 
In this tutorial we would be able to :
- Have an understanding of three js
- Know the relationship between Threejs and WebGl
- Have an understanding on Vite
- Install Vite
- Install three js as a package
- Know some concepts in 3d modelling
-  Use Three js helpers
- Build a portfolio website
 
#### Article quality
The readers stands a lot to gain in this article as it touches essential areas needed for those interested in 3d modelling and game development

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @oyedeletemitope

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
