### ISSUE TITLE
Top Node.js HTML Parsers Libraries

### ISSUE THREAD

**Issue by JudyNduati** [section-engineering-education/engineering-education#5850]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Top Node.js HTML Parsers Libraries

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Top Node.js HTML Parsers Libraries

#### Proposed article introduction
HTML is a simple structured markup language, and everyone who is going to write the web scraper should deal with HTML parsing. There are a lot of Node modules out there for parsing HTML. These libraries are used for web scrapping using Node in JavaScript. Node.js does not let you parse and manipulate markups because it executes code outside the browser.

This article aims to help the reader find the right tool for HTML processing. It will provide a selection of libraries, providing the pros and cons of each, along with some insight into which of the chosen parsers might be the most suitable tasks like web scraping.

#### Key takeaways 
1. Overview of Web Scrapping
2. Node.js HTML Parsers Libraries
- Cheerio
- Parse5
- Html parser2
- Node Html Parse
- Fast HTML Parser
- JSDOM 

#### Article quality
This is a detailed article to help the reader find the right tool for HTML processing by providing a selection of libraries with their advantages and disadvantages. Also, this article will help readers understand which library is most suitable for tasks like web scrapping.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@JudyNduati 
This seems like a very cool topic - but regarding Node.js we are currently not publishing many Node.js articles because we have more than enough currently in our EngEd library.
As we did a big push the last few months and we are currently not accepting any more Node.js articles to publish for the time being.
Please feel free to suggest an alternate topic to explore. 🚀
