### ISSUE TITLE
A Guide to Run your React Native Apps with Typescript

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#5851]
#### Proposed title of the article

An Absolute Beginner Guide to Run your React Native Apps with Typescript

#### Proposed article introduction

React Native runs of JavaScript by default. However, to leverage the advantages that Typescript (a superset of JavaScript) offers, it is possible to set up your whole React Native apps to run wholes on Typescript. This guide aims to thoroughly introduce the reader to running React Native apps with Typescript. We will learn the advantages of running React Native apps with Typescript and how to set them up with React Native. In the end, we will create a very handy blog application that uses Typescript to run the React Native application.

#### Key takeaways 

- What is Typescript
- Why run apps with Typescript
- Getting Started with Typescript
- What is React Native
- Why use React to run Native apps
- Initializing your First React Native project with Typescript
- Set up a Typescript Blog app using React Native
- Create React Native blog app components
- Add posts to the application
- Fetch all added posts
- Fetch a single added post

#### Article quality

This guide will be a thoughtful introduction to Typescript and React Native. For better understanding, the reader will also be able to create a whole application that uses React Native to run the Typescript code.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. :rocket:

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @kimkimani 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #5851 via #6016
