### ISSUE TITLE
How To Use FormData Web API With Fetch to POST Form Data As JSON To An API Endpoint

### ISSUE THREAD

**Issue by gisioraelvis** [section-engineering-education/engineering-education#5852]
## Proposed title of the article
How To Use FormData Web API With Fetch to POST Form Data As JSON To An API Endpoint

## Proposed article introduction
The Fetch API is used to make requests from a web on the front end through to the back end API endpoint, but if you want to send the data to the API as JSON, a bit of extra work is needed. This article demonstrates how to make use of the FormData and Fetch API to send form data as JSON.

## Key takeaways 
- In-depth guide and core concepts around the FormData and Fetch APIs.
- How to make use of the built-in browser APIs to send form data as JSON.
- How to receive form data as JSON at an API endpoint.

## Article quality
In this article, we explore the core concept of FormData and Fetch APIs from the ground up in a clear and concise manner making it friendly for beginners and people with no prior knowledge of the two APIs.
With an example then make use of the built-in FormData and Fetch APIs(no external packages) to implement step by step form that sends data as JSON to an API endpoint.

## References
[Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)
[FormData API](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. :rocket:

**Comment by LinusMuema** [comment]
good topic @gisioraelvis - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your tutorial very beneficial.
