### ISSUE TITLE
Turn your Python Script into a ‘Real’ Program with Docker

### ISSUE THREAD

**Issue by yitzackRabin** [section-engineering-education/engineering-education#5853]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Turn your Python Script into a ‘Real’ Program with Docker

No worries, I’m sure the developer was kind enough to give you an installation script to get you up and running. So you run their script, and the next thing you know your shell is a massacre of error logs. “Well it worked on my machine”, is what the developer will normally retort when you ask for help.
Docker solves this issue by making Dockerized applications almost trivially portable. This tutorial will show you how to quickly Dockerize your Python applications so that you can easily share them with anyone who has Docker.
In particular, we will be focused on scripts that are intended to be run as a background process.

#### Key takeaways 
1. Understanding Docker
2. Learning how to share docker files
3. Getting the importance of dockerization

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. :rocket:

**Comment by LinusMuema** [comment]
Hi @yitzackRabin 

Your article suggestion was great. However, it seems to have sections copied verbatim from [this article](https://prog.world/how-to-turn-a-python-script-into-a-real-program-with-docker/) and other sections are paraphrased. Therefore we cannot proceed with your suggestion as we focus more on original content. This is to avoid the inevitable
closure in the plagiarism stage.

Please feel free to explore other options.
