### ISSUE TITLE
[BLOCKCHAIN] Introduction to Blockchain Transactions and UTXOS

### ISSUE THREAD

**Issue by Adespscientist** [section-engineering-education/engineering-education#5865]
Introduction to Blockchain Transactions and UTXOS

You need to Understand the Importance of Blockchain transactions and UTXOS.
Why is Blockchain the hope of the future in storing and decentralizing record transactions?
Blockchains are best known for their important role in cryptocurrency approaches, such as Bitcoin for harboring a secure and decentralized record of transactions. Blockchain is a circulated database that is transferred among computer networks, as a database, a blockchain stores data electronically in a digital form.

Why we need to dive deeply into blockchain Transactions and UTXOS is because the most essential application of a blockchain is to buy and sell without a man in the middle and understands all the transaction process and also be able to exchange information through a safe network. UTXOS (Unspent Transaction Output) is the total amount left after performing a cryptocurrency transaction, UTXOS is responsible for the beginning and end of a transaction. UTXOS may sound tough but you will get to understand how simple they are once we begin this tutorial.

At the end of this tutorial, the reader should fully understand
- BlockChain Transactions and UTXOS
- The importance of Blockchain Transactions and UTXOS
- How to carry out a successful Transaction
- How to practice and build a Transaction with UTXOS
- Why UTXOS is Important in Blockchain Transactions

Article quality
Most times people create posts online complaining about why they are getting unconfirmed transactions. This is because they do not fully understand how Blockchain transactions and UTXOS works. So in this special tutorial, I will be diving deeply into this topics and guide you on important tips to make you build successful transactions and also, to make you understand the importance of Blockchain Transaction and UTXOS

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. :rocket:

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites. A google search of your article's title brought up several results talking of the same topic.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
