### ISSUE TITLE
Creating a user login web system using php and mysql

### ISSUE THREAD

**Issue by MBITHE4760** [section-engineering-education/engineering-education#5866]
Description
A login is a set of credentials used to authenticate a user. Most often, these consist of a username and password. Operating system login – Windows and Mac systems can be configured to require a login in order to use the computer after it is turned on or woken from sleep mode.

Key takeaways
-Create the Database Table
-Create the Config File
After creating the table, we need create a PHP script in order to connect to the MySQL database server.
-Create the Registration Form

References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. :rocket:

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
