### ISSUE TITLE
[Languages] Create a Type Ahead Feature in JavaScript  using Fetch and  Regex

### ISSUE THREAD

**Issue by gmcodes20** [section-engineering-education/engineering-education#5869]
#### Proposed title of the article
[Languages] Create a Type Ahead Feature in JavaScript using Fetch and Regex

#### Proposed article introduction
Designing a website with an intuitive user interface is one of the goals/challenges of a web developer.  This tutorial shows how to create a search suggestion for a given search paradigm. What this tutorial does is search a list of States in America from the  [Cites.Json file](https://gist.githubusercontent.com/Miserlou/c5cd8364bf9b2420bb29/raw/2bf258763cdddd704f8ffd3ea9a3e81d25e2c6f6/cities.json), the highlight the typed text when displaying the search result to the user.

To get the Data (i.e. the American state information)  from the JSON file, the fetch() method was used.  The fetch() method provides an easy way to get data to the page asynchronously. Just like XMLhttprequest, Fetch allow the page to load data from an external source without having to reload the page. But the main difference is that Fetch() uses Promises, which enables a simpler and cleaner API, avoiding callback hell.

#### Key takeaways 
The most important things the reader should understand in this tutorial are:
- Highlighting Part of a list element
- More insight on the keyup eventlistener in JS
- A better understanding of regex
- Using Array filter in JS

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. :rocket:

**Comment by LinusMuema** [comment]
Hi @gmcodes20 

Your article introduction is a bit short. You have given a summary of your article instead of the introduction. Please make the change and ping me to reopen and check the suggestion.

**Comment by LinusMuema** [comment]
good topic @gmcodes20 - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)

**Comment by gmcodes20** [comment]
> good topic @gmcodes20 - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)

Thank you, and be sure I will do my best
