### ISSUE TITLE
How to Use React Hooks to Generate Random Colors

### ISSUE THREAD

**Issue by HEking2** [section-engineering-education/engineering-education#5870]
### Topic Suggestion
How to Use React Hooks to Generate Random Colors

#### Proposed article introduction
Essentially, if we are familiar with React, we have all used react custom hooks (like useState, useEffect , useContext etc.). We can also create our own react hooks and use them wherever we want. So there's a small piece of code that generates random colors. In this article, we will create a random color generator custom hook (in our custom hook file), a function for changing color called (generateColor), and we will pass color and generate color as return. Then, in our App.js, we will destructure this and use that generate color as a onClick event function for a button that will change the color of our window.

#### Key takeaways 
- Understanding react hooks
- Creating react application
- procedural steps on how to generate rndom colors using React hooks 
 - example of  codes to use in app.js
#### Article quality
The article is intended to be precise and clear to the point, illustrated by codes making it more practical and interesting, to increase time spent on the page.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. :rocket:

**Comment by LinusMuema** [comment]
Hi @HEking2 

Your article suggestion is great. However, it seems to have been copied verbatim from [this website](https://www.geeksforgeeks.org/how-to-generate-random-colors-by-using-react-hooks/). Therefore, we cannot proceed with your suggestion as we focus on original content and to avoid the inevitable closure in the plagiarism check stage.

Please feel free to explore other topics.
