### ISSUE TITLE
[Machine Learning] Outlier detection and removal when building machine learning models

### ISSUE THREAD

**Issue by francis966** [section-engineering-education/engineering-education#5873]
#### Proposed title of article
[Machine Learning] Outlier detection and removal when building machine learning models

#### Proposed article introduction
Outliers are observations in a dataset that don't fit in some way, they are extreme values that deviate from other observations on data.  Outliers diverge from an overall pattern on a sample and have a negative impact on the model performance. When we train a machine learning model with the outlier values, they will negatively train the model and therefore the model will not produce the expected values.

For example, when building a model using a dataset that contains the age of people, outliers are values that are extremely high e.g 1000. Naturally, people's ages can not be this high. When we use these values to build the model, the model will give wrong predictions.

Outliers may occur in a dataset due to data entry errors (human errors), measurement errors (instrument errors), and experimental errors (data extraction or experiment planning/executing errors). In this tutorial, we will implement various techniques such as percentile and Z-Score to detect these outliers. We will then remove the outliers from the dataset so that we have a clean dataset that is ready to build machine learning models.

#### Key takeaways 
1. What are outliers?
2. Negative impact of outliers in a dataset.
3. How to detect outliers in a dataset.
4. Implementing the percentile technique to detect and remove outliers.
5. Implementing a z-score technique

#### Article quality
This tutorial is unique because we will take a dataset and clean it by removing all the outliers in the dataset. We will remove the outliers from scratch so that a reader can easily follow the tutorial and remove the outlier. We will use then a clean dataset free from outliers to build the model. This is a practical guide and by the end of the tutorial a reader should be able to implement the percentile and z-score technique in removing outliers from a dataset.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. :rocket:

**Comment by LinusMuema** [comment]
Hi @francis966 

Could you please expand upon how your content will differ from what is already available through this [medium article](https://medium.com/analytics-vidhya/how-to-remove-outliers-for-machine-learning-24620c4657e8)? We lean towards content that offers an original viewpoint/approach around programming-centric topics.
