### ISSUE TITLE
[Languages] Installing, Loading and Uninstalling Packages in R Program

### ISSUE THREAD

**Issue by Victor-Ror** [section-engineering-education/engineering-education#5876]
### Topic Suggestion
[Languages] Installing and Uninstalling Packages in R Program

#### Proposed title of article
Installing and Uninstalling Packages in R Program

#### Proposed article introduction
R packages are a collection of R functions, complied code and sample data. They are stored under a directory called "library" in the R environment. By default, R installs a set of packages during installation. More packages are added later, when they are needed for some specific purpose. When we start the R console, only the default packages are available by default. Other packages which are already installed have to be loaded explicitly to be used by the R program that is going to use them.

The base  version of R that is available for downloading enables the user to get started in R, but as the student escalates in data analysis he/she will exhaust the features of the basic R. It will therefore prompt the student to install the additional packages.

#### Key takeaways 
- How to install and load R packages.
- How to uninstall R packages 
- How to check the already installed R packages
- How to find the available R packages in the R repository

#### Article quality
This article is going to be beginner friendly to allow the R programming beginners understand how to install and uninstall R packages.
I will  cover this using  two ways, the R pacman package and installing from the CRAN repository with `install.packages("")` function.
  
#### References
[Installing and Uninstalling R Packages](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/install.packages)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Victor-Ror 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
