### ISSUE TITLE
Cookies and Sessions in ASP dot NET

### ISSUE THREAD

**Issue by swambui1** [section-engineering-education/engineering-education#5879]
### Topic Suggestion
Cookies and Sessions in ASP dot NET

### Proposed title of article
Cookies and Sessions in ASP dot NET

### Proposed article introduction
Cookies are small tokens of data that is stored on a client machine. Are utilized to store user data on the client end. Name, user id, contacts, address etc are samples of data stored on the client machine. ASP dot NET provides two types of cookies, Non-persistent and persistent. Cookies that have expiry date are the referred to as persistent, those that don't expire are known as Non-persistent.

Session is a state from where user values are retrieved and kept in the webpage. It is used to pass data from one page to another in ASP dot NET.
In a website sessions allows user to interact with the application and perform operations such as read and write.

### Key takeaways
- Creating cookies in ASP dot NET.
- Properties of cookies.
- Initiation and termination of a session.
- Implementation of sessions in ASP dot NET.

### Article quality
In this article I will introduce user to sessions and cookies in ASP.NET, am going to take the user through creation of cookies, also am going to show the reader how to implement a session in ASP dot NET. Further more am also going to cover properties of cookies, how sessions start and end and what leads to them to start and end. Am hoping this article will be of great value to the engineering community.

### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @swambui1 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #5879 via  #6807
