### ISSUE TITLE
Building Conversational AI with Blenderbot

### ISSUE THREAD

**Issue by EdemGold** [section-engineering-education/engineering-education#5880]
### Topic Suggestion
Building Conversational AI with Blenderbot

### Writing sample(s): 
[How to Build a sentiment analysis web app](https://edemgold.blog/building-a-sentiment-analysis-app)

### Proposed title of the article
Building Conversational AI using Blenderbot

#### Proposed article introduction
Conversational agents are automated systems that are built to converse with humans using natural language. Common examples of conversational Agents include - Siri, Google Assistant, Alexa, Cortana. Blenderbot is an Open Source language generation model built by Facebook AI. It is capable of articulately expressing itself, carrying on meaningful conversations in natural language when given a particular context. 

#### Key takeaways 
- Understanding the meaning of Conversational AI and how it works
- Learning about the Blenderbot model
- Learning about the requirements to build a Conversational Bot with gradio
- Building GUI components for your Conversational Bot using gradio
- Summary

#### Article quality
In this article, I will introduce the core concepts i.e **Conversational AI** and **Blenderbot** as this will give the reader a sense of the ins and outs of their project.

I will also explain to the users how to turn their Conversational AI code into a web app by building GUI components for their model using the open-source Gradio Library and in the process teach them about the gradio library.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @EdemGold 
We already have a tutorial on Blenderbot: https://www.section.io/engineering-education/introduction-to-blenderbot/
Does your article overlap with the mentioned one?
