### ISSUE TITLE
How To Reset MariaDB or MySQL Root Password on Ubuntu 20.04

### ISSUE THREAD

**Issue by jaacobstephenson** [section-engineering-education/engineering-education#5885]
**Proposed title of article**
How To Reset MariaDB or MySQL Root Password on Ubuntu 20.04. 

**Proposed article introduction**
Forgetting your password happens to the best of us. If you have forgotten the root password for your MariaDB or MySQL
database, you are still able to gain access and be reset your password if you have access to a user account with sudo privileges and access to the server. 
This tutorial will show how to reset one's root password for MariaDB/ MySQL databases which are installed with the apt package manager on Ubuntu 20.40. The process for changing the root password is different depending on if one has installed MariaDB or MySQL and the default system configurations that come with the distribution or third-party package.

**Key takeaways** 

- How to identify version of database and stopping the server 
- How to restart server without permission checks 
- Changing root password 
- Returning database server to default settings 

 **Article quality**
 In this article, I will describe the steps to reset the root password only if the default configuration for authentication was altered.

 **References**
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @jaacobstephenson
After some careful consideration, it struck us that this topic may be out of our preferred topics area.

Please feel free to suggest an alternate topic to explore. 🚀
