### ISSUE TITLE
Face recognition using wavelet features in Matlab

### ISSUE THREAD

**Issue by simonmwaniki** [section-engineering-education/engineering-education#5889]
### Topic Suggestion
Face recognition using wavelet features in Matlab

#### Introduction
A face recognition system is a technology capable of matching human faces from digital images or videos frame against face database. Wavelet is a wave-like oscillation with an amplitude that begins at zero, increases or decreases, and returns to zero. These wavelet coefficients are used to extract features from hyperspectral data. These extracted features are called wavelet features.
In this tutorial, a face detection scheme is implemented using the wavelet features. We use wavelet features to extract facial features and use principal component analysis to reduce the wavelet feature vectors. The proposed scheme is very robust and capable of recognizing the faces even if some changes occur in the face, such as growing beards, mustache e.t.c

#### Key takeaways 
- Face image database preparation for training and testing.
- Finding wavelet features.
- PCA for dimension reduction.
- Training and testing procedures.

#### Article quality
This article combines the idea of extracting wavelet feature and using a different algorithm PCA to reduce the dimensions before training and testing.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @simonmwaniki 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
