### ISSUE TITLE
[Language] Arguments of Repository Pattern in Entity-Framework that are not true.

### ISSUE THREAD

**Issue by erixbiz** [section-engineering-education/engineering-education#5890]
### Topic Suggestion
[Language] Arguments of Repository Pattern in Entity-Framework that are not true.

#### Proposed article introduction

When writing code, are you doing it right? That is the question that worries a lot of people. It should be at least what every developer thinks through. Design patterns are one of the thing that we should put in our code to enable writing re-usable and extensible object oriented software. 
Repository pattern is one of the great patterns that we use when building a software application. There are however, a number of myths that surround this pattern that are not true. This article seeks to address each one of them in depth. By the end of it, the reader will be able to have an idea of this whole repository pattern.

#### Key takeaways 
By the end of the article, the reader should be able to 
1. Understand what repository pattern is and its benefits.
2. Go through the arguments around the repository pattern and explain in depth their rational.  
          - Argument 1. Repository over repository. 
          - Argument 2. Increased complexity
          - Argument 3. Use the pattern in simple or complex applications.
          - Argument 4. Repositories are coupled to entity framework.
          - Argument 5. Classes in our application domain are persistent models.

#### Article quality
I will create a simple .NET application API, that will explain the above mentioned arguments using the API . By the end of the article the reader should have had a clear understanding of what this repository pattern is. 

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
I'm closing this topic-suggestion due to inactivity.
It can be reopened.
