### ISSUE TITLE
Building a USSD application with Django

### ISSUE THREAD

**Issue by Olamidun** [section-engineering-education/engineering-education#5891]
### Proposed Title of Article

How To Build A USSD Application With Django

Proposed article introduction

According to [wikipedia](https://en.wikipedia.org/wiki/Unstructured_Supplementary_Service_Data), USSD stands for Unstructured Supplementary Service Data. It is a communications protocol used by GSM cellular telephones to communicate with the mobile network operator's computers. The computer's response is sent back to the phone, generally in a basic format that can easily be seen on the phone display.

I will be using a [CoinGecko's](https://www.coingecko.com/en) official Python [SDK](https://github.com/man-c/pycoingecko) to fetch the price of the cryptocurrencies, for the exchange rate functionality, I will be using [Openexchangerate's](https://openexchangerates.org/api/latest.json) API, and to build out the USSD menus, I will be using [africastalking](https://africastalking.com).

### Key takeaways
- Explanation on how USSD applications work
- How to build out USSD menus using [africastalking](https://www.africastalking.com) API
- Consuming a simple API in Django
- Storing sensitive application information using .env files

### Article quality
In this article, I will show you how to build out USSD menus in Django, and how to connect the functionalities we want the USSD application to have to those menus.

## References
[Africastalking](https://developers.africastalking.com/)
[Django official documentation](https://docs.djangoproject.com/en/4.0/intro/tutorial01/)
[Coingecko](https://www.coingecko.com/en)
[Coingecko official Python SDK](https://github.com/man-c/pycoingecko)
[Openexchangerate](https://openexchangerates.org/api/latest.json)
[Deploying to Heroku](https://www.analyticsvidhya.com/blog/2020/10/step-by-step-guide-for-deploying-a-django-application-using-heroku-for-free/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by LinusMuema** [comment]
good topic @Olamidun  - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your tutorial very beneficial.

**Comment by Olamidun** [comment]
Thank you very much. I appreciate it.
