### ISSUE TITLE
Polymorphism in Python

### ISSUE THREAD

**Issue by Juskam** [section-engineering-education/engineering-education#5892]
#### Proposed title of article
Polymorphism in Python

#### Proposed article introduction
The word polymorphism means having many forms. In programming, polymorphism means the same function name being used for different types.In Python, Polymorphism lets us define methods in the child class that have the same name as the methods in the parent class.In this tutorial I will explain more in depth Polymorphism in Python

#### Key takeaways 
1.Examples of user-defined polymorphic functions.
2.Example of inbuilt polymorphic functions.
3.Polymorphism with Inheritance.
4.Polymorphism with class methods.
5.Polymorphism with a Function and objects

#### Article quality
In this article Polymorphism in python I will employ easy use of language to enhance understanding.It will be indepth article explaining all concept.I will explain all code snippet to ensure it's beginners friendly.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Juskam 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
]Approved

**Comment by ahmadmardeni1** [comment]
I'm closing this topic-suggestion due to inactivity.
It can be reopened.

**Comment by Juskam** [comment]
Hello @ahmadmardeni1 kindly open this issue so that I can do PR.Thank you
