### ISSUE TITLE
GETTING STARTED WITH REDIS USING NODEJS AND MONGODB TO BUILDING A CRUD APPLICATION.

### ISSUE THREAD

**Issue by Alao-Abiodun** [section-engineering-education/engineering-education#5893]
Proposed title of article
GETTING STARTED WITH REDIS USING NODEJS AND MONGODB TO BUILDING A CRUD APPLICATION.

Proposed article introduction
Redis is an in-memory No-SQL database and cache, basically it works by storing and retrieving data which are stored in key-value paired cache way, and its one of the technology tools that makes your application more fast when interacting with APIs or making a request to the server. Redis is used to deal with cases like caching, session-management, event-streaming and message broker.

Key takeaways
1. Setup Redis on windows PC users
2. Setting up Redis package ioredis on NodeJS project
3. Buidling a simple CRUD application using Redis with MongoDB and NodeJS

Article quality
In this article Redis which is an executable file, I will be introducing a very understandable and easy step by step process on how to setup Redis account on windows PC, and get it running with no issues, and also I will be showing the ioredis package which is the latest redis package to use for NodeJS project, because the redis package is not maintained again, and there will be lot of users for beginner who did not know about the latest redis package currently in use now.

References
https://abiodundev.hashnode.dev/how-to-setup-redis-on-windows-pc-ckxpzmz2z03the3s18qx3cpny
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and YouTube videos.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
