### ISSUE TITLE
[Machine Learning] Building a Reinforcement Learning Environment using OpenAI Gym

### ISSUE THREAD

**Issue by splashtonia** [section-engineering-education/engineering-education#5894]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Building a Reinforcement Learning (RL) Environment using OpenAI Gym

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Gym is a toolkit for developing and comparing reinforcement learning algorithms. It supports teaching agents everything from walking to playing games like Pong or Pinball. In this tutorial, we will give you a high-level overview of the toolkit and show you how you can build a custom RL environment which you can use in your project.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to understand:
- An overview of OpenAI's Gym
- Implement an example to demonstrate how we can build a custom environment
- Test an RL agent on the built custom environment

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Learning about a Reinforcement Learning toolkit and using the standard OpenAI environments is not enough. A reader ought to understand how they can build their own custom environments. We'll use Python to help us accomplish this task. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [OpenAI Gym](https://gym.openai.com/)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @splashtonia 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #5894 via #5966
