### ISSUE TITLE
Understanding fibonacci memoization time complexity in Javascript

### ISSUE THREAD

**Issue by gatwirival** [section-engineering-education/engineering-education#5895]
#### Proposed title of article
Understanding fibonacci memoization time complexity in Javascript

#### Proposed article introduction
First let's start by understanding what is a fibonacci number and  what time complexity means. A fibonacci number is a series of numbers in which each number is the sum of the two preceding numbers.The time complexity is the computational complexity that describes the amount of computer time it takes to run an algorithm. 

In this tutorial we will be using Dynamic  programming to solve fibonacci sequence and learn about the time complexity of our solutions.Dynamic programming is a technique to reduce the time complexity  of Fibonacci series from O(2n) to O(n). In case of Dynamic programming, Function calling will be same but the values are stored once a distinct function is executed and the values will be retrieved if the same function calls again. 
#### Key takeaways 
- What is fibonacci numbers
- What is time complexity
- How to implement memoization in JavaScript
- How to use brute-force recursion to solve Dynamic programming questions
- Understand  how time complexity is reduced by memoization improving code runtime

#### Article quality
In this article the reader will learn about fibonacci numbers,time complexity difference between memoized brute-force recursion and brute-force solution which has not been memoized, how to implement memoization in JavaScript and brute-force recursion in JavaScript.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @gatwirival 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
