### ISSUE TITLE
Getting Started with the Eigendecomposiion in Python

### ISSUE THREAD

**Issue by jacksonjate1** [section-engineering-education/engineering-education#5896]
### Proposal Submission

Getting Started with the Eigendecomposiion in Python

#### Proposed article introduction
Eigendecomposition is a Linear Algebra technique used in machine learning to factorize square data matrices into three matrices that are easy to work with under intense matrix transformations. For a matrix to be decomposed using the Eigendecomposition, it must be a square matrix. An Eigendecomposition of a square matrix A is given as A = VSV^-1, where;
V is a matrix of eigenvectors of matrix A,  S is a diagonal matrix of eigenvalues corresponding to eigenvector in the matrix V, and V^-1 is an inverse of V.

The general idea in Eigendecomposition is to represent a matrix by its eigenvalues and eigenvectors that is computationally less expensive than the original matrix. Moreover, this technique does not lose the matrix's information as we can retrieve the original matrix from these three components by multiplying them together.

 The benefit of Eigendecomposition can not be realized when working under small transformations, but when we are transforming a data matrix many times, say 1000 times, we can appreciate its contribution in easing the computational power needed if we were to multiply the borigin\al matrix 1000 times. For, Eigendecomposition we only need to multiply the diagonal matrix 1000 times. This is much easy with a diagonal matrix; we only take each value of the diagonal matrix and raise it to the power value given and obtain a scaled diagonal matrix. This makes the computation very easy and time-saving.

In this article we will look at the following:
- First, we shall clearly explain what Eigendecomposition is and how it is used in machine learning.
- Secondly, by hand, we will perform Eigedecomposition on a synthetic data matrix. Before we can do this first, we shall look at properties that a matrix must satisfy to be decomposed using Eigendecomposition.
- Also, we shall look at the importance of Eigendecomposition over transforming the original matrix. Here we shall compare the computation carried on a matrix with Eigendecomposition and without.
- Lastly, we will implement Eigendecomposition in python.

#### Key takeaways 
By the end of this article, a serious learner will know:
- What's Eigendecomposition
- What are properties a matrix must satisfy to be decomposed using Eigendecomposition
- How to perform Eigendecomposition by hand on a data matrix
- What are the benefits of performing Eigendecomposition on a data matrix
- How Eigendecomposition is implemented in python

#### Article quality
Many articles are already in place trying to handle Eigendecomposition at their best. However, most of them focus on computing this algorithm by hand and leave learners to implement it by themselves. Also, most of them don't let learners know the importance of applying this technique to a data matrix. This article will address these limitations. First, we will show the learner how to compute the Eigendecomposition by hand and implement it using software python, as it's the most used language in machine learning. Then, again, we will show how the Eigendecomposition eases matrix transformation computations by comparing a computation with and without this algorithm. This is what will make this article uniques from the rest already in place.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @jacksonjate1 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
