### ISSUE TITLE
React-Router version 6

### ISSUE THREAD

**Issue by Geraldoeze** [section-engineering-education/engineering-education#5900]
#### Proposed title of article
React-Router version 6. 

#### Proposed article introduction
Routing is an important feature in every web application, it helps in redirecting from one page to another. This reduces the amount of contents and information displayed on a web page, thereby making it easy to access by users.

React.js is a frontend JavaScript library that renders JSX to the DOM browser. React-Router enables routing in React applications, it makes our React applications user friendly and organized.

#### Article quality
In this article, we will learn the new features of React-Router version 6 (v6) and also see how it differs from previous version 5

#### Key takeaways 
1. What is React-Router
2. React-Router version 6 features
3. Upgrading from version 5
4. How to use version 6 features
5. Compare version 5 and 6

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Geraldoeze 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
