### ISSUE TITLE
[API] How to implement dynamic enum mapping in Java/Spring  Boot

### ISSUE THREAD

**Issue by neeshegz** [section-engineering-education/engineering-education#5903]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
[API] How to implement dynamic enum mapping in Java/Spring  Boot

#### Proposed title of article
[API] How to implement dynamic enum mapping in Java/Spring  Boot

#### Proposed article introduction
Conversing with a more senior colleague on a project he worked on, opened my up to the world of dynamic enum classes implementation. Picture this: a base class called Pooler, which initiates the mechanism for a financial technology company to request the banking identity data of a customer. The attributes had statuses and it is just sensible that the data type for statuses is an enum, each with its own declared values internally. 

Normally, this is supposed to be fine. What then could be the problem? The regular approach is that each attribute's status value could change when certain triggers happen - say an event or events from more than one service that talk to one particular service. Now each of these external has their own values, which would need to be mapped to this one listening class' values for statuses to change accordingly. This can get cumbersome as projects grow bigger. In comes dynamic enum discovery and registration that let you declare enum and manipulate statuses only on the fly.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
- Understand the implementation behind multiple enum classes with a centralized solution.
- Avoid the problem mostly common with enums - class pollution
- Learn the steps to implementing dynamic enum discovery and registration

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

My article will be applied to real-life situations as it involves state changing - essential for process flows and object manipulation. Also, it is descriptive for even real beginners and contains more insights than just documentations.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @neeshegz 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by ahmadmardeni1** [comment]
I'm closing this topic-suggestion due to inactivity.
It can be reopened.
