### ISSUE TITLE
A Complete Guide on How to Impute Time Series Missing Values in Python

### ISSUE THREAD

**Issue by DennisKimt** [section-engineering-education/engineering-education#5904]
#### Proposed title of article
A Complete Guide on How to Impute Time Series Missing Values in Python

#### Proposed article introduction
Time series is data that has a time component in it. In other words, the data collected sequentially over time is called time series. Usually, sometimes this data contain missing values, i.e., no record made at a specific time. The approach used to handle missing values in the Time series is usually different from those used to handle missing values in machine learning databases. In time series, special techniques that preserve the consistency of its components are used. 

Usually, we can deal with the missing values in time series data in two ways.

1. omit the entire instance that contains the missing value.
1. Impute the missing values using the method for time series imputations.

Imputation these values, we use methods such as:
1. Mean Imputation
1. Last Observation Carried Forward(LOCF)
1. Seasonality Interpolation
1. Linear interpolation

Intuitively, in this tutorial, we will discuss how each of the above methods works, and with facts, we'll declare which of them works the best. Along each method, we will provide its python implementation..

#### Key takeaways
 
The learn will clearly know:
1. What's time series.
1. Types of time series models.
1. What are time series missing values.
1. How to handle missing values in time series data.
1. Different methods for imputing time series missing values.
1. How to impute time series missing values in python

#### Article quality
This article will provide an in-depth approach to handling time series missing values. We will explore all techniques the learner must know to impute time series data. As all methods will not be applied simultaneously with the future time series, we will, together with the learner, figure out which method is the best to serve as a multipurpose technique with most of the times series. So, we will engage the learner to a high degree.

For a method being multipurpose, it doesn't mean the rest of the techniques are irrelevant. The learner needs to be provided with complete knowledge to have more flexibility on which method to use while handling their time-series data. They should be taught why we go for one method and not the other. So, this article will provide the learner with in-depth information on this topic.

As we will clearly illustrate all our discussions, our implementation session will ensure every code snippet is explained to the point, i.e., what exactly it's performing. So, to will make this article reader-friendly as much as we can.
#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
How is your article unique? Tell us what makes your approach different from similar articles that have been published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice? @DennisKimt

**Comment by DennisKimt** [comment]
Hello @ahmadmardeni1 
Sorry, it was a transfer error, but I have fixed it. So, kindly, you can now review my issue. Thank you.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @DennisKimt 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
