### ISSUE TITLE
Automate Windows Applications using Python

### ISSUE THREAD

**Issue by Bonimum** [section-engineering-education/engineering-education#5906]
#### Proposed title of article
Automate Windows Applications using Python

#### Proposed article introduction
Performing repetitive tasks is very boring and hectic. But what if you can automate those stuff and let a script do that boring task. It is amazing, isn’t it? So, in this article, we are going to learn how to automate Windows applications. Because if you can automate such repetitive tasks you can save your precious time for other important things. Automation is also increasing day by day because there are many things that are repetitive in nature and if they get automated they save your efforts and in many cases huge manpower involved in those tasks.

#### Key takeaways 

- Applications of Automation
- Automating Notepad using Pywinuato
- Automating Excel Application
- Automating Reading Data from excel sheet
- Automating Writing data in an excel sheet

#### Article quality
We will look at some examples in this article. Firstly, we will start with Notepad automation which is quite basic. After that, we will automate the excel application. In excel, we will try to read data from cells and writing data to cells. And we will also look at some more examples ahead. This we will be doing with Python and Pywinuato.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Bonimum 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
