### ISSUE TITLE
Useful Python String Functions Every Data Scientist Should Know About

### ISSUE THREAD

**Issue by fely545** [section-engineering-education/engineering-education#5907]
### Topic Suggestion
Useful Python String Functions Every Data Scientist Should Know About

#### Proposed article introduction

Python string is a built-in type sequence. Strings can be used to handle textual data in Python. Python Strings are immutable sequences of Unicode points. Creating Strings is the simplest and easy to use in Python. To create a string in Python, we simply enclose a text in single as well as double-quotes. Python treats both single and double quotes statements the same. So, In this article, we will be discussing some important and useful Functions of Strings in Python for Data Analysis and Data Manipulation, mainly used in Natural Language Processing(NLP).

####  Key Takeaways

The Python String Functions which we are going to discuss in this article are as follows:

- capitalize( ) function
- lower( ) function
- title( ) function
- casefold( ) function
- upper( ) function
- count( ) function
- find( ) function
- replace( ) function
- swapcase( ) function
- join( ) function

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by WanjaMIKE** [comment]
Unfortunately, the string functions can easily be found in official documentation. We focus more on unique projects. Feel free to suggest another topic.. Thanks
