### ISSUE TITLE
How nested functions are used in Python

### ISSUE THREAD

**Issue by Ghassany** [section-engineering-education/engineering-education#5908]
### Topic Suggestion
How nested functions are used in Python?

#### Proposed article introduction
In this article we will look at examples of the benefits of nested Python functions and how to use them to encapsulate code, closures, and decorators.
Nested (or inner, nested) functions are functions that we define inside other functions to directly access the variables and names defined in the enclosing function. Nested functions have many uses, primarily for creating closures and decorators.

In this article, we will

 - learn how to provide encapsulation and hide functions from external access

 - write helper functions to make code easier to reuse

 - implement closures to persist state between calls

#### Article quality
In this article will be different from the ones available in the internet since it includes some steps which are not included in those articles. We will also create decorators to add behaviour to existing functions.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Ghassany 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
