### ISSUE TITLE
[Languages] Build and deploy Bookmark extension with javaScript

### ISSUE THREAD

**Issue by Kamau-ke** [section-engineering-education/engineering-education#5910]
#### Proposed title of article
Build and deploy Bookmark extension with javaScript
#### Proposed article introduction
We'll make a Site Bookmark app with HTML, CSS, and JavaScript in this article. This will allow us to save links to our favorite websites without having to use a database and instead rely on the local storage of our browser.
Local Storage is known as the web storage API and allows us to store data on the client-side. Data in local storage is stored in form of strings and persists even after closing the session.  Data can only be removed if the user manually deletes it.

#### Key takeaways 
1. Basic CSS styling
2. Selecting elements with javaScript
3. What is Local Storage and use it
4. How to deploy extension in a browser

#### Article quality
This article will be novice-friendly and will help readers advance in javaScript. Readers will be able to store and delete data from local storage, and also create web extensions and deploy them.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Kamau-ke 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
