### ISSUE TITLE
Understanding load testing in selenium

### ISSUE THREAD

**Issue by tesswambui** [section-engineering-education/engineering-education#5915]
#### Topic
Understanding load testing in selenium

#### Proposed title of article
Understanding load testing in selenium

#### Proposed article introduction
Load testing is a test of functionality that ensures that an application serves its purpose and won't misbehave in any circumstance.

Selenium like any other testing software it also supports load testing, which is a section of performance testing.
Load testing in selenium is used to test performance and speed of a web based application when exposed to different intensity of loads. How the application is responding, is it slow or fast. Selenium load testing helps to enhance the efficiency of a web application and make it fast. 

#### Key takeaways
- goals of selenium load testing.
- steps for performing load testing in selenium.
- Benefits of using selenium for load testing.

#### Article quality
In this article am going to take the user through load testing in selenium, steps taken to perform load testing on selenium, goals achieved using selenium to perform load testing and why use selenium instead of other software to perform load testing. Am going to use beginner friendly language to explain the concept to the user.
#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @tesswambui 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
