### ISSUE TITLE
How to build a Java GUI calculator from scratch using Box layout

### ISSUE THREAD

**Issue by princeibs** [section-engineering-education/engineering-education#5916]
### Writing sample(s): 
- [https://dev.to/princeibs](https://dev.to/princeibs)
- [https://www.section.io/engineering-education/working-with-gridbag-layout-in-java/](https://www.section.io/engineering-education/working-with-gridbag-layout-in-java/)

#### Proposed title of article
How to build a Java GUI calculator from scratch using Box layout

#### Proposed article introduction
The concept of building command line calculators is one of those projects every programmer loves to engage with. This is because it can be used to solve real life problems and computations. But limitations tend to come up when you want the calculator to be used by a user who is afraid of the black and white console. This is where GUIs come to play.
In this article, we will be building a calculator from scratch using the box layout to properly layout the components of the calculator. This calculator will be made of two parts, the GUI and the logic part - the part that performs computations. We will also get to learn how real life calculators work under the hood by incorporating functionalities like addition, subtraction, division, multiplication and many more. The article will also expose the readers to the power of box layout and how they can use it in other programs to convert their console apps to a GUI app.
  
#### Key takeaways 
By the end of this article, the readers will
* Get to know the logic that runs real life calculators
* Apply the logic in building a calculator in Java that can perform computations
* Gain a deep knowledge of a box layout and its functionalities
* Learn how to use the box layout to convert console apps to GUI

#### Article quality
Some days ago, I searched Google for assistance on [how to build a GUI calculator with Java using box layout](https://www.google.com/search?q=build+a+gui+calculator+with+java+using+box+layout&rlz=1C1CHBD_enNG902NG902&oq=build&aqs=chrome.0.69i59l3j69i57j69i60j69i61j69i65l2.5207j0j7&sourceid=chrome&ie=UTF-8) which is a course assignment for me. But I couldn't find any answer on the internet. This made me do more offline research on books, consultations, and some snippets of information I was able to get online. Because of the difficulty I encountered before solving the problem, I decided to write about it so as to help other fellow students who are in the same situation but couldn't find answers on the internet.

This article will cover building a fully fledged GUI calculator in Java using the box layout manager. It covers two main aspects which are - building the logic that runs the calculator, and building the calculator GUI using the box layout. 
There is currently no tutorial online that covers building a Java GUI calculator using the box layout. This article will go a long way to help college students who need a solution for assignment, and Java programmers who want to learn about box layout.
Below is a final look of the project - 
![image](https://user-images.githubusercontent.com/64266194/148089034-1ca141b8-e1f0-41b2-8180-0e42568d8dad.png)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @princeibs 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
