### ISSUE TITLE
Building a Model Using Code-first Workflow in .NET Core Web API.

### ISSUE THREAD

**Issue by munyite-megzs** [section-engineering-education/engineering-education#5917]
### Topic Suggestion
Building a Model Using Code-first Workflow in .NET Core Web API.

#### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
If you need to access data from your database, which you often will, you need a persistent framework. With the persistent framework, you will be able to load data or retrieve data from your database. Entity Framework is a persistent framework commonly used in .Net applications. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

1. Adding new Classes.
          - The best way to name migrations.
          - How to use an already existing migration to do another similar migration.
          - How to populate a database table with data using code-first.
2. Modifying an existing class.
         - Ways one can override the conventions to modify database tables in EF code first migration
         - Different Methods applied during modification
3. Deleting an existing class.
         - How to use Entity framework code-first to preserve data before deleting a table.
4. Recover from mistakes.

#### Article quality
This article will go in-depth in terms of explaining the entity framework concepts. Most articles just explain the basics of creating, modifying, and deleting classes,  This article will go past that and explain in detail how migration works when these operations are applied and the changes one can do to the migration class to add, update and delete records in the database. By the end, the reader will be equipped all round on working with EF using .Net Core. Most articles use .NET MVC 5  to explain the concepts. 

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @munyite-megzs 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
