### ISSUE TITLE
Solutions to Common Django Errors in Web Development

### ISSUE THREAD

**Issue by OkothAlvan** [section-engineering-education/engineering-education#5922]
**Suggested article title**

Solutions to Common Django Errors in Web Development

**Proposed topic introduction**

Many times, people get stuck on the way, not only on coding related development but also several other development. This may be as a result of failure to follow instructions, installation error, and various other major or minor reasons. In this article, we shall major on Django errors during web development.
It is almost impossible to reach your destination in web development using any other framework including django without getting stuck on the way. At times there must be an emergence of error. Considering web development, it can be as a result of wrong path, installation, procedures and just ignorance. In this article, I'll make it easy for youby clearly pointing to some common errors associated with django, explaining to you step by step how we can solve these errors to keep going and reach our destination. Happy reading.

**Key takeways**

- 404 page not found error
- No reverse match error
- No module named error
- Template does not exist error
- Djanho-admin not recognized as internal and external command
- Djangi not able to find static files
- NameError
- Internal server error

**Article quality**

In my article, I'll be solving different errors in one article making it easier for the reader to easily find the error and solve it. Not as other articles, in my article, I will be considering several causes of a particular error and give solutions to them since an error can be brought about by many inconveniences. The aim of my article is to make it easy for programmers to reach their destination.

**References**

N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by OkothAlvan** [comment]
Thank you. I'm waiting for the approval.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @OkothAlvan 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by OkothAlvan** [comment]
Noted. Thank you.
