### ISSUE TITLE
[Security] Implementing the throttling pattern to maintain healthy systems with Java Spring Boot

### ISSUE THREAD

**Issue by afropolardev** [section-engineering-education/engineering-education#5925]
#### Proposed title of article
[Security] Implementing the throttling pattern to maintain healthy systems with Java Spring Boot

#### Proposed article introduction
Microsoft defines Throttling as "the control of the consumption of resources used by an instance of an application, an individual tenant, or an entire service." By this, systems keep their functionality in meeting Service Level Agreements, especially when demands for resources go on the high.

The load on a cloud application typically varies over time based on the number of active users or the types of activities they are performing. For example, more users are likely to be active during business hours, or the system might be required to perform computationally expensive analytics at the end of each month. There might also be sudden and unanticipated bursts in activity. If the processing requirements of the system exceed the capacity of the resources that are available, it'll suffer from poor performance and can even fail. If the system has to meet an agreed level of service, such failure could be unacceptable.

The solution strategy of autoscaling is to allow applications to use resources only up to a limit, and then throttle them when this limit is reached. The system should monitor how it's using resources so that, when usage exceeds the threshold, it can throttle requests from one or more users. 

#### Key takeaways 
- Readers will understand the advantages of throttling and how it is done in Java
- Understanding how to limit or encourage requests based on the throttling parameters
- Deferring operations being performed on behalf of low-ranked applications
- Generally safeguarding API structures and provisions

#### Article quality
My article is a product of a design solution I implemented on an API infrastructure problem I navigated. Basically, it goes beyond the documentation and will be applied to other areas of software engineering and infrastructure building.

#### References
https://docs.microsoft.com/en-us/azure/architecture/patterns/throttling

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
