### ISSUE TITLE
[API] Azure DevOps API deployment

### ISSUE THREAD

**Issue by fabulousDesigns** [section-engineering-education/engineering-education#5926]
#### Proposed title of article
Azure DevOps.NET API deployment

#### Proposed article introduction

Workflow management, code collaboration, and app development and deployment are all made easier with Azure DevOps. Collaboration between developers, project managers, and other stakeholders is fostered through Azure DevOps.
We'll learn how to continually integrate and deploy.NET APIs using Azure DevOps.

#### Key takeaways 
- By the end of this instructional exercise we will have covered the following:
1. Setting up SQL Azure database
2. Set up an Azure Application.
3.  Using Azure DevOps, create a Build and Release pipeline.
4. Update .NET app
5. Initiate the Pipeline

#### Article quality
By reading this article learners will understand how Azure DevOps simplifies the management of servers for application deployment. As well as how each machine communicates with Azure DevOps to coordinate app deployment. We will have a clear explanation with well illustrated screen shots to allow learners to understand every bit stated above.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=Azure+DevOps.NET+API+deployment) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by fabulousDesigns** [comment]
@louisefindlay23 Hello From the content online most of the blogs are based on what is already covered in the official documentation and in some steps they are not fully bringing some critical issues of which I intend to provide a one of a kind article that will be Understood by developer at every level on top of that I will provide screen shots to every step to indeed prove that what will be explained actually works. Thanks

**Comment by louisefindlay23** [comment]
Could you tell me what these critical issues are?

**Comment by fabulousDesigns** [comment]
@louisefindlay23,For example in this key takeaway  `Create an Azure DevOps project and build and release pipelines for it.` which is probably the interesting part of the article I have read a few of the blogs and most of them have failed to bring out the context in it among others. Thanks

**Comment by louisefindlay23** [comment]
Thanks, @fabulousDesigns. There seems to be many [articles](https://www.google.com/search?client=firefox-b-d&q=Create+an+Azure+DevOps+project+and+build+and+release+pipelines) with that key takeaway included. Is your article a more complete package or does it have unique material?

**Comment by fabulousDesigns** [comment]
@louisefindlay23 of course it will have more material because I believe knowledge cannot be exhausted I'll also go ahead and show learners the following how to create a SQL Server Database and how to get an Account on Azure DevOps Services and Azure Portal. Thanks
