### ISSUE TITLE
[API]Implementing a GraphQL API server using Go lang and a MongoDB database

### ISSUE THREAD

**Issue by Joakim-gakure** [section-engineering-education/engineering-education#5927]
#### Proposed title of article

Implementing a GraphQL API server using Go lang and a MongoDB database

#### Proposed article introduction

GraphQL is a query language for APIs used to communicate data between a client and a server. This allows you to structure data-driven applications much more flexibly and efficiently than the REST AND SOAP approach. GraphQL provides a complete and understandable description of the data in your API. It gives clients the power to ask for exactly what they need and nothing more. This makes it easier to evolve APIs over time and enables powerful developer tools. It also gives developers more control over how they use data in their apps.

GraphQL can be implemented with different languages and databases of choice such as Golang and MongoDB. Go is a general-purpose language meaning that it can be used for many different things. You can use Go to build web apps, microservices, cloud services, APIs, DevOps toolings, and any application you can think of. This means you will probably use Go to build a server-side-based application. Just like Node.js, you will need the right tooling to be able to handle your server-side code.

After developing your application with Go, you might need a database to store data. One of the databases you can use is MongoDB which is a cross-platform NoSQL database. MongoDB is a cross-platform document-oriented database platform, classified as a NoSQL database. It uses JSON objects as its data tuples. When working with a web application, you might not be aware of the exact data format being sent, and a NoSQL database such a MongoDB would be a good solution for data handling and storage.

This guide runs a GraphQL server using Golang and a MongoDB database.

#### Key takeaways

Introduction to GraphQL
What is GraphQL
Why GraphQL APIs
Configuring a GraphQL server in Go
How to use Mutations and Queries in GraphQL
Create a Golang GraphQL server-based application with all CRUD operations supported

#### Article quality

A number of articles explain the concept of GraphQL with the likes of MERN and MEVN stack. However, GraphQL uses a mechanism that queries data and then displays that data with the GraphQL schema. This guide aims to introduce the Go programmers to the concept of GraphQL. We will explain this concept and how it works. The build and application stack that has GraphQL, Golang, and MongoDB. The reader will also understand the frameworks and libraries we will use to achieve this.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Closed #5927 via #6077
