### ISSUE TITLE
Java Interfaces

### ISSUE THREAD

**Issue by Erastuskanyatta** [section-engineering-education/engineering-education#5930]
#### Proposed title of article
Java Interfaces

#### Proposed article introduction
An interface is a shared boundary across which two or more separate components of a computer system exchange information.

For instance, let's assume we have two classes,  X and Z where class X depends on class Z. If we change class Z, X will be affected. To reduce this impact we put interfaces between the classes such that when we change the code in class Z, we don't affect the code in class X.

In java, interfaces are used to build loosely-coupled, extensible, testable, and reusable components.

#### Key takeaways 
1. What is an interface in java.
2. When to use interfaces
3. How to create an interface.
4. Interface segregation principle.
5. Injecting dependencies in java.

#### Article quality
Interfaces are the most misunderstood features in java. In this topic, I will introduce interfaces in a simple way that will be understood by the majority of developers. In addition to that I will also look at Injection in java.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
