### ISSUE TITLE
Understanding Duck Typing in Python

### ISSUE THREAD

**Issue by Simsamrosh** [section-engineering-education/engineering-education#5931]
#### Proposed title of article
Understanding Duck Typing in Python

#### Proposed article introduction
Duck Typing is a Dynamic Typing notion in which an object's type or class is less essential than the method it defines. We don't check types at all when we use Duck Typing. Rather, we look for the existence of a specific function or trait.
The name comes from the duck test, which states, "If it looks like a duck, swims like a duck, and quack like a duck, then it probably is a duck”.
In this article we'll deeply discuss duck typing comparing it with other typing methods in different dynamic languages such as JavaScript and Ruby. we'll also appreciate its origin and advantages of having it in programming.

#### Key takeaways 
- Definition and general introduction to duck typing
- Benefits of having duck typing
- Comparison with Static and other dynamic typing methods
- Concept of calling functions and executing them 

#### Article quality
This article will provide an in-depth explanation of duck typing as well as incorporate a language easy to be understood by the reader. The reader will appreciate the fact that this tutorial shall provide practicable examples in calling and executing functions in duck typing therefore, making it beginner-friendly. The subject topic will also be compared with other different fields of programming to ensure reader will be oriented all round issue.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @Simsamrosh. This topic seems to have already been covered [extensively](https://www.google.com/search?client=firefox-b-d&q=Understanding+Duck+Typing+in+Python). How is yours unique?

**Comment by Simsamrosh** [comment]
> 

In my article I will include several usages of duck typing using practical examples such as
	-Iterators in python to implement  the __iter__() and __next__() methods in custom class.
	- Callables such as lambda function of  the default_factory argument type.
- sorting with len() by implementing the custom len() function in duck typing.
All of which are absent in other existing blog sites

**Comment by WanjaMIKE** [comment]
Closed #5931 via #6361
