### ISSUE TITLE
Creating ChatBot Using Natural Language Processing in Python

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#5932]
### Topic Suggestion
Creating ChatBot Using Natural Language Processing in Python
#### Proposed article introduction
Bots are pieces of custom-written software that engage in conversation with other internet users on their behalf. Algorithms are the building blocks of bots, which aid them in their work. This means they are self-contained and can begin the process of conservation without the need for human intervention.

We will be designing a chatbot using natural language processing.

#### Key takeaways 
- Type of Bots
- Building the chatbot
- Benefits of bots

#### Article quality
In this article, we'll learn about Creating ChatBot Using Natural Language Processing in Python. The code will be easy to read and understand.
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @vincentkims49. This topic seems to have already been [covered](https://www.google.com/search?client=firefox-b-d&q=Creating+ChatBot+Using+Natural+Language+Processing+in+Python). How will your article add value?

**Comment by vincentkims49** [comment]
@louisefindlay23 
The difference will be seen when I create a simple chatbot using chatterbot as an example in python. In addition, I'll add information on types and benefits of chatbots. Thanks.

**Comment by louisefindlay23** [comment]
Approved but ensure you add enough unique content to benefit our readers.
