### ISSUE TITLE
[language]Flutter speech recognition using Alan voice

### ISSUE THREAD

**Issue by Eze4Manuel** [section-engineering-education/engineering-education#5933]
### Topic Suggestion
[language]Flutter speech recognition using Alan voice
 
#### Proposed article introduction
This is a tutorial session on flutter that teaches the reader how to implement speech recognition on your flutter application. By speaking to our application we can perform actions based on preset commands. When the application running on our devices captures a speech match we can perform any operation we want as we would any other function.

#### Key takeaways 
The reader will learn how to implement speech recognition in his application.
The reader will learn how to integrate voice assistance using commands defined.

#### Article quality
This tutorial session will show an in-depth example of implementing speech recognition with Alan's voice. 

#### References
https://pub.dev/packages/alan_voice
https://github.com/alan-ai/alan-sdk-flutter

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Hi, @Eze4Manuel. This topic seems to have already been [covered](https://www.google.com/search?q=Flutter+speech+recognition+using+Alan+voice). How will yours be unique?

**Comment by Eze4Manuel** [comment]
My topic focuses majorly on the application of commands in speech recognition using "Alan's voice". Example commands will be the center focus of my tutorial and will show how the Alan voice can be used to pass in simple commands.

**Comment by WanjaMIKE** [comment]
Closed #5933 via #6628
