### ISSUE TITLE
[Security] Getting started with Nessus scanner

### ISSUE THREAD

**Issue by Adespscientist** [section-engineering-education/engineering-education#5934]
#### Proposed title of article
Getting started with Nessus Scanner

#### Proposed article introduction
In this tutorial, I will be introducing you to the Nessus scanner and how to be a good Pen-tester using Nessus.
Nessus is a Web vulnerability scanner that allows you to scan your server/Website for vulnerabilities and provide tips on how to fix them. This is open-source software that is available for all, it is available on Windows but it comes inbuilt in Kali-Linux which makes things even easier.

#### Key takeaways 
The reader should be able to
- Install Nessus and know how to use it.

#### Article quality
Most sites covering the same topic only show you how the installation works and how to scan for vulnerabilities, but how to fix this vulnerabilities with nessus they don't show you.
So I will hold you by the hand and show you different ways to help secure a real site with Nessus after a successful scanning is done. You will be using Nessus to find, fix and update servers to increase your security levels.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Please fill in the Article Quality information so we can review your article.

**Comment by Adespscientist** [comment]
Article quality Information done 👍

**Comment by louisefindlay23** [comment]
Thanks, @Adespscientist. Can you tell me how your article is unique amongst [others](https://www.google.com/search?client=firefox-b-d&q=Getting+started+with+Nessus+scanner) covering the same topic?

**Comment by Adespscientist** [comment]
Article quality updated.

**Comment by WanjaMIKE** [comment]
Closed #5934 via #6155
