### ISSUE TITLE
(Machine Learning) Effectiveness of support vector machine in analyzing medical data

### ISSUE THREAD

**Issue by slynn22** [section-engineering-education/engineering-education#5935]
### Topic Suggestion
(Machine Learning) Effectiveness of support vector machine in analyzing medical data

#### Proposed title of the article
Effectiveness of support vector machine (SVM) in analyzing medical data
#### Proposed article introduction
SVM has been termed as one of the key models which are vital in the prognosis and prediction of various diseases. SVM is vital in analyzing medical databases which are vital in predicting and diagnosing various health conditions.
The article's focus is to understand ways in which SVM diagnose and prognoses various health conditions using medical data. The article also highlights why SVM is effective in handling medical data compared to other algorithms.

#### Key takeaways 
1. Understand ways in which SVM transforms medical data to outputs which are vital in diagnosing and prognosis of various health condition
2. Various health conditions that can be diagnosed and prognosis using SVM?
3. why SVM is an effective model in handling medical data compared to other algorithms?
#### Article quality
The article is unique since it will be able to assess the in-depth use of SVM in analyzing medical data to address medical problems
#### References
None for now

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
There seems to be many academic articles on this [topic](https://www.google.com/search?q=Effectiveness+of+support+vector+machine+(SVM)+in+analyzing+medical+data). Will you be using any of them as references?

**Comment by slynn22** [comment]
Really??, i checked and none in section.io have focused on this" _SVM on medical data"_ but there are some on just SVM which I will reference
