### ISSUE TITLE
[Language]Converting a String into an Int in C#

### ISSUE THREAD

**Issue by cathy-254** [section-engineering-education/engineering-education#5937]
#### Proposed title of article
Converting a String into an Int in C#

#### Proposed article introduction
When programming in C# most of the time we are required to convert string to integer or a Number. Most of the time after converting you might get an input string that was not in a correct format error, especially when dealing with user input. Well, in this article I will show the beginner how to convert a string into a number or int without getting any error in C sharp (C#).

I will explain the three bold methods with complete programming examples and show you how to choose the right method for our scenario. It will be made easier like `1+1` for the novices to understand and follow. 

I will prepare a step-by-step demo for learners, to show how we can convert a string into Int using C#.

#### Key takeaways 

In this article, we will focus mainly on the following methods used to convert strings in Integer in C sharp:
   1. Parse() method
   2. Convert class
   3. TryParse() method

#### Article quality
In this article, I will show the novices different ways to convert a string to an integer using the above method and explain them in detail.  Programming examples will be on point and easy to understand even for the novices.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic - or continue working on this one by flushing it out a bit more (i.e. making it more in depth - "such as covering the video and audio APIs like this article and/or providing more detail about how the APIs work or some suggestions to readers as to how they could extend the web app shown (i.e. what extra functionality they could implement).")
