### ISSUE TITLE
[Artificial Intelligence] Overview of Microsoft SSIS

### ISSUE THREAD

**Issue by Yakobo5** [section-engineering-education/engineering-education#5939]
#### Introduction
SQL Server Integration Service is a data storage solution that allows you to extract, manipulate, and load data quickly and easily. It makes it simple to transfer data from one database to another, such as SQL Server, Oracle, or an Excel spreadsheet. In this article, we will learn how SSIS works and the requirements of its integration service. In addition for better understanding, we'll have an example of both a data flow task and an execute SQL task

#### Key takeaways 
1. SSIS definition and how it works
2. SSIS tasks and packages
3. Advantages and disadvantages of SSIS
4. SSIS Best Practices

#### Article quality
The article will be unique as it will cover well-explained examples of how SSIS tasks and packages work. To add on, there will be SSIS best practices as an additional topic. 

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
