### ISSUE TITLE
[Machine Learning] EvalML AutoML Library To Automate machine learning processes

### ISSUE THREAD

**Issue by francis966** [section-engineering-education/engineering-education#5940]
#### Proposed title of article
[Machine Learning] EvalML AutoML Library To Automate machine learning processes

#### Proposed article introduction
EvalML is an AutoML library that builds, optimizes, and evaluates machine learning pipelines using domain-specific objective functions. EvalML can be used to create end-to-end supervised machine learning solutions which are more efficient. EvalMl is used to determine the best-optimized machine learning algorithm in building the model.

By using the best algorithm, the model will have also the best performance and be able to make accurate predictions. This library also automates the processes of Feature Engineering, Feature Selection, Model Creation, And Tuning. This saves time and simplifies the machine learning development process.

Some of the key functionalities of EvalMl are:
- Automation, Data Checks, End-to-end processing, Model Understanding, and Domain-specific modeling.

#### Key takeaways 
1. What is EvalMl.
2. Key functionalities of using EvalMl in model building.
3. Installing EvalMl.
4. Using AutoML to select the best algorithm.
5. Getting The Best Pipeline to produce an optimized model.

#### Article quality
This article is unique because it explores EvalMl in detail.  We will first explore the key functions and methods that EvalMl uses to automate the machine learning process. After this, we will use these functions and methods to build a custom model. We will then use EvalMl to select the best algorithm and get the best pipeline. This will provide a more accurate model, this tutorial will be beginner-friendly and the reader can easily follow the guided steps.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
What dataset will you be using in the article?
