### ISSUE TITLE
[Machine Learning] Customer Segmentation using K-Means Clustering

### ISSUE THREAD

**Issue by charlesndirutu33** [section-engineering-education/engineering-education#5941]
#### Proposed title of article
[Machine Learning] Customer Segmentation using K-Means Clustering

#### Proposed article introduction
Customer segmentation is the process of dividing customers based on their common characteristics – such as demographics or behaviors, so you can market to those customers more effectively. By understanding the market segments, you leverage this targeting in the product, sales, and marketing strategies 

Market segments are used to power product development cycles by informing how you create product offerings for different segments like men vs. women or high income vs. low income.  Market segmentation is crucial for growing profits since it helped companies to know and understand their target markets.

In this tutorial, we will build a model that is able to cluster groups of people depending on the income they earn. We will use the K-means algorithm which is an unsupervised algorithm. The algorithm will identify patterns in data sets containing data points that are not labeled and learn on their own.

#### Key takeaways 
1. What is customer segmentation?
2. Types of segmentation.
3. Segmenting customers based on income earned.
4. Implementing the model using the K-means algorithm.
5. Using the model to plot customer clusters.

#### Article quality
This tutorial will be detailed, we will discuss the different types of customer segmentation before focusing on income segmentation. The tutorial will follow guided steps that are easy to follow and implement. We will also explore the K-means algorithm in detail and the different methods used for clustering. Finally, we will plot the cluster using a scatter plot that will show the distribution of customers.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
What dataset will you use in the article?

**Comment by charlesndirutu33** [comment]
@lalith1403, In this tutorial, I will use this [dataset](https://drive.google.com/file/d/1fQrgIuTwQRtQpAxEgoGcbRjZ28mFrriT/view?usp=sharing). The dataset contains a list of mall customers with their annual income. The dataset also shows their spending, this will be used to build the customer segmentation based on income and their expenditure.

**Comment by lalith1403** [comment]
Thank you for the topic suggestion, however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
