### ISSUE TITLE
Introduction to Rust's type-level recursion

### ISSUE THREAD

**Issue by elizabeth962** [section-engineering-education/engineering-education#5942]
### Topic Suggestion
Introduction to Rust's type-level recursion

### Writing sample(s): 
Include any links or writing samples to help our team gauge your writing quality better.

#### Proposed title of the article
Introduction to Rust's type-level recursion

#### Proposed article introduction
Rust follows the object-oriented model of programming, where the type itself defines the type behavior. Unfortunately, Rust's way of adding behavior to types is difficult to grasp, and it is impossible to add behavior to types without changing the type itself.

Type recursion is a way to define the behavior of a type without changing the type itself. It also refers to evaluating types at compilation time to confirm that a given type class instance exists at a function invocation site. This behavior is different from the runtime value-level recursion, which occurs when we invoke a function that invokes itself.

The article will explain the Rusts type trait system and implement a trait system dealing with type recursion.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways
1. Overview of Rust's type system.
2. Using Rust's Frunk types to define a type system.
3. Manipulating values in HList using the `pluck` function.

#### Article quality
Most of the articles on the web introduce the Rust type system but do not go into Rust's trait system and how to implement the type-level recursion.

#### References
1. [Rust's type system](https://doc.rust-lang.org/book/ch03-02-data-types.html)

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
