### ISSUE TITLE
[Security] Introduction to Secrets Management with Doppler 

### ISSUE THREAD

**Issue by LynetteMwe** [section-engineering-education/engineering-education#5943]
### Topic Suggestion
[Security] Introduction to Secrets Management with Doppler

#### Proposed article introduction
Without the right tool and knowledge, developers often fail to keep their secrets safe. But what are secrets? You may ask. 3rd party API Keys, database configs and urls, passwords and other data alike form secrets that developers are needed to safeguard in their applications.
In this article, we will look at how to manage developer secrets the best way possible, using Doppler solution.
#### Key takeaways 
1. What are Secrets
2.  Why manage Secrets
3.  Traditional and Unconventional ways of Managing Secrets
4.  Introducing Doppler- Managing Secrets the right way.
5.  Setting up Doppler CLI/Doppler Dashboard
6. Conclusion

#### Article quality
This article will be more user based. The reader will be shown how to start a project, add secrets, delete secrets setup environments and more. Besides a learner will obtain advise on some unconventional ways of managing secrets and then learn the best approach required when working with developer secrets.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @LynetteMwe
