### ISSUE TITLE
Getting Started with Boruta Algorithm in Machine Learning

### ISSUE THREAD

**Issue by nelsonnrl** [section-engineering-education/engineering-education#5946]
#### Proposed title of article
Getting Started with Boruta Algorithm in Machine Learning

#### Proposed article introduction
Boruta is a Machine Learning algorithm used in dimensionality reduction to select the most important features from high dimensional datasets. There number of dimensionality reduction algorithms such as Principal Component Analysis, Singular Value Decomposition, etc. One might wonder why we should learn Boruta Algorithm, yet we have all those other algorithms that can be scarry out the same objective. Well, techniques such as Principal Component Analysis take the original features and compress the information into a new feature representing the original one. In so doing, some of the information is lost. With Boruta, we don't generate new features from the original ones; instead, we select the best out of all the available features.

Now, how does the Boruta algorithm work?

At a high level, Boruta takes features of the original dataset and creates a copy of them. The values in all columns of this new feature space are shuffled to attain randomness. These shuffled features are known as *Shandow Features*. The shadow features are merged with the original features to obtain a new feature space whose dimension is twice that of the original dataset. It then creates a classifier on these new features and determines their importance. Now, the algorithm checks if the real feature has higher importance than its corresponding shadow feature. If it is, then the feature is kept; otherwise, it's regarded as insignificant and thus dropped from the dataset. 

On the features qualified on the first iteration, the algorithm again creates their respective shadow features and determines their feature's importance as in the first iteration. Some features are dropped while others are kept. We terminate the algorithm after a certain number of set iterations or when all features have been confirmed or dropped.

Above is the intuition behind the Boruta algorithm.

This tutorial will teach how to implement the Boruta algorithm in python. I intend to take the learner from the basic data preprocessing phase until we implement the Boruta algorithm. Then, we will move a step further and use the features it returns to build a predictive model and determine its accuracy score.

#### Key takeaways 
The key takeaways from this session will be:
The learner will be able to clearly explain how the Boruta algorithm works and have a good understanding of how it is implemented in python. Lastly, they will be able to state its advantages over other dimensionality methods and its disadvantages. All this will be taught in the tutorial.

#### Article quality
In this tutorial, we seek to provide learners a high-level approach to implementing the Boruta Algorithm and how to validate its ability by building a model using the data it returns. This means we shall have an extra step of showing Boruta did an amazing work by comparing the accuracy of such two models.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @nelsonnrl
