### ISSUE TITLE
AI PROJECT FOR LANGUAGE TRANSLATION

### ISSUE THREAD

**Issue by MBITHE4760** [section-engineering-education/engineering-education#5951]
Key takeaways
-Change the language.
-Change sprite and background.
-Explore and build your own program.
-Create your own code block to enable the user to change language to another language.

References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
