### ISSUE TITLE
[Language] Client Side Authentication with ExpressJs Cookies Parser

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#5959]
### Introduction
According to Wikipedia, authentication cookies are commonly used by web servers to authenticate that a user is logged in, and with which account they are logged in. Without the cookie, users would need to authenticate themselves by logging in on each page containing sensitive information that they wish to access. The security of an authentication cookie generally depends on the security of the issuing website and the user's web browser, and on whether the cookie data is encrypted.

### Key takeaways
At the end of this tutorial, readers would have knowledge of the following:
- General overview of web browser cookies
- How authentication cookies works
- Four ambient authority and signatures of cookies
- Demo for client side authentication with cookies parser library

### Article Quality
There are many articles on cookies and session but this tutorial will focus on how to authenticate client using expressjs cookies parser libaray. This will also be light but in-depth for readers to understand better.

### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @Horlawhumy-dev

**Comment by WanjaMIKE** [comment]
Closed #5959 via #6640
