### ISSUE TITLE
[ LANGUAGES ] Implementing multitenancy in a Django website using isolated Mongo DB databases with a shared app server

### ISSUE THREAD

**Issue by Sajeyks** [section-engineering-education/engineering-education#5971]
#### Proposed title of the article
[ LANGUAGES ] Implementing multitenancy in a Django website using isolated Mongo DB databases with a shared app server

#### Proposed article introduction

Multitenancy is whereby one web app installation can be used to serve more than one customer and each customer's data and users are isolated from each other's. example: Imagine that you built a web-based Library Management System for universities, and you want to provide your service to many universities without having to rebuild the same system for each university and hosting each.  

Multitenancy allows you to build one site and offer instances of your site to the universities as Software as a Service(SAAS) while keeping the data of each university isolated. Each university would be a tenant of your site hence the name Multitenancy.

#### Key takeaways 
At the end of the tutorial, the reader should be able to understand :
  1. What is multitenancy
  2. Importances of multitenancy 
  3. Implementing multitenancy in Django using this method
  4. Integrating Django with Mongo Db
  5. The advantages of using this method of multitenancy implementation
  
#### Article quality
This tutorial will look at how to implement multitenancy in Django using another Db other than the Default one provided by Django.
This will be done by building the web app from scratch in a step-to-step approach and then implementing the multitenancy to the app without neglecting the details. We won't use third-party Django apps.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by ahmadmardeni1** [comment]
I'm closing this topic-suggestion due to inactivity.
It can be reopened.

**Comment by Sajeyks** [comment]
Ready to PR .. please reopen @ahmadmardeni1
