### ISSUE TITLE
Simulating a Simple Epidemic Spreading Process on Graphs with Julia

### ISSUE THREAD

**Issue by csamuelsm** [section-engineering-education/engineering-education#5972]
#### Proposed title of article
Simulating a Simple Epidemic Spreading Process on Graphs with Julia 

#### Proposed article introduction
Graphs are structures that represent a set of objects and the relations between them. Formally, we say the objects are the vertices or nodes and the relations are the edges or links. We can often see graphs *“appearing”* around us. For example:

- vertices are cities and edges are roads that directly connect two cities;
- vertices are pages on the Web and edges are links that connect two pages;
- vertices are people and edges are the friendships between two individuals.

Those are just some of the applications of graphs — the list is huge.

Thanks to the nature of graphs, that is, the representation of pairwise interactions/relations, they are good structures to model the spreading of an epidemic. We can represent the individuals (people or animals, for example) as the vertices, and the contact/exposure as the edges.

We are going to model the epidemic as follows:

- every vertex will be in one of the following states:
    - S — Susceptible
    - I — Infected
    - R — Recovered
- at each time step:
    - some exposed susceptible vertices (neighbors of the previously infected vertices) are going to be infected
    - the previously infected vertices will recover and be no longer susceptible or infectious

That’s a simple model and it’s actually meant to be! But at the end of the tutorial, you will be able to make your own modifications and add new features or dynamics as you want.

#### Key takeaways 
- A simple real application of Graphs
- Manipulating Graphs in Julia
- Spreading process in Graphs

#### Article quality
I'm using Julia, a programming language that's not often explored in Section and I think this will add value to the Section community. The theme is a current theme and it will be explained in a simplified way but encouraging the reader to add their own features and to experiment with different dynamics. I will use Graphs and show how it can be used in Julia and a real application of the structure.

#### References
- [The Julia Programming Language](https://julialang.org/)
- [Graph (Discrete Mathematics) - Wikipedia](https://en.wikipedia.org/wiki/Graph_(discrete_mathematics))
- [Spreading processes on networks](https://aaronclauset.github.io/courses/5352/csci5352_F21_L9.pdf)

### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
How is it different than https://youtu.be/k0fr7XjH1_Y?

**Comment by csamuelsm** [comment]
@lalith1403 I'm using a Graph data structure to model the relationships between agents such as the contact or exposure. The model is simpler than the model showed in the video. The focus will be on the dynamics of spreading in such a structure, and how to use, manipulate and visualize Graphs in Julia to create this model: creation, edition, plotting, using the packages Graph.jl, MetaGraphs.jl, GraphPlot.jl etc.

**Comment by lalith1403** [comment]
Also make sure to avoid any overlap with the video. Thank you
