### ISSUE TITLE
[Machine Learning] Leveraging OpenAI Gym and the Anytrading Environment for Trading 

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#5973]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

Leveraging OpenAI Gym and the Anytrading Environment for Trading 

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

AnyTrading is a collection of OpenAI Gym environments for reinforcement learning-based trading algorithms. AnyTrading aims to provide some Gym environments to improve and facilitate the procedure of developing and testing RL-based algorithms in this area. 
In this tutorial, we'll leverage Anytrading environment to build a RL agent that can trade.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to understand:
- How to get started with Gym Anytrading environment
- How to install the environment
- How to load historical data from [MarketWatch](https://www.marketwatch.com/)
- Train an RL agent to trade using the Gym environment

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [Gym Anytrading](https://github.com/AminHP/gym-anytrading)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @Bayler
