### ISSUE TITLE
Solving common microservices problems with Spring cloud consul

### ISSUE THREAD

**Issue by faithsiaji** [section-engineering-education/engineering-education#5983]
### Topic Suggestion
Solving common microservices problems with Spring cloud consul

### Writing sample(s): 
Include any links or writing samples to help our team gauge your writing quality better.

#### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. 

#### Proposed article introduction
[Consul](https://www.consul.io/) is a distributed service discovery and configuration system. It is a distributed key-value store that provides a way to manage configuration across multiple servers. It solves some of the most common microservices problems like:-
1. Distributed configuration - enforces the rule that ensures that all the services use the same configuration.
2. Health checks - ensures that the services are running and healthy.
3. Service discovery - provides a way to discover the services running on the network. It provides a method of registering and unregistering the network location of service instances.

[Spring Boot consul](https://spring.io/guides/gs/consul/) is a Spring Boot starter that provides a convenient way to integrate Consul with Spring Boot. In addition, it provides a convenient way to configure Consul and Spring Boot. Consul is simple to use and provides the functionalities not provided by other distributed configuration systems like zookeeper or etcd.

The article will explain integrating a Spring Boot microservice application with Consul and deploying a distributed configuration and health check services.

#### Key takeaways 
1. Consul and Spring Boot integration.
2. Distributed Microservices health checks.
3. Distributed microservices configuration.

#### Article quality
The article will provide a detailed explanation of integrating Consul in a Spring Boot application. Unfortunately, most of the available tutorials for distributed configuration and health checks only explain zookeeper and etcd, which are very common, making it hard to find a detailed tutorial on integrating Consul for distributed health checks and configuration.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
