### ISSUE TITLE
How To Perform Data Visualization with Pandas

### ISSUE THREAD

**Issue by Ghassany** [section-engineering-education/engineering-education#5986]
### Proposed title of article
How To Perform Data Visualization with Pandas

### Introduction paragraph (2-3 paragraphs)
Data visualization is the most important step in the life cycle of data science, data analytics, or we can say in data engineering. In this article, you will learn how to make a visualization using Python Pandas library. Pandas library in python is mainly used for data analysis. It is not a data visualization library but, we can create basic plots using Pandas.. We will use this library to implement visualization elements like graphs, charts, maps, etc.

### Key takeaways:

- Creating a Data frame
- Creating a Line plot
- Creating a Bar plot
- Creating a Histogram plot
- Creating a Pie chart

### Article quality:
In this article, we will discuss how we can visualize data with data analysis library Pandas without importing any additional data visualization library. Each step in this article will be explained clearly such that even beginners can easily understand it.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Thank you for the topic suggestion , however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
