### ISSUE TITLE
[Android] Implementing Database Driven Push Notifications in Android with Firebase

### ISSUE THREAD

**Issue by JoelKanyi** [section-engineering-education/engineering-education#5992]
#### Proposed article introduction
Push notifications come in handy when you want to give your app's users timely information based on the product that the app is dealing with. Take, for example, an app that deals with giving out and repaying loans. It will be a bad user experience when a user makes a payment and he/she is not notified on the amount paid, balance and other relevant information.

In this tutorial, we will understand what Push notifications are and  their importance. We will then dive deep in understanding how one can send Push notifications based on changes in the Firebase Realtime database.

#### Key takeaways 
- An understanding of what Push notifications are.
- Setting up push notifications both on the Firebase console and on an Android project.
- An understanding of how to send Push notifications based on interactions with the database

#### Article quality
Most of the articles and blog posts on the internet focus on explaining how to setup Push notifications with Firebase and very few explains the concept of Database Driven Push Notifications in Android. This article and I will bring out this topic clearly, making it easy for developers of all levels to understand.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
