### ISSUE TITLE
Implementing RSA encryption Using Python

### ISSUE THREAD

**Issue by Mercycar** [section-engineering-education/engineering-education#5993]
### Topic Suggestion
Implementing RSA encryption Using Python

#### Proposed article introduction
 Data encryption is an important practice used to protect data transfer on the internet. RSA is one of the major cyber security method of data encryption used to send encrypted data on the network. The name RSA refers to the public-key encryption technology developed by RSA Data Security. The abbreviation stands for Rivest, Shamir, and Adleman, the inventors of the technique

In this article I will be looking at how this method of data encryption can be implemented using python. 

#### Key takeaways 
The concept of RSA encryption method
Understand how this method can be implemented using python
Understand the method of data transfer on a network

#### Article quality
This article will be taking the reader through the concept of RSA encryption, how data is transmitted on a network and how RSA can be implemented in python to ensure safe data transfer between the sender and the receiver.

**Comment by louisefindlay23** [comment]
Topic approved but please ensure your article is in-depth and unique enough to add value for our readers.
