### ISSUE TITLE
[Machine Learning] Visualizing Real Time Data using Data Science Tools

### ISSUE THREAD

**Issue by OkothPius** [section-engineering-education/engineering-education#5996]
#### Proposed title of article
[Machine Learning] Visualizing Real Time Data using Data Science Tools

#### Proposed article introduction
Data is a valuable resource to any profession; it becomes even an important aspect of your day-to-day life if you’re a data scientist.  Data scientists use data to find different insights depending on the necessity to be solved. These insights are then used to model and make the foundation of various decisions at different levels. 

As a prerequisite, data scientists need data in the first place. Platforms like TomTom simplifies this long hurdle by making it easier and more reliable for developers and data scientists to extract data from its APIs. They can then use their favorite tools to manipulate and put them to work. There are various ways of getting to play with data and understanding it better. Data visualization is of course the sure way to do so. It enables a developer or a data scientist to comprehend, process, and quickly gain insights by just looking at the trends and patterns. 

In the following article, we’ll go through a hands-on demonstration on how to use TomTom APIs to visualize Real Time Traffic data.

#### Key takeaways 
1. Introduction to Data Science tools
2. Understanding TomTom Traffic API
3. Visualizing Traffic Data using Matplotlib, Seaborn
4. Best Practices for retrieving and visualizing data

#### Article quality
In this article, we'll be going through how to visualize traffic data from a real-time API using Data Science tools such as Matplotlib and Seaborn. Several articles that have already been done on the same topic mainly use data fetched from a CSV file or JSON file (static data). There is no clear article that delves into visualizing real-time data from an API. 

#### References
N/A

**Comment by ahmadmardeni1** [comment]
I'm closing this topic-suggestion due to inactivity.
It can be reopened.
