### ISSUE TITLE
Building a Video Streaming Application with Spring Boot

### ISSUE THREAD

**Issue by john-amiscaray** [section-engineering-education/engineering-education#5998]
#### Proposed title of article

Building a Video Streaming Application with Spring Boot

#### Proposed article introduction

Many of the most popular applications the world use today use some form of video streaming functionality. Being able to implement this feature can give you and your users a lot of creative power to play with. In this guide, we will cover how we can do this using a simple Spring Boot application and a Javascript frontend. In the process, we will discuss what our client and server are doing behind the scenes to make this possible. Finally, as a bonus, we will see how we can write automated tests for our backend.

#### Key takeaways 
- Managing video file uploads
- Client-server communication
- How is the video sent to the client behind the scenes (ex. range header)
- How to write unit and integration tests for our application

#### Article quality
In this guide, I will be making a simple project to demonstrate how one would go about creating a video streaming application with Spring Boot. Unlike other resources about this topic, I will be showing how to dynamically get video files via REST endpoints and a database instead of using static video files. Additionally, some of the other sources I’ve seen used overly complex code to make this possible when it can be done fairly easily leveraging Spring. Finally, I’ve decided to show how someone can write unit and integration tests for the application as a bonus for anyone who wants to learn to do so. This can help anyone thinking of building this type of application not only know the approach to use but be able to do so in a clean, maintainable way.

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=Building+a+Video+Streaming+Application+with+Spring+Boot) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by john-amiscaray** [comment]
@louisefindlay23 thanks for your concern. There are a few ways I have planned to add unique value to this article. I've looked at a few of said articles/resources and some of them would use static video files saved on the server whereas I plan to show how you would retrieve these files dynamically from a client-side application. Additionally, I'll be showing more of the client-side of things (i.e. retrieving the names of all the saved videos, using query parameters to select specific videos to play, etc.) which I haven't seen in other guides. Lastly, I also plan on showing how you would write automated tests for the backend as some additional content that I think the reader could benefit from. Overall, I envision this to be more project-based than the other resources, showing more of what the process of building a full video streaming application would be like rather than just showing the core features that could make it possible.

**Comment by john-amiscaray** [comment]
Although I plan it to be project-based, I will be leaving out some features such as styling and user authentication just for the sake of the article not being overly long and to get straight to the point.
