### ISSUE TITLE
[Machine Learning]: An Introduction to Dimensionality Reduction in Python

### ISSUE THREAD

**Issue by srishilesh** [section-engineering-education/engineering-education#6003]
### Topic Suggestion
Machine Learning

### Writing sample(s): 
https://www.section.io/engineering-education/authors/srishilesh-p-s/

#### Proposed title of article
An Introduction to Dimensionality Reduction

#### Proposed article introduction
Dimensionality reduction refers to techniques for reducing the number of input variables in training data. When dealing with high dimensional data, it is often useful to reduce the dimensionality by projecting the data to a lower dimensional subspace which captures the “essence” of the data.

In this article, the reader will be learning the concept of dimensionality reduction in-detail. Also, the reader will understand and learn to implement various types of dimensionality reduction using Scikit library in Python.

#### Key takeaways 
- The reader will understand what dimensionality reduction is, it's significance in building effective deep learning models
- The reader will understand different ways to reduce dimensions of the dataset
- The reader will be exploring about built-in functions in scikit library to understand it's code implementation.

#### Article quality
- At Section, we do not have any articles related to dimensionality reduction of machine learning datasets
- Although, we have few articles discussing 1 or 2 types of dimensionality reduction with some application, we don't have a common article that lists down all types of dimensionality reductions along with it's implementations.

#### References
- https://en.wikipedia.org/wiki/Dimensionality_reduction

**Comment by lalith1403** [comment]
Hello @srishilesh. This topic is widely covered on the internet. A simple Google search gives 100s of results. How do you plan to make this unique?

**Comment by srishilesh** [comment]
Hey @lalith1403,

Thanks for checking this out.

I totally agree, this topic looks a little repetitive.

When I looked for such articles on the internet, a majority of the articles had its implementations done via Sci-kit library, but most of them would have algorithms built from scratch.

Here, I'll be explaining the mathematical intuitions behind PCA and SVD,  also implement them from scratch. Apart from these, I'll be explaining more about the curse of dimensionality reduction.

I'm pretty sure that you would also have some amazing suggestions that I could possibly use to add more value to the article. Please let me know.

Thanks.

**Comment by lalith1403** [comment]
Thank you for the reply. Implementing from scratch has been covered extensively especially on the Machine Learning mastery blog. I would suggest you propose a new topic. Thank you.

**Comment by srishilesh** [comment]
> Thank you for the reply. Implementing from scratch has been covered extensively especially on the Machine Learning mastery blog. I would suggest you propose a new topic. Thank you.

@lalith1403 

Noted. Thanks for the reply.
