### ISSUE TITLE
HTML5 Document Structure

### ISSUE THREAD

**Issue by Shee254** [section-engineering-education/engineering-education#6004]
#### Proposed title of article
HTML5 Document Structure

#### Proposed article introduction
In this lesson, you will learn about the basics of HTML5. How do you structure a document? What are header and footer tags? An HTML 5 document mainly consists of a Head and Body. The Head contains the data, which informs the browser and even web servers that it is an HTML 5 document. On the other hand, the Body contains content that web browsers actually display.
This tutorial covers all the major elements necessary to craft a basic HTML 5 document.

#### Key takeaways
1.The basic structure
2.Establishing a Document Structure
3.The Body Element in HTML5
4.Headings in HTML5
5.Paragraphs in HTML5

#### Article quality
In this article HTML5 Document Structure, I will make it clear by the use of simple language and explaining all code snippets. I will be direct to the point explaining all bits of this concept

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
