### ISSUE TITLE
Learning the scroll effect in Kivy (Python)

### ISSUE THREAD

**Issue by Eli-Ch** [section-engineering-education/engineering-education#6005]
### Topic Suggestion
Learning the scroll effect in Kivy (Python)
#### Proposed article introduction
[Kivy]
The scroll effect is an animation in a website or an application triggered by scroll action. It makes it easier to make dynamic and interactive websites or other applications hence improving the experience.

The scroll effect helps the interactive websites or applications to bring more delightful content through the scroll. This keeps the readers or the users of the website hooked and spending more time on your site.

When you want to break content into a few sections, Adding a transition to the new section gives users a visual break cue. It suggests a section ends and a new one starts.
#### Key takeaways 
-Making the scroll effect in Kivy
-The learner will know the Two types of scroll effects in Kivy.
-The learner will be able to apply the 2 effects on Kivy projects.
#### Article quality
The article is a tutorial-based in python language to help learners create the scroll effect on their Kivy projects and make them more dynamic.

**Comment by ahmadmardeni1** [comment]
I'm closing this topic-suggestion due to inactivity.
It can be reopened.
