### ISSUE TITLE
Comparison Between CDPs and Data Warehouses

### ISSUE THREAD

**Issue by Pauline-Mwangi** [section-engineering-education/engineering-education#6010]
### Topic Suggestion
Comparison Between CDPs and Data Warehouses

#### Proposed title of article
Comparison Between CDPs and Data Warehouses

#### Proposed article introduction
using customer data as that's what they are meant to do. A data warehouse is a centralized repository where companies store their valuable data assets, including customer, sales, employee data, etc.  However, many often confuse a CDP with a Data warehouse, as in essence, a CDP does store data.

Of course, CDPs and Data Warehouses are different, which is what this article will be covering. This article will explain what sets them apart, why they are often confused, and the pros and cons of CDPs and Data Warehouses.

#### Key takeaways 
1. Understanding Customer Data Platforms (CDPs).
2. Understanding Data Warehouses.
3. CDPs VS Data Warehouses: Differences.
4. CDPS VS Data Warehouses: Where Confusion comes in.
5. CDPS VS Data Warehouses: Pros and Cons
#### Article quality
Customer Data Platforms (CDPs) are a great way of collecting, and This is article will thoroughly explain CDPs and Data Warehouses to readers. Also, it will explain what sets them apart, why they are often confused, and the pros and cons of each. This article will be more detailed, give unique and quality content.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Pauline-Mwangi** [comment]
@louisefindlay23, This article aims to compare CDPs and Data Warehouses. It will discuss both technologies in-depth to give readers a clear understanding. The two technologies are commonly confused by many. This guide will be clear and transparent, showing where the confusion comes in. The article will be much more detailed as it will also go through use cases and real scenarios of both technologies. The article will also look at which technology need to be considered the most and why.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
