### ISSUE TITLE
[Language] How To Integrate Django-Tailwind Styling In Application

### ISSUE THREAD

**Issue by Charity10** [section-engineering-education/engineering-education#6018]
### Introduction
Every application requires good stylings for better and readable contents.  Over the years, the Cascadian Styles Sheet,  CSS has dominated before frameworks came into existence. In this tutorial, we will be covering the way to integrate django-tailwind framework into an application.

### Key takeaways
At the end of this tutorial, readers should be able to apply this styling framework into their application. 

### Article Quality
This tutorial will lead readers to the proper way of integrating django-tailwind for the purpose of styling application.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
