### ISSUE TITLE
Comparing AWS Shared Responsibility Models for Different Products

### ISSUE THREAD

**Issue by BashiirIsla** [section-engineering-education/engineering-education#6019]
#### Article quality
This article explains beyond what is available in the official documentation by comparing different AWS Shared Responsibility Model products, discussing their strengths and weaknesses. it also shares the best practices for working with AWS Shared Responsibility Models - something which is not available in other blogs.
#### References
https://aws.amazon.com/compliance/shared-responsibility-model/

**Comment by lalith1403** [comment]
@hectorkambow @section-engineering-education/content-moderator-team Need your help with this issue.

**Comment by BashiirIsla** [comment]
Hi @lalith1403 
Do you have any updates on this issue?

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
