### ISSUE TITLE
[Languages] Building a Video cataloging app with React, firebase and React-styled-components

### ISSUE THREAD

**Issue by KingsleyJack** [section-engineering-education/engineering-education#6024]
### Topic Suggestion
Building a Video cataloging app with React, firebase and React-styled-components

### Writing sample(s): 
https://www.section.io/engineering-education/building-animated-signin-routes-with-react-and-bootstrap/
https://www.section.io/engineering-education/building-faq-page-using-react-styled-components-and-react/

#### Proposed title of article
Building a Video cataloging app with React, firebase and React-styled-components

#### Proposed article introduction
Video based social media websites and applications has experienced wide spread adoption over the decade from YouTube, Instagram and most recently TikTok.  With average monthly user exceeding a billion.
 Building a video cataloging app capable of displaying and playing videos in categories ranging from sports, entertainments, educational, etc. can be done with React.js and React-styled-components used in creating and styling the user interface and firebase used in uploading and managing the video. 

#### Key takeaways 
At the competition of this tutorial, the reader will have the understanding and knowledge to implement the following:
-	Getting started with React.js
-	Building a video cataloging app with React.js
-	Creating and managing firebase entries
-	Error handling in React.js and firebase
-	Customizing video components with react-styled-components

#### Article quality
This tutorial is a project-based application of React.js, firebase and react-styled-components in creating, managing, uploading, customizing and cataloging video entries. This article will walk the reader through the processes, dependences and steps required in building a video cataloging app with React.js and other modern web development packages.

#### References
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
