### ISSUE TITLE
Do We Need a Database When We Have Apache Kafka? 

### ISSUE THREAD

**Issue by jaykip** [section-engineering-education/engineering-education#6025]
#### Proposed title of article
Do We Need a Database When We Already Have Apache Kafka? 

#### Proposed article introduction
 Kafka has occasionally been described as something much more than just a better message broker. Proponents of this viewpoint position Kafka as a fundamentally new way of managing data, where Kafka replaces the relational database as the definitive record of what has happened. Instead of reading and writing a traditional database, you append events to Kafka and read from downstream views that represent the present state. This architecture has been described as “turning the database inside out“.

In principle, it is possible to implement this architecture in a way that supports both reads and writes. However, during that process, you will eventually confront every hard problem that database management systems have faced for decades. You will more or less have to write a full-fledged DBMS in your application code. And you will probably not do a great job, because databases take years to get right. You will have to deal with dirty reads, phantom reads, write skew, and all the other symptoms of a hastily implemented database.

#### Key takeaways 
Apache Kafka and database explained briefly 
Storage in Kafka 
Queries and Processing in Kafka
Transactions in Kafka
Kafka and ACID Guarantees

#### Article quality
This article digs deeper into Kafka storage functionalities while giving examples. It also deconstructs Kafka and databases. 

#### References
N/A

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
