### ISSUE TITLE
[Language]Generate PDF from MySQL Data using FPDF library 

### ISSUE THREAD

**Issue by taves-hub** [section-engineering-education/engineering-education#6030]
#### Proposed title of the article
Generate PDF from MySQL Data using FPDF library

#### Proposed article introduction
PDF is a very common and popular file format to read, view, and write documents.PDF format is independent of application software, hardware, and operating systems.  It is easy for anyone to deliver PDFs because they are a standard document presentation format. 

FPDF is an open-source library in PHP  used to generate PDF. In this article, we going to read MySQL table data using PHP. And then call FPDF functions to generate PDF from this MySQL data.

You may be thinking that it would be a complex undertaking due to the FPDF library but it's just about as simple as ascertaining `1+1`.
In my final submission, I will prepare a step-by-step demo for learners, to show how we can create pdf documents from MySQL  Data using the FPDF library
#### Key takeaways 
- By the end of this exercise learners will be able to :
    1. Overview of FPDF
    2. Select the data from MySQL database into the page
    3. Getting the FPDF library from fpdf.org.
    4. Copy the fpdf.php file into your application folder.
    5. Include the fpdf.php file into your application file.
    
#### Article quality
This article will help learners with the basics they need to get started with FPDF library. Many articles out there only rely on official documentation and some of the examples they offer are a bit too harsh for novices in PHP. This article will be ideal for novices and the code snippets involved will be illustrated clearly and will be straight on point.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Thank you for the topic suggestion, however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
