### ISSUE TITLE
How to build a Decentralized Chat App

### ISSUE THREAD

**Issue by June-Johnson** [section-engineering-education/engineering-education#6031]
### Proposed title of the article

[Blockchain]How to build a Decentralized Chat App

### Proposed article Introduction
DApps, or decentralized applications, are digital applications with backend code that runs on a decentralized peer-to-peer network of computers. The Dapps are constructed on a blockchain system like Ethereum or Bitcoin and run on it, giving consumers more control over their data and removing the need for centralized control.

In this article, you will learn how to build a decentralized Chat App Using the GUN JavaScript library. The Chat App is a group chat app that can handle thousands of messages per second and also relies heavily on cryptography to implement things like user authentication.

Gun is an open-source cybersecurity technology for syncing decentralized graph databases, it allows one to create community-run and encrypted applications.

#### Key takeaways
At the end of the article the reader should:

- Understand Decentralized applications 
- Be able to build a Dapp using Gun.js

#### Article quality
This essay stands out because it is straightforward, direct, and to the point. I'll guide the reader through simple and easy step-by-step methods for creating a decentralized chat app with Gun.js. 

#### References
- https://gun.eco/
- https://ethereum.org/en/dapps/
- www.freecodecamp.org/news/what-is-web3/

**Comment by lalith1403** [comment]
Thank you for the topic suggestion, however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
