### ISSUE TITLE
[Languages] Hands-on Python-based data visualization using Dash Plotly.

### ISSUE THREAD

**Issue by Nancy245** [section-engineering-education/engineering-education#6032]
### Writing sample(s): 
- [Track users of your site using google analytics](https://www.section.io/engineering-education/track-users-using-google-analytics/)
#### Proposed title of the article
Hands-on Python-based data visualization using Dash Plotly.

#### Proposed article introduction
For web analytics, Dash is a Python framework. You don't need to know HTML, CSS, JavaScript, or any other front-end framework or language to build attractive and fast web dashboards with Dash instead. We'll create our own Dash online dashboard as part of this lesson.

#### Key takeaways 
- By the end of this lesson learners will be able to:
1. Understand what exactly Dash Framework is.
2. Understanding the 3 pillars of Dash Framework.
3. How to set up Data in Dash 
4. Set-up APP Layout section
5. Get to know the Plotly Dash community Forum

#### Article quality
As a result of the extracted information, data visualization helps decision-makers make informed business decisions, increasing customer retention and profits. The necessity to grasp and appreciate Data visualization technologies like Python emerges from this extremely important and in-demand talent. A practical example of how we can visualize data in Dash will be provided in this article.
#### References
N/A

**Comment by lalith1403** [comment]
Thank you for the topic suggestion, however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
