### ISSUE TITLE
[Machine Learning] Teaching AI to Play Space Invaders using Reinforcement Learning

### ISSUE THREAD

**Issue by lcheop** [section-engineering-education/engineering-education#6036]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

Teaching AI to Play Space Invaders using Reinforcement Learning

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

In this tutorial, we will take a look at how you can use Reinforcement Learning to play Atari games. Specifically, we are going to take a look at Space Invaders. We will use the OpenAI's Gym environment and TensorFlow to train an AI model to play the game autonomously. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to:
- Build an Atari environment using OpenAI Gym
- Set up a deep learning model using TensorFlow Keras API
- Train the model using Keras-RL agents.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

[SpaceInvaders-v0](https://gym.openai.com/envs/SpaceInvaders-v0/)

**Comment by lalith1403** [comment]
Thank you for the topic suggestion, however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
