### ISSUE TITLE
[Languages] How to Build a Snake Game In JavaScript

### ISSUE THREAD

**Issue by Kamau-ke** [section-engineering-education/engineering-education#6037]
#### Proposed title of article

How to Build a Snake Game In JavaScript

#### Proposed article introduction
Hands-on projects are the best way to learn any programming language. The Snake Game is a simple game that can be created using the fundamentals of JavaScript and HTML.
Snake is an old-school video game from the late 1970s. The basic goal is to navigate a snake while eating as many apples as possible while avoiding contact with the walls or the snake's body.
In this article, I’ll show you step-by-step how to create this Snake Game using JavaScript and HTML

#### Key takeaways 
1. Display the board and a still snake
2. Make the snake move automatically
3. Use arrow keys to change the snake’s direction
4. Incorporate food and score

#### Article quality
This article will provide learners with a deep understanding of javaScript. Many articles on the internet rely on official documentation, and their examples are hard for beginners to understand. This article will be perfect for novices, as the code snippets will be well demonstrated and straight to the point.

#### References
N/A

**Comment by louisefindlay23** [comment]
Many [articles](https://www.google.com/search?client=firefox-b-d&q=How+to+Build+a+Snake+Game+In+JavaScript) exist that tailor to novices. Is there anything you can add to make it more unique?

**Comment by Kamau-ke** [comment]
@louisefindlay23  I believe that knowledge can never be exhausted, and when I look at nearly similar content online, the majority are not beginner-friendly and are not as engaging as they could be. Of course, this article will be one-of-a-kind, and it will address these issues as gracefully as possible in order to maintain quality and add value to the community. Thanks
