### ISSUE TITLE
[Machine Learning] AutoNLP using AutoVIML library for Natural Language Processing

### ISSUE THREAD

**Issue by jamesomina99** [section-engineering-education/engineering-education#6038]
#### Proposed title of article
[Machine Learning] AutoNLP using AutoVIML library for Natural Language Processing

#### Proposed article introduction
Natural language processing is the branch of computer science that enables machines to understand the text. This process is usually hectic and has many processes. But with the use of AutoVIML which is an AutoNLP library natural language processing has been made easier. AutoVIML builds more robust models that are more effective to perform NLP tasks.

AutoVIML automates the processes of EDA and text processing to format the dataset correctly. It also automates the processes of stemming, tokenization, lemmatization, CounterVectorizer, and TfidfVectorizer. It automates this process using a machine learning Pipeline, this saves the developers time and makes the process of natural language processing easier.

In this tutorial, we build a product review model using AutoVIML. AutoVIML will be able to build a model that classifies customers reviews as either positive or negative.

#### Key takeaways 
1. What is AutoNLP?
2. Installing AutoVIML.
3. Dataset preparation using AutoVIML.
4. Creating a machine learning pipeline to automate the NLP processes.
5. Building the product review model using AutoVIML.

#### Article quality
In this tutorial, we will first explain the stages involved in natural language processing in detail. This will give a reader a deeper understanding of NLP concepts before introducing the AutoNLP concepts. This tutorial will also cover the important  AutoVIML functions that help with the automation process. This tutorial will be detailed and have guided steps that a reader can easily follow. We will finally build a custom product review model.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=AutoNLP+using+AutoVIML+library+for+Natural+Language+Processing) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by jamesomina99** [comment]
Hello @louisefindlay23, In this tutorial, I will be using the `tensorflow_datasets` package for easy loading and pre-preprocessing of our dataset. I will also implement the [Shap](https://shap.readthedocs.io/en/latest/index.html) library to interpret the decisions made by the AutoVIML library. When we integrate Shap and AutoVIML library, this creates more value to the reader, and they build a more sophisticated model. This is because it enables us to understand every decision made during the automation process.

Also, we will build a custom model which is not covered in the other articles, this model will be a sentiment analysis model.
