### ISSUE TITLE
Building notes app using Quasar Framework

### ISSUE THREAD

**Issue by Beatricemuli** [section-engineering-education/engineering-education#6039]
#### Proposed title of article
Building notes app using Quasar Framework 

#### Proposed article introduction
Building cross-platform has been my dream in Software development world, JavaScript healed this wound by coming through with a nice Quasar framework. 
Quasar is an open-source Vue.js-based cross-platform framework that allows developers to build apps both mobile and desktop using wide technologies like Electron and Cordova in a single codebase.
In this tutorial, I'll be building a notes app using firebase to store and retrieve data. I will explain step-wise the from it's installation to deployment. 
#### Key takeaways 
1. Understanding Quasar framework and it's libraries
2. Understanding firebase and how to retrieve data from it using Quasar framework
3. Building a real-time application using quasar  
#### Article quality
This tutorial will provide in-depth understanding to the readers on quasarjs framework and using it to build an application from scratch. 
#### References
1. https://quasar.dev/
2. https://betterprogramming.pub/an-introduction-to-the-quasar-framework-3fed8bc92f6d

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be an article that already covers this [topic](https://www.smashingmagazine.com/2021/10/introduction-quasar-framework-cross-platform-applications/)? Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by Beatricemuli** [comment]
Hello @louisefindlay23 In this tutorial will dive deep using a different approach in this [topic](https://www.smashingmagazine.com/2021/10/introduction-quasar-framework-cross-platform-applications/) which is more covering what is the documentation, since i'll include containerization of application too

**Comment by ahmadmardeni1** [comment]
I'm closing this topic-suggestion due to inactivity.
It can be reopened.
