### ISSUE TITLE
[Machine Learning] Image Classifier using Transfer Learning with Tensorflow

### ISSUE THREAD

**Issue by charles721** [section-engineering-education/engineering-education#6040]
#### Proposed title of article
[Machine Learning] Image Classifier using Transfer Learning with Tensorflow

#### Proposed article introduction
Transfer learning is a deep learning technique that first trains a neural network model on a problem similar to the problem that is being solved. It enables the model to store knowledge gained when solving one problem and applying it to a different but related problem. Transfer learning decreases the training time for the neural network and produces a model with very high performance.

An example of transfer learning is when an image classifier model that is trained to classify lemons is applied to classify oranges. Lemons and oranges are different but related problems. In transfer learning, we just need to fine-tune the original model so that it can work according to our needs.

In this tutorial, we will build an image classifier model that is used to identify the rock-paper-scissors game. We will first import a pre-trained model from the TensorFlow hub before fine-tuning it to play the rock-paper-scissors game.

#### Key takeaways 
1. What is transfer learning?
2. Concepts used in image classification
3. Downloading the pre-trained image classification model from the TensorFlow hub.
4. Fine-tuning the model to understand the rock-paper-scissors game.

#### Article quality
In this tutorial, we will explain the concepts of image classification in detail before we jump into the concept of transfer learning. In the tutorial, we first use simple examples to explain the concept of transfer learning. This gives a reader a deeper understanding of transfer learning and it will be much easier for the reader to understand image classification using transfer learning. The tutorial will also build a custom image classification model that is able to understand the rock-paper-scissors game.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=Image+Classifier+using+Transfer+Learning+with+Tensorflow) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by charles721** [comment]
Hello @louisefindlay23, I will build upon them first, using the latest version of TensorFlow, TensorFlow Core v2.7.0. This new version has new methods and functions used for transfer learning. The other tutorial uses in-built examples to explain transfer learning but in this tutorial, I will be building a unique model. The model will be used to identify the rock-paper-scissors game symbols. I will implement TensorFlow BERT models that will help in fine-tuning our image classifier model.
