### ISSUE TITLE
[Machine Learning] - Understanding PASCAL VOC dataset

### ISSUE THREAD

**Issue by srishilesh** [section-engineering-education/engineering-education#6047]
### Topic Suggestion
Machine Learning

### Writing sample(s): 
https://www.section.io/engineering-education/authors/srishilesh-p-s/

#### Proposed title of article
Understanding PASCAL VOC and COCO datasets

#### Proposed article introduction
Object detection refers to the capability of computer systems to locate desired objects in an image/scene and identify each object. For detection of objects, the training data are either represented using XML files or JSON files. Each representation has it's pros and cons.

In this article, we will be looking at what PASCAL VOC and COCO are, understand the history behind it, how it helps with object detection, which meta-data helps solving detection and segmentation problems, and finally understand the difference between them.

#### Key takeaways 
- The reader will get an insight of what PASCAL VOC and COCO are.
- The reader will understand the history behind these representations
- The reader will understand how exactly is it used for object detection and other segmentation problems.

#### Article quality
This article would deal with explaining explaining, comparing and contrasting the different representation of datasets that we use for detection and segmentation problems. The reader will understand how these representations makes it easier for annotation.

#### References
- http://host.robots.ox.ac.uk/pascal/VOC/
- https://cocodataset.org

**Comment by srishilesh** [comment]
@lalith1403 

As we had discussed via Slack - regarding #5067 , I have created this new issue - which becomes the "Part 1" of #5067

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @srishilesh
