### ISSUE TITLE
[Languages] Learn How to Use React Dashboard to build dashboards in React

### ISSUE THREAD

**Issue by Raphmugo06** [section-engineering-education/engineering-education#6055]
#### Proposed title of the article

Learn How to Use React Dashboard to build dashboards in React

#### Proposed article introduction

Flatologic is a dashboard design company that offers both free and premium options. It's possible to find pre-built applications for Angular, Vue, and React developers. Instead of starting from scratch, this reduces the amount of code and saves time. The free React Dashboard template will be the focus of this essay. GraphQL and Redux are also used in this template. Node.js backend with a React front-end. The design is flexible and secure. In just three easy steps, you'll discover how to build a dashboard in this instructional Exercise. To save local data, we'll utilize MAMP in conjunction with a SQL database.

#### Key takeaways 
- Learners will find the following captivative:
1. Getting React Dashboard up and running.
2. Setup dashboard and the table.
3. App's database and the local database
4. Testing of the application

#### Article quality

By reading this article learners will find out how you can utilize ready-made dashboards and customize them to your satisfaction in react.  They will also appreciate the fact that it's not necessary that you start a project by writing codes from scratch instead you can just utilize a few of them which are just waiting to be used.  The good thing with this article is that it will be in depth and all source codes and snapshots will be well explained to enhance growth of the community
#### References
N/A

**Comment by lalith1403** [comment]
Aren't there existing articles on this? There are articles with the same topic. Can you expand on how it will be different?

**Comment by Pato-254** [comment]
@lalith1403 Hello, The reason why I suggested this topic was because most of the blogs that I have gone through are sugar-coated with what is already covered in the documentation. Most of them have not shown how you can use react dashboards and view them locally, All of them don't actually tell learners why they should have react Dashboards among other issues. These are some of the issues that I would like to address in my article to further provide knowledge to the community

**Comment by lalith1403** [comment]
Topic approved.
