### ISSUE TITLE
[Security] How to perform containerized static application security testing(SAST) using MobSF within a Docker container

### ISSUE THREAD

**Issue by RuthAMare** [section-engineering-education/engineering-education#6058]
#### Proposed title of article
Static application security testing(SAST) using MobSF in a Docker container

#### Proposed article introduction
This article will introduce a reader to application vulnerability testing, outlining the various ways of performing the same. This article will try to make a brief comparison between the static testing method and dynamic method and any other methods in existence.

The article will further focus on the static secutity testing method outlining step by step process of how it works and analyze the results obtained from SAST together with its advantages. This article will use MobSF framework from within a docker container to perform the step by step process of SAST. 

#### Key takeaways 
The reader should master:
1. What is SAST
2. Differences between SAST and DAST
3. Tools used in application security testing
4. Step by Step process of how SAST works
5. Advantages and Disadvantages SAST

#### Article quality
This article will not only cover a detailed process of application security testing but also give the various tools used apart from the tool of focus, and also explain what security testing entails in theory.

#### References
N/A

**Comment by lalith1403** [comment]
The suggestion does not talk about how docker container is used in this article.

**Comment by RuthAMare** [comment]
@lalith1403, the testing will be done from inside a docker container, more of a containerized testing.

**Comment by RuthAMare** [comment]
@lalith1403, the testing will be done from inside a docker container, more of a containerized testing.

**Comment by lalith1403** [comment]
Can you modify the topic suggestion?

**Comment by RuthAMare** [comment]
@lalith1403 , I have modified the topic.
Will that do?

**Comment by lalith1403** [comment]
I meant the topic suggestion. The entire description of what you intend to do. Not just the title.

**Comment by RuthAMare** [comment]
Done

**Comment by RuthAMare** [comment]
@lalith1403 is the modification fine?

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
