### ISSUE TITLE
Building a simple bot scraper to extract prices data

### ISSUE THREAD

**Issue by yitzackRabin** [section-engineering-education/engineering-education#6059]
### Topic Suggestion
Nodejs

### Writing sample(s): 
https://www.section.io/engineering-education/building-a-simple-cryptocurrency-blockchain/

#### Proposed title of article
Building a simple bot scraper to extract prices data
#### Proposed article introduction
It's tedious to always for companies and developers to get prices for their products while trying to fit the market competition. Due to large data available online, it's easy for individuals and companies to hunt for prices and make huge bargain on there products by simply using web bot scraper.
Web scraping is the process of using bots to extract content and data from a website. This makes it easy to get large data than "copy" and "paste" which is time consuming.
In this tutorial, I'll explain using example how to build a simple bot to extract data that maybe use useful to enhance product competiveness in the world market using nodejs.

#### Key takeaways 
1. Readers will understand web scraping use.
2. Readers will enhance their knowledge in nodejs to extract data in different platforms.
3. Readers will have ability to develop rea-time applications.

#### Article quality
This article will dive deep into web scraping using simple examples to the readers, we'll also explain some simple tools used over the world.

#### References
1. https://webscraper.io/
2. https://www.geeksforgeeks.org/what-is-web-scraping-and-how-to-use-it/

**Comment by lalith1403** [comment]
Thank you for the topic suggestion, however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
