### ISSUE TITLE
Practical Guide On The java Stream API With Examples

### ISSUE THREAD

**Issue by gisioraelvis** [section-engineering-education/engineering-education#6072]
## Proposed title of the article
[ Languages, Java, Stream API ] Practical Guide On The java Stream API With Examples

## Proposed article introduction
The Stream API in Java is used to process in-memory data following a map/filter/reduce approach sequentially. This tutorial will be a guide through the Stream API demonstrated in a practical way with examples. 

## Key takeaways 
- How to use the Stream API in Java.
- In-depth guide and core concepts around the Stream API.
- Practical examples of using the Stream API in Java with examples.

## Article quality
In this article, we explore the core concept of Stream API from the ground up in a clear and concise manner making it friendly for beginners and people with no prior knowledge. 

## References
[Stream API](https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html)
[The Stream API](https://dev.java/learn/the-stream-api/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=Practical+Guide+On+The+java+Stream+API+With+Examples) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?
