### ISSUE TITLE
The impact of reinforcement learning in artificial intelligence

### ISSUE THREAD

**Issue by KayTee24** [section-engineering-education/engineering-education#6073]
### Proposed title of article
The impact of reinforcement learning in artificial intelligence

#### Proposed article introduction
Reinforcement learning is a strong artificial intelligence method for developing strategies for dealing with large, complex systems. It's transitioning from research labs to extremely effective real-world applications. Self-driving car startups like Wayve and Waymo use reinforcement learning to develop their control systems.
 Topic to be covered:
- Types of Reinforcement Learning
- How does reinforcement learning work?
- The effect of reinforcement learning
- Learning Models of Reinforcement
- Why use Reinforcement Learning?
- When Not to Use Reinforcement Learning?
- Challenges of Reinforcement Learning
- Examples were reinforcement learning is used in problem solving
- Reward maximization through reinforcement learning

#### Key takeaways 
The learner should be able to:
- Understand the types reinforcement learning
- Under the concept of reinforcement learning
- Tell why reinforcement learning is important
- Tell when not to used reinforcement learning in modeling
- Tell the challenges of reinforcement learning
- Understand the reward maximization of reinforcement learning

#### Prerequisites
-  Beginners understanding on the concept of  decision making
-  Basic knowledge of Artificial Intelligence

#### Article quality
This will be a very comprehensive article on the subject. It will clarify important details not covered in the manuals or elsewhere. For novices, I'd like to make it simpler to understand and use. Examples will be used to provide additional information on when to utilize reinforcement learning and when not to, as well as the impact of reinforcement learning.

#### References
N/A

#### Conclusion
Reinforcement learning will be better positioned to gain an advantage in numerous industries because it tends to tackle problems that previous modeling approaches haven't been able to handle.
Reinforcement learning isn't magic, and it won't identify the best path right away. False starts are also conceivable. When used correctly and given enough time, reinforcement learning can help firms develop unexpected and creative ideas to help them outperform their competitors.

**Comment by louisefindlay23** [comment]
How will your article be one of a kind? That it what you need to write in the Article Quality section.

**Comment by KayTee24** [comment]
Good evening @louisefindlay23 ,
 I have stated your needed point about the article's quality.

**Comment by ahmadmardeni1** [comment]
I'm closing this topic-suggestion due to inactivity.
It can be reopened.
