### ISSUE TITLE
Building a blog using react hooks, strapi v4.0 and prism. 

### ISSUE THREAD

**Issue by muyiwexy** [section-engineering-education/engineering-education#6079]
#### Proposed article introduction
Strapi is an open-source, Node.js based, Headless CMS that saves developers a lot of development time while giving them the freedom to use their favorite tools and frameworks. Strapi also enables content editors to streamline content delivery (text, images, video, etc) across any device.

With react hook, we are able to fetch data from strapi using a designated endpoint. Through the use of react and prism syntax highlighter, we will create a blog containing data stored in our backend. 
 
#### Key takeaways 
In this article, the reader will learn:
 How to use strapi v4.0 to store content on the server. 
Use state hooks to fetch data from strapi.
Create a markdown enabled blog site using prism in react. 

#### References
N/A
### Conclusion

At the end of the tutorial, the reader should be able to achieve the aim of the tutorial above.

**Comment by LinusMuema** [comment]
Hi @muyiwexy 

Could you please expand upon how your content will differ from what is already available through the [Strapi website](https://strapi.io/blog/build-a-blog-with-next-react-js-strapi) and documentation?

**Comment by muyiwexy** [comment]
@LinusMuema, First, I am using a completely different syntax
Second, I am using state hooks to fetch data from strapi.
Third, the blog is markdown enabled and I am getting my media not from the local storage but from strapi itself. Strapi is going to act as a content manager in this article as well as a primary database.

**Comment by LinusMuema** [comment]
Hi @muyiwexy 
Make sure you capitalise on points like the database to make your article stand out as original. Otherwise, topic approved 🚀
