### ISSUE TITLE
Building a Cryptography Machine For Data Encryption and Decryption In Python

### ISSUE THREAD

**Issue by Joesongoma** [section-engineering-education/engineering-education#6080]
### Topic Suggestion
Building a Cryptography Machine For Data Encryption and Decryption In Python

### Writing sample(s): 
https://www.section.io/engineering-education/authors/joseph-ongoma/

#### Proposed article introduction
Encrypting data to be sent on a network is an important feature in the field of networking. This feature enhances the safety of data transmission preventing access of data from third-party access which is termed unauthorized access. For this reason many methods have been implemented to enable data security for transmission.

In this article, we will be discussing the concept of cryptography and how we can implement this feature using python as a programming language.

#### Key takeaways 
From this tutorial, we will be able to understand the concept of:
- cryptography
- data encryption and decryption
- basic python knowledge
The reader will also be able to implement or create his or her own cryptography for data encryption and decryption

#### Article quality
This article intends to take the reader through the concept of data encryption and decryption and a step-by-step on how the reader can implement the method of cryptography in python.

#### References
N/A

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
