### ISSUE TITLE
Performing recursion using Factorial and Fibonacci functions via MATLAB

### ISSUE THREAD

**Issue by peterAdongo** [section-engineering-education/engineering-education#6081]
### Topic Suggestion
Performing recursion using Factorial and Fibonacci functions via MATLAB

#### Introduction
 Recursion is a programming technique using a function or algorithm that calls itself one or more times until a specified condition is met, at which time the rest of each repetition is processed from the last one called to the first. It is a widely used idea in programming to solve complex problems by breaking them down into simpler ones. Recursion mostly occurs frequently in mathematical problems, where many examples of expressions are written in terms of themselves. Calculating the value of nth factorial and the nth Fibonacci number is the best example.

In this tutorial, we will see how to perform recursion by using the Matlab functions. It also looks at how to implement iterative factorial functions and look at the workflow of this algorithm using Matlab. 

#### Key takeaways 
- Implementing iterative factorial functions.
- Calculating factorial recursively.
- Keeping track of recursion.
- Workflow of recursion.

#### Article quality
This article looks deeply at the recursion idea and implements it using Matlab functions.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @peterAdongo 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
