### ISSUE TITLE
Discrete Fourier Transform (DFT) of images and Image Filtering in Matlab

### ISSUE THREAD

**Issue by florenceakinyi** [section-engineering-education/engineering-education#6082]
### Topic Suggestion
Discrete Fourier Transform (DFT) of images and Image Filtering

#### Introduction
The DFT is the sampled Fourier Transform and therefore does not contain all frequencies forming an image, but only a set of samples that is large enough to describe the spatial domain image fully. The number of frequencies corresponds to the number of pixels in the spatial domain image, i.e. the image in the spatial and Fourier domain are of the same size. The Fourier Transform is an important image processing tool used to decompose an image into its sine and cosine components. The output of the transformation represents the image in the Fourier or frequency domain, while the input image is the spatial domain equivalent.

In this tutorial, we will look at a brief theoretical background of Discrete-Time Fourier Transform (DTFT) is first introduced and explain how DTFT is evolved in DFT. Also, the advantages of DFT are explained along with its limitations. Finally, MATLAB code is also given to compute the DFT of images and view their spectrum.

#### Key takeaways
- 2D-Discrete Fourier Transform (DFT), its Applications and Limitations. 
- Frequency domain filtering of noisy images.
- MATLAB Code for image filtering using implemented filters.
- MATLAB Code for removing particular frequency using a Notch Filter. 

#### Article quality
This article looks deeply into the DFT of images and image filtering

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @florenceakinyi 

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
