### ISSUE TITLE
Permutations and Combinations using Python

### ISSUE THREAD

**Issue by Shee254** [section-engineering-education/engineering-education#6084]
#### Proposed title of article
Permutations and Combinations using Python

#### Proposed article introduction
Python provides a library named itertools that contains in-built functions to calculate permutations and combinations. In this article, we will be learning how to find permutations and combinations using Python.

#### Key takeaways 
1.Importing the required library.
2.Finding Permutations
A. Permutations of a Python string.
B. Permutations of multiple numbers.
C. Permutations with certain number of elements.
3.Finding Combinations.
A. Combinations for letters in a word.
B. Combinations of set of numbers.
C. Combinations for repeated numbers.
D. Combinations of numbers with itself.

#### Article quality
In this article Permutations and Combinations using Python I will be clear and precise.I will make use of simple language that a beginner will find it simple to read and understand.All codes snippet will be explained in a clear manner for anyone reading to understand

#### References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @Shee254.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
