### ISSUE TITLE
[Machine Learning] Create a comment moderation function using machine learning from Nyckel

### ISSUE THREAD

**Issue by del-ui** [section-engineering-education/engineering-education#6085]
#### Proposed article introduction
Nyckel is Machine Learning API which has proven very efficient in automated model training even for those with little knowledge in machine learning. A comment function identifies and classify messages with reference to the content it holds. This article creates a comment function, trains a model using Nyckel and integrates the Nyckel model with the function to classify messages on likeliness of spam.
#### Key takeaways 
- Understanding Nyckel API
- Create and train the model using Nyckel.
- Create the Comment function
- Invoke the model from the function
- Model testing
#### Article quality
Unlike other articles, this article trains a model using Nyckel API and invokes it from the comment function. It will
be easy to understand for beginners since the model creation and training using Nyckel is very easy.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
good topic @del-ui - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published and you receiving a payout :)
