### ISSUE TITLE
Building an online code editor using React

### ISSUE THREAD

**Issue by Evelloyd** [section-engineering-education/engineering-education#6087]
### Topic Suggestion
React

### Proposal Submission
Building online code editor using react
#### Proposed article introduction
Installing and integrating code editors in your computer to build an application maybe tiresome and time consuming, either you may need to test and run an application quickly on web using your phone or computer and do not have an opportunity to use a code editor offline.
In some cases, if you're a developer building an application that requires a code editor on it. A code editor is useful in writing, editing and running codes while building your application.
 In this tutorial i'll explain step-wise how to build a code editor using react and you can integrate it in your application if required or just build your own for developing your applications.   
#### Key takeaways 
1. Understanding react and how to integrate it in application.
2. Building real-time application that run codes online.
3. Having greater approach on readers future projects.
#### Article quality
Diving deep into section articles, no related article on this and i'll be explaining this approach using example by building a real-time application to demonstrate this using react.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @Evelloyd 

In as much as the article is not on section, it's still saturated on the internet. We have articles and YouTube videos on the same topic hence we cannot move forward with the topic.

Feel free to explore other topics.

**Comment by yitzackRabin** [comment]
Hi @LinusMuema how about if the author had a different and unique way of implementing thus article?
It seems useful
