### ISSUE TITLE
[Machine Learning] Speech to text transcription model using deep speech

### ISSUE THREAD

**Issue by francis966** [section-engineering-education/engineering-education#6088]
#### Proposed title of article
[Machine Learning] Speech to text transcription model using deep speech

#### Proposed article introduction
Speech-to-text transcription is a subset of natural language processing that is used to convert speech into text. Speech may be in form of video files and audio files,  the model analyses the speech and converts it to the corresponding text. Speech to text is used to recognize and translate spoken language into text by making use of computational linguistics and understanding.

It is used in various areas such as customer service, medical speech diagnosis to convert spoken words to text. This helps improve customer feedback and suggestion. This model makes consumers more comfortable relying on voice services and businesses can now integrate speech recognition to promote growth and lower operating costs.

In this tutorial, we will use the deep speech library to perform speech-to-text transcription. DeepSpeech takes digital audio as input and returns a text transcript of that audio.

#### Key takeaways 
1. Speech to text transcription?
2. Speech-to-text transcription modern applications.
3. Installing deep speech AI
4. Audio input data pre-processing.
5. Modeling training and text output.

#### Article quality
This tutorial is unique because we will first go through the basics of speech-text transcription. It will also cover some of the applications of speech-to-text transcription, this enables the reader to understand the real word use of this model. Finally, we will use a custom input audio and implement the conversion automatically. The model will output a text that represents the original input audio. 
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Good topic @francis966 - approved. Please make sure your article does not reference any youtube tutorial and adds value to what is available online.
