### ISSUE TITLE
Building Ethereum Blockchain API using Node.js

### ISSUE THREAD

**Issue by yitzackRabin** [section-engineering-education/engineering-education#6089]
### Topic Suggestion
[Blockcahin]
### Writing sample(s): 
https://www.section.io/engineering-education/building-a-simple-cryptocurrency-blockchain/

#### Proposed title of article
Building Ethureum Blockchain API using Node.js
#### Proposed article introduction
If you had the first part of my article [Building A simple cryptocurrency blockchain](https://www.section.io/engineering-education/building-a-simple-cryptocurrency-blockchain/). 
For this part i'll build a nodejs API by building and deploying an ethereum blockchain for decentralization.
I'll also explain how to integrate this API and blockchain into a single API stepwise.

#### Key takeaways 
1. Learn how to build APIs using react
2. Understand blockchain and Ethereum.
3. Integrating the APIs into your Application.

**Comment by Kayere** [comment]
Hello @yitzackRabin - could you please provide more info regarding you article.

**Comment by yitzackRabin** [comment]
In this project I'll be building a nodejs API for ethureum blockchain by demonstrating in example and integrating it in an application.

**Comment by yitzackRabin** [comment]
@Kayere It's a continuation of my first article

**Comment by Kayere** [comment]
@yitzackRabin - Even for that you need to provide full details of the article in your topic suggestion. Otherwise, it will be subject to closure.

**Comment by yitzackRabin** [comment]
@Kayere Blockchain cuts edges across many products and use case making it very essential and useful in various technologies.
It is a safe way to record activities and keep data fresh while maintaining history compared to traditional databases. This makes it important to use blockchain in our applications. In this tutorial I'll be explaining how to build a nodejs ethereum blockchain technology API and integrating it I your application.

**Comment by Kayere** [comment]
Approved.

**Comment by yitzackRabin** [comment]
@Kayere Thanks

**Comment by ahmadmardeni1** [comment]
I'm going to close this due to inactivity. It can be reopened.
