### ISSUE TITLE
[Security] Quantum Key Distribution: An overview.

### ISSUE THREAD

**Issue by pop-ecx** [section-engineering-education/engineering-education#6090]
### Topic Suggestion
[Security] Quantum Key Distribution: An overview

#### Proposed title of article
[Security] Quantum Key Distribution: An overview.

#### Proposed article introduction
Quantum key Distribution (QKD), one of the most advanced sub-disciplines of Quantum Information Technology, aims in coming up with novel, sophisticated methods of securely exchanging cryptographic keys by use of basic quantum mechanics concepts such as entanglement and measurement. Since the 1970s, with the advent of quantum cryptography, a number of quantum key distribution or key agreement protocols have been proposed by researchers and academics, with the earliest one being proposed in the year 1984.

#### Key takeaways 
- Understand the types of QKD schemes.
- Understand the intricate workings of major QKD protocols
- Understand the advantage of QKD schemes over conventional classical cryptographic schemes.
- Comprehend potential downside and attacks against QKD schemes.

#### Article quality
This article intends to go deeper into this field while at the same time presenting its ideas in a simple, palatable way for beginners.

#### References
(https://arxiv.org/pdf/1209.0365) [Attacks on quantum key distribution protocols that employ non-ITS authentication.]

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Good topic @pop-ecx - approved. Please make sure your article is unique and adds value to what is available online.

**Comment by pop-ecx** [comment]
Thanks @Kayere.  Noted.
