### ISSUE TITLE
[Mchine Learning] Unsupervised Topic Modeling using Scikit-learn and Non-Negative Matrix Factorization (NMF)

### ISSUE THREAD

**Issue by simonndiritu477** [section-engineering-education/engineering-education#6091]
#### Proposed title of article
[Mchine Learning] Unsupervised Topic Modeling using Scikit-learn and Non-Negative Matrix Factorization (NMF)

#### Proposed article introduction
In machine learning, a topic model is a system that automatically discovers topics occurring in a collection of documents or corpus. This process is an unsupervised technique which means that we don’t have to provide a labeled dataset to topic modeling algorithms and topics are identified automatically by the model. It is implemented as a text mining approach to obtain recurring patterns of words in the textual material.

It is similar to clustering on numeric data, which finds natural groups of items even when we're not sure what we're looking for. Topics models are helpful in identifying important and useful entities that are found in the dataset.  Topic modeling helps us to organize, understand and summarize large collections of textual information. 

In this tutorial, we will use Scikit-learn and Non-Negative Matrix Factorization (NMF). Scikit-learn has inbuilt algorithms that are used to train the model and Non-Negative Matrix Factorization (NMF) is used to reduce the dimension of the input corpora.

#### Key takeaways 
1. Benefit of topic modeling.
2. Dataset preparation.
3. Exploring Scikit-learn algorithms.
4. Non-Negative Matrix Factorization (NMF) methods.
5. Building the topic model.
#### Article quality
This tutorial will cover the process of dataset preparation in detail so that the reader can understand the dataset that we will be using. We also discuss the general rules that govern the implementation of  Non-Negative Matrix Factorization (NMF) methods, exploring NMF both theoretically and practically. In the theoretical approach, we will discuss the math behind NMF and eventually implement it practically using Python

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @lalith1403, could you please have a look at this topic suggestion when you have a chance.

**Comment by simonndiritu477** [comment]
Hello @lalith1403, @Kayere, What is the status of this issue?

**Comment by lalith1403** [comment]
Thank you for the topic suggestion, however this topic is covered well in the documentation. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
