### ISSUE TITLE
[Language]Creating a Custom Mouse Cursor with CSS and JavaScript

### ISSUE THREAD

**Issue by kmwangi-ken** [section-engineering-education/engineering-education#6092]
#### Proposed title of article
Creating a Custom Mouse Cursor with CSS and JavaScript

#### Proposed article introduction
In most cases you can create most you can define a cursor using cursor properties. You might have visited some websites and you were amazed by its amazing features one being its cool mouse cursor that is different from the regular arrow or pointer cursors you are used to.  which sometimes leaves one wondering how it's done. Well, worry no more since in this article I will help novices design a custom cursor using CSS and JavaScript.

Designing a custom mouse really improves the user experience in a website.  I will be explaining how to make a custom mouse cursor. By the end of this article, the learner will learn how to make these cursors with two different methods, using CSS and JavaScript. Then you be will ready to vamp up your website with different creative cursors to keep your audience engaged. Ready? Let's dive in.

Custom Cursor is a browser extension that lets you change your cursor to a custom one from a giant cursor collection to choose from or upload your own.
#### Key takeaways 
1. Custom cursor overview
2. Customizing a Mouse Cursor with CSS
3. Creating a custom Mouse Cursors with JavaScript
4. Styling a custom cursors with CSS
5. How to use JavaScript to make the cursor move

#### Article quality
In this article, I will make it more practical since the novices will be getting results of every code he writes. Unlike the existing articles on the same my article will have a complete script that ties everything together. It will also include comments to make the learners understand and follow.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Thank you for submitting your topic @kmwangi-ken.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
