### ISSUE TITLE
Build Micro-frontends with Reactjs and Docker

### ISSUE THREAD

**Issue by khabdrick** [section-engineering-education/engineering-education#6094]
### Writing sample(s): 
https://okteto.com/blog/develop-and-deploy-a-flask-and-reactjs-app-in-okteto/

#### Proposed title of article
Building Micro-frontends with Reactjs and Docker

Use keyword research to improve your article's SEO.

#### Proposed article introduction
It helps to efficiently develop and scale individual pieces of the application frontend. The idea of micro-frontends came to replicate the benefits that microservices bring to the server-side, but this time directly in front, instead of the monolith where the entire project is built in one codebase. The major benefits we want to archive using Micro-Frontends are: More cohesive codebase, Simplify maintenance, Allows to scale development teams, Simplify updates.
I would like to demonstrate that practically with reactjs and Docker.

ONLY viable topics to pick from:

- Containers
- Languages
- Networking

#### Key takeaways 
- Knowledge about micro-frontend
- How to go about building a micro-frontend with React
- How to connect the micro-frontend in other to get information from each other.
- How to make the micro-front run simultaneously with Docker and Docker compose

#### Article quality
This article is one of its kind.

**Comment by Kayere** [comment]
Thank you for submitting your topic @khabdrick.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
