### ISSUE TITLE
[Languages] Creating A Hand Tracking Module Using Python, OpenCv And MediaPipe

### ISSUE THREAD

**Issue by kirurisimon** [section-engineering-education/engineering-education#6095]
### Topic Suggestion
Creating a hand tracking module using python, OpenCv and MediaPipe

### Writing sample(s): 
[Sample](https://www.section.io/engineering-education/license-plate-detection-and-recognition-using-opencv-and-pytesseract/)
#### Proposed title of article
Creating a hand tracking module using python, OpenCV and MediaPipe

#### Proposed article introduction
When creating projects that involve hand tracking we tend to write the same piece of code over and over again. This not only costs us time but also leads to boredom as we are repeating the same task for every project. We can solve this problem by writing the piece of code once and then converting it into a module. This way we can always call the module to the project we are working on to do the hand tracking.

In this tutorial, we are going to learn how to come up with a code that does hand tracking. We will then learn how to convert the code into a module that we can call whenever we require it to track hands in any project we are working on.

#### Key takeaways 
The reader will:

1. Learn how to create a program that performs hand tracking.
2. Learn how to convert the code into a module that he/she can call to track hands in any project.
3. Understand how OpenCV and MediaPipe libraries are used to create the hand tracking program.

#### Article quality
The article will show the reader each step involved from coming up with the source code to creating a module out of it. The codes will also be well explained not copy-pasted ones. 

#### References
N/A

**Comment by Kayere** [comment]
Sounds like a helpful topic @kirurisimon - approved. Please make sure your article is unique and adds value to what is available online.
