### ISSUE TITLE
[ Languages, Java, JSP ] Implementing User Sign Up, Login and Sessions With Java Server Pages (JSP)

### ISSUE THREAD

**Issue by gisioraelvis** [section-engineering-education/engineering-education#6096]
## Proposed title of the article
[ Languages, Java, JSP ] Implementing User Sign Up, Login and Sessions With Java Server Pages (JSP)

## Proposed article introduction
This article will be a guide through the JSP technology to develop user interfaces which will help understand the basic functionality of Java Server Pages (JSP) to develop web applications. After completing this tutorial you will have the expertise in developing web pages with JSP.

## Key takeaways 
- In-depth guide and core concepts around the JSP technology.
- How to use the JSP to develop web applications user interfaces.
- How to handle HTML form data and user input with JSP.
- A practical example of the JSP in action to develop a user registration form.

## Article quality
This article explores the core concept of JSP from the ground up clearly and concisely with examples making it friendly for beginners and people with no prior knowledge of JSP.

## References
[Stream API](https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html)
[The Stream API](https://dev.java/learn/the-stream-api/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites. Some have even gone further to add MySql.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
