### ISSUE TITLE
[Machine Learning] Contextual Anomalies detection using Isolation Forest

### ISSUE THREAD

**Issue by josephgatura328** [section-engineering-education/engineering-education#6097]
#### Proposed title of article
[Machine Learning] Contextual Anomalies detection using Isolation Forest

#### Proposed article introduction
Anomalies are observations or data points that deviate from a dataset’s normal behavior. Anomalous data can indicate critical incidents or even potential opportunities. Anomalies in the dataset have a negative impact on the model's performance. They give wrong prediction results. Anomaly detection is used to identify data points that deviate from a dataset's normal behavior so that we have a uniform dataset.

Context anomalies are data points that are considered abnormal when viewed against meta-information associated with the data points. Algorithms to detect anomalies generally fall into three types: unsupervised, supervised, and semi-supervised. We will use the Isolation Forest algorithm which is an unsupervised algorithm. It involves training the detection algorithm using completely unlabelled data

In this tutorial, we will be discussing contextual anomalies in detail and how to handle them. We will load our dataset and perform analysis to identify anomalies in the dataset. Finally, we will remove the anomalies in our dataset.

#### Key takeaways 
1. Types of dataset anomalies.
2. Importing the Isolation Forest algorithm.
3. Dataset pre-processing.
4. Implementing the detection techniques using an Isolation Forest.
5. Removing anomalies from our dataset.

#### Article quality
This tutorial is unique because we will first discuss the different types of dataset anomalies such as Global anomalies, contextual anomalies, contextual anomalies, and point anomalies. We will then focus on contextual anomalies which are difficult to identify and handle. The tutorial will also explore the various algorithm that can be used for anomalies detection. Overall, the tutorial will explain each method and function used in detail and simply for the reader to understand.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
