### ISSUE TITLE
Methods to synchronize threads in python

### ISSUE THREAD

**Issue by Dick7603** [section-engineering-education/engineering-education#6098]
#### Proposed title of article
[Languages] Methods to synchronize threads in python

#### Proposed article introduction
Multithreading allows your computer to use many cores/ CPUs simultaneously. However, accessing and modifying shared variables at the same time might result in errors. We will go through the methods of synchronizing threads correctly. Threads are the smallest unit of a program or process that may be scheduled by the OS. An Operating System achieves multitasking by splitting a process into threads. A thread is a small process that provides distinct execution on the system.

#### Key takeaways 
By the end of this tutorial, the reader will understand:
- What it entails with synchronization in python
- Issues in thread synchronization
- Lock objects
- Rlock objects
- Semaphores

#### Article quality
This is going to be a very detailed article about this subject. It will explain important things that aren't in the documentation or on other platforms. I want to make it easier for beginners to understand and use. A lot more will be covered on the advantages and disadvantages of multithreading.

### References
N/A

**Comment by LinusMuema** [comment]
Hi @Dick7603 

Thank you for your article suggestion.

I however have a concern about the originality of the article. You claim the topic covers things not covered on other platforms but I have found two articles on GeeksForGeeks that explain exactly what your article covers. 
- [Synchronization](https://www.geeksforgeeks.org/multithreading-in-python-set-2-synchronization/)
- [Semaphores](https://www.geeksforgeeks.org/synchronization-by-using-semaphore-in-python/) 

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content.

You are more than welcome to pursue another more in depth topic
