### ISSUE TITLE
Getting started With UML Diagrams

### ISSUE THREAD

**Issue by mussooo** [section-engineering-education/engineering-education#6099]
#### Proposed title of the article
Getting started With UML Diagrams

#### Proposed article introduction
UML is an acronym for Unified Modelling Language. It is a language for modeling techniques and software systems.

It is a way of using a diagram to visualize a system or database. Almost all developers must have some knowledge of UML. 

This tutorial will be of much benefit to students and developers as it will cover some of the most used important diagrams.

I had a lot of problems with UML diagrams. I had to learn a lot of things to make it work. Therefore,  I want to use this article to make it easy for all who want to study UML diagrams.

#### Key takeaways 
1. Brief Introduction on what is UML.
2. UML Diagrams
3. Different notations for UML Diagrams
4. Important of UML Diagrams in Software Development

#### Article quality
This article is very friendly to beginners. It will add value to students as well as software developers in developing object-oriented software. 

#### References
N/A

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites:
- [DZone](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjFw4mw5MD1AhUyzIUKHTmvDOQQFnoECAUQAQ&url=https%3A%2F%2Fdzone.com%2Frefcardz%2Fgetting-started-uml&usg=AOvVaw3wcwK8O2IEcV8MTA6JMW8Y)
- [TutorialsPoint](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjFw4mw5MD1AhUyzIUKHTmvDOQQFnoECAYQAQ&url=https%3A%2F%2Fwww.tutorialspoint.com%2Fuml%2Findex.htm&usg=AOvVaw1VIUROHgxHawma65_xCQ0o)
- [Dev.to](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjFw4mw5MD1AhUyzIUKHTmvDOQQFnoECAYQAQ&url=https%3A%2F%2Fwww.tutorialspoint.com%2Fuml%2Findex.htm&usg=AOvVaw1VIUROHgxHawma65_xCQ0o)

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
