### ISSUE TITLE
[Machine Learning] Using Mask-RCNN and the PixelLib library to perform Instance Segmentation

### ISSUE THREAD

**Issue by smkinyan** [section-engineering-education/engineering-education#6101]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

Using Mask-RCNN and the PixelLib library to perform Instance Segmentation

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Pixellib is a library for performing segmentation of objects in images and videos. It supports the two major types of image segmentation, namely; Semantic segmentation and Instance segmentation. This tutorial will discuss about Instance Segmentation using a model called Mask-RCNN. With this model, you will be able to segment yourself from other objects within a frame. We will be performing this using the OpenCV library, PixelLib library, and Python.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to understand:
- What is the PixelLib library.
- How to install the PixelLib library using Python
- How to use OpenCV to capture our frames in real-time. 
- How to apply Mask-RCNN to be able to segment our image. 

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [PixelLib](https://github.com/ayoolaolafenwa/PixelLib)

**Comment by LinusMuema** [comment]
Hi @smkinyan 

Thank you for your submission. 

However, you didn't indicate how article your was going to be unique. After a google search of your article topic. I discovered articles and Youtube videos covering the same. We typically refrain from content that is widely covered on the web as we focus more on original content.

Feel free to explore other options and topics.
