### ISSUE TITLE
How Web 3.0 is Going to Impact the Digital World

### ISSUE THREAD

**Issue by njericeline** [section-engineering-education/engineering-education#6103]
### How Web 3.0 is Going to Impact the Digital World
Web 3.0 is the latest Internet technology that leverages artificial intelligence, blockchain and machine learning to attain real-world human communication. Web 3.0 enables people to own their data and compensate for the time spent on the Web. Web 3.0 is the next stage in the evolution of the internet, and it is going to be a huge leap in network technology as per the current standards. Through the development of the ongoing technology, Web 3.0 provides more solutions for browsing and allows the clients to browse the application data from every part of the world.
In this article, we will discuss:
    • What web 3.0 is
    • The evolution of the Web through its numerous stages
    • The benefits of web 3.0
    • The impact of Web 3.0 in the digital world
    • The future of the digital world
### Key takeaways
The user will understand how Web 3.0 connects big data, machine learning, and artificial intelligence to provide a personalized experience by evaluating the user's data and behavior. Also, the user will understand how people can speak with different devices such as Apple Siri, Alexa, etc., to collect information from the Web.
### Article quality 
The article will be beginner-friendly since it will be easy to read and understand, especially for users with no knowledge about Web 3.0. In addition, the article will have a more detailed explanation about the impacts of Web 3.0 in the digital world than other articles published on the Web that covers this topic.

**Comment by Kayere** [comment]
Thank you for submitting your topic @njericeline.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
