### ISSUE TITLE
[Languages]How to Lively Blur Human Face in Python via OpenCV

### ISSUE THREAD

**Issue by GeekEdmund** [section-engineering-education/engineering-education#6104]
#### Proposed title of article

How to Lively Blur Human Face in Python

#### Proposed article introduction

One's privacy is at times really essential. That is why blurring of faces comes in handy on any kind of media that will be very necessary. To avoid disclosure of one's identity either in a viral or vital situation in which showing the media is essential.
To have this implemented we have to use modules such as the OpenCV. Which provides various methods of blurring that is the Gaucian blur or the pixelated blur. We’ll then review the results of our face blurring and anonymization methods.
In this tutorial, we will be covering face blurring in interesting ways.

#### Key takeaways 

1. We first have to detect the face.
2. Drawing out the region of concern.
3. Performing the actual blurring.
4. Retrieval of the original face from the blurred image. 

#### Article quality
The article's main purpose is to create awareness of such programs that deal with one's privacy increasing self-esteem amongst individuals. Also written in simple and fun ways making it easy to follow.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @GeekEdmund 

Thank you for your suggestion and I have to say, it was well written. 

However, on a google search of the topic, I came across several YouTube videos and articles covering the same topic. We therefore cannot move forward with the article as we focus more on original content that isn't widely covered on the web. I would suggest you first check the topic area before submitting an article.

You seem to have great writing skills from your suggestion so if you can get a good original topic, it would be amazing and good for your portfolio too.

> The `Article Quality` section actually asks how original your content is not really what it entails. This will show you know the value of your article and has more chances of getting approved.
