### ISSUE TITLE
Sorting Algorithms in C

### ISSUE THREAD

**Issue by mwangiki** [section-engineering-education/engineering-education#6105]
#### Proposed title of article
Sorting Algorithms  in C

#### Proposed article introduction

i will use  Sorting Algorithm  to rearrange a given array or list elements according to a comparison operator on the elements. i will use comparison operator to decide the new order of element in the respective data structure

#### Key takeaways 

- Bubble sort
- Insertion sort
- Selection sort
- Quick sort
- Shell sort - Knuth Sequence
- Cocktail shaker sort
- Counting sort
- Merge sort
- Heap sort
- Radix sort
- Quick Sort - Hoare Partition scheme
- Dealer
#### Article quality
- I will use simple language for easy understanding
- It will contain detailed information.
- it will be simple to understand
- it will be direct to the point for easy understanding
#### References
N/A

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
