### ISSUE TITLE
Demystifying Github Actions

### ISSUE THREAD

**Issue by Babatunde13** [section-engineering-education/engineering-education#6108]
### Writing samples: 
[Building a React App with TypeScript](https://www.section.io/engineering-education/building-a-react-app-with-typescript/)
[How To Build GraphQL APIs with ExpressJS and Typescript](https://www.section.io/engineering-education/how-to-build-graphql-apis-with-expressjs-and-typescript/)
[Building A Password Manager With React JS, Crypto JS, and Fauna](https://dev.to/bkoiki950/building-a-password-manager-with-react-js-crypto-js-and-fauna-29g9)

### Topic Suggestion
Demystifying Github Actions

#### Proposed article introduction
Github actions was created by Github Inc, and is a cloud platform which developers can use within Github. It's a very powerful platform but unfortunately some(or even most) developers most especially the non senior ones aren't maximising it. It's free, can be used within Github among other things. This article will talk about different things that Github Actions can be used for, some of the base actions that we have, where to search for base actions and when to use them. Imagine a situation where developers test code base locally and make PRs that someone else needs to review, but you do not have a test workflow set on Github, the reviewer will need to have to pull locally to run the test and ensure that the change is not breaking the existing features, but if you have a test action setup that won't be needed and review will be pretty much faster.

#### Key takeaways 
1. What are Github Actions
2. Github Actions Events
3. Github Actions Marketplace

#### Article quality
Most articles on Github just talk about what Git and Github is and how we can use them to store and share our code with other developers, but most of us already know this, we're in the CI/CD era where we want to automate our CI/CD workflows from testing to deploying, Github Actions allow us to easily achieve this and since we're using the same platform as where we store our code online it even makes it more fun and easier unlike other CI/CD platforms like Travis CI.

#### References
[Github Marketplace](https://github.com/marketplace?type=)
[Github Actions](https://github.com/features/actions)

### Conclusion
This article will serve as an in depth guide to creating actions on Github, when to use them.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic suggestion due to inactivity. It can be reopened.
