### ISSUE TITLE
Downloading and Installing an Ubuntu Server on the Oracle Virtual  Machine

### ISSUE THREAD

**Issue by hezemwash** [section-engineering-education/engineering-education#6110]
#### Proposed title of article
Downloading and Installing an Ubuntu Server on the Oracle Virtual  Machine.

#### Proposed article introduction
This involve process of downloading ubuntu server and virtual box, installing ubuntu server to virtual box. configuring ubuntu archive mirror  and storage to ensure all parts are partitioned correctly. Then installing openssh server on server finally running the commands.

#### Key takeaways 
-downloading and installing server and virtual machine
-downloading, installing an openssh on host machine
-installing ssh client on pc
-installing samba on device
-checking status of samba
-configuring samba
-Hosting HTTP content Through Apache server
-adding modules
-setting up virtual
-Activate virtual host configuration file

#### Article quality
-I will use simple language for easy understanding
-It will contain detailed information.
-it will be simple to understand
-it will be direct to the point for easy understanding

#### References
N/A

**Comment by LinusMuema** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and Youtube videos.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
