### ISSUE TITLE
Magic Methods in Python

### ISSUE THREAD

**Issue by fely545** [section-engineering-education/engineering-education#6114]
### Proposed title of article
Magic Methods in Python
### Proposed article introduction

Magic methods are special methods in python that have double underscores (dunder) on both sides of the method name. Magic methods are predominantly used for operator overloading. Operator overloading means provided additional functionality to the operators, the python implicitly invokes the magic methods to provide additional functionality to it. 
In article I will explain what magic methods are and how they can be used to build Python applications. I will provide an overview of the most widely used magic methods for a range of data types.

### Key takeaways
 - What Are The Python Magic Methods?
 - Widely used magic methods in:
    -  a custom class
    - integers
    - strings
    - lists and dictionary data types.

### Article quality
In this article, we learn how to leverage the use of magic methods in python to provide additional functionalities to the class objects without any overhead which is not included in other blogs. Finally, I will include broader examples illustrating how magic methods can be used in broadcast operations.

**Comment by Kayere** [comment]
Thank you for submitting your topic @fely545.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
