### ISSUE TITLE
Decentralized autonomous organizations (DAOS)

### ISSUE THREAD

**Issue by fxparoo** [section-engineering-education/engineering-education#6115]
Proposed title of article
Decentralized autonomous organizations (DAOS)(Overview of the Decentralized autonomous organizations)

Article Introduction
The objective of this article is to make the readers understand the meaning of DAOS, comparison between DAO and traditional organization,DAO membership and what they are all about,explaining how DAOS work,relationship between DAOS and ethereum and technology stack of the DAOS.

Key takeaways 

1.The reader will be able to understand the underlying stories behind the “DAO HACKS”
2. The reader will  be able to learn why  Etherium Classic and Etherium were birthed.
3.The reader will be able to understand the different between traditional organization and DAOS.

Article quality

My articles will covered a  detailed explanations  about the “DAO HACKS” which makes it unique and different from similar articles published on the same topic

References

https:/ethereum.org/en/dao/
https://www.gemini.com/cryptopedia/the-dao-hack-makerdao
https://coinmarketcap.com/alexandria/article/a-history-of-the-dao-hack

**Comment by Kayere** [comment]
Thank you for submitting your topic @fxparoo.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
