### ISSUE TITLE
Social Authentication with Djoser in React Applications.

### ISSUE THREAD

**Issue by JohnKiguru** [section-engineering-education/engineering-education#6116]
### Topic Suggestion
Social Authentication with Djoser in React Applications.

#### Proposed title of article
Social Authentication with Djoser in React Applications.

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Djoser is a useful tool that you can use to provide authentication for your applications.It allows one to set up authentication using social accounts such as google, facebook, etc.This article aims at handling social authentication using djoser in a react application.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
1. Understand how authentication using djoser works.
2. Implement social authentication using djoser.

#### Article quality
I will be creating a simple react application that allows one to authenticate using a google account using djoser and django for backend. There will be an option for handling authentication using normal username and password.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hello @JohnKiguru

Thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

> I have noticed you haven't removed the pre-submission advice. You can clean up the suggestion by removing those details that aren't part of your suggestion before the CMs get to it. This will help them clearly see your content and review it with ease.

**Comment by JohnKiguru** [comment]
Done...

**Comment by Kayere** [comment]
Good topic @JohnKiguru - approved. Please make sure your article is unique and adds value to what is available online.
