### ISSUE TITLE
Building A School Management System Endpoint Using Flask and Postgresql

### ISSUE THREAD

**Issue by wobin1** [section-engineering-education/engineering-education#6119]
### Writing sample(s): 
https://www.section.io/engineering-education/flutter-authentication-using-flask-api/

#### Proposed title of article
[API]Building A School Management Software Api Endpoints Using Flask and Postgresql

#### Proposed article introduction
Management softwares are very popular because of how they help in automating management systems. They remove the inefficiency of man in all management processes. A management system can be seen as a procedure or process used by any organization to improve its capability of achieving set goals. There are different types of management softwares that help in automating management systems they may include; Hospital management software, Employee management softwares, School management softwares e.t.c. 

In this guide, we will be building a school management software API endpoints using Flask and Postgresql Database. Flask is a python framework for building web applications.  The API endpoints would be able to connect to any client site application be it Mobile, Web, or Desktop. A school management software is a software that helps in managing administrative processes in schools.

#### Key takeaways 
- By the end of this guide the reader will learn how to;
- Build Api endpoints using flask
- write complex database queries like joins 
- Deploy API applications to Heroku

#### Article quality
This article will cover in-depth aspects of programming in a way even beginners will understand. It will cover SQL and Deployment to Heroku.

#### References
[Please list links to any published content/research that you intend to use to support/guide this article.](https://flask-restless.readthedocs.io/en/stable/basicusage.html)

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @wobin1 

Thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Thank you for submitting your topic @wobin1.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
