### ISSUE TITLE
under water sensor network 

### ISSUE THREAD

**Issue by faithwan-gari** [section-engineering-education/engineering-education#6120]
#### Proposed title of article
under water sensor network 

#### Proposed article introduction
under water sensor network is a network that has number of sensors and vehicles to sense and collect data from water. The main phenomena related to acoustic propagation, and discuss how they affect the design and operation of communication systems and networking protocol at various layers. 

#### Key takeaways 
-Under water sensing applications
-Requirement of under water sensor network
-application domain
-Under water communication and network technology
-The network layer, routing and transport.
-Hardware  platforms
-conclusions

#### Article quality
-I will use simple language for easy understanding
-It will contain detailed information.
-it will be simple to understand
-it will be direct to the point for easy understanding
#### References
N/A

**Comment by LinusMuema** [comment]
Hi @faithwan-gari 

Thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Good topic @faithwan-gari - approved. Please make sure your article is unique and adds value to what is available online.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic suggestion due to inactivity. It can be reopened.
