### ISSUE TITLE
[Machine Learning] Optimal Resource Allocation in Wireless Networks Using Machine Learning

### ISSUE THREAD

**Issue by andrew-steve** [section-engineering-education/engineering-education#6122]
#### Proposed title of article
Optimal Resource Allocation in Wireless Networks Using Machine Learning (ML)

#### Proposed article introduction
Resource allocation in wireless networks plays a vital role in the overall performance of a network such as the interconnection speed. In the past, iterative approaches where sufficient enough to allocate resources and achieve convergence at an optimal rate. However, iterative approaches are currently not sufficient due to the large and growing number of users in wireless networks. This is an NP-hard, non-convex optimization problem requiring the use of some sort of intelligence. This article will provide an in-depth overview of how machine learning algorithms can be employed to intelligently allocate resources in wireless networks

#### Key takeaways
- Overview of iterative approaches of resource allocation
- Implementation of the ML based resource allocation
- Performance evaluation of the ML technique
 
#### Article quality
Understanding how wireless networks and how resources are allocated is not sufficient enough in networking. One ought to look for ways of improving network performance to achieve optimal solutions. Applying machine learning techniques ensures this is achieved faster.

**Comment by LinusMuema** [comment]
Hi @andrew-steve 

Thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Great topic. There seems to already be a lot of [research](https://www.google.com/search?client=firefox-b-d&q=Optimal+Resource+Allocation+in+Wireless+Networks+Using+Machine+Learning) in this area/ Do you plan to reference any of it?

**Comment by andrew-steve** [comment]
> Great topic. There seems to already be a lot of [research](https://www.google.com/search?client=firefox-b-d&q=Optimal+Resource+Allocation+in+Wireless+Networks+Using+Machine+Learning) in this area/ Do you plan to reference any of it?

**Comment by andrew-steve** [comment]
Yes, references will be provided where necessary

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic suggestion due to inactivity. It can be reopened.
