### ISSUE TITLE
Working with merge sorting in python

### ISSUE THREAD

**Issue by saraheric** [section-engineering-education/engineering-education#6123]
### Topic Suggestion
[Languages] Working with merge sorting in python

#### Proposed article introduction
The merge function in python can be used to sort a wide variety of data. It uses a divide-and-conquer technique to sort data using a comparison technique. You want to reduce the list to as few elements as possible before moving on to the next level of subdivision. The sorted sub-lists are created by merging all of the sub-lists in reverse order. The result is a single list, which is referred to as merge sorting. There is zero temporal complexity for the merge sort sorting function (`nlogn`).

#### Key takeaways
By the end of this article, the reader will be able to understand:
- What is sorting with merge function and the rationale behind this concept in python
- What is divide and conquer in approach to problem-solving
- Implementation of sorting with merge function
- Advantages and disadvantages of merge sorting in python

#### Article quality
My aim is to make this article as interesting as possible and lean more towards enhancing understanding and beginner-friendly. This article will be in-depth covering all the aspects of this concept. This article will make use of simple and easy language throughout with aim of enhancing understanding. The overall goal is to make it beginner-friendly moreso with language use and practicable examples and screenshots where applicable. I will offer a description of my codes. The reader will appreciate being subjected to the various ways in which merge sorting in python can be implemented as well as detailed explanation of the merge sort algorithm's operations and intuitions..

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @saraheric 

Thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
