### ISSUE TITLE
[Android] How To Change An Activity To A Fragment In Android In Order To Create A Drawer.

### ISSUE THREAD

**Issue by Ainea-Amush** [section-engineering-education/engineering-education#6125]
#### Proposed title of article 
[Android] How To Change An Activity To A Fragment In Android In Order To Create A Drawer

#### Proposed article introduction
Having worked with C,C++ or java programming languages, you realize that almost every program starts with main() function. Similarly in android, the system starts its program in an activity way by invoking specific call back methods such as Oncreate() call back method.

A fragment is just a modular portion of the user interface within an activity and its ability to be added or removed while the containing activity is running makes it useful in creating a drawer ( a panel that displays navigation options from the left edge of an activity)

In this article, we will develop various android activities, change them to a fragment and also create fragments from the AndroidX Fragment Library and include them in an activity to develop a pathway to create a drawer.

#### Key takeaways 
- An understanding of how to create a fragment from the AndroidX Fragment library and include it in an activity
- An understanding of how to create an activity in Android and change it to a fragment
- Creating a navigation drawer from the fragments in an activity in Android

#### Article quality
This article will provide in-depth understanding to the readers on Activities and Fragments in Android and how to manipulate them to create a drawer

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=How+To+Change+An+Activity+To+A+Fragment+In+Android+In+Order+To+Create+A+Drawer) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by Ainea-Amush** [comment]
@louisefindlay23  Hello. Looking at a majority of nearly similar content found online, they are not beginner-friendly as a lot of debugging is required when transferring the content of an activity into a fragment. Of course, this article will address this issues as gracefully as possible. It will be so engaging to the readers and adding value to the community.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
