### ISSUE TITLE
Image Compression with Singular Value Decomposition using python

### ISSUE THREAD

**Issue by Madrinmarison** [section-engineering-education/engineering-education#6128]
#### Proposed article introduction
Image compression is a way to minimize the byte's size in a graphical file without losing the quality of the file to an unacceptable extent. It's an important activity as it makes it economical to store many images in memory space. Also, sending a compressed image over the internet requires less time than the original one.

In this article, we will learn how to compress an image using Singular Value decomposition, a machine learning algorithm that decomposes a matrix into three other matrices of singular components. Thus, using this technique, we will convert our image matrix into its singular vectors and singular values and truncate out the less prominent components that explain less information in image data.

#### Key takeaways 
- What's image compression.
- Other techniques used in image compression
- Importances of image compression in deatail
- How to step by step compress an image without losing much of its information in Google Colab(Python).
- How to reconstruct the compressed image from the reduced data matrices
- Compare the size of the new compressed image and the initial image

#### Article quality
This article is experience-based. The content in this article will be explained very clearly, and we will spend most of our time on the implementation session, where we will explain every single move of our implementation. The content in this article is mainly for non-beginners who are already familiar with the concept of the Singular Value Decomposition. That doesn't mean we will exclude those unfamiliar with such concept. We will provide highly simplified content so that they  can grasp at ease too. So, this article is meant to include both beginners and non-beginners provided are interested in this domain. So, this article will deliver clarity and deep handling of the topic.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @Madrinmarison 

Thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic

**Comment by Madrinmarison** [comment]
@louisefindlay23 okay, I'll consider suggesting another topic. Thank You
