### ISSUE TITLE
[Android] Comparing Okio's Okhttp3 and Retrofit in Performing Network Calls

### ISSUE THREAD

**Issue by nia-vee** [section-engineering-education/engineering-education#6129]
#### Proposed article introduction
Okio is a library that works in conjunction with java.io and java.nio to make data access, storage, and processing considerably easier. It started off as a component of OkHttp, Android's competent HTTP client. 
Retrofit is a REST client for Java and Android application development that is type-safe. Retrofit is a library including interfaces, classes, and methods that provide the functionality required. The retrofit library can parse JSON or XML data and convert it to POJOs (Plain Old Java Objects).
Okio is a well-trained and eager to take on new challenges  and it is also fast and easy android networking library.

#### Key takeaways 
- Understanding the difference between Okio and retrofit network library
- Advantages and Disadvantages of Okio in performing network calls
- Implementing Okio as used in android to performing network calls
- Understanding factors to consider when choosing a network library.

#### Article quality
Over the internet, most articles only major on the basic types of network libraries without going in depth. This article tends to explain the stated network library in depth and in a beginner friendly manner.It also state factors to consider on which network library to use and under which circumstances.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @nia-vee 

Thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Sounds like a helpful topic @nia-vee - Approved. Please make sure your article is unique and adds value to what is available in the official documentations.
