### ISSUE TITLE
[API] Understanding Trends In Technical Documentation

### ISSUE THREAD

**Issue by kwennB** [section-engineering-education/engineering-education#6130]
#### Proposed title of article
Understanding Trends In Technical Documentation or
How to document better API like a pro and trends within Developers documentation

#### Proposed article introduction
There are many resources on general documentation. How to integrate APIs, Understanding APIs, and their benefits e.t.c. There are a few about the backend work that goes on between developers and engineers. That is the work and process it takes to put together the APIs for public use. There are trends in the documentation that most companies use and have adapted to. Although the trends of use could differ from company to company. 

A lot of work goes into API documentation. Some companies haven’t adapted and it makes documenting API tedious and daunting. 
This is why there are good APIs with poor documentation and it results in a waste of time, effort, and resources. 

API documentation does not have to be a tedious job; you don’t have to be a senior engineer to document API. With this article, I’ll be sharing useful trends and processes. Also, workflows for documenting APIs. 

#### Key takeaways 

- How writers interact with engineers on documentation

- Introduction to SCRUM and resources to get started

- How writers handle Open API spec and other resources

- Lists of useful/productive tools for documentation

- Formats for output and responses

- Best practice processes and workflow

#### Article quality
· It serves as guide options for technical writers and developers. There are handy tips for documentation. It'll make the job easier for themselves and others.

**Comment by LinusMuema** [comment]
Hi @kwennB 

Thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by kwennB** [comment]
@louisefindlay23 

Thank you for approving my topic. I'm working toward making the article comprehensive.

I will send in the first draft as soon as possible. 

I'm commenting so my issues doesn't get closed. Thank you.
