### ISSUE TITLE
[Networking] Handling threats using Cisco's ASA feature

### ISSUE THREAD

**Issue by Dawe-7** [section-engineering-education/engineering-education#6132]
#### Proposed title of article
Handling threats using Cisco's ASA feature

#### Proposed article introduction
Information is the main focus of a security engineer and it is one of the main things that is inadequate. Internal logging buffers such as Syslog and SNMP are used on several appliances whose main aim is to ensure confidentiality of information. When there is a lot of raw information, the data is simply dismissed, or challenges become lost within the data; if there is not enough information, the logging itself becomes secondary making its usefulness very scarce.

This is where Cisco’s ASA (Adaptive Security Appliances) comes in and provides threat detection aptitude. The ASA monitors the traffic passing through the appliance and flags (using log entries) a variety of different types of attacks as they occur. It then goes ahead and stores the information in the ASA as a breakdown list of attack statistical data.

In this tutorial, we will discuss how to handle threats using Cisco’s Adaptive Security Appliance feature  and how we can configure it to work within our networks.

#### Key takeaways 
By the end of this turorial, the reader will be able to:
1. Understand what the ASA feature is
2. Know the default threat detection settings
3. How to configure the ASA feature
4. Understand the scanning threat detection feature

#### Article quality
This article will help the reader understand what Cisco's ASA feature. It will include a breakdown of the threats faced by networks and how we can configure both the adaptive security appliance and scnanning threat detection feature in our Cisco devices. The reader will be able to know the two and determine which is better suited for their security appliances.

#### References
N/A

**Comment by Kayere** [comment]
Good topic @Dawe-7 - Approved. Please make sure your article is unique and adds value to what is available in the official documentation.

**Comment by ahmadmardeni1** [comment]
I'm going to close this topic suggestion due to inactivity. It can be reopened.
