### ISSUE TITLE
Build a Lyrics Search Web App with Vanila Javascript & API

### ISSUE THREAD

**Issue by abimbolataofeek** [section-engineering-education/engineering-education#6133]
### Build a Lyrics Search Web App with Vanilla Javascript & API.

Building a web lyrics search app with pure vanilla javascript from scratch is really a great project to improve your javascript and CSS skills as a beginner. In my opinion, I advise building similar projects like this first with pure vanilla JavaScript before some learning javascript frameworks cause this will really help to solidify your javaScript skill. 

In this article, you will be taken through the various HTML and CSS elements along with vanilla JavaScript and also fetching data from API. 

At the end of the project, we will be able to search for any song, lyrics, or singer and we will get the results displayed. We are going to be making use of lyrics.ovh API.

#### Key takeaways 
At the end of this tutorial the reader should be able to:

1. Improve JavaScript Skill
2. Improve CSS Skill 
3. Fetch data from API
4. Learn JavaScript ES6

#### Article quality
In this article, We will be building a lyrics search web app from scratch using Javascript ES6 and this will really improve your CSS and javascript skills.

#### References
https://lyricsovh.docs.apiary.io/#

**Comment by WanjaMIKE** [comment]
This topic suggestion is similar to https://github.com/section-engineering-education/engineering-education/pull/6190
