### ISSUE TITLE
Asterisk in ubuntu to configure Voip in the same network

### ISSUE THREAD

**Issue by mbinya18** [section-engineering-education/engineering-education#6134]
Topic Suggestion
The use of Asterisk Server to configure Voip

 Proposed article introduction
Asterisk is a server, ubuntu based server that can be used to deploy and configure Voip phones. Voip phones are types of phones, the ip addressed phones that are configured to a certain server for communication amongst each other. The article is aimed to help understand the procedure to setting up asterisk in ubuntu and configurations for phones in the same network for communication purposes.

The phones in the same network must be managed from a central point of management and are assigned ip addresses for easy routing of their traffic. The phones then need to have applications installed in them for the ease of registration and authentication purposes.  Asterisk server then is able to manage all the operations showing their action logs on the other side of its manage.

 Key takeaways 
1.What asterisk is
2.How to set up asterisk in ubuntu
3.The functioning of Asterisk
4.What are Voip
5.The functioning of Voip
6.The configuration of Voip in asterisk

 Article quality
This article will help users to use open source server to manage Voip phone calls other than the proprietary server systems. 
References
N/A

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=The+use+of+Asterisk+Server+to+configure+Voip) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by mbinya18** [comment]
I will show how  to connect smartphones, such that, as long as they are connected to the same  wireless network, without the physical connection of the ethernet cables, they are able to call to each other. I am also going to show how we can route the smartphones traffic to act as though they are coming from a single server. Such that, if the dialed number is  not found in their local call manager, then they can fetch data from the core call manager server and try to locate the number in the larger call manger. I will show how we can link Asterisk traffic to the core call manger of choice.
