### ISSUE TITLE
Implementing AES Encryption And Decryption In Java

### ISSUE THREAD

**Issue by Geo-free** [section-engineering-education/engineering-education#6136]
### Writing sample(s): 
https://www.section.io/engineering-education/authors/geoffrey-omukuba/

#### Proposed title of the article
Implementing AES encryption and Decryption In Java

#### Proposed article introduction
Data encryption is an important feature of data protection. There are different methods of data encryption and decryption methods used to encrypt and decrypt data to enhance the safety of data transmitted.

In this article, we will look at AES as a method of data encryption and decryption. AES, `Advanced Encryption Standard` is a block cipher encryption and decryption algorithm that process a block of 128 bits of data using secret keys of 128, 192, or 256 bits.

In this article, we will be discussing how this algorithm can be implemented in Java and how it is processed

#### Key takeaways 
- the concept of the AES algorithm
- how to implement this algorithm in java
- How java processes this algorithm

#### Article quality
This article intends to take the reader through the concept of the AES Algorithm, how to implement it in java, and also how java language processes this encryption algorithm.
#### References
N/A

**Comment by Kayere** [comment]
Good topic @Geo-free - approved. Please make sure your article is unique and adds value to what is available online.
