### ISSUE TITLE
Is Garuda Linux good for beginners ?

### ISSUE THREAD

**Issue by 08-dev-verma** [section-engineering-education/engineering-education#6139]
### Topic Suggestion
Is Garuda Linux good for beginners?

#### Proposed title of the article
Is Garuda Linux good for beginners?

#### Proposed article introduction
Garuda Linux is a Linux distribution that is only primarily based totally on Arch. For customers now no longer acquainted with Arch, allow me to say that it's miles pretty a mission to put Arch in your system. 
Several factors have combined to make this Linux distribution one of the most rapidly expanding Linux distributions ever.
Garuda Linux is a good distro for beginners because it uses the latest version of GNOME, which is a lot easier to use than many other desktop environments. 

#### Key takeaways 

1. This article is easy to read and understand. 
2. We explain the key features of Garuda Linux in a simple manner, so beginners can easily understand it.
3. We describe the installation of Garuda in a simple, brief, and easy approach so that it will be friendly for the readers when they try to go through official release notes and information on it.

#### Article quality
Our article addresses information about Garuda Linux with its advantages, use cases and most importantly covers how users can use it in the most efficient way alongside its documentation.

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
