### ISSUE TITLE
Using hash tables and hash maps in python

### ISSUE THREAD

**Issue by BoldTony1** [section-engineering-education/engineering-education#6140]
#### Proposed title of article
[Languages] Using hash tables and hash maps in python

#### Proposed article introduction
An example of a dataset that uses a key-value pair to store data is a hash table. A hash function generates a unique key for each value. In spite of the large number of values in the hash table, the unique key helps retrieving the data in the hash table faster. The dictionary is used to implement the hash table in python, which stores data in key-value pairs. A hashing method is used by Python to produce the keys of a dictionary. If you like, you may rearrange the dictionary's keys in any way you see fit.

#### Key takeaways 
By the end of this tutorial, the learner will be able to understand:
- What is hash table or hash map concept in python
- Hash tables vs hash map
- How to design and compile dictionaries
- What converged dictionaries entails
- Hash tables utilization using dictionaries

#### Article quality
There will be an in-depth coverage of this concept as the reader has to understand that Hash Tables are important implementations in storing and accessing data. The goal is to make it as easy and interesting in a manner in which it will favour beginners making it beginner-friendly and also enhance understanding. I will provide screenshots and examples where relevant. The reader will appreciate being subjected to how to make a dataframe out of a dictionary.

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
