### ISSUE TITLE
Getting started with IPv6

### ISSUE THREAD

**Issue by NgureWaweru** [section-engineering-education/engineering-education#6141]
**Proposed title of article**

[Networking]Getting started with IPv6

**Proposed article introduction**

IPv6 is a 128-bit long Internet Protocol (IP) intended to replace IPv4. The massive expansion of the internet and the development of new technologies such as 5G and the Internet of Things (IoT) have led to IPv4 running out of addresses. leading to replacing IPv4 with IPv6.

**Key takeaways**

- What is IPv6
- Why IPv6
- IPv6 address formats 
- IPv6 Address Abbreviation
- IPv6 Classification

**Article quality**
This article would deal with explaining and helping the reader in a simple way understand the new internet protocol, IPv6. Intended to enlighten the readers' knowledge about IPv6 and networking.

**References**

N/A

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=Getting+started+with+IPv6) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by NgureWaweru** [comment]
Hello louisefindlay23,
Good question. In fact, this was one of my reasons for the topic suggestion, since I discovered that many of the articles are not very beginner-friendly, giving them a hard time understanding.
In the article, I intend to explore IPv6 in a way that the beginner will understand and which will enlighten their knowledge of the new future internet protocol of IPv6. I will also provide the learner with screenshots for a clear, unambiguous picture of IPv6.
Thank you.

**Comment by WanjaMIKE** [comment]
This article -> https://github.com/section-engineering-education/engineering-education/pull/2186/files and https://www.section.io/engineering-education/why-ipv6-transition-is-important/ already covers majority of your key takeaways. Feel free to suggest another topic. Thanks
