### ISSUE TITLE
Getting started with Android Studio

### ISSUE THREAD

**Issue by 07munene** [section-engineering-education/engineering-education#6146]
#### Proposed title of article
Getting started with Android Studio

#### Proposed article introduction
Android Studio is the official  integrated development environment (IDE) for Google's Android operating system, built on JetBrains' IntelliJ IDEA software and designed specifically for Android development. It provides a unified environment where you can build apps for Android phones, tablets, Android Wear, Android TV, and Android Auto.Structured code modules allow you to divide your project into units of functionality that you can independently build, test, and debug.

In this article, we will get to know how the android studio works, learn some basics of android development and also get to know how to create basic applications using Android studio

#### Key takeaways 
1. Downloading android studio
2. Installing android studio
3. Installing java development kits
4. How to create projects in android studio

#### Article quality
The article is indepth in content and provides a step by step process on how to go about android studio and some of the expected setbacks one may experience. #### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
