### ISSUE TITLE
Exploring How Hashing Secures Data With An Example Using The Builtin Node.js Crypto Module

### ISSUE THREAD

**Issue by maugo21** [section-engineering-education/engineering-education#6149]
## Proposed title of the article
[Node.js, Security]Exploring How Hashing Secures Data With An Example Using The Builtin Node.js Crypto Module

## Proposed article introduction
Hashing is extremely useful and widely used in applications to secure information.

Hashing involves taking an input value of arbitrary length and converting it into another compressed output value(hash value). The most popular applications of hashing include:
- Password Storage and verification
- Data Integrity Check/Message Digest

In this article, we will implement hashing using the built-in Node.js crypto module and an example of password hashing before storage and verification during authentication or authorisation. As a bonus, we will make use of salting to make the hash more unique and harder to guess.

## Key takeaways 
- In-depth guide and core concepts of hashing as Cryptography primitive.
- How to implement password hashing and verification using the built-in Node.js crypto module.
- Making use of salting to get unique and harder to guess password hash.

## Article quality
In this article, we explore the core concept of hashing as cryptography primitive from the ground up(including diagrams) making it friendly for beginners and people with no prior knowledge of cryptography concepts.

We then make use of the built-in Node.js crypto module(no external packages) to implement step by step hashing and real-life examples of how it is applied in applications to hash passwords. As a bonus, we add salt to make the password hash more unique and harder to guess.

## References
[Cryptographic hash function](https://en.wikipedia.org/wiki/Cryptographic_hash_function)
[Node.js Official Docs](https://nodejs.org/api/crypto.html#class-hash)
[How to use the crypto module](https://nodejs.org/en/knowledge/cryptography/how-to-use-crypto-module/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=Exploring+How+Hashing+Secures+Data+With+An+Example+Using+The+Builtin+Node.js+Crypto+Module) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by gisioraelvis** [comment]
The majority of existing articles are not beginner-friendly and don't cover the building concepts. In this article, I will explain all the cryptography concepts in a way that is easy to understand, first as language agonistic and then as a practical guide with the crypto module in Node.js and then implementing a password hashing example.

**Comment by maugo21** [comment]
The majority of existing articles are not beginner-friendly and don't cover the building concepts. In this article I will explain all the cryptography concepts in a way that is easy to understand, first as language agonistic and then as a practical guide with the crypto module in Node.js and then implementing a password hashing example.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
