### ISSUE TITLE
Reading and processing android sensor data using python with CSV read

### ISSUE THREAD

**Issue by josephodhis** [section-engineering-education/engineering-education#6159]
### Topic Suggestion
Reading and processing android sensor data using python with CSV read

#### Introduction
Reading is an action performed by computers to acquire data from a source and place it into their volatile memory for processing. Computers may read information from various sources, such as the Internet or audio and video input ports. Data processing is a process of converting raw data into meaningful information. It involves the digestion of the raw data into a more reasonable form.

This tutorial explains how one records data of various smartphone sensors and processes that data offline using Python. First, you extract the sensor's data, the CSV file is read by Python and the extracted data is processed for display. Also, it is processed for taking wavelet transform.

#### Key takeaways 
- Various mobile sensors.
- Why record and how to record mobile sensor data.
- Third party android app to collect sensor data.
- Python code using csv.reader to read Accelerometer data

#### Article quality
This article shows how you can collect data using your android phone and process this data in python. It also shows how you can link a third party android app to python and share this data. 

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic

**Comment by josephodhis** [comment]
@louisefindlay23 This article shows how to use a third party android app to collect data. Basically, it uses galvanometer sensor. Also, it shows how to export your data in a .csv file format. This data is then read and processed using python libraries.

**Comment by josephodhis** [comment]
@louisefindlay23 any update about this issue please.
