### ISSUE TITLE
How to design virtual scene and sensor simulation using driving scenario App

### ISSUE THREAD

**Issue by peterAdongo** [section-engineering-education/engineering-education#6160]
### Topic Suggestion
How to design virtual scene and sensor simulation using driving scenario App

#### Introduction
Driving scenario App is a toolbox in Matlab that enables you to create driving scenarios. These driving scenarios are used to test the automated driving systems. This toolbox can make all the possible scenarios on the road. It makes it easy to automate and make the systems more efficient. This toolbox can create road and actor models using a drag-and-drop interface. Also, it can configure vision, radar, lidar, and INS sensors mounted on the ego vehicle. These sensors can generate actor and lane boundary detections, point cloud data, and inertial measurements.

In this article, we are going to look more into this tool. First, we will see how we can create a scenario using this app. After this, we will add a sensor to our scenario to make it more efficient and reliable.

#### Key takeaways 
- What is the driving scenario App.
- How to use the driving scenario App.
- Creating virtual scenes.
- Adding sensors to your scene.

#### Article quality
This article creates a virtual scene using the driving scenario App.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
