### ISSUE TITLE
How to denoise images using wavelet transform in Python

### ISSUE THREAD

**Issue by florenceatieno45** [section-engineering-education/engineering-education#6161]
#### Introduction
Image denoising is a big challenge in image processing and computer vision. It is because, at points, it may need more algorithms to do it. The main aim of denoising is to remove noise from the noisy version to give the original version of the signal. Wavelet transform is a very powerful tool widely used for feature extraction and hence finds its importance in machine learning.
In this tutorial, the wavelet transform based denoising of images is explained using Python. Python is a programming language that is very popular among data scientists and machine learning programmers. Also, it helps viewers in understanding the wavelet transform of images using Python.

#### Key takeaways 
- Denoising scheme using Wavelet Transform.
- Anaconda and Spyder for Python code development.
- SciKit-image Python package.
- Explanation of denoise_wavelet() python function of SciKit-image.
- Python code of denoising images.

#### Article quality
This article shows how you can use the wavelet transform to denoise images.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
