### ISSUE TITLE
An Overview of  Different AWS Database Services 

### ISSUE THREAD

**Issue by raboba2re** [section-engineering-education/engineering-education#6162]
#### Proposed article introduction
Amazon Web services (AWS) offer over 200 fully managed services from different data centers globally. Fifteen of these cloud computing services are purpose-built database engines that are grouped into relational and non-relational database services.

A relational database stores data in a tabular form using rows and columns. The columns represent attributes, while the rows represent records. A relational database links information from multiple tables using keys. These keys are uniquely assigned to rows of data within a table and can be queried using the Structured Querying Language (SQL), a language designed to manage a relational database. 

The Non-relational database, also known as NoSQL stores data in an unstructured format using a storage model optimized to meet the specific data being stored. Because data stored in a NoSQL database is an unstructured format, it allows a large amount of data to be handled.

This article will look at some of these databases and use cases for these databases.

#### Key takeaways 
At the end of this article, the reader will learn:
- what a database is
- what relational and nonrelational databases are
- some major relational and nonrelational databases
- best use case for each of these databases.
- 

#### Article quality
This article differs from others because it will cover a wide range of databases in a single article and their uses cases. This will make it easier for developers to choose which database to use depending on their project requirements.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to suggest another topic. Thanks

https://aws.amazon.com/free/database/?trk=ps_a134p000007Cga9AAC&trkCampaign=acq_paid_search_brand&sc_channel=PS&sc_campaign=acquisition_EEM&sc_publisher=Google&sc_category=Database&sc_country=EEM&sc_geo=EMEA&sc_outcome=acq&sc_detail=aws%20database%20services&sc_content=Cloud%20Database_e&sc_matchtype=e&sc_segment=548915588388&sc_medium=ACQ-P|PS-GO|Brand|Desktop|SU|Database|Solution|EEM|EN|Text|xx|Non-EU&s_kwcid=AL!4422!3!548915588388!e!!g!!aws%20database%20services&ef_id=Cj0KCQiAosmPBhCPARIsAHOen-O-Jy1Gc1vUESuimqakhFg3fTGlkw4dDuROMxO7xlY4samVMLlEMjEaAjksEALw_wcB:G:s&s_kwcid=AL!4422!3!548915588388!e!!g!!aws%20database%20services
