### ISSUE TITLE
Easy way to learn blockchain technology

### ISSUE THREAD

**Issue by Dave-Prince** [section-engineering-education/engineering-education#6163]
### Topic Suggestion
Blockchain
#### Proposed title of article
The easy way to learn and understand blockchain technology
#### Proposed article introduction
Blockchain technology is growing so fast in the current world, many find it important to get started learning blockchain and most important the programming part of blockchain development.
Learning blockchain development can feel very overwhelming! Especially getting into new concepts, terms, programming and developers tools to handle this can feel landing into far way different niche.
In this tutorial, I want to explain the easy way of getting into blockchain programming by choosing a task and handling it, in addition, I'll I'll explain how blockchain technology change the current world of technology.

#### Article quality
This tutorial, readers will gain easy way to learning blockchain technology as opposed to the normal steep learning curve. This will be a faster way to get into blockchain development.
#### References
N/a

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
