### ISSUE TITLE
How to identify and fix slow running queries in MySQL

### ISSUE THREAD

**Issue by elphazesedah** [section-engineering-education/engineering-education#6164]
#### Proposed article introduction
Slow execution of queries if a common problem in databases specifically MySQL. This is a huge drawback to users dealing with large databases with dense data contents. This is why MySQL has ways and methods of filtering and identifying the queries that are executing at a slower pace. Having identified these slow queries, there are also methods of handling the queries or even trying to fix their speed of execution.

In this article I will be diving into MySQL queries and how they are executed.  I will go ahead and explain the  techniques of identifying slow running queries in MySQL and explaining in-dept the ways in which they can be made fast.

#### Key takeaways 

1. The reader will be able to understand the techniques for identifying slow running queries in MySQL database.
2. The reader will be able to understand the different ways of fixing slow running queries in MySQL database.
3. The reader will understand  how to execute queries effectively in MySQL database.

#### Article quality
This article will provide a easier and simple to understand guide for identifying and handling slow running queries in MySQL.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=How+to+identify+and+fix+slow+running+queries+in+MySQL) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by elphazesedah** [comment]
Hi... @louisefindlay23 ..I will be working on making this article unique by using easy and simple to understand language to illustrate the common  everyday query problems. Each problem will be coupled with a fix enabling smooth flowing reads for our potential readers. I will also provide illustratory screenshots  for visual understanding.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
