### ISSUE TITLE
Getting Started with Cloud Firestore Database in Flutter

### ISSUE THREAD

**Issue by ianmasae** [section-engineering-education/engineering-education#6168]
#### Proposed title of article
Getting Started with Cloud Firestore Database in Flutter

#### Proposed article introduction
Due to rapid technological advancement, the need for cloud-based applications is briskly increasing. Firestore is a cloud-hosted, NoSQL database used to store and sync app data for global apps.
This tutorial aims to guide the readers through a step-by-step understanding and implementation of a cloud Firestore database in Flutter.

#### Key takeaways 
The reader will be able to:
- Create a cloud Firestore database
- Upload data to cloud Firestore database
- Read data from cloud Firestore database
- Update existing data from cloud Firestore database
- Delete data from cloud Firestore database

#### Article quality
This tutorial aims to comprehensively guide the readers through a step-by-step understanding and implementation of a cloud Firestore database functionalities such as create, read, update and delete in Flutter.

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
