### ISSUE TITLE
[Languages]How Create a Beginners Chat Room in Python Implementing TCP

### ISSUE THREAD

**Issue by GeekEdmund** [section-engineering-education/engineering-education#6169]
#### Proposed title of article
 
How to Create a Beginners Chat Room in Python Implementing TCP

#### Proposed article introduction

A chat room is considered an area on the internet or other computer network where users can communicate, typically one dedicated to a particular topic, Thus allowing multiple users to connect concurrently.
This article borrows a leaf from both socket programming and multi-threading as well which is important in setting up the chat room. The topics can range from anything such as app development to any recipes made in the kitchen.
Chat rooms are great platforms for learning how to communicate. We are going to build a real-time chat room implementing the use of sockets in python.

#### Key takeaways 

1. Importing Relevant Libraries. 
2. Setting up of the socket.
3. Manipulation and Creation of the  Client-Side.
4. Creating the Complete Server-Side Chatroom Code.
5. Creating of connection to the server.

#### Article quality

Explained and coded in a unique way providing a wider range of knowledge cutting across from networking to python programming.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to suggest another topic. Thanks
