### ISSUE TITLE
[Machine Learning] Natural language processing using Gradient Boosting Machine and H2O library

### ISSUE THREAD

**Issue by willyngashu** [section-engineering-education/engineering-education#6171]
#### Proposed title of article
[Machine Learning] Natural language processing using Gradient Boosting Machine(GBM) and H2O library

#### Proposed article introduction
Natural language processing helps machines understand and respond to text or voice data like human beings. We will use the Gradient Boosting Machine and H2O library to build a natural language processing model. GBM is an algorithm that combines the predictions from multiple decision trees to generate the final predictions. Every successive decision tree is built on the errors of the previous trees. The trees in GBM are sequentially and the final output is a model that is fully optimized.  GBM converts weak learners into strong learners.

H2O's is used for automating the machine learning workflow, which includes automatic training and tuning of many models within a user-specified time limit. H2O offers a number of model explainability methods that apply to AutoML objects. This speeds up the development process and saves developers time. H2O also applies various optimization techniques in choosing the best algorithm to build the model. 

Using two libraries we will have every effective model. The model will have high performance and will be able to make accurate predictions.

#### Key takeaways 
1.  Gradient Boosting Machine.
2. Text preprocessing activities.
3. Installing H2O library.
4. H20 methods and functions.
5. Building the model for natural language processing using GBM and H2O.

#### Article quality
This article is unique because we will be building a custom model. We will build a sentiment analysis model which is a type of natural language processing. We will then explore the various GBM method to give a reader a better understanding. Finally, we will integrate GBM and H2O so that we have a fully optimized model. The model will have a high-performance accuracy score and make accurate predictions.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
