### ISSUE TITLE
Random Quote Generator with React

### ISSUE THREAD

**Issue by prince-joel** [section-engineering-education/engineering-education#6173]
### Topic Suggestion
Random Quote Generator with React

### Writing sample(s): 
https://www.section.io/engineering-education/implementing-totp-2fa-using-flask/

#### Proposed title of article
Random Quote Generator with React

#### Proposed article introduction
You might have wonder how random quote generators you see on the web are built. in this article you will learn how to build a Random Quote Generator with React , also see how the quotes are gotten because we will be calling an API where the quote for this tutorial are stored using the fetch method.

#### Key takeaways 
* The reader will be able to build simple UI easily
* The reader will understand what an API is 
* The reader will learn how to call an API using the Fetch method

#### Article quality
In the article the reader does not just only learn how to build, the reader is thought what an API is and shown a detailed way on how to call an API using the Fetch method.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to suggest another topic. 

https://www.google.com/search?q=Random+Quote+Generator+with+React&oq=Random+Quote+Generator+with+React&aqs=chrome..69i57j35i39i362l6j69i61.251j0j7&sourceid=chrome&ie=UTF-8
