### ISSUE TITLE
[Artificial Intelligence] Artificial intelligence in advancing data analytics in banks for improved regulatory compliance

### ISSUE THREAD

**Issue by Florence-Mwangi** [section-engineering-education/engineering-education#6175]
#### Proposed title of article
Artificial intelligence in advancing data analytics in banks for improved regulatory compliance. 

#### Proposed article introduction
Banks experience regulatory compliance issues across different markets.
Banks' regulatory compliance issues occur due to insufficiently advanced technology that could be embedded in the firm's system.  
Artificial Intelligence (AI) is a solution that will maximize data analytics to enable banks to identify regulatory compliance requirements to ensure reduced cases

#### Key takeaways 
1. How artificial intelligence will help to combat fraudulent transactions in banks by using advanced data analytics
2. How banks will use advanced data analytics to guide AI algorithms for anti-money laundering activities.
3. How banks will use artificial intelligence to break down high volume data to acquire valuable insights to improve customer experience
4. How advanced data analytics will be helpful in cognitive systems to make strategic decisions
#### Article quality
The article is unique because it will offer in-depth information on the topic and shed more light on an area with minimal research.

#### References
None for now.

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks

**Comment by Florence-Mwangi** [comment]
kindly open this so that I can upload as requested
