### ISSUE TITLE
[Machine Learning] Machine Learning using Pandas Profiling and Scikit-learn Pipeline

### ISSUE THREAD

**Issue by Bravinsimiyu** [section-engineering-education/engineering-education#6176]
#### Proposed title of article
[Machine Learning] Machine Learning using Pandas Profiling and Scikit-learn Pipeline

#### Proposed article introduction
Pandas profiling is an open-source Python module with which we can quickly do an exploratory data analysis. Pandas Profiling saves us all the work of visualizing and understanding the distribution of each variable. Pandas Profiling generates a report that shows the overview, variables, interactions, correlations, missing values, and a sample of your data. This enables faster data analysis and manipulation.

Python Scikit-learn provides a Pipeline utility to help automate machine learning workflows. Pipelines work by allowing for a linear sequence of data transforms to be chained together culminating in a modeling process that can be evaluated. The Pipeline assembles several steps that can be cross-validated together while setting different parameters.

Through the use of both the Pandas Profiling and Scikit-learn Pipeline, we will be able to build a machine model. The packages will enable to follow all the machine learning workflows and stages.
#### Key takeaways 
1. Installing Pandas Profiling
2. Generating the dataset profile report.
3. Initializing the pipeline steps.
4. Creating the Pipeline transformers and estimators.
5. Automate machine learning workflows.

#### Article quality
This tutorial is unique because we will use both the Pandas Profiling and Scikit-learn Pipeline. By the two libraries, we will build a custom model that predicts customer churn. The tutorial will also use guided steps that explain the installation and the use of these libraries. This is a practical approach. We will also explore the transformers and estimators functions that are used to automate the machine learning workflows

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
