### ISSUE TITLE
Artificial Intelligence in cybersecurity: pitting Algorithms vs Algorithms

### ISSUE THREAD

**Issue by mwangiki** [section-engineering-education/engineering-education#6178]
#### Proposed title of article
Artificial Intelligence in cybersecurity: pitting Algorithms vs Algorithms

#### Proposed article introduction
Artificial Intelligence in cybersecurity is transforming the way we perceive protection against dark hat hacker that have hostile aim. It is important to have firm technique to cybersecurity. It is essential to have comprehensive technique, when firms recognize what algorithms is used because it make great strong security ecosystems.

#### Key takeaways 
-The developing nature of cybercrime
-Best predication through Artificial Intelligence
-Enhancing the scope of Artificial Intelligence in cybersecurity
-Reinforcing models of protection
- Artificial Intelligence to investigate hacking conduct
- 
#### Article quality
-I will use simple language for easy understanding
-It will contain detailed information.
-it will be simple to understand
-it will be direct to the point for easy understanding

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to suggest another topic.
