### ISSUE TITLE
Encyption and decryption of string using python

### ISSUE THREAD

**Issue by hezemwash** [section-engineering-education/engineering-education#6179]
#### Proposed title of article
Encryption and decryption of string using python

#### Proposed article introduction
in this article, I will discuss the concept of encryption and decryption of string in python and execute it. Whereby there will be conversion of text to ciphertext through the process called encryption and decoding the encoded data which is converting back ciphertext to plain text through the process called decryption.
#### Key takeaways 
-introduction to encryption and decryption.
-symmetric key encryption
-steps to be followed for symmetric key encryption
-Asymmetric key encryption
-steps to be followed for Asymmetric key encryption
-conclusion

#### Article quality
-I will use simple language for easy understanding
-It will contain detailed information.
-it will be direct to the point for easy understanding
#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to submit another topic. Thanks

https://www.google.com/search?q=Encyption+and+decryption+of+string+using+python&oq=Encyption+and+decryption+of+string+using+python&aqs=chrome..69i57j69i61.243j0j9&sourceid=chrome&ie=UTF-8
