### ISSUE TITLE
[Languages]Image Gallery CRUD using PHP MySQL

### ISSUE THREAD

**Issue by amosnjoro** [section-engineering-education/engineering-education#6183]
#### Proposed title of article
Image Gallery CRUD using PHP MySQL

Use keyword research to improve your article's SEO.

#### Proposed article introduction
We'll learn about the CURD image gallery in this part. This will be done with PHP and MySQL. Users, students, employees, administrators, and others may require the picture gallery, remove module, and insert update options at times. As a result, we must produce these items for them. We'll use the Photo album to quickly add and remove a photo while maintaining validity. We'll use Bootstrap to construct a beautiful layout with an image gallery in our app.

We'll use Scratch to create a photo gallery with a pleasing layout. It will be quite simple for us to build it with our application if we do it this manner.

#### Key takeaways 
1. Creating image_gallery table
2. Creating DB Configuration file
3. Creating Index.php File.
#### Article quality
My aim in this article is to deliver content that will be understood by learners and an original one.

**Comment by WanjaMIKE** [comment]
Your key takeaways seem to be extracted from https://www.itsolutionstuff.com/post/php-mysql-simple-image-gallery-crud-example-from-scratchexample.html

Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to suggest another topic.
