### ISSUE TITLE
How to Create Functional Buttons using JavaScript

### ISSUE THREAD

**Issue by KiruiBrian14** [section-engineering-education/engineering-education#6184]
### Topic Suggestion
How to create Functional buttons using JavaScript
### Proposed title of article
Creating Functional Buttons using JavaScript.

#### Proposed article introduction
Buttons are present in almost all aspects of web browsers whether is it exiting a site, clicking on a heart shape to like a picture or buttons with descriptions inside them like the ones to save whatever you are inputting in a form. This article will talk about the different types of buttons and how to create them and most importantly how to add functionality to them so that they can do what we want them to do. This article will also address creation of aesthetically pleasing buttons and reduce the long lines of code that are used when creating them using just HTML and CSS.

#### Key takeaways 
1.Learn to create web buttons
2.Learn how to style the buttons and link them the styling to the HTML and JavaScript files.
3.Understand how to use JavaScript to make the buttons functional.

#### Article quality
This article will provide a step by step introduction into creation of buttons to finishing of the functionality of the said buttons and the codes will be well explained, it focuses on simplicity while having your web projects looking neat and actually doing what they're expected to do.

#### References
N/A

### Conclusion
This will be a guide to all looking into creating buttons in web design and how to do it.

**Comment by WanjaMIKE** [comment]
Making buttons functional using event and onclick listeners is covered in numerous articles. Feel free to suggest another topic. Thanks
