### ISSUE TITLE
(Language)How to create  database ,tables and create  connection and insert data using pure PHP coding.

### ISSUE THREAD

**Issue by davidotsieno** [section-engineering-education/engineering-education#6196]
#### Proposed article introduction
When creating databases and tables we tend to use Xampp directly but there is a new way of creating databases and tables plus its connection using PHP pure coding which 

#### Key takeaways 
1. Learn how to create programs using classes and constructors in PHP.
2. Learn how to use functions and objects in PHP 

#### Article quality
This article will show a reader each step involved in creating databases and tables without directly opening the Xampp and creating them.

#### References
PHP documentation.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Feel free to suggest another topic.
