### ISSUE TITLE
Performing unit testing in python

### ISSUE THREAD

**Issue by Dick7603** [section-engineering-education/engineering-education#6199]
#### Proposed title of article
[Languages] Performing unit testing in python

#### Proposed article introduction
Unit testing in Python checks if a software unit provides the required functionality. The software unit might be a module, function, or interface. The developer generally does this testing before passing it on to the next level of integrated testing. Python helps programmers write test cases that cover all potential circumstances during real-time execution and document the findings. This will automate the testing process and allow developers to test several times in a short amount of time.

#### Key takeaways 
By the end of this article, the learner will be able to understand the following:
- What is unit testing in python
- What are some of the ways we can use to test our code in python
- Integration testing vs. unit testing
- What are some of the test runners to employ in python unit testing and their features

#### Article quality
As much as it is challenging to deplete knowledge, the article will provide a stepwise implementation of unit testing in python in an exciting and easy to understand. This article will cover all essential concepts related to unit testing in python and in-depth to make it beginner-friendly. Screenshots and examples where relevant will be provided. This will be more beginner-friendly.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Most of your key takeaways on unit testing seem to be covered by the following articles in this search results https://github.com/section-engineering-education/engineering-education/pulls?q=unit+testing+in+python Feel free to suggest another topic. Thanks
