### ISSUE TITLE
[Blockchain] Understanding Altcoins in Cryptocurrencies 

### ISSUE THREAD

**Issue by selina-maina** [section-engineering-education/engineering-education#6200]
### Topic Suggestion
Understanding Altcoins in Cryptocurrencies 

#### Proposed article introduction
The cryptocurrency space boomed with the introduction and success of bitcoin. The now most popular coin in the market boosted of providing a future where people could transact and make their investments away from the influence of governments and large centralized institutions. Through bitcoin words like defi(decentralized finance) became popular. However bitcoin's domination in the crypto market faced competition from other coins developed to patch up the  setbacks the popular coin had. 

#### Key takeaways 
- Reasons for the development of altcoins 
- An extensive introduction to altcoins 
- Setbacks that in bitcoins that led to the development of altcoins 
- Types of altcoins 
- Functions of each type of altcoin

#### Article quality
The uniqueness of the article will be  brought out through the article's depth. Additionally, blogs on the web focus only on a single coin, this easily confuses most beginners who are seeking to learn more on crypto currencies. This article will act as a map for anyone who seeks to have grounding knowledge on the different coins available in the market.

#### References
n/a

**Comment by WanjaMIKE** [comment]
Thank you for the topic suggestion, however this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore.
