### ISSUE TITLE
[Networking] A Dive into Passwordless SSH

### ISSUE THREAD

**Issue by lin-chez** [section-engineering-education/engineering-education#6201]
### Topic Suggestion
Understanding Passwordless SSH

### Writing sample(s): 
[How to Add Pure CSS Waves to Your Website](https://www.section.io/engineering-education/pure-css-wave-animations-website/)

#### Proposed title of the article
Understanding Passwordless SSH

#### Proposed article introduction
Online privacy and security are vital considerations in technology. In the current era, information is comparable to gold. Because of the value that information holds, there has been a rise in better security practices and strategies meant to ensure information remains secure on the internet. The secure shell host protocol (SSH) is among the vital security implementations technology experts use to secure information on transit in an unsecured network. As time passes the cryptographic based protocol has seen a revamp into a passwordless alternative meant to increase its robustness as one of the best security protocols in use. 

#### Key takeaways 
- what is passwordless SSH
- Reasons for preferring passwordless SSH over normal SSH 
- Advantages and disadvantages of passwordless SSH
- Use cases of passwordless SSH
- How to set up passwordless SSH

#### Article quality
Articles on the web only focus on how one can set up passwordless SSH. This article takes a broad but deeper approach to include the advantages and disadvantages of the technology combined with an explanation of the what, why and how of passwordless SSH.
#### References
N/A

**Comment by WanjaMIKE** [comment]
Seems like you have another open issue @lin-chez
