### ISSUE TITLE
How to implement Shutdown,Restart,Sleep and Lock Workstation actions in C# Window Forms

### ISSUE THREAD

**Issue by fely545** [section-engineering-education/engineering-education#6203]
#### Proposed title of article
 How to implement Shutdown,Restart,Sleep and Lock Workstation actions in C# Window Forms

#### Proposed article introduction
Many people choose to power of their machines using the power button. In this article, I'll show you how to shut down your computer without using the power button. We will be using Window Forms to implement this. We will also learn how to implement restart, log off or lock your computer in C# using windows forms.

### Key Takeaways

- How to work with Windows Forms
- How to implement a working shutdown button
- How to implement a working restart button
- How to implement a working lock  button
- How to implement a working sleep button
 
### Article quality
In this article I will use well explained codes implementing the above key takeaways. We will first create a Windows Form which we will then include the shutdown button, restart button, etc

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
