### ISSUE TITLE
Introduction to Remote Procudure Call 

### ISSUE THREAD

**Issue by morwabe1234** [section-engineering-education/engineering-education#6207]
Introduction to Remote Procudure Call 

Remote procedure call refers to a method of constructing distributed systems. In essence, it enables a software on one system to call a function on another machine without the latter being aware that it is remote.This technique is used for communication between  the client and the server.

Key takeaways
What is a remote procedure call?
Events involved in the remote procedure call.
Diagramatic implementation of a remote procedure call.
Program to implement a remote procedure call in both the server and the client.
Benefits of remote procedure call.
Drawbacks of the remote procedure call.

Article quality
This article is unique as it covers the topic in-depth with additional information about remote procedure calls and implementation of a remote procedure call in both architecture and client-server programs.

References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations such as [these ones](https://www.google.com/search?q=Introduction+to+Remote+Procudure+Call&oq=Introduction+to+Remote+Procudure+Call&aqs=chrome..69i57j69i61.309j0j4&sourceid=chrome&ie=UTF-8)
