### ISSUE TITLE
Understanding filters in PHP

### ISSUE THREAD

**Issue by Nicholas-Obare** [section-engineering-education/engineering-education#6208]
Understanding filters in PHP

PHP Filter is a data filtering plugin that sanitizes or validates data. Many of the methods needed for verifying user input are included in the PHP filter extension, which is meant to make verification easier and faster. In this article, we are to discuss more on PHP filters.

Key takeaways
What is a filter in PHP?
PHP filter example.
Benefits of using  PHP filters.
How to sanitize a string using a PHP filter with an example program.
How to validate an integer using PHP filter with an example program.
how to validate an IP address using PHP filter with an example program.
How to sanitize and validate an email address with an example program.
Article quality
This article is unique as it gives more information about PHP filters and uses PHP programs to implement in each concept being discussed

References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Please feel free to suggest an alternate topic to explore.
