### ISSUE TITLE
Using GCD in python

### ISSUE THREAD

**Issue by Ushter21** [section-engineering-education/engineering-education#6211]
#### Proposed title of article
[Languages] Using GCD in python

#### Proposed article introduction
Among all the complex ideas of trigonometry and arithmetic, one notion employed most frequently in programming is the GCD or Greatest Common Divisor. Greatest Common Divisor (GCD), also referred to as the Highest Common Factor (HCF), is a fundamental concept in mathematics used while finding the most significant common factor that can perfectly divide the two numbers. Similar to other programming languages, python also permits the building of a code that will determine the GCD of two numbers supplied by the user. In this article, we will learn how to accomplish precisely that.

#### Key takeaways 
- Clearly understand what is GCD as a concept in mathematics
- What is GCD in python
- What is the use of GCD in python
- Various methods to use to find GCD in Python Using Recursion
- Exceptions in math.gcd() function of Python

#### Article quality
The article will be in-depth and beginner-friendly. Since the article is about using GCD in python, I will provide practicable and straightforward examples, especially in the methods used in finding GCD in Python. The coverage will employ understandable and straightforward language.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations such as [this](https://www.google.com/search?q=Using+GCD+in+python&oq=Using+GCD+in+python&aqs=chrome..69i57j0i22i30l2j0i22i30i395l4j69i61.902j1j9&sourceid=chrome&ie=UTF-8)
