### ISSUE TITLE
Managing  Work Queues With Beanstalk and Supervisor on Ubuntu 20.04 with Laravel 8

### ISSUE THREAD

**Issue by roselyneodero** [section-engineering-education/engineering-education#6212]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Managing  Work Queues With Beanstalk and Supervisor on Ubuntu 20.04 with Laravel 8

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Building extensive applications sometimes come with some additional problems. These may include operations to upload CSV files which may take time to parse and save into your database.  

The solution to such problems is using the Laravel queued jobs that process these operations in the background.

In this tutorial, I'll teach you everything you need to know about Laravel queues and later on introduce the concepts of [beanstalk](https://beanstalkd.github.io) and Supervisor in Ubuntu 20.04.

Beanstalk is a simple, fast work queue. 

It allows you to run time-consuming tasks asynchronously, such as sending emails, connecting to external APIs, or processing images. 

By doing so, you will reduce your web app latency. In addition, laravel provides out-of-the-box support for beanstalkd.

#### Key takeaways 
- - Understanding the concepts of beanstalkd
- Learning how to integrate the Laravel work queues with beanstalkd
- Running the application with Supervisor on ubuntu 20
#### Article quality
In this article, we discuss the concept of Beanstalk on the latest version of Ubuntu. This is very distinct since the installation process is quite different from previous versions.

Managing queues with Beasnstalkd is very rare since we mostly use Redis. So this article gives people who prefer beanstalk an opportunity to understand this new approach.

Lastly, this article focuses mainly on the Linux environment, which of course provides access to the Supervisor for ease of installation and setup.

> Unlike the existing light article on this topic, this tutorial will give readers a more in-depth explanation on why we use queues with beanstalkd and how we can configure the same without on virtual machines without interfering with the local machine, hence very unique.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Please fill in the article quality section. @roselyneodero

**Comment by roselyneodero** [comment]
@ahmadmardeni1 done!

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @roselyneodero 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to link a PR. 👍
