### ISSUE TITLE
Learn How To Build a Recipe Generator with React

### ISSUE THREAD

**Issue by Chukslord1** [section-engineering-education/engineering-education#6216]
### Topic Suggestion
Recipe Generator with React

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Recipe Generator with React

#### Proposed article introduction
Have you ever wanted to make a dish and needed the recipe for the ingredient to make your desired dish? In this article you are going to learn how to build a Recipe Generator with React, where you enter the name of the dish and the recipe will be made known to you. You will also learn how to get the data for the recipe by calling a recipe API using the Fetch method

#### Key takeaways 
* This article is beginner and intermediate  friendly, the reader will learn how to build a clean user interface using react
* The reader will learn how to build the required components for the application
* * The reader will learn how to use the API to implement CRUD functionalities in the application

#### Article quality
This article will teach the reader how to call build a recipe generator using data from an API,  then implement CRUD operations on the data with React.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

https://www.google.com/search?q=Learn+How+To+Build+a+Recipe+Generator+with+React&oq=Learn+How+To+Build+a+Recipe+Generator+with+React&aqs=chrome..69i57j69i61.271j0j9&sourceid=chrome&ie=UTF-8
