### ISSUE TITLE
Data fetching in React

### ISSUE THREAD

**Issue by giridhar7632** [section-engineering-education/engineering-education#6218]
#### [Node.js] Complete Guide to Data-fetching in React

react, data-fetching, axios, react-query, swr

#### Proposed article introduction

When developing large-scale react apps, I frequently run into issues with optimizing data-fetching methods. So, in this article, I'd like to discuss several common data-fetching techniques in react that make use of react-hooks, react-query, and swr. This article covers a broad range of topics, such as creating custom hooks for data-fetching and utilizing other libraries for the job.

#### Key takeaways 

- Creating custom hooks
- Using React Query
- Introduction to SWR
- Comparison between popular libraries (react-query, swr)

#### Article quality

This article will be unique and covers different popular techniques for data-fetching.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
