### ISSUE TITLE
Improving App Performance With Async And Await In C#

### ISSUE THREAD

**Issue by Ainea-Amush** [section-engineering-education/engineering-education#6220]
#### Proposed title of article
Improving App Performance With Async And Await In C#

#### Proposed article introduction
It has always been every developer's dream to building a nice app to users. Regrettably, some apps developed have not been meeting user needs therefore some get annoyed when using them. For example, in an app, you might have a task that depends on the result of another task or multiple functions that span tasks therefore keeping track of everything becomes difficult .

Unlike in android where the performance of such app has been improved by benchmarking, in this article , we will go a step by step improving the performance of such app using async and await in language c.

Async and await allow us to write what looks like regular function with a few await statements thrown in and the system splits the function into a list of code blocks that can be paused and resumed as the things being awaited finish.

#### Key takeaways

-    Understanding the concept of async and await.
-    How to implement async and await in C#.
-    How C processes this concept in improving app performance.

 #### Article quality

I will take the reader through the concept of async and await, how to implement it in C# and how app performance is improved from the C# processes.

#### References
 N/A

**Comment by WanjaMIKE** [comment]
You seem to have another topic suggestion. Thanks

**Comment by Ainea-Amush** [comment]
@ahmadmardeni1 
Hello, this topic suggestion #6220 was closed because I was told I had another topic suggestion but unfortunately it was closed ....please reopen it and have a look at it. Thank you

**Comment by ahmadmardeni1** [comment]
Hey @Ainea-Amush This topic is already covered by a lot of blog sites. For example: https://medium.com/@frederikbanke/improving-scalability-in-c-using-async-and-await-f97af1466922

Please feel free to suggest another topic.
