### ISSUE TITLE
 Bridge to Kubernetes: The Perfect Replacement for Azure DevSpaces

### ISSUE THREAD

**Issue by BridgetMwikali** [section-engineering-education/engineering-education#6223]
#### Proposed title of article
 Bridge to Kubernetes: The Perfect Replacement for Azure DevSpaces

#### Proposed article introduction
With the fall of Azure Dev Spaces, Bridge to Kubernetes has come in as a replacement. Both these Kubernetes development tools share the same goal; to make debugging and integration testing easy in a complex Kubernetes setup. But they also differ in many ways. The main difference is that, with Bridge to Kubernetes, your code now runs locally on your machine.

This article discusses Bridge to Kubernetes and DevSpaces, gives an overview of how Bridge to Kubernetes works, and explains why Bridge to Kubernetes is a perfect replacement for DevSpaces. 

#### Key takeaways 

1. An overview of Bridge to Kubernetes and DevSpaces.
2. How Bridge to Kubernetes simplifies microservice development in VS Code
3. How Azure DevSpaces differ from Bridge to Kubernetes.

#### Article quality
This article will explain Azure DevSpaces shortcomings that Bridge to Kubernetes came to address. It will also show the reader how Bridge to Kubernetes works to simplify microservice development in Visual Studio Code. 

#### References
https://docs.microsoft.com/en-us/visualstudio/bridge/overview-bridge-to-kubernetes

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).
 @BridgetMwikali 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
