### ISSUE TITLE
Testing for Broken Authentication in Web Apps

### ISSUE THREAD

**Issue by shosenwales** [section-engineering-education/engineering-education#6224]
### Topic Suggestion
Testing for Broken Authentication in Web Apps

### Writing sample(s): 
https://www.section.io/engineering-education/getting-started-with-burpsuite/

https://www.section.io/engineering-education/understanding-cross-site-scripting-attacks/

#### Proposed title of article
Testing for Broken Authentication in Web Apps

#### Proposed article introduction
[Security] This article intends to introduce the reader to broken authentication attacks. Also, simulating how attackers aim to take over accounts, and acquire the same privileges as the attacked user.

#### Key takeaways 
At the end of this article, the reader should be able to:
- Understand what broken authentication is
- Understand the impact of this attack
- Be able to test web applications for this vulnerability

#### Article quality
I won't only be talking about the attack/ vulnerability, i would also show you how to test for such vulnerability by attacking an intentionally vulnerable application.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @shosenwales 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
