### ISSUE TITLE
[API]   API Mocking Tools and Best Practices 

### ISSUE THREAD

**Issue by Polojigide** [section-engineering-education/engineering-education#6226]
#### Proposed title of article
API Mocking Tools and Best Practices 

#### Proposed article introduction
The possibility to create mock-ups / mock system components is becoming increasingly important in contemporary development. It enables a number of development and testing workflows that greatly enhance the agility of developments teams in enterprises with complex infrastructures and systems. 

Just like testing, mocking can be done at many levels; code, API, service, and infrastructure to name some, and can be used for both functional and non-functional scenarios. Specifically, API mocking can empower your development and testing teams in their everyday work.

#### Key takeaways 

- An  overview of API mocking
- Real Backends vs Mock APIs
- Why API Mocking?
- API mocking best practices
- Examples of API mocking frameworks and tools
#### Article quality
This article digs deeper beyond explaining API mocking, unlike other available articles.  It compares mock APIs to real backends and explains the most popular and lesser-known API tools and frameworks while discussing their strengths and weaknesses.  

#### References
N/A

**Comment by ahmadmardeni1** [comment]
How does your article differ from similar ones? Like: https://www.soapui.org/learn/mocking/what-is-api-mocking/ @Polojigide

**Comment by Polojigide** [comment]
@ahmadmardeni1 
The article you've highlighted lists API mocking best practices but doesn't go into details. This article is more in-depth; it digs deeper into this topic to compare API mocking and Real Backends as well as provide the strengths and weaknesses of the most popular and lesser-known API tools and frameworks.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Polojigide 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
