### ISSUE TITLE
(Language) How to add items to a shopping cart  container and display them in a table in PHP

### ISSUE THREAD

**Issue by calvinombati** [section-engineering-education/engineering-education#6227]
#### Proposed article introduction
 In this article, I will demonstrate a PHP  program that explains how to add items into a cart container store them in a database, and query from the database in order to display them in form of a table.
#### Key takeaways 
- The reader should be able to understand how to use bootstrap to create and add items to a shopping cart container.
- Also the reader should be able to understand how to query items from the database and display them in form of a table.
- The reader should be able to know how to create a database, table, and insert items to the table.

#### Article quality
My article will be unique since I will use pure coding  In PHP, HTML, and CSS without any framework.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations such as [this](https://www.google.com/search?q=How+to+add+items+to+a+shopping+cart+container+and+display+them+in+a+table+in+PHP&oq=How+to+add+items+to+a+shopping+cart+container+and+display+them+in+a+table+in+PHP&aqs=chrome..69i57j69i61.239j0j9&sourceid=chrome&ie=UTF-8)
