### ISSUE TITLE
[Android] Getting Started with the New Duration API in Kotlin

### ISSUE THREAD

**Issue by kariuki-boniface** [section-engineering-education/engineering-education#6230]
#### Introduction
The New Duration API which is now part of the Kotlin stdlib. This API is available in Kotlin 1.6.0 and has made it easier to manage time in your android app project. In this tutorial, I will show the learner how to use this API to manage time the simplest way!

#### Key takeaways 
- Understanding the Duration API
- How to represent time using the API in an app
- Extension Properties of the Duration API

#### Article quality
My article will be unique in the fact that this API is very new in the kotlin stdlib. This article will be made as clear and simple as possible for any kind of learner to understand.

#### References
- Kotlin Standard Library APIS
- Kotlin Documentation

**Comment by WanjaMIKE** [comment]
Your current key takeaways seem to be adequately covered in the official documentation -> https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/ Feel free to suggest an alternative topic.
