### ISSUE TITLE
Finding periodicity using autocorrelation in Matlab

### ISSUE THREAD

**Issue by florenceatieno45** [section-engineering-education/engineering-education#6232]
#### Introduction
Periodicity is the quality of being periodic. A periodic function is a function that occurs at similar intervals. Autocorrelation represents the degree of similarity between a given time series and a lagged version of itself over successive time intervals. Autocorrelation measures the relationship between a variable's current value and its past values. Measurement uncertainty and noise sometimes make it difficult to spot oscillatory behaviour in a signal, even if such behaviour is expected.

The autocorrelation sequence of a periodic signal has the same cyclic characteristics as the signal itself. Thus, autocorrelation can help verify the presence of cycles and determine their durations. In this article, we will see how to find the periodicity using Matlab.

#### Key takeaways 
- How periodicity is done.
- Getting the autocorrelation.
- Matlab code for periodicity and autocorrelation.

#### Article quality
This article combines both the periodicity and autocorrelation concepts.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
How does your article differ from the [official docs](https://www.mathworks.com/help/signal/ug/find-periodicity-using-autocorrelation.html)? @florenceatieno45

**Comment by florenceatieno45** [comment]
@ahmadmardeni1 In this article we compute the autocorrelation of the temperature such that it is unity at zero lag. We then restrict the positive and negative lags to three weeks. While doing this, we note the double periodicity of the signal.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @florenceatieno45 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
