### ISSUE TITLE
[Android] Implementing Automatic Animated Sliders in Jetpack Compose

### ISSUE THREAD

**Issue by Janenjoki** [section-engineering-education/engineering-education#6236]
### Writing sample(s): 
My previous articles can be found [here](https://github.com/section-engineering-education/engineering-education/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Ajanenjoki+is%3Amerged)

#### Proposed title of article
Implementing Automatic Animated Sliders in Jetpack Compose

#### Proposed article introduction
The user interface and user experience (UI/UX) of your mobile app is critical. You must create an exceptional user interface and user experience in order for your app to be successful. You can make your app more interactive and engaging by understanding your target audience's needs and preferences. Automated sliders are one of the components that can help you achieve this when implemented correctly.

In this tutorial, you'll learn how to correctly implement automatic Sliders in Jetpack Compose.

#### Key takeaways 
By the end of this tutorial, the reader will be able to:
- Understand what Sliders are
- Create a Slider component using Compose
- Create and Handle/Manage slider states to maintain consistency
- Implement different sliding animations

#### Article quality
There are so many articles and guides about Sliders using the Java/Kotlin and XML (imperative) approach. However, in the new Compose era, there seems to be less sources of correct information as Compose is considerably young! This tutorial will aid in providing the best practice in the above described topic beyond what's available in the official docs.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Please make sure your tutorial does not overlap with any of these:
- https://github.com/section-engineering-education/engineering-education/blob/master/content/articles/animations-in-jetpack-compose/index.md
- https://github.com/section-engineering-education/engineering-education/blob/master/content/articles/creating-custom-animated-shimmer-effect-with-jetpack-compose/index.md
- https://github.com/section-engineering-education/engineering-education/blob/master/content/articles/getting-started-with-jetpack-compose-in-android/index.md

Approved. @Janenjoki

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to link a PR. 👍
