### ISSUE TITLE
Django PostgreSQL Migration from SQLite

### ISSUE THREAD

**Issue by larymak** [section-engineering-education/engineering-education#6238]
#### Introduction
In reference to the official documentation, PostgreSQL is a powerful, open-source object-relational database system that uses and extends the SQL language combined with many other features that safely store complicated data workloads.

The database comes with many features that not only help developers build applications but also help administrators protect data no matter how big or small the dataset is.

#### Key takeaways 
By the end of the article the reader will be able to:
* Set up PostgreSQL locally and solve some of the possible problems likely to be encountered.
* Use PostgreSQL commands.
* Most common PostgreSQL features
* How to switch your database and migrate an existing database to PostgreSQL.

#### Article quality
The article will be unique because; I will be sharing personal experience of some of the challenges I encountered while trying to figure out how to handle the switch. Unlike other articles, I will share challenges likely to be encountered while setting up PostgreSQL and how to handle them since everything will be done with a real project not just a code snippets sample.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @larymak 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
