### ISSUE TITLE
Cleanroom software development

### ISSUE THREAD

**Issue by edwinmain** [section-engineering-education/engineering-education#6240]
**Is your feature suggestion related to a current problem or issue? Please describe.**
A clear and concise description of what the problem is. Ex. I''ve found it difficult when [...]

**Describe the solution you'd like to implement to the program**

**Describe alternatives you've considered or seen**

**Additional context on how you could go about building this**

**Comment by WanjaMIKE** [comment]
Ensure that you fill the required section before submitting a topic for approval. Thanks
