### ISSUE TITLE
A dive into Test-Driven Development (TDD)

### ISSUE THREAD

**Issue by Shikomary** [section-engineering-education/engineering-education#6244]
### Topic Suggestion
A dive into Test-Driven Development (TDD)

#### Proposed article introduction
Test-Driven Development (TDD) is the method of writing test cases before writing the code that verifies those tests. It is based on the recurrence of a relatively brief development cycle. Test-driven development is a strategy in which automated unit tests are used to drive design and dependency separation.

In this article, I will talk more on Test-Driven Development (TDD): ( A Time-Tested Recipe for Quality Software ) in detail. This article helps you understand the history behind TDD, its purpose, its relationship to testing in general, and the benefits you can gain from its use.

#### Key takeaways 
By the end of this tutorial the reader will have understood the following:
1. How do Test-Driven Development (TDD) came into being?
2. Test-Driven Development (TDD)  as a design practice.
3. Test-Driven Development (TDD)  as a well-established engineering practice
4. A small example of Test-Driven Development (TDD)
- Testing libraries
- Test Classes and Methods
- The refactoring stage
5. Which are side effects of Test-Driven Development (TDD)?
6. The different styles of Test-Driven Development (TDD)?

#### Article quality
This will be a unique article explaining the concepts in simple language. The article will have more information on the concepts of Test-Driven Development (TDD)  as a well-established engineering practice which is shallowly discussed in other documentation. It will also include a good and simple demonstration as an example.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
How does your article differ from: https://medium.com/group-a/new-to-tdd-lets-dive-into-it-67b27a01cc05 ? @Shikomary

**Comment by Shikomary** [comment]
Hello @ahmadmardeni1 
I have gone through the article you suggested and it has shallow content on the TDD. Concepts like Test Classes and Methods, the refactoring stage and  side effects of Test-Driven Development (TDD) are note discussed in the article. I will make sure that the article has every information for anyone to understand better using simple illustrations.
Thank You.

**Comment by ahmadmardeni1** [comment]
Okay approved. @Shikomary

**Comment by hectorkambow** [comment]
🤔 
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over [saturated ](https://www.google.com/search?q=Kubernetes+to+connect+IOT+devices&rlz=1C1CHBF_enUS891US891&ei=_OArYrSRKI3P0PEPm6mb-Ak&ved=0ahUKEwi0_5zOoL_2AhWNJzQIHZvUBp8Q4dUDCA4&uact=5&oq=Kubernetes+to+connect+IOT+devices&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQyQVYyQVgvAdoAXABeACAAVaIAVaSAQExmAEAoAEByAEIwAEB&sclient=gws-wiz)throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
