### ISSUE TITLE
Checker game using C++

### ISSUE THREAD

**Issue by mwangiki** [section-engineering-education/engineering-education#6247]
#### Proposed title of article
Making Checkers game using C++

#### Proposed article introduction
I will demonstrate how to make checker game using c++ language. I will discuss different variables and explain code for end user to understand.

#### Key takeaways 
-introduction of checker game
-discuss sitch statement
-variables and matrix used in project
-how to play the checker
-conclusion
#### Article quality
This article aims to go further into this topic while also presenting its principles in a straightforward, understandable manner for newcomers
#### References
N/A

**Comment by WanjaMIKE** [comment]
You seem to have another open topic suggestion. We only accept one at the moment.
