### ISSUE TITLE
Tracking of objects using histogram based tracker in Matlab

### ISSUE THREAD

**Issue by peterAdongo** [section-engineering-education/engineering-education#6250]
#### Introduction
Object tracking is an application of deep learning. The program takes an initial set of object detections, develops a unique identification for each of them, and then tracks the detected objects as they move around frames in a video.
HistogramBasedTracker returns a tracker that tracks an object. It uses the histogram of pixel values to identify the tracked object.

This article will look at how to perform object tracking using the object-based tracker. We then perform tracking of the occluded objects using the Kalman filter. Also, we combine all these concepts and perform multi-object tracking. Multi-object tracking is a technique used to track multiple targets.

#### Key takeaways 
- Object tracking using the object-based tracker.
- Tracking occluded objects.
- Matlab code for tracking.
- Multi-object tracking using the same method.
#### Article quality
This article combines the idea of the histogram and the Kalman filter to perform object tracking

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
How does your article differ from what is already published on the official docs: https://www.mathworks.com/help/vision/ug/using-kalman-filter-for-object-tracking.html ? @peterAdongo

**Comment by peterAdongo** [comment]
@ahmadmardeni1 This article shows how you use a histogram-based tracker to track objects. Also, it shows how you can use the Kalman filter to track occluded objects. All these concepts are then combined together and used for multiple object tracking.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @peterAdongo 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
