### ISSUE TITLE
In-depth Analysis of Special-Purpose Data Structures in Java

### ISSUE THREAD

**Issue by bjayzee** [section-engineering-education/engineering-education#6255]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

### Topic Suggestion
In-depth Analysis of Special-Purpose Data Structures in Java

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article

In-depth Analysis of Special-Purpose Data Structures in Java

#### Proposed article introduction

[Java] Special purpose data structures include Stacks, Queues, and the Priority Queues.
Stacks, queues and priority queues are Abstract Data Types that are implemented by a more fundamental structure such as an Array, Linked-list and a Heap (as in the case of priority queue).
These structures provide a simple interface to the user, typically allowing only insertion and the ability to access or delete an item.

#### Key takeaways 
- Introduction to special-purpose data structure such as Queues, Stack and Priority Queues
- Deep understanding of the concept of collections and its implementation
- Implementation and usage of the special-purpose data structure
- Comparison of Special-purpose data structures
- Exploring the relationship among Collection, Queue, LinkedList, and PriorityQueue and to create priority queues using the PriorityQueue class.
- Complexity Analysis
- Weighing the pros and cons of Stack and Queues

#### Article quality

It provides an indepth analysis of the concept and simplify the concept of special-purpose data structures

#### References

https://www3.cs.stonybrook.edu/~pfodor/courses/CSE260/L20_Lists_Stacks_Queues_and_Priority_Queues.pdf

https://www.tutorialcup.com/interview/stack/how-to-implement-stack-using-priority-queue-or-heap.html

https://www.educative.io/blog/data-structures-stack-queue-java-tutorial

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
