### ISSUE TITLE
[Machine Learning] Sales Forecasting with Neural Prophet

### ISSUE THREAD

**Issue by monicada** [section-engineering-education/engineering-education#6257]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Sales Forecasting with Neural Prophet

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Prophet is a library developed by Facebook that is ideal for performing time series forecasting. It is used to forecast anything that has a time series trend such as the weather and sales. This tutorial will leverage this library to accurately estimate sales trends. We will use the Python programming language for this build. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to:
1. Load data into Google Colab/Jupyter Notebook.
2. Train the Neural Prophet time series model.
3. Make predictions and evaluate time series trends performance.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Most examples I've seen on the web regarding this library is on weather forecasting. However, this library can forecast anything that works with time series such as the estimation of sales and market trends. This tutorial will focus on that.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @monicada 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
