### ISSUE TITLE
[Machine Learning] An Overview of ConvNext

### ISSUE THREAD

**Issue by smkinyan** [section-engineering-education/engineering-education#6259]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

An Overview of ConvNext

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Recently, [Vision Transformers (ViTs)](https://en.wikipedia.org/wiki/Vision_transformer) have superseded ConvNets as the state-of-the-art image classification model. ConvNext aim to argue that with some redesign and by testing the limits of what a pure ConvNet can achieve, you don't need a Transformer achitecture for vision. The ConvNext model is constructed entirely from standard ConvNet modules. ConvNeXt is accurate, efficient, scalable and very simple in design. This tutorial will discuss this new model.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

A couple of things a reader will be able to understand include:
- What is ConvNext?
- How it compares to previous models
- How to implement ConvNext using Keras

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

ConvNext is a new model recently released by Facebook research. It is less that a month old since its release. Not a lot of information is available on it on the internet. This tutorial will explain to our reader what it entails, how it compares to previous models and how to implement it using Keras.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [A ConvNet for the 2020s](https://arxiv.org/abs/2201.03545)
- [ConvNext](https://github.com/facebookresearch/ConvNeXt)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @smkinyan 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
