### ISSUE TITLE
[Artificial Intelligence] Understanding predictive maintenance in factory operations

### ISSUE THREAD

**Issue by kerubo-tech** [section-engineering-education/engineering-education#6260]
#### Proposed title of article
Understanding predictive maintenance in factory operations

#### Proposed article introduction
Predictive maintenance tracks the health of assets, their status and performance in real-time. The aim is to reduce costs by foreseeing unexpected breakdowns thus offering the manufacturer to schedule for maintenance.
Machine learning and Artificial Intelligence is used to detect flaws and failure patterns in the data produced by these assets which most of them are fitted with sensors and IoT devices. Detecting flaws in these assets is not easy but with the right AI algorithms coupled with better machine learning models it becomes easy to predict and even schedule for maintenance.
In the proposed article we will highlight the business value predictive maintenance offers, the data and data processing involved and business outcomes and changes of workflows involved.

#### Key takeaways 
At the end of the proposed article the learner will understand:
- the value of predictive maintenance
- how predictive maintenance can be implemented
- how are monitoring settings are applied to ensure the quality of the product

#### Article quality
The proposed article expounds on how artificially intelligent preventive maintenance can transform the operations of the factory unlike other articles on blog sites which tend to have scattered information on the topic.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @kerubo-tech 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
