### ISSUE TITLE
[Machine Learning] How to Implement Zero-Shot Classification using Python

### ISSUE THREAD

**Issue by lcheop** [section-engineering-education/engineering-education#6261]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

How to Implement Zero-Shot Classification using Python

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Machine learning is an ever-evolving field. One area of machine learning that has evolved greatly over the span of a few years is Natural Language Processing (NLP). The [HuggingFace](https://huggingface.co/) organization has been on the forefront in making contributions in this field. This tutorial will leverage the zero-shot classification model from huggingface to extract model predictions and perform multi-class classification. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

A reader will be able to understand:
- What is Zero-shot classification?
- How to leverage the huggingface API to perform classification
- How to implement your own Zero-Shot classifier using Python

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Some documentations are available online on what Zero-shot learning entails. However, not many articles/tutorials show us how to implement it. Learning how to implement a model is key to becoming an expert ML engineer. This tutorial will show our reader how.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [HuggingFace](https://huggingface.co/models?pipeline_tag=zero-shot-classification&sort=downloads)
- [Zero shot learning](https://en.wikipedia.org/wiki/Zero-shot_learning)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @lcheop 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
