### ISSUE TITLE
[Machine Learning] How to build a Q&A web application using Python and Anvil

### ISSUE THREAD

**Issue by lcheptoo** [section-engineering-education/engineering-education#6263]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

How to build a Q&A web application using Python and Anvil

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Question-Answering Web Apps have been around for a while now. A good example is the use of bots on websites where a user asks a question and an answer is automatically generated. In this build, I will show our readers how to build a Q&A app using one of the pre-trained models on HuggngFace. Anvil is an open-source web-interface that allows a developer to spin up and deploy a web app using Python. It is quite similar to the popular [Gradio](https://gradio.app/) web application used by developers. We will leverage Anvil to build our front-end.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to understand:
1. Where to fetch a pre-trained BERT model from.
2. The different BERT models available.
3. How to import and train the BERT model for Q&A.
4. How to leverage [Anvil](https://anvil.works/) to make the app user friendly.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

There have been articles before that have build Q&A web apps using Python mostly using the BERT model. However, there are many BERT models with different hyper-parameters that exist today. I will be using the multilingual BERT model for this build. This isn't a commonly used model. In addition, most articles use Gradio as the web interface of choice. I will be using [Anvil](https://anvil.works/) instead.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [Anvil](https://anvil.works/)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @lcheptoo 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
