### ISSUE TITLE
[Android]Implementing Reusable Custom Dialog in Android

### ISSUE THREAD

**Issue by NgureWaweru** [section-engineering-education/engineering-education#6264]
**Proposed title of the article**

Implementing Reusable Custom Dialog in Android

**Proposed article introduction**

Dialogs are fairly common in Android. They come in to prompt the apps’ users to make a decision or enter additional information before they can proceed. They might be needed throughout your project. As a result, there's a strong incentive to make them reusable.
In this tutorial, we will understand what custom dialogs are and their importance. We will then dive deep into building them, reusing, handling the button click listener, and solving the conflict of button clicklistner using dialog result code when there is more than one custom dialog in the same activity/fragment.

**Key takeaways**

- understanding what custom dialogs are
- Building a custom dialog
- How to reuse custom dialog throughout a project
- How to hide and show the custom dialog buttons
- Handling button click listener of the custom dialog
- How to resolve a button clicklistener conflict using dialog result code

**Article quality**

This article intends to take the reader through the concept of custom dialog, how to build them and implement them in Kotlin, how to reuse custom dialogs in Kotlin, hiding and showing custom dialog buttons in Kotlin, and handling the clicklistener of the custom dialog button in Kotlin. In this article I will bring out this topic clearly, making it easy for developers of all levels to understand.

**References**

N/A

**Comment by Ericgacoki** [comment]
Hello @NgureWaweru, it seems like **I** already covered most of what you intend to cover in [this article](https://github.com/section-engineering-education/engineering-education/pull/1484). How will yours be different/unique? 🤔

**Comment by Ericgacoki** [comment]
@NgureWaweru
I don't think there's much to explore on custom dialog re-usability as they can easily be inflated in any activity/fragment especially when they are loosely coupled.
@LinusMuema, what do you think about this?

**Comment by LinusMuema** [comment]
Hi @NgureWaweru 
Eric has a good point and the article won't have enough content for the readers. 

Feel free to explore other areas. 

> Tip: more original content always ensures you never have such conflicts whether from section or other articles on the net.
