### ISSUE TITLE
[Machine learning]Build QR Code Scanner User Authentication System in Computer Vision

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#6267]
### Proposal Submission
Building A QR Code Scanner  User Authentication System 
#### Proposed title of article
Build QR Code Scanner User Authentication System in Computer Vision

#### Proposed article introduction
Computer Vision has opened up a plethora of possibilities and one of the simplest and most popular day-to-day applications is the use of QR Codes and Bar Codes Scanners.
Quick Response Code (QR Code) being a matrix type code is popularly used to keep track of items and store data as pixels which correspond to binary codes that can be interpreted to reveal the actual data. With this data can be shared in encrypted form without having to reveal the encoded data explicitly. This acts as an added layer of protection to prevent the misuse of sensitive information.
In this article we will cover as much to equip the reader with the knowledge of the QR Codes, how to scan the codes from an image and how to decode the Codes in Real-Time. With this knowledge of QR codes we will build a user authentication system using the OpenCV library in computer vision that will  checks if a QR Code belongs to authorised personnel and decides whether to grant them access or not

#### Key takeaways 
The reader will be able to:
- Get know to know what QR Codes are and there application in real life.
- Understand how to scan the Code from an Image using OpenCV library.
- Understand how to Decoding QR Codes in Real-Time using camera feed input.
- Understand the implementation of QR Codes in building a user authentication system.
#### Article quality
This article will cover as much not only explaining the concept of QR Codes but also how one can scan and decode the codes. It will also cover QR Code applications in real life and there implementation in building a User Authentication System in Computer Vision.

#### References
N/A

### Templates to use as guides
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @dentonya 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to link a PR. 👍

**Comment by dentonya** [comment]
> Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to link a PR. 👍

hello @hectorkambow  , i already have a PR for this #6765
