### ISSUE TITLE
[Android] Replacing Espresso with Kakao in Writing Automated UI Tests 

### ISSUE THREAD

**Issue by codewithjudy** [section-engineering-education/engineering-education#6268]
#### Proposed article introduction
User Interface (UI) testing ensures that an application meets its functional requirements and achieves the high-quality levels required for it to be successfully adopted by users. One approach to UI testing is to have a human tester perform a set of user actions on the target app and verify that it is behaving correctly. However, this is tiresome, time-consuming, and prone to error. 

Testing user interactions helps ensure users do not encounter unexpected results or have a poor experience when interacting with your app. A more efficient approach is to write your UI tests such that user actions are performed in an automated way.  This automated approach allows you to run your tests quickly and reliably in a repeatable manner.

The Espresso testing framework provides APIs for writing UI tests to simulate user interactions with Views within a single target app. A key benefit of using Espresso is that it provides automatic synchronization of test actions with the UI of the app you are testing.

Even though Espresso is in the writing UI test, the code readability is quite low. When you need to test something more complex than clicking a button, your test code transforms into an unreadable mess.

Kakao provides a fluent way for writing UI tests by abstracting your Activities/Fragments or Views by introducing Screen class. The library makes you enjoy writing automated tests like you are drinking hot chocolate.

Benefits of Kakao :
- Readability.
- Reusability.
- Extensible DSL.

In this tutorial, we will develop a simple Android app and write automated UI tests with Kakao.

#### Key takeaways 
- Get to understand what are automated UI tests.
- Get to know the importance of UI testing.
- Comparisons between Espresso and Kakao.
- Benefits of using Kakao.
- Integrating Kakao into an Android Project and writing tests.

#### Article quality
Not many blogs or sites cover what Kakao is and writing real life scenario tests with it. This article will go the extra mile of giving the reader an insight into what UI testing is and what it entails. I will make the article worthy of any Android developer looking for a good tutorial on automated UI tests with Kakao.

#### References
- [KakaoCup Github](https://github.com/KakaoCup/Kakao)
- [Espresso Docs](https://developer.android.com/training/testing/espresso)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @codewithjudy 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #6268 via #6894
