### ISSUE TITLE
[Android] Creating a Custom TypeConverter to Help in Storing Custom Types in Room Database

### ISSUE THREAD

**Issue by osirevaline** [section-engineering-education/engineering-education#6270]
#### Proposed article introduction
Sometimes, you need your app to store a custom data type such as Date, Bitmap, etc. in a single database column. You support complex types by providing type converters, which are methods that tell Room how to convert complex types to and from known types that Room can persist. You can identify type converters by using the @TypeConverter annotation.

But sometimes this normal  `TypeConverter` isn't enough. Imagine a scenario where you need to store a `List` of Objects e.g Users, Cars, e.t.c. This requires you to come up with a way that you can convert your Data Type to something that `Room` can understand i.e. maybe that `List` of `Objects` to `String`.

In this tutorial, we will create a custom `TypeConverter` and use it in the Room database.

#### Key takeaways 
- What is a TypeConverter?
- What are the complex types in the Room database
- How to create and use a custom TypeConverter in Room database

#### Article quality
This tutorial will help the reader come up with a custom code that he/she doesn't have to write every time when trying to store complex types in database in their Android apps. The tutorial will be short and direct to the point. Most of the blog sites have not covered this topic.

#### References
- N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.
