### ISSUE TITLE
[Blockchain] Understanding layer 2 blockchain

### ISSUE THREAD

**Issue by martha-ngugi** [section-engineering-education/engineering-education#6271]
#### Proposed title of article
Understanding layer 2 blockchain

#### Proposed article introduction
Since the release of Bitcoin, blockchains have continued to grow and gain popularity rapidly over the years. People have used the technology in the wide areas apart from just implementing the payments systems. The reason is that blockchain technology is decentralized and highly secure.
It is evident that no single blockchain technology can provide decentralization, security and scalability in achieving the optimal functionality, most tend to sacrifice dome of the elements. A good example is between the Bitcoin and Etherum which competes in terms of scalability, security and decentralization. In order to gain more popularity solutions like layer 2 protocols have appeared in the recent years.
In the proposed article we will cover in more details what is layer 2 blockchain, how it works and why is it needed in the blockchain network.

#### Key takeaways 
At the end of the article the learner will ne able to understand:
- the concept of layet 2 blockchain
- different layer 2 blockchain solutions currently used in the blockchain network
- the reasons why layer 2 blockchains are implemented in the blockchain ecosystem

#### Article quality
The proposed article provides in-depth knowledge and exploration of the layer 2 blockchain and give examples of where it is currently used, unlike the similar articles online which tend to concentrate more on comparisons between layer 1 and layer 2 blockchains and hence missing out on vital details.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Good topic @martha-ngugi - approved.
