### ISSUE TITLE
Recursive particle tracking in Matlab

### ISSUE THREAD

**Issue by florenceakinyi** [section-engineering-education/engineering-education#6278]
#### Introduction
In particle physics, tracking is reconstructing the trajectory (or track) of electrically charged particles in a particle detector known as a tracker. This method is used in track analysis to determine size distributions and concentrations of nanoparticles in environmental, biological and food samples. Recursive particle tracking is an algorithm based on ellipsoidal differential equations, i.e. a recursive process from a lower to a higher-order interpolation. Each equation is solved as a boundary value problem using the discrete velocity vector information as boundary conditions.

In this tutorial, we will see how to perform the process using Matlab. We will see how to set the threshold, increase that threshold and get the centre mass. We will then loop through all the frames and track the particles in each frame.

#### Key takeaway
- Background theory of tracking.
- What is recursive tracking.
- Matlab code for recursive particle tracking. 

#### Article quality
This article covers into detail recursive particle tracking using Matlab.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Thank you for submitting your topic @florenceakinyi.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
