### ISSUE TITLE
How to produce colors with RGB LEDs using arduino and Matlab graphical user interface

### ISSUE THREAD

**Issue by queenterbruce063** [section-engineering-education/engineering-education#6279]
#### Introduction
Arduino is an open-source hardware and software company, project, and user community that designs and manufactures single-board microcontrollers and microcontroller kits for building digital devices. Arduino board designs use a variety of microprocessors and controllers. The boards are equipped with sets of digital and analogue input/output (I/O) pins that may be interfaced to various expansion boards ('shields') or breadboards (for prototyping) and other circuits.
This tutorial presents a scheme to produce any colour using RGB LEDs controlled by the Arduino Uno board. The Arduino Uno board is interfaced with MATLAB. Also, one can learn how to interface Arduino Uno with Matlab and get an idea of how different colours are produced from three primary colours Red, Green and Blue.
#### Key takeaways 
- Arduino.
- Hardware Support package for arduino in Matlab.
- How to design the GUI using guide in Matlab.
- Matlab code that produces the colors.

#### Article quality
This article shows on how you can program your arduino using Matlab

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Good topic @queenterbruce063 - Approved. Please make sure you don't reference youtube tutorials or any other articles available onine.
