### ISSUE TITLE
A Beginner's Guide to Nonlinear Optimization with Bisection Algorithm

### ISSUE THREAD

**Issue by Daniel695** [section-engineering-education/engineering-education#6280]
#### Proposed article introduction
The Bisection method is one of the simplest and most reliable iterative methods
for the solutions of non-linear equations. This algorithm is mostly used to optimize complicated non-linear Optimization function (cost functions) in deep learning (a sub-field of Machine Learning that uses a neural network to learn from data). Bisection method, also known as Binary chopping or Halfinterval method, relies on the fact that if f(x) is real and continuous in the interval a<x<b, and f(a) and f(b) are of opposite signs, such that,
 f(a)*f(b)<0, then there exist at least one real root between a and b. This means there may be more than one root within this interval. Given the initial interval that contains the root, the Bisection Method works this way:

1. First, partition the initial interval [a,b] into two sub-intervals [a,x_0] and [x_0,b] where x_0 is the midpoint of the initial interval. This is done using the formula:
x_0 = (a+b)/2

2. Evaluate the function f(x) at x_0.

We then consider three cases in determining the root or the new interval containing the root we are looking for.

1. If f(x_0)=0, then x_0 is the required root.

2. If f(x_0) is less than or equal to zero, i.e., is negative, then f(x_0) and f(b) have opposite signs. Therefore, the new interval will be [x_0,b].

3. If f(x_0).0, then the opposite signs for the most closes x points is between f(a) and f(x_0). Therefore, the new interval containing the root is [a,x_0].

Now;
- If case one occurs, the bisection process is terminated since the root has been found.
- If either case $(2)$ or $(3)$ occurs, the process is repeated until the root is obtained to the desired tolerance.

In this article we will look exact how this algorithm work, solve some optimization function using this it, state it's advantages and disadvantages and later learn how it is implemented in python.

#### Key takeaways 
By the end of the session, the learner is expected to, comfortably, be able to:
- Theoretically, explain how the Bisection method works.
- Explain what Zeros of a polynomial function are.
- Perform the Bisection Method by hand. We will come out of the theoretical world and work on a real-world example in this session.
- Determine the number of iterations required to obtain the root of a polynomial function prior to performing the Bisection Method.
- Outline the main shortcomings of the Bisection method and have an idea of the related algorithms that address these problems.
- Implement the Bisection method using the Scipy library in Python.

#### Article quality:
Most of the tutorials online focus a lot on the theory behind the Bisection method, and in comparison, less effort is put into the implementation. The articles that implement this algorithm are usually very shallow on the intuition making the beginner very unfriendly with the content. This article will provide complete content where the learner can learn the theory behind the Bisection algorithm and at the same time implement what they have learned.

Since it will be a two in one article, we will try as much as possible to be straight to the point but without sacrificing the quality of the content. So, the simplification of the content and in-depth coverage of the topic are two elements that will grant this article a uniqueness among all other articles already in place on the same topic. Furthermore, the clarity of the implementation session, i.e., highly explained code snippets, will add value to this article.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Nice topic @Daniel695 - Approved.
