### ISSUE TITLE
How to Integrate Ruby on Rails with React to Create Responsive Apps

### ISSUE THREAD

**Issue by kymomolly** [section-engineering-education/engineering-education#6283]
#### Proposed title of article
How to Integrate Ruby on Rails with React to Create Responsive Apps
#### Proposed article introduction
 In this article, will discuss the  two most frequent techniques to integrate ReactJS and Ruby on Rails in this article. You will be able to construct functional, seamless apps using this combination of technologies. The advantages of the React and Rails backends will be realized, namely their speed, dependability, lightweight, and limitless documentation. Most importantly, these technologies will increase the efficiency of your workforce.
ReactJS and Ruby on Rails make a great framework combination since both of them are widely known in web development
#### Article quality
This article is unique in that it offers good description of how to integrate ruby on rails .with the inclusion of React. The learners will get familiarized with the use of react and how it will help them in setting up their application.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Thank you for submitting your topic @kymomolly.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
