### ISSUE TITLE
Implementing Fingerprint Authentication in Flutter Applications

### ISSUE THREAD

**Issue by ianmasae** [section-engineering-education/engineering-education#6284]
#### Proposed title of article
Implementing Fingerprint Authentication in Flutter Applications

#### Proposed article introduction
Fingerprint authorization refers to using fingerprint biometrics to authenticate a user into a system. Fingerprint authentication automatically compares a user's fingerprint to a stored fingerprint template stored in the device to validate a user's identity.
Biometric authentication provides safety because the biometrics are non-transferable, meaning they cannot be used by anyone else. This form of authentication requires less database memory and small storage space, hence, advantageous for large-scale applications.
This article will go through the implementation of fingerprint authentication in a Flutter application.

#### Key takeaways 
The readers will:
- Understand what biometrics are and their application in today's world
- Understand how fingerprint authentication works in mobile applications
- Understand how to implement finger authentication in mobile applications using Flutter

#### Article quality
This article covers in broadness about fingerprint biometrics authentication for every reader to comprehend this subject. At the end of the article, the readers will be able to apply the knowledge they receive to their Flutter applications.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Cool topic @ianmasae - Approved.
