### ISSUE TITLE
Working with java inner classes

### ISSUE THREAD

**Issue by Wainich21** [section-engineering-education/engineering-education#6287]
#### Proposed title of article
[Languages] Working with java inner classes

#### Proposed article introduction
To put it simply, an inner class is a class that is defined inside a class or interface, which was primarily established to bring java closer to the real world since it is object-oriented. In java, an inner class refers to a class that is a member of another class, or a subclass of that class. A variety of inner classes exist in java.
We employ inner classes to organize classes and interfaces together to make it easier to understand and manage. All members of the outer class may be accessed, including private data and methods.

#### Key takeaways 
- What are inner classes in java, and what necessitates their  use
- What are some of the inner class types
- Various merits with inner classes
- Inner classes vs. nested classes
 
#### Article quality
The article will be in-depth based on the coverage. The article will encompass in-depth coverage of the methods of inner classes: nested inner class, method local inner classes, static nested classes, and anonymous inner classes, including their illustrations. The article will be easy and interesting to read. The article will be beginner-friendly and interesting.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations 

https://www.google.com/search?q=Working+with+java+inner+classes&oq=Working+with+java+inner+classes&aqs=chrome..69i57j69i61.242j0j9&sourceid=chrome&ie=UTF-8
