### ISSUE TITLE
cleanroom software development

### ISSUE THREAD

**Issue by edwinmain** [section-engineering-education/engineering-education#6288]
####Proposed title of article.
Cleanroom software development.
####Proposed article Introduction.
Cleanroom software development.
####Key takeaways.
  -Static verification in the development process.
  -The cleanroom approach to software development.
  -Techniques relied by cleanroom software development.
####Article quality.
Replacement of unit testing system components by inspections to check the consistency of the components with their specification ,cleanroom development  is relevant to this article.
####References.
N/A

**Comment by lalith1403** [comment]
This has no content. Kindly check.

**Comment by WanjaMIKE** [comment]
It seems you have another open topic. We only accept one at the moment.
