### ISSUE TITLE
How to Build a Nestjs MVC Application with MongoDB

### ISSUE THREAD

**Issue by Claradev32** [section-engineering-education/engineering-education#6293]
### Topic Suggestion
How to Build a Nestjs MVC Application with MongoDB

### Proposal Submission
In this tutorial, the reader will learn how to build and structure a NestJS MVC application by building a demo project with MongoDB. They will learn how to set up a Nestjs application, setup and connect a MongoDB database, configure routing in Nestjs, and implement user authentication and authorization. 

#### Proposed title of article
How to Build a Nestjs MVC Application with MongoDB

#### Proposed article introduction
NestJS is a NodeJS framework for building efficient, scalable server-side applications. It uses progressive JavaScript and is built with and fully supports TypeScript. It combines Object-Oriented Programming, Functional Programming, and Functional Reactive Programming.
MVC is a software design pattern commonly used for developing web applications that divides the application logic into three interconnected elements: Model, View, and Controller.
Each of these elements is built to handle specific development aspects of an application. MVC is one of the most frequently used industry-standard web development frameworks to create scalable and extensible projects.
By default, Nestjs uses the Express Library under the hood, which makes all the software development patterns used in Express available in Nest.
In this tutorial, we'll build a NestJS web application using the Express MVC pattern. Hang tight.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.
At the end of this tutorial the reader will be able to:
- Create a NestJS MVC application
- Configure and connect their MongDB database to their Nest project.
- Implement User Authentication and Authorization

#### Article quality
The code snippets for this tutorial will be written using software development best practices. The tutorial will be based on my experience building with Nestjs over the last two years.No part of this tutorial will be copied from any tutorial on Youtube or blogs.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Thank you for submitting your topic @Claradev32.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
