### ISSUE TITLE
How to Build a Discord Bot that gives Workout Tips 

### ISSUE THREAD

**Issue by khabdrick** [section-engineering-education/engineering-education#6298]
### Writing sample(s): 
https://www.section.io/engineering-education/dockerized-django-application-with-github-actions/
#### Proposed title of article
How to Build a Discord bot that gives Workout Tips 

#### Proposed article introduction
The Discord Bot the reader will be building will send fitness tips to people on the Discord server when a particular message is sent. It will be built with Python. Members of the server can create, delete and view a list of workout tips. 

I will show how to build CRUD functionalities on the bot, and also use Flask to make the bot run independently.

ONLY viable topics to pick from:

- Languages

#### Key takeaways 
- The Discord Bot the reader will be building will send fitness tips to people on the Discord server when a particular message is sent. 
- Members of the server can create, delete and view a list of workout tips. 
- The reader will learn how to use Flask to make the Discord bot run independently.

#### Article quality
My article is unique

**Comment by WanjaMIKE** [comment]
This article -> https://github.com/section-engineering-education/engineering-education/pull/2744 already discusses how to create a discord not in Python. Feel free to suggest an alternative topic.
