### ISSUE TITLE
Bill split and Tip app in JavaScript

### ISSUE THREAD

**Issue by GacheruJr** [section-engineering-education/engineering-education#6300]
### Topic Suggestion
[languages]Bill split web app in javascript

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
[Languages]building a simple bill split web app in javascript

Use keyword research to improve your article's SEO.

#### Proposed article introduction

in this article,we are going to build a simple split bill working web app,
I will be using HTML for building sections,CSS for styling and javascript for the responsive and functionality part

#### Key takeaways 
-grasp knowledge of some few HTML tags 
-the reader will be able to understand how javascript works
-reader will gain some knowledge in CSS

#### Article quality
this article is helpful for those starting their journey in javascript

#### References
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations 

https://www.google.com/search?q=Bill+split+and+Tip+app+in+JavaScript&oq=Bill+split+and+Tip+app+in+JavaScript&aqs=chrome..69i57j69i61.481j0j9&sourceid=chrome&ie=UTF-8

**Comment by GacheruJr** [comment]
ok
