### ISSUE TITLE
Managing State in React Applications Using Easy Peasy

### ISSUE THREAD

**Issue by KayveTech** [section-engineering-education/engineering-education#6301]
#### Proposed article introduction
State management is important in React applications as it enables the developer to have a global store containing state that can be modified and accessed from any component. This helps to reduce passing props from one component to another which is tedious. In this article, we will take a look at how we can manage state in our applications using `Easy Peasy`.

`Easy Peasy` is defined as an abstraction of Redux that provides a reimagined API that focuses on developer experience. It allows a developer to quickly and easily manage state, whilst leveraging the strong architectural guarantees and extensive eco-system that Redux has to offer. To demonstrate this, we will create a task tracker application. The application will be styled using `Tailwind CSS`.

#### Key takeaways 
After reading this article, the reader should be able to:
- Understand the concept of state management.
- Manage state in React applications using Easy Peasy.
- Style a React application using Tailwind CSS.

#### Article quality
After going through some articles that have been published on this topic, I realized that they jump right into the code without explaining the essence of state management to the reader and all of them use functional components.

This article will be beginner-friendly as it will explain the concept of state management and why it is important. We will also use `React class components` (this approach has not been covered in the other articles) which familiarize the reader with `React lifecycle methods`.

We will also cover how we can use `thunks` to make asynchronous requests to external APIs.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by Kayere** [comment]
Thank you for submitting your topic @KayveTech.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.

**Comment by KayveTech** [comment]
@Kayere @louisefindlay23 
Please take a look at the `Article quality` section. Yes, the topic has been published on other blog sites but my approach is very different. Please take a look at it.

**Comment by KayveTech** [comment]
@Kayere :eyes:
