### ISSUE TITLE
[Machine Learning] Machine Learning using EvalMl Library

### ISSUE THREAD

**Issue by kelvinkimani501** [section-engineering-education/engineering-education#6306]
#### Proposed title of article
[Machine Learning] Machine Learning using EvalMl Library

#### Proposed article introduction
EvalML is an open-source AutoML library written in python that automates a large part of the machine learning process and we can easily evaluate which machine learning pipeline works better for the given set of data. It builds and optimizes ML pipelines using specific objective functions.

EvalML can be used to create end-to-end supervised machine learning solutions which are more efficient. EvalMl is used to determine the best-optimized machine learning algorithm in building the model.

By using the best algorithm, the model will have also the best performance and be able to make accurate predictions. This library also automates the processes of Feature Engineering, Feature Selection, Model Creation, And Tuning. This saves time and simplifies the machine learning development process. Some of the key functionalities of EvalMl are:

- Automation, Data Checks, End-to-end processing, Model Understanding, and Domain-specific modeling.

#### Key takeaways 
1. What is EvalMl.
2. Key functionalities of using EvalMl in model building.
3. Installing EvalMl.
4. Using AutoML to select the best algorithm.
5. Getting The Best Pipeline to produce an optimized model.

#### Article quality
This article is unique because it explores EvalMl in detail. We will first explore the key functions and methods that EvalMl uses to automate the machine learning process. After this, we will use these functions and methods to build a custom model. We will then use EvalMl to select the best algorithm and get the best pipeline. This will provide a more accurate model, this tutorial will be beginner-friendly and the reader can easily follow the guided steps.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Thank you for submitting your topic @kelvinkimani501.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
