### ISSUE TITLE
Best URL Structure To Improve SEO

### ISSUE THREAD

**Issue by selina-maina** [section-engineering-education/engineering-education#6307]
### Topic Suggestion
Best URL Structure To Improve SEO

### Writing sample(s): 
N/A
#### Proposed title of article
Best URL Structure To Improve SEO

#### Proposed article introduction
Performance is a standard consideration when developing a website. Developers take into account numerous undertakings to ensure their creation perform in an optimized manner. Good SEO practices can increase the popularity of a  website let alone its monetization ability. Additionally, better SEO tactics ensure that a site ranks on the top list of the popular search engines such as Google and Bing. Among the methods of conforming to most practiced SEO techniques is through URL structure optimization.

#### Key takeaways 
In this article you will learn about:
- What is URL structuring. 
- Importance of improving your URL struture.
- Tips on optimizing your next URL.
#### Article quality
The article will feature a deeper dive into the art of URL structuring. Other articles on the web feature a shallow coverage of the topic while this article seeks to hold the reader into the different way they can optimize their next URLs.

#### References
N/A

**Comment by Kayere** [comment]
Good topic @selina-maina - Approved. Please make sure your article is unique and adds value to what is available online.
