### ISSUE TITLE
[Android]Getting Started with Paper Database

### ISSUE THREAD

**Issue by brandy-kay** [section-engineering-education/engineering-education#6311]
#### Proposed article introduction
PaperDB is a NoSQL-like store for Java/Kotlin objects on Android that supports automatic schema migration. The goal of PaperDB is to provide an easy-to-use yet fast object storage solution for Android. It allows users to use Java/Kotlin classes without any annotations, factory methods, or required class extensions. Adding or removing fields from data classes is also no longer a chore because all data structure changes are handled automatically.

#### Key takeaways 
- What is paper database as used in android
- What are the feature of paper database that makes it different from other android databases
- The merits and demerits of paper database
- How to implement paper database in android

#### Article quality
This article explains what is paper database in detail , what makes it difference from other android storage like SQLite and how it is used in android. it also aims to explain the content in beginner friendly manner

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @brandy-kay 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #6311 via #7420
