### ISSUE TITLE
[Blockchain] - Understanding blockchains interoperability via cosmos network

### ISSUE THREAD

**Issue by lewe01** [section-engineering-education/engineering-education#6312]
#### Proposed title of article
Understanding blockchains interoperability via cosmos network

#### Proposed article introduction
The adoption of crypto is still facing challenges and is still low in numbers compared to the global users of the internet. The main reason for this slow adoption is that blockchains have no interoperability between each other. There have been several approaches devised to ensure the cross-chain interactions between the blockchains, however, most only operate between two blockchains.

The current interoperability techniques seem not to make much impact on network efficiency, upgradability and also sustainability. In an attempt to address these issues, cosmos networks have been developed. In this proposed article we will look at the cosmos network in detail and how it helps to achieve cross-chain communication between blockchains.
 
#### Key takeaways 
At the end of the article the reader will understand:
- what is meant by cosmos network and how it works
- explain the three pillars of cosmos economy
- outline the projects built on cosmos network

#### Article quality
The proposed article is helpful to the readers since it gives insightful ways cosmos networks can ensure interoperability between the blockchains with real-life examples of the projects that are already utilizing it.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Great topic - Approved. @
