### ISSUE TITLE
How to Build RESTful APIs With Typescript Without Any Frameworks From Scratch(only using the native modules)

### ISSUE THREAD

**Issue by Rose-stack** [section-engineering-education/engineering-education#6313]
### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 

https://www.section.io/engineering-education/authors/rose-waitherero/

#### Proposed title of article

How to Build RESTful APIs With Typescript Without Any Frameworks From Scratch(only using the native modules)

#### Proposed article introduction

In most cases, when building APIs with languages such as Typescript, developers use open-source libraries and frameworks such as Express.js, CORS, etc. These libraries are readily available in the NPM registry.

Whenever you use such packages, there is a lot of abstraction as you don't utilize the core functionalities of Typescript code. Your application's low-level logic Typescript code is hidden from you as these packages process and execute vanilla Typescript behind the scenes of your application. This guide will help the reader build RESTful APIs With Typescript Without Any Frameworks From Scratch(only using the native modules).

#### Key takeaways 

- Set up Typescript
- Setting up a simple Typescript HTTP server
- Setting up a CRUD Typescript REST API
- Setting up the API controllers
- Adding the API routes using Typescript 
- Fetch task
- Add a new task
- Update a task
- Delete a task
- Testing the API

#### Article quality

This guide will help the reader build an HTTP API server that runs Typescript at its core. This will help to understand the bare bone of vanilla Typescript. In this case, we will not use any frameworks such as express and cors. We will use native and core modules that leverage the vanilla Typescript.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
We already have some articles covering this topic. For example:
- https://www.section.io/engineering-education/how-to-create-a-simple-rest-api-using-typescript-and-nodejs/
- https://www.section.io/engineering-education/a-raw-nodejs-rest-api-without-frameworks-such-as-express/

Please feel free to suggest another topic. @Rose-stack

**Comment by ahmadmardeni1** [comment]
The student explained on Slack that she wants to use raw TS, therefore, making this article unique.

Approved. @Rose-stack
