### ISSUE TITLE
[Machine Learning] - Using python to understand machine learning concepts

### ISSUE THREAD

**Issue by ephraa** [section-engineering-education/engineering-education#6315]
#### Proposed title of article
Using python to understand machine learning concepts

#### Proposed article introduction
Machine Learning is part of Artificial Intelligence involved in studying the computational algorithms and statistical models to perform tasks using patterns and interference. A typical computer will take in data, then the algorithm analyzes the data and learns from it to deduce predictions from it.
Machine Learning contains a set of tools that are used to build models on data that can predict other new types of the same data. However, machine learning models are not 100% accurate as they rely on predictions based on the data provided.
In this article, we look at how python can be used in machine learning models to perform operations and gives out results.

#### Key takeaways 
At the end of the article the learner will understand:
- how the grouping of data into features and targets is performed
- the various machine learning algorithms operations
- the machine learning workflow
- the ways of evaluating the model's performance

#### Article quality
The article equips the learner with extensive details on how machine learning concepts can be implemented using python. The knowledge gained can be used to implement a machine learning model in a given project.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @ephraa 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
