### ISSUE TITLE
Approximating the Speed of an Object and its Distance using OpenCV in Python

### ISSUE THREAD

**Issue by GeekEdmund** [section-engineering-education/engineering-education#6316]
#### Proposed title of article
Approximating the Speed of an Object and its Distance using OpenCV in Python

#### Proposed article introduction
Computers are essential in today's technological age. They can make our lives easier by making other integratable tasks easier to perform such as speed and distance approximation.
We are going to see how to calculate the distance with a webcam using OpenCV in Python. Measure the distance from the object(face) to the camera, capture a Reference image and note down the measured distance using the Distance finder function. 
Likewise, finding the velocity of the object, since speed is the relation of distance with respect to the given time, using coherent functions.
In this tutorial, We will require python packages such as numpy, cv2, mediapipe, math, ctypes, time, and among others to work with and well-explained details on their usage. 

#### Key takeaways 

1. Using OpenCV to find the distance of an object.
2. Finding the velocity or speed of the object.
3. Integration of the distance with respect to speed for simultaneous output.

#### Article quality
Unlike other articles, the code will be well explained and not just copy-pasted. But designed in an eccentric way for easier understanding and consumption. Deeply emphasizing the importance and use of packages.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @GeekEdmund 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
