### ISSUE TITLE
Building a Time Scheduled communication micro-service using Node.js

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#6318]
#### Proposed title of article
Building a Time Scheduled communication micro-service using Node.js.

#### Proposed article introduction
A time scheduled communication micro-service is a minimalistic service that sends messages to users of a particular platform based on scheduled time intervals. For example, a service can be sending an SMS to its users after every five minutes notifying them of a process that is running in the background.

In this article, we will build a service that will be sending SMSes to different parties based on the time intervals entered by the user.

#### Key takeaways 
- How to setup a Node.js micro-service.
- How to handle sending SMSes in Node.js using Twilio API.
- How to schedule tasks to run at different intervals using node-cron package.

#### Article quality
 - The article will be in-depth.
 - The article will address any other related topic in line to building a micro-service using Node.js.
 - The article will be beginner friendly.

#### References
- https://www.twilio.com/docs/sms/quickstart/node
- https://www.digitalocean.com/community/tutorials/nodejs-cron-jobs-by-examples

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @mwangiKibui 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to link a PR. 👍
