### ISSUE TITLE
Integrating Firebase With PHP

### ISSUE THREAD

**Issue by denismwangi** [section-engineering-education/engineering-education#6323]
#### Proposed title of article
[API]Integrating Firebase With PHP

#### Proposed article introduction
Firebase is a real-time service that allows chat, mobile, and applications to exchange data in real-time. Firebase also provides storage, authentication, cloud messaging, notifications, hosting, and other real-time services. This makes its platform a complete and comprehensive set of tools for building high-quality applications.
 Firebase gives developers access to an API that allows them to synchronize application data with the data on the Firebase cloud. In this article, we cover the Firebase database and how Firebase provides real-time backend services.

#### Key takeaways 
What is Firebase.
What is Firebase used for.
How to create a project in Firebase.
Connecting web application with Firebase.
Fetching, inserting, editing, and deleting data from Firebase.

#### Article quality
This article intends to take the reader through all the concepts of Firebase data store in-depth, how to implement Firebase SDK, and how to reuse classes in PHP. In this article I will bring out this topic clearly, making it easy for developers of all levels to understand.

#### References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @denismwangi.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
