### ISSUE TITLE
How to Create a Next.js Blog App using Typescript and the Notion as the Database API

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#6326]
#### Proposed title of the article

How to Create a Next.js Blog App using Typescript and the Notion as the Database API

#### Proposed article introduction

Next.js has been used to create Server-side Rendering" (SSR) and "Static Site Generation" (SSG) apps using JavaScript. This means the app fetches extra data from the server after the browser loads the website's HTML page. Technologies such as SSG often have to rebuild the app when data from the source is updated and render it to the user at build time—making the site load even faster. Hence good user experiences.

In this guide will learn how we can use Next.js with Notion API and create a blog app powered by Typescript code.

#### Key takeaways 

- Introduction to Next.js
- Why Next.js?
- What is the Notion API?
- Why run Next.js With Notion API
- Advantages of using the Next.js Typescript code
- Setup Next.js project with Typescript
- Configure a database with Notion API
- Test the Notion API
- Integrating Notion with Next.js
- Modifying the API calls with Next.js
- Fetching post data from Notion API
- Deploy app on Vercel 

#### Article quality

I found this [article](https://dev.to/solomon04/build-a-blog-powered-by-nextjs-notion-api-57pj) explaining how to build a Notion Next.js App. However, in this guide, the reader will learn:

- The what and why of Next.js
- The Advantages of running Next.js Typescript code
- A good explanation and discussion of what Notion API is
- Be able to set up and configure the Notion API database

Once the reader is familiar with the above., the article will then deeply explain a step by step.

- How you can configure the Notion API with Next.js
- For a deeper understanding, will demonstrate how we can build a blog app from scratch using these technologies

**Comment by kimkimani** [comment]
Hello @WanjaMIKE, I was asking if I can reopen this issue

**Comment by ahmadmardeni1** [comment]
Great topic - Approved. @kimkimani
