### ISSUE TITLE
Working with AdMob Interstitial Google Ads in the Android application - Kotlin

### ISSUE THREAD

**Issue by kipsd254** [section-engineering-education/engineering-education#6328]
### Topic Suggestion
Working with AdMob Interstitial Google Ads in the Android application - Kotlin

#### Proposed article introduction
Every developer has reasons as to why they always develop new applications. Many of them may create an app that does not generate a profit in comparison to the amount they spent. In addition, the developer may develop an interest in collaborating with other organizations through advertising their products and services, maybe with a fee. This can only be integrated using AdMob Interstitial Google Ads to achieve the objective by adding the ad to the application. When the user is surfing through the application on the internet, the ad will pop up in the application and the interested party may get more information about the advert.

This tutorial will be an in-depth guide to what is AdMob Interstitial ads and how you can integrate them into an android app using Kotlin language.

#### Key takeaways 
1. Walkthrough to AdMob Interstitial Google Ads.
2. Setting up the Android Studio.
3. Adding the relevant dependencies of the project.
4. Designing the user interface.
5. Writing the Kotlin code.
6. Testing the application.
7. Conclusion.

#### Article quality
The article will be beginner-friendly by using precise explanations and simple code syntax that will make developers build interest to add ads in the daily applications they develop and monetize from them. 

#### References
N/A

**Comment by Kayere** [comment]
Good topic @davigin - Approved.

**Comment by WanjaMIKE** [comment]
closed #6328 via #7018
