### ISSUE TITLE
Working with multiple linear regression in python

### ISSUE THREAD

**Issue by Wainich21** [section-engineering-education/engineering-education#6333]
#### Proposed title of article
[Machine Learning] Working with multiple linear regression in python

#### Proposed article introduction
Linear regression is used to predict. It is a statistical approach for modeling the connection between two variables. Multiple linear regression requires more than one predictor variable to predict the answer. One continuous dependent variable and numerous independent variables are modeled here. It signifies a dependent variable by utilizing two or more factors.

#### Key takeaways 
By the end of this article, the reader will be able to understand
- What is linear regression and the various types
- What is multiple linear regression, and the reason we need it
- Merits and demerits of working with multiple linear regression
- Some of the considerations before building a multiple linear regression model
- How to build a multiple linear regression model including the various methods of building models

#### Article quality
This article will be in-depth and beginner-friendly. I will expound more on the steps involved in any multiple linear regression model. Relevant examples and screenshots will be provided. The learner will also understand what dummy variables are.

#### References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @Wainich21.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
