### ISSUE TITLE
SSH Tunneling

### ISSUE THREAD

**Issue by Joesongoma** [section-engineering-education/engineering-education#6335]
### Topic Suggestion
SSH Tunneling

### Writing sample(s): 
https://www.section.io/engineering-education/authors/joseph-ongoma/

#### Proposed article introduction
SSH tunneling, also known as SSH port forwarding, is a technique for sending arbitrary data over an encoded SSH connection. SSH tunnels enable connections to a local port (i.e., a port on your own desktop) to be transferred to a remote computer across a secure channel.

To ensure the security of our network services, not all of them are directly accessible from outside the ENCS network. If you are offsite and need to access a protected resource, you can use SSH to tunnel through an accessible resource to reach the protected resource.

In this article, we will look at two main subtopics in SSH tunneling:
- Remote port forwarding 
- Local port forwarding

#### Key takeaways 
After reading this article, the reader will be able to understand the concept of:
- remote port forwarding
- local port forwarding
- SSH tunneling

#### Article quality
This article is meant to give the reader an in-depth knowledge of SSH tunneling and show the reader how to perform remote and local port forwarding on a secure network. 

#### References
N/A

**Comment by Kayere** [comment]
Good topic @Joesongoma - Approved. Please make sure your article is unique and adds value to what is available online.
