### ISSUE TITLE
C# Data Encapsulation

### ISSUE THREAD

**Issue by Mercycar** [section-engineering-education/engineering-education#6336]
### Topic Suggestion
C# Data Encapsulation

### Writing sample(s): 
https://www.section.io/engineering-education/authors/daniel-masika/

#### Proposed article introduction
Encapsulation is the bundling up of data into a single unit. It's the glue that holds code and the data it manipulates together. Encapsulation can also be thought of as a protective shield that prevents data from being accessible by code outside of the shield.

Encapsulation is a procedure in which data members and member functions are bound together in a single unit in C#. Because it will incorporate diverse sorts of data members and member functions into a single unit, the class is the real-time example of encapsulation in c#.

In this article tutorial we will be looking at Encapsulation in  Object Oriented Programming C#. We will learn what encapsulation is in object oriented programming. We will also learn how encapsulation enhance information hiding in C#. We will also look at real time example of data encapsulation in C#. 

I will implement this concept in code using Microsoft Visual Studio to understand clearly how encapsulation is implemented in C#.

#### Key takeaways 
From this article, the reader will understand the concept of:
- Encapsulation
- Real time scenarios of data encapsulation
- How to implement data encapsulation in C#

#### Article quality
This article intends to take the reader through the concept of encapsulation and at the same time looking at the real life scenarios of where data encapsulation is applied and how to implement this scenario in code using C#.

#### References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @Mercycar.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
