### ISSUE TITLE
Creating a scanning Barcode using C# Windows Application

### ISSUE THREAD

**Issue by RayBrian269** [section-engineering-education/engineering-education#6338]
Introduction.
This is an application that can be used to gather product information, by scanning a striped code, in most cases these codes are usually located on the back of the product. The information, one gathers from scanning a product depends on the available information in the local database of the service used. It is a very vital application because it gives a person certain information about the product.
Key takeaways
•	Using C# to create a barcode scanner
•	How to get product information using a barcode scanner
•	Interpreting barcode symbols
•	Detecting QR code

Article quality
This article will be easy to follow for those aspiring to use C# for application development. I believe knowledge can never be exhausted and this article will be novice to be clear even to C#  beginners.

References
N/A.

### Templates to use as guides
-

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=Creating+a+scanning+Barcode+using+C%23+Windows+Application&oq=Creating+a+scanning+Barcode+using+C%23+Windows+Application&aqs=chrome..69i57j69i61j69i60l2.392j0j4&sourceid=chrome&ie=UTF-8), the topic appear to be over saturated on other blog sites and internet sources. Feel free to suggest another topic. Thanks
