### ISSUE TITLE
[Machine Learning]: Understanding COCO datasets

### ISSUE THREAD

**Issue by srishilesh** [section-engineering-education/engineering-education#6339]
### Topic Suggestion
Machine Learning

### Writing sample(s): 
https://www.section.io/engineering-education/authors/srishilesh-p-s/

#### Proposed title of article
Understanding COCO datasets

#### Proposed article introduction
Object detection refers to the capability of computer systems to locate desired objects in an image/scene and identify each object. For detection of objects, the training data are either represented using XML files or JSON files. Each representation has it's pros and cons.

In this article, we will be looking at what COCO is, understand the history behind it, how it helps with object detection, which meta-data helps solving detection and segmentation problems, and finally understand how to validate such datasets.

#### Key takeaways 
- The reader will get an insight of what COCO is.
- The reader will understand the history behind COCO representation
- The reader will understand how exactly is it used for object detection and other segmentation problems.
- The reader will learn to validate the dataset using Python

#### Article quality
This article would deal with explaining explaining, comparing and contrasting the different representation of datasets that we use for detection and segmentation problems. The reader will understand how these representations makes it easier for annotation.

#### References
- https://cocodataset.org

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
