### ISSUE TITLE
How to use the FlutterFire CLI to integrate Firebase into a Flutter app

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#6341]
### Topic Suggestion
How to use the FlutterFire CLI to integrate Firebase into a Flutter app
#### Proposed article introduction
There were a number of platform-specific, manual procedures involved in configuring Firebase for Flutter apps. Firebase may now be initialized directly from Dart thanks to Flutter 2.8. Using the new FlutterFire CLI tool, which generates the right Firebase setup for our project, we can now do this.

I will write this guide to help set up the CLI and get it running.

#### Key takeaways 
1. Installing the Firebase and FlutterFire CLI
2. Creating a new Flutter app
3. Creating a new Firebase project
4. Adding the Firebase project with the FlutterFire CLI
5. Initializing Firebase in the Flutter app
#### Article quality
1. In Section, we do not have any articles related to How to use the FlutterFire CLI to integrate Firebase into a Flutter app.
2. Although, we have a few articles discussing 1 or 2 on How to use the FlutterFire CLI to integrate Firebase into a Flutter app, we don't have a common article that creates both a new flutter app and a new firebase project.
3. Because the [documentation](https://firebase.flutter.dev/docs/cli/) for the FlutterFire CLI is very limited, I will write this guide to help set up the CLI and get it running.
4. As a bonus, I'll show how to set up a Flutter app with different Firebase environments.
5. The code snippets that I will provide will be easier to grasp.
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Unfortunately, this topic appears to be over saturated on other blog sites and official documentation such as https://firebase.flutter.dev/docs/cli/ Feel free to suggest another topic. Thanks
