### ISSUE TITLE
Active Record in Ruby 

### ISSUE THREAD

**Issue by ianmaish** [section-engineering-education/engineering-education#6345]
Topic Suggestion

Active Record in Ruby 

Proposed article introduction

Active Record is the base class for all models in Rails. ORM stands for Object Relational Mapping, and Active Record is an ORM. It enables us to represent database data as Ruby objects, which can subsequently be readily shown and modified. For database access, each Active Record object has the Create, Read, Update, and Delete methods (CRUD). Easy designs and direct mappings between database tables and application objects are possible with the methods.
Active Records in Rails provide a connection and interface between relational database tables and Ruby source code that tries to control database records. The names of Ruby methods are derived directly from the names of the fields in a table.

 Key takeaways 

•	Understand heredocs and use them in ruby code 
•	Learn what are migrations and make migrations 
•	Validation and constraints 
•	Know how to index columns for query optimization 

 Article quality

The article is very unique since I employ the use of code snippets to demonstrate different examples and different applications of topics discussed. The article is easy to read and understand hence it is beginner-friendly. The code snippets are commented on to help the reader understand each step. 

 References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
I think this topic suggestion is quite similar to the official documentation such as https://guides.rubyonrails.org/active_record_basics.html We focus more on unique projects. Feel free to suggest another topic. Thanks
