### ISSUE TITLE
Build a Palindrome Checker using Vanilla Javascript.

### ISSUE THREAD

**Issue by abimbolataofeek** [section-engineering-education/engineering-education#6346]
#### Pre-submission advice

Building a palindrome checker app with pure vanilla Javascript from scratch is really a great project to get started and improve your javascript as well as your Html, CSS skill as a beginner. In my opinion, I advise building similar projects like this first with pure vanilla JavaScript before some learning javascript frameworks cause this will really help to solidify your javaScript skill. 

A palindrome is a word that spells the same either forwards or backward e.g noon, madam. So basically our app is going to take an input then check if the input is a palindrome word or not.

In this article, you will be taken through the various HTML and CSS elements along with vanilla JavaScript.

#### Article quality
This tutorial is totally beginner-friendly, I will be building a palindrome checker web app from scratch using HTML, CSS, and Javascript ES6 and this will really improve your CSS and javascript skills.

#### Key takeaways

At the end of this tutorial the reader should be able to:

1. Improve JavaScript Skill
2. Improve CSS Skill 
3. Understand Javascript Dom and Event
4. Learn JavaScript ES6

#### References:
https://www.w3schools.com/utors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
This topic appears to be over-saturated on other blog sites such as https://javascript.plainenglish.io/build-a-palindrome-checker-in-vanilla-javascript-3470304100a5 We focus more on unique projects. Feel free to suggest another topic. Thanks
