### ISSUE TITLE
[Cloud Computing] Understanding cloud-based data architectures

### ISSUE THREAD

**Issue by verah-tech** [section-engineering-education/engineering-education#6349]
#### Proposed title of article
Understanding cloud-based data architectures

#### Proposed article introduction
Most global enterprises are relying heavily on big data, which assist in uncovering hidden patterns. For this reason, organizations and businesses are switching to new data technologies in order to remain competitive in the market.
However, businesses operating with legacy infrastructure are finding it difficult to utilize these new technologies. This is the main reason that is making businesses migrate to cloud-based technologies.
Nowadays, cloud computing is generating billions of US dollars to businesses in revenue meaning that cloud data architecture is very important to the digital economy as it provides speed and agility and also quick access of data as well as data unification. 
In this proposed article, we will cover in detail the cloud-based data architectures and how businesses can utilize them to maximise their returns.

#### Key takeaways 
At the end of the article, the learner will be able to understand:
- the concept of cloud data architectures.
- the core components of cloud computing.
- the factors considered when building a stable cloud data architecture.

#### Article quality
The proposed article will expound on cloud data architectures, highlighting the cloud computing architectures in relation to the data. The businesses can then utilize the information provided to build their stable data architecture that is cloud-based.

#### References
n/a

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic.
