### ISSUE TITLE
How Robotic Data Automation is Accelerating AIOps Implementations

### ISSUE THREAD

**Issue by jesmweni** [section-engineering-education/engineering-education#6352]
#### Proposed article introduction
Robotic Data Automation (RDA) is a new paradigm to help automate data integration and data preparation activities involved in dealing with machine data for Analytics and AI/Machine Learning applications. RDA is not just a framework, but also includes a set of technologies and product capabilities that help implement the data automation

Robotic Data Automation Fabric (RDAF) infuses AIOps and robotic data workflow automation across the customer’s distributed edge using next-generation technologies like NLP (natural language processing), NLG (natural language generation), distributed messaging, and integrated development environment (IDEs) for building customized, on-the-fly, instantaneous pipelines using low-code databots. 
#### Key takeaways 
The value of RDA
Robotic process automation (RPA) vs Robotic Data Automation (RDA) 
Robotic data automation fabric and data observability
RDAF and edge analytics
#### Article quality
Being a fairly new concept, there are only a few available articles related to Robotic Data Automation (RDA). In addition to giving an in-depth review of what RDA is, this article compares RDA to RPA and explains how Robotic Data Automation Fabric and edge analytics work together. 

#### References
https://www.youtube.com/watch?v=dwq9AQFoXBo
https://www.roboticdata.ai/bot-library/

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic.
