### ISSUE TITLE
Using a Static Method to Check the Accessibility of Static and Non-Static Variables

### ISSUE THREAD

**Issue by AshaIha** [section-engineering-education/engineering-education#6355]
### Topic Suggestion
Using a Static Method to Check the Accessibility of Static and Non-Static Variables
#### Proposed article introduction
Variables, methods, and blocks of code can be protected with Java's static keyword. They are initialized once at the beginning of the execution, which makes them a class variable. Due to the fact that they are static variables, they are accessible simply by class name and do not require an instance.
Statically accessed variables can also only be accessed by Static methods because they belong to a class and not an instance and they can only be accessed by static methods.
#### Key takeaways 
- How static methods can access static variables
- How to access non-static variables inside a static method.
- Reasons why static methods cannot access non–static variables.
#### Article quality
1. In Section, we do not have any articles related to Using a Static Method to Check the Accessibility of Static and Non-Static Variables.
2. Although, we have a few articles discussing 1 or 2 on Using a Static Method to Check the Accessibility of Static and Non-Static Variables, we don't have a common article that calls a non-static method from another class and use static methods to access instance variables.
3. The code snippets that I will provide will be easier to grasp.
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Based on this search -> https://www.google.com/search?q=Using+a+Static+Method+to+Check+the+Accessibility+of+Static+and+Non-Static+Variables&oq=Using+a+Static+Method+to+Check+the+Accessibility+of+Static+and+Non-Static+Variables&aqs=chrome..69i57j69i61.332j0j9&sourceid=chrome&ie=UTF-8 , the topic appears somehow over-saturated on other blog sites and official documentation. Feel free to suggest another topic. Thanks
