### ISSUE TITLE
Extensive Understanding of OS File Systems

### ISSUE THREAD

**Issue by CodeLeom** [section-engineering-education/engineering-education#6356]
### Topic Suggestion
Extensive Understanding of OS File Systems

#### Proposed title of article
Extensive Understanding of OS File Systems

Use keyword research to improve your article's SEO.

#### Proposed article introduction
A file system, often known as file management or FS, is a method of controlling how and where data is stored on a storage drive. It is a logical disk component that compresses files that are divided into groups called directories. It is abstract to a human user and computer-related; as a result, it manages the internal activities of a disk. In this article, I will be discussing all the types of file systems including the yet available ones for end users.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

#### Key takeaways 
Broad understanding of NTFS, REFS, FAT32 and all others

#### Article quality
I will be covering an in-depth explanation of each file systems

#### References
Windows File System, Linux File System and Mac File System as published in the company's documentation

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
This topic appears to divert from program-centric areas. Feel free to suggest another topic. Thanks
