### ISSUE TITLE
Face detection and extracting features using OpenCV

### ISSUE THREAD

**Issue by samtecmwas** [section-engineering-education/engineering-education#6357]
### Proposed title of article
Face detection and extracting features using OpenCV

#### Proposed article introduction
Image processing offers a variety of enhancement that improves the quality of an image. Using OpenCV by  applying mathematical morphology to the image one can detect human face features and extract different unique features such as face, nose ,eye and skin and such information can can be used in  augmented reality operations and its application.

#### Key takeaways 
- Introduction to face detection in OpenCV.
- By ensuring code examples with explanation it will be easier to grasp concepts.
- Understanding the mathematical morphology behind face detection techniques

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
We have several topics on face detection using OpenCV -> https://github.com/section-engineering-education/engineering-education/issues?q=OpenCV Further, the topic appears to be [over saturated](https://www.google.com/search?q=Face+detection+and+extracting+features+using+OpenCV&oq=Face+detection+and+extracting+features+using+OpenCV&aqs=chrome..69i57j69i64j69i61.577j0j9&sourceid=chrome&ie=UTF-8)
