### ISSUE TITLE
[Security] Big Data for Cybersecurity Analytics in security sectors.

### ISSUE THREAD

**Issue by Adespscientist** [section-engineering-education/engineering-education#6364]
### Topic Suggestion
Using Big Data for Cybersecurity Analytics in different security sectors.

#### Pre-submission advice
There are three main challenges that businesses are running into with big data e.g protecting sensitive and personal information, Data rights and ownership, not having to analyze the data. But what are the threats and opportunities involved in Big data and cybersecurity?

Big Data is generally defined as being dense in variety, velocity, and volume. From a cyber security standpoint, big data has ushered in new possibilities in terms of analytics and security solutions to protect data and prevent future cyber attacks
But just as big data has opened up new possibilities for cyber security teams, it has also given cybercriminals the opportunity to access mass quantities of sensitive and personal information through the use of advanced technologies.

Cybersecurity analytics are Increasingly sophisticated attack methods used by cybercriminals and the growing role of malicious insiders in several recent large-scale security breaches clearly indicates that traditional approaches to information security can no longer keep up. so where does the security analytics fits in? 

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an article to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

#### Key takeaways 
After participating in this tutorial you should fully understand 
- What Big Data and Cybersecurity is and its purpose.
- Understand major points where cybersecurity analytics fits in 

#### Article quality
After this lesson, you will develop an insight into the level of awareness and current approaches in information security fraud detection in organizations around the world? Unlike some other blogs that talk about security analytics, I will have close work with you and show you in-depth mesures and future plans of big data security analytics initiatives across different sectors.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
You have another topic in progress.
