### ISSUE TITLE
Login with Twitter using OAuth1.0a Protocol via API in PHP

### ISSUE THREAD

**Issue by Fidelmwangi** [section-engineering-education/engineering-education#6365]
#### Proposed title of article

Login with Twitter using OAuth1.0a Protocol via API in PHP

#### Proposed article introduction

Practically all Internet giants like Google, Facebook, Twitter and LinkedIn support OAuth login. They furnish API with definite documentation to assist designers with coordinating OAuth confirmation. There are numerous customer libraries accessible to carry out Twitter OAuth login. However, I will do with just plain PHP for it is really adequate, lightweight and better. Application with the OAuth login feature has many advantages:

1.  Simplifies the login process.
2. Reduces friction by minimising user’s effort with a single click.
3. Saves developers’ effort from building a custom login.
4. Assures secure authentication flow.

#### Key takeaways 
By the end of this article, the following is expected;

1. Twitter OAuth login flow
2. How to integrate Twitter OAuth login?
3. Generating Twitter app keys
4. Twitter OAuth PHP service
5. PHP code to handle logged-in user data
6. Database script
7. Login with Twitter PHP example output

#### Article quality

There are various ways to implement Twitter OAuth login in a PHP application. Generally, people use built-in client-side libraries to implement. Twitter also recommends one or more PHP libraries in its community API gallery but this article shows a simple code for “Login with Twitter” integration for it uses no external libraries to achieve this. I hope we will have a good ride all along.

#### References

N/A

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=Login+with+Twitter+using+OAuth1.0a+Protocol+via+API+in+PHP&oq=Login+with+Twitter+using+OAuth1.0a+Protocol+via+API+in+PHP&aqs=chrome..69i57j69i61l2.318j0j9&sourceid=chrome&ie=UTF-8), this topic appears to be over-saturated on other blog sites and official documentation. Feel free to suggest another topic. Thanks
