### ISSUE TITLE
Inheritance  in Python

### ISSUE THREAD

**Issue by KARIUKIJOHN** [section-engineering-education/engineering-education#6367]
Inheritance in Python

Introduction

Inheritance is highly valued in object-oriented programming. It enables us to reuse code using an existing class instead of creating a new one. Thanks to Python's inheritance mechanism, one object may inherit all of its parent's attributes and actions. The child class inherits the parent's characteristics and may access all of the parent's data objects and actions. Also, a child class may implement a parent class's functions. This tutorial will cover inheritance extensively.

Key takeaways

By the end of the article, the learners should have covered:

1. An Overview of Inheritance
2. Python inheritance examples
3. Inheritance types
4. Inheritance implementation

Article quality
This article will provide a thorough understanding of the recommended subject. For optimal comprehension of the ideas needed, flow diagrams and code snippets will be used. The topic is suitable for beginners since everything is thoroughly described and detailed.

References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
