### ISSUE TITLE
[Languages]Object-Oriented Programming: Java Classes

### ISSUE THREAD

**Issue by Erastuskanyatta** [section-engineering-education/engineering-education#6368]
#### Proposed title of the article
[Languages]Object-Oriented Programming: Java Classes

#### Proposed article introduction
One of the essential concepts in object-oriented programming is classes.
Programmers use classes and objects interchangeably, but they are different.

A class is a template for creating objects. For example, let's assume we have a class `elevator`. This class may have attributes like `current speed`, `moving` or `not moving`, `current direction`, `current weight`, etc. These attributes are implemented using fields in programming.
In addition, this elevator may have `methods `(behaviours) like `start(), stop(), move(), load(), unload(),` etc.

On the other hand, an object is an instance of a class. From the class elevator, we can create many objects like `elevator1, elevator2, elevator3, `etc. These objects have the same fields and methods, but they can be in a different state. For instance, elevator1 may be moving upwards while elevator2 moves downwards. 

#### Key takeaways 
1. Java classes and objects 
2. Creating a class
3. Memory allocation when creating a new object in Java
4. Coupling in class and how to reduce it
5. Constructors in Java

#### Article quality
In this tutorial, the class concept will be covered in depth so that both beginners and advanced programmers will be able to understand it, unlike the internet tutorials which are not so detailed and not friendly to beginners.

#### References
N/A

**Comment by WanjaMIKE** [comment]
This topic appears to be oversaturated and has already been covered in numerous articles. Feel free to choose another topic. Thanks
