### ISSUE TITLE
Bitwise Operations and their Use Cases in Python

### ISSUE THREAD

**Issue by wanguiwaweru** [section-engineering-education/engineering-education#6376]
#### Proposed title of article

Bitwise Operations and their Use Cases in Python

#### Proposed article introduction

Each language has different operators including arithmetic operators, logical operators, relational operators and bitwise operators. This article delves into bit-wise operators and their use cases in different scenarios. Sometimes it may not be apparent to a developer that a bitwise operator can achieve the objective more effectively. In this article we will gain better insights to help us use bitwise operators more intuitively.

#### Key takeaways 

By the end of the article, the learners should have an understanding of :
1. Bitwise Operators
2. Difference between logical operators and bitwise operators.
3. Uses cases of bitwise operators with examples from sample interview question,

#### Article quality
This article intends to provide an in-depth look into bitwise operators by providing examples and use cases. The article is useful to beginners and more experienced learners who are aware of bitwise operators, but do not know when to use them. I will offer solutions using a brute force approach and another using bitwise operators to demonstrate how to use the operators more intuitively. 

#### References.
1. [Bitwise Operators ](https://python-reference.readthedocs.io/en/latest/docs/operators/#bitwise-operators)
2. [Boolean Operators](https://python-reference.readthedocs.io/en/latest/docs/operators/#boolean-operators)

**Comment by WanjaMIKE** [comment]
This topic appears to be quite similar to -> https://dev.to/freddthink/bit-wise-operations-and-their-use-cases-594n We focus more on unique projects. Feel free to suggest another topic. Thanks
