### ISSUE TITLE
HOW TO MAKE READING SEVERAL  PDF FILES AND THEN  CREATING DATA FRAMES   AUTOMATE IN R

### ISSUE THREAD

**Issue by Victor-Ror** [section-engineering-education/engineering-education#6378]
### Topic Suggestion
HOW TO MAKE READING SEVERAL PDF FILES AND THEN CREATING DATA FRAMES  TO BE AUTOMATE IN R

#### Proposed title of article
 HOW TO MAKE READING SEVERAL PDF FILES AND THEN CREATING DATA FRAMES  TO BE AUTOMATE IN R

#### Proposed article introduction
An individual may have several reports containing large datasets sent to them regularly. If one has a backend system that downloads the files and store them in a folder. The individual  might be interested in specific pages of the  several PDFs, containing  data needed to be in a table format. The need to make this process automatic becomes necessary . The success of automation depends on the consistency of the PDF files. Assuming they have identical processing needs, the process of extracting  the data is very feasible.

So I have put together  a solution for this by running a loop code.

#### Key takeaways 
-The student will be able to print file names with data onto the console in data frames  from different PDFs extracted all at once.
-The student will be able to read and create data  frame  with specific fields from PDFs.
-The student will be able to convert the extracted files from PDFS into text files.

#### Article quality
-The article is beginner friendly.
-The article covers  the automation extensively

#### References
[Creating data frames from PDFs in R](http://theautomatic.net/2018/08/24/getting-data-from-pdfs-the-easy-way-with-r/)

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks

**Comment by Victor-Ror** [comment]
@WanjaMIKE  my tutorial will explain how to extract data without page numbers but just key phrases, and in the reference when the loop is run only the last pdf extracted is entered onto the dataframe as my tutorial will run a loop to print all the data from pdfs onto df all at once.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over [saturated ](https://www.google.com/search?q=PDF+FILES+AND+THEN+CREATING+DATA+FRAMES+AUTOMATE+IN+R&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8)throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
