### ISSUE TITLE
Understanding Few-Shot learning Algorithms

### ISSUE THREAD

**Issue by AndrewOdera** [section-engineering-education/engineering-education#6385]
#### Proposed title of article
Understanding few-shot learning algrorithm

#### Proposed article introduction
In this tutorial, we will discuss algorithms used in few-shot learning and their implementation in machine learning models. Besides we will look at some of the importance of this algorithm as compared to other algorithms in other learning models.

#### Key takeaways 
By the end of this tutorial, the learner will gain skills 
1. Implementing best Algorithm in Few-shot learning
2. Understand Algorithms used in Few-shot learning
3. Deploy the Algorithms in their work during learning.
#### Article quality
Will be the best with well explained terms in ML

#### References
N/A

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=Understanding+Few-Shot+learning+Algorithms&oq=Understanding+Few-Shot+learning+Algorithms&aqs=chrome..69i57j69i61.542j0j9&sourceid=chrome&ie=UTF-8), this topic appears to be somehow oversaturated on other blog sites. Feel free to suggest another topic. Thanks
