### ISSUE TITLE
[Blockchain]Understanding Permissioned Vs. Permissionless Blockchains

### ISSUE THREAD

**Issue by nduta-ndush** [section-engineering-education/engineering-education#6388]
### Topic Suggestion

Understanding Permissioned Vs. Permissionless Blockchains

### Writing sample(s): 
N/A

#### Proposed title of article
Understanding Permissioned Vs. Permissionless Blockchains

#### Proposed article introduction
Bitcoin drew attention to the blockchain world. Bitcoin's market prominence may be attributed to the network's ability to allow its users to conduct transactions recorded on a distributed ledger. The distributed ledger technology (DLT) is not limited to bitcoin but is usable to all blockchain networks. The DLT is a collection of frameworks and paradigms that enable the distribution of information on blockchain networks. Permissioned and permissionless blockchains are two paradigms that enable the proper functioning of distributed ledger technology.

#### Key takeaways 
You will gain:
- What is permissioned and permissionless blockchains.
- Characteristics of the two paradigms.
- Advantages and disadvantages of the two paradigms. 
- Similarities and differences between the two paradigms.
#### Article quality
The article covers concepts that are unpopular among many readers. Also, the depth and breadth of the article make it unique and original from many articles on the web. 

#### References
n/a

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

https://www.google.com/search?q=Understanding+Permissioned+Vs.+Permissionless+Blockchains&oq=Understanding+Permissioned+Vs.+Permissionless+Blockchains&aqs=chrome..69i57j69i61.298j0j9&sourceid=chrome&ie=UTF-8
