### ISSUE TITLE
The use of Kubernetes, Nifi and Kafka to connect IOT devices

### ISSUE THREAD

**Issue by mbinya18** [section-engineering-education/engineering-education#6392]
Proposed title of article
The use of Kubernetes, Nifi and Kafka technologies to link IOT devices

Proposed article introduction
Nifi, Kubernatives and Kafka are a set of technologies that can work with ranges of data and manage it. Nifi deals with the flow of processes, a technology that can be used to show the flow processes in a IOT device. Kubernatives is responsible for  application orchestration which will be used for orchestration of IOT devices with applications and Kafka is responsible for real time data analysis for real time data. I intent to combine the three technologies to enable the interaction of IOT devices and management of their data.

Key takeaways
By the end of the article, the learners should have an understanding of :

1. The use and operation of each technologies
2. The interaction of the KUBECTL
3. The interaction of the three technologies for the communication of IOT devices

Article quality
This article intends to provide an in-depth look into IOT devices integration using Kafka, Nifi and Kubernetes  by providing examples and use cases. The article is useful to beginners and more experienced learners who are aware of IOT devices and how they operate. I will offer solutions using  the three technologies to demonstrate how to use the technologies more intuitively.

References.
N/A

**Comment by WanjaMIKE** [comment]
Could you highlight how the article differs from existing documentation and other blog sites?

**Comment by mbinya18** [comment]
I will mainly focus on the use and integration of kubernetes in its orchestration to the storage of IOT devices data and its processes transactions and management. Nifi will be employed to help in the better tracking of information that can play a major role in better tracking in cases of vulnerabilities. @WanjaMIKE

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over [saturated ](https://www.google.com/search?q=Kubernetes+to+connect+IOT+devices&rlz=1C1CHBF_enUS891US891&ei=_OArYrSRKI3P0PEPm6mb-Ak&ved=0ahUKEwi0_5zOoL_2AhWNJzQIHZvUBp8Q4dUDCA4&uact=5&oq=Kubernetes+to+connect+IOT+devices&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQyQVYyQVgvAdoAXABeACAAVaIAVaSAQExmAEAoAEByAEIwAEB&sclient=gws-wiz)throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
