### ISSUE TITLE
Building a Flutter budget application with sembast NoSQL database

### ISSUE THREAD

**Issue by qawuor** [section-engineering-education/engineering-education#6398]
### Topic Suggestion
Building a Flutter budget application with sembast NoSQL database

### Writing sample(s): 
Include any links or writing samples to help our team gauge your writing quality better.

#### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

### Getting started with Flutter NoSQL database
NoSQL database is a database that stores data in a non-relational way. NoSQL databases are often used to store data that is not meant to be stored in a relational database, i.e. in a chat application, the amount of unrelated data is too large to be stored in a relational database. NoSQL databases offer a lot of advantages over relational databases i.e.:
1. Allows for low-level data manipulation.
2. Data is stored in JSON format, which is easy to read and write and is already being used by several applications.

There are several types of NoSQL databases:
1. Key-Value store - this kind of NoSQL database stores data in a key-value pair similar to the dictionary or hashmap data structure. Examples are Redis Memcache.
2. Graph-based store - this kind of NoSQL database stores data in a graph data structure. Data is stored in nodes that have properties. Examples are Neo4J Flock DB.
3. Document store - this kind of NoSQL database stores data in a document file. Data is stored in documents that are stored in the file system. Examples are MongoDB CouchDB.

Simple Embedded Application Database (sembast) is a document-based NoSQL database embedded in the application. It runs perfectly on the Dart virtual machine, making it suitable for a Flutter application. sembast is small and does not impact the final .apk or .ipa file size.

In the article, I will explain how to use sembast NoSQL database to store unrelated data of a budget Flutter application. Although I have chosen to build a budget application because the budget data differ, several columns in the database may remain unused when a SQL database is used, leading to data integrity issues. This makes the NoSQL database a good candidate for this kind of application.

#### Key takeaways 
1. Introduction to NoSQL databases.
2. NoSQL data structuring and organization.
3. Integrating a NoSQL database into a FLutter application to store data locally on the device.

#### Article quality
As much as it is easy to use and design a NoSQL database, mobile phones do not come bundled with a NoSQL database. Many tutorials heavily explain how to use SQL database (SQLite) that comes bundled with Android and iPhones. This tutorial will explain how to integrate the NoSQL database and build both IOS and Android applications using the Flutter framework.

#### References
Please list links to any published content/research you intend to use to support/guide this article.
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by qawuor** [comment]
Hello @WanjaMIKE I am going to use Sembast Flutter plugin not Firebase to build the in app datastore.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over [saturated ](https://www.google.com/search?q=Flutter+sembast+NoSQL+database&rlz=1C1CHBF_enUS891US891&ei=huIrYqOfHLzF0PEP956YwA8&ved=0ahUKEwij-oCKor_2AhW8IjQIHXcPBvgQ4dUDCA4&oq=Flutter+sembast+NoSQL+database&gs_lcp=Cgdnd3Mtd2l6EAwyBQgAEKIEOgcIABBHELADSgQIQRgASgQIRhgAUIgNWKUoYO9FaARwAXgAgAHQAYgB7QuSAQYxNy4wLjGYAQCgAQHIAQjAAQE&sclient=gws-wiz)throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
