### ISSUE TITLE
[Languages] Parameterized constructor in C++

### ISSUE THREAD

**Issue by BoldTony1** [section-engineering-education/engineering-education#6402]
#### Proposed title of article
Parameterized constructor in C++

#### Proposed article introduction
Parameterized constructor in C++ are particular sorts of methods which are incarnated immediately after an object is formed. C++ carries two types of constructors: Default constructor and  Parameterized constructor. These two constructors are almost similar except for the fact that default constructor lacks arguments but still does incarnation of objects. Parametrized constructor is a specific form of constructor by which an object is built, following supply of further parameters to different instances.

#### Key takeaways 
The following are among the things that the reader will be able to understand:

- Meaning of a constructor
- From constructor to Parameterized constructor
- Working of Parameterized constructor
- Application of Parameterized constructor in C++
- Advantages of Parameterized constructor in C++

#### Article quality
This article intends to take the reader through the concept of parameterized constructor and how to implement it in C++.The reader will be able to comprehend the shift from constructor to parameterized constructor in C++. I will give examples in each step to illustrate the concepts of this article.
#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

https://www.google.com/search?q=parameterized+constructor+in+c%2B%2B&oq=Parameterized+constructor+in+C%2B%2B&aqs=chrome.0.0i512l7j69i61.325j0j9&sourceid=chrome&ie=UTF-8
