### ISSUE TITLE
Python pickling and unpickling

### ISSUE THREAD

**Issue by saraheric** [section-engineering-education/engineering-education#6404]
### Topic Suggestion
Python pickling and unpickling

#### Proposed article introduction
Pickling is a python term to mean serialization. Pickling is a process of converting the state of an object into a byte stream with an aim to store it or send it over a network. Unpickling, which simply means deserializing, is the inverse of pickling. The functions for serialization (dump() and dumps()) and deserialization (load() and loads()) are provided by the pickle module in the standard libraries of python. The use of specific python data in pickle module impairs deserialization of non-python programs. In fact trying to deserialize non-python data is regarded as insecure.

#### Key takeaways 
- Standard conventions in pickle
- Major applications of pickling
- Risks associated with pickling and how to avoid them
- Advantages and Disadvantages of Pickling

#### Article quality
I will feature a deep dive  in pickling and unpickling in python. I will ensure unicity of this article by providing factors to  consider when using pickling and unpickling. Examples and illustrations will be provided where needed.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
