### ISSUE TITLE
App layout design programmatically using Matlab

### ISSUE THREAD

**Issue by vitalisodhis** [section-engineering-education/engineering-education#6406]
### Topic Suggestion
App layout design programmatically using Matlab

### Writing sample(s): 
https://www.section.io/engineering-education/image-processing-using-matlab/

#### Proposed article introduction
The app layout is the structure that interfaces the user with the app. The app consists of figures, these figures contain one or more UI(user interface). The UI components hold the interactive parts used while operating the app.

In Matlab, apps can be designed using GUI(graphical user interface) or programmatically using Matlab functions. This article will discuss designing app figure layout programmatically using Matlab functions. Through these functions, app UI components like buttons, dialog boxes, and containers can be made.

Apps are used in day-to-day activities in making life easier, they can be used in communication, data processing, and entertainment purposes.

#### Key takeaways 
- Creating app layout using matlab functions.
- Understanding the basic components of uifigure based apps.
- Understanding of uifigure function operations.

#### Article quality
The most obvious way of designing an app layout in matlab is by using the App designer or GUI(graphical user interface). This article discusses designing app layout through coding using matlab functions.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
