### ISSUE TITLE
Building an Offline-First application with Node.js

### ISSUE THREAD

**Issue by Claradev32** [section-engineering-education/engineering-education#6407]
### Topic Suggestion
Building an Offline-First application with Node.js

### Writing sample(s): 
https://blog.logrocket.com/designing-modern-theme-open-props/
https://dev.to/claradev32/building-a-node-js-api-with-hapi-js-and-mongodb-454c
https://arctype.com/blog/author/clara/
https://adamtheautomator.com/pswindowsupdate/

### Proposal Submission
In this tutorial, the reader will learn how to build and structure a NestJS MVC application by building a demo project with MongoDB. They will learn how to set up a Nestjs application, setup and connect a MongoDB database, configure routing in Nestjs, and implement user authentication and authorization. 

#### Proposed title of article
Building an Offline-First application with Node.js
- Service Workers
- Splash Screen 
- Google Lighthouse check
- Optimizing application

#### Proposed article introduction
Did you know your Node.js apps can be installed and running on your smartphones? Yes, it is possible with Progressive Apps (PWAS).
Progressive Web Apps (PWAs) are web apps that use service workers, manifests, and other web-platform features, along with progressive enhancement, to provide users with an experience comparable to native apps. 
Progressive Web Apps (PWAs) outperform native apps in terms of efficiency. They operate on demand and are always available, without consuming valuable smartphone memory or data. Users consume less data when they choose a PWA over a native version of the same application (as is the case for the Twitter PWA). However, this does not imply that users should forego the convenience of a native app. They can still save the PWA to their home screen; it's installable without the need for a full download.

In this tutorial, we'll learn how to build an offline-first application with Node.js.

#### Key takeaways 
- Create a Manifest
- Optimizing application
- Configure SSL
- Setup Service Workers
- Google Lighthouse check

#### Article quality
The code snippets for this tutorial will be written using software development best practices. The tutorial will be based on my experience building with Node.js over the last two years.No part of this tutorial will be copied from any tutorial on Youtube or blogs.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @Claradev32

**Comment by Claradev32** [comment]
Hi @lalith1403.
The draft for this tutorial is ready. Here is the dropbox link https://www.dropbox.com/scl/fi/corpat2bugrcbu9j2hyig/Building-an-Offline-First-application-with-Node.js.paper?dl=0&rlkey=i6bm95ycck14f2j89i55h0gmv

Thanks

**Comment by hectorkambow** [comment]
Whenever the articles is ready to be submitted - feel free to submit a pull request to link. 

At that time we can re-open this issue. 👍

**Comment by icode247** [comment]
I have commented with the link to the draft long ago

**Comment by Claradev32** [comment]
@hectorkambow Sorry about the last comment, I forgot. I was using my brothers PC.

I commented with the link to the draft a long time ago.
https://www.dropbox.com/scl/fi/corpat2bugrcbu9j2hyig/Building-an-Offline-First-application-with-Node.js.paper?dl=0&rlkey=i6bm95ycck14f2j89i55h0gmv
