### ISSUE TITLE
python dataclasses

### ISSUE THREAD

**Issue by sabin254** [section-engineering-education/engineering-education#6411]
#### Proposed title of article
python dataclasses

#### Proposed article introduction
Dataclasses are just like other Python classes, but they are specially designed to be used as data containers and provide a cleaner and shorter syntax for quickly creating data objects. Dataclasses have been added in a recent addition in python 3.7 as a utility tool for storing data. DataClasses provides a decorator and functions for automatically adding generated special methods such as __init__() , __repr__() and __eq__() to user-defined classes. in this tutorial, you’ll learn about the Python data class decorator and how to use it effectively.

#### Key takeaways 
1. Introduction to the Python dataclass
2. Default values
3. Convert to a tuple or a dictionary
4. Create immutable objects
5. Customize attribute behaviors
6. Sort objects

#### Article quality
This will be an in-depth article explaining all aspect of this concept. I will make use of simple language which will enable beginners to understand more clearly and also all code snippets will be explained. 

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
