### ISSUE TITLE
Building Finite State Machines with Python Coroutines

### ISSUE THREAD

**Issue by Graceshee** [section-engineering-education/engineering-education#6413]
#### Proposed title of article
Building Finite State Machines with Python Coroutines

#### Proposed article introduction
Finite State Machine is a mathematical model of computation that models a sequential logic. FSM consists of a finite number of states, transition functions, input alphabets, a start state, and end state(s). Implementing an FSM is crucial to solving some of the most interesting problems in Computer Science and in this article, we dive deep into modeling a Finite State Machine using Python coroutines.

#### Key takeaways 
1. Python Coroutines
2. Generators
3. Building a Finite State Machine
-  State
-  FSM Class
-  Driver function

#### Article quality
In the article Building Finite State Machines with Python Coroutines I make use of simple language to enhance easy understanding for learners. I will explain all code snippets and all parts will be explained in depth.

#### References
N/A

**Comment by lalith1403** [comment]
Thank you for the topic suggestion , however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
