### ISSUE TITLE
Integrating Razorpay in a React Django(Django Rest Framework) Application

### ISSUE THREAD

**Issue by kevinkim573** [section-engineering-education/engineering-education#6414]
#### Proposed article introduction
Razorpay is an Indian Payment Processing Platform that allows businesses to accept, process, and disburse payments with its product suite. In this article, we will take a look at how we can integrate Razorpay in a React Django Application to enable a business to send and receive payments. 

#### Key takeaways 
- Working with payment applications.
- Integrating Razorpay in a React Django application.
- React best practices. 

#### Article quality
Articles published on the web covering this topic only tackle the article from one side, either React only or Django only. This is good but not ideal for a beginner who might have an application that works with both React and Django. Implementing it might be difficult for them. In this article, we will do things differently by creating a REST API using Django Rest Framework and consuming the API routes with React. The payment process will be triggered by the user from the React frontend and the Django Rest Framework will interact with the Razorpay API to process the payment.

Other articles also cover this topic using Django templates but in this article, we will create a REST API with Django Rest Framework.

**Comment by WanjaMIKE** [comment]
This article by @zolomohan discusses how to implement razorpay in React. How is this topic different from it?

**Comment by zolomohan** [comment]
Hi @WanjaMIKE. My article covers Razorpay integration with React Native. React and React Native have different Razorpay SDKs.

Also the backend that I used is Node.js but this article aims to cover Django.

I believe there's no overlap here with my article.

**Comment by kevinkim573** [comment]
Hello @WanjaMIKE, as zolomohan has explained, my approach is totally different. There's no overlap.

**Comment by kevinkim573** [comment]
@WanjaMIKE :eyes:

**Comment by kevinkim573** [comment]
@WanjaMIKE, it has been way too long now and Zolomohan already cleared on the overlapping issue.

cc @ahmadmardeni1

**Comment by kevinkim573** [comment]
@hectorkambow, can you please reopen this? The article is now ready.
