### ISSUE TITLE
Orchestrating Containerized Django Application with Docker Swarm

### ISSUE THREAD

**Issue by khabdrick** [section-engineering-education/engineering-education#6416]
### Writing sample(s): 
https://www.section.io/engineering-education/authors/muhammed-ali/

#### Proposed title of article
Orchestrating Django Application with Docker Swarm

Use keyword research to improve your article's SEO.

#### Proposed article introduction
IN this article the reader will go through building a simple Django application and deploying it to the Docker hub. From the deployed application on Docker Hub I will show the reader how to perform some orchestrating using EC2 instances.

ONLY viable topics to pick from:
- Containers
- Networking

#### Key takeaways 
- Building and Deploying Django Containers to a Docker Swarm 
-  Scaling Django Application For Load balancing in Docker Swarm
- Updating Django container on Docker swarm
- Managing Nodes in Docker Swarm

#### Article quality
This article is unique

**Comment by lalith1403** [comment]
Thank you for the topic suggestion, however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
