### ISSUE TITLE
Making Python Integers Iterable

### ISSUE THREAD

**Issue by Alekiie** [section-engineering-education/engineering-education#6418]
#### Proposed title of article
Making Python Integers Iterable.

#### Proposed article introduction
Iterables in Python are objects and containers that could be stepped through one item at a time, usually using a for ... in loop.An iterator is an object that contains a countable number of value.

Technically, in Python, an iterator is an object which implements the iterator protocol, which consist of the methods __iter__() and __next__()

#### Key takeaways 
1.What is a Python iterable?
2.What an iterator protocol is and,
3.Changing Python's source code and make integers iterable,

#### References
Nil

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
