### ISSUE TITLE
Remix.js Vs Next.js

### ISSUE THREAD

**Issue by oyedeletemitope** [section-engineering-education/engineering-education#6423]
#### Key takeaways 
At the end of this article, the readers should be able to:
- Install remix
- Know when to use it
- Features Remix has to offer
- Know which to choose between Remix and Next.js

#### Article quality
- This article is meant to cover aspects like:
- What Remix actually is.
- How to get started
- Comparing Remix with Nextjs
- Why you should use Remix

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
