### ISSUE TITLE
Generating Initial Avatar Image from Username using PHP 

### ISSUE THREAD

**Issue by Wendymwangi** [section-engineering-education/engineering-education#6428]
#### Proposed title of article

Generating Initial Avatar Image from Username using PHP 

#### Proposed article introduction

An avatar is a graphical representation of a user’s identity by using icons or profile thumbnail images. Images are an integral part of the web pages. They help to convey a meaning easily. Depending on the scenario, the images are created dynamically for rendering graphical elements like charts and graphs. In this article, the registration action will invoke the code to generate an initial avatar from the username. For that, an image layer is dynamically generated using PHP GD functions. Then, the user name’s initial letter is passed to render the image binary to the target layer. The generated avatar will be saved in a target folder and the path will be updated in the user database. When the user logs in to the system with the valid credentials, then the dashboard will display the dynamically generated initial avatar.

#### Key takeaways 
1. Advantages of generating dynamic avatar from the username
2. Existing libraries to generate initial avatar from the username
3. PHP GD Library
4. jQueryUI modal window
5. Landing HTML with login register options
6. PHP code to create avatar image using GD functions
7. Invoke function to generate initial avatar
8. Code to show dashboard with avatar

#### Article quality
This article will be on point, simple to understand, well formatted and I hope users will be able to learn and develop a custom code to generate an initial avatar with just core PHP and jQuery for the code snippets  will be simple to understand and implement. I hope we will have a good ride all along

#### References

N/A

**Comment by WanjaMIKE** [comment]
You have another open topic/issue.
