### ISSUE TITLE
[Languages]Working with JSTL and Custom Tag Libraries

### ISSUE THREAD

**Issue by Chaun864** [section-engineering-education/engineering-education#6430]
#### Proposed title of article
Working with JSTL and Custom Tag Libraries

#### Proposed article introduction
JSTL 1.2 is part of Java EE platform and represents a set of tags used to simplify the development of JSP. We can use the JSTL in various pages and avoid use of script tags.

JSTL stands for[server pages standard tag library] and it is a collection of custom JSP tag libraries that provide common web development functionality. JSTL is a standard tag library of the JSP.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
- Introduction
- Core Tags
- SQL Tags
- XML Tags
- Function tags
- Internationalization Tags
#### Article quality

JSTL and Custom Tag Libraries are advanced Java concepts that all Java developers should be familiar with. They are used to make JSP development easier, and I will go over them in detail. I've noticed that this topic has yet to be addressed in the Engineering block, and that those that have do so in a limited way or fail to explain and provide all of the necessary information.

**Comment by lalith1403** [comment]
Please go through contributions guidelines for more information on submitting topic suggestions. Thank you.
