### ISSUE TITLE
[API] How to implement iPay Mpesa STK push API using python

### ISSUE THREAD

**Issue by diannesandra** [section-engineering-education/engineering-education#6434]
### Topic Suggestion
[API] How to implement iPay Mpesa STK push API using python

### Writing sample(s): 
https://www.section.io/engineering-education/authors/dianne-sandra/

#### Proposed title of article
How to implement iPay Mpesa STK push API using python

#### Proposed article introduction
iPay is a payment gateway for Africa. It has made it easier for merchants to accept transaction systems such as VISA, Mastercard, Kenswitch, M-Pesa, Airtel Money. They have the following APIs: Customer to Business(C2B), Business to Business(B2B), Business to Customer(B2C) and STK push. In this tutorial we'll be consuming thier STK-Push endpoints. 

STK push is a request that triggers a USSD prompt on a phone. The prompt contains the amount being deducted, account name of the merchant and the pin input field. iPay has made it possible for developers to send the prompt for both M-Pesa and Airtel Money users using a single codebase.

#### Key takeaways 
1. Create STK prompts for M-Pesa and Airtel Money.
2. Query iPay Transactions.
3. Create Hashes using HMAC.
4. Change Python Objects to JSON.

#### Article quality
This article is the only one that explains how to initate iPay STK-push requests for M-Pesa. It also explains how to query transactions made through iPay servers using python. It throughly explains how iPay systems process REST API requests. The code snippets provided are easy to follow and can be plugged into projects.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
1. [iPay Africa Documentation](https://dev.ipayafrica.com/index.html)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
@section-engineering-education/content-moderator-team

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by diannesandra** [comment]
Hello am done working in the article, would you please open the isse for me to make my submission?

@jerimkaura
