### ISSUE TITLE
[ Languages]Java Errors and How to Debug them

### ISSUE THREAD

**Issue by Erastuskanyatta** [section-engineering-education/engineering-education#6440]
#### Proposed title of the article
Java Errors and How to Debug them

#### Proposed article introduction
As developers implement more and more concepts into their java application, they expose their code to a wider variety of bugs.

Some developers cannot debug their code, discouraging them from further development. Others don't understand the meaning of various java errors, which may hinder further development.

Debugging is the process of detecting and correcting existing and potential errors in software code that could cause it to crash.

This article will discuss the various types of errors in java and how to debug them.

#### Key takeaways 
1. Different types of errors in java code
2. How to debug java errors
3. Define what an error is and what is a bug
4. Look at the debugging procedure

#### Article quality
As a Java developer, I have been having a lot of struggles whenever I come across a bug. I did not understand the error message's meaning, nor did I understand the steps to fix the error. The documents from the Internet were not helpful. In this article, I believe it will add value to developers and help them fix any bugs that they may encounter.

#### References
N/A

**Comment by WanjaMIKE** [comment]
This topic appears to be covered in numerous [blogs and official docs](https://www.google.com/search?q=Java+Errors+and+How+to+Debug+them&oq=Java+Errors+and+How+to+Debug+them&aqs=chrome..69i57j69i61.286j0j4&sourceid=chrome&ie=UTF-8).  Feel free to suggest another topic.
