### ISSUE TITLE
 Working with BinaryReader in C#

### ISSUE THREAD

**Issue by Dick7603** [section-engineering-education/engineering-education#6461]
#### Proposed title of article
[Languages]  Working with BinaryReader in C#

#### Proposed article introduction
BinaryReader is a C# class for dealing with binary data. It's part of the System.IO namespace. BinaryReader is a class that reads binary values from basic data types in a given encoding stream. BinaryReader works with Stream objects, hence we must supply a Stream object to its constructor to generate a BinaryReader object. To cope with binary data, the BinaryReader class contains three overloaded constructors.

#### Key takeaways 
The reader will be able to understand the following:
- What is binaryreader in C#
- Implementing BinaryReader in C#
- What are some of the read() methods different types of data while dealing with BinaryReader
- StreamReader vs BinaryReader

#### Article quality
This article will be covered in an in-depth manner. I will explain all the concepts related to this topic covering all possible approaches. Proper examples with precise outputs and comments will be ensured as well as adding images wherever necessary. It will be interesting to read and beginner-friendly.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

BinaryReader is adequately covered in the official documentation. Thanks
