### ISSUE TITLE
A Gentle Introduction to Exponential Regression in Machine Learning

### ISSUE THREAD

**Issue by sumbaelvis** [section-engineering-education/engineering-education#6465]
#### Proposed title of article
A Gentle Introduction to Exponential Regression in Machine Learning

#### Proposed article introduction
In real-world applications, we are normally interested in representing behaviours of natural phenomena that change over time in mathematical models. Various models have shown to capture those behaviours very well and, thus, different models for different processes. The most widely known model is linear regression. The popularity associated with this model is due to its simplicity. However, this model remains to be elementary. Almost all the real-life systems are nonlinear, which makes applying linear regression directly on most problems very limited. 

Nevertheless, the implication is not that the linear regression is irrelevant.
On the contrary, it has its place in the world of analysis. Due to its cheap computation cost, most nonlinear models usually are transformed to linear and then determine unknown parameters while on the linear space. Once the parameters are found, we then take an inverse of the transformation we took on the original model on them so that they can capture the relationship that exists in the model space.

Now, some of the possible real-world phenomena where we may require a different model other than the linear model is in the case of rapid growth or rapid decay. In these cases, the processes involve doubling time, the time it takes for a quantity to double.
Some phenomena whose growth may exhibit doubling time are financial investments, wildlife populations, natural resources and biological samples. The exponential function might be the appropriate model for modelling these processes.

The exponetial model takes the form:

$(i) \ y = A_0e^{bt}$,
or;
$(ii) \ y = A_0e^{-bt}$
​​ 
where;
- t is any point in time,
- y is the value of the function at any time t,
- $A_0$ is the value of the model at $t=0$,
- $e$ is Euler's constant, which is usually 2.71828..., and,
- b is the constant that determines the rate of change

The first model, i.e., $(i)$, is used to model the process that grows rapidly over time. So, it's the model for rapid growth.

The second case, i.e., $(ii)$, is used to model the process that decays rapidly over time. A good example of where it is applied is modelling radioactivity decay.

In this article, we will learn how to fit an exponential curve. First, we will look at how we approximate model parameters using Least Square's method. Later, we will fit this model to the data using a dataset. Afterwards, we will interpret the coefficient column of the model `summary()` and use it to state down the equation of our model. Finally, we will close our chapter by making predictions using this model.

#### Key takeaways 
1. What's exponential regression?
2. Types of exponential regression, i.e., exponential growth and decay, and their distinct curves.
3. When to use an exponential model to model the data
4. How to determine the exponential model parameters using analytical methods
5. Application of exponential regression
6. How to fit and make predictions using an exponential model in python

#### Article quality
This article will cover all the basics of exponential modelling. It will teach both approaches to exponential parameter approximation, i.e., using least-squares directly on the given function and first linearizing the function to make it easy to determine parameters using linear perspective. So, we will cover this model in detail.

#### References
N/A

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
