### ISSUE TITLE
Tracking Sales Lead With Python

### ISSUE THREAD

**Issue by Ainea-Amush** [section-engineering-education/engineering-education#6471]
#### Proposed title of article
Tracking Sales Lead With Python

#### Proposed article introduction
Sales lead tracking is a strategy where most sales representatives use to actively monitor where the leads are in the sales and marketing funnel and come up with appropriate actions to move the lead to the next stage and close the sale.
It is important to the marketing department to determine where their leads come from, either from referrals, if they are coming from new customers or if they were found on the web.
In this article, we will not focus on how the leads are generated since the content has been fully covered in some previous articles. We will cover as much concerning the python and some of its libraries and its implementation in getting the leads data and tracking where they are coming from.

#### Key takeaways 
The reader will be able to:

- Understand sales lead tracking and its relevance to the business.
- Understand sales lead tracking in python. 
- Understand how some of the python libraries are used in sales lead tracking.

#### Article quality
There have been documentaries online on what tracking sales lead entails, however non of them have shown how to implement it in python. This article will show our reader how to.

#### References
N/A

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to link a PR. 👍
