### ISSUE TITLE
How To Build Rock, Paper, Scissor Game Using Javascript.

### ISSUE THREAD

**Issue by ekpenyongmike** [section-engineering-education/engineering-education#6473]
### Writing sample(s): 
(https://davemikeondateandtimejs.hashnode.dev/how-to-fetch-dataapi-asynchronously-with-ajax)

#### Proposed title of article
How To Build Rock, Paper, Scissor Game Using Javascript. 

#### Proposed article introduction
The main objective of this article is to show the reader how to build a gaming application using javascript.
Rock, paper, sccissor is a game of logic, the app user interface will display players score and computer score, a restart button will be included to cancel the score for a fresh start.

#### Key takeaways 
- Manipulation of the DOM.
- How to build an app from start to finish.
- How to use the if statement also how to call back a function.

#### Article quality
The app build up is unique which makes the content of the  article different from every other written ones out there.

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=How+To+Build+Rock%2C+Paper%2C+Scissor+Game+Using+Javascript.&oq=How+To+Build+Rock%2C+Paper%2C+Scissor+Game+Using+Javascript.&aqs=chrome..69i57j69i61.294j0j9&sourceid=chrome&ie=UTF-8), this topic appears to be widely over-saturated. Feel free to suggest another topic. Thanks
