### ISSUE TITLE
Getting started with python in Blender

### ISSUE THREAD

**Issue by davyke** [section-engineering-education/engineering-education#6478]
#### Proposed article introduction.
Blender is a free and open source 3D modeling program. Modeling, rigging, animation, simulation, rendering, compositing, and motion tracking are all supported, as well as video editing and game production.Python allows you to automate activities with blender's built-in tools to speed up productivity and provide functionality that would otherwise be impossible to achieve manually.

#### Key takeaways 
- introduction to scripting in blender.
-importing modules into blender.
- create addons in blender
- the merits of using python in blender

#### Article quality
This article provide an indepth guide on scripting python in blender .What make it stand out from the rest is how it geared to create best practice when using python in blender. it also aims to explain the content in beginner friendly manner.  
#### References
N/A

**Comment by WanjaMIKE** [comment]
Introductory aspects to this topic/your key takeaways seem to be well covered in other blogs and official docs. Feel free to suggest another topic. Thanks
