### ISSUE TITLE
[Languages] Serializing and deserializing JSON in C#

### ISSUE THREAD

**Issue by K-jacinta** [section-engineering-education/engineering-education#6480]
### Topic Suggestion

Serializing and deserializing JSON in C#

### Writing sample(s): 
https://www.section.io/engineering-education/authors/jacinta-kyulu/

#### Proposed title of article
Serializing and deserializing JSON in C#

#### Proposed article introduction
Data in JSON format is becoming increasingly popular for exchanging information between applications these days. In the context of developing.NET applications, the conversion of JSON data formats to.NET objects and the converse is fairly prevalent. When converting.NET objects, such as strings, into a JSON format, serialization is taking place, and when converting JSON data back into.NET objects, deserialization is taking place, respectively.
 In this article  we will learn about JSON and the different ways of implementing serialization and deserialization in  JSON using C#.

#### Key takeaways 

1. What is JSON 
2. Styles in JSON
3. Different ways  to Serialize / Deserialize JSON Object using C#
4. Using Newtonsoft JSON.

#### Article quality
The unique aspect of my article will be the use of Newtonsoft JSON and the deep dive into three implementation ways of serialization and deserialization of JSON using a good number of examples in the form of code snippets which has not been discussed in-depth in most of the existing articles 

#### References
N/A

**Comment by WanjaMIKE** [comment]
Based on your key takeaways, I think the article does not provide much value to readers. We usually focus more on unique topics. Feel free to suggest another topic. Thanks
