### ISSUE TITLE
Understanding the concept of Exception handling in JSP

### ISSUE THREAD

**Issue by morwabe1234** [section-engineering-education/engineering-education#6489]
Proposed title of the article
Understanding the concept of Exception handling in JSP

Proposed article introduction
Exception handling is a framework for handling runtime faults so that the application's usual flow may be maintained. JSP exception handling is done with the aid of an exception object which is only found in error pages.
In this article, I will discuss the concept of JSP exceptions, the types of JSP exceptions, and how to implement JSP exceptions using examples.

Key takeaways
1. Introduction
2. Definition of JSP exception
3. Error Pages in JSP
4. Ways to handle exceptions in JSP
5. JSP example to handle an exception in error pages.
6. JSP example to handle an exception by use of JSTL tags.
7. Example to use try and catch to handle an exception in JSP.
8. Conclusion

Article quality
Most blocks have not explained clearly the concept of JSP exception handling to readers, and the Majorly JSP exception  handling has yet to be discussed in Section Engineering.

In this article, I'd want to make the reader understand the concept of exception handling in JSP in detail and focus on implementing it using examples.

References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
