### ISSUE TITLE
Automating jobs Scheduling with Django_Cron in Python Application

### ISSUE THREAD

**Issue by damikanye** [section-engineering-education/engineering-education#6490]
### Introduction
Jobs Scheduling are crucial in streaming applications. There are various ways of streaming data from external API to an application through automation. Sometimes, developers need to automate writing of data to the database at every minutes or hours. With the knowledge of this article, readers would be able to do such.

In this tutorial, we will be making hands-on Python application by demonstrating jobs queues with a library called Django-cron.

### key takeaways
At the end of this tutorial, readers would have gained knowledge about how automation of jobs works in Python applications. The following shall be the points of discussion;
- Jobs Scheduling Overview
- Several ways of automating jobs queue
- Demo of jobs scheduling with Django-cron

### Article Quality
Readers would gain a lot by going through this tutorial because not so many articles are on this topic. It is going to be beginner-friendly too and passed information.

### References
N/A

**Comment by damikanye** [comment]
@lalith1403 this topic was not widely covered at all. I worked on a challenging task that required me to learn jobs scheduling in python application. So, I thought of writing about it and using it to solve a particular problem.

Kindly consider this because it will pass value to readers. Thank you!

**Comment by lalith1403** [comment]
Can you go through contribution guidelines and add more details to the topic suggestion. It would help us better understand the project. Thank you.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
