### ISSUE TITLE
[Android] Implementing Social Mentions used in social media To Tag people or Topics in Android

### ISSUE THREAD

**Issue by kariuki-boniface** [section-engineering-education/engineering-education#6494]
#### Introduction
Social mentions are used to tag people or topics in social media apps. When you tag a user, you get a list of users as you type in the "@" sign and the list is filtered as you type in characters eventually narrowing down the list of users to choose from. This helps in quickly finding the name of a user without going through the whole list of members in a certain social media.

In this article, the learner will learn on how to implement this feature the easiest way. This will be of use to anyone looking to build an app that requires this feature.

#### Key takeaways 
- What are social mentions
- Why is it important to use `@` to tag people or topics
- How to implement this feature the easiest way

#### Article quality
My article will unique in such a way that it will be implemented in the easiest way that any reader can understand. This will be done by use of kotlin programming language.

#### References
-

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=Implementing+Social+Mentions+used+in+social+media+To+Tag+people+or+Topics+in+Android&oq=Implementing+Social+Mentions+used+in+social+media+To+Tag+people+or+Topics+in+Android&aqs=chrome..69i57j69i61.425j0j9&sourceid=chrome&ie=UTF-8), this topic appears somehow over-saturated. We focus more on unique projects. Feel free to suggest another topic. Thanks

**Comment by kariuki-boniface** [comment]
@WanjaMIKE you could have atleast let me explain a bit for more info. Does this mean it cannot be reopened,?
