### ISSUE TITLE
[Android] Using Dokka Docummentation Engine  for Android Gradle to generate KDoc or Javadoc comments

### ISSUE THREAD

**Issue by kirwa-elyjah** [section-engineering-education/engineering-education#6495]
#### Introduction
Dokka is a documentation engine for Kotlin, performing the same function as javadoc for Java. Just like Kotlin itself, Dokka fully supports mixed-language Java/Kotlin projects. It understands standard Javadoc comments in Java files and KDoc comments in Kotlin files, and can generate documentation in multiple formats including standard Javadoc, HTML and Markdown.

In this article, the learner will have a know how on using Dokka docummentation engine to generate Javadoc or KDoc comments. This will be done by the constructing a simple app which will be used to illustrate to the learner.

#### Key takeaways 
- What is Dokka Engine
- Generating Kdoc comments
- Generating Javadoc comments
- Applying necessary plugins to enable generating the kdoc/javadoc comments

#### Article quality
My article will be beginner friendly. It will help the beginners in both java and kotlin in generating documentation comments

#### References
- [Dokka Docummentation](https://kotlin.github.io/dokka/1.6.10/)

**Comment by lalith1403** [comment]
Thank you for the topic suggestion, however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
