### ISSUE TITLE
Building a Quotes App API using Django REST framework and MongoDB

### ISSUE THREAD

**Issue by norah254** [section-engineering-education/engineering-education#6497]
### Topic Suggestion
Building a Quotes App API using Django REST framework and MongoDB

### Writing sample(s): 
N/A

#### Proposed title of article
Building a Quotes App API using Django REST framework and MongoDB

#### Proposed article introduction
In this article, we will build a quotes app API using Django REST framework and MongoDB as our database. Django Rest Framework is a Django framework used to write APIs  in Python. MongoDB is a No SQL database that stores data in a json format.

#### Key takeaways 
By the end of this article, the should be able to:
- Understand Django REST framework
- Be able to create their own apps using Django REST
- Understand and use MongoDB

#### Article quality
My article will be using the Sunscrappers guide to the Django Rest Framework which is more in-depth and covers additional topics like view sets.

#### References
N/A

**Comment by WanjaMIKE** [comment]
This article https://github.com/section-engineering-education/engineering-education/pull/2073 guides readers on how to create a Notes API using Django and MongoDB. They will, therefore, use the same tactics.
