### ISSUE TITLE
Feature Selection Techniques in Machine Learning

### ISSUE THREAD

**Issue by FREDERICO23** [section-engineering-education/engineering-education#6498]
### Topic Suggestion
Feature Selection Techniques in Machine Learning

### Writing sample(s): 
N/A

#### Proposed title of article
Feature Selection Techniques in Machine Learning

#### Proposed article introduction
Feature selection is the process of selecting a subset of relevant features from the dataset for use in building machine learning models. It aims to reduce the number of features to reduce the computational cost of modeling and to improve the performance of the model.

In this article, we will look at the merits of feature selection and discuss the techniques used in feature selection.

#### Key takeaways 
By the end of this article, the reader should be able to:
- Understand feature selection
- Know reasons for feature selection
- Know and understand different feature selection techniques e.g Filter Methods, wrapper methods, etc.
- Apply different feature selection techniques for better model performance

#### Article quality
My article will be more in-depth and provide handy tools to the reader by not only providing the theory but also the programming implementation of the techniques

#### References
N/A.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

https://www.google.com/search?q=Feature+Selection+Techniques+in+Machine+Learning&sourceid=chrome&ie=UTF-8
