### ISSUE TITLE
Android System Architecture

### ISSUE THREAD

**Issue by Kimosop-Wakanda** [section-engineering-education/engineering-education#6502]
Topic Suggestion

Android system architecture

Writing sample(s):

https://www.section.io/engineering-education/authors/meshack-kimosop/

Proposed article introduction

Android architecture is a software stack of components to support mobile device needs. Android software stack contains a Linux Kernel, collection of c/c++ libraries which are exposed through an application framework services, runtime, and application.

 The android architecture is divided into four layer:
- Application - Contains the User Interface.
- Application Framework
- Libraries and Android Runtime
- Kernel

The article proposed will discuss all the layers mentioned above in detail with examples to emphasize the points explained.
Furthermore, we will take a look at the android development cycle and the different states in the Android app development cycle.

 

Key takeaways

By the end of the article, the reader should be able to understand the following:

-  The android stack

 - 4 layers of the android architecture

- The android development cycle

Article quality

This article will help the learner understand the breakdown of the android architecture and how different layers relate with each other. This knowledge will enhance a quick understanding of the learner in their android development journey.

References

N/A

**Comment by WanjaMIKE** [comment]
https://www.geeksforgeeks.org/android-system-architecture/#:~:text=The%20Android%20software%20stack%20generally,the%20applications%20and%20run%20time.


Official docs -   https://developer.android.com/guide/platform

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
