### ISSUE TITLE
[Artificial Intelligence] Edge Computing

### ISSUE THREAD

**Issue by Jacinta78** [section-engineering-education/engineering-education#6505]
#### Introduction
Edge computing is a framework in networking that focuses on placing processing as near as feasible to the data source to decrease delay and bandwidth usage. Edge computing, in simple words, implies executing fewer processes on the cloud and relocating them to local locations, such as a user's PC, an Internet of Things (IoT) device, or edge servers. The article will bring out how edge computing is changing the face of IT and corporate computing. Examine what edge computing means, how it operates, the cloud's impact, edge applications, tradeoffs, and implementation issues in depth.

#### Key takeaways 
1. How edge computing works
2. Edge vs. cloud vs. fog computing
3. Edge computing use cases 
4. Benefits of edge computing
5. Edge computing implementation
6. Edge computing, IoT and 5G possibilities
#### Article quality
I will use simple language in the article for easy understanding for everyone. Its content will be unique. I am looking forward to it having educational importance to all its readers.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
