### ISSUE TITLE
[Languages] PHP Profiling 

### ISSUE THREAD

**Issue by Romans70** [section-engineering-education/engineering-education#6507]
#### Introduction
The fundamental step in optimizing any application is profiling it. Profiling tools maintain track of important information, such as how many time statements and functions are required to process and how frequently they're called. The output may be inspected to see if there are any bottlenecks. The article will outline the three types of profilers and how they function. It will also show the differences between profiling and tracing. Furthermore, it will outline the steps in profiling a PHP code.
#### Key takeaways 
1. Types of Profilers
2. Profiling vs. Tracing
3. Steps of profiling a PHP code
#### Article quality
The article will be unique as its contents will be original. The language used will be simple and easily understood.

**Comment by WanjaMIKE** [comment]
### The five steps of profiling PHP code to find inefficiencies
- Step 1: Install on the development machine. Figure 1.
- Step 2: Restart all services. Restart all your services.
- Step 3: Visit the service, and profile the PHP code. 
- Step 4: Drill into the code. 
- Step 5: Time to optimize.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
