### ISSUE TITLE
[Java] I/O in Java: All you need to know

### ISSUE THREAD

**Issue by davidmbochi** [section-engineering-education/engineering-education#6510]
### Introduction
I/O is a short form for input and output in Java. The read and write functionalities are on a network, memory, or file. The Java programming language provides different APIs that the developer can use to realize these functionalities. These API's include the `InputStream`, `OutputStream`, `Reader`, `Writer`, `BufferedReader`, and `BufferedWriter`. 

In this tutorial, the reader will learn how these I/O APIs work, when to use them, and how to differentiate between them by creating, reading, and writing to a file using the `Files` API.

### key takeaways
- Understanding `InputStream` and `OutputStream`
- Understanding `Reader` and `Writer`
- Understanding `BufferedReader` and `BufferedWriter`

### Article quality
The Java I/O APIs can be very confusing even to experienced developers. This tutorial will make the concepts behind their implementations easier for novice and experienced developers to understand.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
