### ISSUE TITLE
[Languages] Understanding padding and its implementation in Html and CSS

### ISSUE THREAD

**Issue by djayjames** [section-engineering-education/engineering-education#6511]
### Writing sample(s): 
https://www.section.io/engineering-education/authors/james-bundi/

#### Proposed title of article
[Languages] Understanding padding and its implementation in Html and CSS

#### Proposed article introduction
Padding refers to the space between an element's content and its boundaries in HTML, although it may apply to anything. The HTML padding may also be used to make web pages more visually appealing and to draw attention to certain web sites. In addition, there are other types, such as padding-top, padding-left, padding-right, and padding-bottom Using the same kind padding formats, we may align the text. The padding and margin both provide more space to the HTML components, resulting in more room for the HTML elements. We also employ CSS styles and their attributes for all padding places.

In this article, we  will look at what padding is, understand how it work and its properties and finally how to add padding in the Html document using the Internal CSS.

#### Key takeaways 
- The reader will get an insight of padding
- The reader will understand the working of padding in CSS and HTML.
- The reader will understand all the All CSS Padding Properties
- The reader will understand how to add Padding in Html documents using the internal CSS.

#### Article quality
This article would deal with explaining padding and step by step guide to show how to to add padding in the Html document using the Internal CSS. The article will also be beginner-friendly and covering all concept of padding in HTML documents.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
