### ISSUE TITLE
[Languages] Getting Started with Streams in Java

### ISSUE THREAD

**Issue by Erastuskanyatta** [section-engineering-education/engineering-education#6512]
#### Proposed title of the article
Getting Started with Streams in Java

#### Proposed article introduction
Streams are one of the most powerful features of Java.
They allow us to process a collection of data in a declarative manner. This makes our code clean and concise.

A stream is a collection of objects that can be piped together to generate a certain outcome.

Streams are created from either collection, arrays, or an arbitrary number of objects.

#### Key takeaways 
1. Creating a stream
2. Slicing a stream
3. Sorting steams
4. Filtering streams
5. Primitive Type Streams

#### Article quality
This article will help all developers understand the concepts of streams in Java.

#### References
N/A

**Comment by WanjaMIKE** [comment]
You have another open topic/PR

**Comment by ahmadmardeni1** [comment]
Hey @Erastuskanyatta What differs your article form: https://www.google.com/search?q=Getting+Started+with+Streams+in+Java&oq=Getting+Started+with+Streams+in+Java&aqs=edge.0.69i59j69i61.263j0j1&sourceid=chrome&ie=UTF-8 ?

**Comment by Erastuskanyatta** [comment]
Hello, @ahmadmardeni1. Thanks for the ping. I have carefully looked at the link you have provided. The Stream content covered is totally different from my key takeaways. None of my key takeaways are covered in that link. Therefore, I am convinced that my article will be different from the one in the blogs. Thank you.

**Comment by ahmadmardeni1** [comment]
Approved. @Erastuskanyatta
