### ISSUE TITLE
An Overview of OpenVAS Scanner

### ISSUE THREAD

**Issue by Amayo-Amayo** [section-engineering-education/engineering-education#6513]
#### Introduction
Open Vulnerability Assessment System (OpenVAS) is a security software developed and managed by Greenbone Networks. The OpenVAS scanner system can find security flaws in a wide range of web servers and networking devices. To easily assess your Internet architecture, consider the OpenVAS program.  The results are sent to your email address for examination, letting you begin resolving any external threat hazards to your networks. This article will explain how to get started with the OenVAS software, how it is installed and how a user can run a scan in it.
#### Key takeaways 
By the end of this article, the reader should be able to;
1. How OpenVAS works
2. Install OpenVAS
3. Run a scan in OpenVAS
#### Article quality
This will be a unique article with more details. In my article, I will use simple language for any person reading to have a better understanding of the concepts. I will make sure that this article helps the rest of EngEd and goes beyond other official documentation.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

The key takeaways can be found in the original documentations.
