### ISSUE TITLE
How to merge two dictionaries in python

### ISSUE THREAD

**Issue by Jairusonkundi** [section-engineering-education/engineering-education#6518]
#### Proposed title of the article
How to merge two dictionaries in python

#### Proposed article introduction
Python dictionary is a key-value pair data structure comprising all items which are unordered.In the Python program, dictionary items may be rearranged and altered dynamically.
In this article, we will discuss python dictionaries and various methods used to merge two dictionaries

#### Key takeaways 
1. Introduction
2. How to merge two dictionaries using for loop.
3. How to merge two dictionaries using the update method.
4. How to merge two dictionaries using a function.
5. How to merge two dictionaries using Copy() and Update() Method.
6. How to merge two dictionaries using unpacking operator.
7. How to merge two dictionaries using the dict() constructor.
8. How to merge two dictionaries using collections.
9. Examples.

#### Article quality
 I've noticed that the concept of merging dictionaries isn't yet covered in the Engineering block, and that those sites that have covered it do so in a limited way, or don't explain and provide all of the information required. In this article, I will discuss it in-depth and show an example of each method.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
