### ISSUE TITLE
Understanding the concept of session in JSP

### ISSUE THREAD

**Issue by Nicholas-Obare** [section-engineering-education/engineering-education#6519]
Proposed title of the article
Understanding the concept of  session in JSP

Proposed article introduction
A session is an object with a unique session ID that is connected with each user, and the user's data is based on the account they have established. In a session, many types of data may be set; these data, which are specific to each site user, assist the user and the website owner in various ways.
 In this article, we will discuss the concept of sessions in JSP, the session implicit object, Session methods in JSP, and how it is implemented.

Key takeaways
Introduction.
The session implicit object .
HttpSession interface methods.
Session methods in JSP.
HttpSession Example.
Article quality
I checked over some of Section Engineering's published writings and realized that the JSP sessions has yet to be covered and in most websites,this concept is just mentioned but not explained in detail, in this article I will explain the JSP sessions in detail.

References

**Comment by LinusMuema** [comment]
Hi @Nicholas-Obare 

In as much as the topic isn't covered on section, I have found several articles in sites like [Geeks for Geeks](https://www.geeksforgeeks.org/jsp-session-implict-object/) and [W3 schools](https://www.w3schools.in/jsp/session/) that have covered this topic. We cannot move forward with this article but you are more than welcome to explore other topics of interest.
