### ISSUE TITLE
[Languages] Simulating Voting Systems with Python

### ISSUE THREAD

**Issue by csamuelsm** [section-engineering-education/engineering-education#6522]
#### Proposed title of article
Simulating Voting Systems with Python

#### Proposed article introduction
Voting is a key element in a Democracy. From time to time, we get to choose our representatives. Each group, city, state, country (etc.) has its own voting system. In a democracy, the purpose of voting is to choose the one (or ones) candidate(s) who better represent the voters. But this is what really happens? How different voting systems can change the results of an election?

Luckily, there are people who studied this through the lenses of math and science. In this article, we are going to understand some different voting systems, visualize them and try to answer questions like those. For this, we are going to use Python.

#### Key takeaways 
- Understanding different voting systems from the point of view of math and science
- Simulating voting systems with Python
- Visualizing different voting systems with Python and Matplotlib

#### Article quality
I haven't found any tutorials about simulating voting systems in any language, so this is a good contribution as it may be the first. Also, it's a good way for the readers to understand the systems while coding and seeing the results by themselves. 

#### References
- [Primer - Alternate Voting Systems](https://www.youtube.com/watch?v=yhO6jfHPFQU)
- [Types of Voting Systems](https://www.electoral-reform.org.uk/voting-systems/types-of-voting-system/)
- [To Build a Better Ballot](https://ncase.me/ballot/)

### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @csamuelsm 

Thank you for submitting your article suggestion. Upon running a simple google search, I came across [several articles](https://medium.com/zoght/voting-systems-a-python-program-a51d556328b) and [GitHub repos](https://github.com/smari/voting) covering the same topic as the one you've suggested. We therefore cannot move forward with your article. We look for more original content that isn't saturated over the internet. 

You are more than welcome to explore other topics that may interest you.
