### ISSUE TITLE
How To Test In Javascript Using Jest

### ISSUE THREAD

**Issue by ekpenyongmike** [section-engineering-education/engineering-education#6525]
### Writing sample(s): 
https://davemikeondateandtimejs.hashnode.dev/how-to-fetch-dataapi-asynchronously-with-ajax

#### Proposed title of article
How To Test In Javascript Using Jest

#### Proposed article introduction
The main objective of this article is to show the reader how to test for each project they  build using javascript , as testing is very important. Readers have to know the basics of unit testing because, they will eventually deal with it as some point. This article will majorly be on the basics of unit testing with jest and how to install it using the npm package. I will also go further  by intoducing the axios  which we will also install using the npm  to be able to fetch data and send a get request to and an api to get data  for testing.

#### Key takeaways 
- How to install using npm package.
- How to run testing on a project. 
- How to get and fetch data asynchronously.

#### Article quality
There is no any article on the internet that shows the basics of unit testing.

**Comment by WanjaMIKE** [comment]
Installing and running *jest* is well covered in the official docs. https://jestjs.io/ This video also dives deeper into that area https://www.youtube.com/watch?v=FgnxcUQ5vho This topic appears a bit over-saturated. Feel free to suggest another topic. Thanks
