### ISSUE TITLE
Concurrency Control in DBMS

### ISSUE THREAD

**Issue by abimbolataofeek** [section-engineering-education/engineering-education#6526]
#### Introduction
Concurrency control is a process of managing simultaneous operations on the database without having them interfere with one another. The concurrency control that every transaction will have some isolation which means as the transaction is getting executed nothing parallel with other transaction and the transaction effect will remain permanent and durable on the database as if the transaction has gotten executed solo, so there is no interference between transactions execution.

There are different types of concurrency control techniques that are used to achieve isolation. Those techniques are Lock-Base, Time-Stampe, Multiversion-Concurrency, Validation Concurrency, Snapshot Isolation, Multiple Granularity. These are used to ensure serializability of schedules 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

#### Article quality
In this tutorial, we are going to be taking a deep dive looking into concurrency control,  types of locks, and strategies. Its completely beginner-friendly advantages.

#### References
https://databasemanagement.fandom.com/wiki/Concurrency_Control

**Comment by WanjaMIKE** [comment]
Ensure that you fill all areas in the topic form before submitting it for approval. Thanks
