### ISSUE TITLE
How To Install MariaDB Database on Ubuntu 20.04|18.04

### ISSUE THREAD

**Issue by Bettkip** [section-engineering-education/engineering-education#6530]
### Introduction
MariaDB is a relational database that is free and open source, providing a SQL interface for data access. MariaDB's GIS and JSON features have recently been introduced to latest editions. The open source community is actively developing MariaDB, a MySQL derivative.

### What will be covered
-Intro to MariaDB databases and its features
-Installation
-Securing database server (mysql_secure_installation)
-Enable network connectivity
-Example of database creation, user, dropping

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
