### ISSUE TITLE
How To Add Extra Drive To VirtualBox VM

### ISSUE THREAD

**Issue by Bettkip** [section-engineering-education/engineering-education#6532]
When your VirtualBox VM runs out of space, you'll need to install an additional drive from your computer's hard drive. Anybody using a virtual machine knows how important it is to be able to allocate enough storage to their virtual machines. This tutorial will show you how to install an additional drive to VirtualBox.

**Comment by WanjaMIKE** [comment]
### Open Oracle VM Virtual Box Manager, select the Virtual Box for which you want to add the new disk and click on Settings.
- Click on Storage, select hard drive and click on Add a hard disk.
- Click on Create New Disk.
- Follow the on-screen instructions to create a new hard disk drive.

**Comment by WanjaMIKE** [comment]
This topic appears somehow over-saturated based on the above simple instructions.
