### ISSUE TITLE
Setup Kubernetes Cluster on Linux using Kubeadm

### ISSUE THREAD

**Issue by Bettkip** [section-engineering-education/engineering-education#6534]
### Kubernetes
Kubernetes is a free and open-source orchestrator for containerized application deployment. Google created it in 2014 as a way to run scalable, dependable systems in containers using application-oriented APIs. It has since evolved to become one of the world's biggest and most popular open-source projects. In every public cloud, Kubernetes is currently the standard API for creating cloud-native apps.
### Kubeadm
Kubeadm is used to build up Kubernetes clusters that pass the Kubernetes conformity tests or to create a minimum viable Kubernetes cluster that follows best practices. Other cluster lifecycle functions supported by Kubeadm include cluster updates and bootstrap tokens. Kubeadm is thus a useful tool for getting started with Kubernetes, orchestrating clusters, and testing apps, as well as a building element for other ecosystems.

**Comment by LinusMuema** [comment]
Hi @Bettkip 

Thanks for submitting your suggestion. After a quick google search, we found that your article has been widely covered over the internet. There are digital ocean ads too about the same. Therefore, we cannot move forward with your article. We are looking for more original content that isn't saturated on the internet. 

You are more than welcome to try out other topics of interest.

> Take note that your suggestion was missing several sections that help us get a better understanding of your topic. Please go through approved topics and see how they utilise the template.
