### ISSUE TITLE
[Languages] How to Create Custom Page Transition in Flutter

### ISSUE THREAD

**Issue by somtobe** [section-engineering-education/engineering-education#6535]
### Topic Suggestion
[lLanguages] How to Create Custom Page Transition in Flutter

### Writing sample(s): 
https://www.section.io/engineering-education/caching-logging-typography-in-flutter/
https://www.section.io/engineering-education/responsive-flutter-design-using-mediaquery-class/

#### Proposed title of article
[lLanguages] How to Create Custom Page Transition in Flutter

#### Proposed article introduction
Transitioning in a flutter application is done by the theme type used, be it Material or Cupertino theme.  For the most part when we want some alternative aesthetic and something specific to what our application needs, say a fade alongside a specific color better represents what you want rather than a size transition. It is good you know how to get it done.
 

#### Key takeaways 
- How to create their very own custom animation
- Exposure to the available transition classes provided by flutter and their various properties
- Build a flutter application specific to the transition they want.

#### References
- https://api.flutter.dev/flutter/widgets/SlideTransition-class.html
- https://api.flutter.dev/flutter/widgets/TransitionRoute-class.html

**Comment by LinusMuema** [comment]
Hi @somtobe 

Thanks for submitting your topic suggestion. The article seems like a really awesome read and I think it has some great value. However, I have one question regarding the similarity between the article and the [official docs](https://docs.flutter.dev/cookbook/animation/page-route-animation). How will your article differ from what is already in the docs?

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to link a PR. 👍
