### ISSUE TITLE
Concurrency Control in DBMS.

### ISSUE THREAD

**Issue by abimbolataofeek** [section-engineering-education/engineering-education#6537]
#### Introduction
Concurrency control is a process of managing simultaneous operations on the database without having them interfere with one another. The concurrency control that every transaction will have some isolation which means as the transaction is getting executed nothing parallel with other transaction and the transaction effect will remain permanent and durable on the database as if the transaction has gotten executed solo, so there is no interference between transactions execution.

#### Key takeaways 
At the end of this tutorial the reader would fully understand:

1. Concurrency control in database 
2. Shared Lock vs Exclusive Locks
3. Dead Locks
4. Two-phase Locking
5. Solving the double booking problem
6. Database connection pooling

#### Article quality
In this tutorial, we are going to be taking a deep dive looking into concurrency control,  types of locks, and strategies. Its completely beginner-friendly advantages.

#### References
https://databasemanagement.fandom.com/wiki/Concurrency_Control

**Comment by LinusMuema** [comment]
Hi @abimbolataofeek 

Thanks for the submission. After a simple google search, we noticed your article is widely covered on other sites like [tutorialspoint](https://www.tutorialspoint.com/what-is-concurrency-control-in-dbms) and [JavaTpoint](https://www.javatpoint.com/dbms-concurrency-control). We cannot move forward with your article suggestion as we are looking for more original content.

Feel free to explore other topics you may be interested in.
