### ISSUE TITLE
[Languages] Understanding Swing in Java

### ISSUE THREAD

**Issue by Fridasam** [section-engineering-education/engineering-education#6541]
#### Topic Suggestion
[Languages]Understanding Swings in Java

#### Proposed title of article
[Languages]Understanding Swing in Java

#### Proposed article introduction
We are in the  era where technology is the mother of all activities whether in the industries, at our homes and many more areas . Based on this, there is need to create software systems and applications that will enhance and enable people to do all the activities of the day-to-day basis. 
Swing is a set of extensible GUI components used by developers in creation of front end based Java application GUI applications.

#### Key takeaways 

1. Introduction to Swing.
2. Features of Swing.
3. Differences between Swing and AWT(Abstract Windowing Toolkit).
4. Components of Swing.
5. Creating Java Swing.

#### Article quality
This article is intended to give reader a better and deeper understanding on Swing and how its different components work to give a proper enhanced Java system.

#### References

NIL

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
