### ISSUE TITLE
[Reactjs] Use Advanced JavaScript in React Render Method.

### ISSUE THREAD

**Issue by unholydisaster** [section-engineering-education/engineering-education#6543]
#### Proposed title of article
[Reactjs] Use Advanced JavaScript in React Render Method.

###   IMPORTANT NOTE: The code and examples have been tested and work with the latest versions of React.

I recently was going through react tutorials and noticed something, most React code has minimal use of advanced JavaScript. Through the use of if-else statements and conditions such as && lot can be achieved while rendering components, From choosing the data to be rendered at specific times of the day to eye catching front-end design achievements can all be attained.

At first, I was not using advanced JavaScript in my web apps but know through this knowledge that am passing down to you I have confidence in React and I hope  by the end you will also be, lets get coding.

#### Key takeaways 
1 Render With an If-Else Condition.
2 Use a Ternary Expression for Conditional Rendering.
3 Use && for a More Concise Conditional.
4 Render Conditionally from Props.
5 Use Array.map() to Dynamically Render Elements.
6 Render React on the Server with renderToString.

#### Article quality
The content contained in the article, can be easily consumed by  newbies and as reference by experienced React developers.

#### References
[ React in depth](https://reactjs.org/docs/jsx-in-depth.html)

**Comment by LinusMuema** [comment]
Hi @unholydisaster    

This sounds like a great article that has great value to readers. Please go over grammar and writing style to improve on the article. Otherwise, topic approved. 🚀

**Comment by unholydisaster** [comment]
Hey, https://github.com/section-engineering-education/engineering-education/pull/6744
#6744 opened 13 hours ago by [unholydisaster](https://github.com/section-engineering-education/engineering-education/issues?q=is%3Apr+is%3Aopen+author%3Aunholydisaster)
16 tasks
