### ISSUE TITLE
[Languages] Java null pointer handling

### ISSUE THREAD

**Issue by adikutch** [section-engineering-education/engineering-education#6545]
Java null pointer handling

Proposed article introduction
NullPointerException is thrown whenever a program utilizes an object reference that has no value. Null references, for example, can be utilized in methods. NullPointerException is thrown whenever you try to use an object reference that has a null value... To access and alter the slots of the null object, use array-like techniques. The value "null" can be thrown as a Throwable value. It is synchronized with a null object.

After then, one must address or even stop the NullPointerException, which can be done in a variety of ways which we shall cover together with a deep understanding of how java handles null pointer exception.

Key takeaways
1. How to achieve maps and nulls
2. How to achieve lombok null checks.
3. Implementing lists and nulls.
Article quality
When handling this topic, my aim is to give out content that will be well understood by any level of learners.

References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
