### ISSUE TITLE
Micro Frontends Using Module Federation In Solid.js

### ISSUE THREAD

**Issue by oyedeletemitope** [section-engineering-education/engineering-education#6547]
#### Micro frontends Using Module Federation In Solid.js
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
**Micro-frontends allow you to develop a website or web app as a collection of elements that you can create and work on independently. In this tutorial, we'll learn about micro frontend, module federation, and how to use Module Federation to create a micro frontend in Solid.js. We'll also learn how to create and share a Micro-Frontend between Solid.JS and React.**

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
At the end of this tutorial, the readers would be able to
- Know what micro frontend is.
- How it works.
- What problem does it solve?
- create a host app
- create a remote app
- consume micro frontend.

#### Article quality
This article tends to show how flexible micro frontend is when it comes to cross-platforming as I'll also be showing how to share between different frameworks using React and Solid.js as an example. Most articles cover using micro frontend in React, angular, and others but not on Solid.js this articles cover that.

**Comment by LinusMuema** [comment]
good topic @oyedeletemitope - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.
