### ISSUE TITLE
User Registration in PHP with Login: Form with MySQL and Code Download

### ISSUE THREAD

**Issue by Denzelmwangi** [section-engineering-education/engineering-education#6551]
#### Proposed title of article

User Registration in PHP with Login: Form with MySQL and Code Download

#### Proposed article introduction

User registration with login is a fundamental part of a site. This article is tied in with building a straightforward, light-weight client enlistment in PHP with login upheld by MySQL information base. I have made client enlistment in PHP with the login script. On the point of arrival, it shows a login structure with an information exchange connect. The enlisted client can enter their login subtleties with the login structure. Once done, he/she can get into the dashboard after fruitful validation. In the event that the client doesn't have a record, then, at that point, he/she can tap the information exchange choice to make another record. The client enrollment structure demands username, email and the secret key from the client. On submission, PHP code permits enrollment on the off chance that the email doesn't as of now exist. This model code has client-side approval for approving the entered client subtleties. And furthermore, it incorporates the server-side uniqueness test. The client email is the base to actually look at uniqueness prior to adding the clients to the MySQL information base.

#### Key takeaways 

* By the end of this article, the following is expected:

1. Create user registration and login form
2. Registration and login form validation
3. Process user registration in PHP
4. PHP login authentication code
5. User dashboard
6. MySQL database script
7. Screenshot of user registration and login form

#### Article quality

There are lots of PHP components for user registration available on the Internet but this article contain weighty stuff with lots of dependencies which incorporates lightweight, secure, feature-packed and customizable code snippets which will be adequate for any website. I want to believe that we will have a decent ride from the beginning till the end.

#### References

N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Denzelmwangi 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
