### ISSUE TITLE
[Machine Learning] Univariate Time Series using Facebook Prophet 

### ISSUE THREAD

**Issue by francis966** [section-engineering-education/engineering-education#6552]
#### Proposed title of article
[Machine Learning] Univariate Time Series using Facebook Prophet 

#### Proposed article introduction
A time series is a sequence of data points that occur in successive order over some period of time. A time series allows one to see what factors influence certain variables from period to period. Examples of time series data are weather records, economic indicators, and patient health evolution metrics.  Time series forecasting is the process of analyzing time series data using statistics and modeling to make predictions and inform strategic decision-making. Time series analysis involves developing models to gain an understanding of the data to understand the underlying causes.

In time series, we have univariate, bivariate, and multivariate modeling. Univariate statistics summarize only one variable at a time, bivariate statistics compare two variables and multivariate statistics compare more than two variables. In this tutorial, we will be focusing on univariate time series modeling. 

Facebook Prophet is a procedure for forecasting time series data based on an additive model where non-linear trends are fit with yearly, weekly, and daily seasonality, plus holiday effects. It works best with time series that have strong seasonal effects and several seasons of historical data. Prophet is robust to missing data and shifts in the trend, and typically handles outliers well.

#### Key takeaways 
1. Univariate vs Bivariate vs Multivariate time series modeling.
2. Examples of univariate data.
3. Installing Facebook Prophet.
4. Dataset preparation.
5. Building NYC Energy Demand time series model.

#### Article quality
This tutorial is unique because we will compare the different types of times series: Univariate vs Bivariate vs Multivariate time series modeling. This will give a reader a detailed understanding before we focus on the univariate model. We then perform the analysis of univariate data to describe the data and find patterns that exist within it. We will then build a custom NYC Energy Demand time series model. This tutorial is detailed and step-by-step implementation.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @francis966
