### ISSUE TITLE
Cleanroom software development

### ISSUE THREAD

**Issue by edwinmain** [section-engineering-education/engineering-education#6556]
#### Proposed title of article
Cleanroom software development.

#### Proposed article introduction
Cleanroom software development is a philosophy that uses formal methods to support rigorous software inspection.
Cleanroom software development has key strategies approaches ,with the objective to zero -defect software is a relevant approach to software development.

#### Key takeaways 
Learner will be able to know how to combine mathematical based methods of software specification.
Through the combine mathematical  based methods  of software specification, learner will be able to know the designing and the correctness verification with statistical.
Learner will be able to verify software fitness for use.

#### Article quality
The article guides the learner on the process  of cleanroom software development ,where article describes each process involved  in every stage.

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles]https://www.google.com/search?client=firefox-b-d&q=Cleanroom+software+development() that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by edwinmain** [comment]
The article will be able to include clear description of software testing
as a statistical experiment.The statistical analysis will be able to
produce the estimation of the reliability to the software with level of
high confidence in the estimation,this will be cooperated with well
explained cleanroom processes and formal methods that are  used in avoiding
software defects.The learner will be beneficial to the key strategies used
in cleanroom approach software development.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
