### ISSUE TITLE
[Machine Learning] Building a Collaborative filtering recommendation model using K-Nearest Neighbors.

### ISSUE THREAD

**Issue by elishanjeche** [section-engineering-education/engineering-education#6557]
#### Proposed title of article
[Machine Learning] Building a Collaborative filtering recommendation model using K-Nearest Neighbors.

#### Proposed article introduction
A recommendation system is a subclass of Information filtering Systems that seeks to predict the rating or the preference a user might give to an item. Recommender systems are used in a variety of areas such as playlist generators for video and music services and product recommenders for online stores and content recommenders for social media platforms. They are used in sites such as YouTube, Amazon and Netflix.

There are two types of recommender models: Content-based filtering System and Collaborative filtering System.  Collaborative filtering System relies on similarities between features of the items. It recommends items to a customer based on previously rated highest items by the same customer.  Collaborative filtering system is based on the past interactions that have been recorded between users and items, in order to produce new recommendations. Collaborative Filtering tends to find what similar users would like and the recommendations to be provided and in order to classify the users into clusters of similar types and recommend each user according to the preference of its cluster.

In this tutorial we will implement the collaborative filtering model using K-Nearest Neighbors. KNN works by finding the distances between a query and all the examples in the data, selecting the specified number examples (K) closest to the query, then votes for the most frequent label. We will build a movie recommendation model using the KNN algorithms.

#### Key takeaways 
1.  Content-based filtering System vs Collaborative filtering System.
2. Types of Content-based filtering System.
3. KNN methods and functions.
4. Movie dataset preparation.
5. Implementing a movie recommendation model using KNN.

#### Article quality
This tutorial will explain the difference between  Content-based filtering System and Collaborative filtering System. This helps s reader to easily differentiate between the two types. When the reader fully understood, we will now start looking at Collaborative filtering in details. We will look a the common examples that use Collaborative filtering before we can implement a custom model from scratch. The tutorial will train a custom movie recommender model and use the model to make predictions. By the end of the tutorial, the model will be able to recommend a user similar movies.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
The grammar here is quite off. Please make sure that your article is fully ready before submitting and use tools like [Grammarly](https://www.grammarly.com/) - Approved. @elishanjeche lishanjeche
