### ISSUE TITLE
[API]Build a messaging API using Twilio’s API and Express.Js

### ISSUE THREAD

**Issue by Sodiq-123** [section-engineering-education/engineering-education#6560]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community members to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error-free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

### Topic Suggestion
[API]Build a messaging API using Twilio’s API and Express.Js

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
https://dev.to/sodiq123/building-a-user-login-system-with-express-js-and-fauna-4p32
https://dev.to/sodiq123/todo-api-with-express-js-and-mongodb-14ej

#### Proposed title of article
Build a messaging API using Twilio’s API and Express.Js

Use keyword research to improve your article's SEO.
Twilio, API, Nodejs

#### Proposed article introduction
Twilio has a couple of APIs that allow you to send and receive a high volume of SMS messages anywhere in the world. Once you get your registered Twilio phone number, you can use the APIs to manage outbound messages (“sending”) and inbound messages (“receiving”).

In this article, you will learn how to send and receive SMS messages with Node.js and Express and save the sent messages in a MongoDB database.

We will first send an SMS with Node.js and the Twilio Messages API. We'll then build an API that can send SMS messages using Express. We'll focus in this article on sending SMS messages using the third-party message API. Still, if you want to send and receive messages with Facebook Messenger, Viber, or WhatsApp, you can do that as well with the Message API.

You can extend the application we're building here to reply to incoming SMS messages or include more complex, interactive elements and give you a head start building autoresponders for your SMS needs.

#### Key takeaways 
What is Twilio
-Give an in-depth explanation to the reader on Twilio and Twilio’s message API.
-Explanation of how Twilio’s message API works.

Getting Started
-Setup Twilio account
-Set up a node server that provides the API for sending a message and the API structure.
-Explore the functionalities of the API endpoints which includes:
-Create a User ({ name, email, password })
-Log a user In (email, password)
-Adding authentication using Jwt
-Add a contact to your Twilio account
-The user can create a contact (In terms of a phone book)
-The user can get a contact by its Id
-The user can delete a contact
-The user can get all contacts
-The user can update a contact ({name, number})
-The user has contacts to send messages to (A number registered with your Twilio Account).
-Save sent messages (More like message history).

#### Article quality
The article is intended for mid-level developers. It takes an in-depth look at authentication and authorization and how to use third-party APIs which in this case, Twilio and how to add MongoDB with Nodejs.

#### References
https://www.twilio.com/blog/what-does-twilio-do
https://console.twilio.com/us1/develop/sms/try-it-out/get-set-up?frameUrl=%2Fconsole%2Fsms%2Fget-setup%3Fx-target-region%3Dus1

### Conclusion
This article takes a look at authentication and authorization, how to implement third party APIs and how to use MongoDB in your Nodejs project.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to link a PR. 👍

**Comment by hectorkambow** [comment]
FYI this article will not be eligible for payout as it was approved before - but closed before as well due to inactivity.

**Comment by Sodiq-123** [comment]
But I was told by you earlier that I can reopen when I'm ready. Also, I didn't make a PR early enough because my laptop had issues and I couldn't really do anything about it for a while. As soon as I got a new laptop and recovered what I had written from my old laptop, I immediately completed it and made a PR.
I'm sorry for any inconveniences, but can this article be eligible for payout. I won't have any delay next time.

**Comment by hectorkambow** [comment]
Totally understand - just in the interest to be fair to the rest of the PRs (and students). 

The main thing is this was approved in Feb - typically we closed inactive topics/PRs in 20 days to a month. 

If it were submitted in that time frame perhaps...the topic form have had to be reopened  (and re-approved ) as well.

**Comment by Sodiq-123** [comment]
So it still can't be eligible for payout ? 😔

**Comment by Sodiq-123** [comment]
You can move on with my article though, I'll suggest another topic after this one is published.
