### ISSUE TITLE
Overview of LANs

### ISSUE THREAD

**Issue by Aderonke1975** [section-engineering-education/engineering-education#6561]
AN OVERVIEW OF LANs
![istockphoto-184281306-612x612](https://user-images.githubusercontent.com/99263187/153418141-b1bcd416-34ae-4717-af15-5eaebd7cf0b3.jpg)

Image from Istockphoto.com
Local Area Network also known as LAN is simply a computer network that interconnects other computers via Ethernet or wifi within a limited space which means the network cannot be shared to other computers outside the space unlike the Wide Area Network also known as WAN.
It is used in limited areas like school laboratories, office buildings, residence and so on. 
TYPES OF LANs
There are 2 types of LANs which include the Small Office Home Office SOHO and Enterprise LANs.
~Small Office Home Office SOHO LAN
![gbps-optical-media-converter-sfp-module-connected-to-ethernet-port-soho-router-office-91639069](https://user-images.githubusercontent.com/99263187/153418354-3dc807ab-c538-4717-b13b-858418cee6c9.jpg)

Image from dreamstime.com
This type of LAN uses Ethernet cables to link different devices (phones, laptops, desktops and so on) to one of the switch ports. It is limited to not less than 10 devices within a specified area and the disadvantage is that it has lower performance.
~Enterprise LAN
![images (5)](https://user-images.githubusercontent.com/99263187/153418454-ee1aafaa-f680-4539-95b8-fad465173de3.jpeg)

Illustration from Cisco.com

The enterprise LAN is similar to the SOHO LAN as they perform almost the same functions.The only difference is that the enterprise LAN is applied on a much larger scale. It is used in large buildings for instance Wireless LANs are installed in each floor of storey buildings like it's in the illustration above to ensure faster connections and performance. The engineers install the Ethernet cabling or wifi from a wiring closet in which LAN switches are installed to offices and conference rooms where internet connection might be needed.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
