### ISSUE TITLE
[Language] Sending "Contact Us" form data as Email without involving server | Smtpjs and Mailtrap

### ISSUE THREAD

**Issue by HillaryKiprono** [section-engineering-education/engineering-education#6562]
#### Proposed article introduction
This Proposed article introduction will show to convert data gathered from the contact form into and email using the Stmpjs library without involving the backend. As an SMTP server Mailtrap is used. The languages used are HTML, CSS, and vanilla Javascript

#### Key takeaways 
- The reader should be able to  understand Smtpjs CDN and Mailtrap Registration
- The reader should be able to understand  SMTP configuration.
- The reader should be able to understand how to write javascript code to convert Form data into an Email.

#### Article quality
-My article will be unique in such a way that it will not involve the backend.
-It will involve the use of pure Javascript programming language.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @HillaryKiprono 

You have copied the exact same name from: https://www.youtube.com/watch?v=lZrDcjyoecY
This is already covered.
