### ISSUE TITLE
A   TUTORIAL ON HOW TO PERFORM WEBSCRAPPING IN R AND PYTHON

### ISSUE THREAD

**Issue by Casmielsantiago** [section-engineering-education/engineering-education#6563]
### Topic Suggestion
.A   TUTORIAL ON HOW TO PERFORM WEBSCRAPPING IN R AND PYTHON

#### Proposed title of article
A   TUTORIAL ON HOW TO PERFORM WEBSCRAPPING IN R AND PYTHON

#### Proposed article introduction
Suppose you need to extract large amounts of data from a website copy pasting might not be a viable solution. This is where web scraping comes in handy. Most of this data is unstructured data in an HTML format which is then converted into structured data in a spreadsheet or a database so that it can be used in various applications such as training machine learning algorithm.

I will use R's rvest package and python's Beautiful soup library  to tackle this problem and also compare the time it takes to complete the task in both R and python .I will use a similar scraper in R and python. I will use a dataset from site that allows web scrapping.
 
#### Key takeaways 
-The student will be able to build a scrapper in both R and python,
-The student will be educated on the application of web scrapping
-The student will be able to understand how web scrapping happens in R and python

#### Article quality
My article is beginner friendly and encompasses web scrapping in R and python extensively.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
We have multiple articles covering this topic. Please feel free to suggest an alternate topic to explore. 🚀 @Casmielsantiago
