### ISSUE TITLE
Automated Smart Replies using ML kit in Android

### ISSUE THREAD

**Issue by robert-muriithi** [section-engineering-education/engineering-education#6566]
#### Proposed article introduction
Smart Replies are contextually one-touch responses that help the user to reply to an incoming text message (or email) efficiently and effortlessly. Smart Replies have been highly successful across several Google products including Gmail, Inbox and Allo. The Smart Reply model is targeted towards text chat use cases. It has a completely different architecture from its cloud-based counterparts, and is built specifically for memory constraints devices such as phones. 

For a learner looking do develop an application with smart and automated replies, this tutorial will fit him/her well.  The tutorial will expound more on firebase ML rather than using Tensor Flow lite.

#### Key takeaways 
- What are smart Replies
- What are the benefits of Smart reply in chat application
- How Firebase ML kit works with Tensor Flow lite
- Step by step implementation of Smart Replies in android

#### Article quality
Unlike other blog posts, my article will first provide an overview of how smart replies is done using Tensorflow through training models. This will narrow down to using Firebase ML kit illustrating how Tensorflow models can be used in Firebase ML kit.

#### References
https://developers.google.com/ml-kit/

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @robert-muriithi 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
