### ISSUE TITLE
Recognizing when VSLM is used

### ISSUE THREAD

**Issue by Aderonke1975** [section-engineering-education/engineering-education#6569]
HOW TO RECOGNIZE WHEN VARIABLE LENGTH SUBNET MASK IS USED
![images (6)](https://user-images.githubusercontent.com/99263187/153477913-f1558490-74ed-42d9-91b0-f8caf051a833.jpeg)

Image from ciscopress.com
Variable Length Subnet Mask (VSLM) aids the division of IP address space into a distinct hierarchy of different sizes of subnets which enhances subnets usability.VSLM is considered to be used by an internetwork when multiple subnet masks are used for different subnets of a single classful network.
However, not all internetwork that uses more than one mask must be using VLSM except if it is of a single classful network. VLSM can only be supported by classless routing protocol

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Aderonke1975 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
