### ISSUE TITLE
Building a simple keyboard using Anvil

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#6570]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

[Languages] Building a simple keyboard using Anvil

Use keyword research to improve your article's SEO.

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Anvil is a free and open-source drag and drop web app builder. It is equivalent to the likes of Gradio application. The framework uses Python only. No HTML, no CSS, and Javascript. This tutorial will leverage this framework to build a functional keyboard similar to the one on your computer. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to:
- Create a web page with Anvil
- Create all the components needed for a calculator, i.e., buttons, image, and text box.
- Create a create panel to replicate how a keyboard appears.
- Implement the different button callbacks
- Test the functionality of the keyboard
- Style the keyboard
- Publish the web app

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Anvil is a fairly new framework. I still haven't seen any build involving building a functional keyboard using the framework.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

[Anvil](https://anvil.works/)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Bayler 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
