### ISSUE TITLE
 How to authenticate users in a React App using Firebase

### ISSUE THREAD

**Issue by prince-joel** [section-engineering-education/engineering-education#6572]
### Topic Suggestion
 How to authenticate users in a React App using Firebase

### Writing sample(s): 
https://www.section.io/engineering-education/implementing-totp-2fa-using-flask/

#### Proposed title of article
 How to authenticate users in a React App using Firebase

#### Proposed article introduction
Sometimes, when building an application that involves using special keys to validate users, you may not want to mess with Backend. Well, this is where Firebase authentication may come in handy. In this tutorial, we will build a simple React application, which will constitute a sign-up page that will use Firebase and its hooks to redirect users to the home page when users successfully sign-up and log in with their correct credentials.

#### Key takeaways
Readers will learn how to authenticate users in any React application with Firebase.
Readers will learn all about Firebase, its hooks, and its authorization functions.
Readers will learn how to use React hooks and the `react-router-dom` to allow users to navigate through the different aspects of the application.
Readers will also learn how to store user credentials in the Firebase store. 

#### Article quality
This article is unique because of its in-depth approach towards making the readers understand the concept of “Authentication” in “React” with “Firebase.” These three keywords will also help to boost the article’s SEO ranking

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @prince-joel 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
