### ISSUE TITLE
Using big data analytics to fight cybersecurity threats 

### ISSUE THREAD

**Issue by Petekavinsky** [section-engineering-education/engineering-education#6575]
### Topic Suggestion
Fighting cybersecurity threats with big data

#### Pre-submission advice
There are three main challenges businesses are running into with big data protecting sensitive and personal information, Data rights and ownership, and not analyzing the data. But what are the threats and opportunities involved in Big data and cybersecurity?

Big Data is generally defined as being dense in variety, velocity, and volume. Big data has ushered in new analytics and security solutions to protect data and prevent future cyberattacks from a cyber security standpoint.
But just as big data has opened up new possibilities for cyber security teams, it has also allowed cybercriminals to access mass quantities of sensitive and personal information through the use of advanced technologies.

Cybersecurity analytics: Increasingly sophisticated attack methods used by cybercriminals and the growing role of malicious insiders in several recent large-scale security breaches indicate that traditional approaches to information security can no longer keep up. So, where does security analytics fits in? 

#### Key takeaways
After participating in this tutorial, you should fully understand
- What Big Data and Cybersecurity is and its purpose.
- Understand major points where cybersecurity analytics fits in

#### Article quality
After this lesson, you will develop an insight into the level of awareness and current approaches in information security fraud detection in organizations worldwide. Unlike some other blogs relating to security analytics, I will closely work with you and show you in-depth measures and plans of significant data security analytics initiatives across different sectors.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Petekavinsky 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
