### ISSUE TITLE
Creating a discussion website in Django

### ISSUE THREAD

**Issue by junior-01** [section-engineering-education/engineering-education#6576]
#### Proposed title of article
Creating a discussion website in Django

#### Proposed article introduction
More often issues are raised and they require an interaction between two or more parties to find a solution, A discussion website built in Django (Python framework), will be of a great deal in developing such website because I found it easier and quick to develop such website. Also, as time goes by I will tackle other skills necessary in Django and as a community grow further our skills based on Django framework.
Other languages that will be used are CSS, JavaScript and html.

#### Key takeaways 

1. What is Django framework and how it work.
2. How to add JavaScript, html and CSS code into Django framework.
3. How to create an admin.
4. How to send images in Django.

#### Article quality
Unlike other blogs, this article will add other features like sending images in a discussion which is not covered by any other blog.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @junior-01
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
