### ISSUE TITLE
Getting started with Recycler Building using BRVAH

### ISSUE THREAD

**Issue by AndrewOdera** [section-engineering-education/engineering-education#6577]
#### Proposed title of article
Getting started with Recycler Building using BRVAH

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

BRVAH It’s a great open source project on Github. Its main function is to help us use Recyclerview control more efficiently and to deal with the Adapter of common requirements in the project. It’s very convenient to use.

BRVAH provides us with BaseQuick Adapter in general, and Adapter in several specific requirements, BaseMultiItemQuick Adapter for complex class layout lists, BaseItemDraggable Adapter for dragging and dropping class lists, and BaseSection QuickAdapter for lists with Section Header View.

#### Key takeaways 
By the end of this tutorial the learner will be able to:

- Set a build.gradle config
- Use xml files to display the outline of the brvah
- Implementing Recyclerview to listen for event
- Make drag and drop Selection from to the view

#### Article quality
BRVAH It’s a great open source project on Github. This article will show how to build recycler from it.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.  @AndrewOdera 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
