### ISSUE TITLE
[Security]What are Honeypots?

### ISSUE THREAD

**Issue by kvardhan10** [section-engineering-education/engineering-education#6578]
#### Proposed title of article
What are Honeypots?

#### Proposed article introduction
INTERNET - one thing that people cannot live without. Almost everything in this world put together by humans will crumble to dust without the internet. Everything either runs or relies on the internet, be it the private sector, the public sector, or the social sector. Hands down, it has become a prominent aspect of our lives. As practical as it sounds, running firms, activities, and businesses over the internet may become very infeasible if the control is lost.

Although knowing and working with the internet remains captivating, it is a place with numerous malware and viruses. Data from users is also targeted by malicious parties. This can result in ransomware, scareware, unsolicited message spamming, IoT attacks, and more. To prevent all of this - Honeypot comes into the picture.

#### Key takeaways 
After reading this article the readers will be able to understand:
- What is a Honeypot
- How does it work
- Types of honeypots
- Its advantages and disadvantages

#### Article quality
This article is written for learners to help them get started in the domain of cybersecurity. Honeypots are one such thing that will help the readers in learning about one of the many topics in this area. The quick description and its functioning are enough for readers to understand the types of threats that exist in the computer world and will help them in avoiding those threats.

#### References
https://en.wikipedia.org/wiki/Honeypot_(computing)
https://www.kaspersky.co.in/resource-center/threats/what-is-a-honeypot

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
