### ISSUE TITLE
[Networking] Managing Web Services in Linux

### ISSUE THREAD

**Issue by splashtonia** [section-engineering-education/engineering-education#6580]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Managing Web Services in Linux

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Tools like `wget` and `cURL` are essential tools that every IT person needs to know. `cURL` allows you to transfer files from the shell over protocols like HTTP, HTTPS, FTP, SFTP, or SCP. This feature allows us to control websites remotely.  On the other hand,` Wget` is a command-line utility for downloading files from the web. With Wget, you can download files using HTTP, HTTPS, and FTP protocols. Wget provides a number of options allowing you to download multiple files, resume downloads, limit the bandwidth, recursive downloads, download in the background, mirror a website, and much more. This tutorial will use these two tools to show you how you can manage web services using them.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to:

- Set up a website on Linux using one command
- Talk to websites using a command line instead of using a website
- Changing directories in Linux
- Changing ports in Linux
- Learn how to use cURL to manage services.
- Learn how to use wget to manage services

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

This tutorial shows our readers how to create a website using only one command. It will show you how to talk to this website using the command line. That's a unique approach that not so many websites cover. It'll also show how to manage these website using web services such as curl and wget.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [Wget](https://linuxize.com/post/wget-command-examples/)
- [cURL](https://curl.se/)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @splashtonia 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
