### ISSUE TITLE
[Languages]Object Detection using OpenCV in Python

### ISSUE THREAD

**Issue by adikutch** [section-engineering-education/engineering-education#6591]
#### Proposed title of article
Object Detection using OpenCV in Python

#### Proposed article introduction
OpenCV is a Python library that plays an important role in image and video processing. It is also useful in computer vision and also plays a crucial role in machine learning. We are also able to process human being handwriting, their faces and such thanks to OpenCV library in Python

Therefore in this  article, since we have mentioned various tasks that can be performed and accomplished using OpenCV, we are going to put our focus on a section of OpenCV that is used in image detection. And we shall go a step further in implementing this by using well explained examples for the simplicity of our learners.

#### Key takeaways 
1. Detecting an object in an image.
2. How to implement object detection
3. How to install the requirements that are required to perform object detection.
#### Article quality
My aim when writing this article is to produce content that will be of high quality and that will be well understood by our learners.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @adikutch 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
