### ISSUE TITLE
Wavelet transform analysis of 1-D signals using Python

### ISSUE THREAD

**Issue by collince777** [section-engineering-education/engineering-education#6594]
#### Introduction
A wavelet is a mathematical function useful in digital signal processing and image compression. A wavelet transform is a way of breaking down (“transforming”) a high-resolution signal into two parts. These parts are the low-resolution approximation part and a part that shows the details about what changed (“detail coefficients”). Very importantly, it does this in a way that allows us to recover the original from the approximation.
In this tutorial, we will see how to perform the wavelet transform of the 1-D signal. Also, we will look at the various packages used for this analysis. The commands and a sample of how to use such commands in an application.

#### Key takeaways 
- Distribution of Anaconda with Spyder IDE.
- PyWavelet package of Anaconda.
- Proper understanding of dwt, idwt, wavedec and waverec Python commands with example codes.
- Sample wavelet transform of audio signals.

#### Article quality
This article covers into detail the wavelet transform with the various python packages and commands involved. It also give an example on how to implement these commands.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @collince777 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
