### ISSUE TITLE
[LANGUAGES] Perfoming Update and Delete Operations on your Spreadsheet files using the Apache POI library in Android

### ISSUE THREAD

**Issue by vinstex** [section-engineering-education/engineering-education#6604]
### Topic Suggestion
Performing Update and Delete Operations on your Spreadsheet files using the Apache POI library in Android

### Writing sample(s): 
[Here](https://www.section.io/engineering-education/android-excel-apachepoi/) is my latest sample.

#### Proposed title of article
Performing Update and Delete Operations on your Spreadsheet files using the Apache POI library in Android

#### Proposed article introduction
A good application should be able to handle all CRUD operations. Owing to that, we will build upon [this](https://www.section.io/engineering-education/android-excel-apachepoi/) article which talks about creating and reading Spreadsheets created using the Apache POI library. We will have a walkthrough on editing cells, renaming columns, deleting sheets &  workbooks, etc.

#### Key takeaways 
The reader will learn about:
- Performing Update and Delete Operations on Apache POI-created spreadsheets.
- Performing Update and Delete Operations on other types of spreadsheets.
- Using Kotlin to achieve this.

#### Article quality
It will be easy to follow with a step-by-step guide. Most importantly, I haven't seen a blog talking about these operations in Android.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @vinstex 

This sounds like an interesting topic. Please make sure to focus more on content that you hadn't covered in your previous article. Topic approved.

🚀
