### ISSUE TITLE
[Languages] The Ultimate Guide to Vue Components

### ISSUE THREAD

**Issue by julie-techie** [section-engineering-education/engineering-education#6614]
### Topic Suggestion
The Ultimate Guide to Vue Components

#### Proposed title of article
The Ultimate Guide to Vue Components

#### Proposed article introduction
Vue Components are one of the important features of VueJS that creates custom elements, which can be reused in HTML. Components can be reused as many times as you want or used in another component, making it a child component. Vue components are written as a combination of JavaScript objects that manage the app's data and an HTML-based template syntax that maps to the underlying DOM structure.

This article will share everything Vue developers need to know about components, including in-depth examples of class, dynamic, single file, functional, and table components.

#### Key takeaways 
1. Vue components introduction
2. Types of components this article will cover

- Class components
- Dynamic components
- Single file components
- Functional components
- Table components
3. For each component this guide will provide use cases, a description of how it works and code samples.

#### Article quality
This detailed guide will share everything Vue developers and readers need to know about  Vue components, including in-depth examples of class components, dynamic components, single-file components, functional components, and table components.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @julie-techie 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by julie-techie** [comment]
@ahmadmardeni1, This topic is not widely covered at all. The kind of content this article aims to cover is not covered on other blogs if you have a keen look. These are some of the resources published online:
https://v2.vuejs.org/v2/guide/components.html
https://snipcart.com/blog/vue-component-example-tutorial
You will notice what this is covering is different. It's in-depth and is unique. Readers will gain a lot from it.
Kindly consider this because it will pass value to readers. Regards!

**Comment by ahmadmardeni1** [comment]
Hey! Thanks for @ing me.

@WanjaMIKE  Can you take a look, please? I still believe that all the key takeaways are already covered on other blog sites. But I would love to know your thoughts. I may be wrong.

**Comment by WanjaMIKE** [comment]
I agree @ahmadmardeni1
