### ISSUE TITLE
Building a Google Direct Download LInk Generator with Vanilla JavaScript

### ISSUE THREAD

**Issue by shegz101** [section-engineering-education/engineering-education#6615]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

### Topic Suggestion
Building a Google Direct Download LInk Generator with Vanilla JavaScript

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Suppose, for instance, you have a file (it could be music, movie, or a document file) stored in the google drive application, and you wish to share the file with friends. You will first right-click on the file, click the get link option, then you will copy the link which you can now share with friends. When the user you share the link with paste it on google, the user (which could be your friend) will notice that the file won't open directly on google's browser but will open by automatically opening the google drive.

In this article, we'll build a web app that generates a direct link to download files stored in our google drive, the app also helps us generates links that we can use to embed files that are stored in our google drive into our personal website. You can simply copy the embedded link generated from the web app we'll build, then paste it in your personal website. For instance, you have a video file stored in google drive, after going through the aforementioned steps to generate the embedded link, create a simple web app, then paste the embedded link, you'll notice that the video is now live on your webpage - you can now access the video (it now plays on you web app). In simple terms, we're building a web app that would generate a link that can help us download files stored in our google drive, directly to our local desktop by just copying the link we get from google drive and paste it in the web app we're building.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1.) The reader will learn how to use an iframe to embed the video file.
2.)  The reader will learn how to use the audio tag to embed the music file.
3.) How to use array methods like includes and replace methods.
4.) Readers will learn how to copy links to clipboards using JavaScript.

#### Article quality
In this article, I will guide readers in a step-by-step method on how to build this web app from scratch, explaining how to style this web app, link it to google drive, explain some needed array methods. I will also build another mini web app, where I will test the app if it's functioning well, by embedding the links generated, so it can be displayed on the browser through an HTML file and not from google drive.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
