### ISSUE TITLE
[Machine Learning] Building a Multivariate time series model using Facebook Prophet

### ISSUE THREAD

**Issue by charles721** [section-engineering-education/engineering-education#6620]
#### Proposed title of article
[Machine Learning] Implementing a Multivariate time series model using Facebook Prophet

#### Proposed article introduction
Time series is a series of data points indexed in time order. Most commonly, a time series is a sequence taken at successive equally spaced points in time. We analyze time-series data in order to extract meaningful statistics and other characteristics of the data. Time series forecasting is used to predict future values based on previously observed values.

Time series datasets are different and are categorized into three groups: Univariate, Bivariate, and Multivariate. Univariate data –
This type of data consists of only one variable. The analysis of univariate data is thus the simplest form of analysis since the information deals with only one quantity that changes. Bivariate data- This type of data involves two different variables. The analysis of this type of data deals with causes and relationships and the analysis is done to find out the relationship among the two variables.  Multivariate data – When the data involves three or more variables. It is similar to bivariate but contains more than one dependent variable.

In this tutorial, we will use multivariate data to build a time series model. The dataset will have more than three variables. We will then use Facebook Prophet for time series analysis.

#### Key takeaways 
1. Difference between Univariate, Bivariate, and Multivariate datasets.
2. Preprocessing the multivariate dataset.
3. Time series analysis using Facebook Prophet.
4. Building a sales prediction model.
5. Time series forecasting.
6
#### Article quality
This tutorial will enable a reader to distinguish between univariate, bivariate, and multivariate time series. We will use practical examples to give an in-depth understanding of the three types. This article will cover time series analysis and decomposition using Facebook Prophet. It will explain how to handle the multivariate dataset and how we will use it to build a multivariate model. Using the steps in this article, we will be able to build a custom sales prediction model and the model will be used for forecating.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @charles721 

Thanks for submitting your article suggestion. However, after a google search of your article title. We found multiple Youtube videos covering it. Due to this, we cannot move forward with your article suggestion. Feel free to explore other topics.
