### ISSUE TITLE
Working with cron command in Linux

### ISSUE THREAD

**Issue by Ken-muriithi** [section-engineering-education/engineering-education#6622]
#### Proposed title of article
Working with cron command in Linux

#### Proposed article introduction
The cron is a Linux-like operating system software program that automates scheduled tasks. It is a daemon process that runs in the background and conducts the specified activities when an event or condition occurs without human input. A system administrator may schedule repetitive tasks to execute automatically in the background at regular intervals by defining a set of commands using cron. It allows users to do scheduled tasks on a regular basis and file synchronization. Cron looks for scheduled jobs periodically and executes them when the planned time fields match the actual time fields. Crontab is also the program used to change the schedule. It is controlled by a crontab file, which specifies shell instructions to execute frequently.

#### Key takeaways 
The reader will understand:
- What is cron and how does it relate to Linux
- Cron vs crontab in Linux
- Variety of reasons why cronjobs are useful in Linux.
- How to work with cron in Linux

#### Article quality
This will be an in-depth coverage in all the aspects of this concept and stepwise where applicable. This will be beginner-friendly in learning how to add or modify and listing crontab. It will be interesting to read and understand.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
