### ISSUE TITLE
[Languages] Multithreading in python

### ISSUE THREAD

**Issue by 07munene** [section-engineering-education/engineering-education#6625]
#### Proposed article introduction
Multithreading is defined as the ability of a processor to run multiple threads at the same time. Like multiprocessing, multithreading is a way to achieve multitasking. 
In Python, the thread module provides a very simple and intuitive API for creating multiple threads programmatically. 

This article  will help the reader understand multithreading and the various techniques of multithreading and see  how to actually implement these techniques  in Python. It also describes which technique to use, depending on whether the application is bound to I / O or CPU.

#### Key takeaways 
1. Multitasking and types of multitasking
2. Threading
3. Techniques of multithreading
4. Applications of multithreading in python

#### Article quality
This will be a detailed article covering all  aspects of this concept explaining to the reader important concepts that are not available in the documentation or other platforms. My goal is to make it more beginner-friendly, simpler and easier to understand. Learn more about multithreading and multithreading with and without synchronization.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
