### ISSUE TITLE
Introduction to Frequent Itemset Mapping with Python

### ISSUE THREAD

**Issue by OMONDIELLY** [section-engineering-education/engineering-education#6626]
### Topic Suggestion
Introduction to Frequent Itemset Mapping with Python

#### Proposed title of article
Introduction to Frequent Itemset Mapping with Python

#### Proposed article introduction
Have you ever been to a shop to purchase an item and you end up buying other items you had not planned? Often, that is frequent itemset mapping at playing. Organizations are now building algorithms that implement frequent item set mapping in order to push sales, recommend content and items, and also to create knowledge bases from a target group (customers).
In this article, we'll learn what frequent itemset mapping is, its key concepts, and also application areas. In the end, we'll create a simple frequent itemset mapping table.

#### Key takeaways 
1. What is a frequent itemset?
2. Why frequent itemset mapping?
3. Key concepts of itemset mapping.
4. Application areas of frequent itemset mapping.
5. Creating a frequent item set mapping.
6. Conclusion.

#### Article quality
This article will help the reader understand concepts behind market basket analysis and association rule mining algorithms. Besides, it will be a hands on article where the reader will learn as he/she practices.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
good topic @OMONDIELLY - approved. Thanks for submitting your article and we look forward to reviewing and hopefully publishing it. I’m sure our readers will enjoy and find your article very beneficial.
