### ISSUE TITLE
Getting started with panda's library functions map( ) and apply( )  and R'S apply function collection for data manipulation

### ISSUE THREAD

**Issue by valentineomondi99** [section-engineering-education/engineering-education#6627]
### Topic Suggestion
Getting started with panda's library functions map( ) and apply( )  and R'S apply function collection for data manipulation

#### Proposed title of article
Getting started with panda's library functions map( ) and apply( )  and R'S apply function collection for data manipulation

#### Proposed article introduction
Data manipulation is one of the techniques in the life cycle of data analysis. The ultimate goal is to complete a task as fast as possible and by consuming less memory. This article will explain how you can use apply(), map(), and applymap () in python and the apply function collection in R to achieve it, and when to use one and not the other in the respective programs. There are several reasons why you may need data preprocessing, for example :changing units (eg data set is in kg and you need it in pounds),changing units (e.g data set is in kg and you need it in pounds),doing some mathematical transformation (log, root, etc),lowercasing or capitalizing strings.

The article encompasses core details on how to manipulate data

#### Key takeaways 
-The student is introduced to apply family functions in R
-The student will be familiar with core details on how to manipulate data
-The student will be introduced to map, apply and mapapply methods in python

#### Article quality
-Each case is explained well with problem methods and the use case of each method will be explained extensively

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
