### ISSUE TITLE
Conditionals in Swift

### ISSUE THREAD

**Issue by Amayo-Amayo** [section-engineering-education/engineering-education#6631]
#### Introduction
In swift, conditionals are used to decide which code should be run at what time.   Conditionals are used to make decisions in a Swift code. The conditionals are with if, else if and else. If this occurs, take action. Control flow is used to manage the way the code flows.

In this article, we’ll learn the types of conditionals and how to use them in a Swift code. We'll look at boolean logic, its expressions and how it affects the execution of conditionals.

#### Key takeaways 
By the end of this article the reader should be well equipped with the following:
1. Definition of a condition in swift
2. Types of conditionals
3. How to use conditionals
4. Expressions and Boolean Logic and how it affects the execution of conditionals
 
#### Article quality
This will be a distinctive article with detailed information. In this article, I will use basic language to ensure that anybody reading it understands the contents. I'll make sure that this article is useful to the whole EngEd and that it goes above and beyond official documentation.

**Comment by WanjaMIKE** [comment]
Conditional statements are a common thing, especially in official documentation.
