### ISSUE TITLE
[Languages] Understanding POST and GET Requests in Java

### ISSUE THREAD

**Issue by Su-sid** [section-engineering-education/engineering-education#6637]
### Topic Suggestion
Languages
### Writing sample(s): 
[Network troubleshooting using traceroute](https://www.section.io/engineering-education/network-troubleshooting-using-traceroute/)

#### Proposed title of article
Understanding Post and Get Requests in Java

#### Proposed article introduction
The modification and display of data is a critical activity in every application. Programmers utilize many techniques to read, change, or delete data from a database. These various ways are standardized so that developers may utilize the same principles while dealing with different databases.  There are five basic techniques for data modification and presentation between a server and an application, over a http connection. POST, GET, PUT, PATCH, and DELETE are the commands. The article will concentrate on two of the five CRUD operations. That is GET and POST requests. 
#### Key takeaways 
After reading the article the reader will know:
- What are GET and POST requests
- Characteristics of GET and POST requests 
- Differences between the two requests 
- How to implement the two methods using the HttpURLConnection and Apache HttpClient classes.

#### Article quality
Other articles and official documentations that relate to this topic suggestion only feature an explanation on how to setup and send the two requests. They however fail to present an in depth explanation on the anatomy of the two requests that this article will include. 

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
