### ISSUE TITLE
[Languages]Message Automation with Pywhatkit in Python

### ISSUE THREAD

**Issue by nduta-ndush** [section-engineering-education/engineering-education#6638]
### Topic Suggestion
Languages
### Writing sample(s): 
N/a

#### Proposed title of article
Working with Pywhatkit for Message Automation in Python

#### Proposed article introduction
Ever been in a scenario where you had to send WhatsApp messages to a group of people? Or have you ever been in a position to send a message at a specific time but you are busy or its late that you fail to send the message? That is  where pywhatkit, a python library, comes in the picture. The library allows a developer to develop a script they can use to automate messages on WhatsApp. 

#### Key takeaways 
The reader will be able to understand how to :
- How to use the pywhatkit to send a message to a single user on their WhatsApp.
- How to use the python library to send a single message to a list of users on WhatsApp at once. 
- How to include a time function for sending a message after a given time. 

#### Article quality
Most article on the web only include a short explannation on how to send a single whatsapp message to a single user. however, this article features an explantion on how to send a message to a list of different users on whatsapp. also, the article also includes how to use a text file as your source of data for either the message body or user list.  
#### References
[Automating your Whatsapp messages](https://www.geeksforgeeks.org/automate-whatsapp-messages-with-python-using-pywhatkit-module/ )

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @nduta-ndush 

Thanks for submitting your article suggestion. However, there are far too many Youtube videos and articles on the internet that cover your topic area. Because of this, we cannot move forward with your article.

Feel free to explore other topic areas.
