### ISSUE TITLE
An Introduction to Decentralized Finance

### ISSUE THREAD

**Issue by corpsgeek** [section-engineering-education/engineering-education#6643]
### Topic Suggestion
An Introduction to Decentralized Finance

### Writing sample(s): 
https://www.section.io/engineering-education/an-introduction-to-blockchain-architecture/
https://www.section.io/engineering-education/structuring-large-applications-with-blueprints-and-application-factory-in-flask/

#### Proposed title of article
An Introduction to Decentralized Finance

#### Proposed article introduction
[Blockchain] Decentralized Finance commonly attributed as DeFi is a sector of the Blockchain ecosystem that has its key point is in the transformation of traditional finance ecosystem into a system where there is an absence in custody and settlement, censor of transaction execution and protocol governance by a central authority.

#### Key takeaways 
- Defining DeFi
- How DeFi is Built and The Different Roles in DeFi
- The Layers in the DeFi Stack
- DeFi Building Block and Services
- Risks in DeFi
- Structures in DeFi Security

#### Article quality
This article covers all aspects of DeFi in a basic manner such that a new entrant in the blockchain world won't be swayed by the complex terms in this space. The goal is to ensure the concept is easy to grab by a beginner and also makes it easy for intermediate and advanced users to have a reference article to refresh their memory from an introductory perspective.

**Comment by ahmadmardeni1** [comment]
Great topic - Approved. @corpsgeek

**Comment by corpsgeek** [comment]
Cool
