### ISSUE TITLE
Understanding Probability Distributions and their Simulations in R

### ISSUE THREAD

**Issue by BejaminNaibei** [section-engineering-education/engineering-education#6652]
#### Proposed title of the article

Understanding Probability Distributions and their Simulations in R

#### Proposed article introduction
When working with distribution, we typically want to know one of the four things below.

1. The density pdf of a particular value.
2. The distribution CDF.
3. The quantile value corresponding to a particular probability.
4. A random draw of values from a particular distribution.
R has functions for obtaining density, distribution, quartile, and a random value.

The general R naming is given as:
- pname: This calculates the density at input X
- pname: This calculates the cumulative probability density(CDF) at input X
- qname: This calculates quartile at an input X
- rname: This generates a random draw from a particular distribution

where the 'name' in all the four cases above represents the name of the given distribution.

Random value generation is a common activity in machine learning especially in Bayesian statistics where the posterior distribution can be intractable and therefore difficult to estimate parameters of interest from them. In such cases, we draw samples randomly from them using methods such as Monte Carlo simulation which is then used to estimate the population parameters. For the learner to be able to advance to such a level, first they should know the basics of how we draw samples from a certain distribution.

In this article, we will cover both the continuous and discrete probability distributions and how we simulate them as well as drawing samples from such simulated distributions. 

#### Key takeaways 
1. What's the probability distribution
2. What is the continuous and discrete probability distributions
3. Under the continuous probability distributions, the learner will know:
  - Uniform distribution; its pdf and how to simulate its distribution
  - Normal distribution; its pdf and how we simulate its distribution. Since the normal distribution is highly applicable in the real world, we shall have some application problems which we will learn how we can solve them using R instead of solving by hand.
  - Chi-Square distribution; how to simulate and solve its problems using R
  - Student-distribution; how to simulate and solve its problems using R
  - Exponential distribution; how to simulate and solve its problems using R
4. Under the discrete probability distribution the learner will know:
  - Binomial distribution: Here we will solve some practical problems using R code.
  - Poisson distributions: We will learn how to solve probability problems of Poisson distribution using R.
  
 5. How to draw samples from the simulated distributions

#### Article quality
  This article aims to make the learner able to solve any probability problem using R software instead of doing so by hand as in practice some problems might be highly challenging to address by hand. So, it will cover the topic in-depth and ensure clarity of the content so that the learner can grasp the content very easily.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @BejaminNaibei 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to link a PR. 👍

**Comment by WanjaMIKE** [comment]
Closed #6652 via 7440
