### ISSUE TITLE
How to use the Simscape electrical toolbox for physical modelling

### ISSUE THREAD

**Issue by florenceakinyi** [section-engineering-education/engineering-education#6653]
### Topic Suggestion
How to use the Simscape electrical toolbox for physical modelling

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-perform-parallel-computing-using-matlab/

#### Introduction
Simscape Electrical toolbox is a toolbox that contains libraries used to model and simulate electrical and electro-mechanical systems. This toolbox is more accurate and time-saving than Simulink. Simscape Electrical helps you develop control systems and test system-level performance. You can parameterize your models using MATLAB variables and expressions and design control systems for electrical systems in Simulink.
This article will look at how to use the Simscape Electrical toolbox to model the various physical models. We will see the difference between Simulink and Simscape and a sample model using this toolbox. Also, we will see the various libraries for this toolbox

#### Key takeaways
- Difference between Simulink and Simscape in consideration to the model.
- Building and simulating a model in Simscape.
- Simscape modelling.

#### Article quality
This article shows the step to step way of using this toolbox to create a physical model.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
This is out of our preferred topics-area.  
Please feel free to suggest an alternate topic to explore. 🚀
