### ISSUE TITLE
Introduction on Ember

### ISSUE THREAD

**Issue by 08-dev-verma** [section-engineering-education/engineering-education#6654]
#### Topic Suggestion
Introduction on Ember

#### Proposed title of the article
Introduction on Ember

#### Proposed article introduction
Ember.js is a free JavaScript web framework that follows the Model–View–View Model (MVVM) architecture. By combining popular idioms and best practises into the framework, developers may design scalable single-page web apps.

It provides a more full MVC pattern than other popular JavaScript application frameworks, as well as capabilities to help you design apps for the web of the future. It's also one of the more opinionated frameworks out there, depending primarily on convention rather than configuration to help you create your app.

#### Key takeaways
This is an easy-to-read and comprehend article.

We go down the essential elements of Ember framwork in an easy-to-understand manner for newcomers.

We describe how to use Ember framwork in a simple, concise, and straightforward manner so that readers can easily navigate through official release notes and information.

#### Article quality
Our article covers the information about Ember framework, including its benefits, use cases, and, most importantly, how users may use it most effectively, as well as its documentation.

#### References
N/A

#### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
How does your article differ from: https://www.google.com/search?q=Introduction+on+Ember&oq=Introduction+on+Ember&aqs=edge..69i57j69i61.474j0j1&sourceid=chrome&ie=UTF-8 ?

**Comment by 08-dev-verma** [comment]
> How does your article differ from: https://www.google.com/search?q=Introduction+on+Ember&oq=Introduction+on+Ember&aqs=edge..69i57j69i61.474j0j1&sourceid=chrome&ie=UTF-8 ?

In my article, I describe the intro of the Ember framework briefly also covering some intermediate topics, its advantages and how it differs from other frameworks with examples.
