### ISSUE TITLE
Wavelet transform analysis of images using WaveletAnalyzer toolbox in Matlab

### ISSUE THREAD

**Issue by atienodorine3** [section-engineering-education/engineering-education#6655]
### Topic Suggestion
Wavelet transform analysis of images using WaveletAnalyzer toolbox in Matlab

### Writing sample(s): 
https://www.section.io/engineering-education/wavelet-transform-based-denoising-of-images-using-matlab/

#### Introduction
The wavelet transform is signal decomposition using a system of wavelets, that is, functions, each of which is a shifted and scaled copy of a function, the mother wavelet. The term wavelet transform defines a class of decomposition methods. Wavelet Analyzer app is an interactive tool for using wavelets to visualize and analyze signals and images. This App can be used for applications such as wavelet transform analysis, denoising images and signals, e.t.c.
This article covers wavelet analysis and synthesis of images using filter banks. Also, it shows how to perform wavelet transform analysis of images using the WaveletAnalyzer toolbox. How to use the various wavelet functions such as dwt2, idwt2, wavedec2 and waverec2 are covered here.

#### Key takeaways 
- Wavelet analysis and synthesis of images using filter banks.
- Wavelet transform analysis of images using WaveletAnalyzer toolbox of Matlab.
- Use of dwt2, idwt2, wavedec2 and waverec2 Matlab function.

#### Article quality
This article shows how to use the WaveletAnalyzer toolbox and the various Matlab functions.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @atienodorine3 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
