### ISSUE TITLE
Getting started with AWS Lambda Golang REST API 

### ISSUE THREAD

**Issue by Frankline012** [section-engineering-education/engineering-education#6656]
#### Proposed title of article

Getting started with AWS Lambda Golang REST API 

#### Proposed article introduction

* In this article, we will go through the process of conveying a Golang API to AWS Lambda and dealing with demands through AWS API Gateway, an interaction which is extremely straight forward and requires a couple of minutes once we understand the steps to be followed. In this case, we will use the concept of serverless architecture which refers to the abstraction of "servers" from application development.  We'll be working in Golang, but the same method can be applied to Python, Node, Java, or any other language or framework you want.

#### Key takeaways 

1. Setting up the aws cli
2. Creating Simple Golang REST API
3. Creating and deploying an AWS Lambda function
4. Setting up the HTTPS API in AWS API Gateway
5. Deploying the HTTP API created

#### Article quality

The fundamental explanation of composing this article is on the grounds that the greater part of the posts includes clarification of extra parts like information bases, reserve, and so forth which is truly helpful however not a clear post on getting started with AWS Lambda Golang REST API procedures. 

#### References

N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Frankline012
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
