### ISSUE TITLE
[Languages] Implementations of dependency injection in C#

### ISSUE THREAD

**Issue by djayjames** [section-engineering-education/engineering-education#6659]
#### Proposed title of the article
[Languages] Implementations of dependency injection in C#

#### Proposed article introduction
Dependence is an object that another object relies on for its existence. When an object wants an object, it doesn't have to build it. This is called dependency injection (or inversion of control). Mocking the dependencies is an effective way to make testing more efficient.

The fact that class B calls a method on class C indicates that class A is dependent upon both classes B and C. Instead of requiring these classes to create instances of B and C, we can use dependency injection to provide an instance of class C to class B and an instance of class B to class A.

#### Key takeaways 
The article will cover:
- An overview of dependency injection 
- How to implement dependency injection using method injection in C#
- How to implement dependency injection using constructor Injection C#
- How to implement dependency injection using property injection c#
- How to implement dependency injection using interface-based injections in C#

#### Article quality
 This article would deal with explaining dependency injection and its implementation in C# in detail. To make my article unique I will create my own project to demonstrate the implementation process. Also, my article will be beginner-friendly and the code snippets will be well explained and tested. 
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @djayjames

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by djayjames** [comment]
can anyone reopen this article for me please!

**Comment by Ericgacoki** [comment]
You may now link the PR!
