### ISSUE TITLE
Getting Started with Sanity CMS

### ISSUE THREAD

**Issue by abimbolataofeek** [section-engineering-education/engineering-education#6661]
### Topic Suggestion
Getting Started with Sanity CMS.

#### Pre-submission advice
Introduction
Building applications and having to worry about the content or database is not efficient.

Sanity is an Open Source Content Management System built with React. Sanity allows you to focus on developing your application without having to worry about the content file storage and databases, Sanity will cover all the hard work for you and allow you to build scalable and user-friendly applications extremely easily. it is also versatile you can create simple things incredibly easily but if you need to create more complex queries and schemas you can do that as well.
 Sanity is a platform for structured content, it helps you manage and deliver your content easily. Another cool stuff about sanity is the Sanity Studio it's a dashboard where you can edit, update, collaborate and manage all of your content.

#### Key takeaways 
At the end of this tutorial the reader would fully understand:

1. CMS & JAM Stack Applications
2. Sanity Installation & Setup
3. Create a project with Sanity
4. Sanity Cli
5. Explore Sanity Studio
6. Schema Types
7. Query Data 
8. Deploy Sanity Studio

#### Article quality
In this tutorial, we are going to be taking a deep dive looking into CMS, JAM Stack Applications Sanity CMS, Setup, data querying, and lot. It's completely beginner-friendly

#### References
https://www.sanity.io/

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
