### ISSUE TITLE
Difference between static and dynamic routing

### ISSUE THREAD

**Issue by NJIRAI** [section-engineering-education/engineering-education#6662]
### Topic Suggestion
Difference between static and dynamic routing

### Writing sample(s): 
N/A
#### Proposed title of article
Difference between static and dynamic routing

#### Proposed article introduction
In most cases, upcoming networkers and even networkers themselves fail to recognize the difference between static and dynamic routing. I was faced with the same challenge initially and thought it would be wise to share the knowledge I have grasped over the years. This article will be very crucial in guiding you on the difference between these two. It will be done through identification of the advantages and disadvantages of these two. We will also identify the similarities between them. We will also see some practical simulation of the the two in cisco packet tracer.

First, we need to understand Routing. What is routing? It is the process of identifying and choosing a path/route to deliver packets from one network to another. It is crucial in transmitting data packets fast. It also helps in avoiding traffic in the network. Routing is then categorized into two; Static and Dynamic routing. What is static routing? It is a process in which we manually add paths/routes to the routing table. Dynamic routing is a technique of finding the best path for data packets on a computer network. We will deeply dwell in these issues to ensure that you get the difference between static and dynamic routing. 
#### Key takeaways 
These article will help the reader in the following ways;
1. Understand static and dynamic routing.  
2. Differentiate between static and dynamic routing.
3. Working with cisco packet tracer.

#### Article quality
This article will help you get a deep understanding of static and dynamic routing, their comparison as well as differences between them. We will also have a privilege to see their simulation on cisco packet tracer.

#### References
N/A

**Comment by NJIRAI** [comment]
Happy learning!

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
