### ISSUE TITLE
Improving Conversations with the Perspective API

### ISSUE THREAD

**Issue by Fidelmwangi** [section-engineering-education/engineering-education#6664]
#### Proposed title of article

Improving Conversations with the Perspective API.

#### Proposed article introduction

The Perspective API is a machine learning tool that is designed to rate a string of text (i.e. a comment) and provide you with a Toxicity Score, a number representing how toxic the text is. The framework learns by perceiving how huge number of online conversations have been moderated and attempts to improve the quality of debate and ensure individuals aren't put off from participating. To get started with using the API, you'll have to demand API access from their site. When you receive the email saying you have access, you'll have to sign in to the Google Developer Console and get your API key. Make your certifications with how much security you'd like and afterward you're prepared to get started. This article incorporates data concerning what highlights are right now accessible and what they're at last intended to accomplish.

#### Key takeaways 

* By the end of this article, the following is expected;

1. Getting a Score with cURL
2. Send An Ajax Request
3. The WordPress Way
4. Privacy and Censorship

#### Article quality

This article will be on point, simple to understand, well formatted and I'm sure users will be able to learn the procedure of Improving Conversations with the Perspective API. The code snippets in this article will be simple to understand and implement. I hope we will have a good ride all along.

#### References

N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Fidelmwangi 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to link a PR. 👍

**Comment by Fidelmwangi** [comment]
@hectorkambow Hello, I'm truly sorry for the inconvenience. Kindly REOPEN this topic form for me to link a PR since it's ready.

**Comment by hectorkambow** [comment]
Closed PR.
