### ISSUE TITLE
A REST API built with Golang without any frameworks, only using the native modules.

### ISSUE THREAD

**Issue by Joakim-gakure** [section-engineering-education/engineering-education#6666]
### Writing sample(s): 

https://www.section.io/engineering-education/authors/joakim-gakure/

#### Proposed title of article

A REST API built with Golang without any frameworks, only using the native modules.

#### Proposed article introduction

I found this issue "[How to Build RESTful APIs with Typescript Without Any Frameworks from Scratch (only using the native modules)](https://github.com/section-engineering-education/engineering-education/issues/6313)". It gave me an idea that I can apply the same using the Golang programming language.

Go is a fast-growing language among developers. Its popularity is still growing and unshaken. Golang ecosystem has a tone of native libraries. However, it has third-party libraries that developers can still choose to use.

When creating Rest API with go, you might choose to use libraries such as Gorm, Go fiber, Gin, fasthttp, etc. On the same, you can still combine this with other third-party libraries to come up with the API of your choice.

However, due to the many libraries that the Go ecosystem has, you can still choose native libraries that you don't have to download and build your APIs. In this guide, we will build a complete and functional REST API. This API will only use native libraries that Golang has.

#### Key takeaways 

- Why Golang
- Why use native modules
- Build a basic server using native modules
- Create a CRUD Golang REST API using native modules
- Fetch from the API
- Post to the API
- Update a record from the API
- Delete a record from the API
- Testing the API
- Third parties packages that you can use to set up Go REST APIs

#### Article quality

This guide aims to help the reader to learn how to make an HTTP server in Golang without using external libraries. The whole application will run with libraries that are core to Golang. Thus no installing any modules of third-party packages such as Gorm, Go fiber, Gin and etc.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Please fill in the form. @Joakim-gakure

**Comment by ahmadmardeni1** [comment]
Great topic. Approved. @Joakim-gakure

**Comment by WanjaMIKE** [comment]
Closed #6666 via #7222
