### ISSUE TITLE
Getting Started with Java Concurrency

### ISSUE THREAD

**Issue by mussooo** [section-engineering-education/engineering-education#6668]
#### Proposed title of article
Getting Started with Java Concurrency

#### Proposed article introduction
Most computers nowadays have multiple processors, which can execute many tasks in parabole. Multiple processors make our application fast and more responsive.

In Java, "concurrency" is the ability of a system to handle multiple things by creating multiple execution units. The concept that helps create multiple execution units is called "multithreading."

In this tutorial, we will learn how to create multiple execution units in Java and also how concurrency works.

#### Key takeaways 
1. Concurrency issues
2. Strategies for Thread Safety
3. Thread Signalling with wait() and notify()
4. Concurrent Collectors
5. Synchronized Collections

#### Article quality

By working on the above key takeaways, which are not well explained in other blogs, the reader will have a better understanding of Java concurrency.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @mussooo 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
