### ISSUE TITLE
[Machine Learning] Leveraging BodyPix for Body Segmentation using Python and OpenCV

### ISSUE THREAD

**Issue by splashtonia** [section-engineering-education/engineering-education#6669]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Leveraging BodyPix for Body Segmentation using Python and OpenCV

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

BodyPix is a body segmentation model that is built on TensorFlow. The model leverages a pre-trained neural network to segment human bodies from frames. Beside segmenting your body, this tutorial will leverage this model to change your background using your webcam and OpenCV. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to:
- Learn about the BodyPix model.
- Learn how to install the model onto our notebook.
- Learn how you can segment your body.
- Learn how to remove and change the background. 

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Not only will I show the readers how to perform the segmentation using one person but also how one can use it on multiple people in an input image or video.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [BodyPix](https://github.com/tensorflow/tfjs-models/tree/master/body-pix)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @splashtonia 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #6669 via #7368
