### ISSUE TITLE
[Languages] Automatic Reference Counting in Swift

### ISSUE THREAD

**Issue by Amayo-Amayo** [section-engineering-education/engineering-education#6670]
#### Introduction
Automatic Reference Counting (ARC) is a memory management attribute used to monitor and manage an application's memory usage. Swift memory management works automatically without control. It automatically allocates or deallocates memory to allow efficient running of applications. 

In other circumstances, though, ARC needs more information about the links between different portions of programs to handle memory. This article explains how to use ARC to handle all of your application's memory in certain instances. It will also discuss reference cycles, their types, and how they are broken. Lastly, it will discuss detecting reference cycles using Xcode visualization tools.

#### Key takeaways 
The reader should be able to understand the following upon going through the article:
1. What ARC is and how it works
2. What reference cycles are and how they are broken
3. The difference between strong, weak, and unowned references
4. How to detect reference cycles using Xcode visualization tools

#### Article quality
This will be a distinctive article with detailed information. I will use basic language to ensure that anybody reading it understands the contents of this article. I'll make sure that this article is helpful to the whole EngEd and goes above and beyond official documentation.

**Comment by ahmadmardeni1** [comment]
How does your article differ from: https://www.google.com/search?q=Automatic+Reference+Counting+in+Swift&oq=Automatic+Reference+Counting+in+Swift&aqs=edge..69i57j69i61.787j0j9&sourceid=chrome&ie=UTF-8 ?

**Comment by Amayo-Amayo** [comment]
Greetings @ahmadmardeni1. My article will be different in that it will contain a clear explanation on how to use Xcode 10, the various functions of ARC, and its best practices which are not mentioned in the articles above.

**Comment by ahmadmardeni1** [comment]
Approved. @Amayo-Amayo

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to link a PR. 👍

**Comment by Amayo-Amayo** [comment]
@hectorkambow Please reopen this issue its PR is ready.

**Comment by hectorkambow** [comment]
👀
