### ISSUE TITLE
Data visualization in React JS using Apex Charts

### ISSUE THREAD

**Issue by stephanieopala** [section-engineering-education/engineering-education#6672]
### Topic Suggestion
Data visualization in React JS using ApexCharts

### Writing sample(s): 
https://dev.to/stephanieopala/simple-navigation-bar-in-react-js-4d5m

#### Proposed title of article
Data visualization in React JS using ApexCharts 

#### Proposed article introduction
ApexCharts.js is a library that is used to visualize data. It provides features such as annotations, responsiveness and animations which make your charts interactive. This article will cover the types of charts provided in this library, how to customize them and how to implement them in your React application.

#### Key takeaways 
- Introduction to ApexChart.js library.
- Reasons why you should use this library in your React web application.
- Types of charts and how to implement them using dynamic data from an external API.

#### Article quality
This article provides an in-depth guide on implementing ApexCharts.js using dynamic data from an external API in React JS.

#### References
[ApexCharts Documentation](https://apexcharts.com/docs/installation/#)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @stephanieopala 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
