### ISSUE TITLE
Kotlin inheritance with examples

### ISSUE THREAD

**Issue by Shee254** [section-engineering-education/engineering-education#6674]
#### Proposed title of article
Kotlin inheritance with examples

#### Proposed article introduction
Inheritance is a feature using which a class inherits all the features of another class. The class from which the features are inherited is known as base class or super class or parent class and the class that inherits the features is known as derived class or sub class or child class. In this tutorial, we will learn what is inheritance and how to implement it in the Kotlin with the help of examples.

#### Key takeaways 
1. What's inheritance
2. Overriding member functions and properties in Kotlin
3. Calling data members and member functions of base class from child class
4. Kotlin Inheritance and primary constructor
5. Kotlin superclass implementation

#### Article quality
In this article kotlin inheritance with examples will make use of simple language and all examples will be explained in a simpler manners for beginners to understand with easy.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @Shee254 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
