### ISSUE TITLE
PHP Performance Optimization

### ISSUE THREAD

**Issue by Jacinta78** [section-engineering-education/engineering-education#6678]
#### Introduction
PHP gives enough performance. However, PHP developers and system administrators may do several things to boost efficiency, even more, some of which require absolutely no work. While PHP is fast and adaptable, it also offers a variety of choices and settings, and selecting the incorrect settings or functions can cause severe performance and scalability issues. 

In this article, we will discuss a few easy ideas you may utilize in your code to improve the performance of your application. For example, employ native functions, use JSON instead of XML, leverage cache systems, and appropriately set up OPcache, PHP-FPM, and Memcached. You can also disable the database connection and restrict the number of database hits.

#### Key takeaways 
By the end of this article, the reader should be able to understand the following:
1. Understand the meaning of performance optimization in PHP
2. Performance bottlenecks
3. The role of Profiling in PHP performance tuning
4. Performance optimization methods in PHP
5. Measuring PHP application performance

#### Article quality
This article will be unique because its contents will be original. The language I will use will be beginner friendly for any reader to understand.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Jacinta78 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready to link a PR. 👍

**Comment by Jacinta78** [comment]
@hectorkambow I'm ready to PR.
