### ISSUE TITLE
Spotting of Passing Objects Using Python 

### ISSUE THREAD

**Issue by lizpart** [section-engineering-education/engineering-education#6679]
#### Proposed title of article

Spotting of Passing Objects Using Python 

#### Proposed article introduction
Spotting of moving objects has become crucial in our lives today. Talking of security, cameras help us a great deal in executing this
function. Other key areas cut across tracking of living organisms and also vehicles in traffic control. 
In this tutorial, we will be performing the identification and recognition of moving objects.
We will be requiring a few tools before carrying on, that is, the laptop's webcam and most of all an external library to be installed
and downloaded which is the OpenCV module. With those at hand, we will be able to tackle our project at hand.

#### Key takeaways 
1. Installation of external libraries
2. Detection of the contours of the object.
3. Capturing of the recognized moving objects.
4. Returning the detected object.

#### Article quality
Unlike other articles, the code will be well explained and not just copy-pasted. But designed in an eccentric way for easier understanding and consumption. Deeply emphasizing the importance and use of the WebCam in relation to OpenCV
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @lizpart 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
