### ISSUE TITLE
[Languages] Creating a Simple Hunt the Wumpus Game with Python, Flask and SocketIO

### ISSUE THREAD

**Issue by csamuelsm** [section-engineering-education/engineering-education#6684]
#### Proposed title of article
Creating a Simple Hunt the Wumpus Game with Python, Flask, and SocketIO

#### Proposed article introduction
One of the first computer games is Hunt the Wumpus. It is a simple adventure game that was developed in 1973. In Hunt the Wumpus, the player is an adventurer entering a dungeon looking for a treasure. The goal of the adventurer is to find the treasure and get out of the dungeon avoiding the pits where he can fall in and the Wumpus: a monster who kills anyone it sees. To do that, the player has to pay attention to the signals: when he is near a pit he can feel a breeze, and when he is near the Wumpus he can smell the Wumpus' stink.

Hunt the Wumpus was studied by computer scientists in the early days of the artificial intelligence field and it exemplifies the use of logic in A.I. In this tutorial, we are going to build a simple graphical web-based Hunt the Wumpus game using Python, Flask, and SocketIO.

#### Key takeaways 
- The Hunt the Wumpus game (rules and a little bit of history)
- A little bit of the Hunt the Wumpus game contributions and applications in the early days of A.I.
- Integrating Flask and SocketIO in a real application
- Creating a simple UI for a simple web-based game 

#### References
- [Hunt the Wumpus - Wikipedia](https://en.wikipedia.org/wiki/Hunt_the_Wumpus)
- [AI - Hunt the Wumpus World Description](https://www.geeksforgeeks.org/ai-the-wumpus-world-description/)
- [Flask](https://flask.palletsprojects.com/en/2.0.x/)
- [SocketIO](https://socket.io/)

### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by hectorkambow** [comment]
@csamuelsm Any update on this PR? 

Just and FYI I will be closing this topic form just to help clear up the queue where possible - **can be REOPENED at anytime** when ready to link a PR. 👍

**Comment by csamuelsm** [comment]
> @csamuelsm Any update on this PR?

I'm working on it. I'll be sending the PR soon.

**Comment by WanjaMIKE** [comment]
Closed #6684 via #7314
