### ISSUE TITLE
URL Manipulation in JavaScript

### ISSUE THREAD

**Issue by prince-joel** [section-engineering-education/engineering-education#6688]
### Topic Suggestion
URL Manipulation in JavaScript

#### Proposed title of article
URL Manipulation in JavaScript. 

#### Proposed article introduction
In web development, there are a lot of situations like pagination, GET requests, or filtering where developers or users’ activities interact with the content of the URL, these situations bring about URL manipulation.

Before we discuss how the URL can be manipulated, let us take a look at what a URL is.
A Uniform Resource Locator, URL is colloquially known as a web address is a reference to a web resource that specifies the location on a computer network and a mechanism for retrieving it.

#### Key takeaways 

- The reader will learn the components of a standard URL

- The reader will learn about two NodeJs APIs for URL manipulation.

- Some noteworthy differences between them.

### Conclusion
After reading this article, readers should have a better understanding of what URLs are, why URL Manipulation is essential in web development, and the role SIMPLE APIs plays in URL Manipulation.

**Comment by lalith1403** [comment]
Thank you for the topic suggestion, however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
