### ISSUE TITLE
[Machine Learning] Time Series Analysis and Forecasting using Auto Time Series 

### ISSUE THREAD

**Issue by elishanjeche** [section-engineering-education/engineering-education#6690]
#### Proposed title of article
[Machine Learning] Time Series Analysis and Forecasting using Auto Time-Series 

#### Proposed article introduction
Time series is a type of machine learning model that is used to forecast future events based on previous events that have been observed at regular time intervals. Times series models can be used to forecast stock market prices, forex prices, pandemic spread, and weather forecasts.

Time series models are used to extract meaningful statistics and other characteristics of the data. This makes the model understand patterns from data and gain useful insights. The model uses the knowledge gained to make forecasts of future values such as a stock. The time series model uses curve fitting techniques to plot the forecast values and come up with a line of best fit. The plot diagrams are used to represent the predicted values.

In this tutorial, we will download our dataset and perform dataset preprocessing. We will then use the auto series library to build our model. The auto series library will use a machine learning pipeline to automate the time series modeling process. Auto time series will use multiple models such as Facebook Prophet, ARIMA, SARIMA, and VAR to train the model. It will train the model and produce an optimized model. Auto time series will search through all the time series libraries and select the one with the best results.

#### Key takeaways 
1. Types of Time series models. (Univariate, bivariate, and multivariate)
2. Time series libraries such as Facebook Prophet, ARIMA, SARIMA, and VAR
3. Time series decomposition and analysis.
4.  Training the model using multiple models.
5. Select the best model and make forecasts.

#### Article quality
This tutorial is unique because it will discuss different types of time series models and libraries. We will compare libraries such as Facebook Prophet, ARIMA, SARIMA, and VAR. We will then combine all these libraries using Auto time series and train the same model. The final model will be fully optimized and give correct forecasts/predictions. It will have detailed and guided steps that are easy for a reader to follow. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and what is covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
