### ISSUE TITLE
Reverse engineering the "Tiktok" algorithm and Implementing it in code.

### ISSUE THREAD

**Issue by KanizoRGB** [section-engineering-education/engineering-education#6691]
### Topic Suggestion
[Languages]Reverse engineering the "Tiktok" algorithm and Implementing it in code.

### Writing sample(s): 
https://www.section.io/engineering-education/an-introduction-to-machine-learning-using-c++/
https://www.section.io/engineering-education/machine-learning-libraries-in-cplusplus/

#### Proposed title of article
Reverse engineering the "Tiktok" algorithm and Implementing it in code.

#### Proposed article introduction
The tremendous success of the social media platform Tiktok has been attributed to its aggressive AI recommendation tool. This is contrary to the old guard social media platforms such as Youtube or Facebook where AI is just a part of the experience. For example in Youtube, the algorithm recommends video suggestions for you to select and watch, so there is still a choice. In Tiktok, the algorithm fiercely dictates what you will watch and this has led the platform to grow rapidly within a short time to become the number one non-gaming application in the united states and the number one social media app across all platforms.
Tiktok has openly come out with the concept of how their algorithm works which can be found on their website. It is from this conceptual idea that we will try to write the code for it in and thus have a simple guide on how to create this popular type of algorithm using python.

#### Key takeaways 
1. The reader will learn of various types of recommendation algorithms.
2. The reader will learn how to combine the various recommendation algorithms in order to avoid redundancy and also to achieve other desired results according to the liking.
3. The reader will learn how to use Apache Spark which is a multi-lingual engine for executing data engineering, data science, and machine learning and thus they will appreciate its speed as compared to running a script traditionally.

#### Article quality
My article is unique as there is no exact code out there that shows how the Tiktok algorithm works and this was a fun process for me as I tried to implement it in code and the solution is very unique. It will follow an anecdotal approach.

#### References
1.https://newsroom.tiktok.com/en-us/how-tiktok-recommends-videos-for-you/

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Hello @KanizoRGB, given the legalities behind reverse engineering proprietary algorithms, we will not be going ahead with this one. 

The suggestion is an interesting one. Please feel free to submit another suggestion. Thank you.
