### ISSUE TITLE
Building a custom stopwatch NPM library in Typescript

### ISSUE THREAD

**Issue by davekola** [section-engineering-education/engineering-education#6692]
### Topic Suggestion
Building a custom stopwatch NPM library in Typescript

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Building a custom stopwatch NPM library in Typescript

#### Proposed article introduction
In beginners web development, there are numerous applications and projects you would want to build to enhance your skills and problem-solving abilities. A custom stopwatch typescript package is one of those interesting projects that has numerous applications in web development, and can widen your typescript horizon.
In this tutorial, we will explore in details the various procedure and logic required to build your custom stopwatch NPM library in typescript and make it available for typescript users around the world to install and implement in their various projects.

#### Key takeaways 
At the completion of this tutorial, the reader is expected to have the understanding and skill required to implement the following:
-	Getting started with typescript library development.
-	Setting up a functional typescript folder structure.
-	Building a custom stopwatch typescript library package.
-	Deploying and making the typescript package available to global users.
-	 Error handling when working typescript libraries.

#### Article quality
This article is a unique project-based tutorial that explores the steps, and logic required to build and deploy globally a custom typescript NPM library, and how to make it available for users around the world to import and use in their web project. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
