### ISSUE TITLE
[API] Different ways to use the Application Configuration in .NET CORE

### ISSUE THREAD

**Issue by titositati** [section-engineering-education/engineering-education#6693]
### Topic Suggestion
[API] Different ways to use the Application Configuration  in .NET CORE

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
.NET Core has a new way of working with configuration that is much more flexible than the way that previous versions of .NET have.

It allows you to:
- Pull configuration from multiple sources and bring it in to one place.
- Easily map that configuration information into classes to make access easier.
- Override configuration from previous sources so that you can import a base configuration then override settings on per-environment basis.
In this article, we shall look at the different levels where configuration can happen. Then look at how we can override the appsettings.json file to fit the different environments our application will be deployed to. 

For example, if the article is based on machine learning, use the following: 
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
- Set up a .NET CORE API.
- Understand the different sections one can use to configure their common application settings.
- How to override the appsettings.json file.
- Reasons why one would want to override the appsettings.json file.

#### Article quality

This article will be very beginner friendly. We will start from setting up a .NET CORE API project as one would do in a real world project. Then go ahead and explain to the reader how one can use the different sections of the .NET CORE API to set up the application's configurations.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
