### ISSUE TITLE
WHAT TO CHECK OF WHEN FINDING A CMS FOR YOUR ONLINE ECOMMERCE STORE.

### ISSUE THREAD

**Issue by Saintdavidking** [section-engineering-education/engineering-education#6694]
Outline;

- Introduction.
Here i will introduce cms, explain what cms does,

- E-commerce store requirements:
Here you will see requirements for an E- commerce store 

- Types of CMS available for your ecommerce store: 
here i will list the types of CMS available and explain them.

-  Things to consider before choosing a CMS for your ecommerce store:
Here you will see things to look for when considering a cms for your ecommerce store.

- Why Headless CMS is the best CMS for your ecommerce store:
Here you will come across Reasons why headless cms has more potential that could boost your productivity as a front end developer.

- How to know when you need to use a CMS in your project: 
here you will learn when you need to use a cms in your project 

- Conclusion.

After going through this article the reader will be able to understand and know what cms to choose and reasons to choose the cms for his or her ecommers store.

**Comment by WanjaMIKE** [comment]
This article seems to be summarized below:

#### 10 considerable points for choosing the best eCommerce CMS
- Popularity. Popularity can be a significant parameter when it comes to choosing the perfect CMS. ...
- Pricing & Payments. 
- Interface & Usability.
- Customizability. 
- Scalability. 
- SEO friendliness. 
- Security. 
- Core functionalities.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
