### ISSUE TITLE
[Language] Getting started with automating word using C#

### ISSUE THREAD

**Issue by K-jacinta** [section-engineering-education/engineering-education#6698]
### Topic Suggestion
Getting started with automating word using C#

### Writing sample(s): 
https://www.section.io/engineering-education/authors/jacinta-kyulu/

#### Proposed article introduction
The goal of Word Automation in C# is to automate the creation of Word documents through the use of C# code in the form of Word Automation. Even while dealing with Word is regarded straightforward, doing it on a computer programmatically becomes more difficult. It is almost entirely via the usage of objects and reference types that much of the work that goes into word automation is accomplished. C# and Visual Basic can be used to automate practically all of the tasks we perform in Word 2003. Text formatting, linking documents, mail merge, inserting documents, embedding documents, inserting photos, applying a watermark, and a variety of other routine operations can all be automated using scripting languages such as Visual Basic for Applications (VBScript) or Python.

#### Key takeaways 
1. Objects used in automation.
2. Automation using a base template.
3. Mail merge
4. Embedding a document
5. Inserting a document and including pictures/watermarks in the document background
6. Basic Text Formatting Options

#### Article quality
This article will be a combination of theory and practical which will be in code snippets which will enable the reader to be able to work with word in C# with ease. Different concepts will be discussed as written in the key takeaways.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=Getting+started+with+automating+word+using+C%23&sourceid=chrome&ie=UTF-8), the word automation topic appears a bit over-saturated. Feel free to suggest another topic. Thanks
