### ISSUE TITLE
 Calculating Fibonacci Numbers Concurrently in Python.

### ISSUE THREAD

**Issue by samkanoi** [section-engineering-education/engineering-education#6701]
### Topic Suggestion
Calculating Fibonacci Numbers Concurrently in Python. 

#### Proposed title of article
 Calculating Fibonacci Numbers Concurrently in Python.

#### Proposed article introduction
This article will teach you how to calculate Fibonacci numbers concurrently in Python. Fibonacci numbers are a sequence of numbers that is the sum of the two preceding numbers plus the next two numbers. The first few numbers in the sequence are 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946 and so on. This article will also show how to use a Python function to calculate Fibonacci numbers of all sizes in a functional programming style and then demonstrate how to transform the calculation into a recursive method.

#### Key takeaways 
- What is Fibonacci numbers?
- How to calculate Fibonacci numbers in Python.
- How to calculate Fibonacci numbers concurrently in Python.
- Demonstrating how to transform the calculation into a recursive method.

**Comment by samkanoi** [comment]
@hectorkambow  kindly reopen the issue

**Comment by hectorkambow** [comment]
@samkanoi  

Is the pull request (article) ready to be submitted? (full polished and error free?)

**Comment by samkanoi** [comment]
@hectorkambow yes it is only that topic wasn't approved

**Comment by louisefindlay23** [comment]
Please fill in the topic suggestion form properly so we can review your topic for consideration.

**Comment by samkanoi** [comment]
@louisefindlay23 done

**Comment by hectorkambow** [comment]
@samkanoi 

As long as the article you plan on contributing is original and unique (different from [other blogsites](https://www.google.com/search?q=Calculating+Fibonacci+Numbers+Concurrently+in+Python&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8))

**Comment by hectorkambow** [comment]
@samkanoi 
Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved
