### ISSUE TITLE
Building a simple Chatbot using Natural Language Toolkit (NLTK) Library in Python

### ISSUE THREAD

**Issue by puritymutunga** [section-engineering-education/engineering-education#6702]
### Topic Suggestion
Building a simple Chatbot using Natural Language Toolkit (NLTK) Library in Python

### Writing sample(s): 
https://www.section.io/engineering-education/authors/purity-mutunga/

#### Proposed article introduction
Isn't it wonderful that you may ask and tell anything to a chatbot and not be evaluated at all? Chatbots are AI-based programs, which fall under the umbrella of Natural Language Processing (NLP), that interact with users to answer their unique questions without the involvement of a human.
A chatbot is a computer program that automates repetitive tasks for a company's customers. Chatbots are now being used in a variety of ways by businesses in a variety of industries in order to respond to customers as quickly as feasible. There are numerous benefits to using chatbots, including a boost in traffic to a company's website.
Customers are asked for their name, email address, and the specifics of their inquiry while interacting with a chatbot. An automated system can deal with simple issues such as a faulty product or a missed reservation, but it can't handle more complex issues, such as a breakdown in service or a requirement for additional information. Furthermore, the majority of clients prefer interacting with a chatbot.

#### Key takeaways 
1. Brief on Chatbots
2. The importance of chatbots
3. Types of Chatbots
4. Building a Chatbot using Python
5. Implementing Chatbot using Python NLTK Library

 #### Article quality
The article will give the reader a brief introduction to Chatbots and then develop one Chatbot using NLTK Library in Python it will be a combination of theory and practical

#### References
N/A

**Comment by WanjaMIKE** [comment]
I think this topic is quite similar to https://github.com/section-engineering-education/engineering-education/issues/5932. Feel free to choose another topic. Thanks
