### ISSUE TITLE
[Languages] How to update and upload profile picture with AJAX and a  JQUERY crop tool in Laravel Framework

### ISSUE THREAD

**Issue by leshack** [section-engineering-education/engineering-education#6703]
### Topic Suggestion
[Languages] How to update and upload profile picture with AJAX and a  JQUERY crop tool in Laravel Framework

#### Proposed article introduction
 Asynchronous JavaScript And XML (AJAX) allows web pages to be updated asynchronously by exchanging data with a web server behind the scenes. This means that it is possible to update parts of a web page, without reloading the whole page.
Classic web pages, (which do not use AJAX) must reload the entire page if the content should change.This has become essential when making an in-page request to the server.

Crop tool allows you to select an area of an image and discard everything outside this area.A crop tool does not alter the size of the image content  at all  compared to resizing.it is essential in cropping images

In this tutorial, we will learn to how to update profile picture with AJAX  in Laravel Framework using a  JQUERY crop tool.

#### Key takeaways 
The reader will be able to:

- Know how to use Ajax in uploading pictures
- Know how to use php framework(laravel) to update and upload picture
- Know how to use a JQUERY crop tool

#### Article quality
By working on the above takeaways, which are not well explained in other blogs and educational documentaries, the reader will have a better understanding of uploading and updating images without reloading the whole web.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=How+to+update+and+upload+profile+picture+with+AJAX+and+a+JQUERY+crop+tool+in+Laravel+Framework&oq=How+to+update+and+upload+profile+picture+with+AJAX+and+a+JQUERY+crop+tool+in+Laravel+Framework&aqs=chrome..69i57j69i61j69i60l2.325j0j7&sourceid=chrome&ie=UTF-8), this topic appears to be a bit over-saturated. We focus more on unique projects. Feel free to suggest another topic. Thanks
