### ISSUE TITLE
[Security] Security concerns and tips for securing DBaaS

### ISSUE THREAD

**Issue by Pauline-Mwangi** [section-engineering-education/engineering-education#6704]
### Topic Suggestion
Security concerns and tips for securing DBaaS

#### Proposed title of article
Security concerns and tips for securing DBaaS

#### Proposed article introduction
Dealing with a DBaaS raises several security concerns, just as working with a traditional database system. When a database is moved to the cloud, the security threat landscape changes significantly. As the cloud presents its own vulnerabilities, security challenges on DBaaS are on a bigger scale.

Many providers such as GCP, AWS and Azure provide hosted databases that are efficient and quick to start with. While the providers take most of the responsibilities regarding the security, some steps must be taken by the user to tighten the databases fully. This guide will discuss some security concerns related to DBaaS, instruct the readers on how to properly secure their DBaaS, and mention some of the most important day 2 operations.

#### Key takeaways 
1. DBaaS overview.
2. Why does the reader need to be concerned about securing DBaaS?
3. Tips for securing DBaaS.

- Setting up proper authentication and authorization.
- Whitelisting the IP addresses that can connect to the database instance.
- Storing the connection credentials securely.
4. Day 2 operations.

- Mention some of the “day 2 operations” related to DBaaS.

#### Article quality
This is a detailed guide that will pass value to readers. By going throw this article, readers will know security concerns regarding DBaaS and measures to take. It will also go through day 2 operations related to DBaaS.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
