### ISSUE TITLE
Creating User Authentication UI(Login and Signup) with Compose Desktop

### ISSUE THREAD

**Issue by Collince-Okeyo** [section-engineering-education/engineering-education#6706]
### Topic Suggestion
[Kotlin] Creating User Authentication UI(Login and Signup) with Compose Desktop

#### Proposed title of article
Creating User Authentication UI(Login and Signup) with Compose Desktop

#### Proposed article introduction
With Compose Multiplatform, one can create a very interesting layout using Kotlin and Jetpack compose for Desktop applications. Having a good user authentication layout attracts users to sign in to your system easily. Compose desktop has made this achievable with a lot of ease unlike SWINGS in Java which requires one to write lots of code. This tutorial will help the reader to understand how to use Compose Desktop to create well-structured desktop applications just like in Android. 

#### Key takeaways 
- How to use Compose Desktop.
- How to implement Layout designs using Compose Desktop.
- Compose desktop design patterns

#### Article quality
This article is going to be unique since Compose Desktop is a new technology that is just coming into existence. it is going to help the learner to get started with Compose Desktop. It will help the learner to also migrate from using the tiresome SWING library in Java. 

#### References
[Compose Desktop](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Getting_Started)

**Comment by WanjaMIKE** [comment]
Compose for Desktop seems like a good topic - since it is just coming out. Let's ensure that it adds value to the community. Thanks
