### ISSUE TITLE
Building a swipe application using the MongoDB Cloud and React js

### ISSUE THREAD

**Issue by bhanjibrilliant** [section-engineering-education/engineering-education#6709]
#### Proposed title of article
Building a swipe application using the MongoDB Cloud and React js
#### Proposed article introduction
In this tutorial, we will discuss the concepts of MongoDB cloud (Database as a service), then create a React application that allows users to swipe to view listings of say, houses like AirBnB. On swipe, depending on the direction, a listing is deleted, takes the user to the details page. There will be also an option to rate the application.

The key objective of this tutorial is to let the React developers understand the concepts of real-time applications and why NoSQL is the next big thing when it comes to handling large data in real time.

Additionally, we use the Express to build a RESTful API for serve our react application.

#### Key takeaways 
- Database as a service
- Power of Mongo DB in handling large data.
- React TinderCard
- The REStful APIs.
- The swipe feature in React
#### Article quality
This is a very unique tutorial, that aims at teaching and enhancing a fullstack JavaScript application. Learners will benefit from by setting up everything on the cloud hence no need to install several apps locally.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
