### ISSUE TITLE
[Edge Computing] Taking advantage of GPU to increase performance in exaflop cloud computing to instantiate big data services in an optimal manner.

### ISSUE THREAD

**Issue by etamoss** [section-engineering-education/engineering-education#6710]
.### Topic Suggestion
[Edge Computing] Taking advantage of GPU to increase performance in exaflop cloud computing to instantiate big data services in an optimal manner.
#### Proposed title of article
Taking advantage of GPU to increase performance in exaflop cloud computing to instantiate big data services in an optimal manner.

#### Proposed article introduction
As the Edge Computing world evolve in terms of new technology, every company, governmental entities, information data centers and even in agricultural revolution considers data as a new and extremely useful phenomenon for their existence. Modern supercomputers and clouds have proved  they can successfully work with petabyte data sets, however, giving a try to  exabyte size datasets  had tend to be a bit difficulty to some users, since high performance and high bandwidth is required to transfer and process such huge volumes of data over the network. 

Previously big data were mostly established purposely  for storing the data and applying some basic analytics modules. Today and in future, as the practice is evolving, there is a need to adopt more advanced newly emerging software and systems for analyzing commercial and increase operational performance to coincide the user needs.

This article provides steps on how to fully utilize the high performance of Big Data services offered by cloud computing technology taking into consideration the use of GPU instead of CPU to control the number of resources and data links as its known as a rule of the thumb that Cloud computing absorb massive data into distributive storage and ensures data reliability by redundant storage. 
#### Key takeaways 
-Brief understanding of cloud computing and Big Data.
-Reduce cost and maximize performance
-Dive into GPU

#### Article quality
This article will be unique in such that cloud scalability and cloud elasticity as a factor in cloud computing and in particular regarding big data management systems  will be fully covered as the current systems posted hardly handle data peaks automatically. Most of the time, cloud scalability is triggered manually rather than automatically and the state-of-the-art of automatic scalable systems shows that most algorithms are reactive or proactive and frequently explore scalability from the perspective of better performance. However, a proper scalable system as proposed in this article would allow both manual and automatic reactive and proactive scalability based on several dimensions such as security, workload rebalance  and redundancy for availability.

#### References
N/A

**Comment by WanjaMIKE** [comment]
I note that one sentence takes the whole paragraph.

**Comment by WanjaMIKE** [comment]
There are some significant readability challenges in your description that raise concerns over how much review/editing would be required from our peer review team. We don't provide editing services and recommend that students leverage online editing services (there are both free and paid services that you can explore), or try engaging with the community or other peers in your network to have them review prior to submitting a revised proposal. Thank you.
