### ISSUE TITLE
Implementation of Dijkstra’s algorithm to find the shortest  path from starting node to target node in a weighted graph

### ISSUE THREAD

**Issue by Daniel-muriithi** [section-engineering-education/engineering-education#6711]
#### Proposed title of the article
Implementation of Dijkstra's algorithm to find the shortest  path from starting node to target node in a weighted graph

#### Proposed article introduction
As the name suggests, the single-source shortest-path Dijkstra algorithm is used in this context. A single source is provided, and we must identify the shortest route between the source and each node to complete this problem.

Dijkstra's algorithm is one method for determining the shortest route between two nodes in a weighted network. From the first vertex, the source, the method constructs a tree containing the shortest paths to every other point on the graph. Using Dijkstra's approach, first published in 1959 and named after its developer, Dutch computer scientist Edsger Dijkstra, may be used in a weighted graph. It is possible to create a graph that is either directed or non-directed. Using the procedure requires that the graph have a non-negative weight on each edge.

In a look at the real-life situation, let's say a student wishes to go as quickly as possible between their house and school. She's aware that some routes are busy and tough to navigate. If an edge has a big weight in Dijkstra's algorithm, it will strive to avoid it in the shortest route tree. For example, students may utilize Dijkstra's algorithm when searching for directions on a map service.

#### Key takeaways 
By the end of this article, we will cover:

- An overview of Graphs
- Understanding the Dijkstra's Algorithm?
- Implementing the Dijkstra's Algorithm?
- Dijkstra's Algorithm in Action
- Dijkstra's Algorithm Applications
- merits and demerits of Dijkstra’s Algorithm

#### Article quality
This article will explain Dijkstra's algorithm for determining the shortest route from one node to another in a weighted network graph in detail. To make my piece unique, I will use an example to demonstrate the implementation process of Dijkstra's algorithm. Also, my article will be beginner-friendly, and the code snippets will be well explained.

#### References
N/A

**Comment by WanjaMIKE** [comment]
I think these [articles](https://github.com/section-engineering-education/engineering-education/issues?q=Dijkstra%E2%80%99s+algorithm) have adequately covered Dijkstra’s algorithm. Feel free to choose another topic. Thanks
