### ISSUE TITLE
How to Integrate Firebase Analytics in a Flutter Project

### ISSUE THREAD

**Issue by Lekwacious** [section-engineering-education/engineering-education#6714]
#### Proposed title of article
How to Integrate Firebase Analytics in a Flutter Project

#### Proposed article introduction
This article teaches how to integrate Firebase Analytics in a Flutter app in order to track business metrics. These metrics, will help in the evaluation of  the impact of changes or updates on the app. For  example,  modifying the initial onboarding experience, to see if it will  lead to improved engagement  and customer acquisition. With mobile app analytics, business owners can collect accurate data to power their product offering, for example how does a change in price model on your app affect or improve customer retention.

This project will use Firebase to track, user session, daily active users(DAU), Monthly Active Users(MAU) the type of devices that your users are using etc. Also You will be able to track the countries where your users are located, the different Screens they routed on your app. All this will help business owners make better business decision.

#### Key takeaways 
- How to Configure Firebase Analytics on a Flutter Project
- How to track User's Events and activities on the App
- How to use the Firebase Analytics dashboard.

#### Article quality
The article will teach this topic using practical project that readers can relate. The code will be written in a production mindset and concept and terminologies broken down to the extent that developers at level will find it the article useful.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

The content can easily be found in the official documentation.

**Comment by Lekwacious** [comment]
I think otherwise. Content on Firebase Analytics on flutter is not littered
on the internet. A google search shows that. Why they may be documentation.
Somethings Young developers finds it difficult to use.
Anyway, if you still feel it's not a good topic to write, you can close the
issue.
