### ISSUE TITLE
VIRTUAL LOCAL AREA NETWORK (VLAN) AND HOW IT IS USED.

### ISSUE THREAD

**Issue by NJIRAI** [section-engineering-education/engineering-education#6715]
### Topic Suggestion
VIRTUAL LOCAL AREA NETWORK (VLAN) AND HOW IT IS USED.

### Writing sample(s): 
N/A

#### Proposed title of article
VIRTUAL LOCAL AREA NETWORK (VLAN) AND HOW IT IS USED.

#### Proposed article introduction
In the modern world, networking has proved to be a major boost in our day to day activities. Rarely will you find an organization with no network connectivity. This has led to an increased rise in new technologies around the world of networking. Virtual local area network (VLAN) is one of the technology that has risen over the years. While switches prove to be adequate for small organizations, large organizations will claim differently. In small networks multiple broadcast might not be a problem, but as size of the network grows, it will certainly be a major problem. The network might fill with garbage and consume large bandwidth.

Another major area of concern will be security. In large network with no VLAN, users are able to see all devices in the network. It is a huge risk especially where they have confidential information. To protect these networks, it means that you would need to restrict access to the network level by segmenting the existing network or simply placing a firewall in front of each critical system, but the cost and complexity will surely make most administrators think twice about it. This is where VLAN comes in.

What is VLAN? VLAN is a custom network which is created from one or more local area networks. It enables a group of devices available in multiple networks to be combined into one logical network. The result becomes a virtual LAN that is administered like a physical LAN. The full form of VLAN is defined as Virtual Local Area Network. Hope you will learn a lot through this article.

#### Key takeaways 
The reader should be able to get the following after reading the article;
1. Understand what we mean by VLAN.
2. Differentiate between VLAN and LAN.
3. Identify the advantages of VLAN.
4. Understand how VLAN works.
5. Know the various VLAN connections.

#### Article quality
This article covers all areas concerned with VLAN intensively. It touches on other topics related to VLAN briefly. It will be simple to understand yet covers more.

#### References
N/A

**Comment by NJIRAI** [comment]
very crucial topic

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
