### ISSUE TITLE
How To Do Proper Theming in Jetpack Compose

### ISSUE THREAD

**Issue by kirwa-elyjah** [section-engineering-education/engineering-education#6718]
### Writing Sample(s)
https://www.section.io/engineering-education/creating-custom-animated-shimmer-effect-with-jetpack-compose/

#### Introduction
Jetpack Compose apps come with a default style that allows us to manipulate shapes, colors, and typography.
However, we frequently want to augment this with other data that we'd like to include in our project, such as dimension or spacing values.
Most developers don't do their app's theming appropriately, resulting in messy code

In this tutorial, the reader will learn how to create themes in a clear and succinct manner. 

#### Key takeaways 
- Understanding Theming in Compose
- Understanding PROPER theming
- Understanding LocalCompositions
- Customizing Compose Theme
- Clean code

#### Article quality
Most developers tend to do theming in a bad way. This tutorial will show the reader on how you can do PROPER theming for an application in Jetpack compose

#### References
N/A

**Comment by WanjaMIKE** [comment]
I think this official doc -> https://developer.android.com/jetpack/compose/themes/material covers theming in Jetpack Compose adequately. Feel free to suggest another topic. Thanks
