### ISSUE TITLE
[Machine Learning] Multivariate Time Series Analysis and Forecasting with Facebook Prophet

### ISSUE THREAD

**Issue by charlesndirutu33** [section-engineering-education/engineering-education#6719]
#### Proposed title of article
[Machine Learning] Multivariate Time Series Analysis and Forecasting with Facebook Prophet

#### Proposed article introduction
Time series is a collection of data points that occur in successive order over time. A time series shows factors that influence variables in a dataset.  Examples of time series data are stock prices, weather records, product sales, forex exchange, and health records. We analyze time-series data in order to extract meaningful statistics and other characteristics of the data. Time series forecasting is used to predict future values based on previously observed values.

Time series datasets are different and are categorized into three groups: Univariate, Bivariate, and Multivariate. Univariate data –
This type of data consists of only one variable. Univariate data: This dataset consists of only one variable that changes over time. Time series analysis of univariate data is faster because the model only uses one variable during training. Bivariate data: This dataset consists of two variables that change over time. Time series analysis of bivariate data involves finding the relationships between two variables. Multivariate data: This data set contains more than two variables. Time series analysis of multivariate data is more complicated because we have to find the relationships among all the variables.

In this tutorial, we will use multivariate data to build a time series model. The dataset will have more than three variables. We will then use Facebook Prophet for time series analysis.

#### Key takeaways 
1. Univariate vs Bivariate vs Multivariate datasets.
2. Preprocessing the multivariate dataset.
3. Multivariate using Facebook Prophet.
4. Modelling a time series model.
5. Time series forecasting.

#### Article quality
This tutorial will explain the difference between univariate, bivariate, and multivariate time series. We will use in-depth and practical examples of the three types. It will also cover time series analysis and decomposition using Facebook Prophet which is a crucial stage in time series modeling. We will build a custom model using the Facebook Prophet methods and functions. This is a practical guide with detailed steps and guidance.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
I think Linus gave feedback on this topic to a user with nearly similar *username*

**Comment by WanjaMIKE** [comment]
Hi @charlesndirutu33 

Thanks for submitting your article suggestion. However, after a google search of your article title. We found multiple Youtube videos covering it. Due to this, we cannot move forward with your article suggestion. Feel free to explore other topics.

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=C+Program+to+Implement+Playfair+Cipher+Algorithm&oq=C+Program+to+Implement+Playfair+Cipher+Algorithm&aqs=chrome..69i57j69i64j69i60.294j0j4&sourceid=chrome&ie=UTF-8), this topic appears a bit oversaturated. We focus more on unique projects. Feel free to suggest another topic. Thanks
