### ISSUE TITLE
C Program to Implement Playfair Cipher Algorithm

### ISSUE THREAD

**Issue by KARIUKIJOHN** [section-engineering-education/engineering-education#6721]
C Program to Implement Play fair Cipher Algorithm

Introduction

Encryption and decryption require a cipher. The ciphertext is the term used to describe it. Different algorithms may transform plain text to encoded text using the ciphertext process. The first practical digraph substitution cipher was the Play fair cipher. In this type of cipher, we encrypt a pair of alphabets instead of a single alphabet.

Key takeaways

By the end of the article, the learners should have covered:

1. Generating key squares
2. Encryption techniques using play fair cipher
3. Decryption algorithm
4. Advantages and disadvantages of using this algorithm

Article quality
This article will provide a thorough understanding of the recommended subject. The topic is suitable for beginners since everything is thoroughly described and detailed. For optimal comprehension of the ideas needed, code snippets will be used.

References
N/A

**Comment by WanjaMIKE** [comment]
This topic appears a bit over-saturated - [search](https://www.google.com/search?q=C+Program+to+Implement+Playfair+Cipher+Algorithm&oq=C+Program+to+Implement+Playfair+Cipher+Algorithm&aqs=chrome..69i57j69i64j69i60.294j0j4&sourceid=chrome&ie=UTF-8) We focus more on unique projects. Feel free to suggest another topic. Thanks
