### ISSUE TITLE
How to make Django and Flask Microservices Work Together

### ISSUE THREAD

**Issue by khabdrick** [section-engineering-education/engineering-education#6722]
### Writing sample(s): 
https://www.section.io/engineering-education/authors/muhammed-ali/

#### Proposed title of article
How to Make Django and Flask Microservices Work Together

#### Proposed article introduction
This article will go through how the reader can potentially build microservices with Django and Flask and connect them with Docker and Redis. This will be a blog application that uses Django for its backend feature and Flask to Display the Data to the users. 

ONLY viable topics to pick from:
- API
- Containers
- Languages

#### Key takeaways 
- Build a microservice with Django
- Build a microservice with Flask
- Connect the two microservices with Redis and Docker

#### Article quality
This is a unique article

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

https://www.google.com/search?q=How+to+Make+Django+and+Flask+Microservices+Work+Together&oq=How+to+Make+Django+and+Flask+Microservices+Work+Together&aqs=chrome..69i57j69i61.284j0j9&sourceid=chrome&ie=UTF-8
