### ISSUE TITLE
How To Implement Drag and Drop File Upload In Next.js.

### ISSUE THREAD

**Issue by gisioraelvis** [section-engineering-education/engineering-education#6723]
### Topic Suggestion

How To Implement Drag and Drop File Upload In Next.js.

#### Writing sample(s):
[ENGED PROGRAM CONTRIBUTOR Gisiora Elvis](https://www.section.io/engineering-education/authors/gisiora-elvis/)

### Proposed article introduction

The Drag and Drop interfaces enable web applications to drag and drop files on a web page, providing a good user experience. This tutorial will guide the reader through how an application can accept one or more files that are dragged from the underlying platform's file manager and dropped on a web page. Will make use of the HTML5 Drag and Drop API and the FileReader API to accomplish this on a Next.js application without any additional libraries. 

#### Key takeaways

Why use a drop zone for file uploads.
An overview of the HTML5 Drag and Drop API and the FileReader API.
How to implement drag and drop file upload in a Nextjs application.

#### Article quality

This is a beginner-friendly and in-depth guide that covers the HTML5 Drag and Drop API and the FileReader API and how to use them to implement drag and drop file upload in a Nextjs application without any additional libraries.

#### References
- [HTML Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)
- [FileReader API](https://developer.mozilla.org/en-US/docs/Web/API/FileReader)
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
