### ISSUE TITLE
Multi threaded HTTP Web Server in Rust

### ISSUE THREAD

**Issue by JuliusGikonyoNyambura** [section-engineering-education/engineering-education#6724]
#### Proposed title of article

Multi-threaded HTTP Web Server in Rust

#### Proposed article introduction

When you're browsing the website, you're basically communicating with a web server. This web server will send a response from the requesting website. A multi-threaded web server enables to handle multiple simultaneous requests from the same server.

When a program is running, it is first loaded and given an address space in the main memory from your hard disk. Once loaded into the memory it is then scheduled onto an available CPU. When a process is scheduled onto a CPU, the program instructions are executed sequentially.

The CPU will execute each line of the program sequentially. It uses a program counter to determine which instruction it is about to execute. The program counter represents part of an execution context. An execution context is a current state of a running process. 

At the same time, you can have multiple execution contexts within a single process. A single execution context is called a thread. A single process can execute one or more threads. These threads can execute simultaneously to run different sections of the program.

In this case, a process is allocated in address space. The threads will share this address space that the parent process has created. This way, threads are considered a lightweight option to a process. This is because a new thread consume less memory than a new process would.

This concept of running more than one thread is called multi-threading. It enables us to do parallel computing efficiently. This guide will implement this concept using Rust.

#### Key takeaways 

- What is a Multi-threading
- How a Multithreaded HTTP Web Server
- Thread-based Server Architectures
- Why do you need Multi-threading
- How to set up the Multi-threaded HTTP Web Server in Rust

#### Article quality

There are some guidelines that run the title Multi-threaded HTTP Web Server in Rust, such as

- [rust-lang.org](https://doc.rust-lang.org/book/ch20-00-final-project-a-web-server.html)
- [oreilly](https://www.oreilly.com/library/view/the-rust-programming/9781098122539/xhtml/ch20.xhtml)
- [sergey blog](https://sergey-melnychuk.github.io/2020/04/27/multi-threaded-http-websocket-server-in-rust/)

This guide aims to export this concept of Multithreaded HTTP Web Server. The reader will then be able to build a full-fledged Multi-threaded HTTP Web Server using Rust.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Topic approved @JuliusGikonyoNyambura - Please makes sure your article is unique and adds value to what is available online.
