### ISSUE TITLE
How to Set Up Web3 Blockchain on Android using the Solana programs

### ISSUE THREAD

**Issue by manmusa100** [section-engineering-education/engineering-education#6726]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

How to Set Up Web3 Blockchain on Android using the Solana programs

#### Proposed article introduction

Web3.0 is an evolution of the internet utilizing blockchain technology and decentralization tools. On the other side, Solana is a fast, cheap, and monstrous blockchain tool. Solana is a high-performance, scalable blockchain that can support crypto applications. Solana can currently handle 50k transactions per second with an average 400ms block time. This guide will implement the Salona blockchain concept using Android.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- What is Web3
- The Relationship Web3 and Blockchain
- What is Solana
- What makes Solana unique
- Set Salona for Android
- Consume Salona using Android

#### Article quality

The reader will learn more about Salona programs while consuming the Salona APIs using Android.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Topic approved @manmusa100 - Please make sure your topic is unique and adds value to what is available online.
