### ISSUE TITLE
How does Quantum key distribution function (QKD)

### ISSUE THREAD

**Issue by Adebogunabdulroheem** [section-engineering-education/engineering-education#6730]
### Topic Suggestion
How does Quantum key distribution function (QKD)

#### Pre-submission advice
Because QKD encrypts data using physics rather than algebra, quantum key distribution (QKD) is the only probably secure communication technique. QKD's security comes from its ability to detect any intrusion on the QKD communication. Because photons have unique and fragile properties, any effort by a third party (or eavesdropper) to read or reproduce them in any way will change their state. The endpoints will detect the change and notify them that the key has been tampered with and should be destroyed. Following that ,then, a new key is sent. Furthermore, since the keys are really random, they are safe from future hacking efforts.

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
By the conclusion of this lesson, you should know:
1. What is QKD and how does it function?
2. What makes QKD impenetrable?
3. Network expansion of QKD
4. How does the future of quantum key distribution appear?

#### Article quality
QKD's security comes from its ability to detect any intrusion on the QKD communication. With QKD all security operations that entail encrypting communication using physics for its encryptions will all be explained in detail in this lesson.

### Conclusion
At the conclusion of this session, you should have a thorough understanding of how quantum key distribution works. 
Unlike other blogs that discuss QKD on the surface, we will go deep into vital QKD facts with you.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
