### ISSUE TITLE
How to Combine and run a Navigation bar and Bottom bar using Jetpack Compose on Android

### ISSUE THREAD

**Issue by Wachira48** [section-engineering-education/engineering-education#6731]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

How to Combine and run a Navigation bar and Bottom bar using Jetpack Compose on Android

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Jetpack Compose is our modern native UI toolkit for android. Jetpack Compose is a new way of designing native android apps using Kotlin without XML. The then XML code is now replaced with Kotlin to design our android apps. The design logic is implemented in Kotlin. It is intuitive and built from scratch to accelerate development, letting you write UI with much less code. This means you just focus on building features and spend less time creating UI you want to showcase in your android application. This guide will use Jetpack Compose to create android navigation. In this guide, we will create and run a Navigation bar and Bottom bar using Jetpack Compose on Android. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- What is Jetpack Compose
- Getting started with Jetpack Compose
- Build a Navigation bar menu Jetpack Compose 
- Build bottom navigation using Jetpack Compose
- Run the Navigation bar menu and bottom navigation 

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Jetpack Compose is a new technology for building native android apps using Kotlin. Several articles describe how to create navigations but using XML codes.

This guide will focus on using Jetpack Compose to run both the Navigation bar menu and bottom navigation bar. The app will run them both in a single activity and show how users can interact with them.

There is a section guide that explains how to create bottom navigation using Jetpack Compose. However, this guide aims to create a full application that runs on the bottom navigation using Jetpack Compose and the navigation bar menu.

There is also another article that creates a bottom navigation bar. However, it does not run on Jetpack Compose. This guide runs the whole app using the Jetpack Compose kotlin code.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Thank you for submitting your topic @Wachira48.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
