### ISSUE TITLE
Understanding wavelet properties and the application of these properties

### ISSUE THREAD

**Issue by simonmwaniki** [section-engineering-education/engineering-education#6738]
### Topic Suggestion
Understanding wavelet properties and the application of these properties

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-design-logistic-map-using-matlab/

#### Introduction
A wavelet is a waveform of effectively limited duration with an average value of zero and nonzero norm. Many signals and images of interest exhibit piecewise smooth behaviour punctuated by transients. Wavelet bases are adept at sparsely representing piecewise regular signals and images, including transient behaviour.
When choosing a suitable wavelet, it is essential to understand a few basic properties of the wavelets, such as Vanishing moments, Support width, Regularity, Symmetry and Orthogonality. These properties help us in the selection of suitable wavelets. This tutorial will show how one can choose an appropriate wavelet transform and the right wavelet for a particular application.

#### Key takeaways 
- What to choose CWT or DWT?
- Understanding wavelets properties.
- Wavelets for Feature Extraction.
- Wavelets for Denoising.
- Wavelets for Compression.
- Wavelets for detection of change or discontinuity.
- Wavelets for other applications (Analysis of Variance, Watermarking, Edge detection, ECG signals, OCR).

#### Article quality
This article covers the wavelet properties and the various application of these properties.

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=Understanding+wavelet+properties+and+the+application+of+these+properties) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by simonmwaniki** [comment]
@louisefindlay23 Wavelet uses a specially generated set of self-similar, orthonormal basis functions that are localized in space and time. This enables wavelet analysis to be performed at different scales or resolutions. Here, we look at the orthonormal functions to perform the wavelet analysis and generate their properties.

**Comment by louisefindlay23** [comment]
@simonmwaniki, are orthonormal functions your unique content that has not been covered elsewhere?

**Comment by simonmwaniki** [comment]
@louisefindlay23 yes. In addition, we look at the vanishing moments, Support width, Regularity, Symmetry properties of these wavelets.
