### ISSUE TITLE
Understanding intermediate representation techniques in compiler design

### ISSUE THREAD

**Issue by root5086** [section-engineering-education/engineering-education#6745]
#### Proposed article introduction
Intermediate code generation is the forth phase of the compilation process after lexical analysis, syntax analysis and semantic analysis. This phase just involves the translation of code into machine independent language. This brings up the need to study techniques and methods of representing these intermediate code in a language that would be executable in any machine to reduce cost and and increase efficiency.

In this article I will be discussing an introduction to intermediate code generation and hence the need for representation techniques. I will the go ahead and discuss the different techniques used in intermediate representation such as Three Address Code,  Directed Acyclic Graphs (DAG), Abstract Syntax Trees (AST)and finally P-code. I will exhaustively discuss there functionalities and use illustratory diagrams a example.

#### Key takeaways 
1. The reader will be able to understand what intermediate code generation is. 
2. The readers will be able to understand the need for intermediate representation techniques in compiler design.
3. The reader will be able to understand the different techniques used in intermediate representation and even be able to attempt example.
4. 
#### Article quality
This article will have a clear and rich introductory background for easy understanding to everyone. I will also use explanatory examples to ensure understanding and flow to the readers. This article will contain everything there is to know about the techniques of intermediate representation.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=Understanding+intermediate+representation+techniques+in+compiler+design) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?
