### ISSUE TITLE
Introduction to LL and LR parsers in compiler construction

### ISSUE THREAD

**Issue by elphazesedah** [section-engineering-education/engineering-education#6746]
#### Proposed article introduction

Parsing is the process of converting an input string into an intermediate representation wit the help of a given predefined grammar. This phase of compiler design is also refereed to as syntax analysis.

LL and LR are parsers used in top-down and bottom-up parsing respectively. LR parser generates parse trees for given strings using unambiguous grammar. LL parsers on the other hand uses context free grammar to generate parse trees for given input strings.

In this article I will introduce the basics of parsers just for general understanding to the reader. I will then go ahead and dive into LL parser discussing its general description, how it works, what grammar it uses and finally the general parsing process of the parser at hand using an example. I will then discuss the LR parser in terms of general description, how it works, the kind of grammar it uses and finally the general functionality of the parser illustrated using an example. Finally ill give a detailed comparison of the two parses.

#### Key takeaways 
1. The reader will be able to understand what LL and LR parsers are.
2. The reader will be able to understand the general functionalities of the two parsers and the grammars that they accept.
3. The reader will be able to parse a given input string using LL and LR parsers.

#### Article quality

This article will have a clear and rich introductory background for easy understanding to everyone. I will also use explanatory examples to ensure understanding and flow to the readers. This article will contain everything there is to know about LL and LR parsers all in a single page.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
