### ISSUE TITLE
POST JSON excluding model and Ajax

### ISSUE THREAD

**Issue by ndungusam** [section-engineering-education/engineering-education#6747]
**Proposed article introducton**

Microsoft introduced AJAX quite some time to enable its web functionality. AJAX removed need for users to continously force a page or refreshing by use of enter button. In this article we shall be demonstrating how to send data from the ASP.net web using Ajax post method without form conversion.  In this article series, we will learn two methods to send the data from View to Controller using the ajax post method in the ASP.NET Core application.
We will use the following methods to submit the form data in this article series:
1. JSON Form  conversion
2. Without form conversion

**Key takeaways**

1. An introduction overview on what is POST JSON and Ajax
2. Covering the JSON form conversion
3. Without form conversion
4. Addition of a an action method named as CreateStudent which wewill use to create a view without form conversion.

**Article quality** 

In this article the reader will become more familiar with what is Ajax and Post Json. This article will have a clear introductory background for easy understanding to everyone. it will contain everything that contains differences of Json form conversion and the non-Json form conversion.

**Reference**

N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
