### ISSUE TITLE
[Languages] How to Use Control Flow In Bash

### ISSUE THREAD

**Issue by JudyNduati** [section-engineering-education/engineering-education#6748]
### Topic Suggestion
How to Use Control Flow In Bash

#### Proposed title of article
How to Use Control Flow In Bash

#### Proposed article introduction
Bash scripting is a great way to automate repetitive tasks and can save you a ton of time as a developer. Bash scripts execute within a Bash interpreter terminal. 

Bash is an extremely flexible language, in order to use it as a scripting language, or build complex programs, you can leverage the `while` and `for` control flow statements. This tutorial will present the full range of bash conditionals, with examples, and show developers how to use them for common bash operations.

#### Key takeaways 
1. Briefly introduce bash.
2. Understand bash control flows
3. Provide step-by-step instructions on implementing the following bash control flows

#### Article quality
This is a well-detailed tutorial, and readers will gain much by going through it as there are not many articles on this topic. It will be beginner-friendly as well as provide information.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
