### ISSUE TITLE
security enhancement using face detection in C#

### ISSUE THREAD

**Issue by owndynyagudi** [section-engineering-education/engineering-education#6749]
### Topic Suggestion
security enhancement using face detection in C#

#### Proposed title of article
security enhancement using face detection in C#

#### Proposed article introduction
Security is a major concern in every system. Many applications have a way to perform verification of data so as to prevent unauthorized users from accessing the system. Common fields that uses the technology of facial recognition  include: Mechatronics, robotic, criminalistics, etc. This article will explain the easiest way through which face detection and recognition can be achieved using C# to create more secured systems.

#### Key takeaways 
1. What face detection and recognition is
2. Applications/ fields where face recognition can be used.
3. Required tools to implement face recognition in C#
4. The process of achieving face recognition in C#
#### Article quality
This article will provide an easier approach to implement face recognition and detection using simple code snippets.
#### References
https://towardsdatascience.com/how-to-build-a-face-detection-and-recognition-system-f5c2cdfbeb8c
https://www.geeksforgeeks.org/face-recognition-using-artificial-intelligence/

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
