### ISSUE TITLE
[Language]How to Make a Turtle Racing Game with PyCharm

### ISSUE THREAD

**Issue by taves-hub** [section-engineering-education/engineering-education#6754]
### Topic Suggestion
How to Make a Turtle Racing Game with PyCharm

#### Proposed article introduction
In this article, I will teach learn how to build a racing game in Python using the Turtle library in just small lines of codes. It will be a more practical since you would like to experience the fun of making the game. It may seem complicated but i will simplify everything to enable the novices follow without any difficulties.  

Turtle is a pre-installed Python library that enables users to create pictures and shapes by providing them with a virtual canvas. The onscreen pen that you use for drawing is called the turtle and this is what gives the library its name. Most developers use turtle to draw shapes, create designs, and make images. But in our case we will use it to design and create a Racing Game. 

Very basic knowledge of Python programming will be enough to go through this article. Also I will teach everything about this turtle library assuming that the novices will get to understand it better. I will teach you everything from scratch.

#### Key takeaways 
- Prerequisites
- Requirements and Installations
- Turtle Library overview
- Defining the Game Canvas
 - Adding Background Graphics
- Working with Turtle Objects 
- Creating the turtle replicas
- Removing the ugly lines
- Moving the turtles forward
- Running multiple turtles in sync
- Setting random moving speed 
- Setting the Finish Line
- Prompting the User to Enter Their Bet 
- Displaying the winner on the Screen

#### Article quality
This article will be easy to follow for those aspiring to use Python for Game Development. I accept information can never be depleted and this article will be fledgling to be clear even to Python novices.

#### Reference
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
