### ISSUE TITLE
Invoking Functions in Kotlin

### ISSUE THREAD

**Issue by RayBrian269** [section-engineering-education/engineering-education#6759]
Topic Suggestion
Invoking functions in Kotlin 
Proposed title of article
Invoking functions in Kotlin 
Proposed article introduction
An interesting feature of the kotlin language is the ability to define an “invoke operator”. Hence when you specify an invoke on a class, it can be called on any instances of the class without a method name. This trick is very useful for classes that really only have one method to be used. In this article I will show everything, and all the relevant examples by creating different invoke functions. Invoking operators also allows instances of your classes to be called as functions.
Key takeaways
1.	What is invoke functions
2.	Defining Invoke operator
3.	Specifying invoke operator on a class

Article quality
This article will provide an easier approach to invoke functions in Kotlin and how to specify invoke operators on a class.
References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @RayBrian269.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
