### ISSUE TITLE
[Security]A Comprehensive Guide to Web Application Firewalls 

### ISSUE THREAD

**Issue by k-lusote** [section-engineering-education/engineering-education#6761]
### Topic Suggestion
Security

### Writing sample(s): 
N/A

#### Proposed title of article
A Comprehensive Guide to Web Application Firewalls

#### Proposed article introduction
Security is a vital consideration in any technology in use. be it mobile phone, application and even server require a certain degree of security implementations that protect and ensure they accomplish their tasks. Security experts and other technology professions recognize the need of having a firewall. However, the traditional firewall that most people are familiar with only serve to protect a device or application only in the second and third layer of the OSI protocol stack. A new breed of firewall has risen with the increased adaptation of web application. This kind of firewall are able to provide protection in the upper layers of the OSI model. This article seeks to provide a comprehensive guide to the new breed of firewalls known as web application firewalls.

#### Key takeaways 
The reader will get to :
- Understand what are web application firewalls and how they work.
- Features of a web application firewall.
- The models of web application firewalls. 
- The types of web application firewalls available in the market. 
- The kind of threats these type of firewalls avert.

#### Article quality
This article is meant to offer a high quality standard by offering a detailed walk though for the reader to fully understand the concept of web application firewalls. Other articles on the web focus on defining what are web application firewalls. But, this article goes beyond a simple definition of WAFs. 
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Thank you for submitting your topic @k-lusote.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
