### ISSUE TITLE
[Android]The Making of Jetpack Compose FormBuilder

### ISSUE THREAD

**Issue by LinusMuema** [section-engineering-education/engineering-education#6762]
### Writing sample(s): 
[Advanced Form Operations in Jetpack Compose](https://www.section.io/engineering-education/jetpack-compose-forms/)

#### Proposed title of article
The Making of Jetpack Compose FormBuilder

#### Proposed article introduction
We recently released the first version of the Jetpack Compose FormBuilder. Getting the inspiration from the [flutter_form_builder](https://pub.dev/packages/flutter_form_builder), we got various aspects of form and the operations in them. Written in Kotlin, the library borrows various concepts such as Kotlin generics and reflection which are areas most android developers don't explore much. The article goes over the classes and functions in the library. It also goes through the decisions made during the development process and the research results from various items.

#### Key takeaways 
By the end of the article, the readers will have:
* A understanding of how to install and use the library
* The methods and classes available in the library
* Kotlin generics and reflection details used in the library
* State management in the form 

#### Article quality
The article hasn't been written on the internet as I created the library and documentation.

#### References
N/A

**Comment by Kayere** [comment]
Cool topic @LinusMuema - Approved.
