### ISSUE TITLE
[Languages]Scanning Microsoft Excel Files using Java

### ISSUE THREAD

**Issue by issakgacogu** [section-engineering-education/engineering-education#6763]
#### Proposed title of article
Scanning Microsoft Excel Files using Java

#### Proposed article introduction
In this segment, we are going to learn how we can read data from an excel file.

In Java, reading excel file is not similar to read word file because of cells in excel file.
JDK does not provide direct API to read or write Microsoft Excel or Word document.

We have to rely on the third-party library that is Apache POI.

#### Key takeaways 

1. Installing and working with Apache POI.
2. Working with Interfaces and Classes.
3. Reading data from XLS file.
4. Reading a particular cell value from a excel file (.xlsx)

#### Article quality
It is written in a simple and easy way to understand using fun code snippets. The goal is to ensure the concept is easy to grab by a beginner and also makes it easy for intermediate and advanced users to apprehend.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @issakgacogu 

After a google search of your topic suggestion, we found several articles that cover the same content as your proposed articles. Due to this, we cannot move forward with the article suggestion. You are more than welcome to explore other topic areas.
