### ISSUE TITLE
How to use wavelet analysis and deep learning to classify signals using Matlab

### ISSUE THREAD

**Issue by florenceakinyi** [section-engineering-education/engineering-education#6764]
### Topic Suggestion
How to use wavelet analysis and deep learning to classify signals using Matlab

### Writing sample(s): 
https://www.section.io/engineering-education/linear-time-invariant-systems-analyzer-using-matlab/

#### Introduction
Wavelet analysis is a mathematical technique used to represent data or functions. The wavelets used in the analysis are functions that possess certain mathematical properties and break the data down into different scales or resolutions. Deep learning is a machine learning technique that teaches computers to do what comes naturally to humans.
Using wavelet analysis and deep learning, we can classify time series data. So it is by using the wavelet features of the data and using these features for training and testing time-series data. A time series(signal) is a collection of observations of well-defined data items obtained through repeated measurements over time. This article will see how to classify these signals using wavelet analysis and deep learning using Matlab.

#### Key takeaways 
- Various continouos time series data base.
- Understanding continouos time series.
- How to create time-frequency representation.
- Matlab code to train your data.
- Matlab code to test your model.

#### Article quality
This article use the wavelet features of the data for classification. This means it also covers the wavelet feature extraction in Matlab.

**Comment by LinusMuema** [comment]
Hi @florenceakinyi 

After a google search of your topic suggestion, we found several articles that cover the same content as your proposed articles. Due to this, we cannot move forward with the article suggestion. You are more than welcome to explore other topic areas.
