### ISSUE TITLE
Building a custom user reviews page with stars rating in react, typescript and Bootstrap library

### ISSUE THREAD

**Issue by TonyRichardd** [section-engineering-education/engineering-education#6767]
### Topic Suggestion
Building a custom user reviews page with stars rating in react, typescript and Bootstrap library

#### Proposed title of article
Building a custom user reviews page with stars rating in react, typescript and Bootstrap library

Use keyword research to improve your article's SEO.

#### Proposed article introduction
In front-end web development, most application is expected to be users (client) centric, meaning the overall users reviews and recommendations must be taken into consideration. Most applications rely on user feedback to improve their service quality delivery.
React, typescript and Bootstrap can be an incredible combination in building a custom user review page that users’ recommendations and stars rating can be displayed, similar to apple store and google play store reviews section.
In this article, we will take a deep dive into the various steps and package dependencies required to build a custom user reviews page in react and typescript.

#### Key takeaways 
After reading the article, the reader is expected to understand and be able to implement the below:
-	Getting started with React application development
-	How to add and use typescript in React
-	Adding and using the Bootstrap library dependency in a React application.
-	Building a custom user review page with star ratings in React.js, typescript and Bootstrap
-	How to populate star rating in typescript

#### Article quality
This tutorial is a unique project-based application of React.js and Bootstrap in creating, customizing and styling a web application. This article will feature the building a of multiple components in React.js and how to populate star ratings. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by TonyRichardd** [comment]
@LinusMuema 
My article is not just centered on the stars rating alone, but the creation of a fully custom user review page. I will be using Material-UI library to show the users avatar, the comments (reviews) and perhaps how to design a form to retrieve the comments from the user. The article you pointed to just covered how to populate stars in typescript but I'll definitely go beyond that.
Best regards

**Comment by LinusMuema** [comment]
Hi @TonyRichardd 

Make sure to focus more on the custom features to make your article stand out more. 

topic approved 🚀
