### ISSUE TITLE
[Security]Improving Password Integrity Through Salting in Java

### ISSUE THREAD

**Issue by Su-sid** [section-engineering-education/engineering-education#6771]
### Topic Suggestion
Security

### Writing sample(s): 
[Understanding quality of service](https://www.section.io/engineering-education/understanding-quality-of-service/)
#### Proposed title of article
Improving Password Integrity Through Salting in Java
#### Proposed article introduction
Passwords are the most widely used authentication technique on the globe. The popularity of passwords stems from their ease of generation and convenience of usage. To have a password, a user only needs to use characters or phrases that they can remember and are unique to them.  Nonetheless, the basic nature of passwords makes them easy to compromise.  As a result, developers frequently consider hashing and salting their users' passwords for security concerns. salting increases the integrity of passwords saved in a database.

#### Key takeaways 
- Detailed understanding of what salts are and why they matter.
- Dangers of using an unsalted password. 
- Importance of random character generators in salting
- A number of code snippets to take the reader through each of the steps in implementing salting through 
           1. User defined random characters 
           2. Using random character generators.
           3. Using the Bycrpt algorithm.
#### Article quality
My article is unique as it follows a step-by-step procedure explaining in simple language what is happening in each block of code. this is to allow the reader to gain a closer understanding of how to do what am explaining on their own without any difficulties. the article follows a systemic approach of how I broke down the problem, question and solved the problem in different ways until I found a solution.

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @Su-sid 

Thank you for suggesting your article. However, after a google search of your topic suggestion, we found several articles that talk about salting like [this one](https://auth0.com/blog/adding-salt-to-hashing-a-better-way-to-store-passwords/). Due to this, we cannot move forward with your article. Feel free to explore other topics of your interest.

> Your article suggestion was pretty well written. I would suggest you look for another topic that isn't widely covered and I think it would be awesome.
