### ISSUE TITLE
Developing a text-to-speech software in Android using Java

### ISSUE THREAD

**Issue by Kimosop-Wakanda** [section-engineering-education/engineering-education#6772]
### Topic Suggestion
Developing a text-to-speech software in Android using Java

### Writing sample(s): 
https://www.section.io/engineering-education/authors/meshack-kimosop/

#### Proposed title of article
Developing a text-to-speech software in Android using Java

#### Proposed article introduction
In order to develop satisfactory software, there are a couple of steps to be followed to do so. There are also prerequisites required to develop the software such as the IDE, suitable programming language, etc.
In the proposed article, we will develop a text-to-speech software using android studio in java.  The learner will not only learn to do so but also learn how to apply the knowledge to develop their own software.
The software to be developed will be able to convert written text to speech and relatively covert audible speech to text.
The learner will also learn how to modify the XML file to make the software more appealing and to modify the java file to make it more interactive.
After successfully developing the software, the learner will get to know how to publish the application software in the playstore.

#### Key takeaways
- Setting up the prerequisites and installing android studio
- Developing XML file for the software
- Programming objects in XML file 
- Running the software on an android device
- Publish the software in the play store

#### Article quality
This article will use well-explained code snippets to help the learner understand a step to step development of software. Images where appropriate will be used to give good guidance in the development process.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Could you change the topic to Developing a text-to-speech software in Android using Java

**Comment by Kimosop-Wakanda** [comment]
@WanjaMIKE 
I have made the change on the topic to the suggested one.

**Comment by WanjaMIKE** [comment]
Noted @Kimosop-Wakanda Let's ensure that it adds value to the community. Thanks
