### ISSUE TITLE
[Languages] Is Golang the Best Fit for embedded systems?

### ISSUE THREAD

**Issue by wanjcarol** [section-engineering-education/engineering-education#6778]
#### Proposed title of article
Is Golang the Best Fit for embedded systems?

#### Proposed article introduction
Developers use a variety of programming languages in embedded systems. The most used languages include C, C++, Python, MicroPython, and Java. In this article, however, we'll analyze Golang's usage in embedded programming and compare it to the C language.

Go is a new generation language, which holds both Python’s fast prototyping and C/C++ applications performance. This trait makes it suitable to be used in embedded field. 

#### Key takeaways 
1. What do embedded systems require? Why does Go fit? 

2. GO vs C for embedded systems

- I/O management 
- Memory management
- Concurrency 
- Compilation 

3. Golang's weaknesses when building embedded systems 
#### Article quality
This article presents a case you may start using Go, a new generation language, for your embedded system needs. It goes further to compare Go to C - the popular language for building embedded systems. 
#### References
https://go.dev/
https://devdocs.io/c/

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
