### ISSUE TITLE
How to send HTTP Requests in Python with urllib3

### ISSUE THREAD

**Issue by Alicewangari** [section-engineering-education/engineering-education#6779]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Web resources are identified by a web address (even if it is not accessible), which is commonly referred to as a URL (Uniform Resource Locator). Most of the time, an end-user manipulates these resources (retrieves, updates, deletes, etc.) utilizing the HTTP protocol and HTTP Methods.

`urllib3` is a powerful, user-friendly HTTP client for Python that adds many important features not found in the standard Python libraries.

In this tutorial, we'll look at how to use the `urllib3` module, which allows us to send HTTP requests programmatically using Python.

#### Key takeaways 
1. Introduction to `urllib3` Module
2. How to Send HTTP Requests in Python with `urllib3`
3. Uploading Files with `urllib3`
4. Send HTTP GET Request
5. HTTP POST Request

#### Article quality
In this tutorial, we'll look at how to use the `urllib3` module, which allows us to send HTTP requests programmatically using Python.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=How+to+send+HTTP+Requests+in+Python+with+urllib3&oq=How+to+send+HTTP+Requests+in+Python+with+urllib3&aqs=chrome..69i57j35i39i362l6j69i60.232j0j7&sourceid=chrome&ie=UTF-8), this topic seems a bit over-saturated. Feel free to suggest another topic. Thanks
