### ISSUE TITLE
Why Data Storage is Shifting to the Blockchain

### ISSUE THREAD

**Issue by Snzovi** [section-engineering-education/engineering-education#6780]
#### Proposed title of article
Why Data Storage is Shifting to the Blockchain
#### Proposed article introduction
When it comes to data storage solutions, there was a moment when traditional in-house data centers were phased out, and the cloud entered the scene as a viable option. However, things are progressing, and it may soon be the turn of distributed storage, which will be based on Blockchain or a Blockchain data storage solution.

The secure data storage market is currently dominated by huge third-party providers, and now it is one of the key targets for Blockchain developers. Soon, everyone could all have access to cheap, secure ways of handling even the most sensitive data, without needing to trust any third parties.
#### Key takeaways 

1. Blockchain storage vs. cloud storage
2. Costs implications of storing data on the blockchain
3. How blockchain is transforming cloud storage
4. Current blockchain storage products available

#### Article quality
The adoption of blockchain as a more secure, cost-friendly alternative data storage system is gaining momentum. It is, therefore, imperative to discuss this not so much explored topic to help get leaders prepared of what to expect of blockchain as a data storage solution.

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic @Snzovi
