### ISSUE TITLE
Getting started with Scaffold in Flutter

### ISSUE THREAD

**Issue by adikutch** [section-engineering-education/engineering-education#6782]
#### Proposed title of article
Getting started with Scaffold in Flutter

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Scaffold is a module present in Flutter that is mostly used in the implementation of the basic material design visual layout structure. When using scaffold in the building of an application, it is easy and do not contain a lot of complications when it comes to the implementation of the same. Still scaffold makes it easier for programmers to develop and implement  responsive applications in this case.

Therefore in this article, we are going to deeply look at how we can develop an application putting into consideration the various buttons which we are supposed to use for the purposes of having a well defined output.

#### Key takeaways 
1. Body- Whose main task is displaying the main content available in the scaffold
2. Using the scaffold drawer property to create the drawer
3. The output  

#### Article quality
The quality of the content that will be in this article is one which will be well understood by any level of learners in the programming world.

#### References
N/A

**Comment by WanjaMIKE** [comment]
I think Scaffold is a basic thing in Flutter and is adequately covered in the documentation.
