### ISSUE TITLE
Working with Datetime in Python with Delorean

### ISSUE THREAD

**Issue by mosesmwangi442** [section-engineering-education/engineering-education#6785]
#### Proposed title of article
Working with Datetime in Python with Delorean

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Working with datetime may be intimidating and difficult, and Python's implementation is no exception. The built-in datetime module in Python exposed us to various classes, including date, datetime, time, timezone, and timedelta, and several external libraries, such as Arrow, have sprung up to solve the shortcomings with the official module.

In this tutorial, we'll look at how to construct and read datetime objects in Delorean, a library built on `pytz`, the standard library for managing timezone difficulties, and `dateutil`, which is used to compute deltas between any two `datetime` objects.

#### Key takeaways
By the end of the article, the readers will learn:
- Installing Delorean
- Creating a Delorean Datetime Object
- Convert String to Delorean Datetime Object
- Generating a Sequence of Dates

#### Article quality
The reader will learn how to convert a string to `datetime` in various formats, how to convert an epoch timestamp into datetime, and how to generate a sequence of dates using the `stops()` generator.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon___ and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations.
