### ISSUE TITLE
INTRODUCTION TO CISCO WIRELESS 3D ANALYZER

### ISSUE THREAD

**Issue by AfubeAngel** [section-engineering-education/engineering-education#6786]
#### Proposed article introduction
The wireless 3D analyzer is a recent and powerful addition to tools that aid in the planning, deploying, and managing of wireless networks across floors and buildings. It gives a more solid perspective of the entire network, provides information on how it affects users, and most importantly, takes into accounts obstacles and interferences that can affect the network. This effective system performs these incredible functions through stimulations and the replication of the floor map.
 
In this article, I will give detailed insight into the Cisco wireless 3D analyzer, its improvement over the 2D map, and basic KYI that aids a network administrator plan and efficiently understand the workings of the system. In addition, I would give an overview of basic terminologies that would help in assimilating how the 3D analyzer works in a wireless network system and its importance in monitoring, troubleshooting, deploying, and maintaining a good network.

#### Key takeaways 
At the end of this article, readers would be able to:
 
1.	Understand how the cisco wireless 3D analyzer works.
2.	Use the fundamental features of the 3D analyzer in planning and deploying a simple network.
3.	Learn how to interpret the stimulations presented in a wireless 3D analyzer regarding the management of networks and interference detection.
4.	Understand the cisco wireless 3D analyzer's effectiveness and role in a wireless network.

#### Article quality
This article is unique because it provides an in-depth knowledge of the cisco wireless 3D analyzer and its role in a network. It further elaborates on its improvement over the 2D map, the functionalities that make it spectacular, and demonstrate how a network specialist can utilize it effectively.

#### References
https://community.cisco.com/t5/cisco-digital-network/introducing-the-wireless-3d-analyzer-on-cisco-dna-center-2-2-3-x/td-p/4530995

https://hostingjournalist.com/cisco-wireless-3d-analyzer-how-to-demo/

https://blogs.cisco.com/networking/cisco-wireless-3d-analyzer

https://www.rcrwireless.com/20211029/test-and-measurement/test-and-measurement-cisco-intros-3d-wi-fi-network-planning

https://bigfin.com/blog/why-it-is-important-to-keep-up-with-changing-technology-trends/

### Conclusion
This article presents an innovative and advanced way of planning, monitoring, and maintaining a wireless network. I hope you find this article efficient in keeping up with trends in the tech world while increasing your wealth of knowledge on wireless connectivity. On its release, the cisco wireless 3D analyzer was described as a game-changer, and with this article, we would see why and how.

**Comment by hectorkambow** [comment]
Good afternoon___ and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations.
