### ISSUE TITLE
Handling missing data: understanding predictive mean matching and regression modelling in R

### ISSUE THREAD

**Issue by valentineomondi99** [section-engineering-education/engineering-education#6787]
### Topic Suggestion
Handling missing data: understanding predictive mean matching and regression modelling in R

#### Proposed title of article
Understanding predictive mean matching and regression modelling in R

#### Proposed article introduction
Any real-world datasets have missing data, which causes problems for both modeling and analysis. To solve this we use  Bayesian statistics-the posterior predictive distribution of possible unobserved values conditional on the observed values according to wikipedia. We will attempt to solve this problem using regression modelling and predictive mean matching using R software. Now linear regression has its limitations — it doesn’t allow for non-linear relationships and needs manual intervention to handle interactions .PMM is great  with non linear models. We will visualize missing data using various plots.

In this article we will cover these concepts extensively with each problems solving method.

#### Key takeaways 
-What is regression modelling
-The student will learn data cleaning methods
-The student will learn about some data visualizations in R
-The student will learn about predictive mean matching method to solve for missing data

#### Article quality
This article aims to make the learner able to solve missing data in datasets and each case method is well explained.

#### References
N/A

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
