### ISSUE TITLE
[Machine Learning] Model explanation with Dalex

### ISSUE THREAD

**Issue by simonkamau497** [section-engineering-education/engineering-education#6788]
#### Proposed title of article
[Machine Learning] Model explanation with Dalex

#### Proposed article introduction
Model explanation allows human users to comprehend and trust the results and output created by machine learning algorithms. Dalex is used to describe an AI model, its expected impact and potential biases. It helps characterize model accuracy, fairness, transparency and outcomes in AI-powered decision making. It is crucial for an organization in building trust and confidence when putting AI models into production. Model explainability also helps an organization adopt a responsible approach to AI development.

Dalex has a set of tools and frameworks to help you understand and interpret predictions made by your machine learning models. Understanding how an AI-enabled system has led to a specific output.  Explainability help developers ensure that the system is working as expected, it might be necessary to meet regulatory standards.

Dalex contrasts with the concept of the  black box in machine learning where even its designers cannot explain why an AI arrived at a specific decision. Model explanation will determine the logical reasoning of the model when making a prediction and explains the decisions made by the model.

#### Key takeaways 
1. Black box vs transparent/glass box models.
2. Benefits of model explanation.
3.  Dalex installation and Dalex `explain ()` function.
4.  Building a customer churn model  using Logistic Regression.
5. Explaining the customer churn model using Dalex.

#### Article quality
This article is unique because it will enable us to build a full transparent model. It is crucial for an organization to have a full understanding of the AI decision-making processes with model monitoring and accountability of AI. It also enable stake holders not to trust them blindly. Using the Dalex functions and methods, users will be able to understand and explain machine learning (ML) algorithms, deep learning and neural networks. This tutorial will use step-by-step guide of how to explain a customer churn model.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
