### ISSUE TITLE
[Machine Learning] An Overview of the Swin Transformer

### ISSUE THREAD

**Issue by lcheptoo** [section-engineering-education/engineering-education#6789]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

An Overview of Swin Transformer

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

In 2021, Transformers were introduced to replace the popular ConvNets in solving computer vision tasks. This Transformer model introduced a patch layer that splits an image into a sequence of patches of 16 by 16 pixels. This Transformer model is called the Vision Transformer (ViT). Yet, the ViT had to rely heavily on a lot of training tricks such as data augmentation to make it reach the performances of state-of-the-art models like ConvNets. This model faced difficulties when it came to solving more general computer vision tasks. This led to the release of a new vision transformer model called the Swin Transformer.

It introduced sliding windows (used in CNNs) into Transformers, which made them resemble ConvNets pretty much. This model made the vision transformer more general-purpose and could be used for a wide variety of vision tasks.

This article will give an overview of this model.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this article, a reader should be able to understand:

- Problems with the Vision Transformer.
- What is the Swin Transformer.
- Architecture of the Swin Transformer

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

The Swin Transformer is a fairly new model released in 2021. This article will give an overview of the model in simple words. We know that reading and understanding research papers can be difficult. This article will break it down for our readers. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [Swin Transformer: Hierarchical Vision Transformer using Shifted Windows](https://arxiv.org/abs/2103.14030)

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
