### ISSUE TITLE
Android Notifications

### ISSUE THREAD

**Issue by paulodhiambo** [section-engineering-education/engineering-education#679]
### Brief Summary: 
Notifications are messages that Android displays outside your app's UI to provide the user with reminders, communication from other people, or other timely information from your app. Users can tap the notification to open your app or take an action directly from the notification.

### Key Takeaways: 
- Android notifications.
- Different types of android notifications.
- How to create different types of android notifications.
- Creating custom Android notifications.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
[Android docs](https://developer.android.com/guide/topics/ui/notifiers/notifications)

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @paulodhiambo . Could you please explain how your article will differ from the docs that you've referenced? We need to be sure that we're presenting original, unique content beyond what's already readily available through public sources.

**Comment by paulodhiambo** [comment]
@ninjaginja the article will be explaining android notifications beyond the basic explanations which are available in the documentation. I will be explaining from the basics of notifications to advance concepts like sending notification messages through Firebase cloud messaging.
