### ISSUE TITLE
How to create a Chat bot in Python using JSON file

### ISSUE THREAD

**Issue by apondi-911** [section-engineering-education/engineering-education#6790]
#### Proposed title of the article
How to create a chatbot in Python using JSON

#### Proposed article introduction
A chatbot is an artificial intelligence (AI) software that can imitate a natural language interaction (or chat) with a user in natural language via messaging apps, websites, mobile apps, or the telephone. It is often described as one of the most advanced and promising expressions of interaction between humans and machines. 

A chatbot only represents the natural evolution of Natural Language Processing (NLP). NLP allows computers and algorithms to understand human interactions via various languages. The task of interpreting and responding to human speech is filled with a lot of challenges thus to overcome these challenges, programmers have integrated a lot of functions to the NLP tech to create useful technology that you can use to understand human speech, process, and return a suitable response.

Python is the preferred language in this article because it is versatile and an easy language for a beginner to pick up with its consistent syntax. Moreover, the natural processing language was written in python.

#### Key takeaways 
- Get to know how a chatbot works
- Types of chatbots
- What an NLP is and how it is applied in chatbots
- How to create a JSON file
- Implementing python language

#### Article quality
This article will help the learner know how a natural processing language works.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations.
