### ISSUE TITLE
[Languages]A Dive Into HashMaps, TreeMaps and HashTables in Java

### ISSUE THREAD

**Issue by nduta-ndush** [section-engineering-education/engineering-education#6791]
### Topic Suggestion
Languages
### Writing sample(s): 
N/A
#### Proposed title of article
A Dive Into HashMaps, TreeMaps and HashTables in Java
#### Proposed article introduction
Data collection, manipulation and deletion are key actions in a program. Important applications rely on a variety of data structures to  perform and handle the different varieties of data they work with. The java collection framework is a library that holds a few interfaces and classes that implement the various data structures and algorithms available in programming. The collection framework includes ways of implementing HashMaps, TreeMaps and HashTables which are the center focus in this article. 

#### Key takeaways 
After reading through the article the reader will gain:
- An understanding of what are HashMaps, TreeMaps and HashTables within the Java collections framework.
- A look at the differences in how the different data structures perform, order values of data and their implementations.
- A code oriented look at the similarities among the three data structures
- The best use case for each of the three data structures.

#### Article quality
The article takes a unique approach where most of the differences and similarities have a follow up code block to show to the reader the exact differences and similarities present among the three data structures. Additionally, the article takes a dip dive into the three data structures allowing the reader to gain solid knowledge on their implementation in a language they love, that is Java

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations.
