### ISSUE TITLE
Setting Kubernetes on Ubuntu 20.04

### ISSUE THREAD

**Issue by josephotienoowino** [section-engineering-education/engineering-education#6793]
#### Proposed article introduction
Kubernetes, also known as K8s, is an open-source platform for container orchestration. It manages clusters meant to run containerized applications, scaling deployments, and provides a platform for deployment automation.
#### Key takeaways 
By the end of this guide, one will be able to:

- Securely install Kubernetes.
- Properly Configure Pod Network on Kubernetes.
- Put together workers nodes to the cluster.
#### References
[Kubernetes](https://kubernetes.io/docs/home/)

### Conclusion
By the end of this tutorial, the learner will be able to install the Container Runtime interface, implement Kubernetes cluster, be able to join workers nodes to the cluster, and more into the server.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Please feel free to suggest an alternate topic to explore. 🚀
