### ISSUE TITLE
Building Asynchronous Task Queuing using Spring Boot in Java

### ISSUE THREAD

**Issue by AndrewOdera** [section-engineering-education/engineering-education#6794]
#### Proposed title of article
Building Asynchronous Task Queuing using Spring Boot in Java

#### Proposed article introduction
Spring is the most popular framework available for Java application development. As such, Spring has one of the largest open source communities.

#### References
[Spring](https://spring.io/projects/spring-boot)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Please feel free to suggest an alternate topic to explore. 🚀  

(it would help if your topic suggestion had more information for us to review). 👍
