### ISSUE TITLE
How Fog Computing is Driving IoT Healthcare

### ISSUE THREAD

**Issue by jaykip** [section-engineering-education/engineering-education#6795]
#### Proposed title of article
How Fog Computing is Driving IoT Healthcare
#### Proposed article introduction
The purpose of fog computing in the IoT is to improve efficiency, performance and reduce the amount of data transferred to the cloud for processing, analysis, and storage. Therefore, the data collected by sensors will be sent to network edge devices for processing and temporary storage, instead of sending them into the cloud, thus reducing network traffic and latency.

The integration of fog computing with the IoT creates a new opportunity for services, which is called fog as a service (FaaS), where a service provider builds an array of fog nodes across its geographic footprint and acts as a landlord to many tenants from many vertical markets. Each fog node hosts local computation, networking, and storage capabilities. 

Smart healthcare decisions in the future would be incomplete, with robust and real-time health observations and monitoring. However, this can be made possible with the deployment of fog computing frameworks that enable data transmission in real-time.
#### Key takeaways 

- The value of integrating fog computing with the IoT
- Fog computing and healthcare monitoring systems
- How fog computing is enabling connected healthcare

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Please feel free to suggest an alternate topic to explore. 🚀
