### ISSUE TITLE
Build, Integrate and Scale-up a Spring Interceptor for Requests and Responses in Java (Spring Boot)

### ISSUE THREAD

**Issue by teevyne** [section-engineering-education/engineering-education#6798]
### Topic Suggestion
Build, Integrate and Scale-up a Spring Interceptor for Requests and Responses in Java (Spring Boot)

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
[Security] Build, Integrate and Scale-up a Spring Interceptor for Requests and Responses in Java (Spring Boot)

#### Proposed article introduction
In my personal project, I have had reasons to add an interceptor. As the name sounds, an Interceptor is a class that comes in between a request reaching the intended endpoint and a response returning to the requesting client - user or application.  

An interceptor can check a request before sending it to its destination. At this point, we might want to perform some authentication of headers, validations of the request body or simply modify the request object by adding some more fields or data to the request body. 

The same can be done for all responses coming from the endpoints. We can intercept them, modify them before passing to the client. The interceptor is also a perfect place to build an encryption gateway. However, in this tutorial, we will only build a request/response interceptor while we will breeze through building an encryption/decryption gateway in the same interceptor.

#### Key takeaways 
At the end of this tutorial, readers would:
- understand what configuration classes
- understand what the `@Configuration` annotation does
- be able to implement interceptors for their projects
- be able to manipulate and scale up the interceptors of the project

#### Article quality
Most articles out there mainly focus on building the interceptor. No emphasis on how it can be scaled and what more can be done with it beyond request and responses In this article, I go through not just building it but working with it to perfectly suit requirements for now and for the future

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
