### ISSUE TITLE
[Machine Learning] Fake news classification using TensorFlow

### ISSUE THREAD

**Issue by josephgatura328** [section-engineering-education/engineering-education#6799]
#### Proposed title of article
[Machine Learning] Fake news classification using TensorFlow

#### Proposed article introduction
Fake news refers to information content that is false, misleading, or whose source cannot be verified. This content may be generated to intentionally damage reputations, deceive, or gain attention and make money through advertising revenue. The prevalence of fake news has increased recently with the rise of social media, especially the Facebook News Feed, and this misinformation has gradually seeped into the mainstream media.

Several factors have been implicated in the spread of fake news, such as political polarization, post-truth politics, motivated reasoning, confirmation, and social media. Fake news can reduce the impact of real news by competing with it. It is important to identify the fake news from the real true news. The problem has been taken over and resolved with the help of Natural Language Processing tools which help us identify fake or true news based on historical data.

There are various types of fake news include such: Clickbait, Propaganda, Satire/parody, and Biased/partisan/hyper-partisan. In this tutorial, we will build a model that classifies fake news into these predefined categories.

#### Key takeaways 
1. What is Fake News and Types of fake news.
2. News dataset preprocessing and analysis.
3. One hot encoding of the categorical dataset.
4. Adding the input layers, hidden layers, drop out layer, and the output layer.
5. Model training and prediction.

#### Article quality
This tutorial will build a custom model that will be used to automatically classify fake news into pre-defined categories. This tutorial will explain how to adequately pre-process the news dataset to make the dataset ready for use. The clean dataset will produce an optimized model that can make accurate predictions.  We will also a Drop layer to the deep neural network to handle model overfitting. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Please feel free to suggest an alternate topic to explore. 🚀
