### ISSUE TITLE
[Machine Learning] Getting Started with Qiskit for Quantum Computing

### ISSUE THREAD

**Issue by monicada** [section-engineering-education/engineering-education#6803]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Getting Started with Qiskit for Quantum Computing

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Qiskit is an acronym for `Quantum Information Software Kit for Quantum Computation`. It is an open-source software development kit for working with quantum computers at the level of circuits, pulses, and algorithms. It provides tools for creating and manipulating quantum programs and running them on prototype quantum devices on IBM Quantum Experience or on simulators on a local computer.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to understand:

- What is Qiskit
- How to install Qiskit
- What Qiskit can do.
- How to implement a simple Qiskit code example

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Quantum computers haven't been with us for a long time. Most people have heard of it but never really tried using it. With open-source toolkit such as Qiskit, I'll be able to introduce our readers to the toolkit and let them experiment using Jupyter Notebooks hosted in IBM Quantum Lab. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [Qiskit](https://qiskit.org/)

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
