### ISSUE TITLE
Collecting and Preparing Image Classification Datasets

### ISSUE THREAD

**Issue by FREDERICO23** [section-engineering-education/engineering-education#6804]
### Topic Suggestion
Collecting and Preparing Image Classification Datasets

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Collecting and Preparing Image Classification Datasets

#### Proposed article introduction
As a data specialist, it is evident to say that during the modeling process, data collection and data preprocessing usually takes a lot of time to implement. This comes with the need of high skills in handling raw and real world data that usually comes with a good piece of noise. 

In this article, we will be looking at how to collect image data for classification problems and splitting the collected data into training, testing and validation sets.

#### Key takeaways 
By the end of this article, the reader should be able to understand how to:
*  Collect image data
*  Label and store the collected data
* Split the data into train, test and validation sets

#### Article quality
 This article provides handy tips to the readers and additional knowledge in the field of Computer Vision. 

#### References
N/A

**Comment by hectorkambow** [comment]
After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. Please feel free to suggest an alternate topic to explore. 🚀
