### ISSUE TITLE
The Abstract Syntax Tree of the Java Language

### ISSUE THREAD

**Issue by FranciscaNg** [section-engineering-education/engineering-education#6805]
### Proposed title of article
The Abstract Syntax Tree of the Java Language

### Introduction paragraph (2-3 paragraphs):
Source code written in a programming language looks like a tree to show how the code looks in an abstract way.

Every one of the tree's nodes is a type of thing that was in the original code.
Abstract syntax trees (ASTs) are data structures that are used by compilers to show how program code is organized. They are used in a lot of different ways in compilers. It is often the result of a compiler's syntax analysis phase, which is called an AST. It is often used as an intermediate representation of the program as it moves through the different stages that the compiler needs. It has a big impact on the compiler's final output.
### Key takeaways: 
- Traversing ASTs
- Transforming ASTs
- Printing ASTs
#### Article quality
- At Section, we do not have any articles related to The Abstract Syntax Tree of the Java Language.
- Although, we have few articles discussing 1 or 2 on The Abstract Syntax Tree of the Java Language, we don't have a common article that talks a lot on Traversing ASTs and Transforming ASTs. 
- The code snippets that I will provide will be easier to grasp.
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
