### ISSUE TITLE
Data wrangling using pandas

### ISSUE THREAD

**Issue by Geofreytech** [section-engineering-education/engineering-education#6806]
### Topic Suggestion
Data wrangling using pandas

#### Proposed article introduction
Wrangling is an important part of data science and analysis, but it's not the only part. Use the Pandas Framework of the Python programming language when you want to change data. People can use Pandas for free and without having to pay for it. It is used for data analysis and data science. Sorting, filtering, grouping, and so on are all examples of this, as are things like grouping and filtering.

A data frame is a type of tool that Python can use to apply the wrangling methods you want to use to different types of data so that you can get the analysis you want. We will be looking more into details about data wrangling using pandas.

#### Key takeaways 
1. Data discovery
2. Data structuring
3. Data cleaning
4. Data enriching
5. Data validation
#### Article quality
- The learner will be able to master the data wrangling concept with ease.
- The code snippets i will provide will be easy to grasp and undertand. 
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
