### ISSUE TITLE
Developing a image gallery with stack view

### ISSUE THREAD

**Issue by Koros-Meshack** [section-engineering-education/engineering-education#6810]
#### Topic Suggestion
Developing a image gallery using stack view adapter

#### Writing sample(s):
https://www.section.io/engineering-education/authors/meshack-koros/

#### Proposed title of article
Developing a image gallery with stack view

#### Proposed article introduction
Stack view is a component of an interface in android studio that allows developers to arrange items in a form like stacked cards. This unique style allows stack view to be used in different fields of software development including developing of a image gallery application. 
In the article proposed, the learner will be able to learn how to design and modify the .xml extension files so as to customize the appearance of the gallery application.  Furthermore, the learner will be able to program the objects in the gallery application through the two .java extensions. The two extensions include the `MainActivity.java` and `StackViewAdapter.java`.
With every step stated, the user will get a clear explanation so as to help them in the development of their own related software.

#### Key takeaways
- Understand what Stack view is 
- Implementation of stack view
- Developing gallery application with stack view
- Code snippets to modify objects in .xml file extension

#### Article quality
The article proposed will use well illustrated images and clearly explained code snippets to ascertain that the user understands all about stack view and software development.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
