### ISSUE TITLE
[Languages] Key Sequence Detection in JavaScript - Using a combination of keys to toggle theme

### ISSUE THREAD

**Issue by gmcodes20** [section-engineering-education/engineering-education#6811]
### Topic Suggestion
Enter topic suggestion here...

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
[Languages] Key Sequence Detection in JavaScript - Using a combination of keys to toggle theme
Use keyword research to improve your article's SEO.

#### Proposed article introduction
JavaScript allows web developers to create events that may occur while users interact with web pages. This tutorial will teach the reader how to perform different actions when certain key sequences are detected. For the purpose of this tutorial, I will create a dark-theme to light-theme toggle using key sequence detection.

#### Key takeaways 
- Reader will understand how key sequence works in JavaScript
- The reader will be able to create a website that changes themes when some key combinations are pressed on the keyboard.
- Readers will be able to differentiate the functions of `keyup`, `keydown`, and `keypress` 

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
