### ISSUE TITLE
Which Golang framework? Gin versus  echo

### ISSUE THREAD

**Issue by nel-20** [section-engineering-education/engineering-education#6812]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Gin is a HTTP web framework written in Golang which was introduced before echo so Gin seems to have more GitHub stars which shows gin to be more active it also has Better logger implementation and single binary server build.

Gin features  a martini-like API with the  best performance up to 40 times faster

While echo  is a performance focused, extensible ,open source Go web application framework standing between stdlib+router and a full-stack web framework.

Given a choice between Echo and Gin, I would definitely go with Echo nowadays for several reasons. Most notably:
•	Active development and support
•	Documentation
•	Nicer handler funs signature (returning an error)
•	A router without absurd pattern matching issues.
•	Less opinionated on certain things like validation (e.g. bring your own validator)
•	Centralized HTTP error handling has 
•	Better quality documentation
•	Custom HTTP error handler
•	Load balancing
•	File download

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- Top gear performance
- HTTPs
- Full HTTP/2 support
- File server
- Logger

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
