### ISSUE TITLE
[Languages]String comparison by implementing the FuzzyWuzzy algorithm in Python

### ISSUE THREAD

**Issue by Dinahanyango** [section-engineering-education/engineering-education#6814]
#### Proposed title of article
String comparison by implementing the FuzzyWuzzy algorithm in Python

Use keyword research to improve your article's SEO.

#### Proposed article introduction
String comparison is as important as any other activity that is usually done using any programming language. It can be done manually but due to human error and complications, it is well presentable when it is done using some lines of code of a programming language. Therefore, there are several number of ways in which one can compare two strings using Python programming language.

We shall put our focus on the FuzzyWuzzy algorithm but we shall still mention on the other methods but in a brief manner. This algorithm is going to show us how the strings in interest are similar and in what level of similarity. This will be achieved through the demonstration of well defined and explained examples.

#### Key takeaways 
1. Algorithm functionalities
2.  Determination of the Levenshtein distance
3. Installtion of the algorithm module

#### Article quality
The quality of the above article will be such that our learners will have the joy reading and implementing the content that will be delivered.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
