### ISSUE TITLE
[Languages]A guide on the implementation of Python in the development of dataframes

### ISSUE THREAD

**Issue by adikutch** [section-engineering-education/engineering-education#6815]
#### Proposed title of article
A guide on the implementation of Python in the development of dataframes

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Python programming language is a diverse language in such a way that it is used in the implementation of various concepts that helps the learners increase their level of knowledge in programming. In regards to that, we are going to have a look at a concept implementation in Python known as Data Frames. 

A data frame is the collection of data in a two dimension format. It may also be identified by its capability of being arranged in a tabulat form. Therefore in this article we are going to cover dataframes are created and in what ways are they created. 

#### Key takeaways 
1. Creating Dataframe from Dicts of series
2. Creating  Dataframe from list of dicts
3.  Creating  Dataframe using the zip() function
#### Article quality
The quality of the content in this article will be well understood by our learners at any level of programming.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
