### ISSUE TITLE
[Languge]Getting started with Rich library in python

### ISSUE THREAD

**Issue by kmwangi-ken** [section-engineering-education/engineering-education#6817]
### Topic Suggestion
Getting started with Rich library in python

#### Proposed article introduction
Rich is a Python library for writing rich text (with color and style) to the terminal. It lets you display advanced content such as tables, markdown, and syntax-highlighted code.
Anyone who prefers using command line, like most Linux users, including myself,  then Rich library will actually be useful for our Python applications.

#### Key takeaways 
- Rich overview
- Installing Rich
- Rich print demo
- styling your console with Rich
- using Tree in Rich
- displaying Rich tables in Python

#### Article quality
This article will be easy to follow for those aspiring to use Rich Python in command line. I believe knowledge can never be exhausted and this article will be clear  to novice  and even to terminal beginners.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
