### ISSUE TITLE
[Languages]Python strip() – How to Trim a String or Line

### ISSUE THREAD

**Issue by kymomolly** [section-engineering-education/engineering-education#6818]
### Topic Suggestion
Python strip() – How to Trim a String or Line
#### Proposed article introduction
In this article I will be discussing about how one can trim a string or line using the python strip() that is .strip() method. This will enable activities such as stripping leading and trailing spaces (as well as the ones inside the string) to be one performed.
 You'll also learn how to remove tabs, newlines, carriage return (CRLF), and other characters. And we'll be using nothing more than native methods and regex—no external libraries required!
#### Key takeaways 
1.How to Remove Leading and Trailing Whitespace from Strings in Python.
2.How to Remove Leading and Trailing Characters from Strings in Python. 
3.How to Remove Only Leading Whitespace and Characters from Strings in Python.
4.How to Remove only Trailing Whitespace and Characters from Strings in Python.
#### Article quality
This is article will in detail describe each and every step on how the trimming of strings will be performed. It will give a clear understanding to the reader which will be of importance.
#### References
N/A

**Comment by WanjaMIKE** [comment]
This topic appears somehow oversaturated in the official blog sites and documentation.
