### ISSUE TITLE
Operation of Dates and Time in Golang

### ISSUE THREAD

**Issue by Emusugut** [section-engineering-education/engineering-education#6820]
#### Introduction
Golang, also known as Go, is a programming language for creating lightweight microservice. It's presently being used to create APIs that interface with our front-end app. Golang is an excellent tool to construct a small working microservice rapidly.
The Go programming language runs under the UNIX epoch standard. The number of minutes or hours since this special day is counted by UNIX to maintain the time records. This article will discuss how to create and store dates and times in Go, the different types of formatting in Go, and understand durations. We will also look at tickers and how to execute code on an interval using tickers. Finally, we'll learn how to save memory using TinyGo
#### Key takeaways 
After reading this article, the reader  would be able to understand the following:
1. What is Golang programming
2. How t  create and store time and dates data in Go
3. Understand time durations and formatting
4. Tickers and how to execute code on an interval using tickers
5. How to save memory using TinyGo

#### Article quality
The article will be unique as its contents will be original. The language used will be simple and easily understood.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
