### ISSUE TITLE
Getting started with Axios in React

### ISSUE THREAD

**Issue by Terripha** [section-engineering-education/engineering-education#6821]
#### Proposed title of article
Getting started with Axios in React

#### Proposed article introduction
At some point during the web development, many web applications will need to interact with a REST API. Axios is a lightweight HTTP client that is equivalent to the native JavaScript Fetch API and is based on the HTTP service.

Axios is promise-based, allowing you to use JavaScript's `async` and `await` functions for more understandable asynchronous programming.

You may also intercept and cancel requests, and cross-site request forgery is protected on the client side.

In this tutorial, we'll look at how to utilize Axios to access the popular JSON placeholder API from within a React project.

#### Key takeaways 
- Axios installation
- Adding data using a POST request
- Updating data using a PATCH request
- Deleting data using a DELETE request
#### Article quality
As I was working on my project, I noted there a few resources on this topic with few information. In this tutorial, we will explore several examples on how to use Axios inside a React application to create HTTP requests and handle responses.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
