### ISSUE TITLE
[Languages] Understanding Sorting Algorithms

### ISSUE THREAD

**Issue by Dawe-7** [section-engineering-education/engineering-education#6823]
#### Proposed title of article
Understanding Sorting Algorithms

#### Proposed article introduction
As programmers we often find it hard to organize data based on our preferences or the way we would like to display our data to users. Because of this sorting algorithms were introduced to make it easier for us to sort our data. 

The significance of sorting lies in the fact that the search for data can be enhanced if and only if data is stored in an organized format.  This data is then displayed to readers/users in a more readable manner. Hence, data sorting is a vital need for a programmer. 

#### Key takeaways 
By the end of this article, the reader will understand:
1.  What is a sorting algorithm
2.  Classification of sorting algorithms
3.  Merge sort
4.  Selection sort
5.  Bubble sort
6.  Bucket sort
7.  Insertion sort
8.  Quick sort
10.  The advantages and disadvantages of each sorting algorithm covered

#### Article quality
This article will be a beginner friendly article but it will be in-depth as well. Most of the content/published blogs are in-depth but not intuitive. Also, in this article all the concepts of sorting algorithms will be covered in the same article unlike other articles. That is, the advantages and disadvantages of each algorithm will be stated.

#### References
N/A

**Comment by WanjaMIKE** [comment]
https://www.section.io/engineering-education/sorting-algorithms-in-js/

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
