### ISSUE TITLE
[Languages] Building A Webpage with Compose Web

### ISSUE THREAD

**Issue by robert-muriithi** [section-engineering-education/engineering-education#6824]
### Topic Suggestion
Building A Website with Compose Web

### Writing sample(s): 
https://www.section.io/engineering-education/extracting-colors-from-image-using-palette-api-in-android/
https://www.section.io/engineering-education/automatic-sms-verification-in-android/

#### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Compose for Web streamlines and accelerates web application UI development, with the goal of eventually allowing UI code exchange between web, desktop, and Android apps. Compose Web is just at the early age of a new era of developing excellent Web applications which can work on all browsers.

In this tutorial, the learner will learn  through  several examples that use the Composable DOM DSL to describe the user interface for a web application

#### Key takeaways 
- Getting Started with Compose Web
- Building Web UI
- Handling Events
- Controlled and uncontrolled inputs
- Style DSL in compose

#### Article quality
This article will be of help to a reader looking to venture into developing a beautiful website with less code. Since Compose is multiplatform now, the applications developed using compose can run on android devices and desktops.

#### References
- Compose Web Documentation

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
