### ISSUE TITLE
Login authentication with social media using passport.js strategies in React js

### ISSUE THREAD

**Issue by ben-cdm** [section-engineering-education/engineering-education#6827]
### Topic Suggestion
Login authentication with social media using passport.js strategies in React js

#### Proposed article introduction
Passport.js is a middleware that helps developers implement authentication and authorization. The blog will use various social media authentication strategies to illustrate how passport.js can be used with ReactJS. Most developers develop login authentication that collects users' data, but in this article we will develop a platform that makes sure the users' information is secure. The blog will also discuss how to redirect the page after successful login and logout. Lastly, we will discuss how we can keep users logged in.

#### Key takeaways 
1. Introduction to Passport.js
2. Coding the project's frontend (User Interface).
3. React social media login authentication.
4. Redirecting the page after successful login and logout.
5. How to keep the user logged in.

#### Article quality
The blog will be suitable for those who would like to add login authentication by using brief and precise explanations and simple code syntax that will help developers build interest. The most important part of this blog will be making sure that the users' information is secure, which is very important in today's world. 

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
