### ISSUE TITLE
Handling Exceptions - Kotlin

### ISSUE THREAD

**Issue by davidginmaina** [section-engineering-education/engineering-education#6829]
### Topic Suggestion
Handling Exceptions - Kotlin

#### Proposed article introduction
There is nothing more disgusting than a developer writing and publishing a project and getting bad comments and low ratings from users. Maybe the application keeps crashing every time the user performs an unwanted activity without his/her knowledge. This is called an exception where an application program keeps stopping. Reasons that may make an application crash include; users running out of memory when the application is on the runtime, referencing arrays that are out of bound e.t.c. To handle this type of exception, we use a method called exception handling so as we reduce the probabilities of an error occurring when the program is being executed. 

Exception handling handles the runtime problems and maintains the flow of program execution. 

In this tutorial, we will elaborate more on what is exception and exception handling demonstrating by writing Kotlin codes that will trap such errors when executing runtime programs. This way never will the program terminate which make the users enjoy an application's 

#### Key takeaways 
- Brief walkthrough to exception and exception handling.
- Types of exceptions
- Major exception keywords
- Exceptions examples
- Conclusion

#### Article quality
The article will be beginner-friendly where every developer will know the importance of using exception handlers when writing their programs. The article shall also discuss in-depth every exception that occurs during execution runtime. 
 
#### References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @davidginmaina.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
