### ISSUE TITLE
Solidity vs Python: Which is the Best Blockchain Platform

### ISSUE THREAD

**Issue by BridgetMwikali** [section-engineering-education/engineering-education#6830]
#### Proposed title of article
A Solidity vs Python: Which is the Best Blockchain Platform

#### Proposed article introduction
In the past few years, we’ve seen blockchain technology grow in popularity. Even though it’s still relatively new, this technology is already being adopted by big companies like IBM and Microsoft. Many software developers are looking to find ways to join the blockchain movement and get in on this exciting new market.

Solidity and Python are two popular programming languages used to write smart contracts on blockchains. The blog will discuss the most important pros and cons of both languages, helping you make an informed decision.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @BridgetMwikali 

Please add the key takeaways as they help us understand the value of your article. Also, add the article quality and make sure to tell us why your article is unique and if possible what value it adds as compared to other available articles.

For now, I will close this to clear up the queue so when done, please ping the content-moderators team to re-open and review the submission.
