### ISSUE TITLE
Using scipy.linalg to Work With Linear Systems in Python

### ISSUE THREAD

**Issue by K-jacinta** [section-engineering-education/engineering-education#6831]
### Topic Suggestion
Using scipy.linalg to Work With Linear Systems in Python

### Writing sample(s): 
https://www.section.io/engineering-education/authors/jacinta-kyulu/

#### Proposed article introduction
 SciPy is an open source Python library for scientific computing, which includes various modules for common tasks in science and engineering, such as linear algebra, optimization and integration/interpolation, and signal processing. In addition to NumPy, Matplotlib, SymPy, IPython and pandas, the SciPy stack includes several other packages for scientific computing. Using vectors and matrices, linear algebra deals with linear equations and how they might be represented. As a pre-requisite to a more in-depth knowledge of machine learning, it is an essential subject in many fields of engineering. scipy.linalg contains a variety of functions for working with linear algebra problems, including determinants, inverses, eigenvalues, eigenvectors, and the singular value decomposition.

In this article, you'll learn how to use scipy.linalg's linear system functions to solve real-world situations. For scipy.linalg to work, the SciPy library must be installed and set up. Anaconda Python distribution and the conda package- and environment-management system can be used to accomplish this.

#### Key takeaways 
1. Introduction to scipy.linalg
2. Using scipy.linalg.solve() to Solve Linear Systems
3. Working With Vectors and Matrices Using NumPy
4. Comparing scipy.linalg With numpy.linalg

#### Article quality
The article will be an in-depth explanation of how to use scipy.linalg and numpy.linalg in python to solve linear systems. We will be using appropriate well explained examples

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @K-jacinta 

Thank you for submitting your article suggestion. However, after a short google search of the topic, we found some articles that cover the same areas as yours. Due to this, we cannot move forward with your article. You are more than welcome to explore other topics of interest.
