### ISSUE TITLE
How to use namedtuple to write clean python code

### ISSUE THREAD

**Issue by puritymutunga** [section-engineering-education/engineering-education#6832]
### Topic Suggestion
How to use namedtuple to write clean python code

### Writing sample(s): 
https://www.section.io/engineering-education/authors/purity-mutunga/

#### Proposed article introduction
The namedtuple() factory function in Python is a convenient way to create tuples. Named fields can be added to tuple subclasses with this feature .The dot notation and the field names can be used to retrieve the values in a named tuple, like obj.attr. Rather than relying on integer indices, Python's namedtuple provides a mechanism to access values using descriptive field names rather than integer indices, which most of the time provide no information on what the values are. As an added benefit, this functionality helps to keep the code simpler and easier to maintain.
In this article we are going to be learning more about the namedtuple()

#### Key takeaways 

1. Brief introduction to namedtuple
2. Creating Tuple-Like Classes With namedtuple()
3. Exploring Additional Features of namedtuple Classes
4. Subclassing namedtuple Classes
5. Writing Pythonic Code With namedtuple
6. Differences between namedtuple and Other Data Structures

#### Article quality
The article will give the reader the understanding of how to use  namedtuple and also other data structures in comparison to namedtuples

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @puritymutunga 

Thank you for submitting your article suggestion. However, after a short google search of the topic, we found several articles that cover the same content as yours. Due to this, we cannot move forward with your article. You are more than welcome to explore other topics of interest.
