### ISSUE TITLE
[Android] Building a Document Scanner with CameraX API and OpenCV in Android

### ISSUE THREAD

**Issue by tomleposo** [section-engineering-education/engineering-education#6833]
#### Building a Document Scanner with CameraX API and OpenCV in Android
CameraX is a Jetpack support library, built to help you make camera app development easier. It provides a consistent and easy-to-use API surface that works across most Android devices.

CamerasX uses a simpler approach that is lifecycle-aware and is based on use cases. It also resolves device compatibility issues for you so that you don't have to include device-specific code in your code base. These features reduce the amount of code you need to write when adding camera capabilities to your app.

OpenCV is a huge open-source library for computer vision, machine learning, and image processing and now it plays a major role in real-time operation which is very important in today’s systems. By using it, one can process images and videos to identify objects, faces, or even the handwriting of a human. When integrated with various libraries, such as CameraX, it is capable of processing the OpenCV array structure for analysis. Identify image patterns and their various features. 

In this tutorial, we will create a simple document scanner with the combination of CameraX and OpenCV for Android.

#### Key takeaways 
- What is CameraX and OpenCV
- Adding both CameraX and OpenCV to the Android app
- Tips on how to reduce the size of OpenCV and only use the necessary dependencies
- Creating a real-time document scanner

#### Article quality
In this tutorial, I will try and come up with something that is unique in a way that will be friendly to those new to CameraX and OpenCV. I will also make sure to use the latest tools and not deprecated ones.

#### References
- [CameraX Docs](https://developer.android.com/training/camerax)
- [Android OpenCV Docs](https://opencv.org/android/)

**Comment by LinusMuema** [comment]
Hi @tomleposo 

Thank you for submitting your article suggestion. However, after a short google search of the topic, we found at least two articles that cover the same content as yours. Due to this, we cannot move forward with your article. You are more than welcome to explore other topics of interest.
