### ISSUE TITLE
[Android] Getting Started with Room Database Relationships in Android

### ISSUE THREAD

**Issue by calvinombati** [section-engineering-education/engineering-education#6834]
#### Proposed article introduction

A relational database collects different types of data sets that use tables, records, and columns. It is used to create a well-defined relationship between database tables so that relational databases can be easily stored. For example of relational databases such as Microsoft SQL Server, Oracle Database, MYSQL, etc.

A relationship is established between two database tables when one table uses a foreign key  that references the primary key of another table. This is the basic concept behind the term relational database. 

One of the huge advantages of a relational database is that, once you have your data held in clearly defined, compact tables, you can connect or relate the data held in different tables. 

There are three types of relationships : 
- one-to-one relationship
- one-to-many relationship
- many-to-many relationship

To be able to identify these relationships, you need to examine the data and have an understanding of what business rules apply to the data and tables.

In this article, we will go through the three relationships in Room DB and then learn how to implement them in an Android app.

#### Key takeaways 
- Understand different relationships in relational databases.
- Recap on implementing Room DB in an Android project.
- Understand circumstances that may force you to have more than one table in an Android project.
- Understand how to create and implement  relationships in an Android project.

#### Article quality
My blog sites and tutorials usually focus on creating tutorials with only one table and they usually don't talk more about relationships which are very key in relational databases. In this tutorial I will talk about the different relations and also do the implementations in an Android project.

#### References

[Room database documentation](https://developer.android.com/training/data-storage/room)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over [saturated ](https://www.google.com/search?q=Room+Database+Relationships+in+Android&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8)throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
