### ISSUE TITLE
[Languages] A Beginner Guide to Getting Started with Rust Programming

### ISSUE THREAD

**Issue by julie-techie** [section-engineering-education/engineering-education#6835]
### Topic Suggestion
A Beginner Guide to Getting Started with Rust Programming

#### Proposed title of article
A Beginner Guide to Getting Started with Rust Programming

#### Proposed article introduction
Rust is an emerging technology, and many people don't exactly know it today. Rust is a back-end programming language that performs very closely with C and C++. It is set to compete in the arena where C++ is playing a dominant game. With C++, it's tricky to write code for real-world projects. Rust is addressing these issues.

Rust is a memory-safe compiled programming language that delivers high-level simplicity with low-level performance. It's a popular choice for building systems where performance is critical, like game engines, databases, or operating systems. The primary goal of this programming language is to serve developers at its core. This article will discuss what Rust is, what can be the foreseen future of Rust, Why it is important, What it can build, and Its implementation.

#### Key takeaways 
1. Overview of Rust
2. Why Rust is important
3. What can you build with Rust
4. Implementing Rust

#### Article quality
This is a detailed guide that will pass value to readers. By going throw this article, readers will know about Rust Programming Language in depth. Developers will learn how it works by implementing it and getting to know what they can build with Rust. This guide is unique and will be understood at a beginner level.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over [saturated ](https://www.google.com/search?q=Rust+Programming+intro&rlz=1C1CHBF_enUS891US891&ei=m3AhYqX1Cpex0PEP096b-Ao&ved=0ahUKEwjlru-DrKv2AhWXGDQIHVPvBq8Q4dUDCA4&uact=5&oq=Rust+Programming+intro&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEOgcIABBHELADOgcIABCwAxBDOgoIABDkAhCwAxgAOg8ILhDUAhDIAxCwAxBDGAE6CAgAEIAEELEDOgQIABBDOgUILhCABDoGCAAQFhAeSgQIQRgASgQIRhgBUIAFWOMKYM8MaAFwAXgAgAHaAYgBgAaSAQUyLjMuMZgBAKABAcgBEcABAdoBBggAEAEYCdoBBggBEAEYCA&sclient=gws-wiz)throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
