### ISSUE TITLE
Using React and SuperTokens SDK to handle signup, manage auth tokens, and social login

### ISSUE THREAD

**Issue by liliankimani** [section-engineering-education/engineering-education#6837]
####Proposed article introduction
It takes time to handle and implement authentication from the ground up. Security vulnerabilities where an account gets hacked and sessions are stolen are common these days. For this reason, many web-based projects adopt social logins such as SuperTokens to correctly handle app authentication.
SuperTokens is an open-source library that aims to offer authentication securely. The library bundles feature such as rotating refresh tokens specified on IETF RFC 6819 to detect and prevent attacks This includes secure login, Passwordless login, access control, two-factor auth, email verification, and more.

####TakeAways
- Using React and SuperTokens SDK to handle signup, manage auth tokens, and social login
- SuperTokens features
- A comparison between SuperTokens and Sessions
- Understanding SuperTokens architecture - Frontend SDK, Backend SDK, and SuperTokens Core

####Article Quality
Essentially, the user will understand deeper the architecture of SuperTokens; Frontend SDK, Backend SDK, and SuperTokens Core. They will learn how to make use of React and SuperTokens SDK in handling signup and social login.

####Potential References
supertokens-auth-react: Docs, Tutorials, Reviews | Openbase. (2022). supertokens-auth-react: Docs, Tutorials, Reviews | Openbase. Openbase. https://openbase.com/js/supertokens-auth-react
supertokens-auth-react examples - CodeSandbox. (2022). Codesandbox.io. https://codesandbox.io/examples/package/supertokens-auth-react
Architecture | SuperTokens Docs. (2022, February 24). Supertokens.com. https://supertokens.com/docs/emailpassword/architecture

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
