### ISSUE TITLE
which is the best platform to use in Internet of things(IOT)? Arduino versus Raspberry Pi

### ISSUE THREAD

**Issue by nel-20** [section-engineering-education/engineering-education#6838]
#### Proposed title of article
 
The best  platform to use in Internet of things (IOT). Arduino versus Raspberry Pi

#### Proposed article introduction
Internet of things (IOT) concept includes creation of network of various devices interacting with each other and their environment. Connectivity wouldn’t be possible without hardware platforms which help developer solve issues such as building autonomous interactive objects or completing common infrastructure related tasks.
Arduino platform was created by Arduino Company and allows for open source prototyping and flexible software development and back.
Arduino is sensible to environments by receiving source data from external sensors and can interact with other control elements over various devices and drivers.
Arduino has built in micro controller which operates on Arduino software.
Arduino offers analogue-to-digital input with connectivity possibility to light, temperature and sound sensor modules.
Arduino is a micro-controller by providing excellent interactivity with external devices and offers wide range of user manual project samples and large mass of users to learn from and share large mass of users to learn from and share knowledge with.
Raspberry Pi-is a series of small single-board computer developed by Raspberry Pi foundation in association with Broadcom.
Raspberry Pi hardware has evolved through several versions featuring variations in the type of Central processing unit (CPU), amount of memory capacity, networking support and peripheral –device support.
Raspberry Pi is a mono-board computing platform similar to a credit card.
Peculiarity of Raspberry Pi is the GPIO (General purpose Input-output) which is a lower-level interface of self-operated control by input-output ports.
Raspberry Pi uses Linux as default operating system and it is fully Android compatible

#### Key takeaways 
•	Expansion
•	Connectivity
•	Power supply
•	Storage
•	Programming
•	Cost

#### Article quality

This topic is very essential in internet of things since it will help distinguish the best platform to use in creation of networks in various devices ,whereby the best platform to use is Raspberry Pi

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over [saturated ](https://www.google.com/search?q=IOT+Arduino+versus+Raspberry+Pi&rlz=1C1CHBF_enUS891US891&ei=kXEhYtLxG8fa0PEPrPiJwAQ&ved=0ahUKEwiS_qb5rKv2AhVHLTQIHSx8AkgQ4dUDCA4&uact=5&oq=IOT+Arduino+versus+Raspberry+Pi&gs_lcp=Cgdnd3Mtd2l6EAMyBAgAEA06BwgAEEcQsAM6CggAEEcQsAMQyQM6BggAEA0QHjoFCAAQogRKBAhBGABKBAhGGABQigNYkgdgmwloAXABeACAAfMBiAGrBZIBBTAuMy4xmAEAoAEByAEIwAEB&sclient=gws-wiz)throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
