### ISSUE TITLE
 Python defaultdict Type for Handling Missing Keys

### ISSUE THREAD

**Issue by augustinemagero** [section-engineering-education/engineering-education#6841]
### Topic Suggestion
 Python defaultdict Type for Handling Missing Keys

#### Proposed article introduction
Trying to access or alter keys that do not exist in Python dictionaries is a common source of frustration. Your code will be interrupted by a KeyError. As a dictionary-like class, Python's standard library offers the defaultdict data type to deal with these kinds of scenarios.
To access or edit a missing key, defaultdict will automatically create the key and generate the default value for it if you try to access or alter a missing key. As a result, defaultdict is an excellent choice for dealing with dictionaries with missing keys.
In this tutorial, you’ll learn How to use the Python defaultdict type for handling missing keys in a dictionary and also when and why to use a Python defaultdict rather than a regular dict

#### Key takeaways

- Brief introduction to missing keys in dictionaries 
- Understanding the Python defaultdict Type.
- Using the Python defaultdict Type
- Emulating the Python defaultdict Type
- Passing Arguments to .default_factory

#### Article quality
With the knowledge of, how to use Python defaultdict Type for Handling Missing Keys the reader will be in a better condition to effectively use the Python defaultdict type in his/her day-to-day programming challenges.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over [saturated ](https://www.google.com/search?q=Python+defaultdict+Type+for+Handling+Missing+Keys&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8)throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
