### ISSUE TITLE
How to Improve Security of Django Applications with Penetration Testing

### ISSUE THREAD

**Issue by khabdrick** [section-engineering-education/engineering-education#6842]
### Writing sample(s): 
https://www.section.io/engineering-education/authors/muhammed-ali/

#### Proposed title of article
How to Improve Security of Django Applications with Penetration Testing

#### Proposed article introduction
This article will go through how the reader can improve the security of their Django application by applying penetration testing. I will go through some basics about penetration testing and then build a simple Django, apply penetration testing, and find ways in which we can solve the security faults discovered during the penetration testing process.

ONLY viable topics to pick from:
- Languages

#### Key takeaways 
- introduction to penetration testing
- Ways to perform penetration testing in Django
- How to improve security in Django

#### Article quality
The article is unique

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over [saturated ](https://www.google.com/search?q=Security+of+Django+Applications+with+Penetration+Testing&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8)throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
