### ISSUE TITLE
Getting Started With Compose Desktop

### ISSUE THREAD

**Issue by omondi-alex** [section-engineering-education/engineering-education#6843]
### Topic Suggestion
Getting Started With Compose Desktop

#### Proposed title of article
Getting Started With Compose Desktop

#### Proposed article introduction
Compose desktop is a new technology for developing desktop applications with rich UI in Kotlin. Since it is a new technology that is coming in, I will cover its basics in this article that will help the learners to understand it. Compose Multiplatform simplifies and accelerates UI development for Desktop and Web applications, and allows extensive UI code sharing between Android, Desktop, and Web.

In this article, we will only learn about the Desktop where we will learn how to create components like menu, tooltips, notification tray, and many others. Basically, this article will cover the basics for a beginner.

#### Key takeaways 
- Understanding Compose Multiplatform.
- Creating Compose desktop application.
- Creating Compose desktop components.
- How to share UI code between Android, Desktop, and Web.

#### Article quality
This article is going to be unique since Compose Desktop is a new technology and has not been covered in most of the blog sites. The article will also cover Compose Deskto[p basics that are very essential for beginners.

#### References
[Compose Desktop](https://github.com/JetBrains/compose-jb)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over [saturated ](https://www.google.com/search?q=Compose+Desktop+intro&rlz=1C1CHBF_enUS891US891&ei=kXIhYornLbaS0PEP5ui7yAk&ved=0ahUKEwjK88Hzrav2AhU2CTQIHWb0DpkQ4dUDCA4&uact=5&oq=Compose+Desktop+intro&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABMgUIIRCgAToECAAQRzoECAAQQzoFCAAQgAQ6BggAEBYQHkoECEEYAEoECEYYAFDmBljGC2DyDGgAcAJ4AIAB5QGIAdcHkgEFMC4yLjOYAQCgAQHIAQjAAQE&sclient=gws-wiz)throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
