### ISSUE TITLE
[Machine Learning] Time series analysis and forecasting on non-stationary data using Facebook Prophet

### ISSUE THREAD

**Issue by charlesndirutu33** [section-engineering-education/engineering-education#6850]
#### Proposed title of article
[Machine Learning] Time series analysis and forecasting on non-stationary data using Facebook Prophet

#### Proposed article introduction
A time series is a collection of data points organized in successive order over time. Time series analysis involves extracting meaningful patterns and other attributes of the historical data. Time series forecasting builds a model that predicts future values based on historical data. Times series models can be used to forecast forex exchange, business sales, stock prices, weather forecasts, and Covid-19 spread.

In time series can be stationary or non-stationary. A stationary time series is one whose properties like mean, variance, covariance does not depend on the time at which the series is observed. Time series are stationary if they do not have a trend or seasonal effects. A non-stationary time series is a type of time series whose statistical properties are changing through time. Data points are often non-stationary when they have means, variances, and covariances that change over time. Non-stationary behaviors can be trends, cycles, random walks, or combinations of the three.

In many cases, we have to make the time stationary. But Facebook Prophet can build the time series model using the non-stationary without making it stationary.

#### Key takeaways 
1. Stationary vs non-stationary time series.
2. How to make a time series stationary.
3. Facebook Prophet components (Trend, Seasonality, Holiday effects)
4. Time-series analysis and decomposition on the non-stationary time series.
5. Time-series Forecasting/making predictions.

#### Article quality
This tutorial is unique because we will discuss the difference between a stationary and non-stationary time series in detail. We will also discuss some of the popular ways that are used to make a time series stationary. The tutorial also explains the Facebook Prophets components such as Trend, Seasonality, Holiday effects. Finally, we will build an Amazon revenue time series model, the time series has both trends and seasonality which makes it non-stationary.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
I closed this topic and told you why. https://github.com/section-engineering-education/engineering-education/issues/6719
