### ISSUE TITLE
Working with Controller and RestController annotations in Spring Framework

### ISSUE THREAD

**Issue by njokiloise** [section-engineering-education/engineering-education#6851]
#### Proposed title of article
Working with Controller and RestController annotations in Spring Framework

#### Proposed article introduction
The `controller` class in Spring Boot is in charge of handling incoming REST API calls, constructing a model, and delivering the view to be shown as a response.

The `@Controller` or `@RestController` annotations are used to annotate the `controller` classes in Spring. These classes are marked as request handlers so that Spring may recognize them as RESTful services during runtime.

In this article, we'll go through the definitions of the `@Controller` and `@RestController` annotations, as well as their use cases and differences.

#### Key takeaways 
- Introduction to the @Controller Annotation
- Write HTML with @Controllers
- Introduction to the @RestController Annotation
- Write XML/JSON with @RestControllers
- Model-View-Controller

#### Article quality
The article will be unique and beginner-friendly where every developer will know what `@Controller` and `@RestController` annotations are, how to apply in HTML and XML/JSON files and much more.

#### References
N/A

**Comment by WanjaMIKE** [comment]
This article -> https://www.section.io/engineering-education/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/ already uses RestController annotations. Therefore, focusing on these two aspects by itself will not make a detailed tutorial. Feel free to suggest another topic. Thanks
