### ISSUE TITLE
Socket Programming In .NET Framework Using C# 

### ISSUE THREAD

**Issue by Geo-free** [section-engineering-education/engineering-education#6852]
### Topic Suggestion
Socket Programming In .NET Framework Using C# 

### Writing sample(s): 
https://www.section.io/engineering-education/authors/geoffrey-omukuba/

#### Proposed article introduction
Socket programming is an approach to associating two nodes on a network to speak with one another. One socket(node) tunes in on a specific port at an IP, while the other socket contacts the other to create an association. The server creates the listener socket while the client connects with the server.

The .NET Framework Socket class is an overseen code form of the attachment administrations given by the Winsock32 API. By and large, the Socket class techniques essentially marshal information into their local Win32 partners and handle any fundamental security checks.

The Socket class upholds two essential modes, simultaneous and nonconcurrent. In simultaneous mode, calls to capacities that perform network activities (like Send and Receive) delay until the activity finishes prior to returning control to the calling program. In offbeat mode, these calls get back right away.

In this tutorial, we will be looking at socket programming on an asynchronous server to better understand this article in the .NET Framework.

#### Key takeaways 
- In this article, I will take the reader through the concept of:
     - Asynchronous mode of function calls
     - Synchronous modes of function calls
- The reader will also understand the concept of socket programming
- The reader will be able to develop a program that can be able to connect to other devices on the network

#### Article quality
This article tends to take the reader through the concept, of socket programming in the .NET Framework and also use a practical approach for a better understanding of it. This will make the reader understand what socket programming is in the best way possible.

#### References
N/A

**Comment by Kayere** [comment]
Topic approved @Geo-free - Please make sure your article is unique and adds value to what is available online.
