### ISSUE TITLE
Creating A Website With Django And Python

### ISSUE THREAD

**Issue by Mercycar** [section-engineering-education/engineering-education#6853]
### Topic Suggestion
Creating A Website With Django And Python

### Writing sample(s):  
https://www.section.io/engineering-education/razor-pages-web-app-tutorial/
https://www.section.io/engineering-education/rsa-encryption-and-decryption-in-python/
https://www.section.io/engineering-education/authorization-and-authentication-in-server-side-blazor/

#### Proposed article introduction
A website is a collection of web pages with related content. These websites are identified by a common domain that direct the visitor to the website when clicked in a web browser.

In this tutorial, I will style the site with Bootstrap and a straightforward HTML subject. I'll design Django to serve static files utilizing the 'staticfiles' module. I will then, tell the reader the best way to load custom text styles and override 'CSS' in the HTML layout. We will be using four main different technologies. ie:
- Django - for our web server
- Postgres - for our database
- Docker - to package the application
- Kubernetes - to manage deployment in the cloud

#### Key takeaways 
After going through this tutorial, the reader will understand how to:
- create a Django server with python
- set up a database in a project.
- deploy a website to the cloud.

#### Article quality
In this article, I will create a Django server with Python, create web pages and style them CSS, set up a database, and even deploy it to the cloud where possible.

#### References
N/A

**Comment by WanjaMIKE** [comment]
I think we already have enough [articles](https://github.com/section-engineering-education/engineering-education/issues?q=Website+With+Django+And+Python) on creating a website using the Django framework. Please suggest another topic. Thanks
