### ISSUE TITLE
[Languages] How Function Components Differ from Classes in React

### ISSUE THREAD

**Issue by shehopes** [section-engineering-education/engineering-education#6854]
#### Proposed title of article
A practical guide on how react functional components differ from class components.

#### Proposed article introduction
While writing a React component we can either use a class or a function. By the use of sample code, I intend to lay out the differences between class and functional components.

As a kick starter, a functional component is essentially a JavaScript function which can accept props as an argument and return a React element. On the other hand, a class component would require you to perform an extension from React. It can therefore create a render function which can return a React element.
While evaluating performance, choosing whether to work with a class or a function does not matter or act as a measure, but rather what the entire code is aimed at achieving.

#### Key takeaways 
-Differentiate between functional components and class components, syntax-wise.
-Observe and notice the differences while;
(i)Rendering functional and class components
(ii)Handling states in functional and class components
(iii)Implementing life cycle methods
-Understand how to choose between functional or class component.

#### Article quality
This tutorial will include code samples to ensure the differences are well illustrated.

#### References
Hooks at a Glance – React. (2021). Reactjs.org. https://reactjs.org/docs/hooks-overview.html
Tutorial: Intro to React – React. (2021). Reactjs.org. https://reactjs.org/tutorial/tutorial.html#making-an-interactive-component
The React Hooks Guide - Tutorials and Examples | KendoReact. (2021). Telerik.com. https://www.telerik.com/kendo-react-ui/react-hooks-guide/

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=How+Function+Components+Differ+from+Classes+in+React&oq=How+Function+Components+Differ+from+Classes+in+React&aqs=chrome..69i57j69i61.339j0j9&sourceid=chrome&ie=UTF-8), this topic appears a bit over-saturated. Feel free to suggest another topic. Thanks
