### ISSUE TITLE
CRYPTOGRAPHY AND ITS EVOLUTION IN NETWORK SECURITY

### ISSUE THREAD

**Issue by NJIRAI** [section-engineering-education/engineering-education#6855]
### Topic Suggestion
CRYPTOGRAPHY AND ITS EVOLUTION IN NETWORK SECURITY

#### Proposed title of article
CRYPTOGRAPHY AND ITS EVOLUTION IN NETWORK SECURITY

#### Proposed article introduction
Historically ,several groups have contributed to the art of cryptography; military, diplomatic corporations and diarists. Military have played the greatest role in cryptography. Within military organizations ,messages to be encrypted were give to poorly paid ,low-level code clerks for encryption and transmission. This sheer volume of messages prevented work from being done by a few elite specialists. until the introduction of computers.

What is cryptography? It is a greek word meaning "hidden writing". it is a technique of securing information and communication through use of codes so that only intended people can understand and process the information. In cryptography, techniques which are used to protect information are obtained from mathematical concepts and a set of rule based calculations known as algorithms to convert messages in ways that can make it hard to decode.

#### Key takeaways 
This article will cover the following;
1. History and evolution of cryptography in network security.
2. It will define cryptography in the most simple manner for learners to understand.
3. It will cover the features of cryptography.
4. It will also deal with the various types of cryptography.

#### Article quality
As indicated in the title ,this article will not only cover cryptography, but will also include its history and evolution to modern technology. This feature itself makes it differ from other published articles.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
