### ISSUE TITLE
Build Microservice Architecture (MSA) REST API using the using Flask

### ISSUE THREAD

**Issue by Anthony-Prince** [section-engineering-education/engineering-education#6862]
#### Proposed article introduction

A microservice architecture (MSA) is a logical structure for designing an application involving loosely-coupled modular components called microservices. This guide will help the reader understand this concept while implementing it as a Flask REST.

#### Key takeaways 

- What is Microservice Architecture (MSA)
- Why do you need Microservice Architecture (MSA)
- Understand what is a Microservice and what t does
- Set up Flask application
- Build a Flask MSA REST

#### Article quality

This guide will help the reader be able to fully understand these concepts. Additionally, the reader will be able to recreate the explained concept using Flask.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
@Antony-Prince ensure that you fill all required sections before submitting a form for approval. Thanks

**Comment by Antony-Prince** [comment]
I have updated this. Please reopen. Thank you

**Comment by WanjaMIKE** [comment]
Nice topic. Let's ensure that it adds value to the community. Thanks @Antony-Prince
