### ISSUE TITLE
How to use Genie.jl to create a web application in Julia.

### ISSUE THREAD

**Issue by janemurugi** [section-engineering-education/engineering-education#6867]
#### Proposed title of article
How to use Genie.jl to create a web application in Julia.

#### Proposed article introduction
Julia is a dynamic, high-level programming language available under the MIT license. Python-like ease of use with the performance of C or C++ is the goal.

Many of Julia's early applications were in the scientific community, where large-scale computations were and still are necessary. However, as the language has developed, more and more applications have gained traction.

Installing Julia and installing packages are only the beginning of what you'll learn in this article.

#### Key takeaways 
- How to install Julia
- How to install Genie.jl
- Creating the Genie Web App
- Web app database development.

#### Article quality
Throughout this article, we'll cover all you need to know to get started building your first web app in Julia. The article will, be unique as we will be creating a web application to help the reader get started

#### References
N/A

**Comment by WanjaMIKE** [comment]
@janemurugi your key takeaways seem a bit basic and thus the article will not provide enough value to the community. Besides, this topic appears a bit [over-saturated](https://www.google.com/search?q=How+to+use+Genie.jl+to+create+a+web+application+in+Julia&sourceid=chrome&ie=UTF-8)
