### ISSUE TITLE
[Android] Authentication with Auth0 SDK in Android

### ISSUE THREAD

**Issue by feswalsalim** [section-engineering-education/engineering-education#6870]
#### Proposed article introduction
Auth0 is a flexible, drop-in solution to add authentication and authorization services to your applications. Your team and organization can avoid the cost, time, and risk that come with building your own solution to authenticate and authorize users. Auth0 is an easy to implement, adaptable authentication and authorization platform. 

The Authentication API enables you to manage all aspects of your user identity when you use Auth0. It offers endpoints so your users can log in, sign up, log out, access APIs, and more. The API supports various identity protocols like OpenID Connect , OAuth 2.0, and SAML.

In this tutorial, we are going to create an Android app that uses Auth0 authentication feature.

#### Key takeaways
- What is Auth0 SDK?
- An understanding of authentication and authorization.
- Features offered by Auth0.
- Pricing.
-  Integrating the SDK into an Android app.

#### Article quality
I performed some searches on the web and there are not many articles/ tutorials talking about setting up authentication in an Android app. Most results come from the doc, but with my article I will use the SDK to come up with an architectured Android app with authentication feature.

#### References
- [Auth0 Docs](https://auth0.com/docs/libraries/auth0-android)

**Comment by WanjaMIKE** [comment]
@feswalsalim I was just going through the documentation https://auth0.com/docs/libraries/auth0-android I feel they already covered most of your key takeaways adequately. Feel free to suggest another topic. Thanks
