### ISSUE TITLE
Getting Started with LU Decomposition in Python

### ISSUE THREAD

**Issue by DennisKimt** [section-engineering-education/engineering-education#6871]
#### Proposed title of article
Getting Started with LU Decomposition in Python

#### Proposed article introduction
LU decomposition is a matrix factorization algorithm that is used to solve simultaneous systems of linear equations. This technique writes a matrix as the product of lower and upper triangular matrix, which sometimes involves permutation.
### How do LU decomposition work
Suppose we have a system of linear equations whose coefficient matrix is given as A.
With LU decomposition, we factorize matrix A as the product of the other two matrices, i.e.,
A = LU;
Where,
- L is a lower triangular matrix, that is, a matrix whose entries are zeros above the main diagonal.
- U is an upper triangular matrix, a matrix whose entries are zeros below the main diagonal.

Now, the question we need to answer is how we compute for the matrix U and matrix L from the coefficient matrix A.
First, let's talk about matrix U.
To solve for matrix U, we perform the forward Guess elimination method on matrix A without swapping rows. While determining the upper matrix U, we keep a record of all the multipliers we use to obtain the zeros below the main diagonal. Once we have determined the upper matrix through the forward Gaussian elimination, we the constructed matrix L as follows:
- Create matrix L with the same dimension as the original matrix A and with ones on the main diagonal and zeros above the main diagonal.
- Enter the multipliers that were used to obtain zeros below the diagonal of matrix U at the respective position below the main diagonal of matrix L. This will give us the L matrix.

Now that we successfully created our upper and lower triangular matrix, how can we use them, and why should we use them.
Actually, there is proof that the LU decomposition algorithm can reduce the computations for the solution to a system of equations by 40 % compared with other methods such as the inverse of the coefficient matrix. This makes the LU decomposition a powerful algorithm. However, we will not go into details to prove this in our article as we believe this is beyond the intention of the content this article seeks to deliver.
Now, let's see how we use the LU decomposition to solve a system of linear equations.
Suppose we are given a system of linear equations represented as:
Ax = b
Where,
- A is the coefficient matrix,
- x is a vector of unknown values
- b is the vector of solutions

Since we know we can decompose A as;
A = LU, we can rewrite our system of equations as:
[LU]x=b.
Multiplying both sides of the above system by L_inverse, i.e., [L^-1], we get,
[L^-1] [LU]x = [L^-1]b.
Since we know, [L^-1] [L] = [I], we can write the above system as:
[I] [U]x = [L^-1]b which we can further reduce to:
[Ux] = [L^-1]b
Now, let,
[L^-1]b = Z, this implies that:
[LZ] = b, and
[Ux] = Z
These two equations are key components in solving any system of linear equations using LU decomposition.
Below is the summary of how the LU decomposition is applied to solve a system of linear equations.

Given matrix, Ax = bAx=b
- First decompose A into L and U matrices
- Create the system LZ = b and solve for Z.
- Set the system Ux = Z and solve for x.

The x vector we obtain above is the solution for the system of linear equations. This algorithm is powerful.
In this article, we will learn in clarity more about how to compute all these matrices we've just outlined above and later implement the process in python.

#### Key takeaways 
- How to decompose a matrix into Upper matrix U and create and create a lower matrix U using the multiplier values used to obtain matrix U.
- How to solve a system of linear equations using this algorithm by hand.
- How to solve a system of linear equations using LU decomposition in pythonl.

#### Article quality
As you can see, this article will dive deeper into the topic. Instead of covering how to compute the LU matrix and rest our case, we will go a step further and show how we solve a system of linear equations using the LU decomposition and its implementation.
Many articles online focus on how to perform LU decomposition, i.e., creating L and U matrix. However, for application, they consider doing it as a separate task. In our article, this will not be the case. Instead, we will provide the learner with a full material that they learn how to decompose a matrix using LU decomposition and apply the knowledge of LU decomposition to solve linear systems with less computational power.

#### References
N/A

**Comment by WanjaMIKE** [comment]
@DennisKimt I liked the detailed explanation. I was curious to determine its plagiarism score. Its 100% This means that even your article will not be unique and thus, provide little value.

![ice](https://user-images.githubusercontent.com/38399942/156993338-c8d4d32d-f468-486c-b20b-5a03740aba3f.png)

**Comment by Daniel695** [comment]
Hello @WanjaMIKE 
I've checked the plagiarism for the above issue and its score is 100 %. With my search, it turns out it's the same issue referring to itself "[issueantenna.com›repo›section-engineering-education›engineering-education›issues›6871](https://issueantenna.com/repo/section-engineering-education/engineering-education/issues/6871)" and not an already written article. Kindly, would search again and try to reach plagiarism links and confirm this. Thank you.

**Comment by DennisKimt** [comment]
Hello @WanjaMIKE
I've checked the plagiarism for the above issue and its score is 100 % just as you found. However, with my search, it turns out it's the same issue referring to itself "[issueantenna.com›repo›section-engineering-education›engineering-education›issues›6871](https://issueantenna.com/repo/section-engineering-education/engineering-education/issues/6871)" and not an already written article. Kindly, would search again and try to reach the plagiarism links and confirm if this is the case on your side. Thank you.
