### ISSUE TITLE
[Machine Learning] Object Detection Using PyTorch

### ISSUE THREAD

**Issue by EssyH** [section-engineering-education/engineering-education#6875]
### Topic Suggestion
[Machine Learning] Object Detection Using PyTorch

#### Proposed title of article
Object Detection Using PyTorch.

#### Proposed article introduction
Object detection is a computer technology that uses a deep learning algorithm to recognize the object, its location, and the capacity to trace the object from given data. The input will be in the form of an image or a video. The key benefit of object detection in PyTorch is that it can define or, to put it another way, identify the class of objects as well as their positions based on the input. The class of an object denotes that it belongs to a specific category of things, such as a person, system, or table.

#### Key takeaways 
- What is PyTorch object detection?
- How to use PyTorch object detection?
 - installation of PyTorch on our system
 - installation of some standard packages on our system such as NumPy, imutils, matplotlib, and tqdm
- PyTorch object detection networks
- Steps by Steps PyTorch object detection script

#### Article quality
Unlike other articles, the code will be well explained and not just copy-pasted. But designed in an eccentric way for easier understanding and consumption. Deeply emphasizing the importance and use of packages required to perform object detection using pytorch

#### References
Please list links to any published content/research that you intend to use to support/guide this article
[Introduction to Pytorch](https://ai.ncsa.illinois.edu/wp-content/uploads/2021/10/Introduction-to-PyTorch.pdf)
[PyTorch: An Imperative Style, High-Performance Deep Learning Library](https://proceedings.neurips.cc/paper/2019/file/bdbca288fee7f92f2bfa9f7012727740-Paper.pdf)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
This article is already covered [here](https://github.com/section-engineering-education/engineering-education/pull/5407). Feel free to suggest another topic. Thanks
