### ISSUE TITLE
[LANGUAGES] Getting Started with YAML, JSON, and XML Data formats

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#6876]
### Introduction
As a software engineer, one must have the basic knowledge about different representation of data formats. For instance, a REST API data is fomated in JSON structure while it is in YAML for cloud-native applications.  This is crucial in development practices and every developers will surely work with these formats. 

### Key takeaways
In this tutorial, readers will learn how to get started with different data formats and the following;
- What is YAML and how it is used to format data.
- YAML syntaxes and their meanings
- JSON and XML structure.
- Differences between these data formats and their functionalites.
- Demo on REST API with JSON

### Article Quality
Readers will benefit immensely in this tutorial because i will be walking them through the various data formats, how they are been used by demo, and syntaxes. This is very crucial to learn in real-world practices.

### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

@Horlawhumy-dev Unfortunately, we already have many articles showing REST APIs and returning JSON data.

**Comment by Horlawhumy-dev** [comment]
@WanjaMIKE sir, thank you for the response on this issue. This tutorial aims to teach readers different types of data formats.
Most beginners struggle to differentiate between these formats, and of which they cannot do without them as developers. 

Kindly allow me to talk about it. I am willing to make this unique, and worth reading at the end. Thank you!

**Comment by Horlawhumy-dev** [comment]
@Wanjamike sir😴
