### ISSUE TITLE
Cross-Site Scripting for Cookie Tracking and Stealing

### ISSUE THREAD

**Issue by munenekelvin** [section-engineering-education/engineering-education#6877]
#### Proposed title of article
Cross-Site Scripting for Cookie Tracking and Stealing

#### Proposed article introduction
When you return to the same website, the cookie that you previously got from that website may be used to identify you when you return. Cookies are alphanumeric strings that are generated at random on a website and transferred to your browser by the website that you have visited before (known as session ID). A common use of cookies is to keep track of your online preferences. Because cookies go across servers, they are subject both to interception and theft. Throughout this tutorial, you will learn about cookies and how they may be hacked.

#### Key takeaways
- How are cookies used in a website
 - Understanding the Cookie Trail
 - How websites utilize cross-site scripting (XSS) to steal cookies

#### Article quality
This article goes into great depth on the use of Cross-Site Scripting for Cookie Tracking and Stealing. While ensuring that the issue is simple to comprehend for beginners, the goal is to simultaneously provide a reference piece for intermediate and advanced users to refresh their memory on the topic from an introductory position..

#### References
N/A

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=Cross-Site+Scripting+for+Cookie+Tracking+and+Stealing&sourceid=chrome&ie=UTF-8), this topic appears a bit over-saturated. We usually focus more on unique projects. Feel free to suggest another one. Thanks
