### ISSUE TITLE
Building a studio landing page with Javascript and GSAP's ScrollTrigger Animation Plugin

### ISSUE THREAD

**Issue by deverten** [section-engineering-education/engineering-education#6880]
#### Introduction
The use of animations enhances a sites appeal and improves the user experience while navigating the website. The Greensock Animation platform popularly known as GSAP is a javascript  animation library that can animate DOM elements, canvas, SVG, CSS properties, , generic JavaScript objects, and so much more. Hence, it boasts of about 10,000,000 websites built with it. Popular websites like Codesandbox, Drupal, Nvidida, Gitlab and a lot more others use this tool for their animations.

GSAP introduced a plugin called ScrollTrigger for creating interactions as you scroll. The scroll Trigger Plugin enables you animate anything on the scroll as long as it can be manipulated with Javascript. The ScrollTrigger Library is an improvement of scroll-driven animation yet it is flexible, user-friendly, it supports vertical and horizontal scrolling (this effect is common amongst award-winning websites today).

In this tutorial, we will build a Studio landing page  that uses GSAP for animations and ScrollTrigger to trigger the animations. The goal is to learn about the GSAP ScrollTrigger plugin, and how to use it to trigger animations on the scroll, and the use cases for it.  you will 

#### Key takeaways 
By the end of this tutorial, the reader should:
- Know how to implement animations using GSAP
- Understand the basics of the GSAP ScrollTrigger plugin and how to use it with Javascript.
- Know how to implement ScrollTriggers vertical and horizontal scrolling in websites.

#### Article quality
This article aims to get developers up to speed with building highly animated websites. It sets the tone for mimicking the award winning websites that exist today.

#### References
- GSAP's Documentation
- ScrollTrigger's Documentation

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic @deverten Let's ensure that it adds value to the community. Thanks
