### ISSUE TITLE
Visualizing Time Series Data With Chart.Js

### ISSUE THREAD

**Issue by Pauline-Mwangi** [section-engineering-education/engineering-education#6881]
### Topic Suggestion
Visualizing Time Series Data With Chart.Js

#### Proposed title of article
Visualizing Time Series Data With Chart.Js

#### Proposed article introduction
Time series data is a collection of observations measured over time. Time series data is everywhere since time is a constituent of everything observable. They can be beneficial for tracking and analyzing changes over time. This guide will visualize time series data with Chart.js and InfluxDB.  InfluxDB is a database specifically designed to work with time-series data.

This article will use Chart.js and InfluxDB to visualize time series data. By leveraging the capabilities of InfluxDB along with the flexibility and power of Chart.js, you can visualize time series data efficiently. This guide will explain how the reader can use Chart.js in conjunction with InfluxDB cloud for data visualization.

#### Key takeaways 
1. Time series data
2. Visualizing Time Series Data with Chart.js and InfluxDB

- Chart.js overview
- Set up project with Chart.js
- Set up InfluxDB
- Configure the client to communicate with InfluxDB cloud
3. Using Chart.js with InfluxDB

- Use Flux to query data from InfluxDB cloud
- Visualize the data with Chart.js and create different types of charts using data from InfluxDB

#### Article quality
This is an interactive and well detailed tutorial about visualizing time series data with chart.js and InfluxDB. The content covered will be unique as this topic is not widely covered.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by WanjaMIKE** [comment]
Seems like a help topic @Pauline-Mwangi Let's ensure that it adds value to the community. Thanks

**Comment by WanjaMIKE** [comment]
Closed #6881 via #7358
