### ISSUE TITLE
[Android]Inter-app and Network Security

### ISSUE THREAD

**Issue by leence00** [section-engineering-education/engineering-education#6885]
Inter-app and Network Security

#### Introduction
Android apps must communicate with one another by sending network requests to backend servers. Understanding the security processes can help to limit the threat or malicious behavior that might occur as a result of inter-app communication. Applications use a variety of ways to interact with one another, and steps are made to ensure that only trustworthy apps can interact with one another.

#### Key takeaways 
- Ensuring interoperability with other components.
- Using network security setup to secure network connection.
- Using certificate authority and certificate pinning to secure network communication.

#### Article quality
This article explain the concept of network security and inter-app communication in a concrete manner which is understandable to both beginners and experts in android development, it also illustrate how to perform network security in android application which is not well illustrated is already published articles.

#### References
N/A

**Comment by WanjaMIKE** [comment]
@leence00 How will you perform the network security?

**Comment by leence00** [comment]
Hello @WanjaMIKE  network security will be done by setting up network security configurations and customizing certificate authorization. trusted by the application

**Comment by ahmadmardeni1** [comment]
cc @WanjaMIKE

**Comment by hectorkambow** [comment]
@leence00 

Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved


https://www.google.com/search?q=Inter-app+and+Network+Security&rlz=1C1CHBF_enUS891US891&ei=YbZhYtyZN7rF0PEPw4KVWA&ved=0ahUKEwiczr3J96X3AhW6IjQIHUNBBQsQ4dUDCA4&uact=5&oq=Inter-app+and+Network+Security&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeMggIIRAWEB0QHjIICCEQFhAdEB4yCAghEBYQHRAeMggIIRAWEB0QHjIICCEQFhAdEB4yCAghEBYQHRAeMggIIRAWEB0QHjIICCEQFhAdEB4yCAghEBYQHRAeOgcIABBHELADSgQIQRgASgQIRhgAUJkDWJkDYOMEaAJwAXgAgAFViAFVkgEBMZgBAKABAqABAcgBCMABAQ&sclient=gws-wiz

**Comment by hectorkambow** [comment]
@leence00 
Closing for now - can be re-opened (or resubmitted) if you decide to add more to your EngEd profile. 

If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.
