### ISSUE TITLE
[Android] How to request runtime application permissions using Dexter- Kotlin

### ISSUE THREAD

**Issue by kabjanet** [section-engineering-education/engineering-education#6886]
### Topic Suggestion
How to request application permissions using Dexter- Kotlin

#### Proposed article introduction
When developing a certain application, there are needs to grant permission to the application to be able to use a certain phone feature of a phone such as a camera and memory storage. Enabling permissions in runtime helps the users to exert more control over the software they have installed on their devices. Using dexter, the user should be able to grant or restrict permissions when the app is operating, rather than when the program is installed. This is more advantageous because the user may have reasons as to why they may grant permission or deny the application may be due to lack of trust, hence using dexter is a better approach.

In this tutorial, we will create an application that allows the users to grant or restrict permission to the application they have installed whenever they want to use the phone feature such as a camera or storing a captured image to the memory.

#### Key takeaways 
- Introduction to Dexter
- Adding relevant dependencies
- Adding permissions to the manifest file according to our application
- Designing the application XML layout
- Writing Kotlin code
- Running the application

#### Article quality
This article will be beginner-friendly and will help the developers understand the importance of using Dexter permission requests to satisfy the user's usability on an application. Since not every user will not be satisfied when allowing permissions to an application which he has no trust, hence will help a user to grant permissions when he feels secure too because some applications can be threats and can lead to the collapse of users' data.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Unfortunately, there seems to be many [online articles](https://www.google.com/search?q=How+to+request+application+permissions+using+Dexter-+Kotlin&oq=How+to+request+application+permissions+using+Dexter-+Kotlin&aqs=chrome..69i57j69i61.346j0j9&sourceid=chrome&ie=UTF-8) on gaining runtime permissions with Dexter. How will this topic be unique?

**Comment by kabjanet** [comment]
Hello @WanjaMIKE, I had a walkthrough on the other blogs which you have just referenced. This article will be unique because I will go ahead to implement Dexter's permission request in the application I will develop. It will use methods such as onActivityResult(), and Intents to access the application settings and load elements such as an image view with a bitmap from the gallery using Glide. I will also clearly illustrate how images captured using the camera can be saved to external storage in the correct format with the help of WRITE_TO_EXTERNAL_STORAGE which is shallowly discussed in other blogs.

Thank you.

**Comment by WanjaMIKE** [comment]
Noted @kabjanet
