### ISSUE TITLE
hands on developing corona-virus  web App in vanilla JavaScript  using Covid-19 and Fetch API.

### ISSUE THREAD

**Issue by Njengab** [section-engineering-education/engineering-education#6887]
### Topic Suggestion
hands on developing corona-virus  web App in vanilla JavaScript  using Covid-19 and Fetch API.

#### Proposed article introduction
Information is essential in today's world. In this article, we will make a Covid-19 web tracker application that gathers  data from Covid cases, recoveries, and deaths in a nation and showcases the information. We will make the app using the vanilla JavaScript ,Covid-19 API and the Fetch API.

#### Key takeaways 
1. Understanding the importance of corona-virus information.
2. HTML and CSS foundation code.
3. Fetch and Covid-19 API  implementation.
4. Vanilla JavaScript complete code.

#### Article quality
My article will be simple and easy to understand, with relevant information on the Covid-!9 pandemic presented in a step-by-step format to serve as a guide for any web developer.
#### References
N/A

**Comment by WanjaMIKE** [comment]
This topic suggestion seems quite similar to https://www.youtube.com/watch?v=nDYKRL7mwRw Therefore, it will not provide enough value to the community. Feel free to suggest another topic. Thanks
