### ISSUE TITLE
Getting started with EmberJS

### ISSUE THREAD

**Issue by Youngshark3** [section-engineering-education/engineering-education#6892]
Topic Suggestion
Getting started with EmberJS

Proposed title of the article
Getting started with EmberJS

Proposed article introduction
Ember.js is a free JavaScript web framework that follows the Model–View–View Model (MVVM) architecture. By combining popular idioms and best practises into the framework, developers may design scalable single-page web apps.

It provides a more full MVC pattern than other popular JavaScript application frameworks, as well as capabilities to help you design apps for the web of the future. It's also one of the more opinionated frameworks out there, depending primarily on convention rather than configuration to help you create your app.

Key takeaways
This is an easy-to-read and comprehend article.

We go down the essential elements of Ember framwork in an easy-to-understand manner for newcomers.

We describe how to use Ember framwork in a simple, concise, and straightforward manner so that readers can easily navigate through official release notes and information.

Article quality
Our article covers the information about Ember framework, including its benefits, use cases, and, most importantly, how users may use it most effectively, as well as its documentation.

**Comment by WanjaMIKE** [comment]
Unfortunately, introductory aspects to Ember.js are already covered adequately in the [official docs](https://emberjs.com/). Therefore, this topic suggestion will not provide adequate value. Feel free to suggest another topic. Thanks
