### ISSUE TITLE
Getting Started With WebRTC and Firebase

### ISSUE THREAD

**Issue by Roy-Wanyoike** [section-engineering-education/engineering-education#6893]
Proposed title of article
Getting Started With WebRTC and Firebase

Introduction paragraph (2-3 paragraphs):
Work from home has been a boom these days. This has been made possible by using various streaming applications
to facilitate communication. For a web developer, WebRTC is an API that is used to build a real-time peer-to-peer connection
between two or more browsers. It is a native browser API and works without the need for a third-party server or native app.

WebRTC facilities real-time audio/video communication on the web using a peer-to-peer protocol,
allowing you to build apps like Zoom, Skype, etc. In this tutorial, we will use JavaScript and Firebase as the signaling server to build a simple video chat application.

Key takeaways:
Getting Started with WebRTC

How WebRTC works

How to use WebRTC API with Firebase

References:
N/A

**Comment by WanjaMIKE** [comment]
@Roy-Wanyoike This topic was already suggested and approved here https://github.com/section-engineering-education/engineering-education/issues/1681 Feel free to suggest another topic. Thanks
