### ISSUE TITLE
Create a Python App that Extracts images, Scan For text Info, Transcribe and save to a .txt file

### ISSUE THREAD

**Issue by Wachira48** [section-engineering-education/engineering-education#6897]
#### Proposed article introduction

Python is a huge and popular language that many developers enjoy working with. Its human-readable syntax makes it a popular language and an easy to learn path. As a developer, you might need to extract information from an image. Images contain visual text that you can extract and add to the relevant text document. Python makes a good choice to create a program that extracts such text from any given image. In this guide, we will learn how to create s python app using the tesseract. We will create and write a Python script that extracts images, scan text, transcribe and save it to a .txt file.

#### Key takeaways 

- Why create a Python App that Extracts images info
- What is Python tesseract
- Set up a Python tesseract project
- Install dependencies
- Create a Python tesseract script that Extracts images info
- Test the Python tesseract app

#### Article quality

The overall guide aims to help the reader build an app that Extracts images info using Python scrips.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Wachira48 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
