### ISSUE TITLE
Working with a private AWS S3 Bucket in Flutter

### ISSUE THREAD

**Issue by Lekwacious** [section-engineering-education/engineering-education#6898]
#### Proposed title of article
Working with a private AWS S3 Bucket in Flutter

#### Proposed article introduction
This article teaches how to use a private AWS S3 Bucket as a cloud file storage in a flutter project. Instead of storing our files directly on the database, it is stored on S3 Bucket and the Presigned URL pointing to the file in the cloud is retrieved and stored on the database. Readers will learn how to work with AWS in a flutter project.

#### Key takeaways 
- Integrating AWS S3 Bucket in a Flutter project.
- File upload and storage on a private AWS S3 Bucket from a flutter App.
- How to download, encrypt and decrypt S3 Bucket Presigned URL.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
