### ISSUE TITLE
CopyLeaks API Automation

### ISSUE THREAD

**Issue by louisefindlay23** [section-engineering-education/engineering-education#6899]
**Is your feature suggestion related to a current problem or issue?**

The web UI of CopyLeaks can hang if the article is rather large resulting in having to copy and paste articles in chunks and have to navigate to the raw GitHub index.md file to copy and paste in which is time consuming for each plagiarism check.

**Describe the solution you'd like to implement to the program**

As an MVP, create a web app that you can enter a GitHub PR number and would obtain the URL of the raw index.md GitHub file and submit the URL to CopyLeaks. The normal PDF report would be generated, saved to the server and then the user would be redirected to view it (and take action as a normal plagiarism check.

There's also the scope to extend and automate this further by attaching the PDF into a GitHub comment and posting this into the PR, automatically when new PRs are submitted, meaning content moderators could review plagiarism checks in GitHub without having to submit scans, saving a lot of time.

**Additional context on how you could go about building this**

**MVP**

1.  Create a basic web server with a form to submit a GitHub PR number, use Octokit (GitHub API) to list files in the PR and obtain the raw file URL of an article's index.md file.
2. Authenticate with the CopyLeaks API (using either Node.js SDK or Axios), submit the file to scan, upon the completion webhook, run either the export webhook or downloads method for PDF Report
3. Download the PDF as a stream using fs
4. Redirect the user to the downloaded PDF file

**Automation**

- Use a webhook and GitHub Automation to trigger the webserver when a new PR has been created
- See Step 2
- Use Octokit to post a comment on the PR with the attachment and possibly results %. - See [GitCord Bot](https://github.com/louisefindlay23/gitcord-bot/blob/main/commands/github-post-comment.js) for a similar example

**Comment by hectorkambow** [comment]
Closing for now - will re-open when we revisit.
