### ISSUE TITLE
Getting started with neural network in PyTorch

### ISSUE THREAD

**Issue by ivymugo** [section-engineering-education/engineering-education#6905]
#### Proposed title of article
Getting started with neural network in PyTorch

#### Proposed article introduction
Neural networks are a set of algorithms, modeled loosely after the human brain, that are designed to recognize patterns. They interpret sensory data through a kind of machine perception, labeling or clustering raw input.

Without using a perceptron or any other hidden layers, we'll construct a single-layer neural network from scratch. It will have two layers: an input layer with training examples and synapses or weights, and neurons, and an output layer with the right responses.

#### Key takeaways 
- Installation of the required libraries
- Building a training model
- Adding learning iterations

#### Article quality
In this article, we will build a neural network that can only recognize very simple patterns on a very small data set. The article will be unique as I will expand it by trying to teach the AI to recognize something in pictures.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
There are tons of tutorials on this topic. How makes your article unique? @ivymugo

**Comment by ivymugo** [comment]
Hello @ahmadmardeni1 I recommended this subject since most blogs that I've read gloss over information that is already included in the documentation. Torch Tensor To NumPy Array Conversion and vice versa (not mentioning all here) have not been well described by most of them. There will be no other article like this one, thus it is important that this one stays true to the spirit of the community while also adding something new. Thanks

**Comment by ahmadmardeni1** [comment]
Approved. Just please make sure you are writing a unique tutorial. @ivymugo
