### ISSUE TITLE
How to analyze Linear Time Integral(LTI) in Python

### ISSUE THREAD

**Issue by florenceakinyi** [section-engineering-education/engineering-education#6908]
### Topic Suggestion
How to analyze Linear Time Integral(LTI) in Python

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-perform-parallel-computing-using-matlab/

#### Introduction
Linear Time-Invariant (LTI) systems are a significant part of the signal processing toolbox that defines the action of a physical system on the signal. LTI systems have the input 'excitation' and the output ' response. The basic principle of these systems is linearity and time invariance.
In this tutorial, we introduce the LTI systems. Also, various time domain and frequency domain analyses of LTI systems are implemented using Python. The Python program can plot various time response curves such as Impulse response, Step response and Ramp response. It can also give various stability plots such as Root locus, Nyquist plot, Bode plot, Log magnitude vs Phase plot (Nichols Plot) and Pole-zero plot. The Python implementation is done using Spyder IDE in the Anaconda environment.

#### Key takeaways 
- Introduction to LTI systems.
- Various (Time domain/ Freq. domain) analysis of LTI systems.
- Anaconda and Spyder for Python implementation.
- Python Control System Library.
- Python code for LTI System Analysis.

#### Article quality
This article shows how you can use Python to analyze LTI systems. These includes the various LTI plots

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
