### ISSUE TITLE
Getting started with React Suspense

### ISSUE THREAD

**Issue by raelmuchiri** [section-engineering-education/engineering-education#6911]
#### Proposed title of article
Getting started with React Suspense

#### Proposed article introduction
React developers use Suspense to tell React that a component is waiting for data to arrive before it can be used. Afterwards, React understands that it must wait for that data to be retrieved before continuing. In the meanwhile, the user will see a fallback and the remainder of the application will be rendered using React. React will return to that specific UI and make the necessary updates whenever the data is available.

Suspense deeply integrates with React, allows developers to more intuitively orchestrate loading states, and avoids race conditions.

#### Key takeaways 
- Why we need Suspense
- Fetch-on-render
- Fetch-then-render
- Solve the data fetching issues
- Benefits of Suspense

#### Article quality
To help the reader understand the fundamentals of Suspense, this article will uniquely cover several questions and aspects that are important to it. This involved going over what Suspense is, why we needed something like Suspense in the first place, how it solves certain data fetching issues and all the benefits that come with Suspense.

#### References
N/A

**Comment by WanjaMIKE** [comment]
*React suspense* seems to be adequately covered in the [official documentation[(https://reactjs.org/docs/concurrent-mode-suspense.html) and thus, will not provide enough value. Feel free to choose another topic. Thanks
