### ISSUE TITLE
[Android] Getting Started with YouTube Android Player API to Play YouTube Videos

### ISSUE THREAD

**Issue by mosestakai** [section-engineering-education/engineering-education#6912]
#### Proposed article introduction
The YouTube Android Player API enables you to incorporate video playback functionality into your Android applications. The API defines methods for loading and playing YouTube videos (and playlists) and for customizing and controlling the video playback experience.

Using the API, you can load or cue videos into a player view embedded in your application's UI. You can then control playback programmatically. For example, you can play, pause, or seek to a specific point in the currently loaded video.

You can also register event listeners to get callbacks for certain events, such as the player loading a video or the player state changing. Finally, the API has helper functionality to support orientation changes as well as transitions to fullscreen playback.

#### Key takeaways 
- What is YouTube's Android Player API?
- How does it work?
- Obtain your KEY.
- Integrating it into an Android project.

#### Article quality
This is something that I have been learning and using it in a Movies app that I am developing, so I thought I should share a clear tutorial so that other developers don't have to go through the whole web looking for a solution. 

#### References
-N/A

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
