### ISSUE TITLE
Unit Testing with Vue-test-utils

### ISSUE THREAD

**Issue by mercybassey** [section-engineering-education/engineering-education#6913]
### Topic Suggestion
Unit Testing with Vue-test-utils

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-receive-emails-using-emailjs-in-vue3/

#### Proposed title of article
Unit Testing with Vue-test-utils

#### Proposed article introduction
[Languages]
As a developer, you happen to write unit tests 90% of the time. It is good practice to write tests; in addition, it is an in-demand skill. [Vue-test-utils](https://v1.test-utils.vuejs.org/) is a library built on top of jest and it is the official library for testing Vue applications. With Vue-test-utils one can check if a component is performing just as it should or if a user is seeing what he/she is meant to see on every component or if a component is accepting the props being passed to it by its parent component and so many functionalities as well.   It's very easy to use and I am ready to share its different use cases and best practices in this article.

#### Key takeaways 
After reading this article, the reader should be able to:
- Know how to write unit tests with the Vue-test-utils library
- Know how to write async tests
- Know why he/she should test

#### Article quality
In this article, I will be going in-depth as I will explain how to write tests for different use cases. 

#### References
https://v1.test-utils.vuejs.org/
https://github.com/vuejs/test-utils

**Comment by WanjaMIKE** [comment]
good topic @mercybassey  - approved. One important note: please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published
