### ISSUE TITLE
[Databases]The evolution and strife for speed within Databases

### ISSUE THREAD

**Issue by phinaomondi** [section-engineering-education/engineering-education#6914]
### Topic Suggestion
Strife for speed within Databases

### Writing sample(s): 
Include any links or writing samples to help our team gauge your writing quality better.

#### Comparative Review of Hadoop, MongoDB and SAP HANA

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Before the world became digital, most companies stored relatively smaller amounts of data that were easy to process and works with. However, as time passed, technology led to the massive generation of huge amounts of data that needed better and advanced processing methods.

Among the first processing and storage technologies was Hadoop. However, later on, many other types of Databases came by in competition with the initial Hadoop. This article discusses the evolution of databases in terms of speed, nature of data storage, scalability and efficiency while narrowing it down to Hadoop, SAP HANA and MongoDB.

In the end, the reader should know which database has a better performance and what is the overheads coming with choosing one over the other.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
- An overview of the evolution of Databases
- The Advantages and Disadvantages of working with various kinds of Databases
- Choosing the right database for your project.

#### Article quality
This article is suitable for developers seeking to decide on which database to choose from depending on the size of the application they intend to build and the available resources. It uniquely explains the evolution of databases and the current trends seen in database technology.

#### Writing samples
https://www.section.io/engineering-education/authors/phina-kersly/

#### References
Please list links to any published content/research you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
