### ISSUE TITLE
How to build an Internet Service Provider Management System using MongoDB, Express, React and Node.js

### ISSUE THREAD

**Issue by wanguiwaweru** [section-engineering-education/engineering-education#6915]
### Topic Suggestion
How to Build an Internet Service Provider Management System using MongoDB, Express, React and Node.js

### Writing sample(s): 
https://dev.to/wanguiwaweru/matplotlib-basics-1aao
https://dev.to/wanguiwaweru/graphs-in-python-1pom

#### Proposed title of article
How to build an Internet Service Provider Management System using MongoDB, Express, React and Node.js

#### Proposed article introduction
In this tutorial, we will learn how to integrate our knowledge of various technologies including MongoDB, React and Node.js to create a functional web application. Internet Service Providers (ISPs) need an informative and dynamic platform to facilitate better management ensuring customer satisfaction and accurate business records.

We will build a management system that allows ISPs to create, read, update and delete customer information and update relevant subscriptions. The ISPs can also retrieve records on the payment status of various customers. The main objective of this tutorial is to provide foundational knowledge on how to create a MERN stack application through a real-life project.

#### Key takeaways 
- Create, Read, Update and Delete (CRUD) operations using MERN stack. 
- Creating a React app.
- MongoDB collections.
- Creating a RESTAPI with Express.

#### Article quality
This tutorial aims to enhance the learners ability to build production-ready fullstack applications. Learners will gain an understanding how the technologies in the MERN stack can be used to build robust products.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
