### ISSUE TITLE
[Artificial Intelligence]Subfields of Artificial Intelligence and Their Properties 

### ISSUE THREAD

**Issue by Brian3811** [section-engineering-education/engineering-education#6916]
### Topic Suggestion
Subfields of Artificial Intelligence and Their Properties 

### Writing sample(s): 
https://www.section.io/engineering-education/introduction-to-kernel-methods-in-machine-learning/

#### Proposed article introduction
First lets begin by describing what is Artificial intelligence; This is the ability of a computer to perform task
that are normally done by human due to their intelligence.
Artificial intelligence has 5 subfields: Machine learning, Robotics, Neural network, Natural Language Processing and Expert System

{1}Machine learning; focuses on the use of data and algorithms to mimic how humans learn and gradually improves
 performance accuracy.
{2} Robotics; focuses on the development of robots that can do tasks without the need for further human intervention
{3} Neural network; focuses on biological intervention in artificial intelligence (AI) that is fashioned after 
the human brain.
{4} Natural Language Processing ;focuses on a computer's ability to interpret spoken and written human language
{5} Experts System; focuses as an expert on challenging situations by drawing information from its knowledge base

#### Key takeaways 
- Definition of Artificial intelligence
- Subfields of Artificial intelligence
- Definitions of each subfield of Artificial intelligence
- Explanations on the Subfields of Artificial intelligence

#### Article quality
This article will be unique from other articles  as in my article i have used simple English making it easy for any
person to understand the subfields of AI easily.
I will ensure that the article helps any person interested in it in EngEd community and any other user
#### References
N/A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
