### ISSUE TITLE
Building a Recommendation System with Lenskit and test it with nDCG in Python

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#6919]
#### Proposed title of article
Building a Recommendation System with Lenskit and test it with nDCG in Python

#### Proposed article introduction
In order to attract new customers and maintain current customers, the recommendation system is a vital tool that understands their preferences and recommends goods they would like. Today are a variety of recommendation systems out there, and many large organizations are still working to make theirs the best. Our research into recommendation can be enhanced and the optimal algorithm discovered more efficiently with the [Lenskit](https://lenskit.org/) framework.

The [nDCG](https://towardsdatascience.com/normalized-discounted-cumulative-gain-37e6f75090e9) measure will be used in this tutorial to evaluate several algorithms for a recommender system, and we'll explore how [Lenskit](https://lenskit.org/) can help us create one.

#### Key takeaways 
- Loading the Dataset
- Importing and Instantiating the Algorithm
- Evaluating the Recommendations

#### Article quality
So in this article, we'll look at two algorithms and see which one is better at recommending things. This can be used to look at more algorithms and more datasets to find the best overall algorithm, or at least one algorithm that is better than another.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=Building+a+Recommendation+System+with+Lenskit+and+test+it+with+nDCG+in+Python&oq=Building+a+Recommendation+System+with+Lenskit+and+test+it+with+nDCG+in+Python&aqs=chrome..69i57j69i60l2.339j0j9&sourceid=chrome&ie=UTF-8), there appears to be several articles covering recommendation systems using the provided technologies. Feel free to suggest another topic. Thanks
