### ISSUE TITLE
[Machine Learning] How to Make Line Follower Robot

### ISSUE THREAD

**Issue by JonesRaven** [section-engineering-education/engineering-education#6920]
### Topic Suggestion
[Machine Learning] How to Make Line Follower Robot

#### Proposed article introduction
The line follower robot is a simple robot that follows a given route based on a specific line, which is commonly a dark line on a light surface. Two sensors are mounted on the robot's front end, and two DC motors drive the robot's wheels. Based on the input signal from the sensors, the circuit board in the robot controls the wheel speed. The robot is controlled in such a way that when it sees a black line, it comes to a halt.

#### Key takeaways 
- What is Line Follower Robot?
- Designing the Outer Structure of the Robot
- Defining the Kinematics
- Designing the Control System
- Examples of Line Follower Robot

#### Article quality
Unlike other articles, this one  will be well explained and designed in an eccentric way for easier understanding and consumption. Using  simple grammar my article will deeply emphasize and guide the reader step by step on how to make line follower robot hence making it beginner-friendly 

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Is this a programming-centric topic? It seems more hardware based.

**Comment by JonesRaven** [comment]
Hello @WanjaMIKE It's a machine learning concept dealing with Arduino though there's no programming codes in it

**Comment by ahmadmardeni1** [comment]
cc @WanjaMIKE

**Comment by JonesRaven** [comment]
@ahmadmardeni1  hello good morning..

**Comment by hectorkambow** [comment]
@JonesRaven 

This one seems a bit out of our wheelhouse as we tend to focus of software related topics.
