### ISSUE TITLE
How to Design Resilient Microservices

### ISSUE THREAD

**Issue by Alicewangari** [section-engineering-education/engineering-education#6921]
#### Proposed title of article
How to Design Resilient Microservices

#### Proposed article introduction
Even if a microservice application has a 99.9% uptime, a downtime of 0.1 percent suddenly becomes noticeable as use becomes larger. There may be just one failure in a thousand requests, but what about a million? That equates to a total of a thousand missteps.

Microservice applications can't have any failures. Instead, you should concentrate on creating microservices that can gracefully recover from errors and minimize the effect of such failures on your system, which are failure-tolerant.

In this article, we'll look at the causes of failure in a microservice application, how to reduce or minimize their influence on a system, and how to optimize service availability — basically, unique approaches to build and assure a dependable, failure-tolerant microservice.

#### Key takeaways 
- Sources of failure
- Maximizing service availability
- Performance testing

#### Article quality
In this article we will look at the various points where failures are likely to occur in a microservice application. We will explore the strategies and techniques we can utilize to mitigate the impact of these failures in our system. To make our article unique, we shall see how can we use performance testing methods to validate that our services are truly fault-tolerant, and can recover gracefully.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

**Comment by WanjaMIKE** [comment]
It can be summarized as:
### How to Make Your Services Resilient?
- Identify Failure Scenarios. ...
- Avoid Cascading Failures. ...
- Avoid Single Points of Failure. ...
- Handle Failures Gracefully and Allow for Fast Degradation. 
- Design for Failures. 
- Circuit Breaker Pattern. 
- Retry Design Pattern. 
- Timeout Design Pattern.
