### ISSUE TITLE
Adding background video view in android application - Kotlin

### ISSUE THREAD

**Issue by judywambaki** [section-engineering-education/engineering-education#6923]
### Topic Suggestion
Adding background video view in android application - Kotlin

#### Proposed article introduction
Application design is key when it comes to developing users' applications. Video views have come to play a major role in android development by creating applications that make a user feel lively and most of the time keep logged in. They can be used in an app as a struct on a particular thing or just a plain video.

In this tutorial, I'd like to develop an application showcasing the use of video view as the activity background. Thereafter, I shall implement floating interactive elements such as buttons and card views in the activity. 

#### Key takeaways 
- Introduction to video view
- Creating application project
- Working with the XML file
- Writing Kotlin code
- Testing the app

#### Article quality
This article will be beginner-friendly that will help the developers know the importance of using video view in their applications activities. It will also use simple Kotlin code with step-by-step procedures to achieve our objective. The readers thereafter can integrate the video view in the application they are building.

#### References
https://www.youtube.com/watch?v=WLwQ3SJjWfY

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
