### ISSUE TITLE
standardscaler and minmaxscar transformition in python

### ISSUE THREAD

**Issue by Geofreytech** [section-engineering-education/engineering-education#6924]
#### Proposed title of article
standardscaler and minmaxscar transformition in python

#### Proposed article introduction
MinMaxscaler and StandardScaler are two scaling methods used in machine learning for continuous data. Minimum and maximum values are set to 0 and 1, respectively, via a MinMaxscaler. To put it another way: The StandardScaler only scales the values between min and max so that they all fall within that range.

We will learn about the principles of MinMaxScaler & StandardScaler using Python code in this article.

#### Key takeaways 
- Reason why  we need Feature Scaling 
- Normalization and standardization
- MinMaxScaler for Normalization
- StandardScaler for Standardization

#### Article quality
- There will be a Pandas data frame involved.
- This post will explain the concepts and distinctions between MinMaxScaler and StandardScaler through Python code examples.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=standardscaler+and+minmaxscar+transformition+in+python&sourceid=chrome&ie=UTF-8), this topic seems a bit over-saturated. We focus more on unique projects. Feel free to suggest another topic. Thanks
