### ISSUE TITLE
[Android] Prefilling Room Database with JSON Data in Android

### ISSUE THREAD

**Issue by benta-odek** [section-engineering-education/engineering-education#6926]
#### Proposed article introduction
Sometimes, you might want your app to start with a database that is already loaded with a specific set of data. This is called pre-populating a database. In Room 2.2.0 and higher, you can use API methods to pre-populate a Room database during initialization with content from a prepackaged database (.db)  file in the device's file system.

From the Android documentation:
- To pre-populate a Room database from a prepackaged database file that is located anywhere in your app's assets/ directory, you can call the createFromAsset() method.
- To pre-populate a Room database from a prepackaged database file that is located anywhere in the device's file system except your app's assets/ directory, call the createFromFile() method.

From the docs, there is no indication as to how you can prefill your DB with JSON data. In this tutorial, we are going to prefill the database that we are going to create with some JSON data that I have prepared, from your end you could be filling it with some JSON data that you have downloaded from your backend.

#### Key takeaways 
- A recap of setting up the Room database.
- Understanding what pre-populating Room database with initial data is.
- When is it necessary to pre-populate a Room DB?
- What is a Room DB callback and how do I add a callback to the database?
- Implementing the pre-filling of Room DB.

#### Article quality
Most of the blog sites and tutorials online focus on pre-populating room database with `.db` data which matches the schema of the database with `createFromAssets` and  `createFromFile` methods. In this tutorial I will make it unique by coming up with an easy and straightforward method of pre-populating Room DB with JSON data.

#### References
- N/A

**Comment by WanjaMIKE** [comment]
Seems like a help topic @benta-odek Let's ensure that it adds value to the community. Thanks
