### ISSUE TITLE
Beginner’s Guide for Data Partitioning in HiveQL

### ISSUE THREAD

**Issue by augustinemagero** [section-engineering-education/engineering-education#6932]
### Topic Suggestion
Beginner’s Guide for Data Partitioning in HiveQL

#### Proposed article introduction
The Apache Software Foundation later acquired Facebook's hive and renamed it Apache Hive after the social media giant constructed it. A wide range of companies make use of it. Amazon Elastic MapReduce makes advantage of this technique. Optimizing Hive with partitioning can increase performance by a factor of 10 or more. An ad-hoc analysis of structured and semi-structured data can be performed using Apache Hive, a data warehouse built on Hadoop. HDFS is capable of storing potentially petabytes of data. As a result, Hadoop users have a tough time searching this enormous amount of data. The Hive made data retrieval easier. In order to submit the MapReduce jobs to the Hadoop cluster, we use Apache Hive to transform the SQL queries into MapReduce jobs. As soon as we submit a SQL query, Hive takes the entire data set into consideration.
Running MapReduce jobs over a large table becomes inefficient as a result of this. As a result, tables are partitioned to address the issue. Apache Hive simplifies partitioning by automatically building divisions at the time of table creation.Let’s have a brief discussion on partitioning in the hive.

#### Key takeaways 

1. Overview of hive, features of hive and use cases of hive 
2. Introduction to partitioning, types of hive partitions and how to do this partitions
3. Data Partitioning Example and managing partition tables
4. Partitioning with external tables
5. Listing Partitions
6. Advantages and disadvantages of hive partitioning

#### Article quality
The article will be a detailed guide on how to use HiveQL for data partitioning using well explained examples

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
