### ISSUE TITLE
Understanding Optical Character Recognition(OCR) with Tesseract, OpenCV, and Python

### ISSUE THREAD

**Issue by puritymutunga** [section-engineering-education/engineering-education#6933]
### Topic Suggestion
Understanding Optical Character Recognition(OCR) with Tesseract, OpenCV, and Python

#### Proposed article introduction
We, as humans, spend nearly every waking moment reading something written on a piece of paper. Our computers and other technologies would be fantastic if they could read the same way we do. More importantly, how can we get our machines to read? Optical character recognition (OCR) comes into play in this situation. OCR (Optical Character Recognition) is a method for digitizing handwritten or printed text and converting it into a searchable and editable digital version.
In this article, we will focus on Tesseract OCR. And to read the images we need OpenCV.

#### Key takeaways 
1.  Introduction to OCR and its applications
2. Build sample OCR Script
3.  Building word clouds on Review images
4. Create audible files (Text to Audio)

#### Article quality
The article will enable the reader to have understanding of the concept of OCR and will be familiar with reading images using OpenCV and grabbing the text from images using pytesseract

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit [over saturated](https://www.google.com/search?q=Optical+Character+Recognition(OCR)+with+Tesseract%2C+OpenCV%2C+and+Python&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8) throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
