### ISSUE TITLE
[security ] Understanding and defense from CSRF attacks

### ISSUE THREAD

**Issue by MutaCyberSec** [section-engineering-education/engineering-education#6935]
**Topic Proposed **
Cross Site Request Forgery 
Use of  CSRF tokens in sites running on Flask python framework to prevent form  submissions from attackers

**Key Takeaways **
Understanding what is a CSRF attack and how it is executed
Understanding and how to generate strong and genuine CSRF tokens for use in defense from these attacks.

Reference
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
