### ISSUE TITLE
How to Build templates for Django Applications with HTMX

### ISSUE THREAD

**Issue by khabdrick** [section-engineering-education/engineering-education#6936]
### Writing sample(s): 
https://www.section.io/engineering-education/authors/muhammed-ali/

#### Proposed title of article
How to Build templates for Django Applications with HTMX

#### Proposed article introduction
In this article, I will build a simple Django application (API), create views of it then go into details of how the reader can implement HTMX in their Django frontend. This is important if you don't want to go through the stress of using a library like React or Vue.

ONLY viable topics to pick from:
- API
- Languages

#### Key takeaways 
- Learn about HTMX
- Learn how to connect HTMX with Django
- Learn how to fetch data directly from the Django API with HTMX

#### Article quality
it is a unique article.

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
