### ISSUE TITLE
[Flutter]Dependency injection in Flutter using ProxyProvider

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#6938]
### Topic Suggestion
Dependency injection in Flutter using ProxyProvider
#### Proposed article introduction
It has been a while since the new version of Provider (v3) came out. It has a new feature called a ProxyProvider. In this case, ProxyProvider is a service that builds its value by using other service providers. This means that you can now put providers into other values that have been given.

We will use the ProxyProvider to add dependencies to our flutter app.
#### Key takeaways 
- Implementation.
- Usage
- Injecting providers
#### Article quality
1. ProxyProvider is a new feature that came out as an update of V3 meaning that it is not widely written on. 
2. I found some few articles and documentations that talks about dependency injection using ProxyProvider but in this tutorial i will be talking about the injections in depth and will provide simple dart codes that can be easily understood and grasp.

#### References
- [ProxyProvider class - provider library](https://pub.dev/documentation/provider/latest/provider/ProxyProvider-class.html)
- [How to Use ProxyProvider with Flutter](https://dev.to/paulhalliday/how-to-use-proxyprovider-with-flutter-3ifo)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @vincentkims49

**Comment by WanjaMIKE** [comment]
@vincentkims49 why is topic similar to https://github.com/section-engineering-education/engineering-education/issues/6937?

**Comment by ahmadmardeni1** [comment]
Oh sorry LOL @WanjaMIKE

**Comment by vincentkims49** [comment]
@WanjaMIKE 
@NdoloBonface  told me to write on it since the Idea was mine. 
We are classmates from the same school. Thanks 👍

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over [saturated ](https://www.google.com/search?q=Dependency+injection+in+Flutter+using+ProxyProvider&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8)throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
