### ISSUE TITLE
[Android] Extracting Text Details on Different Material with Firebase ML Kit  in Android

### ISSUE THREAD

**Issue by JoelKanyi** [section-engineering-education/engineering-education#6939]
#### Proposed article introduction
Assuming you are in an organization that collects the details of your clients manually, this might be a tiresome practice as you have to use a pen and a paper to take the data. 

Firebase ML Kit is a mobile SDK that brings Google's machine learning expertise to Android apps in a powerful yet easy-to-use package. Whether you're new or experienced in machine learning, you can implement the functionality you need in just a few lines of code. There's no need to have deep knowledge of neural networks or model optimization to get started. On the other hand, if you are an experienced ML developer, ML Kit provides convenient APIs that help you use your custom TensorFlow Lite models in your mobile apps.

In this tutorial, we will come up with a simple android app that uses the device camera and the ML kit to text details written on different surfaces.

#### Key takeaways 
- What is Firebase ML Kit?
- How to Integrate the Firebase ML Kit in Android.
- Build an app that extracts the Text details on any material.

#### Article quality
Based on the published content online, there is no article that explains how you can extract the details of a text written on different surfaces i.e road sides, books, billboards and many more with Firebase ML kit and in Android.

#### References
- N/A

**Comment by Agusioma** [comment]
@JoelKanyi, I am looking forward to this. Machine Learnig=ng in Android 🍾

**Comment by WanjaMIKE** [comment]
Is the article specific to the Kenyan National ID. If yes, please change the topic to a more general thing. Thanks

**Comment by JoelKanyi** [comment]
> Is the article specific to the Kenyan National ID. If yes, please change the topic to a more general thing. Thanks

@WanjaMIKE I have changed the topic to be general

**Comment by JoelKanyi** [comment]
Hello @WanjaMIKE, I made the changes.

**Comment by JoelKanyi** [comment]
@WanjaMIKE, please give a feedback of this 🙏

**Comment by JoelKanyi** [comment]
Hello @hectorkambow, kindly look through this issue

**Comment by JoelKanyi** [comment]
@ahmadmardeni1
