### ISSUE TITLE
[Blockchain] Introduction on how to Create ERC20 Tokens and Transact using Brownie (Python)

### ISSUE THREAD

**Issue by RaphaelNdonga** [section-engineering-education/engineering-education#6941]
### Topic Suggestion
Create ERC20 Tokens and Transact using Brownie (Python)

### Writing sample(s): 
https://www.section.io/engineering-education/sealed-classes-in-kotlin/
https://www.section.io/engineering-education/hilt-android-tutorial/

#### Proposed title of article
Create ERC20 Tokens and Transact using Brownie (Python)

#### Proposed article introduction
ERC20 tokens are a representation of something on the Ethereum Blockchain. They can reference a representation of Gold, in which case those tokens are very valuable. They can also reference a representation of someone's toenails, in which case those tokens are somewhat less valueable.

In this tutorial, you are going to do the following:
- Create your own ERC20 token
- Deploy your token to a local blockchain.
- Make transactions using your token
- Create a smart contract that interacts with your token.

#### Key takeaways 
- How to Create your own ERC20 token
- How to Deploy your token to a local blockchain.
- How to Make transactions using your token
- How to Create a smart contract that interacts with your token.

#### Article quality
Youtube videos that have been published on this are very shallow:
https://www.youtube.com/watch?v=8rpir_ZSK1g

They only teach users how to mint tokens. This article will dive deeper by teaching:
- How to check the balance
- How to transfer that token to another address
- What an allowance is and how to grant it. 

The docs are useful but they only describe the smart contracts. They do not describe how to handle this ERC20 tokens using  Brownie. They also don't explain how to Create a smart contract that interacts with your token.

#### References
https://docs.openzeppelin.com/contracts/2.x/api/token/erc20

**Comment by ahmadmardeni1** [comment]
Nice suggestion! Bty I know Patrick. He is a really smart man. Approved. @RaphaelNdonga

**Comment by RaphaelNdonga** [comment]
The Patrick Collins?! That's interesting. @ahmadmardeni1
