### ISSUE TITLE
[LANGUAGES] Creating a stepper form for your Laravel application using React.js

### ISSUE THREAD

**Issue by Agusioma** [section-engineering-education/engineering-education#6943]
### Topic Suggestion
Creating a stepper form for your Laravel application using React.js

### Writing sample(s): 
[Here](https://www.section.io/engineering-education/cpp-model-in-a-python-machine-learning-project/) is my latest sample.

#### Proposed title of article
Creating a stepper form for your Laravel application using React.js

#### Proposed article introduction
One of the many things that keep users happy with your product is a good User Experience(UX). Let's see one instance. A user needs to fill in data for some serious formal activity e.g course enrollment, online bank registration, etc. As expected, such forms usually have many fields. Eventually, the user may get fatigued in the process, or even lose interest along the way. How about creating a stepper(multi-step) form with several sections and steps that allow him/her to fill in the data while taking pauses? It sounds better, right? It also allows us, developers, to also save the information entered in steps so that in case of anything- a power outage, lost internet connection- the data is persisted and the user proceeds from where he left. 

We are going to create one for Laravel using React.js. To save us from writing codes for the banners and connectors, we will use a prebuilt react-form-stepper component.

#### Key takeaways 
The reader will learn about:
- Setting up React in Laravel.
- What is a stepper form- the parts, use cases, etc.
- Using React's conditional rendering to appropriately display and hide the parts of the form.

#### Article quality
It's unique in that it talks about adding this feature in Laravel. Other blogs talk about doing this using React alone or Blade templating files alone. It will also be easy to follow through.

#### References
[GeeksForGeeks](https://www.geeksforgeeks.org/designing-a-stepper-form-in-reactjs/)

**Comment by ahmadmardeni1** [comment]
I think this video is covering the same topic: https://www.youtube.com/watch?v=jgmRM8Cfvxo
Please @ me if I'm wrong. Feel free to suggest an alternate topic to explore. 🚀

**Comment by Agusioma** [comment]
@ahmadmardeni1, no they aren't the same. He is using blade templating which is quite different from my suggestion. I filled the quality section with this --"Other blogs talk about doing this using React alone or Blade templating files alone"-- Before then, I cross-checked with [this blog](https://www.itsolutionstuff.com/post/laravel-multi-step-form-example-tutorialexample.html) and [this](https://blog.devgenius.io/create-a-multi-step-form-with-reactjs-322aa97a2968). So the video does what the latter does.
