### ISSUE TITLE
[Android] Enabling Offline Caching Using Room Persistence Library for Data Fetched with Retrofit in Jetpack Compose

### ISSUE THREAD

**Issue by omondi-alex** [section-engineering-education/engineering-education#6944]
#### Proposed article introduction
Offline caching allows an application to access the data of the app even when not connected to the internet. This is possible in apps that require an internet connection only if the data is cached in the local storage. Room persistence library provides this capability by allowing you to cache the data from a remote server into your local database which can then be accessed offline. We will build the application using the Clean architecture pattern and Jetpack compose.

#### Key takeaways 
- What is offline caching.
- How to use Room to cache data offline with retrofit
- What is Clean Architecture
- How to build an app that fetches data with Retrofit and cache using clean architecture

#### Article quality
The contents that are published online are lacking the implementation of offline caching with room in Jetpack compose and clean architecture. This article is going to use that clean architecture pattern and Jetpack compose.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
