### ISSUE TITLE
Solidity vs Python: Which is the Best Blockchain Platform

### ISSUE THREAD

**Issue by BridgetMwikali** [section-engineering-education/engineering-education#6945]
#### Proposed title of article
Solidity vs Python: Which is the Best Blockchain Platform

#### Proposed article introduction
In the past few years, we’ve seen blockchain technology grow in popularity. Even though it’s still relatively new, this technology is already being adopted by big companies like IBM and Microsoft. Many software developers are looking to find ways to join the blockchain movement and get in on this exciting new market.

Solidity and Python are two popular programming languages used to write smart contracts on blockchains. The blog will discuss the most important pros and cons of both languages, helping you make an informed decision.

#### Key takeaways 
Solidity, Ethereum and Chaincode
Which language is ideal for a smart contract between Python and Solidity?

- Ease of use
- Error handling
- Community and support
- Compatibility

Static typing vs dynamic typing

#### Article quality
This blog discusses why Solidity is likely to become the standard for blockchain platforms in the future. It also compares Python to Solidity in the creation of Ethereum based technology and platforms.

**Comment by ahmadmardeni1** [comment]
I don't think this is the right comparison. Solidity is the top choice for blockchain development.  

Please feel free to suggest an alternate topic to explore. 🚀 @BridgetMwikali
