### ISSUE TITLE
Understanding static HTML export in NextJS 

### ISSUE THREAD

**Issue by Saintdavidking** [section-engineering-education/engineering-education#6947]
OUTLINE:

brief overview of HTML
Why use static HTML
Using static HTML import inNext.JS
Next.JS Static HTML Export Supported Features
Next.JS Static HTML Import nonvalid Features
Code Portability
SEO benefits
Improved First Paint Times

**Comment by ahmadmardeni1** [comment]
This is not the right template. Please read our docs and take a look at other topic suggestions. @Saintdavidking
