### ISSUE TITLE
SQL Injection using Sqlmap

### ISSUE THREAD

**Issue by shosenwales** [section-engineering-education/engineering-education#6948]
### Topic Suggestion
Sql Injection using Sqlmap

### Writing sample(s): 
https://www.section.io/engineering-education/testing-for-broken-authentication-in-web-apps/

https://www.section.io/engineering-education/getting-started-with-burpsuite/

#### Proposed title of article
Sql Injection using Sqlmap

#### Proposed article introduction
[Security] This article seeks to introduce the reader to Sql Injection and Sqlmap, which is a tool for finding sql vulnerabilities in web applications.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.
After reading this article, the reader will understand:
- What Sql Injection is
- How to find sql vulnerabilities using Sqlmap
- Impact and prevention of sql vulnerabilities

#### Article quality

This article will explain to the reader what sql vulnerabilities are, and also demonstrate how to find this vulnerability using a tool called sqlmap. I'll be walking the readers through the process of using the tool and methods to protect web application from this vulnerability

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
This topic is oversaturated on numerous blog sites and official docs. I rejected it before.
