### ISSUE TITLE
[Android]A complete guide on how you can  implement an Autocomplete Textview with custom Adapter

### ISSUE THREAD

**Issue by kamothosimon** [section-engineering-education/engineering-education#6950]
#### Proposed title of article
A complete guide on how you can  implement an Autocomplete Textview with custom Adapter

#### Proposed article introduction

We are going to build an AutoCompleteTextView with a custom adapter, that can not only show text suggestions, but also images. 

At first we will prepare our MainActivity layout as well as the  layout for each suggestions item. We will also create the Java class that will contain the information for each suggestion the name and the image resourceand lastly we will create an ArrayList and fill it with   items

#### Key takeaways 
1.Create an ArrayList and fill it with  items.
2.Understand how to build a Autocomplete TextView 
3.Create the Java class that will contain the information for each suggestion

#### Article quality
The aim of the article is to provide content that will be well understood by all our learners
#### References
N/A

**Comment by ahmadmardeni1** [comment]
This topic has already been covered by a lot of tutorials: https://www.google.com/search?q=how+to+implement+an+Autocomplete+Textview+with+custom+Adapter&oq=how+to+implement+an+Autocomplete+Textview+with+custom+Adapter&aqs=edge..69i57j69i61.1273j0j9&sourceid=chrome&ie=UTF-8


Please feel free to suggest an alternate topic to explore. 🚀 @kamothosimon
