### ISSUE TITLE
[Android] Creating a Video Conferencing App with 100ms SDK in Android

### ISSUE THREAD

**Issue by tomleposo** [section-engineering-education/engineering-education#6951]
#### Proposed title of article

Creating a Video Conferencing App with 100ms SDK in Android

#### Proposed article introduction
100ms is a cloud platform that allows developers to add video and audio conferencing to Web, Android and iOS applications.

The platform provides REST APIs, SDKs, and a dashboard that makes it simple to capture, distribute, record, and render live interactive audio and video.

It adds live video conferencing to your app in 10x fewer lines of application code than any other fully customizable video SDK. It was built by the team that created live video infrastructure powering billions of minutes a day at Facebook and Disney+Hotstar.

In this tutorial we will create a simple android application from scratch and video conferencing capabilities to the app with the help of the 100ms SDK.

#### Key takeaways 
- What is 100ms SDK.
- How is 100ms SDK different from other video conferencing SDKs.
- Pricing.
- How to integrate it into your Android app.

#### Article quality
The article will be beginner friendly and straight to the point. 100ms SDK being new, few articles have been written explaining how it should be used. So I will do my best to explain things well.

#### References
- [100ms Android Docs](https://www.100ms.live/docs/android/v2/foundation/Basics)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @tomleposo
