### ISSUE TITLE
[Languages]Introduction to C# Query basics using expressions

### ISSUE THREAD

**Issue by Joshuathuo** [section-engineering-education/engineering-education#6953]
#### Proposed title of article
Introduction to C# Query basics using expressions

#### Proposed article introduction
A query in line with c#  programming language is defined as a set of instructions that are used in the retrival of data. But of the result query that is generated is automatically different from the query itself.

In this article therefore, we are going to have a look at the basics of query expressions using C# programming language. The results of the queries will also be considered in this example. To achieve this, we shall use well defined example for the purposes of simplicity.

#### Key takeaways 
1. How to start a query expression
2. How to end a query expression
3. A look at implicit and explicit typing of variables

#### Article quality
The quality of the article will be in such a way that it will be understood by every learner at any level.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
This topic has already been covered by a lot of tutorials: https://www.google.com/search?q=Introduction+to+C%23+Query+basics+using+expressions&oq=Introduction+to+C%23+Query+basics+using+expressions&aqs=edge..69i57j69i61.272j0j1&sourceid=chrome&ie=UTF-8 


Please feel free to suggest an alternate topic to explore. 🚀
