### ISSUE TITLE
Using Formik with Next JS and TypeScript to design a registration page

### ISSUE THREAD

**Issue by Terripha** [section-engineering-education/engineering-education#6954]
#### Proposed title of article
Using Formik with Next JS and TypeScript to design a registration page

#### Proposed article introduction
[Jared Palmer](https://formik.org/docs/overview) authored the Formik library out of frustration when building React forms. He needed a way to standardize the input components and the flow of form submission. Formik helps you to write the three most annoying parts of building a form:
- Getting values in and out of form state
- Validation and error messages
- Handling form submission

In this article, we will learn how to construct a form using Next, TypeScript and Formik . A simple registration form will be created, and it will undergo some basic validation before being submitted. In React and React Native, you can use the Formik library to create dynamic forms.

#### Key takeaways 
-  Creating the registration form
- Showing errors in the forms using `formik.errors`
- Integrating Formik to a Next project in Typescript

#### Article quality
In this article we will create a unique project on how to build a registration page using Formik with Next and TypeScript.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic @Terripha Let's ensure that it adds value to the community. Thanks

**Comment by ahmadmardeni1** [comment]
I'm going to close this issue due to inactivity. It can be re-opened.
