### ISSUE TITLE
Uploading, deleting, and downloading images uploaded to sanity.io

### ISSUE THREAD

**Issue by ben-cdm** [section-engineering-education/engineering-education#6956]
#### Proposed title of article
 Uploading, deleting, and downloading images uploaded to sanity.io

#### Proposed article introduction
Sanity.io is a structured content platform. With the help of sanity.io, you can manage text, images, and other media with APIs. Also, you can use the open-source single-page application Sanity Studio to quickly set up an editing environment that you can customize.

In this tutorial, the developer will learn how all this information can be managed on the frontend (website) instead of using Sanity Studio. Using GROQ, we will upload images to sanity.io (Content Lake Database) and retrieve them to be viewed on our website. Afterward, we will implement the delete and download features.

#### Key takeaways 
-  Working with GROQ 
-  Uploading images on the website
-  Retrieving images from Sanity.io
-  Deleting images on the website
-  How can images be downloaded on the website

#### Article quality
The developer will learn both basic/beginner and advanced knowledge on how to use sanity with react js. The developer will also learn how to upload images from the website instead of using sanity cms. The developer will also learn how to use GROQ's sanity query language.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @ben-cdm

**Comment by ben-cdm** [comment]
thanks @ahmadmardeni1 for the advice
