### ISSUE TITLE
How to bring your valuable Java apps into the 21st century

### ISSUE THREAD

**Issue by Eztaezta** [section-engineering-education/engineering-education#6959]
#### Proposed title of article
How to bring your valuable Java apps into the 21st century

#### Proposed article introduction
The IT industry's media is awash in success stories about businesses that have made the switch to the cloud, and new cloud-native applications are being developed on a daily basis. The majority of cloud apps, on the other hand, were already well-suited to cloud infrastructures.

There are many applications that corporations have worked hard to develop over the years. The pandemic of 2020 will only help to emphasize the value of these existing assets to our society, since they will be required to adapt to new demands with minimal expenditure.

There are many reasons why companies want to modernize their applications. For instance, to improve security and protect sensitive data, among others.

#### Key takeaways 
1. The right approach to modernize your application.
2. Best modernization steps.
3. Why do companies want to reap the benefits of modern applications?
4. Advantages of modern applications

#### Article quality
The article will be written in a way that will help the readers understand how to modernize their applications without any challenges.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
