### ISSUE TITLE
Build your first Spark web application

### ISSUE THREAD

**Issue by mosesmwangi442** [section-engineering-education/engineering-education#6961]
#### Proposed title of article
Build your first Spark web application

#### Proposed article introduction
Spark Framework is a simple and expressive Java/Kotlin web framework DSL built for rapid development. Sparks intention is to provide an alternative for Kotlin/Java developers that want to develop their web applications as expressive as possible and with minimal boilerplate. With a clear philosophy Spark is designed not only to make you more productive, but also to make your code better under the influence of Spark’s sleek, declarative and expressive syntax.

To get a general sense of how Spark works, we will quickly walk through creating a website to display a letter to our friends. Then, we'll explore the individual elements of a Spark web application in further detail throughout the article.

#### Key takeaways 
- Integrating HTML into Spark
- How to add resources in our application
- Creating a Root Path

#### Article quality
There are a few articles on Spark Framework with few information. This tutorial will take the reader through the process of running their own Spark web application. This article will be fully unique as we are setting up a unique project and then explore it.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks

**Comment by WanjaMIKE** [comment]
Closed #6961 via #7137
