### ISSUE TITLE
Building a Stopwatch with Javascript and Tailwind CSS

### ISSUE THREAD

**Issue by prince-joel** [section-engineering-education/engineering-education#6967]
#### Proposed title of article
Building a Stopwatch with Javascript and Tailwind CSS

#### Proposed article introduction
Are working on a project that needs a stopwatch or you are performing a task that requires timing? in this article, we will be building a simple stopwatch with javascript and styled with a CSS framework called Tailwind CSS.
If this is your first time using Tailwind, we will be learning briefly how to set up Tailwind CSS using the docs  and get it ready for use.

#### Key takeaways 

-  The reader will learn how to set up Tailwind
- The reader will how to use Tailwind in their application
- The reader will learn how to build a simple stopwatch 

#### References
N/A

**Comment by WanjaMIKE** [comment]
Please include more key takeaways. I believe introductory aspects of tailwind have already been covered by other articles. Thanks

**Comment by prince-joel** [comment]
@WanjaMIKE 
Proposal Submission

Proposed title of article
Building a Stopwatch with JavaScript and Tailwind CSS

Proposed article introduction
Are you working on a project that needs a stopwatch or performing a task that requires timing? in this article, we will be building a simple stopwatch with JavaScript and styled with a CSS framework called Tailwind CSS.
If this is your first time using Tailwind, we will be learning briefly how to set up Tailwind CSS using the docs and get it ready for use.

Key takeaways
The reader will learn how to set up Tailwind
The reader will learn how to use Tailwind in their application
The reader will learn how to build a simple stopwatch
The reader will learn what JavaScript EventListener is and how to use it 
The readers will learn how to automate activities in an application with the use of the stopwatch they have created

References
N/A

**Comment by prince-joel** [comment]
Hello @WanjaMIKE I added new key takeaways are they enough or should I add more
