### ISSUE TITLE
[Security] Disassembly and reverse engineering using cutter

### ISSUE THREAD

**Issue by pop-ecx** [section-engineering-education/engineering-education#6968]
### Topic Suggestion
[Security] Disassembly and reverse engineering using cutter

#### Proposed title of article
Disassembly and reverse engineering using cutter

#### Proposed article introduction
During software development, linkers, compilers and assemblers are used in creating an executable. In order to fully understand how a program works, tools are used in order to disassemble and decompile an executable. This is the essence of reverse engineering. 

Disassembly is the act of converting machine code to assembly code. Disassemblers are tools used in performing this task. Decompilers are used in converting assembly code into a C-like source code. Unlike disassembly, decompiling is more difficult due to decompilers being language and library dependent as well as the compilation process being very lossy. However, development of accurate compilers is still an active area of research.

In this article, we will familiarize with cutter as a disassembly and reverse engineering tool.

#### Key takeaways 
The reader will be able to:
- Understand the meaning of disassembly and reverse engineering.
- Comprehend the necessity of reverse engineering.
- Understand the algorithms used for disassembly.
- Understand the advantages of using cutter for reverse engineering.
- Reverse engineer a simple crackme using cutter.

#### Article quality
This article will go more in depth while at the same time delivering its contents in a palatable way for beginners.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Based on this [search](https://www.google.com/search?q=Disassembly+and+reverse+engineering+using+cutter&oq=Disassembly+and+reverse+engineering+using+cutter&aqs=chrome..69i57j35i39i362l6j69i60.319j0j7&sourceid=chrome&ie=UTF-8), disassembly seems to be over-saturated on other blog sites and official documentation.
