### ISSUE TITLE
Predicting future stock prices using ARIMA model in R

### ISSUE THREAD

**Issue by kipkoech88** [section-engineering-education/engineering-education#6969]
### Topic Suggestion
How to predict future stock market prices using the ARIMA model in R

#### Proposed title of the article
Predicting future stock market prices using ARIMA model in R 

#### Proposed article introduction
[machine learning] How to predict future stock market prices using ARIMA model in R
With the increase in the number of investors in the stock market and the increase in popularity of various cryptocurrencies whose rates in the stock market changes constantly, it is useful to create a program that can predict future prices in the stock market to help investors make a better decision on the right time to invest so that they can maximize their profits.
ARIMA model is one of the most useful models in predicting future trends and in this case, future prices using R language or Python. in this article, I am going to show you how exactly you can go about it step by step

#### Key takeaways 
1. Import yahoo finance data in R
2. Stock charting
3. analyze the correlation of data
4. Differencing data to be stationary
5. do stationary testing using unit root testing
6. Building ARIMA model
7. Fitting ARIMA model and forecasting
8. Performing multiple forecasting

#### Article quality
My article will be unique with well-documented codes that are running and explained in an easy, in-depth manner that a data science beginner can easily understand and be able to perform prediction with this tutorial. 

#### References
https://rpubs.com 
https://www.econ.berkeley.edu
https://towardsdatascience.com

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
