### ISSUE TITLE
[Security]Mastering YARA for Malware Analysis the right way.

### ISSUE THREAD

**Issue by Dyrstiu** [section-engineering-education/engineering-education#6976]
### Topic Suggestion
Mastering YARA for Malware Analysis the right way.

### Writing sample(s): 
https://www.section.io/engineering-education/getting-started-with-visual-basic-net/

#### Proposed title of article
Mastering YARA for Malware Analysis the right way. 

#### Proposed article introduction
YARA is a tool used by cyber security Engineers for malware analysis. It provides a rule-based approach to detect patterns of malware characteristics in files. A rule is a basic description of malware characteristics. The malware contains specific characteristics, such as unique strings, which we can use to identify if a file has malware.

#### Key takeaways 
- What is YARA
- How to install YARA in both Linux and Windows Systems.
- YARA Rules Syntax 
- Running YARA Rules

#### Article quality
This article will guide the user on how to install YARA, its basic syntax and go a step further and demonstrate how YARA rules can be used in malware analysis .

**Comment by ahmadmardeni1** [comment]
What makes your article differ from https://www.google.com/search?q=YARA+for+Malware+Analysis&oq=YARA+for+Malware+Analysis&aqs=edge..69i57j69i61.296j0j9&sourceid=chrome&ie=UTF-8 ? @Dyrstiu

**Comment by Dyrstiu** [comment]
The article you have highlighted does not go through the basic syntax of the YARA rules ,it does not guide the user on how to write their own rules and also how to install YARA on the readers machine.  @ahmadmardeni1

**Comment by ahmadmardeni1** [comment]
Please make sure your article does not overlap with any of them. Approved. @Dyrstiu
