### ISSUE TITLE
[Blockchain] Creating a simple Blockchain cyptocurrency coin with python

### ISSUE THREAD

**Issue by Adespscientist** [section-engineering-education/engineering-education#6978]
### Topic Suggestion
Creating a simple Blockchain cyptocurrency coin with python

#### Pre-submission advice
In the IT industry, the field of Blockchain is rapidly expanding. Blockchain technology is projected to have been embraced by more than one-third of all organizations in the globe, and demand for blockchain developers is on the rise.
The term "cryptocurrency" refers to a sort of currency that is only available online. It does not exist in a physical form, but rather in a blockchain on a server that keeps transaction data in blocks without personal identifying information.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
The reader should be able to understand the following at the end of the tutorial:
- Blockchain Cryptocurrency: What Is It and How Does It Work?
- Setting up the Python environment
- Create a crypto coin with python

#### Article quality
Cheaper and faster money transactions are among the benefits of cryptocurrencies, as are decentralized systems that do not have a single point of failure. One of the benefits of cryptocurrency transactions is that they may be done in a matter of minutes. Unlike other websites that discuss cryptocurrencies, we will show you step by step how to create your own cryptocurrency coin and explain its significance.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
