### ISSUE TITLE
UNDERSTANDING DAEMONS IN LINUX USING NODE.JS

### ISSUE THREAD

**Issue by osepoo** [section-engineering-education/engineering-education#6979]
## Proposed article introduction
- A daemon process simply put is a program that runs in the background smoothly.
“Smoothly” in that even if a session in the foreground is stopped or an input mechanism is interacted with, the daemon process will continue. This is the main difference between Background tasks and daemon processes.
 - The first and obvious method we’ll showcase is using the “&”, showing vividly how it’s affected by SIGHUP and the huponexit parameter.
 We’ll then showcase the disown command including all the functionalities and how It’s affected by standard I/O.
 We’ll then showcase the nohup command with all its functionalities and how it will relate to the ampersand.
We’ll then showcase how to use the screen and Tmux command to implement a daemon process that doesn’t stop when the terminal windows are closed.
Finally, we’ll showcase forever, nodeman and pm2 which are node tools for running node applications as daemon processes.

## Key takeaways 
- Understanding the difference between background and daemon processes.	
- Understanding the effects of SIGHUP signal and huponexit on the ampersand.
- Understanding the disown command in running daemon processes.
- Understanding the nohup command in running daemon processes.
- Understanding the different node tools when running node applications as daemons.
- How to use Tmux to implement daemon processes.
- Understanding how to run a simple node.js server on the terminal as a daemon process.

## Article quality
These are all the different functionalities of how daemon processes work with nodejs servers collected into one article. It’ll be more in-depth as I’ll open up every process with its advantages and disadvantages displaying lines of understandable code as we move along.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @osepoo
