### ISSUE TITLE
How to denoise images using wavelet packet transform(WPT) in Matlab

### ISSUE THREAD

**Issue by queenterbruce063** [section-engineering-education/engineering-education#6980]
### Topic Suggestion
How to denoise images using wavelet packet transform in Matlab

### Writing samples
https://www.section.io/engineering-education/implementation-of-convolution-integral-of-continuous-time-linear-time-invariant-systems-in-matlab/

#### Proposed article introduction
The wavelet packets are the generalized approach of wavelet decomposition which introduces a spacious area of the possibility of signal analysis that permits the better accordance analysis to the signal. It transforms the signal to the frequency domain level. WPT is a generalization of the orthogonal wavelet transform. Wavelet packets are used for finer analysis by breaking up high-frequency space into approximation and detailed space. In wavelet transform, these detailed spaces are not decomposed. Here, only the approximation space is split.
This tutorial explains the basic theoretical background of WPT based denoising scheme, noise variance estimation and universal threshold calculation. The denoising is implemented in MATLAB to do experiments with different noisy 1D and 2D signals. The concept of full tree and best tree-based decomposition is also included.

#### Key takeaways 
- Introduction to Wavelet Packet Transform (WPT).
- WPT based Denoising scheme.
- Noise variance estimation and finding universal threshold.
- Thresholding methods.
- MATLAB functions for WPT and WPT based denoising.
- MATLAB code for denoising images.

#### Article quality
In this article, we cover the WPT into details and how it can be applied in Matlab. This include the Matlab functions for this transform.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
