### ISSUE TITLE
Socket Programming Using Java

### ISSUE THREAD

**Issue by Youngshark3** [section-engineering-education/engineering-education#6983]
#### Proposed title of article
[Networking] Socket Programming Using Java

#### Proposed article introduction
Socket programming is a way of programming in which a computer program sends and receives data over a network connection, this includes computers, smartphones, and other connected devices such as appliances, to devices like routers and servers. A socket is a protocol of the Transmission Control Protocol (TCP) that is used in computer networking to implement communication with a computer over a computer network.

#### Key takeaways 
In this article, I will take the reader through the concept of:
Asynchronous mode of function calls
Synchronous modes of function calls
The reader will also understand the concept of socket programming
The reader will be able to develop a program that can be able to connect to other devices on the network

#### Article quality
This article tends to take the reader through the concept, of socket programming in the java and also use a practical approach for a better understanding of it. This will make the reader understand what socket programming is in the best way possible.

**Comment by WanjaMIKE** [comment]
This topic is already covered here -> https://github.com/section-engineering-education/engineering-education/issues?q=Socket+Programming+Using+Java
