### ISSUE TITLE
[Language]Automating Excel Sheet in Python 

### ISSUE THREAD

**Issue by taves-hub** [section-engineering-education/engineering-education#6991]
### Topic Suggestion
Automating Excel Sheet in Python 

#### Proposed article introduction
Data Analysis forms a crucial part of gaining valuable insights from your customers. Multiple organizations are trying innovative ways to simplify the process of Data Analysis. Some are trying to completely automate this process whereas others are using multiple tools to set up the same. Another innovative technique used by companies to perform Data Analysis is linking their data source with a programming language and having it automate their Data Analysis.
Python Excel Automation is an innovative process that one can use to create visual reports on Python just the same way as you would on Excel seamlessly. Organizations can leverage Python Excel Automation to leverage their business tasks according to their needs.

#### Key takeaways 
By the end of the article, the readers will have:
- Analyze the Excel Dataset
- Create a Pivot Tables using Pandas
- Design the Reports using Openpyxl
- Automate the Report with Python
- Schedule the Python Script
#### Article quality
This article will give the learner a step-by-step guide on setting up Python Excel Automation. It will also give the learner an overview of both Python and MS Excel along with their features. 

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by jerimkaura** [comment]
Hello @taves-hub 

Thanks for the amazing topic suggestion. Just a quick one. Please check to confirm that your article do not overlap with [this one](https://github.com/section-engineering-education/engineering-education/pull/2267)

**Comment by taves-hub** [comment]
@jerimkaura hello... I had gone through the mentioned article and I thought of improving what is in it. In my article I will make sure that even the novices who has no or little knowledge in python understand every bit of what I will be talking about. And also give a life demo.

Let me know what you think

Thank you.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your suggstion. What differs your article from:
1. https://towardsdatascience.com/a-simple-guide-to-automate-your-excel-reporting-with-python-9d35f143ef7?gi=47474941dee2
2. https://www.youtube.com/watch?v=YwIX8w9i2DM 
? @taves-hub

**Comment by taves-hub** [comment]
@ahmadmardeni1 hello sir, I believe that knowledge can never be exhausted, and when I look at nearly similar content online, the above mentioned articles are not beginner-friendly and are not as engaging as they could be. Of course, this article will be one-of-a-kind, and it will address these issues as gracefully as possible in order to maintain quality and add value to the community. Thanks

**Comment by ahmadmardeni1** [comment]
Great! Approved. @taves-hub
