### ISSUE TITLE
[Machine Learning] Multivariate time series using Auto ARIMA

### ISSUE THREAD

**Issue by jamesomina99** [section-engineering-education/engineering-education#6995]
#### Proposed title of article
[Machine Learning] Multivariate time series using Auto ARIMA

#### Proposed article introduction
It is a series of observations taken at specified times basically at equal intervals. It is used to predict future values based on past observed values. The components you might observe in the time-series analysis are Trend, Seasonal, Irregular, and Cyclicity.

A Multivariate time series has more than one time-dependent variable. Each variable depends not only on its past values but also has some dependency on other variables. This dependency is used for forecasting future values.

Forecasting, making predictions about the future, plays a key role in the decision-making process of any company that wants to maintain a successful business. This is due to the fact that success tomorrow is determined by the decisions made today, which are based on forecasts.

An autoregressive integrated moving average, or ARIMA, is a statistical analysis model that uses time-series data to better understand the data set or predict future trends. A statistical model is autoregressive if it predicts future values based on past values. We will be using the `auto_arima` function in Python, which automatically discovers the optimal order for an ARIMA model. The function will automatically determine the parameters `p `, `d `, and `q` of the ARIMA model. The auto. arima() function uses a combination of unit root tests, minimization of the AIC and MLE to obtain an ARIMA model.

#### Key takeaways 
1. Plotting Autocorrelation and Partial Autocorrelation graphs.
2. Difference between Vector Auto Regressive Moving Average models (VARMA) and autoregressive integrated moving average (ARIMA).
3. Importing `auto_arima` function . It automatically determine the parameters `p `, `d `, and `q` of the ARIMA model.
4. SLEX Principal Components Analysis and Differencing.
5. Time series plots and predictions.

#### Article quality
In this tutorial we will build a time seris model that uses Autocorrelation and Partial Autocorrelation plots to better understand the data set and predict future trends. The time series model will predict Forex exchange rates for Euro and US dollar. We will use differencing technique to remove non-stationarity in the data set. We will also discuss how Auto ARIMA works and how it automatically determines the parameters `p `, `d `, and `q`.  Finally we will plot line charts using Plotly Express to visualize the forecast values.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @jamesomina99
