### ISSUE TITLE
Getting started with Unit Testing with Spring Boot

### ISSUE THREAD

**Issue by mussooo** [section-engineering-education/engineering-education#6997]
#### Proposed title of the article
Getting started with Unit Testing with Spring Boot

#### Proposed article introduction
Writing decent unit tests is a skill that takes a long time to perfect. The good news is that the mechanics that support it are simple to grasp.

Unit testing is one of the methods used by developers to ensure that individual units or components function properly.

Before any code is deployed, it is subjected to unit testing to ensure that it fulfills quality standards. This promotes a dependable engineering environment that prioritizes quality.

#### Key takeaways 
At the end of this tutorial the learner will:
1. Learn how to test services
2. Learn how to test repositories
3. Learn how to test controllers
4. Understand the importance of unit testing
5. Define Unit testing.

#### Article quality
With a focus on Spring Boot apps, this tutorial explains these fundamentals and delves into the technical specifics required to construct good unit tests.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @mussooo 
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #6997 via #7350
