### ISSUE TITLE
[Languages]Getting started with Knapsack Problem Python

### ISSUE THREAD

**Issue by EssyH** [section-engineering-education/engineering-education#6998]
### Topic Suggestion
Getting started with Knapsack Problem Python

#### Proposed article introduction
The Knapsack Problem Python is outlined in the following article. Both the problem and the solution are examined using the knapsack problem. We will be provided n items along with their weights and values in this problem. The goal is to select a set of weights that will fill the bag to its maximum capacity. The criteria is that the set we choose must have the most components compared to the other sets, and the overall weight must be less than or equal to the supplied weight. That means the weight must be as light as feasible yet the value must be as high as possible. When programmers must choose from non-divisible items, the Knapsack comes into play.The output will be an integer with the number of items we have chosen in the bag.

#### Key takeaways 
- Problem Approach
- Constraints for Knapsack Problem
- Solving the Knapsack Problem
 - Dynamic Programming
 - Brute Force
 - Greedy Method

#### Article quality
The article is intended to be precise and clear to the point, illustrated by codes making it more practical and interesting, to increase time spent on the page.

#### References
Please list links to any published content/research that you intend to use to support/guide this article

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀 @EssyH
