### ISSUE TITLE
[Security] Generation of invincible password hashes by utilizing CryptoContext  in Passlib python

### ISSUE THREAD

**Issue by MutaCyberSec** [section-engineering-education/engineering-education#7000]
**Proposed article introduction **
 Passlib is a library in python which offers method of hashing text into hash digests using different algorithms. It offers sha_512 which needs more resources to generate strong hashes.
The same password strength can be achieved by combining strong algorithms like sha_265 and argon_2 to produce equally strong hashes or even better ones.
It utilizes multi threading and saving on time and utilizing latest CPU architecture.

Itsdangerous  is used to sign the hashes for a digital signature which ensures that any change  are noticed. 
This ensures safe transit of hashes over a network or computers

**Key Takeaways **
_Faster Hash digest Generation _
_Easy to Check integrity _
_Max security is archived.. At least _

**Comment by ahmadmardeni1** [comment]
Please use the right template. @MutaCyberSec
