### ISSUE TITLE
storing and updating temperature readings for corona fever detection to a database

### ISSUE THREAD

**Issue by ngaremoses** [section-engineering-education/engineering-education#7002]
Topic Suggestion
[networking]storing and updating temperature readings for corona fever detection to a database

Proposed title of article
[networking]storing and updating temperature readings for corona fever detection to a database

 Proposed article introduction
In this article we will learn on how to use the infrared technology used in thermometers to take readings of temperature from people in public and to educe manual work in collecting temperature reading from people every time.Due to the rising cases of corona in the country that are not easy to trace the victims,we should come up with a method of tracking someone's temperature levels every time temperature readings are taken.
This thermometer should be able to take the picture of the person and the readings and send them to the database and also update the readings.The same should also be sent to relevant authorities incase  there is one person whose temperature levels is above normal temperature so that corrective measures should be taken.
The database should update the reading each and every time temperature readings are taken  from an individual.The relevant authorities should also be able to see and extract the records stored in the database. 

Key takeaways 
-An easy way to monitor peoples temperature in public areas.
-Faster relay of information to relevant authorities.
-consistent data of people from the database.

 Article quality
This article aims at giving the learners  the knowledge about the modern corrective measures that can be used to control the spread of corona virus by monitoring the progress of peoples temperature in the public and various areas.Also it equips them with the skills on how to develop automated hospital equipments to helps ease manual work.
References
N/A

**Comment by Kayere** [comment]
Thank you for the topic suggestion @ngaremoses, however, this is a bit outside of our preferred topic areas. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀
