### ISSUE TITLE
 Visualizing sorting algorithm using D3.JS

### ISSUE THREAD

**Issue by gatwirival** [section-engineering-education/engineering-education#7005]
#### Proposed title of the article
 Visualizing sorting algorithm using D3.JS

#### Proposed article introduction

D3.JS is a javascript open-source library used for visualization. D3 is the short form for (data-driven documents). The sorting algorithm is an algorithm used to rearrange a given array according to a comparison operator in an array. The `sort()` method sorts the elements of an array in place and returns the sorted array. 

This article shows how to sort and visualize an algorithm using javascript and D3.js.Visualization enables us to translate data into a visual context making it more understandable. The human brain can easily process visuals instead of long codes to understand the algorithms. There are two types of algorithms in visualization. **Static algorithm visualization**: It shows the algorithm's progress through a series of still images. **Dynamic algorithm visualization**: Algorithm animation that  shows a  continuous movie-like presentation of algorithms operations

#### Key takeaways 
- What is D3.JS?
- What is a sorting algorithm?
- Where to apply a sorting algorithm.
- What is visualization?
- How to Visualize a sorting algorithm.
- How to implement a sorting algorithm.
- How to style your code using CSS.

#### Article quality
The reader will learn how to visualize a sorting algorithm, What is a sorting algorithm, what is D3.JS, and much more.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=Visualizing+sorting+algorithm+using+D3.JS&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
