### ISSUE TITLE
Application of Three Party Game Model in privacy Protection in deep learning.

### ISSUE THREAD

**Issue by OkanyO** [section-engineering-education/engineering-education#7006]
Topic Suggestion

Application of Three Party Game Model in privacy Protection in deep learning.
Proposal Submission

Proposed article introduction

While enjoying the service provided by the platform, privacy leakage incurred by data
submission brings privacy loss to the user. One possible method for this privacy loss could
be due to a malicious attack by an adversary that eavesdrops on the data submitted by
the user. In real-world scenarios, the working efficiency of information retrieval is restricted
by many factors, such as equipment performance and retrieval technique.
A three-party game is designed to capture the complicated interactions among user,
platform, and adversary,  targeting and defending the joint threats from both untrusted
platform and adversary,  

   Key Takeaways

  User Model Design
  Platform Model Design
  Adversary Model Design
  Game model formulation and simulation
 

Article quality

The article is intended to be precise and clear to the point, illustrated by codes making it more practical and interesting, to increase time spent on the page.

References
N/A

Please list links to any published content/research that you intend to use to support/guide this article
Templates to use as guides

    How To Guide Template
    Software Review Template
    Tutorial Template

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@OkanyO 

👋  Thank you for submitting an article suggestion, based on the content provided, it seems that there may be some significant readability challenges in your description that raise concerns over how much review/editing would be required from our peer review team. After reading the description and title I have no real idea what the article is about.

We don't provide editing services and recommend that students leverage online editing services (there are both free and paid services that you can explore), or try engaging with the community or other peers in your network to have them review prior to submitting a revised proposal. 

Thank you.
