### ISSUE TITLE
Generating Random Datasets with Trumania

### ISSUE THREAD

**Issue by kymomolly** [section-engineering-education/engineering-education#7022]
#### Proposed title of article
Generating Random Datasets with Trumania
#### Proposed article introduction
This article will instill the need as to why you might want to generate random datasets and what to expect from them. It will also describe how to use Trumania, a data generation Python library. Generating random dataset is relevant both for data engineers and data scientists.
#### Key takeaways
1.Why generate random datasets  
2. Schema-Based Random Data Generation
3. Generating Inter-related Data with Trumania
4. Creating a Trumania Circus
#### Article quality
The article is of importance as it will provide the reader with expound  understanding on how to use trumania  to generate random datasets. Every step and point will be described in detail to give the needed knowledge and understanding.
#### References
N/A

**Comment by kymomolly** [comment]
@hectorkambow, can this topic be reviewed please.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @kymomolly 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
