### ISSUE TITLE
Web3js vs EthersJS

### ISSUE THREAD

**Issue by TheGhoulRe** [section-engineering-education/engineering-education#7023]
### Topic Suggestion
Web3js vs EthersJS

### Writing sample(s): 
https://dev.to/ghoulkingr/simple-ways-to-compile-and-deploy-solidity-contracts-3kpb

#### Proposed title of article
Web3 vs Ethers

Use keyword research to improve your article's SEO.

#### Key takeaways 
* The readers will be able to tell the strengths and weaknesses of the modules
*  They will be able to know  the scenario where one is most applicable is most applicable
* They'll understand why the both of them exists

#### Article quality
This article helps the readers distinguish between the Web3js and the EthersJS module. In this article the readers will be given a clear understanding of the concepts that the two modules entail and they'll be able to understand why the both of them even exists

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @TheGhoulRe
