### ISSUE TITLE
[Blockchain] Understanding the downsides of smart contracts in blockchain

### ISSUE THREAD

**Issue by ogoti-lilian** [section-engineering-education/engineering-education#7028]
#### Proposed title of the article
Understanding the downsides of smart contracts in blockchain

#### Proposed article introduction
In the blockchain, cryptocurrency is the most popular concept discussed worldwide. However, the smart contracts concept is gradually catching up with the pace in this digital economy. 
The benefits offered by smart contracts are seen to cut across different industries such as insurance, supply chains, and healthcare.  But, the main question remains whether smart contracts are really what are presumed to be?
There is no doubt that smart contracts will be useful in the near future. However, it is better to separate the truth from the hype. 

In an attempt to understand the applications and limitations of smart contracts, it is evident that the technology has a lot of potentials. However, there are still technological and legal factors limiting its successful implementation.
In this proposed article, we will broadly cover the downsides associated with smart contracts.

#### Key takeaways 
At the end of the proposed article, the reader will understand:
- the concept of smart contracts in blockchains.
- how smart contracts work in real-world applications.
- why smart contracts are popularly used.
- the downsides associated with smart contracts.

#### Article quality
Unlike most published articles found on the blog sites, the explanation of each concept of smart contracts in blockchains will be broadly supported by real-life examples. The first-time readers will find the proposed article to be easy to understand and grasp the concepts explained.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved @ogoti-lilian
