### ISSUE TITLE
[Security] Chaos theory and its potential for cryptography

### ISSUE THREAD

**Issue by pop-ecx** [section-engineering-education/engineering-education#7032]
### Topic Suggestion
[Security] Chaos theory and its potential for cryptography

#### Proposed title of article
Chaos theory and its potential for cryptography 

#### Proposed article introduction
Chaos theory is a branch of mathematics that deals with the study of non-linear dynamic systems that exhibit sensitivity to initial conditions. Chaotic conditions exist in nature. A decent and typical example of such is the weather. Since its inception, chaos theory has had numerous applications in various fields such as meteorology, anthropology economics, computer science among others. Chaotic systems can be characterized by: sensitivity to initial conditions, periodic orbit density and topological mixing. It is attributes such as determinism and sensitivity that make chaotic systems attractive for cryptography.

#### Key takeaways 
The reader should be able to understand:
- The characteristics of chaotic systems that make it suitable for cryptography.
- Proposed chaos cryptographic primitives and other applications.
- Practical problems of the proposed primitives.
- Possible solutions.

#### Article quality
This article will introduce the reader to a different approach to cryptography in a simplistic, palatable way.

#### References
[Implementations and practical problems of chaos based cryptography revisited]  (https://www.sciencedirect.com/science/article/abs/pii/S2214212619306544)

**Comment by hectorkambow** [comment]
@lalith1403  @ahmadmardeni1 

Any thoughts on this one 👀
