### ISSUE TITLE
Storing Custom Types with Custom TypeConverter in Room Database

### ISSUE THREAD

**Issue by feswalsalim** [section-engineering-education/engineering-education#7033]
#### Proposed article introduction
Sometimes, you need your app to store a custom data type such as Date, Bitmap, etc. in a single database column. You support complex types by providing type converters, which are methods that tell Room how to convert complex types to and from known types that Room can persist. You can identify type converters by using the @TypeConverter annotation.

But sometimes this normal  `TypeConverter` isn't enough. Imagine a scenario where you need to store a `List` of Objects e.g Users, Cars, e.t.c. This requires you to come up with a way that you can convert your Data Type to something that `Room` can understand i.e. maybe that `List` of `Objects` to `String`.

In this tutorial, we will create a custom `TypeConverter` and use it in the Room database.

#### Key takeaways 
- What is a TypeConverter?
- What are the complex types in the Room database
- How to create and use a custom TypeConverter in Room database

#### Article quality
This tutorial will help the reader come up with a custom code that he/she doesn't have to write every time when trying to store complex types in database in their Android apps. The tutorial will be short and direct to the point. Most of the blog sites have not covered this topic.

#### References
- N/A

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
