### ISSUE TITLE
[Language] Getting Started with Object Oriented in C#

### ISSUE THREAD

**Issue by joylinecherotich** [section-engineering-education/engineering-education#7039]
#### Proposed article introduction
 The object-oriented programming (OOP)  paradigm divides data into objects (data fields) and uses classes to describe the contents and behavior of those objects (methods). It allows objects to communicate with one another by establishing relationships between them.
We'll learn how to define our own types using classes and structs, as well as how to use them in our programs, in this article. We'll look at how to make objects out of classes. We'll also look at how classes and objects may be used to model real-world objects and how they can make building programs to solve complicated problems easier.

#### Key takeaways 

-Learn what a class is and how to construct one in C#.
- Declaring a Class.
-Understand the three concepts of OOP in C# that is encapsulation, inheritance, polymorphism, and how they are applied in programming.
- Using Methods and Access Modifiers.
- Learning about Structs.

#### Article quality
This article will help novices understand why we favor object-oriented programming over procedural programming, as well as the four fundamental ideas of C# OOPs: abstraction, encapsulation, inheritance, and polymorphism, through practical demonstrations. I'll also go through the benefits of each of the four object-oriented programming ideas in depth.

#### References
N/A

**Comment by WanjaMIKE** [comment]
This topic appears a bit oversaturated on other blogs and official docs. Feel free to suggest another topic. Thanks
