### ISSUE TITLE
How to Build an OTP Generator service App using Node.js and React.js

### ISSUE THREAD

**Issue by Rose-stack** [section-engineering-education/engineering-education#7049]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction

An OTP generator is a simple one-time password generator and can be used as a password generator. OTP is a password that is valid for only one login session or transaction on a computer system or other digital device. The use of OTP helps to avoid many disadvantages that are associated with traditional (static) password-based authentication. In simple terms, a service accepting OTPs requires a user to select a preferred OTP generator to deliver this dynamic password.

In this guide, the reader will learn how to set them using a React.js application. The reader will first create a Node.js Restful API that connects to the Twillio API. Then create a React app that Sends authentication SMS messages. This SMS will be used to Handle authentication inside the  React.js application.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- Introduction
- Prerequisites
- Set a React.js application
- Create a client React.js OTP components
- Build a Node.js OTP RESTFUL API
- Connect a React.js client and a Node.js RESTFUL API backend
- Handle authentication using OTP
- Send authentication SMS messages using Twillio API

#### Article quality

Most tutorials only explain the creating of OTP  services using backend such as Node.js. This guide aims to create a full-fledge full-stack application that connects to an OTP API, allowing the frontend to handle all the user interaction to the set API while still performing the OTP operations.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Thank you for submitting your topic @Rose-stack.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
