### ISSUE TITLE
[Blockchain] Can multi-chain DeFi protocols replace legacy finance?

### ISSUE THREAD

**Issue by kerubo-tech** [section-engineering-education/engineering-education#7050]
#### Proposed title of article
Can multi-chain DeFi protocols replace legacy finance?

#### Proposed article introduction
Decentralized finance (DeFi) provided the way of developing secure, transparent, ultra-inclusive financial services platforms. The growth, innovation, and adoption of the DeFi protocols have triggered the discussion of whether the protocols should be enabled for cross-chain communication.
The choice of DeFi protocols design is important to ensure that the DeFi revolution of the finance sector solves the problems faced by legacy finances they seek to replace. Hence posing the danger of an isolated system. Despite this, chain-to-chain interactions in the DeFi network are one of the less prioritized areas in the DeFi ecosystem.
The proposed article will look at the reasons why/why not multi-channel protocols may/may not replace legacy traditional finance.

#### Key takeaways 
At the end of the article the learner will be able to understand:
- where the legacy finance failed
- the reasons why existing DeFi chains cannot yet replace traditional finance
- the challenges faced by DeFi network
- the future of cross-chain protocols

#### Article quality
The article will highlight the concepts using practical examples of the experiences faced by the blockchains that implemented the protocols to make it easy for the learner to understand.

#### References
N/A

**Comment by Kayere** [comment]
Good topic @kerubo-tech - approved. Please make sure your article is unique and adds value to what is available online.

**Comment by WanjaMIKE** [comment]
Closed #7050 via #7352
