### ISSUE TITLE
[Languages] Five Different Types of Inheritance and Polymorphism with Java OOP

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#7052]
### Introduction
Every Objected Oriented Programmin, OOP languages has both the inherintance and polymorphism unique properties. Adequate knowledge of these are solemnly required in order to be  good in any of the languages. In this tutorial, readers will walk through the implementations, and the five distinct types of these properties.

### keytakeaways
- What is Inheritance in OOP language?
-  Examples and types of it.
- How polymorphism  works in OOP.
-  How compile and runtime polymorhism work.
- The different types of the polymorphism.
- Demo of a well-defined class with the properties learned.

### Article Quality
Readers will learn the whole overview of these properties and their types. They will also get to enjoy the demo instances in the  tutorial.

### References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @Horlawhumy-dev.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.

**Comment by Horlawhumy-dev** [comment]
@Kayere sir, thank you for reviewing this. Actually, I am willing to make this unique from any article out there. Can you please review my next issue, sir?
