### ISSUE TITLE
Getting started with firebase cloud messaging using OneSignal in Android Studio

### ISSUE THREAD

**Issue by carolinenji** [section-engineering-education/engineering-education#7053]
### Topic Suggestion
Getting started with firebase cloud messaging using OneSignal in Android Studio

#### Proposed article introduction
Cloud messaging has become a major form of communication in the current world. They are used to notify on a particular issue may be about app advancement or otherwise. It has become a major challenge for developers to communicate with the application users more so if the number of users is extremely large. One signal tries to build the gap of sending personalized notifications to users instead of sending every notification to every user which is sometimes annoying to receive an irrelevant notification.

In this tutorial, we will discuss how you can implement Onesignal in the android studio and push personalized notifications to users who have installed the application.

#### Key takeaways 
- Creating a new android project
- Adding relevant dependencies
- Working with the manifest file
- Integrating our app with firebase
- Getting started with one signal
- Working with MainActivity file
- Testing our application
- Conclusion

#### Article quality
This article will be beginner-friendly with precise and informative steps on how to go along and achieve our objective of pushing notifications to android apps which are discussed in a complex mode in other blogs. 

#### References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @carolinenji.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
