### ISSUE TITLE
 Understanding Lambda in Java

### ISSUE THREAD

**Issue by mosesmoses12** [section-engineering-education/engineering-education#7056]
#### Proposed title of article
 Understanding Lambda in Java
#### Proposed article introduction
Lambda Expressions were introduced in Java 8 in 2014 to allow developers to use functional programming techniques in Java. They are a powerful tool for writing concise and readable code.

A `Lambda`  is a small piece of code that takes in input and outputs a value. They are similar to methods, except they don't require a name and can be used directly within a method's body.

Java lambda enables easy use of APIs and Libraries. An API designed using java lambda can be easier to use and support other APIs.  

#### Key takeaways 
1. Anonymous Inner classes
2. Composing Functions
3. Combining Predicate
4. The BinaryOperator Interface
5. Create an API using lambda

#### Article quality
This article is unique in that it explains the Java Lambda in detail making it friendly to all developers, unlike other published articles which are not well understood.

#### References
N/A

**Comment by Kayere** [comment]
Thank you for submitting your topic @mosesmoses12.

However, after some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

Please feel free to suggest an alternative topic.
