### ISSUE TITLE
Use pandas dataframe to transform a column type into a datetime mode from string format

### ISSUE THREAD

**Issue by Joshuathuo** [section-engineering-education/engineering-education#7057]
#### Proposed title of article
Use pandas dataframe to transform a column type into a datetime mode from string format

#### Proposed article introduction
When working with data in Python's Pandas DataFrame, we frequently come across time series data. Panday is a powerful Python utility for handling time-series data, and in the supplied dataset, we may need to convert the text to Datetime format.

In this article, we'll learn how to convert a text DataFrame column to the dd/mm/yy datetime format. If the dates are not in the correct format, the user will be unable to perform any time-series operations on them. We must transform the dates into the required date-time format to cope with this.
#### Key takeaways 
1. How to implement the DataFrame.astype() Function
2.  How to convert multiple columns from "string" to "datetime" format.
3.  Implementing pandas.to_datetime() Function

#### Article quality
The quality of the content in this article will be of good quality and of benefit to our learners.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation. @Joshuathuo 

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
