### ISSUE TITLE
[Networking]Understanding IPSec

### ISSUE THREAD

**Issue by kvardhan10** [section-engineering-education/engineering-education#7058]
#### Proposed title of article
Understanding IPSec

#### Proposed article introduction
Internet is a vast place with numerous facilities available for the users to rely on. Communication is one such important facility. When two or more internet-connected devices communicate with each other for the transmission of resources and data, they form a network. As remarkable as it appears, sending or receiving anything over this huge network might be rather risky.
 
It is crucial to ensure that both the sender and the receiver are trustworthy because the information being transmitted may be sensitive and should not be publicly disclosed, mandating encryption. It should also be remembered that, just as sensitive information should not be sent, malicious information should not be received as well. Even if such measures are undertaken, it is important to guarantee that no third party interferes or tampers with the connection. To prevent data from being leaked and misused for illicit reasons by the third party, the connection must be secured. This is where IPSec plays its role. 
 
As the name implies, IPSEC (or IP Security) secures the internet protocol suite and establishes secure connections between network users while authenticating them. It also encrypts data to prevent unauthorized access to the data and can only be decrypted using the shared keys by the sender and receiver during a session.

#### Key takeaways 
The readers will learn about:
- IPSec
- Components of IPSec
- Introduction to cryptography
- IPSec cryptographic algorithms
- Why IPSec is needed

#### Article quality 
Other resources available are slightly more technical, making it difficult for beginners to get started with the topic. This may make it easier for them to understand the underlying terms, after which they can move on to the intermediate concepts related to IPSEC.

#### References
https://en.wikipedia.org/wiki/IPsec
https://www.techtarget.com/searchsecurity/definition/IPsec-Internet-Protocol-Security

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @kvardhan10 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
