### ISSUE TITLE
Store legacy data records from your old PC into a blockchain

### ISSUE THREAD

**Issue by KanizoRGB** [section-engineering-education/engineering-education#7059]
### Topic Suggestion
Store legacy data records from your old PC into a blockchain

### Writing sample(s): 

1. https://www.section.io/engineering-education/the-complete-roadmap-to-blockchain-development/
2. https://www.section.io/engineering-education/an-introduction-to-machine-learning-using-c++/

#### Proposed title of article
[Blockchain]Store legacy data records from your old PC into a blockchain

#### Proposed article introduction
The emergence of Web 3.0 has led to the popularity of a technology known as the blockchain. The blockchain has spurred the interest of many and is continually being understood by the public each day. Blockchain has undoubtedly numerous benefits concerning the storage of data. Some of the benefits include ensuring transparency of the data, decentralization, and ensuring security. Every industry is finding new ways of integrating blockchain technologies into their mode of operation more to take advantage of the benefits that come along with it.
In case you are wondering how you may take advantage of this change you are in the right place. As a take-off point, we will look from a developer's point of view, at the steps, you would take to store valuable data from your old PC into a blockchain whether public or private. This is the kind of data you would not want to be tampered with. Afterward, you are free to go out there and explore other ways that you make take advantage of blockchain technology. 

#### Key takeaways 
1. The reader will understand the definition of some terms used while talking about blockchain technology.
3. The reader will understand the importance of storing data in a blockchain.
4. The reader will learn of some creative ways to overcome the size limit of data that can be stored in some blockchain protocols
5. The reader will get to know the cost of storing data on the blockchain
6. The reader will also learn of some issues that arise when storing data on a blockchain.

#### Article quality
My article is unique in the sense that there is no article out there that gives a breakdown of the process that you would take to store data into a blockchain. I follow an anecdotal and creative approach in doing all this. The reader should find this eye-opening and fun to follow along.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @KanizoRGB 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by KanizoRGB** [comment]
Thank you. Doing some polish on the PR
