### ISSUE TITLE
Design and comparative performance analysis of P, I, D, PI, PD, and PID controllers in Matlab

### ISSUE THREAD

**Issue by queenterbruce063** [section-engineering-education/engineering-education#7062]
### Topic Suggestion
Design and comparative performance analysis of P, I, D, PI, PD, and PID controllers in Matlab

### Writing sample(s): 
https://www.section.io/engineering-education/implementation-of-convolution-integral-of-continuous-time-linear-time-invariant-systems-in-matlab/

####Design and comparative performance analysis of P, I, D, PI, PD, and PID controllers in Matlab

#### Proposed article introduction
Design and comparative analysis involve the construction of various controllers. These controllers are then analyzed deeply to get the difference depending on their properties. These properties are analyzed to see their merits and demerits. Also, we analyze their performance to get their efficiency.
This tutorial covers the different types of continuous controllers such as Proportional (P), Integral (I), Derivative (D), Proportional + Integral (PI), Proportional + Derivative (PD) and Proportional + Integral + Derivative (PID), which are explained with their brief theory and properties. 
Their performances are compared with each other highlighting their advantages and disadvantages. The MATLAB implementation is also given for all these controllers.

#### Key takeaways 
- Why need Controllers? 
- Types of Basic Controllers (P, I and D Controllers) and their properties.
- Controller combinations (PI, PD and PID Controllers) and their properties.
- Controller Design in MATLAB.
- MATLAB code for design and implementing PI, PD and PID Controllers.
- Comparative performance analysis of PI, PD and PID Controllers.

#### Article quality
This article explains the theory, and how to design these controllers in matlab. Also it compares their perfomance to give their efficiency.

**Comment by ahmadmardeni1** [comment]
Can you take a look, please? @lalith1403

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved. @queenterbruce063

**Comment by lalith1403** [comment]
I hope it is different from this article https://in.mathworks.com/help/control/getstart/designing-pid-controllers-with-the-pid-tuner-gui.html

**Comment by queenterbruce063** [comment]
@lalith1403 Yeah it is different from that. Here, we don't use any toolbox for the design and the performance analysis.

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
