### ISSUE TITLE
[Machine Learning] Image Colorization using AI and Python

### ISSUE THREAD

**Issue by smkinyan** [section-engineering-education/engineering-education#7065]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Image Colorization using AI and Python

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

 DeOldify is a Deep Learning (DL) based project for colorizing and restoring old images and video. It helps us add color old black and white photos adding life into them. The DL model uses a unique NoGAN architecture to train the model. We will use this model to convert some old black and white photos of a city adding color to them.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to:
- Learn about the Deoldify model and its architecture.
- Install the necessary dependencies.
- Clone the GitHub Repo for the model.
- Download the model.
- Perform colorization on old black and white photos 

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

DeOldify is a model that hasn't been around a long time. Not many tutorials exist on the web regarding the subject. With only a few lines of code, I will show our readers how they can use the model in their projects in the simplest way possible.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [DeOldify: A Deep Learning based project for colorizing and restoring old images](https://github.com/jantic/DeOldify)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @smkinyan 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
