### ISSUE TITLE
[Edge Computing] Using edge computing to handle content migration

### ISSUE THREAD

**Issue by ephnjor2021** [section-engineering-education/engineering-education#7072]
#### Proposed title of article
Using edge computing to handle content migration

#### Proposed article introduction
Content migration involves moving of one content from one content management system to another. The process at times sounds simple and straightforward, but it usually reveals areas of improvement in the site architecture, the design, and the content itself. In case any of these happens the migration process shifts from just 'lift and shift' to reorganizing and redesigning the architecture or content.

A typical migration involves the redesign of information architecture, page, content audit, new taxonomy, or even rewriting content. Sometimes migration may involve switching from one URL to another which poses a number of challenges. Most of these challenges can be solved using edge computing as it will be covered in the proposed article.

#### Key takeaways 
At the end of the article the reader will understand:
- the concept of edge computing and content migration
- the strategies followed for a successful content migration
- the issues associated with content migration and how edge computing offers solutions to each of them

#### Article quality
The article is useful to the entities preparing to perform a successful content migration as it uses a practical approach to possible issues that can arise and be handled using edge computing.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Closed #7072 via #7494
