### ISSUE TITLE
Exception Handling in Java Vs Kotlin

### ISSUE THREAD

**Issue by apondi-911** [section-engineering-education/engineering-education#7074]
#### Proposed title of article
[Languages] Exception Handling in Java Vs Kotlin

#### Proposed article introduction
An exception is an occurrence that causes the program's normal flow to be disrupted. It's a type of object that's thrown at runtime. Exception handling instead is a way of coping with runtime failures while keeping the application's usual flow intact.

Java and Kotlin programming languages implement the use of exception handling mechanisms to resolve runtime errors but there's a difference in how these two languages apply the exceptions. Java has got three types of exceptions Checked, Unchecked, and error exceptions whereas Kotlin use Unchecked exceptions only.

The learner will get to learn about the difference between checked and unchecked exceptions in Java and understand the reason why Kotlin does not use Checked exceptions and the importance of exception handling.

#### Key takeaways 

- What is exception handling?
- Types of Exception handling used in Java and Kotlin
- Why Kotlin does not Implement Checked Exception
- Importance of Exception handling
- Common examples of Exception Handling

#### References
N/A

**Comment by WanjaMIKE** [comment]
This topic appears a bit oversaturated on other blogs and official docs. Feel free to suggest another topic. Thanks
