### ISSUE TITLE
[Android]  Image Loading with ION As an Alternative for Glide

### ISSUE THREAD

**Issue by tanscy-cassie** [section-engineering-education/engineering-education#7075]
### Writing sample(s): 
https://www.section.io/engineering-education/permission-handling-in-jetpack-compose/
https://www.section.io/engineering-education/side-effects-and-effects-handling-in-jetpack-compose/

#### Proposed title of article
Image Loading with ION As an Alternative for Glide

#### Proposed article introduction
Android Asynchronous Networking and Image Loading with ION. Just like other existing libraries such as Glide and Picasso, you can always go for Ion for loading images asynchronously from an API or Firebase. This API is easy to implement and use making it more effective. With it, you can do HTTP POST and GET of JSON objects, cancel requests or perform Grouping.  

ION is more full of features that Glide or Picasso has. Using it will reduce adding a lot more libraries into your app which will make it larger in space taken on the phone.  

#### Key takeaways 
- Understanding ION and comparison with Glide
- Loading Images and JSON objects with ION
- Grouping requests
- Cancelling request
- Logging data with ION

#### Article quality
This article will illustrate on how to use this library through construction of an app that will be simple and clear for everyone to follow along.

#### References
- Dutta's Documentation on ION

**Comment by tanscy-cassie** [comment]
@LinusMuema Can i proceed with the article?

**Comment by LinusMuema** [comment]
Hi @tanscy-cassie 
Sorry for the late reply.

Regarding your article, how different would it be compared to the official docs. I can see the docs have examples for all of the use cases you have mentioned.

**Comment by tanscy-cassie** [comment]
@LinusMuema @ahmadmardeni1 @lalith1403 @louisefindlay23 My article will look into much depth at the uses-cases with good examples illustrating how to use the library in your app. This will also be more understandable than going through the whole documentation. It will be perfect for beginners and also any other developers looking to use this library.

**Comment by hectorkambow** [comment]
@tanscy-cassie 

We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
