### ISSUE TITLE
Build a simple e-commerce web application using Commerce.js and React js

### ISSUE THREAD

**Issue by IreneRaro** [section-engineering-education/engineering-education#7082]
### Topic Suggestion
Build a simple e-commerce web application using Commerce.js and React js

#### Proposed article introduction
Commercejs is an API that enables developers to integrate API-driven commerce into a web or mobile project. With this API, an e-commerce system that a developer usually builds in months will be built in days.

In this blog, we will build a simple web application such that items will be displayed with their prices and an icon to enable the customer/buyer to add items to a chart. Once on the chart, the total cost will be calculated, and items can be removed from the chart or the empty chart. Activities such as removing, adding, and emptying will be possible because of chart.js.

#### Key takeaways 
- Create a free Chec account and setup everything
    - uploading products
- Create a React app
- Install dependencies 
- Learn how to work with commerce.js
- Learn how to use chart.js
- Learn how to sytle using material UI

#### Article quality  
The blog will be beginner-friendly and simplified, enabling developers to integrate commerceJS into their web applications.

#### References
N/A

**Comment by hectorkambow** [comment]
@IreneRaro 
We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
