### ISSUE TITLE
How to make an audiobook reader using JavaScript

### ISSUE THREAD

**Issue by anubhavb11** [section-engineering-education/engineering-education#7091]
### Topic Suggestion
How to make an audiobook reader using JavaScript

#### Proposed article introduction
This article will teach how to make an audio book reader.
This will be a javascript, script when you run it your webcam turns on, then the text visible on your webcam is converted to text and read by the computer. 
I will explain how to create this script 

#### Key takeaways 
* learn about javascript 
* learn about [tesseract.js](https://github.com/naptha/tesseract.js)
* Basics of HTML 

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.

**Comment by hectorkambow** [comment]
@anubhavb11 
We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
