### ISSUE TITLE
Formulating an Information Based Using Prolog

### ISSUE THREAD

**Issue by lizpart** [section-engineering-education/engineering-education#7098]
#### Proposed title of article

Formulating an Information-Based Using Prolog

#### Proposed article introduction

Prolog or PROgramming in LOGics is a logical and declarative programming language used to create artificial intelligence.
In Prolog, we need not mention the way how one problem can be solved, we just need to mention what the problem is
so that Prolog automatically solves it.
You need to formulate your KB so that the questions can be answered correctly, but you must abide by the following
rules:
• Your KB must not contain any fact that is just an instance of one of the questions.
• Each question must require at least two rule firings (resolution steps).
• Background knowledge must be in terms of general categories which contain the individuals.
• Your background knowledge need not be strictly true, but generally reasonable and appropriate for answering
the questions.
In this tutorial, we will be covering the key components of working with the Knowledge-Based. Tools to be used are SWI-prolog and an editor.

#### Key takeaways 
- Creation of facts.
- Creation of rules to be used.
- Query implementation and execution.
- Understanding relations in prolog.

#### Article quality
 This article is designed in an eccentric way for easier understanding and consumption for a beginner and above. It covers extensive details on the knowledge-oriented paradigm also to mention.

#### References
N/A

**Comment by lalith1403** [comment]
Too many grammatical errors in the topic suggestion. Please submit a new issue. Thank you.
