### ISSUE TITLE
[APIs]Consuming the Jenga Banking API using Django

### ISSUE THREAD

**Issue by munubi254** [section-engineering-education/engineering-education#7111]
### Writing sample(s): 
[My samples](https://www.section.io/engineering-education/authors/sandra-moringa/).

#### Proposed title of article
Consuming the Jenga Banking API using Django

#### Proposed article introduction
Jenga API is an API created by Equity Bank(Kenya) ICT team to allow developers to integrate payment in the projects they are working on. It supports several languages e.g Java, Python, PHP, etc. Since Equity Bank is multinational, it is of much importance to learn how to use the API. We will use Django for that.

#### Key takeaways 
- Accessing Jenga API
- Processing the API's responses using Django
- Using Django ORM to save the responses 

#### Article quality
It is easy to follow through, and the API is not much explored.

#### References
Jenga API's [official documentation](https://www.jengaapi.io/).

**Comment by lalith1403** [comment]
Thank you for the topic suggestion, however this is a bit outside of our preferred topic areas. 
We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀

**Comment by munubi254** [comment]
@lalith1403, how is it not programmer-centric? It's the same as this Eng-Ed [here](https://www.section.io/engineering-education/consuming-co-operative-bank-api-using-nodejs/).

**Comment by hectorkambow** [comment]
@lalith1403 did you mean the topic may be written about on other sites 🤔

**Comment by lalith1403** [comment]
The banking API used in this article is a third party app, and therefore, their documentation covers the first 2 points, I believe. 

Hence, I thought it was outside the scope of our covered areas.
