### ISSUE TITLE
[JavaScript] How to build a rich text editor with Vue.js and TipTap

### ISSUE THREAD

**Issue by Morgenstern2573** [section-engineering-education/engineering-education#7119]
#### Proposed title of article
How to build a rich text editor with Vue.js and TipTap

#### Proposed article introduction
A rich text editor is a necessary feature for all web applications that receive user input that require a degree of formatting:
profile bios, lengthy reviews, or even blog posts.

But that raises the question: how do we build one? It seems like a daunting task, and it would be if we had to do it from scratch. 

Thankfully, TipTap solves this problem for us. TipTap is a free, open-source JavaScript library that allows us to create custom rich text editors for our needs.

This article will guide the reader through the process of using TipTap to quickly implement a rich text editor in their Vue.js application.
  
#### Key takeaways 
At the end of the article, the reader will understand:
* What TipTap is
* Why they should use TipTap
* How to construct a Vue.js TipTap editor
* How to obtain the output of the editor in a format of their choice

#### Article quality
TipTap is not an obscure library, but it isn't extremely popular, so there aren't many articles about it yet. The official TipTap documentation is high quality but doesn't recommend a fixed path to implement it (by design).

This article will provide the reader with a much quicker and more straightforward path to get up and running with TipTap as soon as possible.

#### References
[Official TipTap documentation](https://tiptap.dev/introduction)

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
