### ISSUE TITLE
[Languages]Introduction to asynchronous programming, why and when to use it. 

### ISSUE THREAD

**Issue by CT2034-hash** [section-engineering-education/engineering-education#7121]
#### Proposed title of article
[Languages]Introduction to asynchronous programming, why and when to use it. 

#### Proposed article introduction

Asynchronous programming is a programming approach that allows your software to start a potentially long-running activity and then respond to other events while the work is running, rather than having to wait for it to finish. The result is delivered to your software once the process is completed.

In this article, we'll go over what asynchronous programming is, why it's important, how asynchronous functions have been implemented in different programming languages in the past. Also the way it is implemented in our daily lives through APIS

#### Key takeaways 

 *How to use asynchronous programming.
 *understand why asynchronous programming is important.
 *Learn why it is different from synchronous programming

#### References
N/A

**Comment by WanjaMIKE** [comment]
This topic appears a bit oversaturated on other blogs and official docs. Feel free to suggest another topic. Thanks
