### ISSUE TITLE
[Android]Getting started with  Navigation Drawer with Fragments in java 

### ISSUE THREAD

**Issue by mikemore32** [section-engineering-education/engineering-education#7122]
### Topic Suggestion
Getting started with  Navigation Drawer with Fragments and implementing menu and activity 

#### Proposed title of article
Getting started with  Navigation Drawer with Fragments and implementing menu and activity 

#### Proposed article introduction
 we are going to build a navigation drawer from scratch. When we click any of the menu items in our navigation drawer, we will switch between different fragments or trigger another action.
we will add the dependency for the design support library and create the vector icons, as well as the menu xml file with a menu group and multiple menu items, which each have an id, a title and an icon set to them. We will also prepare our activity theme by removing the action bar with the windowActionBar and windowNoTitle attributes, so we can later add a toolbar instead.

#### Key takeaways 
1. Build a navigation drawer
2.  menu items in our navigation drawer
3. Creating menu resource files by Menu resource file

#### Article quality
The article is going to give a clear guideline for implementing navigation drawer to beginner  

#### References
N/A

**Comment by WanjaMIKE** [comment]
There is a template for creating this type of app or functionality in Android Studio. Isnt this topic absolute?

**Comment by mikemore32** [comment]
@WanjaMIKE This article isn't absolute because it  will give a clear guideline step by step to implement the navigation drawer in android by allowing one to switch  between different fragments or trigger another action will also cover adding the dependency for the design support library and create the vector icons

**Comment by hectorkambow** [comment]
👀  

Lets try to make it more unique - go beyond what is in the dos.

Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved


https://www.google.com/search?q=Getting+started+with+Navigation+Drawer+with+Fragments+in+java&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8

**Comment by hectorkambow** [comment]
@mikemore32 
Closing for now - can be re-opened (or resubmitted) if you decide to add more to your EngEd profile. 

If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.
