### ISSUE TITLE
[Machine Learning] Explaining and Interpreting NLP models using LIME

### ISSUE THREAD

**Issue by willyngashu** [section-engineering-education/engineering-education#7130]
#### Proposed title of article
Machine Learning] Explaining and Interpreting NLP models using LIME

#### Proposed article introduction
Model explanation allows human users to comprehend and trust the results and output created by machine learning algorithms. Model interpretation finds out why a model makes certain decisions during the prediction phase. This ensures we have a fair, accountable, and transparent model.

In model interpretation, we try to answer the question; why should we trust the model? Why did the model make this conclusion?

LIME is used to describe a model, its expected impact and potential biases. It helps characterize model accuracy, fairness, transparency and outcomes in AI-powered decision making. It is crucial for an organization in building trust and confidence when putting models into production. Model explainability also helps an organization adopt a responsible approach to develop models.

LIME has a set of tools and frameworks to help you understand and interpret predictions made by your machine learning models. Understanding how an AI-enabled system has led to a specific output. Explainability help developers ensure that the system is working as expected, it might be necessary to meet regulatory standards.

LIME contrasts with the concept of the black box in machine learning where even its designers cannot explain why an AI arrived at a specific decision. Model explanation will determine the logical reasoning of the model when making a prediction and explains the decisions made by the model.
 
#### Key takeaways
1. Importance of model interpretation
2. Model interpretation methods and techniques
3. Building a text classification model using LogisticRegression
4. Textual data interpretation technique.
5. LIME explainer function

#### Article quality
This article is unique because it will enable us to build a full transparent model. It is crucial for an organization to have a full understanding of the decision-making processes with model monitoring and accountability. It also enable stake holders not to trust them blindly. Using the LIME functions and methods, users will be able to understand and explain machine learning (ML) algorithms, deep learning and neural networks. This tutorial will use step-by-step guide of how to explain and Interpret a text classification model. So that we can have full transparency and accountability. We will also be able to showi the explainer results using LIME explainer function.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 


We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=NLP+models+using+LIME&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
