### ISSUE TITLE
highway automated traffic driver authentication using smart cameras

### ISSUE THREAD

**Issue by ngaremoses** [section-engineering-education/engineering-education#7131]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

Topic Suggestion

highway automated traffic driver authentication using smart cameras
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

Proposed title of article

highway automated traffic driver authentication control 

Proposed article introduction
this article is intended to equip learners with the knowledge on how to curb unauthorised drivers from driving on highways .This are the most causes of accidents  and careless driving on major highway roads.
Through this system ,the system will only allow a driver to enter the highway roads only after he or she has been face scanned .This is the time when the entrance to the road is granted.if driver is unauthorised access is denied and the system reports to the authorities by sending avoice message including the number plate of the vehicle for proper procedures t be followed

 Key takeaways 
-The system should be able to give and deny access appropriately
-This system will help the plaw enforcement urgencies to control road traffic effectively.
-Learners be able to get knowledge on  traffic technology
 Article quality
This article is best suited to equip and expand the knowledge of learners interested  in technology advancement to come up with new ideas and expand the already developed systems.
 References
N/A

**Comment by ngaremoses** [comment]
it is a good topic that is addressing the issue of traffic control that will employ a high level of integrity in traffic and driver control from breaking traffic rules

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may a bit out of our wheelhouse. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

We typically refrain from publishing content that is is not practitioner-focused content/programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀
