### ISSUE TITLE
Data visualization using  matplotlib in Python

### ISSUE THREAD

**Issue by duncandegwa** [section-engineering-education/engineering-education#7132]
### Writing sample(s): 
https://www.section.io/engineering-education/visualizing-repositories-using-pygal/

### Topic Suggestion
Data visualization using matplotlib in Python

#### Proposed article introduction
Data visualization involves exploring data through visual representations. It's closely associated with data mining, which uses code to explore the patterns and connections in a data set. A data set can be just a small list of numbers that fits in one line of code or many gigabytes of data. Making beautiful representations of data is about more than pretty pictures. When you have a simple, visually appealing representation of a data set, its meaning becomes clear to viewers. People will see patterns and significance in your data sets that they never knew existed. Fortunately, you don't need a supercomputer to visualize complex data. With Python's efficiency, you can quickly explore data sets made of millions of individual data points on just a laptop. The data points don't have to be numbers, either. People use Python for data-intensive work in genetics, climate research, political and economic analysis, and much more. Data scientists have written an impressive array of visualization and analysis tools in Python. One of the most popular tools is matplotlib, a mathematical plotting library. In this tutorial we'll use matplotlib to make simple plots, such as line graphs and scatter plots. After which, we'll create a more interesting data set based on the concept of a random walk -a visualization generated from a series of random decisions.

#### Key takeaways 

- Installing matplotlib
- Plotting a Simple Line Graph
- Changing the Label Type and Graph Thickness
- Plotting and Styling Individual Points with `scatter()`
- Calculating Data Automatically
- Defining Custom Colors

#### Article quality
This tutorial will use broader examples that will help learners understand how to visualize data in Python easily. Also a different approach is taken to explain this tutorial making it different from other articles available over the internet.

**Comment by WanjaMIKE** [comment]
This topic appears a bit oversaturated on other blogs and official docs. Feel free to choose another topic. Thanks
