### ISSUE TITLE
A SBERT-based Flask web app for automatic text summarization

### ISSUE THREAD

**Issue by FranciscaNg** [section-engineering-education/engineering-education#7139]
### Topic Suggestion
A SBERT-based Flask web app for automatic text summarization
#### Proposed article introduction
Sentence BERT (SBERT), a variant of the pre-trained BERT network, generates semantically relevant sentence embeddings that may be compared using cosine similarity. This capability enables the use of SBERT for novel tasks such as semantic similarity comparison.

We'll use sentence BERT to create a Flask web application that performs automatic text summarization.
#### Key takeaways
- Front-end coding
- back-end coding
- Lounching the application
#### Article quality
This tutorial we will look at front-end and back-end Python coding in detail and lounch the application. The code snippets will be simple and easy to grasp.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
