### ISSUE TITLE
How to develop java RMI client application

### ISSUE THREAD

**Issue by Gladysoby** [section-engineering-education/engineering-education#7144]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

### Topic Suggestion
How to develop java RMI client application

### Writing sample(s): 
https://www.section.io/engineering-education/build-and-run-unikernel-with-ops/

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction

The RMI (remote method Invocation) is an API that offers a mechanism to create disbursed software in java. The RMI allows an object to invoke techniques on an object running in some other JVM.

The RMI provides remote communication between the applications the usage of two objects stub and skeleton. A remote object is an object whose approach can be invoked from another JVM.

#### Key takeaways 
- Remote interface
- Implementing the remote interface
- Creating a server program
- Creating a client program
- Compiling and executing the application
#### Article quality
This article will go beyond what is already in the blogs. In this article i will use the advance methods of developing a java RMI client application which will be a beginner friendly guide with well illustrated steps.

#### References
N)a

### Conclusion
We have developed a java RMI client application with a step by step guide. Now, you can use RMI to connect to Java components or to existing components written in other languages. As Java proves itself to your environment, you can extend your Java use and get all of the advantages-no porting, low upkeep fees, and a secure, relaxed surroundings.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=java+RMI+client+application&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
