### ISSUE TITLE
Implementation of 2-D Discrete Fourier Transform of square functions and natural images in Matlab

### ISSUE THREAD

**Issue by peterAdongo** [section-engineering-education/engineering-education#7177]
### Topic Suggestion
Implementation of 2-D Discrete Fourier Transform of square functions and natural images in Matlab

### Writing sample(s): 
https://www.section.io/engineering-education/tracking-of-objects-using-the-histogram-based-tracker-in-matlab/

#### Proposed article introduction
2-D Discrete Fourier Transform can be considered a means of calculating the transform of a 2D sampled signal defined over a discrete grid. The squaring operation defines a real function called the square function or the squaring function in square functions. Its domain is the whole real line, and its image is the set of nonnegative real numbers. The "natural images" are essentially used as shorthand for images with a rich local covariance structure.
In this tutorial, Discrete Fourier Transform (DFT) of images is introduced. A brief theoretical background of Discrete-Time Fourier Transform (DTFT) is first introduced and explains how DTFT is evolved in DFT. Also, the advantages of DFT are explained along with its limitations. MATLAB code is also given for computing the DFT of images and viewing their spectrum

#### Key takeaways 
- 2D-Discrete Fourier Transform (DFT).
- Applications and Limitations of 2-D DFT. 
- Matlab code for 2D-DFT of a square function 
- Matlab code for the natural image.

#### Article quality
This article shows the implementation of DFT in digital images and natural images. Also, properly covers the background theory of this transform and its applications.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @peterAdongo 
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
