### ISSUE TITLE
[Machine Learning] Simple Swap: A Machine Learning Framework for Swapping Faces

### ISSUE THREAD

**Issue by wilkistermumbi** [section-engineering-education/engineering-education#7178]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Simple Swap: A Machine Learning Framework for Swapping Faces

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Simple Swap (SimSwap) is a ML framework that aims for generalized and high fidelity face swapping. In contrast to previous approaches that either lack the ability to generalize to arbitrary identity or fail to preserve attributes like facial expression and gaze direction, our framework is capable of transferring the identity of an arbitrary source face into an arbitrary target face while preserving the attributes of the target face. We will give an overview of the framework, how it can be applied in various use cases,  and implement an example to demonstrate how it can be used.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to:
- Be given an overview of the framework.
- How to clone the GitHub repo for the framework.
- Installing required dependencies.
- Learn how to face swap images.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

This framework is still relatively new. It was released in 2021. Not much information is available online. In addition, the tutorials that are there only focus on giving an overview of the model but not how to implement it. This tutorial will do just that.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [SimSwap: An Efficient Framework For High Fidelity Face Swapping](https://arxiv.org/pdf/2106.06340v1.pdf)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @wilkistermumbi 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
