### ISSUE TITLE
[Security] Implementing a Proper Backup solution to Protect IP in a High Turnover World

### ISSUE THREAD

**Issue by LeahKui** [section-engineering-education/engineering-education#7182]
### Topic Suggestion
Implementing a Proper Backup solution to Protect IP in a High Turnover World

#### Proposed title of article
Implementing a Proper Backup solution to Protect IP in a High Turnover World

#### Proposed article introduction
companies are struggling to protect their intellectual properties (IP) from mishaps. How do you recover from an angry employee sabotaging your product or a remote employee compromising your security measures? 

In this article, readers will learn why backups are needed and implement a proper backup solution to protect the IP. Also, the article will make a case for backups as a way to protect companies’ IPs and how they can ensure the safety of their products.

#### Key takeaways 
1. Why are backups needed?
2. Why not having backup is a bad idea
3. Implementing a proper backup solution

- How can companies protect their IP?

#### Article quality
This article will help readers understand why backups are crucial and get to know ways to protect companies' IPs to ensure the safety of their products. The article will be straight to the point and unique as this content is not widely published by other sources.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @LeahKui 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
