### ISSUE TITLE
How to build an audio book reader with Javascript, Tesseract js, and the Speech Synthesis API. 

### ISSUE THREAD

**Issue by Nomzy-kush** [section-engineering-education/engineering-education#7183]
### Writing sample(s): 

https://www.section.io/engineering-education/meme-generator-vanilla-javascript-skeleton-html5-canvas/

https://www.section.io/engineering-education/how-to-build-a-currency-converter-with-react-and-its-material-ui/

https://blog.logrocket.com/new-features-unocss-tailwind-css-alternative/

#### Proposed title of article
How to build an audio book reader with Javascript, Tesseract js, and the Speech Synthesis API.

#### Proposed title of the article
How to build an audio book reader with Javascript, Tesseract js, and the Speech Synthesis API.

#### Proposed article introduction
Have you ever wondered how they make your computer speak to you? Well in this article, we will implement OCR(text recognition) in a simple audio book reader using javascript, Tesseract js library - integrated with your computer’s camera, will recognize text in any image. We will also use the Speech synthesis API which will read out that text to you in English. 
Sounds exciting right?

#### Key Takeaways
Readers will learn all about the Tesseract js library which is a pure JavaScript OCR for more than 100 languages.
Readers will learn how to use the Speech synthesis API to recognize text and display it to the user via speech.
Readers will also learn how to get the text shown on the Camera and display them in the web page with JavaScript ES6 classes.

#### Article Quality
This in-depth tutorial will add so much value to readers because along with learning how to build an audio book reader with JavaScript, they will also learn about text and speech recognition technologies. The heading also contains several keywords that will greatly boost the article’s SEO ranking. 

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Nomzy-kush 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@Nomzy-kush 
We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
