### ISSUE TITLE
[Machine Learning] Using Imbalanced-Learn to handle imbalanced text data in natural language processing

### ISSUE THREAD

**Issue by donnexwafula33** [section-engineering-education/engineering-education#7185]
#### Proposed title of article
[Machine Learning] Using Imbalanced-Learn to handle imbalanced text data in natural language processing

#### Proposed article introduction
Imbalanced-Learn is a Python module that helps in balancing the datasets which are highly skewed or biased towards some classes. Thus, it helps in resampling the classes which are otherwise oversampled or under-sampled. It offers a number of re-sampling techniques commonly used in datasets showing strong between-class imbalance.

Most models that are built using the imbalanced data will have a bias towards predicting the majority classes in the dataset and ignore the minority classes. Class imbalance is identified by observing the distribution of classes within your data or using visualizing libraries to plot the class distributions.

Imbalanced-Learn has various techniques that will be used to handle this problem. These techniques are such as Random Under sampling technique resample all classes but the majority class, Random Oversampling technique: resample all classes but the majority class.
In this tutorial, we will discuss these techniques in natural language processing and implement them practically using Python. We will also perform all the text preprocessing steps.

#### Key takeaways 
1. Text preprocessing (we will perform word lemmatization, removing stop words, and removing punctuations).
2.  Performing data augmentation using NLP Transformers.
3. Installing Imbalanced-Learn.
4. Exploring Imbalanced-Learn methods and techniques.
5. Implementing `RandomOverSampler` to balance the classes.

#### Article quality
This tutorial is unique because we will implement text preprocessing in detail so that a reader can understand the concepts in natural language processing. We will create a custom function for word lemmatization, removing stop words, removing punctuations, removing extra white spaces, and removing numbers. This ensures we have a clean dataset for natural language processing.  We will also perform data augmentation using NLP Transformers. Finally, we will implement `RandomOverSampler` to balance the classes.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @donnexwafula33 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
