### ISSUE TITLE
As an EngEd contributor I'd like to have a similar articles section

### ISSUE THREAD

**Issue by hectorkambow** [section-engineering-education/engineering-education#7186]
As an EngEd contributor, I'd like to have a similar articles section at the bottom of all articles. This section would showcase similar articles (in the same topic category).

**Describe Value(s):**
Value here - longer retention time by audience, added exposure to other similar articles that may not be getting page views.

**Done When:**
- We have something similar to the [Section Blog](https://www.section.io/blog/importance-of-application-latency/) section (see image) 
- Should display 3 related articles. 
- Should use Hugo's built-in [Related Content](https://gohugo.io/content-management/related/).
- Should be displayed directly under the comments section and above the footer on EngEd article pages. 

**Styling Expectation:**
- Please use the same styling approach as the Section Blog referenced above. However, instead of using the section Green color for the boxes, please use the EngEd blue color. 

We ask that students please leave a comment on this issue when they start working on the feature.

**Comment by hectorkambow** [comment]
Example:
![image](https://user-images.githubusercontent.com/60800358/158896453-5f4e2c74-71cf-4785-a38d-594f8063c3bf.png)

**Comment by louisefindlay23** [comment]
I'd love to work on this, @hborrelli1 @hectorkambow.

**Comment by hborrelli1** [comment]
Great, thanks @louisefindlay23! We actually decided to just keep is as related articles (not necessarily from the same author) so that we help to highlight other authors and potentially other articles that may not be getting as many views. We decided to not include articles from the same author for now.

**Comment by hectorkambow** [comment]
> Great, thanks @louisefindlay23! We actually decided to just keep is as related articles (not necessarily from the same author) so that we help to highlight other authors and potentially other articles that may not be getting as many views. We decided to not include articles from the same author for now.

Great point - thank you Harry. 

Great question Louise (we should have included that note) - another reason is that we are planning to include a "pinned" article section in the future as well - and we thought that would serve the same purpose if we did author similar articles. 

That way the similar articles section focuses on related articles from other authors (based on the topics perhaps). 


& pinned articles can be any article the author wants to showcase (of theirs).

**Comment by louisefindlay23** [comment]
Thanks, @hectorkambow and @hborrelli1. Great points. A pinned articles section sounds great. Will that be a future CCS issue?

Have made a PR: #7535 for this feature.
