### ISSUE TITLE
[Machine Learning] Univariate time series using Recurrent Neural Networks

### ISSUE THREAD

**Issue by jamesmainamaingi9** [section-engineering-education/engineering-education#7197]
#### Proposed title of article
[Machine Learning] Univariate time series using Recurrent Neural Networks

#### Proposed article introduction
A recurrent neural network (RNN) is a class of artificial neural network where connections between nodes form a direct graph along a sequence. This allows it to exhibit temporal dynamic behavior for a time sequence. 
Unlike feedforward neural networks, RNNs can use their internal state (memory) to process sequences of inputs. This makes them applicable to price prediction but also handwriting and speech recognition.

LSTM are a variant of RNN(recurrent neural network) and are widely used of for time series projects in forecasting and future predictions. Long short-term memory (LSTM) units are units of a recurrent neural network (RNN). LSTM networks are well-suited to classifying, processing and making predictions based on time-series data.

In time series, we have univariate, bivariate, and multivariate modeling. Univariate statistics summarize only one variable at a time, bivariate statistics compare two variables and multivariate statistics compare more than two variables. 
In this tutorial, we will be focusing on univariate time series modeling. Time series forecasting is the process of analyzing time series data using statistics and modeling to make predictions and inform strategic decision-making. Time series analysis involves developing models to gain an understanding of the data to understand the underlying causes.

We will use RNN to build a time series model that predicts monthly milk production.

#### Key takeaways 
1. What are RNNs? 
2. Types of RNNs and Improvements to RNN 
3. Dataset preparation.
4. Time series analysis and decomposition.
5. Time series prediction with only one variable using RNN.

#### Article quality
This article is unique because we will discuss all the types of RNNs and improvements to RNN in details. This will give a reader a good understanding of the RNN architecture. We will explain all the concepts involved in time series so that a beginner can easily follow.

We will then perform time series decompositon so that a reader can know te components that make up a time series. We will also diferentiate univariate, bivariate, and multivariate modeling in clear way. 
Finally we will implement a custom time serie model that predicts monthly milk production. The tutorial wil have a good flow of steps that a reader can easily follow.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Great topic 🚀 , make sure it matches the following: 
* Adds value beyond what is in the official docs and covered in other blog sites.
* To avoid potential article closure, it should not overlap with existing EngEd articles or incoming topic suggestions.

Please reference any relevant EngEd articles in yours and build a unique project - Approved.
