### ISSUE TITLE
[Machine Learning]How to Build a Prediction Model From a Filter Based Feature Selection to Perform Text Classification

### ISSUE THREAD

**Issue by EssyH** [section-engineering-education/engineering-education#7220]
### Topic Suggestion
How to Build a Prediction Model From a Filter Based Feature Selection to Perform Text Classification

#### Proposed article introduction
We will learn how to model text content and make predictions in this post. To find the appropriate features, we will apply simple preprocessing techniques like Feature Hashing. The important features are then selected using the Filter Based Feature Selection tool. The multi-class classification technique is then used to apply the classification.

We will use three distinct ways to extract the word frequencies before using Filter Based Feature Selection, and the models are developed for all of them. Finally, all of the models are evaluated to determine which technique is the best.

#### Key takeaways 
- Filter Based Feature Selection
- Feature Hashing Control
- Basic preprocessing techniques
- Classification
#### Article quality
The article is intended to be precise and clear to the point, illustrated by codes making it more practical and interesting, to increase time spent on the page. Simple grammar will also be used hence it will be beginner-friendly.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Please fill in the article quality section. @EssyH

**Comment by EssyH** [comment]
hello @ahmadmardeni1 the requested changes are in place

**Comment by EssyH** [comment]
Sorry for the late response i was kinda busy doing some assessment tests throughout the previous week

**Comment by ahmadmardeni1** [comment]
No problem! Thank you for submitting your topic. @EssyH 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
