### ISSUE TITLE
How to Use Script Setup in Nuxt 2

### ISSUE THREAD

**Issue by Sanderson006** [section-engineering-education/engineering-education#7224]
**Proposed title of the article**
How to use script setup in Nuxt 2

**Proposed article introduction**
Script setup is a compile-time syntactic sugar for using Composition API inside Single File Components (SFCs).  It usually provides developers with a more concise syntax to write their single file components.
Nuxt 2 is a framework for creating Vue.js which help Vue Developers take advantage of top-notch technologies, fast, easy and in an organized way.
In this article, we are going to see how script setup can be used in Nuxt 2.

**Key takeaways**
At the end of this tutorial the learner will:
1.	Learn how to use the script setup
2.	Understand Nuxt 2 framework

**Article quality**
This will be a step-by-step beginner friendly tutorial that will cover in depth the use of script setup in Nuxt 2. 
References
•	[VueJs](https://vuejs.org/api/sfc-script-setup.html)
•	[Nuxt 2](https://nuxtjs.org/)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by Sanderson006** [comment]
Okay, Thanks for the remarks!
