### ISSUE TITLE
[Security] Data Recovery: RAID and Erasure Coding

### ISSUE THREAD

**Issue by lin-chez** [section-engineering-education/engineering-education#7227]
### Topic Suggestion
Security 

### Writing sample(s): 
[How to add pure CSS waves to your website](https://www.section.io/engineering-education/pure-css-wave-animations-website/)
#### Proposed title of article
Data Recovery: RAID and Reed Solomon Erasure Coding

#### Proposed article introduction
Organization require large amounts of storage alternatives to store their data and information. When the storage needs in your organization start soaring up the roof, alternatives such as moving information to the cloud or fitting dedicated storage servers become viable options. Large storage alternatives like dedicated storage server use a range of data recovery alternatives to ensure that all data stored in their systems can be recovered in case of failures. Alternatives such as RAID implementation, and its competitor Erasure Coding are just but a few of the popular methods used to recover data. 
#### Key takeaways 
This article seeks to educate the reader on:
- A look at the different types of raid methods and finding out which will suite your data recovery needs.
- A discussion on the different erasure coding schemes and finding out which is best in various cases.
- Determining which method suits your hardware type(SSD and HDD), architecture(cloud and hyper converged distributed storage.), performance needs and available storage. 

#### Article quality
This article takes an in-depth approach to discussing the topic of data recovery. The article only focuses on data recovery and how one can use the information compiled in the article to select the best approach between erasure coding and RAID. The article cover additional topics such as identifying the types of technologies beneath RAID and Erasure coding. This is different from other blog articles that mostly focus on defining the two methods and listing out a few differences between the two methods.

#### References
N.A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Your suggestion is not completed.  @lin-chez

**Comment by lin-chez** [comment]
@ahmadmardeni1 Topic suggestion complete

**Comment by ahmadmardeni1** [comment]
How does your article differ from https://www.computerweekly.com/feature/Erasure-coding-vs-RAID-Data-protection-in-the-cloud-era#:~:text=Enter%20erasure%20coding&text=Erasure%20coding%20also%20uses%20less,transmissions%2C%20including%20in%20GSM%20mobiles. ? @lin-chez

**Comment by lin-chez** [comment]
@ahmadmardeni1 .My article differs from the one attached in the following ways. My article covers the types of raid methods and erasure coding schemes and explores which is best for your data recovery needs. The article also touches on hardware and architecture optimal for a given method. This article avoids discussing the definitions and comparisons between the two recovery techniques. The article focuses on data recovery and how to select a method that will suit your needs.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @lin-chez 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
