### ISSUE TITLE
Getting Started with Growth Model in Pyhton

### ISSUE THREAD

**Issue by sumbaelvis** [section-engineering-education/engineering-education#7228]
#### Proposed title of the article
Getting Started with Growth Model in Pyhton
#### Proposed article introduction
Growth models are common in scientific fields and have been developed and used
successfully for specific situations. Some of the situations where these models have shown success are in the description of how something grows with changes in the regressor variable, which is usually time. A life-time example where the growth model is used is modelling the time it takes until the business grows and other situations such as modelling the population growth with time. Growth models take the form:

$y = \frac{a}{(1 + be^{ −cx})}$,

where a , b and c are the constants of the model. At x = 0 , y = a/(1+b)

and as x → ∞ ,

y → a.

In this article, we will learn how to approximate the unknown parameters of the growth model using numerical methods such as the newton raphson algorithm and later state our model, which we will then use to make predictions. These activities will be carried out in python.

#### Key takeaways 
1. What's the Growth model
2. How to establish an optimization problem for the Growth model
3. How to determine the values of the unknown parameters by solving the lost function using the Newton Raphson method
4. How to make the prediction using the growth model
5. How to implement the growth model in python

#### Article quality
This article focuses on making the concept behind the growth model as clear as possible. We will focus on the key concepts and explore them in-depth. During our study, we will simplify concepts and make them easy to understand. This is because the content of this paper will base on a deep understanding of the topic. For the case study, we will provide a thoroughly explained code to make it easy for the learner to connect the theoretical part with the implementation session. Therefore, simplifying the concept, an in-depth approach to the study, and an easy-to-follow implementation session will make the entire content unique.
#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @sumbaelvis 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
