### ISSUE TITLE
volatility modeling in R using Garch model

### ISSUE THREAD

**Issue by kipkoech2000** [section-engineering-education/engineering-education#7230]
### Topic Suggestion
volatility modeling in R using Garch model

#### Proposed title of the article
volatility modeling in R using Garch model

#### Proposed article introduction
[Machine learning] Volatility modeling in R using Garch model
While working on financial data such as stock, cryptocurrency, or indices using ARMA model to forecast their future prices. most of these data show an error term that is strongly or weakly stationary due to factors like market turbulence thus when assumed to be stationary, they may lead to misspecification of the model estimation leading to a bad forecast. 
Garch model will help us to model change in time series that is time dependant volatility (increasing and decreasing volatility)  and in this article, I am going to take you step by step on how to do volatility modeling for your financial data of which in this tutorial we are going to use Amazon data.

#### Key takeaways 
By following the steps in the article. the reader will be able to;
1. Perform financial data scrapping using quantmod
2. calculate daily stock returns and display it
3. calculate the volatility of returns
4. Fit and use Garch mode
5. change Garch model to fit in cases where they follow  skewed distribution instead of normal disrtibution
6. Estimate GJR-GARCH model estimation

#### Article quality
My article will be original, grammar-error-free, well researched with documented 100% working codes that will be engaging and easily be understood by the Machine learning enthusiast of any level either a beginner or advanced who is interested in financial modeling. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
1. https://subscription.packtpub.com
2. https://bookdown.org
3. https://cran.r-project.org
4. https://rpubs.com
5. https://www.idrisstsafack.com

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @kipkoech2000 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@kipkoech2000 

We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
