### ISSUE TITLE
[Languages]How to Work With Customized Axios for  Mulitple Servers in Vue 3

### ISSUE THREAD

**Issue by NaomiSeint** [section-engineering-education/engineering-education#7231]
#### Proposed title of article
How to Work With Customized Axios for  Mulitple Servers in Vue 3

#### Proposed article introduction
In this tutorial, I will walk you through the concepts of Axios in Vue 3. The main aim will solely be to teach you everything you need to know about Axios, and how you can customize it to be able to make requests to multiple servers from your Vue application.

By default, Axios is shipped and only make a request to a single server. This is not an ideal situation when it comes to large scale applications, such as banking systems. Normally, these systems would make multiple, concurrent requests to different servers. To achieve this in Vue SPA, we will customize these Axios to be able to make these requests.
#### Key takeaways 
- Understanding the inner workings of the Axios package for Vue.
- Customizing the Axios package to make requests to multiple servers in Vue 3.
- Integrate the Axios in large scale Vue application.
- Deploying a packaged Vue application.

#### Article quality
The main aim of this tutorial is to help Vue developers to build and customize the Axios package to make requests to multiple servers.
This is a unique feature that most tutorials lack and would come in hand for for developers who work in large scale applications with high reusability demands.

> However my google search did not show any results for this topic!

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Let's ensure that it adds value to the community. Thanks
