### ISSUE TITLE
Dynamic Programming in Javascript using Tabulation

### ISSUE THREAD

**Issue by gatwirival** [section-engineering-education/engineering-education#7232]
#### Proposed article introduction
Dynamic Programming in Javascript using Tabulation

#### Proposed article introduction
Tabulation is a technique used to solve dynamic programming problems. You first fill up a table and then compute the solution to the problem based on the result on the table. It is a Bottom-Up method. We start solving the problems from the base cases (bottom) and gathering answers to the top. Tabulation implementation is iterative in nature.

The advantage of using tabulation is that It‘s fast as we directly access previous states from the table. If all sub-problems must be solved once tabulation is better because all the entries must be filled one by one.

#### Key  takeaways
- What is tabulation?
- What is iteration?
- How to implement tabulation.
- How to use tabulation to solve dynamic programming problems.
- Tabulation time complexity

#### Article quality
This article will cover tabulation algorithms in dynamic programming in depth. The reader will learn how to implement tabulation algorithms, how to work with tabulation to solve dynamic programming problems, and how to calculate tabulation time complexity. This will help the reader to fully understand the topic.

**Comment by WanjaMIKE** [comment]
How does this topic differ from what is already covered here -> https://www.fullstackacademy.com/blog/introduction-to-tabulation-in-dynamic-programming-subset-sum-problem?

**Comment by gatwirival** [comment]
It will be a deep dive into tabulation I will cover 
- pros and cons of tabulation
- I will be solving a grid traveler problem in javascript
- I will use visualizations, Implement the algorithm and write it as code.
- Explain the time complexity in the tabulation

**Comment by hectorkambow** [comment]
👀

**Comment by hectorkambow** [comment]
Lets be sure it is different from what is found in other sites, videos, or blogs. Lets make it unique.

Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved


https://www.google.com/search?q=Dynamic+Programming+in+Javascript+using+Tabulation&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
