### ISSUE TITLE
How to Build a Text Extractor Using React and Google-Cloud-Vision API

### ISSUE THREAD

**Issue by codeInn001** [section-engineering-education/engineering-education#7233]
### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
[Languages] How to Build a Text Extractor Using React and Google-Cloud-Vision API

#### Proposed article introduction
Google Cloud Vision API is a machine learning tool that can classify details from an image provided as an input into thousands of different categories with pre-trained API models. It offers these pre-trained models through an API and the categories are detected as individual objects within the image.

In this tutorial you will get know how can we integrate Google Vision API in our React application and how Google vision API can b used to extract text from images recognition.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

#### Key takeaways 
How to configure and use Google Cloud Vision API
How to integrate Google Cloud vision API in your React Application
How to access firebase for stored images and extracting text from saved Images 

#### Article quality
Most resources on Google vision API dos not cover React, most covers mainly React Native. 
#### References
https://cloud.google.com/vision

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @codeInn001 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by codeInn001** [comment]
@ahmadmardeni1 Apologies for the delay. Article will be ready by next week. thanks.

**Comment by hectorkambow** [comment]
@codeInn001 
We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
