### ISSUE TITLE
Flutter Text Fields Auto-Capitalization Configuration Guide

### ISSUE THREAD

**Issue by Denzelmwangi** [section-engineering-education/engineering-education#7234]
#### Proposed title of article 

Flutter Text Fields Auto-Capitalization Configuration Guide

#### Proposed article introduction

* If you are designing an application’s sign-up and log-in forms, you will need an input field. Flutter is one of the popular open-source frameworks to create an interesting mobile application for android and iOS apps. TextField is an input element that holds alphanumeric data like address, name, password and much more. It enables people to enter details on the on-screen or hardware keyboard. When creating a native mobile application for your business, you can hire an app developer who will use the TextBox widget to create forms, search experiences and send messages.

#### Key takeaways 

* By the end of this article, the following is expected;

1. Tips for auto-capitalization in Flutter’s TextBox
2. Critical properties of TextField widget in a flutter
3. Change Keyboard Type
4. Change TextInputAction

#### Article quality

This article will be on point, simple to understand, well formatted and I'm sure users will be able to learn the procedure of Configuring Auto-Capitalization Behavior in Flutter’s Text Entry Fields. The code snippets in this article will be simple to understand and implement. I hope we will have a good ride all along.

#### References

N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
