### ISSUE TITLE
[Security] Step by step to security threats of NFTS and possible solutions| hardware wallet

### ISSUE THREAD

**Issue by Sreign254** [section-engineering-education/engineering-education#7235]
**### Proposal Submission**

### **Proposed title of the article**

[Security] Step by step to security threats of NFTS and possible solutions| hardware wallet

### **Proposed article introduction**

Whether online or offline, security is one of the major issues that we do have to tackle on our day to day bases.
Both companies and individuals are struggling to protect their individual properties and NFTs. As the metaverse keeps on a flight, the NFT
and digital avatars can be represented by NFTs and moved from one virtual world to another.
Allow me to demystify NFTS.
An NFT (the abbreviation for the non-fungible token ) stands for cryptographically unique tokens that are linked to digital 
and sometimes physical contents, by providing proof of ownership.

Fungible means that the token is interchangeable. For example a dollar, you can swap a dollar with another one dollar and still own one dollar.
Non-fungible means they are unique. They cannot be swapped as no two NFTs are alike. A lot of content has seen turned to NFTs, including
digital arts, movies, and music. In 2021 NFTs has exploded to mainstream leading to the creation of DEFI (Decentralised Finance)
and DAO  ( decentralized autonomous organizations). In the future, the NFT could be used to provide deeds to companies,
sell tickets, and provide marriage certificates,

In this article, the reader will learn about the step-to-step threats on NFTs and implement proper possible solutions to protect their NFTs.

**### Key takeaways**

- Understanding NFTs.
- Understanding NFT's possible threats.
- Possible NFTs security solutions.
- What does the future holds for NFT.

### **Article quality**

This in-depth tutorial will add so much value to the reader because along with learning about block chain, security threats of NFTs and possible
solutions, they will also learn about the future of NFTs.

### **References**

N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Sreign254 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
