### ISSUE TITLE
[Language] Quickest way to create smart dustbin project using Arduino and python.

### ISSUE THREAD

**Issue by JGatura421** [section-engineering-education/engineering-education#7236]
**### Proposal Submission**

### **Proposed title of the article**

[Language] Quickest way to create smart dustbin project using Arduino and python.

**### Proposed title of the article**

Building your first smart dustbin using Arduino and python.

### **Proposed article introduction**

Have you ever wondered how they make elevator doors open automatically or how window blades open and close automatically. 
A dustbin is used to store trash for a temporary base. They are most common in homes, parks, and offices.
Smart dustbin as its name represents its work smartly or we can say that it is an automatic dustbin.

Well in this article I will show you how to make a smart dustbin using Arduino where the lid will automatically open when you approach the trash. A smart dustbin is a very good project especially executed with python and
Arduino. It will work like the smart thing. sounds exciting, right?

**### Key Takeaways**

 At the end of the article, the reader shall be able to

1. Analyse the dustbin program and set it up accordingly.
2. Familiarize himself with Arduino and respective sensors.
3. Design a great prototype for a smart dustbin.

**### Article Quality**

This in-depth tutorial will add so much value to readers because along with learning how to build a dustbin using Arduino thy will also, familiarize themselves with the programming language python.

**### References**

[How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
[Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
[Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
