### ISSUE TITLE
[Networking]  An Introduction to mobile network engineering based on the air interface

### ISSUE THREAD

**Issue by Dennisnjoroge96** [section-engineering-education/engineering-education#7237]
**### Proposal Submission**

### **Proposed title of the article**

 Step guide to the introduction of mobile network engineering based on the air interface.

**### Proposed title of the article**
As the world keeps on changing, so does the technology evolve. We will discuss what mobile network, the air interface and briefly explain wireless communication. Focusing on the four major networks ie' 1G, GSM (Global System for Mobile Communications), 3G (third-generation ),4G (fourth generation), 5G(fifth generation), and the 6G (sixth generation). We will introduce some basic concepts on mobile networking engineering and also focus on the Radio Access Network. (RAN).
the air interface is the communication link created between two BTS, (base station receivers.) we shall briefly also explain what a BTS is and its purpose is on mobile networking and briefly focus on the Air interface.

### **Key Takeaways**

 At the end of the article, the reader shall be able to

- Understanding mobile networking.
- What is a BTS?
- Understand the purpose of a BTS.
- Understanding the basic concepts of mobile networking engineering?
- Understanding the air interface and its concepts/
- What does the future hold on the world of mobile network engineering?

Article Quality

This in-depth tutorial will add so much value to readers because along with understanding the basic concept of mobile network engineering they will also have a glimpse of what the future holds in mobile network engineering.

### 
**References**

N/A

**Comment by ahmadmardeni1** [comment]
Does your article overlap with:
1. https://www.section.io/engineering-education/wireless-mobile-networking/
2. https://www.sciencedirect.com/topics/engineering/air-interface 
? @Dennisnjoroge96

**Comment by Dennisnjoroge96** [comment]
> Does your article overlap with https://www.section.io/engineering-education/wireless-mobile-networking/ ? @Dennisnjoroge96

No, it doesn't overlap with https://www.section.io/engineering-education/wireless-mobile-networking/

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Dennisnjoroge96

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@Dennisnjoroge96 
We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
