### ISSUE TITLE
As an EngEd contributor I'd like the option to add my (LOCATION) on my Author Profile.

### ISSUE THREAD

**Issue by hectorkambow** [section-engineering-education/engineering-education#7240]
As an EngEd contributor I'd my Author Profile to show where I am from

[Describe Value(s)](https://app.getguru.com/card/Tqp9no8c/Six-Types-of-Value?q=value):
[value here is that the author is better showcased to potential employers]

We have this input from google form (google sheets).

Value more for Future students.

Done When:
Done when the author profile showcases where the contributor is from: (see images)

![image](https://user-images.githubusercontent.com/60800358/159312432-b764d4e3-925a-45e1-957a-5dd87578ee68.png)

​​​
![image](https://user-images.githubusercontent.com/60800358/159312413-8e45a9b1-0ea5-43f9-ad66-e73f19a3513e.png)

![image](https://user-images.githubusercontent.com/60800358/159312533-c86bcecc-8363-484e-83b3-f3676691d496.png)

![image](https://user-images.githubusercontent.com/60800358/159312562-813fa62b-d841-4120-9a76-bc782b343e96.png)

**Comment by louisefindlay23** [comment]
@hectorkambow, would this be a feature request that would be suitable for CCC? I'd like to work on it if it was.

My thoughts were to use the [Google Sheets API](https://developers.google.com/sheets/api/quickstart/quickstarts-overview) to obtain the information - matching it either to the Author's Name or the Permalink for the Author Folder depending on what the Google Sheet Input is.

The idea is to use the API with [Go](https://developers.google.com/sheets/api/quickstart/go) and use the application client id and secret authentication method to retrieve and use this information in the `single.html` Hugo Author template as Hugo uses Go so it should be possible to do this within the template file.

An altenative approach would be to use the API with [client-side JavaScript](https://developers.google.com/sheets/api/quickstart/js) which would populate the location field (which would be added in the author template) with the data from the Google Sheet using a `.js` file but the first approach (leveraging Hugo's templating) would be cleaner and preferable.

**Comment by hectorkambow** [comment]
It actually is in our timeline (of CCC items) to roll out! 

We can start this one this upcoming week. 

Harry & I were prepared the "pinned" article section next - we can get this location one set up as well.
