### ISSUE TITLE
 Is machine learning, artificial intelligence, and robotics the future- What is it, and what is the difference?

### ISSUE THREAD

**Issue by Sreign254** [section-engineering-education/engineering-education#7245]
**### Proposal Submission**

**Proposed title of the article**

Is machine learning, artificial intelligence, and robotics the future- What is it, and what is the difference?

**### Proposed article introduction**
 
What an amazing technology? That everyone gets to talk about it but a few get to understand it and maybe get a chance to use it or work on it. consider yourself leaving in the year 2030, where everything shall be a way too different. For example, presence of self-driving cars, robots replacing the work of man, and the evolution of web 3.0. 

 In this article, we shall talk about the three technologies which are going to drive us to that world. That is machine learning, artificial intelligence, and robotics. As well as how shall we utilize the three technologies? That includes taking a deep look at robotics and AI and AI to machine learning. We shall also briefly explain the usage of the current three technologies and how to improve them. What a smart technology that is worth learning.

**### Key takeaways**

- What is machine learning?
- Application of machine learning.
- What is artificial intelligence?
- Application and various types of artificial intelligence.
- What is robotics?
- Utilization of machine learning, artificial intelligence, and robotics.
- Difference in machine learning, artificial intelligence, and robotics.
- What the future holds for machine learning, artificial intelligence, and robotics.?

### Article quality

This article is user-friendly. By the end, you will have understood machine learning, artificial intelligence, and robotics. How they differ from each other and how they work together to create a better world.

References

**### N/A**

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
