### ISSUE TITLE
Generating data for a random walk using Python

### ISSUE THREAD

**Issue by duncandegwa** [section-engineering-education/engineering-education#7247]
### Writing sample(s): 
https://www.section.io/engineering-education/visualizing-repositories-using-pygal/

### Topic Suggestion
Generating data for a random walk using Python

#### Proposed article introduction
 In this tutorial we’ll use Python to generate data for a random walk and then use matplotlib to create a visually appealing representation of the generated data. A random walk is a path that has no clear direction but is determined by a series of random decisions, each of which is left entirely to chance. You might imagine a random walk as the path an ant would take if 
it had lost its mind and took every step in a random direction. Random walks have practical applications in nature, physics, biology, chemistry, and economics. For example, a pollen grain floating on a drop of water moves across the surface of the water because it is constantly being pushed around by water molecules. Molecular motion in a water drop is random, so the path a pollen grain traces out on the surface is a random walk. The code we’ll write in this article models many real-world  situations

#### Key takeaways 

- Creating the RandomWalk() Class
- Choosing Directions
- Plotting the Random Walk
- Coloring the Points
- Plotting the Starting and Ending Points
- Adding Plot Points

#### Article quality
This tutorial will use broader examples that will help learners understand how to generate and visualize data  for a random walk using Python easily. The code we’ll write in this article models many real-world  situations. Also a different approach is taken to explain this tutorial making it different from other articles available over the internet.

**Comment by ahmadmardeni1** [comment]
How does your article differ from [similar ones](https://www.google.com/search?q=Generating+data+for+a+random+walk+using+Python&oq=Generating+data+for+a+random+walk+using+Python&aqs=edge..69i57j69i61.522j0j1&sourceid=chrome&ie=UTF-8)? @duncandegwa

**Comment by duncandegwa** [comment]
Hello 👋 @ahmadmardeni1 I believe this topic is unique from the other articles available in the internet. I have taken a look at these other articles and I found that they only explain how to generate data while this tutorial will go ahead and show how to visualize that data which is not included in these other articles.
