### ISSUE TITLE
[Machine learning] Weka Feature Selection using Python

### ISSUE THREAD

**Issue by paulromans** [section-engineering-education/engineering-education#7249]
### Topic Suggestion
Weka Feature Selection  using Python

### Writing sample(s): 
[Getting Started with Google Drive Node.js API](https://www.section.io/engineering-education/google-drive-api-nodejs/)

#### Proposed title of the article
Weka Feature Selection  using Python

#### Proposed article introduction
Weka is a collection of machine learning algorithms for data mining tasks. Most of the operations on weka are performed on the Graphical User Interface. However, this limits the users from the programming experience and understanding of the behind the scenes operations.

This is the inspiration for this article which sets to illustrate feature selection in weka by actually writing the code for the implementation. Feature selection reduces the number of attributes when developing a predictive model to minimise processing costs.

#### Key takeaways 
- Introduction to Feature selection in Data mining
- Benefits of Feature selection.
- Feature selection using python with Weka libraries.

#### Article quality
There seems to be minimal article implementing Weka libraries on Python directly. Most articles and blogs use Graphical User Interface, limiting the programmer's expertise.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @paulromans 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
