### ISSUE TITLE
[Languages] Understanding optimistic and pessimistic locking in Java

### ISSUE THREAD

**Issue by ephraa** [section-engineering-education/engineering-education#7250]
#### Proposed title of article
Understanding optimistic and pessimistic locking in Java 

#### Proposed article introduction
Locking refers to the mechanism that allows one to perform parallel operations to the same data in the database. It occurs when multiple transactions try to access the same data at the same time. Locking ensures that only one transaction is allowed to modify the data.

Java programming language supports two types of locking mechanisms. These include the optimistic model and pessimistic model. In this guide, we will create a sample database as an example and perform the two types of locking on the data to better demonstrate the concept. We will also see how simultaneous transactions can result without applying locks.

#### Key takeaways 
At the end of the guide the learner will be able to:
- explain the concept of optimistic and pessimistic locking
- demonstrate with practical example how simultaneous access of data can result without locking
- use optimistic and pessimistic locking approaches to resolve the simultaneous transacaions issue 

#### Article quality
The article will follow a practical approach in explaining the concept of optimistic and pessimistic locks for the reader to grasp the concept in a broader way.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @ephraa 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
