### ISSUE TITLE
Developing SQLite database with Android Studio in java

### ISSUE THREAD

**Issue by Koros-Meshack** [section-engineering-education/engineering-education#7251]
**Topic Suggestion**
Developing SQLite database with Android Studio in java

Writing sample(s):
https://www.section.io/engineering-education/collection-in-java/

**Proposal Submission**
**Proposed title of article**
Developing SQLite database with Android Studio in java

**Introduction**
The proposed article will help mobile developers learn how to develop a software that will enable them to input data, save the data, retrieve and view the data entered. They can also search information, update the data and also delete the data. This article will be able to compliment most of the software developed by android developers since most applications deal with data entry, retrieval, update and data deletion.
The article will use clearly explained code  snippets in java language to help the user to fully understand how to develop the application.

**Key takeaways**
* The readers will be able to develop the android application to enter, retrieve, update, search and delete data.
* Developing and modifying .xml files to acquire desired outlook.
* Coding the .java files to develop and access the database.
* The reader can access  code snippets to develop the application.

**Article quality**
The use of code snippets helps the learner to better understand. Screenshots and images will be used to display expected outputs and procedures. This article will be important since most if not all mobile applications rely on data.

**References**
N/A

**Comment by WanjaMIKE** [comment]
This topic seems a bit over-saturated. We focus more on unique tutorials. Feel free to suggest another topic. Thanks
