### ISSUE TITLE
[Languages] Understanding memory leaks in managed languages

### ISSUE THREAD

**Issue by g-wekesa** [section-engineering-education/engineering-education#7252]
#### Proposed title of article
Understanding memory leaks in managed languages

#### Proposed article introduction
Memory leaks refer to the gradual deterioration of system performance that occurs over time as the result of the fragmentation of a computer's RAM. It is caused by poorly designed/programmed applications that fail to free up memory segments when they are no longer needed.

Memory leaks start when a program requests a chunk of memory from the operating system for itself and its data. As the program executes it may need additional memory and therefore makes another request. A well-programmed application explicitly releases the memory that it no longer requires. Unfortunately. not all programs are well-programmed and they do not delete objects properly thereby leading to memory leaks.

A memory leak contributes to the heap size which may not be of major concern. However, if left unattended it leads to memory usage problems. Finding the root cause of the problem in the program can be a difficult task. Unlike crash dump where reference to the specific line can be found, a memory leak remains hidden. In this article, we will look in detail at memory leaks in managed languages.

#### Key takeaways 
At the end of the article the learner will understand:
- the consequences of the memory leaks
- types of heap RAM
- profiling tools used for tracking and fixing memory leaks
- how to detect memory leaks
- common types of memory leaks
- how memory leaks can be prevented

#### Article quality
The article will take a practical approach with examples on how to detect and handle memory leaks and provide possible solutions to the issue.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @g-wekesa 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
