### ISSUE TITLE
[Languages]Breached passwords notification with Auth0 in a Spring Boot application

### ISSUE THREAD

**Issue by elizabeth962** [section-engineering-education/engineering-education#7253]
#### Proposed title of article
Breached passwords notification with Auth0 in a Spring Boot application

Use keyword research to improve your article's SEO.

#### Proposed article introduction
The rise of cases of hackers stealing user passwords and gaining unauthorized access to user social media accounts and even bank accounts. In most cases, users usually use a single password shared across multiple accounts. This gives the hackers easy access to all of the user accounts. Auth0 makes it possible to detect the passwords that have been breached. 

I will show a step by step process of integrating Auth0 in a Spring Boot application to notify users when their passwords have been breached. With this proactive approach, application users can take necessary measures before their accounts are breached.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
1. Integrating Spring Boot application web Auth0 password breach detector.
2. Integrating Auth0 with Spring Security.
3. Setting up automated user notifications in Spring Boot.

#### Article quality
Application security is a serious issue that should always be considered while developing applications. Unfortunately, a large percentage of the applications do not notify their users of potential risks when their passwords have been involved in a breach. This article covers password breach notifications, a security layer to Spring Security that is already covered by several blogs on the internet.

#### References
Please list links to any published content/research you intend to use to support/guide this article.
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @elizabeth962 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
