### ISSUE TITLE
[LANGUAGES] Creating and manipulating word(.docx) documents in android using Kotlin and the Apache POI library

### ISSUE THREAD

**Issue by munubi254** [section-engineering-education/engineering-education#7254]
### Writing sample(s): 
[Samples](https://www.section.io/engineering-education/authors/sandra-moringa/)

#### Proposed title of article
Creating and manipulating word(.docx) documents in android using Kotlin and the Apache POI library

Use keyword research to improve your article's SEO.

#### Proposed article introduction
As android developers, we may get ourselves in situations where handling .docx files is easier and faster than doing it using other platforms. In this article, we are going to look at how to create the documents, format them, and most importantly, extract text from them. We will be using Kotlin.

#### Key takeaways 
Using Kotlin to do these in android:
1. Create .docx files
2. Formatting the files
3. Extracting text from the created files(We may also look at extracting text from existing files)

#### Article quality
It is easy to follow through, and the use of Kotlin with the library is not much explored.

#### References
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @munubi254 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
