### ISSUE TITLE
Understanding coupling in Java

### ISSUE THREAD

**Issue by tesswambui** [section-engineering-education/engineering-education#7255]
### Topic Suggestion
Understanding coupling in Java

### Writing sample(s): 
https://www.section.io/engineering-education/working-with-csv-files-in-java/

#### Proposed title of the article
Understanding Coupling in Java

#### Proposed article introduction
Coupling plays a very important role when working with classes and objects in Java. Coupling refers to the dependency of one class on another.  There are only two sorts of coupling which are weak and strong coupling. The weak coupling means that the classes are weakly related and don't depend much on one another, while strong coupling implies that classes are strongly related and depend much on one another.

#### Key takeaways 
- Strong coupling.
- Properties of strong coupling.
-  Example of strong coupling.
- Weak coupling.
- Main properties of weak coupling.
- Overcoming strong coupling.
- Example of weak coupling.

#### Article quality
In this article am going to introduce the reader to coupling in java, explain the two types of coupling, their properties, examples of how they are performed in java, and Overcoming strong coupling. Am also going to use beginner-friendly language and explanations for beginners to understand. 

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
