### ISSUE TITLE
[API] Building Microservice with Ariadne Graphql and Flask

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#7257]
#### Proposed title of the article
[API] Building Microservice with Ariadne Graphql and Flask.

Use keyword research to improve your article's SEO.

#### Proposed article introduction
This tutorial aims to build a microservice application by integrating Ariadne Graphql and Flask. Readers will find this worthwhile starting from the introduction to Ariadne Graphql, and how to build microservice with the library and Flask.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
In the end of the tutorial, the following would have been well discussed;
- What is Ariadne Graphql.
- Advantages of microservice architecture with Ariadne Graphql and Flask in performance.
- Integrating  Ariadne Graphql with Flask.

#### Article quality
This focuses on the performance issues, and how to get started with  Ariadne Graphql with Flask application. Readers will find this tutorial helpful in their future projects.

#### References
[Ariadne Graphql](https://ariadnegraphql.org/docs/flask-integration)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
How does your article differ from https://www.pluralsight.com/guides/develop-a-microservice-using-ariadne-graphql-with-django ? @Horlawhumy-dev

**Comment by Horlawhumy-dev** [comment]
Thank you for the review sir. Obviously, this tutorial will walk readers  through different framework on how to integrate graphql to build microservices using the library. I will build two APIs with both qraphql and Flask - then make them communicate together via ariadne qraphql.

This is going to add value and worth reading for readers. Moreover, this platform has not had it tutorial on the topic. kindly allow me to talk about this!!
@ahmadmardeni1

**Comment by ahmadmardeni1** [comment]
Thank you for the suggestion.  @[Horlawhumy-dev](https://github.com/Horlawhumy-dev)
I still think this topic is widely covered by other blog sites.

We believe that the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you for the suggestion.  @[Horlawhumy-dev](https://github.com/Horlawhumy-dev)
I still think this topic is widely covered by other blog sites.

We believe that the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you for the suggestion.  @[Horlawhumy-dev](https://github.com/Horlawhumy-dev)
I still think this topic is widely covered by other blog sites.

We believe that the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
