### ISSUE TITLE
[Blockchain] Effectiveness of blockchain in enhancing supply chain transparency

### ISSUE THREAD

**Issue by slynn22** [section-engineering-education/engineering-education#7258]
### Topic Suggestion
Effectiveness of blockchain in enhancing supply chain transparency
#### Proposed article introduction
Lack of transparency is the main challenge that supply chains suffer today. This usually leads to turning away of shipments in the ports, poor customer experience, rising logistic costs, and delays in delivery.
Blockchain is a promising technology that could be vital in addressing the problem. This could be efficient in building trust between the customers, companies, and suppliers. Addressing the issue could also enhance brand loyalty, customer assurance, and more robust partnership.
The article will focus on assessing the effectiveness of blockchain in enhancing supply chain transparency to address the operational problem and improve business productivity.
#### Key takeaways 
1. How blockchain could drive transparency in supply chain 
2. Stakeholders who could use blockchain to enhance the supply chain transparency
3. Why blockchain is the best technology to address the transparency problem in the supply chain

#### Article quality
The article will cover the topic in-depth to see how it could be used in addressing the supply chain transparency issue.

#### References
Not Applicable

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @slynn22 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by slynn22** [comment]
Thank you

**Comment by hectorkambow** [comment]
@slynn22 
We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
