### ISSUE TITLE
[MACHINE LEARNING] Using C++ to create a Machine Learning model in android

### ISSUE THREAD

**Issue by Agusioma** [section-engineering-education/engineering-education#7259]
### Writing sample(s): 
[Samples](https://www.section.io/engineering-education/authors/terrence-aluda/).

#### Proposed title of the article
Using C++ to create a Machine Learning model in android

#### Proposed article introduction
We are going to build on [this](https://www.section.io/engineering-education/cpp-model-in-a-python-machine-learning-project/) article and learn how to create a native machine learning android app using the NDK. We will look at creating a model, loading a heart dataset, and then making a prediction.

> I'm still researching on this. More will be talked about. We may also explore the Neural Networks API.

#### Key takeaways
- Creating a model using the JNI
- Loading a dataset using the JNI
- Making predictions from the dataset

#### Article quality
It is easy to follow through, and this is not much explored.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @auxesis 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
