### ISSUE TITLE
How to implement static maps Image in Vue

### ISSUE THREAD

**Issue by shosenwales** [section-engineering-education/engineering-education#7260]
### Topic Suggestion
How to implement static maps Image in Vue.

### Writing sample(s): 
https://www.section.io/engineering-education/testing-for-broken-authentication-in-web-apps/

https://www.section.io/engineering-education/integrating-firebase-database-in-django/

#### Proposed title of article
 How to implement static maps Image in Vue

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Static map APIs allow an image of a non-interactive map to be included in a webpage. You get to render a map as an image, by specifying a coordinate.

#### Key takeaways 
At the end of this article, the reader should be able to understand:
1. What static map API is
2. How to render a map as an image in a vue application.
3. What OpenStreetMap is

#### Article quality
This article will cover the importance of static map images, how to implement them while leveraging on an open-source map (OpenStreetMap). This article is also going to be easy to follow through, and this is not much explored.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @shosenwales 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
