### ISSUE TITLE
Building a Stopwatch with JavaScript and Tailwind CSS

### ISSUE THREAD

**Issue by prince-joel** [section-engineering-education/engineering-education#7261]
Proposal Submission

Proposed title of article
Building a Stopwatch with JavaScript and Tailwind CSS

Proposed article introduction
Are you working on a project that needs a stopwatch or performing a task that requires timing? in this article, we will be building a simple stopwatch with JavaScript and styled with a CSS framework called Tailwind CSS.
If this is your first time using Tailwind, we will be learning briefly how to set up Tailwind CSS using the docs and get it ready for use.

Key takeaways
The reader will learn how to set up Tailwind
The reader will learn how to use Tailwind in their application
The reader will learn how to build a simple stopwatch
The reader will learn what JavaScript EventListener is and how to use it
The readers will learn how to automate activities in an application with the use of the stopwatch they have created
The readers will learn about the JavaScript functions that they can use to create an effective stopwatch.

References
N/A

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @prince-joel 
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
