### ISSUE TITLE
[Networking]Fundamental basics of Using Atoll tool for radio frequency network planning.

### ISSUE THREAD

**Issue by JGatura421** [section-engineering-education/engineering-education#7264]
### **Proposal Submission**

**### Proposed title of the article**

[Networking]Fundamental basics of Using Atoll tool for radio frequency network planning.

**### Proposed article introduction**

What is atill? Atoll is an open, scalable, and flexible multi-technology network design and optimization platform that supports wireless operators throughout the network cycle from initial design to densification and optimization (RF). It supports technologies such as - GSM/GPRS/EDGE, UMTS/HSPA, CDMA2000 1xRTT/EV-DO.

Radiofrequency(RF) is the oscillation rate of an alternating electric current or voltage or of a magnetic, electric, or mechanical system electromagnetic field or mechanical system in the frequency range from around 20 kHz to around 300 GHz. 

This article explains to the reader what the atoll tool is, how to plan a network or rf network using the software. In this article, the reader will get to know how to take advantage of the atoll user.

**### Key takeaways**

- Understanding RF
 - What is an atoll
 - How to use atoll
 -  Advantages of atoll tool

**### Article quality**

This in-depth tutorial will add so much value to the reader because along with learning about Atoll software and how to use it.

**### References**

[How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
[Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
[Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 


And this topic may be a bit outside of our wheelhouse.

https://www.google.com/search?q=Atoll+for+radio+frequency+network+planning&rlz=1C1CHBF_enUS891US891&ei=dstEYovmBs-x0PEP6KaluAs&ved=0ahUKEwiL-cvM4-72AhXPGDQIHWhTCbcQ4dUDCA4&uact=5&oq=Atoll+for+radio+frequency+network+planning&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEKIEOgcIABBHELADOgoIABBHELADEMkDSgQIQRgASgQIRhgAUPwHWM44YJU_aANwAXgAgAFmiAHpApIBAzMuMZgBAKABAcgBCMABAQ&sclient=gws-wiz
