### ISSUE TITLE
Working with CSV files in R

### ISSUE THREAD

**Issue by Stanw22** [section-engineering-education/engineering-education#7265]
### Topic Suggestion
Working with CSV files in R

#### Proposed title of article
Working with CSV files in R

#### Proposed article introduction
CSV stands for comma-separated values. Like any other programming language like java, R also supports CSV files. One can create, read, edit and even write CSV files utilizing R. A CSV file is popularly used to keep information in tabular form, where each row represents a record.

#### Key takeaways 
- How to create  CSV files in R.
- How CSV files are read in R.
- How to write in a CSV file using R.
- Different CSV operations in R.

#### Article quality
In this article am going to introduce the reader to comma-separated values in R. I will show the user how to create, read, and write into a CSV file utilizing R. I Am also going to handle different CSV operations utilizing R. Furthermore am going to use a beginner-friendly language and concepts to enhance understanding. I believe that the article will be of great value to the entire engineering community.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
