### ISSUE TITLE
biulding a eat out bill splitter using JS

### ISSUE THREAD

**Issue by ngaremoses** [section-engineering-education/engineering-education#7268]
Topic Suggestion
biulding a bill splitter and eat with friends.
Proposed title of article

Eating Out Bill Splitter with js

 Proposal Submission

 Proposed title of article
buildiing a bill splitter and eat with friends.
 Proposed article introduction

Key takeaways 
creating  a splitter eater.
learning how to use js 
getting knowledge on js usage
Article quality
this article will enable learners to gain skills on technology
References
n/a
 Conclusion
this will enhance learners create a split eater

**Comment by ahmadmardeni1** [comment]
There are a lot of grammatical mistakes and readability issues in your suggestion. Please read our docs and work on your writing skills before submitting a new topic. @ngaremoses
