### ISSUE TITLE
[Networking] No cable-No problem, the Quickest way to learn microwave data transmission and why it's better.

### ISSUE THREAD

**Issue by Sreign254** [section-engineering-education/engineering-education#7282]
#### Proposed title of the article

[Networking] No cable-No problem, the Quickest way to learn microwave data transmission and why it's better.

#### Proposed article introduction

Clearly, most people do use microwaves to transmit data more than they think. Microwave is cable-free communication that uses a line of sight and high-frequency beams of radio waves to transmit high-speed connection.
In this article, the reader will learn about microwave transmission and the different types of microwave, microwave link how to install a microwave, different types of microwave bands, and why it's better.
We shall briefly explain the ACM and ATPC adaptation on microwaves. We shall highlight the different uses of microwave links and also their advantages.

#### Key takeaways 

- Introduction to microwave.
- Types of microwave data transmission links.
- Different types of microwave bands.

#### Article quality

This will be the quickest way for a reader to learn about the depth of microwave data transmission links.

#### References

[How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
[Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
[Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Closing this PR because it is a bit outside out of wheelhouse. 

We're more interested in original, practitioner-focused, and software-based content that takes a deeper dive into programming-centric concepts. 
Please feel free to suggest an alternate topic to explore. 🚀
