### ISSUE TITLE
Getting started with vue 3

### ISSUE THREAD

**Issue by Geo-ogy** [section-engineering-education/engineering-education#7283]
**Proposed article introduction**
Vue 3 is the newest version of vue.js. Many changes have been made to vue 3.
In this article I will show you how to get started, by creating your first project.
I will take you through installation of vue 3 on your computer and show you in detail the new features added and the changes made compared to vue.js.

**Key takeaways**
•	After going through the article one should be able to use vue 3.
•	One should learn and understand the new features added and the changes made.
•	One should be able to start a new project with ease.

**Quality of the article**
This article will help developers start using vue 3 with ease.
In this article I will show you the right procedure step by step so as any one would be able to install and start a new project at first try.

**Comment by WanjaMIKE** [comment]
This topic appears to be well covered in the official documentation. Feel free to suggest another topic. Thanks
