### ISSUE TITLE
Using AMP to build web stories

### ISSUE THREAD

**Issue by Youngshark3** [section-engineering-education/engineering-education#7299]
#### Proposed title of article
Using AMP to build web stories

#### Proposed article introduction
The AMP story contains the AMP-story page that has layers inside. Layers in the AMP story page include the images and various text you intend to use.
The <amp-story> is the complete web story responsible for creating the shell of the interface of the story.
AMP story is a component in which we will add the script to the code. Think of the AMP story as a noticeboard that allows people to display messages on it, like posters and memos.

#### Key takeaways 
- Good understanding of HTML.
- Good understanding of CSS
- Some knowledge in Glitch
- Knowledge in boilerplate.
#### Article quality
I will be building a product to explain more of what i will be talking about. I will be glad to handle deeply all the tasks while elaborating.

**Comment by Youngshark3** [comment]
@M0nicah check out my new issue

**Comment by WanjaMIKE** [comment]
Let's wait until the other issue is closed.
