### ISSUE TITLE
Realtime traffic monitoring Spring Boot application

### ISSUE THREAD

**Issue by qawuor** [section-engineering-education/engineering-education#7305]
### Writing sample(s): 
Include any links or writing samples to help our team gauge your writing quality better.

#### Proposed title of the article
Realtime traffic monitoring Spring Boot application

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Traffic jam is a significant problem in any city or town. The cities and towns have a lot of traffic jams, and it is challenging to find out where the traffic jams are. TomTom traffic API provides traffic information that we can use to identify traffic before it occurs. We can also use the TomTom traffic API to determine the areas with the highest traffic jams and the areas with the lowest traffic jams. 

With a traffic monitoring system, taxi drivers can always see the route with the possibility of having a traffic jam or the road with a traffic jam. I will provide a step by step process of integrating TomTom traffic API into a Spring Boot application for efficient traffic monitoring. 

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
1. Integrating Spring Boot application with TomTom API
2. Creating a Traffic monitor user interface with TomTom API, Thymeleaf.
3. Displaying realtime traffic data on the monitor interface.

#### Article quality
With the unresolved traffic jams on major highways, the knowledge on how to develop a traffic monitor that can help users avoid traffic jams is essential. Unfortunately, most available publications only concentrate on the route and directions on the maps neglecting the necessary traffic jam monitoring APIs.

#### References
Please list links to any published content/research you intend to use to support/guide this article.
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@qawuor 
We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
