### ISSUE TITLE
[Android] Creating a Scratch pad with Jetpack Compose

### ISSUE THREAD

**Issue by anne-sogoli** [section-engineering-education/engineering-education#7308]
#### Proposed article introduction
Jetpack Compose makes it easier to work with custom graphics. Many apps need to be able to precisely control exactly what's drawn on the screen. This might be as small as putting a box or a circle on the screen in just the right place, or it might be an elaborate arrangement of graphic elements in many different styles. With Compose's declarative approach, all the graphic configuration happens in one place, instead of being split between a method call and a Paint helper object. Compose takes care of creating and updating the needed objects in an efficient way.

Compose extends its declarative approach to how it handles graphics. Compose's approach offers a number of advantages:
- Compose minimizes the state in its graphic elements, helping you avoid state's programming pitfalls.
- When you draw something, all the options are right where you'd expect them, in the composable function.
- Compose's graphics APIs take care of creating and freeing objects in an efficient way.

In this tutorial, we are going to use different aspects and concepts of compose graphics to come up with a scratch card from scratch 😁.

#### Key takeaways 
- Introduction to compose graphics.
- How does compose rely on the view-based UI's Canvas and other associated objects?
- Creating a scratch pad with compose.

#### Article quality
The article will not duplicate what is already in the docs but will use those concepts to come up with something. From the article, the reader can see how he/she can apply compose graphics in their projects.

#### References
- N/A

**Comment by ahmadmardeni1** [comment]
Great suggestion! 
What do you mean by "come up with something"? @anne-sogoli

**Comment by anne-sogoli** [comment]
Hello @ahmadmardeni1, sorry for not being clear, by coming up means I will use compose graphics to create (implement) a scratch pad app from scratch.  Meaning that I will not be writing what is already in the docs but using the docs as reference to coming up with the scratch pad app.

Thank you in advance.

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @anne-sogoli 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@anne-sogoli 
We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
