### ISSUE TITLE
innovative memory management  with v programming

### ISSUE THREAD

**Issue by MG-44** [section-engineering-education/engineering-education#7310]
Topic suggestion 

Innovative Memory Management with V Programming 

Proposed article introduction 

The v programming language avoids unnecessary allocations by using value types, string buffers and promoting an abstraction free code style. 

V's auto free engine frees most objects in that the compiler inserts necessary free calls automatically during compilation. The remaining small percentage of objects is freed through garbage collection(GC) systematic recovery process. The developer does not need to change anything in their code since it works like in go java or python except there is no heavy GC tracing everything 

Key takeaways 

- Small and easy to build compiler 
- Compiles to native binaries without dependencies  
- Hot code reloading 
- C translation 
- Performance fast as c 
 
Article quality 

The article will be beginner friendly and simplified enabling developers to have better memory management through fast compilation of objects in programs.

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @[MG-44](https://github.com/MG-44)
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
