### ISSUE TITLE
Load testing a Django Application With Locust

### ISSUE THREAD

**Issue by Olamidun** [section-engineering-education/engineering-education#7311]
### Topic Suggestion
How To Use Locust to Load Test Django Applications

#### Proposed title of article
Load Testing Django Applications With Locust

#### Proposed article introduction
Load testing is the practice of testing how an application performs when a lot of users start using it concurrently. The load referred to here is simply the various requests being made to that application at the same time by the users.

Often times we build applications and we have no idea how they will perform when hundreds or even thousands of users try to use it concurrently until we launch them. How do we properly test our applications to make sure they can handle hundreds or even thousands of concurrent requests from hundreds or even thousand of users so we can sit back and have that deserved cup of coffee after launching? This is what we will learn in this article, we will also learn about one or two database optimization functions in Django to further boost the performance of our application.

#### Key takeaways 
- Learners will learn how to test the behavior of their applications when a lot of users try to use it
- Learner will learn about some database optimization tools in Django
- Learners will learn how to use Faker library to generate data for their database to simulate production database

#### Article quality
- My article aims to explain load testing concepts to learner as simple as possible by building a real project.
- My article also cover addition topics like database optimization through Django ORM which will be useful in building performant applications.

#### References
Locust documentation: [Locust](https://locust.io/)
Django documentation: [Django](https://docs.djangoproject.com/en/4.0/)
Faker documentation: [Faker](https://faker.readthedocs.io/en/stable/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Sounds like a helpful topic - let's please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it). @Olamidun 

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting it for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double-check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
