### ISSUE TITLE
Using Cryptography for Network Security in Java.

### ISSUE THREAD

**Issue by OkanyO** [section-engineering-education/engineering-education#7312]
Proposal Submission

How to use Cryptography for Authentication Security with Java.

Proposed title of article

Build Authentication security Using Cryptography with Java.
 
Proposed article introduction
Cryptographic functionality is essential to a massive number of applications.  As data protection regulations mandate how certain types of data should be protected, developers are increasingly required to build cryptography into their code. Java is currently one of the most popular programming languages used across a wide range of application, so it’s important that developers know what to consider when implementing Authentication security using cryptography correctly with java.
Key takeaways

From this article the reader will be able to:

    Get to know Key Exchange with Symmetric Cryptography.
    Understand how to use Timestamps to Establish Freshness.
.   Understand how we can use Nonce's to Establish Freshness.
    Get to know how to implement Authentication using cryptography

Article quality

This article will cover as much not only explaining to the reader the steps involved in building Authentication security using cryptography with java, but also demonstrate to the reader how we can build authentication security using cryptography with java.

References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
We are only accepting one topic per contributor until a PR is merged. Thanks
