### ISSUE TITLE
Understanding BlockingQueue in Java

### ISSUE THREAD

**Issue by tesswambui** [section-engineering-education/engineering-education#7315]
### Topic Suggestion
Understanding BlockingQueue in Java
#### Proposed title of article
Understanding BlockingQueue in Java
#### Proposed article introduction
The queue is a well-organized collection of items in which new items are added from the back and old items are removed from the front. Java queue that supports operations that are awaiting a response from the queue to be hollow when retrieving and removing an item, then waits for the memory space to be available again when adding an object is called `BlockingQueue`. BlockingQueue in Java is utilized to implement the producer-consumer problem.
#### Key takeaways
- Classes used to execute BlockingQueue.
- BlockingQueue syntax.
- Methods utilized to execute the BlockingQueue.
- BlockingQueues of various sorts.
- Operations performed on the BlockingQueue.
- Characteristics of BlockingQueue methods.
#### Article quality
In this article am going to introduce user to the BlockingQueue interface in java, classes that implement BlockingQueue, syntax, methods used to implement the BlockingQueue, operations performed, and characteristics of methods used to implement the Queue. Am going to use beginner friendly examples when explaining the concept to the reader.
#### References
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/BlockingQueue.html

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Please feel free to suggest an alternate topic to explore. 🚀
