### ISSUE TITLE
Understanding Simulation as probabilistic tool.

### ISSUE THREAD

**Issue by AcharaChisom** [section-engineering-education/engineering-education#7319]
Proposed title of article
Understanding simulation as a probabilistic tool.

Proposed article introduction
Simulation is one of the most counter-intuitive tool in our modern day arsenal of tools for solving problems, and sci-fi movies sure doesn't help in that regard. What makes simulation so confusing is mainly due to the fact that it requires viewing the world as having different virtual counterparts i.e how does the same situation occur in different worlds.

The Concept of Simulation
Simulation involves setting up a virtual world that follows the same rules as reality.
It is a probabilistic tool that can surprisingly make complex probabilities easy to calculate.
The current space program of sending rovers to mars provides an ideal example of how simulation can be applied and we shall explore it in this article.

Key takeaways

- The reader will understand the concept of simulation.
- The reader will understand how the rule of sum aids in simulations.
- The reader will understand how to create the specific rules for a virtual event in simulations.
- The reader will go through a practical application of simulation as a problem solving tool.

Article quality
This topic will focus mainly on a real practical application of simulation to a probabilistic problem.

References
None

Conclusion
After reading the article, you will hopefully be more appreciative of simulations and be able to apply it to other problems related to simulations that you have.

**Comment by hectorkambow** [comment]
@AcharaChisom 
We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
