### ISSUE TITLE
[Language] How to Create Page Animations with Granim.js

### ISSUE THREAD

**Issue by Eric-mburu** [section-engineering-education/engineering-education#7320]
### Topic Suggestion
[Language] How to Create Page Animations with Granim.js

#### Proposed title of article
[Language] How to Create Page Animations with Granim.js 

#### Proposed article introduction
Granim.js is a lightweight, dependency-free JavaScript library that creates interactive and fluid gradients animations. It helps develop custom full-color gradient transitions that link nicely and look smooth with any website. It is designed on vanilla JavaScript to run alongside jQuery or other JS libraries. 

Website animations are essential as they attract the attention of the user. They help distract the users when the content is loading to make it appear quicker and enable them to view progress upfront. It keeps your visitors longer on your site by increasing their interest and encouraging more shares and revisits.

#### Key takeaways 

•	What is Granim.js
•	Importance of page animation in your website
•	How Granim.js is used to create page animation

#### Article quality
The article will not duplicate what is already in the docs but will apply those ideas to develop new ideas. From the article, the reader will understand how to create page animations with Granim.js to encourage users to stay longer on their sites and encourage more shares and revisits.

#### References
N/A

**Comment by louisefindlay23** [comment]
Topic approved. Be sure to add lots of detail to provide great value to our readers.

**Comment by hectorkambow** [comment]
@Eric-mburu 
We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
