### ISSUE TITLE
How to classify digits using simple classifiers in Matlab

### ISSUE THREAD

**Issue by atienodorine3** [section-engineering-education/engineering-education#7329]
### Topic Suggestion
How to classify digits using simple classifiers in Matlab

### Writing sample(s): 
https://www.section.io/engineering-education/wavelet-transform-based-denoising-of-images-using-matlab/

#### Proposed article introduction
A classifier in machine learning is an algorithm that automatically orders or categorizes data into one or more of a set of “classes.” For example, the simple classifier classifies three processes. These processes are such as low-level, mid-level and high-level processes. Different activities, which we will later cover in this tutorial, are carried out in each of these processes.

We will learn how to classify digits using a simple classifier. When you are navigating the robot, the robot should be able to understand signs, shapes and objects. This tutorial covers a basic digit classifier which you can later extend for any low-level feature-based object classifier.

#### Key takeaways 
- Getting the feature descriptor of the images.
- Digit dataset.
- Matlab code to classify images using classifiers.
- How to evaluate the Digit Classifier.

#### Article quality
This article covers how we can use simple classifiers to classify digits. We see the process of creating these classifiers and evaluating their performance.

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved
