### ISSUE TITLE
Controlling web pages visible to different users using PHP

### ISSUE THREAD

**Issue by davidokoth006** [section-engineering-education/engineering-education#7330]
#### Proposed title of article

[Language]Controlling web pages visible to different users using PHP

#### Proposed article introduction

There are different categories of users who access a website at any given time. Certain pages in a website are meant to be accessed by specific users. For instance, web pages that are accessed by the system administrator may not be the same as the pages which are accessed by the general users. When deploying critical websites for banks and other organizations with critical user details for example the Directorate of criminal investigation website, protection of the pages is a must.

Due to this reason, it is important to protect certain web pages in order to control user access. This article aims at educating the learner on how they can ensure that their web pages are protected.

#### Key takeaways 
The learner will be able to;

1. create login and logout pages.
2. construct web pages easily using bootstrap.
3. control user access to the pages created.
4. construct a database and connect it to the web pages created

#### Article quality
This article will help the reader protect the web pages thus practicing user access control.

#### References
N/A

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved


https://www.google.com/search?q=Controlling+web+pages++using+PHP&rlz=1C1CHBF_enUS891US891&ei=Z2lHYsCiGbGs0PEPv-GVyA4&ved=0ahUKEwiA8tjA4vP2AhUxFjQIHb9wBekQ4dUDCA4&uact=5&oq=Controlling+web+pages++using+PHP&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQ0gJY0gJg2whoAXABeACAAVSIAVSSAQExmAEAoAEByAEIwAEB&sclient=gws-wiz

**Comment by hectorkambow** [comment]
@davidokoth006 
We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.

**Comment by davidokoth006** [comment]
Hello
I would like to continue with the article. I'm positive it will add value.
I'm requesting that you let me continue with the topic discussion.

**Comment by WanjaMIKE** [comment]
Closed #7622 via #7330
