### ISSUE TITLE
[Machine Learning] Understanding Matrix Correlation and How to Use them for Dimensionality Reduction with Heatmap in Python

### ISSUE THREAD

**Issue by Daniel695** [section-engineering-education/engineering-education#7337]
#### Proposed title of the article
Understanding Matrix Correlation and How to Use them for Dimensionality Reduction with Heatmap in Python

#### Proposed article introduction
Correlation is the statistical technique that measures how linearly two variables are related. In simple terms, this concept measures the dependence between two variables. In many cases, the dataset has more than two variables. Now, our task is to find the correlation between all the variables in the dataset. In such a case, we compute the correlation coefficient for each feature with respect to all other fetaures and store the values in a matrix. A matrix created out of the correlation between columns of a data matrix is called a *Correlation matrix*. 

The correlation between two variables can be measured using the following methods:

- **Pearson correlation coefficient:** This method measures how values of two distinct factors vary with respect to each other. We can compute the Pearson correlation coefficient between two variables, say X and Y using the formula:

$\Large= {\frac{\sum \,(X - \bar X)\,(Y-\bar Y)}{\sqrt{\sum (X - \bar X)^2\,(Y-\bar Y)^2}}}$

- **Rank correlation coefficient:** This method measure the extent to which one variable increases or decreases as the other variable increases or decreases.

The value of correlation can only take the values between -1 and 1. If this coefficient between two variables is zero, there is no dependence between the two variables. When the correlation between two variables is -1, it means that the two variables have negative dependence on each other; that is, as one variable increases, the other decreases. When the correlation coefficient is positive, it implies a positive relationship between the two variables, i.e., as one variable increases, the other variable increases. From these possible values of a correlation between any two variables, we can summarise that the correlation coefficient can either be:

1. Positive Correlation
2. Negative correlation
3. Zero correlation

In practice, we encounter big data, data with many features. As it is a common experience in data science, not all variables have a great contribution to the analysis. Features with least or none contributing to the study variable can only add complexity to the analysis. This makes it expensive and time-consuming to train models on a dataset. Furthermore, the final model is usually very likely to suffer from the risk of overfitting, hence ending with poor generalization. Due to these problems, it is essential to study the dataset and extract variables that significantly contribute to the analysis. The correlation matrix is one of the techniques used in obtaining covariates with significant contributions to the analysis from noisy data.

A must requirement in data analysis is that features should be unrelated. Using the features set, we can find their correlation against each other and get rid of one of those show a strong dependence.

That is what this article aims to do. Since we can't handle big matrices by hand, we shall carry out our operation in Python using a famous correlation map known as correlation Heatmap. However, because we can't handle big data by hand, it doesn't mean we only rely on the software functions and end up not knowing how those computations happen. These computations are not visible at the implementation level. This said we will work on a manageable matrix and outline how we compute a matrix correlation step by step. With this knowledge, the implementation output will not leave the learner in surprise.

Once shown how the correlation matrix is computed from the data matrix, we shall use real-world data on which we will compute the correlation between each feature and all the rest and store results in a correlation Heatmap.

#### Key takeaways 
1. What is the correlation
2. Methods for determining the correlation between two variable
3. Correlation interval and the types of correlation between two variables 
4. How to compute a correlation between two variables using the Pearson correlation coefficient
5. How we plot a correlation Heatmap on a dataset in Python
6. How to identify correlated variables in a Heatmap output
7. Getting rid of highly correlated variables from a dataset through the correlation Heatmap in python

#### Article quality
This article is going to cover the topic from the basics to higher levels, where we put everything we shall have learned into real-world application. Also, we do not intend to load the learner with irrelevant information, so we will be very precise, ensuring we only provide what they need to get the most out of the material optimally. That's all about this project.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Matrix+Correlation+and+How+to+Use+them+for+Dimensionality+Reduction+with+Heatmap+in+Python&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
