### ISSUE TITLE
Why Kafka Is The Future Of Messaging

### ISSUE THREAD

**Issue by jaykip** [section-engineering-education/engineering-education#7357]
#### Proposed title of article
Why Kafka Is The Future Of Messaging

#### Proposed article introduction
You've heard that Apache Kafka and messaging brokers were cut from the same cloth, so how is it possible that Kafka is so much better? The answer is simple: Apache Kafka gives you what traditional message brokers can't - simplicity, scalability, and a trusted platform.

In this article, I'm going to explain why Apache Kafka is the future of messaging and how you can use Kafka to modernize traditional messaging brokers like the Java Messaging Service (JMS). 
#### Key takeaways 
1. How Kafka Is Different from traditional message brokers:
- Kafka Allows for An Event Driven Architecture
- Kafka Lets You Handle Large Volumes of Data Efficiently
- Kafka Is Designed for High Throughput
- Kafka Allows for Multi-Platform Integration
- Kafka Supports Multiple Message Formats

2. Using Apache Kafka to replace traditional message brokers; a case in point is Java Messaging Service (JMS)
3. Kafka for data pipelines 
#### Article quality
Any new technology on the rise will always be compared with existing technology. This comparison is useful as it contrasts Apache Kafka with traditional message brokers such as Java Messaging Service (JMS). 

#### References
https://kafka.apache.org/documentation/

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

https://www.google.com/search?q=Kafka+Is+The+Future+Of+Messaging&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
