### ISSUE TITLE
[Languages]Best Autopilot setup for Django Backend Development 

### ISSUE THREAD

**Issue by mercymeave** [section-engineering-education/engineering-education#7363]
### Writing sample(s): 
https://www.section.io/engineering-education/authors/mercy-meave/

#### Proposed title of the article
Best Autopilot setup for Django Backend Development

#### Proposed article introduction
Most developers know how to write software in Django. However, we should consider that code is read more than it is written. For this reason, we need to follow some of the conventional best practices to write code that is maintainable and readable.

This tutorial intends to put on the best practices for writing readable and maintainable Django code by putting together several packages that work together to achieve this goal. It intends to utilize various libraries to automate testing, code formatting, automatic deployment, dependency management and pre-commit hooks.

We will build a project that follows standard folder organization, automatically re-structure code according to PEP8 standards, manages our dependencies without using the `requirements.txt` file, which gets filled with unnecessarily complicated to track modules when we run `pip freeze` and automate imports sort and testing. Lastly, we will configure a pre-commit hook that ensures all these are done before a commit is done to the repository. In addition, we will add a GitHub action that triggers the tets when a push is made to the repo.

#### Key takeaways 
1. Django best practices
2. Writing testable and readable code
3. Automated testing with pre-commit hooks and GitHub actions
4. Best practice dependency management.

#### Article quality
While most articles have used these libraries in their documentation only, this article intends to build a working Django project with key features set up and illustrated to the readers.

#### References
Please list links to any published content/research you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by WanjaMIKE** [comment]
Closed #7363 via #7554
