### ISSUE TITLE
Get started with Next.js and deploy your Next.js app on vercel

### ISSUE THREAD

**Issue by Dennis-star1001** [section-engineering-education/engineering-education#7365]
### Proposal Submission
Proposed title of the article
Get started with Next.js
### Proposed title of the article
In this article, I’m going to explain what Next.js is all about, breakdown the processes in creating a Next.js application and also explain how to deploy a Next.js application on Vercel   
Key Takeaways
At the end of the article, the reader shall be able to
•	Understanding What Next.js is all about.
•	Understand the purpose of a Next.js.
•	Create a Next.js application.
•	Run a Next.js application.
•	Understand the structure of Next.js folder structure.
•	Understand the concept of dynamic routing and routing in Next.js.
•	Deploy a Next.js application.
Article Quality
This in-depth article will add so much value to reader. This will really make the reader understand the basic concept of Next.js and also help the create a Next.js application with ease.
References
N/A

**Comment by Dennis-star1001** [comment]
Alright.
Thank you.

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
