### ISSUE TITLE
Session vs. Cookies in php

### ISSUE THREAD

**Issue by popoolatopzy** [section-engineering-education/engineering-education#7366]
#### Proposed title of article
###Session vs. Cookies in php

#### Proposed article introduction
*This article will help readers  to understand the following: 

> What session and cookies is
> how session and cookies works 
> Differences between php session and cookies. 
>  When to use session and cookies,
> advantages of session 
> advantages of cookies 
> Limitations of session and cookies.
> how to use session 
> how to use cookies 
>how to create app using session and cookies

**Comment by WanjaMIKE** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
