### ISSUE TITLE
[Languages] A Beginner's Guide to Rollup JavaScript Module Bundler 

### ISSUE THREAD

**Issue by EssyG10** [section-engineering-education/engineering-education#7370]
#### Proposed title of the article

A Beginner's Guide to Rollup JavaScript Module Bundlers

#### Proposed article introduction

JavaScript files may be combined into one file using `javaScript rollup bundler`, which is a programming tool. Rollup bundlers evaluate your initial code files and generate a dependency graph. This means that the rollup module bundler maintains track of both your source file and the dependencies of other parties. Using this dependency structure, you can ensure that all of your dependent files are up to date and error-free. Prior to the advent of bundlers, things were a lot more difficult than they are now. It was a challenge for web developers to keep track of all the files and their dependencies. In this article, we will have a good understanding of `Rollup JavaScript Bundler` and how we can implement it in our JavaScript projects.

#### Key takeaways

By studying this article learners will be entitled to:

- Understanding the in-depth Rollup module Bundler
- The working of Rollup Javascript Bundler
- Popular Rollup JavaScript module bundlers
  - Esbuild
  - Browserify
  - parcel
  - rollup

#### Article quality

Due to rapid changes in the last few years in javaScript, we are past manually including jQuery, Bootstrap, or React on every page of our site but rather bundling everything up into one `static file` that you can load with just a single line of code. Module bundlers are the norm today and offer a hand in a way to organize and combine many files of JavaScript code into one file. For beginners and intermediate JavaScript, learners will get to know how bundler can be utilized when a project becomes too large for a single file or when a project includes working with libraries that have multiple dependencies. Detailed walkthrough with workable examples will be provided to ensure readers have all that it takes to switch to the new way and norm of js bundling rather than the traditional old way

#### References

N/A

**Comment by louisefindlay23** [comment]
Thanks, @EssyG10. How will your article be unique from similar articles such as [this one](https://snipcart.com/blog/javascript-module-bundler)?

**Comment by EssyG10** [comment]
@louisefindlay23 thanks for the question. From the proposed article I intend to introduce beginners in one type on js bundler module which is `rollup` bearing in mind from the blog you have just referred me to have generalized a couple of modules but for this one, beginners will be introduced to rollup and how they can  actually utilize it to be inline with the tradition today that you don't need to manually include developer files such as bootstrap,jQuery among others but instead work with bundler modules to ease their development. Thanks
