### ISSUE TITLE
Building a Twitter Bot with JavaScript

### ISSUE THREAD

**Issue by Titusian72** [section-engineering-education/engineering-education#7371]
#### Proposed title of article
Building a Twitter Bot with JavaScript

#### Proposed article introduction
Twitter is an online news and social networking site where people communicate in short messages called tweets. Tweeting is posting short messages to anyone who follows you on Twitter, with the hope that your words are useful and interesting to someone in your audience. 
In this article, we will be creating a Twitter bot that can retweet, tweet, and like posts.

#### Key takeaways 
1. Apply for a Twitter Developer Account
2.  Setup Project
3.  Setup Files
4. Coding the bot

#### Article quality

This article will give the learner a step-by-step guide on how to build a Twitter bot and an overview of Twitter API along with its features.
#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=Building+a+Twitter+Bot+with+JavaScript) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by Titusian72** [comment]
@louisefindlay23  I feel that knowledge cannot be exhausted, and when I look at similar stuff online, I find that the vast majority is not novice-friendly or as fascinating as it could be. Of course, this article will be unique, and it will gracefully address these flaws in order to retain quality and bring value to the community. Thanks

**Comment by louisefindlay23** [comment]
@Titusian72, so can tell me what specific areas or points you will make that are not covered elsewhere?

**Comment by hectorkambow** [comment]
@Titusian72 
We will be closing this Topic due to inactivity: It can be re-approved at a later date if you'd like to continue working on it and add it to your EngEd author profile.

 Note: it has to be re-approved in case another student or site has published similar content.
