### ISSUE TITLE
[Containers] A Guide To Running Ubuntu Machine and Containerizing Python Application on Windows Powershell Core

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#7373]
### Topic Suggestion
[Containers] A guide to running the latest Ubuntu OS and deploying Python Application on Windows Powershell Core

#### Proposed title of the article
[Containers] A guide to running the latest Ubuntu OS and deploying Python Application on Windows Powershell Core

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Virtually all the time before containers came into the picture, developers worry about operating system differences while testing an application developed from another os locally. Also, the operations team have to worry a lot about the dependencies, libraries for applications before running on a different platform that was not developed. This problem was abstracted away by containers which makes it easier to keep track of libs in all os. 

Ubuntu is one of the major Linux distros that are widely used. Running containers on it is keen to develop and production platform too. In this article, I will be sharing the easier steps to run Linux/ubuntu containers on the windows platform which is required for testing purposes and deployment.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
- Basic Linux commands
- Overview of Containers and how it works
- Steps to running ubuntu image on Windows PowerShell core
- Local deployment of Python Application

#### Article quality
Most of the time developers struggle to get Linux os on their Windows platform either by a virtual machine or partitioning the hardware. This tutorial will solve the problem by introducing the new concept of running Linux on windows through containers without any stress or cost of hardware resources.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Horlawhumy-dev** [comment]
@ahmadmardeni1 sir, this was the topic I came up with following the recent closed issue. Please let me work on this because it has not been covered on section.

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
cc: @section-engineering-education/content-moderator-team 
Unless im missing something here team 🔍 

I'll refer to your background expertise

**Comment by WanjaMIKE** [comment]
Closed #7373 via #7562
