### ISSUE TITLE
Cirq for Quantum Computing

### ISSUE THREAD

**Issue by splashtonia** [section-engineering-education/engineering-education#7378]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Cirq for Quantum Computing

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Cirq is an open-source framework built by the Google AI Quantum Team in 2018. It is a Python software library for writing, manipulating, and optimizing quantum circuits, and then running them on quantum computers and quantum simulators. Cirq provides useful abstractions for dealing with today’s noisy intermediate-scale quantum computers, where details of the hardware are vital to achieving state-of-the-art results.
This tutorial will give an overview of the framework and demonstrate to our readers how they can use this framework to learn about Quantum computing.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- An Overview of Cirq.
- Learn about essential concepts of the framework.
- Implement an example to demonstrate how to use the framework.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Quantum computing is still in its early stages. It might be hard to grasp concepts about Quantum computing. With open-source frameworks such as Cirq, learning about quantum computing is easier. This tutorial will simplify the learning process by demonstrating to our readers how they can get started learning about Quantum computing.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [Cirq](https://quantumai.google/cirq).
- [GitHub](https://github.com/quantumlib/cirq).

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=Cirq+for+Quantum+Computing) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by splashtonia** [comment]
> Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=Cirq+for+Quantum+Computing) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

There are two main programming languages/libraries for quantum computing; Cirq and Qiskit. Many beginners are never sure which one is the best to use. But here, I’m going to cover some of the similarities, differences, pros and cons, and also go through some learning resources and how to find interesting papers and projects that you can do, for both Cirq and Qiskit, to help you decide which to learn.
