### ISSUE TITLE
Remix JS: Is IT The Next-Generation React Framework You Should Use?

### ISSUE THREAD

**Issue by julie-techie** [section-engineering-education/engineering-education#7414]
### Topic Suggestion
Remix JS: Is IT The Next-Generation React Framework You Should Use?

#### Proposed title of article
Remix JS: Is IT The Next-Generation React Framework You Should Use?

#### Proposed article introduction
Remix JS is a full-stack web framework that supports server-side rendering. Also, it lets you build fast, slick, and resilient websites. It is one of the newer web frameworks built on React JavaScript framework. This article will describe the differences between Remix JS, Next.js, React, or other React-based frameworks of your choice and what use cases Remix JS is best suited for.

#### Key takeaways 
1. Introduce Remix JS to readers.
2. Answer the question, Is Remix JS the next-generation framework you should use

-  Give a comparison of Remix JS to other React frameworks (React, Next.js)
- These are comparison points the article will look at:
    - Static site generation and server side rendering
    - Routing
    - Cookie and session support.
    - Styling.
    - Data handling
    - Form handling

#### Article quality
This unique article will serve readers with in-depth content about Remix JS. It will also compare Remix JS with other React frameworks in regard to styling, cookie and session support, static site generation and server-side rendering, etc. The content the article will cover is unique and isn't published in other sources.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. There are several articles that cover the exact topics you propose.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
