### ISSUE TITLE
[Languages] Building an Image Resizing Application  with Computer Vision and Python Tkinter

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#7415]
### Proposal Submission
Building an Image Resizing Application using Computer Vision and Python Tkinter GUI Framework.
#### Proposed title of article
Building an Image Resizing Application with Computer Vision and Python Tkinter

#### Proposed article introduction
Computer vision has opened up many possibilities through the OpenCV Library involving image operations. Resizing an image is one of the image operations which involves changing the dimensions of the image, be it width, height or changing both of them. This also preserves the aspect ratio of the original image in the resized image. To achieve this, we will cover much in this article explaining and showing how one can build an Image Resizing application using the Graphical User Interface (GUI) framework, Tkinter, together with the OpenCV library. 
The application will enable the user to upload and preview the image to resize displaying the image dimensions on the interface. The user will then be able to resize and change the dimensions of the original image. The resizing application will provide an option for previewing the resized image and saving it locally to the machines.

#### Key takeaways 
From this article the reader will be able to:
- Understand Image resizing in Computer Vision.
- Understand how to create User Interfaces using the Tkinter GUI framework.
- Understand how we can integrate the OpenCV library and the Tkinter Framework in building an Image resizing Application.

#### Article quality
This article, will be different since it will cover how image resizing is done using the OpenCV library in computer vision, demonstrate how we can build a graphical user interface application that allows the user to upload images, resize, preview, and download the resized images preserving the aspect ratio of the original image
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator. Including articles that are an exact match for the topics you propose.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
