### ISSUE TITLE
Getting started with RestFul web API in Dart programming

### ISSUE THREAD

**Issue by josephotienoowino** [section-engineering-education/engineering-education#7416]
#### Key takeaways 
By the end of completing reading this tutorial the learner or reader will gain:

- Basic knowledge in Dart language
- Gain knowledge on how to build restful api in Dart
- Be able to deploy web application in Dart

#### Article quality
hope that the article is a new topic.
#### References
Dart programming language
### Conclusion
Finally, after going through this tutorial you will gain knowledge in building Web APIs using Dart language and be able to determine the importance of using Dart to JavaScript.

**Comment by hectorkambow** [comment]
👀  

@josephotienoowino  

The content provided here seem a bit light for us to make an informed decision - I'll refer to the expertise of the @section-engineering-education/content-moderator-team for more insight.

**Comment by ahmadmardeni1** [comment]
Agree with you @hectorkambow 

This topic is already covered by a lot of tutorials. Please feel free to suggest a new topic to explore! @josephotienoowino
