### ISSUE TITLE
Quick guide in command-line and server application in Dart Programming

### ISSUE THREAD

**Issue by AndrewOdera** [section-engineering-education/engineering-education#7422]
#### Proposed title of the article

Quick guide in command-line and server application in Dart Programming
#### Proposed article introduction
In this tutorial the learner will be able to learn how to create command-line application and servers using some of the commands that will be shared in the tutorial. The programmers will be created in the Dart Virtual machine command-line where recourses are based mostly on command-line application. We will also show a standard outputs and error free during application building.

#### Key takeaways 
By the end of this tutorial the learner will be able to gain knowledge in:

- Building there first application in Dart.
- Deploy servers using Dart.
- Able to use command-line applications

#### Article quality
Hope the articles has the best quality as the previous article I wrote in section.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
