### ISSUE TITLE
[Android] How to configure two-factor authentication (2FA) in SSH in CentOS 6 using google authenticator.

### ISSUE THREAD

**Issue by Lavenda99** [section-engineering-education/engineering-education#7423]
How to configure two-factor authentication (2FA) in SSH in CentOS 6 using google authenticator.
 
Proposed article introduction
Secure Shell(SSH) allows you to access the server in a variety of ways. Password login, key-based login, and two-factor authentication are all options. Therefore, there may be another way to protect your server after changing your SSH port, fixing a hole knocker, and making some SSH security changes: using two-factor authentication. Someone may need your mobile device to access your SSH two-factor authentication (2FA) server. This can help you to prevent aggression and unauthorized logging attempts.

Advantages offered by two-factor authentication.
- Two-factor authentication offers the highest level of security. 
- Even if your computer is stolen, the attacker will still need access code to sign in. 

In this guide, I will show you how to set up two-factor authentication on your CentOS 6 server using SSH and Google Authenticator.

 Key takeaways 

- Install the required packages.
- Configure the software.
- Configure google authentication on your mobile app.

 Article quality
The article will not duplicate what is already in the documents, but instead build on those ideas to create something new. The student will learn to use graphic design in their projects after learning this lesson.

 References
- N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic.
