### ISSUE TITLE
Non-concurrently executing Vue 3 and Deepgram subtitles

### ISSUE THREAD

**Issue by Wendymwangi** [section-engineering-education/engineering-education#7424]
#### Proposed title of the article

Non-concurrently executing Vue 3 and Deepgram subtitles

#### Proposed article introduction

* This article will cover how to use Vue 3 composables to power a text-captions component that integrates with Deepgram's speech-to-text API and also illustrate how to build the `AudioCaptions.vue`. Some of the things covered in this article are:

1. Using `async` and `await` to write a composable that fetches a temporary API key from Deepgram.
2. Using Vue 3's `watch` method to react to data that is updating in real-time as Deepgram sends a text transcription back through a browser WebSocket.
3. Writing logic that is sensitive to the order things occur - i.e., asynchronous logic that flows between the component and the composable.

#### Key takeaways 

* By the end of this article, the following is expected;

1. Composables and Asynchronous Logic
2. Composable Using Async and Await
3. Composable That Relies on Asynchronous Events in Other Composables

#### Article quality

This article will be on point, simple to understand, well formatted and I'm sure users will be able to learn the procedure of building the `AudioCaptions.vue`. The code snippets in this article will be simple to understand and implement. I hope we will have a good ride all along.

#### References

N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
