### ISSUE TITLE
Creating floating elements using Floating UI in React

### ISSUE THREAD

**Issue by vogue01** [section-engineering-education/engineering-education#7426]
#### Proposed title of the article
Creating floating elements using Floating UI in React

#### Proposed article introduction
Elements that seem to "float" above the user interface without interfering with its content are known as floating elements. When a user hovers over a certain location of a website, a floating element known as a tooltip appears. User onboarding routines, reminders, and more may all benefit from tooltips, which can be used in a variety of ways.

Popper, a JavaScript library for producing floating items, has been around for a long time. There are a number of advantages to using a floating UI. It may be used in both React and React Native projects since it is cross-platform compatible.

#### Key takeaways 
- Showing tooltips on hover
- The computePosition function and middlewares
- integrating Floating UI with React

#### Article quality
Floating UI is a new player in town and most of the available article in the internet are talking of Popper. We shall create a unique project to achieve the goal of the article and add a new concept to the community. In this article, we shall walk through floating UI, how it works, its different features, how to integrate it into React applications and much more.

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
