### ISSUE TITLE
Learn how to create snake game in python

### ISSUE THREAD

**Issue by Shee254** [section-engineering-education/engineering-education#7429]
#### Proposed title of the article
Learn how to create snake game in python

#### Proposed article introduction
In this article, I will teach you how to come up with a simple snake game that even a beginner in Python would find easy to develop.

There exists a number of ways to create this game and one includes the use of Python’s PyGame library which is a Python library we use to create games.

The other way is by the use of the turtle library. This module comes pre-installed with Python and it provides a virtual canvas for users to create shapes and pictures.

Therefore, this article will use the python's pygame library to implement our simple snake game which is beginner-friendly.

#### Key takeaways 
1. Importing the modules
2. Creating the game’s screen display
3. Converting into OOPS
4. Moving block with timer
5. Create the snake and move the snake and finding the snake
6. Snake eats fruit, find score
7. Game over logic

#### Article quality
In this article building snake game in python will be simple to understand especially to beginners. I will explain step by step and all code snippets will be directly to the point. Hopefully you will find this article helpful.

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
