### ISSUE TITLE
Getting started with security, authorization and authentication in ASP.NET

### ISSUE THREAD

**Issue by swambui1** [section-engineering-education/engineering-education#7432]
### Topic Suggestion
Getting started with security, authorization, and authentication in ASP.NET

### Writing sample(s):
https://www.section.io/engineering-education/cookies-and-sessions-in-asp-dot-net/

#### Proposed title of the article
Getting started with security, authorization, and authentication in ASP.NET

#### Proposed article introduction
Authentication and authorization in ASP.NET are two closely related terms for the security of an application. The process of checking user identity is referred to as `Authentication`, whereas the protocol of checking if a client has access to all the resources needed is called `authorization`. Allowing an authentic client to access resources is also authorization. Authentication of a user is performed first where the user enters valid credentials to be identified, then authorization proceeds, and the user is allowed to access resources in the application.

#### Key takeaways
- Types of authorization in ASP.NET.
- Forms of authorization in ASP.NET.
- Authentication syntax in ASP.NET.
- Implementation of authentication in ASP.NET.

#### Article quality
In this article am going to take the user through security, authorization, and authentication in ASP.NET. I will explain to the user the different forms of authentication and authorization in ASP.NET. Also, I will show the user how to authenticate an application using ASP.NET. The article will be beginner-friendly and simple to understand.

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
