### ISSUE TITLE
[Languages]Achieving Spraying and Sketching in Python Using QPainter and Raster

### ISSUE THREAD

**Issue by lizpart** [section-engineering-education/engineering-education#7439]
#### Proposed title of the article

Achieving Spraying and Sketching in Python Using QPainter and Raster

#### Proposed article introduction

Understanding Raster (pixel-based) graphic operations are the first step in creating custom widgets in PyQt5. All standard widgets are drawn as bitmaps on a rectangular "canvas" that forms the widget's shape. You can draw any widget you want once you understand how this works!
In this tutorial, we'll look at QPainter, which is Qt's API for performing raster graphic operations and serves as the foundation for drawing your own widgets. We'll go over some fundamental sketching and painting operations before putting it all together to execute and implement spraying.
The QPainter class handles raster sketching operations in Qt. This is a generic interface that can be used to draw on a variety of surfaces, including QPixmap.

#### Key takeaways 

- Drawing of primitives.
- Performing a draw point using QPainter.
- Random pattern generation with dots.
- Sketching text using Raster graphics.
- Implementing spraying using dots and different colors.

#### Article quality
This will be an in-depth article covering all the aspects of this concept. It will explain key concepts to readers which is unavailable in the documentation and other platforms such as spraying. I aim at making it more beginner-friendly simple and easy to understand, with step-by-step code snippets. 

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.pythonguis.com/tutorials/bitmap-graphics/) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by lizpart** [comment]
The article covers an painter spraying which is not covered in other blogs... also written in a more procedural way

**Comment by lizpart** [comment]
@louisefindlay23 👆

**Comment by louisefindlay23** [comment]
> The article covers an painter spraying which is not covered in other blogs... also written in a more procedural way

The article I linked to covers spray also. Are you providing extra details not covered elsewhere or are there any unique additional points or are you providing a tutorial to paint a specific thing?

**Comment by lizpart** [comment]
@louisefindlay23 Yes

**Comment by louisefindlay23** [comment]
@lizpart, can you be more specific?

**Comment by lizpart** [comment]
@louisefindlay23 Neural art

**Comment by louisefindlay23** [comment]
Topic approved but please ensure your article is in-depth and unique enough to add value for our readers.
