### ISSUE TITLE
Using the Flutter Chopper library to create REST API calls and parse JSON data from the internet

### ISSUE THREAD

**Issue by MICHELLENGEI** [section-engineering-education/engineering-education#7441]
### Topic Suggestion
Using the Flutter Chopper library to create REST API calls and parse JSON data from the internet

#### Proposed article introduction
Flutter comes pre-installed with networking and JSON serialization features that are sufficient for most tasks. These modules are functional, however they necessitate a significant amount of effort to retrieve JSON from the internet. Many Android and iOS developers are already familiar with the Retrofit library on Android, and the AlamoFire library on iOS, if they come from a programming experience in both platforms. These libraries take care of the heavy lifting, allowing you to focus on other aspects of your life. Wouldn't it be great if you could create something similar for Flutter as well? You can achieve this with the Chopper networking library! This framework, which is designed to be similar to Retrofit, makes it much easier to obtain JSON data from the internet.

#### Key takeaways 

1.  How Flutter implements calling network APIs.
2. How Flutter implements parsing JSON data
3. How Flutter implements showing JSON data in a ListView.
4. How Flutter implements displaying network images.

#### Article quality
In this article, we’ll build a movie listing app that builds data modules and creates network calls and along the way the we will be able to showcase how flutter implements the above key takeaways

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
