### ISSUE TITLE
[languages] A Guide to Custom toast notifications with React components

### ISSUE THREAD

**Issue by Raphtuju007** [section-engineering-education/engineering-education#7442]
#### Proposed title of the article
 A Guide to Custom toast notifications with React components.

#### Proposed article introduction
Toast alerts are modal-like components that provide the user information in the form of buttons or another call to action. The displayed messages are typically short and are either removed by the user or set to expire on their own. Most importantly, toast alerts do not prevent users from interacting with your program, whether on a desktop or on a mobile device. I'll teach you how to construct a custom toast component using React in this tutorial. `UseState` and `useEffect` are two React hooks that will be utilized. 

#### Key takeaways 
The reader will be entitled to the following:
1. Introduction to react components.
2. Creating a toast component.
3. Adding button components.
4. Deleting toast notifications.
5. Auto-delete toast notifications.

#### Article quality
The proposed article seeks to teach those who have just completed learning react JavaScript how to work and integrate multiple react components to generate a desired template like a toast notification. Our case study, react custom toast notifications will be ideal project to develop add in their portfolios. I hope we will have a good ride all through the article.

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
