### ISSUE TITLE
How to Deploy an ERC-721 NFT Smart Contract with Remix IDE

### ISSUE THREAD

**Issue by corpsgeek** [section-engineering-education/engineering-education#7445]
### Topic Suggestion
How to Deploy an ERC-721 NFT Smart Contract

### Writing sample(s): 
- https://www.section.io/engineering-education/an-introduction-to-blockchain-architecture/
- https://www.section.io/engineering-education/an-introduction-to-defi/

#### Proposed title of the article
How to Deploy an ERC-721 NFT Smart Contract

#### Proposed article introduction
[Blockchain] This article will provide a step by step guide to deploying an NFT with Remix IDE and Interplanetary File System

#### Key takeaways 
- How to deploy an ERC-721 token
- Writing the Smart Contract with Remix to deploy the token
- Utilizing IPFS as a decentralized cloud in storing your digital artwork
- Utilising Metamask test networks
- Deploying and Compiling an ERC-721 token

#### Article quality
This article will be succinct towards ensuring beginners in the blockchain space can easily understand how to deploy an NFT token, because it seems to have been made complex and strange to new entrants in this tech space.

#### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=How+to+Deploy+an+ERC-721+NFT+Smart+Contract) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by corpsgeek** [comment]
I have checked through them, mine is a variation of that of quicknode, but it will show how to mint an NFT on the OpenSea market place and using pinafa cloud, coupled with a process on the test opens market place to buy and sell. It basically covers the whole process end-to-end.

**Comment by louisefindlay23** [comment]
Topic approved but please ensure your article is in-depth and unique enough to add value for our readers.
