### ISSUE TITLE
[Machine Learning] Building a Text Generation Web Application using Anvil

### ISSUE THREAD

**Issue by Bayler** [section-engineering-education/engineering-education#7449]
#### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. 

Building a Text Generation Web Application using Anvil

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked, and grammar checked.

Text generation is the task of generating text with the goal of appearing indistinguishable to human-written text.  Using the Happy Transformer model from HuggingFace, we will show our readers how to build a text generation application using Anvil which uses a Python only build in its design.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to have:
- An Overview of Anvil web app
- An Overview of GPT-Neo
- Using the Happy Transformer model for training.
- Generating text using Anvil.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have been published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Articles on the internet only cover what is Anvil and how to work with their various components in building a web application. This tutorial is specific. Using a text generation model from HuggingFace, we will show our readers how to build a text generation app using only a few lines of code. We will also show our readers how to deploy the app online so that anyone with internet can have access to it.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [Anvil](https://anvil.works/)
- [Model](https://huggingface.co/EleutherAI/gpt-neo-2.7B)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
