### ISSUE TITLE
Understanding JSON in Android Studio

### ISSUE THREAD

**Issue by Koros-Meshack** [section-engineering-education/engineering-education#7450]
### Topic Suggestion
Understanding JSON in Android Studio

### Writing sample(s):
https://www.section.io/engineering-education/authors/meshack-koros/

### Proposed title of article
Understanding JSON in Android Studio

### Proposed article introduction
In order for an android application to interact with the database, the program in the xml files should be executed and read by the server. The server cannot recognize a xml file thus the file is converted to JSON. 
JSON is a light weight and much human readable form.  In this article, we will discuss how the file is converted from xml to JSON format. Furthermore, we will discuss different classes of JSON and how we can manipulate them.

We will also discuss the two JSON structures which include a collection of keys and a list of values. Moreover, we will discuss the main JSON components which include **JSON Objects()**, **JSON Array()**,  **key** and **value**.
The user will also get to understand JSON parsing in Android and JSON parsing Methods.

### Key takeaways
By the end of the article the user will be able to understand the following
- JSON classes and structures
- Main JSON components
- JSON parsing in Android and JSON methods

### References
N/A

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
