### ISSUE TITLE
Getting Started with Linear Model in R

### ISSUE THREAD

**Issue by JUDYMUEKE** [section-engineering-education/engineering-education#7452]
### Topic Suggestion
Getting Started with Linear Model in R 

#### Proposed article introduction
In R, a linear model is a statistical or mathematical model that is used to create a relationship between a dependent variable and one or more independent variables. The criteria include that the variables involved in the model's development meet specific assumptions as necessary prerequisites prior to model construction, and that the model comprises certain key components, such as formula, data, subset, weights, method, model, offset, and so on. It is not required to employ all of them all of the time, but only those that are sufficient and useful in the particular situation.

#### Key takeaways 
- Syntax of Linear Model in R
- Types of Linear Model in R
- Advantages of  Linear Model
- Simple Linear Model
- Multiple Linear Model
- Implementation of linear model

#### Article quality
This article focuses on making the concept behind the linear model as clear as possible. We will focus on the key concepts and explore them in-depth. During our study, we will simplify concepts and make them easy to understand. This is because the content of this paper will base on a deep understanding of the topic. For the case study, we will provide a thoroughly explained code to make it easy for the learner to connect the theoretical part with the implementation session. Therefore, simplifying the concept, an in-depth approach to the study, and an easy-to-follow implementation session will make the entire content unique.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations as previously mentioned on your topic form by our content moderator.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
