### ISSUE TITLE
[Language]How to perform CRUD Operations on Python dictionary

### ISSUE THREAD

**Issue by cathy-254** [section-engineering-education/engineering-education#7465]
### Topic Suggestion
How to Perform CRUD Operations on Python dictionary

#### Proposed article introduction
In this article, we will learn what Python Dictionary is and how to generate it. I will also explain into details how to create, remove, update, delete and search elements in a dictionary object.
A dictionary in Python is a scrambled collection of objects. Unlike other data types such as a list or a set which has a single value field, the dictionary type stores a key along with its value. The keys can be of any data type varying from integer to string which makes it more flexible.
This article will give the learner a step-by-step guide on how to generate data in the python dictionary. 

#### Key takeaways 
By the end of the article, the readers will have learnt:
  - Python Dictionary Overview
  - Creating Dictionary
  - Retrieving data from the dictionary
  - Updating data
  - Deleting data from the dictionary
  - Iterating data
  
#### Article quality
In this article, I will show novices how to perform `CRUD`  on python dictionary. Unlike the existing articles on the same my article will have a complete script that ties everything together. Real life demonstration with output and also include comments to make the learners understand and follow.
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by LinusMuema** [comment]
Hi @cathy-254 

Thanks for submitting your article suggestion. However, after a short google search it seems your article has been widely covered on the internet. Due to this, we cannot proceed with your article as it will raise red flags during the plagiarism checks. Please feel free to explore other topics of interest.

**Comment by cathy-254** [comment]
@LinusMuema hello sir, I believe that knowledge can never be exhausted, and when I look at nearly similar online content  are not beginner-friendly and are not as engaging as they should be. Of course, this article will be one-of-a-kind, give live demo on every part of the operation and it will address these issues as gracefully as possible in order to maintain quality and add value to the community.I think it will be unique. Can you have a look at it again. Thanks
