### ISSUE TITLE
Discrete Fourier Transform of 1-D signal in Matlab

### ISSUE THREAD

**Issue by florenceatieno45** [section-engineering-education/engineering-education#7473]
### Topic Suggestion
Discrete Fourier Transform of 1-D signal in Matlab

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-use-edge-histogram-descriptor-to-retrieve-images-in-matlab/

#### Proposed article introduction
This tutorial presents the basic theory of Discrete Fourier Transform (DFT). It includes a background of DTFT and the evolution of DFT from DTFT. It also explains how DFT can be expressed as linear transformation to calculate forward DFT and inverse DFT easily. Also, the computational complexity of DFT/ IDFT calculation is discussed and compared with FFT. The MATLAB implementation is also given by which one can find N-point DFT of any real sequence of any length. This video includes the following topics,

#### Key takeaways 
- Introduction to Discrete-Time Fourier Transform (DTFT).
- Need for Discrete Fourier Transform (DFT).
- DFT Computation method.
- DFT as a linear transformation.
- Algorithm complexity.
- MATLAB Code to find N-point DFT of any sequence.

#### Article quality
This article shows the step to step process of computing DFT and converting the DFT to linear transformation and finding the N-point using Matlab code.

**Comment by LinusMuema** [comment]
Hi @florenceatieno45 

Thanks for submitting your article suggestion. 

After a google search, there were several articles that covered your content. Due to this, we cannot move forward with your article. Please feel free to explore other topics that may be of interest to you.
