### ISSUE TITLE
Significant changes on React Router

### ISSUE THREAD

**Issue by Tiioluwani** [section-engineering-education/engineering-education#7484]
#### Significant changes on React Router [Languages]

Use keyword research to improve your article's SEO.

#### Proposed article introduction
*When it comes to displaying multiple views without having to reload the browse  React Router plays an important role. In this tutorial, we’ll be looking at major changes in react router v6*
Outline
Introduction
New react-router features
Conclusion

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain

- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
At the end of this article, users will be able to 
1. know the new features in react-router
2. Have an understanding of each of them
3. Write the code syntax for each of these features.

#### Article quality
The goal of this article is to discuss these features and enable readers to know how to use them. Those promoting good programming practice.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentation (https://www.google.com/search?q=react+router+v6+significant+changes).

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
