### ISSUE TITLE
 use open cv, tensor flow and docker for Real-time and video processing object detection 

### ISSUE THREAD

**Issue by JGatura421** [section-engineering-education/engineering-education#7490]
**### Proposal Submission**

**### Proposed title of the article**
 use open cv, webcam, tensor flow, and docker for Real-time and video processing object detection .

**### Proposed article introduction**
What is an open cv?  (Open Source Computer Vision Library), is a library of programming functions mainly aimed at real-time computer vision. what is a tensor flow? TensorFlow is a free and open-source software library for machine learning and artificial intelligence.  What is Docker.? Docker is a set of platform as a service (PaaS) products that use OS-level virtualization to deliver software in packages called containers. 
In this article, I will walk you down how to use the three techologies with thee help of AI t track and identify real time object and Tensorflow Object-detection API in a Docker container to perform both real-time (webcam) and video post-processing..

**### Key takeaways**

1. brief intoduction to container technology.
2. understaning open cv
3. Sending/recover a video stream into the container
4. how to run and process the real time video

**### Article quality**

This in-depth tutorial will add so much value to the reader because along with learning about open CV, the user shall also get a brief knowlge about container technology and how to use a docker.
the reader will also get a brief understanding on coding.

**### References**

[How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
[Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
[Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout [other blog sites and official documentation](https://www.google.com/search?client=firefox-b-d&q=use+open+cv%2C+tensor+flow+and+docker+for+Real-time+and+video+processing+object+detection+).

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
