### ISSUE TITLE
Working with Svelte: Build a Todo Application

### ISSUE THREAD

**Issue by DannyXGee** [section-engineering-education/engineering-education#7496]
####  Working with Svelte: Build a Todo Application

Use keyword research to improve your article's SEO.

#### Proposed article introduction
*Svelte is a tool for building fast web applications. it is similar to JavaScript frameworks such as React and Vue, which share a goal or making it easy to build. which share a goal of making it easy to build. In this tutorial, we'll discuss Svelte and also build a to do app*
 
Outline
Introduction
What is svelte
Svelte vs other frameworks(how it ranks) 
Build a todo application
conclusion
For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
At the end of this article, the readers will be able to:
- Have an understanding of Svelte
- know where it ranks among other frameworks
- Build a todo a

#### Article quality
This article is meant to introduce Svelte in the best wy way possible. And also help readers get familiar by building a todo application.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by marienjus** [comment]
This has already been written.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout [other blog sites and official documentation](https://www.google.com/search?client=firefox-b-d&q=Working+with+Svelte%3A+Build+a+Todo+Application).

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
