### ISSUE TITLE
Creating a simple App that denoises 2-D signals using App Designer in Matlab

### ISSUE THREAD

**Issue by florenceakinyi** [section-engineering-education/engineering-education#7506]
### Topic Suggestion
Creating a simple App that denoises 2-D signals using App Designer in Matlab

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-perform-parallel-computing-using-matlab/

#### Proposed article introduction
Signal denoising is the process of removing the available noise in a signal. Signal denoising application is widely used in various fields. Using an app designer, we can create an app that does this. App Designer is an interactive development environment for designing an app layout and programming its behaviour. It provides a fully integrated version of the MATLAB Editor and large interactive UI components. It also offers a grid layout manager to organize your user interface and automatic reflow options to make your app detect and respond to changes in screen size.
This tutorial will look at how we can use an app designer to create a simple app. First, we will look at the various components used by the in-app designer and how to write their callback function. Finally, we will use their methods to create an App to denoise input 2-D signals and view the outputs.

#### Key takeaways 
- How to use the App designer.
- How to add and configure the various components.
- Writing the callback functions of the added components.
- Creating a denoising app.
- 
#### Article quality
This article introduces the app designer and how to create a sample app using the designer. In this case, we are creating a denoising App.

**Comment by louisefindlay23** [comment]
@florenceakinyi, can you tell me how your article is unique? Are the points you raise in the article quality section not covered elsewhere?

**Comment by florenceakinyi** [comment]
@louisefindlay23 In this tutorial we see how we can apply the app designer to create a denoising App. So basically we look how we can apply the denoising technique in App designer.
