### ISSUE TITLE
Run Proxy commands through Proxy tunnels and Proxy chains.

### ISSUE THREAD

**Issue by kush-dev** [section-engineering-education/engineering-education#7513]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission do NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community members to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error-free). 

All revisions and edits should be *completed on your forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

Run Proxy commands through Proxy tunnels and Proxy chains.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

 
First Timer no writing samples from before 

This proposal will teach Linux runners on how to install proxychains and run commands in proxy tunnels.It tends to broaden on network maintenance and network configurations.

Installing proxychains without errors and run your proxy commands on the proxy tunnels

[Networkong]  This proposal will teach Linux runners on how to install proxychains and run commands in proxy tunnels.It tends to broaden on network maintenance and network configurations. Network maintenance is important as it helps users to maintain their network without breakage. This article also improves users privacy on the web while surfing.

 
The reader should be able to configure proxy chains on Linux machines
The reader should be able to run commands through tunnels
The reader should be able to interchange chains in the network

This article gives the reader hand-on skills to accomplish what the article is all about It has a broader and widened research that allows the user to interact with what they are reading.

https://medium.com/swlh/proxying-like-a-pro-cccdc177b081

Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@kush-dev 
Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)

>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.**

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?client=firefox-b-d&q=+Run+Proxy+commands+through+Proxy+tunnels+and+Proxy+chains) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by kush-dev** [comment]
i hope to write this article to get a one on one attachment with the reader
and illustrate how to use proxy chains and its benefits

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
