### ISSUE TITLE
Building forms with Formik in React

### ISSUE THREAD

**Issue by 07BLAIZER** [section-engineering-education/engineering-education#7514]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission do NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community members to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error-free). 

All revisions and edits should be *completed on your forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

### Topic Suggestion
Enter topic suggestion here...
Building forms with Formik in React

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of the article
Building forms with Formik in React

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Formik is a small set of React components and hooks for developing forms in React and React native. It helps with the three most confounding components which are getting values into and out of form state and validation and error messages and lastly how to handle submission of forms. Building forms with React entails putting in state as the container for user data and props as the means to manipulate how state is updated using user input.

#### Key takeaways 
- What is formik
- Getting values into and out of form in Formik
- Validation and error messages in Formik
- Handling form submission in Formik

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have been published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?
This article will go beyond what is offered in official documentation by giving a step by step guide on how to create forms using Formik in React in a beginner friendly manner. It has up-to-date ways of using Formik.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
N/A

### Conclusion
Formik simply quickens your development process and decreases boilerplate code by means of abstracting away parts of your form. Through Formik in React we have developed a form which can be used in many ways such as registration form.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@07BLAIZER 
Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved
