### ISSUE TITLE
UDP Multicasting between Two Computers

### ISSUE THREAD

**Issue by apondi-911** [section-engineering-education/engineering-education#7518]
### Topic Suggestion
[Languages] UDP Multicasting between Two Computers

#### Proposed article introduction
Multicasting is defined as a single source sending to multiple recipients on a network when the receiver broadcasts a signal for acceptance. Multicasting can be used to send a string, audio, and video to a group of hosts in a network.

Multicasting can only be enabled on UDP (User Datagram Protocols) sockets. This is because UDP is a connectionless protocol. In this article, we shall have a deep dive into UDP Multicasting between two computers that is client and a server. We shall have a program that shows the client-side and another the server-side as a result, we shall have a single sender and about three receivers.

We shall also get to look at the IP addresses and Subnet Mask that Multicast uses. We shall conclude by getting to understand why multicasting is preferred over broadcasting.

#### Key takeaways 

1. What is UDP Multicasting?
2. Multicast addresses and groups that are available in a network.
3. Client and Server communication
4. Working with Multicast Sockets 
5. Why Multicasting is preferred over Broadcasting

#### Article quality
This article is unique from the published ones because it will clearly demonstrate client and server communicate and how a message will be sent as one-to-many distribution.

#### References
N/A

**Comment by hectorkambow** [comment]
@apondi-911

**Comment by apondi-911** [comment]
Hello Hector I got the news that now we won't be paid for writing the
articles?

**Comment by hectorkambow** [comment]
@apondi-911 
Just noticed this comment (that is correct moving forward our focus will be shifting). 


Please refer to this Slack message for full details. 

Also FYI please do ping me via Slack for a quicker response in the future as my email notifications get lost.

**Comment by hectorkambow** [comment]
Closing this topic suggestions (for now) due to inacvitity

**Comment by hectorkambow** [comment]
@apondi-911 FYI - if you are still working on publishing it do let me know. 

**_Also if you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers._**
