### ISSUE TITLE
Getting started with Marvel APIs in Laravel 9

### ISSUE THREAD

**Issue by owinojannette** [section-engineering-education/engineering-education#7527]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission do NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community members to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error-free). 

All revisions and edits should be *completed on your forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

### Topic Suggestion
Getting started with Marvel APIs in Laravel 9

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximize your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved. Also, allow 3-7 days for an article to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of the article
Getting started with Marvel APIs in Laravel 9
#### Proposed article introduction
Laravel is one of the most used frameworks right now, and the demand to mock APIs is an on-demand requirement by the developers. In this tutorial, I will introduce the reader to the concepts of Mock APIs with Marvel, and show the inner workings of Marvel.

Most importantly, Marvel APIs require API authentication, which is a tool required by developers who make requests to protected resources. With all these covered in this tutorial, the reader will gain substantial knowledge on how to mock requests to private resources.

Additionally, this tutorial will solely on the latest version of Laravel, which has a couple of changes on how to make these requests, and using Sail, a docker in-built in Laravel.

By the end, the reader will be able to retrieve a list of all characters in the marvel universe and display it on a responsive web page.

#### Key takeaways 
- Understanding the background knowledge about Marvel APIs
- Authenticating APIs to get access to Marvel.
- Design a web page with to render the list obtained from Marvel.

#### Article quality
First, this article is centered on Laravel 9, the latest stable version of Laravel.

Secondly, this tutorial teaches the reader the basic to advanced features of Marvel, and how to authenticate the APIs.

Thirdly, the response from the API is displayed on a responsive page built with Tailwind CSS.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
This seems to be a nice topic. Let's ensure that it adds value to the community. Thanks
