### ISSUE TITLE
How to develop system design and system development life cycle in a computer 

### ISSUE THREAD

**Issue by GATUARUTH** [section-engineering-education/engineering-education#7539]
### Topic Suggestion
How to develop system design and system development life cycle in a computer.(SDLC)

#### Proposed article introduction
System design is the process of defining the components,modulus, interfaces and a data for a system to satisfy specified requirements in a computer.
SDLC is the process used by the software industry design,develop and test high quality softwares.It consist of detailed plan describing how to develop, maintain, replace and alter or enhance specific software in a computer.
#### Key takeaways 
1. To produce high quality system that meet and exceed customer expectations based on customer requirements.
2. Provide IT project managers with the tools to help ensure successful implementation of system that satisfies organization and business objectived.
3. To develop a structure or roadmap that can be used for programming of a computer.

#### Article quality
This article will be unique such that;It will meet customer expectations,reaches complition within time and cost evaluation and work effectively and efficiently in current and planned information technology infrastructure in computer software.

**Comment by louisefindlay23** [comment]
Thank you for your response and we thank you for submitting your topic. After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in depth topic
