### ISSUE TITLE
[Security] Secure Cloud Access using SASE

### ISSUE THREAD

**Issue by RuthAMare** [section-engineering-education/engineering-education#7548]
#### Proposed title of the article
Secure Cloud Access using SASE

#### Proposed article introduction
This article will introduce the learner to SASE as an emerging security technology and stipulate the various security advantages of SASE. It will further give the advantages of SASE over the traditional security implementation.
This article will outline the various traditional security technologies combined to form SASE as a one-stop security offering. It will further give the various postures that an organization using cloud can take to implement SASE for an ideal secure network access.

#### Key takeaways 
1. Introduction to SASE.
2. Key technologies offered as a package by SASE as a security service.
3. Implementtion of SASE for secure network access in the cloud.

#### Article quality
This article will not only give a detailed introduction to SASE but also will give the various ways of implemeting SASE to achieve ideal secure network access on-net or off-net.

#### References
N/A

**Comment by hectorkambow** [comment]
@RuthAMare  

Were you still interested in publishing this blog article?

**Comment by hectorkambow** [comment]
@RuthAMare 
Closing for now - can be re-opened (or resubmitted) if you decide to add more to your EngEd profile. 

If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.
