### ISSUE TITLE
K8 Edge App 2022 Hackathon: "A Simple E-Commerce App Running on Kubernetes"

### ISSUE THREAD

**Issue by WanjaMIKE** [section-engineering-education/engineering-education#7558]
**April 11th - 18th 2022**

In this edge-based hackathon, we will focus on Section's [Kubernetes Edge Interface (KEI)](https://www.section.io/docs/explanations/kei/) solution. [KEI](https://www.section.io/kubernetes-edge-interface/) makes many edge clusters appear as a single cluster, enabling developers to quickly and easily deploy applications across a distributed Edge.

To participate in this hackathon, EngEd students are expected to create a true Kubernetes application for the Edge that is deployed using the KEI process.

Review the judging criteria listed below.

Below you will find full details on the hackathon and any requirements.

### Eligibility
Open to all EngEd students (participants can work individually or in teams of EngEd students). **By submitting this issue form you will have successfully signed up and we will reach out with next steps.** 

### Requirements
Once your K8s Edge application is complete and deployed, create a pull request to attach your submission to. 

Please complete and submit the following required sections listed below via a [Pull Request](https://github.com/section-engineering-education/engineering-education/compare) once your project is ready to be submitted. 

- Your Full Name, email, and EngEd author link.

- Project name, brief description of the project, a public URL link to your Edge app, and a short video that explains how your app works and how you deployed it using KEI. 

- The video should (be about 3 minutes) demonstrate your project using KEI. Videos must be uploaded to YouTube or Vimeo and made public.

- Please include a text description of your project, including how the featured tech (KEI) was utilized. Include what you enjoyed about working with KEI, what you didn't, what worked for you, and what didn’t work for you? Any barriers to get started or points of confusion.

- Include all requested materials alongside your Pull Request before the deadline!

- Proofread your project submission and review the judging criteria again to make sure you have addressed all the areas against which we will review your app.

- Test every link included.

- _Submit your project via a pull request on GitHub titled_ "EngEd - K8s Edge App 2022 Hackathon: Your Project Title Here" and **link** this original issue form to your project pull request.

### Prizes
1st prize: $1250
2nd prize: $750
3rd prize: $500

The first 20 participants to complete (and successfully submit) their projects are eligible to receive a complimentary virtual pass to [KubeCon](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/) ($75.00 value). Simply DM us in the EngEd community channel.

The top 3 winning applications will be points of reference at our booth at the KubeCon event mentioned above.

All other projects will receive honorable mentions on our website.

### Judging criteria: 
- The quality of the project (code effectiveness and code clarity) points for creativity and originality.
- Implementation of the Idea: Includes how well and quickly the project was developed and deployed using the KEI process.
- Was the application successfully deployed to the edge using KEI?
- The application functions completely and as described in the description.

**Comment by hectorkambow** [comment]
@WanjaMIKE 

Can you please share your:
Your Full Name, email, and Domain (URL) project link.

We will be sending over your test environment credentials.

**Comment by WanjaMIKE** [comment]
Collaborated on another project.
