### ISSUE TITLE
Designing graphical control elements

### ISSUE THREAD

**Issue by Wendymwangi** [section-engineering-education/engineering-education#7576]
#### Proposed title of the article

Designing graphical control elements

#### Proposed article introduction

A menu bar is a hierarchical collection of all available system functionalities grouped together as options inside a menu. This grouping is based on the nature of the functionalities. A menu is a set of options presented to the user of a computer application to help the user find information or execute a program function. A tool bar contains the direct shortcuts to the above mentioned functionalities, with the most used ones displayed on the bar. Menu bar usually doesn’t support customization while tool bar does. Status bar is found at the bottom of the browser window. When the Internet is in use, the main function of this bar is to show the computer’s progress in loading the website. It shows  the connection speed between the computer and the server where the web page is stored and how much of the page has been loaded.  Once the page is completely loaded, the bar goes blank again.

#### Key takeaways 

* By the end of this article, the following is expected;

1. Building Menu Bars, Menus, and Toolbars
2. Using Icons and Resources in PyQt
3. Creating Actions for Menus and Toolbars
4. Adding Options to Menus
5. Adding Options to Toolbars
6. Organizing Menu and Toolbar Options
7. Building Context or Pop-Up Menus
8. Connecting Signals and Slots in Menus and Toolbars
9. Populating Python Menus Dynamically
10. Building Python Status Bars

#### Article quality

This article will be on point, simple to understand, well formatted and I'm sure users will be able to learn the procedure of Designing graphical control elements. The code snippets in this article will be simple to understand and implement. I hope we will have a good ride all along.

#### References

N/A

**Comment by louisefindlay23** [comment]
Thank you for submitting your topic suggestion. There seems to be [many articles](https://www.google.com/search?q=Designing+graphical+control+elements+pyqt&client=firefox-b-d&sxsrf=APq-WBtK5YdTup2qAYsp3tGgG97M0dY1bw%3A1650380255528&ei=381eYpH1H6HF8gLXsIaYAQ&ved=0ahUKEwjR4P_GsaD3AhWholwKHVeYARMQ4dUDCA0&uact=5&oq=Designing+graphical+control+elements+pyqt&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABOgcIABBHELADOggIIRAWEB0QHkoECEEYAEoECEYYAFCUBFjPC2DsDGgBcAF4AIABhgGIAfMDkgEDNC4xmAEAoAEByAEIwAEB&sclient=gws-wiz) that already cover this topic. Can you tell me how yours will build upon them and be unique to add value to our readers?

**Comment by hectorkambow** [comment]
@Wendymwangi

**Comment by Wendymwangi** [comment]
@louisefindlay23 Hello sir, this article illustrates the procedures followed in creating visual building blocks which provide an interaction point for the direct manipulation of a given kind of data.

**Comment by hectorkambow** [comment]
@Wendymwangi 

Were you still interested in publishing this article blog post?

**Comment by hectorkambow** [comment]
@Wendymwangi 
Closing for now - can be re-opened (or resubmitted) if you decide to add more to your EngEd profile. 

If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.
