### ISSUE TITLE
K8 Edge App 2022 Hackathon: "KUCC Church App API Running on KEI"

### ISSUE THREAD

**Issue by JoelKanyi** [section-engineering-education/engineering-education#7598]
Name: Joel Kanyi
Email: joelkanyi98@gmail.com
Project: KUCC Church App API Running on KEI

**Comment by hectorkambow** [comment]
👍

**Comment by hectorkambow** [comment]
You should be receiving an email soon w/ credentials and details on the KEI deployment process.
