### ISSUE TITLE
Featured Articles Section on EngEd Author Pages

### ISSUE THREAD

**Issue by hborrelli1** [section-engineering-education/engineering-education#7626]
**This is a feature (or enhancement) proposal related to EngEd improvements.**
As an EngEd contributor/author, I'd like to have the ability to "pin" or add "featured" articles on my profile page. 

**Describe the task(s) you'd like to see done**
- Using front matter variables create a key/value pair of `featuredArticles: [string]`. The `featuredArticles` value will be an array containing strings on article urls.
- On the Author Page, modify the contributed articles section to push the "Featured Articles" to the top of the list. On the featured articles add a label and icon that matches the mockup below. 
- Make sure we are not displaying featured articles twice.

**Additional context**
For the Featured Articles Thumbtack icon, add the following code to the image tag `src` attribute: `{{ if eq $.Site.Params.env "local" }}/{{ else }}/engineering-education/{{ end }}images/thumbtack-icon.png`.

Design Comp:
![Pinned Articles Section Updated](https://user-images.githubusercontent.com/15935329/166329158-f6be604e-c644-4257-9521-75b84972e748.png)

**Notes:**
- When creating a Pull Request for a Community Contributed Code feature (CCC), please append `&template=pull_request_template_ccc.md` to the url to populate the correct Pull Request Template. See example below:

![pr-template-selector](https://user-images.githubusercontent.com/15935329/164524073-45bd5277-6cdf-46b9-aa33-2c2ae0907e45.png)

**Comment by hectorkambow** [comment]
Will be re-working this CCC form with added details. 

A new re-design of the (author pages & main page) may change the designs here.

**Comment by hborrelli1** [comment]
The feature has been updated and is ready to be worked on.
