### ISSUE TITLE
How to Create a Reusable React Form component

### ISSUE THREAD

**Issue by Geraldoeze** [section-engineering-education/engineering-education#7627]
### Topic Suggestion
How to Create a Reusable  Component.

#### Proposed title of the article
Creating a Reusable React form component. 

#### Proposed article introduction
When building a website or application, there's always a need for forms either for sign up or log in or for getting a user choice of items in the website or application.
This topic is all about creating a form component that can be reused in any part of an application.
A reusable form component saves us the trouble of having duplicate code in our application, thereby reducing our codes build size and making us have clean code.

#### Key takeaways 
The first Key take-away in this article is Building a reusable react component.
The second is using State management to handle what gets rendered on the browser.
The third is understanding how react state handles the content being displayed on the browser.
The forth is building a form component that can be rendered where ever you want, with the right contents for that particular form.

#### Article quality
In this tutorial, we'll be building a class component that has React state and renders a normal form page.
Then to make the component reusable, we'll be using mostly props to handle the contents that's get rendered on the browser. The styling, click events and disable buttons will all be handled with props and state in this tutorials.

#### References
N/A

**Comment by hectorkambow** [comment]
@Geraldoeze 

Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@Geraldoeze 

Were you still interested on publishing this topic?

**Comment by Geraldoeze** [comment]
Yes I am still interested.
I will create a PR before the week runs out.
