### ISSUE TITLE
Data Visualization : Rolling Dice with Pygal

### ISSUE THREAD

**Issue by fely545** [section-engineering-education/engineering-education#7637]
### writing sample(s): 
https://www.section.io/engineering-education/storing-data-in-python-using-json-module/

### topic suggestion
rolling dice with pygal

#### proposed article introduction
data visualization involves exploring data through visual representations. in this tutorial we'll use the python visualization package pygal to produce scalable vector graphics files. these are useful in visualizations that are presented on differently sized screens because they scale automatically to fit the viewer's screen. in this tutorial we'll analyze the results of rolling dice. if you roll one regular six-sided die, you have an equal chance of rolling any of the numbers from 1 through 6. however, when using two dice, you're more likely to roll certain numbers rather than others. we'll try to determine which numbers are most likely to occur by generating a data set that represents rolling dice. then we'll plot the results of a large number of rolls to determine which results are more likely than others. 

#### key takeaways 

- creating the die class
- rolling the die
- analyzing the results
- making a histogram
- rolling two dice

#### article quality
this tutorial will explain the concept of rolling the dice and make a visualization on it in a beginner friendly way. since the study of rolling dice is often used in mathematics to explain various types of data analysis, also has real-world applications in casinos and other gambling scenarios, this tutorial will be of great help to it's learners.

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved
