### ISSUE TITLE
Building a token-based authentication solution using Reactjs context API and typescript

### ISSUE THREAD

**Issue by GacheruJr** [section-engineering-education/engineering-education#7640]
### Topic Suggestion
[Languages]

#### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

#### Proposed article introduction
[Languages]:when building web applications,one of the challenges most developers face is authentication.
There are various authentication methods today with their use cases to ensure secure access to our application and services.

- Languages

#### Key takeaways 
-the reader will basic gain knowledge on react js context API and hooks
-gain basics in typesript
-knowledge in password authentication in projects

#### Article quality
i've checked and there has not been articles published on authentication using react js...so this might be the first one and the learner will gain knowledge by going through it.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@GacheruJr 
Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved
