### ISSUE TITLE
[Android] Swipeable Video Player with Jetpack Compose

### ISSUE THREAD

**Issue by JoelKanyi** [section-engineering-education/engineering-education#7643]
#### Proposed article introduction
Just like how YouTube shorts and Tiktok play their videos, different developers would like to know how to do so. Videos occupy the whole screen and play vertically. When a video finishes playing, it scrolls down and a new video is played. Also, the user has the capability to swipe vertically as much as they want.

Jetpack compose being new, implementing such a feature is not that easy. In this tutorial, we are going to create that vertical swipeable video player from scratch with Compose and Exoplayer.

#### Key takeaways 
- What is a swipeable component
- How to use Exoplayer with Jetpack Compose
- Creating a Swipeable composable
- Integrating the composable with Exoplayer

#### Article quality
Most of the tutorials, blogs and articles creates the swipeable player with XML but there is no  single sample that shows how to use Jetpack compose. I will make sure it is an easy read and easy to do tutorial.

#### References
- N/A

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic @JoelKanyi Approved

**Comment by hectorkambow** [comment]
@JoelKanyi 
Are you still working on this topic/article?

**Comment by p42rthicle** [comment]
Hi, where can I find the article?

**Comment by adrifernandev** [comment]
Same here, where can I find the article or the PR? @joelkanyi
