### ISSUE TITLE
Server-side pagination in React JS and Material UI

### ISSUE THREAD

**Issue by stephanieopala** [section-engineering-education/engineering-education#7649]
### Topic Suggestion
Server-side pagination in React JS and Material UI

### Writing sample(s): 
https://www.section.io/engineering-education/data-visualization-in-react-using-apexcharts/

#### Proposed title of the article
Server-side pagination in React JS and Material UI

#### Proposed article introduction

Server-side pagination involves fetching data in data sets based on the requests from the client side such as the page index or a number of items and rendering them. On the other hand, client-side pagination is where all the data is fetched at once from the server using an API call. The data is then stored in memory and displayed based on the page index. This article covers reasons why you should use server-side pagination and how to implement it in React JS and Material UI.

#### Key takeaways 
- What is server-side pagination?
- Difference between server-side pagination and client-side pagination.
- When and why you should use server-side pagination.
- How to implement server-side pagination in React JS and Material UI.

#### Article quality
This article is an in-depth guide to implementing server-side pagination in React JS and Material UI.

#### References
https://mui.com/material-ui/getting-started/usage/

**Comment by hectorkambow** [comment]
👋  

@stephanieopala 

Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved

**Comment by stephanieopala** [comment]
Hello @hectorkambow I haven't been able to work on this. It can be closed

**Comment by hectorkambow** [comment]
@stephanieopala  

No worries - you can ping us anytime you would like to continue or re - open. 


Also a key thing to NOTE is that you can add ANY past articles that you have published on any other site to your EngEd profile. 

Any past projects, blog posts, or video can be added to your portfolio to have them all organized in one place. 

Think of your EngEd profile as a dynamic CV or resume.

**Comment by stephanieopala** [comment]
Noted, thanks
