### ISSUE TITLE
Live Speech to Text Recognition API using Watson and Python

### ISSUE THREAD

**Issue by del-ui** [section-engineering-education/engineering-education#7651]
#### Proposed article introduction
Speech input has been embraced to simplify typing most for people with disabilities. Various machine learning models for speech recognition are being developed to fully automate typing using either recorded or live speech. In this article, you will learn how to build your own speech recognition API  using Watson and Python language. This will be able to convert both recorded and live speech to text in English.

#### Key takeaways 
- Set up Watson service called STT
- Install requirements and Libraries
- Handle errors with PyAudio installation
- Create the API and configure with API-key
- Test - Perform live transcription.

#### Article quality
In this API I will use Watson which is not used in many articles and the API will be able to capture live speech unlike other articles that use recorded speech only.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by del-ui** [comment]
@Kayere  can you check if this topic can be approved

**Comment by hectorkambow** [comment]
@del-ui 

Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
@del-ui 

Next time be sure to ping me to get it reviewed and approved asap.
