### ISSUE TITLE
Routing with React Navigation and Nesting Navigators in React Native

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#7660]
### Topic Suggestion

Routing with React Navigation and Nesting Navigators in React Native
#### Proposed title of article
Routing with React Navigation and Nesting Navigators in React Native
#### Proposed article introduction
Almost every mobile application necessitates switching between screens. React Native has an elegant and simple-to-use navigation library: react-navigation. It is a widely used library for routing and navigation in React Native applications. Nesting navigators means rendering a navigator inside a screen of another navigator. Navigating to another screen will push a new screen in case of stack

Navigators control the transition between various screens. React Navigation supports a variety of navigator types, including Stack Navigators, Drawer Navigators, and Tab Navigators. It can also be used to share info between numerous screens in addition to navigating between them.

We will be developing a simple react native app that will demonstrate how nested navigators and routing.

#### Key takeaways 
- Creating a New React Native App
- Creating screens
- Using Context to Pass Data to Other Screens
- Using nested navigators with React Navigation
#### Article quality
At the conclusion of this tutorial, you will have constructed a simple app. It will display the workers connection count and provide a means of adding new workers. This sample application will demonstrate how to utilize nested react-navigation to navigate mobile application screens.
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by vincentkims49** [comment]
@hectorkambow here is the issue

**Comment by hectorkambow** [comment]
👏

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - **lets please be sure it adds value beyond what is in [any official docs and/or what is covered in other blog sites](https://www.google.com/search?q=Routing+with+React+Navigation+and+Nesting+Navigators+in+React+Native&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
). (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved
