### ISSUE TITLE
Building Jetpack Compose UIs with Material Design 3 Components

### ISSUE THREAD

**Issue by robert-muriithi** [section-engineering-education/engineering-education#7670]
### Topic Suggestion
Building Jetpack Compose UIs with Material Design 3 Components

#### Proposed article introduction
Material is an adaptable system of guidelines, components, and tools that support the best practices of user interface design.  Material 3 was just introduced by Google to replace Material2 and it is the next generation of material designs. Material 3 includes updated theming ,components,typography and Material. You can personalize features like dynamic color, and is designed to be cohesive with the new Android 12 visual style and system UI.

#### Key takeaways 
- Advantages of building apps with Material 3
- Setting up Material 3 to Compose projects
- Structure of Components
- Migrating Existing Material 2 to Material 3

#### Article quality
This article will show how to migrate a project built upon material 2 components to material 3 components as it has not been published on any blog

#### References
https://developer.android.com/jetpack/androidx/releases/compose-material3

**Comment by hectorkambow** [comment]
@robert-muriithi 
Are you still working on this topic/article?

**Comment by robert-muriithi** [comment]
Hello @hectorkambow . I am working on it
