### ISSUE TITLE
Creating ToolTips using CSS

### ISSUE THREAD

**Issue by Dorkness** [section-engineering-education/engineering-education#7673]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission do NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community members to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error-free). 

All revisions and edits should be *completed on your forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

### Topic Suggestion
Enter topic suggestion here...
A How-To Guide on Creating ToolTips using CSS

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.
https://www.notion.so/A-BEGINNERS-GUIDE-TO-MARKDOWN-1e4268a45b4b4010b36fce85e0ef9ab4
#### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. 
A Guide To Creating User-Friendly ToolTips with CSS
Use keyword research to improve your article's SEO.

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked, and grammar checked.
Do you know that information bubble that appears after you hover over specific elements? Well, that is a tooltip! It is meant to convey contextualized information regarding a specific item (usually the one being hovered over). This device is used for a lot of things such as the full meaning of abbreviated words or even the exact measurement of an item.
Since its inception, tooltips have become an integral part of web designs and software programs, so as expected we have come up with ways to include them in our programs.
For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.
[Language] A Guide to Creating User-Friendly ToolTips with CSS
ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.
-Understanding what tooltips are and when to use them
-Learning how to create them using CSS
-Learning how to design them using CSS
#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have been published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?
This article is intended to simply shine a light on the design abilities of tooltips using specific CSS elements. It does not cover additional topics and it is not a deep dive. It is a simple and maybe a little anecdotal guide to tooltip creation and design using CSS.
#### References
Please list links to any published content/research that you intend to use to support/guide this article.
-wikipedia.org
-w3schools.com
-codecademy.com
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Approved

**Comment by hectorkambow** [comment]
@Dorkness 
Are you still working on this topic/article?
