### ISSUE TITLE
Automated Deployment to Playstore with GitHub Actions

### ISSUE THREAD

**Issue by brandy-kay** [section-engineering-education/engineering-education#7677]
Automated Deployment to Play store with GitHub Actions

#### Proposed article introduction
CI/CD is a very important thing every individual should take in account when developing application this is done through several actions like GitHub actions In this article, we’ll learn to automate tasks for deploying your cool Android application to the Google Play Store using GitHub Actions 

#### Key takeaways 
- What is CI/CD 
- What is git hub actions
- How to setup git hub actions
- How to implement automatic deployment step wise

#### Article quality
This article aims to guide both novice a expert reader through various steps and strategies taken to automatically deploy application to play store with GitHub actions.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic. Approved

**Comment by hectorkambow** [comment]
@brandy-kay 
Are you still working on this topic/article?

**Comment by brandy-kay** [comment]
yes am working on it ill be sending the pr today sir

**Comment by brandy-kay** [comment]
i had so problem with my laptop but i have fixed and ill be sending the pr before the end of today @hectorkambow
