### ISSUE TITLE
Build and deploy a data dictionary generator with NodeJS

### ISSUE THREAD

**Issue by saucekode** [section-engineering-education/engineering-education#7683]
#### Introduction
A Data Dictionary contains information about attributes or fields of a certain data set. It can comprise of all the tables in a database, columns of those tables and their descriptions, constraints, primary and foreign key relationships to other tables. It is also great for documentation.

In this article, I will be guiding the readers on a step-by-step process on how to create a simple and configurable data dictionary generator.

#### Key takeaways
The following shall be discussed in the article;

- Readers will be introduced to data dictionaries
- Readers with no prior knowledge of NodeJs will be exposed to the language

#### Article Quality
This article will introduce the readers to how they can further improve documentation with data dictionaries.

**Comment by hectorkambow** [comment]
@saucekode 
Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved
