### ISSUE TITLE
Working with bash arrays

### ISSUE THREAD

**Issue by Anitaachu** [section-engineering-education/engineering-education#7687]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission do NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community members to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error-free). 

All revisions and edits should be *completed on your forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

### Topic Suggestion
Working with bash arrays

### Writing sample(s): 
https://www.section.io/engineering-education/concurrency-in-go/
https://www.section.io/engineering-education/integrating-graphql-api-in-a-django-application/

#### Proposed title of the article
Working with bash arrays

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Bash scripting, just like with other programming languages and scripting tools, allows you to create variables, run for loops, apply conditional logic, and more importantly, you can work with arrays, which are our focus in the tutorial. Arrays in Bash scripting are quite powerful for storing multiple data and fundamental data structures.

In this tutorial, we will walk you through what bash arrays are, the distinction between bash arrays and other concepts, and how to perform key operations on them with detailed examples.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
1. Good understanding of bash arrays.
2. How to perform key operations using bash arrays with detailed examples.
3. How to differentiate bash arrays from other similar bash concepts.
4. The different types of bash arrays with examples and code snippets.

#### Article quality
This article provides a detailed view of what bash arrays are and how to perform key operations with them using code snippets and examples. There are other concepts which may seem similar to bash array this article differentiates these concepts with examples. Lastly, shows how to add, remove and print elements in a bash array.

#### References
N/A.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved


@Anitaachu
