### ISSUE TITLE
Running Kali Linux on Seemless Mode and Window Mode using Win-Kex

### ISSUE THREAD

**Issue by akenz1901** [section-engineering-education/engineering-education#7691]
### Running Kali Linux on Seemless Mode and Window Mode using Win-Kex.

In this article, we will improve the support of WSL(Windows Subsystem Linux) by running and installing Kali Linux on windows in a desktop GUI environment using Win-Kex. Also, we will utilize the windows terminal application to use command-line techniques and shells like PowerShell and Command Prompt in multiple tabs.

The motivation behind this article is to introduce a feasible methodology that enables individuals to quickly test their respective applications on a Linux operating system.

#### Prerequisite
- Basic knowledge of Windows Command Prompt or PowerShell
- Windows 10 OS version and above

#### Key Takeaway
- It will enable Kali Linux enthusiasts to acquire a quick Linux experience.
- It will create a suitable testing environment for developers.
- It will enable individuals to work with shells in multiple tabs.
- It will allow individuals to access the same file/directory using both Kali and Windows OS.
- It will enable individuals already using WSL to utilize a desktop GUI environment for an already installed Kali Linux.
- It will enable individuals to utilize Windows apps and Linux tools on the same set of files.

#### Conclusion
By the end of this article, readers will be efficient working with shells and command-line tools, and this article will be a quick consulting tutorial for readers.

#### References
- [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux)
- [Kali Linux Documentation](https://www.kali.org/docs/)

**Comment by akenz1901** [comment]
@hectorkambow Here's the resubmission of the recently closed topic and I promise to be dedicated and committed to tidying up this contribution.

Thanks always

**Comment by hectorkambow** [comment]
@akenz1901 
Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved

**Comment by akenz1901** [comment]
@hectorkambow 
I appreciate every guide attached in your comment I will ensure I follow every instruction to make this article unique.
