### ISSUE TITLE
Creating and Utilizing Custom Decorators in Django

### ISSUE THREAD

**Issue by BOVAGE** [section-engineering-education/engineering-education#7701]
### Writing sample(s): 
- [How to Integrate Google Analytics in Typesense](https://aviyel.com/post/3169/how-to-integrate-google-analytics-in-typesense)
- [What Exactly is Multithreading](https://bovage.hashnode.dev/what-exactly-is-multithreading)
- [How to use PostgreSQL in a Django Project](https://bovage.hashnode.dev/how-to-use-postgresql-database-in-a-django-project)

#### Proposed title of the article
Creating and Utilizing Custom Decorators in Django

#### Proposed article introduction
In Python, a decorator is a function that takes another function as an argument and adds functionality or augments the function without changing it. Django, as a Python web framework, comes with a large number of built-in decorators. These built-in decorators are used for decorating function based views. However, the real-world application you're working on may require custom checks or validations that django doesn't supply out of the box.

In software development, situations like the one mentioned above are unavoidable. When such a situation happens while developing a Django application, the default option for the normal programmer is to conduct the checks or validations in the view. This method is straightforward, however it is inefficient, and it goes against software development best practices and principles such as DRY (Don't Repeat Yourself). This is because, as the program expands in size, the same check or validation must be performed in numerous views. As a result, the identical code is repeated across the application.

In this article, you'll learn how to develop custom decorators similar to the built-in decorators (such as login_required, require_http_methods, csrf_exempt) used in real-world applications. The following are custom decorators that will be created: 

- authentication_not_required: Users who are signed in will be unable to access a view as a result of this decorator. For login and registration views, this is useful..
- verification_required: Users who haven't verified their email address or phone number will be unable to access a view as a result of this.
- xhr_or_fetch_request_only:  This ensures only request via fetch, XHR(XMLHttpRequest) or AJAX(Asynchronously Javascript and XML) is allowed.

#### Key takeaways 
The reader should be able to do or understand the following after reading this article:
1. Have  a good understanding of how built-in django decorators work internally
2. How to write clean and readable codes that adhere to DRY(Don't Repeat Yourself) principle
3. How to use decorators in class based views

#### Article quality
The most effective approach to understand a programming topic is to apply it to real-world tasks.
This article describes and illustrates how the knowledge gained from this section article on [Getting Started with decorators in Python](https://www.section.io/engineering-education/python-decorators/) can be applied in real world applications. The codes written in this article are well-written and readable. It also delves into the inner workings of Django, utilizing core Python fundamentals.

#### References
[Django Docs](https://docs.djangoproject.com/en/4.0/)
[Django Codebase on Github](https://github.com/django/django)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@BOVAGE 

Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved
