### ISSUE TITLE
[Languages] Optimizing your React App Performance with Turbo React

### ISSUE THREAD

**Issue by EssyG10** [section-engineering-education/engineering-education#7704]
#### Proposed title of the article

Optimizing your React App Performance with Turbo React

#### Proposed article introduction
React Turbo is a babel plugin that changes the value comparison to value subscription change detection approach of your React components at build time. In order to reduce needless recalculation and re-rendering, it adopts fine-grained responsiveness and caches all values. You no longer need to create any `useMemo`, `useCallback`, or even use reselect with Redux after installing React Turbo. Actually, speed optimization requires no code writing or modification. In this article, we will break down Turbo react logic and easily get readers started with it.

#### Key takeaways 

1. Installation and Configuration of turbo react in your project
2. Understanding Value Comparison vs. Value Subscription
3. overhead of the recreation and comparison
4. Compilation

#### Article quality
Despite react being given a higher emphasis while creating front-end solutions, performance optimization is one of the warning signs that developers should be aware of. Developers must learn the finest and most practical approaches to conduct out optimization of their react apps in light of this, which is where React Turbo comes in. To learn how to utilize React Turbo to improve our react apps, we will have a thorough overview with practical examples.

#### References
N/A

**Comment by hectorkambow** [comment]
@EssyG10 
Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved
