### ISSUE TITLE
Authentication and Authorization in Nestjs using Redis and JWT

### ISSUE THREAD

**Issue by Sodiq-123** [section-engineering-education/engineering-education#7748]
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission do NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community members to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error-free). 

All revisions and edits should be *completed on your forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

### Topic Suggestion
Authentication and Authorization in Nestjs using Redis and JWT

### Writing sample(s): 
https://dev.to/sodiq123/building-a-user-login-system-with-express-js-and-fauna-4p32
https://dev.to/sodiq123/todo-api-with-express-js-and-mongodb-14ej

#### Proposed title of the article
Authentication and Authorization in Nestjs using Redis and JWT

Use keyword research to improve your article's SEO.
Nestjs, Redis, JWT, Authentication, Authorization

#### Proposed article introduction
In this article, we are taking a look at authentication and authorization in nestjs by caching jwt in redis and getting available tokens from the redis cache. We take a look at creating auth guards which will be used in authenticated routes (only logged In users can access them).
We'll also learn how to connect postgres using typeorm in nestjs and an explanation of Redis in general and it's advantages in our API.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
- Learn more about Authentication and Authourization in Nestjs.
- Learn how Redis works also and it's importance in our APIs.
- Importance of having authenticated routes.

#### Article quality
The article is intended for mid-level developers with knowledge in nodejs/nestjs. It takes an in-depth look at authentication and authorization using nestjs and how to connect postgres database, Twilio and how to add MongoDB with Nodejs.

#### References
https://redis.io/
https://docs.nestjs.com/guards
https://www.linkedin.com/pulse/why-when-use-redis-hamed-moayeri

### Conclusion
This articles helps explain how to setup a nestjs app, takes a look at authentication and authorization in nestjs using redis to cache tokens and also explains why redis was used and how it important it can be for an API with a lot of users (scalability).

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@Sodiq-123 
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)

ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.
Please reference any relevant EngEd articles in yours. - Approved

**Comment by Sodiq-123** [comment]
Hi @WanjaMIKE as this topic was approved but never published yet and now, it's getting closed.
Any reason why, please?
