### ISSUE TITLE
Deep dive into Kubernetes architecture and Pod Networking

### ISSUE THREAD

**Issue by Horlawhumy-dev** [section-engineering-education/engineering-education#7769]
### Introduction
Best practices for scalable, decoupled, managed application systems are microservices architecture. In a traditional environment, an application was developed on a large monolithic repository and deployed on a dedicated on-premise data centre server. Industrially, packaging system requirements and runtimes are made easier with the container. It solves issues behind applications not running on the same operating systems.

In a microservice architecture, connecting containers across multiple hosts, scaling them, and deploying applications without downtime can be complex. Kubernetes addresses those challenges as a container orchestrator. It approaches the issue of large server deployment by providing components for small web servers or microservices

### Prerequisites
You will need to have basic knowledge of Kubernetes components to follow along;
- Containers
- Service
- Deployment
- Pod
- Cluster
- Node

### Key Takeaways
At the end of the article, you have learned more about the following headings;
- Kubernetes Architecture
- Pod Networking

**Comment by WanjaMIKE** [comment]
Seems like a helpful topic @Horlawhumy-dev
