### ISSUE TITLE
Understanding support vector machines

### ISSUE THREAD

**Issue by mykolkiprono** [section-engineering-education/engineering-education#777]
**Brief Summary:** 

Support vector machines are set of supervised learning methods mainly used for classification problems though they can also be used for regression and outlier detection, they are very efficient in high dimensional spaces and are  memory efficient since they only use  a subset of the training points in the decision function

 **Key Takeaways:** 
1. Understand what support vector machines are.
2. Appreciating what support vector machines are  used for in machine learning.
3. Understand the matematical formulation behind support vector machines.
4. Be able to solve a real world problem using  support vector machines.

### _References:_ 
N/A

**Comment by ninjaginja** [comment]
good topic @mykolkiprono - approved

**Comment by hectorkambow** [comment]
closing - can reopen a new issue with new topic 👍
