### ISSUE TITLE
Understanding OOP(object-oriented programing) in JavaScript: The ultimate Guide (2022)

### ISSUE THREAD

**Issue by Succyvibe** [section-engineering-education/engineering-education#7771]
#### Proposed title of the article
Understanding OOP(object-oriented programing) in JavaScript: The ultimate Guide (2022)

#### Proposed article introduction
In JavaScript and Programming in General we have Three programming paradigms which are Procedural Programming, Object Oriented Programming, and Functional Programming, and they are simply the different ways with which we can write or organize our code.

Starting out with JavaScript, procedural programming is the most obvious style to start with which is why I believe we were all introduced to procedural programming at the start of our JavaScript journey. This style is basically writing sequential series of execution steps and tasks for the engine to be able to execute the code step by step.

Moreover to advance as a JavaScript developer you need an in-depth knowledge of Object Oriented Programming (OOP). In this article, you will be learning all about OOP from the ground up.

#### Key takeaways 
At the end of this article, readers would be able to:
* Readers will learn how to create objects using Constructor function
* Readers will learn how to create objects using modern ES6 classes
* Readers will learn the importance of OOP in their JavaScript journey 
* Readers will know the four fundamental principles of OOP

#### Article quality
While other article focuses more on just showing code examples, I'm going to give detailed explanation of each concept before proceeding to give examples using real life objects that the readers would easily relate with to enable them understand each concept easily
I'm going to be building the concept from ground up, putting beginners as well as intermediate and advanced readers in mind. Rather than starting of with advanced OOP concept like Constructor function, I will start off by teaching how to create basic object in JavaScript and how to  access object properties with code examples

#### References
[JavaScript Algorithms and Data Structures](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/)
[Object Oriented Programming in JavaScript – Explained with Examples](https://www.freecodecamp.org/news/how-javascript-implements-oop/#:~:text=JavaScript%20leverages%20its%20prototype%20nature,just%20take%20note%20of%20that.)
[Object-oriented programming](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_programming)

### Conclusion
In this article, we looked at what OOP is and why OOP is important as a JavaScript developer. We also went ahead to look at how to create basic JavaScript objects with real life code examples.

We also took it further by looking at how to create objects in JavaScript using more advanced methods like the Constructor function and also ES6 classes. 

The concepts we explored in this article are very useful for JavaScript developers, which is why I congratulate you for coming thus far with me. This is a step-up game in your JavaScript Journey

**Comment by Succyvibe** [comment]
Hello @WanjaMIKE It's been awhile, I have been trying to reach out to you. Hope all is well with you

**Comment by WanjaMIKE** [comment]
Yeah it has been. I was away for sometime. Are you still interested with this article? It can be a good addition to your profile.

**Comment by Succyvibe** [comment]
Yeah sure I am still interested. Thanks for going through it again. I sent
you message on twitter

**Comment by Succyvibe** [comment]
I have some other articles I would love to contribute to the platform.

**Comment by Succyvibe** [comment]
@WanjaMIKE Guess you're really busy, please do check on my messages when you're free. Thanks
