### ISSUE TITLE
Creating a laravel blog with livewire component

### ISSUE THREAD

**Issue by NPKIN1998** [section-engineering-education/engineering-education#7779]
#### Proposed title of the article
Creating a laravel blog with livewire component

#### Proposed article introduction
Laravel is PHP framework that is powered by blade template engine and is powerful in creating web application. They are many people with out the ability to set up their Laravel project to use live-wire. For this reason, I am suggesting that may show the how incorporate live-wire in Laravel by creating a blog website to show how it may be use in web project built with Laravel framework.

It is beginner friendly, issue to help understand how laravel project is created and then adding live-wire to the project by a beginner can create a web application using laravel and live-wire. 

The following are the perquisite of these project basic understanding of html,CSS and java script or any CSS framework like bootstrap. The topics shall be covered:
-installing PHP environment in Linux distribution like Kali
-install composer
-install npm
creating Laravel project via composer
-Adding auth ui
-Adding live-wire component on Laravel project

**Comment by WanjaMIKE** [comment]
Topic approved @NPKIN1998 This will help improve your profile.
