### ISSUE TITLE
Edge Functions and The Future of Web Development

### ISSUE THREAD

**Issue by giridhar7632** [section-engineering-education/engineering-education#7784]
### Topic Suggestion
Edge Functions and The Future of Web Development

#### Pre-submission advice
This article will be about web development using serverless functions. It will contain the implementation of serverless edge functions using NextJS and Vercel.

### Writing sample(s): 
- https://dev.to/hackmamba/build-a-full-stack-jamstack-application-5apm
- https://www.section.io/engineering-education/integrate-airtable-with-nextjs/

#### Title
Edge Functions and The Future of the Web Development

#### Introduction
Edge functions were made available to hobby developers after Netlify and Vercel introduced their edge runtimes. The edge functions will significantly accelerate your serverless backend. In this article, I'll go over edge functions in Vercel's edge runtime. I'll begin by explaining what edge functions are and when and why we should use them in our web development projects. I'll also discuss about the future of web development, specifically whether serverless and cloud functions will be replaced by edge functions.

#### Key takeaways 
By the end of this tutorial,
- One will understand what Edge Functions are, and how to use them.
- One will be able to use the Vercel's edge runtime.
- One will understand the pros and cons of edge functions.

#### Article quality
Many articles use Netlify, but I want to use the Vercel to demonstrate edge functions. I'll include all of the details about edge functions, including their history related to cloud computing.

#### References
- https://vercel.com/features/edge-functions
- https://www.netlify.com/blog/announcing-serverless-compute-with-edge-functions/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Topic approved @giridhar7632  This will help improve your profile.
