### ISSUE TITLE
Scaling your android app with kubernetes

### ISSUE THREAD

**Issue by Youngshark3** [section-engineering-education/engineering-education#7795]
The industry of building mobile apps is growing so fast. It  is due to this that scalability is required. In this tutorial we will learn how to scale our android app using Kubernetes.  Kubernetes is a powerful tool for managing and scaling applications, including Android apps.

### Pre-requisite
What is kubernetes?
How to set up k8?
build a small android app
Scale the app

**Comment by WanjaMIKE** [comment]
Topic approved @Youngshark3

**Comment by Youngshark3** [comment]
Hello Wanjamike i have an article not yet published
