### ISSUE TITLE
Stir Framework in Action in a Spring Web App

### ISSUE THREAD

**Issue by john-amiscaray** [section-engineering-education/engineering-education#7804]
#### Proposed title of the article
Stir Framework in Action in a Spring Web App

#### Proposed article introduction
January 26th, 2023 saw the release of Stir version 1.0.0 to Maven central, an open-source Java framework I’ve developed over the past two months. Stir is a feature-rich server-side rendering framework that allows you to generate HTML on the fly. With its developer-friendly API and extensive documentation, you can get started with it right away and use it as the templating solution for your next backend project.

In this tutorial, I’ll show Stir in action by creating a simple to-do application with Spring. In the process, we’ll see the major features of Stir, the advantages of using it, and proper usage of it for your next project. By the end of this guide, you will have everything you need to know to use Stir for server-side development.

#### Key takeaways
- The advantages of Stir as a server-side rendering solution
- HTML Document Templating
- Building a custom AbstractUIElement class
- Working with element descriptors
- How to use Stir in a production application

#### Article quality
This guide will provide the reader with examples of the practical applications of Stir by going step-by-step through a to-do app powered by it.

#### References
https://github.com/john-amiscaray/Stir

**Comment by WanjaMIKE** [comment]
Go ahead @john-amiscaray Seems like a good topic. Tag me when you create a PR. I hope you are aware about the new rules regarding payment. Thanks

**Comment by john-amiscaray** [comment]
@WanjaMIKE I created the PR. See #7807.
