### ISSUE TITLE
CSS FlexBox Vs CSS Grid

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#827]
### Brief Summary: 
CSS has two layout systems; Flexbox and CSS grid. They help developers to structure and display web content.
This guide will help discuss and compare these two layouts with the following key takeaways. 

### Key Takeaways: 
- What is CSS FlexBox
- What is CSS FlexBox
- When to use Flexbox and when to use CSS grid
- Property differences

### References: 
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox

**Comment by ninjaginja** [comment]
good topic @kimkimani - approved
