### ISSUE TITLE
CRUD operation with MySQL using Vue.js and PhP.

### ISSUE THREAD

**Issue by CodeLeom** [section-engineering-education/engineering-education#862]
### Brief Summary: 
CRUD functionality is mostly required on every dynamic web based project. This article will put you through on how you can connect your Vuejs project with a MYSQL database. 

### Key Takeaways: 
In this article, you will learn how to select, insert, update, and delete records from a MySQL database with Vue.js and PHP.

### References: 
 'N/A'

**Comment by ninjaginja** [comment]
good topic @CodeLeom - approved. One minor note, please be mindful to retain consistency in your references of Vue.js, MySQL, and PHP.

**Comment by CodeLeom** [comment]
Alright, I will be consistent.  Thank you

**Comment by hectorkambow** [comment]
closing can be reopened with new issue form
