### ISSUE TITLE
Creating a RESTful web API in Node.js using Postgres SQL and Express

### ISSUE THREAD

**Issue by kimkimani** [section-engineering-education/engineering-education#866]
### Brief Summary: 

Section blog has an introductory to [Express](https://www.section.io/engineering-education/express/) guide, and here is a [node.js with MySQL](https://github.com/section-io/engineering-education/issues/826) guide in progress.
This guide will walk through creating an API with these two libraries to move information around the server to the client-side and vice versa.

### Key Takeaways: 

This will be a beginner/introductory APP.

I'll create a server to make responses and request to a MySQL database and make a client-side page to interact with the server and the database values.

This [Tutorial](https://www.section.io/engineering-education/building-a-basic-api-with-nodejs/) talks about a node.js RESTful API but I believe the two won't collide, as I will focus database data to interact with a server with an interaction client-side page.
### References: 
https://www.tutorialspoint.com/restful/restful_introduction.htm
https://www.npmjs.com/package/mysql
https://expressjs.com/en/starter/basic-routing.html

**Comment by ninjaginja** [comment]
good topic @kimkimani - approved

**Comment by kimkimani** [comment]
Taking some time to draft the PR. It will be opened when draft is ready.
