### ISSUE TITLE
Data fetching with React suspense and concurrent mode

### ISSUE THREAD

**Issue by ReactifyStudio** [section-engineering-education/engineering-education#896]
### Brief Summary: 
ReactJS is a JavaScript library for creating interactive user interfaces.In this tutorial,we are going to use React suspense API and interact with a backend API for data fetching.

### Key Takeaways: 
 1.ReactJS introduction
2.ReactJS best practices
3.How to interact with a third party API for data fetching

### References: 
https://reactjs.org/

**Comment by ninjaginja** [comment]
good topic @ReactifyStudio - approved.

As a side note, before suggesting new topics, we ask that you please see a single article through from start to finish so you can incorporate any/all feedback on subsequent articles, and so we can facilitate reviews and payouts faster for everyone.

**Comment by ReactifyStudio** [comment]
The feature is still experimental in React. I need to focus on stable versions first.
