### ISSUE TITLE
Spotipy: The Spotify Wrapper for Python Part 1

### ISSUE THREAD

**Issue by joshjwelsh** [section-engineering-education/engineering-education#907]
### Brief Summary: 
The idea is for this to be a series. 1st piece will be going through spotify api and spotipy. Learn the basics, authentication process and how to get basic data. This is a tutorial. 

### Key Takeaways: 
1) Spotify API and Spotipy introduction 
2) User authentication   
3) Get your most recently played songs 

### References: 
https://spotipy.readthedocs.io/en/2.12.0/
 https://developer.spotify.com/

**Comment by ninjaginja** [comment]
@joshjwelsh could you please explain how this tutorial differs from what's already available in the docs?

**Comment by joshjwelsh** [comment]
Well firstly this is part 1 of a 3 part series so I need to start the series off with the most basic information, authentication, scoping, setting up an environment etc. Secondly to properly do this project you need information from both the spotify docs and the spotipy docs, the idea of this tutorial is to condense the core aspects of both into a single document that can help you get started faster. Also to overcome common problems that come up such as data limits. @ninjaginja

**Comment by ninjaginja** [comment]
Perfect! Thanks for the clarification - makes sense. Sounds like a great tutorial - approved.
