### ISSUE TITLE
Implementing sorting algorithms in JavaScript.

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#952]
### Brief Summary: 
Sorting refers to arranging elements in a systematic order. Sorting algorithms are therefore instructions to a program in order to arrange data in a particular order. They are important in ensuring efficiency in terms of time taken and memory used. In this article we are going to cover fundamental sorting algorithms in JavaScript.

### Key Takeaways: 
- What are sorting algorithms.
- Why use sorting algorithms.
- Fundamental sorting algorithms and how you can implement them in JavaScript.

### References: 
- https://medium.com/@rajat_m/implement-5-sorting-algorithms-using-javascript-63c5a917e811

**Comment by ninjaginja** [comment]
good topic @mwangiKibui - approved
