### ISSUE TITLE
How to Use Seaborn for Data Visualization

### ISSUE THREAD

**Issue by rahulbanerjee26** [section-engineering-education/engineering-education#974]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
How to Use Seaborn for Data Visualization. Seaborn is a great tool for creating graphs in Python. Graphs created using seaborn are more appealing than matplotlib

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- Readers will understand how to load data frames and use seaborn to visualize the data
- Reader will know how to plot different kinds of graphs using seaborn
- Reader will know to customize graphs i.e change colors, add titles and labels

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @rahulbanerjee26 - approved. 

Just a note of advice, we recommend seeing a single article through from start to finish before beginning on a new topic. This allows you to incorporate any/all feedback into future articles while also allowing us to expedite reviews and payouts for everyone.
